"""Batch 016 - Physics round 4: takes Physics past the 500 curated-question mark (auto-retire of the old bank).

Stand-alone applied/calculation items across all fifteen JAMB Physics topics; no new passages
(the four data passages of batch 015 remain in rotation).

    python3 scripts/build_content_batch16.py -> content/batch_016_physics_round4.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Physics"
PASSAGES = []
PQ = []

Q = [
    # ---------------- Measurement and Units ----------------
    ("Measurement and Units", "Medium", "The pressure of a gas is measured as 2.5 × 10⁵ N/m². Expressed in fundamental units, N/m² is equivalent to",
     "kg m⁻¹ s⁻²", "kg m s⁻²", "kg m² s⁻²", "kg m⁻² s⁻¹", "A",
     "N = kg m s⁻², so N/m² = kg m s⁻² ÷ m² = kg m⁻¹ s⁻²."),
    ("Measurement and Units", "Hard", "A cylinder has a diameter of 2.0 cm and a length of 10.00 cm. Its volume, quoted to the correct number of significant figures, is",
     "31 cm³", "31.4 cm³", "31.42 cm³", "314 cm³", "A",
     "V = πr²l = π × 1.0² × 10.00 = 31.4 cm³, but the diameter has only two significant figures, so the answer is quoted as 31 cm³.", "round(math.pi*10)"),
    ("Measurement and Units", "Medium", "The period of a mass m on a spring of force constant k is T = 2π√(m/k). The unit of k in base SI units is",
     "kg s⁻²", "kg m s⁻²", "kg m⁻¹", "s² kg⁻¹", "A",
     "Rearranging, k = 4π²m/T², so its unit is kg/s² = kg s⁻² (the same as N/m)."),
    ("Measurement and Units", "Easy", "Which of the following measurements is recorded to three significant figures?",
     "0.025 kg", "2.50 m", "0.0025 m", "25 cm", "B",
     "In 2.50 the zero after the decimal point is significant, giving three significant figures; the others have two."),
    ("Measurement and Units", "Medium", "To find the thickness of one sheet of paper, a student measures the thickness of a stack of 200 sheets with a vernier caliper and divides by 200. This is done because",
     "a single sheet is too thin for the caliper to measure accurately", "the caliper cannot measure anything shorter than one centimetre", "a single sheet of paper expands as soon as it is handled", "a stack of sheets has a smaller zero error than one sheet", "A",
     "One sheet (about 0.1 mm) is thinner than the caliper's precision; measuring many sheets and dividing spreads the reading error over all of them."),
    ("Measurement and Units", "Medium", "A stopwatch that runs slow is used to time a 100 m race. The recorded times will be",
     "too short, a systematic error", "too long, a systematic error", "too short, a random error", "correct on average", "A",
     "A slow watch under-records every interval by the same fraction; the error is always in the same direction, so it is systematic and cannot be removed by averaging."),
    ("Measurement and Units", "Easy", "The density of a liquid is 0.8 g/cm³. In SI units this is",
     "8 kg/m³", "80 kg/m³", "800 kg/m³", "8,000 kg/m³", "C",
     "1 g/cm³ = 1,000 kg/m³, so 0.8 g/cm³ = 800 kg/m³.", "0.8*1000"),
    ("Measurement and Units", "Hard", "A rectangular plate has sides measured as 4.0 ± 0.1 cm and 2.0 ± 0.1 cm. The greatest possible value of its area is",
     "8.0 cm²", "8.61 cm²", "8.2 cm²", "9.0 cm²", "B",
     "Taking both sides at their maximum values: 4.1 × 2.1 = 8.61 cm².", "4.1*2.1"),
    ("Measurement and Units", "Easy", "The wavelength 6.4 × 10⁻⁷ m expressed in nanometres is",
     "0.64 nm", "64 nm", "640 nm", "6,400 nm", "C",
     "1 nm = 10⁻⁹ m, so 6.4 × 10⁻⁷ m = 640 × 10⁻⁹ m = 640 nm.", "6.4e-7/1e-9"),
    ("Measurement and Units", "Medium", "A student determines g by timing a simple pendulum. Which of the following introduces a systematic error?",
     "starting the stopwatch slightly late on some of the swings", "measuring the length to the top of the bob instead of to its centre", "counting the oscillations aloud while timing them", "using a heavier bob on the same length of thread", "B",
     "Measuring to the wrong point makes every length reading too small by the same amount, shifting all the results in one direction."),
    # ---------------- Scalars and Vectors ----------------
    ("Scalars and Vectors", "Medium", "A ship sails 30 km due east and then 40 km due north. The bearing of its final position from the starting point is approximately",
     "037°", "053°", "127°", "143°", "A",
     "tan θ = 30/40 = 0.75, so θ = 37° measured from north towards east: bearing 037°.", "round(math.degrees(math.atan(30/40)))"),
    ("Scalars and Vectors", "Medium", "A force of 50 N acts at 30° to the vertical. Its vertical component is",
     "25 N", "43.3 N", "50 N", "86.6 N", "B",
     "Vertical component = 50 cos 30° = 50 × 0.866 = 43.3 N.", "50*math.cos(math.radians(30))"),
    ("Scalars and Vectors", "Medium", "Forces of 3 N and 4 N act on a particle at right angles to each other, and a third force of 5 N acts in the direction opposite to their resultant. The net force on the particle is",
     "0 N", "5 N", "10 N", "12 N", "A",
     "The resultant of 3 N and 4 N at right angles is 5 N; the third force cancels it exactly, so the particle is in equilibrium.", "0"),
    ("Scalars and Vectors", "Medium", "An aeroplane heads due north at 200 km/h while a wind blows at 50 km/h towards the east. Its speed over the ground is approximately",
     "150 km/h", "206 km/h", "250 km/h", "194 km/h", "B",
     "The two velocities are perpendicular: ground speed = √(200² + 50²) = 206 km/h.", "math.sqrt(200**2+50**2)"),
    ("Scalars and Vectors", "Easy", "A tyre gauge reads 2.2 bar, a weighing scale reads 700 N and a signpost says 'Lagos 40 km, north-west'. The reading that is a scalar quantity is the",
     "700 N, since weight always acts vertically", "2.2 bar, since pressure has no direction", "40 km north-west, since it names a direction", "700 N and the 40 km north-west together", "B",
     "Pressure has magnitude only; weight (a force) and the signpost's displacement both have a direction."),
    ("Scalars and Vectors", "Medium", "A delivery rider goes 5 km north to a shop, 5 km east to a second shop and then 5 km south to the customer. The rider's displacement from the starting point is",
     "5 km east", "15 km", "5 km north", "zero", "A",
     "The northward and southward legs cancel, leaving only the 5 km eastward leg; the distance walked is 15 km but the displacement is 5 km east.", "5"),
    ("Scalars and Vectors", "Medium", "Two vectors have magnitudes 8 units and 6 units. If the magnitude of their sum is 14 units, the angle between them is",
     "0°", "60°", "90°", "180°", "A",
     "The sum equals 8 + 6 only when the vectors point in the same direction, i.e. the angle between them is zero.", "0"),
    ("Scalars and Vectors", "Medium", "A car travels 60 km due north in 1 hour and then returns 60 km due south in the next hour. Its average velocity for the whole journey is",
     "0 km/h", "30 km/h", "60 km/h", "120 km/h", "A",
     "Average velocity = total displacement ÷ time = 0 ÷ 2 h = 0, although the average speed is 60 km/h.", "0"),
    ("Scalars and Vectors", "Medium", "A body moving with uniform speed in a circular path has",
     "constant velocity and zero acceleration", "changing velocity and an acceleration towards the centre", "constant velocity and an acceleration along the tangent", "changing speed and zero acceleration", "B",
     "The direction of motion changes continuously, so the velocity changes and there is a centripetal acceleration even though the speed is constant."),
    ("Scalars and Vectors", "Hard", "A boat crosses a river 100 m wide by heading straight across at 2 m/s while the river flows at 1.5 m/s. The distance the boat is carried downstream is",
     "50 m", "75 m", "100 m", "125 m", "B",
     "Crossing time = 100/2 = 50 s; in that time the current carries the boat 1.5 × 50 = 75 m downstream.", "100/2*1.5"),
    ("Scalars and Vectors", "Medium", "The resultant of two forces of 12 N and 5 N acting at right angles is balanced by a third force. The magnitude of the third force is",
     "7 N", "13 N", "17 N", "60 N", "B",
     "The resultant is √(12² + 5²) = 13 N, so the balancing force (equilibrant) is also 13 N, in the opposite direction.", "math.sqrt(144+25)"),
    ("Scalars and Vectors", "Medium", "A force of 100 N acts at 60° to the direction in which a body moves. The component of the force in the direction of motion is",
     "50 N", "86.6 N", "100 N", "0 N", "A",
     "Component along the motion = 100 cos 60° = 50 N; only this part does work on the body.", "100*math.cos(math.radians(60))"),
    ("Scalars and Vectors", "Hard", "Two tug boats pull a barge with equal forces F, their tow ropes making an angle of 60° with each other. The magnitude of the resultant pull on the barge is",
     "F", "1.73F", "2F", "0.5F", "B",
     "R² = F² + F² + 2F² cos 60° = 3F², so R = √3 F = 1.73F.", "math.sqrt(3)"),
    # ---------------- Motion ----------------
    ("Motion", "Medium", "A car accelerates uniformly from 10 m/s to 30 m/s in 8 s. The distance it covers during this time is",
     "80 m", "160 m", "240 m", "320 m", "B",
     "Distance = average velocity × time = ½(10 + 30) × 8 = 160 m.", "(10+30)/2*8"),
    ("Motion", "Hard", "A stone is thrown horizontally at 15 m/s from the top of a cliff 20 m high. Taking g = 10 m/s², it strikes the ground at a horizontal distance from the foot of the cliff of",
     "15 m", "30 m", "40 m", "60 m", "B",
     "Time of fall t = √(2h/g) = √(40/10) = 2 s; horizontal distance = 15 × 2 = 30 m.", "15*math.sqrt(2*20/10)"),
    ("Motion", "Medium", "A body starts from rest and moves with uniform acceleration. The ratio of the distance covered in the first 2 s to the distance covered in the first 4 s is",
     "1 : 2", "1 : 4", "1 : 8", "1 : 16", "B",
     "s = ½at², so the distances are in the ratio 2² : 4² = 4 : 16 = 1 : 4."),
    ("Motion", "Easy", "The displacement–time graph of a body is a straight line inclined to the time axis. The body is",
     "at rest", "moving with uniform velocity", "moving with uniform acceleration", "moving with increasing velocity", "B",
     "A constant slope on a displacement–time graph means the displacement changes at a steady rate: uniform velocity."),
    ("Motion", "Hard", "A lift starts from rest and accelerates upwards at 2 m/s² for 3 s, then moves at constant velocity for 5 s. The total distance travelled in the 8 s is",
     "30 m", "39 m", "48 m", "64 m", "B",
     "First stage: s = ½ × 2 × 3² = 9 m, reaching v = 6 m/s; second stage: 6 × 5 = 30 m; total 39 m.", "0.5*2*9+6*5"),
    ("Motion", "Hard", "A ball is dropped from a height of 80 m. Taking g = 10 m/s², the distance it falls during the last second of its fall is",
     "20 m", "35 m", "45 m", "60 m", "B",
     "Total time = √(2 × 80/10) = 4 s; distance in the first 3 s = ½ × 10 × 9 = 45 m, so the last second covers 80 − 45 = 35 m.", "80-0.5*10*9"),
    ("Motion", "Medium", "A particle performs simple harmonic motion with amplitude 5 cm and period 2 s. Its maximum speed is approximately",
     "2.5 cm/s", "15.7 cm/s", "31.4 cm/s", "10 cm/s", "B",
     "ω = 2π/T = π rad/s; v_max = Aω = 5 × π = 15.7 cm/s.", "5*math.pi"),
    ("Motion", "Medium", "A wheel of radius 0.5 m rotates at 120 revolutions per minute. The linear speed of a point on its rim is approximately",
     "3.14 m/s", "6.28 m/s", "12.6 m/s", "60 m/s", "B",
     "120 rev/min = 2 rev/s, so ω = 2π × 2 = 4π rad/s and v = rω = 0.5 × 4π = 6.28 m/s.", "0.5*120*2*math.pi/60"),
    ("Motion", "Medium", "A cyclist rides round a circular track of radius 20 m at a constant speed of 10 m/s. His acceleration is",
     "zero", "5 m/s² towards the centre of the track", "5 m/s² along the tangent to the track", "0.5 m/s² towards the centre of the track", "B",
     "Centripetal acceleration a = v²/r = 100/20 = 5 m/s², always directed towards the centre.", "100/20"),
    ("Motion", "Medium", "A parachutist falling at terminal velocity opens her parachute. Immediately afterwards she",
     "continues to fall at the same speed", "decelerates because the air resistance now exceeds her weight", "accelerates because her weight suddenly increases", "stops falling and hangs motionless in the air", "B",
     "The open parachute greatly increases the drag; the upward force is now larger than the weight, so she slows until a new, lower terminal velocity is reached."),
    # ---------------- Forces and Equilibrium ----------------
    ("Forces and Equilibrium", "Easy", "A body of mass 5 kg is acted on by two opposing forces of 30 N and 10 N along the same line. Its acceleration is",
     "2 m/s²", "4 m/s²", "6 m/s²", "8 m/s²", "B",
     "Net force = 30 − 10 = 20 N; a = F/m = 20/5 = 4 m/s².", "20/5"),
    ("Forces and Equilibrium", "Hard", "A uniform beam 6 m long weighing 300 N rests on supports at its two ends. A 600 N load is placed 2 m from the left end. The reaction at the left support is",
     "350 N", "450 N", "550 N", "650 N", "C",
     "Taking moments about the right end: R × 6 = 300 × 3 + 600 × 4 = 3,300, so R = 550 N.", "(300*3+600*4)/6"),
    ("Forces and Equilibrium", "Easy", "A tight nut is loosened more easily with a long spanner than with a short one because the longer spanner",
     "applies a much larger force directly on the nut", "produces a larger moment for the same applied force", "has a smaller mass and so is easier to swing", "reduces the friction between the nut and its thread", "B",
     "Moment = force × perpendicular distance; a longer handle gives a bigger turning effect for the same push."),
    ("Forces and Equilibrium", "Easy", "A 1.5 kg book rests on a horizontal table. Taking g = 10 m/s², the normal reaction of the table on the book is",
     "1.5 N", "15 N", "150 N", "zero", "B",
     "The book is in equilibrium, so the upward reaction equals its weight, mg = 1.5 × 10 = 15 N.", "1.5*10"),
    ("Forces and Equilibrium", "Medium", "A block of weight 20 N rests on a plane inclined at 30° to the horizontal. The component of its weight acting down the plane is",
     "10 N", "17.3 N", "20 N", "40 N", "A",
     "Component along the plane = W sin θ = 20 × sin 30° = 10 N; the component into the plane is 20 cos 30° = 17.3 N.", "20*math.sin(math.radians(30))"),
    ("Forces and Equilibrium", "Medium", "The smallest horizontal force needed to start a 60 kg crate sliding on a rough floor is 240 N. Taking g = 10 m/s², the coefficient of static friction is",
     "0.25", "0.4", "2.5", "4.0", "B",
     "μ = limiting friction ÷ normal reaction = 240/(60 × 10) = 0.4.", "240/600"),
    ("Forces and Equilibrium", "Medium", "A 1,000 kg car moving at 20 m/s is stopped by its brakes in 5 s. The average braking force is",
     "200 N", "4,000 N", "5,000 N", "20,000 N", "B",
     "Deceleration = 20/5 = 4 m/s²; F = ma = 1,000 × 4 = 4,000 N.", "1000*20/5"),
    ("Forces and Equilibrium", "Medium", "A 3 kg mass is pulled vertically upwards by a rope with an acceleration of 3 m/s². Taking g = 10 m/s², the tension in the rope is",
     "21 N", "30 N", "39 N", "9 N", "C",
     "T − mg = ma, so T = m(g + a) = 3 × 13 = 39 N.", "3*(10+3)"),
    ("Forces and Equilibrium", "Hard", "A boy stands on a bathroom scale in a lift that is moving downwards and slowing down. The reading on the scale is",
     "greater than his weight", "less than his weight", "equal to his weight", "zero", "A",
     "Slowing down while descending means the acceleration is upwards, so the reaction R = m(g + a) is larger than the weight."),
    ("Forces and Equilibrium", "Medium", "Two boys pull on opposite ends of a rope with forces of 200 N each and the rope does not move. The tension in the rope is",
     "0 N", "100 N", "200 N", "400 N", "C",
     "Each end is pulled with 200 N and the rope is in equilibrium; the tension throughout the rope is 200 N, not the sum of the two pulls.", "200"),
    ("Forces and Equilibrium", "Hard", "A 4 kg mass and a 6 kg mass hang from the ends of a light string passing over a smooth pulley. Taking g = 10 m/s², the acceleration of the masses is",
     "1 m/s²", "2 m/s²", "5 m/s²", "10 m/s²", "B",
     "Net force = (6 − 4) × 10 = 20 N acting on a total mass of 10 kg: a = 20/10 = 2 m/s².", "(6-4)*10/(6+4)"),
    ("Forces and Equilibrium", "Hard", "A light metre rule carries a 40 g mass at the 10 cm mark and a 60 g mass at the 80 cm mark. It balances horizontally on a knife-edge placed at the",
     "45 cm mark", "52 cm mark", "55 cm mark", "62 cm mark", "B",
     "For balance 40(x − 10) = 60(80 − x), so 100x = 5,200 and x = 52 cm.", "5200/100"),
    # ---------------- Work, Energy and Power ----------------
    ("Work Energy and Power", "Medium", "A 60 kg athlete runs up a hill 30 m high in 1 minute. Taking g = 10 m/s², her average power output against gravity is",
     "30 W", "300 W", "1,800 W", "18,000 W", "B",
     "Work against gravity = mgh = 60 × 10 × 30 = 18,000 J; power = 18,000/60 = 300 W.", "60*10*30/60"),
    ("Work Energy and Power", "Medium", "A 0.2 kg ball dropped from a height of 5 m rebounds to a height of 3.2 m. Taking g = 10 m/s², the energy lost in the bounce is",
     "1.8 J", "3.6 J", "6.4 J", "10 J", "B",
     "Energy lost = mg(h₁ − h₂) = 0.2 × 10 × (5 − 3.2) = 3.6 J.", "0.2*10*(5-3.2)"),
    ("Work Energy and Power", "Medium", "A 2 kg block sliding along a horizontal floor at 6 m/s comes to rest after travelling 9 m. The average frictional force on it is",
     "2 N", "4 N", "6 N", "12 N", "B",
     "Kinetic energy = ½ × 2 × 6² = 36 J; work done by friction F × 9 = 36, so F = 4 N.", "0.5*2*36/9"),
    ("Work Energy and Power", "Easy", "An electricity bill is charged in kilowatt-hours, a physicist quotes photon energies in electron-volts and a food label gives energy in kilojoules. A quantity that these three units can NOT all measure is",
     "energy", "work", "heat", "power", "D",
     "Kilowatt-hour, electron-volt and kilojoule are all units of energy (work or heat); power is energy per second and is measured in watts."),
    ("Work Energy and Power", "Medium", "A catapult stores 4 J of elastic potential energy and fires a 20 g stone. Ignoring losses, the speed of the stone as it leaves the catapult is",
     "10 m/s", "20 m/s", "40 m/s", "200 m/s", "B",
     "½mv² = 4, so v² = 8/0.02 = 400 and v = 20 m/s.", "math.sqrt(2*4/0.02)"),
    ("Work Energy and Power", "Hard", "A machine lifts a 200 kg load through 5 m in 20 s while taking an input power of 1 kW. Taking g = 10 m/s², the efficiency of the machine is",
     "25%", "50%", "75%", "100%", "B",
     "Useful power = 200 × 10 × 5/20 = 500 W; efficiency = 500/1,000 × 100 = 50%.", "500/1000*100"),
    ("Work Energy and Power", "Medium", "A pump raises water to a tank 10 m above the ground at the rate of 30 kg every minute. Taking g = 10 m/s², the useful power of the pump is",
     "5 W", "50 W", "300 W", "3,000 W", "B",
     "Work per minute = 30 × 10 × 10 = 3,000 J; power = 3,000/60 = 50 W.", "30*10*10/60"),
    ("Work Energy and Power", "Medium", "A body of mass m moving with velocity v has kinetic energy E. If its velocity increases to 3v, its kinetic energy becomes",
     "3E", "6E", "9E", "27E", "C",
     "Kinetic energy is proportional to v², so tripling the velocity multiplies the energy by 3² = 9.", "9"),
    ("Work Energy and Power", "Easy", "When a moving car is braked to a stop, most of its kinetic energy is converted into",
     "potential energy of the car", "heat in the brakes and tyres", "sound energy from the road", "chemical energy in the battery", "B",
     "Friction in the brakes and between the tyres and the road turns the kinetic energy into heat."),
    ("Work Energy and Power", "Medium", "A 500 g toy car is pushed up a smooth slope with an initial speed of 4 m/s. Taking g = 10 m/s², the vertical height it rises before stopping is",
     "0.4 m", "0.8 m", "1.6 m", "8 m", "B",
     "½mv² = mgh, so h = v²/2g = 16/20 = 0.8 m; the mass cancels.", "16/20"),
    ("Work Energy and Power", "Medium", "A generator converts 80% of the mechanical energy supplied to it into electrical energy. To deliver 4 kW of electrical power it must receive mechanical power of",
     "3.2 kW", "4.8 kW", "5 kW", "8 kW", "C",
     "Input = output ÷ efficiency = 4/0.8 = 5 kW.", "4/0.8"),
    # ---------------- Momentum and Machines ----------------
    ("Momentum and Machines", "Medium", "A 3 kg rifle fires a 15 g bullet at 300 m/s. The recoil speed of the rifle is",
     "0.5 m/s", "1.5 m/s", "3 m/s", "15 m/s", "B",
     "Momentum is conserved: 3 × v = 0.015 × 300, so v = 1.5 m/s.", "0.015*300/3"),
    ("Momentum and Machines", "Medium", "A 60 kg man jumps horizontally out of a stationary 240 kg boat at 2 m/s. The boat moves off in the opposite direction at",
     "0.25 m/s", "0.5 m/s", "2 m/s", "8 m/s", "B",
     "60 × 2 = 240 × v, so v = 0.5 m/s.", "120/240"),
    ("Momentum and Machines", "Hard", "A 5 kg body moving at 4 m/s collides head-on with a 3 kg body moving at 2 m/s in the opposite direction. If they stick together, their common speed after the collision is",
     "1.75 m/s", "3.25 m/s", "2.0 m/s", "0.5 m/s", "A",
     "Total momentum = 5 × 4 − 3 × 2 = 14 kg m/s shared by 8 kg: v = 14/8 = 1.75 m/s.", "(5*4-3*2)/8"),
    ("Momentum and Machines", "Medium", "A 2 kg hammer moving at 5 m/s strikes a nail and stops in 0.01 s. The average force on the nail is",
     "100 N", "1,000 N", "10,000 N", "50 N", "B",
     "F = change in momentum ÷ time = (2 × 5)/0.01 = 1,000 N.", "2*5/0.01"),
    ("Momentum and Machines", "Medium", "Seat belts and air bags reduce injury in a car crash mainly because they",
     "reduce the change in the passenger's momentum", "increase the time over which the momentum changes", "increase the force needed to stop the passenger", "bring the car itself to rest much more quickly", "B",
     "The passenger's momentum change is fixed; spreading it over a longer time reduces the average force on the body."),
    ("Momentum and Machines", "Medium", "A block and tackle with 6 pulleys lifts a 900 N load with an effort of 200 N. Its efficiency is",
     "50%", "66.7%", "75%", "80%", "C",
     "MA = 900/200 = 4.5 and VR = 6, so efficiency = 4.5/6 × 100 = 75%.", "4.5/6*100"),
    ("Momentum and Machines", "Medium", "An inclined plane 6 m long rises through a height of 1.5 m. A 500 N load is pushed up it with an effort of 200 N. The efficiency of the plane is",
     "40%", "62.5%", "75%", "25%", "B",
     "VR = 6/1.5 = 4; MA = 500/200 = 2.5; efficiency = 2.5/4 × 100 = 62.5%.", "2.5/4*100"),
    ("Momentum and Machines", "Easy", "A lever has its fulcrum 20 cm from the load and 80 cm from the effort. Ignoring friction, the effort needed to lift a 100 N load is",
     "20 N", "25 N", "40 N", "400 N", "B",
     "Effort × 80 = 100 × 20, so the effort is 25 N.", "100*20/80"),
    ("Momentum and Machines", "Hard", "A screw jack has a pitch of 4 mm and a handle 28 cm long, and is 50% efficient. The effort needed to raise a 4,400 N load is (take π = 22/7)",
     "10 N", "20 N", "40 N", "55 N", "B",
     "VR = 2πR/pitch = 2 × 22/7 × 280/4 = 440; MA = 0.5 × 440 = 220; effort = 4,400/220 = 20 N.", "4400/(0.5*2*22/7*280/4)"),
    ("Momentum and Machines", "Medium", "A ball bounces off a wall with the same speed at which it arrived. The quantity that is unchanged by the collision is its",
     "momentum", "kinetic energy", "velocity", "direction of motion", "B",
     "Speed is unchanged so the kinetic energy is unchanged; the velocity and momentum reverse direction."),
    ("Momentum and Machines", "Hard", "Which of the following machines has a velocity ratio less than 1?",
     "a pair of scissors with long blades and short handles", "a crowbar with a long handle and a short lifting end", "a bottle opener with the pivot near the cap", "a nutcracker with the nut close to the hinge", "A",
     "With short handles and long blades the blade tips move further than the handles, so the effort moves less than the load: VR < 1 and the machine gains speed, not force."),
    # ---------------- Properties of Matter ----------------
    ("Properties of Matter", "Medium", "A spring of natural length 15 cm stretches to 19 cm when a 20 N load hangs from it. The force constant of the spring is",
     "5 N/m", "50 N/m", "500 N/m", "5,000 N/m", "C",
     "k = F/e = 20/0.04 = 500 N/m.", "20/0.04"),
    ("Properties of Matter", "Medium", "Two identical springs, each of force constant k, are joined end to end (in series) and a load hangs from the lower one. Compared with a single spring carrying the same load, the total extension is",
     "half as much", "the same", "twice as much", "four times as much", "C",
     "Each spring carries the full load and stretches by the same amount, so the total extension doubles (the combined constant is k/2)."),
    ("Properties of Matter", "Easy", "A cube of side 10 cm and mass 2 kg rests on a table. Taking g = 10 m/s², the pressure it exerts on the table is",
     "200 Pa", "2,000 Pa", "20,000 Pa", "20 Pa", "B",
     "P = F/A = 20 N ÷ 0.01 m² = 2,000 Pa.", "20/0.01"),
    ("Properties of Matter", "Hard", "A U-tube contains water. Oil of density 800 kg/m³ is poured into one arm and forms a column 10 cm high. The height of water above the oil–water interface in the other arm is",
     "6.4 cm", "8 cm", "10 cm", "12.5 cm", "B",
     "Pressures balance at the interface level: 800 × 10 = 1,000 × h, so h = 8 cm.", "0.8*10"),
    ("Properties of Matter", "Medium", "A block of ice floats in water with 90% of its volume below the surface. The density of ice is approximately",
     "90 kg/m³", "900 kg/m³", "1,000 kg/m³", "1,100 kg/m³", "B",
     "Fraction submerged = density of ice ÷ density of water, so the density of ice is 0.9 × 1,000 = 900 kg/m³.", "900"),
    ("Properties of Matter", "Hard", "An object weighs 12 N in air and 9 N when fully immersed in water. Its apparent weight when fully immersed in a liquid of relative density 1.2 is",
     "7.2 N", "8.4 N", "9.6 N", "10.8 N", "B",
     "Upthrust in water = 3 N; in the denser liquid it is 1.2 × 3 = 3.6 N, so the apparent weight is 12 − 3.6 = 8.4 N.", "12-3*1.2"),
    ("Properties of Matter", "Medium", "A hydraulic lift has a small piston of area 20 cm² and a large piston of area 400 cm². The force needed on the small piston to raise a 6,000 N car on the large piston is",
     "30 N", "300 N", "600 N", "3,000 N", "B",
     "Pressure is the same on both pistons: F/20 = 6,000/400, so F = 300 N.", "6000*20/400"),
    ("Properties of Matter", "Medium", "Water rises higher in a narrower capillary tube because",
     "a narrower tube holds less water and so is easier to fill", "the height of capillary rise is inversely proportional to the tube radius", "the water inside a narrower tube has a lower density", "the air pressure inside a narrower tube is greater", "B",
     "h = 2T cos θ/(rρg): the surface-tension force grows with the circumference (∝ r) but the weight of the column grows with r², so a smaller radius supports a taller column."),
    ("Properties of Matter", "Easy", "A small drop of water takes a spherical shape because",
     "gravity pulls on it equally in every direction", "surface tension makes its surface area as small as possible", "the water in a drop has a very high viscosity", "air pressure squeezes it evenly from all sides", "B",
     "Surface tension acts to minimise the surface area, and a sphere has the smallest surface area for a given volume."),
    ("Properties of Matter", "Medium", "The elastic limit of a wire is the",
     "greatest load it can carry before it finally breaks", "point beyond which it does not regain its original length when unloaded", "load at which extension stops being proportional to load", "load at which the wire begins to melt", "B",
     "Up to the elastic limit the deformation is temporary; beyond it the wire is permanently stretched."),
    ("Properties of Matter", "Medium", "A brick weighs 30 N and its faces measure 20 cm × 10 cm, 20 cm × 5 cm and 10 cm × 5 cm. The greatest pressure it can exert when resting on a table is",
     "1,500 Pa", "3,000 Pa", "6,000 Pa", "600 Pa", "C",
     "Pressure is greatest on the smallest face, 10 × 5 = 50 cm² = 0.005 m²: P = 30/0.005 = 6,000 Pa.", "30/0.005"),
    # ---------------- Heat and Thermal Physics ----------------
    ("Heat and Thermal Physics", "Hard", "A constant-volume gas thermometer reads 80 kPa at the ice point and 109.3 kPa at the steam point. The temperature at which it reads 100 kPa is approximately",
     "25 °C", "68 °C", "75 °C", "92 °C", "B",
     "θ = (P − P₀)/(P₁₀₀ − P₀) × 100 = (100 − 80)/(109.3 − 80) × 100 = 68 °C.", "(100-80)/(109.3-80)*100"),
    ("Heat and Thermal Physics", "Easy", "The reading of a clinical thermometer does not fall when it is taken out of the patient's mouth because",
     "the mercury in the stem cannot contract once it has expanded", "a constriction in the bore stops the mercury flowing back into the bulb", "the bulb is so small that it cools far more slowly than the stem", "the thick glass of the stem is a very poor conductor of heat", "B",
     "The narrow kink just above the bulb breaks the mercury thread as it contracts, leaving the reading in the stem until the thermometer is shaken."),
    ("Heat and Thermal Physics", "Medium", "Steam at 100 °C causes a more severe burn than the same mass of boiling water at 100 °C because the steam",
     "is always at a much higher temperature than the water", "gives up its latent heat of vaporisation as it condenses", "moves much faster and so strikes the skin harder", "penetrates more deeply into the skin than water does", "B",
     "Each kilogram of steam releases about 2.26 × 10⁶ J on condensing before it even starts to cool as water."),
    ("Heat and Thermal Physics", "Hard", "A 2 kW heater raises the temperature of 5 kg of water from 20 °C to 100 °C in 15 minutes. Taking c = 4,200 J kg⁻¹ K⁻¹, the heat lost to the surroundings during this time is",
     "12,000 J", "120,000 J", "1,680,000 J", "1,800,000 J", "B",
     "Supplied: 2,000 × 900 = 1,800,000 J; absorbed by the water: 5 × 4,200 × 80 = 1,680,000 J; the difference, 120,000 J, was lost.", "2000*900-5*4200*80"),
    ("Heat and Thermal Physics", "Medium", "A gas at 27 °C is heated at constant pressure until its volume doubles. Its final temperature is",
     "54 °C", "327 °C", "600 °C", "273 °C", "B",
     "At constant pressure V ∝ T (kelvin): 300 K → 600 K, which is 600 − 273 = 327 °C.", "600-273"),
    ("Heat and Thermal Physics", "Medium", "Ice at −10 °C is heated steadily until it becomes water at 10 °C. During this process the temperature",
     "rises at the same steady rate from start to finish", "stays constant while the ice melts and rises before and after", "stays constant from start to finish at 0 °C", "falls while the ice melts and then rises again", "B",
     "Heat supplied during melting goes into the latent heat of fusion, so the temperature pauses at 0 °C until all the ice has melted."),
    ("Heat and Thermal Physics", "Medium", "A metal ball just passes through a metal ring at room temperature. If only the ring is heated,",
     "the ball still cannot pass because the ring shrinks", "the ball passes through easily because the hole expands", "the hole becomes smaller as the metal expands inwards", "nothing changes because only the ball's size matters", "B",
     "A hole in a heated plate expands exactly as if it were made of the same metal, so the ring's opening becomes larger."),
    ("Heat and Thermal Physics", "Easy", "A car radiator uses water as its coolant mainly because water",
     "is cheap and has a low boiling point", "has a high specific heat capacity", "is a good conductor of electricity", "has a low density", "B",
     "A high specific heat capacity lets each kilogram of water carry away a large amount of heat for a small rise in temperature."),
    ("Heat and Thermal Physics", "Easy", "Heat from the Sun reaches the Earth through the vacuum of space by",
     "conduction", "convection", "radiation", "evaporation", "C",
     "Conduction and convection need a material medium; only radiation (electromagnetic waves) can cross empty space."),
    # ---------------- Waves ----------------
    ("Waves", "Medium", "A radio wave of wavelength 3 m and a light wave of wavelength 6 × 10⁻⁷ m both travel through a vacuum. Which statement is correct?",
     "the light wave travels faster", "both travel at the same speed", "the radio wave travels faster", "the light wave has the lower frequency", "B",
     "All electromagnetic waves travel at 3 × 10⁸ m/s in a vacuum; the shorter-wavelength light wave has the higher frequency."),
    ("Waves", "Medium", "A transverse wave on a rope has a frequency of 40 Hz and successive crests are 0.5 m apart. The time the wave takes to travel 100 m along the rope is",
     "2.5 s", "5 s", "10 s", "20 s", "B",
     "v = fλ = 40 × 0.5 = 20 m/s; time = 100/20 = 5 s.", "100/(40*0.5)"),
    ("Waves", "Medium", "Two waves of the same frequency and amplitude arrive at a point exactly in phase. The amplitude of the resulting vibration is",
     "zero", "equal to the amplitude of one wave", "twice the amplitude of one wave", "half the amplitude of one wave", "C",
     "In-phase waves interfere constructively: crest meets crest, so the displacements add to give double the amplitude."),
    ("Waves", "Medium", "A stationary (standing) wave differs from a progressive wave in that a stationary wave",
     "transfers energy from one place to another", "has points (nodes) that never move", "has all points vibrating with the same amplitude", "cannot be produced on a stretched string", "B",
     "A stationary wave is formed by two identical waves travelling in opposite directions; at the nodes they always cancel, and no energy is carried along."),
    ("Waves", "Medium", "In a stationary wave the distance between a node and the adjacent antinode is 15 cm. The wavelength of the wave is",
     "15 cm", "30 cm", "60 cm", "7.5 cm", "C",
     "Node to neighbouring antinode is a quarter of a wavelength, so λ = 4 × 15 = 60 cm.", "4*15"),
    ("Waves", "Medium", "A radio station transmits on a wavelength of 300 m. Its frequency is (c = 3 × 10⁸ m/s)",
     "1 kHz", "100 kHz", "1,000 kHz", "10,000 kHz", "C",
     "f = c/λ = 3 × 10⁸/300 = 10⁶ Hz = 1,000 kHz (1 MHz).", "3e8/300/1e3"),
    ("Waves", "Medium", "The spectral lines in the light from a distant star are found to be shifted towards the red end of the spectrum. This shows that the star is",
     "moving away from the Earth", "moving towards the Earth", "stationary relative to the Earth", "much hotter than the Sun", "A",
     "By the Doppler effect, light from a receding source is received at a lower frequency (longer wavelength), i.e. shifted towards red."),
    ("Waves", "Easy", "An ambulance siren sounds higher in pitch as the vehicle approaches and lower as it moves away. This is an example of",
     "resonance", "the Doppler effect", "beats", "diffraction", "B",
     "Relative motion between the source and the listener changes the frequency received; this is the Doppler effect."),
    ("Waves", "Easy", "Which of the following electromagnetic waves has the shortest wavelength?",
     "radio waves", "microwaves", "ultraviolet rays", "gamma rays", "D",
     "In order of decreasing wavelength: radio, microwaves, infrared, visible, ultraviolet, X-rays, gamma rays."),
    ("Waves", "Hard", "A wave is described by y = 0.02 sin(4πx − 100πt), where x and y are in metres and t in seconds. The wavelength of the wave is",
     "0.25 m", "0.5 m", "2 m", "4 m", "B",
     "Comparing with y = A sin(kx − ωt): k = 4π = 2π/λ, so λ = 0.5 m.", "2/4"),
    ("Waves", "Medium", "Water waves of wavelength 2 cm pass through a gap 2 cm wide, and identical waves pass through a gap 20 cm wide. The waves spread out",
     "equally in both cases", "more after passing through the 2 cm gap", "more after passing through the 20 cm gap", "in neither case", "B",
     "Diffraction is greatest when the gap width is about equal to the wavelength."),
    ("Waves", "Medium", "In a microwave oven the food is heated because the microwaves",
     "are absorbed by water molecules in the food, which then vibrate faster", "burn the outer surface of the food and the heat then conducts inwards", "pass straight through the food and heat the metal walls of the oven", "are reflected repeatedly by the food until it warms up", "A",
     "Microwaves of about 2.45 GHz are strongly absorbed by water molecules, raising the internal energy of the food throughout."),
    # ---------------- Sound ----------------
    ("Sound", "Medium", "A boy hears the echo of his shout from a wall 2 s after shouting. If he walks 165 m closer to the wall and shouts again, the echo returns after (speed of sound = 330 m/s)",
     "0.5 s", "1 s", "1.5 s", "3 s", "B",
     "Original distance = 330 × 2/2 = 330 m; new distance = 165 m; echo time = 2 × 165/330 = 1 s.", "2*165/330"),
    ("Sound", "Medium", "Sound travels faster in water than in air mainly because",
     "water has a much greater density than air", "water is far less compressible than air", "water is usually colder than the air above it", "sound waves become transverse in water", "B",
     "The speed of sound depends on the ratio of elasticity to density; water's very high bulk modulus outweighs its greater density."),
    ("Sound", "Medium", "A closed pipe and an open pipe have the same length. The fundamental frequency of the closed pipe is",
     "the same as that of the open pipe", "half that of the open pipe", "twice that of the open pipe", "a quarter of that of the open pipe", "B",
     "Fundamental: closed pipe f = v/4L, open pipe f = v/2L, so the closed pipe gives half the frequency."),
    ("Sound", "Medium", "The quality (timbre) of a note produced by a musical instrument depends on the",
     "amplitude of the fundamental vibration alone", "number and relative strengths of the overtones present", "speed at which the sound travels through the room", "loudness with which the note is played", "B",
     "The same note sounds different on a flute and a guitar because each instrument adds its own mixture of overtones to the fundamental."),
    ("Sound", "Medium", "A sonometer wire 60 cm long is in tune with a fork of frequency 300 Hz. Keeping the tension the same, the length that will be in tune with a 360 Hz fork is",
     "40 cm", "50 cm", "72 cm", "30 cm", "B",
     "f ∝ 1/L at constant tension: L = 60 × 300/360 = 50 cm.", "60*300/360"),
    ("Sound", "Medium", "A stretched wire has a fundamental frequency of 200 Hz. If the tension is increased to nine times its original value with the length unchanged, the fundamental frequency becomes",
     "200 Hz", "600 Hz", "1,800 Hz", "66.7 Hz", "B",
     "f ∝ √T, so multiplying the tension by 9 multiplies the frequency by 3: 600 Hz.", "200*3"),
    ("Sound", "Easy", "When the intensity of a sound wave is increased, the property of the sound that increases is its",
     "frequency", "loudness", "pitch", "speed", "B",
     "Intensity depends on the square of the amplitude and is perceived as loudness; pitch depends on frequency."),
    ("Sound", "Hard", "With a certain tuning fork an air column closed at one end resonates first when it is 16 cm long and next when it is 50 cm long. The wavelength of the note is",
     "34 cm", "68 cm", "64 cm", "100 cm", "B",
     "Successive resonance lengths differ by λ/2: 50 − 16 = 34 cm, so λ = 68 cm (end correction cancels).", "2*(50-16)"),
    ("Sound", "Hard", "In a resonance tube experiment the first and second resonance lengths with a 500 Hz fork are 16 cm and 50 cm. The speed of sound in the air is",
     "160 m/s", "340 m/s", "500 m/s", "250 m/s", "B",
     "λ = 2(0.50 − 0.16) = 0.68 m; v = fλ = 500 × 0.68 = 340 m/s.", "2*(0.50-0.16)*500"),
    ("Sound", "Hard", "A 512 Hz fork sounded with a second fork gives 3 beats per second. When a little wax is stuck to the second fork the beats increase to 5 per second. The original frequency of the second fork was",
     "509 Hz", "515 Hz", "512 Hz", "517 Hz", "A",
     "Wax lowers the second fork's frequency; the beats increased, so its frequency moved further below 512 Hz — it was 512 − 3 = 509 Hz.", "512-3"),
    ("Sound", "Medium", "Ultrasound rather than X-rays is used to scan an unborn baby because ultrasound",
     "has a much higher frequency than X-rays", "does not ionise or damage living tissue", "travels through the body faster than X-rays", "produces sharper images of the bones", "B",
     "Ultrasound is a high-frequency sound wave; unlike X-rays it carries no ionising energy and is safe for the developing baby."),
    ("Sound", "Medium", "A fishing trawler's depth finder records an echo 0.8 s after emitting a pulse. Taking the speed of sound in sea water as 1,500 m/s, the water beneath the trawler is",
     "300 m", "600 m", "1,200 m", "1,875 m", "B",
     "The pulse travels down and back: depth = 1,500 × 0.8/2 = 600 m deep.", "1500*0.8/2"),
    # ---------------- Light and Optics ----------------
    ("Light and Optics", "Hard", "An object is placed 40 cm in front of a convex (diverging) mirror of focal length 20 cm. The image is",
     "13.3 cm behind the mirror, virtual, erect and diminished", "40 cm in front of the mirror, real, inverted and same size", "13.3 cm in front of the mirror, real, inverted and diminished", "40 cm behind the mirror, virtual, erect and magnified", "A",
     "With f = −20 cm: 1/v = 1/f − 1/u = −1/20 − 1/40 = −3/40, so v = −13.3 cm — a virtual, erect image one-third the size."),
    ("Light and Optics", "Medium", "A concave mirror of focal length 15 cm is used to throw a sharp image of a lamp onto a screen 60 cm from the mirror. The lamp must be placed at",
     "12 cm", "20 cm", "45 cm", "75 cm", "B",
     "1/u = 1/f − 1/v = 1/15 − 1/60 = 3/60, so u = 20 cm.", "1/(1/15-1/60)"),
    ("Light and Optics", "Medium", "A ray of light inside glass of refractive index 1.5 meets the glass–air surface at an angle of incidence of 45°. The ray is",
     "refracted away from the normal into the air", "totally internally reflected back into the glass", "refracted towards the normal into the air", "absorbed completely at the surface", "B",
     "sin C = 1/1.5 gives a critical angle of about 42°; 45° exceeds this, so no light escapes and the ray is totally reflected."),
    ("Light and Optics", "Medium", "A coin at the bottom of a beaker of water appears to be raised. This is because light from the coin",
     "is totally reflected at the surface of the water", "bends away from the normal as it leaves the water", "bends towards the normal as it leaves the water", "travels faster in the water than it does in air", "B",
     "Refraction away from the normal on leaving the denser medium makes the rays appear to come from a point higher than the coin."),
    ("Light and Optics", "Medium", "A converging lens forms a real image the same size as the object when the object is placed",
     "at the principal focus", "at twice the focal length", "between the principal focus and the lens", "at a very great distance", "B",
     "With u = 2f the image is also at 2f, real, inverted and the same size (magnification 1)."),
    ("Light and Optics", "Medium", "A slide projector uses a converging lens to throw a large image of a slide onto a distant screen. The slide must be placed",
     "between the lens and its principal focus", "between f and 2f from the lens", "exactly at 2f from the lens", "further than 2f from the lens", "B",
     "An object between f and 2f gives a real, inverted and magnified image beyond 2f on the other side — the image is then focused on the screen."),
    ("Light and Optics", "Easy", "The image formed on the film of a simple camera is",
     "real, inverted and diminished", "virtual, erect and magnified", "real, erect and diminished", "virtual, inverted and magnified", "A",
     "The object is far beyond 2f, so the converging lens forms a small, real, inverted image just beyond its focal point."),
    ("Light and Optics", "Medium", "A short-sighted person cannot see distant objects clearly because the image of a distant object is formed",
     "behind the retina", "in front of the retina", "on the retina but upside down", "on the blind spot", "B",
     "The eyeball is too long or the lens too powerful, so parallel rays converge before the retina; a diverging lens corrects the defect."),
    ("Light and Optics", "Medium", "White light passes first through a red filter and then through a green filter. The light that emerges is",
     "yellow", "red", "green", "no light at all (black)", "D",
     "The red filter transmits only red light, which the green filter absorbs, so nothing passes through both."),
    ("Light and Optics", "Medium", "A spectacle lens has a power of −2.5 D. It is a",
     "converging lens of focal length 40 cm", "diverging lens of focal length 40 cm", "converging lens of focal length 25 cm", "diverging lens of focal length 2.5 cm", "B",
     "f = 1/P = 1/2.5 m = 40 cm; the negative sign means a diverging (concave) lens.", "1/2.5*100"),
    ("Light and Optics", "Easy", "The image in a pinhole camera becomes sharper but dimmer when",
     "the pinhole is made larger", "the pinhole is made smaller", "the box is made shorter", "a second pinhole is added", "B",
     "A smaller hole lets through a narrower cone of rays from each point of the object (sharper) but less light overall (dimmer)."),
    ("Light and Optics", "Medium", "A diver under water looks up and sees the surface above her act like a mirror, except for a bright circular window directly overhead. The mirror-like region is produced by",
     "refraction of light from the air into the water at small angles", "total internal reflection of light striking the surface beyond the critical angle", "diffraction of light round the edge of the bright circular window", "dispersion of sunlight into colours at the water surface", "B",
     "Light from below the surface that meets it at more than the critical angle (about 49° for water) cannot escape and is reflected back down, so the surface looks silvery outside the window."),
    # ---------------- Electricity ----------------
    ("Electricity", "Medium", "Three resistors of 2 Ω, 3 Ω and 6 Ω are connected in parallel. Their combined resistance is",
     "1 Ω", "11 Ω", "6 Ω", "0.5 Ω", "A",
     "1/R = 1/2 + 1/3 + 1/6 = 1, so R = 1 Ω.", "1/(1/2+1/3+1/6)"),
    ("Electricity", "Hard", "A wire of resistance 12 Ω is cut into three equal pieces which are then connected in parallel. The resistance of the combination is",
     "36 Ω", "4 Ω", "1.33 Ω", "12 Ω", "C",
     "Each piece is 4 Ω; three 4 Ω resistors in parallel give 4/3 = 1.33 Ω.", "4/3"),
    ("Electricity", "Hard", "Bulbs rated 40 W, 240 V and 100 W, 240 V are connected in series across a 240 V supply. Which bulb glows brighter?",
     "the 40 W bulb, because it has the larger resistance and carries the same current", "the 100 W bulb, because its higher power rating means it always glows brighter", "both glow equally brightly, because the same current flows through both", "the 100 W bulb, because it draws a larger current than the 40 W bulb", "A",
     "In series the current is the same in both; power = I²R, so the bulb with the larger resistance (the 40 W bulb, R = V²/P) dissipates more power."),
    ("Electricity", "Medium", "A 1.5 kW electric iron is used for 2 hours a day for 30 days. At ₦60 per kilowatt-hour the cost of the electricity used is",
     "₦900", "₦2,700", "₦5,400", "₦10,800", "C",
     "Energy = 1.5 × 2 × 30 = 90 kWh; cost = 90 × ₦60 = ₦5,400.", "1.5*2*30*60"),
    ("Electricity", "Medium", "The resistance of a wire is R. If the wire is replaced by one of the same material and length but twice the diameter, the new resistance is",
     "one-quarter of R", "half of R", "twice R", "four times R", "A",
     "R = ρL/A and doubling the diameter multiplies the area by four, so the resistance falls to R/4."),
    ("Electricity", "Medium", "A cell of e.m.f. 1.5 V and internal resistance 0.5 Ω is short-circuited by a thick copper wire of negligible resistance. The current that flows is",
     "0.75 A", "1.5 A", "3 A", "0.33 A", "C",
     "I = E/r = 1.5/0.5 = 3 A; the internal resistance alone limits the current.", "1.5/0.5"),
    ("Electricity", "Hard", "Two identical cells, each of e.m.f. 2 V and internal resistance 1 Ω, are connected in parallel across a 1.5 Ω resistor. The current in the resistor is",
     "0.5 A", "1 A", "1.6 A", "2 A", "B",
     "In parallel the e.m.f. stays 2 V and the internal resistance halves to 0.5 Ω: I = 2/(0.5 + 1.5) = 1 A.", "2/(0.5+1.5)"),
    ("Electricity", "Medium", "A 5 μF capacitor is charged to a potential difference of 200 V. The charge stored on it is",
     "1 × 10⁻³ C", "4 × 10⁻² C", "1 × 10³ C", "2.5 × 10⁻⁸ C", "A",
     "Q = CV = 5 × 10⁻⁶ × 200 = 1 × 10⁻³ C.", "5e-6*200/1e-3"),
    ("Electricity", "Easy", "In house wiring the fuse for an appliance is always placed in the",
     "neutral wire", "live wire", "earth wire", "neutral and earth wires together", "B",
     "When a fuse in the live wire blows it disconnects the appliance from the high-voltage side; in the neutral wire the appliance would remain live after the fuse blew."),
    ("Electricity", "Medium", "A student mistakenly connects a voltmeter in series with a bulb and a cell. The bulb does not light because the voltmeter",
     "has a very high resistance and allows almost no current to flow", "has a very low resistance and short-circuits the bulb", "reverses the direction of the current in the circuit", "uses up the whole e.m.f. of the cell as heat", "A",
     "A voltmeter is designed to draw negligible current; in series it acts almost like an open switch."),
    # ---------------- Magnetism and Electromagnetic Induction ----------------
    ("Magnetism and Electromagnetic Induction", "Medium", "A step-up transformer has 200 turns in its primary coil and 4,000 turns in its secondary. If the primary current is 2 A, the secondary current (assuming 100% efficiency) is",
     "0.1 A", "40 A", "20 A", "0.5 A", "A",
     "Ip Np = Is Ns for an ideal transformer: Is = 2 × 200/4,000 = 0.1 A — the voltage goes up 20 times, the current down 20 times.", "2*200/4000"),
    ("Magnetism and Electromagnetic Induction", "Hard", "20 kW of power is sent along cables of total resistance 5 Ω. When the transmission voltage is 10 kV, the power lost as heat in the cables is",
     "20 W", "200 W", "2,000 W", "4 kW", "A",
     "I = P/V = 20,000/10,000 = 2 A; loss = I²R = 4 × 5 = 20 W.", "(20000/10000)**2*5"),
    ("Magnetism and Electromagnetic Induction", "Hard", "A coil of 50 turns and area 0.02 m² has its plane perpendicular to a magnetic field of 0.4 T. The field is reduced to zero in 0.1 s. The average e.m.f. induced in the coil is",
     "0.4 V", "4 V", "40 V", "0.04 V", "B",
     "E = N ΔΦ/Δt = 50 × (0.4 × 0.02)/0.1 = 4 V.", "50*0.4*0.02/0.1"),
    ("Magnetism and Electromagnetic Induction", "Medium", "A transformer does not work with a steady direct current in its primary coil because",
     "a direct current cannot flow through a coil of many turns", "a steady current produces a steady flux, which induces no e.m.f.", "the soft-iron core becomes permanently magnetised by d.c.", "a direct current has no potential difference across it", "B",
     "An e.m.f. is induced only while the magnetic flux linking the secondary is changing; a constant current gives a constant flux."),
    ("Magnetism and Electromagnetic Induction", "Easy", "An electric motor and a generator are alike in construction. The difference is that in a motor",
     "electrical energy is converted to mechanical energy", "mechanical energy is converted to electrical energy", "no magnetic field is required", "the coil does not rotate", "A",
     "A motor is driven by a current and turns; a generator is turned and produces a current."),
    ("Magnetism and Electromagnetic Induction", "Hard", "The back e.m.f. in a running electric motor",
     "increases the current drawn when the motor runs faster", "opposes the applied voltage and limits the current as the motor speeds up", "is greatest when the motor is stationary", "is produced by the split-ring commutator", "B",
     "The rotating coil acts as a generator; its induced e.m.f. opposes the supply, which is why a motor draws a large current only at start-up."),
    ("Magnetism and Electromagnetic Induction", "Medium", "A magnetic compass is placed directly below a horizontal wire that runs north–south. When a large current is switched on in the wire, the needle",
     "continues to point towards magnetic north as before", "is deflected sideways towards the east or the west", "swings round to point vertically downwards", "loses its magnetism while the current flows", "B",
     "Oersted's experiment: the current produces a magnetic field in circles round the wire, which is east–west below the wire and turns the needle."),
    ("Magnetism and Electromagnetic Induction", "Medium", "A charged particle moving parallel to the lines of a magnetic field experiences",
     "the maximum possible force", "no force at all", "a force along the field direction", "a force opposite to the field direction", "B",
     "The magnetic force is F = qvB sin θ; when the velocity is parallel to the field, θ = 0 and the force is zero."),
    ("Magnetism and Electromagnetic Induction", "Hard", "An electron (charge 1.6 × 10⁻¹⁹ C) moving at 2 × 10⁶ m/s at right angles to a magnetic field of 0.5 T experiences a force of",
     "1.6 × 10⁻¹³ N", "3.2 × 10⁻¹³ N", "8.0 × 10⁻¹⁴ N", "1.6 × 10⁻¹⁹ N", "A",
     "F = qvB = 1.6 × 10⁻¹⁹ × 2 × 10⁶ × 0.5 = 1.6 × 10⁻¹³ N.", "1.6e-19*2e6*0.5/1e-13"),
    ("Magnetism and Electromagnetic Induction", "Easy", "Which of the following metals is NOT attracted by a magnet?",
     "iron", "nickel", "cobalt", "copper", "D",
     "Iron, nickel and cobalt are ferromagnetic; copper is not attracted by a magnet."),
    ("Magnetism and Electromagnetic Induction", "Medium", "The frequency of the alternating e.m.f. produced by a simple generator is doubled when",
     "the number of turns on the coil is doubled", "the speed of rotation of the coil is doubled", "the strength of the magnetic field is doubled", "the area of the coil is doubled", "B",
     "One revolution produces one complete cycle, so the output frequency equals the rotation rate; the other changes alter only the peak e.m.f."),
    ("Magnetism and Electromagnetic Induction", "Easy", "A magnetic field is described as uniform when its field lines are",
     "parallel and equally spaced", "curved round the poles of a magnet", "crowded together near the poles", "all pointing towards the north pole", "A",
     "Equally spaced parallel lines mean the field has the same strength and direction everywhere, as between the flat poles of a horseshoe magnet."),
    # ---------------- Atomic and Nuclear Physics ----------------
    ("Atomic and Nuclear Physics", "Medium", "A radioactive nuclide has a half-life of 3 hours. The fraction of the original nuclei that has decayed after 9 hours is",
     "1/8", "7/8", "1/3", "2/3", "B",
     "9 hours is three half-lives, so 1/8 of the nuclei remain and 7/8 have decayed.", "7/8"),
    ("Atomic and Nuclear Physics", "Hard", "In the fission reaction ²³⁵₉₂U + ¹₀n → ¹⁴¹₅₆Ba + ⁹²₃₆Kr + x ¹₀n, the value of x is",
     "1", "2", "3", "4", "C",
     "Mass numbers balance: 235 + 1 = 141 + 92 + x, so x = 3 neutrons.", "236-233"),
    ("Atomic and Nuclear Physics", "Medium", "The nuclide ²¹⁰₈₂Pb decays by beta emission. The daughter nuclide has",
     "atomic number 83 and mass number 210", "atomic number 81 and mass number 210", "atomic number 82 and mass number 209", "atomic number 80 and mass number 206", "A",
     "Beta emission turns a neutron into a proton: the atomic number rises by one and the mass number is unchanged."),
    ("Atomic and Nuclear Physics", "Hard", "A Geiger counter registers 40 counts per minute from background radiation alone, and 680 counts per minute with a radioactive source present. After two half-lives of the source it will register about",
     "170 counts per minute", "200 counts per minute", "160 counts per minute", "210 counts per minute", "B",
     "Source count = 680 − 40 = 640; after two half-lives it is 160, plus the constant background of 40 gives 200.", "640/4+40"),
    ("Atomic and Nuclear Physics", "Medium", "Nuclear fusion, the process that powers the Sun, involves",
     "the splitting of heavy nuclei into lighter ones", "the joining of light nuclei to form a heavier nucleus", "the emission of alpha particles from uranium nuclei", "the capture of electrons by protons", "B",
     "In the Sun hydrogen nuclei fuse to form helium, releasing energy from the loss of mass (E = mc²)."),
    ("Atomic and Nuclear Physics", "Easy", "Which radiation from a radioactive source is NOT deflected by electric or magnetic fields?",
     "alpha particles", "beta particles", "gamma rays", "all three are deflected", "C",
     "Gamma rays are uncharged electromagnetic waves; alpha (positive) and beta (negative) particles are deflected in opposite directions."),
    ("Atomic and Nuclear Physics", "Medium", "In a nuclear reactor the control rods are made of boron or cadmium because these materials",
     "absorb neutrons readily", "slow down fast neutrons", "release extra neutrons", "reflect neutrons back into the core", "A",
     "Lowering the rods removes neutrons from the chain reaction and slows it; raising them speeds it up."),
    ("Atomic and Nuclear Physics", "Medium", "The moderator (graphite or heavy water) in a nuclear reactor is used to",
     "absorb the excess neutrons and stop the reaction", "slow the fast neutrons so they cause further fission", "carry the heat away from the hot fuel rods", "shield the workers from the radiation produced", "B",
     "Slow (thermal) neutrons are far more likely to be captured by uranium-235 and cause fission than fast ones."),
    ("Atomic and Nuclear Physics", "Hard", "The mass defect of a nucleus is 0.1 u. Taking 1 u = 1.66 × 10⁻²⁷ kg and c = 3 × 10⁸ m/s, the binding energy of the nucleus is approximately",
     "1.5 × 10⁻¹¹ J", "1.5 × 10⁻¹³ J", "5.0 × 10⁻²⁰ J", "1.5 × 10⁻⁸ J", "A",
     "E = Δm c² = 0.1 × 1.66 × 10⁻²⁷ × (3 × 10⁸)² = 1.5 × 10⁻¹¹ J.", "0.1*1.66e-27*9e16/1e-11"),
    ("Atomic and Nuclear Physics", "Medium", "A radioisotope chosen as a medical tracer should have",
     "a very long half-life so that it remains active in the body for years", "a short half-life and gamma emission that can be detected outside the body", "a long half-life and alpha emission that stays inside the body tissue", "no radiation at all so that the patient is not harmed in any way", "B",
     "Gamma rays escape the body to be detected by a camera, and a short half-life keeps the patient's total dose small."),
    ("Atomic and Nuclear Physics", "Medium", "A sample contains 8 × 10²⁰ atoms of a radioactive isotope with a half-life of 5 days. The number of undecayed atoms left after 15 days is",
     "1 × 10²⁰", "2 × 10²⁰", "4 × 10²⁰", "5 × 10¹⁹", "A",
     "15 days is three half-lives: 8 → 4 → 2 → 1 × 10²⁰ atoms.", "8/8"),
    ("Atomic and Nuclear Physics", "Medium", "Alpha particles are more strongly ionising than beta particles because alpha particles",
     "move much faster and so hit more atoms every second", "carry more charge and move more slowly, so they ionise more atoms per cm", "are electromagnetic waves that penetrate deep into matter", "have no charge and so collide directly with the nuclei of atoms", "B",
     "The doubly charged, heavy, relatively slow alpha particle pulls electrons off almost every atom it passes, which is also why its range is so short."),
    # ---------------- Electronics and Modern Physics ----------------
    ("Electronics and Modern Physics", "Medium", "Light whose frequency is below the threshold frequency of a metal falls on its surface. The metal",
     "emits electrons only if the light is bright enough", "emits no electrons however bright the light is", "emits electrons after a short time delay", "emits electrons with very high kinetic energy", "B",
     "Each photon has energy hf, which is less than the work function; no single photon can free an electron, whatever the intensity."),
    ("Electronics and Modern Physics", "Medium", "The stopping potential for the photoelectrons emitted from a metal is 1.2 V. The maximum kinetic energy of the electrons is (e = 1.6 × 10⁻¹⁹ C)",
     "1.92 × 10⁻¹⁹ J", "1.2 × 10⁻¹⁹ J", "1.33 × 10⁻¹⁹ J", "1.92 × 10⁻²⁰ J", "A",
     "KE_max = eV_s = 1.6 × 10⁻¹⁹ × 1.2 = 1.92 × 10⁻¹⁹ J.", "1.2*1.6"),
    ("Electronics and Modern Physics", "Hard", "A metal with a work function of 2.0 eV is illuminated with violet light of wavelength 400 nm. Taking hc = 1,240 eV nm, the fastest photoelectrons leave with a kinetic energy of",
     "1.1 eV", "3.1 eV", "5.1 eV", "0.5 eV", "A",
     "Photon energy = hc/λ = 1,240/400 = 3.1 eV; KE_max = 3.1 − 2.0 = 1.1 eV.", "1240/400-2"),
    ("Electronics and Modern Physics", "Medium", "Silicon doped with boron (a Group 3 element) becomes a semiconductor in which the majority charge carriers are",
     "free electrons", "holes", "protons", "negative ions", "B",
     "Boron has one electron fewer than silicon, leaving a vacancy (hole) in the bonding; the material is p-type."),
    ("Electronics and Modern Physics", "Medium", "A bridge rectifier of four diodes is fed with a 50 Hz alternating supply. The ripple frequency of its full-wave rectified output is",
     "25 Hz", "50 Hz", "100 Hz", "200 Hz", "C",
     "Full-wave rectification turns both halves of each cycle positive, giving two pulses per cycle: 2 × 50 = 100 Hz.", "100"),
    ("Electronics and Modern Physics", "Medium", "In a common-emitter transistor amplifier, a small change in the base current produces",
     "a large change in the collector current", "no change in the collector current", "an equal change in the collector current", "a large change in the base voltage only", "A",
     "The collector current is β times the base current (β typically 50–300), which is the basis of current amplification."),
    ("Electronics and Modern Physics", "Medium", "A transistor has a current gain of 100. When its base current is 20 μA the collector current is",
     "0.2 mA", "2 mA", "20 mA", "200 mA", "B",
     "Ic = β Ib = 100 × 20 μA = 2,000 μA = 2 mA.", "100*20e-6/1e-3"),
    ("Electronics and Modern Physics", "Medium", "A security alarm should sound (output 1) when either the door sensor or the window sensor, or both, is triggered (input 1). The logic gate needed is",
     "an AND gate", "an OR gate", "a NOT gate", "a NAND gate", "B",
     "An OR gate gives an output of 1 when at least one of its inputs is 1; an AND gate would need both sensors to be triggered at once."),
    ("Electronics and Modern Physics", "Easy", "In a cathode-ray oscilloscope the electron beam is produced by",
     "photoelectric emission from a cold cathode", "thermionic emission from a heated cathode", "radioactive decay inside the tube", "field emission from the anode", "B",
     "A heated filament (cathode) boils off electrons, which are then accelerated and focused by the anodes."),
    ("Electronics and Modern Physics", "Hard", "X-rays and gamma rays are both electromagnetic waves. The essential difference is that X-rays",
     "have much longer wavelengths than any gamma rays and less energy", "come from electron transitions or stopped electrons, not from the nucleus", "cannot penetrate matter as gamma rays do and are stopped by paper", "carry an electric charge whereas gamma rays are always neutral", "B",
     "Gamma rays originate in the nucleus; X-rays are produced outside it, by fast electrons striking a target or by inner-shell electron transitions."),
    ("Electronics and Modern Physics", "Medium", "The de Broglie wavelength of a moving particle is halved when its",
     "mass is halved", "momentum is doubled", "speed is halved", "charge is doubled", "B",
     "λ = h/p, so the wavelength is inversely proportional to the momentum."),
    ("Electronics and Modern Physics", "Easy", "A light-emitting diode (LED) gives out light only when it is",
     "reverse biased", "forward biased", "connected to an alternating supply", "heated to a high temperature", "B",
     "Current flows through the junction only in forward bias, and the recombining charge carriers release their energy as light."),
    ("Electronics and Modern Physics", "Medium", "In Bohr's model of the hydrogen atom, an electron that moves from the second energy level down to the first",
     "absorbs a photon whose energy equals the gap between the levels", "emits a photon whose energy equals the gap between the levels", "loses part of its electric charge to the nucleus", "gains kinetic energy without any radiation being emitted", "B",
     "Falling to a lower level releases energy as a photon of frequency f = (E₂ − E₁)/h; jumping up requires a photon to be absorbed."),
]

FIX = {}


def build():
    build_batch(
        S, "batch_016_physics_round4.json", "batch_016_physics_round4",
        "Physics round 4: applied and calculation items across all fifteen topics, taking Physics past 500 curated questions.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
