"""Batch 047 - WAEC/NECO Chemistry, Paper 1 round 1.

WASSCE Chemistry Paper 1 is a 50-item objective paper (60 minutes).  This batch
covers the SSCE syllabus: particulate nature of matter, atomic structure,
periodicity, bonding, the mole concept and stoichiometry, gas laws, solutions,
water treatment, electrolysis, energy changes and rates of reaction,
equilibrium, acids/bases/salts, redox, metals, non-metals, organic chemistry
and separation techniques.  All calculations (molar masses, titration,
percentage composition, gas laws, electrolysis) carry independent `verify`
computations; molar volume at s.t.p. is taken as 22.4 dm³ and the Faraday as
96,500 C, as in WASSCE papers.

    python3 scripts/build_content_batch47.py -> content/batch_047_waec_chemistry.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Chemistry"

T_MATTER = "Particulate Nature of Matter"
T_ATOMIC = "Atomic Structure"
T_PERIOD = "Periodic Table and Periodicity"
T_BOND = "Chemical Bonding and Structure"
T_STOICH = "Mole Concept and Stoichiometry"
T_GAS = "Gas Laws"
T_SOL = "Solutions and Solubility"
T_WATER = "Water and Water Treatment"
T_ELEC = "Electrolysis"
T_RATE = "Energy Changes and Rates of Reaction"
T_EQM = "Chemical Equilibrium"
T_ACID = "Acids, Bases and Salts"
T_REDOX = "Redox Reactions and Cells"
T_METAL = "Metals and Their Compounds"
T_NONMET = "Non-metals and Their Compounds"
T_ORG = "Organic Chemistry"
T_LAB = "Separation and Laboratory Techniques"

PASSAGES = []
PQ = []

Q = [
    # -------------------------------------------------- particulate nature
    (T_MATTER, "Easy", "Diffusion is the movement of particles",
     "from a region of higher concentration to a region of lower concentration", "from a region of lower concentration to a higher one", "only in solids", "that stops when a gas is cooled", "A",
     "Particles spread down their concentration gradient until evenly distributed.", None),
    (T_MATTER, "Medium", "In the diffusion of hydrogen chloride and ammonia along a tube, the white ring of ammonium chloride forms nearer the hydrogen chloride end because",
     "ammonia is lighter and diffuses faster", "hydrogen chloride is lighter and diffuses faster", "both gases have equal masses", "ammonia is insoluble in water", "A",
     "Ammonia (M = 17) travels further in the same time than the heavier HCl (M = 36.5).", None),
    (T_MATTER, "Easy", "The random movement of tiny pollen grains in water seen under a microscope is called",
     "Brownian motion", "diffusion", "osmosis", "evaporation", "A",
     "Brownian motion is caused by water molecules continually hitting the grains.", None),
    (T_MATTER, "Medium", "In which state of matter are the particles held in fixed positions, only vibrating about them?",
     "Solid", "Liquid", "Gas", "Vapour", "A",
     "Strong forces hold solid particles in a fixed lattice, so they only vibrate.", None),
    (T_MATTER, "Medium", "The direct change of a solid into vapour on heating is called",
     "sublimation", "evaporation", "condensation", "melting", "A",
     "Solids like iodine and naphthalene sublime straight to vapour on heating.", None),
    (T_MATTER, "Easy", "Evaporation of a liquid in an open dish causes cooling because",
     "the most energetic molecules escape from the surface", "the dish absorbs heat from the liquid", "new molecules are formed in the vapour", "air pushes the molecules down", "A",
     "Only the fastest molecules leave, so the average kinetic energy left behind falls.", None),

    # ------------------------------------------------------ atomic structure
    (T_ATOMIC, "Easy", "The nucleus of an atom contains",
     "protons and neutrons", "protons and electrons", "electrons and neutrons", "neutrons only", "A",
     "Protons and neutrons sit in the nucleus; electrons occupy shells around it.", None),
    (T_ATOMIC, "Easy", "The atomic number of an element equals the number of",
     "protons in its nucleus", "neutrons in its nucleus", "protons plus neutrons", "electrons plus neutrons", "A",
     "Atomic number is defined by the proton count and fixes the element's identity.", None),
    (T_ATOMIC, "Medium", "An atom of sodium has mass number 23 and atomic number 11. How many neutrons does it contain?",
     "12", "23", "11", "34", "A",
     "Neutrons = mass number − atomic number = 23 − 11 = 12.", "23-11"),
    (T_ATOMIC, "Medium", "How many electrons are present in the chloride ion, Cl⁻? (Chlorine's atomic number is 17.)",
     "18", "17", "16", "35", "A",
     "The negative charge means one extra electron: 17 + 1 = 18.", "17+1"),
    (T_ATOMIC, "Medium", "Isotopes of an element have the same number of protons but different numbers of",
     "neutrons", "electrons in the outer shell", "nuclei charges", "chemical properties are different", "A",
     "Isotopes differ in neutron number, so their mass numbers differ.", None),
    (T_ATOMIC, "Hard", "Chlorine exists as 75% of the isotope of mass 35 and 25% of the isotope of mass 37. Its relative atomic mass is",
     "35.5", "36.0", "35.7", "36.5", "A",
     "RAM = (75 × 35 + 25 × 37)/100 = 35.5.", "(75*35+25*37)/100"),
    (T_ATOMIC, "Medium", "The electron configuration of an atom of potassium (atomic number 19) is",
     "2, 8, 8, 1", "2, 8, 9", "2, 8, 8, 8, 1", "2, 8, 1, 8", "A",
     "Potassium fills the shells 2 then 8 then 8, leaving one electron in the fourth shell.", None),
    (T_ATOMIC, "Medium", "An atom with the electron configuration 2, 8, 8 belongs to which group of the periodic table?",
     "Group 0 (noble gases)", "Group 1", "Group 7", "Group 8 in the transition block", "A",
     "A complete outer shell of eight electrons makes it a noble gas like argon.", None),
    (T_ATOMIC, "Hard", "The maximum number of electrons that can occupy the shell with n = 3 is",
     "18", "8", "32", "10", "A",
     "The capacity is 2n² = 2 × 3² = 18 electrons.", "2*3**2"),
    (T_ATOMIC, "Hard", "An element X has 13 protons. The formula of its most common ion is",
     "X³⁺", "X⁺", "X²⁺", "X³⁻", "A",
     "With configuration 2, 8, 3, atom X (aluminium) loses three electrons to gain a stable shell.", None),

    # ------------------------------------------------------------- periodicity
    (T_PERIOD, "Easy", "The elements in Group 1 of the periodic table are known collectively as the",
     "alkali metals", "alkaline earth metals", "halogens", "noble gases", "A",
     "Lithium, sodium and potassium are the soft, reactive alkali metals.", None),
    (T_PERIOD, "Easy", "Which group contains elements that are monatomic and very unreactive gases?",
     "Group 0", "Group 1", "Group 7", "Group 2", "A",
     "Noble gases have complete outer shells, so they rarely react.", None),
    (T_PERIOD, "Medium", "Bromine is a red-brown liquid at room temperature. Iodine, the element below it, is a",
     "black solid", "pale yellow gas", "red-brown gas", "silvery liquid", "A",
     "Down Group 7 the states rise from gas (F₂, Cl₂) to liquid (Br₂) to solid (I₂).", None),
    (T_PERIOD, "Medium", "Sodium is stored under oil in the laboratory because it",
     "reacts vigorously with air and water", "is a very soft metal that crumbles", "melts easily in the sun", "reacts with other metals", "A",
     "The oil keeps air and moisture away from the very reactive metal surface.", None),
    (T_PERIOD, "Hard", "Going down Group 1 from lithium to potassium, the reactivity of the metals",
     "increases because the outer electron is lost more easily", "decreases because the atoms get smaller", "stays exactly the same", "increases because the nucleus attracts more", "A",
     "The outer electron is further from the nucleus and lost more readily down the group.", None),
    (T_PERIOD, "Hard", "Going down Group 7 from chlorine to iodine, the reactivity of the halogens",
     "decreases", "increases", "remains constant", "first increases then decreases", "A",
     "The incoming electron is gained less easily as the atoms get larger.", None),
    (T_PERIOD, "Medium", "The number of electron shells in an atom tells you its",
     "period in the periodic table", "group in the periodic table", "atomic mass", "valency", "A",
     "Elements in the same period have the same number of occupied shells.", None),
    (T_PERIOD, "Medium", "Copper(II) salts are usually blue in colour. This is a property typical of",
     "transition metals", "alkali metals", "halogens", "noble gases", "A",
     "Coloured compounds and variable oxidation states are classic transition-metal features.", None),
    (T_PERIOD, "Easy", "The family name for the elements in Group 7 is the",
     "halogens", "alkalis", "chalcogens", "actinides", "A",
     "Fluorine, chlorine, bromine and iodine are the halogen family.", None),
    (T_PERIOD, "Hard", "An element with atomic number 12 belongs to",
     "Group 2 and Period 3", "Group 3 and Period 2", "Group 2 and Period 2", "Group 12", "A",
     "Magnesium is 2, 8, 2: two outer electrons (Group 2) in three shells (Period 3).", None),

    # ------------------------------------------------------------------ bonding
    (T_BOND, "Easy", "The bond formed when sodium reacts with chlorine is",
     "ionic", "covalent", "metallic", "dative", "A",
     "Sodium transfers an electron to chlorine, giving Na⁺ and Cl⁻ held by electrostatic force.", None),
    (T_BOND, "Easy", "A covalent bond involves the sharing of",
     "a pair of electrons between two atoms", "electrons free to move through a lattice", "protons between nuclei", "neutrons between atoms", "A",
     "Each bonded atom contributes one electron to the shared pair.", None),
    (T_BOND, "Medium", "In the ammonium ion, NH₄⁺, one of the N–H bonds is formed by a lone pair donated by nitrogen. This bond is described as",
     "dative covalent", "metallic", "ionic", "hydrogen bonding", "A",
     "Both shared electrons come from one atom, so the bond is dative (coordinate) covalent.", None),
    (T_BOND, "Medium", "Metals are good conductors of electricity because they",
     "have free-moving electrons", "contain mobile ions", "are always solids", "have free protons", "A",
     "The delocalised outer electrons drift when a potential difference is applied.", None),
    (T_BOND, "Medium", "Which property is typical of ionic compounds?",
     "They conduct when molten or in solution", "They have very low boiling points", "They are usually gases at room temperature", "They dissolve easily in petrol and kerosene", "A",
     "Strong electrostatic forces give high melting points; melted or dissolved ions carry charge.", None),
    (T_BOND, "Medium", "Simple molecular covalent substances have low melting points because",
     "only weak intermolecular forces exist between the molecules", "the covalent bonds inside molecules are weak", "they contain free electrons", "they are always metals", "A",
     "Melting separates molecules, overcoming weak forces, not the strong covalent bonds.", None),
    (T_BOND, "Hard", "Graphite conducts electricity but diamond does not because graphite",
     "has free electrons between its layers", "is made of different atoms", "has stronger covalent bonds", "contains ions", "A",
     "Each carbon in graphite uses three bonds, leaving delocalised electrons that conduct.", None),
    (T_BOND, "Hard", "Diamond is extremely hard because",
     "each carbon bonds to four others in a network", "its atoms are held together by ionic bonds", "it contains free-moving delocalised electrons", "its molecules form very long chains", "A",
     "The three-dimensional network of strong covalent bonds makes diamond very hard.", None),
    (T_BOND, "Medium", "The formation of Mg²⁺ from a magnesium atom involves",
     "the loss of two electrons", "the gain of two electrons", "the loss of two protons", "sharing two electrons", "A",
     "Magnesium (2, 8, 2) loses its two outer electrons to reach a stable arrangement.", None),
    (T_BOND, "Hard", "Water has an unusually high boiling point for such a small molecule because of",
     "hydrogen bonding between its molecules", "ionic bonds between its atoms", "its covalent bonds inside the molecule", "the oxygen it contains", "A",
     "Strong hydrogen bonds between water molecules need extra energy to break.", None),
    (T_BOND, "Medium", "Which pair of elements would form a compound by electron transfer?",
     "Magnesium and oxygen", "carbon and sulphur", "hydrogen and chlorine", "nitrogen and oxygen", "A",
     "A metal reacting with a non-metal transfers electrons to form ions.", None),
    (T_BOND, "Easy", "The bond that holds a pair of chlorine atoms together in a chlorine molecule is",
     "a single covalent bond", "an ionic bond", "a double covalent bond", "a metallic bond", "A",
     "The two chlorine atoms share one pair of electrons.", None),

    # --------------------------------------------- mole concept/stoichiometry
    (T_STOICH, "Easy", "One mole of any substance contains",
     "6.02 × 10²³ particles", "22.4 particles", "6.02 × 10⁻²³ particles", "1 gram of particles", "A",
     "The Avogadro constant is 6.02 × 10²³ particles per mole.", None),
    (T_STOICH, "Easy", "How many moles are present in 8 g of oxygen gas, O₂? (O = 16.)",
     "0.25", "0.5", "4", "8", "A",
     "M(O₂) = 32, so n = 8 ÷ 32 = 0.25 mol.", "8/32"),
    (T_STOICH, "Medium", "How many moles are present in 11 g of carbon dioxide? (C = 12, O = 16.)",
     "0.25", "0.5", "2", "0.44", "A",
     "M(CO₂) = 12 + 32 = 44, so n = 11 ÷ 44 = 0.25 mol.", "11/44"),
    (T_STOICH, "Medium", "What volume does 0.25 mol of a gas occupy at s.t.p.? (Molar volume = 22.4 dm³.)",
     "5.6 dm³", "22.4 dm³", "11.2 dm³", "2.24 dm³", "A",
     "V = 0.25 × 22.4 = 5.6 dm³ at standard temperature and pressure.", "0.25*22.4"),
    (T_STOICH, "Medium", "How many molecules are present in 0.5 mol of ammonia gas?",
     "3.01 × 10²³", "6.02 × 10²³", "1.204 × 10²⁴", "6.02 × 10²²", "A",
     "0.5 × 6.02 × 10²³ = 3.01 × 10²³ molecules.", None),
    (T_STOICH, "Medium", "What is the mass of 0.2 mol of sodium hydroxide? (Na = 23, O = 16, H = 1.)",
     "8 g", "4 g", "40 g", "80 g", "A",
     "M(NaOH) = 40, so mass = 0.2 × 40 = 8 g.", "0.2*40"),
    (T_STOICH, "Hard", "Calculate the concentration of a solution containing 3.65 g of hydrogen chloride in 500 cm³ of solution.",
     "0.2 mol/dm³", "0.1 mol/dm³", "7.3 mol/dm³", "2.0 mol/dm³", "A",
     "n = 3.65 ÷ 36.5 = 0.1 mol in 0.5 dm³, so c = 0.2 mol/dm³.", "3.65/36.5/0.5"),
    (T_STOICH, "Hard", "25.0 cm³ of 0.1 mol/dm³ hydrochloric acid exactly neutralises 20.0 cm³ of sodium hydroxide solution. The concentration of the alkali is",
     "0.125 mol/dm³", "0.08 mol/dm³", "0.1 mol/dm³", "0.25 mol/dm³", "A",
     "For the 1:1 reaction, C(NaOH) = (0.1 × 25) ÷ 20 = 0.125 mol/dm³.", "0.1*25/20"),
    (T_STOICH, "Hard", "What mass of calcium oxide is obtained by heating 50 g of calcium carbonate? (CaCO₃ = 100, CaO = 56.)",
     "28 g", "56 g", "50 g", "22 g", "A",
     "CaCO₃ → CaO + CO₂, so 50 g gives 50 × 56/100 = 28 g of CaO.", "50/100*56"),
    (T_STOICH, "Hard", "In the reaction 2H₂ + O₂ → 2H₂O, what mass of oxygen is needed to burn 8 g of hydrogen completely?",
     "64 g", "32 g", "16 g", "8 g", "A",
     "n(H₂) = 4 mol, needing 2 mol of O₂ = 64 g.", "8/2*0.5*32"),
    (T_STOICH, "Hard", "What is the percentage by mass of nitrogen in ammonia, NH₃? (N = 14, H = 1.)",
     "82.4%", "46.7%", "17.6%", "50.0%", "A",
     "%N = (14 ÷ 17) × 100 = 82.4%.", "14/17*100"),
    (T_STOICH, "Hard", "What is the percentage by mass of water in Na₂CO₃·10H₂O? (Na₂CO₃ = 106, H₂O = 18.)",
     "63.0%", "37.0%", "50.0%", "17.0%", "A",
     "Ten waters weigh 180 out of 286, giving (180 ÷ 286) × 100 = 63.0%.", "180/286*100"),
    (T_STOICH, "Hard", "A hydrocarbon contains 85.7% carbon and 14.3% hydrogen by mass. Its empirical formula is",
     "CH₂", "CH", "CH₃", "C₂H₅", "A",
     "Dividing by atomic masses gives 7.14 : 14.3, which simplifies to 1 : 2, so CH₂.", None),
    (T_STOICH, "Hard", "20 g of an impure sample of calcium carbonate gives 2.24 dm³ of carbon dioxide at s.t.p. The percentage purity of the sample is",
     "50%", "80%", "25%", "100%", "A",
     "n(CO₂) = 0.1 mol, so 10 g of pure CaCO₃ reacted: (10 ÷ 20) × 100 = 50%.", "2.24/22.4*100/20*100"),
    (T_STOICH, "Medium", "What mass of copper is deposited when a current is passed through copper(II) sulphate solution for long enough to transfer 0.4 mol of electrons? (Cu = 64.)",
     "12.8 g", "25.6 g", "6.4 g", "51.2 g", "A",
     "Cu²⁺ needs 2 electrons per atom, so 0.2 mol Cu = 12.8 g is deposited.", "0.4/2*64"),

    # ------------------------------------------------------------------ gas laws
    (T_GAS, "Medium", "A gas occupies 200 cm³ at a pressure of 750 mmHg. What is its volume at 760 mmHg, at the same temperature?",
     "197.4 cm³", "202.7 cm³", "150 cm³", "250 cm³", "A",
     "By Boyle's law, V₂ = (750 × 200) ÷ 760 = 197.4 cm³.", "750*200/760"),
    (T_GAS, "Medium", "A gas occupies 300 cm³ at 27°C. What is its volume at 57°C, at the same pressure?",
     "330 cm³", "270 cm³", "600 cm³", "317 cm³", "A",
     "Charles' law with kelvin: V₂ = 300 × 330/300 = 330 cm³.", "300*(57+273)/(27+273)"),
    (T_GAS, "Easy", "In gas law calculations, temperatures must be converted to",
     "kelvin", "degrees Celsius", "degrees Fahrenheit", "millimetres", "A",
     "Adding 273 to the Celsius reading gives the kelvin temperature the laws require.", None),
    (T_GAS, "Medium", "Express 25°C in kelvin.",
     "298 K", "248 K", "273 K", "2980 K", "A",
     "K = °C + 273 = 25 + 273 = 298 K.", "25+273"),
    (T_GAS, "Hard", "A fixed mass of gas at 300 K and 600 cm³ is heated to 450 K at constant pressure. Its new volume is",
     "900 cm³", "400 cm³", "450 cm³", "1,200 cm³", "A",
     "V/T is constant, so V₂ = 600 × 450/300 = 900 cm³.", "600*450/300"),
    (T_GAS, "Hard", "Gases can be compressed easily because",
     "their particles are far apart", "their particles are tightly packed", "their particles are large", "they contain air", "A",
     "The large spaces between gas particles allow them to be pushed closer.", None),

    # ---------------------------------------------------------- solutions
    (T_SOL, "Easy", "In a sugar solution, the sugar is the",
     "solute", "solvent", "solution", "suspension", "A",
     "The substance dissolved is the solute; the liquid doing the dissolving is the solvent.", None),
    (T_SOL, "Medium", "A solution that cannot dissolve any more solute at a given temperature is described as",
     "saturated", "concentrated", "dilute", "supersaturated always", "A",
     "At saturation the dissolved solute is in equilibrium with the undissolved solid.", None),
    (T_SOL, "Hard", "5 g of potassium nitrate dissolves in 25 g of water at 20°C. The solubility of potassium nitrate at that temperature is",
     "20 g per 100 g of water", "5 g per 100 g of water", "25 g per 100 g of water", "80 g per 100 g of water", "A",
     "Solubility = (5 ÷ 25) × 100 = 20 g of salt per 100 g of water.", "5/25*100"),
    (T_SOL, "Hard", "What is the percentage by mass of a solution made by dissolving 5 g of salt in 95 g of water?",
     "5%", "5.3%", "95%", "0.5%", "A",
     "Percentage = (5 ÷ (5 + 95)) × 100 = 5% of the solution mass.", "5/(5+95)*100"),
    (T_SOL, "Medium", "Two liquids that mix completely in all proportions, like ethanol and water, are said to be",
     "miscible", "immiscible", "saturated", "insoluble", "A",
     "Miscible liquids form a single homogeneous layer when mixed.", None),
    (T_SOL, "Medium", "Oil and water form two layers on mixing. The best apparatus for separating them is the",
     "separating funnel", "filter funnel", "distillation flask", "evaporating dish", "A",
     "Immiscible liquids separate into layers that can be run off through a tap.", None),
    (T_SOL, "Medium", "A suspension differs from a true solution because a suspension",
     "contains particles that settle out on standing", "is always completely colourless to the eye", "cannot be filtered by ordinary filter paper", "contains no solvent at all in the mixture", "A",
     "Suspension particles are large enough to scatter light and settle on standing.", None),
    (T_SOL, "Easy", "Increasing the temperature usually increases the solubility of a solid solute because",
     "particles move faster and separate more easily", "the solute evaporates away before dissolving", "the solvent molecules become heavier", "the solute particles become larger overall", "A",
     "Higher kinetic energy helps solvent particles break solute particles apart.", None),

    # ----------------------------------------------------- water and treatment
    (T_WATER, "Easy", "When acidified water is electrolysed, hydrogen and oxygen are collected in the volume ratio",
     "2 : 1", "1 : 2", "1 : 8", "1 : 1", "A",
     "Water contains twice as many hydrogen atoms, so twice the volume of hydrogen forms.", "2/1"),
    (T_WATER, "Medium", "The chemical test for water uses anhydrous copper(II) sulphate, which changes from white to",
     "blue", "pink", "white stays white", "black", "A",
     "Anhydrous CuSO₄ turns blue as it takes up water of crystallisation.", None),
    (T_WATER, "Medium", "Temporary hardness of water is caused mainly by dissolved",
     "calcium hydrogencarbonate", "sodium chloride", "calcium sulphate", "magnesium chloride", "A",
     "Hydrogencarbonates of calcium and magnesium cause hardness that boiling removes.", None),
    (T_WATER, "Medium", "Hardness that cannot be removed by boiling is called permanent hardness. It can be removed by adding",
     "washing soda (sodium carbonate)", "common salt (sodium chloride)", "plenty of soap solution instead", "a little dilute hydrochloric acid", "A",
     "Sodium carbonate precipitates the calcium ions, softening the water.", None),
    (T_WATER, "Easy", "Hard water wastes soap because",
     "the calcium salts react with soap to form scum", "hard water is heavier than soft water", "soap dissolves better in hard water", "hard water is hot", "A",
     "Calcium and magnesium ions form an insoluble scum instead of lather.", None),
    (T_WATER, "Hard", "In municipal water treatment, alum (aluminium sulphate) is added to",
     "make fine suspended particles clump together", "kill all the bacteria in the raw water", "soften the hard water in the tank", "add fluoride ions to the water", "A",
     "Alum coagulates suspended mud into flocs that settle or are filtered out.", None),
    (T_WATER, "Medium", "Chlorine is added near the end of municipal water treatment in order to",
     "kill disease-causing germs", "remove colour", "soften the water", "neutralise acids", "A",
     "Chlorination disinfects the supply, making the water safe to drink.", None),

    # ------------------------------------------------------------- electrolysis
    (T_ELEC, "Easy", "An electrolyte is a substance that",
     "conducts electricity when molten or dissolved", "conducts electricity as a solid metal", "never conducts electricity in any state", "dissolves in every liquid it meets", "A",
     "Electrolytes are ionic substances whose ions become mobile on melting or dissolving.", None),
    (T_ELEC, "Medium", "In electrolysis, oxidation occurs at the",
     "anode", "cathode", "battery", "voltmeter", "A",
     "The anode is the positive electrode where electrons are removed (oxidation).", None),
    (T_ELEC, "Medium", "When molten sodium chloride is electrolysed, the product at the cathode is",
     "sodium metal", "chlorine gas", "hydrogen gas", "sodium hydroxide", "A",
     "Sodium ions migrate to the cathode and gain electrons to form sodium metal.", None),
    (T_ELEC, "Hard", "When concentrated sodium chloride solution is electrolysed using carbon electrodes, the gas produced at the anode is",
     "chlorine", "oxygen", "hydrogen", "carbon dioxide", "A",
     "Chloride ions are discharged in preference to hydroxide ions in concentrated brine.", None),
    (T_ELEC, "Hard", "When DILUTE sodium chloride solution is electrolysed, the gas produced at the anode is",
     "oxygen", "chlorine", "hydrogen", "ammonia", "A",
     "In dilute solution hydroxide ions are discharged in preference to chloride ions.", None),
    (T_ELEC, "Medium", "When copper(II) sulphate solution is electrolysed with carbon electrodes, the cathode becomes coated with",
     "copper metal", "oxygen gas", "sulphur", "carbon", "A",
     "Cu²⁺ ions are discharged at the cathode as copper metal, and the blue colour fades.", None),
    (T_ELEC, "Hard", "In the industrial purification of copper by electrolysis, the impure copper is made the",
     "anode, and it dissolves", "cathode, and it grows", "anode, and it grows", "cathode, and it dissolves", "A",
     "Impure copper dissolves from the anode while pure copper deposits on the cathode.", None),
    (T_ELEC, "Medium", "In silver plating a spoon by electrolysis, the spoon is made the",
     "cathode", "anode", "electrolyte", "salt bridge", "A",
     "Metal objects to be plated are always the cathode, where the metal deposits.", None),
    (T_ELEC, "Hard", "What quantity of electricity in coulombs is carried by a current of 2 A flowing for 965 s?",
     "1,930 C", "965 C", "482.5 C", "3,860 C", "A",
     "Q = It = 2 × 965 = 1,930 C.", "2*965"),
    (T_ELEC, "Hard", "How many faradays of electricity are needed to deposit one mole of aluminium from molten alumina?",
     "3", "1", "2", "6", "A",
     "Al³⁺ needs three electrons per ion, so three faradays deposit one mole.", "3"),

    # ------------------------------------------------ rates and energy changes
    (T_RATE, "Easy", "A reaction that gives out heat to the surroundings is",
     "exothermic", "endothermic", "neutral", "reversible", "A",
     "Exothermic reactions raise the temperature of the surroundings.", None),
    (T_RATE, "Medium", "Dissolving ammonium chloride in water causes the container to feel cold. The change is",
     "endothermic", "exothermic", "explosive", "not a chemical change", "A",
     "Heat is absorbed from the surroundings, so the solution and vessel cool down.", None),
    (T_RATE, "Easy", "Powdered marble reacts faster with dilute acid than marble chips because the powder",
     "has a larger total surface area exposed", "is chemically purer than the chips", "is lighter in total mass than chips", "absorbs more water from the acid", "A",
     "More surface is exposed, so more collisions happen per second.", None),
    (T_RATE, "Medium", "Increasing the temperature increases the rate of a reaction mainly because",
     "collisions become more frequent and energetic", "the activation energy of reaction falls", "the reaction becomes exothermic overall", "any catalyst present works harder", "A",
     "Hotter particles collide more often and more of them exceed the activation energy.", None),
    (T_RATE, "Medium", "A catalyst increases the rate of a reaction by",
     "lowering the activation energy", "raising the temperature", "increasing the concentration", "being used up in the reaction", "A",
     "A catalyst offers an easier pathway; it is unchanged at the end.", None),
    (T_RATE, "Hard", "The minimum energy reacting particles must have for a collision to succeed is the",
     "activation energy", "kinetic energy only", "lattice energy", "ionisation energy", "A",
     "Collisions below the activation energy simply bounce apart.", None),
    (T_RATE, "Medium", "Manganese(IV) oxide speeds up the decomposition of hydrogen peroxide. After the reaction, the MnO₂",
     "remains chemically unchanged", "has been used up completely", "turns into oxygen", "becomes a new compound", "A",
     "Catalysts are recovered unchanged, which is why only a little is needed.", None),
    (T_RATE, "Hard", "Food cooks faster in a pressure cooker because",
     "the higher pressure raises the boiling point of water", "the water boils at a lower temperature", "less heat escapes the cooker", "the food is under less pressure", "A",
     "Water boils above 100°C inside, so cooking proceeds at a hotter temperature.", None),

    # -------------------------------------------------------------- equilibrium
    (T_EQM, "Medium", "At dynamic equilibrium, the rate of the forward reaction",
     "equals the rate of the backward reaction", "is greater than the backward rate", "has fallen to zero", "keeps increasing", "A",
     "Both reactions continue at equal speeds, so concentrations stay constant.", None),
    (T_EQM, "Hard", "In the Haber process, N₂(g) + 3H₂(g) ⇌ 2NH₃(g) + heat. Which change increases the yield of ammonia?",
     "Increasing the pressure", "Decreasing the pressure", "Increasing the temperature", "Removing the catalyst", "A",
     "Four gas moles become two, so high pressure shifts the equilibrium to the right.", None),
    (T_EQM, "Medium", "In the Haber process, the catalyst used is",
     "iron", "platinum", "vanadium(V) oxide", "nickel only", "A",
     "Finely divided iron catalyses the formation of ammonia.", None),
    (T_EQM, "Hard", "The Contact process for making sulphur trioxide uses which catalyst?",
     "Vanadium(V) oxide", "Iron", "Platinum", "Manganese(IV) oxide", "A",
     "V₂O₅ catalyses SO₂ + ½O₂ → SO₃ in the Contact process.", None),
    (T_EQM, "Medium", "Compromise conditions of about 450°C are used in the Haber process because",
     "a low temperature is too slow though it favours yield", "450°C is the cheapest temperature for fuel", "iron only works well at exactly 450°C", "ammonia decomposes rapidly below 450°C", "A",
     "The forward reaction is exothermic, so high temperature cuts yield but low temperature is too slow.", None),
    (T_EQM, "Hard", "Adding a catalyst to a system at equilibrium",
     "brings equilibrium faster without shifting its position", "shifts the equilibrium position right", "increases the final yield of the products", "stops the backward reaction completely", "A",
     "Both directions speed up equally, so the equilibrium mixture is unchanged.", None),

    # ---------------------------------------------------- acids, bases and salts
    (T_ACID, "Easy", "The pH of a neutral solution at 25°C is",
     "7", "0", "1", "14", "A",
     "Pure water has equal H⁺ and OH⁻ concentrations, giving pH 7.", "7"),
    (T_ACID, "Easy", "Dilute hydrochloric acid turns blue litmus paper",
     "red", "blue stays blue", "green", "white", "A",
     "Acids turn blue litmus red; alkalis turn red litmus blue.", None),
    (T_ACID, "Medium", "Phenolphthalein indicator is colourless in acid and turns",
     "pink in alkali", "blue in alkali", "yellow in alkali", "red in alkali", "A",
     "Phenolphthalein is colourless below about pH 8 and pink in alkaline solution.", None),
    (T_ACID, "Medium", "The ionic equation for neutralisation is",
     "H⁺ + OH⁻ → H₂O", "H⁺ + O²⁻ → OH⁻", "Na⁺ + Cl⁻ → NaCl", "H₂O → H⁺ + OH⁻", "A",
     "Whatever the acid and alkali, the essential change is hydrogen ions meeting hydroxide ions.", None),
    (T_ACID, "Medium", "Dilute acid reacts with a metal carbonate to give a salt, water and",
     "carbon dioxide", "hydrogen", "oxygen", "ammonia", "A",
     "The carbonate fizzes, releasing CO₂ that turns limewater milky.", None),
    (T_ACID, "Medium", "Which acid is dibasic?",
     "Tetraoxosulphate(VI) acid (H₂SO₄)", "Hydrochloric acid (HCl)", "Trioxonitrate(V) acid (HNO₃)", "Ethanoic acid (CH₃COOH)", "A",
     "Each H₂SO₄ molecule can release two replaceable hydrogen ions.", None),
    (T_ACID, "Hard", "Which salt preparation method is suitable for making an INSOLUBLE salt?",
     "Precipitation by mixing two soluble salts", "Evaporation of a salt solution", "Neutralising an acid with an alkali", "Crystallisation of a hot solution", "A",
     "Mixing two soluble reactants that form an insoluble product precipitates it directly.", None),
    (T_ACID, "Hard", "Which compound is deliquescent and is used as a laboratory drying agent?",
     "Anhydrous calcium chloride", "Washing soda", "Common salt", "Limestone", "A",
     "Deliquescent substances absorb so much water that they dissolve; CaCl₂ is a classic example.", None),
    (T_ACID, "Medium", "Washing soda, Na₂CO₃·10H₂O, loses its water of crystallisation on exposure to air. Such a salt is",
     "efflorescent", "deliquescent", "hygroscopic", "anhydrous", "A",
     "Efflorescent salts lose their water of crystallisation to the air and become powdery.", None),
    (T_ACID, "Hard", "A strong acid differs from a weak acid because a strong acid",
     "ionises completely in water", "has a higher molar mass", "always contains sulphur", "is always more concentrated", "A",
     "Strength is about degree of ionisation, not concentration of the solution.", None),
    (T_ACID, "Medium", "The reaction between an acid and a base to form salt and water only is called",
     "neutralisation", "hydrolysis", "sublimation", "displacement", "A",
     "Neutralisation removes the acidic and basic properties of the reactants.", None),
    (T_ACID, "Hard", "Which reagent, added to a solution, would confirm the presence of a sulphate ion?",
     "Barium chloride acidified with dilute hydrochloric acid", "Silver nitrate solution in dilute nitric acid", "Aqueous sodium hydroxide in excess", "Dilute ammonia solution in a test tube", "A",
     "A white precipitate of barium sulphate that cannot dissolve in acid confirms sulphate.", None),

    # ------------------------------------------------------------------ redox
    (T_REDOX, "Easy", "Oxidation is the",
     "loss of electrons", "gain of electrons", "gain of protons", "sharing of electrons", "A",
     "Remember OIL RIG: oxidation is loss, reduction is gain of electrons.", None),
    (T_REDOX, "Medium", "In the reaction Zn + Cu²⁺ → Zn²⁺ + Cu, the reducing agent is",
     "zinc", "copper ions", "copper metal", "the electrons", "A",
     "Zinc loses electrons and so reduces the copper ions while itself being oxidised.", None),
    (T_REDOX, "Medium", "What is the oxidation number of sulphur in SO₂?",
     "+4", "+2", "−2", "+6", "A",
     "Two oxygens at −2 each give −4, so sulphur must be +4 for the compound to be neutral.", "2*2"),
    (T_REDOX, "Hard", "What is the oxidation number of manganese in KMnO₄?",
     "+7", "+5", "+2", "+4", "A",
     "K is +1 and each O is −2, so Mn = +7 to balance the compound.", "8-1"),
    (T_REDOX, "Medium", "Rusting of iron requires both",
     "oxygen and water", "oxygen and salt only", "water and carbon dioxide", "nitrogen and water", "A",
     "Iron rusts only when both air (oxygen) and moisture are present.", None),
    (T_REDOX, "Medium", "Galvanising protects iron from rusting by coating it with",
     "zinc", "tin", "copper", "lead", "A",
     "The zinc layer shields the iron and corrodes sacrificially even when scratched.", None),
    (T_REDOX, "Hard", "Blocks of magnesium are fixed to steel ship hulls to provide",
     "sacrificial protection", "galvanising", "electroplating", "cathodic coating of paint", "A",
     "Magnesium corrodes in place of the iron, protecting the hull sacrificially.", None),
    (T_REDOX, "Hard", "In a simple zinc-copper cell, electrons flow through the wire from",
     "zinc to copper", "copper to zinc", "both directions equally", "the electrolyte to the wire", "A",
     "Zinc is more reactive, releases electrons, and acts as the negative electrode.", None),
    (T_REDOX, "Medium", "When Fe²⁺ changes to Fe³⁺, the iron(II) ion has been",
     "oxidised", "reduced", "neutralised", "displaced", "A",
     "Losing an electron raises the charge, which is oxidation.", None),
    (T_REDOX, "Easy", "Which of these is an oxidising agent?",
     "Chlorine", "Hydrogen", "Carbon", "Sulphur dioxide", "A",
     "Chlorine readily accepts electrons from other substances.", None),

    # --------------------------------------------------------- metals
    (T_METAL, "Easy", "Which metal reacts most vigorously with cold water?",
     "Sodium", "Zinc", "Iron", "Copper", "A",
     "In the reactivity series, potassium and sodium react violently with cold water.", None),
    (T_METAL, "Medium", "In the blast furnace, the chief reducing agent that converts iron(III) oxide to iron is",
     "carbon monoxide", "carbon dioxide", "nitrogen", "sulphur dioxide", "A",
     "Hot CO from burning coke strips oxygen from the haematite, leaving molten iron.", None),
    (T_METAL, "Medium", "In the blast furnace, limestone is added to",
     "remove impurities as slag", "provide the iron", "make carbon monoxide", "cool the furnace", "A",
     "Limestone decomposes to lime, which combines with sandy impurities to form slag.", None),
    (T_METAL, "Hard", "Aluminium is extracted by the electrolysis of molten alumina rather than by heating with carbon because",
     "aluminium sits too high in the series for carbon reduction", "aluminium is far cheaper than carbon coke", "alumina melts at a very low temperature", "carbon reacts violently with hot alumina", "A",
     "Carbon cannot displace aluminium from its oxide, so electrolysis is required.", None),
    (T_METAL, "Medium", "Brass is an alloy of copper and",
     "zinc", "tin", "lead", "iron", "A",
     "Brass is copper plus zinc; bronze is copper plus tin.", None),
    (T_METAL, "Medium", "Stainless steel contains iron with mainly",
     "chromium and nickel", "zinc and tin", "carbon only", "copper and lead", "A",
     "Chromium and nickel give stainless steel its rust resistance.", None),
    (T_METAL, "Hard", "When quicklime (calcium oxide) is mixed with water, the product is",
     "slaked lime (calcium hydroxide)", "limestone (calcium carbonate)", "washing soda (sodium carbonate)", "plaster of Paris (calcium sulphate)", "A",
     "CaO + H₂O → Ca(OH)₂, an exothermic slaking reaction.", None),
    (T_METAL, "Medium", "Which metal is found free (native) in the earth's crust?",
     "Gold", "Sodium", "Aluminium", "Zinc", "A",
     "Unreactive metals like gold occur uncombined because they are low in the series.", None),
    (T_METAL, "Medium", "A metal that is liquid at room temperature is",
     "mercury", "sodium", "magnesium", "bromine", "A",
     "Mercury is the only metal that is liquid under ordinary conditions.", None),
    (T_METAL, "Hard", "In a flame test, a golden-yellow flame colour indicates the presence of",
     "sodium", "potassium", "calcium", "copper", "A",
     "Sodium compounds colour the flame golden yellow; potassium gives lilac.", None),
    (T_METAL, "Medium", "Aluminium resists corrosion although it is reactive because",
     "a thin oxide film forms on its surface", "it is covered by oil in the air", "it does not react with oxygen", "the air cools it", "A",
     "The tough, invisible aluminium oxide layer protects the metal beneath.", None),
    (T_METAL, "Easy", "Which metal is used for making electrical cables because it is a very good conductor?",
     "Copper", "Iron", "Lead", "Zinc", "A",
     "Copper combines excellent conductivity with ductility and affordability.", None),

    # --------------------------------------------------------- non-metals
    (T_NONMET, "Medium", "Oxygen can be prepared in the laboratory by the catalytic decomposition of hydrogen peroxide. The catalyst used is",
     "manganese(IV) oxide", "iron", "copper", "vanadium(V) oxide", "A",
     "MnO₂ speeds up 2H₂O₂ → 2H₂O + O₂ at room temperature.", None),
    (T_NONMET, "Easy", "A gas that relights a glowing splint is",
     "oxygen", "hydrogen", "carbon dioxide", "ammonia", "A",
     "The glowing splint test is the classic confirmatory test for oxygen.", None),
    (T_NONMET, "Medium", "Hydrogen gas is prepared in the laboratory by reacting dilute acid with",
     "zinc granules", "copper turnings", "sodium chloride", "limestone", "A",
     "Zn + 2HCl → ZnCl₂ + H₂; the gas burns with a squeaky pop.", None),
    (T_NONMET, "Medium", "Carbon monoxide is a dangerous gas because it",
     "combines with haemoglobin and stops oxygen transport", "it dissolves the lung tissue slowly in water", "it turns cold limewater milky white", "it is a strongly acidic gas in nature", "A",
     "CO binds haemoglobin about 200 times more strongly than oxygen does.", None),
    (T_NONMET, "Easy", "Carbon dioxide turns limewater",
     "milky", "blue", "red", "black", "A",
     "The cloudy precipitate of calcium carbonate is the test for carbon dioxide.", None),
    (T_NONMET, "Hard", "Ammonia gas cannot be dried using concentrated tetraoxosulphate(VI) acid because",
     "ammonia is a base and reacts with the acid", "ammonia is insoluble in acids", "the acid evaporates with ammonia", "ammonia is too light", "A",
     "NH₃ would be neutralised by the acid; it is dried with quicklime instead.", None),
    (T_NONMET, "Medium", "Chlorine gas in the laboratory bleaches damp (not dry) red litmus paper. This shows that chlorine bleaches by",
     "forming hypochlorous acid with the moisture", "directly attacking the dye molecules", "reducing the litmus paper chemically", "heating the damp paper strongly", "A",
     "Chlorine reacts with water to form the bleaching agent HOCl.", None),
    (T_NONMET, "Medium", "Ammonia is manufactured industrially by the",
     "Haber process", "Contact process", "Ostwald process", "Solvay process", "A",
     "N₂ and H₂ combine over iron in the Haber process.", None),
    (T_NONMET, "Easy", "The gas that is most soluble in water and gives a fountain experiment in the laboratory is",
     "ammonia", "nitrogen", "hydrogen", "methane", "A",
     "Ammonia's extreme solubility sucks water up the tube, producing the fountain.", None),
    (T_NONMET, "Hard", "Which gas is responsible for the depletion of the ozone layer?",
     "Chlorofluorocarbons", "Carbon dioxide", "Nitrogen", "Methane", "A",
     "CFC refrigerants release chlorine atoms that destroy ozone high in the atmosphere.", None),

    # ---------------------------------------------------------------- organic
    (T_ORG, "Easy", "The general molecular formula of the alkanes is",
     "CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙHₙ", "A",
     "Methane CH₄, ethane C₂H₆ and propane C₃H₈ follow CₙH₂ₙ₊₂.", None),
    (T_ORG, "Easy", "The alkene series is described as unsaturated because its members",
     "contain a carbon-carbon double bond", "contain only single bonds", "cannot burn", "are solids", "A",
     "The C=C double bond can open up and add other atoms, so the molecule is unsaturated.", None),
    (T_ORG, "Medium", "Which compound will decolourise bromine water rapidly?",
     "Ethene", "Ethane", "Methane", "Benzene under normal conditions", "A",
     "Ethene's double bond adds bromine, removing the reagent's colour instantly.", None),
    (T_ORG, "Medium", "How many structural isomers does butane, C₄H₁₀, have?",
     "2", "1", "3", "4", "A",
     "Butane exists as the straight chain and as 2-methylpropane.", "2"),
    (T_ORG, "Medium", "Members of the same homologous series have",
     "the same general formula and similar properties", "exactly the same molar mass always", "the same boiling point for all members", "different functional groups in the series", "A",
     "Each member differs from the next by −CH₂−, so properties vary gradually.", None),
    (T_ORG, "Hard", "Ethanol can be prepared industrially from glucose by the process of",
     "fermentation with yeast", "esterification", "cracking", "polymerisation", "A",
     "Yeast converts C₆H₁₂O₆ to ethanol and carbon dioxide at about 35°C.", None),
    (T_ORG, "Hard", "When ethanol is heated with concentrated H₂SO₄ at about 180°C, the organic product is",
     "ethene", "ethane", "ethanoic acid", "ethyl ethanoate", "A",
     "Concentrated sulphuric acid dehydrates ethanol, eliminating water to form ethene.", None),
    (T_ORG, "Hard", "Ethanoic acid reacts with ethanol in the presence of concentrated H₂SO₄ to form",
     "ethyl ethanoate and water", "ethene and water", "ethanol only", "soap and glycerol", "A",
     "This esterification produces the fruity-smelling ester ethyl ethanoate.", None),
    (T_ORG, "Medium", "The alkaline hydrolysis of an ester, used in soap making, is called",
     "saponification", "condensation", "substitution", "fermentation", "A",
     "Boiling fat with sodium hydroxide gives soap and glycerol: saponification.", None),
    (T_ORG, "Medium", "Polythene is manufactured by the process of",
     "addition polymerisation of ethene", "condensation of ethanol", "cracking of ethane", "esterification of acids", "A",
     "Thousands of ethene molecules join to form the long polythene chain.", None),
    (T_ORG, "Hard", "Which polymer is formed by condensation polymerisation?",
     "Nylon", "Polythene", "Polystyrene", "Polyvinyl chloride", "A",
     "Nylon forms from a diamine and a dicarboxylic acid, releasing water molecules.", None),
    (T_ORG, "Medium", "Cracking in the petroleum industry means",
     "breaking big hydrocarbon molecules into smaller ones", "boiling crude oil into useful fractions", "joining small molecules into plastics", "burning off the heavy oil residues", "A",
     "Cracking converts heavy fractions into petrol and useful alkenes.", None),
    (T_ORG, "Easy", "The functional group of the alkanols (alcohols) is",
     "the hydroxyl group, −OH", "the carboxyl group, −COOH", "the carbon-carbon double bond", "the ester linkage", "A",
     "Alcohols like ethanol and propanol carry the −OH group.", None),
    (T_ORG, "Medium", "Vinegar is a dilute solution of",
     "ethanoic acid", "ethanol", "ethyl ethanoate", "citric acid", "A",
     "Vinegar gets its sour taste and smell from about 5% ethanoic acid.", None),

    # ------------------------------------------------------- separation/lab
    (T_LAB, "Easy", "The best method for separating a suspension of chalk in water is",
     "filtration", "distillation", "evaporation", "chromatography", "A",
     "The insoluble chalk is trapped on the filter paper as the water passes.", None),
    (T_LAB, "Medium", "To obtain pure water from salt solution, the best method is",
     "distillation", "filtration", "decantation", "crystallisation", "A",
     "The water vaporises, condenses in the Liebig condenser and is collected pure.", None),
    (T_LAB, "Medium", "Common salt is obtained from its solution by",
     "evaporation to dryness", "filtration", "sublimation", "use of a separating funnel", "A",
     "The solvent is driven off, leaving the solid salt in the dish.", None),
    (T_LAB, "Medium", "The separation of pure iodine from a mixture of iodine and sand is best achieved by",
     "sublimation", "decantation", "distillation", "crystallisation", "A",
     "Iodine sublimes on gentle warming and deposits as crystals on a cold surface.", None),
    (T_LAB, "Hard", "In paper chromatography, the Rf value of a spot equals",
     "distance moved by the spot divided by distance moved by the solvent front", "distance moved by the solvent divided by spot distance", "spot distance times solvent distance", "the colour intensity of the spot", "A",
     "Rf values identify substances by comparing how far they travel.", None),
    (T_LAB, "Medium", "Crude oil is separated into fractions such as petrol and kerosene by",
     "fractional distillation", "filtration", "crystallisation", "sublimation", "A",
     "The fractions boil at different temperatures and condense at different levels.", None),
    (T_LAB, "Medium", "Which apparatus is used to deliver an exact volume of 25.0 cm³ of solution in a titration?",
     "Pipette", "Burette", "Measuring cylinder", "Beaker", "A",
     "The pipette delivers one fixed volume; the burette measures variable volumes added.", None),
    (T_LAB, "Easy", "Before smelling an unknown gas in the laboratory, you should",
     "waft a little of the gas towards your nose", "inhale deeply directly from the test tube", "taste a drop of it on the tongue", "heat the tube first in a flame", "A",
     "Wafting limits the amount inhaled in case the gas is irritating or poisonous.", None),
    (T_LAB, "Hard", "Which solution is used to test for the presence of chloride ions?",
     "Acidified silver nitrate", "Barium chloride", "Sodium hydroxide", "Lime water", "A",
     "A white precipitate of silver chloride that darkens in light confirms chloride.", None),
    (T_LAB, "Medium", "Which drying agent is suitable for drying ammonia gas?",
     "Quicklime (calcium oxide)", "Concentrated H₂SO₄", "Anhydrous calcium chloride", "Phosphorus(V) oxide", "A",
     "Only a basic drying agent leaves ammonia unreacted; acids absorb it.", None),
]

if __name__ == "__main__":
    build_batch(
        S,
        "batch_047_waec_chemistry.json",
        "batch_047_waec_chemistry",
        "WAEC/NECO Chemistry Paper 1, round 1: full SSCE syllabus - matter, atomic "
        "structure, periodicity, bonding, mole concept and stoichiometry, gas laws, "
        "solutions, water, electrolysis, rates and equilibrium, acids/bases/salts, redox, "
        "metals, non-metals, organic chemistry and separation techniques. All "
        "calculations machine-verified (molar volume 22.4 dm3 at s.t.p., F = 96,500 C).",
        PASSAGES,
        PQ,
        Q,
        exam_type="WAEC",
    )
