"""Batch 026 - Christian Religious Studies round 3, part B (the Gospels).

Birth and early life of Jesus, baptism and temptation, discipleship, miracles, parables, Sermon on the
Mount, mission of the disciples, great confession, transfiguration, triumphal entry and cleansing of the
temple, Last Supper, trials and death, resurrection and ascension, Jesus' teachings about Himself.
Scripture-based and application (scenario) items in the JAMB style.

    python3 scripts/build_content_batch26.py -> content/batch_026_crs_round3b.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Christian Religious Studies"

T_BIRTH = "The Birth and Early Life of Jesus"
T_BAPT = "The Baptism and Temptation of Jesus"
T_DISC = "Discipleship"
T_MIR = "Miracles"
T_PAR = "The Parables"
T_SERM = "The Sermon on the Mount"
T_MISS = "The Mission of the Disciples"
T_CONF = "The Great Confession"
T_TRANS = "The Transfiguration"
T_ENTRY = "The Triumphal Entry and the Cleansing of the Temple"
T_SUPPER = "The Last Supper"
T_TRIAL = "The Trials and the Death of Jesus"
T_RES = "Resurrection, Appearances and Ascension"
T_SELF = "Jesus' Teachings about Himself"

PASSAGES = []
PQ = []

Q = [
    # ---------------- The Birth and Early Life of Jesus ----------------
    (T_BIRTH, "Medium", "When Mary asked the angel, 'How can this be, since I have no husband?' Gabriel replied that",
     "the Holy Spirit would come upon her and the child would be called the Son of God",
     "Joseph would become the father of the child after their wedding",
     "she should go to Bethlehem and wait for a sign from the priests",
     "her cousin Elizabeth would explain the mystery to her",
     "A", "Luke 1:34-35: 'The Holy Spirit will come upon you, and the power of the Most High will overshadow you.'"),
    (T_BIRTH, "Medium", "Joseph, being a just man and unwilling to put Mary to shame, resolved to divorce her quietly, but changed his mind because",
     "an angel told him in a dream that the child was conceived of the Holy Spirit",
     "Mary's parents paid him a large sum of money to keep the marriage",
     "the elders of Nazareth ordered him to complete the marriage",
     "Elizabeth came from Judea to plead on Mary's behalf",
     "A", "Matthew 1:19-21: the angel said, 'Do not fear to take Mary your wife, for that which is conceived in her is of the Holy Spirit.'"),
    (T_BIRTH, "Medium", "Mary's song, 'He has put down the mighty from their thrones, and exalted those of low degree; he has filled the hungry with good things, and the rich he has sent empty away,' shows that the coming of Jesus would",
     "overturn human standards of power and wealth",
     "make Israel the richest nation on earth",
     "restore the throne of Herod to the family of David",
     "bring prosperity mainly to the priests in Jerusalem",
     "A", "Luke 1:46-55 (the Magnificat): God's salvation lifts the humble and humbles the proud."),
    (T_BIRTH, "Medium", "Jesus was born in Bethlehem rather than Nazareth because",
     "Joseph went there to be enrolled in the census decreed by Caesar Augustus",
     "Herod had ordered all descendants of David to live in Bethlehem",
     "Mary's parents lived in Bethlehem and wanted her near them",
     "the wise men had told Joseph to go there",
     "A", "Luke 2:1-5: Joseph went to Bethlehem, the city of David, to be enrolled with Mary, fulfilling Micah 5:2."),
    (T_BIRTH, "Medium", "The angel's message to the shepherds was 'good news of a great joy which will come to all the people'. The fact that it came first to shepherds shows that",
     "the gospel is for the humble and lowly, not just the powerful",
     "the shepherds were priests who served in the temple",
     "Bethlehem had no other inhabitants at the time",
     "the angels could not find the palace of Herod",
     "A", "Luke 2:8-14: shepherds were poor and of low social standing, yet they were the first to hear of the Saviour's birth."),
    (T_BIRTH, "Medium", "Herod told the wise men, 'Go and search diligently for the child, and when you have found him bring me word, that I too may come and worship him.' His real intention was to",
     "find the child and kill him",
     "offer the child gifts of gold, frankincense and myrrh",
     "adopt the child as his heir",
     "send the child to be educated in Rome",
     "A", "Matthew 2:8, 13, 16: warned in a dream, the wise men did not return, and Herod killed all the boys in Bethlehem aged two and under."),
    (T_BIRTH, "Medium", "A politician publicly praises a rival while secretly plotting to destroy him. His conduct resembles that of",
     "Herod towards the infant Jesus",
     "Simeon towards the child in the temple",
     "the shepherds towards Mary and Joseph",
     "Zechariah towards his son John",
     "A", "Matthew 2:7-8: Herod's pretended desire to worship masked a plan to murder the child."),
    (T_BIRTH, "Medium", "When Jesus' parents found him in the temple after three days, he said, 'Did you not know that I must be in my Father's house?' This shows that at twelve Jesus",
     "was already aware of his unique relationship with God",
     "had decided to leave his parents and live with the priests",
     "was rebuking his parents for going to the Passover",
     "had been adopted by the teachers of the law",
     "A", "Luke 2:49: Jesus' words reveal his consciousness of God as his Father; yet he went home and was obedient to his parents."),
    (T_BIRTH, "Medium", "After the incident in the temple, Jesus 'went down with them and came to Nazareth, and was obedient to them; and Jesus increased in wisdom and in stature, and in favour with God and man'. A teenager who feels that being religious frees him from obeying his parents should learn from this that",
     "obedience to parents is part of growing in favour with God",
     "Jesus obeyed only because he was too young to leave home",
     "wisdom is gained by staying in the temple rather than at home",
     "parents should not question children about religious matters",
     "A", "Luke 2:51-52: Jesus, though conscious of his divine sonship, submitted to his earthly parents."),
    (T_BIRTH, "Medium", "The prophetess Anna, who was at the temple when Jesus was presented, responded by",
     "giving thanks to God and speaking of the child to all who were looking for redemption",
     "warning Mary that Herod was seeking to kill the child",
     "asking Joseph to leave the child in the temple to be trained",
     "offering the pair of turtledoves required by the law",
     "A", "Luke 2:36-38: Anna, a widow of eighty-four, gave thanks and spoke of him to all who waited for the redemption of Jerusalem."),

    # ---------------- The Baptism and Temptation of Jesus ----------------
    (T_BAPT, "Medium", "John tried to prevent Jesus from being baptised, saying, 'I need to be baptised by you.' Jesus insisted because",
     "it was fitting for him to fulfil all righteousness",
     "he had sins that needed to be washed away",
     "he wanted to become one of John's disciples",
     "the crowd expected every teacher to be baptised",
     "A", "Matthew 3:14-15: Jesus, though sinless, identified himself with the people he came to save."),
    (T_BAPT, "Medium", "Immediately after his baptism, Jesus was led by the Spirit into the wilderness to be tempted. This sequence shows that",
     "spiritual high points may be followed by severe testing",
     "the Spirit was punishing Jesus for being baptised",
     "Jesus had lost the approval God gave him at the Jordan",
     "the devil has authority over those who are baptised",
     "A", "Matthew 4:1: the same Spirit who descended at the baptism led Jesus into the wilderness; testing followed the declaration of sonship."),
    (T_BAPT, "Medium", "In the temptation to turn stones into bread, the devil was urging Jesus to",
     "use his divine power to satisfy his own needs apart from God's will",
     "feed the crowds of Galilee so that they would make him king",
     "prove that he could survive without any food at all",
     "reject the Passover bread and eat ordinary bread instead",
     "A", "Matthew 4:3-4: Jesus answered, 'Man shall not live by bread alone, but by every word that proceeds from the mouth of God.'"),
    (T_BAPT, "Medium", "On the pinnacle of the temple the devil quoted Psalm 91, 'He will give his angels charge of you.' Jesus replied, 'You shall not tempt the Lord your God,' teaching that",
     "scripture must not be twisted to justify testing God with reckless acts",
     "the Psalms are not part of God's inspired word",
     "angels no longer protect the people of God",
     "the temple was not a holy place",
     "A", "Matthew 4:5-7: Jesus refused to demand a spectacular sign from God, using scripture rightly against scripture misused."),
    (T_BAPT, "Medium", "A church member says, 'God will protect me, so I will drive at top speed without a seat belt.' His attitude is like the temptation Jesus rejected when he said,",
     "'You shall not tempt the Lord your God.'",
     "'Man shall not live by bread alone.'",
     "'You shall worship the Lord your God and him only shall you serve.'",
     "'Get behind me, Satan!'",
     "A", "Matthew 4:7: deliberately courting danger and expecting God to intervene is putting God to the test."),
    (T_BAPT, "Medium", "The devil offered Jesus all the kingdoms of the world if he would fall down and worship him. This temptation was to",
     "gain his rightful kingship by a short cut that avoided the cross",
     "become the governor of Judea under the Roman emperor",
     "abandon Galilee and preach only in foreign lands",
     "share his authority equally with the devil",
     "A", "Matthew 4:8-10: the devil offered glory without suffering; Jesus chose the way of obedience to the Father."),
    (T_BAPT, "Medium", "In each of the three temptations Jesus answered the devil with",
     "a quotation from the book of Deuteronomy",
     "a miracle that proved he was the Son of God",
     "a command to the angels to drive the devil away",
     "a promise to obey the devil after his ministry ended",
     "A", "Matthew 4:4, 7, 10 quote Deuteronomy 8:3, 6:16 and 6:13; Jesus overcame with the written word of God."),
    (T_BAPT, "Medium", "A candidate is offered examination answers by a friend and refuses, saying, 'I would rather fail honestly.' His refusal reflects the principle Jesus applied when he rejected",
     "the offer of the kingdoms of the world in exchange for worshipping the devil",
     "John's attempt to prevent him from being baptised",
     "Peter's request to build three booths on the mountain",
     "the crowd's attempt to make him king by force",
     "A", "Matthew 4:8-10: like Jesus, the student refuses to gain a good end by a wrong means."),
    (T_BAPT, "Medium", "Luke notes that after the temptations the devil 'departed from him until an opportune time'. This suggests that",
     "temptation is not defeated once for all but returns at other moments in life",
     "the devil was completely destroyed in the wilderness",
     "Jesus would never face any further testing",
     "the devil had become one of Jesus' followers",
     "A", "Luke 4:13: the devil returned in other forms, for instance through Peter (Matthew 16:23) and at Gethsemane."),

    # ---------------- Discipleship ----------------
    (T_DISC, "Medium", "When Jesus told Simon to put out into the deep and let down the nets, Simon said, 'Master, we toiled all night and took nothing! But at your word I will let down the nets.' This shows that discipleship requires",
     "obedience to the word of Jesus even against one's own experience",
     "fishing skill that can be used for the service of God",
     "working at night rather than during the day",
     "waiting until the evidence is clear before acting",
     "A", "Luke 5:4-6: Simon obeyed despite a fruitless night, and the nets nearly broke with fish."),
    (T_DISC, "Medium", "Seeing the great catch of fish, Simon Peter fell at Jesus' knees and said, 'Depart from me, for I am a sinful man, O Lord.' Jesus responded,",
     "'Do not be afraid; henceforth you will be catching men.'",
     "'Get behind me, Satan! You are a hindrance to me.'",
     "'O man of little faith, why did you doubt?'",
     "'Foxes have holes, and birds of the air have nests.'",
     "A", "Luke 5:8-11: rather than leave him, Jesus called Peter to a new task, and the fishermen left everything and followed him."),
    (T_DISC, "Medium", "To the man who said, 'Lord, let me first go and bury my father,' Jesus replied, 'Leave the dead to bury their own dead; but as for you, go and proclaim the kingdom of God.' Jesus was teaching that",
     "the call of the kingdom takes priority over every other claim, however legitimate",
     "Christians should not attend the funerals of their relatives",
     "the man's father was still alive and did not need burial",
     "only priests were permitted to bury the dead in Israel",
     "A", "Luke 9:59-60: the demands of discipleship are urgent and must not be postponed indefinitely for family duties."),
    (T_DISC, "Medium", "Jesus said, 'No one who puts his hand to the plough and looks back is fit for the kingdom of God.' A convert who keeps longing for his former life of crime is",
     "like the ploughman who looks back and cannot plough a straight furrow",
     "a good example of the total commitment Jesus demanded",
     "like Peter, who left his nets to follow Jesus",
     "like Zacchaeus, who restored fourfold what he had taken",
     "A", "Luke 9:62: single-minded commitment is required; divided loyalty makes a disciple unfit for kingdom service."),
    (T_DISC, "Medium", "Jesus told the rich young ruler, 'Sell what you possess and give to the poor... and come, follow me,' because",
     "his wealth stood between him and wholehearted devotion to God",
     "the disciples needed money to fund their mission",
     "poverty is required of every person who follows Jesus",
     "the young man had gained his riches by fraud",
     "A", "Matthew 19:21-22: the man went away sorrowful because he had great possessions; his riches were his real master."),
    (T_DISC, "Medium", "When the Pharisees asked why Jesus ate with tax collectors and sinners, he replied,",
     "'Those who are well have no need of a physician, but those who are sick.'",
     "'Render to Caesar the things that are Caesar's.'",
     "'The Sabbath was made for man, not man for the Sabbath.'",
     "'Let him who is without sin among you be the first to throw a stone.'",
     "A", "Mark 2:15-17: Jesus called Levi the tax collector and defended eating with sinners, whom he came to call."),
    (T_DISC, "Medium", "Jesus warned would-be disciples to count the cost, like a man who intends to build a tower or a king going to war. The point is that",
     "one should consider seriously what following Jesus demands before committing",
     "only wealthy people who can afford towers should become disciples",
     "Christians should prepare for physical warfare against unbelievers",
     "discipleship can be abandoned whenever it becomes costly",
     "A", "Luke 14:28-33: 'whoever of you does not renounce all that he has cannot be my disciple'."),
    (T_DISC, "Medium", "A student who publicly identifies as a Christian in a hostile hostel and accepts mockery for it is fulfilling Jesus' word that a disciple must",
     "deny himself, take up his cross daily and follow him",
     "hide his faith until conditions become favourable",
     "leave school and join a monastery",
     "avoid contact with unbelievers altogether",
     "A", "Luke 9:23: bearing the cross means accepting shame and suffering for the sake of Christ."),
    (T_DISC, "Medium", "Jesus said, 'If any one comes to me and does not hate his own father and mother... yes, and even his own life, he cannot be my disciple.' By 'hate' he meant that",
     "love for him must so far exceed every other love that others seem like hatred by comparison",
     "disciples must break off all relations with their families",
     "family members are the chief enemies of the kingdom of God",
     "disciples should neglect the care of their aged parents",
     "A", "Luke 14:26: a Semitic idiom for 'love less'; Jesus elsewhere commanded honour for parents (Mark 7:9-13)."),

    # ---------------- Miracles ----------------
    (T_MIR, "Medium", "Before healing the paralytic lowered through the roof, Jesus said, 'My son, your sins are forgiven,' and the scribes objected. Jesus then healed the man in order to",
     "show that the Son of man has authority on earth to forgive sins",
     "prove that the man's paralysis was caused by his own sin",
     "reward the four friends for their hard work",
     "punish the scribes for their unbelief",
     "A", "Mark 2:5-12: the visible healing confirmed the invisible authority to forgive sins."),
    (T_MIR, "Medium", "The woman with the flow of blood touched Jesus' garment secretly, but Jesus insisted on finding out who had touched him because",
     "he wanted her to receive not only healing but also open assurance of faith and peace",
     "he intended to rebuke her for making him ceremonially unclean",
     "he wanted to know who had stolen from him in the crowd",
     "the disciples had asked him to identify the thief",
     "A", "Mark 5:25-34: 'Daughter, your faith has made you well; go in peace, and be healed of your disease.'"),
    (T_MIR, "Medium", "When Jairus was told, 'Your daughter is dead. Why trouble the Teacher any further?' Jesus said to him,",
     "'Do not fear, only believe.'",
     "'Your faith has made you well; go in peace.'",
     "'Why are you afraid? Have you no faith?'",
     "'Talitha cumi', which means 'Little girl, arise'.",
     "A", "Mark 5:35-36: Jesus encouraged the ruler to keep faith in the face of death and then raised the girl."),
    (T_MIR, "Medium", "When the disciples wanted to send the crowd away to buy food, Jesus said, 'You give them something to eat,' and then fed five thousand with five loaves and two fish. This teaches that",
     "Jesus can multiply the little we offer to meet the needs of many",
     "disciples should never carry food when travelling",
     "large crowds should be dispersed before evening",
     "bread and fish are the only foods Christians should eat",
     "A", "Mark 6:35-44: the disciples' small resources, placed in Jesus' hands, fed the multitude with twelve baskets left over."),
    (T_MIR, "Medium", "At the pool of Bethzatha Jesus asked a man who had been ill for thirty-eight years, 'Do you want to be healed?' The man complained that he had no one to put him into the pool. Jesus",
     "healed him with a word on the Sabbath without using the pool at all",
     "carried him into the pool when the water was troubled",
     "told him to wait for an angel to come and heal him",
     "asked his disciples to lift him into the pool",
     "A", "John 5:5-9: 'Rise, take up your pallet, and walk'; the healing led to conflict because it was the Sabbath."),
    (T_MIR, "Medium", "The blind man healed in John 9 said to the Pharisees, 'One thing I know, that though I was blind, now I see.' His answer illustrates that",
     "personal experience of Christ's power is a testimony that arguments cannot overturn",
     "blind people should not be questioned by religious leaders",
     "the man did not know who had healed him",
     "the Pharisees had healed him themselves",
     "A", "John 9:24-25: the man could not settle theological debates but he could not deny what Jesus had done for him."),
    (T_MIR, "Medium", "A Christian who is asked to break the law by his employer replies, 'God who healed my child can also find me another job.' His confidence resembles that of the centurion who told Jesus,",
     "'Only say the word, and my servant will be healed.'",
     "'Lord, if you had been here, my brother would not have died.'",
     "'Depart from me, for I am a sinful man, O Lord.'",
     "'Lord, I believe; help my unbelief!'",
     "A", "Matthew 8:8-10: the centurion trusted the authority of Jesus' word alone, and Jesus marvelled at such faith."),
    (T_MIR, "Medium", "The Gerasene demoniac, once healed, begged to go with Jesus, but Jesus told him,",
     "'Go home to your friends, and tell them how much the Lord has done for you.'",
     "'Follow me, and I will make you a fisher of men.'",
     "'See that you say nothing to any one.'",
     "'Come and see where I am staying.'",
     "A", "Mark 5:18-20: the healed man became a witness in the Decapolis, in contrast to others whom Jesus told to keep silent."),
    (T_MIR, "Medium", "When the ruler of the synagogue was indignant that Jesus healed a crippled woman on the Sabbath, Jesus called him a hypocrite because",
     "he would untie his ox or ass on the Sabbath to water it but objected to a daughter of Abraham being loosed",
     "he had healed people himself on the Sabbath in previous years",
     "the woman was his own relative and he had refused to help her",
     "he had invited Jesus to the synagogue specifically to heal her",
     "A", "Luke 13:10-17: Jesus exposed the inconsistency of caring for animals on the Sabbath while denying relief to a suffering person."),
    (T_MIR, "Medium", "The raising of the widow's son at Nain was prompted by",
     "Jesus' compassion when he saw the weeping mother",
     "the request of the elders of the town",
     "the faith of the widow, who touched his garment",
     "the disciples' desire to see a sign",
     "A", "Luke 7:11-15: 'When the Lord saw her, he had compassion on her and said to her, Do not weep.'"),

    # ---------------- The Parables ----------------
    (T_PAR, "Medium", "In the parable of the sower, the seed sown on rocky ground represents those who",
     "receive the word with joy but fall away when tribulation comes because they have no root",
     "hear the word but the cares of the world and the delight in riches choke it",
     "hear the word and immediately the evil one snatches it away",
     "hear the word, understand it and bear fruit a hundredfold",
     "A", "Matthew 13:20-21: shallow enthusiasm without depth cannot survive persecution."),
    (T_PAR, "Medium", "A church member who receives the word gladly but abandons the faith the moment his family opposes him is like the seed sown",
     "on rocky ground, where it sprang up quickly but withered in the sun",
     "along the path, where the birds came and devoured it",
     "among thorns, which grew up and choked it",
     "on good soil, where it brought forth grain",
     "A", "Matthew 13:5-6, 20-21: no root means no endurance under pressure."),
    (T_PAR, "Medium", "In the parable of the weeds, the householder told his servants not to gather the weeds before the harvest because",
     "in gathering the weeds they might root up the wheat along with them",
     "the weeds would eventually turn into wheat if left alone",
     "the enemy who sowed them would return and remove them",
     "the servants were too tired to work in the field",
     "A", "Matthew 13:24-30: final separation of the righteous and the wicked belongs to God at the close of the age."),
    (T_PAR, "Medium", "A pastor decides to expel every member he suspects of secret sin. The parable of the weeds cautions him that",
     "judgment and separation belong to God at the harvest, and hasty uprooting harms the wheat",
     "the church should contain only perfect people",
     "weeds should be pulled up as soon as they are noticed",
     "the enemy has no power to sow weeds among the wheat",
     "A", "Matthew 13:29-30, 36-43: the Son of man will send his angels to gather out of his kingdom all causes of sin at the end."),
    (T_PAR, "Medium", "In the parable of the labourers in the vineyard, those hired at the eleventh hour received the same wage as those hired first. The parable teaches that",
     "God's generosity in the kingdom is not measured by human ideas of merit",
     "employers should pay all workers exactly the same regardless of hours",
     "latecomers to the faith will have a higher place in heaven",
     "the first labourers were cheated by a dishonest householder",
     "A", "Matthew 20:1-16: 'Do you begrudge my generosity?... So the last will be first, and the first last.'"),
    (T_PAR, "Medium", "In the parable of the wise and foolish maidens, the foolish ones were shut out because",
     "they took no oil with their lamps and were absent buying some when the bridegroom came",
     "they fell asleep while the wise maidens stayed awake",
     "they refused to share their oil with the others",
     "they arrived at the feast before the bridegroom",
     "A", "Matthew 25:1-13: all ten slept, but only the wise were prepared; 'Watch therefore, for you know neither the day nor the hour.'"),
    (T_PAR, "Medium", "In the parable of the sheep and the goats, the King says, 'As you did it to one of the least of these my brethren, you did it to me.' The parable teaches that",
     "practical care for the needy is treated as service rendered to Christ himself",
     "sheep are more valuable than goats in the eyes of God",
     "only those who preach the gospel will enter the kingdom",
     "the final judgment is based on the number of prayers said",
     "A", "Matthew 25:31-46: feeding the hungry, welcoming strangers, clothing the naked and visiting the sick and imprisoned are the marks of the righteous."),
    (T_PAR, "Medium", "A student says she loves Jesus but ignores a hungry classmate sitting beside her every day. The parable of the sheep and the goats warns that",
     "neglect of the needy is counted as neglect of Christ himself",
     "her love for Jesus is enough since she did nothing wrong",
     "feeding classmates is the duty of the school and not of students",
     "only the rich are expected to help those in need",
     "A", "Matthew 25:45: 'As you did it not to one of the least of these, you did it not to me.'"),
    (T_PAR, "Medium", "In the parable of the rich man and Lazarus, Abraham refused to send Lazarus to warn the rich man's brothers because",
     "they had Moses and the prophets, and would not be convinced even if someone rose from the dead",
     "Lazarus was too weak from his sores to make the journey",
     "the brothers had already died and joined the rich man",
     "the great chasm made it impossible for anyone to leave paradise",
     "A", "Luke 16:27-31: those who ignore the scriptures will not be persuaded by miracles."),
    (T_PAR, "Medium", "The parable of the two sons, one who said 'I will not' but later went to the vineyard and one who said 'I go, sir' but did not, was told to show that",
     "tax collectors and harlots who repented were entering the kingdom before the religious leaders who only professed obedience",
     "sons should always obey their fathers immediately without argument",
     "the first son was punished for his rude answer",
     "vineyard work was reserved for the eldest son",
     "A", "Matthew 21:28-32: actual obedience matters more than verbal profession."),
    (T_PAR, "Medium", "A church officer promises to organise the youth camp, does nothing, and later criticises a reluctant member who eventually did the work. According to the parable of the two sons, the one who did the father's will was",
     "the reluctant member who at first refused but later did the work",
     "the officer who made the promise in front of everyone",
     "neither of them, since both showed a wrong attitude",
     "both equally, since intentions count as much as actions",
     "A", "Matthew 21:31: 'Which of the two did the will of his father?' They said, 'The first.'"),
    (T_PAR, "Medium", "In the parable of the wicked tenants, the owner finally sent his son, saying, 'They will respect my son.' The tenants killed him. The parable pointed to",
     "the rejection and killing of Jesus by the leaders of Israel after they had rejected the prophets",
     "the failure of the Roman governors to protect Jewish farmers",
     "the destruction of the vineyards of Galilee by the Samaritans",
     "the need for landlords to collect rent in person",
     "A", "Mark 12:1-12: the chief priests perceived that he had told the parable against them."),

    # ---------------- The Sermon on the Mount ----------------
    (T_SERM, "Medium", "Jesus said, 'You are the salt of the earth; but if salt has lost its taste, how shall its saltness be restored?' A Christian who behaves exactly like his corrupt colleagues is",
     "salt that has lost its taste and is good for nothing",
     "a lamp placed on a stand to give light to the house",
     "a city set on a hill that cannot be hid",
     "salt that preserves society from decay",
     "A", "Matthew 5:13: disciples who lose their distinctive character lose their usefulness to the world."),
    (T_SERM, "Medium", "Jesus said, 'Think not that I have come to abolish the law and the prophets; I have come not to abolish them but to fulfil them.' He then taught that anger and lust break the commandments against murder and adultery. This shows that Jesus",
     "required a righteousness that goes deeper than outward acts to the heart",
     "abolished the Ten Commandments for his followers",
     "regarded murder and adultery as minor offences",
     "wanted the scribes to add more rules to the law",
     "A", "Matthew 5:17-28: 'Unless your righteousness exceeds that of the scribes and Pharisees, you will never enter the kingdom of heaven.'"),
    (T_SERM, "Medium", "Jesus said, 'If you are offering your gift at the altar, and there remember that your brother has something against you, leave your gift there before the altar and go; first be reconciled to your brother.' A choir member who refuses to speak to another member but still sings every Sunday should",
     "seek reconciliation first, because broken relationships hinder acceptable worship",
     "continue singing, since worship is more important than relationships",
     "leave the choir permanently until the other member apologises",
     "report the matter to the pastor and wait for judgment",
     "A", "Matthew 5:23-24: God values reconciliation with one's brother above religious offerings."),
    (T_SERM, "Medium", "Jesus taught, 'Let what you say be simply Yes or No; anything more than this comes from evil.' This teaches that Christians should",
     "be so truthful that oaths are unnecessary",
     "never appear in court to give evidence",
     "swear only by heaven and not by earth",
     "answer every question with a single word",
     "A", "Matthew 5:33-37: a disciple's plain word should be as reliable as a sworn oath."),
    (T_SERM, "Medium", "'If any one strikes you on the right cheek, turn to him the other also.' Jesus was teaching his followers to",
     "renounce personal revenge and overcome evil with generosity",
     "provoke their enemies until they strike again",
     "avoid ever defending the weak against injustice",
     "report every assault to the Roman authorities",
     "A", "Matthew 5:38-42: the principle 'an eye for an eye' was replaced by non-retaliation and readiness to give."),
    (T_SERM, "Medium", "Jesus commanded, 'Love your enemies and pray for those who persecute you, so that you may be sons of your Father who is in heaven; for he makes his sun rise on the evil and on the good.' The reason given for loving enemies is that",
     "it reflects the impartial goodness of God the Father",
     "enemies will always become friends if they are loved",
     "the Roman law required Jews to love their oppressors",
     "loving enemies earns a place among the Pharisees",
     "A", "Matthew 5:44-48: children resemble their Father, who shows kindness to the just and the unjust alike."),
    (T_SERM, "Medium", "A businessman announces his donation to the church over the loudspeaker so that everyone will applaud. Jesus warned that such givers",
     "have already received their reward",
     "will receive a double reward from the Father",
     "should give even more to gain approval",
     "are the salt of the earth",
     "A", "Matthew 6:1-4: 'When you give alms, sound no trumpet before you, as the hypocrites do... they have received their reward.'"),
    (T_SERM, "Medium", "In the Lord's Prayer the petition 'forgive us our debts, as we also have forgiven our debtors' is followed by the warning that",
     "if you do not forgive men their trespasses, neither will your Father forgive your trespasses",
     "debts must be repaid in full before prayer can be heard",
     "only debts owed to fellow Christians need to be forgiven",
     "God forgives without any condition whatever a person does",
     "A", "Matthew 6:12, 14-15: receiving God's forgiveness is bound up with extending forgiveness to others."),
    (T_SERM, "Medium", "'Do not lay up for yourselves treasures on earth, where moth and rust consume and where thieves break in and steal... For where your treasure is, there will your heart be also.' Jesus was teaching that",
     "what a person values most determines the direction of his heart and life",
     "Christians should not own houses, land or savings of any kind",
     "money should be hidden where thieves cannot find it",
     "earthly wealth is a sure sign of God's blessing",
     "A", "Matthew 6:19-21, 24: 'You cannot serve God and mammon.'"),
    (T_SERM, "Medium", "'Look at the birds of the air: they neither sow nor reap nor gather into barns, and yet your heavenly Father feeds them.' Jesus said this to teach his disciples",
     "not to be anxious about food and clothing but to seek first the kingdom of God",
     "that work is unnecessary because God feeds those who trust him",
     "that farming is a less spiritual occupation than fishing",
     "that birds are more valuable than human beings",
     "A", "Matthew 6:25-34: 'Seek first his kingdom and his righteousness, and all these things shall be yours as well.'"),
    (T_SERM, "Medium", "Jesus said, 'Not every one who says to me, Lord, Lord, shall enter the kingdom of heaven, but he who does the will of my Father.' He compared those who hear his words and do them to",
     "a wise man who built his house upon the rock",
     "a foolish man who built his house upon the sand",
     "a lamp hidden under a bushel",
     "a tree that bears evil fruit",
     "A", "Matthew 7:21-27: the house on the rock withstood rain, floods and wind because it was founded on obedience."),
    (T_SERM, "Medium", "'Enter by the narrow gate; for the gate is wide and the way is easy that leads to destruction.' Jesus meant that",
     "the way of true discipleship is demanding and followed by few",
     "Christians should build narrow gates at their homes",
     "large churches are always on the way to destruction",
     "salvation is impossible for most people",
     "A", "Matthew 7:13-14: 'The gate is narrow and the way is hard that leads to life, and those who find it are few.'"),

    # ---------------- The Mission of the Disciples ----------------
    (T_MISS, "Medium", "Jesus sent out the twelve with the instruction, 'Preach as you go, saying, The kingdom of heaven is at hand. Heal the sick, raise the dead, cleanse lepers, cast out demons. You received without pay, give without pay.' The last sentence forbids",
     "turning the ministry of healing and preaching into a means of making money",
     "accepting food and lodging from those who received the message",
     "healing people who could not pay the temple tax",
     "preaching to people who had not first paid the disciples",
     "A", "Matthew 10:7-8: the gifts of the kingdom were freely received and must be freely given."),
    (T_MISS, "Medium", "A preacher charges a fixed fee before he will pray for the sick. He violates the principle Jesus gave when he said,",
     "'You received without pay, give without pay.'",
     "'The labourer deserves his food.'",
     "'Shake off the dust from your feet.'",
     "'Be wise as serpents and innocent as doves.'",
     "A", "Matthew 10:8: healing is a gift of God's grace and must not be sold."),
    (T_MISS, "Medium", "Jesus told the disciples to take no gold, silver or copper, no bag, no two tunics, no sandals or staff, 'for the labourer deserves his food'. This meant that they should",
     "depend on God's provision through the hospitality of those they served",
     "beg for money from door to door in every town",
     "expect to starve as a sign of their devotion",
     "carry only what they could steal from unbelievers",
     "A", "Matthew 10:9-11: travelling light expressed trust in God and urgency in the mission."),
    (T_MISS, "Medium", "Jesus instructed the disciples that if any town would not receive them or listen to their words, they should",
     "shake off the dust from their feet as they left that town",
     "call down fire from heaven to destroy it",
     "remain there until the people repented",
     "report the town to the Roman governor",
     "A", "Matthew 10:14: the gesture was a solemn testimony that the town had rejected the message and was responsible for its choice."),
    (T_MISS, "Medium", "Jesus warned, 'Behold, I send you out as sheep in the midst of wolves; so be wise as serpents and innocent as doves.' He meant that the disciples should be",
     "prudent in dealing with danger while remaining pure in motive and conduct",
     "aggressive towards their opponents like a serpent striking",
     "silent and passive like sheep being led to slaughter",
     "cunning enough to deceive those who threatened them",
     "A", "Matthew 10:16: wisdom without harm; prudence without dishonesty."),
    (T_MISS, "Medium", "When the seventy returned with joy, saying, 'Lord, even the demons are subject to us in your name!' Jesus told them to",
     "rejoice rather that their names were written in heaven",
     "keep the power secret until after the resurrection",
     "return to the villages and cast out more demons",
     "demand payment from those they had delivered",
     "A", "Luke 10:17-20: the greatest cause for joy is salvation itself, not spectacular power."),
    (T_MISS, "Medium", "Jesus told the disciples, 'When they deliver you up, do not be anxious how you are to speak or what you are to say... for it is not you who speak, but the Spirit of your Father speaking through you.' This promise concerned",
     "help in bearing witness when brought before councils and rulers",
     "the writing of the gospels many years later",
     "speaking in foreign tongues at Pentecost",
     "preaching the Sermon on the Mount",
     "A", "Matthew 10:17-20: persecution would give opportunity for testimony, and the Spirit would supply the words."),
    (T_MISS, "Medium", "A missionary moves on from a village that repeatedly drives him out, instead of forcing himself on the people, and later returns when invited. He is following Jesus' instruction to",
     "shake off the dust from his feet and leave a town that will not receive him",
     "stay in one house and not move from house to house",
     "take neither bag nor money for the journey",
     "greet no one on the road",
     "A", "Matthew 10:14 and Luke 10:10-11: the disciples were not to compel acceptance but to move on with a solemn witness."),

    # ---------------- The Great Confession ----------------
    (T_CONF, "Medium", "When Jesus asked, 'Who do men say that the Son of man is?' the disciples reported that people said he was",
     "John the Baptist, Elijah, Jeremiah or one of the prophets",
     "the Messiah, the Son of the living God",
     "a carpenter's son from Nazareth and nothing more",
     "Beelzebul, the prince of demons",
     "A", "Matthew 16:13-14: popular opinion honoured Jesus as a prophet but fell short of recognising him as the Christ."),
    (T_CONF, "Medium", "Jesus told Peter, 'Blessed are you, Simon Bar-Jona! For flesh and blood has not revealed this to you, but my Father who is in heaven.' This shows that",
     "true recognition of Jesus as the Christ comes by divine revelation",
     "Peter had studied the scriptures more than the other disciples",
     "Peter's father Jonah had told him who Jesus was",
     "the confession was a lucky guess that Jesus rewarded",
     "A", "Matthew 16:17: Peter's insight was a gift from the Father, not a human deduction."),
    (T_CONF, "Medium", "After Peter's confession Jesus charged the disciples to tell no one that he was the Christ, because",
     "the people expected a political Messiah and would misunderstand his mission",
     "he was not yet certain that he was the Messiah",
     "the disciples might be arrested immediately by Herod",
     "only the high priest was permitted to announce the Messiah",
     "A", "Matthew 16:20-21: from that time he began to teach that he must suffer, die and rise, correcting their expectations."),
    (T_CONF, "Medium", "When Jesus foretold his suffering and death, Peter rebuked him, saying, 'God forbid, Lord! This shall never happen to you.' Jesus replied, 'Get behind me, Satan!' because Peter was",
     "on the side of men, not of God, in opposing the way of the cross",
     "secretly plotting with the chief priests against Jesus",
     "possessed by an evil spirit at that moment",
     "trying to take the leadership of the disciples from Jesus",
     "A", "Matthew 16:22-23: Peter's love expressed the same temptation the devil offered - glory without suffering."),
    (T_CONF, "Medium", "A church member advises his pastor to stop preaching against a powerful politician 'so that trouble does not come to you'. His well-meant advice resembles",
     "Peter's rebuke of Jesus after the great confession",
     "Peter's confession that Jesus is the Christ",
     "James and John's request to sit at Jesus' right and left",
     "Thomas' demand to see the nail prints",
     "A", "Matthew 16:22-23: avoiding suffering at the cost of God's will is a temptation even when it comes from a friend."),
    (T_CONF, "Medium", "Immediately after the great confession, Jesus said, 'If any man would come after me, let him deny himself and take up his cross and follow me. For whoever would save his life will lose it.' This linked Peter's confession to",
     "the cost of following a Messiah whose path led to the cross",
     "the promise that the disciples would never suffer",
     "the building of a church on the rock of Caesarea Philippi",
     "the immediate establishment of an earthly kingdom",
     "A", "Matthew 16:24-26: confessing Christ means sharing his way of self-denial and suffering."),
    (T_CONF, "Medium", "The great confession took place in the district of",
     "Caesarea Philippi",
     "Capernaum by the sea",
     "Bethany near Jerusalem",
     "Nazareth in Galilee",
     "A", "Matthew 16:13: 'When Jesus came into the district of Caesarea Philippi, he asked his disciples...'"),
    (T_CONF, "Hard", "Jesus said to Peter, 'I will give you the keys of the kingdom of heaven, and whatever you bind on earth shall be bound in heaven.' In Acts, Peter used this authority when he",
     "opened the door of faith to the Jews at Pentecost and to the Gentiles at the house of Cornelius",
     "refused to allow the Gentiles to be baptised without circumcision",
     "closed the temple in Jerusalem to all non-Jewish worshippers",
     "appointed himself high priest in place of Caiaphas",
     "A", "Matthew 16:19; Acts 2 and 10: Peter's preaching admitted first Jews and then Gentiles into the church."),

    # ---------------- The Transfiguration ----------------
    (T_TRANS, "Medium", "The three disciples Jesus took up the mountain of transfiguration were",
     "Peter, James and John",
     "Peter, Andrew and Philip",
     "James, John and Thomas",
     "Matthew, Mark and Luke",
     "A", "Matthew 17:1: 'Jesus took with him Peter and James and John his brother, and led them up a high mountain apart.'"),
    (T_TRANS, "Medium", "The appearance of Moses and Elijah with Jesus at the transfiguration signified that",
     "the law and the prophets bore witness to Jesus and found their fulfilment in him",
     "Moses and Elijah had returned to lead the nation of Israel",
     "Jesus was only one prophet among equals",
     "the disciples should build a permanent shrine on the mountain",
     "A", "Matthew 17:3: Moses represents the law and Elijah the prophets; both pointed forward to Christ."),
    (T_TRANS, "Medium", "Peter said, 'Lord, it is well that we are here; if you wish, I will make three booths.' His suggestion showed that he",
     "wanted to prolong the glorious moment and did not yet grasp that the path led to the cross",
     "had understood that Jesus was greater than Moses and Elijah",
     "expected Jesus to establish his kingdom on the mountain that day",
     "was trying to send Moses and Elijah away",
     "A", "Matthew 17:4-5; Luke 9:33 notes that Peter did not know what he said; the voice from the cloud corrected the emphasis."),
    (T_TRANS, "Medium", "The voice from the cloud at the transfiguration said, 'This is my beloved Son, with whom I am well pleased; listen to him.' The command 'listen to him' emphasised that",
     "Jesus' teaching, including his prediction of suffering, carried God's own authority",
     "Moses and Elijah were to be ignored from then on",
     "the disciples were to write down everything Jesus said",
     "only Peter, James and John were allowed to hear Jesus",
     "A", "Matthew 17:5: the disciples had resisted the teaching about the cross; God commanded them to heed it."),
    (T_TRANS, "Medium", "Coming down the mountain, Jesus commanded the three disciples to tell no one the vision until",
     "the Son of man had been raised from the dead",
     "they had told the other nine apostles",
     "Elijah had come and restored all things",
     "the Passover had been celebrated in Jerusalem",
     "A", "Matthew 17:9: only after the resurrection would the glory of the transfiguration be rightly understood."),
    (T_TRANS, "Medium", "When the disciples asked, 'Why do the scribes say that first Elijah must come?' Jesus answered that Elijah had already come and they did not know him. He was referring to",
     "John the Baptist",
     "Moses on the mountain",
     "the prophet Malachi",
     "Simeon in the temple",
     "A", "Matthew 17:10-13: 'Then the disciples understood that he was speaking to them of John the Baptist.'"),
    (T_TRANS, "Medium", "A believer wishes she could stay in the joy of a retreat for ever and dreads returning to the difficulties at home. Her feeling resembles that of",
     "Peter, who wanted to build three booths on the mountain",
     "Judas, who complained about the wasted ointment",
     "Martha, who was distracted with much serving",
     "the rich young ruler, who went away sorrowful",
     "A", "Matthew 17:4: like Peter, she would prolong the mountain-top experience, but discipleship continues in the valley below."),
    (T_TRANS, "Medium", "At the foot of the mountain the disciples could not heal a boy with an epileptic spirit. Jesus attributed their failure to",
     "their little faith",
     "the boy's father's unbelief",
     "the absence of Peter, James and John",
     "the fact that it was the Sabbath",
     "A", "Matthew 17:19-20: 'Because of your little faith... if you have faith as a grain of mustard seed, nothing will be impossible to you.'"),

    # ---------------- The Triumphal Entry and the Cleansing of the Temple ----------------
    (T_ENTRY, "Medium", "The crowd at the triumphal entry shouted, 'Hosanna to the Son of David! Blessed is he who comes in the name of the Lord!' The title 'Son of David' showed that they",
     "recognised Jesus as the promised Messiah of David's line",
     "believed Jesus was the physical son of King Herod",
     "were mocking Jesus for claiming royal descent",
     "thought Jesus was a Levite from the tribe of the priests",
     "A", "Matthew 21:9: 'Hosanna' means 'save now', and 'Son of David' was a messianic title."),
    (T_ENTRY, "Medium", "By riding into Jerusalem on a donkey rather than a horse, Jesus presented himself as",
     "a humble king of peace, not a military conqueror",
     "a poor man who could not afford a horse",
     "a pilgrim like every other Galilean at the feast",
     "a prophet in the tradition of Elijah",
     "A", "Matthew 21:4-5 (Zechariah 9:9): 'your king is coming to you, humble, and mounted on an ass'."),
    (T_ENTRY, "Medium", "When the Pharisees asked Jesus to rebuke his disciples for their praise, he replied,",
     "'If these were silent, the very stones would cry out.'",
     "'Render to Caesar the things that are Caesar's.'",
     "'My house shall be called a house of prayer.'",
     "'Destroy this temple, and in three days I will raise it up.'",
     "A", "Luke 19:39-40: the praise was fitting and could not be suppressed."),
    (T_ENTRY, "Medium", "As Jesus drew near and saw Jerusalem he wept over it because",
     "the city did not know the time of its visitation and would be destroyed",
     "the crowd was too small for a royal welcome",
     "the temple had been cleansed by the Romans",
     "his disciples had abandoned him at the gate",
     "A", "Luke 19:41-44: Jesus foresaw the destruction of the city that rejected the things that make for peace."),
    (T_ENTRY, "Medium", "Jesus drove the traders out of the temple and overturned the tables of the money-changers, saying they had made God's house 'a den of robbers'. The traders were guilty of",
     "exploiting worshippers and turning the court of the Gentiles into a market",
     "selling animals that the law did not permit as sacrifices",
     "refusing to pay the temple tax to the priests",
     "trading on the Sabbath against the law of Moses",
     "A", "Mark 11:15-17: 'My house shall be called a house of prayer for all the nations'; commerce had displaced the worship of the Gentiles."),
    (T_ENTRY, "Medium", "A church turns its Sunday service into a marketplace where members are pressured to buy the pastor's products at inflated prices. This resembles the situation Jesus condemned when he",
     "cleansed the temple of those who bought and sold",
     "cursed the fig tree that had leaves but no fruit",
     "rebuked the Pharisees for their long prayers",
     "wept over the city of Jerusalem",
     "A", "Mark 11:15-17: turning worship into an occasion for profit makes God's house a den of robbers."),
    (T_ENTRY, "Medium", "After the cleansing of the temple, the chief priests and scribes sought a way to destroy Jesus, but they feared him because",
     "all the multitude was astonished at his teaching",
     "the Roman soldiers were guarding him",
     "he had threatened to burn down the temple",
     "the money-changers had joined his disciples",
     "A", "Mark 11:18: the leaders' hostility was held in check by Jesus' popularity with the people."),
    (T_ENTRY, "Medium", "The blind and the lame came to Jesus in the temple after its cleansing and he healed them. This showed that",
     "the temple, cleansed of trade, became again a place of God's mercy",
     "healing was only permitted in the temple courts",
     "the chief priests approved of Jesus' actions",
     "the money-changers had been healing people before",
     "A", "Matthew 21:14-16: the house of prayer became a house of healing, while children cried 'Hosanna to the Son of David'."),
    (T_ENTRY, "Medium", "When the chief priests asked Jesus, 'By what authority are you doing these things?' he answered with a question about",
     "whether the baptism of John was from heaven or from men",
     "whose image and inscription was on the coin",
     "which commandment was the greatest",
     "whose wife the woman with seven husbands would be",
     "A", "Matthew 21:23-27: the leaders could not answer without condemning themselves, so Jesus declined to tell them."),

    # ---------------- The Last Supper ----------------
    (T_SUPPER, "Medium", "At the Last Supper Jesus took bread, blessed and broke it, and said, 'Take, eat; this is my body.' The bread symbolised",
     "his body given in death for his followers",
     "the manna eaten by Israel in the wilderness",
     "the unleavened bread of the Passover only",
     "the loaves that fed the five thousand",
     "A", "Matthew 26:26; Luke 22:19: 'This is my body which is given for you. Do this in remembrance of me.'"),
    (T_SUPPER, "Medium", "Jesus said of the cup, 'This is my blood of the covenant, which is poured out for many for the forgiveness of sins.' The cup therefore signified",
     "a new covenant established by his sacrificial death",
     "the wine of the Passover meal and nothing more",
     "the blood of the lambs slain in the temple",
     "the judgment coming upon Jerusalem",
     "A", "Matthew 26:28: Jesus' death inaugurated the new covenant foretold in Jeremiah 31."),
    (T_SUPPER, "Medium", "When the disciples disputed about which of them was the greatest, Jesus said, 'Let the greatest among you become as the youngest, and the leader as one who serves.' He supported this by pointing out that",
     "he himself was among them as one who serves",
     "the kings of the Gentiles were called benefactors",
     "Peter had been chosen as the greatest apostle",
     "the youngest disciple would sit at his right hand",
     "A", "Luke 22:24-27: 'I am among you as one who serves.'"),
    (T_SUPPER, "Medium", "Jesus told Peter, 'Simon, Simon, behold, Satan demanded to have you, that he might sift you like wheat, but I have prayed for you that your faith may not fail; and when you have turned again, strengthen your brethren.' This shows that",
     "Jesus foresaw Peter's fall but also his restoration and future ministry",
     "Peter would never deny Jesus because Jesus had prayed for him",
     "Satan had taken complete control of Peter",
     "Peter was being removed from the company of the apostles",
     "A", "Luke 22:31-32: Jesus' intercession ensured that Peter's failure would not be final."),
    (T_SUPPER, "Medium", "When Jesus began to wash the disciples' feet, Peter protested, 'You shall never wash my feet.' Jesus answered,",
     "'If I do not wash you, you have no part in me.'",
     "'Blessed are you, Simon Bar-Jona!'",
     "'You are the Christ, the Son of the living God.'",
     "'Feed my sheep.'",
     "A", "John 13:8: Peter then asked to be washed entirely, and Jesus explained the meaning of the act."),
    (T_SUPPER, "Medium", "A company director who insists on serving food to the cleaners at the staff party, rather than being served, is practising what Jesus taught when he",
     "washed the disciples' feet and told them to wash one another's feet",
     "told the disciples to take no bag or money for the journey",
     "overturned the tables of the money-changers",
     "cursed the fig tree that bore no fruit",
     "A", "John 13:12-15: 'I have given you an example, that you also should do as I have done to you.'"),
    (T_SUPPER, "Medium", "Jesus said at the supper, 'A new commandment I give to you, that you love one another; even as I have loved you.' The newness of this commandment lay in",
     "its standard: the self-giving love of Jesus himself",
     "the fact that love had never been commanded before",
     "its limitation to the twelve apostles only",
     "its replacement of the command to love God",
     "A", "John 13:34-35: 'By this all men will know that you are my disciples, if you have love for one another.'"),
    (T_SUPPER, "Medium", "After Judas received the morsel and went out, John notes, 'and it was night'. This detail suggests",
     "the spiritual darkness of Judas' betrayal",
     "that the supper was held later than usual",
     "that the disciples had run out of lamp oil",
     "that the Passover always began at midnight",
     "A", "John 13:30: the physical night mirrors the darkness of the deed Judas had gone to do."),
    (T_SUPPER, "Medium", "Paul taught that whoever eats the bread or drinks the cup of the Lord in an unworthy manner will be guilty of profaning the body and blood of the Lord. He therefore urged believers to",
     "examine themselves before partaking",
     "abstain from the supper for the rest of their lives",
     "eat a full meal at home first",
     "receive the supper only from an apostle",
     "A", "1 Corinthians 11:27-29: 'Let a man examine himself, and so eat of the bread and drink of the cup.'"),

    # ---------------- The Trials and the Death of Jesus ----------------
    (T_TRIAL, "Medium", "Before the Sanhedrin many bore false witness against Jesus, but their testimony did not agree. Jesus was finally condemned when",
     "he answered 'I am' to the high priest's question whether he was the Christ, the Son of the Blessed",
     "two witnesses agreed that he had planned to burn down the temple",
     "Judas testified that Jesus had claimed to be king",
     "Peter admitted under oath that Jesus was a blasphemer",
     "A", "Mark 14:55-64: the high priest tore his garments and said, 'You have heard his blasphemy.'"),
    (T_TRIAL, "Medium", "Pilate asked Jesus, 'Are you the King of the Jews?' Jesus replied that his kingship was not of this world, otherwise",
     "his servants would have fought to prevent his being handed over to the Jews",
     "he would have accepted the crown the crowd offered him in Galilee",
     "Herod would have been removed from his throne",
     "the Roman legions would have joined his army",
     "A", "John 18:36: Jesus' kingdom is spiritual and does not advance by violence."),
    (T_TRIAL, "Medium", "Pilate's wife sent word to him, 'Have nothing to do with that righteous man, for I have suffered much over him today in a dream.' Pilate nevertheless condemned Jesus because",
     "he feared a riot and wished to satisfy the crowd",
     "Jesus had confessed to leading an armed rebellion",
     "Herod had ordered him to carry out the sentence",
     "the witnesses had proved that Jesus blasphemed Caesar",
     "A", "Matthew 27:19, 24-26: Pilate washed his hands, declared himself innocent of Jesus' blood, and released Barabbas."),
    (T_TRIAL, "Medium", "A magistrate who knows an accused person is innocent but convicts him to avoid the anger of a mob is acting like",
     "Pilate, who delivered Jesus to be crucified to satisfy the crowd",
     "Joseph of Arimathea, who asked for the body of Jesus",
     "Simon of Cyrene, who was compelled to carry the cross",
     "the centurion, who declared that Jesus was the Son of God",
     "A", "Mark 15:15: 'Pilate, wishing to satisfy the crowd, released for them Barabbas... and delivered him to be crucified.'"),
    (T_TRIAL, "Medium", "Herod Antipas questioned Jesus at length, hoping to see a sign, but Jesus",
     "made no answer at all",
     "performed a miracle to gain his release",
     "rebuked Herod for the murder of John the Baptist",
     "asked Herod to send him back to Galilee",
     "A", "Luke 23:8-11: Herod and his soldiers treated him with contempt and sent him back to Pilate in a gorgeous robe."),
    (T_TRIAL, "Medium", "On the cross Jesus prayed, 'Father, forgive them; for they know not what they do.' This prayer shows that",
     "he practised the love for enemies that he had taught",
     "he expected the soldiers to release him at once",
     "the soldiers had asked him for forgiveness",
     "he had forgotten the suffering he was enduring",
     "A", "Luke 23:34: Jesus interceded for his executioners, fulfilling his own teaching in Matthew 5:44."),
    (T_TRIAL, "Medium", "The penitent thief said, 'Jesus, remember me when you come into your kingdom,' and Jesus replied,",
     "'Truly, I say to you, today you will be with me in Paradise.'",
     "'Father, into thy hands I commit my spirit!'",
     "'My God, my God, why hast thou forsaken me?'",
     "'It is finished.'",
     "A", "Luke 23:42-43: salvation was granted to a dying criminal who turned to Jesus in faith."),
    (T_TRIAL, "Medium", "Jesus' cry, 'My God, my God, why hast thou forsaken me?' expresses",
     "the depth of his suffering as he bore the sin of the world, in the words of Psalm 22",
     "his regret that he had ever come to Jerusalem",
     "his doubt about whether God existed",
     "a call to Elijah to come and rescue him",
     "A", "Mark 15:34 quotes Psalm 22:1; bystanders wrongly thought he was calling Elijah."),
    (T_TRIAL, "Medium", "The Roman centurion who stood facing Jesus said, 'Truly this man was the Son of God!' after he saw",
     "the manner in which Jesus breathed his last",
     "the soldiers dividing his garments by casting lots",
     "Joseph of Arimathea taking the body down",
     "the guards fleeing from the tomb",
     "A", "Mark 15:39: a Gentile soldier confessed what the religious leaders denied."),
    (T_TRIAL, "Medium", "Joseph of Arimathea, a respected member of the council who was looking for the kingdom of God, 'took courage and went to Pilate, and asked for the body of Jesus'. His act was courageous because",
     "it openly identified him with a man the council had condemned",
     "Pilate had ordered that anyone who touched the body be killed",
     "he had to fight the soldiers for the body",
     "the tomb he provided belonged to the high priest",
     "A", "Mark 15:42-46: a secret disciple came into the open at the moment of greatest danger."),

    # ---------------- Resurrection, Appearances and Ascension ----------------
    (T_RES, "Medium", "The women who came to the tomb early on the first day of the week were wondering who would roll away the stone. They found that",
     "the stone was rolled back and a young man in a white robe told them Jesus had risen",
     "the soldiers were still guarding the sealed tomb",
     "Peter and John had already removed the body",
     "the stone had been broken into pieces by an earthquake",
     "A", "Mark 16:1-6: 'He has risen, he is not here; see the place where they laid him.'"),
    (T_RES, "Medium", "The angel told the women, 'Go, tell his disciples and Peter that he is going before you to Galilee.' The special mention of Peter shows that",
     "Peter, despite his denial, was not cast off but included in the restoration",
     "Peter was already the head of the church in Jerusalem",
     "Peter had been absent from the other disciples since the arrest",
     "the angel did not regard Peter as a disciple any more",
     "A", "Mark 16:7: grace reached out to the disciple who had failed most publicly."),
    (T_RES, "Medium", "Mary Magdalene mistook the risen Jesus for the gardener until",
     "he called her by her name",
     "he showed her his hands and his side",
     "he broke bread in her presence",
     "Peter arrived and identified him",
     "A", "John 20:14-16: 'Jesus said to her, Mary. She turned and said to him in Hebrew, Rabboni!'"),
    (T_RES, "Medium", "On the road to Emmaus, Jesus said to the two disciples, 'O foolish men, and slow of heart to believe all that the prophets have spoken! Was it not necessary that the Christ should suffer these things and enter into his glory?' He then",
     "interpreted to them in all the scriptures the things concerning himself",
     "vanished immediately without saying anything more",
     "sent them back to Jerusalem to tell Peter",
     "showed them the wounds in his hands and feet",
     "A", "Luke 24:25-27: the risen Christ opened the scriptures, beginning with Moses and all the prophets."),
    (T_RES, "Medium", "The chief priests gave the soldiers money to say, 'His disciples came by night and stole him away while we were asleep.' The weakness of this story is that",
     "sleeping soldiers could not have known who took the body",
     "the disciples were in Galilee at the time",
     "the tomb had no stone to be moved",
     "the soldiers were Jewish and not Roman",
     "A", "Matthew 28:11-15: the bribe and the contradictory story show the leaders' desperation to deny the resurrection."),
    (T_RES, "Medium", "When Jesus appeared to the disciples and they thought they saw a spirit, he said, 'Handle me, and see; for a spirit has not flesh and bones as you see that I have,' and he",
     "ate a piece of broiled fish before them",
     "walked on the water of the lake",
     "disappeared through the locked door",
     "washed their feet once more",
     "A", "Luke 24:36-43: the risen Jesus demonstrated that his resurrection was bodily, not a ghostly apparition."),
    (T_RES, "Medium", "By the Sea of Tiberias Jesus asked Peter three times, 'Simon, son of John, do you love me?' and each time charged him, 'Feed my sheep.' The threefold question corresponded to",
     "Peter's three denials, allowing him to be publicly restored",
     "the three years Peter had followed Jesus",
     "the three booths Peter had wanted to build",
     "the three thousand who would be converted at Pentecost",
     "A", "John 21:15-17: Peter was grieved at the third question, but the threefold commission reinstated him as shepherd."),
    (T_RES, "Medium", "Before his ascension Jesus told the apostles, 'You shall receive power when the Holy Spirit has come upon you; and you shall be my witnesses in Jerusalem and in all Judea and Samaria and to the end of the earth.' This verse gives",
     "the programme of the church's mission, beginning at home and spreading to the whole world",
     "a promise that the apostles would rule Israel from Jerusalem",
     "an instruction to remain in Jerusalem permanently",
     "the date on which the Holy Spirit would come",
     "A", "Acts 1:8: the outline of the book of Acts follows this geographical expansion."),
    (T_RES, "Medium", "As the apostles gazed into heaven after the ascension, two men in white robes told them that",
     "this Jesus would come again in the same way as they saw him go into heaven",
     "Jesus had gone to Galilee and would meet them there",
     "they should elect a new leader in place of Jesus",
     "the kingdom would be restored to Israel that very year",
     "A", "Acts 1:10-11: the ascension carries the promise of the second coming."),
    (T_RES, "Medium", "A church member says, 'The resurrection is only a symbol that Jesus' ideas live on.' The gospel accounts contradict this because",
     "the risen Jesus was touched, ate food and showed his wounds",
     "the disciples never actually saw Jesus after his death",
     "the tomb was never found empty",
     "Jesus appeared only in dreams to the disciples",
     "A", "Luke 24:39-43 and John 20:27: the evangelists stress the physical reality of the resurrection body."),

    # ---------------- Jesus' Teachings about Himself ----------------
    (T_SELF, "Medium", "After feeding the five thousand Jesus said, 'I am the bread of life; he who comes to me shall not hunger.' He meant that",
     "he alone satisfies the deepest spiritual need of humanity",
     "he would provide free bread daily for his followers",
     "his followers would never need to eat ordinary food",
     "the manna in the wilderness had been his own body",
     "A", "John 6:35: the crowd sought loaves; Jesus pointed them to himself as the food that endures to eternal life."),
    (T_SELF, "Medium", "Jesus said, 'I am the light of the world; he who follows me will not walk in darkness, but will have the light of life.' A person who claims to follow Jesus but lives in deliberate sin",
     "contradicts this claim, since following the light means leaving darkness",
     "is walking in the light because he goes to church",
     "shows that light and darkness can coexist in a disciple",
     "proves that the light of life is a future reward only",
     "A", "John 8:12; 1 John 1:6: 'If we say we have fellowship with him while we walk in darkness, we lie.'"),
    (T_SELF, "Medium", "Jesus said, 'I am the door; if any one enters by me, he will be saved.' This claim means that",
     "he is the only way of entry into salvation and the fold of God",
     "the temple gate had been closed to Gentiles",
     "his followers should build churches with narrow doors",
     "salvation is available through any religious teacher",
     "A", "John 10:7-9: the shepherd's door image stresses exclusive access through Christ."),
    (T_SELF, "Medium", "Jesus said, 'I am the resurrection and the life; he who believes in me, though he die, yet shall he live.' He spoke these words to",
     "Martha, before raising her brother Lazarus",
     "Mary Magdalene, at the empty tomb",
     "Thomas, after the resurrection",
     "Nicodemus, when he came by night",
     "A", "John 11:25-27: Martha responded, 'Yes, Lord; I believe that you are the Christ, the Son of God.'"),
    (T_SELF, "Medium", "'I am the true vine, and my Father is the vinedresser... Apart from me you can do nothing.' Jesus was teaching that",
     "fruitful Christian life depends on continual union with him",
     "farming is the most suitable occupation for Christians",
     "the Father prunes only the branches that bear no fruit",
     "believers can bear fruit through their own strength",
     "A", "John 15:1-5: 'He who abides in me, and I in him, he it is that bears much fruit.'"),
    (T_SELF, "Medium", "A church worker who used to be effective becomes proud, stops praying and gradually loses all influence for good. His experience illustrates Jesus' saying,",
     "'Apart from me you can do nothing.'",
     "'The Son of man came not to be served but to serve.'",
     "'Before Abraham was, I am.'",
     "'I am the good shepherd.'",
     "A", "John 15:5: a branch cut off from the vine withers; effectiveness flows from abiding in Christ."),
    (T_SELF, "Medium", "When Jesus said, 'Before Abraham was, I am,' the Jews took up stones to throw at him because",
     "he was claiming the divine name and eternal existence",
     "he had insulted Abraham, their father",
     "he claimed to be older than Moses",
     "it was unlawful to mention Abraham in the temple",
     "A", "John 8:58-59: 'I am' echoes God's name in Exodus 3:14; the hearers understood it as a claim to deity."),
    (T_SELF, "Medium", "Jesus said, 'The Son of man came not to be served but to serve, and to give his life as a ransom for many.' The word 'ransom' indicates that his death",
     "was the price paid to set sinners free",
     "was an unfortunate accident of history",
     "would be reversed by the payment of money",
     "freed only the twelve apostles",
     "A", "Mark 10:45: Jesus interpreted his coming death as a redemptive, substitutionary act."),
    (T_SELF, "Medium", "Jesus said, 'I and the Father are one,' and, 'He who has seen me has seen the Father.' These sayings teach",
     "the unity of the Son with the Father, so that Jesus reveals God fully",
     "that Jesus and the Father are the same person in different roles",
     "that the Father ceased to exist when the Son was born",
     "that Jesus was only a human prophet sent by God",
     "A", "John 10:30 and 14:9: Jesus claimed a unique oneness with the Father while remaining distinct from him."),
    (T_SELF, "Medium", "A dying Christian tells her family, 'Do not weep for me; I am only going to the room he has prepared.' She is drawing on Jesus' promise,",
     "'In my Father's house are many rooms... I go to prepare a place for you.'",
     "'I am the bread of life; he who comes to me shall not hunger.'",
     "'I am the door of the sheep.'",
     "'You are the light of the world.'",
     "A", "John 14:2-3: 'I will come again and will take you to myself, that where I am you may be also.'"),
]

FIX = {
    "the devil quoted Psalm 91": (
        "scripture must not be twisted to justify testing God with reckless acts",
        "the Psalms should not be quoted by anyone except the priests in the temple",
        "angels no longer protect the people of God as they did in the days of David",
        "the pinnacle of the temple was not a holy place from which to pray"),
    "By 'hate' he meant that": (
        "love for him must so far exceed every other love that others seem like hatred by comparison",
        "disciples must break off all relations with their families as soon as they begin to follow him",
        "family members are the chief enemies of the kingdom of God and must be treated with suspicion",
        "disciples should neglect the care of their aged parents in order to devote all their time to him"),
    "The Gerasene demoniac, once healed": (
        "'Go home to your friends, and tell them how much the Lord has done for you.'",
        "'Follow me, and I will make you a fisher of men, for the harvest is plentiful.'",
        "'See that you say nothing to any one, but go and show yourself to the priest.'",
        "'Come and see where I am staying, and remain with me until the feast.'"),
    "Jesus called him a hypocrite because": (
        "he would untie his ox or ass on the Sabbath to water it but objected to a daughter of Abraham being loosed",
        "he had healed several people himself on the Sabbath in previous years without any complaint from the elders",
        "the woman was his own relative and he had refused for eighteen years to help her in any way at all",
        "he had invited Jesus to the synagogue specifically to heal her and then denied doing so before the people"),
    "The parable of the weeds cautions him that": (
        "judgment and separation belong to God at the harvest, and hasty uprooting harms the wheat",
        "the church should contain only perfect people, so every suspected sinner must be removed at once",
        "weeds should be pulled up as soon as they are noticed, before they can spread to the whole field",
        "the enemy has no power to sow weeds among the wheat once the pastor has purified the church"),
    "the foolish ones were shut out because": (
        "they took no oil with their lamps and were absent buying some when the bridegroom came",
        "they fell asleep while the wise maidens stayed awake and kept watch through the night",
        "they refused to share their oil with the others when the bridegroom's arrival was delayed",
        "they arrived at the feast before the bridegroom and were sent away for their impatience"),
    "The parable of the two sons": (
        "tax collectors and harlots who repented were entering the kingdom before the religious leaders who only professed obedience",
        "sons should always obey their fathers immediately without argument, since delayed obedience is the same as disobedience",
        "the first son was punished for his rude answer even though he later did the work his father had asked him to do",
        "vineyard work was reserved for the eldest son, while the younger son was expected to remain at home with his mother"),
    "The tenants killed him. The parable pointed to": (
        "the rejection and killing of Jesus by the leaders of Israel after they had rejected the prophets",
        "the failure of the Roman governors to protect Jewish farmers from bandits in the hills of Galilee",
        "the destruction of the vineyards of Galilee by the Samaritans during the reign of Herod the Great",
        "the need for landlords to collect their rent in person rather than sending servants to do it"),
    "is followed by the warning that": (
        "if you do not forgive men their trespasses, neither will your Father forgive your trespasses",
        "debts must be repaid in full before any prayer can be heard by the Father who is in heaven",
        "only debts owed to fellow Christians need to be forgiven, while others may be collected in full",
        "God forgives without any condition whatever a person does, so forgiving others is optional"),
    "The command 'listen to him' emphasised that": (
        "Jesus' teaching, including his prediction of suffering, carried God's own authority",
        "Moses and Elijah were to be ignored from then on because their words had lost all value",
        "the disciples were to write down everything Jesus said from that day until the ascension",
        "only Peter, James and John were permitted to hear Jesus teach for the rest of his ministry"),
    "he wept over it because": (
        "the city did not know the time of its visitation and would be destroyed",
        "the crowd that welcomed him was too small for a royal entry into the city",
        "the temple had been cleansed by the Romans before he could reach it",
        "his disciples had abandoned him at the gate and fled back to Galilee"),
    "Jesus was finally condemned when": (
        "he answered 'I am' to the high priest's question whether he was the Christ, the Son of the Blessed",
        "two witnesses agreed that he had planned to burn down the temple during the coming Passover feast",
        "Judas testified before the council that Jesus had claimed to be king of the Jews in place of Caesar",
        "Peter admitted under oath in the courtyard that Jesus had blasphemed against the name of God"),
    "why hast thou forsaken me?' expresses": (
        "the depth of his suffering as he bore the sin of the world, in the words of Psalm 22",
        "his regret that he had ever come to Jerusalem instead of remaining safely in Galilee",
        "his doubt about whether God existed, since no rescue had come from heaven",
        "a call to Elijah to come down from heaven and rescue him from the cross"),
    "who would roll away the stone. They found that": (
        "the stone was rolled back and a young man in a white robe told them Jesus had risen",
        "the soldiers were still guarding the sealed tomb and refused to let them come near it",
        "Peter and John had already removed the body and carried it away to Galilee",
        "the stone had been broken into pieces by an earthquake and the tomb was full of rubble"),
}


def build():
    build_batch(
        S, "batch_026_crs_round3b.json", "batch_026_crs_round3b",
        "Christian Religious Studies round 3 (part B): the Gospels - birth and early life of Jesus, baptism and temptation, discipleship, miracles, parables, Sermon on the Mount, mission of the disciples, great confession, transfiguration, triumphal entry and temple cleansing, Last Supper, trials and death, resurrection and ascension, Jesus' teachings about Himself - scripture-based and application items.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
