"""Batch 048 - WAEC/NECO Physics, Paper 1 round 1.

WASSCE Physics Paper 1 is a 50-item objective paper (75 minutes).  This batch
covers the SSCE syllabus: measurements, motion, force and momentum, work/energy/
power, machines, pressure, heat, waves and sound, light, electricity,
electromagnetism and modern physics.  Every calculation carries an independent
`verify` expression (g = 10 m/s² where stated; speeds, masses and charges chosen
to give clean WASSCE-style answers).

    python3 scripts/build_content_batch48.py -> content/batch_048_waec_physics.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Physics"

T_MEAS = "Measurements and Units"
T_MOT = "Motion"
T_FORCE = "Force, Momentum and Newton's Laws"
T_WORK = "Work, Energy and Power"
T_MACH = "Machines"
T_PRESS = "Pressure and Upthrust"
T_HEAT = "Heat Energy"
T_WAVE = "Waves and Sound"
T_LIGHT = "Light and Optics"
T_ELEC = "Electricity"
T_MAG = "Magnetism and Electromagnetism"
T_MOD = "Modern Physics"

PASSAGES = []
PQ = []

Q = [
    # --------------------------------------------------------------- measurement
    (T_MEAS, "Easy", "The instrument used to measure the internal diameter of a thin tube accurately is the",
     "micrometer screw gauge", "metre rule", "measuring cylinder", "hydrometer", "A",
     "The micrometer screw gauge reads to 0.01 mm, ideal for small internal and external diameters.", None),
    (T_MEAS, "Easy", "Which of the following is a fundamental unit?",
     "Kelvin", "Newton", "Joule", "Watt", "A",
     "Kelvin is one of the seven base units; the newton, joule and watt are derived units.", None),
    (T_MEAS, "Easy", "Which instrument is most suitable for measuring the mass of an object in the laboratory?",
     "Beam balance", "Spring balance", "Hydrometer", "Ammeter", "A",
     "A beam balance compares masses; a spring balance measures weight (a force).", None),
    (T_MEAS, "Medium", "The volume of a small stone can be measured using a",
     "measuring cylinder and water", "vernier calliper", "micrometer screw gauge", "stop-watch", "A",
     "The rise in water level in the cylinder gives the volume of an immersed stone.", None),
    (T_MEAS, "Easy", "Time in the physics laboratory is measured with a",
     "stop-watch", "barometer", "ammeter", "thermometer", "A",
     "Stop-watches time events to a fraction of a second.", None),
    (T_MEAS, "Medium", "The smallest length that a vernier calliper can measure is",
     "0.1 mm", "0.01 mm", "1 mm", "0.001 mm", "A",
     "A vernier calliper reads to 0.1 mm; finer readings need the micrometer gauge.", "0.1"),
    (T_MEAS, "Medium", "Express 2.6 metres in centimetres.",
     "260 cm", "0.026 cm", "26 cm", "2,600 cm", "A",
     "Multiplying by 100 converts metres to centimetres: 2.6 × 100 = 260 cm.", "2.6*100"),
    (T_MEAS, "Hard", "A student measures a rod as 20.5 cm, 20.7 cm and 20.6 cm in three trials. The average length is",
     "20.6 cm", "20.5 cm", "20.7 cm", "61.8 cm", "A",
     "Averaging the readings: (20.5 + 20.7 + 20.6) ÷ 3 = 20.6 cm.", "(20.5+20.7+20.6)/3"),
    (T_MEAS, "Medium", "Which quantity is a vector?",
     "Velocity", "Mass", "Temperature", "Energy", "A",
     "Vectors have both magnitude and direction; velocity is speed in a stated direction.", None),
    (T_MEAS, "Easy", "Which of these is a scalar quantity?",
     "Distance", "Displacement", "Force", "Acceleration", "A",
     "Distance has magnitude only, with no direction attached.", None),

    # -------------------------------------------------------------------- motion
    (T_MOT, "Easy", "A car starts from rest and accelerates uniformly at 2 m/s² for 5 s. Its final speed is",
     "10 m/s", "2.5 m/s", "7 m/s", "20 m/s", "A",
     "v = u + at = 0 + 2 × 5 = 10 m/s.", "2*5"),
    (T_MOT, "Medium", "A car starts from rest with uniform acceleration 2 m/s². The distance covered in 5 s is",
     "25 m", "10 m", "50 m", "20 m", "A",
     "s = ut + ½at² = 0 + ½ × 2 × 25 = 25 m.", "0.5*2*5**2"),
    (T_MOT, "Medium", "A car travelling at 20 m/s is brought uniformly to rest in 50 m. Its retardation is",
     "4 m/s²", "0.4 m/s²", "8 m/s²", "2 m/s²", "A",
     "v² = u² + 2as gives 0 = 400 + 2a(50), so a = −4 m/s².", "20**2/(2*50)"),
    (T_MOT, "Easy", "A stone is dropped from rest. Taking g = 10 m/s², its speed after 3 s is",
     "30 m/s", "3.3 m/s", "45 m/s", "90 m/s", "A",
     "v = gt = 10 × 3 = 30 m/s.", "10*3"),
    (T_MOT, "Medium", "A stone is dropped from rest. Taking g = 10 m/s², the distance fallen in 3 s is",
     "45 m", "30 m", "90 m", "15 m", "A",
     "h = ½gt² = ½ × 10 × 9 = 45 m.", "0.5*10*3**2"),
    (T_MOT, "Easy", "The gradient of a distance-time graph gives",
     "speed", "acceleration", "distance", "displacement", "A",
     "Change of distance per unit time is the definition of speed.", None),
    (T_MOT, "Easy", "The area under a velocity-time graph gives",
     "distance travelled", "acceleration", "speed", "force", "A",
     "Multiplying velocity by time gives the distance covered.", None),
    (T_MOT, "Medium", "A cyclist covers 90 km in 1.5 hours. The average speed is",
     "60 km/h", "45 km/h", "135 km/h", "30 km/h", "A",
     "Average speed = 90 ÷ 1.5 = 60 km/h.", "90/1.5"),
    (T_MOT, "Medium", "The velocity of a body increases uniformly from 4 m/s to 16 m/s in 3 s. Its acceleration is",
     "4 m/s²", "5.3 m/s²", "12 m/s²", "2 m/s²", "A",
     "a = (16 − 4) ÷ 3 = 4 m/s².", "(16-4)/3"),
    (T_MOT, "Medium", "A body moving with uniform velocity has zero",
     "acceleration", "displacement", "speed", "momentum", "A",
     "No change in velocity means the acceleration is zero.", None),
    (T_MOT, "Hard", "A ball is thrown vertically upwards at 20 m/s. Taking g = 10 m/s², the maximum height reached is",
     "20 m", "40 m", "10 m", "2 m", "A",
     "At the top v = 0, so h = u²/2g = 400 ÷ 20 = 20 m.", "20**2/(2*10)"),
    (T_MOT, "Hard", "A train travels the first half of a journey at 30 km/h and the second half at 60 km/h. Which statement is true about the journey?",
     "The average speed is less than 45 km/h", "The average speed is 45 km/h", "The average speed is more than 45 km/h", "The average speed cannot be found", "A",
     "More time is spent on the slower half, so the average is pulled below the simple mean of 45 km/h.", None),
    (T_MOT, "Easy", "Which of these is an example of uniform acceleration?",
     "A freely falling stone in vacuum", "A car turning a corner at constant speed", "A car at rest", "A bus moving at constant speed", "A",
     "A falling body gains equal velocity in equal times; turning at constant speed changes only direction.", None),

    # ----------------------------------------------------- force and momentum
    (T_FORCE, "Easy", "A force of 20 N acts on a mass of 4 kg. The acceleration produced is",
     "5 m/s²", "80 m/s²", "0.2 m/s²", "16 m/s²", "A",
     "From F = ma, a = 20 ÷ 4 = 5 m/s².", "20/4"),
    (T_FORCE, "Easy", "The weight of a 60 kg girl, taking g = 10 m/s², is",
     "600 N", "6 N", "60 N", "6,000 N", "A",
     "W = mg = 60 × 10 = 600 N.", "60*10"),
    (T_FORCE, "Easy", "The momentum of a 1,000 kg car moving at 20 m/s is",
     "20,000 kg·m/s", "50 kg·m/s", "200 kg·m/s", "2,000 kg·m/s", "A",
     "p = mv = 1,000 × 20 = 20,000 kg·m/s.", "1000*20"),
    (T_FORCE, "Medium", "A 0.5 kg ball moving at 6 m/s is brought to rest. The magnitude of its change in momentum is",
     "3 kg·m/s", "6 kg·m/s", "0.5 kg·m/s", "12 kg·m/s", "A",
     "Δp = mv − 0 = 0.5 × 6 = 3 kg·m/s.", "0.5*6"),
    (T_FORCE, "Hard", "A 0.5 kg ball moving at 6 m/s is stopped by a wall in 0.1 s. The average force of the impact is",
     "30 N", "3 N", "0.6 N", "60 N", "A",
     "F = change of momentum ÷ time = 3 ÷ 0.1 = 30 N.", "0.5*6/0.1"),
    (T_FORCE, "Medium", "Newton's third law implies that when a boy kicks a ball,",
     "the ball exerts an equal and opposite force on his foot", "the ball pushes nothing back", "the forces cancel so the ball cannot move", "only the ball experiences a force", "A",
     "Forces act in pairs on different bodies: foot on ball and ball on foot.", None),
    (T_FORCE, "Easy", "The friction between a car's tyres and the road is useful because it",
     "allows the car to start, stop and turn", "wastes the engine's power", "makes the car slip", "reduces the car's speed always", "A",
     "Without friction the wheels would spin and braking would fail.", None),
    (T_FORCE, "Medium", "A body in equilibrium under three forces must have the forces",
     "adding to zero as vectors", "equal in magnitude always", "acting in one direction", "parallel to each other", "A",
     "Balanced forces give zero resultant, so no acceleration occurs.", None),
    (T_FORCE, "Easy", "Which statement about mass and weight is correct?",
     "Mass is constant while weight varies with gravity", "Weight is constant while mass varies", "Both are exactly the same quantity", "Mass is measured in newtons", "A",
     "Mass is the quantity of matter; weight is the gravitational force on it.", None),
    (T_FORCE, "Medium", "A resultant force of zero acts on a moving body. The body will",
     "continue moving with the same velocity", "slow down steadily and then stop", "come to rest immediately after braking", "accelerate uniformly in its direction", "A",
     "Newton's first law: with no net force the motion stays unchanged.", None),
    (T_FORCE, "Hard", "Why does a passenger lurch forward when a bus brakes suddenly?",
     "his body tends to continue in its state of motion", "the seat behind pushes him forward hard", "the force of gravity acts forward on him", "the bus engine pulls his body forward", "A",
     "Inertia keeps the passenger moving until the seat belt restrains him.", None),

    # --------------------------------------------------------- work/energy/power
    (T_WORK, "Easy", "A force of 50 N moves a box 4 m in the direction of the force. The work done is",
     "200 J", "12.5 J", "54 J", "800 J", "A",
     "W = F × d = 50 × 4 = 200 J.", "50*4"),
    (T_WORK, "Easy", "A boy of mass 60 kg climbs 5 m up a staircase. Taking g = 10 m/s², the work he does against gravity is",
     "3,000 J", "300 J", "600 J", "12 J", "A",
     "W = mgh = 60 × 10 × 5 = 3,000 J.", "60*10*5"),
    (T_WORK, "Easy", "The kinetic energy of a 2 kg mass moving at 6 m/s is",
     "36 J", "12 J", "72 J", "6 J", "A",
     "KE = ½mv² = ½ × 2 × 36 = 36 J.", "0.5*2*6**2"),
    (T_WORK, "Medium", "A machine does 600 J of work in 12 s. Its power is",
     "50 W", "7,200 W", "0.02 W", "588 W", "A",
     "P = W ÷ t = 600 ÷ 12 = 50 W.", "600/12"),
    (T_WORK, "Medium", "A man of weight 500 N climbs 4 m in 10 s. His power is",
     "200 W", "2,000 W", "50 W", "125 W", "A",
     "P = (500 × 4) ÷ 10 = 200 W.", "500*4/10"),
    (T_WORK, "Medium", "A stone released from rest 20 m above the ground strikes the ground with speed (g = 10 m/s²)",
     "20 m/s", "200 m/s", "10 m/s", "40 m/s", "A",
     "mgh = ½mv² gives v = √(2 × 10 × 20) = 20 m/s.", "math.sqrt(2*10*20)"),
    (T_WORK, "Easy", "The work done by a force is zero when the force acts",
     "perpendicular to the direction of motion", "along the direction of motion", "against the motion", "on a heavy body", "A",
     "No component of the force along the motion means no work is done.", None),
    (T_WORK, "Medium", "One horsepower is equal to about",
     "746 W", "100 W", "1,000 W", "550 W only", "A",
     "One horsepower is the imperial unit of power, equal to about 746 watts.", "746"),
    (T_WORK, "Hard", "A pump lifts 60 kg of water through a height of 5 m every minute. Taking g = 10 m/s², its power is",
     "50 W", "3,000 W", "300 W", "500 W", "A",
     "Each minute it does 3,000 J of work, so the power is 3,000 ÷ 60 = 50 W.", "60*10*5/60"),
    (T_WORK, "Hard", "A ball is thrown upwards. At the highest point of its flight,",
     "kinetic energy is zero and potential energy is greatest", "both forms of energy have become zero", "kinetic energy reaches its greatest value", "potential energy falls back down to zero", "A",
     "The ball momentarily stops, so all its energy is stored as potential energy.", None),

    # -------------------------------------------------------------------- machines
    (T_MACH, "Easy", "A lever uses an effort of 50 N to raise a load of 200 N. Its mechanical advantage is",
     "4", "0.25", "150", "10,000", "A",
     "MA = load ÷ effort = 200 ÷ 50 = 4.", "200/50"),
    (T_MACH, "Medium", "In a wheel and axle, the wheel radius is 30 cm and the axle radius is 5 cm. The velocity ratio is",
     "6", "0.17", "35", "25", "A",
     "The effort moves round the big wheel while the load moves round the small axle, so VR = 30 ÷ 5 = 6.", "30/5"),
    (T_MACH, "Medium", "A machine has MA 4 and VR 5. Its efficiency is",
     "80%", "125%", "20%", "100%", "A",
     "Efficiency = (MA ÷ VR) × 100 = 80%.", "4/5*100"),
    (T_MACH, "Easy", "The efficiency of a real machine is always less than 100% because of",
     "friction in moving parts", "the load being too heavy", "the effort being too small", "gravity acting always", "A",
     "Work is wasted against friction and lifting moving parts.", None),
    (T_MACH, "Medium", "In a pulley system with four ropes supporting the load, the velocity ratio is",
     "4", "2", "8", "1", "A",
     "Each supporting rope shares the load, giving VR equal to the number of ropes.", "4"),
    (T_MACH, "Easy", "A machine that is a distance multiplier has a velocity ratio that is",
     "less than 1", "greater than 1", "equal to 1", "always zero", "A",
     "Speed multipliers like bicycles trade force for distance: VR < 1 means effort moves less.", None),
    (T_MACH, "Hard", "An inclined plane 5 m long raises a load 1 m high. Its velocity ratio is",
     "5", "0.2", "4", "6", "A",
     "VR = length of slope ÷ height = 5 ÷ 1 = 5.", "5/1"),
    (T_MACH, "Medium", "Which machine is used to raise water from a well in many Nigerian villages?",
     "a pulley system mounted on a simple frame", "a hydraulic press for lifting loads", "a system of gears and chains", "a bicycle wheel and axle system", "A",
     "A single fixed pulley changes the direction of the effort for easy pulling.", None),

    # ----------------------------------------------------------- pressure/upthrust
    (T_PRESS, "Easy", "A force of 600 N acts on an area of 2 m². The pressure exerted is",
     "300 Pa", "1,200 Pa", "150 Pa", "30 Pa", "A",
     "P = F ÷ A = 600 ÷ 2 = 300 N/m².", "600/2"),
    (T_PRESS, "Medium", "The pressure at a depth of 10 m in water of density 1,000 kg/m³, taking g = 10 m/s², is",
     "100,000 Pa", "10,000 Pa", "1,000 Pa", "1,000,000 Pa", "A",
     "P = ρgh = 1,000 × 10 × 10 = 100,000 Pa.", "1000*10*10"),
    (T_PRESS, "Easy", "The height of a mercury barometer column at standard atmospheric pressure is about",
     "76 cm", "7.6 cm", "760 cm", "10 cm", "A",
     "Normal atmospheric pressure supports a 76 cm column of mercury.", "76"),
    (T_PRESS, "Medium", "A hydraulic press has pistons of area 2 cm² and 200 cm². A force of 50 N on the small piston lifts a load of",
     "5,000 N", "0.5 N", "500 N", "2 N", "A",
     "Pressure is transmitted equally: F = 50 × (200 ÷ 2) = 5,000 N.", "50*200/2"),
    (T_PRESS, "Medium", "A block of volume 0.002 m³ is fully immersed in water (density 1,000 kg/m³, g = 10 m/s²). The upthrust on it is",
     "20 N", "2 N", "200 N", "0.2 N", "A",
     "Upthrust = ρVg = 1,000 × 0.002 × 10 = 20 N.", "1000*0.002*10"),
    (T_PRESS, "Easy", "A body floats in a liquid when its weight is",
     "equal to the upthrust", "greater than the upthrust", "less than the upthrust always", "zero", "A",
     "Balanced forces leave the body floating at rest.", None),
    (T_PRESS, "Medium", "A ship floats higher in sea water than in fresh water because sea water",
     "has a greater density", "is warmer", "has waves", "is deeper", "A",
     "A denser liquid gives more upthrust, so less of the ship is submerged.", None),
    (T_PRESS, "Medium", "A rectangular block has mass 240 g and volume 30 cm³. Its density is",
     "8 g/cm³", "0.125 g/cm³", "7,200 g/cm³", "0.8 g/cm³", "A",
     "ρ = m ÷ V = 240 ÷ 30 = 8 g/cm³.", "240/30"),
    (T_PRESS, "Easy", "A dam wall is thicker at the bottom than the top because pressure in a liquid",
     "increases with depth", "decreases with depth", "acts upwards only", "is constant everywhere", "A",
     "The deeper water exerts the larger pressure, so the wall needs more thickness below.", None),
    (T_PRESS, "Hard", "The atmospheric pressure on a day when the barometer reads 76 cm of mercury is about (ρ = 13,600 kg/m³, g = 10 m/s²)",
     "103,360 Pa", "10,336 Pa", "103 Pa", "1,033,600 Pa", "A",
     "P = 0.76 × 13,600 × 10 = 103,360 Pa.", "0.76*13600*10"),
    (T_PRESS, "Medium", "It is less painful to walk on sand with flat slippers than with narrow heels because the slippers",
     "spread the person's force over a larger area", "reduce the weight of the person walking", "increase the pressure under the foot", "absorb the pull of gravity somehow", "A",
     "The same force over a bigger area gives a smaller pressure.", None),

    # ----------------------------------------------------------------------- heat
    (T_HEAT, "Easy", "Heat is transferred through a metal spoon in hot soup mainly by",
     "conduction", "convection", "radiation", "evaporation", "A",
     "Metals conduct heat along their particles from the hot to the cold end.", None),
    (T_HEAT, "Easy", "Land and sea breezes are caused by",
     "convection currents in air", "conduction through the ground", "radiation from the moon", "evaporation of sea water", "A",
     "Air warmed by the land or sea rises and circulates as convection currents.", None),
    (T_HEAT, "Medium", "The vacuum between the walls of a thermos flask reduces heat transfer by",
     "conduction and convection", "radiation only", "evaporation", "condensation", "A",
     "A vacuum has no particles, so neither conduction nor convection can cross it.", None),
    (T_HEAT, "Easy", "Heat from the sun reaches the earth by",
     "radiation", "conduction", "convection", "reflection", "A",
     "Infrared radiation travels through empty space needs no medium.", None),
    (T_HEAT, "Medium", "Convert 68°F to degrees Celsius.",
     "20°C", "37.8°C", "52°C", "88°C", "A",
     "C = (F − 32) × 5/9 = 36 × 5/9 = 20°C.", "(68-32)/1.8"),
    (T_HEAT, "Easy", "The SI unit of temperature is the",
     "kelvin", "degree Celsius", "degree Fahrenheit", "joule", "A",
     "Temperature in kelvin is the SI base quantity; °C is common but derived.", None),
    (T_HEAT, "Medium", "Calculate the heat needed to raise 200 g of water from 30°C to 80°C (c = 4,200 J/kg·K).",
     "42,000 J", "4,200 J", "420,000 J", "4,200,000 J", "A",
     "Q = mcθ = 0.2 × 4,200 × 50 = 42,000 J.", "0.2*4200*50"),
    (T_HEAT, "Hard", "A 2 kW electric kettle heats water for 1 minute. The heat supplied is",
     "120,000 J", "2,000 J", "120 J", "7,200,000 J", "A",
     "Q = Pt = 2,000 × 60 = 120,000 J.", "2000*60"),
    (T_HEAT, "Medium", "Water has its maximum density at",
     "4°C", "0°C", "100°C", "−4°C", "A",
     "The anomalous expansion of water peaks at 4°C, which is why ice floats.", "4"),
    (T_HEAT, "Medium", "A gas occupies 600 cm³ at 300 K. At constant pressure and 450 K its volume becomes",
     "900 cm³", "400 cm³", "600 cm³", "1,350 cm³", "A",
     "Charles' law: V ∝ T, so V = 600 × 450/300 = 900 cm³.", "600*450/300"),
    (T_HEAT, "Hard", "A metal rod is 2.000 m long at 0°C and 2.004 m at 100°C. Its linear expansivity is",
     "0.00002 per K", "0.002 per K", "0.0002 per K", "0.02 per K", "A",
     "α = ΔL/(L₁Δθ) = 0.004/(2 × 100) = 0.00002 /K.", "0.004/(2*100)"),
    (T_HEAT, "Medium", "Which surface is the best absorber of radiation?",
     "A dull black surface", "A shiny silver surface", "A white surface", "A polished mirror", "A",
     "Dull black surfaces both absorb and radiate heat best.", None),
    (T_HEAT, "Easy", "The fixed points on a Celsius thermometer are separated by",
     "100 divisions", "80 divisions", "180 divisions", "212 divisions", "A",
     "Ice point 0°C to steam point 100°C gives 100 equal divisions.", "100"),
    (T_HEAT, "Hard", "Evaporation of water in a clay pot keeps the water cool because",
     "the fastest molecules escape and lower the average energy", "clay conducts the heat away very quickly indeed", "the water absorbs extra heat from the warm air", "the clay surface reflects the sunlight away", "A",
     "Only energetic molecules escape, so those left behind are cooler.", None),

    # ---------------------------------------------------------------- waves/sound
    (T_WAVE, "Medium", "A wave of frequency 50 Hz has a wavelength of 4 m. Its speed is",
     "200 m/s", "12.5 m/s", "54 m/s", "0.08 m/s", "A",
     "v = fλ = 50 × 4 = 200 m/s.", "50*4"),
    (T_WAVE, "Medium", "The period of a wave of frequency 250 Hz is",
     "0.004 s", "4 s", "0.04 s", "250 s", "A",
     "T = 1/f = 1/250 = 0.004 s.", "1/250"),
    (T_WAVE, "Easy", "Sound waves are",
     "longitudinal waves", "transverse waves", "electromagnetic waves", "mechanical transverse waves", "A",
     "Sound particles vibrate along the direction the wave travels.", None),
    (T_WAVE, "Easy", "Light waves and radio waves are both",
     "electromagnetic transverse waves", "longitudinal mechanical waves", "sound waves", "stationary waves", "A",
     "They are parts of one electromagnetic family needing no medium.", None),
    (T_WAVE, "Medium", "A boy claps and hears the echo from a cliff 2 s later. If sound travels at 340 m/s, the cliff is",
     "340 m away", "680 m away", "170 m away", "1,360 m away", "A",
     "The sound travels there and back: d = (340 × 2) ÷ 2 = 340 m.", "340*2/2"),
    (T_WAVE, "Medium", "The pitch of a note depends on its",
     "frequency", "amplitude", "speed", "wavelength only", "A",
     "Higher frequency is heard as a higher pitch.", None),
    (T_WAVE, "Easy", "The loudness of a sound depends mainly on its",
     "amplitude", "frequency", "speed", "harmonics only", "A",
     "A bigger amplitude carries more energy and sounds louder.", None),
    (T_WAVE, "Easy", "The bell-in-a-vacuum-jar experiment shows that sound",
     "cannot travel through a vacuum", "needs no medium", "travels faster in vacuum", "is an electromagnetic wave", "A",
     "As air is pumped out the ringing fades, though the hammer is still seen striking.", None),
    (T_WAVE, "Medium", "Sounds above the range of human hearing have frequencies greater than about",
     "20,000 Hz", "20 Hz", "2,000 Hz", "200 Hz", "A",
     "Audible sound spans roughly 20 Hz to 20,000 Hz; ultrasound lies above it.", "20000"),
    (T_WAVE, "Hard", "Which property of light waves shows they are transverse?",
     "They can be polarised", "They need a medium", "They travel at 340 m/s", "They cannot be reflected", "A",
     "Only transverse waves can be polarised; longitudinal waves cannot.", None),

    # --------------------------------------------------------------------- light
    (T_LIGHT, "Easy", "The image formed by a plane mirror is always",
     "virtual, upright, same size and laterally inverted", "real, inverted and laterally inverted always", "real, upright and smaller than the object", "virtual, inverted and the same size as the object", "A",
     "Plane mirror images are behind the mirror, same size, and reversed left to right.", None),
    (T_LIGHT, "Medium", "A girl stands 2 m in front of a plane mirror. The distance between her and her image is",
     "4 m", "2 m", "1 m", "8 m", "A",
     "The image lies 2 m behind the mirror, giving 2 + 2 = 4 m.", "2*2"),
    (T_LIGHT, "Easy", "A ray strikes a plane mirror at 35° to the normal. The angle of reflection is",
     "35°", "55°", "70°", "0°", "A",
     "The law of reflection: angle of incidence equals angle of reflection.", "35"),
    (T_LIGHT, "Medium", "A pencil partly dipped in water appears bent because light",
     "is refracted at the water surface", "is reflected by the water", "travels in a straight line", "is absorbed by the water", "A",
     "The speed change on entering water bends the rays, displacing the image.", None),
    (T_LIGHT, "Medium", "Light passes from air into glass of refractive index 1.5. If the angle of incidence is 45°, the angle of refraction is approximately",
     "28°", "45°", "62°", "14°", "A",
     "sin r = sin 45° ÷ 1.5 = 0.471, giving r ≈ 28°.", "math.degrees(math.asin(math.sin(math.radians(45))/1.5))"),
    (T_LIGHT, "Hard", "The critical angle for a glass of refractive index 1.5 is approximately",
     "42°", "30°", "48°", "60°", "A",
     "sin C = 1/n = 1/1.5, so C ≈ 41.8°, about 42°.", "math.degrees(math.asin(1/1.5))"),
    (T_LIGHT, "Medium", "Optical fibres transmit light over long distances by",
     "total internal reflection", "dispersion", "diffraction", "polarisation", "A",
     "Light hitting the fibre wall beyond the critical angle reflects with no loss.", None),
    (T_LIGHT, "Easy", "White light passed through a triangular prism splits into",
     "a spectrum of colours", "white and black rays", "infrared only", "two beams", "A",
     "Dispersion separates the colours because each bends by a different amount.", None),
    (T_LIGHT, "Medium", "In the dispersion of white light by a prism, the colour deviated least is",
     "red", "violet", "green", "blue", "A",
     "Red light has the longest wavelength and is refracted least.", None),
    (T_LIGHT, "Easy", "A concave mirror is used in a car headlamp because it",
     "reflects light from its focus into a parallel beam", "forms only virtual images for all positions", "spreads the incoming light in every direction", "absorbs the light that strikes its surface", "A",
     "A bulb at the principal focus reflects off the concave mirror as a parallel beam.", None),
    (T_LIGHT, "Medium", "A converging lens has a focal length of 0.25 m. Its power is",
     "+4 dioptres", "+0.25 dioptres", "+25 dioptres", "−4 dioptres", "A",
     "P = 1/f = 1/0.25 = 4 D, positive for a converging lens.", "1/0.25"),
    (T_LIGHT, "Hard", "An object is placed 20 cm from a concave mirror of focal length 15 cm. The image distance is",
     "60 cm", "12 cm", "35 cm", "7.5 cm", "A",
     "1/v = 1/f − 1/u = 1/15 − 1/20 = 1/60, so v = 60 cm in front of the mirror.", "1/(1/15-1/20)"),
    (T_LIGHT, "Medium", "A long-sighted person sees distant objects clearly but not near ones. The defect is corrected with a",
     "converging lens", "diverging lens", "concave mirror", "plain glass", "A",
     "The eyeball is too short, so a converging lens brings near rays to a focus on the retina.", None),
    (T_LIGHT, "Easy", "The image in a pinhole camera is",
     "inverted and real", "upright and virtual", "inverted and virtual", "upright and magnified", "A",
     "Rays crossing at the pinhole project a real, inverted image on the screen.", None),

    # ---------------------------------------------------------------- electricity
    (T_ELEC, "Easy", "When a glass rod is rubbed with silk, the rod becomes",
     "positively charged", "negatively charged", "neutral", "magnetic", "A",
     "Glass loses electrons to silk, leaving it with a positive charge.", None),
    (T_ELEC, "Easy", "Two like charges brought close together will",
     "repel each other", "attract each other", "not interact", "neutralise each other", "A",
     "Like charges repel; unlike charges attract.", None),
    (T_ELEC, "Medium", "The gold-leaf electroscope is used to",
     "detect the presence and sign of electric charge", "measure the size of an electric current", "measure the resistance of a wire segment", "store large amounts of charge for later use", "A",
     "Charge shared with the leaves makes them diverge, showing charge is present.", None),
    (T_ELEC, "Easy", "A lightning conductor protects a building by",
     "giving charge a safe path down into the earth", "stopping the thunder that follows lightning", "insulating the roof of the whole building", "reflecting the lightning back into the sky", "A",
     "Its pointed tip and thick earth wire channel the discharge harmlessly to ground.", None),
    (T_ELEC, "Medium", "A charge of 12 C flows through a wire in 4 s. The current is",
     "3 A", "48 A", "0.33 A", "8 A", "A",
     "Current is the rate of flow of charge: I = 12 ÷ 4 = 3 A.", "12/4"),
    (T_ELEC, "Easy", "A potential difference of 6 V drives a current through a 2 Ω resistor. The current is",
     "3 A", "12 A", "0.33 A", "6 A", "A",
     "Ohm's law: I = V/R = 6 ÷ 2 = 3 A.", "6/2"),
    (T_ELEC, "Medium", "Two 6 Ω resistors connected in parallel have a total resistance of",
     "3 Ω", "12 Ω", "6 Ω", "0.33 Ω", "A",
     "1/R = 1/6 + 1/6 = 1/3, so R = 3 Ω.", "1/(1/6+1/6)"),
    (T_ELEC, "Hard", "A 3 Ω resistor and a 6 Ω resistor are connected in parallel. The combined resistance is",
     "2 Ω", "9 Ω", "4.5 Ω", "18 Ω", "A",
     "1/R = 1/3 + 1/6 = 1/2, so R = 2 Ω.", "1/(1/3+1/6)"),
    (T_ELEC, "Easy", "An ammeter is connected in a circuit in",
     "series", "parallel", "series-parallel", "any position", "A",
     "The whole current must pass through the ammeter's low resistance.", None),
    (T_ELEC, "Easy", "A voltmeter is connected in a circuit in",
     "parallel with the component", "series with the component", "series with the battery only", "any position", "A",
     "Its high resistance lets it measure the p.d. across a component without diverting current.", None),
    (T_ELEC, "Medium", "A torch lamp draws 0.5 A from a 4 V supply. The power of the lamp is",
     "2 W", "8 W", "0.125 W", "4 W", "A",
     "Electrical power is voltage times current: 4 × 0.5 = 2 W.", "4*0.5"),
    (T_ELEC, "Hard", "A current of 2 A flows through a 5 Ω resistor. The power dissipated is",
     "20 W", "10 W", "2.5 W", "40 W", "A",
     "Using P = I²R with I = 2 A gives 4 × 5 = 20 W of heat.", "2**2*5"),
    (T_ELEC, "Hard", "A 2 kW heater runs for 3 hours. The energy consumed is",
     "6 kWh", "5 kWh", "2 kWh", "0.6 kWh", "A",
     "Energy = power × time = 2 × 3 = 6 kWh.", "2*3"),
    (T_ELEC, "Hard", "A family uses 6 kWh of electricity at ₦40 per kWh. The bill is",
     "₦240", "₦640", "₦46", "₦2,400", "A",
     "Six units at ₦40 each cost 6 × 40 = ₦240.", "6*40"),
    (T_ELEC, "Medium", "A fuse rated 5 A in a circuit will blow when the current",
     "exceeds 5 A", "falls below 5 A", "equals exactly 5 A always", "reverses direction", "A",
     "The fuse wire melts above its rating, protecting the appliance.", None),
    (T_ELEC, "Easy", "Electrical appliances are earthed so that",
     "any leakage current flows safely to the ground", "they draw a much smaller current overall", "their working parts last a lot longer", "they can work without a live wire fitted", "A",
     "The earth wire gives fault current an easy path, preventing shocks.", None),
    (T_ELEC, "Medium", "The resistance of a wire increases when its",
     "length increases or cross-sectional area decreases", "length decreases and area stays constant", "cross-sectional area of the wire increases", "temperature of the conductor falls a little", "A",
     "R = ρL/A: longer and thinner conductors resist more.", None),
    (T_ELEC, "Easy", "Which material allows electric current to pass through it easily?",
     "Copper", "Rubber", "Glass", "Dry wood", "A",
     "Copper is a good conductor with free electrons.", None),

    # -------------------------------------------------------- magnetism and EMI
    (T_MAG, "Easy", "Two north poles brought close together will",
     "repel each other", "attract each other", "do nothing", "demagnetise each other", "A",
     "Like magnetic poles repel one another.", None),
    (T_MAG, "Medium", "Outside a bar magnet, the magnetic field lines run from",
     "the north pole to the south pole", "the south pole to the north pole", "east to west", "the middle to both ends", "A",
     "By convention field lines leave the north-seeking pole and enter the south pole.", None),
    (T_MAG, "Easy", "The only metals attracted strongly by magnets are",
     "iron, nickel and cobalt", "copper, silver and gold", "aluminium and zinc", "lead and tin", "A",
     "Ferromagnetic materials are strongly attracted by magnets.", None),
    (T_MAG, "Medium", "The strength of an electromagnet is increased by",
     "increasing the current and the number of turns", "replacing the iron core with a plastic one", "reversing the terminals of the battery", "replacing the coil with a much thinner wire", "A",
     "More turns, more current and a soft iron core all strengthen the electromagnet.", None),
    (T_MAG, "Medium", "A compass needle comes to rest pointing",
     "along the earth's magnetic field", "towards the nearest mountain", "in any direction", "always downwards", "A",
     "The magnetised needle aligns itself with the earth's field, roughly north-south.", None),
    (T_MAG, "Hard", "A current-carrying conductor placed in a magnetic field experiences a force. This is the principle of the",
     "electric motor", "dynamo", "transformer", "electroscope", "A",
     "The motor effect converts electrical energy to mechanical rotation.", None),
    (T_MAG, "Hard", "A generator produces electricity by",
     "rotating a coil in a magnetic field", "chemical reactions in a cell", "heating a thermocouple", "storing charge on plates", "A",
     "Electromagnetic induction: a changing flux through the coil induces an EMF.", None),
    (T_MAG, "Hard", "A transformer has 1,200 primary turns and 480 secondary turns. If the primary voltage is 240 V, the secondary voltage is",
     "96 V", "600 V", "240 V", "48 V", "A",
     "Vs = Vp × Ns/Np = 240 × 480/1,200 = 96 V.", "240*480/1200"),
    (T_MAG, "Medium", "A step-up transformer has more turns on the",
     "secondary coil than the primary coil", "primary coil than the secondary", "core than the coils", "neither coil", "A",
     "More secondary turns raise the voltage delivered.", None),
    (T_MAG, "Medium", "Faraday's law of electromagnetic induction states that the induced EMF depends on the",
     "rate of change of magnetic flux", "size of the magnet", "resistance of the coil", "temperature of the core", "A",
     "Faster flux changes induce larger EMFs.", None),
    (T_MAG, "Easy", "In the domestic mains supply, the alternating current",
     "reverses its direction many times each second", "flows in only one direction at all times", "has no measurable voltage at any instant", "cannot be measured by any instrument", "A",
     "Nigerian mains AC reverses 50 times each second (50 Hz).", None),

    # ------------------------------------------------------------- modern physics
    (T_MOD, "Easy", "An alpha particle is identical with",
     "a helium nucleus", "an electron", "a proton only", "a light ray", "A",
     "Alpha particles carry two protons and two neutrons, with charge +2.", None),
    (T_MOD, "Easy", "A beta particle is a fast-moving",
     "electron", "proton", "neutron", "helium nucleus", "A",
     "Beta decay emits electrons created when a neutron changes into a proton.", None),
    (T_MOD, "Medium", "Which radiation has the greatest penetrating power?",
     "Gamma rays", "Alpha particles", "Beta particles", "Cathode rays", "A",
     "Gamma rays, being uncharged electromagnetic waves, pass through several cm of lead.", None),
    (T_MOD, "Hard", "A radioactive isotope has a half-life of 8 days. Starting with 16 g, the mass remaining after 32 days is",
     "1 g", "2 g", "4 g", "8 g", "A",
     "32 days is four half-lives, so 16 → 8 → 4 → 2 → 1 g.", "16/2**4"),
    (T_MOD, "Hard", "Uranium-238 emits an alpha particle. The mass number of the daughter nucleus is",
     "234", "236", "238", "230", "A",
     "Alpha emission removes 4 from the mass number: 238 − 4 = 234.", "238-4"),
    (T_MOD, "Medium", "The photoelectric effect shows that light behaves as",
     "packets of energy carried by particle-like photons", "continuous waves with no energy packets", "a magnetic field around a moving charge", "a kind of sound wave of very high pitch", "A",
     "Electrons are ejected only above a threshold frequency, one packet per photon.", None),
    (T_MOD, "Medium", "In the photoelectric effect, increasing the intensity of the light increases the",
     "number of electrons emitted per second", "kinetic energy of each electron", "threshold frequency", "work function", "A",
     "More photons per second free more electrons; each electron's energy depends on frequency.", None),
    (T_MOD, "Easy", "X-rays are produced when",
     "fast electrons strike a metal target", "sound hits a crystal", "light passes through glass", "magnets are heated", "A",
     "Sudden deceleration of electrons at the target converts kinetic energy into X-rays.", None),
    (T_MOD, "Medium", "Which is a medical use of X-rays?",
     "Detecting bone fractures", "Treating malaria", "Measuring blood pressure", "Testing hearing", "A",
     "X-rays pass through flesh but are absorbed by bone, imaging fractures.", None),
    (T_MOD, "Hard", "Nuclear fusion, the source of the sun's energy, is the",
     "joining of light nuclei into a heavier one", "splitting of a heavy nucleus", "burning of hydrogen gas", "capture of an electron", "A",
     "Hydrogen nuclei fuse into helium, releasing enormous energy.", None),
    (T_MOD, "Hard", "The half-life of a radioactive element is the time taken for",
     "half the atoms present to decay", "all atoms to decay", "the radiation to double", "the mass to melt", "A",
     "Each half-life halves whatever amount remains, whatever the starting mass.", None),
    (T_MOD, "Medium", "Thick lead shielding is used around radioactive sources because lead",
     "absorbs the radiation strongly", "reflects light", "is cheap and light", "is attracted to radiation", "A",
     "Lead's dense atoms absorb alpha, beta and much gamma radiation.", None),
]

if __name__ == "__main__":
    build_batch(
        S,
        "batch_048_waec_physics.json",
        "batch_048_waec_physics",
        "WAEC/NECO Physics Paper 1, round 1: full SSCE syllabus - measurements, "
        "motion, force and momentum, work/energy/power, machines, pressure and "
        "upthrust, heat, waves and sound, light, electricity, electromagnetism and "
        "modern physics. Every calculation machine-verified (g = 10 m/s2 where stated).",
        PASSAGES,
        PQ,
        Q,
        exam_type="WAEC",
    )
