"""Batch 042 - WAEC English, Paper 1 (Lexis & Structure), round 1.

Written to the WASSCE English Paper 1 scheme: eighty multiple-choice questions in one
hour — forty on LEXIS (word meaning, synonyms, antonyms, idioms, collocations) and
forty on STRUCTURE (grammar and sentence completion).  The topic names carry the
'Lexis —' / 'Structure —' prefix so the exam engine can build the real 40/40 split.

    python3 scripts/build_content_batch42.py -> content/batch_042_waec_english_lexis_structure.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "English"

T_SYN = "Lexis — Synonyms"
T_ANT = "Lexis — Antonyms"
T_CTX = "Lexis — Word Meaning in Context"
T_IDI = "Lexis — Idioms & Figurative Language"
T_COL = "Lexis — Collocations & Usage"
T_TEN = "Structure — Tense & Aspect"
T_AGR = "Structure — Subject-Verb Agreement"
T_PRE = "Structure — Prepositions"
T_CON = "Structure — Conjunctions & Linkers"
T_DET = "Structure — Determiners & Pronouns"
T_WOR = "Structure — Word Order & Transformation"
T_CLO = "Structure — Sentence Completion"

PASSAGES = []
PQ = []

Q = [
    # ------------------------------------------------------------------ synonyms
    (T_SYN, "Easy", "The chairman was OVERJOYED when the results were announced. A word closest in meaning to OVERJOYED is",
     "thrilled", "upset", "surprised", "worried",
     "A", "Overjoyed means extremely happy; thrilled is the nearest in meaning, while upset is almost the opposite."),
    (T_SYN, "Easy", "The clerk was noted for being METICULOUS in his work. METICULOUS means",
     "careful and precise", "careless", "very fast", "very loud",
     "A", "Meticulous describes someone who pays great attention to detail and is careful and precise."),
    (T_SYN, "Medium", "Supplies of food became SCARCE after the flood. SCARCE is closest in meaning to",
     "hard to find", "plentiful", "cheap", "fresh",
     "A", "Scarce means not enough to meet the need; hard to find captures that meaning."),
    (T_SYN, "Easy", "The crowd's reaction to the news was HOSTILE. A word nearest in meaning to HOSTILE is",
     "unfriendly", "excited", "curious", "silent",
     "A", "Hostile means showing opposition or unfriendliness; excited, curious and silent do not fit."),
    (T_SYN, "Medium", "Despite the injuries, the athlete was RESILIENT and returned to play. RESILIENT means",
     "able to recover quickly", "very strong", "very fast", "very aggressive",
     "A", "Resilient describes the ability to recover quickly from difficulty or injury."),
    (T_SYN, "Easy", "His FRUGAL habits allowed him to save for his children's fees. FRUGAL is closest in meaning to",
     "thrifty", "greedy", "wasteful", "rich",
     "A", "Frugal means using money or resources carefully, the same as thrifty; wasteful is the opposite."),
    (T_SYN, "Easy", "The DILIGENT student always finished her assignments early. DILIGENT means",
     "hardworking", "forgetful", "careless", "slow",
     "A", "Diligent means showing steady, careful effort in one's work — hardworking."),
    (T_SYN, "Medium", "The sky turned OMINOUS before the storm broke. OMINOUS is nearest in meaning to",
     "threatening", "clear", "bright", "calm",
     "A", "Ominous means giving the impression that something bad is going to happen — threatening."),
    (T_SYN, "Medium", "The minister was CANDID about the challenges facing the economy. CANDID means",
     "honest and direct", "angry", "silent", "clever",
     "A", "Candid means frank, honest and direct in saying what one thinks."),
    (T_SYN, "Easy", "The old bridge was ROBUST enough to carry heavy vehicles. ROBUST means",
     "strong and sturdy", "narrow", "weak", "old",
     "A", "Robust describes something strong and sturdy, built to withstand heavy use."),
    (T_SYN, "Easy", "The lecture was so TEDIOUS that half the students dozed off. TEDIOUS means",
     "boring", "interesting", "short", "important",
     "A", "Tedious means slow, long and dull — boring; the students' dozing confirms it."),
    (T_SYN, "Medium", "She was AVERSE to speaking in public. AVERSE is closest in meaning to",
     "unwilling", "delighted", "confident", "curious",
     "A", "Averse means strongly opposed or unwilling to do something."),
    (T_SYN, "Hard", "The beauty of the sunset was EPHEMERAL; it lasted only a few minutes. EPHEMERAL means",
     "short-lived", "permanent", "colourful", "bright",
     "A", "Ephemeral means lasting for a very short time — short-lived."),
    (T_SYN, "Medium", "The manager offered a COMPROMISE solution that satisfied both parties. COMPROMISE means",
     "middle-ground", "final", "harsh", "secret",
     "A", "A compromise is a solution where each side gives up something — a middle-ground result."),

    # ------------------------------------------------------------------ antonyms
    (T_ANT, "Easy", "The store was ABUNDANT with fresh produce. A word opposite in meaning to ABUNDANT is",
     "scarce", "fresh", "green", "local",
     "A", "Abundant means existing in large quantities; scarce (not enough) is the opposite."),
    (T_ANT, "Medium", "The judge was known to be BENEVOLENT towards first-time offenders. A word opposite in meaning to BENEVOLENT is",
     "cruel", "kind", "generous", "fair",
     "A", "Benevolent means kind and generous; cruel is the opposite."),
    (T_ANT, "Easy", "The soldier was COURAGEOUS when he entered the burning building. A word opposite in meaning to COURAGEOUS is",
     "timid", "strong", "brave", "bold",
     "A", "Courageous means brave and not afraid; timid (shy, easily frightened) is the opposite."),
    (T_ANT, "Easy", "The classroom was CHAOTIC during the fire drill. A word opposite in meaning to CHAOTIC is",
     "orderly", "noisy", "crowded", "bright",
     "A", "Chaotic means in complete disorder; orderly is the opposite."),
    (T_ANT, "Easy", "Her family was GENEROUS with food for the visitors. A word opposite in meaning to GENEROUS is",
     "selfish", "rich", "kind", "warm",
     "A", "Generous means willing to give freely; selfish (unwilling to share) is the opposite."),
    (T_ANT, "Medium", "He was very HUMBLE about his success. A word opposite in meaning to HUMBLE is",
     "arrogant", "quiet", "gentle", "modest",
     "A", "Humble means having a modest view of oneself; arrogant (excessively proud) is the opposite."),
    (T_ANT, "Easy", "The teacher was LENIENT about late submissions. A word opposite in meaning to LENIENT is",
     "strict", "angry", "slow", "kind",
     "A", "Lenient means not strict or severe; strict is the direct opposite."),
    (T_ANT, "Medium", "His house was MODEST in size but full of love. A word opposite in meaning to MODEST is",
     "grand", "small", "plain", "tidy",
     "A", "Modest here means not large or showy; grand (large and impressive) is the opposite."),
    (T_ANT, "Easy", "The manager was RIGID in his decision. A word opposite in meaning to RIGID is",
     "flexible", "firm", "stubborn", "hard",
     "A", "Rigid means not able to change or bend; flexible is the opposite."),
    (T_ANT, "Medium", "The school has always been TOLERANT of different customs. A word opposite in meaning to TOLERANT is",
     "intolerant", "friendly", "polite", "calm",
     "A", "Tolerant means accepting of other views and customs; intolerant refuses them."),
    (T_ANT, "Medium", "The market was TRANSIENT during the festival, closing after a few days. A word opposite in meaning to TRANSIENT is",
     "permanent", "busy", "noisy", "cheap",
     "A", "Transient means lasting only a short time; permanent (fixed, lasting) is the opposite."),
    (T_ANT, "Easy", "The hospital corridor was VACANT when the nurses took their break. A word opposite in meaning to VACANT is",
     "occupied", "dark", "clean", "long",
     "A", "Vacant means empty, not occupied; occupied is the direct opposite."),
    (T_ANT, "Medium", "Her apology was SINCERE and everyone forgave her. A word opposite in meaning to SINCERE is",
     "fake", "deep", "short", "public",
     "A", "Sincere means genuine and meant in good faith; fake (not genuine) is the opposite."),

    # ------------------------------------------------------------------ meaning in context
    (T_CTX, "Medium", "The old man's eyes were RHEUMY after the funeral. RHEUMY here means",
     "watery", "red", "blind", "sharp",
     "A", "Rheumy means filled with tears or mucus; watery fits a man who has been crying."),
    (T_CTX, "Medium", "The student's excuses were BIZARRE and nobody believed them. BIZARRE here means",
     "strange", "clever", "polite", "long",
     "A", "Bizarre means very strange or unusual; nobody would believe strange excuses."),
    (T_CTX, "Easy", "The road to the village was so BUMPY that our luggage fell out of the car. BUMPY here means",
     "full of holes", "narrow", "long", "closed",
     "A", "A bumpy road has many raised lumps or holes that shake a vehicle."),
    (T_CTX, "Medium", "The company LAY OFF many workers when orders fell. LAY OFF here means",
     "dismiss", "punish", "promote", "train",
     "A", "To lay off workers means to dismiss them from work, usually for economic reasons."),
    (T_CTX, "Easy", "The boy's behaviour was OUTRAGEOUS at the party. OUTRAGEOUS means",
     "shockingly bad", "calm", "quiet", "polite",
     "A", "Outrageous means shocking or far beyond what is acceptable — shockingly bad."),
    (T_CTX, "Medium", "If we wanted to keep our seats we had to PAY UP. PAY UP means",
     "pay the full amount", "borrow money", "save money", "spend slowly",
     "A", "Pay up means to pay the full amount that is owed, usually at once."),
    (T_CTX, "Hard", "His voice was TORN between joy and fear. TORN here means",
     "divided", "loud", "weak", "clear",
     "A", "Torn between two feelings means divided by them, not sure which dominates."),
    (T_CTX, "Medium", "The two brothers FELL OUT over the family land. FELL OUT means",
     "had a quarrel", "met again", "travelled far", "worked together",
     "A", "To fall out with someone means to have a quarrel and stop being friendly."),
    (T_CTX, "Easy", "The new policy is set to TAKE EFFECT from January. TAKE EFFECT means",
     "begin to operate", "fail", "change", "disappear",
     "A", "When a policy takes effect it formally begins to operate and apply."),
    (T_CTX, "Easy", "The student was SUSPENDED from school for fighting. SUSPENDED here means",
     "temporarily removed", "finely punished", "promoted", "excused",
     "A", "Suspension in school means being temporarily removed from classes as a punishment."),
    (T_CTX, "Easy", "The farmer's harvest was BOUNTIFUL this season. BOUNTIFUL means",
     "very large", "very small", "very late", "very poor",
     "A", "Bountiful means abundant; a bountiful harvest is a very large one."),
    (T_CTX, "Medium", "The child was SPOILED by too much attention from the grandparents. SPOILED here means",
     "pampered", "ruined", "lost", "tired",
     "A", "A spoiled child is one who has been pampered and given too much, so he behaves badly."),
    (T_CTX, "Hard", "The politician's promises were VACUOUS and meant nothing. VACUOUS means",
     "empty", "loud", "new", "clear",
     "A", "Vacuous means empty of real meaning or substance; the promises meant nothing."),
    (T_CTX, "Easy", "The team's performance was PATHETIC in the final match. PATHETIC means",
     "disappointingly poor", "amazing", "average", "exciting",
     "A", "Pathetic here means disappointingly poor or deserving of pity."),
    (T_CTX, "Hard", "Her explanation was CIRCUMLOCUTORY and wasted a lot of time. CIRCUMLOCUTORY means",
     "long-winded", "brief", "clear", "kind",
     "A", "Circumlocutory means using more words than necessary in an indirect way — long-winded."),
    (T_CTX, "Easy", "The news came as a SHOCK: the school was to close. SHOCK in this sentence means",
     "a sudden surprise", "anger", "fear", "pain",
     "A", "As a noun here, shock means a sudden unpleasant surprise that stuns people."),

    # ------------------------------------------------------------------ idioms
    (T_IDI, "Medium", "When asked about the plan, the clerk accidentally LET THE CAT OUT OF THE BAG. The expression means he",
     "revealed the secret", "lost his temper", "became angry", "ran away",
     "A", "To let the cat out of the bag means to reveal a secret, usually by mistake."),
    (T_IDI, "Easy", "That new phone COSTS AN ARM AND A LEG. The expression means it is",
     "very expensive", "very old", "very heavy", "very small",
     "A", "To cost an arm and a leg is a common idiom for being very expensive."),
    (T_IDI, "Medium", "You HIT THE NAIL ON THE HEAD when you said the problem was money. The expression means you",
     "spoke exactly right", "were angry", "were late", "were kind",
     "A", "To hit the nail on the head means to describe exactly what is causing a situation."),
    (T_IDI, "Easy", "We meet only ONCE IN A BLUE MOON. The expression means we meet",
     "very rarely", "every month", "very often", "at night",
     "A", "Once in a blue moon describes something that happens very rarely."),
    (T_IDI, "Easy", "I don't want to join the match; I'm UNDER THE WEATHER. The expression means I am",
     "feeling unwell", "in the shade", "cold", "wet",
     "A", "To be under the weather is an idiom for feeling slightly unwell or sick."),
    (T_IDI, "Medium", "The lawyer submitted the papers AT THE ELEVENTH HOUR. The expression means",
     "at the last moment", "at one o'clock", "very early", "in the morning",
     "A", "At the eleventh hour means at the very last possible moment, just before it is too late."),
    (T_IDI, "Medium", "Failing the first test turned out to be A BLESSING IN DISGUISE. The expression means it",
     "brought good results", "was a punishment", "was bad luck", "was a problem",
     "A", "A blessing in disguise is something that seems bad at first but later produces good results."),
    (T_IDI, "Easy", "My sister SPILLED THE BEANS about our surprise party. The expression means she",
     "told the secret", "cried", "was happy", "helped us",
     "A", "To spill the beans means to tell a secret or reveal information that should be kept."),
    (T_IDI, "Easy", "The test was A PIECE OF CAKE for the class topper. The expression means it was",
     "very easy", "very difficult", "very long", "very new",
     "A", "A piece of cake is an idiom meaning something very easy to do."),
    (T_IDI, "Medium", "The new teacher BROKE THE ICE with a joke at the first lesson. The expression means she",
     "started a conversation", "told a lie", "became cold", "left early",
     "A", "To break the ice means to ease tension and start a friendly conversation."),
    (T_IDI, "Hard", "He is BARKING UP THE WRONG TREE if he thinks I did it. The expression means he",
     "is accusing the wrong person", "is barking loudly", "is very angry", "is lost",
     "A", "Barking up the wrong tree means to pursue a mistaken line of thought or accusation."),
    (T_IDI, "Medium", "The family stayed together THROUGH THICK AND THIN. The expression means",
     "in good times and bad", "for a long time", "far away from home", "with great difficulty",
     "A", "Through thick and thin means in all circumstances, both good and bad."),
    (T_IDI, "Medium", "After the crash, the old car was DEAD AS A DOORNAIL. The expression means it was",
     "completely finished", "very fast", "very new", "very loud",
     "A", "Dead as a doornail means completely dead or, for an object, totally useless."),
    (T_IDI, "Medium", "She PUT HER FOOT IN IT when she insulted the guest. The expression means she",
     "made a social mistake", "fell down", "was cold", "was wrong",
     "A", "To put one's foot in it means to say or do something tactless and embarrassing."),
    (T_IDI, "Medium", "The two farmers are IN THE SAME BOAT during this election. The expression means they",
     "share the same situation", "are swimming", "are close friends", "are fighting",
     "A", "In the same boat means in the same difficult situation, with the same risks."),

    # ------------------------------------------------------------------ collocations
    (T_COL, "Easy", "The government has decided to ____ the price of fuel.",
     "raise", "lift", "bring", "make",
     "A", "The correct collocation is to raise a price (or to increase it); lift and bring do not take 'price'."),
    (T_COL, "Easy", "Students must ____ their projects by Friday.",
     "submit", "do", "take", "make",
     "A", "We submit an assignment, project or application; the other verbs do not collocate with 'projects' here."),
    (T_COL, "Easy", "The police want to ____ the man who stole the car.",
     "arrest", "fine", "release", "warn",
     "A", "The police arrest a criminal; they may fine or warn minor offenders, but arrest fits a thief."),
    (T_COL, "Medium", "The board ____ a new manager to run the sales department.",
     "appointed", "made", "did", "took",
     "A", "A company appoints someone to a job or position; made, did and took do not collocate here."),
    (T_COL, "Easy", "The school ____ the inter-house sports this year.",
     "organized", "made", "did", "took",
     "A", "We organize an event such as a sports competition; the other verbs are not used with events."),
    (T_COL, "Medium", "The government will ____ measures to reduce traffic.",
     "take", "make", "do", "bring",
     "A", "The fixed expression is to take measures (or to take action) to deal with a problem."),
    (T_COL, "Easy", "The company ____ a lot of money on advertising.",
     "spent", "took", "gave", "paid",
     "A", "You spend money on something; 'paid' needs a person as object (paid the workers)."),
    (T_COL, "Easy", "The hall must stay clean; don't ____ a mess.",
     "make", "do", "have", "take",
     "A", "The correct collocation is to make a mess; we do not 'do', 'have' or 'take' a mess."),
    (T_COL, "Medium", "The judge ____ the man to ten years in prison.",
     "sentenced", "punished", "gave", "made",
     "A", "A judge sentences a prisoner to a term; 'sentenced to ten years' is the legal collocation."),
    (T_COL, "Easy", "The students ____ the visit to the museum.",
     "enjoyed", "did", "took", "made",
     "A", "We enjoy a visit, trip or game; the other verbs do not collocate with 'the visit'."),
    (T_COL, "Easy", "The firemen ____ the fire before it spread to the next building.",
     "put out", "put off", "put up", "put in",
     "A", "To put out a fire means to make it stop burning; the other phrasal verbs mean different things."),
    (T_COL, "Medium", "You will ____ a lot from this lesson.",
     "benefit", "win", "gain", "get",
     "A", "The formal collocation is to benefit from something; 'benefit a lot' fits best here."),
    (T_COL, "Easy", "The team ____ the final match 3–1.",
     "won", "beat", "hit", "took",
     "A", "You win a match or game; 'beat' is used with a person or team (beat the rivals)."),
    (T_COL, "Easy", "The news ____ quickly, and the whole village came out.",
     "spread", "grew", "ran", "walked",
     "A", "News spreads from person to person; it does not grow, run or walk."),
    (T_COL, "Easy", "She always ____ good care of her younger brother.",
     "takes", "makes", "gives", "does",
     "A", "The fixed expression is to take care of someone; we also say 'look after', not 'make care'."),
    (T_COL, "Medium", "The bank will not ____ a loan to anyone without security.",
     "grant", "sell", "make", "buy",
     "A", "A bank grants (or gives) a loan; it does not sell, make or buy one for a customer."),
    (T_COL, "Medium", "The law ____ everyone to pay taxes.",
     "requires", "suggests", "hopes", "dreams",
     "A", "The law requires or obliges people to do something; suggests, hopes and dreams are too weak."),
    (T_COL, "Easy", "The singer ____ a new song for the festival.",
     "released", "did", "took", "carried",
     "A", "Artists release a song or album to the public; the other verbs do not fit."),
    (T_COL, "Easy", "The thief ____ the window to enter the house.",
     "broke", "damaged", "hit", "made",
     "A", "The thief broke the window; 'break' is the verb used with glass in this context."),
    (T_COL, "Easy", "You should ____ your hands before eating.",
     "wash", "bathe", "dry", "shake",
     "A", "The standard expression is to wash your hands before eating; the other verbs do not fit."),
    (T_COL, "Medium", "The doctor ____ the patient to rest for a week.",
     "advised", "warned", "suggested", "promised",
     "A", "The doctor advised the patient to rest; 'suggest' cannot take 'person + to-infinitive' like this."),
    (T_COL, "Medium", "WAEC is an ____ examination taken at the end of secondary school.",
     "external", "internal", "private", "school",
     "A", "WAEC is an external examination (set by an outside body); school-set tests are internal."),

    # ------------------------------------------------------------------ tense
    (T_TEN, "Medium", "By the time the police arrived, the thieves ____.",
     "had fled", "fled", "have fled", "will flee",
     "A", "The fleeing happened before the police arrived in the past, so the past perfect 'had fled' is required."),
    (T_TEN, "Easy", "She has lived in this house ____ 2015.",
     "since", "for", "from", "during",
     "A", "Since is used with a point in time (2015); for is used with a period (eight years)."),
    (T_TEN, "Medium", "They ____ English for three years now.",
     "have studied", "studied", "study", "are studying",
     "A", "An action that started in the past and continues 'now' takes the present perfect: have studied."),
    (T_TEN, "Easy", "While I ____ home, I met an old friend.",
     "was walking", "walked", "walk", "have walked",
     "A", "A longer background action in the past is put in the past continuous: was walking."),
    (T_TEN, "Medium", "The train ____ at six o'clock tomorrow morning.",
     "leaves", "will leaving", "leaved", "has left",
     "A", "Timetabled future events use the simple present: the train leaves at six o'clock."),
    (T_TEN, "Easy", "If it rains, we ____ the match.",
     "will cancel", "cancel", "would cancel", "cancelled",
     "A", "In a first conditional, the if-clause is present and the main clause takes will + verb: will cancel."),
    (T_TEN, "Medium", "He ____ his keys, so he could not open the door.",
     "had lost", "has lost", "loses", "will lose",
     "A", "Losing the keys happened before he failed to open the door, so the past perfect is used: had lost."),
    (T_TEN, "Easy", "Look! The baby ____.",
     "is sleeping", "sleeps", "slept", "has slept",
     "A", "'Look!' shows the action is happening now, so the present continuous is needed: is sleeping."),
    (T_TEN, "Hard", "By next week, we ____ the results.",
     "will have received", "received", "receive", "have received",
     "A", "An action completed before a future point uses the future perfect: will have received."),
    (T_TEN, "Easy", "When I was a child, I ____ my grandmother every weekend.",
     "visited", "visit", "am visiting", "have visited",
     "A", "A repeated past habit uses the simple past: visited."),
    (T_TEN, "Medium", "The books ____ by the teacher yesterday.",
     "were checked", "are checked", "have been checked", "were checking",
     "A", "A finished passive action at a past time uses was/were + past participle: were checked."),
    (T_TEN, "Medium", "This is the best film I ____ this year.",
     "have seen", "saw", "see", "will see",
     "A", "A period that is still open ('this year') takes the present perfect: have seen."),
    (T_TEN, "Medium", "He ____ in Lagos until 2020, then moved to Abuja.",
     "lived", "has lived", "is living", "lives",
     "A", "A completed past period before another past event uses the simple past: lived."),
    (T_TEN, "Medium", "The bridge was damaged last month; it ____ since then.",
     "has been repaired", "was repaired", "is repairing", "repairs",
     "A", "'Since then' links a past event to now, so the present perfect passive is used: has been repaired."),

    # ------------------------------------------------------------------ agreement
    (T_AGR, "Medium", "Neither the students nor the teacher ____ present.",
     "was", "were", "are", "have been",
     "A", "With neither...nor, the verb agrees with the nearer subject 'teacher' (singular): was."),
    (T_AGR, "Easy", "Each of the boys ____ a book.",
     "has", "have", "are", "were",
     "A", "'Each of' is always singular, so the verb takes the singular form: has."),
    (T_AGR, "Medium", "The number of students in the class ____ this term.",
     "has increased", "have increased", "are increasing", "were increasing",
     "A", "'The number of' is singular (the number itself increased); 'a number of' would be plural."),
    (T_AGR, "Medium", "A number of teachers ____ at the meeting.",
     "were", "was", "is", "has been",
     "A", "'A number of' means 'many' and takes a plural verb: were."),
    (T_AGR, "Easy", "Each of the girls ____ given a gift.",
     "was", "were", "are", "have been",
     "A", "'Each of the girls' is singular, so the correct verb is the singular 'was'."),
    (T_AGR, "Easy", "Mathematics ____ my favourite subject.",
     "is", "are", "were", "be",
     "A", "Subjects of study such as mathematics are treated as singular: is."),
    (T_AGR, "Easy", "The news ____ true.",
     "is", "are", "were", "be",
     "A", "'News' ends in -s but is singular in English: the news is true."),
    (T_AGR, "Medium", "The furniture in the room ____ old.",
     "is", "are", "were", "be",
     "A", "'Furniture' is an uncountable noun and always takes a singular verb: is."),
    (T_AGR, "Medium", "There ____ a book and two pens on the table.",
     "is", "are", "were", "be",
     "A", "With 'there is/are' and a list, the verb agrees with the nearest item: a book, so 'is'."),
    (T_AGR, "Medium", "The herd of cattle ____ grazing in the field.",
     "is", "are", "were", "be",
     "A", "The collective noun 'herd' acts as one unit here, so the singular verb 'is' is used."),
    (T_AGR, "Medium", "Every student and teacher ____ invited to the ceremony.",
     "was", "were", "are", "have been",
     "A", "Subjects joined by 'and' after 'every' are treated as one: every student and teacher was."),
    (T_AGR, "Hard", "The rest of the money ____ gone.",
     "has", "have", "are", "were",
     "A", "'Money' is uncountable, so 'the rest of the money' takes the singular verb: has gone."),

    # ------------------------------------------------------------------ prepositions
    (T_PRE, "Easy", "He was accused ____ stealing money.",
     "of", "for", "with", "about",
     "A", "The correct preposition is 'accused of' + noun/gerund; 'charged with' is a different pattern."),
    (T_PRE, "Easy", "She is very interested ____ learning French.",
     "in", "on", "about", "at",
     "A", "The fixed expression is 'interested in' + noun/gerund."),
    (T_PRE, "Medium", "The success of the project depends ____ everyone's effort.",
     "on", "in", "with", "by",
     "A", "The verb 'depend' always takes the preposition 'on': depends on everyone's effort."),
    (T_PRE, "Easy", "He is very good ____ mathematics.",
     "at", "in", "on", "for",
     "A", "The collocation is 'good at' + subject/skill (also 'bad at')."),
    (T_PRE, "Easy", "As a child, she was afraid ____ the dark.",
     "of", "from", "with", "by",
     "A", "The fixed expression is 'afraid of' + noun."),
    (T_PRE, "Easy", "They got married ____ 2019.",
     "in", "on", "at", "by",
     "A", "We use 'in' with years, months and seasons: married in 2019."),
    (T_PRE, "Easy", "He is proud ____ his son's achievement.",
     "of", "for", "with", "about",
     "A", "The fixed expression is 'proud of' + noun."),
    (T_PRE, "Medium", "The manager is responsible ____ the new office.",
     "for", "of", "to", "with",
     "A", "The collocation is 'responsible for' + noun or gerund."),
    (T_PRE, "Medium", "Despite the rain, he insisted ____ playing.",
     "on", "in", "at", "by",
     "A", "The verb 'insist' takes 'on': insisted on playing."),
    (T_PRE, "Easy", "All students must participate ____ the exercise.",
     "in", "on", "at", "by",
     "A", "The verb 'participate' always takes 'in': participate in the exercise."),
    (T_PRE, "Medium", "She is capable ____ doing the work alone.",
     "of", "to", "for", "with",
     "A", "The adjective 'capable' is followed by 'of' + gerund: capable of doing."),
    (T_PRE, "Easy", "Your answer is different ____ mine.",
     "from", "than", "to", "as",
     "A", "In formal English, 'different' is followed by 'from': different from mine."),

    # ------------------------------------------------------------------ conjunctions
    (T_CON, "Easy", "____ he was tired, he finished the work.",
     "Although", "Because", "So", "But",
     "A", "Although introduces a contrast (tired, yet finished); because would give the wrong logic."),
    (T_CON, "Easy", "She studied hard, ____ she passed the exam.",
     "so", "but", "although", "while",
     "A", "Passing is the result of studying hard, so the result linker 'so' is needed."),
    (T_CON, "Medium", "The two brothers have different views; one supports the plan, ____ opposes it.",
     "the other", "another", "other", "others",
     "A", "With exactly two people, we use 'one ... the other'; 'another' means an additional one."),
    (T_CON, "Medium", "We left early ____ we could avoid the traffic.",
     "so that", "because", "although", "even though",
     "A", "'So that' + could expresses purpose: we left early in order to avoid traffic."),
    (T_CON, "Medium", "He bought a new car ____ his salary was low.",
     "even though", "because", "so", "therefore",
     "A", "The contrast (bought a car despite a low salary) needs the concession linker 'even though'."),
    (T_CON, "Easy", "You can have tea ____ coffee.",
     "or", "and", "but", "nor",
     "A", "When choosing between two things, we use 'or': tea or coffee."),
    (T_CON, "Medium", "____ did he come, nor did he call.",
     "Neither", "Either", "Both", "All",
     "A", "The paired correlative is 'neither ... nor', so the sentence opens with 'Neither'."),
    (T_CON, "Medium", "The examination was cancelled ____ the heavy rain.",
     "due to", "because", "so", "although",
     "A", "'Because' needs a clause; before the noun phrase 'the heavy rain' we use 'due to'."),
    (T_CON, "Easy", "She was late ____ she had missed the bus.",
     "because", "although", "so", "but",
     "A", "Missing the bus is the reason for being late, so the cause linker 'because' is correct."),
    (T_CON, "Hard", "Not only ____ the test, but he also topped the class.",
     "did he pass", "he passed", "he passing", "passing he",
     "A", "After the negative 'not only' at the start, the auxiliary comes before the subject: did he pass."),
    (T_CON, "Medium", "We were about to leave ____ it started to rain.",
     "when", "while", "because", "so",
     "A", "'Was/were about to + verb, when ...' describes an interrupted plan: when it started to rain."),
    (T_CON, "Easy", "____ of the two options is correct.",
     "Neither", "None", "No", "Both",
     "A", "With two items and a singular verb, 'Neither ... is' is correct; 'none' is for three or more."),

    # ------------------------------------------------------------------ determiners & pronouns
    (T_DET, "Easy", "____ boy standing at the door is my brother.",
     "The", "A", "An", "Some",
     "A", "A specific boy (the one at the door) is referred to, so the definite article 'the' is needed."),
    (T_DET, "Easy", "She has ____ apple in her bag.",
     "an", "a", "the", "some",
     "A", "'Apple' begins with a vowel sound, so the indefinite article 'an' is used."),
    (T_DET, "Medium", "I lost my wallet; can you lend me ____ to get home?",
     "some", "few", "many", "much",
     "A", "With an uncountable noun in a request where a yes answer is hoped for, 'some' is used."),
    (T_DET, "Easy", "The books on the table are ____.",
     "ours", "our", "us", "ourselves",
     "A", "A possessive pronoun that stands alone after 'are' is needed: ours."),
    (T_DET, "Medium", "____ of the students passed the test.",
     "All", "Every", "Each", "None",
     "A", "'Every' and 'each' take singular verbs; the plural 'passed' matches 'All of the students'."),
    (T_DET, "Easy", "____ was at the party, so we all had fun.",
     "Everyone", "Every", "All", "Each",
     "A", "'Everyone' is a singular pronoun meaning all the people; 'every' alone cannot stand as subject."),
    (T_DET, "Medium", "The man ____ car was stolen called the police.",
     "whose", "who", "whom", "which",
     "A", "'Whose' shows possession in a relative clause: the man whose car was stolen."),
    (T_DET, "Easy", "The girl ____ won the prize is from this school.",
     "who", "whom", "whose", "which",
     "A", "The relative pronoun is the subject of 'won', referring to a person: who."),
    (T_DET, "Easy", "They met each other ____ the first day at school.",
     "on", "in", "at", "by",
     "A", "We use 'on' with days and dates: on the first day."),
    (T_DET, "Medium", "____ of the twins is a doctor.",
     "Each", "Both", "Every", "All",
     "A", "The singular verb 'is' requires the singular subject 'Each'; 'Both ... are' would be plural."),
    (T_DET, "Medium", "I have two brothers, and ____ of them lives abroad.",
     "each", "both", "all", "neither",
     "A", "The singular verb 'lives' matches 'each of them'; 'both' and 'all' would take 'live'."),
    (T_DET, "Easy", "The letter was addressed ____ the manager.",
     "to", "for", "with", "by",
     "A", "A letter is addressed to a person: addressed to the manager."),

    # ------------------------------------------------------------------ word order
    (T_WOR, "Medium", "No sooner had he arrived ____ the phone rang.",
     "than", "when", "as", "but",
     "A", "'No sooner ... than' is the fixed pair; 'hardly ... when' is the other pattern."),
    (T_WOR, "Medium", "____ does she like music that she plays the piano.",
     "So", "Such", "Too", "Very",
     "A", "The 'so ... that' structure expresses degree and result: so does she like music that ..."),
    (T_WOR, "Easy", "He is so kind ____ everyone trusts him.",
     "that", "as", "than", "which",
     "A", "'So + adjective + that' introduces the result: so kind that everyone trusts him."),
    (T_WOR, "Hard", "Hardly ____ the house when it began to rain.",
     "had I left", "I left", "I had left", "did I leave",
     "A", "After 'hardly' at the start, invert with the auxiliary: hardly had I left the house."),
    (T_WOR, "Medium", "Choose the most appropriate sentence.",
     "The harder you study, the better you perform.",
     "The hard you study, the well you perform.",
     "Harder you study, better you perform.",
     "The more you study, the best you perform.",
     "A", "The comparative pair needs 'the + comparative ... the + comparative': the harder ... the better."),
    (T_WOR, "Easy", "She can swim, ____?",
     "can't she", "doesn't she", "isn't she", "didn't she",
     "A", "A question tag repeats the auxiliary of the statement with the opposite polarity: can't she."),
    (T_WOR, "Easy", "They haven't finished, ____?",
     "have they", "don't they", "aren't they", "hadn't they",
     "A", "The auxiliary 'have' (in its negative form) is repeated with a positive tag: have they."),
    (T_WOR, "Medium", "I have never seen such a beautiful view. The correct tag is",
     "have I", "do I", "am I", "was I",
     "A", "With the present perfect and the negative word 'never', the tag is positive: have I."),
    (T_WOR, "Medium", "What surprised me was ____ the test was so easy.",
     "that", "which", "because", "so",
     "A", "A noun clause that completes 'was' is introduced by 'that': was that the test was so easy."),
    (T_WOR, "Hard", "Choose the sentence with the correct word order.",
     "Rarely have I had such luck.",
     "Rarely I have had such luck.",
     "Rarely had I have such luck.",
     "Rarely I had have such luck.",
     "A", "A negative adverb at the start triggers inversion: rarely have I had such luck."),
    (T_WOR, "Easy", "This is ____ film I have ever seen.",
     "the best", "best", "a better", "the better",
     "A", "A superlative comparison needs 'the + superlative': the best film."),
    (T_WOR, "Medium", "Her answer was ____ than mine.",
     "more correct", "correcter", "more correctly", "much correct",
     "A", "'Correct' is a flat adjective in standard usage, so its comparative is 'more correct'."),

    # ------------------------------------------------------------------ sentence completion
    (T_CLO, "Medium", "If I ____ you, I would accept the offer.",
     "were", "was", "am", "would be",
     "A", "The second conditional uses 'if + past subjunctive': if I were you, I would ..."),
    (T_CLO, "Easy", "He spoke loudly ____ everyone in the room could hear him.",
     "so that", "because", "although", "if",
     "A", "'So that' + could expresses purpose: he spoke loudly in order that everyone could hear."),
    (T_CLO, "Medium", "The police are investigating the accident to find out what ____.",
     "happened", "happens", "will happen", "had happen",
     "A", "The accident is a finished past event, so the reported clause uses the simple past: what happened."),
    (T_CLO, "Easy", "She has been working here ____ ten years.",
     "for", "since", "from", "by",
     "A", "'For' is used with a period of time (ten years); 'since' is used with a starting point."),
    (T_CLO, "Medium", "____ it is late, let's continue working.",
     "Even though", "Because", "So", "But",
     "A", "The sentence concedes that it is late, so the concession linker 'even though' fits."),
    (T_CLO, "Easy", "The book ____ I borrowed from the library is very interesting.",
     "which", "who", "whom", "whose",
     "A", "A thing (book) that is the object of 'borrowed' takes the relative pronoun 'which'."),
    (T_CLO, "Easy", "He promised ____ help me with my project.",
     "to", "for", "in", "at",
     "A", "'Promise' is followed by the to-infinitive: promised to help."),
    (T_CLO, "Easy", "We must be quiet, ____ the baby is sleeping.",
     "because", "although", "so", "but",
     "A", "The baby sleeping is the reason for being quiet, so the cause linker 'because' is used."),
    (T_CLO, "Medium", "The more I think about it, ____ sense it makes.",
     "the more", "more", "most", "much",
     "A", "The double comparative pattern needs 'the more ... the more': the more sense it makes."),
    (T_CLO, "Hard", "By next year, they ____ the new bridge.",
     "will have built", "will build", "built", "have built",
     "A", "A project completed before a future point uses the future perfect: will have built."),
    (T_CLO, "Medium", "She denied ____ the money.",
     "taking", "to take", "take", "taken",
     "A", "'Deny' is followed by a gerund: denied taking the money."),
    (T_CLO, "Easy", "He was too tired ____ any more work.",
     "to do", "doing", "do", "for doing",
     "A", "The 'too + adjective + to-infinitive' pattern is needed: too tired to do."),
    (T_CLO, "Medium", "I look forward ____ from you soon.",
     "to hearing", "hearing", "hear", "to hear",
     "A", "'Look forward to' uses a gerund after the preposition 'to': to hearing from you."),
    (T_CLO, "Easy", "The examination is ____ difficult for most students.",
     "quite", "very much", "real", "too much",
     "A", "An adjective like 'difficult' is modified by 'quite'; 'very much' is used with verbs or past participles."),
    (T_CLO, "Medium", "We ____ to leave early tomorrow.",
     "are supposed", "are supposing", "supposing", "was supposed",
     "A", "The fixed expression is 'be supposed to' + verb: we are supposed to leave early."),
    (T_CLO, "Medium", "____ the bad weather, the flight was not cancelled.",
     "Despite", "Although", "However", "Therefore",
     "A", "Before a noun phrase we need the preposition 'despite'; 'although' needs a full clause."),
    (T_CLO, "Medium", "She is the girl ____ I mentioned in my letter.",
     "whom", "which", "whose", "what",
     "A", "The relative pronoun is the object of 'mentioned', referring to a person: whom."),
]

FIX = {}
deactivate = None
retire_topics = None

build_batch(S, "batch_042_waec_english_lexis_structure.json", "batch_042_waec_english_lexis_structure",
            "WAEC English Paper 1 (Lexis & Structure) round 1: 80 lexis + 80 structure items in WASSCE style.",
            PASSAGES, PQ, Q, FIX, deactivate, retire_topics, exam_type="WAEC")
