"""Batch 013 - Biology round 3 (JAMB syllabus, applied/experimental style).

Four data passages (quadrat count, food tests, germination set-ups, potometer readings) and ~155
stand-alone items across the whole syllabus. Numerical answers (densities, ratios, genetics) are
verified in Python before the file is written.

    python3 scripts/build_content_batch13.py -> content/batch_013_biology_round3.json
"""
import json
import math
import re
import textwrap
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_content_batch1 import _balance, _num  # noqa: E402
from distractor_fixes import apply_fixes  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "content", "batch_013_biology_round3.json")
S = "Biology"

# ---------------------------------------------------------------------------
# Data passages (runs of 3+ spaces between columns render as a monospace table)
# ---------------------------------------------------------------------------
PASSAGES = [
    ("B1", "Ecology", "Quadrat study of a school field",
     "A student threw a 1 m² quadrat at random ten times on a school field of area 500 m² and "
     "recorded the number of each plant species inside the quadrat at every throw. The totals for "
     "the ten throws are shown below.\n\n"
     "Species              Total count\n"
     "Elephant grass           120\n"
     "Sida (broom weed)         60\n"
     "Tridax                    40\n"
     "Goat weed                 20"),
    ("B2", "Nutrition", "Food tests on four samples",
     "Four food samples, W, X, Y and Z, were tested in the laboratory. The results are shown below "
     "(+ means a positive result, - means negative).\n\n"
     "Test                  W    X    Y    Z\n"
     "Iodine solution       +    -    -    +\n"
     "Benedict's solution   -    +    -    -\n"
     "Biuret test           -    +    +    +\n"
     "Sudan III             -    +    +    -"),
    ("B3", "Growth", "Germination of bean seeds",
     "Five test tubes, each containing five bean seeds on cotton wool, were kept for one week under "
     "the conditions described below. In tube E the seeds were covered with boiled, cooled water "
     "and a layer of oil.\n\n"
     "Tube   Conditions              Result\n"
     "A      moist, warm, light      all grew\n"
     "B      moist, warm, dark       all grew\n"
     "C      dry, warm, light        none\n"
     "D      moist, in a fridge      none\n"
     "E      moist, warm, no air     none"),
    ("B4", "Transport", "Transpiration measured with a potometer",
     "A leafy shoot was set up in a potometer and the distance moved by the air bubble in ten "
     "minutes was recorded under four different conditions.\n\n"
     "Condition                 Distance (mm)\n"
     "Still air, shade               12\n"
     "Still air, sunlight            30\n"
     "Fan blowing, sunlight          55\n"
     "Leaves coated with\n"
     "  vaseline, sunlight            4"),
]

# (passage, difficulty, q, A, B, C, D, answer, explanation, verify)
PQ = [
    ("B1", "Medium", "From the quadrat data above, the estimated population of Tridax on the whole field is",
     "40", "400", "2,000", "20,000", "C",
     "Density = 40 plants in 10 m² = 4 per m²; population = 4 × 500 m² = 2,000 plants.", "40/10*500"),
    ("B1", "Easy", "From the quadrat data above, the species with the highest population density is",
     "Elephant grass", "Sida", "Tridax", "Goat weed", "A",
     "Elephant grass had 120 plants in 10 m² (12 per m²), the highest count of the four species."),
    ("B1", "Medium", "In the quadrat study above, the quadrat was thrown at random in order to",
     "cover the whole field quickly", "avoid bias in choosing the sample areas", "count only the tallest plants", "protect the student from insects", "B",
     "Random sampling ensures every part of the field has an equal chance of being sampled, so the estimate is not biased."),
    ("B1", "Medium", "From the quadrat data above, the total density of all plants on the field is",
     "24 per m²", "240 per m²", "48 per m²", "2.4 per m²", "A",
     "Total plants counted = 120 + 60 + 40 + 20 = 240 in ten 1 m² quadrats, i.e. 24 plants per m².", "240/10"),
    ("B1", "Medium", "The quadrat method used in the study above would be least suitable for estimating the population of",
     "grasses on a lawn", "birds nesting in the trees round the field", "snails on the field", "weeds in a farm", "B",
     "Quadrats suit plants and slow-moving or sessile animals; birds move too fast and too far to be counted in a fixed frame."),
    ("B2", "Easy", "From the food-test results above, the sample that contains starch only is",
     "W", "X", "Y", "Z", "A",
     "W gives a positive iodine test (starch) and is negative for the other three tests. Z also contains starch, but its positive Biuret test shows that it contains protein as well."),
    ("B2", "Medium", "From the food-test results above, sample Y is most likely",
     "boiled yam", "groundnut paste", "glucose solution", "pap (ogi)", "B",
     "Y is positive for protein (Biuret) and fat (Sudan III); groundnuts are rich in both protein and oil."),
    ("B2", "Medium", "From the food-test results above, sample X could be",
     "fresh milk", "palm oil", "cassava flour", "distilled water", "A",
     "X contains reducing sugar (lactose), protein and fat, the three food classes found in milk; Y has no sugar, so it is not milk."),
    ("B2", "Easy", "In the food tests above, a positive Biuret test is shown by a colour change to",
     "blue-black", "brick red", "purple or violet", "translucent yellow", "C",
     "Biuret reagent turns purple/violet with proteins; blue-black is iodine with starch and brick red is Benedict's with reducing sugar."),
    ("B2", "Medium", "In the food tests above, before the Benedict's result for X could be read, the mixture of X and Benedict's solution had to be",
     "cooled in ice", "heated in a water bath", "left in the dark", "shaken with oil", "B",
     "Benedict's test only works when the food and reagent are heated; a brick-red precipitate then shows reducing sugar."),
    ("B3", "Medium", "In the germination experiment above, a comparison of tubes A and B shows that",
     "light is not necessary for germination", "light is essential for germination", "warmth is not necessary for germination", "seeds germinate faster in the dark", "A",
     "A and B differ only in light, yet both sets germinated, so light is not a requirement for germination."),
    ("B3", "Medium", "In the germination experiment above, tubes A and C together show that germination requires",
     "light", "water", "cotton wool", "darkness", "B",
     "A and C differ only in moisture; the dry seeds in C did not germinate, so water is necessary."),
    ("B3", "Medium", "In the germination experiment above, the seeds in tube D failed to germinate because",
     "the cold killed the seeds", "low temperature stopped the enzymes from working", "there was too much water", "the fridge was dark", "B",
     "Germination depends on enzymes that break down stored food; near 4 °C they are practically inactive. B shows darkness alone does not prevent germination."),
    ("B3", "Medium", "In the germination experiment above, the boiled, cooled water and oil layer in tube E were used to",
     "keep the seeds warm", "exclude oxygen from the seeds", "supply mineral salts", "prevent fungal growth", "B",
     "Boiling drives dissolved air out of water and the oil layer stops air re-entering, so tube E tests the need for oxygen."),
    ("B3", "Medium", "The bean seeds in the experiment above show epigeal germination, which means that",
     "the cotyledons are carried above the soil", "the cotyledons remain below the soil", "the radicle emerges last", "the seeds need no water", "A",
     "In epigeal germination the hypocotyl elongates and lifts the cotyledons above ground, as in beans; maize shows hypogeal germination."),
    ("B4", "Medium", "The potometer in the experiment above directly measures the rate of",
     "photosynthesis", "water uptake by the shoot", "respiration of the leaves", "growth of the shoot", "B",
     "A potometer measures how fast the cut shoot draws in water; this is taken as roughly equal to the rate of transpiration."),
    ("B4", "Medium", "From the potometer data above, the rate of transpiration in sunlight was how many times the rate in shade (still air)?",
     "1.5 times", "2.5 times", "3.0 times", "4.5 times", "B",
     "Sunlight, still air: 30 mm; shade, still air: 12 mm; 30 ÷ 12 = 2.5 times.", "30/12"),
    ("B4", "Medium", "In the potometer experiment above, the fan increased the distance moved by the bubble because moving air",
     "cools the leaves and closes the stomata", "removes water vapour from around the leaves", "supplies more carbon dioxide", "increases the pressure in the xylem", "B",
     "Wind blows away the humid layer round the leaf, steepening the diffusion gradient for water vapour, so transpiration rises."),
    ("B4", "Medium", "In the potometer experiment above, coating the leaves with vaseline reduced the reading because the vaseline",
     "blocked the stomata", "killed the guard cells", "reflected the sunlight", "stopped photosynthesis", "A",
     "Vaseline seals the stomatal pores through which most water vapour escapes, so very little water was drawn up."),
    ("B4", "Medium", "In setting up the potometer above, the shoot was cut and fitted under water in order to",
     "wash off dust from the leaves", "prevent air bubbles from entering the xylem", "cool the shoot", "supply mineral salts to the shoot", "B",
     "An air lock in the xylem would break the water column and stop uptake, so the cut end must never be exposed to air."),
]

# ---------------------------------------------------------------------------
# Stand-alone items: (topic, difficulty, q, A, B, C, D, answer, explanation[, verify])
# ---------------------------------------------------------------------------
Q = [
    # Variety of Organisms
    ("Variety of Organisms", "Medium", "Viruses are described as being on the borderline between living and non-living things because they",
     "have cells but no nuclei", "reproduce only inside living cells and can be crystallised outside them", "feed and grow like bacteria", "move about freely in air and water", "B",
     "Outside a host a virus is an inert particle that can even form crystals; inside a living cell it multiplies, so it shows life only when parasitising a cell."),
    ("Variety of Organisms", "Medium", "An organism consists of a single cell with no membrane-bound nucleus and a cell wall that is not made of cellulose. It belongs to the kingdom",
     "Protista", "Fungi", "Monera", "Plantae", "C",
     "Prokaryotic cells (no true nucleus) with non-cellulose walls are characteristic of bacteria and blue-green algae, kingdom Monera."),
    ("Variety of Organisms", "Medium", "Euglena is difficult to place among plants or animals because it",
     "has a cell wall and a flagellum", "possesses chloroplasts yet swims with a flagellum and can feed on organic matter", "reproduces by spores like a fungus", "lacks a nucleus and chloroplasts", "B",
     "Euglena photosynthesises like a plant but moves with a flagellum, has no cellulose wall and can feed heterotrophically in the dark, like an animal."),
    ("Variety of Organisms", "Medium", "Rhizopus (bread mould) is classified as a fungus rather than a plant because it",
     "grows on bread", "lacks chlorophyll and feeds saprophytically through hyphae", "produces flowers and seeds", "has roots, stems and leaves", "B",
     "Fungi have no chlorophyll, so they absorb digested food from dead matter through thread-like hyphae; their walls contain chitin, not cellulose."),
    ("Variety of Organisms", "Medium", "Mosses are usually found in damp, shady places mainly because",
     "they cannot tolerate sunlight", "their male gametes must swim in water to reach the eggs", "they feed on decaying leaves", "their spores are dispersed by water", "B",
     "Bryophytes have no vascular tissue and their sperms need a film of water to swim to the archegonia, so they depend on moisture."),
    ("Variety of Organisms", "Medium", "A fern differs from a moss in that the fern",
     "reproduces by seeds", "has true roots, stems and leaves with vascular tissue", "needs no water for fertilisation", "has no alternation of generations", "B",
     "Ferns (Pteridophyta) are vascular plants with true roots, stems and fronds; spores develop in sori under the fronds. Mosses lack vascular tissue."),
    ("Variety of Organisms", "Easy", "A student finds an animal with a soft unsegmented body, a muscular foot and a coiled shell. It belongs to the phylum",
     "Annelida", "Arthropoda", "Mollusca", "Echinodermata", "C",
     "A muscular foot, mantle and (usually) a calcareous shell are the diagnostic features of molluscs such as snails."),
    ("Variety of Organisms", "Medium", "An animal has two body divisions, four pairs of walking legs and no antennae. It is",
     "an insect", "an arachnid", "a crustacean", "a myriapod", "B",
     "Arachnids (spiders, scorpions, ticks) have cephalothorax and abdomen, eight legs and no antennae; insects have three body parts, six legs and one pair of antennae."),
    ("Variety of Organisms", "Easy", "A student examines an animal with a dry scaly skin that lays eggs with leathery shells on land. It belongs to the class",
     "Amphibia", "Reptilia", "Aves", "Mammalia", "B",
     "Reptiles such as lizards and snakes have dry scaly skins and lay leathery-shelled eggs on land; amphibians have moist skins and breed in water."),
    ("Variety of Organisms", "Medium", "Birds and mammals resemble each other in that both",
     "have feathers and lay eggs", "maintain a constant body temperature and have a four-chambered heart", "have hair and mammary glands", "possess a diaphragm and hollow bones", "B",
     "Both classes are homoiothermic (warm-blooded) with a completely divided four-chambered heart; feathers are for birds only and hair for mammals only."),
    ("Variety of Organisms", "Medium", "Which feature of the tapeworm is an adaptation to living in the intestine of its host?",
     "a well-developed digestive system", "a thick cuticle that resists digestive enzymes", "eyes for detecting light", "a pair of powerful jaws", "B",
     "The tapeworm has no gut; it absorbs digested food through its body surface, holds on with hooks and suckers and is protected by a cuticle."),
    ("Variety of Organisms", "Medium", "The clitellum of the earthworm functions in",
     "locomotion", "secreting the cocoon in which fertilised eggs are laid", "gaseous exchange", "sensing light", "B",
     "The swollen clitellum secretes mucus and the cocoon; the earthworm is hermaphrodite but cross-fertilises."),
    ("Variety of Organisms", "Medium", "Hydra captures and paralyses its prey by means of",
     "a sticky tongue", "stinging cells on its tentacles", "poisonous jaws", "a muscular foot", "B",
     "The tentacles carry nematocysts (stinging cells) that discharge threads to paralyse small animals, which are then pushed into the mouth."),
    ("Variety of Organisms", "Medium", "The lateral line of a bony fish enables it to",
     "see in dim light", "detect vibrations and pressure changes in the water", "regulate its body temperature", "control its buoyancy", "B",
     "The lateral line is a row of sensory pits that detect water movement; buoyancy is controlled by the swim bladder."),
    ("Variety of Organisms", "Medium", "Pine and cycads are classified as gymnosperms because their",
     "seeds are borne naked on cone scales", "seeds are enclosed in fruits", "leaves have parallel veins", "flowers are pollinated by insects", "A",
     "Gymnosperm means naked seed: the ovules lie exposed on the scales of cones instead of inside an ovary."),
    ("Variety of Organisms", "Easy", "A plant has leaves with parallel veins, a fibrous root system and floral parts in threes. It is",
     "a dicotyledon", "a monocotyledon", "a gymnosperm", "a fern", "B",
     "Parallel venation, fibrous roots, floral parts in threes and one cotyledon are the marks of monocots such as maize and grasses."),
    # Cell Structure and Organization
    ("Cell Structure and Organization", "Easy", "A cell has a biconcave shape, contains haemoglobin and lacks a nucleus. Which of the following statements about it is correct?",
     "It engulfs bacteria that enter the body", "It transports oxygen from the lungs to the tissues", "It helps the blood to clot at a wound", "It manufactures antibodies against germs", "B",
     "The biconcave, nucleus-free cell packed with haemoglobin is a red blood cell, whose job is to carry oxygen; white cells engulf germs and make antibodies, platelets clot blood."),
    ("Cell Structure and Organization", "Medium", "Which organelle would be most abundant in the flight muscle cells of a bird?",
     "chloroplasts", "mitochondria", "lysosomes", "vacuoles", "B",
     "Flight demands a great deal of energy, which is released in the mitochondria during aerobic respiration."),
    ("Cell Structure and Organization", "Easy", "Proteins are assembled in the cell on the",
     "ribosomes", "mitochondria", "lysosomes", "centrioles", "A",
     "Ribosomes, free or attached to the endoplasmic reticulum, are the sites of protein synthesis."),
    ("Cell Structure and Organization", "Medium", "Red blood cells placed in distilled water swell and burst, but onion cells in distilled water do not, because onion cells",
     "have no nucleus", "are surrounded by a rigid cellulose wall", "contain no water", "have thicker cell membranes", "B",
     "Water enters both by osmosis; the plant cell wall resists further expansion and the cell merely becomes turgid, while the animal cell haemolyses."),
    ("Cell Structure and Organization", "Medium", "A strip of yam placed in a concentrated salt solution for an hour becomes soft and limp because its cells",
     "gain water and burst", "lose water by osmosis and become flaccid", "absorb salt by diffusion", "die from lack of oxygen", "B",
     "Water moves out of the cells into the stronger solution; the protoplasts shrink (plasmolysis) and the tissue loses turgor."),
    ("Cell Structure and Organization", "Medium", "Root hair cells absorb nitrate ions from soil water even when the concentration inside the cell is already higher than outside. The process involved is",
     "osmosis", "diffusion", "active transport", "plasmolysis", "C",
     "Movement against a concentration gradient needs energy from respiration, which is active transport; that is why roots need oxygen."),
    ("Cell Structure and Organization", "Easy", "The spreading of the smell of perfume across a room illustrates",
     "osmosis", "diffusion", "active transport", "turgor", "B",
     "Perfume molecules move from a region of high concentration to regions of low concentration until evenly spread: diffusion."),
    ("Cell Structure and Organization", "Medium", "The level of organisation shown by Hydra, whose body has distinct layers of similar cells working together, is",
     "cell level", "tissue level", "organ level", "system level", "B",
     "Hydra's two cell layers act as tissues but it has no true organs; Amoeba is at cell level, flatworms at organ level and earthworms at system level."),
    ("Cell Structure and Organization", "Medium", "Which of the following statements is NOT part of the cell theory?",
     "All living things are made up of cells", "New cells arise from pre-existing cells", "All cells contain chloroplasts", "The cell is the basic unit of life", "C",
     "Only photosynthetic plant cells contain chloroplasts; the cell theory makes no such claim."),
    ("Cell Structure and Organization", "Medium", "A cell from which the nucleus has been removed soon dies because the nucleus",
     "stores the cell's food", "controls the activities of the cell and carries the chromosomes", "releases energy for the cell", "makes the cell wall", "B",
     "The nucleus carries the genetic material that directs protein synthesis and cell division; without it the cell cannot maintain itself."),
    # Nutrition
    ("Nutrition", "Medium", "In testing a leaf for starch, the leaf is boiled in alcohol in order to",
     "kill the leaf", "remove the chlorophyll so that the iodine colour can be seen", "soften the cuticle", "dissolve the starch", "B",
     "The leaf is first boiled in water to kill it and burst the cells, then in alcohol to decolourise it; iodine then shows starch as blue-black."),
    ("Nutrition", "Medium", "A potted plant is kept in a dark cupboard for 48 hours before an experiment on photosynthesis in order to",
     "kill the pests on it", "remove starch already stored in the leaves", "make the leaves turn yellow", "stop the plant from respiring", "B",
     "Destarching ensures that any starch found after the experiment was made during the experiment itself."),
    ("Nutrition", "Medium", "A destarched potted plant had one leaf enclosed in a flask containing soda lime (which absorbs carbon dioxide) and was left in sunlight for six hours. When tested with iodine the enclosed leaf stayed brown while an uncovered leaf turned blue-black. This shows that photosynthesis requires",
     "light", "carbon dioxide", "chlorophyll", "oxygen", "B",
     "The enclosed leaf had light and chlorophyll but no carbon dioxide (removed by the soda lime), so it made no starch; the uncovered leaf did."),
    ("Nutrition", "Medium", "A farmer notices that his maize plants are stunted and their older leaves have turned pale yellow. The soil is most likely deficient in",
     "nitrogen", "phosphorus", "potassium", "calcium", "A",
     "Nitrogen is needed for proteins and chlorophyll; deficiency causes stunted growth and yellowing (chlorosis) that begins in the older leaves."),
    ("Nutrition", "Medium", "Magnesium is an essential mineral element for green plants because it is a component of",
     "cellulose", "chlorophyll", "starch", "cell membranes", "B",
     "Each chlorophyll molecule has a magnesium atom at its centre, so magnesium shortage causes chlorosis."),
    ("Nutrition", "Medium", "Insectivorous plants such as the pitcher plant and sundew trap insects because they usually grow in soils that are poor in",
     "water", "nitrogen", "light", "carbon dioxide", "B",
     "The digested insects supply nitrogenous compounds that the waterlogged, acidic soils cannot provide; the plants still photosynthesise."),
    ("Nutrition", "Medium", "A patient whose bile duct is blocked would have the greatest difficulty in digesting",
     "starch", "fats and oils", "proteins", "sugars", "B",
     "Bile salts emulsify fats into tiny droplets so that lipase can act; without bile most fat passes out undigested."),
    ("Nutrition", "Medium", "The hydrochloric acid in gastric juice",
     "digests proteins directly", "provides the acidic medium in which pepsin works and kills bacteria in food", "emulsifies fats", "neutralises the acid from the pancreas", "B",
     "Pepsin works best at about pH 2; the acid also destroys many microbes swallowed with food."),
    ("Nutrition", "Medium", "The ileum is well adapted for absorbing digested food because it",
     "has thick muscular walls", "has numerous villi with thin walls and a rich blood supply", "secretes hydrochloric acid", "is the shortest part of the gut", "B",
     "Villi and microvilli give a huge surface area; each villus has capillaries for sugars and amino acids and a lacteal for fats."),
    ("Nutrition", "Medium", "Saliva that has been boiled is mixed with starch solution and kept at 37 °C for 30 minutes. Iodine still turns the mixture blue-black because",
     "boiling destroyed the amylase in the saliva", "starch cannot be digested by saliva", "37 °C is too cold for the enzyme", "iodine reacts with saliva", "A",
     "Enzymes are proteins that are permanently denatured by boiling; unboiled saliva at 37 °C would have converted the starch to maltose."),
    ("Nutrition", "Medium", "The dental formula of an adult human is I 2/2, C 1/1, Pm 2/2, M 3/3. The total number of teeth is",
     "20", "28", "32", "36", "C",
     "The formula gives one half of the upper and lower jaws: (2 + 1 + 2 + 3) × 2 = 16 per jaw, 32 teeth altogether.", "(2+1+2+3)*4"),
    ("Nutrition", "Medium", "The diastema (a gap without teeth) in the jaw of a goat allows",
     "the animal to bite off grass", "the tongue to move freshly cut grass aside while other grass is being chewed", "the canines to grow longer", "the animal to breathe while eating", "B",
     "Herbivores have no upper incisors or canines; the gap lets the tongue separate cut grass from the grass being ground by the molars."),
    ("Nutrition", "Easy", "A sailor who has eaten no fresh fruit or vegetables for months develops swollen, bleeding gums and wounds that refuse to heal. He is suffering from",
     "rickets", "scurvy", "kwashiorkor", "beriberi", "B",
     "Scurvy is caused by a lack of vitamin C (ascorbic acid), found in fresh fruit and vegetables; it causes bleeding gums and poor wound healing."),
    ("Nutrition", "Easy", "A food sample rubbed on filter paper leaves a permanent translucent mark. The sample contains",
     "starch", "protein", "fat or oil", "reducing sugar", "C",
     "The grease-spot test: fats and oils leave a translucent patch that does not dry off, unlike water."),
    ("Nutrition", "Medium", "Which of the following organisms is a saprophyte?",
     "a tapeworm in the intestine", "a mushroom growing on a dead log", "a mistletoe on a mango tree", "a lion feeding on an antelope", "B",
     "Saprophytes feed on dead organic matter; the tapeworm and mistletoe are parasites and the lion is a holozoic carnivore."),
    # Transport
    ("Transport", "Easy", "The pulmonary artery differs from all other arteries in that it carries",
     "oxygenated blood", "deoxygenated blood", "blood under high pressure", "blood away from the heart", "B",
     "It carries deoxygenated blood from the right ventricle to the lungs; the pulmonary vein is the only vein that carries oxygenated blood."),
    ("Transport", "Medium", "A complete ring of bark was removed from a woody stem. After some weeks the bark just above the ring swelled. This shows that",
     "water moves down the stem in the xylem", "manufactured food moves down the stem in the phloem", "the stem was infected by fungi", "the xylem lies in the bark", "B",
     "Removing the bark removes the phloem; sugars moving down from the leaves accumulate above the ring, causing the swelling."),
    ("Transport", "Medium", "A well-watered plant wilts on a hot, dry afternoon and recovers in the evening because during the afternoon",
     "the roots stop absorbing water", "water is lost by transpiration faster than it is absorbed", "photosynthesis uses up the water", "the stomata are closed", "B",
     "Rapid transpiration makes cells lose turgor temporarily; in the cool evening absorption catches up and turgor is restored."),
    ("Transport", "Medium", "The main force that pulls water to the top of a tall tree is",
     "root pressure", "transpiration pull", "capillarity alone", "osmosis in the leaves", "B",
     "Evaporation from the leaves creates a suction transmitted down the continuous water columns in the xylem (cohesion-tension)."),
    ("Transport", "Medium", "A person of blood group O can donate blood to people of all ABO groups because the red cells of group O",
     "have both antigens A and B", "have neither antigen A nor antigen B", "contain no haemoglobin", "have no antibodies", "B",
     "Without A or B antigens on the cells, the recipient's antibodies have nothing to clump; group AB people are universal recipients."),
    ("Transport", "Medium", "Veins possess valves but arteries do not, because in veins the blood",
     "flows faster", "is under low pressure and could flow backwards", "is always oxygenated", "contains more red cells", "B",
     "Valves prevent backflow in the low-pressure return to the heart; skeletal muscles squeezing the veins help push the blood along."),
    ("Transport", "Easy", "The wall of the left ventricle is thicker than that of the right ventricle because the left ventricle",
     "receives blood from the lungs", "pumps blood round the whole body", "holds more blood", "beats more often", "B",
     "The left ventricle must generate enough pressure to drive blood through the systemic circulation; the right pumps only to the nearby lungs."),
    ("Transport", "Medium", "A person who bleeds for an unusually long time from small cuts probably has a shortage of",
     "red blood cells", "white blood cells", "platelets", "plasma", "C",
     "Platelets start the clotting process that seals a wound; their deficiency prolongs bleeding."),
    ("Transport", "Medium", "Lymph differs from blood in that lymph",
     "contains no white cells", "lacks red blood cells", "flows in arteries", "carries no fats", "B",
     "Lymph is tissue fluid drained into lymph vessels; it carries lymphocytes and absorbed fats but no red cells or platelets."),
    ("Transport", "Medium", "People who live at high altitudes have more red blood cells than those at sea level because at high altitudes",
     "the air is colder", "the air contains less oxygen per breath", "food is scarce", "there is more sunlight", "B",
     "With less oxygen available, the body makes more red cells and haemoglobin to carry enough oxygen to the tissues."),
    ("Transport", "Medium", "Transpiration from a leaf would be fastest on a day that is",
     "cool, humid and still", "hot, dry and windy", "cold and rainy", "warm and humid", "B",
     "Heat and dryness increase evaporation, and wind carries the vapour away, keeping the diffusion gradient steep."),
    # Respiration
    ("Respiration", "Medium", "Germinating bean seeds were placed in one vacuum flask and boiled seeds in another, each with a thermometer. After two days the temperature in the first flask had risen by several degrees. This shows that germinating seeds",
     "release heat energy during respiration", "absorb heat from the surroundings", "carry out photosynthesis", "give off oxygen", "A",
     "Some of the energy released in respiration is lost as heat; the boiled (dead) seeds in the control flask do not respire, so their flask stays at room temperature."),
    ("Respiration", "Medium", "Bread dough rises when it is left in a warm place after yeast has been added because the yeast",
     "absorbs water from the flour and swells up", "releases carbon dioxide by fermenting the sugars in the flour", "produces heat that expands the dough", "breaks down the gluten into gases", "B",
     "Yeast respires anaerobically (fermentation), converting sugars to ethanol and carbon dioxide; the trapped gas bubbles make the dough rise."),
    ("Respiration", "Medium", "The cramps and fatigue felt in the muscles after vigorous exercise are due to the accumulation of",
     "carbon dioxide", "lactic acid", "urea", "alcohol", "B",
     "When oxygen supply cannot keep up, muscles respire anaerobically, forming lactic acid; the oxygen debt is repaid afterwards by rapid breathing."),
    ("Respiration", "Medium", "During inspiration (breathing in) in humans,",
     "the diaphragm relaxes and rises", "the diaphragm contracts and flattens while the ribs move up and out", "the volume of the chest decreases", "the pressure in the lungs rises above atmospheric", "B",
     "These movements enlarge the thorax, lowering the pressure in the lungs so that air flows in."),
    ("Respiration", "Medium", "Insects exchange gases with the air through",
     "gills on the abdomen", "spiracles leading into a system of tracheae", "the moist body surface", "lungs in the thorax", "B",
     "Air enters through spiracles and travels along tracheae and tracheoles directly to the tissues, so insect blood carries little oxygen."),
    ("Respiration", "Medium", "Aerobic respiration is more useful to an organism than anaerobic respiration because aerobic respiration",
     "needs no enzymes", "releases far more energy from each molecule of glucose", "produces alcohol", "occurs only in plants", "B",
     "Complete oxidation of glucose to carbon dioxide and water yields about 38 ATP, compared with 2 ATP from anaerobic breakdown."),
    ("Respiration", "Medium", "The gill filaments of a fish are numerous, thin and richly supplied with blood in order to",
     "filter food from the water", "increase the surface area for gas exchange", "help the fish to swim", "store oxygen for later use", "B",
     "A large, thin, well-perfused surface allows rapid diffusion of oxygen from water into the blood."),
    ("Respiration", "Medium", "A green plant kept in complete darkness for 24 hours will",
     "release oxygen and make starch", "release carbon dioxide and use up stored food", "neither respire nor photosynthesise", "absorb carbon dioxide only", "B",
     "In the dark photosynthesis stops but respiration continues, so the plant gives out carbon dioxide and its starch reserves fall."),
    ("Respiration", "Medium", "Hydrogen carbonate indicator turns yellow when a small animal is kept in a sealed tube with it because the animal",
     "uses up the oxygen", "releases carbon dioxide, making the solution more acidic", "warms the solution", "releases water vapour", "B",
     "The indicator is red in normal air and turns yellow as dissolved carbon dioxide forms carbonic acid; it turns purple when carbon dioxide is removed."),
    # Excretion
    ("Excretion", "Medium", "A routine test shows glucose in a patient's urine. The patient most likely suffers from",
     "kidney stones", "diabetes mellitus", "malaria", "anaemia", "B",
     "Without enough insulin, blood glucose rises so high that the kidney tubules cannot reabsorb all of it and glucose appears in urine."),
    ("Excretion", "Medium", "A student drinks two litres of water within a short time. About an hour later he passes a large volume of pale urine because",
     "less ADH is secreted, so the kidney tubules reabsorb less water", "more ADH is secreted, so the tubules reabsorb more water", "the extra water is excreted through the lungs", "the bladder muscles contract more strongly", "A",
     "When the blood is diluted the pituitary releases less antidiuretic hormone, the collecting ducts reabsorb less water and a large volume of dilute urine is formed."),
    ("Excretion", "Medium", "Ultrafiltration of blood in the kidney takes place in the",
     "loop of Henle", "glomerulus and Bowman's capsule", "collecting duct", "ureter", "B",
     "High pressure in the glomerular capillaries forces water, salts, glucose and urea into the Bowman's capsule; cells and proteins stay in the blood."),
    ("Excretion", "Medium", "A patient with severe liver disease has an abnormally low level of urea in the blood. This is because the liver is the organ that",
     "filters urea out of the blood", "converts excess amino acids to urea by deamination", "stores urea until it is passed in the urine", "removes urea from the body in the bile", "B",
     "Deamination in the liver removes the amino group from surplus amino acids; the ammonia formed is converted to the less toxic urea, so a damaged liver makes less urea."),
    ("Excretion", "Medium", "Which of the following is a way in which plants get rid of waste products?",
     "sweating through the leaves", "storing wastes such as tannins and resins in leaves and bark that are later shed", "passing urine through the roots", "coughing out gases through lenticels", "B",
     "Plants have no excretory organs; they store wastes in tissues that are shed (leaves, bark, fruits) or exude gums, latex and resins."),
    ("Excretion", "Easy", "The excretory products removed by the lungs are",
     "urea and salts", "carbon dioxide and water vapour", "bile pigments", "uric acid and ammonia", "B",
     "Carbon dioxide and some water from respiration leave the body in exhaled air."),
    ("Excretion", "Medium", "Protein found in a person's urine suggests damage to the",
     "bladder", "glomeruli of the kidney", "ureters", "urethra", "B",
     "Healthy glomerular walls hold back large protein molecules; when they are damaged, proteins leak into the filtrate."),
    ("Excretion", "Medium", "Glucose filtered into the kidney tubule is normally returned to the blood by",
     "diffusion in the collecting duct", "selective reabsorption in the proximal convoluted tubule", "osmosis in the loop of Henle", "secretion in the Bowman's capsule", "B",
     "All the useful glucose is actively reabsorbed in the first coiled tubule, so normal urine contains none."),
    # Support and Movement
    ("Support and Movement", "Medium", "The earthworm moves through the soil by means of",
     "jointed legs", "a hydrostatic skeleton worked by circular and longitudinal muscles, with chaetae for grip", "a shell and a muscular foot", "fins and a tail", "B",
     "Fluid in the body cavity is squeezed by the muscles so that segments alternately lengthen and shorten, while bristles (chaetae) anchor the body."),
    ("Support and Movement", "Medium", "Insects and other arthropods must moult periodically because their",
     "muscles grow too fast", "exoskeleton cannot stretch as the animal grows", "wings wear out", "legs need replacing", "B",
     "The rigid chitinous exoskeleton is shed (ecdysis) and a new, larger one hardens; growth occurs in the short soft period between."),
    ("Support and Movement", "Medium", "When the forearm is bent at the elbow,",
     "both the biceps and triceps contract", "the biceps contracts while the triceps relaxes", "the triceps contracts while the biceps relaxes", "both muscles relax", "B",
     "Biceps and triceps are antagonistic: the biceps flexes the arm and the triceps straightens it."),
    ("Support and Movement", "Easy", "A muscle is attached to a bone by a",
     "ligament", "tendon", "cartilage", "nerve", "B",
     "Tendons join muscle to bone; ligaments join bone to bone at joints."),
    ("Support and Movement", "Medium", "The vertebra that bears the odontoid process and allows the head to turn from side to side is the",
     "atlas", "axis", "lumbar vertebra", "sacrum", "B",
     "The axis (second cervical vertebra) has a peg on which the atlas rotates; nodding occurs between the skull and the atlas."),
    ("Support and Movement", "Easy", "The type of joint at the shoulder and hip, which allows movement in all directions, is a",
     "hinge joint", "pivot joint", "ball-and-socket joint", "gliding joint", "C",
     "The rounded head of the humerus or femur fits into a cup-shaped socket; elbows and knees are hinge joints."),
    ("Support and Movement", "Medium", "A young herbaceous plant droops when it is short of water because",
     "its xylem collapses", "its cells lose turgor", "its leaves close their stomata", "photosynthesis stops", "B",
     "Non-woody plants are held erect by the turgor pressure of their cells; when water is lost the cells become flaccid and the plant wilts."),
    ("Support and Movement", "Medium", "A seedling placed near a window bends towards the light because",
     "light destroys auxin on the lit side, so cells there grow faster", "auxin accumulates on the shaded side, making cells there elongate more", "the lit side dries out", "the roots pull the shoot towards the window", "B",
     "Auxin moves away from light to the shaded side, where it stimulates cell elongation, so the shoot curves towards the light (positive phototropism)."),
    ("Support and Movement", "Medium", "The folding of the leaves of Mimosa pudica when touched is described as a nastic movement rather than a tropism because",
     "it is very slow", "the direction of the response is not related to the direction of the stimulus", "it involves growth", "it happens only at night", "B",
     "Tropisms are growth movements towards or away from a stimulus; nastic responses are the same whichever side is touched."),
    ("Support and Movement", "Medium", "In a bony fish, forward propulsion is produced mainly by the",
     "pectoral fins", "caudal (tail) fin and the body muscles", "dorsal fin", "swim bladder", "B",
     "Side-to-side beats of the tail drive the fish forward; paired fins steer and brake, and the dorsal fin prevents rolling."),
    # Reproduction
    ("Reproduction", "Medium", "A flower has large brightly coloured petals, a sweet scent, nectar at the base of the petals and sticky, spiny pollen grains. Its stigma is most likely to be",
     "large and feathery, hanging outside the flower", "small and sticky, held inside the flower", "absent, since the flower is self-pollinated", "long and dry, exposed to the wind", "B",
     "These are the features of an insect-pollinated flower; its stigma is small and sticky and lies inside the flower where visiting insects brush against it, unlike the feathery exposed stigmas of wind-pollinated flowers."),
    ("Reproduction", "Medium", "Cross-pollination is more advantageous to a species than self-pollination because it",
     "requires less pollen", "produces offspring with greater variation and vigour", "is more certain to occur", "needs no pollinating agent", "B",
     "Mixing genes from two parents increases variation, which helps the species adapt; self-pollination gives more uniform offspring."),
    ("Reproduction", "Hard", "In flowering plants, the endosperm is triploid because it is formed when",
     "the egg fuses with two male nuclei", "one male nucleus fuses with the two polar nuclei of the embryo sac", "two eggs fuse together", "the zygote divides without meiosis", "B",
     "Double fertilisation: one male nucleus fertilises the egg (diploid zygote) and the other joins the two polar nuclei (triploid endosperm)."),
    ("Reproduction", "Easy", "After fertilisation in a flowering plant, the ovule develops into the",
     "fruit", "seed", "endosperm", "pericarp", "B",
     "The ovule becomes the seed and the ovary wall becomes the fruit (pericarp)."),
    ("Reproduction", "Medium", "The edible part of the cashew is a swollen pedicel (flower stalk). The cashew is therefore described as",
     "a true fruit", "a false fruit", "a drupe", "a legume", "B",
     "A false fruit develops partly from tissues other than the ovary; the true fruit of the cashew is the kidney-shaped nut."),
    ("Reproduction", "Medium", "The mango fruit is classified as a drupe because it",
     "splits open when ripe", "has a fleshy mesocarp and a single hard stony endocarp around the seed", "develops from many ovaries", "has a dry papery wall", "B",
     "Drupes (mango, coconut) have a stony inner wall; berries such as tomato have soft inner walls and many seeds."),
    ("Reproduction", "Medium", "The fruits of Tridax have a ring of fine hairs (pappus). This adapts them for dispersal by",
     "water", "wind", "animals", "explosion", "B",
     "The hairs act like a parachute so the light fruit is carried away by air currents."),
    ("Reproduction", "Medium", "Fruits of Desmodium have hooks on their surface, an adaptation for dispersal by",
     "wind", "animals", "water", "the plant itself", "B",
     "Hooked fruits cling to the fur of animals or clothing of people and are carried far from the parent plant."),
    ("Reproduction", "Medium", "In humans, fertilisation normally takes place in the",
     "uterus", "oviduct (fallopian tube)", "vagina", "ovary", "B",
     "Sperms meet the egg in the upper oviduct; the zygote then travels to the uterus, where it implants."),
    ("Reproduction", "Medium", "The testes of a man are held in the scrotum outside the body cavity because",
     "there is no room inside the abdomen", "sperm production requires a temperature slightly lower than body temperature", "the scrotum protects them from injury", "sperms need light to develop", "B",
     "Sperm formation is impaired at 37 °C; the scrotum keeps the testes about 2-3 °C cooler."),
    ("Reproduction", "Medium", "In a regular 28-day menstrual cycle, ovulation usually occurs on about the",
     "1st day", "7th day", "14th day", "28th day", "C",
     "The egg is released about the middle of the cycle; if it is not fertilised, the uterine lining is shed about 14 days later.", "14"),
    ("Reproduction", "Medium", "The placenta of a mammal",
     "allows the blood of mother and foetus to mix freely", "allows oxygen and food to pass to the foetus and wastes to pass back without mixing the two bloods", "produces the sperms", "stores the eggs", "B",
     "Exchange occurs by diffusion across the placental villi; the two circulations remain separate, protecting the foetus from the mother's blood pressure."),
    ("Reproduction", "Medium", "Identical twins are produced when",
     "two eggs are fertilised by two sperms", "one fertilised egg divides into two separate embryos", "an egg is fertilised by two sperms", "two eggs are fertilised by one sperm", "B",
     "Identical twins share all their genes because they come from one zygote; fraternal twins come from two separately fertilised eggs."),
    ("Reproduction", "Easy", "Ginger is propagated vegetatively by means of",
     "runners", "rhizomes", "bulbs", "stem cuttings", "B",
     "The ginger 'root' is an underground stem (rhizome) with buds that sprout into new plants; cassava is grown from stem cuttings."),
    ("Reproduction", "Medium", "The life cycle of the mosquito (egg, larva, pupa, adult) is an example of",
     "incomplete metamorphosis", "complete metamorphosis", "alternation of generations", "asexual reproduction", "B",
     "Complete metamorphosis has a pupal stage; the cockroach and grasshopper show incomplete metamorphosis (egg, nymph, adult)."),
    ("Reproduction", "Medium", "Yeast reproduces asexually by",
     "binary fission", "budding", "spore formation", "fragmentation", "B",
     "A small outgrowth forms on the parent cell, receives a nucleus and pinches off; Amoeba divides by binary fission."),
    # Growth
    ("Growth", "Medium", "In maize, the cotyledon remains below the ground during germination because the part of the embryo that elongates is the",
     "hypocotyl", "epicotyl", "radicle", "plumule", "B",
     "Hypogeal germination: the epicotyl elongates and pushes the plumule up while the cotyledon stays buried; in beans the hypocotyl elongates (epigeal)."),
    ("Growth", "Medium", "Ink marks were made at equal intervals along a young root. After two days the marks just behind the tip had spread furthest apart. This shows that the region of greatest growth in length is",
     "the root cap", "the region of elongation just behind the tip", "the region of root hairs", "the base of the root", "B",
     "Cells are produced at the meristem in the tip and then elongate in the zone behind it; older regions have stopped growing."),
    ("Growth", "Medium", "Increase in the girth of a woody stem (secondary growth) results from the activity of the",
     "apical meristem", "cambium", "pith", "epidermis", "B",
     "The vascular cambium divides to produce new xylem inside and phloem outside, thickening the stem year by year."),
    ("Growth", "Medium", "Meiosis differs from mitosis in that meiosis",
     "produces two identical cells", "halves the chromosome number and produces four cells", "occurs in all body cells", "does not involve chromosomes", "B",
     "Meiosis occurs in the gonads (and in anthers and ovules) to form gametes with half the chromosome number; mitosis gives identical diploid cells for growth."),
    ("Growth", "Easy", "Human body cells contain 46 chromosomes. The number of chromosomes in a human sperm is",
     "92", "46", "23", "12", "C",
     "Gametes are haploid, formed by meiosis, so a sperm carries 23 chromosomes; fertilisation restores 46.", "46/2"),
    ("Growth", "Medium", "Some hard-coated seeds germinate only after the coat has been scratched or partly burnt. This treatment breaks dormancy by",
     "supplying warmth to the embryo", "allowing water and oxygen to reach the embryo", "killing the embryo", "removing the cotyledons", "B",
     "The impermeable testa keeps water and air out; scarification lets them in so that germination can start."),
    ("Growth", "Medium", "Unripe bananas ripen faster when kept in a closed bag with a ripe one because the ripe fruit releases",
     "auxin", "ethene (ethylene)", "gibberellin", "abscisic acid", "B",
     "Ethene is a gaseous plant hormone that promotes fruit ripening; it accumulates in the closed bag."),
    ("Growth", "Medium", "The most reliable measure of the growth of a plant over several weeks is its increase in",
     "height", "dry mass", "fresh mass", "number of leaves", "B",
     "Dry mass excludes the water content, which varies from hour to hour, and reflects the real increase in living material."),
    # Coordination and Control
    ("Coordination and Control", "Medium", "When a person touches a hot object and withdraws the hand before feeling pain, the impulse travels in the order",
     "receptor → motor neurone → brain → sensory neurone → muscle", "receptor → sensory neurone → spinal cord → motor neurone → muscle", "muscle → sensory neurone → spinal cord → receptor", "brain → spinal cord → receptor → muscle", "B",
     "A spinal reflex arc passes through the spinal cord, not the brain, which is why the response is so fast; pain is felt slightly later."),
    ("Coordination and Control", "Medium", "A patient who staggers and cannot coordinate his movements after an accident has probably damaged the",
     "cerebrum", "cerebellum", "medulla oblongata", "spinal cord", "B",
     "The cerebellum controls balance, posture and the coordination of voluntary movements."),
    ("Coordination and Control", "Medium", "Breathing and heartbeat are controlled by the",
     "cerebrum", "cerebellum", "medulla oblongata", "hypothalamus", "C",
     "The medulla at the base of the brain regulates involuntary activities such as breathing, heart rate and swallowing."),
    ("Coordination and Control", "Medium", "When the eye focuses on a near object,",
     "the ciliary muscles relax and the lens becomes thinner", "the ciliary muscles contract, the suspensory ligaments slacken and the lens becomes thicker", "the pupil closes completely", "the retina moves forward", "B",
     "A thicker, more convex lens bends light more strongly, bringing rays from a near object to a focus on the retina (accommodation)."),
    ("Coordination and Control", "Medium", "A student can read a book clearly but cannot see the board from the back of the class. His defect and its correction are",
     "long sight; convex lens", "short sight; concave lens", "astigmatism; convex lens", "colour blindness; tinted glasses", "B",
     "In short sight (myopia) the image of a distant object forms in front of the retina; a diverging (concave) lens moves it back."),
    ("Coordination and Control", "Medium", "In dim light we see objects only in shades of grey because",
     "the pupil closes", "only the rods, which are insensitive to colour, respond to weak light", "the cones are damaged", "the lens becomes opaque", "B",
     "Rods work in low light but cannot distinguish colours; cones give colour vision but need bright light."),
    ("Coordination and Control", "Medium", "The part of the ear responsible for maintaining balance is the",
     "cochlea", "semicircular canals", "ear drum", "ossicles", "B",
     "Movement of fluid in the three semicircular canals tells the brain about the position and movement of the head; the cochlea is for hearing."),
    ("Coordination and Control", "Medium", "After a heavy meal rich in starch, blood glucose is brought back to normal by insulin, which",
     "converts glycogen to glucose in the liver", "promotes the conversion of glucose to glycogen in the liver and muscles", "increases the breakdown of fats", "stops the absorption of glucose", "B",
     "Insulin from the islets of Langerhans lowers blood glucose; glucagon does the opposite when glucose is low."),
    ("Coordination and Control", "Medium", "A frightened person has a pounding heart, dilated pupils and raised blood sugar. These changes are caused by",
     "insulin", "adrenaline", "thyroxine", "oestrogen", "B",
     "Adrenaline from the adrenal glands prepares the body for 'fight or flight' in an emergency."),
    ("Coordination and Control", "Medium", "A swelling at the front of the neck (goitre) is usually caused by a shortage of iodine, because iodine is needed to make",
     "insulin", "thyroxine", "adrenaline", "growth hormone", "B",
     "The thyroid gland enlarges as it tries to make enough thyroxine, the hormone that controls the metabolic rate."),
    ("Coordination and Control", "Medium", "The pituitary is called the master gland because it",
     "is the largest gland in the body", "secretes hormones that control other endocrine glands", "produces insulin and adrenaline", "lies in the neck", "B",
     "Pituitary hormones regulate the thyroid, adrenal cortex, ovaries and testes, besides producing growth hormone and ADH."),
    ("Coordination and Control", "Medium", "On a hot day the skin helps to cool the body by",
     "constricting the blood vessels and stopping sweat", "dilating the surface blood vessels and producing sweat that evaporates", "shivering", "raising the hairs", "B",
     "Vasodilation brings warm blood to the surface to lose heat, and evaporation of sweat takes latent heat from the skin."),
    ("Coordination and Control", "Medium", "The root of a seedling laid horizontally curves downwards after a day. This response is",
     "negative phototropism", "positive geotropism", "positive hydrotropism", "a nastic movement", "B",
     "Roots grow towards the pull of gravity (positive geotropism); shoots grow away from it."),
    # Ecology
    ("Ecology", "Medium", "In the food chain grass → grasshopper → lizard → hawk, the lizard is",
     "a producer", "a primary consumer", "a secondary consumer", "a tertiary consumer", "C",
     "The grasshopper eats the producer (primary consumer); the lizard eats the grasshopper (secondary); the hawk is the tertiary consumer."),
    ("Ecology", "Medium", "In the food chain grass → grasshopper → lizard → hawk, the least energy is available to the",
     "grass", "grasshopper", "lizard", "hawk", "D",
     "Only about 10 per cent of the energy at one level passes to the next, so the top consumer receives the least."),
    ("Ecology", "Medium", "In a grassland, the dry mass of the grass is far greater than that of the antelopes feeding on it, which in turn is greater than that of the lions. A pyramid drawn from these masses is called a pyramid of",
     "numbers", "biomass", "energy", "population", "B",
     "A pyramid of biomass compares the dry mass of living material at each trophic level; a pyramid of numbers counts individuals and a pyramid of energy shows energy flow."),
    ("Ecology", "Easy", "The instrument used to measure the relative humidity of the air in a habitat is the",
     "anemometer", "hygrometer", "rain gauge", "barometer", "B",
     "A wet-and-dry bulb hygrometer measures humidity; the anemometer measures wind speed and the rain gauge rainfall."),
    ("Ecology", "Medium", "The turbidity (cloudiness) of a pond is measured with a",
     "Secchi disc", "light meter", "pH meter", "thermometer", "A",
     "The depth at which the black-and-white Secchi disc disappears from view indicates how turbid the water is."),
    ("Ecology", "Medium", "Farmers plant cowpea or groundnut on a field to restore its fertility because these legumes",
     "need no water", "carry nitrogen-fixing bacteria in their root nodules", "produce large leaves", "prevent all weeds", "B",
     "Rhizobium bacteria in the nodules convert atmospheric nitrogen into compounds the plant, and later the soil, can use."),
    ("Ecology", "Medium", "Nitrosomonas and Nitrobacter are important in the nitrogen cycle because they",
     "convert nitrates back to nitrogen gas", "convert ammonium compounds to nitrites and then to nitrates", "fix nitrogen in root nodules", "break down proteins into amino acids", "B",
     "These nitrifying bacteria produce nitrates, the form of nitrogen plants absorb best; denitrifying bacteria do the reverse."),
    ("Ecology", "Medium", "A lichen is an association between an alga and a fungus in which the alga makes food by photosynthesis and the fungus supplies water and anchorage. This relationship is",
     "parasitism", "mutualism", "commensalism", "saprophytism", "B",
     "Both partners benefit; lichens are also pioneer organisms on bare rock in primary succession."),
    ("Ecology", "Medium", "The remora fish attaches itself to a shark and feeds on scraps from the shark's meals without harming it. This is an example of",
     "parasitism", "commensalism", "mutualism", "predation", "B",
     "One partner benefits and the other is neither helped nor harmed: commensalism."),
    ("Ecology", "Medium", "The size of a population of lizards on an island would decrease as a result of an increase in",
     "natality", "immigration", "mortality", "food supply", "C",
     "Births and immigration add individuals; deaths and emigration remove them."),
    ("Ecology", "Medium", "An abandoned farm is first colonised by grasses, then shrubs, and after many years by forest trees. This sequence of changes is called",
     "adaptation", "ecological succession", "migration", "competition", "B",
     "Each community alters the habitat so that another can replace it, until a stable climax community (the forest) is reached."),
    ("Ecology", "Medium", "A vegetation zone with tall grasses, scattered fire-resistant trees and distinct wet and dry seasons is",
     "tropical rainforest", "savanna", "mangrove swamp", "desert", "B",
     "The Guinea and Sudan savannas of Nigeria have these features; rainforest has continuous tall trees and mangroves grow in salt water."),
    ("Ecology", "Medium", "Mangrove trees of the Niger Delta have breathing roots (pneumatophores) that grow upwards out of the mud because",
     "the mud is waterlogged and poor in oxygen", "they need to trap sunlight", "the roots absorb salt from the air", "they support the tree against the wind", "A",
     "Pneumatophores take in oxygen for the submerged roots; prop (stilt) roots provide the support."),
    ("Ecology", "Medium", "Competition between individuals of the same species is usually more intense than competition between different species because members of the same species",
     "are more aggressive", "need exactly the same resources", "live longer", "reproduce faster", "B",
     "Individuals of one species share the same food, space, mates and nesting sites, so every one of these is contested."),
    ("Ecology", "Medium", "Desert plants such as cacti survive drought because they have",
     "broad thin leaves", "succulent stems, leaves reduced to spines and sunken stomata", "shallow roots and many stomata", "large flowers", "B",
     "These features store water and reduce transpiration; long roots reach deep water."),
    ("Ecology", "Medium", "Decomposers such as bacteria and fungi are essential in an ecosystem because they",
     "produce oxygen", "return nutrients from dead organisms to the soil and air", "eat living plants", "make the soil acidic", "B",
     "By breaking down dead matter they release carbon dioxide, nitrogen compounds and minerals for producers to reuse."),
    # Soil
    ("Soil", "Medium", "Equal volumes of sandy, loamy and clay soils are placed in three funnels and the same volume of water is poured on each. The greatest volume of water drains through the sandy soil in ten minutes because sandy soil has",
     "small particles and tiny pores", "large particles with large air spaces", "much humus", "the highest capillarity", "B",
     "Large spaces between the coarse particles let water pass quickly; clay's tiny pores hold water back."),
    ("Soil", "Medium", "A farm remains waterlogged for days after rain. Its soil is most likely",
     "sandy", "clayey", "loamy", "gravelly", "B",
     "Clay particles are very small, so the pores are tiny and drainage is very poor."),
    ("Soil", "Easy", "Loamy soil is the best for growing most crops because it",
     "contains only sand", "has a balance of sand, silt, clay and humus that gives good drainage and water retention", "is always wet", "contains no living organisms", "B",
     "Loam drains well yet holds enough water and nutrients, and is easy to work."),
    ("Soil", "Medium", "In a capillarity experiment, water rises highest, though slowly, in the tube containing",
     "coarse sand", "clay", "gravel", "loam", "B",
     "The finer the particles, the narrower the capillary spaces and the greater the height to which water rises; in sand it rises fast but not far."),
    ("Soil", "Medium", "Humus improves a soil mainly because it",
     "makes the soil lighter in colour", "holds water and nutrients and improves soil structure", "kills soil bacteria", "increases drainage in clay only", "B",
     "Decayed organic matter binds particles into crumbs, retains moisture, supplies nutrients and darkens the soil so it warms faster."),
    ("Soil", "Medium", "Earthworms improve the fertility of soil by",
     "eating crop roots", "burrowing, which aerates and drains the soil, and by producing casts rich in nutrients", "adding sand to the soil", "removing humus", "B",
     "Their tunnels admit air and water, and their casts and dead bodies add organic matter."),
    ("Soil", "Medium", "Heavy rain on a sandy farm carries dissolved nutrients down beyond the reach of crop roots. This loss is called",
     "erosion", "leaching", "evaporation", "weathering", "B",
     "Leaching removes soluble minerals such as nitrates; erosion removes the soil itself."),
    ("Soil", "Medium", "Which farming practice best restores nitrogen to a soil that has been cropped for several years?",
     "burning the stubble every year", "rotating cereals with legumes and adding manure", "planting maize continuously", "removing all crop residues", "B",
     "Legumes fix nitrogen and manure adds organic nitrogen; continuous cropping and burning deplete it."),
    ("Soil", "Medium", "On a sloping farm, erosion by running water is best reduced by",
     "ploughing up and down the slope", "making ridges along the contours and planting cover crops", "removing all vegetation", "burning the grass", "B",
     "Contour ridges slow the run-off and cover crops shield the soil from raindrops and bind it with roots."),
    # Humans and Environment
    ("Humans and Environment", "Medium", "Fertiliser washed from farms into a lake causes fish to die some weeks later because",
     "the fertiliser poisons the fish directly", "algae multiply, then die and decay, using up the dissolved oxygen", "the water becomes too cold", "the fish eat the fertiliser", "B",
     "This is eutrophication: the nutrient-rich water produces an algal bloom whose decomposition by bacteria removes oxygen."),
    ("Humans and Environment", "Medium", "Acid rain, which damages buildings and forests, is produced mainly by",
     "carbon dioxide from respiration", "sulphur dioxide and oxides of nitrogen from burning fuels", "oxygen from photosynthesis", "methane from cattle", "B",
     "These gases dissolve in rain to form sulphuric and nitric acids."),
    ("Humans and Environment", "Medium", "Chlorofluorocarbons (CFCs) released from old refrigerators are harmful because they",
     "cause acid rain", "destroy the ozone layer, letting more ultraviolet radiation reach the earth", "poison fish", "block sunlight", "B",
     "More ultraviolet light increases skin cancer and eye damage and harms crops and plankton."),
    ("Humans and Environment", "Medium", "The gas that contributes most to global warming because of its release from burning fossil fuels is",
     "oxygen", "carbon dioxide", "nitrogen", "hydrogen", "B",
     "Carbon dioxide traps heat radiated from the earth (the greenhouse effect); methane and CFCs also contribute."),
    ("Humans and Environment", "Medium", "Discarded polythene bags are a lasting problem in Nigerian cities because they",
     "dissolve in rain water", "are non-biodegradable and block drains, causing floods", "attract earthworms", "decay within a week", "B",
     "Micro-organisms cannot break polythene down, so it persists for many years."),
    ("Humans and Environment", "Medium", "Overgrazing by cattle in the northern savanna leads to desertification because",
     "cattle add manure to the soil", "removal of the grass cover exposes the soil to wind and water erosion", "cattle drink all the water", "grass grows back faster", "B",
     "Bare, trampled soil dries out, loses its top layer and can no longer support vegetation."),
    ("Humans and Environment", "Medium", "An outbreak of cholera in a village is most likely to follow the",
     "eating of unripe fruit", "contamination of the drinking water by sewage", "bite of infected mosquitoes", "inhaling of dust", "B",
     "Cholera and typhoid are water-borne diseases spread by faecal contamination of water and food; houseflies also carry the germs."),
    ("Humans and Environment", "Medium", "The vector of sleeping sickness (trypanosomiasis) in humans and cattle is the",
     "Anopheles mosquito", "tsetse fly", "housefly", "blackfly", "B",
     "Tsetse flies (Glossina) transmit Trypanosoma; Anopheles carries malaria and blackflies carry river blindness."),
    ("Humans and Environment", "Medium", "Which of the following measures would best reduce the spread of malaria in a community?",
     "boiling drinking water", "clearing stagnant water where Anopheles mosquitoes breed and sleeping under treated nets", "vaccinating dogs", "spraying crops with fertiliser", "B",
     "Malaria is transmitted only by the female Anopheles mosquito, so controlling the vector controls the disease."),
    ("Humans and Environment", "Medium", "Game reserves and national parks are established mainly to",
     "provide meat for the towns", "conserve wildlife and their habitats", "clear land for farming", "collect firewood", "B",
     "Protected areas prevent hunting and habitat destruction so that species do not become extinct."),
    # Heredity and Variation
    ("Heredity and Variation", "Medium", "In guinea pigs black coat (B) is dominant to white (b). A heterozygous black male is mated with a white female and 12 offspring are produced. The number of white offspring expected is",
     "0", "3", "6", "9", "C",
     "Bb × bb gives 1 Bb (black) : 1 bb (white), so half of the 12 offspring, i.e. 6, are expected to be white.", "6"),
    ("Heredity and Variation", "Medium", "In the cross Tt × Tt (tallness dominant), the genotypic ratio of the offspring is",
     "3 : 1", "1 : 2 : 1", "1 : 1", "9 : 3 : 3 : 1", "B",
     "One TT : two Tt : one tt; the phenotypic ratio is 3 tall : 1 short."),
    ("Heredity and Variation", "Medium", "To find out whether a tall pea plant is TT or Tt, it should be crossed with",
     "another tall plant", "a short (tt) plant", "itself only", "any plant of unknown genotype", "B",
     "A test cross with the recessive: if any short offspring appear the tall parent is Tt; if all are tall it is TT."),
    ("Heredity and Variation", "Medium", "A pure-breeding tall pea plant was crossed with a pure-breeding short one and the F1 plants were allowed to self-pollinate. Out of 400 F2 plants, the number expected to be tall is",
     "100", "200", "300", "400", "C",
     "F1 plants are all Tt; selfing gives 3 tall : 1 short, so three-quarters of 400, i.e. 300, are expected to be tall.", "300"),
    ("Heredity and Variation", "Medium", "In cattle, a red bull mated with a white cow produces roan calves whose coats have both red and white hairs. This type of inheritance is",
     "complete dominance", "codominance", "sex-linked inheritance", "polygenic inheritance", "B",
     "In codominance both alleles are expressed fully in the heterozygote (red and white hairs side by side), unlike incomplete dominance where the heterozygote is intermediate."),
    ("Heredity and Variation", "Hard", "Two pink-flowered four o'clock plants are crossed. The fraction of the offspring expected to be white is",
     "1/2", "1/4", "3/4", "0", "B",
     "RW × RW gives RR (red), RW, RW (pink) and WW (white); one in four is white.", "1/4"),
    ("Heredity and Variation", "Medium", "A man of blood group A and a woman of blood group B have a child of blood group O. The genotypes of the parents must be",
     "IAIA and IBIB", "IAi and IBi", "IAIB and ii", "IAIA and IBi", "B",
     "A group O child (ii) needs an i allele from each parent, so both parents are heterozygous."),
    ("Heredity and Variation", "Medium", "Two parents of blood group A have a child of blood group O. Which statement about the parents is correct?",
     "Both parents are homozygous (IAIA)", "Both parents are heterozygous (IAi)", "One parent must actually be group O", "The child cannot be theirs", "B",
     "A group O child (ii) receives one i allele from each parent, so both group A parents must be IAi; each therefore has a 1 in 4 chance of a group O child."),
    ("Heredity and Variation", "Medium", "Both husband and wife have the sickle-cell trait (genotype AS). The probability that a child of theirs will have sickle-cell anaemia (SS) is",
     "0", "1/4", "1/2", "3/4", "B",
     "AS × AS gives 1 AA : 2 AS : 1 SS, so each child has a one in four chance of being SS.", "1/4"),
    ("Heredity and Variation", "Medium", "A couple in which one partner is AA and the other AS cannot have a child with sickle-cell anaemia because",
     "the S allele is not inherited", "every child receives an A allele from the AA parent", "the S allele is dominant", "AS individuals are sterile", "B",
     "The children can only be AA or AS; both partners must carry S for an SS child to be possible."),
    ("Heredity and Variation", "Medium", "The sex of a child is determined by the father because",
     "the egg carries a Y chromosome", "sperms carry either an X or a Y chromosome while all eggs carry X", "the father has more chromosomes", "the Y chromosome comes from the mother", "B",
     "A Y-bearing sperm produces a boy (XY); an X-bearing sperm produces a girl (XX)."),
    ("Heredity and Variation", "Hard", "Haemophilia is a sex-linked recessive condition. A haemophiliac man (XhY) marries a woman who is not a carrier (XHXH). Which of the following is correct about their children?",
     "all the daughters will be carriers but none of the sons will be affected", "all the sons will be haemophiliac and the daughters normal", "half the daughters and half the sons will be haemophiliac", "none of the children will receive the haemophilia allele", "A",
     "Every daughter receives the father's Xh and the mother's XH, so all are carriers; sons receive the father's Y and a normal X from the mother, so none is affected."),
    ("Heredity and Variation", "Hard", "In a dihybrid cross between two plants heterozygous for two independently inherited characters (RrYy × RrYy), the fraction of offspring showing both recessive characters is",
     "1/4", "1/8", "1/16", "9/16", "C",
     "The 9 : 3 : 3 : 1 ratio gives one double recessive (rryy) in sixteen.", "1/16"),
    ("Heredity and Variation", "Medium", "Which of the following characters shows continuous variation in humans?",
     "blood group", "ability to roll the tongue", "height", "sex", "C",
     "Height varies gradually over a range because many genes and the environment influence it; the others fall into distinct classes."),
    ("Heredity and Variation", "Medium", "Mendel's first law (law of segregation) states that",
     "characters are blended in the offspring", "the two alleles of a pair separate during gamete formation so that each gamete carries only one", "acquired characters are inherited", "all genes are linked", "B",
     "Each parent passes on one allele of each pair; the pair is restored at fertilisation."),
    ("Heredity and Variation", "Medium", "In a disputed paternity case, a man of blood group O could not be the father of a child whose blood group is",
     "A", "B", "O", "AB", "D",
     "A group O father can give only the i allele, but an AB child must receive IA from one parent and IB from the other."),
    ("Heredity and Variation", "Medium", "A sudden, heritable change in the genetic material of an organism is called",
     "adaptation", "mutation", "variation", "segregation", "B",
     "Mutations may be caused by radiation or certain chemicals and are a source of new variation."),
    # Evolution
    ("Evolution", "Medium", "Lamarck explained the long neck of the giraffe by suggesting that",
     "giraffes with longer necks survived and reproduced more", "ancestral giraffes stretched their necks to reach leaves and passed the longer neck to their offspring", "the long neck arose by mutation", "God created giraffes with long necks", "B",
     "Lamarck's theory of use and disuse and the inheritance of acquired characters is not accepted today, because acquired changes are not inherited."),
    ("Evolution", "Medium", "According to Darwin's theory of natural selection,",
     "all individuals of a species are identical", "individuals with favourable variations survive, reproduce and pass the variations to their offspring", "organisms change because they want to", "acquired characters are inherited", "B",
     "Variation, over-production, struggle for existence and survival of the fittest lead to gradual change in populations."),
    ("Evolution", "Medium", "After clean-air laws reduced the soot on tree trunks in English cities, the pale form of the peppered moth became common again and the dark form declined. This shows that",
     "the moths changed colour to match the cleaner trees", "the direction of natural selection changes when the environment changes", "dark colour is caused by soot and not inherited", "pale moths reproduce faster than dark moths in all environments", "B",
     "On clean, lichen-covered trunks the pale moths were now the better camouflaged ones, so birds ate more dark moths; selection favoured a different form when the environment changed."),
    ("Evolution", "Medium", "The flipper of a whale, the wing of a bat and the arm of a man have the same basic pentadactyl plan. Such structures are",
     "analogous and show convergent evolution", "homologous and suggest descent from a common ancestor", "vestigial", "unrelated", "B",
     "Homologous structures share origin and structure though they may differ in function; the wings of birds and insects are analogous."),
    ("Evolution", "Medium", "The appendix and the coccyx in humans are described as vestigial organs because they",
     "are larger than in other mammals", "are reduced remnants of organs that were functional in ancestral forms", "developed recently", "have no blood supply", "B",
     "Vestigial organs are evidence of evolution: the coccyx is the remnant of a tail and the appendix of a larger caecum."),
    ("Evolution", "Medium", "Archaeopteryx is regarded as evidence of evolution because its fossil shows",
     "a fish with legs", "features of both reptiles (teeth, bony tail) and birds (feathers)", "the first flowering plant", "a mammal with feathers", "B",
     "It is a link between reptiles and birds, supporting the view that birds evolved from reptilian ancestors."),
    ("Evolution", "Medium", "Darwin observed that finches on different Galapagos islands had beaks suited to different foods although they resembled one mainland species. This is an example of",
     "adaptive radiation", "industrial melanism", "artificial selection", "inheritance of acquired characters", "A",
     "A single ancestral species gave rise to several species, each adapted to a different way of life."),
    ("Evolution", "Medium", "Bacteria that survive a course of antibiotics multiply and produce resistant populations. This illustrates",
     "natural selection", "Lamarckism", "vestigial organs", "spontaneous generation", "A",
     "The drug kills susceptible bacteria; the few with resistance-conferring mutations survive and reproduce."),
]


# Option sets rewritten so that the correct answer is never conspicuously longer than the
# distractors (same letter positions as in the rows above). Key = unique part of the stem.
FIX = {
    "least suitable for estimating the population of": ("grasses growing on a school lawn", "birds nesting in the trees round the field", "snails crawling on the field at night", "weeds growing between rows on a farm"),
    "the seeds in tube D failed to germinate because": ("the cold in the fridge killed the seed embryos", "low temperature stopped the enzymes from working", "there was far too much water in the tube", "the inside of the fridge was completely dark"),
    "borderline between living and non-living": ("have cells with cytoplasm but no true nuclei", "multiply only inside living cells but can be crystallised", "feed, grow and respire in the same way as bacteria", "move about freely in air, water and soil like bacteria"),
    "Euglena is difficult to place": ("has a cellulose cell wall as well as a whip-like flagellum", "has chloroplasts yet swims with a flagellum and can feed like an animal", "reproduces by spores in the same way as a fungus does", "lacks both a nucleus and chloroplasts like a bacterium"),
    "Rhizopus (bread mould) is classified": ("grows on stale bread and other cooked foods", "lacks chlorophyll and feeds saprophytically through hyphae", "produces flowers and seeds like a plant", "has true roots, stems and leaves like a plant"),
    "Mosses are usually found in damp": ("they cannot tolerate direct sunlight for long", "their male gametes must swim in water to reach the eggs", "they feed on the decaying leaves found there", "their spores can only be dispersed by water"),
    "A fern differs from a moss": ("reproduces by means of seeds instead of spores", "has true roots, stems and leaves with vascular tissue", "needs no water at all for fertilisation to occur", "shows no alternation of generations in its life"),
    "Birds and mammals resemble each other": ("have feathers on their bodies and lay eggs with hard shells", "maintain a constant body temperature and have a four-chambered heart", "have hair on their bodies and feed their young on milk", "possess a muscular diaphragm and light hollow bones"),
    "The clitellum of the earthworm": ("locomotion through the burrows in the soil", "secreting the cocoon in which fertilised eggs are laid", "gaseous exchange through the moist body wall", "sensing light and touch at the front end"),
    "Hydra captures and paralyses": ("a long sticky tongue", "stinging cells on its tentacles", "a pair of poisonous jaws", "a broad muscular foot"),
    "The lateral line of a bony fish": ("see clearly in dim light at the bottom of the river", "detect vibrations and pressure changes in the water", "regulate its body temperature in cold water", "control its buoyancy at different depths"),
    "A strip of yam placed in a concentrated salt": ("gain water by osmosis and finally burst", "lose water by osmosis and become flaccid", "absorb the salt rapidly by diffusion", "die quickly from a lack of oxygen"),
    "nucleus has been removed soon dies": ("stores the food reserves on which the cell feeds", "controls the activities of the cell and carries the chromosomes", "releases all the energy the cell needs for its work", "makes the cell wall and the cell membrane"),
    "the leaf is boiled in alcohol": ("kill the leaf and stop all its chemical reactions", "remove the chlorophyll so that the iodine colour can be seen", "soften the waxy cuticle so that iodine can enter", "dissolve the starch so that it can be tested"),
    "The hydrochloric acid in gastric juice": ("digests proteins directly into amino acids", "gives pepsin the acid medium it needs and kills germs in food", "emulsifies fats into tiny droplets for lipase", "neutralises the alkaline juice from the pancreas"),
    "The ileum is well adapted": ("has thick muscular walls that churn the food", "has numerous villi with thin walls and a rich blood supply", "secretes hydrochloric acid and the enzyme pepsin", "is the shortest and widest part of the gut"),
    "The diastema": ("the animal to bite off grass close to the ground", "the tongue to hold cut grass aside while other grass is being chewed", "the canines to grow longer without damaging the lips", "the animal to breathe freely while it is eating"),
    "wilts on a hot, dry afternoon": ("the roots stop absorbing water from the hot soil", "water is lost by transpiration faster than it is absorbed", "photosynthesis uses up all the water in the leaves", "the stomata are tightly closed by the heat"),
    "Veins possess valves but arteries do not": ("flows much faster than in the arteries", "is under low pressure and could flow backwards", "is always oxygenated and bright red", "contains far more red cells and platelets"),
    "People who live at high altitudes": ("the air is much colder all the year", "the air contains less oxygen per breath", "food is scarce in the mountains", "there is much more sunlight there"),
    "Insects exchange gases with the air": ("gills on the sides of the abdomen", "spiracles leading into a system of tracheae", "the moist surface of the whole body", "a pair of lungs inside the thorax"),
    "Aerobic respiration is more useful": ("needs no enzymes to break down the glucose", "releases far more energy from each molecule of glucose", "produces alcohol that the organism can use", "occurs only in green plants during the day"),
    "The gill filaments of a fish": ("filter food particles from the water", "increase the surface area for gas exchange", "help the fish to swim faster in water", "store oxygen for use when water is short"),
    "Hydrogen carbonate indicator turns yellow": ("uses up all the oxygen in the sealed tube", "releases carbon dioxide, making the solution more acidic", "warms the solution with its body heat", "releases water vapour into the tube"),
    "Ultrafiltration of blood in the kidney": ("loop of Henle and the medulla", "glomerulus and Bowman's capsule", "collecting duct of the nephron", "ureter leading to the bladder"),
    "plants get rid of waste products": ("sweating out waste water through pores in the leaves", "storing wastes such as tannins in leaves and bark that are later shed", "passing liquid wastes out through the root hairs", "coughing waste gases out through the lenticels"),
    "Glucose filtered into the kidney tubule": ("simple diffusion in the collecting duct", "selective reabsorption in the proximal convoluted tubule", "osmosis in the descending loop of Henle", "active secretion in the Bowman's capsule"),
    "The earthworm moves through the soil": ("pairs of jointed legs on each segment of the body", "a hydrostatic skeleton worked by muscles, with chaetae for grip", "a muscular foot that glides on a trail of slime", "fins and a tail that beat from side to side"),
    "must moult periodically": ("muscles grow too fast for the body", "exoskeleton cannot stretch as the animal grows", "wings wear out and must be replaced", "legs are lost and need replacing"),
    "nastic movement rather than a tropism": ("it takes place very slowly over several hours", "the response is the same whichever direction the stimulus comes from", "it involves permanent growth of the leaf cells", "it happens only at night when there is no light"),
    "forward propulsion is produced mainly": ("pectoral and pelvic fins", "caudal (tail) fin and the body muscles", "single dorsal fin on the back", "swim bladder in the body cavity"),
    "Cross-pollination is more advantageous": ("requires much less pollen to succeed", "produces offspring with greater variation and vigour", "is far more certain to occur every season", "needs no insect or wind to carry the pollen"),
    "the endosperm is triploid": ("the egg cell fuses with two male nuclei at the same time", "one male nucleus fuses with the two polar nuclei of the embryo sac", "two egg cells in the embryo sac fuse together", "the zygote divides three times without meiosis"),
    "The mango fruit is classified as a drupe": ("splits open along two seams when it is ripe", "has a fleshy mesocarp and a hard stony endocarp round the seed", "develops from many separate ovaries of one flower", "has a dry papery wall and many small seeds"),
    "held in the scrotum": ("there is not enough room for them inside the abdomen", "sperms form best at a temperature slightly below body temperature", "the scrotum protects them from injury during sport", "developing sperms need daylight to mature properly"),
    "The placenta of a mammal": ("allows the blood of the mother and the foetus to mix freely", "exchanges food, oxygen and wastes without mixing the two bloods", "produces the eggs that are fertilised in the uterus", "stores the food that the baby will need after birth"),
    "Ink marks were made at equal intervals": ("the root cap at the very tip of the root", "the region of elongation just behind the tip", "the region covered with root hairs", "the base of the root near the stem"),
    "Meiosis differs from mitosis": ("produces two cells identical to the parent", "halves the chromosome number and produces four cells", "occurs in all the body cells during growth", "does not involve the chromosomes at all"),
    "When the eye focuses on a near object": ("the ciliary muscles relax, the ligaments tighten and the lens thins", "the ciliary muscles contract, the ligaments slacken and the lens thickens", "the pupil closes almost completely to cut out stray light", "the retina moves forward until the image is sharp"),
    "In dim light we see objects only in shades of grey": ("the pupil closes and lets very little light in", "only the rods, which are insensitive to colour, respond to weak light", "the cones are temporarily damaged by the lack of light", "the lens becomes cloudy and opaque in weak light"),
    "brought back to normal by insulin": ("converts glycogen in the liver back into glucose", "promotes the change of glucose to glycogen in the liver and muscles", "increases the breakdown of fats into fatty acids", "stops the absorption of glucose from the ileum"),
    "The pituitary is called the master gland": ("is the largest endocrine gland in the body", "secretes hormones that control other endocrine glands", "produces both insulin and adrenaline", "lies in the neck just below the larynx"),
    "Farmers plant cowpea or groundnut": ("need very little water and no fertiliser", "carry nitrogen-fixing bacteria in their root nodules", "produce large leaves that shade out weeds", "prevent all weeds from growing on the field"),
    "Nitrosomonas and Nitrobacter": ("convert nitrates in the soil back to nitrogen gas", "convert ammonium compounds to nitrites and then to nitrates", "fix nitrogen gas inside the root nodules of legumes", "break down proteins in dead matter into amino acids"),
    "Competition between individuals of the same species": ("are much more aggressive", "need exactly the same resources", "live longer than others", "reproduce much faster"),
    "Desert plants such as cacti": ("broad thin leaves with a great many stomata", "succulent stems, leaves reduced to spines and sunken stomata", "shallow roots and stomata on both leaf surfaces", "large brightly coloured flowers all the year"),
    "Decomposers such as bacteria and fungi": ("produce the oxygen that animals breathe", "return nutrients from dead organisms to the soil and air", "eat living plants and keep them from spreading", "make the soil acidic so that weeds cannot grow"),
    "Loamy soil is the best": ("contains nothing but coarse sand, which drains very quickly", "has a balance of sand, clay and humus that drains well yet holds water", "stays wet all the year round, so crops never lack water", "contains no living organisms to attack crop roots"),
    "Humus improves a soil mainly": ("makes the soil lighter in colour and cooler", "holds water and nutrients and improves soil structure", "kills the bacteria that live in the soil", "increases drainage in clay soils only"),
    "Earthworms improve the fertility": ("eating the roots of weeds so that crops grow better", "burrowing, which aerates the soil, and producing casts rich in nutrients", "carrying sand up to the surface to improve drainage", "removing dead leaves and humus from the surface"),
    "best restores nitrogen to a soil": ("burning the stubble at the end of every season", "rotating cereals with legumes and adding manure", "planting maize continuously on the same field", "removing all crop residues after harvest"),
    "erosion by running water is best reduced": ("ploughing straight up and down the slope", "making ridges along the contours and planting cover crops", "removing all vegetation from the slope", "burning the grass before the rains begin"),
    "Fertiliser washed from farms into a lake": ("the fertiliser poisons the fish as soon as it reaches them", "algae multiply, then die and decay, using up the dissolved oxygen", "the water becomes too cold for the fish to breed", "the fish eat the fertiliser and cannot digest it"),
    "Acid rain, which damages buildings": ("carbon dioxide from the respiration of animals", "sulphur dioxide and oxides of nitrogen from burning fuels", "oxygen released by green plants in photosynthesis", "methane released by cattle and rice fields"),
    "Chlorofluorocarbons (CFCs)": ("dissolve in rain water and make the rain acidic", "destroy the ozone layer, so more ultraviolet light reaches the earth", "poison the fish in rivers and lakes near cities", "block the sunlight that crops need to grow"),
    "Discarded polythene bags": ("dissolve in rain water and poison the wells", "are non-biodegradable and block drains, causing floods", "attract earthworms and rats to the streets", "decay within a week and give off bad smells"),
    "Overgrazing by cattle": ("cattle add so much manure that the soil becomes too rich", "removal of the grass cover exposes the soil to wind and water erosion", "cattle drink all the water in the rivers and wells", "grass grows back faster than the cattle can eat it"),
    "An outbreak of cholera": ("eating of unripe fruit from the farms", "contamination of the drinking water by sewage", "bite of infected Anopheles mosquitoes", "inhaling of dust during the harmattan"),
    "best reduce the spread of malaria": ("boiling all drinking water and washing hands before meals", "clearing stagnant water where mosquitoes breed and using treated nets", "vaccinating all the dogs and cats in the community", "spraying all the crops on the farms with fertiliser"),
    "one partner is AA and the other AS": ("the S allele is never passed on to children", "every child receives an A allele from the AA parent", "the S allele is dominant over the A allele", "people of genotype AS are always sterile"),
    "The sex of a child is determined by the father": ("every egg carries a Y chromosome as well as an X", "sperms carry either an X or a Y chromosome while all eggs carry X", "the father has more chromosomes than the mother", "the Y chromosome is passed on only by the mother"),
    "Mendel's first law": ("the characters of the two parents are blended in the offspring", "the two alleles of a pair separate so that each gamete carries only one", "characters acquired during life are passed to the offspring", "all the genes on a chromosome are always inherited together"),
    "Lamarck explained the long neck": ("giraffes born with longer necks survived and reproduced more than others", "ancestral giraffes stretched their necks and passed the longer neck to their young", "the long neck arose by a sudden mutation in one generation", "giraffes were created with long necks and have never changed"),
    "According to Darwin's theory": ("all the individuals of a species are exactly identical", "individuals with favourable variations survive and pass them to their offspring", "organisms change their bodies to suit their needs", "characters acquired during life are inherited by the young"),
    "described as vestigial organs": ("are larger in humans than in any other mammals", "are reduced remnants of organs that worked in ancestral forms", "appeared only recently in the history of humans", "have no blood supply and no nerves of their own"),
    "Archaeopteryx is regarded as evidence": ("a fish with four legs that could walk on dry land", "features of both reptiles (teeth, bony tail) and birds (feathers)", "the first flowering plant to appear on the earth", "a mammal with feathers instead of hair on its body"),
}


def build():
    questions, bad = [], []
    for row in PQ:
        key, diff, q, a, b, c, d, ans, exp = row[:9]
        verify = row[9] if len(row) > 9 else None
        topic = next(t for k, t, _, _ in PASSAGES if k == key)
        item = {"subject": S, "topic": topic, "passage": key, "difficulty": diff, "q": q, "A": a, "B": b, "C": c, "D": d, "answer": ans, "explanation": exp}
        questions.append((item, verify))
    for row in Q:
        topic, diff, q, a, b, c, d, ans, exp = row[:9]
        verify = row[9] if len(row) > 9 else None
        item = {"subject": S, "topic": topic, "difficulty": diff, "q": q, "A": a, "B": b, "C": c, "D": d, "answer": ans, "explanation": exp}
        questions.append((item, verify))
    hits = {k: 0 for k in FIX}
    for item, _ in questions:
        for key, opts in FIX.items():
            if key in item["q"]:
                hits[key] += 1
                for letter, text in zip("ABCD", opts):
                    item[letter] = text
    assert all(v == 1 for v in hits.values()), {k: v for k, v in hits.items() if v != 1}
    for item, verify in questions:
        if verify:
            expected = eval(verify, {"math": math})
            got = _num(item[item["answer"]])
            if got is None or abs(got - expected) > max(0.01 * abs(expected), 0.006):
                bad.append((item["q"][:60], item["answer"], item[item["answer"]], expected))
    if bad:
        for b_ in bad:
            print("MISMATCH:", b_)
        sys.exit("Verification failed - file not written.")
    questions = [it for it, _ in questions]
    apply_fixes(questions)
    _balance(questions)
    texts = [(x["q"], x.get("passage")) for x in questions]
    assert len(texts) == len(set(texts)), "duplicate question text"
    for x in questions:
        assert x["answer"] in "ABCD" and all(x[k] for k in "ABCD"), x["q"]
        assert len(x["explanation"]) >= 25, x["q"]
        assert len({x[k].strip().lower() for k in "ABCD"}) == 4, x["q"]
        lens = {k: len(x[k]) for k in "ABCD"}
        longest_other = max(v for k, v in lens.items() if k != x["answer"])
        assert not (lens[x["answer"]] > 30 and lens[x["answer"]] > 1.5 * longest_other), ("length bias", x["q"], lens)
    wrapped = {}
    for key, _, _, text in PASSAGES:
        lines = []
        for line in text.split("\n"):
            if len(line) <= 42 or re.search(r"\S {3,}\S", line):
                lines.append(line)
            else:
                lines.extend(textwrap.wrap(line, 42))
        for line in lines:
            assert len(line) <= 42, (key, len(line), line)
        wrapped[key] = "\n".join(lines)
    batch = {
        "batch_id": "batch_013_biology_round3",
        "exam_type": "JAMB",
        "note": "Biology round 3: four data passages (quadrat, food tests, germination, potometer) and applied items across the JAMB syllabus.",
        "passages": [{"key": k, "title": t, "text": wrapped[k]} for k, _, t, _ in PASSAGES],
        "questions": questions,
        "deactivate": [],
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(batch, fh, ensure_ascii=False, indent=1)
    from collections import Counter
    print(f"wrote {OUT}: {len(questions)} questions, {len(PASSAGES)} passages")
    print("answer letters:", dict(Counter(x["answer"] for x in questions)))
    print("per topic:", dict(Counter(x["topic"] for x in questions)))


if __name__ == "__main__":
    build()
