"""Batch 041 - Post-UTME Current Affairs, round 1.

Nigeria and world general knowledge the way universities ask it in screening tests: officeholders,
the constitution and structure of government, history and national symbols, economy and
institutions, elections, security agencies, geography and culture, Africa and the world, sports and
entertainment, everyday ICT.  Every fact was checked against a primary or major-news source in
September 2026; items that age (officeholders, "latest" events) say so in the stem.

    python3 scripts/build_content_batch41.py -> content/batch_041_current_affairs_round1.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Current Affairs"

T_GOV = "Nigeria: Government and Officeholders"
T_CONST = "Nigeria: Constitution and Structure of Government"
T_HIST = "Nigeria: History and National Symbols"
T_ECON = "Nigeria: Economy, Institutions and Policies"
T_ELEC = "Nigeria: Elections and Politics"
T_SEC = "Nigeria: Security and Law Enforcement"
T_GEO = "Nigeria: Geography, Infrastructure and Culture"
T_WORLD = "Africa and the World"
T_SPORT = "Sports and Entertainment"
T_ICT = "Everyday ICT and Computer Literacy"

PASSAGES = []
PQ = []

Q = [
    # ------------------------------------------------------------------ officeholders
    (T_GOV, "Easy", "Nigeria's President, sworn in on 29 May 2023, is",
     "Bola Ahmed Tinubu", "Muhammadu Buhari", "Atiku Abubakar", "Goodluck Jonathan",
     "A", "Bola Ahmed Tinubu of the APC took the oath of office on 29 May 2023 after winning the February 2023 election."),
    (T_GOV, "Easy", "The Vice-President of Nigeria who took office alongside the President in May 2023 is",
     "Yemi Osinbajo", "Kashim Shettima", "Namadi Sambo", "Ifeanyi Okowa",
     "B", "Senator Kashim Shettima, a former Governor of Borno State, has been Vice-President since 29 May 2023."),
    (T_GOV, "Easy", "The President of the 10th Senate of Nigeria is",
     "Ahmad Lawan", "Bukola Saraki", "Godswill Akpabio", "Barau Jibrin",
     "C", "Senator Godswill Akpabio was elected Senate President when the 10th National Assembly was inaugurated in June 2023."),
    (T_GOV, "Easy", "The Speaker of the House of Representatives in the 10th National Assembly is",
     "Femi Gbajabiamila", "Yakubu Dogara", "Benjamin Kalu", "Tajudeen Abbas",
     "D", "Rt. Hon. Tajudeen Abbas, from Kaduna State, has been Speaker since June 2023; Benjamin Kalu is his deputy."),
    (T_GOV, "Medium", "The Deputy Senate President of the 10th Senate is",
     "Barau Jibrin", "Ovie Omo-Agege", "Ike Ekweremadu", "Benjamin Kalu",
     "A", "Senator Barau Jibrin of Kano State is Deputy Senate President; Benjamin Kalu is Deputy Speaker of the House."),
    (T_GOV, "Medium", "The Chief Justice of Nigeria sworn in on 22 August 2024 is",
     "Justice Olukayode Ariwoola", "Justice Kudirat Kekere-Ekun", "Justice Ibrahim Tanko Muhammad", "Justice Walter Onnoghen",
     "B", "Justice Kudirat Kekere-Ekun succeeded Justice Olukayode Ariwoola and is the second woman to hold the office."),
    (T_GOV, "Medium", "In October 2025 a new Chairman of INEC was sworn in to succeed Prof. Mahmood Yakubu. He is",
     "Prof. Attahiru Jega", "Prof. Maurice Iwu", "Festus Okoye", "Prof. Joash Amupitan",
     "D", "Prof. Joash Amupitan, a law professor and SAN, took office as INEC Chairman on 23 October 2025."),
    (T_GOV, "Easy", "The Governor of the Central Bank of Nigeria as at 2026 is",
     "Godwin Emefiele", "Sanusi Lamido Sanusi", "Olayemi Cardoso", "Folashodun Shonubi",
     "C", "Olayemi Cardoso was confirmed as CBN Governor by the Senate in September 2023."),
    (T_GOV, "Easy", "The Inspector-General of Police of Nigeria as at 2026 is",
     "Kayode Egbetokun", "Usman Alkali Baba", "Mohammed Adamu", "Ibrahim Idris",
     "A", "Kayode Egbetokun was appointed Inspector-General of Police in June 2023."),
    (T_GOV, "Medium", "The National Security Adviser to the President as at 2026 is",
     "Babagana Monguno", "Nuhu Ribadu", "Sambo Dasuki", "Andrew Azazi",
     "B", "Nuhu Ribadu, pioneer chairman of the EFCC, has been National Security Adviser since June 2023."),
    (T_GOV, "Medium", "The Secretary to the Government of the Federation as at 2026 is",
     "Boss Mustapha", "Babachir Lawal", "Anyim Pius Anyim", "George Akume",
     "D", "Senator George Akume, a former Governor of Benue State, is Secretary to the Government of the Federation."),
    (T_GOV, "Medium", "The Chief of Staff to President Tinubu is",
     "Ibrahim Gambari", "Abba Kyari", "Femi Gbajabiamila", "Hadiza Bala Usman",
     "C", "Femi Gbajabiamila, Speaker of the 9th House of Representatives, became Chief of Staff in June 2023."),
    (T_GOV, "Easy", "Nigeria's Minister of Education as at 2026 is",
     "Dr Tunji Alausa", "Prof. Tahir Mamman", "Adamu Adamu", "Prof. Suwaiba Ahmad",
     "A", "Dr Maruf Tunji Alausa became Minister of Education in October 2024; Prof. Suwaiba Ahmad is Minister of State."),
    (T_GOV, "Easy", "The Minister of the Federal Capital Territory as at 2026 is",
     "Muhammad Bello", "Nyesom Wike", "Bala Mohammed", "Dave Umahi",
     "B", "Nyesom Wike, former Governor of Rivers State, has been FCT Minister since August 2023."),
    (T_GOV, "Medium", "The Coordinating Minister of Health and Social Welfare is",
     "Dr Osagie Ehanire", "Prof. Isaac Adewole", "Dr Tunji Alausa", "Prof. Ali Pate",
     "D", "Prof. Muhammad Ali Pate has led the health ministry since August 2023."),
    (T_GOV, "Medium", "Nigeria's Minister of Works, in charge of federal highways such as the Lagos-Calabar coastal road, is",
     "Babatunde Fashola", "Dave Umahi", "Nyesom Wike", "Festus Keyamo",
     "B", "Engr. Dave Umahi, former Governor of Ebonyi State, is Minister of Works."),
    (T_GOV, "Hard", "In April 2026 the President replaced Wale Edun as Minister of Finance and Coordinating Minister of the Economy with",
     "Zainab Ahmed", "Kemi Adeosun", "Taiwo Oyedele", "Doris Anite",
     "C", "Taiwo Oyedele, who had chaired the Presidential Committee on Fiscal Policy and Tax Reforms, took over the finance ministry in April 2026."),
    (T_GOV, "Medium", "Nigeria's Minister of Foreign Affairs as at 2026 is",
     "Yusuf Tuggar", "Geoffrey Onyeama", "Bosun Tijani", "Hannatu Musawa",
     "A", "Ambassador Yusuf Maitama Tuggar has been Minister of Foreign Affairs since August 2023."),
    (T_GOV, "Medium", "The Minister of Information and National Orientation as at 2026 is",
     "Lai Mohammed", "Labaran Maku", "Dele Alake", "Mohammed Idris",
     "D", "Mohammed Idris Malagi is Minister of Information and National Orientation; Dele Alake is Minister of Solid Minerals."),
    (T_GOV, "Medium", "Nigeria's Minister of Defence as at 2026 is",
     "Bashir Magashi", "Mohammed Badaru Abubakar", "Bello Matawalle", "Mansur Dan-Ali",
     "B", "Mohammed Badaru Abubakar, former Governor of Jigawa State, is Minister of Defence; Bello Matawalle is Minister of State."),
    (T_GOV, "Medium", "The Attorney-General of the Federation and Minister of Justice as at 2026 is",
     "Abubakar Malami", "Mohammed Adoke", "Lateef Fagbemi", "Bayo Ojo",
     "C", "Prince Lateef Fagbemi, SAN, has been Attorney-General of the Federation since August 2023."),
    (T_GOV, "Hard", "The Chief of Defence Staff appointed in October 2025 is",
     "General Christopher Musa", "General Lucky Irabor", "General Abayomi Olonisakin", "General Olufemi Oluyede",
     "D", "General Olufemi Oluyede became Chief of Defence Staff on 24 October 2025, replacing General Christopher Musa."),
    (T_GOV, "Hard", "The Chief of Army Staff appointed in October 2025 is",
     "Major-General Waidi Shaibu", "Lt-General Taoreed Lagbaja", "Lt-General Faruk Yahaya", "Lt-General Tukur Buratai",
     "A", "Major-General Waidi Shaibu was named Chief of Army Staff in the October 2025 change of service chiefs."),
    (T_GOV, "Hard", "The Chief of Naval Staff appointed in October 2025 is",
     "Vice Admiral Emmanuel Ogalla", "Rear Admiral Idi Abbas", "Vice Admiral Awwal Gambo", "Vice Admiral Ibok-Ete Ibas",
     "B", "Rear Admiral Idi Abbas took over as Chief of Naval Staff in October 2025."),
    (T_GOV, "Hard", "The Chief of Air Staff appointed in October 2025 is",
     "Air Marshal Hasan Abubakar", "Air Marshal Oladayo Amao", "Air Marshal Sadique Abubakar", "AVM Sunday Kelvin Aneke",
     "D", "Air Vice Marshal Sunday Kelvin Aneke became Chief of Air Staff in October 2025."),
    (T_GOV, "Medium", "The Group Chief Executive Officer of NNPC Limited appointed in April 2025 is",
     "Mele Kyari", "Maikanti Baru", "Bayo Ojulari", "Andrew Yakubu",
     "C", "Bayo Ojulari replaced Mele Kyari as head of NNPC Limited on 2 April 2025."),
    (T_GOV, "Medium", "The Director-General of NAFDAC as at 2026 is",
     "Prof. Mojisola Adeyeye", "Dr Paul Orhii", "Prof. Dora Akunyili", "Dr Yetunde Oni",
     "A", "Prof. Mojisola Christianah Adeyeye has headed NAFDAC since 2017; the late Dora Akunyili led it from 2001 to 2008."),
    (T_GOV, "Medium", "The Nigerian who serves as Deputy Secretary-General of the United Nations is",
     "Ngozi Okonjo-Iweala", "Akinwumi Adesina", "Arunma Oteh", "Amina J. Mohammed",
     "D", "Amina J. Mohammed, a former Nigerian Minister of Environment, has been UN Deputy Secretary-General since 2017."),
    (T_GOV, "Easy", "The Nigerian who is Director-General of the World Trade Organisation is",
     "Amina J. Mohammed", "Ngozi Okonjo-Iweala", "Obiageli Ezekwesili", "Arunma Oteh",
     "B", "Dr Ngozi Okonjo-Iweala became WTO Director-General in March 2021, the first woman and first African in the post."),
    (T_GOV, "Medium", "In March 2025 the President declared a state of emergency in one state, suspending its governor, deputy governor and House of Assembly for six months. The state is",
     "Kano", "Plateau", "Rivers", "Zamfara",
     "C", "Emergency rule was declared in Rivers State on 18 March 2025 and a sole administrator ran the state until September 2025."),
    (T_GOV, "Medium", "The governor re-elected in the Anambra State election of 8 November 2025 is",
     "Willie Obiano", "Peter Obi", "Nicholas Ukachukwu", "Charles Soludo",
     "D", "Prof. Charles Soludo of APGA won a second term with over 422,000 votes, taking all 21 local government areas."),
    (T_GOV, "Medium", "The Executive Chairman of the EFCC appointed in October 2023 is",
     "Ola Olukoyede", "Abdulrasheed Bawa", "Ibrahim Magu", "Nuhu Ribadu",
     "A", "Ola Olukoyede succeeded Abdulrasheed Bawa as EFCC chairman in October 2023."),
    (T_GOV, "Easy", "The Governor of Lagos State as at 2026 is",
     "Akinwunmi Ambode", "Babajide Sanwo-Olu", "Babatunde Fashola", "Bola Tinubu",
     "B", "Babajide Sanwo-Olu has governed Lagos State since May 2019 and was re-elected in 2023."),

    # ------------------------------------------------------------------ constitution
    (T_CONST, "Easy", "Nigeria is made up of 36 states, the Federal Capital Territory and how many local government areas?",
     "768", "774", "777", "744",
     "B", "The 1999 Constitution lists 774 local government areas across the 36 states, plus six area councils in the FCT."),
    (T_CONST, "Easy", "The Nigerian Senate has how many members?",
     "108", "120", "109", "360",
     "C", "Three senators from each of the 36 states plus one for the FCT gives 109 senators."),
    (T_CONST, "Easy", "The House of Representatives in Nigeria has how many members?",
     "306", "469", "109", "360",
     "D", "The House has 360 members elected from federal constituencies; together with the 109 senators the National Assembly has 469 members."),
    (T_CONST, "Medium", "A legislature with two chambers, like Nigeria's National Assembly, is described as",
     "bicameral", "unicameral", "federal", "bipartisan",
     "A", "Bicameral means two chambers: the Senate and the House of Representatives."),
    (T_CONST, "Easy", "The constitution currently in force in Nigeria is the Constitution of",
     "1963", "1979", "1999", "1989",
     "C", "The 1999 Constitution came into force on 29 May 1999 with the return to civilian rule; it has since been amended several times."),
    (T_CONST, "Easy", "Making laws for the federation is the main duty of which arm of government?",
     "The executive", "The legislature", "The judiciary", "The civil service",
     "B", "The legislature (National Assembly) makes laws; the executive implements them and the judiciary interprets them."),
    (T_CONST, "Easy", "The third tier of government in Nigeria is the",
     "state government", "federal government", "traditional council", "local government",
     "D", "Nigeria has three tiers: federal, state and local government."),
    (T_CONST, "Medium", "Abia, Anambra, Ebonyi, Enugu and Imo states make up which geopolitical zone?",
     "South-South", "South-East", "North-Central", "South-West",
     "B", "Nigeria's six geopolitical zones are North-Central, North-East, North-West, South-East, South-South and South-West."),
    (T_CONST, "Medium", "Since the Not Too Young To Run Act of 2018, the minimum age to contest for President of Nigeria is",
     "40 years", "30 years", "35 years", "45 years",
     "C", "The 2018 amendment reduced the age for President from 40 to 35 and for the House of Representatives from 30 to 25."),
    (T_CONST, "Medium", "Under the 1999 Constitution, the longest any one person may serve as President of Nigeria is",
     "eight years", "twelve years", "four years", "ten years",
     "A", "A presidential term is four years and no one may be elected more than twice, so the maximum is eight years."),
    (T_CONST, "Easy", "The minimum age at which a Nigerian may register and vote in an election is",
     "16 years", "21 years", "20 years", "18 years",
     "D", "Every citizen of 18 years and above who registers with INEC is entitled to vote."),
    (T_CONST, "Easy", "The head of the judiciary in Nigeria is the",
     "Attorney-General of the Federation", "President of the Court of Appeal", "Chief Justice of Nigeria", "Chief Judge of the FCT",
     "C", "The Chief Justice of Nigeria heads the Supreme Court and the whole judicial arm."),
    (T_CONST, "Medium", "Nigeria's seat of government officially moved from Lagos to Abuja in",
     "1976", "1991", "1999", "1983",
     "B", "The FCT was created in 1976, but the formal movement of the capital to Abuja took place on 12 December 1991 under General Babangida."),
    (T_CONST, "Medium", "A bill passed by both chambers of the National Assembly normally becomes law when",
     "the Senate President signs it", "the Chief Justice approves it", "INEC gazettes it", "the President assents to it",
     "D", "Presidential assent turns a bill into an Act; if assent is withheld, a two-thirds vote of each chamber can override the veto."),
    (T_CONST, "Medium", "The power to remove (impeach) the President of Nigeria for gross misconduct belongs to the",
     "Supreme Court", "National Assembly", "Council of State", "Federal Executive Council",
     "B", "Impeachment is a legislative process requiring a two-thirds majority of each chamber of the National Assembly."),
    (T_CONST, "Medium", "Elections into local government councils in a state are conducted by the",
     "State Independent Electoral Commission", "Independent National Electoral Commission", "State House of Assembly", "Local Government Service Commission",
     "A", "Each state has its own State Independent Electoral Commission (SIEC) for council elections; INEC conducts federal and state elections and those in the FCT area councils."),
    (T_CONST, "Hard", "In July 2024 the Supreme Court ruled that allocations from the Federation Account must be paid directly to",
     "state governors", "the National Assembly", "local government councils", "the Federal Inland Revenue Service",
     "C", "The judgment on local government autonomy stopped governors from holding council funds in joint accounts and ordered direct payment to democratically elected councils."),
    (T_CONST, "Medium", "The principle that federal appointments must reflect the diversity of Nigeria's states and ethnic groups is called",
     "rule of law", "separation of powers", "checks and balances", "federal character",
     "D", "Federal character, in Section 14 of the Constitution, guards against domination of government by any one group."),
    (T_CONST, "Easy", "Since 1979 Nigeria has practised which system of government?",
     "Parliamentary", "Presidential", "Monarchical", "Confederal",
     "B", "The First Republic used the parliamentary (Westminster) system; since the 1979 Constitution Nigeria has run an executive presidential system."),
    (T_CONST, "Easy", "The official residence and office of the President of Nigeria is",
     "Dodan Barracks, Lagos", "State House, Marina", "Aso Rock Presidential Villa, Abuja", "Government House, Kaduna",
     "C", "The Presidential Villa at Aso Rock in Abuja has housed Nigeria's presidents since 1991; Dodan Barracks was used in Lagos."),
    (T_CONST, "Hard", "The Constitution allows the Supreme Court of Nigeria to have the Chief Justice and not more than how many other justices?",
     "15", "25", "12", "21",
     "D", "Section 230 fixes the Supreme Court at the Chief Justice and up to 21 justices."),
    (T_CONST, "Medium", "Nigeria was first divided into 12 states in 1967 by",
     "General Yakubu Gowon", "General Murtala Mohammed", "General Ibrahim Babangida", "General Sani Abacha",
     "A", "Gowon replaced the four regions with 12 states in May 1967; Abacha's 1996 creation brought the total to the present 36."),
    (T_CONST, "Medium", "The Commander-in-Chief of the Armed Forces of Nigeria is the",
     "Chief of Defence Staff", "President", "Minister of Defence", "Chief of Army Staff",
     "B", "The Constitution makes the President the Commander-in-Chief; the Chief of Defence Staff is the most senior serving officer."),
    (T_CONST, "Medium", "Who presides over a joint sitting of the Senate and the House of Representatives?",
     "The Speaker of the House", "The President of Nigeria", "The Chief Justice of Nigeria", "The Senate President",
     "D", "The Senate President presides over joint sittings, such as the presentation of the annual budget."),

    # ------------------------------------------------------------------ history & symbols
    (T_HIST, "Easy", "Nigeria gained independence from Britain on",
     "1 October 1963", "1 October 1960", "12 June 1993", "29 May 1999",
     "B", "Independence came on 1 October 1960; Nigeria became a republic exactly three years later."),
    (T_HIST, "Easy", "Nigeria became a republic, replacing the Queen with a Nigerian Head of State, in",
     "1960", "1966", "1963", "1979",
     "C", "The Republican Constitution took effect on 1 October 1963 with Dr Nnamdi Azikiwe as ceremonial President."),
    (T_HIST, "Easy", "The Northern and Southern Protectorates were amalgamated into one Nigeria in 1914 by",
     "Sir Hugh Clifford", "Sir James Robertson", "Sir Ralph Moor", "Lord Frederick Lugard",
     "D", "Lord Lugard carried out the amalgamation on 1 January 1914 and became the first Governor-General of Nigeria."),
    (T_HIST, "Medium", "The name 'Nigeria' was first suggested in 1897 by",
     "Flora Shaw", "Mary Slessor", "Lord Lugard", "Mungo Park",
     "A", "Flora Shaw, a journalist with The Times of London who later married Lord Lugard, coined the name from the River Niger."),
    (T_HIST, "Easy", "Nigeria's first and only Prime Minister was",
     "Nnamdi Azikiwe", "Obafemi Awolowo", "Abubakar Tafawa Balewa", "Ahmadu Bello",
     "C", "Sir Abubakar Tafawa Balewa led the government from 1957 until the January 1966 coup in which he was killed."),
    (T_HIST, "Easy", "Nigeria's first President, a ceremonial head of state from 1963, was",
     "Shehu Shagari", "Nnamdi Azikiwe", "Obafemi Awolowo", "Aguiyi-Ironsi",
     "B", "Dr Nnamdi Azikiwe was Governor-General from 1960 and President from 1963 to 1966."),
    (T_HIST, "Medium", "Nigeria's first executive President, elected in 1979, was",
     "Olusegun Obasanjo", "Nnamdi Azikiwe", "Shehu Shagari", "Moshood Abiola",
     "C", "Alhaji Shehu Shagari of the NPN was the first President with executive powers under the 1979 Constitution."),
    (T_HIST, "Medium", "Nigeria's first military Head of State, after the coup of January 1966, was",
     "Yakubu Gowon", "Aguiyi-Ironsi", "Murtala Mohammed", "Odumegwu Ojukwu",
     "B", "Major-General Johnson Aguiyi-Ironsi took power in January 1966 and was killed in the counter-coup of July 1966."),
    (T_HIST, "Easy", "The Nigerian Civil War was fought between",
     "1960 and 1963", "1966 and 1970", "1970 and 1975", "1967 and 1970",
     "D", "The war began on 6 July 1967 and ended on 15 January 1970 with the surrender of Biafra."),
    (T_HIST, "Medium", "The Head of State of Nigeria throughout the civil war was",
     "Yakubu Gowon", "Aguiyi-Ironsi", "Murtala Mohammed", "Olusegun Obasanjo",
     "A", "General Yakubu Gowon led Nigeria from 1966 to 1975 and declared 'no victor, no vanquished' at the end of the war."),
    (T_HIST, "Easy", "Democracy Day, celebrated on 12 June, marks the presidential election of 1993 widely believed to have been won by",
     "Bashir Tofa", "Ernest Shonekan", "Moshood Abiola", "Olusegun Obasanjo",
     "C", "The 12 June 1993 election won by Chief M.K.O. Abiola of the SDP was annulled by General Babangida; 12 June became Democracy Day in 2018."),
    (T_HIST, "Easy", "Nigeria returned to civilian rule on 29 May 1999 with the swearing-in of",
     "Shehu Shagari", "Olusegun Obasanjo", "Umaru Yar'Adua", "Ernest Shonekan",
     "B", "Chief Olusegun Obasanjo won the 1999 election and served two terms until 2007."),
    (T_HIST, "Medium", "The military leader who handed over power to elected civilians on 29 May 1999 was",
     "Sani Abacha", "Ibrahim Babangida", "Abdulsalami Abubakar", "Muhammadu Buhari",
     "C", "General Abdulsalami Abubakar took over after Abacha's death in June 1998 and completed the transition within a year."),
    (T_HIST, "Medium", "Which leader ruled Nigeria as a military Head of State from 1983 to 1985 and later as elected President from 2015 to 2023?",
     "Olusegun Obasanjo", "Ibrahim Babangida", "Yakubu Gowon", "Muhammadu Buhari",
     "D", "Buhari came to power in the December 1983 coup and won the 2015 and 2019 elections as a civilian."),
    (T_HIST, "Medium", "The military Head of State assassinated in the failed coup of 13 February 1976 was",
     "Murtala Mohammed", "Aguiyi-Ironsi", "Sani Abacha", "Yakubu Gowon",
     "A", "General Murtala Mohammed was killed in Lagos in the coup led by Lt-Col. Dimka; Obasanjo succeeded him."),
    (T_HIST, "Medium", "Who became President of Nigeria in May 2010 following the death of President Umaru Yar'Adua?",
     "Namadi Sambo", "Goodluck Jonathan", "Atiku Abubakar", "Muhammadu Buhari",
     "B", "Vice-President Goodluck Jonathan was sworn in on 6 May 2010 and won the election of 2011."),
    (T_HIST, "Easy", "The Nigerian flag was designed in 1959 by",
     "Ben Enwonwu", "Pa Benedict Odiase", "Michael Taiwo Akinkunmi", "Aina Onabolu",
     "C", "Taiwo Akinkunmi, then a student in London, won the national competition for the flag design."),
    (T_HIST, "Easy", "On the Nigerian flag, the green bands stand for",
     "agriculture", "the Niger and Benue rivers", "peace", "oil wealth",
     "A", "Green represents agriculture and the land's fertility; the white band represents peace and unity."),
    (T_HIST, "Medium", "In May 2024 Nigeria re-adopted its old national anthem, which begins with the words",
     "'Arise, O compatriots'", "'Nigeria, we hail thee'", "'Oh God of creation'", "'The labour of our heroes past'",
     "B", "The National Anthem Act 2024, signed on 29 May 2024, restored 'Nigeria, We Hail Thee', which had been used from 1960 to 1978."),
    (T_HIST, "Medium", "On Nigeria's coat of arms, the Y-shaped white wavy bands on the black shield represent",
     "unity in diversity", "the Atlantic Ocean", "the rivers Niger and Benue", "the six geopolitical zones",
     "C", "The two bands meeting on the shield stand for the Niger and the Benue meeting at Lokoja; the black shield is Nigeria's fertile soil."),
    (T_HIST, "Medium", "The motto written under Nigeria's coat of arms is",
     "'One Nation, One Destiny'", "'Peace and Unity'", "'Faith, Work and Progress'", "'Unity and Faith, Peace and Progress'",
     "D", "The coat of arms carries the motto 'Unity and Faith, Peace and Progress'."),
    (T_HIST, "Easy", "Nigeria's oldest university, founded in 1948, is the",
     "University of Nigeria, Nsukka", "University of Lagos", "University of Ibadan", "Ahmadu Bello University",
     "C", "The University College, Ibadan, opened in 1948 as a college of the University of London and became a full university in 1962."),
    (T_HIST, "Medium", "The first indigenous university in Nigeria, opened in 1960 by Dr Nnamdi Azikiwe, is the",
     "University of Nigeria, Nsukka", "University of Ibadan", "University of Ife", "University of Lagos",
     "A", "UNN opened in October 1960; UI was founded earlier but as a college of the University of London."),
    (T_HIST, "Medium", "The naira replaced the Nigerian pound as the national currency on",
     "1 October 1960", "1 January 1973", "1 January 1980", "29 May 1999",
     "B", "Nigeria changed to the decimal naira and kobo on 1 January 1973."),
    (T_HIST, "Medium", "The National Youth Service Corps (NYSC) was established in 1973 by the government of",
     "Olusegun Obasanjo", "Murtala Mohammed", "Shehu Shagari", "Yakubu Gowon",
     "D", "Gowon set up the NYSC by decree in May 1973 to promote national unity after the civil war."),
    (T_HIST, "Medium", "Nigeria's last national population census, held in 2006, put the population at about",
     "88 million", "120 million", "140 million", "200 million",
     "C", "The 2006 census recorded about 140 million people; a new census has been postponed several times since 2023."),
    (T_HIST, "Medium", "Nigeria celebrated its 65th independence anniversary on 1 October",
     "2024", "2025", "2026", "2023",
     "B", "Independence was in 1960, so the 65th anniversary fell on 1 October 2025 and the 66th on 1 October 2026."),
    (T_HIST, "Medium", "The first woman to serve as Chief Justice of Nigeria, sworn in in 2012, was",
     "Justice Kudirat Kekere-Ekun", "Justice Mary Odili", "Justice Zainab Bulkachuwa", "Justice Aloma Mariam Mukhtar",
     "D", "Justice Aloma Mariam Mukhtar was CJN from 2012 to 2014; Justice Kekere-Ekun in 2024 became the second woman in the office."),
    (T_HIST, "Easy", "The first African to win the Nobel Prize in Literature, in 1986, was",
     "Chinua Achebe", "Wole Soyinka", "Ben Okri", "Chimamanda Adichie",
     "B", "Professor Wole Soyinka won the Nobel Prize in Literature in 1986."),
    (T_HIST, "Easy", "The 1958 novel 'Things Fall Apart', one of the most widely read African books, was written by",
     "Chinua Achebe", "Cyprian Ekwensi", "Wole Soyinka", "Amos Tutuola",
     "A", "Chinua Achebe's 'Things Fall Apart' tells the story of Okonkwo and the coming of colonial rule to Umuofia."),
    (T_HIST, "Hard", "The port city annexed by Britain in 1861, becoming the first British colony in what is now Nigeria, was",
     "Calabar", "Port Harcourt", "Lagos", "Badagry",
     "C", "Lagos was annexed as a Crown colony in 1861; the protectorates of the interior came later in the 1880s and 1890s."),
    (T_HIST, "Medium", "General Sani Abacha's creation of six new states in 1996 raised the number of states in Nigeria to",
     "30", "36", "32", "21",
     "B", "Abacha created Bayelsa, Ebonyi, Ekiti, Gombe, Nasarawa and Zamfara on 1 October 1996, bringing the total to 36."),

    # ------------------------------------------------------------------ economy & institutions
    (T_ECON, "Easy", "The National Minimum Wage Act signed in July 2024 fixed Nigeria's minimum monthly wage at",
     "₦30,000", "₦60,000", "₦70,000", "₦100,000",
     "C", "President Tinubu signed the Act on 29 July 2024, raising the minimum wage from ₦30,000 to ₦70,000."),
    (T_ECON, "Easy", "The petrol subsidy in Nigeria was ended by the President's announcement 'subsidy is gone' on",
     "29 May 2023", "1 January 2024", "12 June 2023", "1 October 2023",
     "A", "The removal was announced in President Tinubu's inaugural speech on 29 May 2023, and pump prices rose sharply the same week."),
    (T_ECON, "Easy", "The Dangote Petroleum Refinery, the largest single-train refinery in the world, is located at",
     "Bonny, Rivers State", "Warri, Delta State", "Kaduna", "Lekki, Lagos State",
     "D", "The 650,000 barrels-per-day refinery in the Lekki Free Zone was commissioned on 22 May 2023."),
    (T_ECON, "Medium", "The refining capacity of the Dangote Refinery is about",
     "650,000 barrels per day", "210,000 barrels per day", "1.5 million barrels per day", "445,000 barrels per day",
     "A", "At 650,000 barrels per day it exceeds the combined capacity of Nigeria's four government-owned refineries."),
    (T_ECON, "Medium", "When the National Bureau of Statistics rebased Nigeria's GDP in July 2025, it changed the base year from 2010 to",
     "2015", "2019", "2020", "2023",
     "B", "The 2025 rebasing used 2019 as the new base year and put the 2024 GDP at about ₦372.8 trillion."),
    (T_ECON, "Hard", "After the 2025 GDP rebasing, which sector moved up to become the third-largest in Nigeria's economy, pushing crude oil and gas to fifth place?",
     "Telecommunications", "Manufacturing", "Real estate", "Financial services",
     "C", "The rebased figures ranked real estate third behind crop production and trade, with crude petroleum and natural gas fifth."),
    (T_ECON, "Easy", "The government agency that publishes Nigeria's inflation, unemployment and GDP figures is the",
     "Central Bank of Nigeria", "National Bureau of Statistics", "Budget Office of the Federation", "Nigeria Revenue Service",
     "B", "The National Bureau of Statistics (NBS) is Nigeria's official statistical agency."),
    (T_ECON, "Hard", "Under the tax reform laws signed in 2025, the Federal Inland Revenue Service was replaced from January 2026 by the",
     "Nigeria Revenue Service", "Joint Tax Board", "Federal Tax Authority", "National Revenue Agency",
     "A", "The Nigeria Revenue Service (Establishment) Act 2025 created the NRS to collect federal taxes and non-tax revenue in place of FIRS."),
    (T_ECON, "Hard", "The Nigeria Tax Act 2025 merged the education tax, NASENI and NITDA levies into a single 4% charge on company profits called the",
     "Consolidated Revenue Levy", "Development Levy", "Education Trust Levy", "Solidarity Levy",
     "B", "The 4% Development Levy replaces several separate levies and funds bodies such as TETFund, NELFUND and NASENI."),
    (T_ECON, "Medium", "The Nigerian Education Loan Fund (NELFUND), created by the Student Loans Act of 2024, gives students",
     "free university tuition", "loans for tuition and upkeep", "bursaries for teachers only", "scholarships to study abroad",
     "B", "NELFUND lends tuition and upkeep money to students in public tertiary institutions, repayable after graduation and employment."),
    (T_ECON, "Medium", "The Petroleum Industry Act of 2021 turned the national oil company into a limited liability company known as",
     "Nigerian Petroleum Corporation Plc", "NNPC Limited", "Nigeria Oil and Gas Authority", "NNPC Holdings",
     "B", "NNPC Limited was incorporated in 2021 and unveiled in July 2022 as a commercial company under the Petroleum Industry Act."),
    (T_ECON, "Easy", "Nigeria became a member of the Organisation of the Petroleum Exporting Countries (OPEC) in",
     "1960", "1985", "1971", "1979",
     "C", "Nigeria joined OPEC in 1971; the organisation's headquarters is in Vienna, Austria."),
    (T_ECON, "Easy", "The institution that issues Nigeria's currency and manages the country's monetary policy is the",
     "Nigeria Deposit Insurance Corporation", "Central Bank of Nigeria", "Federal Ministry of Finance", "Bank of Industry",
     "B", "The Central Bank of Nigeria, established in 1958, issues the naira and sets the monetary policy rate."),
    (T_ECON, "Medium", "The digital form of the naira launched by the Central Bank in October 2021 is called the",
     "eNaira", "NairaCoin", "CBN Pay", "Naira Digital",
     "A", "The eNaira, launched on 25 October 2021, is a central bank digital currency, not a cryptocurrency."),
    (T_ECON, "Easy", "The BVN that every bank customer in Nigeria must have stands for",
     "Bank Validation Network", "Basic Verification Notice", "Bank Verification Number", "Biometric Value Number",
     "C", "The Bank Verification Number, introduced by the CBN in 2014, links a customer's biometrics to all their bank accounts."),
    (T_ECON, "Easy", "The National Identification Number (NIN) is issued by the",
     "National Population Commission", "Nigeria Immigration Service", "Independent National Electoral Commission", "National Identity Management Commission",
     "D", "NIMC enrols citizens and residents and issues the 11-digit NIN used for SIM cards, passports and banking."),
    (T_ECON, "Medium", "The agency that protects depositors by insuring the money kept in Nigerian banks is the",
     "Securities and Exchange Commission", "Nigeria Deposit Insurance Corporation", "Asset Management Corporation", "Bank of Industry",
     "B", "The NDIC pays insured depositors when a bank fails; the SEC regulates the capital market instead."),
    (T_ECON, "Medium", "The body that regulates Nigeria's capital market, including the stock exchange, is the",
     "Securities and Exchange Commission", "Nigeria Deposit Insurance Corporation", "Corporate Affairs Commission", "Central Bank of Nigeria",
     "A", "The SEC regulates the capital market; shares are traded on the Nigerian Exchange (NGX)."),
    (T_ECON, "Medium", "Lekki Deep Sea Port, Nigeria's first deep seaport, was commissioned in January 2023 in",
     "Rivers State", "Cross River State", "Lagos State", "Akwa Ibom State",
     "C", "The port in the Lekki Free Zone, Lagos, can berth much larger vessels than Apapa and Tin Can Island."),
    (T_ECON, "Medium", "The Second Niger Bridge links Asaba in Delta State with",
     "Lokoja in Kogi State", "Onitsha in Anambra State", "Ajaokuta in Kogi State", "Aba in Abia State",
     "B", "The 1.6 km bridge, opened to traffic in 2022-2023, relieves the old Niger Bridge between Asaba and Onitsha."),
    (T_ECON, "Medium", "The 700-kilometre coastal highway under construction from Lagos is planned to end in",
     "Port Harcourt", "Warri", "Uyo", "Calabar",
     "D", "The Lagos-Calabar Coastal Highway runs through the coastal states to Calabar in Cross River State."),
    (T_ECON, "Medium", "The Lagos Blue Line, the first rail line of the Lagos light-rail network opened in 2023, runs from Marina to",
     "Ikeja", "Mile 2", "Agbado", "Lekki",
     "B", "The first phase of the Blue Line runs from Marina to Mile 2; the Red Line, opened in 2024, runs towards Agbado."),
    (T_ECON, "Easy", "Nigeria's biggest export and main source of foreign exchange is",
     "cocoa", "crude oil", "solid minerals", "palm oil",
     "B", "Crude oil and gas provide most of Nigeria's export earnings, although agriculture employs more people."),
    (T_ECON, "Medium", "The Nigeria LNG plant, which exports liquefied natural gas, is located on",
     "Bonny Island, Rivers State", "Escravos, Delta State", "Brass, Bayelsa State", "Snake Island, Lagos State",
     "A", "NLNG's six trains (with a seventh under construction) are on Bonny Island in Rivers State."),
    (T_ECON, "Medium", "The Ajaokuta Steel Company, Nigeria's largest steel project, is located in",
     "Kogi State", "Delta State", "Kaduna State", "Plateau State",
     "A", "Ajaokuta is in Kogi State, near the iron-ore deposits of Itakpe."),
    (T_ECON, "Medium", "The Kainji Dam, Nigeria's oldest large hydroelectric dam, is built on the",
     "River Benue", "River Kaduna", "River Niger", "River Ogun",
     "C", "Kainji Dam in Niger State was completed in 1968 on the River Niger; Jebba and Shiroro dams came later."),
    (T_ECON, "Easy", "President Tinubu's overall development programme is known as the",
     "Transformation Agenda", "Renewed Hope Agenda", "Seven-Point Agenda", "Vision 20:2020",
     "B", "'Renewed Hope' was the slogan of the 2023 campaign and the name of the administration's agenda."),
    (T_ECON, "Medium", "The busiest airport in Nigeria, serving Lagos, is named after",
     "Nnamdi Azikiwe", "Murtala Muhammed", "Mallam Aminu Kano", "Sam Mbakwe",
     "B", "Murtala Muhammed International Airport is in Ikeja, Lagos; Abuja's airport is named after Nnamdi Azikiwe."),
    (T_ECON, "Medium", "Mobile network operators such as MTN, Airtel and Glo are regulated in Nigeria by the",
     "National Broadcasting Commission", "Nigerian Communications Commission", "NITDA", "Federal Ministry of Information",
     "B", "The NCC licenses telecom operators and sets rules on tariffs, SIM registration and quality of service."),
    (T_ECON, "Medium", "Nigeria's first satellite, launched in September 2003, was",
     "NigComSat-1", "NigeriaSat-X", "NigeriaSat-1", "NigeriaSat-2",
     "C", "NigeriaSat-1, an earth-observation satellite built for NASRDA, was launched from Russia in 2003."),
    (T_ECON, "Hard", "The African Continental Free Trade Area (AfCFTA), under which trading started on 1 January 2021, has its secretariat in",
     "Abuja, Nigeria", "Accra, Ghana", "Addis Ababa, Ethiopia", "Kigali, Rwanda",
     "B", "The AfCFTA Secretariat is in Accra; the agreement was signed in Kigali in 2018 and Nigeria signed in 2019."),
    (T_ECON, "Medium", "The unit into which one naira is divided is the",
     "cent", "kobo", "shilling", "pence",
     "B", "One naira is made up of 100 kobo."),

    # ------------------------------------------------------------------ elections & politics
    (T_ELEC, "Medium", "Under INEC's revised timetable, Nigeria's presidential and National Assembly elections of 2027 hold on",
     "Saturday 20 February 2027", "Saturday 6 February 2027", "Saturday 16 January 2027", "Saturday 25 February 2027",
     "C", "INEC moved the 2027 elections forward under the Electoral Act 2026: presidential and National Assembly polls on 16 January 2027, the first January presidential election since 1999."),
    (T_ELEC, "Medium", "Under the revised INEC timetable, the governorship and State Houses of Assembly elections of 2027 hold on",
     "6 February 2027", "6 March 2027", "16 January 2027", "13 March 2027",
     "A", "Governorship and State Assembly elections were fixed for Saturday 6 February 2027, three weeks after the presidential poll."),
    (T_ELEC, "Hard", "The new electoral law signed in 2026 that changed the timing of the 2027 elections repealed the",
     "Electoral Act 2010", "Electoral Act 2006", "Electoral Act 2015", "Electoral Act 2022",
     "D", "The Electoral Act 2026 repealed and replaced the Electoral Act 2022 that governed the 2023 general election."),
    (T_ELEC, "Easy", "In Nigerian elections, BVAS stands for",
     "Biometric Voter Authentication Service", "Bimodal Voter Accreditation System", "Ballot Verification and Audit System", "Basic Voter Access Scheme",
     "B", "The BVAS device accredits voters by fingerprint or face and uploads polling-unit results."),
    (T_ELEC, "Medium", "The INEC portal on which polling-unit result sheets are uploaded for the public to view is called",
     "IReV", "e-Collation", "INEC Live", "ResultHub",
     "A", "IReV, the INEC Result Viewing portal, displays scanned Form EC8A results from polling units."),
    (T_ELEC, "Easy", "Nigeria's most recent presidential election, won by Bola Tinubu, was held on",
     "25 February 2023", "23 February 2019", "18 March 2023", "28 March 2015",
     "A", "The presidential and National Assembly elections held on 25 February 2023; governorship elections followed on 18 March 2023."),
    (T_ELEC, "Medium", "In the 2023 presidential election, the candidate who came second was",
     "Peter Obi (Labour Party)", "Rabiu Kwankwaso (NNPP)", "Atiku Abubakar (PDP)", "Yemi Osinbajo (APC)",
     "C", "INEC declared Tinubu (APC) winner with Atiku Abubakar (PDP) second and Peter Obi (Labour Party) third."),
    (T_ELEC, "Medium", "Which of these states holds its governorship election outside the general election cycle (an 'off-cycle' election)?",
     "Lagos", "Kano", "Rivers", "Anambra",
     "D", "Eight states vote off-cycle because of past court judgments: Anambra, Bayelsa, Edo, Ekiti, Imo, Kogi, Ondo and Osun."),
    (T_ELEC, "Medium", "Governor Charles Soludo of Anambra State belongs to which political party?",
     "APGA", "APC", "PDP", "Labour Party",
     "A", "The All Progressives Grand Alliance has governed Anambra since 2006; Soludo was re-elected on its platform in November 2025."),
    (T_ELEC, "Easy", "The full name of INEC is the",
     "Independent Nigerian Electoral Council", "Independent National Electoral Commission", "Interim National Election Committee", "Integrated National Electoral Commission",
     "B", "INEC, the Independent National Electoral Commission, was established in 1998 to organise federal and state elections."),
    (T_ELEC, "Medium", "The exercise through which INEC registers new voters between elections is called",
     "Voter Card Collection", "Electoral Roll Update", "Continuous Voter Registration", "Voter Enumeration",
     "C", "Continuous Voter Registration (CVR) allows citizens who turn 18 or relocate to register or transfer their registration."),
    (T_ELEC, "Medium", "The party that has controlled the federal government since 2015 is the",
     "PDP", "APC", "APGA", "Labour Party",
     "B", "The All Progressives Congress won the presidency in 2015 (Buhari) and 2023 (Tinubu)."),
    (T_ELEC, "Medium", "The Chairman of INEC is appointed by the President subject to confirmation by the",
     "Council of State only", "Supreme Court", "House of Representatives", "Senate",
     "D", "The Constitution requires Senate confirmation of the INEC Chairman after consultation with the Council of State."),
    (T_ELEC, "Hard", "To be declared winner of a presidential election in Nigeria at the first ballot, a candidate needs the highest number of votes and at least one-quarter of the votes in",
     "all 36 states", "two-thirds of the states and the FCT", "half of the states", "the six geopolitical zones",
     "B", "Section 134 requires the highest votes plus not less than 25% in at least two-thirds of the 36 states and the FCT."),
    (T_ELEC, "Medium", "The annulled presidential election of 12 June 1993 was conducted under the military government of",
     "Sani Abacha", "Ibrahim Babangida", "Muhammadu Buhari", "Abdulsalami Abubakar",
     "B", "General Babangida's government annulled the election; he 'stepped aside' in August 1993 for the Shonekan interim government."),
    (T_ELEC, "Medium", "In Nigerian elections, the card a registered voter presents at the polling unit is the",
     "National Identity Card", "Permanent Voter Card", "Voter Access Card", "Electoral Slip",
     "B", "The Permanent Voter Card (PVC) is issued by INEC after registration and is read by the BVAS on election day."),

    # ------------------------------------------------------------------ security & law enforcement
    (T_SEC, "Easy", "The agency responsible for investigating advance-fee fraud, money laundering and other financial crimes in Nigeria is the",
     "ICPC", "EFCC", "NDLEA", "DSS",
     "B", "The Economic and Financial Crimes Commission was established in 2003."),
    (T_SEC, "Medium", "The ICPC, set up in 2000, deals mainly with",
     "drug trafficking", "road accidents", "corruption in public offices", "counterfeit drugs",
     "C", "The Independent Corrupt Practices and Other Related Offences Commission investigates bribery and abuse of office in the public service."),
    (T_SEC, "Easy", "The Nigerian agency that arrests drug traffickers and destroys cannabis farms is the",
     "NSCDC", "NAFDAC", "NDLEA", "NAPTIP",
     "C", "The National Drug Law Enforcement Agency was established in 1989."),
    (T_SEC, "Medium", "The paramilitary agency that protects pipelines, power installations and other critical national infrastructure is the",
     "Nigeria Security and Civil Defence Corps", "Federal Road Safety Corps", "Nigeria Immigration Service", "Nigerian Correctional Service",
     "A", "The NSCDC also supervises private guard companies and protects schools under the Safe Schools initiative."),
    (T_SEC, "Easy", "The body that enforces traffic laws and issues driver's licences and number plates on Nigerian highways is the",
     "Nigeria Police Force", "Federal Road Safety Corps", "VIO", "NSCDC",
     "B", "The Federal Road Safety Corps was established in 1988."),
    (T_SEC, "Medium", "Nigeria's domestic intelligence and internal security service is the",
     "National Intelligence Agency", "Defence Intelligence Agency", "Department of State Services", "Nigeria Security and Civil Defence Corps",
     "C", "The DSS handles internal security; the NIA handles foreign intelligence and the DIA military intelligence."),
    (T_SEC, "Medium", "The agency that fights human trafficking in Nigeria is",
     "NAPTIP", "NDLEA", "NEMA", "NOA",
     "A", "The National Agency for the Prohibition of Trafficking in Persons was established in 2003."),
    (T_SEC, "Medium", "The agency that coordinates the response to floods, building collapses and other disasters in Nigeria is",
     "NCDC", "NEMA", "NSCDC", "NOA",
     "B", "The National Emergency Management Agency coordinates disaster response; state agencies are called SEMAs."),
    (T_SEC, "Easy", "The Nigerian Defence Academy, which trains officers for the Army, Navy and Air Force, is located in",
     "Abuja", "Jaji", "Kaduna", "Zaria",
     "C", "The NDA has been in Kaduna since 1964."),
    (T_SEC, "Easy", "Which of these is NOT one of the three services of the Nigerian Armed Forces?",
     "Nigerian Army", "Nigerian Navy", "Nigerian Air Force", "Nigeria Police Force",
     "D", "The Armed Forces are the Army, Navy and Air Force; the police is a separate civil force under the Inspector-General."),
    (T_SEC, "Medium", "The Nigeria Immigration Service is responsible for",
     "issuing international passports", "registering companies", "collecting import duties", "insuring bank deposits",
     "A", "The NIS issues Nigerian passports, controls the borders and regulates the stay of foreigners; Customs collects duties."),
    (T_SEC, "Medium", "The Western Nigeria Security Network launched by the six South-West states in January 2020 is popularly called",
     "Ebube Agu", "Hisbah", "Amotekun", "Civilian JTF",
     "C", "Amotekun ('leopard' in Yoruba) supports the police in Ekiti, Lagos, Ogun, Ondo, Osun and Oyo states."),
    (T_SEC, "Easy", "Nigeria has a single national police force headed by the",
     "Minister of Police Affairs", "Chief of Defence Staff", "Inspector-General of Police", "Police Service Commission",
     "C", "Policing is on the exclusive legislative list, so there is one Nigeria Police Force under the Inspector-General; states cannot yet run their own."),
    (T_SEC, "Medium", "The agency that registers and regulates food, drugs, cosmetics and bottled water in Nigeria is",
     "NAFDAC", "SON", "NCDC", "CPC",
     "A", "NAFDAC, set up in 1993, gives products their registration numbers; SON sets standards for other goods."),

    # ------------------------------------------------------------------ geography, infrastructure & culture
    (T_GEO, "Easy", "The rivers Niger and Benue meet at",
     "Onitsha", "Lokoja", "Jebba", "Makurdi",
     "B", "The confluence is at Lokoja in Kogi State, which was also Lugard's first administrative capital."),
    (T_GEO, "Medium", "The highest point in Nigeria, Chappal Waddi, is located in",
     "Plateau State", "Adamawa State", "Taraba State", "Cross River State",
     "C", "Chappal Waddi (about 2,419 m) is in the Gashaka-Gumti area of Taraba State near the Cameroon border."),
    (T_GEO, "Easy", "The largest state in Nigeria by land area is",
     "Borno", "Kaduna", "Kano", "Niger",
     "D", "Niger State covers about 76,000 square kilometres; Lagos is the smallest state by area."),
    (T_GEO, "Easy", "The country on Nigeria's western border is",
     "Cameroon", "Benin Republic", "Chad", "Ghana",
     "B", "Benin lies to the west, Niger to the north, Chad to the north-east and Cameroon to the east."),
    (T_GEO, "Easy", "Nigeria shares its eastern border with",
     "Cameroon", "Togo", "Niger", "Benin Republic",
     "A", "Cameroon borders Nigeria to the east, from the Lake Chad area down to the Bakassi peninsula."),
    (T_GEO, "Medium", "Zuma Rock, the landmark on the Abuja-Kaduna road, actually stands in",
     "Kaduna State", "the FCT", "Niger State", "Nasarawa State",
     "C", "Zuma Rock is in Madalla, Niger State, just outside the FCT boundary."),
    (T_GEO, "Easy", "Olumo Rock, a famous tourist site and place of refuge during the 19th-century wars, is in",
     "Ibadan", "Abeokuta", "Ile-Ife", "Oyo",
     "B", "Olumo Rock is in Abeokuta, the capital of Ogun State."),
    (T_GEO, "Easy", "Nigeria's time zone is West Africa Time, which is",
     "GMT + 1", "GMT + 2", "GMT", "GMT − 1",
     "A", "Nigeria is one hour ahead of Greenwich Mean Time all year round."),
    (T_GEO, "Easy", "Nigeria's southern coastline lies on the",
     "Gulf of Aden", "Red Sea", "Gulf of Guinea", "Mediterranean Sea",
     "C", "The Gulf of Guinea is part of the Atlantic Ocean; the Niger Delta opens into it."),
    (T_GEO, "Medium", "Moving from the coast northwards, the correct order of Nigeria's vegetation belts is",
     "rainforest, mangrove swamp, savanna, Sahel", "mangrove swamp, rainforest, savanna, Sahel", "savanna, rainforest, mangrove swamp, Sahel", "Sahel, savanna, rainforest, mangrove swamp",
     "B", "Rainfall decreases northwards: mangrove swamp on the coast, then rainforest, then Guinea and Sudan savanna, then Sahel in the far north."),
    (T_GEO, "Medium", "The Argungu International Fishing Festival is held in",
     "Kebbi State", "Sokoto State", "Niger State", "Kwara State",
     "A", "Argungu is on the Sokoto River in Kebbi State; the festival dates from 1934."),
    (T_GEO, "Medium", "The Osun-Osogbo Sacred Grove, a UNESCO World Heritage Site, is in",
     "Oyo State", "Ekiti State", "Osun State", "Ondo State",
     "C", "The grove on the outskirts of Osogbo was listed by UNESCO in 2005 and hosts the annual Osun festival."),
    (T_GEO, "Hard", "Nigeria's first UNESCO World Heritage Site, listed in 1999, is the Sukur Cultural Landscape in",
     "Adamawa State", "Borno State", "Taraba State", "Bauchi State",
     "A", "Sukur, in the Mandara Mountains of Adamawa State, was listed in 1999; Osun-Osogbo followed in 2005."),
    (T_GEO, "Easy", "The Eyo masquerade festival is associated with",
     "Kano", "Benin City", "Lagos", "Calabar",
     "C", "Eyo, with its white-robed masquerades, is a Lagos Island festival held to honour a departed chief or oba."),
    (T_GEO, "Easy", "The annual Durbar, a procession of horsemen marking the end of Ramadan and Eid, is best known in",
     "Kano", "Enugu", "Ibadan", "Uyo",
     "A", "The Kano Durbar, recognised by UNESCO in 2024, is held at the Emir's palace; Katsina, Zaria and Bida also hold durbars."),
    (T_GEO, "Easy", "The month-long Calabar Carnival, called 'Africa's biggest street party', is held in",
     "Akwa Ibom State", "Cross River State", "Rivers State", "Bayelsa State",
     "B", "The carnival runs through December in Calabar, capital of Cross River State."),
    (T_GEO, "Easy", "The dry, dusty north-east wind that blows from the Sahara over Nigeria between November and March is the",
     "monsoon", "trade wind", "harmattan", "sirocco",
     "C", "The harmattan brings cool mornings, dust haze and dry skin in the dry season."),
    (T_GEO, "Medium", "Lake Chad is shared by Nigeria, Chad, Niger and",
     "Sudan", "Benin", "Cameroon", "Central African Republic",
     "C", "The four countries of the Lake Chad Basin are Nigeria, Niger, Chad and Cameroon."),
    (T_GEO, "Easy", "The Nigerian city nicknamed the 'Coal City' is",
     "Jos", "Enugu", "Kaduna", "Warri",
     "B", "Coal was mined at Enugu from 1909; Port Harcourt is the 'Garden City' and Jos the 'Tin City'."),
    (T_GEO, "Easy", "Nigeria's most populous city and commercial capital is",
     "Abuja", "Kano", "Ibadan", "Lagos",
     "D", "Lagos, the capital until 1991, remains the largest city and the centre of commerce and finance."),
    (T_GEO, "Easy", "Nigeria's film industry is popularly known as",
     "Bollywood", "Nollywood", "Naijawood", "Kannywood",
     "B", "Nollywood is one of the largest film industries in the world by number of films; Kannywood is the Hausa-language industry in Kano."),
    (T_GEO, "Easy", "The three most widely spoken indigenous languages in Nigeria are",
     "Hausa, Igbo and Yoruba", "Hausa, Fulfulde and Kanuri", "Yoruba, Edo and Ijaw", "Igbo, Efik and Tiv",
     "A", "Hausa, Igbo and Yoruba are recognised as the major national languages alongside English, the official language."),
    (T_GEO, "Medium", "The town on Nigeria's border with Benin Republic that was a major slave port and now hosts a 'Point of No Return' monument is",
     "Badagry", "Calabar", "Bonny", "Brass",
     "A", "Badagry in Lagos State has slave-trade relics and the 'Point of No Return' on Gberefu Island."),

    # ------------------------------------------------------------------ Africa & the world
    (T_WORLD, "Easy", "The headquarters of the African Union is in",
     "Abuja, Nigeria", "Nairobi, Kenya", "Addis Ababa, Ethiopia", "Johannesburg, South Africa",
     "C", "The AU, which replaced the OAU in 2002, is headquartered in Addis Ababa."),
    (T_WORLD, "Medium", "The Chairperson of the African Union Commission elected in February 2025 to succeed Moussa Faki is",
     "Raila Odinga", "Mahmoud Ali Youssouf", "Nkosazana Dlamini-Zuma", "Jean Ping",
     "B", "Djibouti's long-serving foreign minister Mahmoud Ali Youssouf defeated Kenya's Raila Odinga after seven rounds of voting."),
    (T_WORLD, "Easy", "ECOWAS, the Economic Community of West African States, was founded in 1975 by the Treaty of",
     "Abuja", "Accra", "Dakar", "Lagos",
     "D", "The Treaty of Lagos was signed on 28 May 1975; the ECOWAS Commission is now based in Abuja."),
    (T_WORLD, "Medium", "The three countries that formally left ECOWAS in January 2025 to form the Alliance of Sahel States are",
     "Mali, Burkina Faso and Niger", "Chad, Sudan and Libya", "Guinea, Gambia and Senegal", "Mauritania, Mali and Chad",
     "A", "The three military-led states announced their withdrawal in January 2024 and it took effect on 29 January 2025."),
    (T_WORLD, "Easy", "The Secretary-General of the United Nations as at 2026 is",
     "Ban Ki-moon", "Kofi Annan", "António Guterres", "Amina J. Mohammed",
     "C", "António Guterres of Portugal has been UN Secretary-General since January 2017; his second term runs to the end of 2026."),
    (T_WORLD, "Medium", "The Nigerian who served as President of the African Development Bank from 2015 to 2025 is",
     "Akinwumi Adesina", "Ngozi Okonjo-Iweala", "Charles Soludo", "Sanusi Lamido Sanusi",
     "A", "Dr Akinwumi Adesina, a former Minister of Agriculture, completed two five-year terms at the AfDB."),
    (T_WORLD, "Hard", "The Mauritanian economist who became President of the African Development Bank on 1 September 2025 is",
     "Donald Kaberuka", "Sidi Ould Tah", "Tidjane Thiam", "Amadou Hott",
     "B", "Dr Sidi Ould Tah was elected in May 2025 with over 76% of the votes and succeeded Akinwumi Adesina."),
    (T_WORLD, "Medium", "The pope elected on 8 May 2025, the first from the United States, took the name",
     "Benedict XVII", "John Paul III", "Francis II", "Leo XIV",
     "D", "Cardinal Robert Prevost became Pope Leo XIV after the death of Pope Francis in April 2025."),
    (T_WORLD, "Medium", "The 2025 Nobel Peace Prize was awarded to the Venezuelan opposition leader",
     "María Corina Machado", "Juan Guaidó", "Leopoldo López", "Michelle Bachelet",
     "A", "María Corina Machado was honoured on 10 October 2025 for her struggle for democratic rights in Venezuela."),
    (T_WORLD, "Easy", "The President of the United States inaugurated on 20 January 2025 is",
     "Joe Biden", "Kamala Harris", "Donald Trump", "Barack Obama",
     "C", "Donald Trump returned to the White House as the 47th President after winning the November 2024 election."),
    (T_WORLD, "Medium", "The President of Ghana who took office in January 2025 is",
     "Nana Akufo-Addo", "John Dramani Mahama", "Mahamudu Bawumia", "John Kufuor",
     "B", "John Mahama won the December 2024 election and returned to office for a second, non-consecutive term."),
    (T_WORLD, "Medium", "The first G20 summit held on African soil took place in November 2025 in",
     "Cairo, Egypt", "Lagos, Nigeria", "Johannesburg, South Africa", "Nairobi, Kenya",
     "C", "South Africa held the G20 presidency in 2025 and hosted the leaders' summit in Johannesburg."),
    (T_WORLD, "Medium", "The 2025 United Nations climate conference, COP30, was hosted in Belém by",
     "India", "Brazil", "Azerbaijan", "Egypt",
     "B", "COP30 was held in Belém, at the mouth of the Amazon, in November 2025; COP29 was in Baku, Azerbaijan."),
    (T_WORLD, "Easy", "The head of the Commonwealth of Nations, of which Nigeria has been a member since 1960, is",
     "the UN Secretary-General", "the British Prime Minister", "King Charles III", "the Commonwealth Secretary-General",
     "C", "King Charles III succeeded Queen Elizabeth II as Head of the Commonwealth in 2022; the secretariat is in London."),
    (T_WORLD, "Easy", "The headquarters of OPEC is in",
     "Riyadh, Saudi Arabia", "Vienna, Austria", "Geneva, Switzerland", "Doha, Qatar",
     "B", "OPEC has been headquartered in Vienna since 1965."),
    (T_WORLD, "Easy", "The United Nations, which Nigeria joined in October 1960, has its headquarters in",
     "Geneva", "Paris", "New York", "Washington DC",
     "C", "The UN headquarters is in New York; Geneva hosts many UN agencies such as the WHO."),
    (T_WORLD, "Medium", "The ECOWAS Parliament and the ECOWAS Court of Justice sit in",
     "Lomé", "Abuja", "Accra", "Dakar",
     "B", "Nigeria hosts the ECOWAS Commission, Parliament and Court in Abuja."),
    (T_WORLD, "Easy", "The largest country in Africa by land area is",
     "Nigeria", "Sudan", "Democratic Republic of Congo", "Algeria",
     "D", "Algeria became Africa's largest country when Sudan split in 2011; Nigeria is the most populous."),
    (T_WORLD, "Hard", "In January 2025 Nigeria was admitted as a partner country of which grouping of major emerging economies?",
     "G7", "BRICS", "OECD", "ASEAN",
     "B", "Brazil, as chair, announced Nigeria's admission as a BRICS partner country on 17 January 2025."),
    (T_WORLD, "Medium", "The World Health Organisation has its headquarters in",
     "New York", "Geneva", "Rome", "Vienna",
     "B", "The WHO is based in Geneva, Switzerland; its Africa regional office is in Brazzaville."),

    # ------------------------------------------------------------------ sports & entertainment
    (T_SPORT, "Easy", "In the WAFCON final of 26 July 2025 in Rabat, the Super Falcons came from 2-0 down to beat the hosts Morocco",
     "3-2", "2-1", "4-2", "3-1",
     "A", "Nigeria won 3-2 to lift a record tenth Women's Africa Cup of Nations title, the team's 'Mission X'."),
    (T_SPORT, "Medium", "The Super Falcons' victory at the 2024 WAFCON (played in 2025) was Nigeria's",
     "eighth title", "twelfth title", "tenth title", "ninth title",
     "C", "It was Nigeria's tenth WAFCON title in 13 editions of the tournament."),
    (T_SPORT, "Medium", "The Nigerian named Player of the Tournament at the 2024 WAFCON was",
     "Asisat Oshoala", "Rasheedat Ajibade", "Chiamaka Nnadozie", "Esther Okoronkwo",
     "B", "Captain Rasheedat Ajibade won the award; goalkeeper Chiamaka Nnadozie was named best goalkeeper."),
    (T_SPORT, "Medium", "The coach who led the Super Falcons to the 2024 WAFCON title was",
     "Randy Waldrum", "Florence Omagbemi", "Justine Madugu", "Thomas Dennerby",
     "C", "Justine Madugu, who took charge in 2024, was named Coach of the Tournament."),
    (T_SPORT, "Medium", "At the 2025 Africa Cup of Nations hosted by Morocco, the Super Eagles finished in",
     "first place", "second place", "third place", "fourth place",
     "C", "Nigeria won the third-place match; the final was played between Senegal and Morocco."),
    (T_SPORT, "Hard", "The Player of the Tournament at the 2025 Africa Cup of Nations was",
     "Victor Osimhen", "Achraf Hakimi", "Mohamed Salah", "Sadio Mané",
     "D", "Senegal's Sadio Mané was named best player; Morocco's Brahim Díaz won the Golden Boot."),
    (T_SPORT, "Medium", "The 2027 Africa Cup of Nations will be co-hosted by Kenya, Uganda and",
     "Rwanda", "Tanzania", "Ethiopia", "Zambia",
     "B", "The three East African countries will stage the 2027 tournament together."),
    (T_SPORT, "Easy", "The 2026 FIFA World Cup, the first with 48 teams, was hosted jointly by the United States, Canada and",
     "Brazil", "Argentina", "Mexico", "Colombia",
     "C", "The tournament ran from 11 June to 19 July 2026 across the three North American countries."),
    (T_SPORT, "Medium", "The 2026 FIFA World Cup was won by",
     "Argentina", "Spain", "France", "Brazil",
     "B", "Spain beat Argentina 1-0 after extra time in the final at the MetLife Stadium, New Jersey."),
    (T_SPORT, "Medium", "Nigeria missed the 2026 World Cup after losing the CAF play-off final in November 2025 on penalties to",
     "Cameroon", "Gabon", "Democratic Republic of Congo", "Senegal",
     "C", "After a 1-1 draw in Rabat, DR Congo won the shoot-out 4-3; the Super Eagles had beaten Gabon 4-1 in the semi-final."),
    (T_SPORT, "Medium", "The Malian who coached the Super Eagles during the 2026 World Cup qualifiers was",
     "José Peseiro", "Eric Chelle", "Gernot Rohr", "Augustine Eguavoen",
     "B", "Eric Chelle was appointed Super Eagles head coach in January 2025."),
    (T_SPORT, "Medium", "The 2025 men's Ballon d'Or was won by the Paris Saint-Germain forward",
     "Ousmane Dembélé", "Lamine Yamal", "Mohamed Salah", "Vinícius Júnior",
     "A", "Dembélé won the award on 22 September 2025 after PSG's first Champions League title; Lamine Yamal was second."),
    (T_SPORT, "Easy", "The Super Eagles have won the Africa Cup of Nations how many times?",
     "two", "five", "four", "three",
     "D", "Nigeria won in 1980 (Lagos), 1994 (Tunisia) and 2013 (South Africa)."),
    (T_SPORT, "Medium", "The Nigerian who set the women's 100 metres hurdles world record of 12.12 seconds in 2022 is",
     "Blessing Okagbare", "Tobi Amusan", "Ese Brume", "Favour Ofili",
     "B", "Tobi Amusan set the record in the semi-final of the 2022 World Championships in Oregon and went on to win gold."),
    (T_SPORT, "Medium", "Nigeria's first individual Olympic gold medal was won in the long jump at Atlanta 1996 by",
     "Mary Onyali", "Falilat Ogunkoya", "Chioma Ajunwa", "Blessing Okagbare",
     "C", "Chioma Ajunwa jumped 7.12 m to win gold; the 'Dream Team' also won the football gold at the same Games."),
    (T_SPORT, "Medium", "At the 2025 Grammy Awards, the Nigerian singer who won Best African Music Performance for 'Love Me JeJe' was",
     "Ayra Starr", "Tems", "Tiwa Savage", "Yemi Alade",
     "B", "Tems won her second Grammy in February 2025 with 'Love Me JeJe', a reworking of Seyi Sodimu's 1997 hit."),
    (T_SPORT, "Medium", "Nigeria's under-17 team, the Golden Eaglets, has won the FIFA U-17 World Cup a record",
     "three times", "four times", "six times", "five times",
     "D", "The Golden Eaglets won in 1985, 1993, 2007, 2013 and 2015."),
    (T_SPORT, "Easy", "Nigeria's senior women's basketball team is known as",
     "D'Tigers", "Falconets", "D'Tigress", "Super Falcons",
     "C", "D'Tigress is the women's basketball team; D'Tigers are the men, and the Falconets are the under-20 women's footballers."),
    (T_SPORT, "Easy", "The national stadium in Abuja was renamed in 2019 in honour of",
     "Murtala Muhammed", "Moshood Abiola", "Stephen Keshi", "Nnamdi Azikiwe",
     "B", "President Buhari renamed it the Moshood Abiola National Stadium on 12 June 2019."),
    (T_SPORT, "Easy", "The Nigerian musician regarded as the creator of the Afrobeat genre is",
     "King Sunny Adé", "Fela Anikulapo-Kuti", "Burna Boy", "Ebenezer Obey",
     "B", "Fela Kuti developed Afrobeat in the late 1960s, blending highlife, jazz and funk with political lyrics."),
    (T_SPORT, "Medium", "The Super Falcons' semi-final win at the 2024 WAFCON came against the defending champions",
     "Zambia", "Ghana", "Morocco", "South Africa",
     "D", "Nigeria beat South Africa 2-1 with a 94th-minute winner from Michelle Alozie."),

    # ------------------------------------------------------------------ everyday ICT
    (T_ICT, "Easy", "The part of a computer that carries out instructions and is often called its 'brain' is the",
     "hard disk", "central processing unit", "monitor", "keyboard",
     "B", "The CPU processes data; the hard disk stores it and the keyboard and monitor are input and output devices."),
    (T_ICT, "Easy", "Which of these is an INPUT device?",
     "Printer", "Monitor", "Scanner", "Speaker",
     "C", "A scanner sends data into the computer; printers, monitors and speakers send information out."),
    (T_ICT, "Medium", "RAM is described as volatile memory because",
     "it cannot be upgraded", "its contents are lost when power goes off", "it stores files permanently", "it is slower than a hard disk",
     "B", "Random Access Memory holds data only while the computer is on; unsaved work disappears when power is lost."),
    (T_ICT, "Easy", "On a Windows computer, the keyboard shortcut Ctrl + C is used to",
     "close a window", "copy the selected text", "cut the selected text", "cancel printing",
     "B", "Ctrl + C copies, Ctrl + X cuts, Ctrl + V pastes and Ctrl + Z undoes the last action."),
    (T_ICT, "Easy", "The keyboard shortcut Ctrl + S in most programs is used to",
     "search the document", "select all", "save the document", "start a new file",
     "C", "Saving often with Ctrl + S protects your work from being lost."),
    (T_ICT, "Easy", "Which application is best suited for preparing a class budget with automatic totals?",
     "Microsoft Word", "Microsoft Excel", "Microsoft PowerPoint", "Notepad",
     "B", "Excel is a spreadsheet; its cells and formulas add up figures automatically."),
    (T_ICT, "Easy", "In the web address https://www.jamb.gov.ng, the letters 'www' stand for",
     "web wide world", "world wide web", "world web window", "wide world web",
     "B", "The World Wide Web is the system of linked web pages accessed through the internet."),
    (T_ICT, "Medium", "One byte is made up of how many bits?",
     "4", "16", "10", "8",
     "D", "Eight bits make a byte; about 1,024 bytes make a kilobyte and 1,024 kilobytes make a megabyte."),
    (T_ICT, "Easy", "The symbol that must appear in every e-mail address, as in student@gmail.com, is",
     "#", "@", "&", "%",
     "B", "The @ sign separates the user name from the domain name of the mail provider."),
    (T_ICT, "Medium", "A message that pretends to come from your bank and asks you to click a link and enter your PIN is an example of",
     "spam filtering", "phishing", "encryption", "a firewall",
     "B", "Phishing tricks people into revealing passwords, PINs or card details; banks never ask for these by e-mail or SMS."),
    (T_ICT, "Easy", "Which of these is an operating system?",
     "Microsoft Word", "Google Chrome", "Android", "WhatsApp",
     "C", "Android, Windows, iOS and Linux are operating systems; the others are application programs."),
    (T_ICT, "Easy", "The physical parts of a computer that can be touched, such as the mouse and the monitor, are called",
     "software", "firmware", "hardware", "programs",
     "C", "Hardware is the equipment; software is the set of instructions that runs on it."),
    (T_ICT, "Easy", "A program used to visit websites, such as Chrome, Firefox or Safari, is called a",
     "search engine", "web browser", "modem", "server",
     "B", "A browser displays web pages; Google is a search engine that you use inside a browser."),
    (T_ICT, "Medium", "The saying 'garbage in, garbage out' (GIGO) means that",
     "computers must be cleaned often", "old files should be deleted", "wrong input produces wrong output", "computers make their own errors",
     "C", "A computer processes exactly what it is given, so incorrect data leads to incorrect results."),
    (T_ICT, "Medium", "Computers store and process all data using the binary number system, which has the base",
     "10", "16", "8", "2",
     "D", "Binary uses only the digits 0 and 1, matching the on and off states of electronic circuits."),
    (T_ICT, "Medium", "The World Wide Web was invented in 1989 by",
     "Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Mark Zuckerberg",
     "B", "Tim Berners-Lee created the web at CERN; the internet itself is older."),
    (T_ICT, "Easy", "Software that detects and removes viruses and other malicious programs is called",
     "a compiler", "antivirus software", "a spreadsheet", "a browser",
     "B", "Antivirus programs scan files and downloads for malware and should be kept up to date."),
    (T_ICT, "Medium", "Storing your files on services such as Google Drive so you can open them from any device is known as",
     "cloud storage", "cache memory", "a local area network", "flash memory",
     "A", "Cloud storage keeps files on remote servers reached over the internet."),
    (T_ICT, "Easy", "A strong password should",
     "be your date of birth", "mix letters, numbers and symbols", "be the same on every site", "be shared with a friend for safety",
     "B", "Long passwords that combine letters, numbers and symbols, and that are not reused, are hardest to guess."),
    (T_ICT, "Easy", "In a computer-based test like the UTME, the candidate chooses answers mainly with the",
     "printer", "mouse or touchpad", "scanner", "projector",
     "B", "CBT candidates click options with a mouse (or touchpad) and may use the keyboard's letter keys."),
]

if __name__ == "__main__":
    build_batch(S, "batch_041_current_affairs_round1.json", "batch_041_current_affairs_round1",
                "Post-UTME Current Affairs round 1: Nigeria and world general knowledge for university screening tests "
                "(officeholders, constitution, history, economy, elections, security, geography, Africa/world, sports, ICT). "
                "Facts checked September 2026.",
                PASSAGES, PQ, Q, exam_type="POST-UTME")
