"""Batch 022 - Economics round 3, part B (macro-economics and the Nigerian economy).

National income and its measurement, money and banking, inflation and deflation, unemployment, population,
agriculture, industrialisation, trade, international trade, balance of payments, public finance, taxation,
economic development and planning.  Two data passages: a national-income accounts table and a population
table.  Together with batch 021 this takes Economics past 500 curated items and auto-retires the old bank.

    python3 scripts/build_content_batch22.py -> content/batch_022_econ_round3b.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Economics"

PASSAGES = [
    ("E4", "Measurement of National Income", "National income accounts of Country K",
     "The table shows figures for Country K in a year, in billions of naira.\n\n"
     "Consumption expenditure (C)        4,000\n"
     "Gross private investment (I)       1,200\n"
     "Government expenditure (G)         1,500\n"
     "Exports (X)                          900\n"
     "Imports (M)                        1,100\n"
     "Depreciation                         400\n"
     "Net factor income from abroad       -200\n"
     "Population (millions)                 50"),
    ("E5", "Population", "Population figures for two states",
     "The table gives population information for two states in a year.\n\n"
     "                    State A   State B\n"
     "Population (m)         6.0       3.0\n"
     "Land area (000 km2)   20.0      30.0\n"
     "Births per 1,000        45        20\n"
     "Deaths per 1,000        15        10\n"
     "Under 15 years (%)      48        25\n"
     "Over 64 years (%)        3        12"),
]

PQ = [
    ("E4", "Medium", "From the table above, Country K's gross domestic product (GDP) by the expenditure method is",
     "₦6,500 billion", "₦6,900 billion", "₦7,600 billion", "₦6,100 billion", "A",
     "GDP = C + I + G + (X − M) = 4,000 + 1,200 + 1,500 + (900 − 1,100) = ₦6,500 billion.", "4000+1200+1500+900-1100"),
    ("E4", "Medium", "From the table above, Country K's gross national product (GNP) is",
     "₦6,300 billion", "₦6,700 billion", "₦6,500 billion", "₦6,100 billion", "A",
     "GNP = GDP + net factor income from abroad = 6,500 − 200 = ₦6,300 billion.", "6500-200"),
    ("E4", "Medium", "From the table above, Country K's net national product (NNP) is",
     "₦5,900 billion", "₦6,100 billion", "₦6,300 billion", "₦6,700 billion", "A",
     "NNP = GNP − depreciation = 6,300 − 400 = ₦5,900 billion.", "6300-400"),
    ("E4", "Easy", "From the table above, Country K's balance of trade in the year was",
     "a deficit of ₦200 billion", "a surplus of ₦200 billion", "a deficit of ₦2,000 billion", "a surplus of ₦900 billion", "A",
     "Balance of trade = exports − imports = 900 − 1,100 = −₦200 billion, a deficit.", "200"),
    ("E4", "Medium", "From the table above, Country K's per capita GDP is",
     "₦130,000", "₦13,000", "₦1,300,000", "₦126,000", "A",
     "Per capita GDP = GDP ÷ population = ₦6,500 billion ÷ 50 million = ₦130,000.", "6500e9/50e6"),
    ("E4", "Medium", "From the table above, net investment in Country K was",
     "₦800 billion", "₦1,200 billion", "₦1,600 billion", "₦400 billion", "A",
     "Net investment = gross investment − depreciation = 1,200 − 400 = ₦800 billion.", "1200-400"),
    ("E4", "Hard", "The negative net factor income from abroad in the table above means that",
     "foreigners earned more from Country K than its citizens earned abroad", "Country K imported more goods than it exported", "Country K's currency lost value during the year", "the government of Country K borrowed from abroad", "A",
     "Net factor income = income earned abroad by residents − income earned at home by foreigners; a negative figure means the outflow of factor income was larger."),
    ("E4", "Medium", "If the price level in Country K rose by 30% between the base year and the year in the table, the real GDP of the year in base-year prices is",
     "₦5,000 billion", "₦8,450 billion", "₦4,550 billion", "₦6,500 billion", "A",
     "Real GDP = nominal GDP ÷ price index × 100 = 6,500 ÷ 130 × 100 = ₦5,000 billion.", "6500/1.3"),
    ("E5", "Easy", "From the table above, the population density of State A is",
     "300 persons per km²", "100 persons per km²", "200 persons per km²", "120 persons per km²", "A",
     "Density = population ÷ area = 6,000,000 ÷ 20,000 km² = 300 persons per km².", "6e6/20000"),
    ("E5", "Easy", "From the table above, the population density of State B is",
     "100 persons per km²", "300 persons per km²", "10 persons per km²", "90 persons per km²", "A",
     "3,000,000 ÷ 30,000 = 100 persons per km².", "3e6/30000"),
    ("E5", "Medium", "From the table above, the natural rate of population growth of State A is",
     "3% per annum", "4.5% per annum", "1.5% per annum", "6% per annum", "A",
     "Natural growth = birth rate − death rate = 45 − 15 = 30 per 1,000 = 3%.", "3"),
    ("E5", "Medium", "From the table above, the natural increase in State B's population in the year was",
     "30,000 people", "60,000 people", "10,000 people", "90,000 people", "A",
     "Growth rate = (20 − 10)/1,000 = 1%; 1% of 3,000,000 = 30,000.", "0.01*3e6"),
    ("E5", "Medium", "From the table above, the state with the heavier dependency burden is",
     "State A, because over half of its people are children or elderly", "State B, because 12% of its people are over 64", "State B, because it has the larger land area", "State A, because it has the lower death rate", "A",
     "Dependants (under 15 + over 64): State A 51%, State B 37%. A larger share of dependants means fewer workers support each dependant."),
    ("E5", "Hard", "Judging from the table above, the population pyramid of State A would have",
     "a very broad base and a narrow top", "a narrow base and a broad top", "roughly equal width at every age", "a broad top and a narrow middle", "A",
     "High birth rates and 48% under 15 give a wide base; only 3% over 64 makes the top narrow: a typical developing-country pyramid."),
    ("E5", "Medium", "Judging from the table above, which of the following policies is State A most likely to need urgently?",
     "expansion of primary schools and child health services", "more old people's homes and pension schemes", "incentives to raise the birth rate", "policies to attract young immigrants", "A",
     "Nearly half the population of State A is below 15, so schools and child health services face the greatest pressure."),
]

Q = [
    # ---------------- National Income ----------------
    ("National Income", "Easy", "National income is best defined as",
     "the total money value of goods and services produced by a country in a year", "the total amount of money in circulation in a country", "the revenue collected by the government in a year", "the total wages paid to workers in a country", "A",
     "National income measures the flow of final output (or equivalently incomes) over a period, usually one year."),
    ("National Income", "Medium", "In the circular flow of income in a two-sector economy, households supply ______ to firms and receive ______ in return.",
     "factors of production; factor incomes", "goods and services; taxes", "taxes; subsidies", "savings; investment", "A",
     "Households own the factors and sell their services to firms for wages, rent, interest and profit, which they spend on firms' output."),
    ("National Income", "Medium", "Savings, taxes and imports are ______ from the circular flow of income, while investment, government spending and exports are ______.",
     "leakages (withdrawals); injections", "injections; leakages (withdrawals)", "transfer payments; subsidies", "final goods; intermediate goods", "A",
     "Withdrawals take spending out of the flow; injections add spending that did not come from current domestic income."),
    ("National Income", "Medium", "If the marginal propensity to consume is 0.8, the value of the simple multiplier is",
     "5", "0.8", "1.25", "8", "A",
     "Multiplier = 1/(1 − MPC) = 1/(1 − 0.8) = 1/0.2 = 5.", "1/(1-0.8)"),
    ("National Income", "Hard", "A government increases its spending on roads by ₦200 billion in an economy where the marginal propensity to save is 0.25. The eventual increase in national income is",
     "₦800 billion", "₦250 billion", "₦50 billion", "₦200 billion", "A",
     "Multiplier = 1/MPS = 1/0.25 = 4; 4 × ₦200 billion = ₦800 billion.", "200/0.25"),
    ("National Income", "Medium", "A household with an income of ₦100,000 spends ₦85,000 and saves the rest. If its income rises to ₦120,000 and spending rises to ₦100,000, its marginal propensity to consume is",
     "0.75", "0.85", "0.83", "0.25", "A",
     "MPC = ΔC/ΔY = 15,000/20,000 = 0.75.", "15000/20000"),
    ("National Income", "Medium", "The equilibrium level of national income in a simple economy is reached when",
     "planned saving equals planned investment", "consumption equals total income", "exports equal imports", "government revenue equals its expenditure", "A",
     "In the two-sector model, income is in equilibrium when withdrawals (savings) equal injections (investment)."),
    ("National Income", "Medium", "Per capita income is a poor measure of the welfare of a country's citizens mainly because it",
     "says nothing about how income is distributed", "is always measured in a foreign currency", "excludes the output of the agricultural sector", "is calculated only once every ten years", "A",
     "An average can hide extreme inequality: a few very rich people can raise per capita income while most remain poor."),
    ("National Income", "Easy", "A rise in a country's nominal national income accompanied by an equal percentage rise in prices means that real national income has",
     "remained unchanged", "risen by the same percentage", "doubled", "fallen to zero", "A",
     "Real income adjusts for price changes; if prices and money income rise equally, the volume of goods is unchanged."),
    ("National Income", "Medium", "Which of the following would increase a country's national income?",
     "an increase in the output of its farms and factories", "a rise in the prices of second-hand cars sold", "an increase in pensions paid to retired workers", "a transfer of money from one bank to another", "A",
     "Only new production of goods and services adds to national income; transfers and second-hand sales do not."),
    ("National Income", "Hard", "In an economy, the consumption function is C = 50 + 0.6Y (in ₦ billion) and investment is ₦70 billion. The equilibrium level of income is",
     "₦300 billion", "₦120 billion", "₦200 billion", "₦250 billion", "A",
     "Y = C + I = 50 + 0.6Y + 70, so 0.4Y = 120 and Y = 300.", "120/0.4"),
    ("National Income", "Medium", "The average propensity to consume of a household whose income is ₦200,000 and whose consumption is ₦150,000 is",
     "0.75", "0.25", "1.33", "0.5", "A",
     "APC = C/Y = 150,000/200,000 = 0.75.", "150000/200000"),
    # ---------------- Measurement of National Income ----------------
    ("Measurement of National Income", "Easy", "The three methods of measuring national income are the",
     "income, output and expenditure methods", "cash, credit and barter methods", "fiscal, monetary and physical methods", "primary, secondary and tertiary methods", "A",
     "In principle all three give the same total because output produced equals income earned equals expenditure made."),
    ("Measurement of National Income", "Medium", "When measuring national income by the output method, the value-added approach is used in order to",
     "avoid double counting", "include transfer payments", "exclude the services of the government", "measure only agricultural output", "A",
     "Adding the full value of intermediate and final goods would count the same output more than once; value added counts each stage's contribution only."),
    ("Measurement of National Income", "Medium", "A farmer sells cocoa beans to a processor for ₦200,000; the processor sells cocoa powder to a factory for ₦350,000; the factory sells chocolate to consumers for ₦600,000. The total value added is",
     "₦600,000", "₦1,150,000", "₦400,000", "₦550,000", "A",
     "Value added = 200,000 + 150,000 + 250,000 = ₦600,000, the value of the final good.", "600000"),
    ("Measurement of National Income", "Easy", "Pensions and unemployment benefits paid by the government are excluded from national income because they are",
     "transfer payments not made in return for current production", "paid in cash rather than in goods", "too small to affect the total", "already counted as government expenditure", "A",
     "Transfer payments redistribute existing income; no new output is produced in exchange for them."),
    ("Measurement of National Income", "Medium", "The difference between GDP and GNP is",
     "net factor income from abroad", "depreciation of capital", "indirect taxes less subsidies", "the value of exports less imports", "A",
     "GNP = GDP + income earned by residents abroad − income earned by foreigners at home."),
    ("Measurement of National Income", "Medium", "National income at factor cost is obtained from national income at market prices by",
     "subtracting indirect taxes and adding subsidies", "adding indirect taxes and subtracting subsidies", "subtracting depreciation", "adding net factor income from abroad", "A",
     "Market prices include indirect taxes (which are not factor incomes) and exclude subsidies, so both adjustments are needed."),
    ("Measurement of National Income", "Medium", "A country's GNP at market prices is ₦90 trillion, indirect taxes are ₦8 trillion, subsidies ₦2 trillion and depreciation ₦6 trillion. Its national income (NNP at factor cost) is",
     "₦78 trillion", "₦84 trillion", "₦74 trillion", "₦96 trillion", "A",
     "NNP = 90 − 6 = 84; at factor cost = 84 − 8 + 2 = ₦78 trillion.", "90-6-8+2"),
    ("Measurement of National Income", "Medium", "Which of the following is a problem in measuring national income in Nigeria?",
     "the large amount of unrecorded subsistence and informal-sector output", "the absence of any government statistical agency", "the fact that most Nigerians are paid in foreign currency", "the small size of the agricultural sector", "A",
     "Output consumed by producers themselves and informal trade go largely unrecorded, so figures understate true output."),
    ("Measurement of National Income", "Medium", "A housewife's unpaid work at home is not counted in national income because",
     "it is not exchanged for money in the market", "it does not satisfy any human want", "it is counted as government expenditure", "it is a transfer payment", "A",
     "National income counts market transactions; the same work done by a paid house-help would be counted."),
    ("Measurement of National Income", "Medium", "The GDP deflator is used to",
     "convert nominal GDP into real GDP", "measure the level of unemployment", "calculate the balance of payments", "convert GDP into GNP", "A",
     "Real GDP = nominal GDP ÷ deflator × 100; it removes the effect of price changes."),
    ("Measurement of National Income", "Medium", "Nigeria's nominal GDP rose from ₦150 trillion to ₦180 trillion in a year in which prices rose by 20%. Real GDP",
     "was unchanged", "rose by 20%", "rose by 40%", "fell by 20%", "A",
     "Real GDP in base prices = 180 ÷ 1.2 = ₦150 trillion, the same as before; the whole increase was inflation."),
    ("Measurement of National Income", "Medium", "In the income method, national income is obtained by adding",
     "wages, rent, interest and profit", "consumption, investment and government spending", "the outputs of agriculture, industry and services", "exports, imports and net factor income", "A",
     "The income method sums the rewards of the factors of production, excluding transfer payments."),
    ("Measurement of National Income", "Hard", "A firm sold goods worth ₦10 million but ₦1 million of these were made in the previous year and taken from stock. In this year's national income accounts,",
     "₦9 million is counted, as the stock reduction is subtracted", "the full ₦10 million is counted as this year's output", "only the ₦1 million taken from stock is counted", "nothing is counted because the goods were sold to consumers", "A",
     "Output is what was produced in the year; goods produced earlier were counted then, so the fall in stocks is deducted."),
    # ---------------- Money ----------------
    ("Money", "Easy", "The most important function of money is to serve as a",
     "medium of exchange", "store of value", "standard of deferred payment", "unit of account", "A",
     "Money's primary role is to overcome the difficulties of barter by being generally accepted in exchange."),
    ("Money", "Easy", "Prices of goods in a supermarket are written in naira. Money here is serving as a",
     "unit of account", "medium of exchange", "store of value", "standard of deferred payment", "A",
     "Money provides a common measure in which the values of different goods can be expressed and compared."),
    ("Money", "Medium", "A contractor agrees to be paid ₦5 million when a building is completed in two years' time. Money here serves as a",
     "standard of deferred payment", "medium of exchange", "unit of account", "measure of value", "A",
     "Money allows contracts involving future payments to be expressed and settled."),
    ("Money", "Easy", "Which of the following qualities of money makes it possible to buy small items such as a sachet of water?",
     "divisibility", "durability", "portability", "homogeneity", "A",
     "Money must be divisible into small units so that goods of low value can be bought."),
    ("Money", "Medium", "A high rate of inflation weakens money's function as a",
     "store of value", "medium of exchange", "unit of account", "means of payment", "A",
     "When prices rise fast, money loses purchasing power, so people are reluctant to hold it as a store of wealth."),
    ("Money", "Medium", "Money supply M1 in Nigeria consists of",
     "currency in circulation and demand deposits", "only the notes and coins issued by the CBN", "savings and time deposits in banks", "treasury bills and government bonds", "A",
     "M1 (narrow money) is currency outside banks plus current-account (demand) deposits."),
    ("Money", "Medium", "The value of money is measured by",
     "the quantity of goods and services it can buy", "the amount of gold backing it", "the exchange rate with the US dollar", "the number of notes in circulation", "A",
     "The value (purchasing power) of money varies inversely with the general price level."),
    ("Money", "Medium", "Which of the following is a function of a commercial bank?",
     "accepting deposits and granting loans to customers", "issuing the country's currency notes and coins", "acting as banker to the federal government", "controlling the money supply through the cash ratio", "A",
     "Commercial banks take deposits, lend, and provide payment services; the other functions belong to the central bank."),
    ("Money", "Medium", "The Central Bank of Nigeria acts as lender of last resort. This means that it",
     "lends to commercial banks that are in temporary difficulty", "gives loans to individuals who cannot get bank loans", "borrows from the public when the government is short of funds", "lends only to foreign governments", "A",
     "By lending to banks in difficulty, the central bank protects depositors and the stability of the banking system."),
    ("Money", "Medium", "The CBN raises the monetary policy rate (MPR) from 18.75% to 22.75%. The most likely effect is that",
     "commercial banks raise their lending rates and borrowing falls", "commercial banks lower their lending rates and borrowing rises", "the money supply expands rapidly", "prices of goods rise faster", "A",
     "The MPR is the rate at which the CBN lends to banks; raising it makes credit dearer and slows the growth of money supply."),
    ("Money", "Medium", "The central bank sells government securities in the open market in order to",
     "reduce the money supply", "increase the money supply", "increase commercial bank lending", "reduce the rate of interest", "A",
     "Buyers pay with bank deposits, reducing banks' reserves and their ability to lend; this is contractionary open-market operation."),
    ("Money", "Hard", "The cash (reserve) ratio is 20%. A commercial bank receives a new cash deposit of ₦500,000. The maximum total deposits the banking system can eventually create from it are",
     "₦2,500,000", "₦500,000", "₦100,000", "₦400,000", "A",
     "Credit multiplier = 1/cash ratio = 1/0.2 = 5; 5 × ₦500,000 = ₦2,500,000.", "500000/0.2"),
    ("Money", "Medium", "The central bank instructs banks to lend more to agriculture and less to importers. This instrument of monetary policy is",
     "selective credit control (directives)", "open market operations", "bank rate policy", "moral suasion", "A",
     "Directives that specify how much banks may lend and to whom are selective (qualitative) credit controls."),
    ("Money", "Medium", "A bank's liquidity ratio requires it to hold a proportion of its deposits as",
     "cash and assets that can quickly be turned into cash", "long-term loans to industry", "shares in private companies", "buildings and other fixed assets", "A",
     "Liquid assets (cash, treasury bills, call money) let the bank meet withdrawals; the ratio is also a monetary control tool."),
    ("Money", "Medium", "Which of the following does NOT create money in the economy?",
     "a customer withdrawing cash from his current account", "a commercial bank granting an overdraft to a trader", "the central bank buying treasury bills from the public", "the central bank printing new currency notes", "A",
     "Withdrawing cash only changes the form of money held; bank lending and central-bank purchases add to the money supply."),
    ("Money", "Medium", "Nigeria's introduction of new naira notes in 2022–23 and the withdrawal of old ones was mainly an exercise in",
     "currency redesign to control cash outside the banking system", "devaluation of the naira", "converting the country to a barter economy", "increasing the money supply", "A",
     "The CBN said the redesign aimed to mop up excess cash held outside banks and curb counterfeiting."),
    ("Money", "Easy", "A creditor refuses to accept a cheque but cannot lawfully refuse naira notes offered to settle the same debt. This is because naira notes are",
     "legal tender, which must by law be accepted", "made of gold or silver", "used only for international payments", "issued by the commercial banks", "A",
     "Naira notes and coins are legal tender in Nigeria; a cheque is not, since it may be refused."),
    ("Money", "Medium", "Bank deposits created by lending are called",
     "credit (or bank) money", "token money", "commodity money", "fiat currency", "A",
     "When a bank grants a loan it credits the borrower's account, creating a deposit that can be spent."),
    # ---------------- Inflation ----------------
    ("Inflation", "Easy", "Inflation is best defined as",
     "a persistent rise in the general price level", "a rise in the price of one important good", "an increase in the value of money", "a fall in the quantity of money in circulation", "A",
     "Inflation refers to a sustained increase in the average level of prices, not a one-off rise in a single price."),
    ("Inflation", "Medium", "Nigeria's consumer price index stood at 250 in January and 300 in December of the same year. The rate of inflation over the year was",
     "20%", "50%", "16.7%", "25%", "A",
     "(300 − 250)/250 × 100 = 20%.", "(300-250)/250*100"),
    ("Inflation", "Medium", "During an oil boom, the government paid large salary arrears and spending rose sharply while output could not keep pace. The resulting inflation is",
     "demand-pull inflation", "cost-push inflation", "imported inflation", "structural deflation", "A",
     "When total spending grows faster than the economy's capacity to produce, too much money chases too few goods."),
    ("Inflation", "Medium", "A fall in the value of the naira raised the prices of imported machinery, drugs and wheat, pushing up prices generally. This is",
     "imported inflation", "demand-pull inflation", "hyperinflation", "creeping inflation", "A",
     "When the domestic prices of imports rise because of foreign prices or exchange-rate changes, inflation is imported."),
    ("Inflation", "Easy", "Inflation of 2–3% per year over a long period is described as",
     "creeping inflation", "hyperinflation", "galloping inflation", "stagflation", "A",
     "Slow, steady rises in prices are creeping (mild) inflation; hyperinflation involves extremely rapid rises."),
    ("Inflation", "Medium", "Which of the following groups is most likely to lose during inflation?",
     "pensioners on fixed incomes", "borrowers who repay fixed sums", "traders holding large stocks of goods", "owners of houses and land", "A",
     "Fixed money incomes buy less as prices rise; debtors gain because they repay in money that is worth less."),
    ("Inflation", "Medium", "A situation in which rising prices are accompanied by rising unemployment and stagnant output is",
     "stagflation", "reflation", "deflation", "hyperinflation", "A",
     "Stagflation combines stagnation (low growth and high unemployment) with inflation."),
    ("Inflation", "Medium", "A fiscal measure to control inflation is",
     "increasing taxes and reducing government spending", "raising the cash reserve ratio of banks", "selling treasury bills to the public", "increasing the monetary policy rate", "A",
     "Fiscal policy uses the budget (taxes and spending); the others are monetary policy instruments."),
    ("Inflation", "Medium", "A monetary measure to control inflation is",
     "raising the monetary policy rate", "reducing government spending on roads", "increasing income tax rates", "reducing import duties", "A",
     "A higher policy rate makes borrowing dearer, reducing credit and spending."),
    ("Inflation", "Medium", "A trader borrowed ₦1 million at 15% interest in a year when inflation was 25%. The real rate of interest was approximately",
     "−10%", "10%", "40%", "15%", "A",
     "Real interest rate ≈ nominal rate − inflation rate = 15 − 25 = −10%; the lender lost purchasing power.", "-10"),
    ("Inflation", "Easy", "The instrument commonly used to measure the rate of inflation in Nigeria is the",
     "consumer price index", "exchange rate", "GDP growth rate", "monetary policy rate", "A",
     "The National Bureau of Statistics computes the CPI from the prices of a basket of goods and services."),
    ("Inflation", "Medium", "Inflation discourages saving because",
     "the purchasing power of money saved falls over time", "banks refuse to accept deposits during inflation", "the government taxes all savings during inflation", "interest rates always rise above the inflation rate", "A",
     "If prices rise faster than the interest earned, savers can buy less with their savings later than now."),
    ("Inflation", "Medium", "The value of money and the general price level are",
     "inversely related", "directly related", "unrelated", "always equal", "A",
     "When prices rise, each naira buys less, so the value of money falls."),
    ("Inflation", "Hard", "According to the quantity theory of money (MV = PT), if the money supply doubles while velocity and the volume of transactions stay constant, the price level will",
     "double", "halve", "remain unchanged", "rise by 50%", "A",
     "With V and T fixed, P is proportional to M, so doubling M doubles P."),
    ("Inflation", "Medium", "A rise in the price of a single good, such as tomatoes during the rainy season, is NOT inflation because",
     "inflation refers to a rise in the general level of prices", "tomatoes are not included in the price index", "the price of tomatoes never falls again", "inflation affects only imported goods", "A",
     "A relative price change in one good is different from a sustained rise in the average of all prices."),
    # ---------------- Deflation ----------------
    ("Deflation", "Easy", "Deflation is",
     "a persistent fall in the general price level", "a fall in the price of one good", "a slowing down of the rate of inflation", "a fall in the value of money", "A",
     "Deflation is the opposite of inflation: the average level of prices falls and the value of money rises."),
    ("Deflation", "Medium", "During deflation, the group most likely to gain is",
     "people on fixed incomes and creditors", "borrowers who owe fixed sums", "traders holding large stocks", "producers of manufactured goods", "A",
     "Falling prices raise the purchasing power of fixed money incomes and of the money repaid to lenders."),
    ("Deflation", "Medium", "A likely effect of deflation on an economy is",
     "rising unemployment as producers cut output", "rapid expansion of investment", "an increase in the profits of firms", "a fall in the value of money", "A",
     "Falling prices squeeze profits and lead firms to cut production and jobs; consumers also postpone purchases."),
    ("Deflation", "Medium", "A slowing of the rate of inflation from 30% to 20% is called",
     "disinflation", "deflation", "reflation", "stagflation", "A",
     "Disinflation is a fall in the rate of inflation; prices still rise, but more slowly. Deflation is an actual fall in prices."),
    ("Deflation", "Medium", "A policy of increasing government spending and cutting interest rates to lift an economy out of deflation and depression is",
     "reflation", "disinflation", "devaluation", "deregulation", "A",
     "Reflation deliberately expands demand to raise output, employment and prices after a slump."),
    ("Deflation", "Medium", "A government wishing to correct deflation would most likely",
     "reduce taxes and increase its spending", "raise the cash reserve ratio of banks", "sell more treasury bills to the public", "increase income tax rates", "A",
     "Expansionary fiscal policy injects spending into the economy to raise demand and prices."),
    ("Deflation", "Medium", "Consumers often delay purchases during deflation because",
     "they expect prices to be lower in the future", "goods become unavailable in the shops", "the government bans the purchase of luxuries", "their money incomes rise faster than prices", "A",
     "Expected falling prices make waiting rational, which further reduces demand and deepens the slump."),
    ("Deflation", "Hard", "Deflation increases the real burden of debt because",
     "the money repaid is worth more than the money borrowed", "interest rates always rise during deflation", "banks demand immediate repayment of all loans", "the nominal value of the debt is increased by law", "A",
     "With falling prices, the fixed sum a debtor repays commands more goods than the sum originally borrowed."),
    ("Deflation", "Medium", "Which of the following situations best describes deflation?",
     "the consumer price index falls from 120 to 115 over a year", "the inflation rate falls from 15% to 12%", "the price of petrol falls while all other prices rise", "the exchange rate of the naira falls against the dollar", "A",
     "A falling price index means the general price level is falling, which is deflation."),
    ("Deflation", "Medium", "During the Great Depression of the 1930s, falling prices, falling output and mass unemployment occurred together. This situation is best described as",
     "deflation accompanied by depression", "demand-pull inflation", "stagflation", "hyperinflation", "A",
     "Prices and output fell together in the 1930s, the classic combination of deflation and depression."),
    # ---------------- Unemployment ----------------
    ("Unemployment", "Medium", "A shoemaker in Aba lost his job when cheap imported shoes flooded the market and the demand for locally made shoes collapsed. He is experiencing",
     "structural unemployment", "frictional unemployment", "seasonal unemployment", "voluntary unemployment", "A",
     "Structural unemployment arises from a lasting change in the pattern of demand or technology in an industry."),
    ("Unemployment", "Medium", "Workers laid off during a general slump in economic activity are experiencing",
     "cyclical unemployment", "frictional unemployment", "seasonal unemployment", "residual unemployment", "A",
     "Cyclical (demand-deficient) unemployment rises when total demand falls in a recession."),
    ("Unemployment", "Easy", "Rice farm labourers in Kebbi who have no work between the harvest and the next planting season are",
     "seasonally unemployed", "structurally unemployed", "frictionally unemployed", "cyclically unemployed", "A",
     "Seasonal unemployment follows the calendar of activities in farming, construction and tourism."),
    ("Unemployment", "Medium", "A bank replaced its cashiers with ATMs and dismissed many of them. The cashiers are victims of",
     "technological unemployment", "seasonal unemployment", "frictional unemployment", "voluntary unemployment", "A",
     "Technological unemployment results when machines take over jobs previously done by labour."),
    ("Unemployment", "Medium", "Ten men are employed on a family farm that could be worked just as well by six. The four extra workers illustrate",
     "disguised (hidden) unemployment", "frictional unemployment", "cyclical unemployment", "structural unemployment", "A",
     "When workers add nothing to output (their marginal product is zero), they are disguisedly unemployed."),
    ("Unemployment", "Medium", "A graduate engineer who works as a commercial motorcycle rider because he cannot find an engineering job is",
     "underemployed", "frictionally unemployed", "voluntarily unemployed", "fully employed", "A",
     "Underemployment occurs when a worker's skills or hours are not fully used."),
    ("Unemployment", "Medium", "A labour force of 80 million contains 68 million employed people. The unemployment rate is",
     "15%", "12%", "85%", "17.6%", "A",
     "Unemployed = 80 − 68 = 12 million; 12/80 × 100 = 15%.", "12/80*100"),
    ("Unemployment", "Medium", "Which of the following is a likely cause of the high rate of graduate unemployment in Nigeria?",
     "a mismatch between the skills taught and the skills employers need", "a shortage of people willing to attend university", "the very small number of universities in the country", "the high wages paid to all fresh graduates", "A",
     "Many graduates lack the practical skills demanded by industry, while the economy creates too few formal jobs."),
    ("Unemployment", "Medium", "A policy most likely to reduce structural unemployment is",
     "retraining workers in the skills demanded by growing industries", "increasing the money supply to raise total demand", "paying higher unemployment benefits", "reducing the school-leaving age", "A",
     "Structural unemployment reflects a mismatch of skills, which retraining corrects; more demand alone does not."),
    ("Unemployment", "Medium", "The labour force of a country consists of",
     "all persons of working age who are working or actively seeking work", "the whole population of the country", "all persons employed in the civil service", "children, students and retired persons", "A",
     "Full-time students, the retired and those not seeking work are outside the labour force."),
    ("Unemployment", "Medium", "Rural-urban migration in Nigeria contributes to urban unemployment because",
     "migrants arrive faster than the towns can create jobs", "rural areas have more jobs than the towns", "migrants refuse to accept any paid employment", "urban wages fall below rural wages", "A",
     "Young people move to cities in search of better-paid work, but formal urban jobs grow more slowly than the number of arrivals."),
    ("Unemployment", "Hard", "The natural rate of unemployment consists of",
     "frictional and structural unemployment", "cyclical and seasonal unemployment", "voluntary unemployment only", "disguised unemployment only", "A",
     "Even at full employment some workers are between jobs or lack current skills; this is the natural rate."),
    ("Unemployment", "Medium", "An economic consequence of high unemployment is",
     "a loss of output that could have been produced", "a rise in the level of national income", "an increase in government tax revenue", "a fall in the crime rate", "A",
     "Idle labour means the economy produces below its potential; tax revenue falls and social problems rise."),
    ("Unemployment", "Medium", "The Nigerian government's N-Power and similar schemes were mainly intended to",
     "provide skills and temporary jobs for unemployed youths", "reduce the number of universities in the country", "raise the retirement age of civil servants", "restrict rural-urban migration by law", "A",
     "Such programmes engage unemployed graduates and youths in public service and training to improve employability."),
    # ---------------- Population ----------------
    ("Population", "Easy", "The census is important to a government mainly because it",
     "provides data for planning services such as schools and hospitals", "increases the population of the country", "determines the prices of goods in the market", "replaces the need to collect taxes", "A",
     "Accurate population data are needed to plan, allocate resources and delimit constituencies."),
    ("Population", "Medium", "A country's population is 220 million and its labour force is 88 million. The dependency ratio is",
     "1.5 dependants per worker", "0.4 dependants per worker", "2.5 dependants per worker", "0.67 dependants per worker", "A",
     "Dependants = 220 − 88 = 132 million; 132 ÷ 88 = 1.5.", "132/88"),
    ("Population", "Medium", "A high dependency ratio in a country implies that",
     "each worker supports many non-working people", "the country has an ageing population only", "the birth rate is lower than the death rate", "most of the population is in paid employment", "A",
     "A large share of children and old people relative to workers places a heavy burden on the working population."),
    ("Population", "Easy", "Optimum population is the population size that",
     "gives the highest output per head with the available resources", "is the largest a country can feed", "the government decides is ideal", "has the lowest death rate", "A",
     "Below the optimum, more people would raise per capita output; above it, per capita output falls."),
    ("Population", "Medium", "A country is said to be over-populated when",
     "an increase in population reduces output per head", "its population is larger than that of its neighbours", "its population exceeds 100 million", "most of its people live in cities", "A",
     "Over-population is relative to resources, not absolute numbers: extra people lower average output."),
    ("Population", "Medium", "Which of the following would lead to a fall in a country's birth rate?",
     "wider education of women and later marriage", "an improvement in child health services", "early marriage of girls", "a rise in the number of polygamous families", "A",
     "Educated women tend to marry later and have fewer children."),
    ("Population", "Medium", "The main reason for the rapid growth of Nigeria's population since independence has been",
     "a high birth rate combined with a falling death rate", "large-scale immigration from Europe", "a rise in both birth and death rates", "the return of Nigerians from abroad", "A",
     "Improved health care cut death rates while birth rates stayed high, so natural increase was rapid."),
    ("Population", "Medium", "Nigeria's population is described as youthful because",
     "a large proportion of the people are below 15 years of age", "most of the people are between 40 and 60 years", "the death rate is higher than the birth rate", "there are more old people than young people", "A",
     "A high birth rate produces a population in which children make up a large share."),
    ("Population", "Medium", "Net migration is",
     "the difference between immigration and emigration", "the total number of people who leave a country", "the movement of people from villages to towns", "the number of foreigners living in a country", "A",
     "Population change = births − deaths + immigrants − emigrants; net migration is the last two combined."),
    ("Population", "Medium", "Which of the following is an economic effect of a rapidly growing population in a developing country?",
     "pressure on schools, hospitals and housing", "a fall in the size of the labour force", "a fall in the demand for food", "a reduction in unemployment", "A",
     "Fast growth means more people to feed, educate and house, straining limited resources."),
    ("Population", "Medium", "The population of a town rose from 500,000 to 600,000 in five years. Its average annual (simple) growth rate was",
     "4%", "20%", "5%", "2%", "A",
     "Total growth = 100,000/500,000 = 20% over five years, or 4% per year on a simple basis.", "20/5"),
    ("Population", "Medium", "Which region of Nigeria has the highest population density?",
     "the south-east and Lagos area", "the Sahel zone of the far north", "the middle belt", "the mangrove swamps of the Niger Delta", "A",
     "Lagos, Anambra and Imo are among the most densely populated parts of the country."),
    ("Population", "Medium", "Malthus predicted that population growth would outstrip food supply. His prediction has not come true in most countries mainly because of",
     "improvements in agricultural technology and birth control", "the rise in the death rate from wars", "the ban on migration between countries", "the fall in the world's total population", "A",
     "Modern farming methods raised food output far faster than Malthus expected, and family sizes fell with development."),
    ("Population", "Medium", "The working population of a country is",
     "the people of working age who are willing and able to work", "everybody aged between 0 and 64 years", "all the people who are currently employed", "the total population minus children", "A",
     "The working population (labour force) includes both the employed and the unemployed who are seeking work."),
    # ---------------- Agriculture ----------------
    ("Agriculture", "Medium", "A major reason why many Nigerian farmers still produce small quantities is",
     "the land tenure system, which fragments farmland into small plots", "the ban on the use of fertilisers in Nigeria", "the very high wages paid to farm workers", "the absence of any demand for food crops", "A",
     "Communal and inheritance-based tenure splits land into small scattered plots that discourage mechanisation."),
    ("Agriculture", "Easy", "Agriculture contributes to Nigeria's industrial development mainly by",
     "supplying raw materials such as cotton, cocoa and palm oil to factories", "providing electricity for factories", "producing machinery for industries", "fixing the prices of manufactured goods", "A",
     "Agro-based industries (textiles, beverages, soap) depend on farm produce as inputs."),
    ("Agriculture", "Medium", "The main purpose of the commodity marketing boards in Nigeria before 1986 was to",
     "buy export crops from farmers at fixed prices and sell them abroad", "import food to sell cheaply to consumers", "lend money to farmers at low interest rates", "train farmers in modern farming methods", "A",
     "Boards were monopoly buyers of cocoa, groundnuts, cotton and palm produce; the surplus they kept became a source of government revenue."),
    ("Agriculture", "Medium", "Before the oil boom of the 1970s, Nigeria's main source of foreign exchange was",
     "the export of agricultural produce such as cocoa, groundnuts and palm oil", "the export of refined petroleum products", "revenue from tourism", "the export of manufactured goods", "A",
     "Groundnut pyramids in Kano, cocoa in the west and palm produce in the east dominated exports until crude oil took over."),
    ("Agriculture", "Medium", "A major problem of agricultural marketing in Nigeria is",
     "poor roads and storage, which cause large post-harvest losses", "the excessive use of machines by farmers", "the ban on selling farm produce in urban markets", "the small number of consumers who eat farm produce", "A",
     "Much perishable produce spoils before reaching the market because of bad roads and lack of storage."),
    ("Agriculture", "Medium", "Plantation agriculture differs from peasant farming in that plantations",
     "grow a single cash crop on a large scale with hired labour", "produce only food for the farmer's family", "use small plots and simple tools", "are found only in the northern savannah", "A",
     "Plantations (rubber, oil palm, cocoa estates) are large, specialised and commercially organised."),
    ("Agriculture", "Medium", "Guaranteed minimum prices for farm produce are intended to",
     "protect farmers' incomes from sharp price falls", "reduce the quantity of food produced", "raise the cost of food to consumers permanently", "discourage farmers from growing cash crops", "A",
     "A price floor assures farmers of a minimum return, encouraging them to keep producing."),
    ("Agriculture", "Medium", "Which of the following is a disadvantage of the shifting cultivation practised by peasant farmers?",
     "it wastes land and cannot support a large population", "it requires expensive machinery", "it exhausts the soil permanently in one season", "it produces only export crops", "A",
     "Leaving land fallow for years means large areas are needed to feed few people; it becomes impossible as population grows."),
    ("Agriculture", "Medium", "The Anchor Borrowers' Programme of the Central Bank of Nigeria was designed to",
     "provide credit and inputs to smallholder farmers linked to processors", "buy all rice produced in Nigeria at a fixed price", "import fertiliser for sale to large plantations only", "replace the ministry of agriculture", "A",
     "Farmers received loans in the form of inputs and sold their output to anchor firms who helped recover the loans."),
    ("Agriculture", "Medium", "Farm mechanisation is difficult in much of southern Nigeria because",
     "farm plots are small and scattered and the terrain is often forested", "farmers are not allowed to buy tractors", "the soil is too fertile for machines", "there is no demand for farm produce", "A",
     "Tractors need large, cleared, consolidated fields to be economical."),
    ("Agriculture", "Medium", "Agricultural prices fluctuate more than the prices of manufactured goods mainly because",
     "farm output depends on weather and supply cannot respond quickly to price", "farmers change their prices every day for no reason", "manufactured goods are never affected by demand changes", "the government fixes the prices of all farm produce", "A",
     "Supply shocks from weather and pests, combined with inelastic demand and supply, produce large price swings."),
    ("Agriculture", "Medium", "Agriculture in Nigeria is still the largest employer of labour, yet its share of GDP is much smaller than its share of employment. This shows that",
     "productivity per worker in agriculture is low", "farmers earn more than factory workers", "agriculture uses more capital than industry", "most farm output is exported", "A",
     "When a sector employs many workers but produces relatively little output, output per worker is low."),
    ("Agriculture", "Medium", "Agricultural extension services are provided to",
     "teach farmers improved methods and spread new technology", "buy farmers' produce at harvest time", "collect taxes from rural farmers", "build roads in farming areas", "A",
     "Extension workers link research institutes to farmers by demonstrating better seeds, fertiliser use and practices."),
    # ---------------- Industrialization ----------------
    ("Industrialization", "Medium", "A strategy of encouraging local factories to make goods that were previously imported is",
     "import substitution industrialisation", "export promotion", "nationalisation", "economic integration", "A",
     "Import substitution protects and promotes home industries to replace imports such as textiles and beverages."),
    ("Industrialization", "Medium", "Which of the following is a common problem of industrialisation in Nigeria?",
     "inadequate and unreliable electricity supply", "an excess of skilled manpower", "very low cost of borrowing", "the absence of any raw materials", "A",
     "Firms spend heavily on generators and diesel because grid power is unreliable, raising costs."),
    ("Industrialization", "Medium", "Many Nigerian factories depend on imported raw materials and machines. A large fall in the value of the naira will therefore",
     "raise their costs of production", "reduce their costs of production", "have no effect on their costs", "increase the supply of local raw materials at once", "A",
     "Imported inputs cost more naira when the currency depreciates."),
    ("Industrialization", "Medium", "Industries such as cement and quarrying are usually located near their raw materials because",
     "the raw materials are bulky and lose weight in processing", "the finished products are more expensive to store", "workers prefer to live in rural areas", "the government forbids them to locate in cities", "A",
     "Transporting heavy limestone is costlier than moving the lighter finished cement, so factories sit near quarries."),
    ("Industrialization", "Medium", "Breweries and soft-drink bottling plants tend to locate near large cities because",
     "their products are bulky and their main market is the city", "cities have the cheapest land", "their raw materials are found only in cities", "they need cool weather to operate", "A",
     "Market-oriented industries locate near consumers to reduce the cost of distributing bulky or perishable products."),
    ("Industrialization", "Medium", "A cottage industry is one in which",
     "production is carried out in the home with simple tools", "large machines are used in a big factory", "the state owns all the equipment", "goods are produced mainly for export", "A",
     "Weaving, pottery and local soap-making done at home are examples."),
    ("Industrialization", "Medium", "Small-scale industries are important in Nigeria mainly because they",
     "create many jobs with relatively little capital", "produce all the country's exports", "require no raw materials", "never face competition from imports", "A",
     "Labour-intensive small firms spread employment and use local materials and skills."),
    ("Industrialization", "Medium", "The Ajaokuta Steel Company was intended to",
     "provide the basic industry for producing iron and steel for other industries", "refine crude oil into petrol and diesel", "assemble vehicles for export", "process cocoa into chocolate", "A",
     "Iron and steel is a basic (heavy) industry whose output feeds engineering and construction industries."),
    ("Industrialization", "Medium", "Industrial estates and free trade zones such as the Lekki Free Zone are set up to",
     "attract manufacturers with infrastructure and tax incentives in one location", "prevent foreign firms from operating in Nigeria", "relocate all factories to rural areas", "increase the tariffs on imported goods", "A",
     "Concentrating services and incentives in one place lowers the cost of setting up and running factories."),
    ("Industrialization", "Medium", "Industrialisation can help a country's balance of payments by",
     "reducing imports and increasing exports of manufactured goods", "increasing the import of consumer goods", "reducing the output of the agricultural sector", "raising the price of foreign currency", "A",
     "Home production replaces imports and may generate exports, both of which improve the current account."),
    ("Industrialization", "Medium", "Industries producing goods for immediate use by consumers, such as bread and soap, are",
     "light (consumer goods) industries", "heavy (capital goods) industries", "extractive industries", "construction industries", "A",
     "Light industries make consumer goods; heavy industries make machinery, steel and other capital goods."),
    ("Industrialization", "Medium", "The localisation of industries in Lagos has produced external economies such as",
     "a pool of skilled labour and specialised suppliers", "cheaper land than in rural areas", "the absence of traffic congestion", "lower wages than elsewhere in the country", "A",
     "Concentration of firms creates shared services, trained labour and supporting industries that benefit every firm."),
    # ---------------- Trade ----------------
    ("Trade", "Easy", "A wholesaler differs from a retailer in that the wholesaler",
     "buys in bulk from producers and sells in smaller lots to retailers", "sells directly to the final consumer", "produces the goods that he sells", "operates only in rural markets", "A",
     "The wholesaler is the link between producers and retailers, breaking bulk and holding stock."),
    ("Trade", "Medium", "A trader buys goods from a Nigerian factory and sells them to consumers in Kano. This is",
     "home (domestic) trade", "foreign trade", "entrepôt trade", "bilateral trade", "A",
     "Trade within the borders of one country is home trade."),
    ("Trade", "Medium", "A Lagos company imports electronics from China and re-exports them to Benin Republic. This is",
     "entrepôt trade", "home trade", "barter trade", "bilateral aid", "A",
     "Entrepôt trade is the re-export of imported goods, often with little or no processing."),
    ("Trade", "Medium", "The naira was exchanged at ₦1,500 to $1 in January and ₦1,650 to $1 in June. The naira",
     "depreciated against the dollar", "appreciated against the dollar", "was revalued by the CBN", "remained stable against the dollar", "A",
     "More naira are needed to buy one dollar, so the naira lost value."),
    ("Trade", "Medium", "An exporter sells goods worth $50,000 when the exchange rate is ₦1,600 to $1. The naira value of the goods is",
     "₦80,000,000", "₦8,000,000", "₦31,250", "₦800,000,000", "A",
     "50,000 × 1,600 = ₦80,000,000.", "50000*1600"),
    ("Trade", "Medium", "A depreciation of the naira is expected to",
     "make Nigerian exports cheaper abroad and imports dearer at home", "make Nigerian exports dearer abroad and imports cheaper at home", "reduce the naira prices of imported goods", "have no effect on the prices of imports", "A",
     "A weaker naira means foreigners pay less of their currency for Nigerian goods, while Nigerians pay more naira for imports."),
    ("Trade", "Medium", "Nigeria's official adoption of a market-determined exchange rate in 2023 meant that the naira's value would be set mainly by",
     "the demand for and supply of foreign exchange", "the President by decree", "the World Bank", "the prices fixed by the bureau de change association", "A",
     "Under a floating (market) system, the exchange rate is determined by market forces rather than fixed by the central bank."),
    ("Trade", "Medium", "The main advantage of a fixed exchange rate system is that it",
     "gives certainty to traders and investors", "allows the currency to adjust automatically to shocks", "requires no foreign reserves", "guarantees a balance of payments surplus", "A",
     "Stable rates reduce exchange-rate risk in international contracts, though large reserves are needed to defend them."),
    ("Trade", "Easy", "Documents used in foreign trade include a bill of lading, which is",
     "a receipt for goods shipped and evidence of the contract of carriage", "a demand for payment sent by the exporter", "a licence to import goods", "a certificate showing where goods were made", "A",
     "The bill of lading is issued by the shipping company and gives title to the goods."),
    ("Trade", "Medium", "A trader's goods are held at the port until she pays import duty. The duty is collected by the",
     "Nigeria Customs Service", "Central Bank of Nigeria", "Federal Inland Revenue Service", "Nigerian Ports Authority", "A",
     "Customs administers duties on goods entering and leaving the country."),
    ("Trade", "Medium", "Middlemen in the distribution chain are often accused of",
     "raising prices to consumers by taking large margins", "producing goods of poor quality", "refusing to buy from farmers", "paying too much tax to the government", "A",
     "Each link in a long chain adds a margin, so consumers may pay far more than farmers receive."),
    ("Trade", "Medium", "The ECOWAS Trade Liberalisation Scheme aims to",
     "remove tariffs on goods originating within member states", "impose higher tariffs on goods from West Africa", "stop the movement of workers between member states", "replace the naira with a foreign currency", "A",
     "Free movement of qualifying goods within the community is meant to expand intra-regional trade."),
    # ---------------- International Trade ----------------
    ("International Trade", "Medium", "Country A can produce both rice and cloth more cheaply than Country B, but its advantage is greatest in rice. According to the principle of comparative advantage, Country A should",
     "specialise in rice and import cloth from Country B", "produce both goods and trade nothing", "specialise in cloth and import rice", "stop trading with Country B", "A",
     "Each country gains by specialising in the good in which its comparative (relative) advantage is greatest, even if one has an absolute advantage in both."),
    ("International Trade", "Medium", "A country has an absolute advantage in producing a good when it can",
     "produce more of the good with the same resources than another country", "produce the good at a lower opportunity cost only", "sell the good at a higher price than other countries", "import the good more cheaply than it can make it", "A",
     "Absolute advantage refers to greater productivity; comparative advantage refers to lower opportunity cost."),
    ("International Trade", "Medium", "Nigeria's export price index rose from 100 to 130 while its import price index rose from 100 to 104. Its terms of trade are",
     "125, an improvement", "80, a deterioration", "104, unchanged", "26, a deterioration", "A",
     "Terms of trade = export price index ÷ import price index × 100 = 130/104 × 100 = 125; a rise means each unit of exports buys more imports.", "130/104*100"),
    ("International Trade", "Easy", "A tax imposed on imported goods is",
     "a tariff (customs duty)", "an excise duty", "a quota", "a subsidy", "A",
     "Tariffs raise the price of imports to protect home producers and raise revenue."),
    ("International Trade", "Easy", "A government limits the quantity of rice that may be imported each year. This restriction is",
     "a quota", "a tariff", "an embargo", "a subsidy", "A",
     "A quota is a quantitative restriction on imports; an embargo bans them completely."),
    ("International Trade", "Medium", "Nigeria banned the importation of certain items and closed its land borders in 2019 mainly to",
     "protect local producers and curb smuggling", "increase the volume of imports", "encourage the dumping of foreign goods", "reduce the prices of imported food", "A",
     "The measures were intended to boost local rice and poultry production and stop smuggled goods."),
    ("International Trade", "Medium", "Dumping in international trade means",
     "selling goods abroad at a price below their cost or home price", "throwing away goods that cannot be sold", "importing goods without paying customs duty", "exporting goods that have expired", "A",
     "Exporters may dump goods to capture foreign markets, harming the importing country's producers."),
    ("International Trade", "Medium", "Which of the following is an argument AGAINST protectionism?",
     "consumers pay higher prices and have less choice", "it protects infant industries until they mature", "it prevents the dumping of cheap foreign goods", "it protects strategic industries such as defence", "A",
     "Tariffs and quotas raise prices, reduce choice and invite retaliation; the others are arguments for protection."),
    ("International Trade", "Medium", "A Kano trader who sells grain in Lagos faces fewer difficulties than one who sells grain in Niger Republic mainly because trade across the border",
     "involves different currencies, languages, laws and trade barriers", "is always carried out by governments", "does not involve the transport of goods", "is never affected by prices", "A",
     "Exchange rates, customs regulations and immobility of factors between countries distinguish it from home trade."),
    ("International Trade", "Medium", "A country whose exports consist mainly of crude oil is vulnerable because",
     "a fall in the world oil price sharply reduces its export earnings", "oil is never demanded by other countries", "it cannot import any goods", "its currency will always appreciate", "A",
     "Over-dependence on one export makes government revenue and foreign exchange earnings unstable."),
    ("International Trade", "Medium", "Free trade areas, customs unions and common markets are all forms of",
     "economic integration", "protectionism", "central planning", "import substitution", "A",
     "They remove barriers between member states to varying degrees."),
    ("International Trade", "Medium", "The African Continental Free Trade Area (AfCFTA) is intended to",
     "create a single market for goods and services across Africa", "replace all African currencies with one currency", "restrict trade between African and non-African countries", "abolish the customs services of African countries", "A",
     "AfCFTA aims to remove tariffs and barriers on most goods traded among African countries."),
    ("International Trade", "Medium", "The gains from international trade include",
     "a wider variety of goods and lower prices for consumers", "the elimination of all unemployment", "the removal of the need for a national currency", "the end of competition between firms", "A",
     "Specialisation and exchange raise world output and give consumers access to goods not produced at home."),
    ("International Trade", "Hard", "Country P gives up 2 tonnes of yam for each tonne of rice it produces, while Country Q gives up 5 tonnes of yam per tonne of rice. Country Q has a comparative advantage in",
     "yam", "rice", "both goods", "neither good", "A",
     "Q's opportunity cost of rice (5 yam) is higher than P's (2 yam), so Q has the lower opportunity cost in yam and should specialise in it."),
    # ---------------- Balance of Payments ----------------
    ("Balance of Payments", "Easy", "The balance of payments is",
     "a record of all economic transactions between a country and the rest of the world in a year", "the difference between the value of visible exports and visible imports", "the amount of money a country owes to foreign banks", "the government's annual budget statement", "A",
     "It includes trade in goods and services, income flows, transfers and capital movements."),
    ("Balance of Payments", "Medium", "Which of the following is recorded as an invisible export for Nigeria?",
     "money spent by foreign tourists visiting Nigeria", "crude oil sold to India", "cocoa beans shipped to the Netherlands", "cars imported from Japan", "A",
     "Services sold to foreigners (tourism, shipping, insurance, banking) are invisible exports."),
    ("Balance of Payments", "Medium", "In a year, a country's visible exports were $40 billion, visible imports $55 billion, invisible exports $20 billion and invisible imports $12 billion. Its current account balance was",
     "a deficit of $7 billion", "a surplus of $7 billion", "a deficit of $15 billion", "a surplus of $8 billion", "A",
     "Trade balance = 40 − 55 = −15; invisible balance = 20 − 12 = +8; current account = −15 + 8 = −$7 billion.", "7"),
    ("Balance of Payments", "Medium", "A country whose visible exports exceed its visible imports has",
     "a favourable balance of trade", "an unfavourable balance of trade", "a balance of payments deficit", "a capital account deficit", "A",
     "The balance of trade compares merchandise (visible) exports and imports only."),
    ("Balance of Payments", "Medium", "Remittances sent home by Nigerians working abroad are recorded in the balance of payments as",
     "current transfers (a credit)", "visible exports", "capital outflows", "invisible imports", "A",
     "Diaspora remittances are unrequited transfers that bring foreign exchange into the country."),
    ("Balance of Payments", "Medium", "A foreign company builds a new factory in Ogun State. This transaction appears in Nigeria's balance of payments as",
     "an inflow in the capital and financial account", "an invisible import in the current account", "a visible export", "a current transfer out of the country", "A",
     "Foreign direct investment is recorded as a capital (financial) account inflow."),
    ("Balance of Payments", "Medium", "Which of the following measures would help to correct a persistent balance of payments deficit?",
     "devaluing the currency to make exports cheaper and imports dearer", "removing all restrictions on imports", "raising the exchange rate of the currency", "increasing government spending on imported goods", "A",
     "Devaluation, import restrictions and export promotion all work to reduce a deficit."),
    ("Balance of Payments", "Medium", "A country finances a balance of payments deficit by",
     "drawing on its foreign reserves or borrowing from abroad", "printing more of its own currency", "raising the wages of its workers", "reducing its exports", "A",
     "A deficit means foreign-currency payments exceed receipts; the gap is covered from reserves or by loans."),
    ("Balance of Payments", "Medium", "Nigeria's external reserves are held mainly to",
     "settle international payments and support the value of the naira", "pay the salaries of civil servants", "finance the building of local roads", "lend to commercial banks in naira", "A",
     "Reserves in foreign currency allow the country to meet import bills and intervene in the foreign exchange market."),
    ("Balance of Payments", "Medium", "Devaluation improves the balance of payments only if",
     "the demand for exports and imports is sufficiently elastic", "the country imports nothing", "the demand for imports is perfectly inelastic", "foreign prices rise at the same time", "A",
     "If demand is inelastic, cheaper exports earn less and dearer imports are still bought, so the balance may worsen."),
    ("Balance of Payments", "Medium", "A large fall in the world price of crude oil affects Nigeria's balance of payments mainly by",
     "reducing export earnings and the current account balance", "increasing the volume of manufactured exports", "reducing the demand for foreign exchange", "increasing the country's foreign reserves", "A",
     "Oil makes up the bulk of Nigeria's export receipts, so a price fall widens the current account deficit."),
    ("Balance of Payments", "Medium", "In balance of payments accounting, the payment of interest on Nigeria's foreign debt is recorded as",
     "an invisible import (debit) in the current account", "a visible import", "a capital inflow", "an invisible export (credit)", "A",
     "Interest paid to foreign lenders is an outflow of factor income, part of the invisible (services and income) account."),
    ("Balance of Payments", "Hard", "The capital account of the balance of payments records",
     "flows of loans and investments between a country and the rest of the world", "exports and imports of goods only", "payments for shipping and insurance", "gifts and remittances", "A",
     "Foreign direct investment, portfolio investment and external borrowing appear in the capital and financial account."),
    # ---------------- Public Finance ----------------
    ("Public Finance", "Easy", "Public finance is concerned with",
     "the revenue and expenditure of the government", "the profits of public limited companies", "the savings of private households", "the lending activities of commercial banks", "A",
     "It studies how governments raise money (taxes, borrowing) and spend it."),
    ("Public Finance", "Medium", "A budget in which planned revenue exceeds planned expenditure is",
     "a surplus budget", "a deficit budget", "a balanced budget", "a supplementary budget", "A",
     "A surplus budget withdraws more from the economy than it injects and can be used to fight inflation."),
    ("Public Finance", "Medium", "A government facing a recession is most likely to adopt",
     "a deficit budget to stimulate demand", "a surplus budget to reduce spending", "a balanced budget", "higher taxes on consumers", "A",
     "Spending more than it collects injects demand into a depressed economy."),
    ("Public Finance", "Medium", "The main source of revenue for Nigeria's federal government in recent decades has been",
     "receipts from crude oil and gas", "company income tax", "personal income tax", "revenue from tourism", "A",
     "Oil receipts have provided the largest share of federally collected revenue, though non-oil revenue has grown."),
    ("Public Finance", "Medium", "Government spending on roads, power stations and schools is classified as",
     "capital expenditure", "recurrent expenditure", "transfer payments", "debt servicing", "A",
     "Capital expenditure creates long-lasting assets; recurrent expenditure covers salaries and running costs."),
    ("Public Finance", "Easy", "Salaries of civil servants and the running costs of ministries are",
     "recurrent expenditure", "capital expenditure", "development expenditure", "transfer payments", "A",
     "Recurrent expenditure is repeated every year to keep government services running."),
    ("Public Finance", "Medium", "The national debt is",
     "the total amount owed by the government to its creditors at home and abroad", "the money the government spent in the current year", "the total value of goods imported in a year", "the money owed by all citizens to banks", "A",
     "It accumulates from past budget deficits financed by borrowing."),
    ("Public Finance", "Medium", "Debt servicing refers to",
     "the payment of interest and repayment of principal on loans", "the borrowing of new loans by the government", "the cancellation of a country's debts", "the collection of taxes to finance the budget", "A",
     "A large share of Nigeria's revenue has gone to servicing its domestic and external debt."),
    ("Public Finance", "Medium", "Nigeria's Federation Account is",
     "the pool into which federally collected revenue is paid before being shared among the tiers of government", "the personal account of the President", "an account kept by each state for its own taxes", "a loan account with the World Bank", "A",
     "Revenue in the Federation Account is distributed to the federal, state and local governments by an agreed formula."),
    ("Public Finance", "Medium", "Which of the following is a reason why the government borrows?",
     "to finance capital projects when tax revenue is insufficient", "to reduce the total supply of money in circulation", "to lower the level of national income", "to discourage private firms from investing", "A",
     "Loans supplement revenue for projects such as railways and power plants whose benefits last many years."),
    ("Public Finance", "Medium", "Fiscal policy refers to the use of",
     "taxation and government expenditure to influence the economy", "interest rates and the money supply to influence the economy", "tariffs alone to protect industries", "exchange controls to manage the currency", "A",
     "Fiscal policy is the budget side; monetary policy is the central bank's domain."),
    ("Public Finance", "Medium", "The removal of the petrol subsidy in Nigeria in 2023 was expected mainly to",
     "reduce government expenditure and free funds for other uses", "lower the pump price of petrol", "increase the government's spending on subsidies", "reduce the revenue of state governments", "A",
     "Subsidy payments had consumed a large share of revenue; removal was meant to save funds, though it raised petrol prices."),
    ("Public Finance", "Medium", "A supplementary budget is",
     "additional spending approved after the main budget proves insufficient", "the budget of a state government", "a budget in which revenue equals expenditure", "a budget prepared by the central bank", "A",
     "Supplementary appropriations cover unforeseen expenditure during the financial year."),
    ("Public Finance", "Hard", "A government's revenue is ₦12 trillion and its expenditure is ₦16 trillion, of which ₦5 trillion is debt service. Its fiscal deficit is",
     "₦4 trillion", "₦9 trillion", "₦1 trillion", "₦5 trillion", "A",
     "Fiscal deficit = expenditure − revenue = 16 − 12 = ₦4 trillion.", "16-12"),
    # ---------------- Taxation ----------------
    ("Taxation", "Easy", "A tax whose burden cannot be shifted to another person is",
     "a direct tax", "an indirect tax", "a regressive tax", "an excise duty", "A",
     "Personal income tax and company tax are borne by the person or firm on whom they are levied."),
    ("Taxation", "Easy", "Value added tax (VAT) is classified as",
     "an indirect tax", "a direct tax", "a progressive tax", "a capital tax", "A",
     "VAT is levied on goods and services and its burden is passed on to the final consumer in the price."),
    ("Taxation", "Medium", "Nigeria's VAT rate of 7.5% is charged on most goods. If a consumer pays ₦21,500 for a product including VAT, the price before VAT was",
     "₦20,000", "₦19,887.50", "₦21,000", "₦23,112.50", "A",
     "Price × 1.075 = 21,500, so price = 21,500 ÷ 1.075 = ₦20,000.", "21500/1.075"),
    ("Taxation", "Medium", "Under a progressive tax system, a person earning ₦1 million pays ₦50,000 in tax. A person earning ₦5 million would pay",
     "more than ₦250,000", "exactly ₦250,000", "less than ₦250,000", "exactly ₦50,000", "A",
     "Progressive taxation takes a larger percentage as income rises; 5% of ₦5 million is ₦250,000, so a higher rate means more than that."),
    ("Taxation", "Medium", "A flat tax of ₦500 per person, levied on rich and poor alike, is",
     "regressive, because it takes a larger share of a poor person's income", "progressive, because the rich pay the same amount", "proportional, because everyone pays the same amount", "a direct tax that cannot be regressive", "A",
     "The same sum is a bigger percentage of a small income than of a large one."),
    ("Taxation", "Medium", "A tax that takes the same percentage of income from everybody is",
     "proportional", "progressive", "regressive", "indirect", "A",
     "Under a proportional tax the rate is constant whatever the income."),
    ("Taxation", "Easy", "The canon of taxation that requires the cost of collecting a tax to be small relative to the revenue it yields is",
     "economy", "certainty", "convenience", "equity", "A",
     "Adam Smith's canons are equity, certainty, convenience and economy."),
    ("Taxation", "Medium", "Pay-As-You-Earn (PAYE), under which tax is deducted from salaries monthly, satisfies mainly the canon of",
     "convenience", "economy", "equity", "flexibility", "A",
     "Tax is collected at the time and in the manner most convenient for the taxpayer."),
    ("Taxation", "Medium", "A tax on cigarette manufacturers is passed on to smokers through higher prices. Economists say that the ______ of the tax has shifted to the smokers.",
     "incidence (final burden)", "rate of collection", "collecting agency", "purpose of spending", "A",
     "Formal incidence is on the person who pays the government; effective incidence is on whoever ultimately bears it."),
    ("Taxation", "Hard", "A tax of ₦100 per unit is placed on a good whose demand is perfectly inelastic. The burden of the tax falls",
     "entirely on consumers", "entirely on producers", "equally on consumers and producers", "on the government", "A",
     "With perfectly inelastic demand consumers buy the same quantity at any price, so the whole tax is passed on to them."),
    ("Taxation", "Medium", "Which of the following is an advantage of indirect taxes?",
     "they are difficult to evade because they are included in prices", "they fall more heavily on the rich than on the poor", "their burden is always borne by producers", "they do not affect the prices of goods", "A",
     "Everyone who buys taxed goods pays; but they tend to be regressive."),
    ("Taxation", "Medium", "The body responsible for collecting company income tax and VAT in Nigeria is the",
     "Federal Inland Revenue Service", "Central Bank of Nigeria", "Nigeria Customs Service", "Bureau of Public Enterprises", "A",
     "FIRS administers federal taxes; states collect personal income tax through their internal revenue services."),
    ("Taxation", "Medium", "A tax on the profits of companies is",
     "a direct tax", "an indirect tax", "a customs duty", "an excise duty", "A",
     "Company income tax is levied directly on the firm's profits and cannot easily be shifted."),
    ("Taxation", "Medium", "Governments impose taxes for all of the following reasons EXCEPT to",
     "increase the consumption of harmful goods", "raise revenue for public services", "redistribute income from rich to poor", "protect infant industries from imports", "A",
     "Taxes on alcohol and tobacco aim to reduce, not increase, their consumption."),
    ("Taxation", "Medium", "Mr Adeyemi earns ₦3 million a year. The first ₦300,000 is tax-free, the next ₦300,000 is taxed at 7% and the rest at 15%. His tax is",
     "₦381,000", "₦450,000", "₦405,000", "₦360,000", "A",
     "7% of 300,000 = 21,000; 15% of the remaining 2,400,000 = 360,000; total = ₦381,000.", "0.07*300000+0.15*2400000"),
    # ---------------- Economic Development ----------------
    ("Economic Development", "Medium", "Economic growth differs from economic development in that growth refers to",
     "an increase in a country's total output, while development includes improvements in welfare", "improvements in health and education only", "the fair distribution of income among citizens", "the change from agriculture to industry", "A",
     "Growth is a rise in real output; development also involves structural change and better living standards."),
    ("Economic Development", "Medium", "The Human Development Index measures a country's development using",
     "life expectancy, education and income per head", "the size of its army and population", "its total exports and imports", "the number of cars per household", "A",
     "The HDI combines health, knowledge and standard of living into one index."),
    ("Economic Development", "Medium", "Which of the following is a characteristic of a developing country?",
     "a large proportion of the labour force in agriculture", "a very high income per head", "a low birth rate and an ageing population", "a highly developed manufacturing sector", "A",
     "Developing economies typically depend heavily on primary production and have low productivity."),
    ("Economic Development", "Medium", "The vicious circle of poverty describes a situation in which",
     "low income leads to low savings, low investment and hence low income again", "rich countries become richer every year", "poor countries cannot borrow from abroad", "population falls as income rises", "A",
     "Low incomes prevent the saving needed for investment, so productivity and incomes stay low."),
    ("Economic Development", "Medium", "Foreign aid can help a developing country's development mainly by",
     "supplementing domestic savings to finance investment", "increasing the country's dependency on imports permanently", "reducing the level of education", "replacing the need for domestic taxation", "A",
     "Aid can fill the gap between the investment needed and the savings available, if well used."),
    ("Economic Development", "Medium", "A serious obstacle to economic development in Nigeria is",
     "corruption and poor infrastructure", "an excess of skilled manpower", "too much capital investment", "an ageing population", "A",
     "Diversion of public funds and unreliable power and transport raise costs and discourage investment."),
    ("Economic Development", "Medium", "Nigeria's economy is described as under-developed rather than undeveloped because",
     "it has large resources that are not yet fully and efficiently used", "it has no natural resources at all", "its population is too small to develop", "it has already reached its full potential", "A",
     "Under-development implies unexploited potential in land, minerals and people."),
    ("Economic Development", "Medium", "Which of the following is an indicator of improved economic development?",
     "a rise in life expectancy and literacy rates", "a rise in the number of people below the poverty line", "an increase in infant mortality", "a rise in the share of agriculture in employment", "A",
     "Development shows in better health, education and living standards, not just in output figures."),
    ("Economic Development", "Medium", "The Sustainable Development Goals (SDGs) adopted by the United Nations in 2015 aim, among other things, to",
     "end poverty and hunger and ensure quality education and health by 2030", "increase military spending in poor countries", "abolish international trade", "reduce the world's population by half", "A",
     "The 17 SDGs cover poverty, hunger, health, education, gender equality, clean energy and climate action."),
    ("Economic Development", "Medium", "Economic diversification is recommended for Nigeria mainly to",
     "reduce dependence on crude oil for revenue and foreign exchange", "increase the share of oil in total exports", "reduce the output of the agricultural sector", "discourage the growth of small businesses", "A",
     "A broader base of exports and revenue makes the economy less vulnerable to oil price shocks."),
    ("Economic Development", "Medium", "Human capital development refers to",
     "investment in education, training and health to raise the productivity of people", "the building of factories and roads", "the accumulation of foreign reserves", "the purchase of machinery from abroad", "A",
     "Healthier, better-educated workers are more productive and adaptable."),
    ("Economic Development", "Medium", "A country's real GDP grew by 3% in a year in which its population grew by 3.5%. Its real income per head",
     "fell slightly", "rose slightly", "was unchanged", "doubled", "A",
     "When population grows faster than output, output per person falls."),
    # ---------------- Economic Planning ----------------
    ("Economic Planning", "Easy", "Economic planning is",
     "the deliberate direction of a country's resources towards chosen objectives over a period", "the annual budget speech of the minister of finance", "the recording of past economic transactions", "the pricing of goods by private firms", "A",
     "Plans set targets for growth, employment and infrastructure and outline the means of achieving them."),
    ("Economic Planning", "Medium", "Nigeria's First National Development Plan covered the period",
     "1962–1968", "1970–1974", "1975–1980", "1981–1985", "A",
     "The First Plan was launched in 1962; the Second (1970–74) followed the civil war."),
    ("Economic Planning", "Medium", "A plan that lays down targets for each sector of the economy and directs resources to meet them is",
     "a comprehensive (central) plan", "an indicative plan", "a rolling plan", "a perspective plan", "A",
     "Comprehensive plans are typical of centrally planned economies; indicative plans only guide private decisions."),
    ("Economic Planning", "Medium", "Nigeria's 1990–1992 plan was reviewed at the end of 1990 and extended to cover 1991–1993, and this was repeated every year. Such a plan is described as",
     "a rolling plan", "a fixed five-year plan", "a local government plan", "a twenty-year perspective plan", "A",
     "Nigeria adopted three-year rolling plans in 1990 to allow adjustment to changing conditions."),
    ("Economic Planning", "Medium", "A perspective plan differs from a medium-term plan in that it",
     "sets broad goals for a long period such as 15 to 25 years", "covers only one financial year", "is prepared by private firms", "contains no targets at all", "A",
     "Nigeria's Vision 2010 and Vision 20:2020 were long-term perspective plans."),
    ("Economic Planning", "Medium", "A common reason for the failure of development plans in Nigeria is",
     "inadequate and unreliable statistical data", "the absence of any natural resources", "too much money in the treasury", "the very small size of the population", "A",
     "Poor data on population, output and prices make targets unrealistic; political instability and corruption also contribute."),
    ("Economic Planning", "Medium", "Which of the following is an objective of economic planning?",
     "raising the standard of living and reducing unemployment", "increasing the rate of inflation", "widening the gap between rich and poor", "reducing the output of the economy", "A",
     "Plans aim at growth, employment, price stability, balanced regional development and fairer income distribution."),
    ("Economic Planning", "Medium", "Nigeria's Structural Adjustment Programme (SAP) of 1986 was introduced mainly to",
     "restructure the economy by reducing dependence on oil and imports and liberalising markets", "nationalise all foreign companies in Nigeria", "increase the number of marketing boards", "fix the exchange rate of the naira permanently", "A",
     "SAP devalued the naira, abolished marketing boards, privatised enterprises and removed many controls."),
    ("Economic Planning", "Medium", "In an indicative plan, the government",
     "sets out expected trends and encourages private firms to follow them", "directly owns and runs all the industries", "forbids private investment in the economy", "fixes the prices of all goods and services", "A",
     "Indicative planning guides rather than commands, using incentives to steer the private sector."),
    ("Economic Planning", "Medium", "Adequate funding, reliable data and political stability are",
     "conditions for successful economic planning", "obstacles to economic planning", "features of a subsistence economy", "canons of taxation", "A",
     "Without finance, information and continuity of policy, plan targets are unlikely to be met."),
    ("Economic Planning", "Medium", "Nigeria's National Development Plan 2021–2025 emphasised",
     "diversification, infrastructure and job creation", "a return to marketing boards", "the abolition of private enterprise", "the reduction of the labour force", "A",
     "Recent plans have focused on growing non-oil sectors, closing infrastructure gaps and creating jobs for the youth."),
]

FIX = {
    "instructs banks to lend more to agriculture": (
        "selective credit control (directives)", "open market operations in securities", "bank rate (monetary policy rate) policy", "moral suasion through persuasion"),
    "liquidity ratio requires it to hold": (
        "cash and assets that can quickly be turned into cash", "long-term loans to manufacturing and mining firms", "shares and debentures in private limited companies", "buildings, vehicles and other fixed assets it owns"),
    "Great Depression of the 1930s": (
        "deflation accompanied by depression", "demand-pull inflation with full employment", "stagflation caused by rising oil prices", "hyperinflation caused by printing money"),
    "labour force of a country consists of": (
        "all persons of working age who are working or actively seeking work", "the whole population of the country including children and the aged", "all persons employed in the civil service and the public corporations", "children, full-time students and retired persons who receive pensions"),
    "Optimum population is the population size": (
        "gives the highest output per head with the available resources", "is the largest number of people the country can possibly feed", "the government of the day decides is ideal for the country", "has the lowest death rate and the highest life expectancy"),
    "Agriculture contributes to Nigeria's industrial development": (
        "supplying raw materials such as cotton, cocoa and palm oil to factories", "providing electricity and water for the factories in the industrial estates", "producing the machinery and spare parts used by manufacturing industries", "fixing the prices at which manufactured goods are sold in the markets"),
    "commodity marketing boards in Nigeria before 1986": (
        "buy export crops from farmers at fixed prices and sell them abroad", "import food from abroad and sell it cheaply to consumers in the cities", "lend money to farmers at low interest rates for buying farm inputs", "train farmers in modern farming methods through extension officers"),
    "Before the oil boom of the 1970s": (
        "the export of agricultural produce such as cocoa, groundnuts and palm oil", "the export of refined petroleum products such as petrol and kerosene", "revenue from foreign tourists visiting the country's game reserves", "the export of manufactured goods such as textiles and cement"),
    "Farm mechanisation is difficult in much of southern Nigeria": (
        "farm plots are small and scattered and the terrain is often forested", "farmers in the region are not allowed by law to buy or hire tractors", "the soil of the region is too fertile to need any form of machinery", "there is no demand for the food crops grown on the farms of the region"),
    "Agricultural extension services are provided to": (
        "teach farmers improved methods and spread new technology", "buy farmers' produce at harvest time at guaranteed prices", "collect taxes and levies from farmers in the rural areas", "build feeder roads and bridges in the main farming areas"),
    "encouraging local factories to make goods that were previously imported": (
        "import substitution industrialisation", "export promotion industrialisation", "nationalisation of foreign companies", "regional economic integration"),
    "Ajaokuta Steel Company was intended to": (
        "provide the basic industry for producing iron and steel for other industries", "refine crude oil into petrol, diesel and kerosene for the domestic market", "assemble cars and lorries for export to other West African countries", "process cocoa beans into chocolate and beverages for export to Europe"),
    "Lekki Free Zone are set up to": (
        "attract manufacturers with infrastructure and tax incentives in one location", "prevent foreign firms from operating anywhere within the country's borders", "relocate all the factories in the big cities to the rural areas of the country", "increase the customs duties charged on goods imported into the country"),
    "wholesaler differs from a retailer": (
        "buys in bulk from producers and sells in smaller lots to retailers", "sells goods in small quantities directly to the final consumers", "manufactures the goods that he sells in his own factory or workshop", "operates only in the rural markets that are held on fixed days"),
    "bill of lading, which is": (
        "a receipt for goods shipped and evidence of the contract of carriage", "a demand for payment sent by the exporter to the foreign importer", "a licence issued by the government permitting goods to be imported", "a certificate showing the country in which the goods were produced"),
    "trade across the border": (
        "involves different currencies, languages, laws and trade barriers", "is always carried out by governments rather than by private firms", "does not involve the physical transport of goods from place to place", "is never affected by changes in the prices of the goods traded"),
    "exports consist mainly of crude oil is vulnerable": (
        "a fall in the world oil price sharply reduces its export earnings", "crude oil is never demanded by the industrialised countries", "it cannot import any manufactured goods from other countries", "its currency will always appreciate against other currencies"),
    "finances a balance of payments deficit by": (
        "drawing on its foreign reserves or borrowing from abroad", "printing more of its own currency notes and coins", "raising the wages and salaries of its own workers", "reducing the volume of goods that it exports abroad"),
    "external reserves are held mainly to": (
        "settle international payments and support the value of the naira", "pay the monthly salaries of federal and state civil servants", "finance the construction of local roads and rural markets", "lend money in naira to commercial banks that are short of cash"),
    "payment of interest on Nigeria's foreign debt is recorded as": (
        "an invisible import (debit) in the current account", "a visible import (debit) in the trade account", "a capital inflow in the financial account", "an invisible export (credit) in the current account"),
    "capital account of the balance of payments records": (
        "flows of loans and investments between a country and the rest of the world", "exports and imports of physical goods such as oil, cocoa and machinery", "payments made for services such as shipping, insurance and banking", "gifts, grants and remittances received from or sent to other countries"),
    "main source of revenue for Nigeria's federal government": (
        "receipts from crude oil and gas", "company income tax receipts", "personal income tax receipts", "revenue from foreign tourists"),
    "Federation Account is": (
        "the pool into which federally collected revenue is paid before being shared", "the account into which each state government pays its own internal revenue", "the account kept by the central bank for the salaries of federal workers", "the loan account that the federal government keeps with the World Bank"),
    "supplementary budget is": (
        "additional spending approved after the main budget proves insufficient", "the annual budget presented by a state government to its assembly", "a budget in which planned revenue is exactly equal to planned spending", "a budget prepared by the central bank for its own annual operations"),
    "Economic growth differs from economic development": (
        "an increase in a country's total output, while development includes welfare", "improvements in health and education, while development means more output", "the fair distribution of income, while development means higher exports", "the change from agriculture to industry, while development means more trade"),
    "vicious circle of poverty describes": (
        "low income leads to low savings, low investment and hence low income again", "rich countries grow richer every year while poor countries grow poorer", "poor countries cannot borrow from abroad because they have no collateral", "population falls as income rises, so the labour force keeps shrinking"),
    "under-developed rather than undeveloped because": (
        "it has large resources that are not yet fully and efficiently used", "it has no natural resources at all and must import all its raw materials", "its population is too small to provide the labour needed for development", "it has already reached its full potential and cannot develop any further"),
    "Sustainable Development Goals (SDGs)": (
        "end poverty and hunger and ensure quality education and health by 2030", "increase military spending in poor countries to guarantee their security", "abolish international trade between developed and developing countries", "reduce the population of the world by half before the end of the century"),
    "Human capital development refers to": (
        "investment in education, training and health to raise the productivity of people", "the building of factories, roads, bridges and railways by the government", "the accumulation of foreign reserves by the central bank of a country", "the purchase of modern machinery and equipment from foreign countries"),
    "Economic planning is": (
        "the deliberate direction of a country's resources towards chosen objectives", "the annual budget speech delivered by the minister of finance", "the recording of the economic transactions of the past financial year", "the fixing of the prices of goods and services by private business firms"),
    "perspective plan differs from a medium-term plan": (
        "sets broad goals for a long period such as 15 to 25 years", "covers only one financial year and is revised every month", "is prepared by private firms rather than by the government", "contains no targets at all, only a description of the economy"),
    "Structural Adjustment Programme (SAP) of 1986": (
        "restructure the economy by reducing dependence on oil and liberalising markets", "nationalise all the foreign companies operating in the country's oil sector", "increase the number of commodity marketing boards buying farmers' produce", "fix the exchange rate of the naira permanently at one naira to one dollar"),
    "In an indicative plan, the government": (
        "sets out expected trends and encourages private firms to follow them", "directly owns and runs all the industries and farms in the country", "forbids private individuals and firms from investing in the economy", "fixes the prices of all goods and services sold in the country"),
}


def build():
    build_batch(
        S, "batch_022_econ_round3b.json", "batch_022_econ_round3b",
        "Economics round 3 (part B): macro-economics and the Nigerian economy - national income and its measurement, money and banking, inflation, deflation, unemployment, population, agriculture, industrialisation, trade, international trade, balance of payments, public finance, taxation, development and planning, with a national-income accounts table and a two-state population table as data passages.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
