"""Batch 043 - WAEC English, Paper 3 (Test of Orals), round 1.

Nigeria's WASSCE English includes a 60-item multiple-choice Test of Orals (45 minutes)
covering the phonetics syllabus: pure vowels and diphthongs, consonants and clusters,
rhymes, stress, intonation, letter sounds and homophones.  All items use standard IPA
symbols, exactly as the CBT displays them.  Topic names start with 'Test of Orals' so
the engine can build the paper from this slice of the English bank.

    python3 scripts/build_content_batch43.py -> content/batch_043_waec_english_test_of_orals.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "English"

T_VOW = "Test of Orals — Vowels and Diphthongs"
T_CONS = "Test of Orals — Consonants and Clusters"
T_RHYME = "Test of Orals — Rhymes"
T_STRESS = "Test of Orals — Stress"
T_INTON = "Test of Orals — Intonation"
T_LETTER = "Test of Orals — Letters and Letter Groups"
T_HOMO = "Test of Orals — Homophones"

PASSAGES = []
PQ = []

Q = [
    # ------------------------------------------------------------------ vowels
    (T_VOW, "Easy", "Which of the following words contains the vowel /iː/?",
     "sheep", "ship", "shop", "soap",
     "A", "Sheep is pronounced /ʃiːp/ with the long /iː/; ship has /ɪ/, shop /ɒ/ and soap /əʊ/."),
    (T_VOW, "Easy", "Which of the following words contains the vowel /ɪ/?",
     "sit", "seat", "set", "sat",
     "A", "Sit is /sɪt/; seat has /iː/, set /e/ and sat /æ/."),
    (T_VOW, "Easy", "In which word is the letter 'e' pronounced /e/?",
     "bed", "beat", "bite", "boot",
     "A", "Bed is /bed/ with /e/; beat is /biːt/, bite /baɪt/ and boot /buːt/."),
    (T_VOW, "Easy", "Which of the following words contains the vowel /æ/?",
     "cat", "cot", "coat", "cut",
     "A", "Cat is /kæt/ with /æ/; cot /kɒt/, coat /kəʊt/ and cut /kʌt/."),
    (T_VOW, "Easy", "In which word is the letter 'o' pronounced /ɒ/?",
     "hot", "hole", "hope", "home",
     "A", "Hot is /hɒt/; the other three words all contain the diphthong /əʊ/."),
    (T_VOW, "Medium", "Which of the following words contains the vowel /ɔː/?",
     "four", "five", "fire", "file",
     "A", "Four is /fɔː/; five is /faɪv/, fire /ˈfaɪə/ and file /faɪl/."),
    (T_VOW, "Easy", "In which word is the letter 'u' pronounced /ʌ/?",
     "cup", "cool", "cube", "cute",
     "A", "Cup is /kʌp/; cool is /kuːl/, cube /kjuːb/ and cute /kjuːt/."),
    (T_VOW, "Medium", "Which of the following words contains the vowel /ʊ/?",
     "book", "boot", "blue", "move",
     "A", "Book is /bʊk/ with short /ʊ/; boot is /buːt/, blue /bluː/ and move /muːv/."),
    (T_VOW, "Easy", "In which word is the letter combination 'oo' pronounced /uː/?",
     "food", "book", "full", "put",
     "A", "Food is /fuːd/ with long /uː/; book /bʊk/, full /fʊl/ and put /pʊt/."),
    (T_VOW, "Medium", "Which of the following words contains the vowel /ɑː/?",
     "car", "cat", "coat", "cure",
     "A", "Car is /kɑː/; cat /kæt/, coat /kəʊt/ and cure /kjʊə/."),
    (T_VOW, "Medium", "In which word is the vowel /ɜː/ found?",
     "bird", "bear", "bare", "bar",
     "A", "Bird is /bɜːd/; bear /beə/, bare /beə/ and bar /bɑː/."),
    (T_VOW, "Hard", "In which word does the unstressed vowel /ə/ (schwa) appear at the start?",
     "about", "boot", "eat", "see",
     "A", "About is /əˈbaʊt/ and opens with the schwa /ə/; the others have /uː/, /iː/ and /iː/."),
    (T_VOW, "Easy", "Which of the following words contains the diphthong /eɪ/?",
     "face", "foot", "moon", "book",
     "A", "Face is /feɪs/ with /eɪ/; foot /fʊt/, moon /muːn/ and book /bʊk/."),
    (T_VOW, "Medium", "In which word is the letter combination 'ie' pronounced /aɪ/?",
     "five", "field", "fire", "find",
     "A", "Five is /faɪv/ with /aɪ/ for 'ie'; in field the 'ie' is /iː/, while fire and find do not use 'ie' that way."),
    (T_VOW, "Medium", "Which of the following words contains the diphthong /ɔɪ/?",
     "choice", "chair", "cheer", "cheap",
     "A", "Choice is /tʃɔɪs/ with /ɔɪ/; chair /tʃeə/, cheer /tʃɪə/ and cheap /tʃiːp/."),
    (T_VOW, "Easy", "In which word is the letter combination 'ou' pronounced /aʊ/?",
     "house", "though", "through", "group",
     "A", "House is /haʊs/ with /aʊ/; though /ðəʊ/, through /θruː/ and group /gruːp/."),
    (T_VOW, "Easy", "Which of the following words contains the diphthong /əʊ/?",
     "phone", "food", "moon", "blue",
     "A", "Phone is /fəʊn/ with /əʊ/; the other words all have the long /uː/."),
    (T_VOW, "Medium", "In which word is the letter combination 'air' pronounced /eə/?",
     "chair", "fear", "near", "hear",
     "A", "Chair is /tʃeə/; fear /fɪə/, near /nɪə/ and hear /hɪə/ all use /ɪə/."),
    (T_VOW, "Medium", "Which pair of words both contain the diphthong /aʊ/?",
     "mouth and south", "moon and boot", "face and rain", "car and coat",
     "A", "Mouth /maʊθ/ and south /saʊθ/ both use /aʊ/; the other pairs use different vowels."),
    (T_VOW, "Hard", "In which word is 'ough' pronounced /uː/?",
     "through", "though", "thought", "cough",
     "A", "Through is /θruː/; though is /ðəʊ/, thought /θɔːt/ and cough /kɒf/."),
    (T_VOW, "Hard", "In which word is 'ough' pronounced /əʊ/?",
     "though", "through", "thought", "cough",
     "A", "Though is /ðəʊ/; through is /θruː/, thought /θɔːt/ and cough /kɒf/."),
    (T_VOW, "Hard", "In which word is 'ough' pronounced /ɔː/?",
     "thought", "though", "through", "cough",
     "A", "Thought is /θɔːt/ with /ɔː/; though /ðəʊ/, through /θruː/ and cough /kɒf/."),
    (T_VOW, "Hard", "In which word is 'ough' pronounced /ɒ/?",
     "cough", "though", "through", "bough",
     "A", "Cough is /kɒf/; though /ðəʊ/, through /θruː/ and bough /baʊ/."),
    (T_VOW, "Medium", "Which pair of words has the same vowel sound?",
     "sheep and beat", "ship and seat", "fish and beat", "car and coat",
     "A", "Sheep /ʃiːp/ and beat /biːt/ both have /iː/; the other pairs differ."),

    # ------------------------------------------------------------------ consonants
    (T_CONS, "Easy", "Which of the following words begins with the sound /θ/?",
     "think", "this", "that", "they",
     "A", "Think begins with voiceless /θ/; this, that and they all begin with /ð/."),
    (T_CONS, "Easy", "In which word is 'th' pronounced /ð/?",
     "that", "think", "three", "thick",
     "A", "That is /ðæt/; think /θɪŋk/, three /θriː/ and thick /θɪk/ use voiceless /θ/."),
    (T_CONS, "Medium", "Which of the following words contains the sound /ʃ/?",
     "sugar", "sun", "sing", "soft",
     "A", "Sugar is /ˈʃʊɡə/ with /ʃ/; the other words begin with /s/."),
    (T_CONS, "Medium", "In which word is the letter 's' pronounced /ʒ/?",
     "measure", "message", "music", "museum",
     "A", "In measure the 's' is voiced as /ʒ/ (/meʒə/); in the others it is /s/."),
    (T_CONS, "Medium", "Which of the following words ends with the sound /tʃ/?",
     "watch", "chair", "tea", "cheap",
     "A", "Watch is /wɒtʃ/ and ends in /tʃ/; the other words end in /eə/, /iː/ and /iːp/."),
    (T_CONS, "Medium", "In which word is 'ch' pronounced /k/?",
     "school", "chair", "church", "teacher",
     "A", "In school, 'ch' is /k/ (/skuːl/); in the others it is /tʃ/."),
    (T_CONS, "Medium", "In which word is the letter 'c' pronounced /s/?",
     "city", "car", "cake", "cool",
     "A", "City is /ˈsɪti/; in car, cake and cool the 'c' is /k/."),
    (T_CONS, "Medium", "Which word ends with the sound /ŋ/?",
     "singing", "sing", "sings", "singer",
     "A", "Singing ends in the nasal /ŋ/; sing ends in /g/, sings in /z/ and singer in /ə/."),
    (T_CONS, "Easy", "In which word is 'x' pronounced /ks/?",
     "box", "exam", "exit", "exact",
     "A", "Box ends in /ks/; in exam, exit and exact the 'x' is /z/."),
    (T_CONS, "Easy", "In which word is 'x' pronounced /z/?",
     "exam", "box", "mix", "fix",
     "A", "Exam has /z/ for 'x' (/ɪɡzæm/); box, mix and fix all have /ks/."),
    (T_CONS, "Medium", "In which word is the letter 'k' silent?",
     "knife", "kind", "kite", "kick",
     "A", "Knife is /naɪf/; the 'k' before 'n' is silent, as in knife, knee and knuckle."),
    (T_CONS, "Medium", "In which word is the letter 'w' silent?",
     "write", "work", "well", "week",
     "A", "Write is /raɪt/; the 'w' is silent in write, wrong and wrap."),
    (T_CONS, "Medium", "In which word is the first 'h' silent?",
     "hour", "heart", "hand", "half",
     "A", "Hour is /aʊə/ with a silent 'h'; the others are pronounced with /h/."),
    (T_CONS, "Easy", "Which pair of words begins with the sound /ʃ/?",
     "ship and sheep", "school and shoe", "sun and sing", "soft and saw",
     "A", "Ship /ʃɪp/ and sheep /ʃiːp/ both begin with /ʃ/; school begins /sk/, and the s-words begin with /s/."),
    (T_CONS, "Medium", "In which word is 'ph' pronounced /f/ in the middle of the word?",
     "graph", "phone", "physics", "phrase",
     "A", "Graph /ɡrɑːf/ has /f/ for 'ph' in the middle; the others begin with /f/."),

    # ------------------------------------------------------------------ rhymes
    (T_RHYME, "Easy", "Which word rhymes with 'caught'?",
     "taught", "catch", "coat", "city",
     "A", "Caught /kɔːt/ and taught /tɔːt/ rhyme; catch /kætʃ/, coat /kəʊt/ and city do not."),
    (T_RHYME, "Easy", "Which word rhymes with 'night'?",
     "light", "knee", "knew", "coat",
     "A", "Night /naɪt/ rhymes with light /laɪt/; knee /niː/, knew /njuː/ and coat /kəʊt/ do not."),
    (T_RHYME, "Easy", "Which word rhymes with 'house'?",
     "mouse", "nose", "moose", "rose",
     "A", "House /haʊs/ rhymes with mouse /maʊs/; nose /nəʊz/, moose /muːs/ and rose /rəʊz/ differ."),
    (T_RHYME, "Medium", "Which word rhymes with 'fire'?",
     "tire", "fur", "four", "fair",
     "A", "Fire /ˈfaɪə/ rhymes with tire /ˈtaɪə/; fur /fɜː/, four /fɔː/ and fair /feə/ differ."),
    (T_RHYME, "Medium", "Which word rhymes with 'city'?",
     "pretty", "sitting", "sister", "sit",
     "A", "City /ˈsɪti/ rhymes with pretty /ˈprɪti/; sitting /ˈsɪtɪŋ/, sister /ˈsɪstə/ and sit /sɪt/ do not."),
    (T_RHYME, "Medium", "Which word rhymes with 'silly'?",
     "billy", "honey", "handy", "hilly",
     "A", "Silly /ˈsɪli/ rhymes with billy /ˈbɪli/; honey /ˈhni/, handy /ˈhændi/ and hilly /ˈhɪli/ differ."),
    (T_RHYME, "Medium", "Which word rhymes with 'peach'?",
     "beach", "rich", "pitch", "match",
     "A", "Peach /piːtʃ/ rhymes with beach /biːtʃ/; rich /rɪtʃ/, pitch /pɪtʃ/ and match /mætʃ/ differ."),
    (T_RHYME, "Easy", "Which word rhymes with 'book'?",
     "look", "back", "bag", "bed",
     "A", "Book /bʊk/ rhymes with look /lʊk/; back /bæk/, bag /bæg/ and bed /bed/ do not."),
    (T_RHYME, "Medium", "Which word rhymes with 'came'?",
     "name", "time", "team", "home",
     "A", "Came /keɪm/ rhymes with name /neɪm/; time /taɪm/, team /tiːm/ and home /həʊm/ differ."),
    (T_RHYME, "Medium", "Which word rhymes with 'heart'?",
     "start", "hurt", "hair", "care",
     "A", "Heart /hɑːt/ rhymes with start /stɑːt/; hurt /hɜːt/, hair /heə/ and care /keə/ differ."),
    (T_RHYME, "Medium", "Which word rhymes with 'shoe'?",
     "blue", "shook", "shake", "short",
     "A", "Shoe /ʃuː/ rhymes with blue /bluː/; shook /ʃʊk/, shake /ʃeɪk/ and short /ʃɔt/ differ."),
    (T_RHYME, "Medium", "Which word rhymes with 'time'?",
     "crime", "team", "home", "name",
     "A", "Time /taɪm/ rhymes with crime /kraɪm/; team /tiːm/, home /həʊm/ and name /neɪm/ differ."),
    (T_RHYME, "Hard", "Which word rhymes with 'question'?",
     "education", "section", "decision", "position",
     "A", "Question /ˈkwestʃən/ shares its /-ʃən/ ending with education /ˌedʒuˈkeɪʃən/."),
    (T_RHYME, "Medium", "Which pair of words rhymes?",
     "caught and taught", "house and nose", "book and wood", "car and cart",
     "A", "Caught /kɔːt/ and taught /tɔːt/ rhyme; the other pairs use different vowel sounds."),

    # ------------------------------------------------------------------ stress
    (T_STRESS, "Easy", "In which word is the stress on the SECOND syllable?",
     "begin", "teacher", "garden", "happy",
     "A", "Begin is /bɪˈɡɪn/ with second-syllable stress; teacher, garden and happy are stressed on the first."),
    (T_STRESS, "Easy", "Which of these words is stressed on the SECOND syllable?",
     "hotel", "garden", "English", "president",
     "A", "Hotel is /həʊˈtel/ with second-syllable stress; the others open with the stress."),
    (T_STRESS, "Medium", "In which word does the stress fall on the SECOND syllable?",
     "machine", "teacher", "garden", "student",
     "A", "Machine is /məˈʃiːn/ with second-syllable stress; the others are first-syllable words."),
    (T_STRESS, "Medium", "Which of the following words carries the stress on its second syllable?",
     "descend", "beautiful", "Monday", "doctor",
     "A", "Descend is /dɪˈsend/ with second-syllable stress; the others carry first-syllable stress."),
    (T_STRESS, "Medium", "Which word below has the stress on its SECOND syllable?",
     "arrive", "teacher", "garden", "doctor",
     "A", "Arrive is /əˈraɪv/ with second-syllable stress; the others are stressed on the first."),
    (T_STRESS, "Hard", "As a noun, which of these words is stressed on the SECOND syllable?",
     "permit", "garden", "happy", "Monday",
     "A", "The noun permit is /pəˈmɪt/ with second-syllable stress; the others are first-syllable words."),
    (T_STRESS, "Medium", "In which of the words below is the main stress on the SECOND syllable?",
     "explain", "beautiful", "student", "president",
     "A", "Explain is /ɪkˈspleɪn/ with second-syllable stress; the others are first-syllable words."),
    (T_STRESS, "Medium", "Which word below is stressed on the SECOND syllable?",
     "deserve", "English", "doctor", "garden",
     "A", "Deserve is /dɪˈzɜːv/ with second-syllable stress; the others open with the stress."),
    (T_STRESS, "Easy", "In which word is the stress on the FIRST syllable?",
     "teacher", "machine", "hotel", "begin",
     "A", "Teacher is /ˈtiːtʃə/ with first-syllable stress; machine, hotel and begin are stressed later."),
    (T_STRESS, "Easy", "Which of these words is stressed on the FIRST syllable?",
     "garden", "begin", "hotel", "machine",
     "A", "Garden is /ˈɡɑːdn/ with first-syllable stress; the others carry second-syllable stress."),
    (T_STRESS, "Easy", "In which word does the stress fall on the FIRST syllable?",
     "English", "hotel", "machine", "begin",
     "A", "English is /ˈɪŋɡlɪʃ/ with first-syllable stress; the others are stressed on the second."),
    (T_STRESS, "Easy", "Which word below carries the stress on its first syllable?",
     "happy", "begin", "hotel", "machine",
     "A", "Happy is /ˈhæpi/ with first-syllable stress; the others carry second-syllable stress."),
    (T_STRESS, "Medium", "In which word is the main stress on the FIRST syllable?",
     "Monday", "arrive", "descend", "relax",
     "A", "Monday is /ˈmʌndeɪ/ with first-syllable stress; arrive, descend and relax are stressed later."),
    (T_STRESS, "Medium", "In which word is the stress on the THIRD syllable?",
     "vegetable", "garden", "teacher", "happy",
     "A", "Vegetable is /ˌvedʒəˈteɪbəl/ with the main stress on the third syllable /teɪ/."),
    (T_STRESS, "Medium", "Which of these words is stressed on the THIRD syllable?",
     "information", "beautiful", "doctor", "president",
     "A", "Information is /ˌɪnfəmeɪʃn/ with the main stress on the third syllable /meɪ/."),
    (T_STRESS, "Medium", "In which word does the stress fall on the THIRD syllable?",
     "education", "English", "garden", "teacher",
     "A", "Education is /ˌedʒuˈkeɪʃn/ with the main stress on the third syllable /keɪ/."),
    (T_STRESS, "Hard", "As a noun, the word 'record' is stressed on which syllable?",
     "the first", "the second", "the third", "it has no stress",
     "A", "The noun REcord /ˈrekɔːd/ carries the stress on the first syllable; the verb reCORD falls on the second."),
    (T_STRESS, "Hard", "In which pair does the stress change between the noun and the verb?",
     "present — present", "garden — gardens", "apple — apples", "student — students",
     "A", "The noun PREsent /ˈpreznt/ and the verb preSENT /prɪˈzent/ have different stress positions."),
    (T_STRESS, "Hard", "Which of these noun-verb pairs shows a change of stress?",
     "contract — contract", "garden — gardens", "happy — happily", "teacher — teachers",
     "A", "The noun CONtract /ˈkɒntrækt/ and the verb conTRACT /kənˈtrækt/ differ in stress."),
    (T_STRESS, "Medium", "In compound nouns such as 'blackboard', the stress usually falls on",
     "the first part", "the second part", "both parts equally", "no part at all",
     "A", "Compound nouns like BLAckboard /ˈblækbɔːd/ carry the stress on their first part."),

    # ------------------------------------------------------------------ intonation
    (T_INTON, "Easy", "What intonation do we use in the statement 'The examination will start at eight o'clock'?",
     "falling", "rising", "rising then falling", "flat",
     "A", "Statements end with a falling intonation, which signals a complete thought."),
    (T_INTON, "Easy", "What intonation do we use in the question 'Are you coming to the party'?",
     "rising", "falling", "flat", "falling then rising",
     "A", "Yes/no questions take a rising intonation at the end."),
    (T_INTON, "Medium", "What intonation do we use in the question 'Where did you buy the book'?",
     "falling", "rising", "flat", "rising then falling",
     "A", "Wh- questions (where, what, why) take a falling intonation, unlike yes/no questions."),
    (T_INTON, "Medium", "We use a RISING intonation in all of the following EXCEPT",
     "commands", "yes/no questions", "requests", "expressing surprise",
     "A", "Commands such as 'Close the door' end with falling intonation; the others commonly rise."),
    (T_INTON, "Hard", "In the list 'I bought rice, beans, yam, and fish', the word 'yam' usually takes",
     "a rising tone", "a falling tone", "a flat tone", "a falling-then-rising tone",
     "A", "Items before the last in a list rise; only the final item 'fish' falls."),
    (T_INTON, "Medium", "The final item in a list usually takes what intonation?",
     "a falling tone", "a rising tone", "a flat tone", "a rising-then-falling tone",
     "A", "The last item of a list completes the thought and takes a falling tone."),
    (T_INTON, "Easy", "Which sentence takes a FALLING intonation at the end?",
     "Close the door", "Is it cold", "Can you help", "Really",
     "A", "The command 'Close the door' is said with falling intonation; the others rise."),
    (T_INTON, "Medium", "In expressing strong surprise ('You PASSED the exam!'), we usually use",
     "a rising tone", "a falling tone", "a flat tone", "no change of tone",
     "A", "Strong surprise raises the pitch, so the exclamation ends with a rising tone."),

    # ------------------------------------------------------------------ letters
    (T_LETTER, "Easy", "In which word is 'ea' pronounced /iː/?",
     "meat", "bread", "head", "dead",
     "A", "Meat is /miːt/; in bread, head and dead the 'ea' is /e/."),
    (T_LETTER, "Easy", "In which word is 'ea' pronounced /e/?",
     "bread", "meat", "sea", "team",
     "A", "Bread is /bred/ with /e/; meat /miːt/, sea /siː/ and team /tiːm/ have /iː/."),
    (T_LETTER, "Medium", "In which word is the letter 'a' pronounced /eɪ/?",
     "name", "man", "map", "make",
     "A", "Name is /neɪm/ with /eɪ/; man /mæn/ and map /mæp/ have /æ/, and make uses the 'a-e' pattern."),
    (T_LETTER, "Medium", "In which word is the letter 'y' pronounced /aɪ/?",
     "my", "yes", "system", "yellow",
     "A", "My is /maɪ/ with /aɪ/ for 'y'; in yes and yellow it is /j/, and in system it is /ɪ/."),
    (T_LETTER, "Hard", "In which word is 'ou' pronounced /ʌ/?",
     "country", "house", "mouth", "loud",
     "A", "Country is /ˈkʌntri/ with /ʌ/; house /haʊs/, mouth /maʊθ/ and loud /laʊd/ use /aʊ/."),
    (T_LETTER, "Medium", "In which word is 'oo' pronounced /ʊ/?",
     "good", "food", "moon", "school",
     "A", "Good is /ɡʊd/ with the short /ʊ/; the others all have the long /uː/."),
    (T_LETTER, "Hard", "In which word is 'oo' pronounced /ʌ/?",
     "blood", "good", "boot", "food",
     "A", "Blood is /blʌd/ with /ʌ/; good /ɡʊd/, boot /buːt/ and food /fuːd/ differ."),
    (T_LETTER, "Easy", "In which word is the letter 'o' pronounced /əʊ/?",
     "go", "hot", "lock", "box",
     "A", "Go is /gəʊ/ with /əʊ/; hot /hɒt/, lock /lɒk/ and box /bɒks/ have /ɒ/."),
    (T_LETTER, "Medium", "In which word is the final 'e' silent?",
     "made", "met", "bed", "red",
     "A", "Made is /meɪd/ and the final 'e' is not pronounced; in the others the 'e' is heard."),
    (T_LETTER, "Easy", "In which word is the letter 'c' pronounced /k/?",
     "car", "city", "magic", "special",
     "A", "Car is /kɑː/; in city, magic and special the 'c' sounds as /s/."),

    # ------------------------------------------------------------------ homophones
    (T_HOMO, "Medium", "Which pair of words are homophones?",
     "rain and reign", "rain and raise", "plain and plate", "boat and boot",
     "A", "Rain /reɪn/ and reign /reɪn/ sound the same but differ in meaning and spelling."),
    (T_HOMO, "Medium", "Which of the following pairs of words are homophones?",
     "flower and flour", "flower and flow", "flour and flow", "flower and floor",
     "A", "Flower /ˈflaə/ and flour /ˈflaʊə/ are pronounced identically."),
    (T_HOMO, "Medium", "Which pair of words below are homophones?",
     "meet and meat", "meet and seat", "meat and seat", "meet and mean",
     "A", "Meet /miːt/ and meat /miːt/ are pronounced the same."),
    (T_HOMO, "Medium", "Which of these pairs of words are homophones?",
     "know and no", "know and now", "no and nose", "know and not",
     "A", "Know /nəʊ/ and no /nəʊ/ are pronounced the same; now /naʊ/, nose /nəʊz/ and not /nɒt/ differ."),
    (T_HOMO, "Medium", "Which pair of words is pronounced exactly the same?",
     "hear and here", "hear and hero", "here and hero", "hear and hare",
     "A", "Hear /hɪə/ and here /hɪə/ sound the same in Nigerian English."),
    (T_HOMO, "Easy", "Which two words sound exactly alike?",
     "to and two", "too and tool", "two and toll", "to and tool",
     "A", "To /tuː/ and two /tuː/ are pronounced identically."),
]

FIX = {}
deactivate = None
retire_topics = None

build_batch(S, "batch_043_waec_english_test_of_orals.json", "batch_043_waec_english_test_of_orals",
            "WAEC English Paper 3 (Test of Orals) round 1: phonetics items in CBT multiple-choice form.",
            PASSAGES, PQ, Q, FIX, deactivate, retire_topics, exam_type="WAEC")
