"""Batch 030 - Commerce round 3, part A (trade and the aids to trade).

Introduction to commerce, occupation, production, factors of production, trade, home trade and business
documents, foreign trade, retail and wholesale trade, channels of distribution, transportation,
communication and warehousing.  Scenario items plus two data passages (an invoice and a country's
external transactions).

    python3 scripts/build_content_batch30.py -> content/batch_030_commerce_round3a.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Commerce"

T_INTRO = "Introduction to Commerce"
T_OCC = "Occupation"
T_PROD = "Production"
T_FOP = "Factors of Production"
T_TRADE = "Trade"
T_HOME = "Home Trade"
T_FOREIGN = "Foreign Trade"
T_RETAIL = "Retail Trade"
T_WHOLE = "Wholesale Trade"
T_CHAN = "Channels of Distribution"
T_TRANS = "Transportation"
T_COMM = "Communication"
T_WARE = "Warehousing"

PASSAGES = [
    ("C1", T_HOME, "Invoice received by Ada Fashion Stores",
     "Ada Fashion Stores, Enugu, received the following invoice from Kano Textiles Ltd.\n"
     "\n"
     "Invoice No. 0417     Date: 3 March 2026\n"
     "Your order No. 88 of 20 February 2026\n"
     "Item                Qty   Unit price\n"
     "Ankara, 6 yards     100     ₦4,000\n"
     "Lace, 5 yards        40     ₦9,000\n"
     "Less trade discount          10%\n"
     "Terms: 5% cash discount if paid\n"
     "within 7 days; otherwise net 30 days.\n"
     "Carriage paid.     E. & O.E."),
    ("C2", T_FOREIGN, "External transactions of Country Z, 2025",
     "The table shows the external transactions of Country Z for 2025.\n"
     "\n"
     "Item                          $ billion\n"
     "Visible exports                      45\n"
     "Visible imports                      52\n"
     "Services sold to foreigners          12\n"
     "Services bought from foreigners       8\n"
     "Remittances received                  9\n"
     "Remittances paid out                  2"),
]

PQ = [
    ("C1", "Easy", "The total list price of the goods on the invoice is",
     "₦760,000", "₦684,000", "₦736,000", "₦800,000",
     "A", "Ankara: 100 × ₦4,000 = ₦400,000; lace: 40 × ₦9,000 = ₦360,000; total list price ₦760,000.", "760000"),
    ("C1", "Medium", "If Ada Fashion Stores pays the invoice on 20 March 2026, the amount payable is",
     "₦684,000", "₦760,000", "₦649,800", "₦722,000",
     "A", "Trade discount of 10% (₦76,000) is deducted on the invoice: ₦760,000 − ₦76,000 = ₦684,000. Payment on 20 March is after 7 days, so no cash discount applies.", "684000"),
    ("C1", "Hard", "If Ada Fashion Stores pays on 8 March 2026, it pays",
     "₦649,800", "₦684,000", "₦646,000", "₦722,000",
     "A", "Payment within 7 days earns the 5% cash discount on ₦684,000, i.e. ₦34,200; the amount paid is ₦649,800.", "649800"),
    ("C1", "Easy", "'Carriage paid' on the invoice means that",
     "Kano Textiles Ltd bears the cost of transporting the goods to Enugu",
     "Ada Fashion Stores must pay the transporter on delivery of the goods",
     "the goods will be collected from the seller's warehouse by the buyer",
     "the transport cost has been added to the invoice total to be paid",
     "A", "Carriage paid means the seller pays the cost of delivery; carriage forward would make the buyer pay."),
    ("C1", "Hard", "Five pieces of lace arrived damaged and were returned. Kano Textiles Ltd should send Ada Fashion Stores",
     "a credit note for ₦40,500", "a debit note for ₦45,000", "a credit note for ₦45,000", "an invoice for ₦40,500",
     "A", "Returned goods are credited at the invoiced (net) price: 5 × ₦9,000 = ₦45,000 less 10% trade discount = ₦40,500, shown on a credit note.", "40500"),
    ("C1", "Easy", "The document Ada Fashion Stores sent to Kano Textiles Ltd on 20 February 2026 was",
     "an order", "a quotation", "a statement of account", "an advice note",
     "A", "The invoice quotes 'Your order No. 88 of 20 February 2026'; the buyer places an order and the seller responds with goods and an invoice."),
    ("C2", "Medium", "Country Z's balance of trade in 2025 was",
     "a deficit of $7 billion", "a surplus of $7 billion", "a deficit of $4 billion", "a surplus of $11 billion",
     "A", "Balance of trade = visible exports − visible imports = 45 − 52 = −$7 billion, an unfavourable (deficit) balance."),
    ("C2", "Medium", "The balance of invisible trade of Country Z was",
     "a surplus of $11 billion", "a deficit of $11 billion", "a surplus of $4 billion", "a surplus of $21 billion",
     "A", "Invisible receipts = 12 + 9 = 21; invisible payments = 8 + 2 = 10; invisible balance = +$11 billion."),
    ("C2", "Hard", "Country Z's current account balance for 2025 was",
     "a surplus of $4 billion", "a deficit of $4 billion", "a deficit of $7 billion", "a surplus of $11 billion",
     "A", "Current account = balance of trade + invisible balance = −7 + 11 = +$4 billion, a surplus."),
    ("C2", "Easy", "Remittances received from citizens working abroad are recorded in the accounts of Country Z as",
     "an invisible export", "a visible export", "a visible import", "an invisible import",
     "A", "Money earned abroad and sent home is a receipt from foreigners without any goods crossing the border, so it is an invisible export."),
    ("C2", "Medium", "If Country Z wished to turn its balance of trade into a surplus, the most appropriate measure would be to",
     "promote exports of goods and restrict non-essential imports through tariffs and quotas",
     "increase the remittances paid out to foreign workers living in the country",
     "buy more shipping and insurance services from companies based abroad",
     "reduce the sale of banking and tourism services to foreigners",
     "A", "The balance of trade concerns visible goods only; raising exports or cutting imports of goods is what improves it."),
]

Q = [
    # ---------------- Introduction to Commerce ----------------
    (T_INTRO, "Medium", "A cocoa farmer in Ondo sells his beans to a licensed buying agent, who sells them to an exporter in Lagos. A shipping line carries the beans to Amsterdam and an insurer covers them for the voyage. Of all these activities, the one that is NOT part of commerce is",
     "growing the cocoa on the farm", "buying by the licensed agent", "carriage by the shipping line", "insuring the cargo for the voyage",
     "A", "Growing cocoa is extractive industry (production). Buying, selling, transport and insurance are trade and aids to trade, which make up commerce."),
    (T_INTRO, "Easy", "Commerce is best described as the study of",
     "the distribution and exchange of goods and services, together with the activities that assist them",
     "the manufacture of finished goods from raw materials in factories and workshops",
     "the rendering of direct personal services such as teaching, nursing and hairdressing",
     "the management of a country's revenue, taxation and public spending by the government",
     "A", "Commerce covers trade (buying and selling) and the aids to trade such as banking, insurance, transport, warehousing, communication and advertising."),
    (T_INTRO, "Easy", "Which pair consists only of aids to trade?",
     "banking and warehousing", "mining and fishing", "retailing and wholesaling", "farming and manufacturing",
     "A", "Banking and warehousing assist trade; retailing and wholesaling are trade itself; mining, fishing, farming and manufacturing are industry."),
    (T_INTRO, "Medium", "A bakery in Aba produces 5,000 loaves a day but can sell only 800 in its own shop. The commercial activity that would most directly solve this problem is",
     "distribution through wholesalers and retailers in other towns",
     "buying a bigger oven so as to raise daily output further",
     "employing more bakers to work on the night shift",
     "changing the recipe so that the bread tastes better",
     "A", "The bakery's problem is distribution, not production; commerce links producers to consumers through the channel of distribution."),
    (T_INTRO, "Medium", "Tourism is regarded as an aid to trade mainly because it",
     "earns foreign exchange and creates demand for transport, hotels and local goods",
     "extracts minerals and timber from the natural environment for export",
     "converts raw materials into finished goods for sale in foreign markets",
     "provides free entertainment to citizens during the public holidays",
     "A", "Tourism brings visitors whose spending stimulates trade in transport, hospitality, crafts and other goods and services."),
    (T_INTRO, "Easy", "A trader in Onitsha buys textiles from a Lagos importer and sells them in her shop, using a bank loan, a haulage company and an insurance policy along the way. The banking, transport and insurance services she used are collectively called",
     "aids to trade", "home trade", "extractive industry", "direct services",
     "A", "Aids to trade are the services that make buying and selling possible: banking, insurance, transport, warehousing, communication, advertising and tourism."),
    (T_INTRO, "Easy", "The main difference between commerce and industry is that",
     "industry produces goods while commerce distributes and exchanges them",
     "industry is carried on by the government while commerce is private",
     "commerce produces goods while industry deals with their transport",
     "industry deals only with services while commerce deals only with goods",
     "A", "Industry (extractive, manufacturing, constructive) creates goods; commerce moves them from producers to consumers."),
    (T_INTRO, "Medium", "Which of the following best explains why commerce expanded after the introduction of money?",
     "Money removed the need for a double coincidence of wants, making exchange easier",
     "Money made it possible to grow more food on the same piece of farm land",
     "Money made transport by rail and road free of charge for every trader",
     "Money forced every producer to consume everything that he produced",
     "A", "Under barter each trader had to find someone who wanted his goods and had what he wanted; money made exchange quick and general."),
    (T_INTRO, "Easy", "The functions of commerce include all of the following EXCEPT",
     "the conversion of raw cotton into cloth in a textile mill",
     "the movement of goods from producers to consumers",
     "the provision of a link between producers and consumers",
     "the creation of employment in trade and its aids",
     "A", "Turning cotton into cloth is manufacturing, an industrial activity; the others are functions of commerce."),
    (T_INTRO, "Medium", "A country with good roads, reliable electricity, honest courts and a stable currency will attract more commercial activity because these are",
     "factors that promote the growth of commerce",
     "examples of aids to trade in the strict sense",
     "branches of the extractive industry",
     "direct personal services to consumers",
     "A", "Infrastructure, a stable currency, security and the rule of law are conditions that encourage trade, though they are not themselves aids to trade."),
    (T_INTRO, "Easy", "Home trade differs from foreign trade in that home trade",
     "takes place within the borders of one country and uses one currency",
     "requires import licences, customs duties and foreign exchange",
     "is carried out only by the government of the country",
     "involves goods only, whereas foreign trade involves services only",
     "A", "Home (internal or domestic) trade is buying and selling within a country; foreign trade crosses national borders and involves different currencies."),
    (T_INTRO, "Medium", "A student says 'commerce is just buying and selling'. The best correction is that commerce",
     "also includes the aids to trade such as banking, insurance, transport and advertising",
     "is really the same thing as manufacturing goods in factories and workshops",
     "includes only foreign trade and not the trade within the country itself",
     "refers only to the activities of the stock exchange and the commercial banks",
     "A", "Trade is the core of commerce, but commerce also embraces the services that assist trade."),
    (T_INTRO, "Medium", "Which of the following obstacles to trade is removed by warehousing?",
     "the time gap between production and consumption",
     "the distance between producer and consumer",
     "the lack of information about goods available",
     "the risk of loss of goods by fire, theft or accident",
     "A", "Warehousing stores goods until they are needed, bridging time; transport bridges distance, advertising bridges lack of knowledge and insurance covers risk."),
    (T_INTRO, "Easy", "The obstacle of consumers' lack of knowledge about a new product is chiefly overcome by",
     "advertising", "insurance", "warehousing", "banking",
     "A", "Advertising informs consumers that a product exists, what it does and where to buy it."),
    (T_INTRO, "Easy", "Insurance is an aid to trade because it",
     "removes the fear of loss and so encourages people to take business risks",
     "provides the buildings in which goods are stored before they are sold",
     "carries goods from the place of production to the place of sale",
     "supplies the money that traders need to buy their opening stock",
     "A", "By compensating for insured losses, insurance gives traders confidence to invest and to move goods."),
    (T_INTRO, "Hard", "A characteristic of commerce that distinguishes it from a direct service is that commerce",
     "is concerned with goods and the services that help their exchange, not personal skill",
     "is always provided free of charge to the whole community by the government",
     "requires a university degree from every person who takes part in it",
     "cannot be carried on without the use of computers and the internet",
     "A", "Direct services (doctors, lawyers, barbers) sell personal skill; commerce deals with the exchange of goods and the aids to that exchange."),
    # ---------------- Occupation ----------------
    (T_OCC, "Easy", "Police officers, soldiers and civil servants render services to the community as a whole rather than to identified individuals. Their occupations are classified as",
     "indirect services", "direct services", "commercial occupations", "constructive occupations",
     "A", "Indirect services benefit society generally; direct services such as those of a doctor or lawyer are rendered to particular persons."),
    (T_OCC, "Easy", "Which of the following is a constructive occupation?",
     "building the Second Niger Bridge", "mining tin on the Jos Plateau", "refining crude oil at Warri", "selling cement in a shop",
     "A", "Constructive occupations build roads, bridges, dams and houses; mining is extractive, refining is manufacturing and selling is commercial."),
    (T_OCC, "Medium", "A man quarries granite, another crushes it into chippings at a plant, and a third uses the chippings to build a road. Their occupations are, in order,",
     "extractive, manufacturing and constructive", "constructive, extractive and manufacturing",
     "manufacturing, commercial and extractive", "extractive, commercial and constructive",
     "A", "Quarrying takes material from nature (extractive), crushing processes it (manufacturing) and road building is constructive."),
    (T_OCC, "Easy", "A market woman who buys tomatoes from farmers in Kano and sells them in Enugu is engaged in a",
     "commercial occupation", "manufacturing occupation", "direct service", "extractive occupation",
     "A", "Buying and selling goods is trade, which is a commercial occupation."),
    (T_OCC, "Easy", "Which of the following workers is NOT engaged in an industrial occupation?",
     "a bank cashier", "a welder in a shipyard", "a rice farmer", "a bricklayer",
     "A", "Banking is an aid to trade (commercial occupation); welding, farming and bricklaying are industrial (manufacturing, extractive, constructive)."),
    (T_OCC, "Easy", "Occupations are classified into industrial, commercial and service occupations according to",
     "the nature of the work done", "the income earned by the worker", "the number of hours worked per week", "the location where the work is done",
     "A", "The classification depends on what the worker does: produce goods, exchange goods or render services."),
    (T_OCC, "Medium", "A soldier paid by the federal government and a lawyer who charges fees to private clients are both engaged in",
     "service occupations, though one is indirect and the other direct",
     "commercial occupations, since both are paid in money",
     "industrial occupations, since both produce a visible result",
     "extractive occupations, since both draw on natural talent",
     "A", "The soldier renders an indirect service to the community; the lawyer renders a direct service to individual clients."),
    (T_OCC, "Easy", "Poultry farming, fishing and lumbering belong to the same group of occupations because they all",
     "obtain products directly from nature", "change raw materials into finished goods",
     "distribute goods to final consumers", "render services directly to individuals",
     "A", "They are extractive (primary) occupations, which take products from land, water and forests."),
    (T_OCC, "Easy", "A factory that assembles imported parts into television sets is engaged in",
     "manufacturing (secondary) production", "extractive (primary) production", "tertiary production", "constructive production",
     "A", "Assembling components into finished goods is manufacturing, the secondary stage of production."),
    (T_OCC, "Medium", "Which of the following is an example of a tertiary occupation?",
     "operating a haulage company", "growing rice in Kebbi", "weaving cloth in Abeokuta", "drilling for crude oil in Bayelsa",
     "A", "Tertiary occupations provide services such as transport, banking and trade; the others are primary or secondary."),
    (T_OCC, "Medium", "A graduate who cannot find paid employment starts making and selling liquid soap at home. In terms of occupation, she has moved from",
     "unemployment into manufacturing and commerce", "commerce into the extractive industry",
     "direct services into indirect services", "industry into the civil service",
     "A", "Making soap is manufacturing (industry) and selling it is trade (commerce)."),
    (T_OCC, "Easy", "Interdependence among occupations means that",
     "each occupation depends on the products or services of others",
     "every worker must hold two jobs at the same time",
     "the government must own all businesses in the country",
     "no occupation can be carried on in a rural area",
     "A", "A farmer needs the blacksmith's hoe and the trader's market; the trader needs the farmer's crops and the transporter's lorry."),
    (T_OCC, "Easy", "A journalist, an accountant and a computer programmer earn their living mainly by",
     "selling their skills as direct services", "extracting raw materials from the earth",
     "buying and reselling goods for profit", "constructing roads, bridges and houses",
     "A", "These are professional (direct) services rendered to clients or employers for a fee or salary."),
    (T_OCC, "Medium", "Specialisation among occupations is made possible chiefly by",
     "the existence of money and exchange", "government control of prices", "the abolition of foreign trade", "the size of a country's army",
     "A", "A person can concentrate on one occupation only if he can exchange his output or wages for the other things he needs."),
    # ---------------- Production ----------------
    (T_PROD, "Easy", "In commerce, production is regarded as complete only when goods",
     "reach the final consumer", "leave the factory gate", "are stored in a warehouse", "are advertised on television",
     "A", "Production is the creation of utility, and utility is not fully realised until the goods are in the hands of the consumer."),
    (T_PROD, "Medium", "A farmer harvests cassava, a processor turns it into garri, a transporter carries it to the city, and a retailer sells it. The transporter and the retailer are",
     "engaged in tertiary production", "not producers because they make nothing",
     "engaged in primary production", "engaged in secondary production",
     "A", "Tertiary production consists of the services (transport, trade, banking) that bring goods to the consumer."),
    (T_PROD, "Easy", "Production creates form, place, time and possession utility. Storing yams from harvest until the lean season creates",
     "time utility", "form utility", "place utility", "possession utility",
     "A", "Making goods available at the time they are wanted creates time utility."),
    (T_PROD, "Easy", "A carpenter turning planks into chairs creates",
     "form utility", "time utility", "place utility", "possession utility",
     "A", "Changing the form of a material to make it more useful creates form utility."),
    (T_PROD, "Easy", "When a retailer sells a phone to a customer and hands it over, the utility created is",
     "possession utility", "form utility", "time utility", "place utility",
     "A", "Transferring ownership of goods to the person who wants them creates possession utility."),
    (T_PROD, "Medium", "Which of the following is an example of indirect production?",
     "a tailor sewing clothes to sell to the public", "a woman cooking dinner for her own family",
     "a man building a hut for himself on his farm", "a boy fetching water for his own bath",
     "A", "Indirect production is production for exchange; direct production is producing for one's own use."),
    (T_PROD, "Easy", "A shoe factory employs one worker to cut leather, another to stitch, another to fix soles and another to polish. This arrangement is",
     "division of labour", "vertical integration", "mass consumption", "diversification",
     "A", "Splitting a job into separate tasks, each done by a different worker, is division of labour."),
    (T_PROD, "Easy", "A disadvantage of division of labour to the worker is that",
     "repeating one small task all day becomes monotonous",
     "output per worker falls sharply over time",
     "the worker must buy all his own tools",
     "the worker can never be replaced by another",
     "A", "Repetitive work causes boredom and loss of pride in the finished product; it also makes workers easy to replace."),
    (T_PROD, "Medium", "Division of labour is limited mainly by",
     "the size of the market for the product", "the height of the factory building",
     "the number of banks in the town", "the age of the factory owner",
     "A", "Specialisation pays only if enough units can be sold; a small market cannot absorb large specialised output."),
    (T_PROD, "Medium", "Large-scale production usually lowers the cost per unit because",
     "fixed costs are spread over a greater number of units",
     "the government pays part of the wages of large firms",
     "large firms do not pay for their raw materials",
     "workers in large firms are never paid overtime",
     "A", "Spreading rent, machinery and management costs over more units gives economies of scale."),
    (T_PROD, "Easy", "A rancher in Adamawa rears cattle, a factory in Kano cans the beef, a trader sells the tins and a lorry carries them to Lagos. The rancher's activity is",
     "primary production", "secondary production", "tertiary production", "indirect production",
     "A", "Primary (extractive) production obtains raw materials and food directly from nature; canning is secondary, trade and transport tertiary."),
    (T_PROD, "Easy", "The stage of production in which raw materials are transformed into finished or semi-finished goods is",
     "secondary production", "primary production", "tertiary production", "direct production",
     "A", "Manufacturing and construction make up secondary production."),
    (T_PROD, "Medium", "A company that grows sugar cane on its own plantation, refines the sugar in its own mill and sells it through its own shops is engaged in",
     "primary, secondary and tertiary production", "primary production only", "tertiary production only", "indirect services only",
     "A", "Growing cane is primary, refining is secondary and retailing is tertiary production."),
    (T_PROD, "Medium", "Mechanisation in production is likely to",
     "increase output and reduce the number of unskilled workers needed",
     "reduce output while increasing the number of workers needed",
     "leave output unchanged but double the cost per unit",
     "make division of labour impossible in the factory",
     "A", "Machines raise output per worker, so fewer hands are needed for the same or greater output."),
    (T_PROD, "Medium", "Which factor is most likely to limit large-scale production of yam flour in a small town?",
     "a small market that cannot absorb the output", "the availability of yams in the area",
     "the presence of a good road to the town", "the existence of a bank in the town",
     "A", "The extent of the market limits the scale of production and of division of labour."),
    # ---------------- Factors of Production ----------------
    (T_FOP, "Medium", "A farmer pays ₦50,000 a year for the use of a plot of land, ₦200,000 in wages to his labourers and ₦30,000 as interest on a bank loan. The three payments are the rewards of",
     "land, labour and capital respectively", "capital, land and labour respectively",
     "labour, capital and land respectively", "entrepreneur, land and capital respectively",
     "A", "Rent is the reward of land, wages of labour and interest of capital; profit is the reward of the entrepreneur."),
    (T_FOP, "Easy", "Which of the following is classified as capital in production?",
     "a tractor used on a farm", "a river used for fishing", "a farmer's own labour", "the sunshine that ripens crops",
     "A", "Capital is man-made wealth used in further production; rivers and sunshine are land (gifts of nature)."),
    (T_FOP, "Easy", "The factor of production that bears the risk of the business and receives profit is",
     "the entrepreneur", "labour", "capital", "land",
     "A", "The entrepreneur organises the other factors, takes decisions and bears the risk of loss in return for profit."),
    (T_FOP, "Easy", "Land as a factor of production includes",
     "all natural resources such as forests, rivers and minerals",
     "only the soil used for growing crops",
     "the buildings erected on a plot by the owner",
     "the money paid to acquire a plot of land",
     "A", "In economics and commerce 'land' means all free gifts of nature, not just the soil."),
    (T_FOP, "Medium", "Mrs Okafor combined ₦2 million of her savings, a rented shop and two employees to start a bakery, taking the risk that it might fail. Mrs Okafor is functioning as",
     "an entrepreneur", "labour", "capital", "land",
     "A", "Combining the factors of production and bearing the risk is the role of the entrepreneur."),
    (T_FOP, "Easy", "A university lecturer's monthly salary is the reward for the factor of production called",
     "labour", "capital", "land", "enterprise",
     "A", "Wages and salaries are the reward for labour, whether physical or mental."),
    (T_FOP, "Medium", "Which feature distinguishes land from the other factors of production?",
     "its total supply is fixed and it is a gift of nature",
     "it can be increased by saving and investment",
     "it is mobile and can be moved from place to place",
     "it receives profit as its reward",
     "A", "Land is geographically immobile, fixed in supply and not man-made; capital is man-made and can be increased."),
    (T_FOP, "Easy", "Capital differs from land in that capital",
     "is man-made and can be increased by saving", "is a free gift of nature",
     "is fixed in total supply", "receives rent as its reward",
     "A", "Capital (machines, buildings, tools) is produced by man and grows when people save and invest."),
    (T_FOP, "Easy", "A bus conductor in Ibadan trains as an electrician and takes a job with a construction firm in the same city. He has shown",
     "occupational mobility of labour", "geographical mobility of labour", "the immobility of labour", "the mobility of capital",
     "A", "Occupational mobility is a change of job or trade; geographical mobility is a change of place."),
    (T_FOP, "Medium", "A skilled machine operator in Kano refuses to accept a better-paid job in Lagos because of family ties. This illustrates a barrier to",
     "geographical mobility of labour", "occupational mobility of labour", "the mobility of capital", "the division of labour",
     "A", "Family ties, housing and language are obstacles to the geographical mobility of labour."),
    (T_FOP, "Medium", "The efficiency of labour can be raised by all of the following EXCEPT",
     "reducing the wages paid to workers", "training and education of workers",
     "good working conditions and welfare", "the use of better tools and machines",
     "A", "Lower wages reduce motivation; training, good conditions and better equipment raise efficiency."),
    (T_FOP, "Easy", "Working capital, as distinct from fixed capital, consists of",
     "cash, stock and debtors used in day-to-day trading", "buildings, machinery and vehicles",
     "land and permanent structures", "the entrepreneur's skill and experience",
     "A", "Working (circulating) capital is used up or changes form in the course of trading; fixed capital is used repeatedly."),
    (T_FOP, "Medium", "Which of the following would be regarded as a factor of production rather than a product of production?",
     "a lorry used by a distributor", "bread sold in a shop", "a shirt bought by a consumer", "a bottle of soft drink",
     "A", "A lorry used in business is capital, a factor of production; the other items are consumer goods."),
    # ---------------- Trade ----------------
    (T_TRADE, "Easy", "Trade is best defined as",
     "the buying and selling of goods and services", "the production of goods in factories",
     "the storage of goods in warehouses", "the transport of goods by road and rail",
     "A", "Trade is exchange; production, storage and transport are industry or aids to trade."),
    (T_TRADE, "Easy", "A Kano trader sells leather bags to a shop in Abuja; another sells the same bags to a shop in Accra, Ghana. The two transactions are, respectively,",
     "home trade and foreign trade", "foreign trade and home trade", "retail trade and wholesale trade", "entrepot trade and home trade",
     "A", "Trade within Nigeria is home trade; a sale to a buyer in Ghana is foreign (export) trade."),
    (T_TRADE, "Easy", "The two main divisions of home trade are",
     "wholesale trade and retail trade", "import trade and export trade",
     "entrepot trade and bilateral trade", "barter trade and credit trade",
     "A", "Home trade is divided into wholesale (selling in bulk to traders) and retail (selling in small units to consumers)."),
    (T_TRADE, "Easy", "Import trade, export trade and entrepot trade are the three divisions of",
     "foreign trade", "home trade", "retail trade", "wholesale trade",
     "A", "Foreign trade consists of import, export and entrepot (re-export) trade; home trade is divided into wholesale and retail."),
    (T_TRADE, "Easy", "Bilateral trade is trade",
     "between two countries only", "among many countries at once",
     "within one country", "between a wholesaler and a retailer",
     "A", "Bilateral means two-sided; multilateral trade involves many countries."),
    (T_TRADE, "Medium", "Under barter, a yam farmer who wants a goat must find a goat owner who wants yams. This difficulty is called",
     "double coincidence of wants", "indivisibility of goods", "lack of a store of value", "absence of deferred payment",
     "A", "Each party must want exactly what the other offers; money removes this difficulty."),
    (T_TRADE, "Easy", "Trade makes it possible for a country to",
     "consume goods it cannot produce itself", "produce everything its people need",
     "avoid the use of money completely", "keep all its goods within its borders",
     "A", "Through trade, countries exchange their surpluses for goods they cannot produce or produce only at high cost."),
    (T_TRADE, "Medium", "Which of the following is NOT a reason why countries trade with one another?",
     "every country can produce all goods at the same cost",
     "differences in climate and natural resources",
     "differences in skills and technology",
     "the desire to sell surplus output abroad",
     "A", "Trade arises precisely because countries differ in resources, skills and costs of production."),
    (T_TRADE, "Easy", "Multilateral trade exists when",
     "many countries trade with one another", "a country trades with one partner only",
     "trade takes place only within a region of a country", "goods are exchanged without the use of money",
     "A", "Multilateral trade involves several countries buying from and selling to one another."),
    (T_TRADE, "Medium", "Counter-trade, in which a country exchanges crude oil directly for machinery from another country, is a modern form of",
     "barter", "hire purchase", "entrepot trade", "retail trade",
     "A", "Exchanging goods directly for goods without money changing hands is barter, even between governments."),
    # ---------------- Home Trade ----------------
    (T_HOME, "Easy", "A retailer wants to know the prices and terms at which a wholesaler will supply goods before placing an order. He should send",
     "a letter of enquiry", "an invoice", "a credit note", "a receipt",
     "A", "The enquiry asks for information; the seller replies with a quotation, catalogue or price list."),
    (T_HOME, "Easy", "In reply to an enquiry, a supplier sends a document stating prices, discounts and delivery terms. This document is",
     "a quotation", "a debit note", "a statement of account", "a delivery note",
     "A", "A quotation states the terms on which the seller is willing to supply the goods."),
    (T_HOME, "Easy", "A buyer who is satisfied with a quotation then sends the seller",
     "an order", "an invoice", "a receipt", "a credit note",
     "A", "The order instructs the seller to supply the goods described at the quoted terms."),
    (T_HOME, "Medium", "A wholesaler under-charged a retailer by ₦5,000 on an invoice. To correct the error he sends",
     "a debit note for ₦5,000", "a credit note for ₦5,000", "a receipt for ₦5,000", "a fresh quotation",
     "A", "A debit note increases the amount the buyer owes; a credit note reduces it."),
    (T_HOME, "Easy", "A document that accompanies goods and is signed by the buyer as proof that the goods were received is",
     "a delivery note", "an advice note", "a consignment note", "an order form",
     "A", "The delivery note lists the goods delivered; the buyer signs a copy which the seller keeps as evidence of delivery."),
    (T_HOME, "Easy", "A supplier sends a note to a customer informing him that goods have been dispatched and should arrive soon. This document is",
     "an advice note", "a delivery note", "a credit note", "an invoice",
     "A", "The advice note is sent ahead of the goods so that the buyer can prepare to receive them."),
    (T_HOME, "Medium", "An invoice bears the letters 'E. & O.E.' This means the seller",
     "may correct any errors or omissions found later", "will not accept the return of the goods",
     "has already received payment in full", "will pay the cost of carriage",
     "A", "'Errors and omissions excepted' reserves the seller's right to correct mistakes on the invoice."),
    (T_HOME, "Easy", "A retailer in Jos receives goods from a Lagos supplier marked 'carriage forward'. When the transporter arrives, the retailer must",
     "pay the transporter the cost of carrying the goods", "refuse the goods until the supplier pays the transporter",
     "return the goods to the supplier at his own expense", "pay the supplier an extra 10% on the invoice",
     "A", "Carriage forward: the buyer pays the transporter on arrival; carriage paid: the seller has already paid."),
    (T_HOME, "Medium", "A price list marked 'ex-warehouse' means the price",
     "excludes the cost of moving the goods from the seller's warehouse",
     "includes delivery to the buyer's own premises",
     "includes insurance and freight to the buyer's town",
     "is only valid if the buyer pays cash on delivery",
     "A", "Ex-warehouse (or ex-works) prices cover the goods only; the buyer arranges and pays for carriage."),
    (T_HOME, "Easy", "A trader who receives a cash discount of 2½% on an invoice of ₦400,000 pays",
     "₦390,000", "₦410,000", "₦380,000", "₦398,000",
     "A", "2½% of ₦400,000 is ₦10,000, so the trader pays ₦390,000.", "390000"),
    (T_HOME, "Easy", "'C.O.D.' on a contract of sale means",
     "the buyer pays when the goods are delivered", "the buyer pays before the goods are sent",
     "the seller allows three months' credit", "the goods are sent free of charge",
     "A", "Cash on delivery: the carrier collects payment when handing over the goods."),
    (T_HOME, "Medium", "'C.W.O.' (cash with order) protects the seller because",
     "he receives payment before releasing the goods", "he can charge interest on the unpaid balance",
     "the buyer must collect the goods himself", "the goods remain his property after delivery",
     "A", "Cash with order means the buyer pays when ordering, so the seller bears no credit risk."),
    (T_HOME, "Medium", "The purpose of a trade discount is to",
     "enable the retailer to sell at the list price and still make a profit",
     "reward the buyer for paying his account promptly",
     "compensate the buyer for goods that arrived damaged",
     "cover the cost of transporting the goods to the buyer",
     "A", "Trade discount is given by a manufacturer or wholesaler to a trader off the list price; the trader's margin lies in that discount."),
    (T_HOME, "Medium", "Unlike a trade discount, a cash discount",
     "is given only when payment is made within a stated period",
     "is deducted on the invoice before the total is calculated",
     "is given to all buyers regardless of when they pay",
     "increases with the quantity of goods bought",
     "A", "Cash discount rewards prompt payment and is deducted at the time of payment, not on the invoice."),
    (T_HOME, "Easy", "A quantity discount is given to a customer who",
     "buys goods in large quantities", "pays for goods in cash", "collects goods from the seller's warehouse", "returns damaged goods",
     "A", "Quantity (bulk) discount encourages large orders, which cut the seller's costs per unit."),
    (T_HOME, "Easy", "A receipt is a document which",
     "acknowledges that payment has been received", "requests payment for goods supplied",
     "corrects an overcharge on an invoice", "lists goods available for sale",
     "A", "The receipt is the buyer's evidence of payment; the invoice requests payment."),
    (T_HOME, "Hard", "A wholesaler sends his customers a document at the end of every month showing the goods supplied, payments received and the balance owing. A retailer who finds the closing balance too high should check it against",
     "the invoices and credit notes received during the month",
     "the supplier's catalogue and current price list",
     "the delivery notes signed by the supplier's driver",
     "the order forms he sent at the start of the month",
     "A", "The statement of account summarises invoices, credit notes and payments; comparing it with those documents reveals any error."),
    (T_HOME, "Medium", "A pharmacy buys drugs with a list price of ₦250,000. The wholesaler allows 20% trade discount and 5% cash discount for payment within 14 days. If the pharmacy pays on the tenth day, the amount paid is",
     "₦190,000", "₦200,000", "₦187,500", "₦237,500",
     "A", "Trade discount: ₦250,000 − 20% = ₦200,000; cash discount: ₦200,000 − 5% = ₦190,000.", "190000"),
    (T_HOME, "Easy", "Which of the following documents is NOT used in home trade?",
     "bill of lading", "invoice", "credit note", "delivery note",
     "A", "The bill of lading is a shipping document used in foreign trade."),
    (T_HOME, "Medium", "A catalogue differs from a price list in that a catalogue",
     "describes and often illustrates the goods, while a price list shows only prices",
     "is sent only to foreign buyers, while a price list is for home buyers",
     "is a binding legal contract, while a price list is not",
     "shows the balance owed by each customer at the end of the month",
     "A", "A catalogue gives descriptions and pictures of goods; a price list simply states current prices."),
    (T_HOME, "Medium", "A buyer received goods worth ₦60,000 that he had not ordered and returned them. The seller should issue",
     "a credit note for ₦60,000", "a debit note for ₦60,000", "an invoice for ₦60,000", "a receipt for ₦60,000",
     "A", "Returns reduce the amount owed by the buyer, and the seller records the reduction on a credit note."),
    (T_HOME, "Easy", "Terms of payment on an invoice read 'Net 30 days'. This means",
     "the full amount is due within 30 days with no discount", "a 30% discount is allowed for prompt payment",
     "payment must be made in 30 monthly instalments", "the goods must be returned within 30 days",
     "A", "'Net' means no further discount; the invoice total must be paid within 30 days."),
    (T_HOME, "Easy", "An invoice serves the buyer chiefly as",
     "a record of the goods bought and the amount owed", "proof that the goods have been paid for",
     "a title document that can be sold to a bank", "an offer that he is free to reject",
     "A", "The invoice shows quantities, prices, discounts and the total due; the receipt is the proof of payment."),
    # ---------------- Foreign Trade ----------------
    (T_FOREIGN, "Easy", "A Nigerian importer of machinery from Germany must usually obtain, before shipment, a document that authorises the importation. This document is",
     "an import licence", "a bill of lading", "a certificate of origin", "a consular invoice",
     "A", "An import licence (or import permit) is the government's authority to bring specified goods into the country."),
    (T_FOREIGN, "Easy", "A document certifying the country in which goods were produced, often needed to claim preferential customs duty within ECOWAS, is",
     "a certificate of origin", "a bill of lading", "an indent", "a charter party",
     "A", "The certificate of origin shows where goods were made, which determines the rate of duty under trade agreements."),
    (T_FOREIGN, "Medium", "An importer in Lagos orders goods through an agent abroad by sending a document that specifies the goods, quantity and price. This document is",
     "an indent", "a bill of sight", "a dock warrant", "a freight note",
     "A", "An indent is an order sent to an agent abroad; it may be open (agent chooses supplier) or closed (supplier named)."),
    (T_FOREIGN, "Medium", "A bill of lading is important to an importer because it",
     "serves as a document of title enabling him to claim the goods from the ship",
     "shows the exchange rate at which the goods were bought",
     "guarantees that the goods are of merchantable quality",
     "exempts the goods from customs duty on arrival",
     "A", "The bill of lading is a receipt, evidence of the contract of carriage and a document of title to the goods."),
    (T_FOREIGN, "Easy", "Goods sent by air are covered by",
     "an airway bill", "a bill of lading", "a charter party", "a mate's receipt",
     "A", "The airway bill is the air-transport equivalent of the bill of lading, though it is not a document of title."),
    (T_FOREIGN, "Easy", "A contract by which an exporter hires a whole ship to carry his cargo is",
     "a charter party", "a bill of lading", "a consular invoice", "a letter of hypothecation",
     "A", "A charter party hires a ship for a voyage or a period of time."),
    (T_FOREIGN, "Medium", "Goods quoted 'F.O.B. Apapa' means the price includes",
     "all costs up to loading the goods on board the ship at Apapa",
     "freight and insurance to the buyer's port of destination",
     "customs duty payable at the port of destination",
     "delivery to the buyer's own warehouse",
     "A", "Free on board: the seller's responsibility ends once the goods are on the ship; the buyer pays freight and insurance."),
    (T_FOREIGN, "Hard", "An importer who has not received full documents and cannot describe the goods exactly may enter them at customs on",
     "a bill of sight", "a bill of entry", "a bill of exchange", "a bill of lading",
     "A", "A bill of sight allows the goods to be examined so that a full entry can be made later."),
    (T_FOREIGN, "Easy", "A ship's manifest is",
     "a list of all the cargo carried by a ship", "a receipt for goods placed in a bonded warehouse",
     "an order to pay the exporter a stated sum", "a licence to import restricted goods",
     "A", "The manifest lists every consignment on board and is presented to customs at the port."),
    (T_FOREIGN, "Easy", "A quota, as an instrument of trade policy, is",
     "a limit on the quantity of a good that may be imported", "a tax on goods brought into the country",
     "a total ban on the import of a good", "a subsidy paid to exporters",
     "A", "A quota restricts quantity; a tariff is a tax; an embargo is a ban."),
    (T_FOREIGN, "Medium", "Which of the following would improve Nigeria's balance of trade?",
     "an increase in exports of cocoa and sesame", "an increase in imports of cars",
     "an increase in Nigerians' holidays abroad", "a fall in the price of crude oil exports",
     "A", "The balance of trade improves when visible exports rise relative to visible imports."),
    (T_FOREIGN, "Easy", "A country's balance of payments records",
     "all its receipts from and payments to other countries in a year",
     "only the value of its visible exports and imports",
     "the total revenue collected by the customs service",
     "the amount of foreign currency held by the central bank",
     "A", "The balance of payments covers visible and invisible trade and capital movements; the balance of trade covers goods only."),
    (T_FOREIGN, "Easy", "Payments for shipping, insurance, tourism and banking services between countries are recorded as",
     "invisible trade", "visible trade", "entrepot trade", "bilateral trade",
     "A", "Services do not pass through customs as goods do, so they are 'invisible' items."),
    (T_FOREIGN, "Medium", "A Nigerian importer agrees to pay a Chinese exporter 90 days after the goods are shipped. The exporter draws a document ordering the importer to pay the sum on that date. This document is",
     "a bill of exchange", "a promissory note", "a letter of credit", "a bank draft",
     "A", "A bill of exchange is an unconditional written order by the creditor requiring the debtor to pay a stated sum at a fixed date."),
    (T_FOREIGN, "Easy", "Dumping occurs when",
     "goods are sold abroad at a price lower than in the home market",
     "imported goods are destroyed by customs officers",
     "goods are stored in a bonded warehouse without paying duty",
     "a country bans the export of raw materials",
     "A", "Dumping is selling exports below the home price or below cost, which can harm producers in the importing country."),
    (T_FOREIGN, "Easy", "Excise duty differs from customs duty in that excise duty is levied on",
     "goods produced within the country", "goods imported into the country",
     "goods exported from the country", "goods passing through the country in transit",
     "A", "Excise duty is charged on home-produced goods such as beer and cigarettes; customs duty on imports and exports."),
    (T_FOREIGN, "Easy", "The main function of the Nigerian Export Promotion Council (NEPC) is to",
     "encourage and assist the export of non-oil products", "collect customs duties on imports at the ports",
     "fix the exchange rate of the naira", "grant import licences to manufacturers",
     "A", "NEPC promotes and develops non-oil exports through incentives, information and training."),
    (T_FOREIGN, "Medium", "A consular invoice is",
     "an invoice certified by the importing country's consul, stating the true value of the goods",
     "a receipt issued by the port authority when goods are landed from a ship",
     "a document showing that freight has been paid in full to the carrier",
     "a bill drawn by the exporter on the importer's bank for the price",
     "A", "The consul's certification helps the importing country's customs to assess duty correctly and prevent dumping."),
    (T_FOREIGN, "Medium", "Which of the following is an invisible export of Nigeria?",
     "fees earned by Nigerian banks from foreign customers", "cocoa sold to the Netherlands",
     "crude oil sold to India", "cars imported from Japan",
     "A", "Services sold to foreigners earn foreign exchange without goods leaving the country; they are invisible exports."),
    (T_FOREIGN, "Medium", "The Economic Community of West African States (ECOWAS) promotes trade among members mainly by",
     "removing tariffs and other barriers on goods produced within the region",
     "fixing a single price for all goods sold in West Africa",
     "banning trade between members and countries outside the region",
     "printing a common currency that is already used in every member state",
     "A", "The ECOWAS Trade Liberalisation Scheme allows qualifying goods to move among member states free of duty."),
    (T_FOREIGN, "Hard", "An 'ex-ship' price quoted to an importer covers",
     "all costs until the goods are available on board at the port of destination",
     "only the cost of the goods at the exporter's own factory gate",
     "the cost of transporting the goods from the port to the buyer's premises",
     "the customs duty payable at the destination port only",
     "A", "Ex-ship: the seller bears all costs and risks until the ship reaches the destination port; unloading and duty are for the buyer."),
    (T_FOREIGN, "Easy", "Goods imported into Nigeria and kept in a bonded warehouse may be re-exported",
     "without payment of import duty", "only after import duty has been paid",
     "only after being processed", "only if they are perishable",
     "A", "Duty is paid only when goods are withdrawn for home use; goods re-exported from bond attract no duty."),
    (T_FOREIGN, "Medium", "Terms of trade refer to",
     "the ratio of a country's export prices to its import prices",
     "the conditions attached to a letter of credit",
     "the discount allowed on a foreign invoice",
     "the period of credit allowed to an importer",
     "A", "Terms of trade improve when export prices rise relative to import prices."),
    (T_FOREIGN, "Easy", "A Nigerian trader who wants to buy goods from a supplier in Brazil finds that the supplier speaks Portuguese, quotes in dollars and follows different commercial laws. These difficulties illustrate",
     "barriers to international trade", "advantages of international trade",
     "aids to international trade", "divisions of international trade",
     "A", "Different currencies, languages, laws and tariffs make foreign trade more difficult than home trade."),
    (T_FOREIGN, "Easy", "A Nigerian exporter receives $20,000 and sells the dollars to his bank at ₦1,500 to $1. He receives",
     "₦30,000,000", "₦3,000,000", "₦300,000,000", "₦15,000,000",
     "A", "$20,000 × ₦1,500 = ₦30,000,000.", "20000*1500"),
    # ---------------- Retail Trade ----------------
    (T_RETAIL, "Easy", "A retailer who moves from street to street selling bread from a tray on his head is",
     "a hawker", "a stall holder", "a mail-order retailer", "a departmental store owner",
     "A", "Hawkers and pedlars are itinerant small-scale retailers with no fixed premises."),
    (T_RETAIL, "Easy", "Which of the following is a function of the retailer to the consumer?",
     "breaking bulk and selling in small quantities convenient to the consumer",
     "manufacturing goods according to the consumer's own specification",
     "providing finance to the manufacturer for large-scale production",
     "storing goods for the wholesaler at the retailer's own expense",
     "A", "The retailer buys in bulk from the wholesaler and sells in units the consumer can afford and use."),
    (T_RETAIL, "Medium", "A small shop owner buys goods on credit from a wholesaler and gives credit to trusted customers in her neighbourhood. This shows that the small-scale retailer",
     "gives personal service and credit that large stores rarely give",
     "always sells at lower prices than large stores",
     "buys directly from foreign manufacturers",
     "does not need any capital to start business",
     "A", "Personal attention, credit and nearness to customers are the main strengths of the small retailer."),
    (T_RETAIL, "Medium", "Small-scale retailers survive in Nigeria despite competition from supermarkets mainly because they",
     "sell in very small units, give credit and are located close to customers",
     "buy directly from foreign manufacturers at lower prices",
     "advertise heavily on radio and television",
     "are exempted by law from paying any taxes",
     "A", "Selling a single cube of seasoning or a sachet of milk near the customer's home meets needs supermarkets do not serve."),
    (T_RETAIL, "Easy", "A retail outlet that sells a wide range of food and household goods on a self-service basis with customers paying at check-out counters is",
     "a supermarket", "a mail-order house", "a mobile shop", "a specialty shop",
     "A", "Supermarkets are large self-service stores selling mainly food and household items."),
    (T_RETAIL, "Easy", "A retailer who sells goods through a catalogue and delivers them by post or courier operates",
     "a mail-order business", "a chain store", "a department store", "a market stall",
     "A", "Mail-order retailers have no shop; customers order from catalogues or online and goods are delivered."),
    (T_RETAIL, "Medium", "A 'multiple shop' (chain store) is characterised by",
     "many branches selling similar goods under centralised buying and control",
     "a single very large building divided into departments",
     "the sale of goods by post from a catalogue",
     "a van that carries goods to villages on market days",
     "A", "Multiple shops have several branches with the same name, layout and goods, controlled from a head office."),
    (T_RETAIL, "Medium", "Under a deferred payment (credit sale) arrangement, unlike hire purchase, the buyer",
     "becomes the owner of the goods immediately, even though he pays by instalments",
     "never becomes the owner of the goods at any stage",
     "must pay the whole price before taking the goods",
     "can return the goods at any time and stop paying",
     "A", "In a credit sale ownership passes at once; under hire purchase it passes only when the last instalment is paid."),
    (T_RETAIL, "Medium", "A furniture shop sells a set costing ₦300,000 cash on hire purchase for a deposit of ₦60,000 and 12 monthly instalments of ₦25,000. The hire-purchase charge is",
     "₦60,000", "₦300,000", "₦360,000", "₦25,000",
     "A", "Total hire-purchase price = ₦60,000 + 12 × ₦25,000 = ₦360,000; charge = ₦360,000 − ₦300,000 = ₦60,000.", "60000"),
    (T_RETAIL, "Hard", "A retailer's mark-up is 25% on cost. Her margin on selling price is",
     "20%", "25%", "12.5%", "33.3%",
     "A", "If cost is 100, selling price is 125 and gross profit 25; margin = 25/125 × 100 = 20%.", "20"),
    (T_RETAIL, "Easy", "Automatic vending machines are most suitable for selling",
     "small standardised goods such as drinks and snacks", "expensive goods such as cars",
     "perishable goods such as fresh fish", "goods that require demonstration",
     "A", "Vending machines sell low-priced, uniform, pre-packed items without a sales assistant."),
    (T_RETAIL, "Medium", "A department store differs from a supermarket in that a department store",
     "sells a wide variety of goods in separate departments, often with personal service",
     "sells goods only by self-service with no attendants at all",
     "sells only foodstuffs and household consumables",
     "operates from a vehicle that moves from place to place",
     "A", "Department stores are 'many shops under one roof' with sales assistants; supermarkets are self-service and food-based."),
    (T_RETAIL, "Easy", "One advantage of large-scale retailing is that",
     "bulk buying earns large trade discounts, allowing lower prices",
     "the owner knows every customer personally",
     "very little capital is needed to start",
     "there is no need for any advertising",
     "A", "Large retailers buy directly from manufacturers in bulk and pass some of the savings to customers."),
    (T_RETAIL, "Easy", "A disadvantage of a department store is that",
     "it needs large capital and high running costs, so prices may be high",
     "it cannot offer more than one type of goods",
     "it is always situated in a village",
     "customers are not allowed to see the goods before buying",
     "A", "Prime city sites, large staff and elaborate buildings make department stores costly to run."),
    (T_RETAIL, "Medium", "The practice of selling a few well-known items at a loss to attract customers who then buy other goods is called",
     "loss-leader pricing", "price skimming", "dumping", "resale price maintenance",
     "A", "The loss leader draws customers into the shop, where profits are made on other purchases."),
    (T_RETAIL, "Medium", "Branding and pre-packaging by manufacturers have reduced the importance of the retailer's function of",
     "weighing, measuring and packing goods for customers", "giving credit to customers",
     "locating the shop near customers", "offering after-sales service",
     "A", "Pre-packed branded goods arrive ready for sale, so the retailer no longer weighs and wraps them."),
    (T_RETAIL, "Medium", "A supermarket turns over its stock 10 times a year and its average stock at cost is ₦150,000. Its cost of goods sold for the year is",
     "₦1,500,000", "₦15,000", "₦150,000", "₦1,650,000",
     "A", "Rate of stock turnover = cost of goods sold ÷ average stock, so cost of goods sold = 10 × ₦150,000 = ₦1,500,000.", "1500000"),
    (T_RETAIL, "Easy", "A discount store is a retail outlet that",
     "sells branded goods below the usual retail price by keeping its costs low",
     "discounts bills of exchange for traders",
     "gives loans to retailers at low interest",
     "sells goods only to members of a club",
     "A", "Discount stores offer few services and simple premises so that they can undercut other retailers."),
    (T_RETAIL, "Medium", "Franchising, as used by fast-food chains, allows the franchisee to",
     "use the franchisor's name, products and methods in return for a fee",
     "own shares in the franchisor's company automatically",
     "sell any goods he likes under his own name",
     "obtain goods free of charge from the franchisor",
     "A", "The franchisee runs his own outlet under the franchisor's brand and system, paying an initial fee and royalties."),
    (T_RETAIL, "Easy", "Which of the following is a common reason for the failure of small retail shops?",
     "poor record-keeping and mixing business money with personal money",
     "too much capital and too many trained staff",
     "buying goods at very large trade discounts",
     "locating the shop close to the customers",
     "A", "Many small traders fail because they draw business cash for private use and keep no proper records."),
    (T_RETAIL, "Medium", "Consumer cooperative shops differ from other retail outlets in that",
     "they are owned by their customers, who share the surplus according to their purchases",
     "they are owned by the government and sell at controlled prices",
     "they sell only to wholesalers and never to consumers",
     "they are owned by manufacturers who sell only their own brands",
     "A", "Members own the shop, each has one vote and the surplus is returned as a patronage dividend."),
    (T_RETAIL, "Easy", "A retailer displays goods attractively in the shop window and arranges them neatly on shelves. The purpose is to",
     "attract customers and increase sales", "reduce the shop's electricity bill",
     "satisfy the requirements of the tax authority", "comply with the Sale of Goods Act",
     "A", "Display is a form of sales promotion at the point of sale."),
    (T_RETAIL, "Medium", "A retailer's selling price for a bag of rice is ₦90,000 and his mark-up is 20% on cost. The cost price is",
     "₦75,000", "₦72,000", "₦108,000", "₦70,000",
     "A", "Selling price = cost × 1.2, so cost = ₦90,000 ÷ 1.2 = ₦75,000.", "90000/1.2"),
    # ---------------- Wholesale Trade ----------------
    (T_WHOLE, "Easy", "A wholesaler helps the retailer chiefly by",
     "breaking bulk and supplying small quantities near the retailer's shop",
     "manufacturing goods to the retailer's specification",
     "advertising the retailer's shop on television",
     "selling directly to the retailer's customers",
     "A", "The wholesaler buys in bulk from many producers and sells smaller lots to retailers, often on credit."),
    (T_WHOLE, "Medium", "A wholesaler's function of holding stock helps to",
     "stabilise prices by releasing goods gradually to the market",
     "increase the price of goods to consumers",
     "reduce the variety of goods available to consumers",
     "eliminate the need for retailers",
     "A", "By storing goods when supply is high and releasing them when it is low, wholesalers even out prices."),
    (T_WHOLE, "Medium", "A manufacturer of sugar can plan production evenly through the year although demand is seasonal because",
     "wholesalers buy and store the sugar until it is needed",
     "consumers buy sugar only in December",
     "retailers pay in advance for a year's supply",
     "the government fixes the price of sugar",
     "A", "Wholesalers relieve the manufacturer of storage and allow continuous production."),
    (T_WHOLE, "Easy", "Cash-and-carry wholesalers differ from traditional wholesalers in that they",
     "sell only for cash and do not deliver goods to retailers",
     "give long credit and free delivery to retailers",
     "sell directly to final consumers only",
     "operate only in foreign trade",
     "A", "Retailers pay cash and carry the goods away themselves, so prices are lower."),
    (T_WHOLE, "Medium", "A wholesaler who takes possession of goods and sells them on behalf of a manufacturer for a commission, without owning them, is",
     "a factor", "a merchant wholesaler", "a rack jobber", "a retailer",
     "A", "A factor is an agent who holds the goods and may sell in his own name; a merchant wholesaler buys and owns the goods."),
    (T_WHOLE, "Medium", "A rack jobber is a wholesaler who",
     "supplies and services display racks in supermarkets and is paid for goods actually sold",
     "sells goods to farmers only in rural markets",
     "exports goods on behalf of the government",
     "buys goods at auction for resale abroad",
     "A", "Rack jobbers stock and maintain racks of specialised goods in retail stores, which pay only for what is sold."),
    (T_WHOLE, "Easy", "The wholesaler passes information about consumer preferences from retailers to",
     "manufacturers", "customs officers", "bankers", "insurers",
     "A", "As the link between retailers and producers, the wholesaler tells manufacturers what consumers want."),
    (T_WHOLE, "Hard", "Which of the following situations makes the elimination of the wholesaler possible?",
     "a manufacturer producing goods to the order of a few large retailers",
     "a manufacturer producing very small quantities of many different goods",
     "goods being bought by thousands of small scattered retailers",
     "goods that need to be stored for a long time before sale",
     "A", "Large retailers buying directly in bulk can perform the wholesaler's functions themselves."),
    (T_WHOLE, "Easy", "A wholesaler who imports goods and sells them to retailers in the home country is",
     "an import merchant", "an export merchant", "a retailer", "a broker",
     "A", "Import merchants buy goods abroad in their own name and distribute them to home retailers."),
    (T_WHOLE, "Easy", "When a manufacturer sells directly to consumers through his own retail shops, the wholesaler is",
     "eliminated", "given more work", "paid a higher commission", "converted into a retailer",
     "A", "Direct selling by the producer cuts out both the independent wholesaler and the independent retailer."),
    (T_WHOLE, "Medium", "A wholesaler buys 500 cartons of milk at a list price of ₦8,000 per carton with a trade discount of 15% and sells them at ₦9,000 per carton. His gross profit is",
     "₦1,100,000", "₦500,000", "₦600,000", "₦1,000,000",
     "A", "Cost = 500 × ₦8,000 × 0.85 = ₦3,400,000; sales = 500 × ₦9,000 = ₦4,500,000; gross profit = ₦1,100,000.", "1100000"),
    (T_WHOLE, "Medium", "Which of the following is an advantage of the wholesaler to the manufacturer?",
     "the wholesaler finances the manufacturer by paying promptly for goods bought in bulk",
     "the wholesaler sells the goods at a loss so as to increase demand for them",
     "the wholesaler makes the goods on behalf of the manufacturer",
     "the wholesaler prevents retailers from selling the goods",
     "A", "Prompt payment for large quantities gives the manufacturer working capital to continue production."),
    (T_WHOLE, "Easy", "A wholesaler who specialises in one line of goods, such as pharmaceuticals, is called",
     "a specialist wholesaler", "a general wholesaler", "a retailer", "a broker",
     "A", "General wholesalers handle many lines; specialist wholesalers concentrate on one class of goods."),
    (T_WHOLE, "Easy", "Which of the following is NOT a function of the wholesaler?",
     "manufacturing goods for retailers", "warehousing goods", "grading and packaging goods", "giving credit to retailers",
     "A", "Wholesalers distribute goods; they do not manufacture them."),
    (T_WHOLE, "Easy", "A wholesaler prepares, grades and packs kolanuts into standard sizes before selling them to retailers. This function is",
     "preparing goods for sale", "breaking bulk", "risk bearing", "financing the producer",
     "A", "Grading, blending, packing and branding make goods ready for retail sale."),
    (T_WHOLE, "Medium", "A wholesaler bears risk on behalf of the manufacturer when",
     "goods he has bought fall in price or go out of fashion before he sells them",
     "the manufacturer raises the price of goods after delivery",
     "the retailer buys directly from the manufacturer",
     "the government reduces import duty on the goods",
     "A", "Having bought and paid for the goods, the wholesaler bears the risk of price falls, deterioration and changes in fashion."),
    # ---------------- Channels of Distribution ----------------
    (T_CHAN, "Easy", "The most common channel for the distribution of consumer goods such as detergent is",
     "manufacturer to wholesaler to retailer to consumer", "manufacturer directly to consumer",
     "manufacturer to retailer to wholesaler to consumer", "wholesaler to manufacturer to retailer to consumer",
     "A", "Mass-produced consumer goods normally pass through both a wholesaler and a retailer."),
    (T_CHAN, "Medium", "A cement company appoints Mr Dike to sell its cement in Anambra; he never buys the cement himself but receives 2% of every sale he arranges. Mr Dike is",
     "an agent", "a merchant wholesaler", "a retailer", "a consumer",
     "A", "Agents sell on behalf of a principal for commission without taking ownership; merchant wholesalers buy and own what they sell."),
    (T_CHAN, "Easy", "A middleman in the channel of distribution is",
     "any person or firm between the producer and the final consumer",
     "a worker in the middle of an assembly line",
     "a manager who supervises junior staff",
     "the customer who buys goods for his own use",
     "A", "Wholesalers, retailers, agents and brokers are middlemen."),
    (T_CHAN, "Easy", "A manufacturer of industrial machinery is most likely to sell",
     "directly to the industrial users", "through hawkers", "through supermarkets", "through mail order to households",
     "A", "Expensive technical goods bought by few customers are sold directly, often with installation and service."),
    (T_CHAN, "Medium", "Which of the following goods would most likely be distributed through the longest channel?",
     "matches sold in every village in the country", "aircraft sold to airlines",
     "custom-made furniture", "fresh vegetables sold at the farm gate",
     "A", "Cheap, standardised goods bought by millions of scattered consumers pass through several middlemen."),
    (T_CHAN, "Easy", "A factor influencing the choice of a channel of distribution is",
     "the nature of the product, such as whether it is perishable or bulky",
     "the colour of the manufacturer's factory building",
     "the number of banks in the country",
     "the age of the managing director",
     "A", "Perishability, value, bulk, the size of the market and the resources of the producer determine the channel."),
    (T_CHAN, "Hard", "Elimination of middlemen may NOT reduce the price to the consumer because",
     "the functions of the middlemen still have to be performed by someone at a cost",
     "consumers generally prefer to pay higher prices",
     "the government fixes the prices of all goods",
     "middlemen do not charge for their services",
     "A", "Storage, bulk breaking, transport and credit remain necessary; whoever performs them incurs the cost."),
    (T_CHAN, "Easy", "Farmers who sell their tomatoes to consumers at a roadside stall are using",
     "a direct (zero-level) channel", "a two-level channel", "a three-level channel", "an agent channel",
     "A", "No middleman stands between producer and consumer, so the channel is direct."),
    (T_CHAN, "Medium", "A broker in the channel of distribution",
     "brings buyer and seller together for a commission without handling the goods",
     "buys goods in bulk and stores them in his warehouse",
     "manufactures goods for sale to wholesalers",
     "transports goods from the factory to the retailer",
     "A", "Unlike a factor, a broker does not take possession of the goods; he negotiates the deal."),
    (T_CHAN, "Medium", "An advantage of selling through wholesalers rather than directly to retailers is that the manufacturer",
     "deals with fewer customers and so reduces selling and distribution costs",
     "receives a higher price per unit from wholesalers",
     "no longer needs to advertise the product",
     "can stop producing goods for stock",
     "A", "A few large orders from wholesalers are cheaper to handle than thousands of small retail orders."),
    (T_CHAN, "Easy", "A company sells its products through its website and delivers by courier to customers' homes. The channel used is",
     "direct selling through e-commerce", "a channel through wholesalers",
     "a channel through agents and brokers", "an entrepot channel",
     "A", "Online sales from producer to consumer bypass all middlemen."),
    (T_CHAN, "Medium", "A del credere agent is one who",
     "guarantees payment for goods sold on credit in return for extra commission",
     "sells goods by public auction to the highest bidder",
     "clears imported goods through customs for a fee",
     "insures goods against loss while in transit",
     "A", "The del credere agent bears the risk of the buyer's default and earns a higher commission for it."),
    (T_CHAN, "Medium", "Multi-level (network) marketing distributes products through",
     "independent distributors who recruit other distributors and earn commissions",
     "government-owned shops in every state",
     "wholesalers who sell only to supermarkets",
     "auctions held in the manufacturer's factory",
     "A", "Each distributor sells directly and earns commission on sales made by those he recruits."),
    (T_CHAN, "Easy", "A brewery appoints key distributors in each state who buy from it in bulk and supply bars and shops. In the channel of distribution the key distributors act as",
     "wholesalers", "retailers", "consumers", "manufacturers",
     "A", "They buy in bulk from the producer and sell to retailers, which is the wholesaler's role."),
    # ---------------- Transportation ----------------
    (T_TRANS, "Easy", "A pharmaceutical company must deliver vaccines that need to be kept cold to clinics scattered across a state within a day. The most suitable means is",
     "refrigerated road vans", "rail wagons", "inland waterways", "pipeline",
     "A", "Road transport reaches scattered destinations door to door, and refrigerated vans keep the cold chain."),
    (T_TRANS, "Easy", "Which of the following is an advantage of road transport over rail transport?",
     "it provides door-to-door delivery", "it carries bulky goods more cheaply over long distances",
     "it is less affected by weather and traffic", "it causes fewer accidents",
     "A", "Lorries can collect and deliver anywhere there is a road; trains are confined to the track."),
    (T_TRANS, "Easy", "Sea transport is most suitable for",
     "bulky, heavy goods that are not urgently needed", "perishable goods needed within hours",
     "urgent business documents", "passengers travelling within a city",
     "A", "Ships carry huge loads cheaply but slowly."),
    (T_TRANS, "Medium", "A tramp ship differs from a liner in that a tramp",
     "has no fixed route or timetable and goes wherever cargo is available",
     "sails on a fixed route according to a published timetable",
     "carries only passengers and mail",
     "operates only on inland rivers",
     "A", "Tramps are chartered as cargo is offered; liners run scheduled services."),
    (T_TRANS, "Easy", "The document issued by a road haulage firm acknowledging receipt of goods for carriage is",
     "a consignment note", "a bill of lading", "a charter party", "an airway bill",
     "A", "The consignment note is the road (or rail) carrier's receipt and contract of carriage."),
    (T_TRANS, "Medium", "Containerisation has benefited international trade mainly by",
     "reducing handling time, pilferage and damage to goods",
     "increasing the number of dock workers needed",
     "making it impossible to carry small consignments",
     "eliminating the need for ships",
     "A", "Sealed standard containers move from lorry to ship to train without the goods being handled."),
    (T_TRANS, "Easy", "The main disadvantage of air transport is that",
     "it is expensive and unsuitable for bulky, low-value goods", "it is the slowest means of transport",
     "it cannot cross national borders", "it cannot carry perishable goods",
     "A", "High freight rates and limited capacity confine air freight to light, valuable or urgent goods."),
    (T_TRANS, "Medium", "An advantage of pipelines over road tankers for moving petroleum products is that pipelines",
     "operate continuously at low running cost once built", "can carry any type of goods including solids",
     "need no capital to construct", "can be moved easily to a new route",
     "A", "Pipelines cost much to build but move liquids and gas cheaply, safely and continuously."),
    (T_TRANS, "Easy", "Which of the following factors is LEAST important in choosing a means of transport?",
     "the colour of the goods", "the cost of carriage", "the urgency of delivery", "the nature of the goods",
     "A", "Cost, speed, safety, nature of goods and distance matter; colour does not."),
    (T_TRANS, "Easy", "Inland waterways such as the River Niger are useful for transporting",
     "bulky goods cheaply between riverside towns", "urgent medical supplies",
     "passengers in a hurry", "goods to towns far from any river",
     "A", "River transport is slow and limited to navigable rivers but very cheap for heavy loads."),
    (T_TRANS, "Easy", "Transport creates",
     "place utility by moving goods to where they are wanted", "form utility by changing the shape of goods",
     "time utility by storing goods", "possession utility by advertising goods",
     "A", "Moving goods from where they are produced to where they are demanded adds place utility."),
    (T_TRANS, "Medium", "A haulage company charges by weight and distance. Which of the following is a fixed cost to the company?",
     "the annual insurance premium on its lorries", "fuel used on each trip",
     "drivers' allowances per trip", "toll fees paid on each journey",
     "A", "Insurance, licences and depreciation are paid whether or not the lorries move; fuel and tolls vary with trips."),
    (T_TRANS, "Medium", "The transport of goods by rail in Nigeria is limited mainly by",
     "the limited network and poor condition of many tracks", "the high speed of trains",
     "the low carrying capacity of wagons", "the door-to-door service rail provides",
     "A", "Few lines, old tracks and irregular services restrict rail freight."),
    (T_TRANS, "Easy", "Which of the following is an advantage of rail transport?",
     "it carries heavy and bulky goods over long distances at relatively low cost",
     "it provides door-to-door service to every village",
     "it is the fastest means of transport available",
     "it can change its route to avoid traffic jams",
     "A", "Trains carry large tonnages of cement, grain and containers cheaply over long distances."),
    (T_TRANS, "Medium", "A freight forwarder assists an exporter by",
     "arranging transport, documentation and customs clearance of goods",
     "manufacturing the goods for export",
     "buying the goods and reselling them abroad",
     "insuring the exporter's factory against fire",
     "A", "Forwarding agents specialise in moving goods through ports and borders on behalf of shippers."),
    (T_TRANS, "Easy", "The Nigerian Ports Authority (NPA) is responsible for",
     "managing seaports and providing port facilities", "operating all the airlines in Nigeria",
     "constructing federal highways", "issuing driving licences",
     "A", "NPA manages the ports, quays and harbours through which sea-borne trade passes."),
    (T_TRANS, "Easy", "Roll-on roll-off (Ro-Ro) vessels are designed to carry",
     "vehicles that are driven on and off the ship", "crude oil in bulk", "passengers only", "liquefied gas",
     "A", "Ro-Ro ships have ramps so that cars and lorries can be driven aboard."),
    (T_TRANS, "Easy", "For a trader whose goods have a high value in relation to their weight, such as jewellery, the most suitable means of transport is",
     "air transport", "sea transport", "rail transport", "pipeline",
     "A", "Air freight is costly per kilogram, but fast and secure, so it suits light, valuable goods."),
    (T_TRANS, "Easy", "Which of the following is a disadvantage of sea transport?",
     "it is slow and unsuitable for highly perishable goods", "it cannot carry bulky goods",
     "it is the most expensive means of transport", "it cannot be used for international trade",
     "A", "Voyages take weeks, so fresh goods must go by air or in refrigerated ships."),
    (T_TRANS, "Easy", "Transport helps to widen the market for goods because it",
     "enables goods to be sold far from where they are produced", "reduces the quantity of goods produced",
     "prevents goods from leaving the factory", "raises the price of goods in the local market",
     "A", "Cheap, reliable transport lets producers reach distant customers and so expands the market."),
    (T_TRANS, "Easy", "The Federal Road Safety Corps (FRSC) contributes to transport in Nigeria by",
     "enforcing road traffic rules and reducing accidents", "building railway lines",
     "operating the airports", "collecting customs duty at the ports",
     "A", "FRSC regulates road use, issues driver's licences and promotes road safety."),
    # ---------------- Communication ----------------
    (T_COMM, "Easy", "A company needs to inform 5,000 customers across the country of a change in prices at low cost within a day. The most suitable means is",
     "bulk SMS or e-mail", "registered post", "personal visits by sales staff", "telegram",
     "A", "Electronic messages reach thousands of people instantly at very low cost."),
    (T_COMM, "Easy", "Which of the following is a means of oral communication?",
     "telephone", "e-mail", "letter", "fax",
     "A", "The telephone carries the spoken word; the others are written communication."),
    (T_COMM, "Medium", "A courier service differs from the ordinary postal service in that a courier",
     "collects and delivers door-to-door, usually faster but at a higher charge",
     "delivers items only within a single city and never between states",
     "is always owned and operated by the federal government",
     "carries letters only and does not accept parcels of any size",
     "A", "Couriers offer speed, tracking and door-to-door service for a premium price."),
    (T_COMM, "Easy", "Video conferencing enables a firm to",
     "hold meetings with people in different places without travelling", "send goods to customers in other towns",
     "store goods in distant warehouses", "print documents in colour",
     "A", "Participants see and hear one another over the internet, saving travel time and cost."),
    (T_COMM, "Easy", "The internet has helped commerce mainly by",
     "making it possible to advertise, order and pay for goods online", "removing the need for transport of goods",
     "abolishing customs duties on imports", "eliminating all risks in business",
     "A", "E-commerce, online advertising and electronic payments all depend on the internet."),
    (T_COMM, "Easy", "Which of the following is a mass communication medium?",
     "television", "telephone", "letter", "memo",
     "A", "Mass media such as television, radio and newspapers reach large audiences at once."),
    (T_COMM, "Easy", "A memorandum (memo) is used for",
     "written communication within an organisation", "communication with foreign suppliers only",
     "advertising to the general public", "paying for goods bought online",
     "A", "Memos pass information between departments or staff inside a firm."),
    (T_COMM, "Easy", "The Nigerian Communications Commission (NCC) is responsible for",
     "regulating telecommunications services in Nigeria", "delivering letters and parcels",
     "printing newspapers", "operating radio stations",
     "A", "NCC licenses and regulates telephone and internet service providers."),
    (T_COMM, "Medium", "A business sends an important legal document by registered post rather than ordinary post because",
     "registered post provides proof of posting and compensation if the item is lost",
     "registered post costs less than ordinary post for every item sent",
     "ordinary post is not permitted to carry legal documents of any kind",
     "registered post is always delivered by air within the same day",
     "A", "Registration records the item at every stage and the sender obtains a receipt."),
    (T_COMM, "Easy", "Communication in business is important because it",
     "enables buyers and sellers to exchange information about goods, prices and orders",
     "removes the need for money in exchange",
     "converts raw materials into finished goods",
     "guarantees profit to every trader",
     "A", "Enquiries, quotations, orders and complaints all depend on effective communication."),
    (T_COMM, "Easy", "Which of the following is an example of visual communication?",
     "a chart or poster", "a telephone call", "a radio jingle", "a voice note",
     "A", "Charts, posters, signs and pictures communicate through sight."),
    (T_COMM, "Easy", "A telephone call to a supplier has an advantage over a letter in that it",
     "gets an immediate response", "provides a permanent written record",
     "is always cheaper", "cannot be misunderstood",
     "A", "Speech allows instant two-way discussion; a letter provides the record."),
    (T_COMM, "Medium", "Barriers to effective communication in business include",
     "the use of technical jargon and poor listening", "clear language and prompt feedback",
     "short messages and good timing", "the use of the receiver's own language",
     "A", "Jargon, noise, poor listening and wrong choice of medium prevent messages from being understood."),
    (T_COMM, "Easy", "NIPOST is the government agency responsible for",
     "postal services in Nigeria", "telecommunications regulation", "television broadcasting", "internet banking",
     "A", "The Nigerian Postal Service handles mail, postal orders and related services."),
    (T_COMM, "Easy", "An e-mail differs from a letter sent by post in that an e-mail",
     "is delivered electronically within seconds to any part of the world", "always requires a postage stamp",
     "cannot carry attachments", "must be handwritten",
     "A", "E-mail travels over the internet almost instantly and can carry documents and pictures."),
    # ---------------- Warehousing ----------------
    (T_WARE, "Easy", "A warehouse owned by a manufacturer and used to store his own goods is",
     "a private warehouse", "a public warehouse", "a bonded warehouse", "a state warehouse",
     "A", "Private warehouses belong to the firm whose goods they hold."),
    (T_WARE, "Easy", "A trader who does not own a warehouse but rents space to store goods for a fee uses",
     "a public warehouse", "a private warehouse", "a factory warehouse", "a retail shop",
     "A", "Public warehouses let space to any trader who pays the charges."),
    (T_WARE, "Medium", "An importer cannot pay duty on a large consignment at once. To avoid the goods being seized he should",
     "keep the goods in a bonded warehouse and pay duty as he withdraws them",
     "sell the goods immediately at the port",
     "return the goods to the exporter",
     "keep the goods in his own private warehouse",
     "A", "Bonded warehouses hold dutiable goods under customs control until duty is paid on the portion withdrawn."),
    (T_WARE, "Medium", "Goods in a bonded warehouse may be",
     "re-packed, blended or labelled under customs supervision",
     "sold to consumers without paying duty",
     "removed at any time without customs permission",
     "stored free of charge by the government",
     "A", "Owners may prepare goods for sale in bond, but nothing leaves for home use until duty is paid."),
    (T_WARE, "Easy", "Warehousing helps to stabilise prices because",
     "goods stored can be released gradually to match demand", "goods in a warehouse cannot be sold",
     "warehouses increase the cost of production", "warehouses reduce the quantity of goods available",
     "A", "Storage prevents gluts at harvest and shortages later, keeping prices steadier."),
    (T_WARE, "Easy", "Which of the following goods most requires a cold-storage warehouse?",
     "frozen fish", "cement", "textiles", "iron rods",
     "A", "Perishable foods must be kept at low temperature to prevent spoilage."),
    (T_WARE, "Medium", "A warehouse keeper issues a document to the owner of goods deposited, which can be transferred to a buyer as evidence of ownership. This document is",
     "a warehouse warrant", "a bill of lading", "a credit note", "an invoice",
     "A", "A warehouse (or dock) warrant is a document of title to goods in store."),
    (T_WARE, "Easy", "Warehousing enables producers of seasonal goods such as rice to",
     "make the goods available to consumers throughout the year", "sell all the rice on the day of harvest",
     "avoid the use of transport", "sell only to the government",
     "A", "Storage bridges the gap between the harvest season and year-round consumption."),
    (T_WARE, "Easy", "Which of the following is NOT a function of a warehouse?",
     "manufacturing goods for sale", "protecting goods from theft and weather",
     "enabling bulk breaking", "storing goods until they are needed",
     "A", "Warehouses store, protect and prepare goods; they do not produce them."),
    (T_WARE, "Medium", "A wholesaler's warehouse close to a city helps retailers because",
     "they can replenish their stock quickly in small quantities", "they no longer need to keep any stock",
     "they can buy directly from foreign suppliers", "they are exempted from paying for the goods",
     "A", "Nearby stocks let retailers buy little and often, reducing their own storage needs."),
    (T_WARE, "Easy", "State (government) warehouses are usually located",
     "at ports and airports for goods awaiting customs clearance", "in every village market",
     "inside supermarkets", "in private homes",
     "A", "Government warehouses at ports hold imported goods until they are cleared."),
    (T_WARE, "Medium", "A firm that keeps large stocks in its warehouse incurs",
     "storage costs and the risk of goods deteriorating or going out of fashion",
     "no costs at all until the goods are sold",
     "lower insurance premiums than firms with no stock",
     "customs duty on locally produced goods",
     "A", "Stock ties up capital and attracts rent, insurance and the risk of loss in value."),
    (T_WARE, "Easy", "Modern warehouses use computers and barcodes mainly to",
     "keep accurate records of stock received and issued", "produce the goods stored",
     "advertise goods to consumers", "collect taxes for the government",
     "A", "Computerised stock control shows what is in store, where it is and when to reorder."),
    (T_WARE, "Easy", "Warehousing and transport are complementary because",
     "goods must be stored while awaiting transport and after arrival before sale",
     "goods can only be transported by the warehouse owner",
     "transport is never needed once goods are stored",
     "warehouses replace the need for transport",
     "A", "Transport moves goods between points; warehouses hold them at those points until they are needed."),
]

FIX = {
    "refines the sugar in its own mill and sells it through its own shops is engaged in": (
        "primary, secondary and tertiary production",
        "primary production at every stage of the process",
        "tertiary production at every stage of the process",
        "indirect services at every stage of the process"),
    "Capital differs from land in that capital": (
        "is man-made and can be increased by saving",
        "is a free gift of nature to every producer",
        "is fixed in total supply for all time",
        "receives rent as its reward for production"),
    "Which of the following is an invisible export of Nigeria?": (
        "fees earned by Nigerian banks from foreign customers",
        "cocoa beans sold by Nigerian farmers to the Netherlands",
        "crude oil sold by Nigeria to refineries in India",
        "second-hand cars imported into Nigeria from Japan"),
    "unlike hire purchase, the buyer": (
        "becomes the owner of the goods immediately, even though he pays by instalments",
        "never becomes the owner of the goods at any stage of the payment period",
        "must pay the whole price in cash before he is allowed to take the goods",
        "can return the goods at any time and stop paying the remaining instalments"),
    "One advantage of large-scale retailing is that": (
        "bulk buying earns large trade discounts, allowing lower prices",
        "the owner knows every customer personally and gives them credit",
        "very little capital is needed to start and run the business",
        "there is no need for any advertising or window display at all"),
    "have reduced the importance of the retailer's function of": (
        "weighing, measuring and packing goods for customers",
        "giving credit to regular customers who are known to him",
        "locating the shop close to where the customers live",
        "offering after-sales service on the goods he sells"),
    "A discount store is a retail outlet that": (
        "sells branded goods below the usual retail price by keeping its costs low",
        "discounts bills of exchange for traders who need cash before maturity",
        "gives loans to small retailers at rates of interest below the bank rate",
        "sells goods only to registered members who pay a yearly subscription"),
    "common reason for the failure of small retail shops?": (
        "poor record-keeping and mixing business money with personal money",
        "too much capital and too many trained staff for the size of the shop",
        "buying goods at very large trade discounts from the wholesalers",
        "locating the shop close to the customers in a residential area"),
    "A rack jobber is a wholesaler who": (
        "stocks and services display racks in supermarkets and is paid for goods actually sold",
        "sells goods to farmers only in rural markets on the days the markets are held",
        "exports goods on behalf of the government and is paid a fixed commission",
        "buys goods at public auction for resale to retailers in other countries"),
    "Elimination of middlemen may NOT reduce the price to the consumer because": (
        "the functions of the middlemen still have to be performed by someone at a cost",
        "consumers generally prefer to pay higher prices for goods that pass through middlemen",
        "the government fixes the prices of all goods whether or not middlemen are used",
        "middlemen do not charge anything for the services they render to producers"),
    "Multi-level (network) marketing distributes products through": (
        "independent distributors who recruit other distributors and earn commissions",
        "government-owned shops in every state, which sell only at controlled prices",
        "wholesalers who sell only to supermarkets and never to small retailers",
        "auctions held in the manufacturer's factory at the end of every month"),
    "The main disadvantage of air transport is that": (
        "it is expensive and unsuitable for bulky, low-value goods",
        "it is the slowest means of transport for goods and passengers",
        "it cannot cross national borders without a customs escort",
        "it cannot carry perishable goods such as flowers and fish"),
    "Which of the following is an advantage of rail transport?": (
        "it carries heavy and bulky goods over long distances at relatively low cost",
        "it provides door-to-door service to every village and hamlet in the country",
        "it is the fastest means of transport available for urgent consignments",
        "it can change its route at any time to avoid traffic jams and bad roads"),
    "Roll-on roll-off (Ro-Ro) vessels are designed to carry": (
        "vehicles that are driven on and off the ship",
        "crude oil pumped in and out of the ship",
        "passengers who board by ladder from boats",
        "liquefied gas kept under great pressure"),
    "Video conferencing enables a firm to": (
        "hold meetings with people in different places without travelling",
        "send goods to customers in other towns without using a transporter",
        "store goods in distant warehouses without paying any rent",
        "print documents in colour in any office it chooses"),
    "The internet has helped commerce mainly by": (
        "making it possible to advertise, order and pay for goods online",
        "removing the need for transport of goods from producer to consumer",
        "abolishing customs duties on all goods imported into the country",
        "eliminating all the risks that traders face in doing business"),
    "The Nigerian Communications Commission (NCC) is responsible for": (
        "regulating telecommunications services in Nigeria",
        "delivering letters and parcels throughout Nigeria",
        "printing and distributing newspapers in Nigeria",
        "operating the federal radio stations in Nigeria"),
    "Communication in business is important because it": (
        "enables buyers and sellers to exchange information about goods, prices and orders",
        "removes the need for money in the exchange of goods between buyers and sellers",
        "converts raw materials into finished goods that can be sold to the consumers",
        "guarantees a profit to every trader who takes part in buying and selling"),
    "An e-mail differs from a letter sent by post in that an e-mail": (
        "is delivered electronically within seconds to any part of the world",
        "always requires a postage stamp before it can be sent to the receiver",
        "cannot carry attachments such as documents, pictures or videos",
        "must be handwritten and signed by the sender before it is sent"),
    "To avoid the goods being seized he should": (
        "keep the goods in a bonded warehouse and pay duty as he withdraws them",
        "sell the goods immediately at the port to any buyer who offers cash",
        "return the goods to the exporter and ask for his money to be refunded",
        "keep the goods in his own private warehouse until he can pay the duty"),
    "State (government) warehouses are usually located": (
        "at ports and airports for goods awaiting customs clearance",
        "in every village market for goods awaiting sale",
        "inside supermarkets for goods awaiting display",
        "in private homes for goods awaiting delivery"),
    "Modern warehouses use computers and barcodes mainly to": (
        "keep accurate records of stock received and issued",
        "produce the goods that are stored in the warehouse",
        "advertise the stored goods to consumers on television",
        "collect taxes from traders on behalf of the government"),
}


def build():
    build_batch(
        S, "batch_030_commerce_round3a.json", "batch_030_commerce_round3a",
        "Commerce round 3 (part A): introduction to commerce, occupation, production, factors of production, trade, home trade and business documents, foreign trade, retail and wholesale trade, channels of distribution, transportation, communication and warehousing - scenario items with an invoice passage and a balance-of-payments passage.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
