"""Batch 017 - Chemistry round 4: takes Chemistry past the 500 curated-question mark.

Two short data passages (gas-law readings and a rates/energy profile table) plus ~180 stand-alone
applied items across all fifteen JAMB Chemistry topics.

    python3 scripts/build_content_batch17.py -> content/batch_017_chemistry_round4.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Chemistry"

PASSAGES = [
    ("C5", "Chemical Reactions", "Reaction of iron filings with copper(II) tetraoxosulphate(VI)",
     "Excess iron filings were added to 100 cm³ of 0.50 mol/dm³ copper(II) tetraoxosulphate(VI) "
     "solution in a beaker and stirred until the blue colour disappeared. The temperature and "
     "the mass of solid in the beaker were recorded. (Fe = 56, Cu = 64)\n\n"
     "Reading                      Value\n"
     "Initial temperature (°C)      27.0\n"
     "Final temperature (°C)        34.5\n"
     "Mass of iron added (g)        5.60\n"
     "Mass of solid at end (g)      6.00"),
    ("C6", "Acids Bases and Salts", "pH of some household and laboratory solutions",
     "The pH of several solutions was measured with a pH meter at 25 °C. The results are shown "
     "below.\n\n"
     "Solution                    pH\n"
     "Lime juice                  2.2\n"
     "Rain water                  5.6\n"
     "Pure water                  7.0\n"
     "Baking soda solution        8.4\n"
     "Household bleach           12.5"),
]

PQ = [
    ("C5", "Medium", "In the experiment above, the blue colour of the solution disappeared because",
     "the copper(II) ions were reduced to copper metal by the iron", "the iron filings absorbed the blue dye from the solution", "the tetraoxosulphate(VI) ions were destroyed by the iron", "the solution evaporated as the temperature rose", "A",
     "Fe(s) + Cu²⁺(aq) → Fe²⁺(aq) + Cu(s): the blue Cu²⁺ ions are replaced by pale green Fe²⁺ ions and reddish-brown copper is deposited."),
    ("C5", "Medium", "In the experiment above, the number of moles of copper(II) ions that reacted was",
     "0.005", "0.05", "0.5", "5.0", "B",
     "n = C × V = 0.50 × 100/1,000 = 0.05 mol.", "0.5*100/1000"),
    ("C5", "Hard", "From the experiment above, the mass of iron that dissolved was",
     "0.4 g", "2.8 g", "3.2 g", "5.6 g", "B",
     "One mole of iron reacts per mole of Cu²⁺: 0.05 × 56 = 2.8 g of iron dissolved.", "0.05*56"),
    ("C5", "Hard", "In the experiment above, the mass of solid at the end (6.00 g) is greater than the mass of iron added because",
     "the iron rusted and gained oxygen from the air", "each 56 g of iron dissolved was replaced by 64 g of copper deposited", "water of crystallisation was absorbed by the iron", "the tetraoxosulphate(VI) crystallised out on the iron", "B",
     "2.8 g of iron dissolved but 0.05 × 64 = 3.2 g of copper was deposited; 5.60 − 2.8 + 3.2 = 6.00 g."),
    ("C5", "Easy", "The rise in temperature recorded in the experiment above shows that the reaction is",
     "endothermic", "exothermic", "reversible", "a neutralisation", "B",
     "Heat is given out to the solution, raising its temperature from 27.0 °C to 34.5 °C, so the reaction is exothermic."),
    ("C5", "Medium", "In the reaction studied above, iron acts as",
     "the oxidising agent", "the reducing agent", "a catalyst", "an acid", "B",
     "Iron loses electrons (Fe → Fe²⁺ + 2e⁻) and gives them to the copper(II) ions, so it is oxidised and is the reducing agent."),
    ("C6", "Easy", "From the table above, the solution with the highest hydrogen ion concentration is",
     "lime juice", "rain water", "baking soda solution", "household bleach", "A",
     "The lower the pH, the higher the hydrogen ion concentration; lime juice (pH 2.2) is the most acidic."),
    ("C6", "Medium", "From the table above, the ratio of the hydrogen ion concentration in rain water to that in pure water is approximately",
     "1.4 : 1", "25 : 1", "1 : 25", "5.6 : 7", "B",
     "pH 5.6 → [H⁺] = 10⁻⁵·⁶ = 2.5 × 10⁻⁶; pH 7 → 10⁻⁷; ratio = 10¹·⁴ ≈ 25 : 1.", "10**1.4"),
    ("C6", "Medium", "Rain water in the table above has a pH below 7 because it contains dissolved",
     "oxygen from the air", "carbon(IV) oxide forming a weak acid", "sodium chloride from the sea", "ammonia from decaying matter", "B",
     "CO₂ + H₂O ⇌ H₂CO₃, a weak acid, so even unpolluted rain is slightly acidic (about pH 5.6)."),
    ("C6", "Medium", "Methyl orange is red below pH 3.1 and yellow above pH 4.4. From the table above, the solutions in which methyl orange would appear yellow are",
     "lime juice and rain water only", "rain water and pure water only", "all the solutions except lime juice", "baking soda solution and bleach only", "C",
     "Every solution in the table except lime juice (pH 2.2) has a pH above 4.4, so methyl orange is yellow in rain water, pure water, baking soda solution and bleach."),
    ("C6", "Medium", "From the table above, the hydroxide ion concentration in household bleach is approximately",
     "1.0 × 10⁻¹² mol/dm³", "3.2 × 10⁻² mol/dm³", "12.5 mol/dm³", "1.0 × 10⁻⁷ mol/dm³", "B",
     "pOH = 14 − 12.5 = 1.5, so [OH⁻] = 10⁻¹·⁵ = 3.2 × 10⁻² mol/dm³.", "round(10**-1.5*100,1)"),
    ("C6", "Easy", "Baking soda solution (pH 8.4 in the table above) is used to relieve acid indigestion because it",
     "is a strong alkali that destroys the stomach lining", "neutralises excess hydrochloric acid in the stomach", "dissolves the food in the stomach more quickly", "lowers the pH of the stomach contents further", "B",
     "Sodium hydrogentrioxocarbonate(IV) is a mild base: NaHCO₃ + HCl → NaCl + H₂O + CO₂."),
]

Q = [
    # ---------------- States of Matter ----------------
    ("States of Matter", "Medium", "A balloon filled with 2.0 dm³ of helium at 27 °C and 1.0 atm rises to a height where the temperature is −23 °C and the pressure 0.5 atm. Its volume there is",
     "1.0 dm³", "3.3 dm³", "4.0 dm³", "8.0 dm³", "B",
     "V₂ = V₁ × (P₁/P₂) × (T₂/T₁) = 2.0 × (1.0/0.5) × (250/300) = 3.3 dm³.", "round(2*(1/0.5)*(250/300),1)"),
    ("States of Matter", "Medium", "Ammonia and hydrogen chloride gases are released at the same time from opposite ends of a 1 m glass tube. The white ring of ammonium chloride forms",
     "exactly in the middle of the tube", "nearer the hydrogen chloride end", "nearer the ammonia end", "at the ammonia end itself", "B",
     "Ammonia (M = 17) diffuses faster than hydrogen chloride (M = 36.5), so it travels further before the gases meet."),
    ("States of Matter", "Hard", "50 cm³ of oxygen diffuses through a porous pot in 40 s. The time for 50 cm³ of a gas of relative molecular mass 128 to diffuse under the same conditions is (O₂ = 32)",
     "20 s", "80 s", "160 s", "10 s", "B",
     "Rate ∝ 1/√M, so time ∝ √M: t = 40 × √(128/32) = 40 × 2 = 80 s.", "40*math.sqrt(128/32)"),
    ("States of Matter", "Easy", "The smell of perfume opened at one end of a room soon reaches the other end. This is because the perfume molecules",
     "are attracted by the walls of the room", "diffuse through the air by random motion", "are carried only by the light in the room", "react with the air to form a gas", "B",
     "Gas molecules move randomly and spread from where they are concentrated to where they are not — diffusion."),
    ("States of Matter", "Medium", "A cylinder of fixed volume contains a gas at 2.0 atm and 27 °C. The temperature at which the pressure becomes 3.0 atm is",
     "40.5 °C", "177 °C", "450 °C", "327 °C", "B",
     "P/T is constant: T₂ = 300 × 3.0/2.0 = 450 K = 177 °C.", "300*3/2-273"),
    ("States of Matter", "Medium", "Which of the following statements about real gases is correct?",
     "they behave most ideally at high pressure and low temperature", "they behave most ideally at low pressure and high temperature", "their molecules have zero volume at all temperatures", "there are no forces at all between their molecules", "B",
     "At low pressure the molecules are far apart, and at high temperature they move too fast for the weak attractions to matter, so the ideal-gas assumptions nearly hold."),
    ("States of Matter", "Medium", "Naphthalene balls kept in a wardrobe gradually become smaller and disappear without leaving a liquid. This is because naphthalene",
     "melts and then evaporates very quickly", "sublimes directly from solid to vapour", "dissolves in the moisture of the air", "decomposes into gases on standing", "B",
     "Sublimation is the direct change from solid to gas; iodine and ammonium chloride behave similarly."),
    ("States of Matter", "Hard", "A chemist finds that 112 cm³ of an unknown gas, measured at s.t.p., has a mass of 0.16 g. The gas is most likely (molar volume = 22,400 cm³; H = 1, C = 12, O = 16, S = 32)",
     "methane, CH₄", "oxygen, O₂", "carbon(IV) oxide, CO₂", "sulphur(IV) oxide, SO₂", "B",
     "Moles = 112/22,400 = 0.005; M = 0.16/0.005 = 32, the relative molecular mass of oxygen."),
    ("States of Matter", "Medium", "Crystals of copper(II) tetraoxosulphate(VI) are best obtained from its solution by",
     "boiling the solution to dryness over a strong flame", "evaporating the solution to saturation and allowing it to cool slowly", "filtering the solution through fine filter paper", "adding a large volume of cold water and stirring", "B",
     "Slow cooling of a saturated solution gives large, well-formed crystals; boiling to dryness gives a powder and drives off water of crystallisation."),
    ("States of Matter", "Medium", "A liquid boils at 80 °C at sea level. On a high mountain where the atmospheric pressure is lower, it boils at",
     "80 °C", "a temperature below 80 °C", "a temperature above 80 °C", "100 °C", "B",
     "A liquid boils when its vapour pressure equals the external pressure; a lower external pressure is reached at a lower temperature."),
    ("States of Matter", "Easy", "Which of the following mixtures can be separated by using a separating funnel?",
     "ethanol and water", "kerosene and water", "salt and water", "sand and salt", "B",
     "Kerosene and water are immiscible liquids that form two layers; the lower layer is run off through the tap."),
    ("States of Matter", "Medium", "Which of the following is a chemical change?",
     "dissolving sugar in water", "rusting of an iron nail", "melting of candle wax", "magnetising an iron rod", "B",
     "Rusting produces a new substance (hydrated iron(III) oxide) and cannot easily be reversed; the others are physical changes."),
    ("States of Matter", "Medium", "Salt is separated from a solution of salt in water by evaporation rather than by filtration because",
     "salt particles are too heavy to be held back by filter paper", "dissolved salt particles are too small to be trapped by filter paper", "filter paper dissolves in salt solution", "evaporation is always faster than filtration", "B",
     "A true solution contains ions or molecules that pass straight through filter paper; only insoluble solids are filtered off."),
    # ---------------- Atomic Structure ----------------
    ("Atomic Structure", "Medium", "An element has two isotopes, ⁶³X (69%) and ⁶⁵X (31%). Its relative atomic mass is approximately",
     "63.3", "63.6", "64.0", "64.4", "B",
     "RAM = (63 × 0.69) + (65 × 0.31) = 43.47 + 20.15 = 63.6.", "63*0.69+65*0.31"),
    ("Atomic Structure", "Medium", "The species ⁴⁰₁₈Ar, ⁴⁰₂₀Ca²⁺ and ³⁹₁₉K⁺ all have the same",
     "number of protons", "number of electrons", "number of neutrons", "mass number", "B",
     "Ar has 18 electrons; Ca²⁺ has 20 − 2 = 18; K⁺ has 19 − 1 = 18. They are isoelectronic."),
    ("Atomic Structure", "Medium", "The maximum number of electrons that can occupy the third shell (n = 3) of an atom is",
     "8", "18", "32", "6", "B",
     "The maximum is 2n² = 2 × 3² = 18 (the 3s, 3p and 3d sub-shells together).", "18"),
    ("Atomic Structure", "Hard", "Which of the following electronic configurations represents an atom in an excited state?",
     "1s² 2s² 2p⁶ 3s¹", "1s² 2s² 2p⁵ 3s¹", "1s² 2s² 2p⁶", "1s² 2s² 2p³", "B",
     "In 1s² 2s² 2p⁵ 3s¹ an electron occupies 3s while 2p is still incomplete; the ground state of that atom (neon) would be 1s² 2s² 2p⁶."),
    ("Atomic Structure", "Medium", "The atomic number of an element is 24. The number of electrons in its 3d sub-shell is",
     "4", "5", "6", "2", "B",
     "Chromium is exceptional: its configuration is [Ar] 3d⁵ 4s¹, a half-filled d sub-shell being especially stable.", "5"),
    ("Atomic Structure", "Medium", "The energy of an electron in an atom is lowest when the electron is in the",
     "outermost shell", "shell nearest the nucleus", "3d sub-shell", "4s sub-shell", "B",
     "Electrons closest to the nucleus are most strongly attracted and have the lowest (most negative) energy."),
    ("Atomic Structure", "Medium", "Which of the following statements about cathode rays is correct?",
     "they are positively charged and heavy", "they are streams of electrons, deflected towards a positive plate", "they are electromagnetic waves like light", "they cannot be deflected by a magnetic field", "B",
     "Thomson showed that cathode rays are negatively charged particles (electrons) with the same charge-to-mass ratio whatever gas or cathode metal is used."),
    ("Atomic Structure", "Medium", "A nuclide ²²⁶₈₈X emits an alpha particle and the daughter nuclide then emits a beta particle. The final nuclide has",
     "atomic number 86 and mass number 222", "atomic number 87 and mass number 222", "atomic number 85 and mass number 222", "atomic number 88 and mass number 226", "B",
     "Alpha emission: 88 → 86, 226 → 222; beta emission then raises the atomic number to 87 with the mass number unchanged."),
    ("Atomic Structure", "Medium", "Which of the following radiations has the greatest penetrating power?",
     "alpha particles", "beta particles", "gamma rays", "protons", "C",
     "Gamma rays are high-energy electromagnetic waves stopped only by thick lead or concrete; alpha particles are stopped by paper."),
    ("Atomic Structure", "Hard", "A radioactive element has a half-life of 30 minutes. The time taken for its activity to fall to 12.5% of its original value is",
     "60 min", "90 min", "120 min", "240 min", "B",
     "12.5% = 1/8 = (½)³, three half-lives: 3 × 30 = 90 minutes.", "3*30"),
    ("Atomic Structure", "Medium", "Nuclear fission differs from ordinary chemical reactions in that fission",
     "involves only the outermost electrons of the atoms", "changes one element into different elements", "releases far less energy per atom", "never produces radiation of any kind", "B",
     "In fission the nucleus itself splits into nuclei of lighter elements; chemical reactions rearrange electrons and leave every nucleus unchanged."),
    ("Atomic Structure", "Medium", "The number of protons, neutrons and electrons in the ion ³²₁₆S²⁻ are respectively",
     "16, 16, 14", "16, 16, 18", "16, 32, 18", "18, 16, 16", "B",
     "Protons = 16; neutrons = 32 − 16 = 16; the 2− charge means two extra electrons: 16 + 2 = 18."),
    # ---------------- Periodic Table ----------------
    ("Periodic Table", "Medium", "Elements A, B, C and D have atomic numbers 8, 11, 16 and 17 respectively. The pair of elements with the most similar chemical properties is",
     "A and B", "A and C", "B and D", "C and D", "B",
     "A (2,6) and C (2,8,6) both have six outer electrons and belong to Group 6; B (2,8,1) is in Group 1 and D (2,8,7) in Group 7."),
    ("Periodic Table", "Medium", "Going down Group 7 (the halogens), the elements change at room temperature from",
     "solid to gas", "gas to liquid to solid", "liquid to gas", "gas directly to solid", "B",
     "Fluorine and chlorine are gases, bromine is a liquid and iodine is a solid; van der Waals forces increase with molecular size."),
    ("Periodic Table", "Medium", "The first ionisation energies of Na, Mg and Al are 496, 738 and 578 kJ/mol. The value for aluminium is lower than that for magnesium because",
     "aluminium has a smaller nuclear charge than magnesium", "the outer electron of aluminium is in a 3p orbital, further from the nucleus and shielded by the 3s electrons", "aluminium is a metal while magnesium is a non-metal", "aluminium atoms are much larger than magnesium atoms", "B",
     "Al: [Ne] 3s² 3p¹; the 3p electron is higher in energy and more easily removed than one of the paired 3s electrons of Mg."),
    ("Periodic Table", "Easy", "Which of the following elements is a noble gas?",
     "nitrogen", "chlorine", "argon", "hydrogen", "C",
     "Argon (Group 0) has a complete outer shell of eight electrons and is chemically inert."),
    ("Periodic Table", "Medium", "The oxides of period 3 elements change across the period from",
     "acidic to basic", "basic to amphoteric to acidic", "amphoteric to basic", "neutral to basic", "B",
     "Na₂O and MgO are basic, Al₂O₃ is amphoteric, and SiO₂, P₄O₁₀, SO₃ and Cl₂O₇ are acidic."),
    ("Periodic Table", "Medium", "An element forms a chloride of formula XCl₂ and an oxide XO that dissolves in water to give an alkaline solution. X is most likely",
     "aluminium", "calcium", "carbon", "sulphur", "B",
     "A metal of Group 2 forms a +2 ion; CaO dissolves in water to give calcium hydroxide (lime water)."),
    ("Periodic Table", "Medium", "Element X (atomic number 19) and element Y (atomic number 35) combine to form a compound. The formula and bond type of the compound are",
     "XY, covalent", "XY, ionic", "X₂Y, ionic", "XY₂, covalent", "B",
     "X is potassium (Group 1, forms X⁺) and Y is bromine (Group 7, forms Y⁻); they form the ionic compound KBr."),
    ("Periodic Table", "Medium", "Which of the following ions has the smallest ionic radius?",
     "Na⁺", "Mg²⁺", "Al³⁺", "F⁻", "C",
     "All four are isoelectronic (10 electrons); Al³⁺ has the greatest nuclear charge (13) pulling the same electrons closest."),
    ("Periodic Table", "Medium", "A group of elements have the electronic configurations ns² np⁵. They",
     "readily lose one electron to form positive ions", "readily gain one electron to form negative ions", "are inert and form no compounds", "form ions with a charge of 2+", "B",
     "One electron short of a full shell, these halogens gain an electron to form X⁻ ions."),
    ("Periodic Table", "Hard", "The elements of period 3 in order of increasing electronegativity are",
     "Na < Mg < Al < Si < P < S < Cl", "Cl < S < P < Si < Al < Mg < Na", "Na < Al < Mg < Si < S < P < Cl", "Ar < Cl < S < P < Si < Al < Mg", "A",
     "Electronegativity rises across a period as the nuclear charge increases and the atomic radius shrinks; argon is not assigned a value."),
    ("Periodic Table", "Medium", "Which pair of elements would react most violently with each other?",
     "sodium and chlorine", "magnesium and oxygen", "caesium and fluorine", "lithium and iodine", "C",
     "Caesium is the most reactive common metal (largest atom, outer electron most easily lost) and fluorine the most reactive non-metal."),
    ("Periodic Table", "Medium", "Transition elements are able to act as catalysts mainly because they",
     "are very dense and have high melting points", "can exist in several oxidation states", "form only colourless compounds", "have completely filled d sub-shells", "B",
     "Variable oxidation states let a transition metal accept and donate electrons readily, providing an alternative reaction path (e.g. Fe in the Haber process, V₂O₅ in the Contact process)."),
    # ---------------- Chemical Bonding ----------------
    ("Chemical Bonding", "Medium", "Magnesium oxide has a much higher melting point (2,852 °C) than sodium chloride (801 °C) because",
     "Mg²⁺ and O²⁻ ions carry double charges, so the electrostatic attraction in the lattice is much stronger", "magnesium oxide is covalent while sodium chloride is ionic", "sodium chloride contains water of crystallisation", "magnesium oxide molecules are much heavier than sodium chloride molecules", "A",
     "Lattice energy increases with the product of the ionic charges; (2+)(2−) gives roughly four times the attraction of (1+)(1−)."),
    ("Chemical Bonding", "Medium", "Which of the following molecules is linear?",
     "H₂O", "CO₂", "NH₃", "CH₄", "B",
     "Carbon in CO₂ has two double bonds and no lone pairs, so the molecule is linear (O=C=O, 180°)."),
    ("Chemical Bonding", "Medium", "The bond angle in methane, CH₄, is",
     "90°", "104.5°", "107°", "109.5°", "D",
     "Four bonding pairs and no lone pairs around carbon repel equally, giving a regular tetrahedron with 109.5° angles.", "109.5"),
    ("Chemical Bonding", "Medium", "The bond angle in water (104.5°) is smaller than that in ammonia (107°) because",
     "oxygen is a bigger atom than nitrogen", "water has two lone pairs which repel the bonding pairs more strongly", "water has more hydrogen atoms than ammonia", "the O–H bond is longer than the N–H bond", "B",
     "Lone pair–lone pair repulsion is greater than lone pair–bond pair repulsion, so the two lone pairs on oxygen squeeze the bonds closer."),
    ("Chemical Bonding", "Medium", "Which of the following substances is held together by van der Waals forces only?",
     "sodium chloride", "solid carbon(IV) oxide (dry ice)", "diamond", "copper", "B",
     "Dry ice consists of separate CO₂ molecules attracted only by weak intermolecular forces, which is why it sublimes at −78 °C."),
    ("Chemical Bonding", "Medium", "Hydrogen chloride is a covalent gas, yet its aqueous solution conducts electricity because",
     "the gas contains free ions even before it dissolves", "water molecules pull the HCl molecules apart into H₃O⁺ and Cl⁻ ions", "water itself is a good conductor of electricity", "chlorine atoms lose electrons to the water", "B",
     "The polar H–Cl bond breaks heterolytically in water: HCl + H₂O → H₃O⁺ + Cl⁻, and the mobile ions carry the current."),
    ("Chemical Bonding", "Easy", "Tetrachloromethane (CCl₄) does not dissolve in water because",
     "it is a non-polar molecule while water is polar", "its molecules are too heavy to mix with water", "it reacts violently with water", "it is an ionic compound", "A",
     "Water's hydrogen bonds are not compensated by any attraction to the non-polar CCl₄ molecules, so the two liquids do not mix."),
    ("Chemical Bonding", "Medium", "Which of the following contains a coordinate (dative covalent) bond?",
     "H₂O", "NH₄⁺", "NaCl", "Cl₂", "B",
     "In NH₄⁺ the nitrogen lone pair forms the fourth N–H bond by donating both electrons to a proton."),
    ("Chemical Bonding", "Medium", "The electron-pair geometry around the central atom in ammonia is tetrahedral, but the molecule is described as pyramidal because",
     "one of the four positions is occupied by a lone pair, which is not counted in the shape", "nitrogen can only form three bonds at right angles", "the three hydrogen atoms lie in the same plane as nitrogen", "the N–H bonds are double bonds", "A",
     "Shape describes the positions of atoms only; the lone pair sits at one tetrahedral corner, leaving a trigonal pyramid of atoms with 107° angles."),
    ("Chemical Bonding", "Medium", "Which of the following pairs of elements would form a covalent compound?",
     "sodium and chlorine", "magnesium and oxygen", "carbon and hydrogen", "potassium and bromine", "C",
     "Two non-metals with similar electronegativities share electrons; the other pairs are metal + non-metal and form ionic compounds."),
    ("Chemical Bonding", "Medium", "Ethanol (C₂H₅OH) is soluble in water but hexane (C₆H₁₄) is not. This is because ethanol",
     "has a lower relative molecular mass than hexane", "can form hydrogen bonds with water molecules through its –OH group", "is an ionic compound while hexane is covalent", "has a higher boiling point than hexane", "B",
     "The polar –OH group hydrogen-bonds with water; hexane has only non-polar C–H and C–C bonds."),
    ("Chemical Bonding", "Medium", "Which of the following properties is characteristic of a metallic bond?",
     "electrons are transferred from one atom to another", "electrons are shared between pairs of atoms", "positive ions are held in a sea of delocalised electrons", "the bond is formed only between two different elements", "C",
     "The mobile electrons account for the conductivity, lustre and malleability of metals."),
    # ---------------- Mole Concept and Stoichiometry ----------------
    ("Mole Concept and Stoichiometry", "Medium", "The volume of 0.20 mol/dm³ hydrochloric acid that contains 0.73 g of HCl is (HCl = 36.5)",
     "50 cm³", "100 cm³", "200 cm³", "20 cm³", "B",
     "Moles = 0.73/36.5 = 0.02; volume = 0.02/0.20 = 0.1 dm³ = 100 cm³.", "0.73/36.5/0.2*1000"),
    ("Mole Concept and Stoichiometry", "Hard", "A sample of hydrated sodium tetraoxosulphate(VI), Na₂SO₄·xH₂O, of mass 3.22 g gave 1.42 g of the anhydrous salt on heating. The value of x is (Na₂SO₄ = 142, H₂O = 18)",
     "5", "7", "10", "12", "C",
     "Anhydrous salt: 1.42/142 = 0.01 mol; water lost: 1.80/18 = 0.10 mol; ratio 1 : 10, so x = 10.", "(3.22-1.42)/18/(1.42/142)"),
    ("Mole Concept and Stoichiometry", "Medium", "The mass of silver deposited by the same quantity of electricity that deposits 3.2 g of copper is (Cu = 64, Ag = 108)",
     "5.4 g", "10.8 g", "21.6 g", "2.7 g", "B",
     "3.2 g Cu = 0.05 mol, needing 0.1 mol of electrons; Ag⁺ + e⁻ → Ag, so 0.1 mol = 10.8 g of silver.", "3.2/64*2*108"),
    ("Mole Concept and Stoichiometry", "Hard", "10 cm³ of a gaseous hydrocarbon required 30 cm³ of oxygen for complete combustion and produced 20 cm³ of carbon(IV) oxide (all volumes at the same temperature and pressure). The hydrocarbon is",
     "CH₄", "C₂H₄", "C₂H₆", "C₃H₈", "B",
     "Gay-Lussac: CₓHᵧ + 3O₂ → 2CO₂ + …; 2 carbons use 2 O₂ for CO₂, the remaining O₂ forms 2H₂O, so y = 4: C₂H₄."),
    ("Mole Concept and Stoichiometry", "Medium", "The number of ions in 0.5 mol of aluminium chloride, AlCl₃, when fully dissociated is (Avogadro's number = 6.0 × 10²³)",
     "3.0 × 10²³", "6.0 × 10²³", "1.2 × 10²⁴", "2.4 × 10²³", "C",
     "Each formula unit gives 4 ions (1 Al³⁺ + 3 Cl⁻): 0.5 × 4 × 6.0 × 10²³ = 1.2 × 10²⁴.", "0.5*4*6/10"),
    ("Mole Concept and Stoichiometry", "Medium", "50 cm³ of 0.1 mol/dm³ NaOH is added to 50 cm³ of 0.1 mol/dm³ H₂SO₄. The resulting solution is",
     "neutral", "acidic, because half of the acid remains unreacted", "alkaline, because the base is in excess", "acidic, because sodium tetraoxosulphate(VI) is an acid salt", "B",
     "H₂SO₄ needs 2 mol of NaOH per mole; 0.005 mol of NaOH neutralises only 0.0025 mol of the 0.005 mol of acid present."),
    ("Mole Concept and Stoichiometry", "Medium", "The relative molecular mass of a gas that has a vapour density of 32 is",
     "16", "32", "64", "128", "C",
     "Relative molecular mass = 2 × vapour density = 64.", "2*32"),
    ("Mole Concept and Stoichiometry", "Medium", "When 0.1 mol of a metal M reacted with excess acid, 2,240 cm³ of hydrogen was liberated at s.t.p. The valency of M is (molar volume = 22.4 dm³)",
     "1", "2", "3", "4", "B",
     "2,240 cm³ = 0.1 mol H₂ = 0.2 mol of H atoms displaced by 0.1 mol of M, so each atom of M supplies 2 electrons: valency 2.", "2"),
    ("Mole Concept and Stoichiometry", "Medium", "The mass of oxygen gas that contains the same number of molecules as 14 g of nitrogen gas is (N = 14, O = 16)",
     "8 g", "14 g", "16 g", "32 g", "C",
     "14 g of N₂ = 0.5 mol; 0.5 mol of O₂ = 0.5 × 32 = 16 g.", "14/28*32"),
    ("Mole Concept and Stoichiometry", "Hard", "In the reaction 2Al + 3Cl₂ → 2AlCl₃, 5.4 g of aluminium is mixed with 14.2 g of chlorine. The limiting reagent and the mass of AlCl₃ formed are (Al = 27, Cl = 35.5)",
     "chlorine; 17.8 g", "aluminium; 26.7 g", "chlorine; 26.7 g", "aluminium; 17.8 g", "A",
     "Al = 0.2 mol, Cl₂ = 14.2/71 = 0.2 mol; 0.2 mol Cl₂ needs only 0.133 mol Al, so chlorine runs out first and gives 0.2 × 2/3 = 0.133 mol AlCl₃ = 0.133 × 133.5 = 17.8 g.", "14.2/71*2/3*133.5"),
    ("Mole Concept and Stoichiometry", "Medium", "The concentration in g/dm³ of a 0.25 mol/dm³ solution of potassium hydroxide is (KOH = 56)",
     "7 g/dm³", "14 g/dm³", "28 g/dm³", "56 g/dm³", "B",
     "Concentration in g/dm³ = molar concentration × molar mass = 0.25 × 56 = 14 g/dm³.", "0.25*56"),
    ("Mole Concept and Stoichiometry", "Medium", "How many moles of hydrogen atoms are present in 0.25 mol of ethanol, C₂H₅OH?",
     "0.25", "1.5", "6", "3", "B",
     "Each molecule of C₂H₆O contains 6 hydrogen atoms: 0.25 × 6 = 1.5 mol.", "0.25*6"),
    # ---------------- Acids, Bases and Salts ----------------
    ("Acids Bases and Salts", "Medium", "Which of the following statements describes a strong acid?",
     "an acid with a very high concentration", "an acid that is completely ionised in aqueous solution", "an acid that reacts quickly with all metals", "an acid whose solution has a pH of about 5", "B",
     "Strength refers to the degree of ionisation, not the concentration; a dilute solution of HCl is still a strong acid."),
    ("Acids Bases and Salts", "Medium", "A 0.1 mol/dm³ solution of ethanoic acid has a pH of about 3 while 0.1 mol/dm³ hydrochloric acid has a pH of 1. Which statement is correct?",
     "ethanoic acid is more concentrated than hydrochloric acid", "ethanoic acid is only slightly ionised in water", "hydrochloric acid is a weaker acid than ethanoic acid", "both acids release the same number of hydrogen ions", "B",
     "The same concentration gives 100 times fewer H⁺ ions in the ethanoic acid solution, showing that only a small fraction of its molecules ionise."),
    ("Acids Bases and Salts", "Medium", "The volume of 0.5 mol/dm³ sodium hydroxide needed to neutralise 25 cm³ of 0.2 mol/dm³ tetraoxosulphate(VI) acid is",
     "5 cm³", "10 cm³", "20 cm³", "40 cm³", "C",
     "Moles of acid = 0.2 × 0.025 = 0.005; NaOH needed = 0.01 mol; volume = 0.01/0.5 = 0.02 dm³ = 20 cm³.", "0.2*25*2/0.5"),
    ("Acids Bases and Salts", "Medium", "Which of the following salts is a normal salt?",
     "NaHCO₃", "KHSO₄", "Na₂SO₄", "Ca(HCO₃)₂", "C",
     "A normal salt has all the replaceable hydrogen of the acid replaced by a metal; the others still contain replaceable hydrogen (acid salts)."),
    ("Acids Bases and Salts", "Medium", "Zinc oxide is described as amphoteric because it",
     "reacts with acids only", "reacts with both acids and alkalis to form salts", "dissolves in water to give a neutral solution", "reacts with neither acids nor alkalis", "B",
     "ZnO + 2HCl → ZnCl₂ + H₂O and ZnO + 2NaOH + H₂O → Na₂Zn(OH)₄; Al₂O₃ and PbO behave similarly."),
    ("Acids Bases and Salts", "Medium", "Which of the following is a basic salt?",
     "Zn(OH)Cl", "NaHSO₄", "KNO₃", "NH₄Cl", "A",
     "A basic salt contains hydroxide or oxide ions as well as the normal anion, e.g. Zn(OH)Cl and Pb(OH)NO₃."),
    ("Acids Bases and Salts", "Medium", "A double salt is exemplified by",
     "potash alum, K₂SO₄·Al₂(SO₄)₃·24H₂O", "sodium chloride, NaCl", "copper(II) tetraoxosulphate(VI), CuSO₄·5H₂O", "calcium trioxocarbonate(IV), CaCO₃", "A",
     "A double salt crystallises from a solution of two simple salts and gives both sets of ions in solution."),
    ("Acids Bases and Salts", "Medium", "A solution of sodium trioxocarbonate(IV) turns red litmus blue although it contains no hydroxide. This is because",
     "trioxocarbonate(IV) ions react with water to form hydroxide ions", "sodium ions are strongly alkaline", "the salt contains free sodium hydroxide", "carbon(IV) oxide gas escapes and leaves an alkali", "A",
     "CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻ (salt hydrolysis) makes the solution alkaline."),
    ("Acids Bases and Salts", "Medium", "Which of the following indicators is most suitable for the titration of a strong acid against a weak base such as ammonia?",
     "phenolphthalein", "methyl orange", "litmus", "starch", "B",
     "The end point of a strong acid–weak base titration is on the acidic side (pH about 5), within the range of methyl orange (3.1–4.4)."),
    ("Acids Bases and Salts", "Easy", "Which of the following oxides is neutral?",
     "carbon(II) oxide", "sulphur(IV) oxide", "calcium oxide", "aluminium oxide", "A",
     "CO (like N₂O and H₂O) reacts with neither acids nor bases; SO₂ is acidic, CaO basic and Al₂O₃ amphoteric."),
    ("Acids Bases and Salts", "Medium", "Anhydrous calcium chloride left in an open dish absorbs moisture from the air and eventually forms a solution. This behaviour is called",
     "efflorescence", "deliquescence", "hygroscopy", "hydrolysis", "B",
     "A deliquescent substance absorbs so much water vapour that it dissolves in it; a hygroscopic substance absorbs moisture without dissolving."),
    ("Acids Bases and Salts", "Medium", "Which of the following is the correct method for diluting concentrated tetraoxosulphate(VI) acid?",
     "pour the water quickly into the concentrated acid", "add the acid slowly to the water while stirring", "mix equal volumes of acid and water in a closed bottle", "heat the acid first and then add the water", "B",
     "Dilution is highly exothermic; adding acid to a large volume of water spreads the heat, whereas water added to acid can boil and spit."),
    ("Acids Bases and Salts", "Medium", "An aqueous solution has a pOH of 3. Its pH and nature are",
     "3, acidic", "11, alkaline", "11, acidic", "3, alkaline", "B",
     "pH + pOH = 14, so pH = 11, which is alkaline.", "14-3"),
    ("Acids Bases and Salts", "Hard", "Lead(II) chloride is prepared by mixing solutions of lead(II) trioxonitrate(V) and sodium chloride. The pure dry salt is obtained by",
     "evaporating the mixture to dryness", "filtering, washing the residue with distilled water and drying it", "distilling off the water and collecting the residue", "crystallising the filtrate by slow cooling", "B",
     "PbCl₂ is insoluble in cold water, so it is filtered off as a precipitate, washed free of soluble NaNO₃ and dried."),
    # ---------------- Chemical Reactions (redox) ----------------
    ("Chemical Reactions", "Medium", "In the reaction Cl₂ + 2KBr → 2KCl + Br₂, chlorine",
     "is reduced and acts as the oxidising agent", "is oxidised and acts as the reducing agent", "is reduced and acts as the reducing agent", "undergoes no change in oxidation number", "A",
     "Cl goes from 0 to −1 (gains electrons, reduced) while Br⁻ is oxidised to Br₂; the substance reduced is the oxidising agent."),
    ("Chemical Reactions", "Medium", "The oxidation number of chlorine in KClO₃ is",
     "+1", "+3", "+5", "+7", "C",
     "K = +1, three O = −6; for a neutral compound Cl = +5.", "5"),
    ("Chemical Reactions", "Medium", "The oxidation number of phosphorus in the tetraoxophosphate(V) ion, PO₄³⁻, is",
     "+3", "+5", "−3", "+8", "B",
     "Four O = −8; the ion charge is −3, so P − 8 = −3 and P = +5.", "5"),
    ("Chemical Reactions", "Medium", "Which of the following reactions is a decomposition reaction?",
     "2Na + Cl₂ → 2NaCl", "2KClO₃ → 2KCl + 3O₂", "Zn + CuSO₄ → ZnSO₄ + Cu", "NaOH + HCl → NaCl + H₂O", "B",
     "A single compound breaks down into two or more simpler substances on heating."),
    ("Chemical Reactions", "Medium", "Hydrogen peroxide acts as a reducing agent in its reaction with",
     "potassium iodide solution, which turns brown", "acidified potassium tetraoxomanganate(VII), which is decolourised", "lead(II) sulphide, which turns white", "iron(II) ions, which turn to iron(III)", "B",
     "H₂O₂ reduces MnO₄⁻ to Mn²⁺ and is itself oxidised to oxygen; in the other cases it oxidises the other reagent."),
    ("Chemical Reactions", "Hard", "In the half-equation Cr₂O₇²⁻ + 14H⁺ + xe⁻ → 2Cr³⁺ + 7H₂O, the value of x is",
     "2", "3", "6", "12", "C",
     "Chromium falls from +6 to +3 for each of the two atoms: 2 × 3 = 6 electrons gained.", "6"),
    ("Chemical Reactions", "Medium", "When a piece of sodium is dropped into water it fizzes and the resulting solution turns red litmus blue. The gas and the solution are respectively",
     "oxygen and sodium oxide", "hydrogen and sodium hydroxide", "hydrogen and sodium trioxocarbonate(IV)", "oxygen and sodium hydroxide", "B",
     "2Na + 2H₂O → 2NaOH + H₂; the alkaline sodium hydroxide turns litmus blue."),
    ("Chemical Reactions", "Medium", "Which of the following equations is correctly balanced?",
     "Fe + O₂ → Fe₂O₃", "4Fe + 3O₂ → 2Fe₂O₃", "2Fe + O₂ → Fe₂O₃", "4Fe + O₂ → 2Fe₂O₃", "B",
     "4 Fe and 6 O atoms on each side: 4Fe + 3O₂ → 2Fe₂O₃."),
    ("Chemical Reactions", "Medium", "The reaction between an acid and a base to form a salt and water only is called",
     "hydrolysis", "neutralisation", "displacement", "decomposition", "B",
     "H⁺(aq) + OH⁻(aq) → H₂O(l) is the essential change in every neutralisation."),
    ("Chemical Reactions", "Medium", "Iron(II) tetraoxosulphate(VI) solution slowly turns from green to yellow-brown on standing in air. This is because",
     "iron(II) ions are oxidised to iron(III) ions by oxygen", "the water evaporates and concentrates the solution", "iron(II) ions are reduced to iron metal", "carbon(IV) oxide in the air forms iron(II) trioxocarbonate(IV)", "A",
     "Fe²⁺ is easily oxidised to Fe³⁺ (yellow-brown) by dissolved oxygen, which is why freshly prepared solution is used in tests."),
    ("Chemical Reactions", "Medium", "A metal M reacts with dilute acid to release hydrogen and its oxide is reduced by hydrogen on heating. M is most likely",
     "sodium", "iron", "copper", "gold", "B",
     "A metal below hydrogen (Cu, Ag, Au) gives no hydrogen with acid; a metal well above (Na, Ca) has an oxide that hydrogen cannot reduce. Iron fits both conditions."),
    ("Chemical Reactions", "Hard", "25 cm³ of 0.02 mol/dm³ acidified KMnO₄ is exactly decolourised by 20 cm³ of an iron(II) solution. The concentration of the iron(II) solution is",
     "0.025 mol/dm³", "0.125 mol/dm³", "0.005 mol/dm³", "0.25 mol/dm³", "B",
     "MnO₄⁻ reacts with 5 Fe²⁺: moles MnO₄⁻ = 0.02 × 0.025 = 0.0005; Fe²⁺ = 0.0025 mol in 20 cm³, so C = 0.0025/0.020 = 0.125 mol/dm³.", "0.02*25*5/20"),
    # ---------------- Electrochemistry ----------------
    ("Electrochemistry", "Medium", "In the electrolysis of dilute tetraoxosulphate(VI) acid with platinum electrodes, the volumes of gas collected at the cathode and anode are in the ratio",
     "1 : 1", "1 : 2", "2 : 1", "4 : 1", "C",
     "Cathode: 4H⁺ + 4e⁻ → 2H₂; anode: 4OH⁻ → O₂ + 2H₂O + 4e⁻; for the same charge, twice as much hydrogen as oxygen."),
    ("Electrochemistry", "Hard", "During the electrolysis of copper(II) tetraoxosulphate(VI) solution with carbon electrodes, the solution gradually becomes",
     "more alkaline as copper is deposited", "acidic, because tetraoxosulphate(VI) acid is left in solution", "a deeper blue as copper ions form", "neutral, with no change in composition", "B",
     "Cu²⁺ is deposited at the cathode and OH⁻ is discharged as O₂ at the anode, leaving H⁺ and SO₄²⁻ ions, i.e. H₂SO₄, so the blue fades and the pH falls."),
    ("Electrochemistry", "Medium", "In the electrolysis of copper(II) tetraoxosulphate(VI) solution with copper electrodes, the anode",
     "gains mass as copper is deposited on it", "loses mass as copper dissolves into the solution", "liberates oxygen gas", "liberates hydrogen gas", "B",
     "At an active copper anode, Cu → Cu²⁺ + 2e⁻ occurs in preference to the discharge of OH⁻; the cathode gains an equal mass."),
    ("Electrochemistry", "Medium", "The mass of aluminium deposited when 3 faradays of electricity are passed through molten aluminium oxide is (Al = 27)",
     "9 g", "27 g", "54 g", "81 g", "B",
     "Al³⁺ + 3e⁻ → Al: 3 F deposits 1 mol = 27 g.", "27"),
    ("Electrochemistry", "Hard", "A current of 2 A is passed through a solution of a metal salt for 32 minutes 10 seconds and 1.28 g of the metal (relative atomic mass 64) is deposited. The charge on the metal ion is (1 F = 96,500 C)",
     "+1", "+2", "+3", "+4", "B",
     "Q = 2 × 1,930 = 3,860 C = 0.04 F; moles deposited = 1.28/64 = 0.02; 0.04/0.02 = 2 electrons per ion.", "2*1930/96500/(1.28/64)"),
    ("Electrochemistry", "Medium", "Which of the following ions is discharged first at the cathode when a mixture of their salts in aqueous solution is electrolysed?",
     "Na⁺", "K⁺", "Cu²⁺", "Ca²⁺", "C",
     "Ions of metals lower in the electrochemical series are discharged in preference; Cu²⁺ is well below H⁺, whereas Na⁺, K⁺ and Ca²⁺ are above it."),
    ("Electrochemistry", "Medium", "The standard hydrogen electrode is assigned a potential of",
     "+1.00 V", "0.00 V", "−1.00 V", "+0.76 V", "B",
     "All other standard electrode potentials are measured relative to the hydrogen electrode at 1 atm, 25 °C and 1 mol/dm³ H⁺.", "0"),
    ("Electrochemistry", "Medium", "A student joins a magnesium rod dipping in Mg²⁺ solution to a silver rod dipping in Ag⁺ solution through a salt bridge and a voltmeter. Given E°(Mg²⁺/Mg) = −2.37 V and E°(Ag⁺/Ag) = +0.80 V, the voltmeter should read",
     "1.57 V", "3.17 V", "−1.57 V", "0.80 V", "B",
     "E°cell = E°cathode − E°anode = 0.80 − (−2.37) = 3.17 V.", "0.80+2.37"),
    ("Electrochemistry", "Medium", "In a zinc–carbon dry cell, the zinc case acts as the",
     "cathode, where reduction occurs", "anode, where zinc is oxidised", "electrolyte", "depolariser", "B",
     "Zinc dissolves as Zn²⁺, releasing electrons (Zn → Zn²⁺ + 2e⁻); the carbon rod is the positive terminal and MnO₂ the depolariser."),
    ("Electrochemistry", "Medium", "Which of the following is NOT a factor that determines which ion is discharged at an electrode?",
     "the position of the ion in the electrochemical series", "the concentration of the ion in the solution", "the nature of the electrode", "the colour of the electrolyte", "D",
     "Discharge depends on the electrochemical series, concentration and the electrode material; colour has no effect."),
    ("Electrochemistry", "Medium", "A copper spoon is to be electroplated with nickel. The correct arrangement is",
     "spoon as anode, nickel as cathode, in nickel(II) tetraoxosulphate(VI) solution", "spoon as cathode, nickel as anode, in nickel(II) tetraoxosulphate(VI) solution", "spoon as cathode, nickel as anode, in copper(II) tetraoxosulphate(VI) solution", "spoon as anode, nickel as cathode, in dilute tetraoxosulphate(VI) acid", "B",
     "The object to be plated is the cathode, the plating metal is the anode (which replenishes the ions) and the electrolyte contains ions of the plating metal."),
    ("Electrochemistry", "Medium", "The electrolysis of brine (concentrated sodium chloride solution) is used industrially to produce",
     "sodium metal, chlorine and water", "chlorine, hydrogen and sodium hydroxide", "hydrogen, oxygen and sodium chloride", "sodium metal and oxygen", "B",
     "Cl⁻ is discharged at the anode, H⁺ at the cathode, and Na⁺ and OH⁻ remain in solution as sodium hydroxide."),
    # ---------------- Energy and Rates of Reaction ----------------
    ("Energy and Rates of Reaction", "Medium", "The heat of formation of water is −286 kJ/mol. The heat evolved when 4 g of hydrogen burns completely in oxygen is (H = 1)",
     "143 kJ", "286 kJ", "572 kJ", "1,144 kJ", "C",
     "4 g of H₂ = 2 mol, forming 2 mol of water: 2 × 286 = 572 kJ.", "4/2*286"),
    ("Energy and Rates of Reaction", "Medium", "When solid sodium hydroxide dissolves in water the beaker becomes warm. Which statement is correct?",
     "ΔH is positive and the process is exothermic", "ΔH is negative and the process is exothermic", "ΔH is positive and the process is endothermic", "ΔH is negative and the process is endothermic", "B",
     "Heat is released to the surroundings (the water warms), so the enthalpy change is negative: exothermic."),
    ("Energy and Rates of Reaction", "Hard", "Fresh milk left at 30 °C goes sour in about 10 hours. If the rate of the souring reaction doubles for every 10 °C rise in temperature, the same milk kept in a refrigerator at 0 °C should stay fresh for about",
     "30 hours", "40 hours", "80 hours", "60 hours", "C",
     "Cooling by three steps of 10 °C makes the reaction 2³ = 8 times slower, so the milk lasts about 8 × 10 = 80 hours.", "8*10"),
    ("Energy and Rates of Reaction", "Medium", "Marble chips react with 1.0 mol/dm³ hydrochloric acid. Which change would NOT increase the rate at which carbon(IV) oxide is produced?",
     "crushing the marble chips into powder", "warming the acid", "using 2.0 mol/dm³ acid", "adding water to the acid", "D",
     "Dilution lowers the concentration of H⁺ ions, so collisions become less frequent and the rate falls."),
    ("Energy and Rates of Reaction", "Medium", "The activation energy of a reaction is the",
     "energy released when the products are formed", "minimum energy that colliding particles must have for a reaction to occur", "difference between the energies of reactants and products", "energy needed to heat the reactants to their boiling points", "B",
     "Only collisions with energy at least equal to the activation energy lead to bond breaking and reaction."),
    ("Energy and Rates of Reaction", "Medium", "In an energy profile diagram the enthalpy change of a reaction is represented by the",
     "height of the peak above the reactants", "difference in energy between the reactants and the products", "height of the peak above the products", "total energy of the products", "B",
     "ΔH = H(products) − H(reactants); the height of the peak above the reactants is the activation energy."),
    ("Energy and Rates of Reaction", "Medium", "Which of the following statements about a catalyst is correct?",
     "it increases the yield of product at equilibrium", "it provides an alternative reaction path with a lower activation energy", "it is used up during the reaction", "it raises the enthalpy change of the reaction", "B",
     "A catalyst is chemically unchanged at the end and does not alter ΔH or the equilibrium position; it only makes the reaction faster."),
    ("Energy and Rates of Reaction", "Medium", "Enzymes in the human body work best at about 37 °C. At 70 °C they stop working because",
     "the substrate molecules move too fast to be caught", "the enzyme protein is denatured and loses its shape", "the water in the cells boils away", "the activation energy becomes too high", "B",
     "Heat breaks the weak bonds that hold the enzyme in its precise three-dimensional shape, destroying the active site."),
    ("Energy and Rates of Reaction", "Medium", "Sodium thiosulphate solution reacts with dilute acid to form a yellow precipitate of sulphur. Doubling the concentration of the thiosulphate makes the cross under the flask disappear",
     "in about half the time", "in about twice the time", "in the same time", "instantly", "A",
     "Rate is roughly proportional to concentration for this reaction, so the time taken to form the same amount of sulphur is about halved."),
    ("Energy and Rates of Reaction", "Medium", "The entropy of a system decreases when",
     "ice melts to form liquid water", "steam condenses to form liquid water", "a solid dissolves in water", "a gas expands into a larger container", "B",
     "Condensation turns freely moving gas molecules into a more ordered liquid, reducing the disorder (entropy)."),
    ("Energy and Rates of Reaction", "Hard", "For a certain reaction ΔH = +50 kJ/mol and ΔS = +200 J K⁻¹ mol⁻¹. The reaction becomes spontaneous (ΔG < 0) above a temperature of",
     "25 K", "250 K", "2,500 K", "0.25 K", "B",
     "ΔG = ΔH − TΔS = 0 when T = ΔH/ΔS = 50,000/200 = 250 K; above this temperature ΔG is negative.", "50000/200"),
    ("Energy and Rates of Reaction", "Medium", "Which of the following is an endothermic process?",
     "burning of charcoal", "neutralisation of an acid by a base", "thermal decomposition of limestone", "rusting of iron", "C",
     "CaCO₃ must be heated continuously to decompose it into CaO and CO₂; heat is absorbed."),
    # ---------------- Chemical Equilibrium ----------------
    ("Chemical Equilibrium", "Medium", "For the reaction N₂(g) + 3H₂(g) ⇌ 2NH₃(g), increasing the pressure",
     "shifts the equilibrium to the left", "shifts the equilibrium to the right, giving more ammonia", "has no effect on the position of equilibrium", "decomposes the ammonia formed", "B",
     "Four moles of gas become two; the system relieves the added pressure by favouring the side with fewer gas molecules."),
    ("Chemical Equilibrium", "Medium", "Which of the following changes alters the value of the equilibrium constant of a reaction?",
     "adding a catalyst", "changing the temperature", "changing the pressure", "changing the concentration of a reactant", "B",
     "K depends only on temperature; the other changes may shift the position of equilibrium but K itself stays the same."),
    ("Chemical Equilibrium", "Hard", "At a certain temperature the equilibrium constant Kc for A(g) + B(g) ⇌ C(g) + D(g) is 4. If 1 mol each of A and B are mixed in a 1 dm³ vessel, the equilibrium concentration of C is",
     "0.33 mol/dm³", "0.50 mol/dm³", "0.67 mol/dm³", "0.80 mol/dm³", "C",
     "x²/(1 − x)² = 4, so x/(1 − x) = 2 and x = 2/3 = 0.67 mol/dm³.", "2/3"),
    ("Chemical Equilibrium", "Medium", "In the reaction CaCO₃(s) ⇌ CaO(s) + CO₂(g) carried out in a closed vessel, the amount of CO₂ at equilibrium is increased by",
     "adding more CaCO₃", "removing some CaO", "raising the temperature", "increasing the pressure", "C",
     "The decomposition is endothermic, so heating shifts it to the right; solids do not appear in the equilibrium expression, so adding or removing them has no effect."),
    ("Chemical Equilibrium", "Medium", "The colour of the equilibrium mixture 2NO₂(g) (brown) ⇌ N₂O₄(g) (colourless), ΔH = −57 kJ, becomes darker when the mixture is",
     "cooled in ice", "heated in warm water", "compressed", "left undisturbed", "B",
     "Heating favours the endothermic (reverse) direction, producing more brown NO₂."),
    ("Chemical Equilibrium", "Medium", "For the equilibrium H₂(g) + I₂(g) ⇌ 2HI(g), increasing the pressure",
     "increases the amount of HI", "decreases the amount of HI", "has no effect on the position of equilibrium", "stops the forward reaction", "C",
     "There are two moles of gas on each side, so a pressure change cannot favour either direction."),
    ("Chemical Equilibrium", "Medium", "In a saturated solution of silver chloride in contact with the solid, adding sodium chloride solution causes",
     "more silver chloride to dissolve", "some silver chloride to precipitate", "no change at all", "the silver chloride to turn black", "B",
     "Extra Cl⁻ ions push the equilibrium AgCl(s) ⇌ Ag⁺ + Cl⁻ to the left (common-ion effect), so solid is deposited."),
    ("Chemical Equilibrium", "Medium", "A reversible reaction reaches equilibrium in a closed vessel. Which statement about the system is correct?",
     "the concentrations of reactants and products are equal", "the reaction has stopped completely", "the forward and reverse reactions occur at the same rate", "no product is being formed any more", "C",
     "Equilibrium is dynamic: both reactions continue but at equal rates, so the concentrations stay constant (not necessarily equal)."),
    ("Chemical Equilibrium", "Hard", "The equilibrium constant Kc for the reaction 2A(g) ⇌ B(g) is 0.5 dm³/mol. The value of Kc for B(g) ⇌ 2A(g) at the same temperature is",
     "0.5 dm³/mol", "2 mol/dm³", "0.25 mol/dm³", "1 mol/dm³", "B",
     "Reversing a reaction inverts its equilibrium constant: 1/0.5 = 2, with the units also inverted.", "1/0.5"),
    ("Chemical Equilibrium", "Medium", "The solubility of a gas in water decreases when",
     "the temperature is lowered", "the pressure of the gas is increased", "the temperature is raised", "the volume of water is increased", "C",
     "Dissolving a gas is exothermic, so heating drives the gas out — which is why warm fizzy drinks go flat quickly."),
    ("Chemical Equilibrium", "Medium", "A solution contains more solute than a saturated solution would normally hold at that temperature. Such a solution is",
     "dilute", "unsaturated", "supersaturated", "concentrated but unsaturated", "C",
     "A supersaturated solution is unstable; a small crystal added to it causes the excess solute to crystallise out at once."),
    # ---------------- Metals and Non-Metals ----------------
    ("Metals and Non-Metals", "Medium", "Which of the following metals is extracted by electrolysis rather than by chemical reduction?",
     "iron", "zinc", "sodium", "copper", "C",
     "Sodium is too reactive for carbon or hydrogen to reduce its compounds; it is obtained by electrolysing molten sodium chloride (Downs cell)."),
    ("Metals and Non-Metals", "Medium", "In the blast furnace, limestone is added along with the iron ore and coke in order to",
     "act as a fuel and raise the temperature", "remove sandy impurities as slag", "supply carbon(II) oxide for the reduction", "prevent the iron from melting", "B",
     "CaCO₃ → CaO + CO₂, then CaO + SiO₂ → CaSiO₃ (slag), which floats on the molten iron and is tapped off separately."),
    ("Metals and Non-Metals", "Medium", "Zinc is used to galvanise iron because zinc",
     "is cheaper and heavier than iron", "is more reactive than iron and corrodes preferentially, protecting the iron", "forms a hard coating that cannot be scratched", "is less reactive than iron and forms a barrier", "B",
     "Even when the coating is scratched, zinc is oxidised in place of the iron (sacrificial protection)."),
    ("Metals and Non-Metals", "Medium", "A metal reacts vigorously with cold water, its hydroxide is strongly alkaline and its carbonate does not decompose on gentle heating. The metal is most likely",
     "magnesium", "copper", "potassium", "zinc", "C",
     "Only the alkali metals react vigorously with cold water and have thermally stable carbonates; Mg reacts only with steam and its carbonate decomposes."),
    ("Metals and Non-Metals", "Medium", "When copper is heated in air it becomes coated with a black solid. The black solid is",
     "copper(I) oxide", "copper(II) oxide", "copper(II) trioxocarbonate(IV)", "carbon", "B",
     "2Cu + O₂ → 2CuO; the black layer is copper(II) oxide."),
    ("Metals and Non-Metals", "Medium", "Anhydrous white copper(II) tetraoxosulphate(VI) is used in the laboratory to",
     "test for the presence of water", "dry chlorine gas", "detect carbon(IV) oxide", "absorb ammonia", "A",
     "It turns blue as it takes up water of crystallisation: CuSO₄ + 5H₂O → CuSO₄·5H₂O."),
    ("Metals and Non-Metals", "Medium", "Which of the following gases is collected by downward delivery (upward displacement of air)?",
     "hydrogen", "ammonia", "chlorine", "helium", "C",
     "Chlorine is much denser than air, so it sinks and fills the jar from the bottom; hydrogen and ammonia are collected by upward delivery."),
    ("Metals and Non-Metals", "Medium", "Hydrogen sulphide gas is passed through a solution of a salt and a black precipitate forms. The salt is most likely",
     "zinc chloride", "lead(II) trioxonitrate(V)", "sodium chloride", "magnesium tetraoxosulphate(VI)", "B",
     "Pb²⁺ + H₂S → PbS (black) + 2H⁺; zinc gives a white sulphide, and Na⁺ and Mg²⁺ sulphides do not precipitate."),
    ("Metals and Non-Metals", "Medium", "Aluminium foil does not react noticeably with water or air although aluminium is a fairly reactive metal. This is because",
     "aluminium is actually below hydrogen in the activity series", "a thin, tough layer of aluminium oxide protects the surface", "aluminium foil is coated with a plastic film", "the metal is too thin for the reaction to be seen", "B",
     "The oxide film formed instantly in air is impervious and seals the metal beneath it (anodising thickens it deliberately)."),
    ("Metals and Non-Metals", "Medium", "Nitrogen(IV) oxide, a brown gas, is produced when",
     "ammonium chloride is heated", "copper reacts with concentrated trioxonitrate(V) acid", "zinc reacts with dilute hydrochloric acid", "sodium trioxonitrate(V) is dissolved in water", "B",
     "Cu + 4HNO₃(conc) → Cu(NO₃)₂ + 2NO₂ + 2H₂O; the brown fumes are NO₂."),
    ("Metals and Non-Metals", "Medium", "Ammonia gas is identified in the laboratory by the fact that it",
     "turns moist red litmus blue and gives dense white fumes with hydrogen chloride", "relights a glowing splint", "turns lime water milky", "bleaches moist litmus paper", "A",
     "Ammonia is the common alkaline gas; with HCl vapour it forms a white smoke of ammonium chloride."),
    ("Metals and Non-Metals", "Medium", "Which of the following is an allotrope of carbon?",
     "carborundum", "graphite", "carbon(IV) oxide", "coal gas", "B",
     "Diamond, graphite and the fullerenes are allotropes: different structural forms of the element carbon."),
    ("Metals and Non-Metals", "Medium", "Rhombic and monoclinic sulphur are",
     "isotopes of sulphur", "allotropes of sulphur", "compounds of sulphur with oxygen", "isomers of sulphur", "B",
     "Both are crystalline forms of the element sulphur made of S₈ rings packed differently; the transition temperature is 96 °C."),
    ("Metals and Non-Metals", "Medium", "Sulphur(IV) oxide is passed into water and the solution is tested. The solution",
     "turns blue litmus red because it contains trioxosulphate(IV) acid", "turns red litmus blue because it is alkaline", "has no effect on litmus", "turns lime water milky", "A",
     "SO₂ + H₂O ⇌ H₂SO₃, a weak acid; SO₂ is an acidic oxide."),
    # ---------------- Organic Chemistry ----------------
    ("Organic Chemistry", "Medium", "The general formula of the alkynes is",
     "CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙH₂ₙ₊₁OH", "C",
     "Alkynes contain one triple bond and have four fewer hydrogens than the corresponding alkane: e.g. C₂H₂, C₃H₄."),
    ("Organic Chemistry", "Medium", "A compound with the structure CH₃CH₂CH₂CHO gives a silver mirror when warmed with Tollens' reagent. The compound is",
     "butan-1-ol", "butanal", "butanone", "butanoic acid", "B",
     "The –CHO group at the end of a four-carbon chain makes it an aldehyde (butanal); aldehydes reduce Tollens' reagent to silver."),
    ("Organic Chemistry", "Medium", "A reagent bottle in the laboratory shows the structure CH₃CH(CH₃)CH₂CH₂OH. The correct IUPAC name to write on its label is",
     "2-methylbutan-1-ol", "3-methylbutan-1-ol", "pentan-1-ol", "3-methylbutan-2-ol", "B",
     "Number from the end nearer the –OH: the chain is butan-1-ol and the methyl group is on carbon 3."),
    ("Organic Chemistry", "Medium", "But-1-ene and but-2-ene are examples of",
     "chain isomers", "positional isomers", "functional group isomers", "geometric isomers", "B",
     "They have the same carbon skeleton and functional group but differ in the position of the double bond."),
    ("Organic Chemistry", "Medium", "Which of the following compounds is a functional-group isomer of propanal, CH₃CH₂CHO?",
     "propanone, CH₃COCH₃", "propan-1-ol", "propanoic acid", "propene", "A",
     "Propanal and propanone both have the formula C₃H₆O but one is an aldehyde and the other a ketone."),
    ("Organic Chemistry", "Medium", "Ethanoic acid reacts with sodium hydroxide to form",
     "sodium ethanoate and water", "ethanol and hydrogen", "ethene and water", "sodium ethoxide and hydrogen", "A",
     "CH₃COOH + NaOH → CH₃COONa + H₂O — a neutralisation, since ethanoic acid is a (weak) acid."),
    ("Organic Chemistry", "Medium", "The reaction between ethanoic acid and ethanol in the presence of concentrated tetraoxosulphate(VI) acid produces a compound with a fruity smell. The compound is",
     "ethyl ethanoate", "ethanal", "diethyl ether", "sodium ethanoate", "A",
     "Acid + alcohol → ester + water; ethyl ethanoate, CH₃COOC₂H₅, is the ester."),
    ("Organic Chemistry", "Medium", "The alkane that has isomers is",
     "methane", "ethane", "propane", "butane", "D",
     "Butane (C₄H₁₀) exists as n-butane and 2-methylpropane; the three smaller alkanes have only one structure each."),
    ("Organic Chemistry", "Medium", "Polythene is formed from ethene by",
     "condensation polymerisation", "addition polymerisation", "substitution", "dehydration", "B",
     "Ethene molecules add to one another through their double bonds with no by-product: n CH₂=CH₂ → (–CH₂–CH₂–)ₙ."),
    ("Organic Chemistry", "Hard", "Which of the following statements about benzene is correct?",
     "it readily decolourises bromine water at room temperature", "all six C–C bonds are of the same length", "it is a straight-chain hydrocarbon", "it contains three isolated double bonds", "B",
     "The six π electrons are delocalised round the ring, so every bond is intermediate between single and double (0.139 nm)."),
    ("Organic Chemistry", "Medium", "Ethanol for use as a fuel is produced from cassava or sugar cane by",
     "cracking", "fermentation", "hydration of ethene", "esterification", "B",
     "Yeast enzymes convert glucose to ethanol and carbon(IV) oxide: C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂."),
    ("Organic Chemistry", "Medium", "The product obtained when 1 mol of ethyne reacts with 2 mol of hydrogen over a nickel catalyst is",
     "ethene", "ethane", "methane", "polyethyne", "B",
     "Both π bonds of the triple bond are hydrogenated: C₂H₂ + 2H₂ → C₂H₆."),
    ("Organic Chemistry", "Medium", "A kerosene stove with a badly adjusted wick burns with a yellow, smoky flame and blackens the bottom of the pot. The black deposit forms because",
     "the kerosene contains a lot of dissolved carbon powder", "the fuel burns incompletely in a limited supply of air, leaving unburnt carbon", "the pot reacts with the hot kerosene vapour to form soot", "the flame is too hot and decomposes the metal of the pot", "B",
     "With insufficient oxygen a hydrocarbon burns incompletely, forming carbon (soot) and carbon(II) oxide instead of only CO₂ and water."),
    ("Organic Chemistry", "Medium", "Which of the following is a secondary alcohol?",
     "CH₃CH₂CH₂OH", "CH₃CH(OH)CH₃", "(CH₃)₃COH", "CH₃OH", "B",
     "In propan-2-ol the carbon carrying the –OH is bonded to two other carbon atoms."),
    ("Organic Chemistry", "Medium", "Carboxylic acids have higher boiling points than alkanes of similar molecular mass because",
     "carboxylic acid molecules are much heavier", "carboxylic acid molecules form hydrogen bonds with one another", "carboxylic acids are ionic compounds", "alkanes decompose before they boil", "B",
     "Pairs of –COOH groups hydrogen-bond into dimers, so far more energy is needed to separate the molecules than for non-polar alkanes."),
    ("Organic Chemistry", "Medium", "A gaseous hydrocarbon decolourises bromine water, has the empirical formula CH₂ and a vapour density of 28. The hydrocarbon is (C = 12, H = 1)",
     "ethene", "propene", "butene", "pentene", "C",
     "Relative molecular mass = 2 × 28 = 56; (CH₂)ₙ: 14n = 56, so n = 4: C₄H₈, butene."),
    # ---------------- Water, Air and Environmental Chemistry ----------------
    ("Water Air and Environmental Chemistry", "Medium", "Temporary hardness in water is caused by dissolved",
     "calcium hydrogentrioxocarbonate(IV)", "calcium tetraoxosulphate(VI)", "sodium chloride", "magnesium chloride", "A",
     "Ca(HCO₃)₂ decomposes on boiling to insoluble CaCO₃, which is why this hardness can be removed by boiling."),
    ("Water Air and Environmental Chemistry", "Medium", "Kettles used to boil hard water develop a white deposit (fur) because",
     "the water evaporates and leaves sodium chloride behind", "calcium hydrogentrioxocarbonate(IV) decomposes to insoluble calcium trioxocarbonate(IV)", "the metal of the kettle corrodes and forms an oxide", "soap in the water forms scum on the element", "B",
     "Ca(HCO₃)₂ → CaCO₃ + H₂O + CO₂ on heating; the insoluble trioxocarbonate(IV) coats the element."),
    ("Water Air and Environmental Chemistry", "Medium", "Water is softened by passing it through an ion-exchange resin. The resin removes hardness by",
     "filtering out the calcium salts", "replacing calcium and magnesium ions with sodium ions", "boiling the water inside the column", "adding chlorine to the water", "B",
     "Ca²⁺ and Mg²⁺ ions are held by the resin and Na⁺ ions are released; sodium salts do not form scum."),
    ("Water Air and Environmental Chemistry", "Medium", "Chlorine is added to municipal water supplies in order to",
     "remove suspended particles", "kill harmful micro-organisms", "make the water taste better", "remove dissolved salts", "B",
     "Chlorine (or oxochlorate(I) ions) disinfects the water; coagulation and filtration handle the suspended solids."),
    ("Water Air and Environmental Chemistry", "Medium", "The percentage by volume of oxygen in clean dry air is approximately",
     "1%", "21%", "50%", "78%", "B",
     "Air is about 78% nitrogen, 21% oxygen, 0.9% argon and 0.04% carbon(IV) oxide.", "21"),
    ("Water Air and Environmental Chemistry", "Medium", "A candle burning in a closed jar over water goes out after a while and the water level rises about one-fifth of the way up the jar. This shows that",
     "the air is about one-fifth oxygen", "the candle produces water vapour only", "carbon(IV) oxide is lighter than air", "nitrogen supports combustion", "A",
     "The oxygen (about 21% of the air) is used up and the CO₂ formed largely dissolves, so the water rises to replace the oxygen consumed."),
    ("Water Air and Environmental Chemistry", "Medium", "The main gas responsible for the greenhouse effect and global warming is",
     "oxygen", "nitrogen", "carbon(IV) oxide", "argon", "C",
     "CO₂ (with methane and water vapour) absorbs infrared radiation emitted by the Earth and traps heat in the atmosphere."),
    ("Water Air and Environmental Chemistry", "Medium", "The layer of ozone in the upper atmosphere is important because it",
     "supplies oxygen for breathing at high altitude", "absorbs harmful ultraviolet radiation from the Sun", "reflects radio waves back to the Earth", "traps heat and keeps the Earth warm", "B",
     "Ozone (O₃) absorbs most of the Sun's UV-B radiation, which would otherwise cause skin cancer and crop damage."),
    ("Water Air and Environmental Chemistry", "Medium", "Chlorofluorocarbons (CFCs) released from old refrigerators damage the environment mainly by",
     "causing acid rain", "destroying the ozone layer", "polluting rivers with chloride ions", "producing smog in cities", "B",
     "UV light releases chlorine atoms from CFCs, and each chlorine atom catalyses the destruction of thousands of ozone molecules."),
    ("Water Air and Environmental Chemistry", "Medium", "Water is described as the universal solvent because",
     "it dissolves every known substance", "its polar molecules dissolve a very wide range of ionic and polar substances", "it is the most abundant liquid on Earth", "it has a neutral pH", "B",
     "The polar O–H bonds and hydrogen bonding let water surround and separate ions and polar molecules."),
    ("Water Air and Environmental Chemistry", "Medium", "Which of the following pollutants is produced mainly by the incomplete combustion of petrol in car engines?",
     "sulphur(IV) oxide", "carbon(II) oxide", "ozone", "chlorine", "B",
     "With limited oxygen the carbon in the fuel is oxidised only as far as CO, a colourless, odourless and poisonous gas."),
    ("Water Air and Environmental Chemistry", "Medium", "Fertiliser washed from farms into a lake makes the water green with algae; the fish later die because",
     "the fertiliser is directly poisonous to fish", "decaying algae use up the dissolved oxygen in the water", "the algae eat the fish eggs", "the water becomes too acidic", "B",
     "This is eutrophication: bacteria decomposing the dead algal bloom consume dissolved oxygen, suffocating fish and other aquatic life."),
    ("Water Air and Environmental Chemistry", "Medium", "Distilled water does not conduct electricity appreciably because it",
     "contains no dissolved gases", "contains very few ions", "is a covalent liquid that cannot be electrolysed", "has a pH of exactly 7", "B",
     "Pure water is only very slightly ionised (about 10⁻⁷ mol/dm³ of H⁺ and OH⁻); tap water conducts because of dissolved salts."),
    # ---------------- Industrial Chemistry ----------------
    ("Industrial Chemistry", "Medium", "In the Contact process the reaction 2SO₂ + O₂ ⇌ 2SO₃ is carried out at about 450 °C and 1–2 atm with a vanadium(V) oxide catalyst. A high pressure is NOT used because",
     "high pressure would decompose the catalyst", "the yield is already about 98% at low pressure, so the extra cost is not justified", "high pressure shifts the equilibrium to the left", "sulphur(VI) oxide is a solid at high pressure", "B",
     "Although higher pressure would favour SO₃ slightly, the conversion is already almost complete under mild conditions."),
    ("Industrial Chemistry", "Medium", "The products of the Solvay process are sodium trioxocarbonate(IV) and",
     "sodium hydroxide", "calcium chloride", "ammonium tetraoxosulphate(VI)", "chlorine", "B",
     "Overall: 2NaCl + CaCO₃ → Na₂CO₃ + CaCl₂; the ammonia is recycled."),
    ("Industrial Chemistry", "Medium", "Nitrogen for the Haber process is obtained from",
     "the decomposition of ammonium salts", "the fractional distillation of liquid air", "the electrolysis of brine", "the reduction of trioxonitrate(V) salts", "B",
     "Air is liquefied and its components separated by their boiling points (N₂ −196 °C, O₂ −183 °C)."),
    ("Industrial Chemistry", "Medium", "In the manufacture of trioxonitrate(V) acid by the Ostwald process, ammonia is first",
     "dissolved in water", "oxidised over a platinum catalyst to nitrogen(II) oxide", "reduced to nitrogen gas", "reacted with sulphuric acid", "B",
     "4NH₃ + 5O₂ → 4NO + 6H₂O at about 900 °C over Pt/Rh; the NO is then oxidised to NO₂ and absorbed in water."),
    ("Industrial Chemistry", "Medium", "Soap is made by boiling palm oil with concentrated sodium hydroxide solution. This reaction is called",
     "esterification", "saponification", "fermentation", "hydrogenation", "B",
     "The alkali hydrolyses the fat (an ester) into glycerol and the sodium salts of the fatty acids, which are the soap."),
    ("Industrial Chemistry", "Medium", "Common salt is added to the mixture at the end of soap making in order to",
     "give the soap a pleasant taste", "reduce the solubility of the soap so that it separates out", "make the soap lather better", "neutralise the excess alkali", "B",
     "Salting out: soap is less soluble in brine, so it rises to the surface and can be skimmed off from the glycerol solution."),
    ("Industrial Chemistry", "Medium", "Which of the following is a natural polymer?",
     "nylon", "polythene", "starch", "PVC", "C",
     "Starch is a polymer of glucose made by plants; the others are synthetic."),
    ("Industrial Chemistry", "Medium", "Petrol, kerosene and diesel are obtained from crude oil by",
     "cracking", "fractional distillation", "polymerisation", "electrolysis", "B",
     "The fractions are separated in a tall column according to their boiling-point ranges."),
    ("Industrial Chemistry", "Medium", "A fraction of crude oil that boils at a higher temperature than petrol consists of hydrocarbons that",
     "have shorter carbon chains and are more flammable", "have longer carbon chains and are more viscous", "contain more hydrogen per carbon atom", "are gases at room temperature", "B",
     "Boiling point rises with chain length as van der Waals forces increase; longer chains also flow less easily and ignite less readily."),
    ("Industrial Chemistry", "Medium", "The setting of cement after water is added is mainly the result of",
     "evaporation of the water", "hydration reactions forming interlocking crystals of calcium silicates and aluminates", "the cement dissolving completely in the water", "reaction with oxygen in the air", "B",
     "Cement hardens chemically, not by drying — it will set even under water."),
    ("Industrial Chemistry", "Medium", "Which of the following statements about soapless detergents is correct?",
     "they are made from animal fats by boiling with caustic soda", "they are usually made from petroleum products and do not form scum in hard water", "they cannot remove grease from clothes", "they are all readily biodegradable", "B",
     "The sulphonate salts in soapless detergents have soluble calcium and magnesium salts, so they lather in hard water; some branched-chain types resist bacterial breakdown."),
    ("Industrial Chemistry", "Medium", "Nitrogenous fertilisers such as urea and ammonium tetraoxosulphate(VI) are applied to crops because nitrogen is needed for",
     "strong root formation only", "the synthesis of proteins and chlorophyll", "preventing insect attack", "raising the pH of the soil", "B",
     "Nitrogen is a component of amino acids, proteins and chlorophyll; a deficiency gives yellow, stunted plants."),
    # ---------------- Chemistry of Biomolecules ----------------
    ("Chemistry of Biomolecules", "Medium", "Glucose reduces Fehling's or Benedict's solution because its molecule contains",
     "a free aldehyde group", "an ester group", "a carboxylic acid group", "a benzene ring", "A",
     "The –CHO group of glucose is oxidised to –COOH while Cu²⁺ is reduced to the brick-red Cu₂O precipitate."),
    ("Chemistry of Biomolecules", "Medium", "The bond that links amino acids together in a protein chain is the",
     "glycosidic bond", "peptide bond", "ester bond", "hydrogen bond", "B",
     "The –COOH group of one amino acid condenses with the –NH₂ group of the next to form a –CO–NH– peptide link, releasing water."),
    ("Chemistry of Biomolecules", "Medium", "Starch and cellulose are both polymers of glucose, yet cotton (cellulose) cannot be digested by humans while starch can. The difference is in",
     "the number of glucose units in each polymer", "the way the glucose units are linked (α-links in starch, β-links in cellulose)", "the elements present in each polymer", "the solubility of glucose itself", "B",
     "Human amylase hydrolyses only the α-1,4 glycosidic links of starch."),
    ("Chemistry of Biomolecules", "Medium", "A fat that is solid at room temperature differs from an oil that is liquid mainly in that the fat",
     "contains more unsaturated fatty acid chains", "contains more saturated fatty acid chains", "is not an ester", "contains no glycerol", "B",
     "Saturated chains pack closely and have higher melting points; the C=C bonds in unsaturated oils prevent close packing."),
    ("Chemistry of Biomolecules", "Medium", "The iodine number of an oil is a measure of its",
     "acidity", "degree of unsaturation", "relative molecular mass", "density", "B",
     "Iodine adds across C=C double bonds; the more unsaturated the oil, the greater the mass of iodine absorbed per 100 g."),
    ("Chemistry of Biomolecules", "Medium", "Which of the following is the monomer of natural rubber?",
     "ethene", "isoprene (2-methylbuta-1,3-diene)", "vinyl chloride", "styrene", "B",
     "Natural rubber latex is poly(isoprene); vulcanising with sulphur cross-links the chains and makes it harder."),
    ("Chemistry of Biomolecules", "Medium", "Maltose is hydrolysed by dilute acid to give",
     "glucose and fructose", "two molecules of glucose", "glucose and galactose", "starch", "B",
     "Maltose is a disaccharide made of two glucose units; sucrose gives glucose + fructose and lactose gives glucose + galactose."),
    ("Chemistry of Biomolecules", "Medium", "In the Millon's test a protein sample gives",
     "a blue-black colour", "a brick-red precipitate", "a red colour or precipitate", "a white precipitate", "C",
     "Millon's reagent reacts with the tyrosine in proteins to give a red coloration; blue-black is the starch–iodine test."),
    ("Chemistry of Biomolecules", "Medium", "Enzymes are described as biological catalysts because they",
     "are used up as the reaction proceeds", "speed up reactions in living cells and remain unchanged at the end", "provide the energy for the reactions of the cell", "are carbohydrates that store energy", "B",
     "Enzymes are proteins that lower the activation energy of specific reactions and are regenerated after each turnover."),
    ("Chemistry of Biomolecules", "Medium", "Vegetable oil is hardened into margarine by hydrogenation. The catalyst used is",
     "vanadium(V) oxide", "finely divided nickel", "platinum gauze", "iron filings", "B",
     "Hydrogen is bubbled through the hot oil over nickel at about 180 °C, saturating some of the C=C bonds."),
    ("Chemistry of Biomolecules", "Medium", "Which of the following statements about amino acids is correct?",
     "they contain only carbon and hydrogen", "each contains both an amino group and a carboxyl group", "they are all obtained from carbohydrates", "they cannot form polymers", "B",
     "The –NH₂ and –COOH groups on the same molecule make amino acids amphoteric and let them link into proteins."),
    ("Chemistry of Biomolecules", "Medium", "Sucrose is a non-reducing sugar, but after boiling with dilute acid the solution reduces Benedict's solution. The acid has",
     "oxidised the sucrose to an acid", "hydrolysed the sucrose to glucose and fructose", "converted the sucrose into starch", "removed water to form caramel", "B",
     "Inversion: C₁₂H₂₂O₁₁ + H₂O → C₆H₁₂O₆ (glucose) + C₆H₁₂O₆ (fructose), both of which are reducing sugars."),
]

FIX = {
    "The value for aluminium is lower than that for magnesium because": ("the nuclear charge of aluminium is smaller than that of magnesium, so its electrons are held less firmly", "the outer electron of aluminium is in a 3p orbital, further out and shielded by the 3s electrons", "aluminium is a poorer conductor than magnesium, so its electrons are less mobile in the solid", "the aluminium atom has a much larger radius than the magnesium atom because it has extra shells"),
    "The bond angle in water (104.5°) is smaller than that in ammonia (107°) because": ("oxygen is a larger atom than nitrogen, so its bonds lie further apart", "water has two lone pairs which repel the bonding pairs more strongly", "water has fewer hydrogen atoms, so the bonds have more room to spread", "the O–H bond is longer than the N–H bond and bends more easily"),
    "held together by van der Waals forces only": ("solid sodium chloride", "solid carbon(IV) oxide", "solid diamond", "solid copper metal"),
    "with carbon electrodes, the solution gradually becomes": ("more alkaline, as hydroxide ions build up round the cathode", "acidic, because tetraoxosulphate(VI) acid is left in solution", "a deeper blue, because copper ions form at the carbon anode", "neutral, because the ions removed at each electrode balance"),
    "the enthalpy change of a reaction is represented by the": ("height of the peak above the level of the reactants", "difference in energy between the reactants and the products", "height of the peak above the level of the products", "total energy of the products measured from the baseline"),
    "H₂(g) + I₂(g) ⇌ 2HI(g), increasing the pressure": ("increases the amount of HI in the mixture", "decreases the amount of HI in the mixture", "has no effect on the position of equilibrium", "stops the forward reaction from taking place"),
    "Zinc is used to galvanise iron because zinc": ("is cheaper and denser than iron, so it forms a heavy coat", "is more reactive than iron and corrodes first, protecting the iron", "forms a very hard coating that cannot be scratched off the iron", "is less reactive than iron and acts only as a barrier to water"),
    "Ammonia gas is identified in the laboratory by the fact that it": ("turns moist red litmus blue and gives white fumes with hydrogen chloride", "relights a glowing splint and gives white fumes with hydrogen chloride", "turns lime water milky and turns moist blue litmus paper red", "bleaches moist litmus paper and gives a pop sound with a lighted splint"),
    "Kettles used to boil hard water develop a white deposit (fur) because": ("the water evaporates and leaves the dissolved sodium chloride behind", "calcium hydrogentrioxocarbonate(IV) decomposes to insoluble calcium trioxocarbonate(IV)", "the metal of the kettle corrodes and forms a white layer of metal oxide", "the soap dissolved in the water forms a scum that sticks to the element"),
    "The resin removes hardness by": ("filtering out the calcium salts as solid particles", "replacing calcium and magnesium ions with sodium ions", "boiling the water inside the column to remove the salts", "adding chlorine that destroys the calcium and magnesium ions"),
    "Water is described as the universal solvent because": ("it dissolves every known substance completely at room temperature", "its polar molecules dissolve a wide range of ionic and polar substances", "it is the most abundant liquid on Earth and is found in every solution", "it has a neutral pH, so it reacts with neither acids nor bases"),
    "A high pressure is NOT used because": ("high pressure would decompose the vanadium(V) oxide catalyst", "the yield is already about 98% at low pressure, so the extra cost is not justified", "high pressure shifts this equilibrium to the left and lowers the yield", "sulphur(VI) oxide would solidify in the pipes at high pressure"),
    "by the Ostwald process, ammonia is first": ("dissolved in water to form ammonium hydroxide", "oxidised over a platinum catalyst to nitrogen(II) oxide", "reduced to nitrogen gas over an iron catalyst", "reacted with tetraoxosulphate(VI) acid to form a salt"),
    "Common salt is added to the mixture at the end of soap making in order to": ("give the soap a pleasant smell and taste", "reduce the solubility of the soap so that it separates out", "make the soap lather better in hard water", "neutralise the excess alkali left in the mixture"),
    "The setting of cement after water is added is mainly the result of": ("evaporation of the water from the wet mixture", "hydration reactions forming interlocking crystals of calcium silicates", "the cement powder dissolving completely in the water added", "reaction of the cement with oxygen and carbon(IV) oxide in the air"),
    "are applied to crops because nitrogen is needed for": ("strong root formation only", "making proteins and chlorophyll", "keeping insects off the leaves", "raising the pH of the soil"),
    "cannot be digested by humans while starch can. The difference is in": ("the number of glucose units in each polymer chain", "the way the glucose units are linked (α in starch, β in cellulose)", "the elements present in each of the two polymers", "the solubility of the glucose units in water"),
    "the monomer of natural rubber?": ("ethene, CH₂=CH₂", "isoprene, CH₂=C(CH₃)CH=CH₂", "chloroethene, CH₂=CHCl", "phenylethene, C₆H₅CH=CH₂"),
}


def build():
    build_batch(
        S, "batch_017_chemistry_round4.json", "batch_017_chemistry_round4",
        "Chemistry round 4: two data passages (iron/copper displacement, pH table) and applied items across all fifteen topics, taking Chemistry past 500 curated questions.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
