"""Builds content/batch_006_sciences_round2.json — Physics, Chemistry, Biology round 2 (calculation and
experiment items; numerical answers verified in Python) and the bank-wide retirement rules for one-line
recall questions in every subject.

Run:  python3 scripts/build_content_batch6.py
"""
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_content_batch1 import _balance, _num  # noqa: E402
from distractor_fixes import apply_fixes  # noqa: E402

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(BASE, "content", "batch_006_sciences_round2.json")

PHYS = [
    ("Measurement and Units", "Easy", "A student measures the length of a pencil five times and obtains 12.1 cm, 12.3 cm, 12.2 cm, 12.2 cm and 12.2 cm. The best estimate of the length is", "12.1 cm", "12.2 cm", "12.3 cm", "61.0 cm", "B", "Mean = (12.1 + 12.3 + 12.2 + 12.2 + 12.2)/5 = 61.0/5 = 12.2 cm.", "61/5"),
    ("Measurement and Units", "Medium", "The unit of power expressed in fundamental units is", "kg m s⁻²", "kg m² s⁻²", "kg m² s⁻³", "kg m s⁻¹", "C", "Power = energy/time; energy = force × distance = (kg m s⁻²)(m) = kg m² s⁻²; dividing by s gives kg m² s⁻³.", None),
    ("Scalars and Vectors", "Medium", "A boy walks 3 km east and then 4 km north. His displacement from the starting point is", "1 km", "5 km", "7 km", "12 km", "B", "Displacement is the straight-line distance: √(3² + 4²) = √25 = 5 km (north-east of the start).", "(9+16)**0.5"),
    ("Scalars and Vectors", "Medium", "Two forces of 6 N and 8 N act on a body at right angles to each other. The magnitude of their resultant is", "2 N", "10 N", "14 N", "48 N", "B", "Resultant = √(6² + 8²) = √100 = 10 N.", "(36+64)**0.5"),
    ("Motion", "Medium", "A car travelling at 30 m/s is brought to rest by its brakes in a distance of 90 m. The deceleration is", "3 m/s²", "5 m/s²", "10 m/s²", "15 m/s²", "B", "v² = u² − 2as ⇒ 0 = 900 − 2a(90) ⇒ a = 900/180 = 5 m/s².", "900/180"),
    ("Motion", "Medium", "An object thrown vertically upwards returns to the thrower after 4 s. Taking g = 10 m/s², the initial speed was", "10 m/s", "20 m/s", "40 m/s", "80 m/s", "B", "Time to the top = 2 s; v = u − gt ⇒ 0 = u − 10(2) ⇒ u = 20 m/s.", "10*2"),
    ("Motion", "Hard", "A train accelerates uniformly from 10 m/s to 30 m/s over a distance of 400 m. The time taken is", "10 s", "20 s", "40 s", "80 s", "B", "Average velocity = (10 + 30)/2 = 20 m/s; t = s/v_avg = 400/20 = 20 s.", "400/20"),
    ("Forces and Equilibrium", "Medium", "A uniform metre rule is balanced at the 40 cm mark when a mass of 20 g hangs at the 10 cm mark. The mass of the rule is", "10 g", "20 g", "40 g", "60 g", "D", "Weight of the rule acts at 50 cm. Moments about 40 cm: 20 × 30 = M × 10 ⇒ M = 60 g.", "20*30/10"),
    ("Forces and Equilibrium", "Medium", "A 5 kg block rests on a rough horizontal surface. If the coefficient of static friction is 0.4 and g = 10 m/s², the minimum horizontal force needed to start it moving is", "2 N", "20 N", "50 N", "125 N", "B", "Limiting friction F = μR = 0.4 × (5 × 10) = 20 N.", "0.4*50"),
    ("Work Energy and Power", "Medium", "A stone of mass 2 kg falls from a height of 20 m. Taking g = 10 m/s² and ignoring air resistance, its kinetic energy just before hitting the ground is", "40 J", "200 J", "400 J", "800 J", "C", "All potential energy becomes kinetic: mgh = 2 × 10 × 20 = 400 J.", "2*10*20"),
    ("Work Energy and Power", "Medium", "A pump lifts 200 kg of water through 15 m every minute. Taking g = 10 m/s², the power of the pump is", "50 W", "500 W", "3,000 W", "30,000 W", "B", "Work per minute = mgh = 200 × 10 × 15 = 30,000 J; power = 30,000/60 = 500 W.", "200*10*15/60"),
    ("Momentum and Machines", "Medium", "A gun of mass 5 kg fires a bullet of mass 20 g at 400 m/s. The recoil velocity of the gun is", "0.8 m/s", "1.6 m/s", "8 m/s", "16 m/s", "B", "Momentum conserved: 5 × v = 0.02 × 400 ⇒ v = 8/5 = 1.6 m/s.", "0.02*400/5"),
    ("Momentum and Machines", "Medium", "An inclined plane 5 m long is used to raise a load through a height of 1 m. Its velocity ratio is", "0.2", "1", "5", "6", "C", "VR of an inclined plane = length of slope/height = 5/1 = 5.", "5/1"),
    ("Momentum and Machines", "Hard", "A block and tackle with 4 pulleys is used to lift a load of 600 N with an effort of 200 N. Its efficiency is", "25%", "50%", "75%", "133%", "C", "VR = 4 (number of pulleys); MA = 600/200 = 3; efficiency = 3/4 × 100 = 75%.", "3/4*100"),
    ("Properties of Matter", "Medium", "A wire of length 2 m is stretched by 4 mm when a load of 40 N hangs from it. The load required to stretch a similar wire of the same length by 6 mm is", "20 N", "40 N", "60 N", "80 N", "C", "Hooke's law: force ∝ extension ⇒ F = 40 × 6/4 = 60 N.", "40*6/4"),
    ("Properties of Matter", "Medium", "A body weighs 50 N in air and 30 N when completely immersed in water. The upthrust on the body is", "20 N", "30 N", "50 N", "80 N", "A", "Upthrust = weight in air − weight in water = 50 − 30 = 20 N.", "50-30"),
    ("Properties of Matter", "Hard", "A body weighs 50 N in air and 30 N in water. The relative density of the body is", "0.6", "1.67", "2.5", "5.0", "C", "Relative density = weight in air/upthrust in water = 50/(50 − 30) = 2.5.", "50/20"),
    ("Properties of Matter", "Medium", "A hydraulic press has pistons of area 10 cm² and 500 cm². A force of 40 N on the small piston produces a force on the large piston of", "0.8 N", "80 N", "2,000 N", "20,000 N", "C", "Pressure is transmitted equally: F₂ = F₁ × A₂/A₁ = 40 × 500/10 = 2,000 N.", "40*500/10"),
    ("Heat and Thermal Physics", "Medium", "A metal rod 2.000 m long at 0 °C becomes 2.002 m long at 100 °C. Its linear expansivity is", "1 × 10⁻⁵ /K", "2 × 10⁻⁵ /K", "1 × 10⁻³ /K", "2 × 10⁻³ /K", "A", "α = ΔL/(L₀Δθ) = 0.002/(2 × 100) = 1 × 10⁻⁵ per kelvin.", None),
    ("Heat and Thermal Physics", "Hard", "0.2 kg of water at 80 °C is mixed with 0.3 kg of water at 30 °C. Ignoring heat losses, the final temperature of the mixture is", "45 °C", "50 °C", "55 °C", "60 °C", "B", "Heat lost = heat gained: 0.2(80 − T) = 0.3(T − 30) ⇒ 16 − 0.2T = 0.3T − 9 ⇒ T = 25/0.5 = 50 °C.", "25/0.5"),
    ("Heat and Thermal Physics", "Medium", "A 1 kW electric kettle takes 2 minutes to raise the temperature of 1 kg of water by 25 °C. The energy wasted is (specific heat capacity of water = 4200 J/kg K)", "15 kJ", "105 kJ", "120 kJ", "225 kJ", "A", "Energy supplied = 1000 × 120 = 120,000 J; useful = 1 × 4200 × 25 = 105,000 J; wasted = 15,000 J = 15 kJ.", "(1000*120-4200*25)/1000"),
    ("Heat and Thermal Physics", "Medium", "The temperature of a body is 27 °C. On the kelvin scale this is", "246 K", "273 K", "300 K", "327 K", "C", "K = °C + 273 = 27 + 273 = 300 K.", "27+273"),
    ("Waves", "Medium", "The distance between two successive crests of a water wave is 20 cm and 5 crests pass a point every second. The speed of the wave is", "0.25 m/s", "1 m/s", "4 m/s", "100 m/s", "B", "λ = 0.2 m, f = 5 Hz; v = fλ = 5 × 0.2 = 1 m/s.", "5*0.2"),
    ("Waves", "Medium", "A radio station broadcasts at a frequency of 100 MHz. Taking the speed of radio waves as 3 × 10⁸ m/s, the wavelength is", "0.3 m", "3 m", "30 m", "300 m", "B", "λ = v/f = 3 × 10⁸ / 1 × 10⁸ = 3 m.", "3e8/1e8"),
    ("Sound", "Medium", "A stretched string of length 50 cm vibrates in its fundamental mode with a frequency of 200 Hz. If the length is reduced to 25 cm at the same tension, the new fundamental frequency is", "50 Hz", "100 Hz", "400 Hz", "800 Hz", "C", "For a fixed tension f ∝ 1/L; halving the length doubles the frequency: 400 Hz.", "200*50/25"),
    ("Sound", "Medium", "A ship sends a sound pulse to the sea bed and receives the echo 3 s later. If the speed of sound in water is 1500 m/s, the depth of the sea is", "500 m", "1,125 m", "2,250 m", "4,500 m", "C", "Distance travelled = 1500 × 3 = 4500 m, there and back ⇒ depth = 2250 m.", "1500*3/2"),
    ("Light and Optics", "Medium", "A concave mirror of focal length 10 cm forms a real image 30 cm from the mirror. The object distance is", "7.5 cm", "15 cm", "20 cm", "40 cm", "B", "1/u = 1/f − 1/v = 1/10 − 1/30 = 2/30 ⇒ u = 15 cm.", "1/(1/10-1/30)"),
    ("Light and Optics", "Medium", "An object 2 cm tall is placed 20 cm from a converging lens of focal length 15 cm. The magnification of the image is", "0.75", "1.5", "3", "4", "C", "1/v = 1/15 − 1/20 = 1/60 ⇒ v = 60 cm; m = v/u = 60/20 = 3.", "60/20"),
    ("Light and Optics", "Medium", "The speed of light in a glass of refractive index 1.5 is (speed in air = 3 × 10⁸ m/s)", "1 × 10⁸ m/s", "2 × 10⁸ m/s", "3 × 10⁸ m/s", "4.5 × 10⁸ m/s", "B", "v = c/n = 3 × 10⁸/1.5 = 2 × 10⁸ m/s.", None),
    ("Light and Optics", "Medium", "A person cannot see objects clearly beyond 2 m. The defect and the lens needed to correct it are", "long sight; converging lens", "short sight; diverging lens", "astigmatism; cylindrical lens", "long sight; diverging lens", "B", "Inability to see distant objects is short sight (myopia), corrected with a diverging (concave) lens.", None),
    ("Electricity", "Medium", "Three 6 Ω resistors are connected in parallel and the combination is connected in series with a 4 Ω resistor. The total resistance is", "2 Ω", "6 Ω", "10 Ω", "22 Ω", "B", "Parallel: 6/3 = 2 Ω; series with 4 Ω gives 2 + 4 = 6 Ω.", "6/3+4"),
    ("Electricity", "Hard", "A cell of e.m.f. 1.5 V and internal resistance 0.5 Ω is connected to a 2.5 Ω resistor. The current in the circuit is", "0.5 A", "0.6 A", "0.75 A", "3 A", "A", "I = E/(R + r) = 1.5/(2.5 + 0.5) = 0.5 A.", "1.5/3"),
    ("Electricity", "Hard", "A cell of e.m.f. 1.5 V and internal resistance 0.5 Ω drives a current of 0.5 A through an external resistor. The terminal p.d. of the cell is", "0.25 V", "1.0 V", "1.25 V", "1.5 V", "C", "Terminal p.d. = E − Ir = 1.5 − 0.5 × 0.5 = 1.25 V.", "1.5-0.25"),
    ("Electricity", "Medium", "A wire of resistance 8 Ω is stretched until its length doubles (volume unchanged). Its new resistance is", "4 Ω", "8 Ω", "16 Ω", "32 Ω", "D", "Doubling the length halves the area; R ∝ L/A ⇒ R becomes 8 × 2 × 2 = 32 Ω.", "8*4"),
    ("Electricity", "Medium", "Four 100 W bulbs are used for 5 hours a day for 30 days. The energy consumed is", "15 kWh", "60 kWh", "150 kWh", "600 kWh", "B", "Power = 4 × 100 = 400 W = 0.4 kW; energy = 0.4 × 5 × 30 = 60 kWh.", "0.4*5*30"),
    ("Electricity", "Medium", "Two capacitors of 2 μF and 3 μF are connected in parallel across a 10 V supply. The total charge stored is", "12 μC", "20 μC", "30 μC", "50 μC", "D", "Parallel: C = 2 + 3 = 5 μF; Q = CV = 5 × 10 = 50 μC.", "5*10"),
    ("Magnetism and Electromagnetic Induction", "Medium", "A transformer steps 240 V down to 12 V and delivers 2 A to a lamp. Assuming 100% efficiency, the current in the primary coil is", "0.1 A", "0.4 A", "10 A", "40 A", "A", "Power in = power out: 240 × Iₚ = 12 × 2 ⇒ Iₚ = 24/240 = 0.1 A.", "12*2/240"),
    ("Magnetism and Electromagnetic Induction", "Medium", "A magnet is pushed into a coil connected to a galvanometer and the needle deflects to the right. When the magnet is pulled out at the same speed, the needle", "does not move", "deflects to the right again", "deflects to the left", "deflects to the right with double the reading", "C", "Lenz's law: the induced current reverses when the direction of motion (change of flux) reverses.", None),
    ("Atomic and Nuclear Physics", "Medium", "The activity of a radioactive sample falls to one-eighth of its original value in 24 minutes. Its half-life is", "3 minutes", "6 minutes", "8 minutes", "12 minutes", "C", "1/8 = (1/2)³ — three half-lives in 24 minutes ⇒ half-life = 8 minutes.", "24/3"),
    ("Atomic and Nuclear Physics", "Medium", "When a nucleus emits a beta particle, its", "mass number decreases by 4", "atomic number increases by 1", "atomic number decreases by 2", "mass number increases by 1", "B", "A neutron becomes a proton and an electron (the beta particle) is emitted: mass number unchanged, atomic number +1.", None),
    ("Electronics and Modern Physics", "Medium", "Light of frequency 6 × 10¹⁴ Hz falls on a metal whose work function is 2 × 10⁻¹⁹ J. Taking h = 6.6 × 10⁻³⁴ J s, the maximum kinetic energy of the emitted electrons is", "1.96 × 10⁻¹⁹ J", "3.96 × 10⁻¹⁹ J", "5.96 × 10⁻¹⁹ J", "2.0 × 10⁻¹⁹ J", "A", "KE = hf − W = 6.6 × 10⁻³⁴ × 6 × 10¹⁴ − 2 × 10⁻¹⁹ = 3.96 × 10⁻¹⁹ − 2 × 10⁻¹⁹ = 1.96 × 10⁻¹⁹ J.", None),
    ("Electronics and Modern Physics", "Medium", "A p-n junction diode conducts easily when", "the p-side is connected to the negative terminal of the battery", "it is reverse biased", "the p-side is connected to the positive terminal of the battery", "no voltage is applied", "C", "Forward bias (p to positive, n to negative) narrows the depletion layer and allows current to flow.", None),
]

CHEM = [
    ("Atomic Structure", "Medium", "An element has the electronic configuration 1s² 2s² 2p⁶ 3s² 3p⁴. The element", "is in Group 4", "forms a 2− ion", "is a metal", "has 4 electrons in its outermost shell", "B", "The outer shell 3s² 3p⁴ holds 6 electrons (Group 6); it gains 2 electrons to form X²⁻ (like sulphur).", None),
    ("Atomic Structure", "Medium", "Which pair of species are isotopes?", "²³Na and ²⁴Mg", "³⁵Cl and ³⁷Cl", "¹⁶O and ¹⁶O²⁻", "¹²C and ¹⁴N", "B", "Isotopes are atoms of the same element (same atomic number) with different mass numbers: ³⁵Cl and ³⁷Cl.", None),
    ("Periodic Table", "Medium", "Elements X, Y and Z have atomic numbers 11, 17 and 18 respectively. The compound most likely formed between X and Y is", "covalent XY", "ionic XY", "ionic X₂Y", "covalent XY₂", "B", "X (2,8,1) is a metal that loses one electron; Y (2,8,7) is a non-metal that gains one; they form the ionic compound XY (like NaCl). Z (2,8,8) is a noble gas.", None),
    ("Chemical Bonding", "Medium", "Ammonia (NH₃) reacts with a hydrogen ion to form the ammonium ion, NH₄⁺. The bond formed between NH₃ and H⁺ is", "ionic", "covalent", "co-ordinate (dative) covalent", "metallic", "C", "Nitrogen donates its lone pair to H⁺, which contributes no electrons — a dative covalent bond.", None),
    ("Chemical Bonding", "Medium", "Which substance conducts electricity in the molten state but not in the solid state?", "copper", "sodium chloride", "graphite", "sulphur", "B", "Ionic solids have fixed ions; when melted the ions become mobile and conduct. Copper and graphite conduct as solids; sulphur never does.", None),
    ("Mole Concept and Stoichiometry", "Medium", "The volume of 0.5 mol/dm³ hydrochloric acid needed to neutralise 2.0 g of sodium hydroxide is (NaOH = 40)", "25 cm³", "50 cm³", "100 cm³", "200 cm³", "C", "n(NaOH) = 2/40 = 0.05 mol = n(HCl); V = n/C = 0.05/0.5 = 0.1 dm³ = 100 cm³.", "0.05/0.5*1000"),
    ("Mole Concept and Stoichiometry", "Medium", "What mass of magnesium oxide is produced when 4.8 g of magnesium burns completely in oxygen? (Mg = 24, O = 16)", "4.0 g", "6.4 g", "8.0 g", "12.8 g", "C", "2Mg + O₂ → 2MgO; n(Mg) = 4.8/24 = 0.2 mol ⇒ 0.2 mol MgO × 40 g/mol = 8.0 g.", "4.8/24*40"),
    ("Mole Concept and Stoichiometry", "Hard", "A hydrocarbon contains 85.7% carbon by mass and has a relative molecular mass of 42. Its molecular formula is (C = 12, H = 1)", "CH₂", "C₂H₄", "C₃H₆", "C₄H₈", "C", "C : H = 85.7/12 : 14.3/1 = 7.14 : 14.3 = 1 : 2 ⇒ empirical formula CH₂ (mass 14); 42/14 = 3 ⇒ C₃H₆.", None),
    ("Mole Concept and Stoichiometry", "Medium", "How many moles of oxygen atoms are present in 0.5 mol of Al₂(SO₄)₃?", "3", "4", "6", "12", "C", "Each formula unit has 3 × 4 = 12 oxygen atoms; 0.5 × 12 = 6 mol of O atoms.", "0.5*12"),
    ("Mole Concept and Stoichiometry", "Medium", "2.24 dm³ of a gas at s.t.p. has a mass of 6.4 g. Its relative molecular mass is (molar volume = 22.4 dm³)", "16", "32", "64", "128", "C", "n = 2.24/22.4 = 0.1 mol; M = 6.4/0.1 = 64 (sulphur(IV) oxide, SO₂).", "6.4/(2.24/22.4)"),
    ("States of Matter", "Medium", "A gas at 27 °C and 1 atm is heated to 327 °C at constant volume. The new pressure is", "0.5 atm", "1.5 atm", "2 atm", "12 atm", "C", "P ∝ T at constant volume: P₂ = 1 × 600/300 = 2 atm.", "600/300"),
    ("States of Matter", "Medium", "A sealed balloon contains 2 dm³ of air at 1 atm. Its volume when the external pressure falls to 0.8 atm at the same temperature is", "1.6 dm³", "2.5 dm³", "2.8 dm³", "0.4 dm³", "B", "Boyle's law: V₂ = P₁V₁/P₂ = 1 × 2/0.8 = 2.5 dm³.", "2/0.8"),
    ("Acids Bases and Salts", "Medium", "20 cm³ of 0.1 mol/dm³ sodium hydroxide is mixed with 20 cm³ of 0.1 mol/dm³ hydrochloric acid. The pH of the resulting solution is", "1", "7", "13", "14", "B", "Equal moles of a strong acid and strong base neutralise completely to give a neutral salt solution, pH 7.", None),
    ("Acids Bases and Salts", "Medium", "A solution has a hydrogen-ion concentration of 1 × 10⁻⁵ mol/dm³. The solution is", "strongly acidic with pH 5", "weakly acidic with pH 5", "alkaline with pH 9", "neutral", "B", "pH = −log(10⁻⁵) = 5, below 7 but only mildly acidic.", None),
    ("Acids Bases and Salts", "Medium", "Which of the following methods is most suitable for preparing an insoluble salt such as barium tetraoxosulphate(VI)?", "neutralisation followed by evaporation", "double decomposition (precipitation)", "reaction of a metal with an acid", "direct combination of the elements", "B", "Mixing solutions of soluble salts (e.g. BaCl₂ + Na₂SO₄) precipitates the insoluble salt, which is filtered off and washed.", None),
    ("Acids Bases and Salts", "Medium", "When a few drops of universal indicator are added to a solution of sodium trioxocarbonate(IV), the colour observed is", "red", "orange", "green", "blue or purple", "D", "Na₂CO₃ is a salt of a strong base and weak acid; it hydrolyses to give an alkaline solution (pH ≈ 11).", None),
    ("Chemical Reactions", "Medium", "In the reaction 2FeCl₂ + Cl₂ → 2FeCl₃, the substance being reduced is", "FeCl₂", "Cl₂", "FeCl₃", "Fe²⁺", "B", "Chlorine gains electrons (0 → −1); it is reduced and acts as the oxidising agent. Iron is oxidised from +2 to +3.", None),
    ("Chemical Reactions", "Medium", "What mass of copper(II) oxide is needed to react completely with 20 cm³ of 2.0 mol/dm³ tetraoxosulphate(VI) acid? (CuO = 80)", "1.6 g", "3.2 g", "6.4 g", "8.0 g", "B", "CuO + H₂SO₄ → CuSO₄ + H₂O. n(acid) = 2 × 0.02 = 0.04 mol = n(CuO); mass = 0.04 × 80 = 3.2 g.", "2*0.02*80"),
    ("Energy and Rates of Reaction", "Medium", "A student adds 1 g of powdered zinc to acid and, in a second experiment, 1 g of zinc granules to the same acid. The powdered zinc reacts faster because", "it has a lower activation energy", "it has a larger surface area", "it is purer", "it is hotter", "B", "Smaller particles expose more surface to the acid, so more successful collisions occur per second.", None),
    ("Energy and Rates of Reaction", "Medium", "In an energy profile diagram, the products lie at a higher energy level than the reactants. The reaction is", "exothermic", "endothermic", "spontaneous", "catalytic", "B", "Energy is absorbed to raise the products above the reactants: ΔH is positive (endothermic).", None),
    ("Energy and Rates of Reaction", "Medium", "A catalyst speeds up a reaction by", "raising the temperature", "increasing the concentration of reactants", "providing an alternative path of lower activation energy", "increasing the energy of the products", "C", "A catalyst lowers the activation energy so that more colliding molecules can react.", None),
    ("Chemical Equilibrium", "Medium", "For the equilibrium 2SO₂(g) + O₂(g) ⇌ 2SO₃(g), ΔH = −196 kJ, the yield of SO₃ is decreased by", "increasing the pressure", "increasing the temperature", "removing SO₃ as it forms", "adding more O₂", "B", "The forward reaction is exothermic, so raising the temperature shifts the equilibrium to the left (Le Chatelier).", None),
    ("Chemical Equilibrium", "Medium", "The solubility of a salt is 20 g per 100 g of water at 30 °C. A solution containing 15 g of the salt in 50 g of water at 30 °C is", "unsaturated", "saturated", "supersaturated", "dilute", "C", "50 g of water dissolves at most 10 g at 30 °C; 15 g exceeds this, so the solution holds more than saturation — supersaturated.", None),
    ("Electrochemistry", "Medium", "In the electrolysis of concentrated sodium chloride solution using carbon electrodes, the product at the anode is", "hydrogen", "sodium", "chlorine", "oxygen", "C", "In concentrated brine, Cl⁻ is discharged in preference to OH⁻ at the anode, giving chlorine; hydrogen forms at the cathode.", None),
    ("Electrochemistry", "Medium", "A current of 2 A flows for 16 minutes 5 seconds through molten aluminium oxide. The mass of aluminium deposited is (Al = 27, F = 96,500 C/mol)", "0.09 g", "0.18 g", "0.27 g", "0.54 g", "B", "Q = 2 × 965 = 1930 C = 0.02 F; Al³⁺ + 3e⁻ → Al ⇒ 0.02/3 mol × 27 = 0.18 g.", "2*965/96500/3*27"),
    ("Electrochemistry", "Medium", "In an electrochemical cell the electrode where oxidation occurs is the", "cathode", "anode", "salt bridge", "electrolyte", "B", "Oxidation always takes place at the anode (An Ox); reduction at the cathode (Red Cat).", None),
    ("Water Air and Environmental Chemistry", "Medium", "A sample of water still forms a scum with soap even after boiling. The hardness is most likely due to", "calcium hydrogentrioxocarbonate(IV)", "magnesium hydrogentrioxocarbonate(IV)", "calcium tetraoxosulphate(VI)", "dissolved carbon(IV) oxide", "C", "Permanent hardness, not removed by boiling, is caused by the sulphates and chlorides of calcium and magnesium.", None),
    ("Water Air and Environmental Chemistry", "Medium", "The gas mainly responsible for the depletion of the ozone layer is", "carbon(IV) oxide", "sulphur(IV) oxide", "chlorofluorocarbons", "nitrogen", "C", "CFCs release chlorine atoms in the stratosphere that catalyse the breakdown of ozone.", None),
    ("Metals and Non-Metals", "Medium", "Iron is extracted from haematite in the blast furnace. The reducing agent that converts Fe₂O₃ to iron is", "carbon(IV) oxide", "carbon(II) oxide", "limestone", "oxygen", "B", "Fe₂O₃ + 3CO → 2Fe + 3CO₂; carbon(II) oxide formed from coke is the main reducing agent.", None),
    ("Metals and Non-Metals", "Medium", "A metal is extracted from its molten chloride by electrolysis rather than by reduction with carbon because the metal", "is very unreactive", "is more reactive than carbon", "is a liquid at room temperature", "forms a covalent chloride", "B", "Metals above carbon in the reactivity series (Na, Ca, Mg, Al) cannot be reduced by carbon and are extracted by electrolysis.", None),
    ("Metals and Non-Metals", "Medium", "Aluminium does not corrode as readily as iron because", "aluminium is less reactive than iron", "aluminium forms a thin, tough oxide layer that protects it", "aluminium does not react with oxygen", "iron is a transition metal", "B", "The adherent Al₂O₃ film seals the surface; iron's rust is porous and flakes off.", None),
    ("Organic Chemistry", "Medium", "The compound CH₃CH₂CH₂OH and CH₃CH(OH)CH₃ are", "isomers", "homologues", "allotropes", "polymers", "A", "Both are C₃H₈O (propan-1-ol and propan-2-ol) with different structures — isomers.", None),
    ("Organic Chemistry", "Medium", "Ethanol is dehydrated by passing its vapour over heated aluminium oxide. The product is", "ethanal", "ethanoic acid", "ethene", "ethane", "C", "Dehydration removes water: C₂H₅OH → C₂H₄ + H₂O.", None),
    ("Organic Chemistry", "Medium", "The IUPAC name of CH₃CH₂CH(CH₃)CH₃ is", "2-methylbutane", "3-methylbutane", "pentane", "2-methylpropane", "A", "The longest chain has 4 carbons (butane), with a methyl group on carbon 2 when numbered from the end nearest the branch.", None),
    ("Organic Chemistry", "Medium", "When propene is polymerised, the product is", "polyethene", "polypropene", "polystyrene", "polyvinyl chloride", "B", "Addition polymerisation of propene monomers gives poly(propene).", None),
    ("Organic Chemistry", "Medium", "Soap is made by boiling a fat or oil with", "dilute hydrochloric acid", "concentrated sodium hydroxide", "ethanol", "sodium chloride", "B", "Saponification: fat + NaOH → soap (sodium salt of fatty acids) + glycerol.", None),
    ("Chemistry of Biomolecules", "Medium", "A food sample turns purple when warmed with sodium hydroxide and a few drops of copper(II) tetraoxosulphate(VI) solution. The food contains", "starch", "glucose", "protein", "fat", "C", "The biuret test gives a violet/purple colour with proteins (peptide bonds).", None),
    ("Industrial Chemistry", "Medium", "In the Haber process the conditions used are about 450 °C, 200 atm and an iron catalyst. The moderately high temperature is chosen because", "it gives the highest yield of ammonia", "it is a compromise between yield and rate of reaction", "iron only works above 400 °C", "ammonia decomposes at low temperatures", "B", "Low temperature favours yield (exothermic) but makes the reaction too slow; 450 °C balances yield against speed.", None),
    ("Industrial Chemistry", "Medium", "The raw materials for the Solvay process for making sodium trioxocarbonate(IV) are", "sodium chloride, limestone and ammonia", "sodium hydroxide and carbon(IV) oxide", "sodium and oxygen", "sea water and chlorine", "A", "Brine (NaCl), limestone (for CO₂) and ammonia (recycled) are the Solvay inputs.", None),
    ("Periodic Table", "Medium", "Going down Group 7 from fluorine to iodine, the elements", "become more reactive", "become less reactive", "change from gases to metals", "form more stable hydrides", "B", "Reactivity of the halogens decreases down the group because the outer shell is farther from the nucleus and gains electrons less readily.", None),
]

BIO = [
    ("Cell Structure and Organization", "Medium", "A student observed a thin slice of onion under the microscope and saw cells with a cell wall and nucleus but no chloroplasts. This is because", "onion cells are animal cells", "the bulb grows underground and does not photosynthesise", "the slice was too thin", "chloroplasts are found only in roots", "B", "Onion bulb scales are underground storage tissue; they have plant cell walls but no chloroplasts because they receive no light."),
    ("Cell Structure and Organization", "Medium", "Using a microscope with a ×10 eyepiece and a ×40 objective, a cell appears 2 mm wide. Its actual width is", "0.005 mm", "0.05 mm", "0.5 mm", "800 mm", "A", "Total magnification = 10 × 40 = 400; actual size = image size/magnification = 2/400 = 0.005 mm."),
    ("Variety of Organisms", "Medium", "An organism is single-celled, has no true nucleus and no membrane-bound organelles. It belongs to the kingdom", "Protista", "Fungi", "Monera (Prokaryotae)", "Plantae", "C", "Prokaryotes (bacteria and blue-green algae) lack a true nucleus and are placed in Monera."),
    ("Variety of Organisms", "Medium", "A plant has parallel-veined leaves, fibrous roots and flower parts in threes. It is most likely", "a dicotyledon", "a monocotyledon", "a fern", "a gymnosperm", "B", "Parallel venation, fibrous roots and trimerous flowers are monocot features (e.g. maize, grasses)."),
    ("Nutrition", "Medium", "A patient is unable to digest fats properly after the removal of the gall bladder because", "no lipase is produced", "bile that emulsifies fats can no longer be stored and released in quantity", "the stomach cannot churn food", "the pancreas stops working", "B", "The gall bladder stores bile; bile salts emulsify fats into droplets so that lipase can act on them."),
    ("Nutrition", "Medium", "A child has bow legs and a deformed chest. The child most likely lacks", "vitamin A", "vitamin C", "vitamin D and calcium", "iron", "C", "Rickets, with soft, bent bones, results from a deficiency of vitamin D and calcium."),
    ("Nutrition", "Medium", "A child has a swollen belly, thin limbs and reddish hair. The condition is most likely", "kwashiorkor", "marasmus", "scurvy", "beriberi", "A", "Kwashiorkor is protein deficiency: oedema (swollen belly), wasted muscles and discoloured hair."),
    ("Nutrition", "Medium", "In an experiment, a test tube containing starch solution and saliva was kept at 37 °C. After 20 minutes, iodine solution gave no blue-black colour. This shows that", "the starch had been converted to sugar by salivary amylase", "iodine does not react with starch at 37 °C", "saliva destroys iodine", "the starch had evaporated", "A", "Amylase in saliva hydrolyses starch to maltose at body temperature, so no starch is left to react with iodine."),
    ("Nutrition", "Medium", "The same starch-saliva experiment was repeated with the saliva first boiled. Iodine turned blue-black. This is because boiling", "increased the enzyme's activity", "denatured the enzyme, so the starch was not digested", "converted starch to glucose", "made the iodine stronger", "B", "Enzymes are proteins; boiling changes their shape permanently (denaturation) and they stop working."),
    ("Transport", "Medium", "A leafy shoot was placed in water containing red dye. After some hours, a cross-section of the stem showed red colour only in certain tissues. Those tissues were", "phloem", "xylem", "cortex", "pith", "B", "Water and dissolved substances move up the plant through xylem vessels, which the dye stained."),
    ("Transport", "Medium", "A ring of bark (containing phloem) was removed from around a tree trunk. After some weeks the bark above the ring swelled because", "water accumulated above the ring", "sugars moving down from the leaves could not pass the ring", "the xylem was blocked", "the roots sent food upwards", "B", "Ringing removes phloem; food translocated downwards from the leaves accumulates above the cut."),
    ("Transport", "Medium", "A person's red blood cell count is low and the cells are small and pale. The person most likely lacks", "vitamin C", "iodine", "iron", "calcium", "C", "Iron is needed to make haemoglobin; its shortage causes iron-deficiency anaemia."),
    ("Transport", "Medium", "Blood leaving the lungs through the pulmonary vein is", "deoxygenated and goes to the right atrium", "oxygenated and goes to the left atrium", "oxygenated and goes to the right ventricle", "deoxygenated and goes to the left ventricle", "B", "The pulmonary vein is the only vein carrying oxygenated blood; it enters the left atrium."),
    ("Respiration", "Medium", "Two flasks of germinating seeds were set up; the seeds in the second flask were first boiled. A thermometer in the first flask showed a rise in temperature, the second showed none. This shows that", "boiled seeds respire faster", "living seeds release heat during respiration", "boiling adds heat to seeds", "germinating seeds absorb heat", "B", "Respiration releases energy, some as heat; killed (boiled) seeds do not respire."),
    ("Respiration", "Medium", "When a person breathes out, the diaphragm", "contracts and flattens", "relaxes and becomes dome-shaped", "moves downwards", "pushes the ribs outwards", "B", "Expiration: the diaphragm relaxes and rises, the ribs fall, chest volume decreases and air is forced out."),
    ("Respiration", "Medium", "Yeast added to a sugar solution in a warm place produces bubbles of gas and a smell of alcohol. The process is", "aerobic respiration", "anaerobic respiration (fermentation)", "photosynthesis", "transpiration", "B", "Yeast ferments glucose to ethanol and carbon(IV) oxide in the absence of oxygen."),
    ("Excretion", "Medium", "Glucose was found in a patient's urine. This suggests a problem with", "the kidney's ability to reabsorb glucose or with insulin production", "the liver's production of bile", "the lungs", "the sweat glands", "A", "Normally all glucose is reabsorbed in the proximal tubule; excess blood glucose (diabetes) overwhelms reabsorption."),
    ("Excretion", "Medium", "On a cold day a person passes more dilute urine than on a hot day because", "the kidneys work harder in cold weather", "less water is lost as sweat, so less ADH is released and less water is reabsorbed", "the bladder expands in cold weather", "cold water is drunk", "B", "With less sweating the blood is more dilute; ADH secretion falls and the kidney tubules reabsorb less water."),
    ("Support and Movement", "Medium", "A plant left unwatered wilts because", "its xylem vessels break", "its cells lose turgor as water leaves the vacuoles", "its cell walls dissolve", "photosynthesis stops", "B", "Turgor pressure supports soft tissues; when water is short the cells become flaccid and the plant droops."),
    ("Support and Movement", "Medium", "The hinge joint at the elbow allows movement", "in all directions", "in one plane only", "by rotation only", "by gliding only", "B", "Hinge joints (elbow, knee) permit bending and straightening in one plane; ball-and-socket joints move in all directions."),
    ("Reproduction", "Medium", "A flower has brightly coloured petals, a strong scent, nectar and sticky pollen grains. It is adapted for pollination by", "wind", "water", "insects", "gravity", "C", "Colour, scent and nectar attract insects; sticky pollen clings to their bodies."),
    ("Reproduction", "Medium", "In humans, the fusion of a sperm carrying a Y chromosome with an ovum produces", "a female child", "a male child", "twins", "an infertile child", "B", "The ovum always carries X; X + Y gives a male (XY)."),
    ("Reproduction", "Medium", "The part of the mammalian female reproductive system where fertilisation normally takes place is the", "ovary", "uterus", "oviduct (fallopian tube)", "vagina", "C", "Sperm meet the ovum in the oviduct; the zygote then travels to the uterus to implant."),
    ("Growth", "Medium", "A germinating bean seed was marked with ink lines at equal intervals along the radicle. After two days the lines just behind the tip were farthest apart. This shows that", "growth occurs equally along the root", "the region of elongation lies just behind the root tip", "the root tip does not grow", "the ink stimulated growth", "B", "Cells produced at the tip (meristem) elongate in the zone just behind it, spreading the marks."),
    ("Growth", "Medium", "Seeds soaked in water and kept in a warm, dark, airy cupboard germinated, while identical seeds kept in a refrigerator did not. The experiment shows that germination requires", "light", "suitable temperature", "soil", "carbon(IV) oxide", "B", "Both sets had water and air; only the temperature differed."),
    ("Coordination and Control", "Medium", "A boy walking from bright sunlight into a dim room cannot see clearly at first. During this time his", "pupils constrict", "pupils dilate to admit more light", "lenses become thinner", "corneas thicken", "B", "The iris reflex widens the pupil in dim light; adjustment takes a few moments."),
    ("Coordination and Control", "Medium", "A person with goitre (swollen neck) most likely has a deficiency of", "iron", "iodine", "calcium", "vitamin A", "B", "The thyroid gland enlarges when it cannot make enough thyroxine for lack of iodine."),
    ("Coordination and Control", "Medium", "A student frightened by a snake finds her heart racing and her mouth dry. The hormone responsible is", "insulin", "adrenaline", "thyroxine", "oestrogen", "B", "Adrenaline, from the adrenal glands, prepares the body for 'fight or flight'."),
    ("Ecology", "Medium", "In a pond, small fish eat water fleas which feed on algae; herons eat the fish. The organisms with the greatest total biomass are the", "herons", "small fish", "water fleas", "algae", "D", "Energy is lost at each trophic level, so producers (algae) have the greatest biomass in a normal pyramid."),
    ("Ecology", "Medium", "Lichens growing on a bare rock surface are an example of", "climax vegetation", "pioneer organisms in primary succession", "parasites", "secondary succession", "B", "Lichens colonise bare rock first, breaking it down to form soil for later communities."),
    ("Ecology", "Medium", "A tapeworm lives in the intestine of a man, absorbing digested food and causing him harm. The relationship is", "mutualism", "commensalism", "parasitism", "saprophytism", "C", "One organism benefits at the expense of the living host — parasitism."),
    ("Ecology", "Medium", "Bacteria in the root nodules of legumes fix nitrogen for the plant and receive sugars in return. This relationship is", "parasitism", "mutualism (symbiosis)", "predation", "competition", "B", "Both partners benefit — mutualism."),
    ("Soil", "Medium", "Two equal samples of soil were heated: sample A lost 15% of its mass, sample B lost 3%. Sample A most likely contains more", "sand", "humus (organic matter)", "clay", "gravel", "B", "Strong heating burns off organic matter; the greater loss shows more humus."),
    ("Soil", "Medium", "A farmer notices that his crops grow poorly in a waterlogged field. The main reason is that", "there is too much humus", "the roots lack oxygen for respiration", "the soil is too warm", "there are too many earthworms", "B", "Waterlogging fills air spaces; roots cannot respire and nutrient uptake fails."),
    ("Humans and Environment", "Medium", "Repeated spraying of a farm with the same insecticide became less effective after a few years because", "the insecticide evaporated", "resistant insects survived and multiplied", "the crops absorbed the insecticide", "the farmer used too little", "B", "Natural selection: the few resistant insects survive each spraying and pass on their resistance."),
    ("Humans and Environment", "Medium", "The main reason why farmers practise crop rotation with legumes is that legumes", "need little water", "add nitrogen to the soil through root-nodule bacteria", "have deep roots", "grow quickly", "B", "Rhizobium in legume nodules fixes atmospheric nitrogen, enriching the soil for the next crop."),
    ("Heredity and Variation", "Medium", "A man with blood group A (genotype IᴬIᴼ) marries a woman with blood group B (IᴮIᴼ). The percentage of their children expected to have blood group O is", "0%", "25%", "50%", "75%", "B", "Gametes Iᴬ, i × Iᴮ, i give IᴬIᴮ, Iᴬi, Iᴮi, ii — one in four (25%) is ii (group O)."),
    ("Heredity and Variation", "Medium", "Which of the following is an example of discontinuous variation in humans?", "height", "body mass", "skin colour", "ability to roll the tongue", "D", "Tongue rolling is either present or absent (discrete classes); height, mass and skin colour vary continuously."),
    ("Heredity and Variation", "Medium", "A haemophiliac man marries a woman who is not a carrier. Their sons will be", "all haemophiliac", "all normal", "50% haemophiliac", "all carriers", "B", "Sons receive the Y chromosome from the father and a normal X from the mother; they are all normal. Daughters will all be carriers."),
    ("Evolution", "Medium", "The forelimbs of a bat, a whale and a man have the same basic bone structure but different functions. This is evidence of evolution from", "analogous structures", "homologous structures", "vestigial structures", "fossils", "B", "Homologous structures share a common origin, suggesting a common ancestor."),
]

# Bank-wide retirement of one-line recall items (tier-0 only; keep at least 150 active per subject)
DEACT = []
for subj in ("Biology", "Chemistry", "Christian Religious Studies", "Commerce", "Economics", "Government",
             "Islamic Religious Studies", "Literature in English", "Physics", "Use of English"):
    DEACT.append({"subject": subj, "max_length": 40, "no_digit": True, "keep_at_least": 150,
                  "reason": "one-line recall stems under 40 characters"})
    DEACT.append({"subject": subj, "starts_with": ["What is ", "What are ", "Define ", "Which of these is the definition", "What does the term", "The definition of "],
                  "keep_at_least": 150, "reason": "definition-style stems"})


def build():
    questions, bad = [], []
    for subject, rows in (("Physics", PHYS), ("Chemistry", CHEM)):
        for topic, diff, q, a, b, c, d, ans, exp, verify in rows:
            item = {"subject": subject, "topic": topic, "difficulty": diff, "q": q, "A": a, "B": b, "C": c, "D": d, "answer": ans, "explanation": exp}
            if verify:
                expected = eval(verify, {"math": math})
                got = _num(item[ans])
                if got is None or abs(got - expected) > max(0.01 * abs(expected), 0.006):
                    bad.append((q[:60], ans, item[ans], expected))
            questions.append(item)
    for topic, diff, q, a, b, c, d, ans, exp in BIO:
        questions.append({"subject": "Biology", "topic": topic, "difficulty": diff, "q": q, "A": a, "B": b, "C": c, "D": d, "answer": ans, "explanation": exp})
    if bad:
        for b_ in bad:
            print("MISMATCH:", b_)
        sys.exit("Verification failed — file not written.")
    apply_fixes(questions)
    _balance(questions)
    texts = [x["q"] for x in questions]
    assert len(texts) == len(set(texts)), "duplicate question text"
    assert all(x["answer"] in "ABCD" and all(x[k] for k in "ABCD") for x in questions)
    batch = {
        "batch_id": "batch_006_sciences_round2",
        "exam_type": "JAMB",
        "note": "Physics/Chemistry/Biology round 2 (verified calculations, experiment-based items) + bank-wide retirement of one-line recall stems in every subject.",
        "passages": [],
        "questions": questions,
        "deactivate": DEACT,
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(batch, fh, ensure_ascii=False, indent=1)
    from collections import Counter
    print(f"wrote {OUT}: {len(questions)} questions")
    print("answer letters:", dict(Counter(x['answer'] for x in questions)))
    print("per subject:", dict(Counter(x['subject'] for x in questions)))


if __name__ == "__main__":
    build()
