"""Builds content/batch_003_econ_govt_commerce.json — applied Economics, Government and Commerce.
Every Economics/Commerce calculation carries a `verify` expression that is evaluated before writing.

Run:  python3 scripts/build_content_batch3.py
"""
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_content_batch1 import _balance, _num  # noqa: E402

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(BASE, "content", "batch_003_econ_govt_commerce.json")

# (topic, difficulty, question, A, B, C, D, answer, explanation, verify)
ECON = [
    ("Scarcity, Choice and Opportunity Cost", "Easy", "Ngozi has ₦2,000 and can buy either a textbook or a pair of sandals, each costing ₦2,000. She buys the textbook. Her opportunity cost is", "the ₦2,000 she spent", "the pair of sandals", "the textbook", "both the textbook and the sandals", "B", "Opportunity cost is the next best alternative forgone — the sandals she could not buy, not the money itself.", None),
    ("Scale of Preference", "Easy", "A student lists her wants in order: (1) JAMB form, (2) textbooks, (3) a new phone, (4) shoes. With money for only two items she buys the form and the textbooks. Her list illustrates", "a scale of preference", "division of labour", "the law of diminishing returns", "specialisation", "A", "A scale of preference ranks wants in order of importance so that the most pressing ones are satisfied first with limited resources.", None),
    ("Basic Economic Concepts", "Medium", "Which of the following is a positive economic statement?", "The government should subsidise petrol", "An increase in the price of petrol raises transport fares", "Nigerians deserve cheaper electricity", "Taxes on the rich ought to be higher", "B", "A positive statement describes what is and can be tested against facts; statements with 'should', 'ought' or 'deserve' are normative (value judgements).", None),
    ("Economic Systems", "Medium", "In a country the state owns the major means of production and a central planning body decides what to produce, how to produce it and for whom. This is", "capitalism", "a mixed economy", "a command economy", "a traditional economy", "C", "State ownership plus central planning are the defining features of a command (planned/socialist) economy.", None),
    ("Production", "Easy", "A carpenter buys planks, makes chairs and sells them to a furniture shop, which sells them to customers. The carpenter's activity is an example of", "primary production", "secondary production", "tertiary production", "direct services", "B", "Turning raw materials (planks) into finished goods (chairs) is manufacturing — secondary production. Extraction is primary; selling and services are tertiary.", None),
    ("Factors of Production", "Easy", "Mrs Bello used her savings, hired two tailors, rented a shop and bore the risk of opening a fashion business. The factor of production she herself supplies is", "land", "labour", "capital", "entrepreneurship", "D", "Organising the other factors and bearing the risk of the business is the role of the entrepreneur.", None),
    ("Division of Labour and Specialization", "Medium", "In a Nnewi shoe factory one worker cuts the leather, another stitches it and a third fixes the soles. A likely disadvantage of this arrangement is", "a fall in the total output of the factory", "monotony and loss of all-round craftsmanship", "a rise in the average cost of each pair of shoes", "reduced scope for the use of machinery", "B", "Division of labour raises output and lowers unit cost, but repeating one small task is boring and workers no longer learn the whole craft.", None),
    ("Demand", "Easy", "The price of a brand of noodles stayed the same, yet its sales in Lagos fell sharply after a rival brand cut its price. This is a change in", "quantity demanded", "demand", "supply", "quantity supplied", "B", "A change caused by something other than the good's own price (here, the price of a substitute) shifts the whole demand curve — a change in demand.", None),
    ("Supply", "Easy", "After a good rainy season, tomato farmers brought far more tomatoes to Mile 12 market at every price. On a diagram this is shown as", "a movement along the supply curve", "a rightward shift of the supply curve", "a leftward shift of the supply curve", "a movement along the demand curve", "B", "More supplied at every price means the supply curve shifts to the right; a movement along the curve happens only when the good's own price changes.", None),
    ("Price Determination", "Medium", "In a market, demand is Qd = 100 − 2P and supply is Qs = 20 + 2P. The equilibrium price is", "₦15", "₦20", "₦25", "₦40", "B", "At equilibrium Qd = Qs: 100 − 2P = 20 + 2P ⇒ 80 = 4P ⇒ P = ₦20.", "(100-20)/4"),
    ("Price Determination", "Medium", "If demand is Qd = 100 − 2P and supply is Qs = 20 + 2P, the equilibrium quantity is", "40 units", "60 units", "80 units", "100 units", "B", "Equilibrium price is ₦20 (100 − 2P = 20 + 2P). Substituting: Q = 100 − 2(20) = 60 units.", "100-2*20"),
    ("Price Determination", "Medium", "The government fixes the price of a bag of rice below the equilibrium price. The likely result is", "a surplus of rice", "a shortage of rice and black-marketing", "a fall in the demand for rice", "an increase in the supply of rice", "B", "At a price below equilibrium, quantity demanded exceeds quantity supplied; the shortage encourages hoarding and black-market sales above the official price.", None),
    ("Elasticity of Demand and Supply", "Medium", "When the price of a good rose from ₦50 to ₦60, the quantity demanded fell from 200 to 150 units. Using the original values, the price elasticity of demand is", "0.4", "0.8", "1.25", "2.5", "C", "% change in quantity = 50/200 = 25%; % change in price = 10/50 = 20%; elasticity = 25/20 = 1.25 (elastic).", "(50/200)/(10/50)"),
    ("Elasticity of Demand and Supply", "Medium", "The demand for a product is price inelastic. If the seller raises the price, total revenue will", "fall", "rise", "remain unchanged", "fall to zero", "B", "With inelastic demand the percentage fall in quantity is smaller than the percentage rise in price, so total revenue (price × quantity) increases.", None),
    ("Elasticity of Demand and Supply", "Hard", "A 10% rise in the price of garri led to a 5% rise in the quantity of rice demanded. The cross elasticity of demand between rice and garri is ______ and the two goods are ______.", "0.5; substitutes", "2; complements", "−0.5; complements", "0.5; complements", "A", "Cross elasticity = 5%/10% = +0.5. A positive value means the goods are substitutes: dearer garri pushes consumers towards rice.", "5/10"),
    ("Elasticity of Demand and Supply", "Medium", "When a consumer's monthly income rose from ₦40,000 to ₦50,000, his purchase of eggs rose from 20 to 30 crates. The income elasticity of demand for eggs is", "0.5", "1", "2", "4", "C", "% change in quantity = 10/20 = 50%; % change in income = 10,000/40,000 = 25%; income elasticity = 50/25 = 2 (a normal, income-elastic good).", "(10/20)/(10000/40000)"),
    ("Consumer Behaviour", "Medium", "A thirsty student gains 10 utils from the first sachet of water, 7 from the second, 4 from the third and 1 from the fourth. The total utility from three sachets is", "4 utils", "7 utils", "21 utils", "22 utils", "C", "Total utility is the sum of the marginal utilities: 10 + 7 + 4 = 21 utils.", "10+7+4"),
    ("Consumer Behaviour", "Easy", "A thirsty student gains 10 utils from the first sachet of water, 7 from the second, 4 from the third and 1 from the fourth. The falling satisfaction from each extra sachet illustrates the law of", "demand", "diminishing marginal utility", "diminishing returns", "comparative advantage", "B", "As more units of a good are consumed, the extra satisfaction from each additional unit falls — the law of diminishing marginal utility.", None),
    ("Theory of the Firm", "Medium", "A farmer keeps adding labourers to a fixed plot of land. After the fifth labourer, each extra worker adds less to total output than the one before. This illustrates", "economies of scale", "the law of diminishing returns", "diseconomies of scale", "the law of comparative cost", "B", "When more of a variable factor (labour) is added to a fixed factor (land), marginal product eventually falls — the law of diminishing returns.", None),
    ("Costs of Production", "Medium", "A bakery's fixed cost is ₦20,000 per day. When it produces 100 loaves its total cost is ₦45,000. The average variable cost per loaf is", "₦200", "₦250", "₦450", "₦650", "B", "Total variable cost = 45,000 − 20,000 = ₦25,000; AVC = 25,000/100 = ₦250.", "(45000-20000)/100"),
    ("Costs of Production", "Hard", "A firm's total cost rises from ₦120,000 to ₦132,000 when output increases from 40 to 44 units. The marginal cost per unit is", "₦300", "₦3,000", "₦12,000", "₦30,000", "B", "Marginal cost = change in total cost ÷ change in output = 12,000/4 = ₦3,000.", "12000/4"),
    ("Revenue and Profit", "Easy", "A trader sells 500 mangoes at ₦80 each. Her total cost was ₦30,000. Her profit is", "₦4,000", "₦10,000", "₦40,000", "₦70,000", "B", "Total revenue = 500 × 80 = ₦40,000; profit = 40,000 − 30,000 = ₦10,000.", "500*80-30000"),
    ("Revenue and Profit", "Medium", "A firm in a perfectly competitive market sells at ₦50 per unit. Its marginal revenue is", "less than ₦50", "₦50", "more than ₦50", "zero", "B", "A perfectly competitive firm is a price taker: each extra unit sells at the market price, so marginal revenue = average revenue = price.", None),
    ("Market Structures", "Medium", "Only one company supplies electricity to a whole city and there is no close substitute. This market structure is", "perfect competition", "oligopoly", "monopoly", "monopolistic competition", "C", "A single seller of a product with no close substitute is a monopoly.", None),
    ("Market Structures", "Medium", "Nigeria's mobile telephone industry is dominated by four large firms whose pricing decisions affect one another. This is an example of", "perfect competition", "oligopoly", "monopoly", "monopsony", "B", "A few large, interdependent firms dominating a market is an oligopoly.", None),
    ("National Income", "Medium", "In a closed economy with no government sector, consumption is ₦300 billion and investment is ₦100 billion. National income is", "₦100 billion", "₦200 billion", "₦300 billion", "₦400 billion", "D", "With no government or foreign trade, Y = C + I = 300 + 100 = ₦400 billion.", "300+100"),
    ("Measurement of National Income", "Hard", "A country's GDP is ₦50 trillion, net factor income from abroad is −₦2 trillion and depreciation is ₦3 trillion. Its net national product (NNP) is", "₦45 trillion", "₦47 trillion", "₦51 trillion", "₦55 trillion", "A", "GNP = GDP + net factor income from abroad = 50 − 2 = 48; NNP = GNP − depreciation = 48 − 3 = ₦45 trillion.", "50-2-3"),
    ("Measurement of National Income", "Medium", "A country's nominal GDP is ₦60 trillion and its GDP deflator is 120. Real GDP is", "₦40 trillion", "₦48 trillion", "₦50 trillion", "₦72 trillion", "C", "Real GDP = nominal GDP ÷ (deflator/100) = 60 ÷ 1.2 = ₦50 trillion.", "60/1.2"),
    ("Measurement of National Income", "Medium", "A tailor buys cloth for ₦5,000 and sells the finished dress for ₦12,000. The value added by the tailor is", "₦5,000", "₦7,000", "₦12,000", "₦17,000", "B", "Value added = value of output − cost of intermediate inputs = 12,000 − 5,000 = ₦7,000.", "12000-5000"),
    ("Measurement of National Income", "Medium", "Counting both the value of flour sold to a bakery and the full value of the bread made from it when computing national income leads to", "double counting", "under-valuation", "inflation", "transfer payments", "A", "The flour's value is already included in the price of the bread; adding it again counts it twice — double counting, avoided by using value added or final goods only.", None),
    ("Money", "Easy", "A farmer in Zamfara wants to exchange his millet for a goat, but the goat owner wants yams instead. This problem of barter is called the lack of", "double coincidence of wants", "a store of value", "divisibility", "a unit of account", "A", "Barter works only when each party wants exactly what the other offers — a double coincidence of wants — which money removes.", None),
    ("Money", "Medium", "Bala keeps part of his salary in a bank to pay school fees in January. Money here is serving as a", "medium of exchange", "store of value", "unit of account", "standard of deferred payment", "B", "Holding money to spend later is using it as a store of value.", None),
    ("Inflation", "Medium", "A basket of goods that cost ₦20,000 in January cost ₦25,000 in December of the same year. The rate of inflation for the year is", "5%", "20%", "25%", "125%", "C", "Inflation rate = (25,000 − 20,000)/20,000 × 100 = 25%.", "(25000-20000)/20000*100"),
    ("Inflation", "Medium", "A sharp rise in the price of diesel increased transport and production costs, and the prices of most goods rose. This type of inflation is", "demand-pull inflation", "cost-push inflation", "hyperinflation", "creeping inflation", "B", "When rising costs of inputs push producers to raise prices, the result is cost-push inflation.", None),
    ("Inflation", "Easy", "During a period of rapid inflation, the group most likely to gain is", "pensioners living on fixed monthly incomes", "people who borrowed at a fixed interest rate", "people who keep their savings in cash at home", "workers whose salaries are fixed by contract", "B", "Borrowers repay in money that is worth less than what they borrowed; fixed-income earners and savers lose purchasing power.", None),
    ("Deflation", "Medium", "A persistent fall in the general price level accompanied by falling output and rising unemployment is", "inflation", "deflation", "stagflation", "reflation", "B", "Deflation is a sustained fall in the general price level, usually with falling output and jobs; stagflation is stagnation WITH rising prices.", None),
    ("Unemployment", "Medium", "A Nigerian graduate who is willing and able to work cannot find a job because the skills employers want differ from his training. He is experiencing", "frictional unemployment", "seasonal unemployment", "structural unemployment", "voluntary unemployment", "C", "A mismatch between workers' skills and the jobs available is structural unemployment.", None),
    ("Unemployment", "Easy", "A labour force of 60 million contains 8 million people who are willing and able to work but have no jobs. The unemployment rate is approximately", "7.5%", "8%", "13.3%", "15%", "C", "Unemployment rate = unemployed ÷ labour force × 100 = 8/60 × 100 ≈ 13.3%.", "8/60*100"),
    ("Population", "Medium", "A country has a population of 200 million and a land area of 1,000,000 km². Its population density is", "0.2 persons per km²", "20 persons per km²", "200 persons per km²", "2,000 persons per km²", "C", "Population density = population ÷ land area = 200,000,000 ÷ 1,000,000 = 200 persons per km².", "200e6/1e6"),
    ("Population", "Medium", "A country's birth rate is 40 per 1,000 and its death rate is 12 per 1,000. Ignoring migration, its natural rate of population growth is", "1.2%", "2.8%", "5.2%", "28%", "B", "Natural increase = birth rate − death rate = 28 per 1,000 = 2.8% per year.", "(40-12)/10"),
    ("Population", "Easy", "A country's population is made up largely of people under 15 years of age. One likely consequence is", "a low dependency ratio", "a high dependency ratio", "a falling birth rate", "a large labour force", "B", "Children depend on the working population; a youthful population means many dependants per worker.", None),
    ("Taxation", "Medium", "Mr Okon earns ₦2,000,000 a year and pays ₦200,000 in income tax; Mrs Ade earns ₦5,000,000 and pays ₦750,000. This tax system is", "progressive", "regressive", "proportional", "indirect", "A", "Mr Okon pays 10% and Mrs Ade pays 15%: the rate rises with income, which is a progressive tax.", None),
    ("Taxation", "Medium", "The value added tax (VAT) charged on goods bought in a supermarket is an example of", "a direct tax", "an indirect tax", "a progressive tax", "a capital tax", "B", "VAT is levied on goods and services and passed on to the consumer in the price — an indirect tax.", None),
    ("Public Finance", "Medium", "In a year the federal government's revenue was ₦10 trillion while its expenditure was ₦13 trillion. The budget is", "a surplus budget of ₦3 trillion", "a deficit budget of ₦3 trillion", "a balanced budget", "a supplementary budget", "B", "Expenditure exceeds revenue by 13 − 10 = ₦3 trillion, so the budget is in deficit.", "13-10"),
    ("International Trade", "Medium", "With one unit of resources Country A can produce 10 bags of rice or 5 bales of cotton, while Country B can produce 4 bags of rice or 4 bales of cotton. According to comparative advantage, Country A should specialise in", "rice", "cotton", "both goods", "neither good", "A", "A gives up ½ bale of cotton per bag of rice; B gives up 1 bale. A's opportunity cost of rice is lower, so A specialises in rice and B in cotton.", None),
    ("Balance of Payments", "Medium", "In a year Nigeria's visible exports were $60 billion and its visible imports $40 billion. Its balance of trade is", "a deficit of $20 billion", "a surplus of $20 billion", "a surplus of $100 billion", "balanced", "B", "Balance of trade = visible exports − visible imports = 60 − 40 = a $20 billion surplus.", "60-40"),
    ("Balance of Payments", "Medium", "Which of the following transactions is recorded in the invisible account of Nigeria's balance of payments?", "the export of crude oil to India", "the import of parboiled rice from Thailand", "payment to foreign airlines for flights", "the export of cocoa beans to Europe", "C", "Invisible items are services such as transport, tourism, insurance and banking; goods (oil, rice, cocoa) are visible items.", None),
    ("Trade", "Easy", "The exchange rate changes from ₦1,500 = $1 to ₦1,600 = $1. This means the naira has", "appreciated", "depreciated", "been revalued", "been fixed", "B", "More naira are now needed to buy one dollar, so the naira has lost value — it has depreciated.", None),
    ("Trade", "Medium", "A Nigerian importer buys goods worth $2,000 when the exchange rate is ₦1,500 to $1. The naira cost of the goods is", "₦300,000", "₦3,000,000", "₦30,000,000", "₦1,333", "B", "2,000 × 1,500 = ₦3,000,000.", "2000*1500"),
    ("Agriculture", "Medium", "A government buys surplus cocoa when the world price falls and releases it when the price rises, in order to keep farmers' incomes stable. This policy is", "price control", "a buffer stock scheme", "a subsidy", "rationing", "B", "Buying in gluts and selling in shortages to stabilise price and income is a buffer stock scheme.", None),
    ("Industrialization", "Medium", "A country sets up factories to produce locally the goods it used to import. It is pursuing", "export promotion", "import substitution", "nationalisation", "privatisation", "B", "Replacing imports with home-produced goods is the import-substitution strategy of industrialisation.", None),
    ("Economic Development", "Medium", "Country X's GDP grew by 5% last year, yet poverty, illiteracy and infant mortality remained unchanged. Country X experienced", "economic development without growth", "economic growth without development", "stagnation", "a recession", "B", "Growth is a rise in output; development requires improvement in welfare (health, education, poverty). Output rose but welfare did not.", None),
    ("Economic Planning", "Easy", "A government sets out targets for output, employment and infrastructure to be achieved over the next five years. This document is", "a budget", "a development plan", "a balance of payments statement", "a party manifesto", "B", "A medium-term statement of economic targets and the means of achieving them is a development plan; a budget covers one year's revenue and expenditure.", None),
]

GOVT = [
    ("Basic Concepts in Government", "Medium", "Nigeria rejected a foreign country's attempt to dictate its trade laws, insisting that only its own government can make laws for Nigerians. This illustrates", "legitimacy", "sovereignty", "authority", "influence", "B", "Sovereignty is the supreme power of a state to make and enforce laws within its territory free from external control."),
    ("Basic Concepts in Government", "Medium", "A traffic warden directs vehicles and drivers obey because the law empowers him to do so. The warden is exercising", "power", "authority", "influence", "force", "B", "Authority is the right to command that comes from an office recognised by law; power is the mere ability to compel."),
    ("Basic Concepts in Government", "Medium", "After a keenly contested election, citizens widely accept the new government's right to rule. The government is said to enjoy", "sovereignty", "legitimacy", "coercion", "influence", "B", "Legitimacy is the popular acceptance of a government's right to govern."),
    ("Forms of Government", "Medium", "In Country X the head of state inherited the throne, but real power is exercised by an elected parliament and prime minister. Country X is", "an absolute monarchy", "a constitutional monarchy", "a republic", "a theocracy", "B", "A hereditary monarch who reigns but does not rule, with power in elected institutions, is a constitutional monarchy (e.g. the United Kingdom)."),
    ("Forms of Government", "Medium", "A small group of wealthy families controls all the important offices of government in a country. This form of government is", "a democracy", "an oligarchy", "a monarchy", "a theocracy", "B", "Oligarchy is rule by a small privileged group."),
    ("Arms of Government", "Easy", "The National Assembly passes a bill, the President assents to it, and later the Supreme Court declares a section of it unconstitutional. The court is exercising", "judicial review", "legislative oversight", "executive veto", "impeachment", "A", "Judicial review is the power of the courts to declare laws or actions of the other arms void where they conflict with the constitution."),
    ("Arms of Government", "Medium", "The Senate refuses to confirm a ministerial nominee sent by the President. This is an example of", "separation of powers", "checks and balances", "the rule of law", "delegated legislation", "B", "One arm of government restraining another is checks and balances; separation of powers merely assigns different functions to different arms."),
    ("Arms of Government", "Medium", "The National Assembly gives a ministry power to make detailed regulations under an Act. Those regulations are an example of", "judicial precedent", "delegated legislation", "a constitutional amendment", "a private member's bill", "B", "Laws made by a body other than the legislature under powers granted by the legislature are delegated (subsidiary) legislation."),
    ("Systems of Governance", "Medium", "In a country the head of government is chosen from the majority party in parliament and can be removed by a vote of no confidence. This is a", "presidential system", "parliamentary system", "confederal system", "unitary system", "B", "Fusion of the executive and the legislature, with the cabinet responsible to parliament, defines the parliamentary (cabinet) system."),
    ("Systems of Governance", "Medium", "In Nigeria's Fourth Republic the President is both head of state and head of government and is elected separately from the legislature. This is a feature of the", "parliamentary system", "presidential system", "monarchical system", "collegial system", "B", "A separately elected chief executive who combines both roles is the hallmark of the presidential system."),
    ("Structures of Governance", "Medium", "In Country Y the central government can create or abolish regional governments at will, and the regions derive all their powers from the centre. Country Y operates", "a federal system", "a unitary system", "a confederation", "a presidential system", "B", "In a unitary state all power belongs to the centre, which may delegate to (and withdraw from) lower units as it wishes."),
    ("Structures of Governance", "Medium", "Nigeria's constitution shares law-making powers between the federal and state governments through the exclusive, concurrent and residual lists. This arrangement is called", "unitarism", "confederalism", "federalism", "devolution", "C", "Constitutional division of powers between a central government and component units, each supreme in its own sphere, is federalism."),
    ("Political Ideologies", "Medium", "A government takes over the major industries, abolishes private ownership of large businesses and plans the economy centrally in the name of equality. This ideology is", "capitalism", "socialism", "fascism", "liberalism", "B", "Public ownership of the means of production and central planning in pursuit of equality are socialist principles."),
    ("Constitution", "Medium", "In Country Z the constitution can be amended by a simple majority in parliament, in the same way as an ordinary law. Its constitution is", "rigid", "flexible", "unwritten", "federal", "B", "A constitution amended by the ordinary law-making procedure is flexible; one needing a special procedure is rigid."),
    ("Constitution", "Medium", "The 1999 Constitution of Nigeria can be altered only with the approval of two-thirds of each house of the National Assembly and of the Houses of Assembly of at least two-thirds of the states. This shows that the constitution is", "flexible", "rigid", "unwritten", "confederal", "B", "A special, difficult amendment procedure makes a constitution rigid."),
    ("Principles of Democratic Government", "Medium", "A former state governor was arrested and tried for corruption after leaving office, just like any other citizen. This illustrates the principle of", "separation of powers", "the rule of law", "popular sovereignty", "federal character", "B", "Equality before the law — nobody is above the law — is a central element of the rule of law."),
    ("Principles of Democratic Government", "Medium", "A newspaper publishes a story sharply critical of the President and is not shut down. This best illustrates", "freedom of the press", "separation of powers", "judicial independence", "delegated legislation", "A", "Freedom of the press and of expression are basic features of a democratic government."),
    ("Processes of Legislation", "Medium", "A bill has passed its first and second readings in the House of Representatives. The next stage is the", "presidential assent", "committee stage", "third reading", "transmission to the Senate", "B", "The order is: first reading, second reading (debate on principles), committee stage (detailed examination), report stage, third reading, then the other chamber and assent."),
    ("Processes of Legislation", "Medium", "The President refuses to sign a bill passed by the National Assembly. Under the 1999 Constitution the bill can still become law if", "the Senate President signs it on the President's behalf", "each house passes it again by a two-thirds majority", "the Supreme Court declares it constitutional", "the Council of State approves it by a simple majority", "B", "Section 58 provides that if assent is withheld, the National Assembly may pass the bill again by two-thirds majority and it becomes law without assent."),
    ("Citizenship", "Medium", "Mr Kwame, a Ghanaian, has lived in Nigeria for 20 years, is of good character and applies to become a Nigerian citizen. If granted, he becomes a citizen by", "birth", "registration", "naturalisation", "descent", "C", "A foreigner who acquires citizenship after long residence and meeting the legal conditions is naturalised."),
    ("Citizenship", "Easy", "Which of the following is a duty of a Nigerian citizen rather than a right?", "freedom of expression", "payment of taxes", "the right to fair hearing", "freedom of movement", "B", "Rights are what the citizen is entitled to; paying taxes, obeying the law and defending the country are duties."),
    ("The Electoral Process", "Medium", "To be declared winner of a Nigerian presidential election, a candidate must have the highest number of votes and at least", "one-quarter of the votes cast in each of at least two-thirds of the states and the FCT", "one-half of the votes cast in each of the thirty-six states", "two-thirds of the votes cast in at least half of the states", "the votes of a majority of all registered voters in the federation", "A", "Section 134 of the 1999 Constitution requires a spread of not less than 25% of the votes in at least two-thirds of the states and the Federal Capital Territory."),
    ("The Electoral Process", "Medium", "A system in which parties win seats in proportion to their share of the total votes cast is", "the simple majority system", "proportional representation", "the second ballot", "the absolute majority system", "B", "Proportional representation allocates seats according to each party's percentage of votes."),
    ("The Electoral Process", "Medium", "In a constituency election Candidate A scored 40%, B 35% and C 25% of the votes, and A was declared the winner. The electoral system used is", "the absolute majority system", "the simple majority system", "proportional representation", "the second ballot system", "B", "A won without more than half of the votes; a plurality is enough under the simple majority system."),
    ("The Electoral Process", "Easy", "The body responsible for conducting federal and state elections in Nigeria is the", "Nigeria Police Force", "Independent National Electoral Commission", "National Assembly", "Federal Character Commission", "B", "INEC organises and supervises federal and state elections; state electoral commissions handle local government elections."),
    ("Political Parties and Party Systems", "Medium", "A country has many registered parties, but only two of them have a realistic chance of forming the government. Its party system is best described as", "a one-party system", "a two-party system", "a multi-party system", "a zero-party system", "B", "A two-party system exists where two major parties dominate and alternate in power, even if minor parties exist."),
    ("Political Parties and Party Systems", "Medium", "The main difference between a political party and a pressure group is that a political party", "seeks to influence government policy", "aims to win elections and control the government", "is always larger", "must be registered", "B", "Both influence policy, but only a party contests elections in order to take over government."),
    ("Pressure Groups", "Medium", "The Nigeria Labour Congress threatens a nationwide strike to force the government to raise the minimum wage. The NLC is acting as", "a political party", "a pressure group", "a public corporation", "a civil service body", "B", "A pressure group seeks to influence government decisions in its members' interest without seeking to govern."),
    ("Pressure Groups", "Medium", "The Nigerian Medical Association campaigns for better pay and working conditions for doctors. It is best classified as", "a promotional pressure group", "a professional (sectional) pressure group", "an anomic group", "a political party", "B", "Sectional or professional groups defend the economic interests of their own members; promotional groups pursue a cause for society at large."),
    ("Public Opinion", "Medium", "A radio phone-in programme gathers strong public objections to a new levy, and the government later withdraws it. This shows the role of", "public opinion", "the judiciary", "the civil service", "the electoral commission", "A", "Public opinion — the views of the people on an issue — can influence and restrain government policy."),
    ("The Civil Service", "Medium", "A permanent secretary who served under one ruling party continues in office when a different party wins the election. This illustrates the civil-service principle of", "anonymity", "neutrality", "permanence", "secrecy", "C", "Career civil servants remain in office when governments change — permanence. Neutrality refers to not taking political sides."),
    ("The Civil Service", "Medium", "A minister publicly takes responsibility for an error made by officials in her ministry, whose names are never mentioned. This illustrates the civil-service principle of", "anonymity", "permanence", "neutrality", "expertise", "A", "Civil servants act in the minister's name and are not publicly identified — anonymity; the minister answers for the ministry."),
    ("Pre-Colonial Political Systems", "Medium", "In the pre-colonial Igbo political system, village decisions were taken at the general assembly of adult males and by the council of elders, with no king. The system was", "monarchical", "centralised", "acephalous (decentralised)", "theocratic", "C", "Acephalous means 'without a head': authority was shared among assemblies, elders, age grades and title societies rather than held by a king."),
    ("Pre-Colonial Political Systems", "Medium", "In the Old Oyo Empire the Oyo Mesi could compel an unpopular Alaafin to commit suicide by presenting him with an empty calabash. This shows that the system had", "an absolute monarchy", "checks and balances on the Alaafin", "a republican government", "a written constitution", "B", "The Oyo Mesi (and the Ogboni) limited the Alaafin's power — a traditional system of checks and balances."),
    ("Imperialist Penetration and Colonial Administration", "Medium", "The British governed Northern Nigeria through the emirs and their existing institutions. This system was called", "direct rule", "indirect rule", "assimilation", "association", "B", "Indirect rule used traditional rulers as agents of colonial administration."),
    ("Imperialist Penetration and Colonial Administration", "Medium", "Indirect rule was least successful in Eastern Nigeria mainly because", "the people had rejected Christianity and Western education", "the area had no centralised traditional rulers, so warrant chiefs were imposed", "the British had too few soldiers stationed in the region", "the region was too large and thickly populated to administer", "B", "The Igbo system was acephalous; the artificial warrant chiefs lacked legitimacy, leading to resentment and the 1929 Aba Women's Riot."),
    ("Nationalism and the Decolonization Process", "Medium", "A major effect of the Second World War on Nigerian nationalism was that", "it brought nationalist agitation to an end for a decade", "returning soldiers and wartime experiences intensified demands for self-government", "Nigeria was granted independence immediately the war ended", "the British granted universal adult suffrage to all Nigerians", "B", "Ex-servicemen who had fought for freedom abroad, the Atlantic Charter and economic hardship all strengthened the demand for self-rule after 1945."),
    ("Constitutional Development in Nigeria", "Medium", "The Nigerian constitution that first established a truly federal system of government was the", "Clifford Constitution of 1922", "Richards Constitution of 1946", "Macpherson Constitution of 1951", "Lyttleton Constitution of 1954", "D", "The Lyttleton Constitution made the regions autonomous with their own powers — the beginning of federalism; Richards only introduced regionalism."),
    ("Constitutional Development in Nigeria", "Medium", "The Clifford Constitution of 1922 is remembered mainly for", "introducing the elective principle", "creating three regions in Nigeria", "granting internal self-government", "introducing a federal constitution", "A", "It allowed, for the first time, the election of four Africans (three for Lagos, one for Calabar) into the Legislative Council."),
    ("Political Parties and the First Republic", "Medium", "In the First Republic the NPC, NCNC and AG drew their main support respectively from the", "North, East and West", "West, North and East", "East, West and North", "whole country equally", "A", "The Northern People's Congress was based in the North, the NCNC in the East and the Action Group in the West — parties were largely regional."),
    ("Military Rule in Nigeria", "Medium", "The first military coup in Nigeria took place in", "January 1966", "July 1966", "July 1975", "December 1983", "A", "The coup of 15 January 1966 ended the First Republic; the counter-coup followed in July 1966."),
    ("Military Rule in Nigeria", "Medium", "A common feature of military regimes in Nigeria was that they governed by", "acts of parliament", "decrees", "bye-laws", "referendums", "B", "Military governments suspended parts of the constitution and legislated by decree (federal) and edicts (state)."),
    ("The Second Republic", "Medium", "The Second Republic (1979–1983) differed from the First Republic mainly in that it operated", "a parliamentary system", "a presidential system", "a unitary system", "a one-party system", "B", "The 1979 Constitution replaced the Westminster parliamentary model with an American-style executive presidency."),
    ("The Third Republic", "Medium", "The presidential election of 12 June 1993, widely believed to have been won by M.K.O. Abiola, was", "upheld by the Supreme Court of Nigeria", "annulled by the Babangida military government", "won by Bashir Tofa of the NRC", "boycotted by voters in most states", "B", "The annulment of the June 12 election ended the transition to the Third Republic."),
    ("The Fourth Republic", "Medium", "Nigeria's Fourth Republic began on", "1 October 1979", "29 May 1999", "12 June 1993", "1 October 1960", "B", "Civilian rule returned on 29 May 1999 with the inauguration of President Olusegun Obasanjo under the 1999 Constitution."),
    ("Nigerian Federalism", "Medium", "Matters such as defence, currency and foreign affairs, on which only the National Assembly may legislate, are on the", "concurrent list", "residual list", "exclusive legislative list", "local government list", "C", "The exclusive list is reserved for the federal government; both tiers may legislate on the concurrent list; residual matters belong to the states."),
    ("Local Government Administration", "Medium", "The number of local government areas listed in the 1999 Constitution of Nigeria is", "768", "774", "776", "780", "B", "The First Schedule of the 1999 Constitution lists 774 local government areas."),
    ("Public Corporations and Parastatals", "Medium", "The government sold its majority shares in a state-owned electricity company to private investors. This is", "nationalisation", "privatisation", "commercialisation", "indigenisation", "B", "Transferring ownership of public enterprises to private hands is privatisation; nationalisation is the reverse."),
    ("Foreign Policy", "Medium", "Nigeria's foreign policy has consistently given priority to African affairs, for example its support for liberation movements in Southern Africa. This principle is known as", "non-alignment with the power blocs", "Africa as the centrepiece of foreign policy", "isolationism from world affairs", "imperialism towards neighbouring states", "B", "Successive governments have made Africa the centrepiece of Nigeria's foreign policy."),
    ("Nigeria's Relations with Other Countries", "Medium", "Nigeria's leading role in the ECOMOG peacekeeping operations in Liberia and Sierra Leone in the 1990s demonstrates its commitment to", "regional peace and security in West Africa", "colonial expansion", "isolationism", "non-interference in African affairs", "A", "Nigeria provided most of the troops and funding for ECOMOG to restore peace in the sub-region."),
    ("International Organizations", "Medium", "The organ of the United Nations in which five permanent members have the power of veto is the", "General Assembly", "Security Council", "Secretariat", "International Court of Justice", "B", "The USA, Russia, China, the UK and France are permanent members of the Security Council and can veto substantive resolutions."),
    ("Nigeria and International Organizations", "Medium", "ECOWAS was established by the Treaty of Lagos in 1975 mainly to", "create a common army for West Africa", "promote economic integration among West African states", "fight apartheid in Southern Africa", "replace the Organisation of African Unity", "B", "The Economic Community of West African States was formed to promote trade, co-operation and economic integration in the sub-region."),
]

COMM = [
    ("Introduction to Commerce", "Easy", "A farmer in Benue grows yams; a lorry driver transports them to Lagos, a wholesaler stores them and a retailer sells them to consumers. All the activities apart from growing the yams fall under", "industry", "commerce", "direct services", "extraction", "B", "Commerce covers trade and the aids to trade (transport, warehousing, banking, insurance, advertising, communication); growing the yams is production (industry).", None),
    ("Occupation", "Medium", "A lawyer, a teacher and a doctor render services directly to people. Their occupations are classified as", "industrial occupations", "commercial occupations", "direct services", "extractive occupations", "C", "Personal services rendered directly to individuals are direct services (tertiary occupations).", None),
    ("Occupation", "Easy", "Fishing, mining and lumbering are examples of", "extractive industries", "constructive industries", "manufacturing industries", "tertiary occupations", "A", "Extractive industries take natural resources directly from land or sea.", None),
    ("Production", "Medium", "A student argues that a lorry driver who carries tomatoes from Jos to Port Harcourt is not a producer because he makes nothing. This is wrong because", "driving long distances is hard physical work", "the driver adds place utility to the tomatoes", "the driver is paid wages for the journey", "tomatoes would rot if they were not moved quickly", "B", "Production is the creation of utility; transport adds place utility, just as warehousing adds time utility.", None),
    ("Factors of Production", "Easy", "The machines, buildings and delivery vans a firm uses to produce goods are examples of", "land", "labour", "capital", "enterprise", "C", "Capital consists of man-made goods used in further production.", None),
    ("Trade", "Medium", "A Nigerian company buys cocoa from farmers in Ondo and sells it to a chocolate maker in Belgium. This transaction is", "home trade", "import trade", "export trade", "entrepôt trade", "C", "Selling goods produced at home to buyers abroad is export trade.", None),
    ("Foreign Trade", "Medium", "Goods are imported into Nigeria and later re-exported to Niger Republic without being processed. This is", "bilateral trade", "entrepôt trade", "home trade", "counter trade", "B", "Entrepôt trade is the importation of goods for re-export.", None),
    ("Foreign Trade", "Medium", "A document issued by a shipping company acknowledging receipt of goods on board and serving as a document of title to them is", "a bill of lading", "a certificate of origin", "an invoice", "a consular invoice", "A", "The bill of lading is a receipt, a contract of carriage and a document of title; the holder can claim the goods.", None),
    ("Foreign Trade", "Medium", "The difference between the value of a country's visible exports and its visible imports is its", "balance of payments", "balance of trade", "terms of trade", "exchange rate", "B", "The balance of trade covers goods only; the balance of payments also includes services and capital flows.", None),
    ("Home Trade", "Medium", "A trader buys goods on credit. The document the seller sends at the end of the month showing all the transactions and the balance owing is", "a statement of account", "a credit note", "a debit note", "a receipt", "A", "A statement of account summarises invoices, payments and returns for the period and shows the amount outstanding.", None),
    ("Home Trade", "Medium", "A buyer returned damaged goods to the seller. The document the seller issues to reduce the amount the buyer owes is", "a debit note", "a credit note", "an invoice", "a delivery note", "B", "A credit note (usually printed in red) reduces the buyer's debt; a debit note increases it.", None),
    ("Home Trade", "Medium", "An electronics shop offers 5% off for payment within 7 days. A customer with a ₦120,000 invoice pays on the third day. He pays", "₦114,000", "₦120,000", "₦126,000", "₦60,000", "A", "Cash discount = 5% of 120,000 = ₦6,000; amount paid = 120,000 − 6,000 = ₦114,000.", "120000*0.95"),
    ("Home Trade", "Medium", "A trader's opening stock was ₦200,000, purchases for the year ₦800,000 and closing stock ₦300,000. The cost of goods sold is", "₦500,000", "₦700,000", "₦900,000", "₦1,300,000", "B", "Cost of goods sold = opening stock + purchases − closing stock = 200,000 + 800,000 − 300,000 = ₦700,000.", "200000+800000-300000"),
    ("Wholesale Trade", "Medium", "A wholesaler buys goods with a list price of ₦500,000 at a trade discount of 20%. He pays", "₦100,000", "₦400,000", "₦480,000", "₦600,000", "B", "Trade discount = 20% of 500,000 = ₦100,000; amount payable = ₦400,000.", "500000*0.8"),
    ("Wholesale Trade", "Medium", "A manufacturer produces a million sachets of detergent daily, while each shop buys only a few cartons. The wholesaler helps the manufacturer chiefly by", "advertising the detergent on national television", "buying in bulk and breaking bulk for retailers", "fixing the price at which retailers must sell", "manufacturing the sachets more cheaply", "B", "The wholesaler buys in large quantities, stores the goods and sells in smaller lots to retailers, relieving the producer of storage and small orders.", None),
    ("Retail Trade", "Medium", "A shop in Lagos sells only children's clothing and toys, with trained staff who advise customers. This retailer is", "a department store", "a supermarket", "a specialist shop", "a mobile shop", "C", "A shop that deals in one line of goods and offers expert service is a specialist shop.", None),
    ("Retail Trade", "Medium", "A retailer bought a phone for ₦80,000 and sold it for ₦100,000. The mark-up as a percentage of cost price is", "20%", "25%", "80%", "125%", "B", "Mark-up = profit ÷ cost × 100 = 20,000/80,000 × 100 = 25%. (Margin on selling price would be 20%.)", "20000/80000*100"),
    ("Retail Trade", "Medium", "Under a hire purchase agreement, ownership of the goods passes to the buyer", "on payment of the deposit", "when the goods are delivered", "on payment of the final instalment", "when the agreement is signed", "C", "In hire purchase the buyer hires the goods and becomes owner only after the last instalment; under a credit sale ownership passes at once.", None),
    ("Retail Trade", "Hard", "A shop's cost of goods sold for the year was ₦1,800,000 and its average stock at cost was ₦300,000. The rate of stock turnover is", "4 times", "6 times", "8 times", "10 times", "B", "Rate of turnover = cost of goods sold ÷ average stock = 1,800,000/300,000 = 6 times a year.", "1800000/300000"),
    ("Channels of Distribution", "Medium", "A bakery sells bread directly to consumers from its own shop. Its channel of distribution is", "producer → consumer", "producer → retailer → consumer", "producer → wholesaler → retailer → consumer", "producer → agent → wholesaler → consumer", "A", "Selling straight to the final consumer with no middleman is the shortest (direct) channel.", None),
    ("Transportation", "Medium", "A Kano trader wants to send 40 tonnes of cement to Lagos as cheaply as possible and is not in a hurry. The most suitable means of transport is", "air", "rail", "motorcycle", "pipeline", "B", "Rail carries heavy, bulky goods over long distances cheaply, though it is slower and less flexible than road.", None),
    ("Transportation", "Medium", "Fresh flowers grown in Jos are needed in London within 24 hours. The most suitable means of transport is", "sea", "rail", "air", "road", "C", "Air transport is the fastest and is ideal for perishable, high-value goods despite its cost.", None),
    ("Communication", "Medium", "A company wants to send an exact copy of a signed contract to a partner abroad within minutes. The most suitable means is", "a telephone call to read out the contract", "an e-mail with the scanned document attached", "a telegram summarising the main terms", "a photocopy sent by surface mail", "B", "E-mail delivers documents instantly and an attachment reproduces the signed page exactly.", None),
    ("Warehousing", "Medium", "Imported goods on which customs duty has not yet been paid are kept in", "a bonded warehouse", "a public warehouse", "a wholesaler's warehouse", "a cold store", "A", "Bonded warehouses hold dutiable goods under customs control until duty is paid or the goods are re-exported.", None),
    ("Warehousing", "Medium", "A tomato wholesaler keeps stock in cold rooms and releases it gradually through the year. Warehousing here helps to", "raise prices by creating artificial scarcity", "stabilise prices by evening out supply", "improve the quality of the tomatoes", "avoid paying tax on unsold stock", "B", "Storing goods from times of plenty to times of scarcity smooths supply and keeps prices steadier.", None),
    ("Insurance", "Hard", "A building worth ₦20 million was insured for ₦10 million. Fire caused damage of ₦4 million. Under the average clause the insurer pays", "₦1 million", "₦2 million", "₦4 million", "₦10 million", "B", "Under-insurance: payment = loss × (sum insured ÷ value) = 4 × 10/20 = ₦2 million.", "4*10/20"),
    ("Insurance", "Medium", "After an accident Mr Eze received from his insurer exactly the cost of repairing his car, and no more. The principle applied is", "subrogation", "indemnity", "utmost good faith", "insurable interest", "B", "Indemnity restores the insured to his position before the loss; he must not profit from insurance.", None),
    ("Insurance", "Medium", "A man insured his neighbour's house, hoping to collect money if it burnt down. His claim would fail because he lacks", "indemnity", "insurable interest", "proximate cause", "contribution", "B", "One can insure only something whose loss would cause one financial loss — insurable interest.", None),
    ("Insurance", "Medium", "When applying for life assurance, Mrs Ojo concealed the fact that she had a heart condition. The insurer can repudiate a claim because she breached the principle of", "subrogation", "utmost good faith", "contribution", "indemnity", "B", "Utmost good faith (uberrimae fidei) requires the proposer to disclose all material facts.", None),
    ("Insurance", "Medium", "A trader pays ₦50,000 a year to an insurer to cover his shop against fire. The ₦50,000 is the", "claim", "premium", "policy", "cover note", "B", "The premium is the consideration paid for insurance cover; the policy is the contract document.", None),
    ("Banking", "Medium", "A trader wants a cheque that cannot be cashed over the counter but must be paid into a bank account. He should", "open the cheque", "cross the cheque", "post-date the cheque", "endorse the cheque", "B", "Two parallel lines across the face of a cheque (crossing) mean it can only be paid through a bank account, which is safer.", None),
    ("Banking", "Medium", "A customer's cheque was returned by the bank marked 'refer to drawer'. The most likely reason is that", "the cheque was crossed", "the drawer had insufficient funds", "the payee was unknown", "the bank was closed", "B", "'Refer to drawer' (R/D) usually means there is not enough money in the drawer's account to honour the cheque.", None),
    ("Banking", "Medium", "Mrs Ade deposited ₦200,000 in a savings account paying 5% simple interest per annum. After 2 years she earns interest of", "₦10,000", "₦20,000", "₦40,000", "₦220,000", "B", "Simple interest = principal × rate × time = 200,000 × 0.05 × 2 = ₦20,000.", "200000*0.05*2"),
    ("Banking", "Medium", "The bank that issues the naira, supervises other banks and acts as banker to the federal government is the", "Bank of Industry", "Central Bank of Nigeria", "Nigeria Deposit Insurance Corporation", "Federal Mortgage Bank", "B", "These are the functions of a central bank; in Nigeria it is the CBN.", None),
    ("Stock Exchange", "Medium", "Chidi bought 1,000 shares of a company at ₦25 each and received a dividend of ₦2 per share. His dividend yield is", "2%", "8%", "12.5%", "25%", "B", "Dividend yield = dividend per share ÷ price per share × 100 = 2/25 × 100 = 8%.", "2/25*100"),
    ("Stock Exchange", "Medium", "An investor buys shares expecting their price to rise so that he can sell them at a profit. He is called", "a bear", "a bull", "a stag", "a jobber", "B", "A bull buys expecting prices to rise; a bear sells expecting a fall; a stag buys new issues to resell quickly.", None),
    ("Business Units", "Medium", "Two friends pool ₦5 million, run a restaurant together and share the profits, but each is personally liable for all the debts of the business. Their business is", "a private limited company", "a partnership", "a co-operative society", "a public corporation", "B", "Joint ownership by two to twenty persons sharing profits, with unlimited liability, is an ordinary partnership.", None),
    ("Business Units", "Medium", "A cement company invites the general public to buy its shares, which are traded on the Nigerian Exchange. It is", "a private limited company", "a public limited company", "a partnership", "a public corporation", "B", "Only a public limited company (Plc) may offer its shares to the public and have them quoted on the stock exchange.", None),
    ("Business Units", "Medium", "A shareholder of a limited company loses only the amount he invested when the company fails. This is because of", "unlimited liability", "limited liability", "perpetual succession", "double taxation", "B", "Limited liability restricts a member's loss to the amount unpaid on his shares; his personal property is safe.", None),
    ("Sources of Business Finance", "Medium", "A company wishing to raise long-term capital without giving up any ownership can issue", "ordinary shares", "debentures", "preference shares", "bonus shares", "B", "Debentures are loans to the company; holders are creditors, not owners, and receive fixed interest.", None),
    ("Sources of Business Finance", "Medium", "A supplier delivers ₦2 million worth of goods to a retailer, to be paid for in 60 days. The retailer is financing his stock through", "a bank overdraft", "trade credit", "hire purchase", "leasing", "B", "Buying goods now and paying later is trade credit — a short-term source of finance.", None),
    ("Business Management", "Medium", "The manager of a firm divides the work among departments and assigns authority and responsibility to each. This function of management is", "planning", "organising", "controlling", "motivating", "B", "Organising is arranging people, tasks and authority so that plans can be carried out.", None),
    ("Marketing", "Medium", "A company reduced the price of its soap, redesigned the packaging, advertised on radio and made the soap available in rural markets. The four elements it adjusted are the", "marketing mix", "business units", "channels of distribution", "trade associations", "A", "Product, price, promotion and place are the 4Ps of the marketing mix.", None),
    ("Marketing", "Medium", "A company gives out free samples of a new toothpaste in a market and offers 'buy two, get one free'. This is", "advertising", "sales promotion", "public relations", "personal selling", "B", "Short-term incentives such as free samples, coupons and bonus packs are sales promotion.", None),
    ("Advertising", "Medium", "An advertisement simply announces that a new brand of malt drink is now available, stating its price and where to buy it. This type of advertising is", "persuasive", "informative", "competitive", "generic", "B", "Informative advertising gives facts about a product without attempting to compare or persuade.", None),
    ("Consumer Protection", "Medium", "A customer bought a blender that stopped working after two days and the seller refused to replace it. The federal agency to which she should complain is the", "National Agency for Food and Drug Administration and Control", "Federal Competition and Consumer Protection Commission", "Nigerian Investment Promotion Commission", "Corporate Affairs Commission", "B", "The FCCPC handles consumer complaints and enforces consumer rights in Nigeria.", None),
    ("Trade Associations", "Medium", "Manufacturers in Nigeria have come together in the Manufacturers Association of Nigeria (MAN) mainly to", "fix the retail prices of manufactured goods", "protect and promote the common interests of members", "collect company taxes on behalf of government", "take over the functions of the chambers of commerce", "B", "Trade associations speak for their members, lobby government and provide information and standards.", None),
    ("Government and Business", "Medium", "The government bans the importation of rice to protect local farmers. This trade policy instrument is", "a tariff", "a quota", "an embargo", "a subsidy", "C", "A total ban on the import of a product is an embargo; a quota limits the quantity; a tariff is a tax.", None),
    ("Government and Business", "Medium", "The government imposes a 20% duty on imported cars. This is", "a quota", "a tariff", "an embargo", "exchange control", "B", "A tax on imported goods is a tariff (customs duty).", None),
]


def build():
    questions, bad = [], []
    for subject, rows in (("Economics", ECON), ("Commerce", COMM)):
        for topic, diff, q, a, b, c, d, ans, exp, verify in rows:
            item = {"subject": subject, "topic": topic, "difficulty": diff, "q": q, "A": a, "B": b, "C": c, "D": d, "answer": ans, "explanation": exp}
            if verify:
                expected = eval(verify, {"math": math})
                got = _num(item[ans])
                if got is None or abs(got - expected) > max(0.01 * abs(expected), 0.006):
                    bad.append((q[:60], ans, item[ans], expected))
            questions.append(item)
    for topic, diff, q, a, b, c, d, ans, exp in GOVT:
        questions.append({"subject": "Government", "topic": topic, "difficulty": diff, "q": q, "A": a, "B": b, "C": c, "D": d, "answer": ans, "explanation": exp})
    if bad:
        for b_ in bad:
            print("MISMATCH:", b_)
        sys.exit("Verification failed — file not written.")
    _balance(questions)
    texts = [x["q"] for x in questions]
    assert len(texts) == len(set(texts)), "duplicate question text"
    assert all(x["answer"] in "ABCD" and all(x[k] for k in "ABCD") for x in questions)
    batch = {
        "batch_id": "batch_003_econ_govt_commerce",
        "exam_type": "JAMB",
        "note": "Applied Economics (calculations verified), scenario-based Government, applied Commerce (calculations verified).",
        "passages": [],
        "questions": questions,
        "deactivate": [],
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(batch, fh, ensure_ascii=False, indent=1)
    from collections import Counter
    print(f"wrote {OUT}: {len(questions)} questions")
    print("answer letters:", dict(Counter(x['answer'] for x in questions)))
    print("per subject:", dict(Counter(x['subject'] for x in questions)))


if __name__ == "__main__":
    build()
