"""Batch 029 - Literature in English round 3, part B (forms, themes, plot, narration and set texts).

Genre and forms, themes and characterisation, plot/setting/structure, narrative techniques and point of
view - each item built around a short scenario or mini-extract - plus general items on the widely read
set texts (Antony and Cleopatra, To Kill a Mockingbird, An Inspector Calls, A Man for All Seasons, The
Marriage of Anansewa, The Lion and the Jewel, Second Class Citizen, Wuthering Heights, So the Path Does
Not Die, and the commonly prescribed African and non-African poems).

    python3 scripts/build_content_batch29.py -> content/batch_029_lit_round3b.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Literature in English"
T_GEN = "Genre and Forms of Literature"
T_THEME = "Themes and Characterization"
T_PLOT = "Plot, Setting and Structure"
T_NARR = "Narrative Techniques and Point of View"
T_AFD = "African Drama"
T_NAD = "Non-African Drama"
T_AFP = "African Prose"
T_NAP = "Non-African Prose"
T_AFPO = "African Poetry"
T_NAPO = "Non-African Poetry"

PASSAGES = []
PQ = []

Q = [
    # ---------------- Genre and Forms ----------------
    (T_GEN, "Easy", "A play in which a proud general destroys himself and those he loves through his own jealousy, ending in several deaths, is best classified as",
     "a tragedy", "a comedy", "a farce", "a masque",
     "A", "A serious play ending in the downfall of a great figure through a flaw is a tragedy."),
    (T_GEN, "Easy", "A play full of mistaken identities, slamming doors and absurd coincidences, written purely to make the audience laugh, is",
     "a farce", "a tragedy", "an elegy", "a melodrama",
     "A", "Farce relies on exaggerated situations, physical humour and improbable plots."),
    (T_GEN, "Medium", "A play in which the innocent heroine is tied to a railway line by a moustache-twirling villain and rescued at the last moment by a flawless hero is",
     "a melodrama", "a tragicomedy", "a satire", "a pastoral",
     "A", "Melodrama features sensational plots, stock characters of pure good and evil, and strong appeals to emotion."),
    (T_GEN, "Medium", "A play that begins with a shipwreck and threats of death but ends with forgiveness, reunion and a wedding is",
     "a tragicomedy", "a farce", "a tragedy", "a history play",
     "A", "A tragicomedy mixes serious danger with a happy ending, as in Shakespeare's late romances."),
    (T_GEN, "Medium", "A short play with a single act, one setting and a story that takes about forty minutes to perform is",
     "a one-act play", "an epic drama", "a chronicle play", "a trilogy",
     "A", "A one-act play is a complete drama in a single act, usually with few characters and one situation."),
    (T_GEN, "Medium", "A dramatic work in which the whole story is told through the songs of the actors, with no spoken dialogue, is",
     "an opera", "a mime", "a pantomime", "a masque",
     "A", "Opera is drama set entirely to music and sung."),
    (T_GEN, "Medium", "A performer tells a whole story through bodily movement and facial expression without using any words. This form is",
     "mime", "opera", "farce", "burlesque",
     "A", "Mime conveys action and emotion through gesture alone."),
    (T_GEN, "Medium", "A prose fiction of about eighty pages, longer than a short story but shorter than a novel, is",
     "a novella", "an epic", "an anthology", "a memoir",
     "A", "A novella is a mid-length prose narrative, such as 'Animal Farm' or 'The Old Man and the Sea'."),
    (T_GEN, "Easy", "A prose narrative that can be read at one sitting, with few characters and a single main incident, is",
     "a short story", "a novel", "an epic", "a chronicle",
     "A", "The short story concentrates on one effect or incident and a small cast."),
    (T_GEN, "Easy", "A story such as 'The Tortoise and the Birds', in which animals act like humans and a moral is drawn, is",
     "a fable", "a legend", "a lyric", "an ode",
     "A", "A fable is a brief tale, often with animal characters, that teaches a moral."),
    (T_GEN, "Easy", "A traditional story that explains how the sky came to be far from the earth is",
     "a myth", "a biography", "a farce", "a sonnet",
     "A", "Myths are traditional stories that explain natural phenomena, origins or beliefs."),
    (T_GEN, "Medium", "A traditional story about Moremi of Ile-Ife, a historical figure whose deeds have been embellished over generations, is",
     "a legend", "a myth", "a fable", "a parable",
     "A", "Legends are traditional stories about human heroes believed to have lived, often mixing fact and exaggeration."),
    (T_GEN, "Easy", "A short story told to illustrate a moral or spiritual lesson, such as the story of the Prodigal Son, is",
     "a parable", "a limerick", "a satire", "an epic",
     "A", "A parable is a simple story used to teach a moral or religious truth."),
    (T_GEN, "Medium", "A novel in which the villain is a cruel factory owner and the plot exposes child labour in order to press for reform is best described as",
     "a social or thesis novel", "a Gothic novel", "a picaresque novel", "a detective novel",
     "A", "A social-problem (thesis) novel dramatises a social evil to argue for change, as Dickens often did."),
    (T_GEN, "Medium", "A novel that follows a roguish hero of low birth through a series of loosely connected adventures on the road is",
     "picaresque", "epistolary", "pastoral", "Gothic",
     "A", "The picaresque novel is episodic and centres on a resourceful rogue (picaro)."),
    (T_GEN, "Medium", "A novel set in a gloomy castle with secret passages, ghosts, a persecuted heroine and a sinister villain belongs to the",
     "Gothic tradition", "pastoral tradition", "picaresque tradition", "epistolary tradition",
     "A", "Gothic fiction features mystery, terror, decaying settings and the supernatural."),
    (T_GEN, "Medium", "A novel set during the Nigerian Civil War that includes real generals and real battles alongside invented characters is",
     "a historical novel", "a science fiction novel", "a fable", "an allegory",
     "A", "Historical novels place fictional characters within real past events."),
    (T_GEN, "Medium", "A prose narrative in which a clever hare repeatedly outwits stronger animals, told by an elder to children, belongs to",
     "the trickster tale tradition of oral literature", "the epistolary tradition of the novel", "the sonnet tradition of lyric poetry", "the realist tradition of drama",
     "A", "Trickster tales (Tortoise, Hare, Ananse) are a staple of African oral literature."),
    (T_GEN, "Medium", "A poem of praise chanted for a Yoruba king, listing his ancestors, attributes and deeds, is an example of",
     "oral panegyric (praise) poetry", "the Petrarchan sonnet", "the dramatic monologue", "the mock epic",
     "A", "Oriki and similar forms are oral praise poems addressed to persons, lineages or towns."),
    (T_GEN, "Medium", "A short poem expressing the personal feelings of a single speaker, often musical in quality, is",
     "a lyric", "an epic", "a ballad", "a chronicle",
     "A", "Lyric poetry expresses the thoughts and emotions of a speaker; it was originally sung to the lyre."),
    (T_GEN, "Medium", "A poem in which a duke, speaking to a visitor, unintentionally reveals that he had his last wife killed, is",
     "a dramatic monologue", "an elegy", "a pastoral", "a limerick",
     "A", "In a dramatic monologue a single speaker addresses a silent listener and reveals his character, as in Browning's 'My Last Duchess'."),
    (T_GEN, "Medium", "A poem that idealises the simple life of shepherds in the countryside is",
     "a pastoral", "an epic", "a satire", "a limerick",
     "A", "Pastoral poetry presents rural life, especially that of shepherds, in an idealised way."),
    (T_GEN, "Medium", "A poem that uses the grand style of the epic to describe a trivial quarrel over a stolen lock of hair is",
     "a mock epic", "a true epic", "an elegy", "a ballad",
     "A", "The mock epic applies heroic conventions to trivial subjects for comic effect, as in Pope's 'The Rape of the Lock'."),
    (T_GEN, "Medium", "A sonnet that divides into an octave rhyming abbaabba and a sestet rhyming cdecde is",
     "a Petrarchan (Italian) sonnet", "a Shakespearean (English) sonnet", "a Spenserian sonnet", "a curtal sonnet",
     "A", "The Petrarchan sonnet has an octave and a sestet with a turn (volta) between them."),
    (T_GEN, "Medium", "The change in thought or mood between the octave and the sestet of a sonnet is called the",
     "volta", "caesura", "envoi", "refrain",
     "A", "The volta or 'turn' marks the shift in argument in a sonnet."),
    (T_GEN, "Medium", "A short poem ending with a witty or surprising twist, such as 'I am His Highness' dog at Kew; / Pray tell me, sir, whose dog are you?' is",
     "an epigram", "an epic", "an elegy", "an ode",
     "A", "An epigram is a brief, pointed poem or saying, often ending in a sting."),
    (T_GEN, "Medium", "A poem inscribed on a tombstone or written as if for one, summing up the life of the dead person, is",
     "an epitaph", "an epithet", "an epilogue", "an epigraph",
     "A", "An epitaph commemorates the dead; an epigraph is a quotation at the start of a work."),
    (T_GEN, "Medium", "A quotation placed at the beginning of a novel or chapter to suggest its theme is",
     "an epigraph", "an epitaph", "an epilogue", "an epigram",
     "A", "An epigraph is a motto or quotation prefixed to a work or section."),
    (T_GEN, "Medium", "A speech or section added at the end of a play or novel to round off the story is",
     "an epilogue", "a prologue", "an interlude", "an exposition",
     "A", "An epilogue concludes a work; a prologue introduces it."),
    (T_GEN, "Medium", "A long poem such as 'Sundiata' or 'The Iliad' celebrating the deeds of a national hero in elevated language is",
     "an epic", "a lyric", "a sonnet", "a limerick",
     "A", "The epic is a long narrative poem on a grand scale about heroic deeds."),
    (T_GEN, "Medium", "A poem that laments the death of a friend and ends with consolation is",
     "an elegy", "an ode", "a ballad", "an epigram",
     "A", "The elegy is a poem of mourning, usually moving from grief towards consolation."),
    (T_GEN, "Medium", "Free verse differs from blank verse in that free verse",
     "has neither regular metre nor rhyme, while blank verse is unrhymed iambic pentameter", "always rhymes, while blank verse never does",
     "is written only in couplets, while blank verse uses quatrains", "is used only in drama, while blank verse is used only in lyrics",
     "A", "Blank verse keeps a regular metre (iambic pentameter) without rhyme; free verse abandons regular metre too."),
    (T_GEN, "Medium", "A novel that presents a nightmarish future society controlled by a totalitarian government is",
     "a dystopian novel", "a pastoral novel", "a picaresque novel", "a Bildungsroman",
     "A", "Dystopian fiction imagines an oppressive future world, as in Orwell's '1984'."),
    (T_GEN, "Medium", "An account of the writer's own life, such as Wole Soyinka's 'Ake: The Years of Childhood', is",
     "an autobiography", "a biography", "a novel", "an epic",
     "A", "An autobiography is a life story written by its subject; a biography is written by someone else."),
    (T_GEN, "Medium", "A play that presents the everyday problems of ordinary people in a realistic setting, using natural dialogue, is called",
     "a domestic or realistic drama", "a masque", "a heroic tragedy", "a miracle play",
     "A", "Realistic (domestic) drama depicts ordinary life credibly, as in Ibsen's plays."),
    (T_GEN, "Medium", "In the theatre, the group of performers who comment on the action and sing between scenes, as in Greek tragedy, is the",
     "chorus", "cast", "audience", "orchestra",
     "A", "The chorus in Greek drama comments on events and expresses communal views."),
    (T_GEN, "Medium", "A literary work in which every character and event stands for an abstract idea, such as Bunyan's 'The Pilgrim's Progress', is",
     "an allegory", "a farce", "a limerick", "an epigram",
     "A", "Allegory carries a second, symbolic level of meaning throughout."),

    # ---------------- Themes and Characterisation ----------------
    (T_THEME, "Medium", "In a novel, a young woman defies her father, her village and her church to marry a man of a different tribe, and the story follows the consequences. The central theme is",
     "the conflict between individual choice and communal tradition", "the corrupting influence of political power",
     "the loneliness of old age", "the destructive power of greed",
     "A", "The heroine's personal choice is set against the demands of family, community and religion."),
    (T_THEME, "Medium", "A play shows a headmaster who preaches honesty at assembly but sells examination papers at night. The play's main concern is",
     "hypocrisy", "patriotism", "romantic love", "the beauty of nature",
     "A", "The gap between what the character professes and what he does is the essence of hypocrisy."),
    (T_THEME, "Medium", "A novel set in a Lagos slum follows a family that loses its home to a demolition ordered to make way for a luxury estate. The dominant theme is",
     "social injustice and the plight of the poor", "the joys of childhood", "the supernatural", "the conflict between generations",
     "A", "The poor are dispossessed for the benefit of the rich, which foregrounds injustice."),
    (T_THEME, "Medium", "A character who is described only as 'the greedy landlord' and behaves exactly the same on every appearance is",
     "a flat character", "a round character", "a dynamic character", "a foil",
     "A", "Flat characters are built around a single trait and do not develop."),
    (T_THEME, "Medium", "A heroine who is generous yet vain, brave yet impulsive, and who surprises the reader by her decisions is",
     "a round character", "a flat character", "a stock character", "a chorus",
     "A", "Round characters are complex, many-sided and capable of surprising the reader convincingly."),
    (T_THEME, "Medium", "In a play the hero's timid, cautious friend is placed beside him so that the hero's recklessness stands out. The friend serves as",
     "a foil", "a protagonist", "a narrator", "a chorus",
     "A", "A foil is a character whose qualities contrast with and highlight those of another."),
    (T_THEME, "Medium", "A character who begins a novel as a selfish miser and ends it as a generous benefactor after a night of visions is",
     "a dynamic character", "a static character", "a stock character", "a flat character",
     "A", "A dynamic character undergoes significant inner change, like Scrooge in 'A Christmas Carol'."),
    (T_THEME, "Medium", "Throughout a long novel the loyal servant remains exactly as faithful and cheerful at the end as at the beginning. He is",
     "a static character", "a dynamic character", "a tragic hero", "an anti-hero",
     "A", "A static character does not change in the course of the work."),
    (T_THEME, "Medium", "The main character of a novel is a cowardly, dishonest clerk with no admirable qualities, yet the story centres on him. He is",
     "an anti-hero", "a tragic hero", "a foil", "a confidant",
     "A", "An anti-hero is a central character who lacks conventional heroic virtues."),
    (T_THEME, "Medium", "A character to whom the heroine confides her secrets so that the audience learns her thoughts is",
     "a confidant(e)", "an antagonist", "a foil", "a narrator",
     "A", "The confidant exists largely to receive the protagonist's confidences."),
    (T_THEME, "Medium", "In a play, the villain's greed, ambition and hypocrisy are revealed not by the author's comment but through his own speeches and actions. This method of characterisation is",
     "indirect (dramatic) characterisation", "direct (expository) characterisation", "authorial intrusion", "stream of consciousness",
     "A", "Indirect characterisation lets readers infer traits from speech, action and the responses of others."),
    (T_THEME, "Medium", "A novelist writes, 'Chief Odili was a mean, suspicious man who trusted nobody.' This is an example of",
     "direct characterisation", "indirect characterisation", "dramatic irony", "symbolism",
     "A", "The narrator states the character's traits explicitly."),
    (T_THEME, "Medium", "A hero who is noble and admired but whose downfall is caused by excessive pride is a",
     "tragic hero", "stock character", "picaresque hero", "confidant",
     "A", "The tragic hero, in Aristotle's sense, is a great person brought down by a flaw (hamartia), often pride (hubris)."),
    (T_THEME, "Medium", "In a novel about the civil war, the constant presence of vultures over every scene of fighting is a",
     "motif", "foil", "subplot", "prologue",
     "A", "A motif is a recurring image or element that reinforces a theme."),
    (T_THEME, "Medium", "A play repeatedly shows fathers ruining their sons through excessive ambition for them. The recurring idea is the play's",
     "theme", "setting", "plot", "diction",
     "A", "The theme is the central idea explored through the action."),
    (T_THEME, "Medium", "In a story, a man who reported his neighbour to the secret police is himself arrested on the same neighbour's false report. This outcome illustrates",
     "poetic justice", "comic relief", "pathetic fallacy", "in medias res",
     "A", "Poetic justice is the fitting reward of virtue or punishment of vice within the work."),
    (T_THEME, "Medium", "A novel about a village girl who goes to the city, is corrupted by easy money and returns home broken deals mainly with the theme of",
     "the destructive lure of urban life", "the dignity of labour", "the innocence of childhood", "religious devotion",
     "A", "The city's temptations and their cost form the central concern."),
    (T_THEME, "Medium", "A poem describes a soldier's return to a village that no longer recognises him. Its central concern is",
     "alienation", "romantic love", "national pride", "the beauty of nature",
     "A", "The returning soldier's estrangement from his own community is alienation."),
    (T_THEME, "Medium", "A play presents a ruler who silences journalists, rigs elections and jails his rivals, and the chorus laments the people's suffering. The play is chiefly concerned with",
     "political oppression and the abuse of power", "the conflict between love and duty", "the pain of unrequited love", "the passage of time",
     "A", "Tyranny and its effects on the people dominate the action."),
    (T_THEME, "Medium", "A character called 'the Common Man' who plays a steward, a boatman, a jailer and an executioner in the same play represents",
     "the ordinary person who adapts to survive under any regime", "a single historical figure of great importance",
     "the playwright himself appearing on stage", "the supernatural forces controlling the plot",
     "A", "In Bolt's 'A Man for All Seasons' the Common Man stands for ordinary, self-preserving humanity."),
    (T_THEME, "Medium", "In a novel, the heroine's wicked stepmother, her handsome prince and her fairy godmother are all instantly recognisable types. Such characters are",
     "stock characters", "round characters", "dynamic characters", "narrators",
     "A", "Stock characters are conventional types familiar from many stories."),
    (T_THEME, "Medium", "A novelist shows a corrupt minister being kind to his children and generous to beggars while stealing public money. The purpose is most likely to",
     "present a complex, believable character rather than a simple villain", "prove that corruption is harmless",
     "show that the minister is a static character", "make the reader admire corruption",
     "A", "Mixing virtues and vices makes a round, credible character."),
    (T_THEME, "Medium", "A play in which a mother sacrifices her savings, health and reputation to see her son through university, only to be abandoned by him, explores the theme of",
     "ingratitude and parental sacrifice", "war and its aftermath", "religious hypocrisy", "the supernatural",
     "A", "The mother's sacrifice and the son's ingratitude form the central idea."),
    (T_THEME, "Medium", "Two brothers in a novel take opposite paths: one stays to farm the family land, the other goes abroad and forgets home. The novelist uses them to explore",
     "the tension between tradition and modernity", "the theme of romantic jealousy", "the horrors of slavery", "the innocence of childhood",
     "A", "The contrasting brothers embody the pull between old ways and new."),
    (T_THEME, "Medium", "The character through whose eyes and sympathies the reader experiences most of a novel is the",
     "protagonist", "antagonist", "foil", "chorus",
     "A", "The protagonist is the central figure whose fortunes the reader follows."),
    (T_THEME, "Medium", "In a play, the villain is not a person but the drought that slowly destroys the village. The antagonist here is",
     "an impersonal force of nature", "a flat character", "a confidant", "a stock villain",
     "A", "The antagonist may be a person, society, nature or the hero's own weakness."),
    (T_THEME, "Medium", "A poem in which a market woman's cheerful bargaining hides her grief for a dead child presents the character mainly through",
     "contrast between outward behaviour and inner feeling", "direct statement by the poet", "the opinions of other characters", "physical description alone",
     "A", "The gap between appearance and inner reality reveals her character."),
    (T_THEME, "Medium", "A novel about a lawyer who defends an innocent man against a hostile town, knowing he will lose, explores chiefly",
     "moral courage in the face of prejudice", "the pleasures of rural life", "the supernatural", "the conflict between generations",
     "A", "Standing for justice despite certain defeat is moral courage, as in Atticus Finch."),
    (T_THEME, "Medium", "A play about a girl promised in marriage to four suitors by her scheming father explores mainly",
     "greed, cunning and the commodification of marriage", "the horrors of war", "religious conversion", "the loneliness of exile",
     "A", "The father's trading of his daughter for gifts is the mainspring of 'The Marriage of Anansewa'."),
    (T_THEME, "Medium", "A play in which a whole wealthy family is shown to share responsibility for a poor girl's suicide is chiefly concerned with",
     "collective social responsibility", "the supernatural", "the beauty of the countryside", "romantic rivalry",
     "A", "Priestley's 'An Inspector Calls' insists that 'we are responsible for each other'."),
    (T_THEME, "Medium", "A poem in which a father tells his son that people now 'laugh with their teeth' and 'shake hands without hearts' deals with the theme of",
     "hypocrisy and the loss of sincerity in modern life", "the beauty of nature", "patriotic sacrifice", "the joy of friendship",
     "A", "Okara's 'Once Upon a Time' laments the false manners of modern society."),
    (T_THEME, "Medium", "A poem in which the speaker ignores the arrest of his neighbours one after another until the soldiers come for him deals with",
     "indifference to injustice and its consequences", "the pleasures of village life", "the sorrow of lost love", "the wonder of creation",
     "A", "Osundare's 'Not My Business' shows that silence in the face of tyranny finally costs the silent."),

    # ---------------- Plot, Setting and Structure ----------------
    (T_PLOT, "Medium", "A novel opens with the hero already on trial for murder and then goes back to narrate the events that led to the crime. The opening technique is called",
     "in medias res", "denouement", "exposition", "foreshadowing",
     "A", "Beginning 'in the middle of things' plunges the reader into the action before the background is supplied."),
    (T_PLOT, "Medium", "The part of a play in which the characters, setting and situation are introduced is the",
     "exposition", "climax", "falling action", "resolution",
     "A", "Exposition provides the background information needed to follow the plot."),
    (T_PLOT, "Medium", "The event that sets the main conflict of a story in motion, such as the arrival of a stranger claiming the hero's land, is the",
     "inciting incident", "denouement", "epilogue", "catharsis",
     "A", "The inciting incident launches the central conflict."),
    (T_PLOT, "Medium", "The series of events in which tension mounts as the hero struggles against obstacles is the",
     "rising action", "falling action", "exposition", "resolution",
     "A", "Rising action builds complications towards the climax."),
    (T_PLOT, "Medium", "The moment in a tragedy when the hero discovers that the man he has killed was his own father is",
     "the climax or turning point", "the exposition", "the prologue", "the subplot",
     "A", "The climax is the point of highest tension and decisive change in the hero's fortunes."),
    (T_PLOT, "Medium", "The events that follow the climax and lead towards the ending are the",
     "falling action", "rising action", "inciting incident", "exposition",
     "A", "Falling action shows the consequences of the climax."),
    (T_PLOT, "Medium", "The French term for the final unravelling of the plot, in which mysteries are explained and the fate of characters settled, is the",
     "denouement", "volta", "envoi", "coup de theatre",
     "A", "Denouement means 'untying' - the resolution of the complications."),
    (T_PLOT, "Medium", "A novel begins with the hero as an old man, then moves back to his childhood, and the rest of the book works forward to the opening scene. This structure uses",
     "an extended flashback", "a subplot", "a chorus", "an epigraph",
     "A", "Flashback (analepsis) narrates events earlier than the story's present."),
    (T_PLOT, "Medium", "In the first chapter a fortune-teller warns that 'water will take what fire has spared'. In the last chapter the hero drowns. The early warning is an example of",
     "foreshadowing", "flashback", "anticlimax", "comic relief",
     "A", "Foreshadowing hints at events to come."),
    (T_PLOT, "Medium", "In a play about a king's fall, the comic quarrels of two servants run alongside the main action. The servants' story is",
     "a subplot", "the exposition", "the climax", "the denouement",
     "A", "A subplot is a secondary line of action that parallels or contrasts with the main plot."),
    (T_PLOT, "Medium", "A novel set in Enugu in 1967, in a house where every window has been taped against bomb blasts, uses setting mainly to",
     "establish the atmosphere and historical context of war", "describe the beauty of the landscape", "introduce the narrator", "provide comic relief",
     "A", "Time and place here root the story in the Nigerian Civil War and create tension."),
    (T_PLOT, "Medium", "The time, place and social circumstances in which the action of a work occurs are together called the",
     "setting", "plot", "theme", "style",
     "A", "Setting includes historical period, geographical location and social environment."),
    (T_PLOT, "Medium", "A story in which the whole action takes place in one room during a single night observes",
     "unity of place and time", "the epistolary form", "in medias res", "the picaresque structure",
     "A", "The classical unities restrict a play to one place, one day and one action."),
    (T_PLOT, "Medium", "A novel in which each chapter is narrated by a different member of the same family, all describing the same funeral, has",
     "a multiple-viewpoint structure", "a chronological structure", "an epistolary structure", "a picaresque structure",
     "A", "Several narrators giving their own versions of events create a multiple-perspective structure."),
    (T_PLOT, "Medium", "A play in which the conflict is resolved by the sudden arrival of a rich uncle nobody had mentioned uses a device called",
     "deus ex machina", "dramatic irony", "soliloquy", "catharsis",
     "A", "Deus ex machina is an improbable, contrived resolution introduced from outside the plot."),
    (T_PLOT, "Medium", "A novel is told as a sequence of loosely connected episodes on a journey, any of which could be removed without damaging the story. Its plot is",
     "episodic", "tightly unified", "circular", "epistolary",
     "A", "Episodic plots string together separate incidents, as in picaresque fiction."),
    (T_PLOT, "Medium", "A story ends where it began, with the hero once again waiting at the same bus stop, so that the reader feels nothing has changed. The structure is",
     "circular", "linear", "episodic", "climactic",
     "A", "A circular (cyclical) structure returns to the opening situation."),
    (T_PLOT, "Medium", "The struggle between the hero and the forces opposing him, which drives the plot forward, is called",
     "conflict", "setting", "theme", "diction",
     "A", "Conflict is the clash of opposing forces at the centre of plot."),
    (T_PLOT, "Medium", "A character who must choose between saving his brother and keeping a promise to his dying father faces",
     "internal conflict", "conflict with nature", "conflict with society", "conflict with the supernatural",
     "A", "The struggle within a character's own mind is internal (man versus self) conflict."),
    (T_PLOT, "Medium", "A novel in which a fisherman battles a giant marlin and then sharks for three days presents mainly",
     "conflict between man and nature", "conflict between man and society", "conflict between man and himself", "conflict between two families",
     "A", "The struggle against natural forces is external conflict of the man-versus-nature kind."),
    (T_PLOT, "Medium", "A novel about a whistle-blower persecuted by his ministry, his neighbours and the press presents mainly",
     "conflict between the individual and society", "conflict between man and nature", "internal conflict", "conflict between rival lovers",
     "A", "The hero's struggle is against social institutions and pressures."),
    (T_PLOT, "Medium", "A short story in which a woman waits by a phone for news of her son, and the story ends without the call coming, uses",
     "an open ending", "a closed ending", "a happy ending", "a prologue",
     "A", "An open ending leaves the outcome unresolved for the reader to imagine."),
    (T_PLOT, "Medium", "A play in which the final scene shows the lovers married, the villain jailed and every mystery explained has",
     "a closed ending", "an open ending", "a circular structure", "a subplot",
     "A", "A closed ending ties up all the threads of the plot."),
    (T_PLOT, "Medium", "When a novel of many chapters is called 'well-made', the praise refers mainly to",
     "the tight, logical arrangement of its plot", "the beauty of its landscape descriptions", "the number of its characters", "its use of dialect",
     "A", "A well-made plot is carefully constructed so that every incident contributes to the whole."),
    (T_PLOT, "Medium", "A play in five acts in which the hero's fortunes rise until the third act and decline thereafter follows",
     "the classical pyramidal structure", "the epistolary structure", "the circular structure", "the stream-of-consciousness structure",
     "A", "Freytag's pyramid places the climax at the centre with rising action before and falling action after."),
    (T_PLOT, "Medium", "A novelist interrupts a tense scene of a robbery to spend a chapter on the hero's childhood. The interruption is",
     "a digression or flashback that delays the main action", "the climax of the novel", "the denouement", "an example of comic relief",
     "A", "A move away from the main action into earlier events is a flashback or digression."),
    (T_PLOT, "Medium", "In a novel the physical setting - a decaying mansion whose walls crack as the family quarrels - functions chiefly as",
     "a symbol of the family's collapse", "comic relief", "the antagonist", "a subplot",
     "A", "Setting can mirror and symbolise the state of the characters."),
    (T_PLOT, "Medium", "The statement 'The king died and then the queen died of grief' differs from 'The king died and then the queen died' in that the first",
     "is a plot, because it supplies causality", "is a setting, because it names the place", "is a theme, because it states an idea", "is a subplot, because it is secondary",
     "A", "E. M. Forster's distinction: a story is events in time; a plot is events linked by cause."),
    (T_PLOT, "Medium", "A novel set 'in a town very much like Onitsha, in the years just after independence' has a setting that is",
     "realistic but fictionalised", "fantastic", "allegorical", "pastoral",
     "A", "The setting draws on a real place and period without naming them exactly."),
    (T_PLOT, "Medium", "A tense, comic scene of a drunken porter joking at the gate immediately after a murder is an example of",
     "comic relief", "climax", "exposition", "foreshadowing",
     "A", "Comic relief eases tension in a serious work, as with the Porter in 'Macbeth'."),
    (T_PLOT, "Medium", "In a play, the last speech announces that the young couple will rebuild the burnt village together. This constitutes the",
     "resolution", "inciting incident", "exposition", "rising action",
     "A", "The resolution settles the outcome of the conflict."),

    # ---------------- Narrative Techniques and Point of View ----------------
    (T_NARR, "Medium", "'I was nine the year the soldiers came, and I remember the smell of the burning market more than anything.' The point of view is",
     "first person", "third person omniscient", "third person limited", "second person",
     "A", "The narrator uses 'I' and tells his own experience."),
    (T_NARR, "Medium", "'Amaka did not know that her brother, two streets away, was at that moment signing the papers that would ruin them both.' The narrator is",
     "omniscient", "first person", "unreliable", "a participant in the story",
     "A", "The narrator knows what Amaka does not and what is happening elsewhere - an all-knowing point of view."),
    (T_NARR, "Medium", "'She watched the door. Whatever he was deciding on the other side, she could only guess.' The narration is",
     "third person limited to one character", "first person", "omniscient", "second person",
     "A", "The narrator uses 'she' but is confined to her knowledge and perceptions."),
    (T_NARR, "Medium", "'You wake before the alarm. You dress in the dark so as not to wake her. You do not yet know this is the last time.' The narration is in the",
     "second person", "first person", "third person omniscient", "third person objective",
     "A", "The narrator addresses the character as 'you'."),
    (T_NARR, "Medium", "A story is narrated by a proud swindler who insists that everyone he cheated deserved it. The reader is expected to see more than he admits. He is",
     "an unreliable narrator", "an omniscient narrator", "an objective narrator", "a chorus",
     "A", "An unreliable narrator's account cannot be taken at face value because of bias, ignorance or self-deception."),
    (T_NARR, "Medium", "A narrator reports only what could be seen and heard, like a camera, never entering any character's mind. This is",
     "the objective (dramatic) point of view", "the omniscient point of view", "the first-person point of view", "stream of consciousness",
     "A", "The objective narrator records externals only, as in Hemingway's 'Hills Like White Elephants'."),
    (T_NARR, "Medium", "A novel is told by the hero's friend, who observes and reports the hero's rise and fall. This is",
     "first-person peripheral (observer) narration", "first-person central narration", "omniscient narration", "second-person narration",
     "A", "The narrator is a minor participant who tells someone else's story, like Nick in 'The Great Gatsby'."),
    (T_NARR, "Medium", "A novel consists entirely of letters exchanged between two sisters, one in Lagos and one in London. The technique is",
     "epistolary", "stream of consciousness", "frame narrative", "in medias res",
     "A", "The epistolary novel tells its story through letters (or diaries, e-mails)."),
    (T_NARR, "Medium", "'Rain again - Mama's cough - the bus fare - if only - forty naira short - his shoes, oh his shoes -' This passage uses",
     "stream of consciousness", "dialogue", "omniscient commentary", "epistolary narration",
     "A", "The unpunctuated flow of associated thoughts imitates the mind at work."),
    (T_NARR, "Medium", "A tale in which an old sailor tells his story to a wedding guest, so that the main story is enclosed inside another, uses",
     "a frame narrative", "an epistolary form", "second-person narration", "an objective point of view",
     "A", "A frame narrative is a story within a story, as in Coleridge's 'Rime of the Ancient Mariner'."),
    (T_NARR, "Medium", "'Dear reader, you may well ask why she did not simply leave him. I shall tell you.' This is an example of",
     "authorial intrusion", "stream of consciousness", "objective narration", "dramatic monologue",
     "A", "The narrator steps out of the story to address the reader directly."),
    (T_NARR, "Medium", "A chapter presents the same accident first through the driver's eyes and then through the victim's. The technique is",
     "shifting or multiple point of view", "objective narration", "epistolary narration", "flashback",
     "A", "The narrative perspective moves between characters."),
    (T_NARR, "Medium", "Instead of writing 'She was angry', the novelist writes, 'She set the plate down so hard the rice jumped.' This illustrates the technique of",
     "showing rather than telling", "telling rather than showing", "authorial intrusion", "summary narration",
     "A", "Showing presents concrete action for the reader to interpret; telling states the feeling."),
    (T_NARR, "Medium", "'Ten years passed. The children grew, the roof was mended twice, and Papa's hair turned white.' This is an example of",
     "summary narration", "scenic presentation", "dialogue", "soliloquy",
     "A", "Summary compresses a long period into a few sentences, unlike a scene presented moment by moment."),
    (T_NARR, "Medium", "A play uses a Storyteller who speaks directly to the audience, introduces characters and comments on their behaviour. This device draws on",
     "the African oral narrative tradition", "the epistolary novel", "the well-made play", "the theatre of the absurd",
     "A", "Sutherland's 'The Marriage of Anansewa' adapts the Ananse storyteller into the play."),
    (T_NARR, "Medium", "'He said he would come. He said it twice. He said it the way he said everything - as if saying it made it so.' The narrator's attitude is conveyed chiefly through",
     "tone", "setting", "rhyme", "stage directions",
     "A", "The dry repetition and comment reveal the narrator's sceptical tone."),
    (T_NARR, "Medium", "A novel about a war is narrated by a child who reports the adults' quarrels without understanding them, so the reader grasps more than the narrator. This creates",
     "dramatic irony", "comic relief", "poetic justice", "pathetic fallacy",
     "A", "The gap between the naive narrator's understanding and the reader's produces irony."),
    (T_NARR, "Medium", "In a novel the reader is told what every character in the village thinks, but the narrator never judges them. The narrator is best described as",
     "omniscient but non-intrusive", "first person and unreliable", "objective and limited", "second person",
     "A", "The narrator has full knowledge but withholds comment."),
    (T_NARR, "Medium", "A novelist tells a story of a marriage entirely through the husband's diary. A disadvantage of this technique is that",
     "the reader knows only what the diarist chooses to record", "the reader learns the thoughts of every character",
     "the story cannot have a plot", "the wife's feelings are reported directly",
     "A", "A single subjective document limits and possibly distorts what the reader can know."),
    (T_NARR, "Medium", "'The story you are about to read was found in a tin box in my late uncle's room. I have changed nothing.' This opening device is intended to",
     "create an impression of authenticity", "introduce the climax", "reveal the theme directly", "provide comic relief",
     "A", "The 'found manuscript' frame makes the fiction seem like a real document."),
    (T_NARR, "Medium", "In a play, a character alone on stage says, 'Now I am alone. O, what a rogue and peasant slave am I!' The speech is",
     "a soliloquy", "an aside", "a prologue", "a chorus",
     "A", "A soliloquy is a speech in which a character alone reveals inner thoughts."),
    (T_NARR, "Medium", "In a play, while two characters talk, a third turns to the audience and mutters, 'He lies; I saw him take it.' This is",
     "an aside", "a soliloquy", "an epilogue", "a monologue",
     "A", "An aside is a brief remark heard by the audience but not by the other characters."),
    (T_NARR, "Medium", "In drama, information about the past - a murder ten years ago, a lost will - is conveyed through the dialogue of characters rather than by a narrator. This is called",
     "dramatic exposition", "epistolary narration", "authorial intrusion", "summary narration",
     "A", "Plays deliver background information through what characters say and do."),
    (T_NARR, "Medium", "Notes in a play such as '(She crosses to the window, her back to him)' are",
     "stage directions", "asides", "soliloquies", "epigraphs",
     "A", "Stage directions instruct actors and directors on movement, gesture and setting."),
    (T_NARR, "Medium", "A novelist reproduces the speech of a Warri trader exactly as it sounds - 'Na wetin dey happen?' The use of such speech is called",
     "dialect or local colour", "blank verse", "stream of consciousness", "omniscient narration",
     "A", "Dialect gives characters authenticity and local flavour."),
    (T_NARR, "Medium", "An author who writes 'The little thief was, as thieves go, a rather charming one' is using",
     "an ironic authorial tone", "an objective point of view", "a stream-of-consciousness technique", "an epistolary form",
     "A", "The narrator's wry judgement colours the description."),
    (T_NARR, "Medium", "A short story ends with a sudden reversal - the beggar the heroine has been feeding turns out to be her long-lost father. The device is",
     "a twist or surprise ending", "in medias res", "exposition", "foreshadowing",
     "A", "A twist ending overturns the reader's expectations at the close, as in O. Henry's stories."),
    (T_NARR, "Medium", "The novelist presents a whole scene through what a servant overhears from behind a door. The servant is functioning as",
     "a reflector or focaliser", "an antagonist", "a chorus", "a foil",
     "A", "A focaliser is the character through whose perception the scene is filtered."),
    (T_NARR, "Medium", "A novel written entirely in the present tense - 'She opens the door. The room is empty.' - creates mainly",
     "immediacy, as if events unfold before the reader", "a sense of distance from events long past", "an epistolary effect", "dramatic exposition",
     "A", "Present-tense narration makes action feel immediate."),
    (T_NARR, "Medium", "In an oral tale the narrator pauses to ask the listeners, 'And what do you think the tortoise did next?' before continuing. This shows that oral narrative is",
     "participatory and interactive", "always in the third person", "fixed and unchangeable", "always tragic",
     "A", "Oral performance involves audience participation and response."),

    # ---------------- African Drama ----------------
    (T_AFD, "Medium", "In 'The Marriage of Anansewa', Ananse collects gifts from four chiefs by promising each of them his daughter. To escape the trap he has set for himself, he",
     "stages Anansewa's death to test which chief truly loves her", "sends Anansewa abroad to study",
     "marries Anansewa to the first chief who paid", "confesses everything to the chiefs and returns their gifts",
     "A", "The mock funeral reveals that only Chief-Who-Is-Chief responds with genuine love and generosity."),
    (T_AFD, "Medium", "The Storyteller in 'The Marriage of Anansewa' functions mainly to",
     "narrate, comment on the action and link the play to the Ananse folktale tradition", "act as Ananse's rival for the chiefs' gifts",
     "play the part of the fourth chief in disguise", "represent the colonial government",
     "A", "Sutherland's 'Anansegoro' form adapts the oral storyteller into the theatre."),
    (T_AFD, "Medium", "The musical interludes in 'The Marriage of Anansewa', performed by the players and audience, are called",
     "mboguo", "oriki", "griot", "kente",
     "A", "The mboguo are songs that comment on and advance the action, drawn from the Akan storytelling tradition."),
    (T_AFD, "Medium", "In 'The Marriage of Anansewa', Anansewa finally marries",
     "Chief-Who-Is-Chief", "the Chief of Sapa", "Togbe Klu IV", "the Chief of the Mines",
     "A", "Chief-Who-Is-Chief proves his love by his response to the news of her 'death', and she 'revives' to marry him."),
    (T_AFD, "Medium", "Ananse in 'The Marriage of Anansewa' is best described as",
     "a cunning trickster whose schemes nearly destroy him", "a noble chief betrayed by his daughter",
     "a foolish servant who cannot understand money", "a colonial officer imposing new laws",
     "A", "Ananse, the spider of folklore, is the archetypal trickster."),
    (T_AFD, "Medium", "In 'The Lion and the Jewel', Sidi rejects Lakunle's proposal chiefly because he",
     "refuses to pay the bride price, which she sees as an insult", "is much older than she is",
     "is already married to two wives", "has no education",
     "A", "Lakunle calls the bride price a 'savage custom'; Sidi thinks refusing it would brand her as no virgin."),
    (T_AFD, "Medium", "Baroka in 'The Lion and the Jewel' wins Sidi by",
     "pretending to Sadiku that he has become impotent, so that Sidi comes to mock him", "paying a larger bride price than Lakunle",
     "threatening to banish her family from Ilujinle", "promising to send her to school in Lagos",
     "A", "Sadiku spreads the false news; Sidi visits Baroka to taunt him and is seduced."),
    (T_AFD, "Medium", "In 'The Lion and the Jewel', Lakunle's half-digested Western ideas and his scorn for village customs make him",
     "a comic figure whose modernity is shallow", "the tragic hero of the play",
     "the wise voice of the community", "a symbol of traditional authority",
     "A", "Soyinka satirises Lakunle's confused, imitative 'progress'."),
    (T_AFD, "Medium", "The title 'The Lion and the Jewel' refers to",
     "Baroka and Sidi", "Lakunle and Sadiku", "Baroka and Lakunle", "Sidi and Sadiku",
     "A", "Baroka, the Bale, is the lion; Sidi, the village belle whose photograph appears in a magazine, is the jewel."),
    (T_AFD, "Medium", "A feature that distinguishes much African drama from the European well-made play is",
     "the integration of song, dance, drumming and audience participation into the action", "the total absence of any conflict",
     "the use of a single set and a single scene", "the exclusion of comic elements",
     "A", "African drama typically draws on communal performance traditions."),
    (T_AFD, "Medium", "In 'The Marriage of Anansewa', Christie (Christiana Yamoah) is",
     "Ananse's helper and companion who assists his schemes", "one of the four chiefs who court Anansewa",
     "Anansewa's grandmother who opposes the marriage", "the Storyteller in disguise",
     "A", "Christie supports Ananse in managing the chiefs and the mock funeral."),
    (T_AFD, "Medium", "In 'The Lion and the Jewel', the mime of the stranger with the camera, performed by the villagers, is an example of",
     "a play within the play used to narrate past events", "a soliloquy", "an aside", "an epilogue",
     "A", "The villagers act out the photographer's earlier visit - drama used as flashback."),

    # ---------------- Non-African Drama ----------------
    (T_NAD, "Medium", "In 'Antony and Cleopatra', Antony marries Octavia in order to",
     "strengthen his political alliance with Octavius Caesar", "punish Cleopatra for her unfaithfulness",
     "obey the command of the Roman Senate", "gain control of Pompey's fleet",
     "A", "The marriage to Caesar's sister is a political bond that Antony soon breaks by returning to Egypt."),
    (T_NAD, "Medium", "Enobarbus in 'Antony and Cleopatra' deserts Antony but dies soon afterwards because",
     "he is overwhelmed by shame when Antony sends his treasure after him", "Caesar has him executed as a traitor",
     "Cleopatra poisons him", "he is killed at the battle of Actium",
     "A", "Antony's generosity breaks Enobarbus's heart: 'I fight against thee! No: I will go seek some ditch wherein to die.'"),
    (T_NAD, "Medium", "The famous description of Cleopatra on her barge - 'The barge she sat in, like a burnished throne, / Burned on the water' - is spoken by",
     "Enobarbus", "Antony", "Octavius Caesar", "Charmian",
     "A", "Enobarbus describes her first meeting with Antony at Cydnus in Act 2."),
    (T_NAD, "Medium", "At the battle of Actium, Antony loses because he",
     "follows Cleopatra's fleeing ships and abandons the fight", "refuses to fight at sea",
     "is betrayed by Octavia", "is wounded by Caesar in single combat",
     "A", "Antony flies 'like a doting mallard' after Cleopatra's ships."),
    (T_NAD, "Medium", "Antony tries to kill himself after receiving false news that",
     "Cleopatra is dead", "Caesar has entered Alexandria", "Octavia has divorced him", "Enobarbus has betrayed him",
     "A", "Cleopatra sends Mardian to say she has died; Antony falls on his sword but does not die at once."),
    (T_NAD, "Medium", "Cleopatra chooses to die by the bite of the asp mainly because she",
     "refuses to be led in triumph through Rome by Caesar", "wishes to be reunited with Julius Caesar",
     "has been condemned to death by the Egyptian priests", "wants to punish Charmian and Iras",
     "A", "She will not be shown to 'the shouting varletry of censuring Rome' or mocked on the stage."),
    (T_NAD, "Medium", "'Age cannot wither her, nor custom stale / Her infinite variety' is said of",
     "Cleopatra", "Octavia", "Fulvia", "Charmian",
     "A", "Enobarbus sums up Cleopatra's endless fascination."),
    (T_NAD, "Medium", "The central conflict in 'Antony and Cleopatra' is between",
     "Antony's Roman duty and his passion for Cleopatra", "Cleopatra and Octavia over a throne",
     "Caesar and Pompey over the corn supply", "Enobarbus and Antony over strategy",
     "A", "Rome (duty, discipline, politics) is set against Egypt (pleasure, love, excess)."),
    (T_NAD, "Medium", "In 'An Inspector Calls', Eva Smith lost her job at Birling's factory because she",
     "led a group of workers asking for higher wages", "stole money from the office",
     "was rude to a customer in the shop", "refused to work on Sundays",
     "A", "Birling sacked her for asking for a rise after the strike."),
    (T_NAD, "Medium", "In 'An Inspector Calls', Sheila's part in Eva Smith's downfall was that she",
     "had her dismissed from Milwards out of jealousy and bad temper", "refused her charity at the Brumley Women's Organisation",
     "kept her as a mistress and then abandoned her", "got her pregnant and stole money to support her",
     "A", "Sheila used her family's influence to have the shop girl sacked."),
    (T_NAD, "Medium", "Mrs Birling's contribution to Eva Smith's fate in 'An Inspector Calls' was that she",
     "used her influence to refuse the girl help from a charity committee", "sacked her from the family factory",
     "reported her to the police for theft", "arranged for her to marry Gerald Croft",
     "A", "Mrs Birling turned the pregnant girl away, blaming the unknown father - who was her own son Eric."),
    (T_NAD, "Medium", "Mr Birling's confident claims in 'An Inspector Calls' that the Titanic is 'unsinkable' and that there will be no war are examples of",
     "dramatic irony, since the 1945 audience knows he is wrong", "foreshadowing of a happy ending",
     "comic relief provided by a servant", "poetic justice",
     "A", "The play is set in 1912, and the audience knows what followed."),
    (T_NAD, "Medium", "The Inspector's final speech in 'An Inspector Calls' warns that if men do not learn responsibility for one another they will be taught it 'in fire and blood and anguish'. The speech expresses the play's",
     "central message of social responsibility", "comic tone", "romantic subplot", "Gothic atmosphere",
     "A", "Priestley's socialist message is delivered through the Inspector."),
    (T_NAD, "Medium", "At the end of 'An Inspector Calls', the telephone rings to announce that",
     "a girl has just died and a police inspector is on his way", "Gerald has been arrested",
     "Eric has run away from home", "Birling has received his knighthood",
     "A", "After the family decides Goole was a hoax, the real call restores the mystery and the moral."),
    (T_NAD, "Medium", "In 'An Inspector Calls', the characters who show genuine remorse are",
     "Sheila and Eric", "Mr and Mrs Birling", "Gerald and Mr Birling", "Mrs Birling and Gerald",
     "A", "The younger generation accepts responsibility; the parents care only about scandal."),
    (T_NAD, "Medium", "In 'A Man for All Seasons', Sir Thomas More refuses to",
     "swear the oath acknowledging the King as head of the Church in England", "attend the King's wedding to Catherine of Aragon",
     "become Lord Chancellor after Wolsey", "allow his daughter Margaret to marry",
     "A", "More's conscience will not let him take the oath under the Act of Supremacy."),
    (T_NAD, "Medium", "In 'A Man for All Seasons', Richard Rich secures More's conviction by",
     "committing perjury at the trial", "producing a letter More wrote to the Pope",
     "confessing his own treason", "bribing the Duke of Norfolk",
     "A", "Rich falsely swears that More denied the King's title; More notes he has sold his soul 'for Wales'."),
    (T_NAD, "Medium", "In 'A Man for All Seasons', More's legal defence rests on the principle that",
     "silence must be taken as consent, so his silence cannot be treason", "the King is above the law",
     "a Chancellor cannot be tried", "conscience is a matter for Parliament",
     "A", "More argues 'qui tacet consentire' - the law presumes that silence gives consent, not denial."),
    (T_NAD, "Medium", "When Roper says he would cut down every law in England to get at the Devil, More replies that he would give the Devil benefit of law",
     "for his own safety's sake, because laws protect everyone", "because the Devil is innocent",
     "because Roper is a lawyer", "because the King commands it",
     "A", "'When the last law was down, and the Devil turned round on you - where would you hide?'"),
    (T_NAD, "Medium", "The Common Man in 'A Man for All Seasons' addresses the audience directly and changes roles on stage. This technique is associated with",
     "epic theatre and the breaking of dramatic illusion", "classical Greek tragedy", "the well-made play", "melodrama",
     "A", "Bolt borrowed Brechtian devices to keep the audience thinking rather than merely feeling."),

    # ---------------- African Prose ----------------
    (T_AFP, "Medium", "In Pede Hollist's 'So the Path Does Not Die', Fina's life is shaped by",
     "an initiation ceremony that was left incomplete in her childhood", "the death of her parents in the civil war",
     "her marriage to a wealthy chief in Freetown", "her election as a village leader",
     "A", "Her father's intervention in the Bondo initiation leads to the family's exile and Fina's lasting sense of not belonging."),
    (T_AFP, "Medium", "'So the Path Does Not Die' moves between Sierra Leone and",
     "the United States of America", "the United Kingdom", "Nigeria", "South Africa",
     "A", "Fina leaves Freetown for America, where she faces the problems of immigrant life."),
    (T_AFP, "Medium", "A central concern of 'So the Path Does Not Die' is",
     "the harm done by female genital mutilation and the search for identity in the diaspora", "the struggle for independence from colonial rule",
     "the corruption of a military government", "the rivalry between two football clubs",
     "A", "The novel examines a harmful tradition, women's choices and the alienation of the immigrant."),
    (T_AFP, "Medium", "In 'Second Class Citizen', Francis burns the manuscript of Adah's first novel, 'The Bride Price'. This act shows him as",
     "jealous and determined to crush her independence", "a supportive husband who wanted a better draft",
     "a publisher who rejected her work", "a religious man opposed to fiction",
     "A", "The burning of the manuscript is the final blow that leads Adah to leave him."),
    (T_AFP, "Medium", "The title 'Second Class Citizen' refers to Adah's status",
     "as a black immigrant woman in London and as a woman in her own culture", "as a junior civil servant in Lagos",
     "as a student who failed her examinations", "as the second wife of Francis",
     "A", "Adah is doubly marginalised - by race in England and by gender at home."),
    (T_AFP, "Medium", "In 'Unexpected Joy at Dawn', the separated siblings Nii Tackie and Mama Orojo live in",
     "Ghana and Nigeria respectively", "Ghana and Togo respectively", "Sierra Leone and Liberia respectively", "Nigeria and Cameroon respectively",
     "A", "The novel is set against the expulsions of aliens between Ghana and Nigeria."),
    (T_AFP, "Medium", "A common feature of African novels such as 'Things Fall Apart' and 'So the Path Does Not Die' is",
     "the tension between traditional customs and modern or foreign values", "the use of the epistolary form throughout",
     "a setting entirely in Europe", "the absence of female characters",
     "A", "Culture conflict is a major theme in African fiction."),
    (T_AFP, "Medium", "Adah in 'Second Class Citizen' can best be described as",
     "determined and resilient in the face of repeated setbacks", "timid and completely dependent on Francis",
     "wealthy and idle", "cruel to her children",
     "A", "Adah fights for education, work and independence against her husband and society."),

    # ---------------- Non-African Prose ----------------
    (T_NAP, "Medium", "In 'To Kill a Mockingbird', the story is narrated by",
     "Scout (Jean Louise Finch), looking back on her childhood", "Atticus Finch",
     "Jem Finch", "an omniscient narrator",
     "A", "The adult Scout recalls events in Maycomb when she was a child."),
    (T_NAP, "Medium", "In 'To Kill a Mockingbird', Atticus Finch defends",
     "Tom Robinson, a black man accused of raping Mayella Ewell", "Boo Radley, accused of murdering Bob Ewell",
     "Bob Ewell, accused of assaulting the children", "Dill, accused of running away from home",
     "A", "The trial of Tom Robinson is the centre of the novel."),
    (T_NAP, "Medium", "Atticus tells his children it is 'a sin to kill a mockingbird' because mockingbirds",
     "do nothing but sing and harm no one", "are protected by state law",
     "are the rarest birds in Alabama", "belong to Boo Radley",
     "A", "The mockingbird symbolises innocents such as Tom Robinson and Boo Radley."),
    (T_NAP, "Medium", "In 'To Kill a Mockingbird', Boo Radley finally emerges to",
     "save Jem and Scout from Bob Ewell's attack", "testify at Tom Robinson's trial",
     "confront Atticus about the children's games", "leave Maycomb for ever",
     "A", "Boo kills Bob Ewell while protecting the children; Sheriff Tate says Ewell 'fell on his knife'."),
    (T_NAP, "Medium", "Atticus's advice that you never understand a person 'until you climb into his skin and walk around in it' expresses the novel's theme of",
     "empathy", "revenge", "ambition", "patriotism",
     "A", "Learning to see from another's point of view is central to Scout's growth."),
    (T_NAP, "Medium", "Scout disperses the lynch mob outside the jail by",
     "talking innocently to Mr Cunningham about his son and his legal troubles", "threatening the men with Atticus's gun",
     "calling the sheriff on the telephone", "singing a hymn with Calpurnia",
     "A", "Her childish courtesy shames Cunningham into leading the men away."),
    (T_NAP, "Medium", "Mrs Dubose in 'To Kill a Mockingbird' is used by Atticus to teach Jem that real courage is",
     "fighting on when you know you are licked before you begin", "a man with a gun in his hand",
     "never speaking to one's enemies", "winning every argument",
     "A", "Mrs Dubose breaks her morphine addiction before dying."),
    (T_NAP, "Medium", "In 'Wuthering Heights', the story is told mainly through",
     "Lockwood's diary and Nelly Dean's narration to him", "Heathcliff's letters",
     "Catherine's diary alone", "an omniscient narrator",
     "A", "Bronte uses a double frame narrative: Lockwood records what Nelly tells him."),
    (T_NAP, "Medium", "Heathcliff is brought to Wuthering Heights as a child by",
     "Mr Earnshaw, who found him in Liverpool", "Hindley, who bought him from gypsies",
     "Edgar Linton, who adopted him", "Nelly Dean, his aunt",
     "A", "Old Mr Earnshaw returns from Liverpool with the 'gypsy brat'."),
    (T_NAP, "Medium", "Catherine's declaration 'I am Heathcliff' in 'Wuthering Heights' expresses",
     "her sense that her identity is inseparable from his", "her plan to disguise herself as him",
     "her decision to marry him immediately", "her hatred of Edgar Linton",
     "A", "She marries Edgar for status but feels her soul is one with Heathcliff's."),
    (T_NAP, "Medium", "The two houses in 'Wuthering Heights' - the Heights and Thrushcross Grange - symbolise",
     "wild passion and civilised refinement respectively", "poverty and religion respectively",
     "the town and the sea respectively", "childhood and old age respectively",
     "A", "The stormy Heights contrast with the calm, cultivated Grange."),
    (T_NAP, "Medium", "'Wuthering Heights' ends with",
     "the union of Hareton Earnshaw and the younger Catherine", "the marriage of Heathcliff and Catherine",
     "the destruction of both houses by fire", "Lockwood marrying Nelly Dean",
     "A", "The second generation heals the feud after Heathcliff's death."),
    (T_NAP, "Medium", "A novel such as 'To Kill a Mockingbird', which traces a child's growth in understanding of an adult world, can be described as",
     "a Bildungsroman", "a Gothic romance", "a picaresque novel", "an epistolary novel",
     "A", "The novel of formation follows the moral education of a young protagonist."),
    (T_NAP, "Medium", "In 'To Kill a Mockingbird', the gifts left in the knothole of the oak tree come from",
     "Boo Radley", "Atticus", "Dill", "Miss Maudie",
     "A", "Boo's secret gifts are ended when Nathan Radley fills the hole with cement."),

    # ---------------- African Poetry ----------------
    (T_AFPO, "Medium", "In Osundare's 'Not My Business', the refrain 'What business of mine is it / So long they don't take the yam / From my savouring mouth?' expresses",
     "selfish indifference to the suffering of others", "courage in defending neighbours",
     "gratitude for a good harvest", "grief at the death of a friend",
     "A", "The speaker ignores each arrest until the jeep comes for him."),
    (T_AFPO, "Medium", "The ending of 'Not My Business', in which the jeep waits 'on my bewildered lawn', shows that",
     "silence in the face of injustice does not protect the silent", "the soldiers have come to reward the speaker",
     "the speaker has finally reported his neighbours", "the yam harvest has failed",
     "A", "The speaker who minded 'his business' becomes the next victim."),
    (T_AFPO, "Medium", "The characters Akanni, Danladi and Chinwe in 'Not My Business' represent",
     "ordinary Nigerians from different regions victimised by a repressive regime", "the speaker's children",
     "the soldiers who carry out the arrests", "traditional rulers of the three regions",
     "A", "Their names, drawn from different ethnic groups, show that oppression spares no one."),
    (T_AFPO, "Medium", "In Okara's 'Once Upon a Time', the father says that people once 'laughed with their hearts and their eyes' but now 'laugh with their teeth'. The contrast is between",
     "sincerity and hypocrisy", "youth and age", "wealth and poverty", "war and peace",
     "A", "Genuine warmth has given way to hollow social pretence."),
    (T_AFPO, "Medium", "In 'Once Upon a Time', the father wants to 'unlearn all these muting things' and asks his son to",
     "show him how to laugh as he used to laugh as a child", "teach him to speak English",
     "forgive him for leaving home", "avoid all strangers",
     "A", "The child's natural laughter represents the innocence the father has lost."),
    (T_AFPO, "Medium", "'I have learned to wear many faces / like dresses' in 'Once Upon a Time' is an example of",
     "simile expressing social hypocrisy", "hyperbole expressing anger", "onomatopoeia", "apostrophe",
     "A", "The speaker compares his changing false expressions to changes of clothing."),
    (T_AFPO, "Medium", "In Soyinka's 'Night', the night is presented as",
     "an oppressive female presence whose 'hand is heavy' on the speaker's brow", "a friendly companion who brings rest",
     "a soldier guarding the city", "a child playing on the beach",
     "A", "The poem opens 'Your hand is heavy, Night, upon my brow' and personifies night as a powerful woman."),
    (T_AFPO, "Medium", "The line 'Hide me now, when night children haunt the earth' in Soyinka's 'Night' expresses the speaker's",
     "fear and desire for protection from the mysterious forces of night", "joy at the arrival of his children",
     "wish to join the night children in play", "anger at the noise of the city",
     "A", "The speaker feels vulnerable to the 'misted calls' that could 'undo' him."),
    (T_AFPO, "Medium", "In Osundare's 'The Leader and the Led', the animals reject the lion, hyena, giraffe and others as leaders because",
     "each has a flaw that makes it unfit to rule alone", "they are all too old",
     "they refuse to be chosen", "they cannot speak",
     "A", "The lion's 'paws are too fierce', the hyena's 'a stench', and so on."),
    (T_AFPO, "Medium", "The conclusion of 'The Leader and the Led' - a leader who 'knows how to follow' and followers 'mindful of their right to lead' - advocates",
     "leadership based on humility and mutual accountability", "military rule",
     "the rule of the strongest animal", "the abolition of all leaders",
     "A", "The forest sage recommends 'a hybrid of habits' - balanced, accountable leadership."),
    (T_AFPO, "Medium", "In Senghor's 'Black Woman', the poet celebrates the woman as",
     "a symbol of Africa's beauty and life-giving strength", "a victim of colonial exploitation",
     "a rival to the European woman", "a warrior in battle",
     "A", "'Naked woman, black woman, clothed with your colour which is life' - the woman embodies Africa itself."),
    (T_AFPO, "Medium", "'Black Woman' ends with the poet's wish to 'fix' the woman's beauty in the Eternal 'before jealous fate turns you to ashes'. This expresses",
     "the desire to preserve beauty through art against time and death", "fear of the woman's anger",
     "regret at leaving Africa", "a prayer for children",
     "A", "The poem, like many love poems, offers art as a defence against mortality."),
    (T_AFPO, "Medium", "The tone of Osundare's 'Not My Business' in the first three stanzas is best described as",
     "ironically detached and self-satisfied", "openly grief-stricken", "joyfully celebratory", "reverent and prayerful",
     "A", "The speaker's callous refrain is ironic; the poet condemns what the speaker approves."),
    (T_AFPO, "Medium", "A common feature of 'Not My Business' and 'Once Upon a Time' is that both",
     "use a simple, conversational voice to criticise a social evil", "are written in strict sonnet form",
     "celebrate the beauty of the African landscape", "are addressed to a dead lover",
     "A", "Both poems use plain language and a speaking voice to expose indifference and hypocrisy."),
    (T_AFPO, "Medium", "The image of the smile that is 'like a snake's bare fangs' in 'Once Upon a Time' suggests",
     "the speaker's awareness that his own false smile has become dangerous and unnatural", "his admiration for snakes",
     "his fear of animals", "his happiness at being home",
     "A", "Looking in the mirror, the speaker sees that his social smile has become predatory."),

    # ---------------- Non-African Poetry ----------------
    (T_NAPO, "Medium", "Byron's 'She Walks in Beauty' compares the woman to",
     "'the night / Of cloudless climes and starry skies'", "'a summer's day'",
     "'a red, red rose'", "'a host of golden daffodils'",
     "A", "The opening simile joins darkness and light in her beauty."),
    (T_NAPO, "Medium", "In 'She Walks in Beauty', 'One shade the more, one ray the less, / Had half impaired the nameless grace' suggests that the woman's beauty",
     "depends on a perfect balance of dark and light", "is entirely a matter of bright colours",
     "is spoilt by too much light", "cannot be seen at night",
     "A", "Any change in the mixture would diminish her grace."),
    (T_NAPO, "Medium", "The closing lines of 'She Walks in Beauty' - 'A mind at peace with all below, / A heart whose love is innocent!' - show that the poem praises",
     "inner goodness as well as outward beauty", "physical beauty alone",
     "the woman's wealth and rank", "the woman's skill in dancing",
     "A", "The final stanza moves from appearance to moral character."),
    (T_NAPO, "Medium", "In Heaney's 'Digging', the pen is compared to",
     "a gun and then to a spade", "a sword", "a plough", "a torch",
     "A", "'The squat pen rests; snug as a gun' opens the poem; it ends 'I'll dig with it'."),
    (T_NAPO, "Medium", "The speaker in 'Digging' says 'I've no spade to follow men like them' but resolves to dig with his pen. This expresses",
     "his continuation of the family tradition of labour through writing", "his rejection of his father and grandfather",
     "his decision to become a farmer", "his shame at being a poet",
     "A", "Writing becomes the poet's own form of digging into the past and the soil of memory."),
    (T_NAPO, "Medium", "'The cold smell of potato mould, the squelch and slap / Of soggy peat' in 'Digging' appeals to the senses of",
     "smell, hearing and touch", "sight only", "taste only", "hearing only",
     "A", "The lines combine olfactory, auditory and tactile imagery, with onomatopoeia in 'squelch and slap'."),
    (T_NAPO, "Medium", "In Maya Angelou's 'Still I Rise', the repeated line 'I rise' functions as",
     "a refrain asserting defiant resilience", "an apology for past mistakes",
     "a lament for lost youth", "a description of the sunrise",
     "A", "The refrain builds to a triumphant climax against oppression."),
    (T_NAPO, "Medium", "'You may write me down in history / With your bitter, twisted lies' in 'Still I Rise' addresses",
     "those who have oppressed and misrepresented black people", "the poet's own children",
     "a lover who has left", "a teacher at school",
     "A", "The 'you' is the oppressor whose version of history the speaker rejects."),
    (T_NAPO, "Medium", "'Cause I walk like I've got oil wells / Pumping in my living room' in 'Still I Rise' conveys",
     "confident self-worth that provokes the oppressor", "the speaker's actual wealth",
     "the speaker's love of luxury", "a complaint about poverty",
     "A", "The exaggerated image asserts pride and dignity that need no material basis."),
    (T_NAPO, "Medium", "'I'm a black ocean, leaping and wide' in 'Still I Rise' is",
     "a metaphor of vast, unstoppable power", "a simile about swimming",
     "an example of onomatopoeia", "a description of the sea at night",
     "A", "The speaker identifies herself with an ocean - immense and irresistible."),
    (T_NAPO, "Medium", "In W. W. Gibson's 'The Stone', the speaker is asked by a young woman to",
     "cut a gravestone for her lover, who was killed by a fall of stone", "build her a house of stone",
     "carve a statue of the king", "break the stone that blocks her road",
     "A", "The girl's lover died when 'the stone fell on him', and she asks the mason for 'a stone for him'."),
    (T_NAPO, "Medium", "The repeated question 'And will you cut a stone for him?' in Gibson's 'The Stone' gives the poem the quality of",
     "a ballad", "a sonnet", "a limerick", "an epigram",
     "A", "The refrain-like repetition and the tale of love and death are ballad features."),
    (T_NAPO, "Medium", "In Chaucer's 'The Nun's Priest's Tale', Chauntecleer is",
     "a proud cock who is nearly carried off by a fox", "a knight on a quest",
     "a monk who loves hunting", "a miller who cheats his customers",
     "A", "The tale is a beast fable set in a poor widow's yard."),
    (T_NAPO, "Medium", "The fox in 'The Nun's Priest's Tale' captures Chauntecleer by",
     "flattering him into closing his eyes to crow", "digging under the fence at night",
     "disguising himself as a hen", "offering him corn",
     "A", "Vanity makes Chauntecleer shut his eyes and stretch his neck to sing."),
    (T_NAPO, "Medium", "Chauntecleer escapes from the fox by",
     "persuading the fox to open his mouth to taunt the pursuers", "pecking out the fox's eyes",
     "calling on Pertelote to attack", "promising the fox a hen",
     "A", "The tale's morals: beware flattery, and do not speak when you should keep silent."),
    (T_NAPO, "Medium", "'The Nun's Priest's Tale' is an example of",
     "a mock-heroic beast fable", "a tragedy in blank verse", "a pastoral elegy", "an epistolary narrative",
     "A", "Chaucer treats a farmyard incident in the grand manner of epic and romance."),
    (T_NAPO, "Medium", "In Fleur Adcock's 'The Telephone Call', the speaker is told that she has won a huge lottery prize, but the callers finally reveal that",
     "they do not deal in money and only wanted her to experience the feeling of winning", "she must pay a fee to collect the prize",
     "the prize has been given to someone else", "she has won a car instead of money",
     "A", "The 'Universal Lotteries' turn out to be 'Experiential'; the call is a hoax."),
    (T_NAPO, "Medium", "The tone of the callers in 'The Telephone Call' is best described as",
     "breezily cheerful and manipulative", "solemn and threatening", "grief-stricken", "reverent",
     "A", "Their chirpy patter contrasts with the emptiness of what they offer."),
    (T_NAPO, "Medium", "In Angelou's 'Caged Bird', the free bird that 'dares to claim the sky' is contrasted with the caged bird whose 'wings are clipped and his feet are tied'. The two birds represent",
     "the privileged and the oppressed in a divided society", "the poet and her mother",
     "summer and winter in the American South", "the young and the old in one family",
     "A", "The free bird enjoys unearned liberty while the caged bird, standing for the oppressed, can only sing of freedom."),
    (T_NAPO, "Medium", "T. S. Eliot's 'The Journey of the Magi' ends with the speaker saying he 'should be glad of another death' because",
     "the birth of Christ has made his old world and beliefs meaningless", "the journey has exhausted him physically",
     "he has lost his camels and gifts", "he wishes to return to Bethlehem",
     "A", "The Birth was 'hard and bitter agony... like Death, our death'; he is alienated from 'the old dispensation'."),
    (T_NAPO, "Medium", "The image 'three trees on the low sky' in 'The Journey of the Magi' foreshadows",
     "the crucifixion", "the flight into Egypt", "the return of the Magi", "the star over Bethlehem",
     "A", "The three trees anticipate the three crosses of Calvary."),
    (T_NAPO, "Medium", "'Digging' and 'Still I Rise' are alike in that both",
     "draw strength from ancestors or forebears", "are written in strict sonnet form",
     "describe a journey by sea", "mourn the death of a child",
     "A", "Heaney honours his father and grandfather; Angelou speaks as 'the dream and the hope of the slave'."),
]

FIX = {
    "The purpose is most likely to": (
        "present a complex, believable character rather than a simple villain",
        "prove to the reader that corruption does no real harm to anyone",
        "show that the minister is a static character who never changes",
        "make the reader admire the minister and excuse his corruption"),
    "only to be abandoned by him, explores the theme of": (
        "ingratitude and parental sacrifice",
        "war and its aftermath in a village",
        "religious hypocrisy among the clergy",
        "the supernatural and ancestral spirits"),
    "presents the character mainly through": (
        "contrast between outward behaviour and inner feeling",
        "direct statement of her qualities by the poet",
        "the opinions expressed by the other market women",
        "detailed physical description of her appearance"),
    "promised in marriage to four suitors by her scheming father explores mainly": (
        "greed, cunning and the commodification of marriage",
        "the horrors of civil war and the plight of refugees",
        "religious conversion and the clash of faiths",
        "the loneliness of exile in a foreign country"),
    "'shake hands without hearts' deals with the theme of": (
        "hypocrisy and the loss of sincerity in modern life",
        "the beauty of nature and the changing seasons",
        "patriotic sacrifice in the struggle for freedom",
        "the joy of friendship between children at play"),
    "until the soldiers come for him deals with": (
        "indifference to injustice and its consequences",
        "the pleasures of village life and farming",
        "the sorrow of lost love and separation",
        "the wonder of creation and the natural world"),
    "spend a chapter on the hero's childhood. The interruption is": (
        "a digression or flashback that delays the main action",
        "the climax of the novel, where tension is highest",
        "the denouement, where all mysteries are explained",
        "an example of comic relief after a tense scene"),
    "a decaying mansion whose walls crack as the family quarrels - functions chiefly as": (
        "a symbol of the family's collapse",
        "comic relief from the quarrels",
        "the antagonist of the story",
        "a subplot running beside the main plot"),
    "she could only guess.' The narration is": (
        "third person limited to one character",
        "first person told by the woman herself",
        "omniscient, entering every mind",
        "second person addressing the reader"),
    "first through the driver's eyes and then through the victim's. The technique is": (
        "shifting or multiple point of view",
        "objective narration by a camera-eye",
        "epistolary narration through letters",
        "flashback to an earlier accident"),
    "The Storyteller in 'The Marriage of Anansewa' functions mainly to": (
        "narrate, comment on the action and link the play to the Ananse folktale tradition",
        "act as Ananse's chief rival for the gifts sent by the four chiefs to Anansewa",
        "play the part of the fourth chief in disguise so that Anansewa will not recognise him",
        "represent the colonial government and its officers in their dealings with the village"),
    "Sidi rejects Lakunle's proposal chiefly because he": (
        "refuses to pay the bride price, which she sees as an insult",
        "is much older than she is and already has grey hair",
        "is already married to two wives in another village",
        "has no education and cannot read the magazine"),
    "Baroka in 'The Lion and the Jewel' wins Sidi by": (
        "pretending to Sadiku that he has become impotent, so that Sidi comes to mock him",
        "paying a far larger bride price than Lakunle could ever afford to pay for her",
        "threatening to banish her family from Ilujinle if she refuses to become his wife",
        "promising to send her to school in Lagos and to build her a house with a tin roof"),
    "distinguishes much African drama from the European well-made play is": (
        "the integration of song, dance, drumming and audience participation into the action",
        "the total absence of any conflict between the characters from beginning to end",
        "the use of a single set and a single scene throughout the whole performance",
        "the complete exclusion of comic elements from plays on serious subjects"),
    "the mime of the stranger with the camera, performed by the villagers, is an example of": (
        "a play within the play used to narrate past events",
        "a soliloquy spoken by Lakunle to the audience",
        "an aside addressed to Sadiku by Baroka",
        "an epilogue that closes the action of the play"),
    "Enobarbus in 'Antony and Cleopatra' deserts Antony but dies soon afterwards because": (
        "he is overwhelmed by shame when Antony sends his treasure after him",
        "Caesar has him executed as a traitor who cannot be trusted by either side",
        "Cleopatra poisons him for advising Antony to fight on land instead of at sea",
        "he is fatally wounded at the battle of Actium while covering Antony's retreat"),
    "At the battle of Actium, Antony loses because he": (
        "follows Cleopatra's fleeing ships and abandons the fight",
        "refuses to fight at sea although his generals urge him to",
        "is betrayed by Octavia, who sends his plans to Caesar",
        "is wounded by Caesar in single combat before the battle"),
    "Mrs Birling's contribution to Eva Smith's fate in 'An Inspector Calls' was that she": (
        "used her influence to refuse the girl help from a charity committee",
        "sacked her from the family factory for asking for higher wages",
        "reported her to the police for stealing money from the shop",
        "arranged for her to be sent away so that Gerald would forget her"),
    "that there will be no war are examples of": (
        "dramatic irony, since the 1945 audience knows he is wrong",
        "foreshadowing of a happy ending for the Birling family",
        "comic relief provided by a foolish servant character",
        "poetic justice, since his predictions come true"),
    "The speech expresses the play's": (
        "central message of social responsibility",
        "comic tone and light-hearted atmosphere",
        "romantic subplot between Sheila and Gerald",
        "Gothic atmosphere of terror and mystery"),
    "the telephone rings to announce that": (
        "a girl has just died and a police inspector is on his way",
        "Gerald has been arrested for his part in the girl's death",
        "Eric has run away from home and taken the stolen money",
        "Birling has received the knighthood he was hoping for"),
    "More's legal defence rests on the principle that": (
        "silence must be taken as consent, so his silence cannot be treason",
        "the King is above the law and therefore cannot be a party to a trial",
        "a Lord Chancellor cannot be tried by any court below Parliament",
        "conscience is a matter for Parliament and not for individual men"),
    "More replies that he would give the Devil benefit of law": (
        "for his own safety's sake, because laws protect everyone",
        "because the Devil is innocent until he is proved guilty",
        "because Roper is a lawyer and must respect the courts",
        "because the King commands it and must be obeyed"),
    "This technique is associated with": (
        "epic theatre and the breaking of dramatic illusion",
        "classical Greek tragedy and the use of a chorus",
        "the well-made play of the nineteenth century",
        "melodrama and its stock heroes and villains"),
    "A central concern of 'So the Path Does Not Die' is": (
        "the harm done by female genital mutilation and the search for identity in the diaspora",
        "the struggle for independence from colonial rule and the rise of the first nationalists",
        "the corruption of a military government and the journalists who try to expose it",
        "the rivalry between two football clubs and the violence between their supporters"),
    "The title 'Second Class Citizen' refers to Adah's status": (
        "as a black immigrant woman in London and as a woman in her own culture",
        "as a junior civil servant in the Lagos office of the American consulate",
        "as a student who failed her examinations and lost her scholarship",
        "as the second wife of Francis, who married another woman in London"),
    "'Things Fall Apart' and 'So the Path Does Not Die' is": (
        "the tension between traditional customs and modern or foreign values",
        "the use of the epistolary form of letters throughout the whole novel",
        "a setting entirely in Europe with no scenes on the African continent",
        "the absence of any female characters of importance to the plot"),
    "In 'To Kill a Mockingbird', the story is narrated by": (
        "Scout (Jean Louise Finch), looking back on her childhood",
        "Atticus Finch, recalling the trial many years later",
        "Jem Finch, writing as a lawyer in his old age",
        "an omniscient narrator who enters every character's mind"),
    "Scout disperses the lynch mob outside the jail by": (
        "talking innocently to Mr Cunningham about his son and his legal troubles",
        "threatening the men with the shotgun that Atticus keeps in the house",
        "calling the sheriff on the telephone from the newspaper office",
        "singing a hymn with Calpurnia until the men become ashamed"),
    "to teach Jem that real courage is": (
        "fighting on when you know you are licked before you begin",
        "a man with a gun in his hand facing down a dangerous enemy",
        "never speaking to one's enemies or answering their insults",
        "winning every argument by being cleverer than one's opponent"),
    "In 'Wuthering Heights', the story is told mainly through": (
        "Lockwood's diary and Nelly Dean's narration to him",
        "Heathcliff's letters to Catherine from abroad",
        "Catherine's diary alone, found after her death",
        "an omniscient narrator who comments on events"),
    "From my savouring mouth?' expresses": (
        "selfish indifference to the suffering of others",
        "courage in defending neighbours from the soldiers",
        "gratitude for a good harvest of yams and corn",
        "grief at the death of a friend taken by the jeep"),
    "The characters Akanni, Danladi and Chinwe in 'Not My Business' represent": (
        "ordinary Nigerians from different regions victimised by a repressive regime",
        "the speaker's children, who are taken away one after another by the soldiers",
        "the soldiers who carry out the arrests on the orders of the government",
        "traditional rulers of the three regions who collaborate with the regime"),
    "and asks his son to": (
        "show him how to laugh as he used to laugh as a child",
        "teach him to speak English like the people in town",
        "forgive him for leaving home to work in the city",
        "avoid all strangers who laugh with their teeth"),
    "In Soyinka's 'Night', the night is presented as": (
        "an oppressive female presence whose 'hand is heavy' on the speaker's brow",
        "a friendly companion who brings rest and sweet dreams to the tired speaker",
        "a soldier guarding the city against the thieves who come out after dark",
        "a child playing on the beach while the speaker watches from the shore"),
    "in Soyinka's 'Night' expresses the speaker's": (
        "fear and desire for protection from the mysterious forces of night",
        "joy at the arrival of his children after a long journey home",
        "wish to join the night children in their games on the sand",
        "anger at the noise of the city that keeps him awake till dawn"),
    "the animals reject the lion, hyena, giraffe and others as leaders because": (
        "each has a flaw that makes it unfit to rule alone",
        "they are all too old to lead the animals to water",
        "they refuse to be chosen and hide in the forest",
        "they cannot speak the language of the other animals"),
    "'mindful of their right to lead' - advocates": (
        "leadership based on humility and mutual accountability",
        "military rule by the strongest and most feared animal",
        "the rule of the oldest animal in the whole forest",
        "the abolition of all leaders and the end of authority"),
    "In Senghor's 'Black Woman', the poet celebrates the woman as": (
        "a symbol of Africa's beauty and life-giving strength",
        "a victim of colonial exploitation and forced labour",
        "a rival to the European woman in elegance and wealth",
        "a warrior in battle against the invaders of her land"),
    "'before jealous fate turns you to ashes'. This expresses": (
        "the desire to preserve beauty through art against time and death",
        "fear of the woman's anger if the poet should ever leave her",
        "regret at leaving Africa for a life of exile in France",
        "a prayer for children who will inherit the woman's beauty"),
    "in the first three stanzas is best described as": (
        "ironically detached and self-satisfied",
        "openly grief-stricken and mournful",
        "joyfully celebratory and thankful",
        "reverent, prayerful and solemn"),
    "'like a snake's bare fangs' in 'Once Upon a Time' suggests": (
        "the speaker's awareness that his own false smile has become dangerous and unnatural",
        "his admiration for snakes, which he regards as the most beautiful of all creatures",
        "his fear of animals, which has grown since he moved from the village to the town",
        "his happiness at being home again among people who laugh with their hearts"),
    "Byron's 'She Walks in Beauty' compares the woman to": (
        "'the night / Of cloudless climes and starry skies'",
        "'a summer's day' that is 'more lovely and more temperate'",
        "'a red, red rose / That's newly sprung in June'",
        "'a host of golden daffodils' beside the lake"),
    "but resolves to dig with his pen. This expresses": (
        "his continuation of the family tradition of labour through writing",
        "his rejection of his father and grandfather and their way of life",
        "his decision to give up poetry and become a farmer like them",
        "his shame at being a poet in a family of hard-working farmers"),
    "in 'Still I Rise' addresses": (
        "those who have oppressed and misrepresented black people",
        "the poet's own children, who have forgotten their history",
        "a lover who has left her for another woman",
        "a teacher at school who gave her low marks in history"),
    "in 'Still I Rise' conveys": (
        "confident self-worth that provokes the oppressor",
        "the speaker's actual wealth from the oil business",
        "the speaker's love of luxury and expensive things",
        "a complaint about poverty and the lack of a proper house"),
    "the speaker is asked by a young woman to": (
        "cut a gravestone for her lover, who was killed by a fall of stone",
        "build her a house of stone on the hill above the village",
        "carve a statue of the king for the square in the market town",
        "break the stone that blocks the road to her lover's farm"),
    "Chauntecleer escapes from the fox by": (
        "persuading the fox to open his mouth to taunt the pursuers",
        "pecking out the fox's eyes while he runs through the wood",
        "calling on Pertelote and the hens to attack the fox together",
        "promising the fox a fat hen if he will let him go free"),
    "but the callers finally reveal that": (
        "they do not deal in money and only wanted her to experience the feeling of winning",
        "she must pay a large registration fee before the prize money can be sent to her",
        "the prize has been given to someone else because she took too long to answer",
        "she has won a car instead of money and must collect it from another city"),
    "The tone of the callers in 'The Telephone Call' is best described as": (
        "breezily cheerful and manipulative",
        "solemn, threatening and cold",
        "grief-stricken and full of pity",
        "reverent, humble and apologetic"),
    "he 'should be glad of another death' because": (
        "the birth of Christ has made his old world and beliefs meaningless",
        "the journey has exhausted him physically and he longs for rest",
        "he has lost his camels and gifts and cannot face his people",
        "he wishes to return to Bethlehem and die near the child"),
}


def build():
    build_batch(
        S, "batch_029_lit_round3b.json", "batch_029_lit_round3b",
        "Literature in English round 3 (part B): genre and forms, themes and characterisation, plot/setting/structure and narrative techniques - each item built around a scenario or mini-extract - plus general items on the widely read set texts (Antony and Cleopatra, To Kill a Mockingbird, An Inspector Calls, A Man for All Seasons, The Marriage of Anansewa, The Lion and the Jewel, Second Class Citizen, Wuthering Heights, So the Path Does Not Die) and the commonly prescribed African and non-African poems.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
