"""Batch 027 - Christian Religious Studies round 3, part C (Acts, the Epistles and Christian living).

Love, fellowship in the early church, the Holy Spirit and mission, opposition, mission to the Gentiles,
justification by faith, law and grace, new life in Christ, joint heirs, humility, forgiveness, spiritual
gifts, giving, civic responsibility, dignity of labour, second coming, impartiality, prayer, community
living, corruption and sexual immorality.  Scripture-based and application (scenario) items.

    python3 scripts/build_content_batch27.py -> content/batch_027_crs_round3c.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Christian Religious Studies"

T_LOVE = "Love"
T_FELL = "Fellowship in the Early Church"
T_HS = "The Holy Spirit and the Mission of the Church"
T_OPP = "Opposition to the Gospel Message"
T_GENT = "Mission to the Gentiles"
T_JUST = "Justification by Faith"
T_LAW = "The Law and Grace"
T_NEW = "New Life in Christ"
T_HEIR = "Christians as Joint Heirs with Christ"
T_HUM = "Humility"
T_FORG = "Forgiveness"
T_GIFT = "Spiritual Gifts"
T_GIVE = "Christian Giving"
T_CIVIC = "Civic Responsibility"
T_LAB = "Dignity of Labour"
T_SEC = "The Second Coming of Christ"
T_IMP = "Impartiality"
T_PRAY = "Effective Prayer"
T_COMM = "Christian Living in the Community"
T_CORR = "Corruption"
T_SEX = "Sexual Immorality"

PASSAGES = []
PQ = []

Q = [
    # ---------------- Love ----------------
    (T_LOVE, "Medium", "Paul wrote, 'Love is patient and kind; love is not jealous or boastful; it is not arrogant or rude.' A church elder who constantly reminds members of how much he has done for the church is failing the test that love",
     "is not boastful or arrogant",
     "bears all things and endures all things",
     "does not rejoice at wrong",
     "is patient and kind",
     "A", "1 Corinthians 13:4: genuine love does not parade its achievements or seek recognition."),
    (T_LOVE, "Medium", "Paul said that faith, hope and love abide, 'but the greatest of these is love', because",
     "love never ends, whereas prophecy, tongues and knowledge will pass away",
     "love is easier to practise than either faith or hope",
     "faith and hope were given only to the apostles",
     "love was the only gift the Corinthians possessed",
     "A", "1 Corinthians 13:8-13: love outlasts every gift and belongs to the perfect age to come."),
    (T_LOVE, "Medium", "John wrote, 'If any one says, I love God, and hates his brother, he is a liar; for he who does not love his brother whom he has seen, cannot love God whom he has not seen.' A member who fasts weekly but refuses to greet a fellow member is",
     "contradicting his claim to love God by his hatred of his brother",
     "showing that love of God is more important than love of neighbour",
     "practising the higher form of love that John commended",
     "keeping the first commandment while ignoring only a minor rule",
     "A", "1 John 4:20-21: love for God is proved by love for the brethren; the two cannot be separated."),
    (T_LOVE, "Medium", "'Greater love has no man than this, that a man lay down his life for his friends.' Jesus demonstrated this",
     "by dying on the cross for those he called his friends",
     "by washing the feet of the disciples at the supper",
     "by feeding the five thousand in the wilderness",
     "by raising Lazarus from the dead at Bethany",
     "A", "John 15:13; Romans 5:8: 'While we were yet sinners Christ died for us.'"),
    (T_LOVE, "Medium", "When a lawyer asked, 'Who is my neighbour?' Jesus told the parable of the Good Samaritan and then asked, 'Which of these three proved neighbour to the man who fell among the robbers?' Jesus turned the question round to show that",
     "the real issue is not who deserves my love but whether I act as a neighbour to anyone in need",
     "Samaritans were better neighbours than Jews by nature",
     "priests and Levites were excused from helping the wounded",
     "only those who live nearby can be regarded as neighbours",
     "A", "Luke 10:29-37: 'Go and do likewise' - neighbour-love is defined by the one who shows mercy."),
    (T_LOVE, "Medium", "John wrote, 'In this is love, not that we loved God but that he loved us and sent his Son to be the expiation for our sins.' This teaches that",
     "God's love came first and is the source and model of our love",
     "human love for God earns the sending of the Son",
     "love is a feeling that cannot be commanded",
     "only those who first love God are loved by him",
     "A", "1 John 4:10, 19: 'We love, because he first loved us.'"),

    # ---------------- Fellowship in the Early Church ----------------
    (T_FELL, "Medium", "After Pentecost the believers 'devoted themselves to the apostles' teaching and fellowship, to the breaking of bread and the prayers'. A church that concentrates on entertainment and fund-raising while neglecting Bible teaching and prayer has departed from",
     "the pattern of the first Christian community in Jerusalem",
     "the instructions Paul gave to the church at Corinth",
     "the decision of the Council of Jerusalem",
     "the practice of the synagogue in Nazareth",
     "A", "Acts 2:42: teaching, fellowship, breaking of bread and prayer were the four marks of the early church."),
    (T_FELL, "Medium", "Barnabas sold a field and laid the money at the apostles' feet. His act was praised because",
     "it was a voluntary gift for the needs of the whole community",
     "he was the richest member of the Jerusalem church",
     "the apostles had demanded that every member sell his land",
     "he kept part of the price for his own use",
     "A", "Acts 4:36-37: Barnabas, 'son of encouragement', gave freely, in contrast to Ananias and Sapphira."),
    (T_FELL, "Medium", "Peter told Ananias, 'While it remained unsold, did it not remain your own? And after it was sold, was it not at your disposal?' This shows that the sin of Ananias and Sapphira was",
     "lying to the Holy Spirit by pretending to give the whole price",
     "selling property that belonged to the church",
     "refusing to sell their property like the others",
     "giving too small a portion of the price to the apostles",
     "A", "Acts 5:3-4: they were free to keep the money; their sin was deceit that sought credit for generosity they had not shown."),
    (T_FELL, "Medium", "The Hellenists murmured against the Hebrews because their widows were neglected in the daily distribution. The apostles solved the problem by",
     "appointing seven men of good repute to serve tables while they gave themselves to prayer and the word",
     "expelling the Hellenists from the church in Jerusalem",
     "sending the Hebrew widows back to their home towns",
     "abolishing the daily distribution altogether",
     "A", "Acts 6:1-6: Stephen, Philip and five others were chosen, and the word of God increased."),
    (T_FELL, "Medium", "A church treasurer publicly announces a huge pledge, is applauded, and later secretly pays only a fraction while insisting he paid everything. His conduct resembles that of",
     "Ananias and Sapphira",
     "Barnabas of Cyprus",
     "Simon the sorcerer",
     "Cornelius the centurion",
     "A", "Acts 5:1-11: the couple lied about the amount given in order to appear more generous than they were."),
    (T_FELL, "Medium", "Luke records that the early believers 'were of one heart and soul, and no one said that any of the things which he possessed was his own'. A youth fellowship whose members pay each other's school fees and share food in hard times is practising",
     "the communal sharing of the early church",
     "the tithing law of the Old Testament",
     "the collection Paul organised for Jerusalem",
     "the Nazirite vow of separation",
     "A", "Acts 4:32-35: 'there was not a needy person among them' because the believers shared what they had."),

    # ---------------- The Holy Spirit and the Mission of the Church ----------------
    (T_HS, "Medium", "On the day of Pentecost the crowd asked, 'What does this mean?' while others mocked, saying, 'They are filled with new wine.' Peter answered that",
     "this was the fulfilment of Joel's prophecy that God would pour out His Spirit on all flesh",
     "the disciples had indeed been drinking at the feast",
     "the crowd should return to their countries at once",
     "only the apostles could ever receive the Holy Spirit",
     "A", "Acts 2:14-21: Peter quoted Joel 2:28-32 and preached Christ crucified and risen."),
    (T_HS, "Medium", "When the crowd at Pentecost were 'cut to the heart' and asked, 'Brethren, what shall we do?' Peter told them to",
     "repent and be baptised in the name of Jesus Christ for the forgiveness of sins",
     "go back to the temple and offer a sin offering",
     "wait in Jerusalem until the Spirit came upon them",
     "sell their possessions and give the money to the apostles",
     "A", "Acts 2:37-41: about three thousand were baptised and added that day."),
    (T_HS, "Medium", "Jesus promised, 'The Counsellor, the Holy Spirit, whom the Father will send in my name, he will teach you all things, and bring to your remembrance all that I have said to you.' This promise assured the disciples that",
     "the Spirit would guide them into the truth after Jesus had gone",
     "they would never need to study the scriptures again",
     "Jesus would remain physically present with them for ever",
     "the Spirit would replace the need for prayer",
     "A", "John 14:26 and 16:13: the Spirit continues the teaching ministry of Jesus in the church."),
    (T_HS, "Medium", "The Holy Spirit said to the church at Antioch, 'Set apart for me Barnabas and Saul for the work to which I have called them.' This shows that",
     "the Spirit directs the missionary work of the church",
     "the apostles in Jerusalem appointed all missionaries",
     "Antioch had replaced Jerusalem as the mother church",
     "Barnabas and Saul chose their own field of work",
     "A", "Acts 13:1-3: the church fasted, prayed, laid hands on them and sent them off, 'being sent out by the Holy Spirit'."),
    (T_HS, "Medium", "Philip was directed by the Spirit to join the chariot of the Ethiopian eunuch, who was reading Isaiah 53. Philip",
     "began with that scripture and told him the good news of Jesus, and baptised him",
     "told him to go to Jerusalem and ask the apostles for an explanation",
     "refused to speak to him because he was a foreigner",
     "sold him a copy of the gospel of Matthew",
     "A", "Acts 8:26-39: the Spirit led Philip to a Gentile seeker, and the gospel began to reach Africa."),
    (T_HS, "Medium", "A church committee chooses a mission field purely because it is comfortable and well funded, without prayer. Acts 13 and 16 suggest they have forgotten that",
     "the Spirit calls and directs missionaries, sometimes forbidding one route and opening another",
     "missionaries should always go to the wealthiest cities first",
     "only ordained apostles may choose a mission field",
     "mission work should be confined to one's own tribe",
     "A", "Acts 16:6-10: Paul was forbidden by the Spirit to preach in Asia and was directed by a vision to Macedonia."),

    # ---------------- Opposition to the Gospel Message ----------------
    (T_OPP, "Medium", "After being beaten by order of the Sanhedrin, the apostles left 'rejoicing that they were counted worthy to suffer dishonour for the name'. Their attitude shows that",
     "suffering for Christ was regarded as an honour, not a cause for despair",
     "the beating had been light and did them no real harm",
     "they expected the council to apologise the next day",
     "they had decided to stop preaching in the temple",
     "A", "Acts 5:40-42: they continued every day in the temple and at home to teach and preach Jesus as the Christ."),
    (T_OPP, "Medium", "Stephen's speech before the council ended with the charge, 'You stiff-necked people... you always resist the Holy Spirit. As your fathers did, so do you.' The council responded by",
     "grinding their teeth, casting him out of the city and stoning him",
     "releasing him because his speech had convinced them",
     "referring the case to the Roman governor Felix",
     "appointing him to preach in the synagogue of the Freedmen",
     "A", "Acts 7:51-60: Stephen saw the Son of man standing at God's right hand and died praying for his killers."),
    (T_OPP, "Medium", "After Stephen's death a great persecution scattered the church, 'and those who were scattered went about preaching the word'. The result was that",
     "the persecution spread the gospel to Samaria and beyond instead of stopping it",
     "the church in Jerusalem ceased to exist for many years",
     "the apostles fled to Rome and never returned",
     "the believers renounced their faith to save their lives",
     "A", "Acts 8:1-4: opposition became the means of expansion, fulfilling Acts 1:8."),
    (T_OPP, "Medium", "Herod killed James the brother of John with the sword and imprisoned Peter, but 'earnest prayer for him was made to God by the church'. The outcome was that",
     "an angel released Peter from prison during the night",
     "Peter was executed the following morning",
     "Herod repented and became a Christian",
     "the church paid a ransom for Peter's release",
     "A", "Acts 12:1-17: Peter's chains fell off and he walked out past the guards to the house where the church was praying."),
    (T_OPP, "Medium", "At Philippi, after being beaten and thrown into the inner prison with their feet in the stocks, Paul and Silas",
     "prayed and sang hymns to God at midnight while the prisoners listened",
     "cursed the magistrates and demanded to see the emperor",
     "bribed the jailer to let them escape before dawn",
     "renounced their Roman citizenship to gain release",
     "A", "Acts 16:22-34: an earthquake opened the doors, and the jailer and his household believed and were baptised."),
    (T_OPP, "Medium", "A Christian teacher is mocked by colleagues for refusing to falsify results, yet she continues cheerfully and wins some of them over. Her response reflects the apostles' example of",
     "rejoicing under dishonour for the name of Christ and continuing to witness",
     "withdrawing from public life until persecution ceases",
     "returning insult for insult to defend the gospel",
     "reporting the mockers to the authorities for punishment",
     "A", "Acts 5:41-42; 1 Peter 4:14, 16: 'If you are reproached for the name of Christ, you are blessed.'"),

    # ---------------- Mission to the Gentiles ----------------
    (T_GENT, "Medium", "When Peter came to Cornelius he said, 'You yourselves know how unlawful it is for a Jew to associate with or to visit any one of another nation; but God has shown me that I should not call any man common or unclean.' Peter learned this lesson through",
     "the vision of the great sheet let down from heaven",
     "the teaching of Gamaliel in Jerusalem",
     "a letter from Paul about the Gentile churches",
     "the conversion of the Ethiopian eunuch by Philip",
     "A", "Acts 10:9-16, 28: the vision of clean and unclean animals prepared Peter to accept Gentiles."),
    (T_GENT, "Medium", "While Peter was still speaking at the house of Cornelius, the Holy Spirit fell on all who heard the word. Peter then said,",
     "'Can any one forbid water for baptising these people who have received the Holy Spirit just as we have?'",
     "'Silver and gold have I none, but what I have I give you.'",
     "'Your money perish with you, because you thought you could obtain the gift of God with money.'",
     "'We must obey God rather than men.'",
     "A", "Acts 10:44-48: God's gift of the Spirit to Gentiles settled the question of their admission."),
    (T_GENT, "Medium", "Some men from Judea taught the brethren at Antioch, 'Unless you are circumcised according to the custom of Moses, you cannot be saved.' The Council of Jerusalem replied that Gentile believers should",
     "abstain from what has been sacrificed to idols, from blood, from what is strangled and from unchastity, but need not be circumcised",
     "be circumcised and keep the whole law of Moses before baptism",
     "form a separate church and never eat with Jewish believers",
     "return to their former religions until the apostles visited them",
     "A", "Acts 15:1-29: James' judgment was that they 'should not trouble those of the Gentiles who turn to God'."),
    (T_GENT, "Medium", "At the Council of Jerusalem Peter argued, 'God made no distinction between us and them, but cleansed their hearts by faith. Now therefore why do you make trial of God by putting a yoke upon the neck of the disciples?' The 'yoke' referred to",
     "the demand that Gentiles keep the law of Moses in order to be saved",
     "the Roman taxes imposed on the churches of Asia",
     "the persecution of the church by King Herod",
     "the requirement that Gentiles pay for the temple sacrifices",
     "A", "Acts 15:7-11: salvation is 'through the grace of the Lord Jesus' for Jew and Gentile alike."),
    (T_GENT, "Medium", "At Pisidian Antioch, when the Jews contradicted Paul and reviled him, Paul and Barnabas said, 'Since you thrust it from you... behold, we turn to the Gentiles.' They justified this by quoting the prophecy,",
     "'I have set you to be a light for the Gentiles, that you may bring salvation to the uttermost parts of the earth.'",
     "'Behold, a virgin shall conceive and bear a son.'",
     "'The stone which the builders rejected has become the head of the corner.'",
     "'Out of Egypt have I called my son.'",
     "A", "Acts 13:44-48: the Gentiles rejoiced, and 'as many as were ordained to eternal life believed'."),
    (T_GENT, "Medium", "A congregation insists that converts from another ethnic group must adopt its language and dress before they can be baptised. This resembles the error corrected at",
     "the Council of Jerusalem",
     "the stoning of Stephen",
     "the conversion of Saul on the Damascus road",
     "the shipwreck of Paul at Malta",
     "A", "Acts 15: the church decided not to burden Gentile converts with Jewish customs as a condition of salvation."),
    (T_GENT, "Medium", "Paul wrote that in Christ 'there is neither Jew nor Greek, there is neither slave nor free, there is neither male nor female; for you are all one in Christ Jesus'. This teaches that",
     "the gospel abolishes barriers of race, class and sex within the people of God",
     "Jews and Greeks should worship in separate buildings",
     "slavery was abolished throughout the Roman empire by Paul",
     "there are no differences of role or gift among Christians",
     "A", "Galatians 3:28: all who are baptised into Christ share equally in the promise to Abraham."),

    # ---------------- Justification by Faith ----------------
    (T_JUST, "Medium", "Paul wrote, 'For by grace you have been saved through faith; and this is not your own doing, it is the gift of God - not because of works, lest any man should boast.' A church member who says, 'God must accept me because of my thirty years of service,' has misunderstood",
     "that salvation is God's free gift received by faith, not a wage earned by works",
     "that good works are forbidden to those who are saved by grace",
     "that faith is unnecessary once a person has served the church",
     "that long service in the church is the only true evidence of faith",
     "A", "Ephesians 2:8-9: boasting is excluded because justification rests on grace alone."),
    (T_JUST, "Medium", "Paul argued that Abraham was reckoned righteous before he was circumcised, in order to show that",
     "Abraham is the father of all who believe, whether circumcised or not",
     "circumcision was abolished in the days of Abraham",
     "only the descendants of Abraham can be justified",
     "Abraham earned his righteousness by obeying the law",
     "A", "Romans 4:9-12: faith, not the sign of circumcision, was the ground of Abraham's righteousness."),
    (T_JUST, "Medium", "Paul wrote, 'Now to one who works, his wages are not reckoned as a gift but as his due. And to one who does not work but trusts him who justifies the ungodly, his faith is reckoned as righteousness.' Paul contrasts",
     "earning acceptance with God by works and receiving it freely by faith",
     "the wages of a labourer and the salary of a civil servant",
     "the ungodly who work hard and the godly who are lazy",
     "faith in Abraham and faith in Moses",
     "A", "Romans 4:4-5: justification is a gift to those who trust God, not a payment for merit."),
    (T_JUST, "Medium", "Paul said to the Galatians, 'If justification were through the law, then Christ died to no purpose.' He meant that",
     "seeking righteousness through law-keeping makes the death of Christ unnecessary and empties it of meaning",
     "Christ died only for those who had already kept the law perfectly",
     "the Galatians should combine faith in Christ with circumcision to be safe",
     "the law was abolished so that Christians may live as they please",
     "A", "Galatians 2:21: to add works of law to faith is to deny the sufficiency of the cross."),
    (T_JUST, "Medium", "'Therefore, since we are justified by faith, we have peace with God through our Lord Jesus Christ.' A believer who is constantly terrified that God will reject her over every small failing needs to understand that",
     "justification gives a settled peace with God based on Christ's work, not on her performance",
     "peace with God is reserved for those who never fail",
     "she should increase her good works until the fear disappears",
     "God's acceptance is withdrawn each time a believer sins",
     "A", "Romans 5:1-2: the justified stand in grace and rejoice in hope, not in fear."),
    (T_JUST, "Medium", "James wrote, 'Faith by itself, if it has no works, is dead.' Paul wrote that a man is justified by faith apart from works of law. The two teachings agree because",
     "Paul speaks of how a person is accepted by God, while James speaks of the works that prove faith is genuine",
     "James rejected Paul's gospel and taught salvation by works",
     "Paul later changed his mind and accepted James' position",
     "the two apostles were writing about two different gods",
     "A", "James 2:14-26 attacks a dead, merely verbal faith; Paul attacks reliance on works for acceptance - both agree that true faith works through love (Galatians 5:6)."),

    # ---------------- The Law and Grace ----------------
    (T_LAW, "Medium", "Paul wrote, 'Through the law comes knowledge of sin,' and, 'I should not have known what it is to covet if the law had not said, You shall not covet.' This shows that a function of the law is to",
     "expose sin and make people aware of their guilt",
     "remove sin from the hearts of those who study it",
     "make coveting acceptable in certain circumstances",
     "replace the need for a Saviour",
     "A", "Romans 3:20 and 7:7: the law reveals sin but cannot cure it."),
    (T_LAW, "Medium", "Paul asked, 'Are we to continue in sin that grace may abound? By no means! How can we who died to sin still live in it?' He was answering the objection that",
     "free grace encourages people to sin without restraint",
     "the law of Moses had been too strict for Gentiles",
     "Christians must be circumcised to receive grace",
     "grace is available only to those who never sin",
     "A", "Romans 6:1-4: those united with Christ in baptism have died to sin and are to walk in newness of life."),
    (T_LAW, "Medium", "A young convert says, 'Since I am under grace, it does not matter how I live.' Paul's answer would be that",
     "grace frees believers from sin's dominion so that they become slaves of righteousness, not so that they may sin freely",
     "he is correct, since the law has no more relevance for a Christian's conduct",
     "he should return to keeping the whole law of Moses to be safe",
     "grace is withdrawn from anyone who asks such a question",
     "A", "Romans 6:14-18: 'You who were once slaves of sin have become... slaves of righteousness.'"),
    (T_LAW, "Medium", "Paul wrote to the Galatians, 'For freedom Christ has set us free; stand fast therefore, and do not submit again to a yoke of slavery.' The 'yoke of slavery' he warned against was",
     "the attempt to secure salvation by circumcision and law-keeping",
     "the Roman system of slavery in the province of Galatia",
     "the payment of the temple tax by Gentile believers",
     "obedience to the moral teaching of Jesus",
     "A", "Galatians 5:1-4: 'You are severed from Christ, you who would be justified by the law; you have fallen away from grace.'"),
    (T_LAW, "Medium", "Paul described the law as 'holy, and the commandment is holy and just and good', yet insisted that it could not give life. The law's weakness lay in",
     "human sinful nature, which the law could expose but not change",
     "the fact that Moses wrote it down inaccurately",
     "its being given only to the tribe of Levi",
     "its abolition by the Roman authorities",
     "A", "Romans 7:12 and 8:3: 'God has done what the law, weakened by the flesh, could not do: sending his own Son.'"),
    (T_LAW, "Medium", "Paul said Christ is 'the end of the law, that every one who has faith may be justified'. Christians therefore relate to the law as",
     "a standard fulfilled in Christ and written on the heart by the Spirit, not as a way of earning salvation",
     "a set of rules that must be kept perfectly before God will accept them",
     "an ancient document with no bearing on how believers live",
     "a burden imposed only on Jewish Christians",
     "A", "Romans 10:4 and 8:4: the just requirement of the law is fulfilled in those who walk according to the Spirit."),

    # ---------------- New Life in Christ ----------------
    (T_NEW, "Medium", "Paul urged the Ephesians to 'put off your old nature which belongs to your former manner of life... and put on the new nature, created after the likeness of God'. He then gave practical examples, including",
     "'Let the thief no longer steal, but rather let him labour, doing honest work with his hands.'",
     "'Let every person be subject to the governing authorities.'",
     "'If any one will not work, let him not eat.'",
     "'Owe no one anything, except to love each other.'",
     "A", "Ephesians 4:22-32: putting off the old nature includes truthfulness, honest work, wholesome speech and forgiveness."),
    (T_NEW, "Medium", "Paul listed the works of the flesh as including 'immorality, impurity, licentiousness, idolatry, sorcery, enmity, strife, jealousy, anger, selfishness, dissension, party spirit, envy, drunkenness'. A believer who claims to be Spirit-filled but constantly stirs up quarrels and factions in church is showing",
     "works of the flesh rather than the fruit of the Spirit",
     "the fruit of the Spirit called faithfulness",
     "the gift of discernment of spirits",
     "the boldness of the apostles before the council",
     "A", "Galatians 5:19-23: strife, dissension and party spirit belong to the flesh; the Spirit produces peace and gentleness."),
    (T_NEW, "Medium", "Paul wrote, 'I have been crucified with Christ; it is no longer I who live, but Christ who lives in me.' This describes",
     "a new identity in which the believer's life is governed by Christ",
     "Paul's physical death on a cross in Rome",
     "the loss of individual personality in the church",
     "a ritual performed by the Galatians at baptism",
     "A", "Galatians 2:20: 'the life I now live in the flesh I live by faith in the Son of God, who loved me and gave himself for me'."),
    (T_NEW, "Medium", "A former armed robber who now runs a legitimate business and returns to visit prisoners with the gospel illustrates Paul's teaching that",
     "in Christ the old has passed away and the new has come",
     "the works of the flesh cannot be overcome in this life",
     "believers should avoid all contact with criminals",
     "salvation is earned by making up for past sins",
     "A", "2 Corinthians 5:17: 'If any one is in Christ, he is a new creation.'"),
    (T_NEW, "Medium", "Paul told the Colossians, 'Put to death therefore what is earthly in you: immorality, impurity, passion, evil desire, and covetousness, which is idolatry.' Covetousness is called idolatry because",
     "the greedy person makes possessions the object of his trust and devotion in place of God",
     "the Colossians made statues of gold and worshipped them",
     "only pagans were tempted to be covetous",
     "coveting was punished by the same penalty as idolatry under Roman law",
     "A", "Colossians 3:5; compare Matthew 6:24: 'You cannot serve God and mammon.'"),
    (T_NEW, "Medium", "'Do not be conformed to this world but be transformed by the renewal of your mind.' A student who joins in examination malpractice because 'everybody does it' is",
     "being conformed to the world instead of being transformed",
     "proving that his mind has been renewed by the Spirit",
     "presenting his body as a living sacrifice",
     "discerning the will of God, which is good and acceptable",
     "A", "Romans 12:1-2: the renewed mind resists the pressure of the surrounding culture."),

    # ---------------- Christians as Joint Heirs with Christ ----------------
    (T_HEIR, "Medium", "Paul wrote, 'You did not receive the spirit of slavery to fall back into fear, but you have received the spirit of sonship. When we cry, Abba! Father! it is the Spirit himself bearing witness with our spirit that we are children of God.' This shows that",
     "the believer's assurance of sonship comes from the inner witness of the Spirit",
     "Christians must remain fearful in order to be accepted by God",
     "only the apostles were permitted to call God 'Father'",
     "sonship is proved by the size of one's inheritance on earth",
     "A", "Romans 8:15-16: Abba is an intimate Aramaic word for Father, used by Jesus himself."),
    (T_HEIR, "Medium", "Paul said believers are 'heirs of God and fellow heirs with Christ, provided we suffer with him in order that we may also be glorified with him'. A prosperity preacher who teaches that true Christians never suffer contradicts",
     "the link Paul makes between sharing Christ's sufferings and sharing His glory",
     "the teaching that Christians are children of God",
     "the promise that the Spirit bears witness with our spirit",
     "the doctrine that Christ was raised from the dead",
     "A", "Romans 8:17: suffering with Christ is part of the path to glory, not a sign of God's rejection."),
    (T_HEIR, "Medium", "Paul wrote that 'the sufferings of this present time are not worth comparing with the glory that is to be revealed to us'. He meant that",
     "the future inheritance far outweighs present hardship",
     "Christians do not really suffer in this life",
     "glory is given now to those who suffer most",
     "suffering is always caused by the believer's own sin",
     "A", "Romans 8:18: the hope of glory puts present troubles in proportion."),
    (T_HEIR, "Medium", "In Galatians Paul said that 'when the time had fully come, God sent forth his Son, born of woman, born under the law, to redeem those who were under the law, so that we might receive adoption as sons'. Adoption means that believers",
     "are made full members of God's family with the rights of heirs",
     "must serve as slaves in the household of God",
     "are related to God only by the law of Moses",
     "become sons of Abraham by circumcision",
     "A", "Galatians 4:4-7: 'So through God you are no longer a slave but a son, and if a son then an heir.'"),
    (T_HEIR, "Medium", "Peter described the believer's inheritance as 'imperishable, undefiled, and unfading, kept in heaven for you'. This contrasts with earthly inheritances, which",
     "can be lost, spoilt or squandered",
     "are always shared equally among children",
     "are received only after the death of the father",
     "are more valuable than anything kept in heaven",
     "A", "1 Peter 1:3-5: the heavenly inheritance is secure because God guards both it and those who will receive it."),

    # ---------------- Humility ----------------
    (T_HUM, "Medium", "Paul told the Philippians, 'Do nothing from selfishness or conceit, but in humility count others better than yourselves. Let each of you look not only to his own interests, but also to the interests of others.' A prefect who takes credit for his classmates' work is failing to",
     "count others better than himself",
     "have the mind of Christ, who was obedient unto death",
     "work out his salvation with fear and trembling",
     "shine as a light in a crooked generation",
     "A", "Philippians 2:3-4: humility puts the interests and honour of others before one's own."),
    (T_HUM, "Medium", "Paul wrote that Christ 'humbled himself and became obedient unto death, even death on a cross. Therefore God has highly exalted him and bestowed on him the name which is above every name.' This teaches that",
     "the way to true exaltation is through humble obedience",
     "Christ was exalted because he demanded recognition",
     "humility always brings promotion in this life",
     "Christ was not divine until after the resurrection",
     "A", "Philippians 2:8-11: 'Whoever humbles himself will be exalted' (Luke 14:11) is supremely illustrated in Christ."),
    (T_HUM, "Medium", "Peter wrote, 'Clothe yourselves, all of you, with humility toward one another, for God opposes the proud, but gives grace to the humble.' The image of clothing suggests that humility",
     "should be visible in a believer's conduct at all times",
     "can be put on only on special religious occasions",
     "is a garment worn by priests in the temple",
     "is needed only by young people towards their elders",
     "A", "1 Peter 5:5-6: 'Humble yourselves therefore under the mighty hand of God, that in due time he may exalt you.'"),
    (T_HUM, "Medium", "The disciples argued about who was the greatest. Jesus set a child in their midst and said, 'Whoever humbles himself like this child, he is the greatest in the kingdom of heaven.' He meant that greatness in the kingdom belongs to",
     "those who are humble and dependent, not to those who seek status",
     "those who are physically small like children",
     "the youngest member of every congregation",
     "those who have the most children",
     "A", "Matthew 18:1-4: a child had no status in that society; Jesus made humility the measure of greatness."),
    (T_HUM, "Medium", "A choir leader who insists on sitting on the front row at every service so that visitors will notice him is behaving like the guests Jesus described who",
     "chose the places of honour at a marriage feast",
     "made excuses and would not come to the banquet",
     "refused to wear a wedding garment",
     "came in from the streets and lanes of the city",
     "A", "Luke 14:7-11: 'When you are invited, go and sit in the lowest place... every one who exalts himself will be humbled.'"),

    # ---------------- Forgiveness ----------------
    (T_FORG, "Medium", "In the parable of the unforgiving servant, the king said, 'You wicked servant! I forgave you all that debt because you besought me; and should not you have had mercy on your fellow servant, as I had mercy on you?' The parable teaches that",
     "those who have received God's forgiveness must forgive others",
     "debts should never be forgiven under any circumstances",
     "kings are more merciful than ordinary servants",
     "small debts matter more to God than large ones",
     "A", "Matthew 18:23-35: the servant forgiven ten thousand talents refused to forgive a hundred denarii."),
    (T_FORG, "Medium", "A church member who was forgiven a large loan by a fellow member later has her tenant arrested over a small unpaid rent. She resembles",
     "the unforgiving servant in Jesus' parable",
     "the prodigal son's father",
     "the good Samaritan",
     "Joseph forgiving his brothers",
     "A", "Matthew 18:28-30: having received mercy, the servant seized his fellow servant by the throat over a trifling debt."),
    (T_FORG, "Medium", "Joseph told his brothers, 'Fear not, for am I in the place of God? As for you, you meant evil against me; but God meant it for good.' Joseph was able to forgive because he",
     "saw God's purpose at work even in the wrong done to him",
     "had forgotten how his brothers had treated him",
     "was too powerful for the brothers to harm him again",
     "wanted the brothers to remain his slaves in Egypt",
     "A", "Genesis 50:19-21: Joseph refused revenge and provided for his brothers and their children."),
    (T_FORG, "Medium", "Paul told the Colossians, 'As the Lord has forgiven you, so you also must forgive.' The measure of Christian forgiveness is therefore",
     "the forgiveness that Christ has extended to the believer",
     "the number of times the offender says sorry",
     "the seriousness of the offence committed",
     "the custom of one's community or family",
     "A", "Colossians 3:13 and Ephesians 4:32: believers forgive as freely as they have been forgiven in Christ."),
    (T_FORG, "Medium", "In the parable of the prodigal son, the elder brother was angry and refused to go in to the feast. His attitude represents",
     "those who resent God's free forgiveness of repentant sinners",
     "the joy of heaven over one sinner who repents",
     "the humility of the tax collector in the temple",
     "the patience of the father who waited for his son",
     "A", "Luke 15:25-32: the elder brother mirrors the Pharisees who grumbled that Jesus received sinners."),
    (T_FORG, "Medium", "Jesus taught, 'If your brother sins, rebuke him, and if he repents, forgive him; and if he sins against you seven times in the day, and turns to you seven times, and says, I repent, you must forgive him.' This teaches that forgiveness should be",
     "unlimited and repeated whenever the offender repents",
     "granted only once to each person in a lifetime",
     "withheld until the offender has paid compensation",
     "offered only to members of one's own family",
     "A", "Luke 17:3-4; compare Matthew 18:22: 'seventy times seven'."),

    # ---------------- Spiritual Gifts ----------------
    (T_GIFT, "Medium", "Paul wrote, 'Now there are varieties of gifts, but the same Spirit... To each is given the manifestation of the Spirit for the common good.' Spiritual gifts are therefore given",
     "for the benefit of the whole church, not for personal display",
     "only to pastors and evangelists who lead congregations",
     "as rewards for those who have been Christians the longest",
     "so that gifted members may be honoured above the rest",
     "A", "1 Corinthians 12:4-7: every gift serves the common good of the body."),
    (T_GIFT, "Medium", "Paul said, 'If the foot should say, Because I am not a hand, I do not belong to the body, that would not make it any less a part of the body.' He was addressing members who",
     "felt inferior because they lacked the more spectacular gifts",
     "wanted to leave the church and start their own fellowship",
     "were proud of their gifts and despised others",
     "believed that the body of Christ had only one member",
     "A", "1 Corinthians 12:14-20: every member is needed, however humble its function."),
    (T_GIFT, "Medium", "A church usher feels useless because she cannot preach or sing. Paul's teaching in 1 Corinthians 12 reminds her that",
     "God has arranged every member in the body as He chose, and the less visible parts are indispensable",
     "only those who can preach have received a spiritual gift",
     "she should stop ushering until she receives a better gift",
     "the eye is the only member that matters in the body",
     "A", "1 Corinthians 12:18-22: 'the parts of the body which seem to be weaker are indispensable'."),
    (T_GIFT, "Medium", "Paul preferred prophecy to uninterpreted tongues in the assembly because",
     "prophecy edifies the church, whereas tongues without interpretation edify only the speaker",
     "tongues were a gift given only to the apostles",
     "prophecy was easier to fake than speaking in tongues",
     "the Corinthians did not possess the gift of tongues",
     "A", "1 Corinthians 14:1-5, 19: 'In church I would rather speak five words with my mind... than ten thousand words in a tongue.'"),
    (T_GIFT, "Medium", "Paul concluded his instructions on the use of gifts in worship with the words, 'All things should be done decently and in order,' because",
     "God is not a God of confusion but of peace",
     "the Roman authorities forbade noisy meetings",
     "only the elders were allowed to speak in the assembly",
     "spiritual gifts had ceased in the church at Corinth",
     "A", "1 Corinthians 14:33, 40: orderly worship reflects the character of God and builds up the church."),
    (T_GIFT, "Medium", "A member who speaks in tongues loudly during the sermon so that no one can hear the preacher is disregarding Paul's instruction that",
     "if there is no interpreter, the speaker should keep silence in church and speak to himself and to God",
     "tongues are the greatest of all the gifts and must never be restrained",
     "the preacher should stop and wait for the tongue to finish",
     "only women should speak in tongues in the assembly",
     "A", "1 Corinthians 14:27-28: tongues in public worship require interpretation and order."),

    # ---------------- Christian Giving ----------------
    (T_GIVE, "Medium", "Paul wrote, 'Each one must do as he has made up his mind, not reluctantly or under compulsion, for God loves a cheerful giver.' A pastor who locks the church doors until a target sum has been collected is violating the principle that",
     "giving should be voluntary and cheerful, not forced",
     "only tithes and not offerings are acceptable to God",
     "giving should be done in secret without any record",
     "the rich should give more than the poor",
     "A", "2 Corinthians 9:7: compulsion destroys the cheerfulness that God loves."),
    (T_GIVE, "Medium", "Paul said, 'He who sows sparingly will also reap sparingly, and he who sows bountifully will also reap bountifully.' He was encouraging the Corinthians to",
     "give generously to the collection for the poor saints in Jerusalem",
     "plant more crops in order to become wealthy",
     "give only when they were certain of a financial return",
     "sell their farms and give the money to the apostles",
     "A", "2 Corinthians 9:1-8: the context is the relief fund for Jerusalem, and generosity is met by God's sufficiency."),
    (T_GIVE, "Medium", "Paul commended the Macedonians because 'their abundance of joy and their extreme poverty have overflowed in a wealth of liberality... they gave according to their means, and beyond their means, of their own free will'. This teaches that",
     "generous giving depends on willingness, not on wealth",
     "only the poor are expected to give to the church",
     "poverty is a sign of God's blessing on a church",
     "Christians should give until they become destitute",
     "A", "2 Corinthians 8:1-5: 'first they gave themselves to the Lord and to us by the will of God'."),
    (T_GIVE, "Medium", "Paul motivated the Corinthians to give by reminding them of 'the grace of our Lord Jesus Christ, that though he was rich, yet for your sake he became poor, so that by his poverty you might become rich'. The supreme model for Christian giving is therefore",
     "the self-giving of Christ in his incarnation and death",
     "the tithe that Abraham gave to Melchizedek",
     "the generosity of the rich young ruler",
     "the offering of the Pharisee in the temple",
     "A", "2 Corinthians 8:9: giving is a response to grace received."),
    (T_GIVE, "Medium", "Paul instructed that the collection be set aside 'on the first day of every week' by each person 'as he may prosper', so that",
     "giving would be regular, planned and proportionate to income",
     "the apostles could take the money for their own use",
     "only the wealthy would be required to contribute",
     "the church would not need to give again for many years",
     "A", "1 Corinthians 16:1-2: systematic, proportionate giving rather than emotional, occasional appeals."),

    # ---------------- Civic Responsibility ----------------
    (T_CIVIC, "Medium", "Paul wrote, 'Let every person be subject to the governing authorities. For there is no authority except from God.' He gave as the reason that the ruler",
     "is God's servant for your good and an avenger who executes wrath on the wrongdoer",
     "is always righteous and can never make an unjust law",
     "has power to forgive sins in the name of God",
     "will reward Christians with positions in government",
     "A", "Romans 13:1-4: government exists by God's ordinance to restrain evil and promote good."),
    (T_CIVIC, "Medium", "Paul urged 'that supplications, prayers, intercessions and thanksgivings be made for all men, for kings and all who are in high positions, that we may lead a quiet and peaceable life'. A church that curses its national leaders every Sunday is neglecting",
     "the duty to pray for those in authority",
     "the duty to pay taxes to whom taxes are due",
     "the duty to obey God rather than men",
     "the duty to evangelise government officials",
     "A", "1 Timothy 2:1-2: prayer for rulers, even pagan ones, is a Christian obligation."),
    (T_CIVIC, "Medium", "Peter and John told the Sanhedrin, 'Whether it is right in the sight of God to listen to you rather than to God, you must judge.' Together with Romans 13, this teaches that Christian obedience to the state",
     "is real but limited: when the state commands what God forbids, God must be obeyed",
     "is absolute, whatever the authorities command",
     "applies only to Christian governments",
     "can be withdrawn whenever taxes are raised",
     "A", "Acts 4:19-20 and 5:29: 'We must obey God rather than men' - the exception that limits Romans 13."),
    (T_CIVIC, "Medium", "A Christian civil servant is ordered by his director to destroy evidence of fraud. He refuses but continues to perform all his lawful duties diligently. He is correctly applying",
     "obedience to lawful authority combined with the principle of obeying God rather than men",
     "the teaching that all authority must be resisted",
     "the teaching that civil servants are exempt from Romans 13",
     "the principle that the end justifies the means",
     "A", "Romans 13:1-7 with Acts 5:29: submission to authority stops where sin begins, without rebellion in other matters."),
    (T_CIVIC, "Medium", "Peter wrote, 'Be subject for the Lord's sake to every human institution... Honour all men. Love the brotherhood. Fear God. Honour the emperor.' This was written when the emperor was",
     "a pagan ruler, showing that respect for authority does not depend on the ruler's faith",
     "a Christian who had built churches throughout the empire",
     "a Jew who had restored the temple in Jerusalem",
     "Peter's own relative from Galilee",
     "A", "1 Peter 2:13-17: written under Nero or a similar pagan emperor; honour is due to the office."),
    (T_CIVIC, "Medium", "Paul wrote, 'Pay all of them their dues, taxes to whom taxes are due, revenue to whom revenue is due, respect to whom respect is due.' A trader who under-declares her income to avoid tax is",
     "failing in a duty Paul lays on Christians towards the state",
     "acting rightly if the government is corrupt",
     "obeying God rather than men",
     "exercising the freedom Christ purchased for her",
     "A", "Romans 13:6-7: paying taxes honestly is part of Christian submission to the authorities God has ordained."),

    # ---------------- Dignity of Labour ----------------
    (T_LAB, "Medium", "Paul reminded the Thessalonians, 'We were not idle when we were with you, we did not eat any one's bread without paying, but with toil and labour we worked night and day, that we might not burden any of you.' Paul worked in order to",
     "give the believers an example to imitate",
     "become wealthy from the tent-making trade",
     "avoid preaching the gospel in public",
     "prove that apostles were not entitled to support",
     "A", "2 Thessalonians 3:7-9: 'not because we have not that right, but to give you in our conduct an example to imitate'."),
    (T_LAB, "Medium", "Paul instructed, 'Whatever your task, work heartily, as serving the Lord and not men.' A cleaner who does her job thoroughly even when the supervisor is absent is",
     "serving the Lord in her ordinary work, as Paul taught",
     "working only for the wages she receives",
     "wasting effort that could be used for church activities",
     "seeking the praise of men rather than of God",
     "A", "Colossians 3:23-24: all honest work done for the Lord has dignity and will be rewarded by Him."),
    (T_LAB, "Medium", "Paul commanded, 'Let the thief no longer steal, but rather let him labour, doing honest work with his hands, so that he may be able to give to those in need.' Honest work is presented as",
     "the means of meeting one's own needs and helping others",
     "a punishment reserved for converted thieves",
     "less spiritual than full-time preaching",
     "unnecessary for those who have faith",
     "A", "Ephesians 4:28: work replaces stealing and makes generosity possible."),
    (T_LAB, "Medium", "Genesis records that God 'took the man and put him in the garden of Eden to till it and keep it' before the fall. This shows that work is",
     "part of God's original good purpose for man, not merely a curse",
     "a punishment introduced only after Adam sinned",
     "meant only for those who cannot afford servants",
     "less honourable than rest and worship",
     "A", "Genesis 2:15: labour belonged to paradise; the toil and thorns of Genesis 3:17-19 came after the fall."),
    (T_LAB, "Medium", "Paul wrote that some at Thessalonica were 'living in idleness, mere busybodies, not doing any work'. He commanded such persons 'to do their work in quietness and to earn their own living'. A graduate who refuses every job that is 'below his level' while depending on his relatives is",
     "ignoring Paul's command to earn one's own living",
     "rightly waiting for the work God has prepared for him",
     "following the example of Paul's tent-making",
     "practising the communal sharing of the early church",
     "A", "2 Thessalonians 3:10-12: 'If any one will not work, let him not eat.'"),
    (T_LAB, "Medium", "Jesus himself was known in Nazareth as 'the carpenter, the son of Mary', and Paul was a tent-maker. These facts teach that",
     "manual labour is honourable and compatible with spiritual calling",
     "only carpenters and tent-makers can serve God",
     "religious leaders should never engage in manual work",
     "trade is a hindrance to the preaching of the gospel",
     "A", "Mark 6:3 and Acts 18:3: the Lord and the apostle both dignified ordinary work."),

    # ---------------- The Second Coming of Christ ----------------
    (T_SEC, "Medium", "Paul told the Thessalonians that at the coming of the Lord 'the dead in Christ will rise first; then we who are alive... shall be caught up together with them in the clouds to meet the Lord in the air'. He wrote this to",
     "comfort believers who grieved that their dead would miss the Lord's coming",
     "warn the Thessalonians to stop working and wait for the Lord",
     "reveal the exact date of the second coming",
     "prove that only the living would be saved",
     "A", "1 Thessalonians 4:13-18: 'Therefore comfort one another with these words.'"),
    (T_SEC, "Medium", "Jesus said, 'But of that day and hour no one knows, not even the angels of heaven, nor the Son, but the Father only.' A preacher who announces the exact date of Christ's return is",
     "claiming knowledge that Jesus said belongs to the Father alone",
     "fulfilling the duty to watch and be ready",
     "following the example of Paul in Thessalonica",
     "interpreting the signs of the times correctly",
     "A", "Matthew 24:36; Acts 1:7: 'It is not for you to know times or seasons.'"),
    (T_SEC, "Medium", "Peter wrote that scoffers would say, 'Where is the promise of his coming?' and answered that 'the Lord is not slow about his promise... but is forbearing toward you, not wishing that any should perish, but that all should reach repentance'. The apparent delay of the second coming is therefore due to",
     "God's patience in giving people opportunity to repent",
     "God's forgetfulness of the promise He made",
     "the church's failure to pray for Christ's return",
     "the opposition of the Roman emperor",
     "A", "2 Peter 3:3-9: 'with the Lord one day is as a thousand years'."),
    (T_SEC, "Medium", "A church member sells his property, stops working and sits waiting for the Lord's return. Paul's letters to the Thessalonians show that his conduct is",
     "mistaken, because believers are to keep working quietly while they wait",
     "commendable, because it shows total faith in the promise",
     "the pattern the apostles followed after the ascension",
     "required of every Christian who expects the Lord's return",
     "A", "2 Thessalonians 3:6-12: idleness in the name of the second coming was rebuked."),
    (T_SEC, "Medium", "In the parable of the talents the master returned 'after a long time' and settled accounts with his servants. Applied to the second coming, the parable teaches that believers should",
     "use faithfully what God has entrusted to them until the Lord returns",
     "bury their gifts safely so that nothing is lost",
     "expect the master to return within a few days",
     "trade with the master's money for their own profit",
     "A", "Matthew 25:14-30: 'Well done, good and faithful servant... enter into the joy of your master.'"),
    (T_SEC, "Medium", "Jesus said the coming of the Son of man would be 'as were the days of Noah... they were eating and drinking, marrying and giving in marriage, until the day when Noah entered the ark, and they did not know until the flood came'. The point is that",
     "his coming will be sudden and will surprise those who are unprepared",
     "eating, drinking and marriage are sinful activities",
     "the world will end by a second flood",
     "only eight people will be saved at the second coming",
     "A", "Matthew 24:37-42: 'Watch therefore, for you do not know on what day your Lord is coming.'"),

    # ---------------- Impartiality ----------------
    (T_IMP, "Medium", "James wrote, 'If you show partiality, you commit sin, and are convicted by the law as transgressors.' He described partiality as a breach of",
     "the royal law, 'You shall love your neighbour as yourself'",
     "the law of the Sabbath",
     "the law of tithing",
     "the law of circumcision",
     "A", "James 2:8-9: favouritism denies the equal love the law commands."),
    (T_IMP, "Medium", "James asked, 'Has not God chosen those who are poor in the world to be rich in faith and heirs of the kingdom?... But you have dishonoured the poor man.' He pointed out the folly of favouring the rich, who",
     "oppressed the believers, dragged them into court and blasphemed the name",
     "had built the synagogue in which the believers met",
     "were more likely to become Christians than the poor",
     "had been chosen by God to lead the church",
     "A", "James 2:5-7: the church was flattering the very class that persecuted it."),
    (T_IMP, "Medium", "A pastor gives the children of wealthy members leading roles in every programme while ignoring the poor children. This is the sin James called",
     "partiality or respect of persons",
     "the works of the flesh",
     "grieving the Holy Spirit",
     "quenching the Spirit",
     "A", "James 2:1: 'show no partiality as you hold the faith of our Lord Jesus Christ, the Lord of glory'."),
    (T_IMP, "Medium", "Peter said at the house of Cornelius, 'Truly I perceive that God shows no partiality, but in every nation any one who fears him and does what is right is acceptable to him.' This truth means that in the church",
     "no race or nation may be treated as second-class",
     "all members must adopt Jewish customs",
     "Gentiles should form separate congregations",
     "only Romans may hold positions of leadership",
     "A", "Acts 10:34-35: God's impartiality is the basis for the church's unity across nations."),
    (T_IMP, "Medium", "Paul warned Timothy, 'In the presence of God and of Christ Jesus and of the elect angels I charge you to keep these rules without favour, doing nothing from partiality.' This shows that impartiality is required especially in",
     "church discipline and the treatment of elders",
     "the choice of hymns for worship",
     "the payment of the temple tax",
     "the interpretation of prophecy",
     "A", "1 Timothy 5:19-21: charges against elders were to be handled fairly, without prejudice or favour."),

    # ---------------- Effective Prayer ----------------
    (T_PRAY, "Medium", "James wrote, 'You ask and do not receive, because you ask wrongly, to spend it on your passions.' A student who prays for wealth so that he can outshine his friends is",
     "asking wrongly, with selfish motives",
     "praying according to the will of God",
     "exercising the prayer of faith that James commended",
     "praying like Elijah for rain",
     "A", "James 4:3: motive matters in prayer; God does not supply selfish desires."),
    (T_PRAY, "Medium", "In Gethsemane Jesus prayed, 'My Father, if it be possible, let this cup pass from me; nevertheless, not as I will, but as thou wilt.' This teaches that effective prayer",
     "expresses honest desire yet submits to the Father's will",
     "always obtains exactly what is requested",
     "should never mention the suffering one wants to avoid",
     "must be repeated three times to be heard",
     "A", "Matthew 26:39-44: Jesus' submission is the model of prayer 'according to his will' (1 John 5:14)."),
    (T_PRAY, "Medium", "Jesus said, 'Whatever you ask in prayer, believe that you receive it, and you will. And whenever you stand praying, forgive, if you have anything against any one.' Two conditions for effective prayer given here are",
     "faith and a forgiving spirit",
     "fasting and loud crying",
     "long prayers and many words",
     "standing and facing Jerusalem",
     "A", "Mark 11:24-25: believing prayer and forgiveness of others go together."),
    (T_PRAY, "Medium", "Jesus told a parable of a friend who came at midnight asking for three loaves, and said that 'because of his importunity he will rise and give him whatever he needs'. The lesson is that",
     "persistence in prayer is rewarded",
     "neighbours should not be disturbed at night",
     "God is reluctant and must be worn down",
     "prayer should be made only at midnight",
     "A", "Luke 11:5-10: 'Ask, and it will be given you; seek, and you will find; knock, and it will be opened to you.'"),
    (T_PRAY, "Medium", "Jesus warned, 'In praying do not heap up empty phrases as the Gentiles do; for they think that they will be heard for their many words.' A prayer leader who believes God answers only long, shouted prayers has forgotten that",
     "the Father knows what we need before we ask him",
     "God hears only prayers offered in the temple",
     "prayer must be made in a language no one understands",
     "long prayers are always a sign of great faith",
     "A", "Matthew 6:7-8: prayer is addressed to a loving Father, not to a deity who must be impressed by volume."),
    (T_PRAY, "Medium", "James taught, 'Is any among you sick? Let him call for the elders of the church, and let them pray over him, anointing him with oil in the name of the Lord; and the prayer of faith will save the sick man.' He added, 'Confess your sins to one another, and pray for one another,' because",
     "unconfessed sin can hinder prayer and healing within the fellowship",
     "the elders cannot pray unless they know every sin of the member",
     "confession replaces the need for medical treatment",
     "only public sinners fall ill",
     "A", "James 5:14-16: 'The prayer of a righteous man has great power in its effects.'"),

    # ---------------- Christian Living in the Community ----------------
    (T_COMM, "Medium", "Paul wrote, 'Bless those who persecute you; bless and do not curse them. Rejoice with those who rejoice, weep with those who weep... Repay no one evil for evil.' A Christian whose neighbour damaged her fence and who then pours refuse into his compound has violated",
     "the command to repay no one evil for evil",
     "the command to rejoice with those who rejoice",
     "the command to be subject to the governing authorities",
     "the command to owe no one anything",
     "A", "Romans 12:14-21: 'Do not be overcome by evil, but overcome evil with good.'"),
    (T_COMM, "Medium", "Paul urged, 'If possible, so far as it depends upon you, live peaceably with all.' The phrase 'so far as it depends upon you' recognises that",
     "a Christian should do his own part for peace even though others may refuse it",
     "peace is impossible and need not be attempted",
     "Christians should withdraw from all contact with unbelievers",
     "peace should be pursued only with fellow believers",
     "A", "Romans 12:18: the believer is responsible for his own conduct, not for the response of others."),
    (T_COMM, "Medium", "Peter wrote, 'Maintain good conduct among the Gentiles, so that in case they speak against you as wrongdoers, they may see your good deeds and glorify God.' This teaches that a Christian's behaviour in the community",
     "is a witness that can silence slander and bring glory to God",
     "should be hidden from unbelievers to avoid persecution",
     "does not matter as long as his faith is sincere",
     "should copy the standards of the surrounding society",
     "A", "1 Peter 2:12, 15: 'by doing right you should put to silence the ignorance of foolish men'."),
    (T_COMM, "Medium", "Jesus said, 'Let your light so shine before men, that they may see your good works and give glory to your Father who is in heaven.' A Christian trader known throughout the market for honest scales and fair prices is",
     "letting her light shine so that others may glorify God",
     "seeking the praise of men rather than of God",
     "hiding her lamp under a bushel",
     "practising her piety before men to be seen by them",
     "A", "Matthew 5:16: visible good works that point to the Father are the intended witness of disciples."),
    (T_COMM, "Medium", "Paul told the Romans, 'Owe no one anything, except to love each other; for he who loves his neighbour has fulfilled the law.' A Christian who refuses to repay a loan to an unbeliever, saying the man is 'a sinner anyway', is",
     "ignoring Paul's teaching on honesty and love towards all",
     "obeying the command to have no fellowship with darkness",
     "correctly applying the principle of grace over law",
     "practising the communal sharing of the early church",
     "A", "Romans 13:8-10: love does no wrong to a neighbour, and debts must be honoured."),
    (T_COMM, "Medium", "Paul wrote, 'Let no evil talk come out of your mouths, but only such as is good for edifying, as fits the occasion, that it may impart grace to those who hear.' A church member who spreads gossip about a neighbour's marriage is",
     "using speech to tear down rather than to build up",
     "exercising the gift of discernment",
     "speaking the truth in love",
     "correcting a fellow believer as Paul commanded",
     "A", "Ephesians 4:29-31: slander and evil talk grieve the Holy Spirit."),

    # ---------------- Corruption ----------------
    (T_CORR, "Medium", "When Simon the sorcerer offered money for the power to confer the Holy Spirit, Peter said, 'Your silver perish with you, because you thought you could obtain the gift of God with money!' A candidate who pays a bribe to be ordained a church minister is repeating",
     "the sin of Simon, treating the things of God as items for sale",
     "the generosity of Barnabas, who sold a field",
     "the faith of Cornelius, who gave alms liberally",
     "the zeal of Apollos, who was mighty in the scriptures",
     "A", "Acts 8:18-24: the attempt to buy spiritual office or power is called 'simony' after him."),
    (T_CORR, "Medium", "Judas Iscariot agreed to betray Jesus to the chief priests for thirty pieces of silver. John notes that Judas 'was a thief, and as he had the money box he used to take what was put into it'. This suggests that",
     "small acts of dishonesty prepared the way for his great betrayal",
     "Judas was forced by the priests to betray Jesus",
     "the other disciples also stole from the money box",
     "Judas gave all the money to the poor",
     "A", "John 12:6 and Matthew 26:14-16: corruption in small matters grew into treachery."),
    (T_CORR, "Medium", "John the Baptist told the tax collectors, 'Collect no more than is appointed you,' and the soldiers, 'Rob no one by violence or by false accusation, and be content with your wages.' A customs officer who demands 'settlement' above the official duty is",
     "committing the abuse that John condemned",
     "following the advice given to the soldiers",
     "showing the fruit that befits repentance",
     "obeying the command to render to Caesar",
     "A", "Luke 3:12-14: John required repentance to show itself in honest handling of public office."),
    (T_CORR, "Medium", "Zacchaeus said, 'Behold, Lord, the half of my goods I give to the poor; and if I have defrauded any one of anything, I restore it fourfold.' A converted contractor who returns money he had inflated on government projects is showing",
     "the restitution that accompanies genuine repentance",
     "that salvation can be bought with money",
     "the tithe required by the law of Moses",
     "the communal sharing of the early church",
     "A", "Luke 19:8-9: Jesus responded, 'Today salvation has come to this house.'"),
    (T_CORR, "Medium", "Paul wrote, 'The love of money is the root of all evils; it is through this craving that some have wandered away from the faith and pierced their hearts with many pangs.' Note that Paul condemns",
     "the love of money, not money itself",
     "all possession of money by Christians",
     "the use of money for trade and business",
     "the payment of wages to church workers",
     "A", "1 Timothy 6:10: it is the craving for riches, not wealth as such, that leads to ruin."),
    (T_CORR, "Medium", "The law of Moses commanded, 'You shall take no bribe, for a bribe blinds the officials, and subverts the cause of those who are in the right.' The bribe is condemned because it",
     "perverts justice against the innocent",
     "reduces the income of the government",
     "is a form of gift that only the rich can afford",
     "was permitted for judges but not for kings",
     "A", "Exodus 23:8 and Deuteronomy 16:19: bribery corrupts judgment and oppresses the righteous."),

    # ---------------- Sexual Immorality ----------------
    (T_SEX, "Medium", "Paul told the Corinthians, 'Do you not know that your body is a temple of the Holy Spirit within you, which you have from God? You are not your own; you were bought with a price. So glorify God in your body.' He used this argument to",
     "urge believers to flee from sexual immorality",
     "encourage them to build a temple in Corinth",
     "explain why Christians should fast regularly",
     "justify the payment of the temple tax",
     "A", "1 Corinthians 6:18-20: immorality sins against one's own body, which belongs to God."),
    (T_SEX, "Medium", "Joseph resisted Potiphar's wife although she pressed him 'day after day', and when she caught his garment he fled out of the house. His example teaches that",
     "avoiding the occasion of temptation is wiser than trusting one's own strength",
     "servants should always obey their masters' wives",
     "a false accusation can be avoided by staying near the tempter",
     "faithfulness is guaranteed to bring immediate reward",
     "A", "Genesis 39:7-12: Joseph refused, avoided her, and finally fled, though it cost him prison."),
    (T_SEX, "Medium", "A student says, 'My body is mine; what I do with it in private is nobody's business.' Paul's answer would be that",
     "the believer's body belongs to the Lord, having been bought with a price",
     "private sins are not counted as sins by God",
     "the body is evil and therefore does not matter",
     "only public immorality brings judgment",
     "A", "1 Corinthians 6:13, 19-20: 'The body is not meant for immorality, but for the Lord.'"),
    (T_SEX, "Medium", "Paul instructed that a man in the Corinthian church who was living with his father's wife should be removed from the fellowship, because",
     "a little leaven leavens the whole lump, and open immorality tolerated corrupts the whole church",
     "the man had refused to pay his tithe to the church",
     "the church had no authority to forgive any sin",
     "his father had complained to the Roman governor",
     "A", "1 Corinthians 5:1-13: discipline aimed at the offender's restoration and the purity of the church."),
    (T_SEX, "Medium", "The writer of Hebrews said, 'Let marriage be held in honour among all, and let the marriage bed be undefiled; for God will judge the immoral and adulterous.' This teaches that",
     "sexual relations belong within marriage, which God honours and protects",
     "marriage is a lower state than remaining single",
     "adultery is judged only by human courts",
     "married people are exempt from sexual temptation",
     "A", "Hebrews 13:4: marriage is honourable and its exclusive bond is guarded by God's judgment."),
    (T_SEX, "Medium", "Nathan told David, 'You have despised the word of the LORD... the sword shall never depart from your house.' This shows that David's adultery",
     "was forgiven but still brought lasting consequences on his family",
     "was overlooked because he was king",
     "had no effect on anyone except Bathsheba",
     "was punished by his immediate removal from the throne",
     "A", "2 Samuel 12:9-14: 'The LORD has put away your sin', yet the child died and strife followed in David's house."),
]

FIX = {
    "Jesus turned the question round to show that": (
        "the real issue is not who deserves my love but whether I act as a neighbour to anyone in need",
        "Samaritans were better neighbours than Jews by nature and should be preferred as travelling companions",
        "priests and Levites were excused from helping the wounded because of the rules about ritual purity",
        "only those who live in the same town or village can properly be regarded as one's neighbours"),
    "The apostles solved the problem by": (
        "appointing seven men of good repute to serve tables while they gave themselves to prayer and the word",
        "expelling the Hellenists from the church in Jerusalem and sending them to form a church in Samaria",
        "sending the Hebrew widows back to their home towns so that the Hellenist widows could be fed first",
        "abolishing the daily distribution altogether and telling every family to provide for its own widows"),
    "'They are filled with new wine.' Peter answered that": (
        "this was the fulfilment of Joel's prophecy that God would pour out His Spirit on all flesh",
        "the disciples had indeed been drinking at the feast, but only to celebrate the resurrection",
        "the crowd should return to their countries at once and wait for the apostles to visit them",
        "only the twelve apostles could ever receive the Holy Spirit, so the crowd need not be concerned"),
    "Acts 13 and 16 suggest they have forgotten that": (
        "the Spirit calls and directs missionaries, sometimes forbidding one route and opening another",
        "missionaries should always go first to the wealthiest cities, where the greatest support is found",
        "only ordained apostles from Jerusalem may choose a mission field for the churches to support",
        "mission work should be confined to one's own tribe and language until every member is converted"),
    "The Council of Jerusalem replied that Gentile believers should": (
        "abstain from what has been sacrificed to idols, from blood, from what is strangled and from unchastity, but need not be circumcised",
        "be circumcised and keep the whole law of Moses before baptism, exactly as the men from Judea had taught them at Antioch",
        "form a separate church with its own elders and never eat with Jewish believers, so that neither group would be offended",
        "return to their former religions until the apostles could visit them, since the question could not be settled by letter"),
    "They justified this by quoting the prophecy,": (
        "'I have set you to be a light for the Gentiles, that you may bring salvation to the uttermost parts of the earth.'",
        "'Behold, a virgin shall conceive and bear a son, and his name shall be called Emmanuel, which means God with us.'",
        "'The stone which the builders rejected has become the head of the corner; this was the Lord's doing.'",
        "'Out of Egypt have I called my son, and I will gather the outcasts of Israel from the four corners of the earth.'"),
    "needs to understand that": (
        "justification gives a settled peace with God based on Christ's work, not on her performance",
        "peace with God is reserved for those who never fail, so her fear is the proper response to sin",
        "she should increase her good works until the fear disappears and God is satisfied with her record",
        "God's acceptance is withdrawn each time a believer sins and must be regained by fresh repentance"),
    "The two teachings agree because": (
        "Paul speaks of how a person is accepted by God, while James speaks of the works that prove faith is genuine",
        "James rejected Paul's gospel and taught salvation by works, but the church later decided that both were right",
        "Paul later changed his mind and accepted James' position that works must be added to faith for salvation",
        "the two apostles were writing about two different covenants, one for Jews and the other for Gentiles"),
    "it does not matter how I live.' Paul's answer would be that": (
        "grace frees believers from sin's dominion so that they become slaves of righteousness, not so that they may sin freely",
        "he is correct, since the law has no more relevance for a Christian's conduct once he has been baptised into Christ",
        "he should return to keeping the whole law of Moses to be safe, since grace alone cannot restrain the flesh",
        "grace is withdrawn from anyone who asks such a question, and he must be baptised again before he can be restored"),
    "He then gave practical examples, including": (
        "'Let the thief no longer steal, but rather let him labour, doing honest work with his hands.'",
        "'Let every person be subject to the governing authorities, for there is no authority except from God.'",
        "'If any one will not work, let him not eat, for we hear that some of you are living in idleness.'",
        "'Owe no one anything, except to love each other, for he who loves his neighbour has fulfilled the law.'"),
    "reminds her that": (
        "God has arranged every member in the body as He chose, and the less visible parts are indispensable",
        "only those who can preach or prophesy have received a spiritual gift, and the rest serve without one",
        "she should stop ushering until she receives a better gift, since ushering is not listed among the gifts",
        "the eye is the only member that matters in the body, and the other parts exist merely to support it"),
    "Paul preferred prophecy to uninterpreted tongues": (
        "prophecy edifies the church, whereas tongues without interpretation edify only the speaker",
        "tongues were a gift given only to the twelve apostles and had ceased before Paul's time",
        "prophecy was easier to fake than speaking in tongues and therefore easier to control",
        "the Corinthians did not possess the gift of tongues and were only pretending to speak in them"),
    "He gave as the reason that the ruler": (
        "is God's servant for your good and an avenger who executes wrath on the wrongdoer",
        "is always righteous and can never make an unjust law, since God appointed him",
        "has power to forgive sins in the name of God and to admit people to the church",
        "will reward Christians with positions in government if they support him faithfully"),
    "this teaches that Christian obedience to the state": (
        "is real but limited: when the state commands what God forbids, God must be obeyed",
        "is absolute, whatever the authorities command, since all authority comes from God",
        "applies only to Christian governments and may be withheld from pagan rulers",
        "can be withdrawn whenever taxes are raised or the church's property is threatened"),
    "He is correctly applying": (
        "obedience to lawful authority combined with the principle of obeying God rather than men",
        "the teaching that all human authority must be resisted because it is opposed to God",
        "the teaching that civil servants are exempt from Romans 13 because they are part of the state",
        "the principle that the end justifies the means, since exposing fraud is a good end"),
    "This was written when the emperor was": (
        "a pagan ruler, showing that respect for authority does not depend on the ruler's faith",
        "a Christian who had built churches throughout the empire and protected the apostles",
        "a Jew who had restored the temple in Jerusalem and invited Peter to preach there",
        "Peter's own relative from Galilee, which explains why the apostle urged such loyalty"),
    "He described partiality as a breach of": (
        "the royal law, 'You shall love your neighbour as yourself'",
        "the law of the Sabbath, 'Six days you shall labour'",
        "the law of tithing, 'Bring the full tithes into the storehouse'",
        "the law of circumcision given to Abraham and his seed"),
    "what I do with it in private is nobody's business.' Paul's answer would be that": (
        "the believer's body belongs to the Lord, having been bought with a price",
        "private sins are not counted as sins by God, so the matter is closed",
        "the body is evil and therefore what is done with it does not matter",
        "only public immorality brings judgment, while private sins are overlooked"),
    "should be removed from the fellowship, because": (
        "a little leaven leavens the whole lump, and open immorality tolerated corrupts the whole church",
        "the man had refused to pay his tithe to the church for more than a year despite repeated warnings",
        "the church had no authority to forgive any sin and could only hand offenders over to the state",
        "his father had complained to the Roman governor, who threatened to close the church in Corinth"),
}


def build():
    build_batch(
        S, "batch_027_crs_round3c.json", "batch_027_crs_round3c",
        "Christian Religious Studies round 3 (part C): Acts, the Epistles and Christian living - love, fellowship, the Holy Spirit and mission, opposition, mission to the Gentiles, justification, law and grace, new life, joint heirs, humility, forgiveness, spiritual gifts, giving, civic responsibility, dignity of labour, second coming, impartiality, prayer, community living, corruption and sexual immorality - scripture-based and application items.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
