"""Batch 035 - Principles of Accounts (Accounting) round 1, part A.

First curated bank for the Accounting subject (JAMB "Principles of Accounts"): nature of accounting,
concepts and conventions, source documents and books of original entry, the accounting equation and
ledger, trial balance, correction of errors and suspense account, ethics and regulatory bodies, cash
book and discounts, petty cash and the imprest system, bank reconciliation, final accounts of a sole
trader, year-end adjustments, depreciation and disposal of fixed assets.  Scenario, computation and
data-table items in the style of the UTME paper.

    python3 scripts/build_content_batch35.py -> content/batch_035_accounting_round1a.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Accounting"

T_NAT = "Nature and Significance of Accounting"
T_CON = "Accounting Concepts and Conventions"
T_SRC = "Source Documents and Books of Original Entry"
T_EQN = "The Accounting Equation and Ledger"
T_TB = "Trial Balance"
T_ERR = "Correction of Errors and Suspense Account"
T_ETH = "Ethics and Regulatory Bodies"
T_CB = "Cash Book and Discounts"
T_PC = "Petty Cash Book and Imprest System"
T_BRS = "Bank Reconciliation Statements"
T_FIN = "Final Accounts of a Sole Trader"
T_ADJ = "Adjustments: Accruals, Prepayments and Provisions"
T_DEP = "Depreciation and Disposal of Fixed Assets"

PASSAGES = [
    ("A1", T_FIN, "Balances of Ngozi Stores",
     "The following balances were extracted from the books of Ngozi Stores, a sole trader, on 31 December 2025.\n\n"
     "Item                          ₦\n"
     "Opening stock           120,000\n"
     "Purchases               850,000\n"
     "Sales                 1,400,000\n"
     "Returns inwards          20,000\n"
     "Returns outwards         15,000\n"
     "Carriage inwards         10,000\n"
     "Carriage outwards        25,000\n"
     "Wages and salaries      180,000\n"
     "Rent                     60,000\n"
     "Discount received        12,000\n\n"
     "Closing stock was valued at ₦150,000."),
    ("A2", T_BRS, "Cash book and bank statement of Bello Enterprises",
     "On 31 March 2026 the cash book of Bello Enterprises showed a debit bank balance of ₦86,000. When the cash book was compared with the bank statement the following were discovered:\n"
     "(i) cheques issued to suppliers but not yet presented to the bank, ₦24,000;\n"
     "(ii) cheques received and lodged but not yet credited by the bank, ₦15,000;\n"
     "(iii) bank charges of ₦2,500 shown only in the bank statement;\n"
     "(iv) a standing order for insurance of ₦6,000 paid by the bank;\n"
     "(v) a dividend of ₦9,000 paid directly into the account by a company;\n"
     "(vi) a customer's cheque for ₦7,500 returned by the bank marked 'refer to drawer'."),
    ("A4", T_PC, "Petty cash of Gateway College",
     "The petty cashier of Gateway College keeps an imprest of ₦50,000 which is restored on the first working day of every month. The petty cash payments for April 2026 were:\n\n"
     "Item                        ₦\n"
     "Postage stamps          4,500\n"
     "Cleaning materials      7,200\n"
     "Transport fares         9,800\n"
     "Stationery              6,300\n"
     "Refreshments            3,700"),
    ("A5", T_EQN, "Kemi's first month in business",
     "Kemi started a provisions business on 1 May 2026 with ₦500,000 cash. During May the following took place:\n"
     "1. She bought goods on credit from Dele for ₦120,000.\n"
     "2. She bought a motor van for cash, ₦200,000.\n"
     "3. She sold goods which had cost ₦60,000 for ₦90,000 cash.\n"
     "4. She paid Dele ₦50,000 cash on account.\n"
     "5. She took ₦20,000 cash from the business for her personal use."),
    ("A6", T_DEP, "Machine bought by Delta Bakery",
     "Delta Bakery bought a dough-mixing machine on 1 January 2023 for ₦2,400,000. The machine was expected to last five years and to have a scrap value of ₦400,000 at the end of that time. The bakery's financial year ends on 31 December. On 1 January 2026 the machine was sold for ₦1,000,000 cash."),
]

PQ = [
    # ---------------- A1 Ngozi Stores ----------------
    ("A1", "Easy", "Using the balances of Ngozi Stores, the net purchases for the year were",
     "₦845,000", "₦835,000", "₦865,000", "₦855,000",
     "A", "Net purchases = purchases 850,000 − returns outwards 15,000 + carriage inwards 10,000 = ₦845,000. Carriage inwards is part of the cost of bringing goods in.", "850000-15000+10000"),
    ("A1", "Easy", "The net sales (turnover) of Ngozi Stores for the year were",
     "₦1,385,000", "₦1,380,000", "₦1,420,000", "₦1,400,000",
     "B", "Net sales = sales 1,400,000 − returns inwards 20,000 = ₦1,380,000. Returns outwards relate to purchases, not sales.", "1400000-20000"),
    ("A1", "Medium", "The cost of goods sold by Ngozi Stores during the year was",
     "₦965,000", "₦830,000", "₦815,000", "₦820,000",
     "C", "Cost of goods sold = opening stock 120,000 + net purchases 845,000 − closing stock 150,000 = ₦815,000.", "120000+845000-150000"),
    ("A1", "Medium", "The gross profit of Ngozi Stores for the year was",
     "₦585,000", "₦550,000", "₦575,000", "₦565,000",
     "D", "Gross profit = net sales 1,380,000 − cost of goods sold 815,000 = ₦565,000.", "1380000-815000"),
    ("A1", "Hard", "The net profit of Ngozi Stores for the year was",
     "₦312,000", "₦300,000", "₦324,000", "₦337,000",
     "A", "Net profit = gross profit 565,000 + discount received 12,000 − (carriage outwards 25,000 + wages 180,000 + rent 60,000) = 577,000 − 265,000 = ₦312,000.", "565000+12000-25000-180000-60000"),
    ("A1", "Easy", "In the trading account of Ngozi Stores, the cost of goods available for sale was",
     "₦845,000", "₦965,000", "₦980,000", "₦970,000",
     "B", "Goods available for sale = opening stock 120,000 + net purchases 845,000 = ₦965,000, before deducting closing stock.", "120000+845000"),
    # ---------------- A2 Bello bank reconciliation ----------------
    ("A2", "Medium", "The adjusted cash book balance of Bello Enterprises on 31 March 2026 was",
     "₦86,000", "₦95,000", "₦79,000", "₦70,000",
     "C", "Only items (iii) to (vi) go into the cash book: 86,000 − 2,500 − 6,000 + 9,000 − 7,500 = ₦79,000. Unpresented and uncredited cheques are timing differences.", "86000-2500-6000+9000-7500"),
    ("A2", "Hard", "The balance shown by the bank statement of Bello Enterprises on 31 March 2026 was",
     "₦70,000", "₦88,000", "₦79,000", "₦97,000",
     "B", "Start from the adjusted cash book balance of 79,000, add unpresented cheques 24,000 (the bank has not yet paid them) and deduct uncredited lodgements 15,000: ₦88,000.", "79000+24000-15000"),
    ("A2", "Easy", "Which item in the Bello Enterprises comparison increases the balance in the cash book?",
     "the dividend paid directly into the account", "the standing order for insurance", "the cheque returned marked 'refer to drawer'", "the bank charges shown only on the statement",
     "A", "A dividend received directly by the bank is money the business did not know it had; it is debited in the cash book and increases the balance. The others reduce it."),
    ("A2", "Medium", "The total amount that should be credited in the cash book of Bello Enterprises to bring it up to date is",
     "₦31,000", "₦24,000", "₦9,000", "₦16,000",
     "D", "Credits (payments out) are bank charges 2,500 + standing order 6,000 + dishonoured cheque 7,500 = ₦16,000. The dividend is a debit.", "2500+6000+7500"),
    ("A2", "Easy", "In the Bello Enterprises case, the cheque returned marked 'refer to drawer' means that",
     "the bank had already paid the cheque twice", "the customer's account did not have enough money to meet the cheque", "the cheque was lodged after the closing date of the statement", "the customer had cancelled the sale",
     "B", "'Refer to drawer' is written on a dishonoured cheque: the drawer's bank refuses payment, usually because the account has insufficient funds."),
    # ---------------- A4 Gateway College petty cash ----------------
    ("A4", "Easy", "The total petty cash payments of Gateway College for April 2026 amounted to",
     "₦31,500", "₦27,800", "₦35,200", "₦18,500",
     "A", "4,500 + 7,200 + 9,800 + 6,300 + 3,700 = ₦31,500 was spent from the imprest during the month.", "4500+7200+9800+6300+3700"),
    ("A4", "Easy", "The cash remaining with the petty cashier of Gateway College on 30 April 2026 was",
     "₦31,500", "₦50,000", "₦18,500", "₦16,300",
     "C", "Cash in hand = imprest 50,000 − payments 31,500 = ₦18,500 before the float is restored.", "50000-31500"),
    ("A4", "Medium", "The amount the bursar must give the petty cashier of Gateway College on 1 May 2026 to restore the imprest is",
     "₦50,000", "₦31,500", "₦18,500", "₦81,500",
     "B", "Under the imprest system the cashier is reimbursed exactly what was spent, ₦31,500, so that the float returns to ₦50,000.", "31500"),
    ("A4", "Medium", "When the Gateway College imprest is restored on 1 May 2026, the entry in the main cash book is",
     "debit petty cash book, credit bank ₦50,000", "debit bank, credit petty cash ₦31,500", "debit petty cash account, credit bank ₦31,500", "debit sundry expenses, credit petty cash ₦31,500",
     "C", "Reimbursement transfers ₦31,500 from the bank (credit) to the petty cash (debit); the expenses themselves are posted from the analysis column totals."),
    # ---------------- A5 Kemi ----------------
    ("A5", "Easy", "Kemi's cash balance at the end of May 2026 was",
     "₦320,000", "₦340,000", "₦290,000", "₦300,000",
     "A", "Cash = 500,000 − 200,000 (van) + 90,000 (sales) − 50,000 (paid Dele) − 20,000 (drawings) = ₦320,000. The credit purchase did not involve cash.", "500000-200000+90000-50000-20000"),
    ("A5", "Easy", "At the end of May 2026 Kemi owed her creditor Dele",
     "₦120,000", "₦50,000", "₦70,000", "₦60,000",
     "C", "Dele supplied goods worth 120,000 and was paid 50,000, leaving a creditor balance of ₦70,000.", "120000-50000"),
    ("A5", "Medium", "The total assets of Kemi's business on 31 May 2026 amounted to",
     "₦640,000", "₦580,000", "₦520,000", "₦600,000",
     "B", "Cash 320,000 + stock (120,000 − 60,000 = 60,000) + motor van 200,000 = ₦580,000.", "320000+60000+200000"),
    ("A5", "Hard", "Kemi's capital at the end of May 2026 was",
     "₦500,000", "₦530,000", "₦480,000", "₦510,000",
     "D", "Closing capital = opening capital 500,000 + profit (90,000 − 60,000 = 30,000) − drawings 20,000 = ₦510,000. Check: assets 580,000 − creditors 70,000 = 510,000.", "500000+30000-20000"),
    ("A5", "Medium", "Which of Kemi's May transactions changed the total of her assets without changing her capital or liabilities?",
     "buying the motor van for cash", "buying goods on credit from Dele", "taking cash for personal use", "selling goods for ₦90,000 cash",
     "A", "Paying cash for a van simply exchanges one asset for another: total assets, liabilities and capital are all unchanged. The other transactions change liabilities or capital."),
    # ---------------- A6 Delta Bakery machine ----------------
    ("A6", "Easy", "Using the straight-line method, the annual depreciation on Delta Bakery's machine is",
     "₦480,000", "₦400,000", "₦560,000", "₦440,000",
     "B", "Straight line: (cost 2,400,000 − scrap 400,000) ÷ 5 years = ₦400,000 each year.", "(2400000-400000)/5"),
    ("A6", "Medium", "The net book value of Delta Bakery's machine on 31 December 2025 under the straight-line method was",
     "₦1,200,000", "₦960,000", "₦1,600,000", "₦800,000",
     "A", "Three years' depreciation (2023, 2024, 2025) = 3 × 400,000 = 1,200,000; net book value = 2,400,000 − 1,200,000 = ₦1,200,000.", "2400000-3*400000"),
    ("A6", "Hard", "If Delta Bakery had used the reducing-balance method at 20% per annum, the depreciation charge for 2025 would have been",
     "₦384,000", "₦480,000", "₦307,200", "₦400,000",
     "C", "2023: 20% of 2,400,000 = 480,000 (NBV 1,920,000); 2024: 384,000 (NBV 1,536,000); 2025: 20% of 1,536,000 = ₦307,200.", "2400000*0.8*0.8*0.2"),
    ("A6", "Medium", "Under the straight-line method, the sale of Delta Bakery's machine on 1 January 2026 resulted in a",
     "profit on disposal of ₦200,000", "loss on disposal of ₦200,000", "loss on disposal of ₦228,800", "profit on disposal of ₦600,000",
     "B", "Net book value on the date of sale was 1,200,000; sale proceeds 1,000,000; the shortfall of ₦200,000 is a loss on disposal charged to the profit and loss account."),
    ("A6", "Easy", "The scrap value of ₦400,000 in the Delta Bakery case is the",
     "amount the machine can be sold for at any time", "estimated value of the machine at the end of its useful life", "annual repair cost of the machine", "cost of installing the machine",
     "B", "Scrap (residual) value is the estimated amount recoverable when the asset is retired; it is deducted from cost before spreading the depreciable amount."),
]

Q = [
    # ---------------- Nature and significance ----------------
    (T_NAT, "Easy", "Recording the daily transactions of a shop in the books in a systematic manner is best described as",
     "bookkeeping", "auditing", "budgeting", "costing",
     "A", "Bookkeeping is the routine recording of transactions; accounting goes further to classify, summarise, interpret and report them."),
    (T_NAT, "Easy", "The Italian monk who first published a description of the double entry system in 1494 was",
     "Adam Smith", "John Keynes", "Luca Pacioli", "Alfred Marshall",
     "C", "Luca Pacioli described double entry bookkeeping in his 1494 work Summa de Arithmetica, and is regarded as the father of accounting."),
    (T_NAT, "Medium", "A bank considering a loan application from Ade Motors would be most interested in the firm's",
     "advertising budget", "choice of external auditors", "staff welfare policy", "liquidity and ability to repay",
     "D", "Lenders use accounting information to judge whether a business generates enough cash to service interest and repay the principal."),
    (T_NAT, "Easy", "Which of the following is an internal user of accounting information?",
     "management", "trade creditors", "the tax authority", "prospective investors",
     "A", "Managers work inside the entity and use accounting information for planning and control; the others are external users."),
    (T_NAT, "Medium", "A company published its 2024 financial statements in 2026. The information failed the qualitative characteristic of",
     "understandability", "timeliness", "comparability", "verifiability",
     "B", "Information loses its capacity to influence decisions when it arrives too late; timeliness is an enhancing characteristic of useful information."),
    (T_NAT, "Easy", "Presenting this year's figures side by side with last year's figures in the same format mainly enhances",
     "materiality", "prudence", "comparability", "objectivity",
     "C", "Comparability allows users to identify trends over time and differences between entities."),
    (T_NAT, "Easy", "The branch of accounting that gathers financial evidence for use in court cases and fraud investigations is",
     "cost accounting", "forensic accounting", "management accounting", "government accounting",
     "B", "Forensic accounting applies investigative and accounting skills to disputes and litigation."),
    (T_NAT, "Easy", "Cost accounting is primarily concerned with",
     "assessing the tax payable by a company", "ascertaining and controlling the cost of products and services", "expressing an opinion on published accounts", "recording receipts and payments of government",
     "B", "Cost accounting accumulates and analyses costs so that management can price products and control expenditure."),
    (T_NAT, "Medium", "Management accounting differs from financial accounting in that management accounting",
     "is governed strictly by accounting standards", "reports only on past events", "produces reports mainly for internal decision making", "must be audited every year",
     "C", "Management accounting reports are prepared for managers, are not bound by reporting standards and often look to the future (budgets, forecasts)."),
    (T_NAT, "Easy", "The person who examines the financial statements of a company and expresses an independent opinion on them is the",
     "company secretary", "auditor", "bookkeeper", "cost clerk",
     "B", "An auditor independently examines the records and reports whether the statements give a true and fair view."),
    (T_NAT, "Medium", "A trader who cannot tell whether he made a profit or a loss last year most probably",
     "kept no proper accounting records", "made too many cash sales", "employed an auditor", "paid too much tax",
     "A", "One of the main objectives of bookkeeping is to enable the profit or loss of a period to be determined; without records this is impossible."),
    (T_NAT, "Easy", "A major objective of keeping accounting records by a sole trader is to",
     "avoid paying tax", "ascertain the profit or loss for a period", "reduce the prices of goods", "increase the number of customers",
     "B", "Records make it possible to prepare a trading and profit and loss account and to know the financial position at any date."),
    (T_NAT, "Medium", "The accounts of the federal, state and local governments are prepared mainly to show",
     "how public funds were received and spent", "the profit earned for shareholders", "the market value of government shares", "the goodwill of the government",
     "A", "Government (public sector) accounting is concerned with stewardship and accountability for public money, not profit."),
    (T_NAT, "Easy", "The branch of accounting concerned with the effect of an organisation's activities on the community and on nature is",
     "auditing and assurance services", "taxation and revenue accounting", "social and environmental accounting", "financial and cost accounting",
     "C", "Social and environmental accounting reports on matters such as pollution, community projects and employee welfare."),
    (T_NAT, "Easy", "Accounting is often called the language of business because it",
     "is written and read only by professional accountants", "communicates the financial results of an entity to interested parties", "uses the English language in every country of the world", "is taught as a compulsory course in every business school",
     "B", "Through statements and reports, accounting communicates the performance and position of an entity to owners, lenders and others."),
    (T_NAT, "Medium", "Which of the following is a characteristic of useful accounting information?",
     "complexity", "secrecy", "reliability", "bulkiness",
     "C", "Useful information should be reliable (faithfully representing what it claims), relevant, comparable and understandable."),
    (T_NAT, "Medium", "The main difference between bookkeeping and accounting is that accounting",
     "is done only by the owner of the business and never by clerks", "records transactions without using the double entry system", "interprets and reports the recorded information for decision making", "stops at the trial balance stage and never goes beyond it",
     "C", "Bookkeeping ends at recording; accounting summarises, analyses and interprets the records so users can make decisions."),
    # ---------------- Concepts and conventions ----------------
    (T_CON, "Easy", "Mr Okon paid his daughter's school fees from the shop's cash and the payment was recorded as drawings. The concept applied is",
     "business entity", "going concern", "materiality", "consistency",
     "A", "The entity concept treats the business as separate from its owner, so private payments from business cash are drawings, not expenses."),
    (T_CON, "Easy", "Fixed assets are recorded at cost less depreciation rather than at their forced-sale values because of the",
     "money measurement concept", "going concern concept", "dual aspect concept", "realisation concept",
     "B", "Going concern assumes the business will continue operating, so assets are not valued as if they were about to be sold off."),
    (T_CON, "Easy", "A trader makes a provision for doubtful debts before any debtor actually fails to pay. This illustrates the concept of",
     "consistency", "periodicity", "prudence", "realisation",
     "C", "Prudence (conservatism) requires anticipating possible losses but not possible gains."),
    (T_CON, "Medium", "Electricity consumed in December 2025 but paid for in January 2026 is charged in the accounts for 2025 because of the",
     "accrual concept", "historical cost concept", "entity concept", "money measurement concept",
     "A", "Under the accrual (matching) concept, expenses are recognised in the period in which they are incurred, not when cash is paid."),
    (T_CON, "Easy", "The skill and loyalty of a company's chief engineer do not appear in its balance sheet because of the",
     "going concern concept", "prudence concept", "consistency concept", "money measurement concept",
     "D", "Only items that can be expressed in monetary terms are recorded; staff quality cannot be objectively measured in naira."),
    (T_CON, "Medium", "A company that changes its depreciation method every year to suit its profit target violates the concept of",
     "materiality", "consistency", "duality", "entity",
     "B", "Consistency requires the same treatment of similar items from period to period so that results are comparable."),
    (T_CON, "Medium", "A stapler costing ₦1,500 that will last five years is written off as an expense in the year of purchase. The convention applied is",
     "materiality", "objectivity", "prudence", "going concern",
     "A", "Materiality permits insignificant items to be treated in the simplest way, since capitalising and depreciating a stapler would not affect any decision."),
    (T_CON, "Easy", "Land bought in 2010 for ₦3 million and now worth ₦30 million is still shown in the books at ₦3 million under the",
     "realisation concept", "historical cost concept", "periodicity concept", "matching concept",
     "B", "The historical cost concept records assets at the actual amount paid for them, which is objective and verifiable."),
    (T_CON, "Medium", "Revenue is recognised when goods are delivered to a customer and not when the order is received. This is the",
     "entity concept", "consistency concept", "realisation concept", "going concern concept",
     "C", "Under the realisation concept revenue is recognised when it is earned, that is when ownership of goods passes to the buyer."),
    (T_CON, "Easy", "Preparing financial statements at regular intervals of twelve months is required by the",
     "periodicity concept", "prudence concept", "materiality concept", "dual aspect concept",
     "A", "The periodicity (accounting period) concept divides the life of a business into regular periods for reporting."),
    (T_CON, "Easy", "The principle that every transaction affects at least two accounts is the",
     "realisation concept", "dual aspect concept", "matching concept", "entity concept",
     "B", "Dual aspect is the basis of double entry: every debit has a corresponding credit."),
    (T_CON, "Medium", "Recording assets at amounts supported by invoices and receipts rather than the owner's personal estimates reflects",
     "objectivity", "materiality", "prudence", "consistency",
     "A", "Objectivity requires accounting records to be based on verifiable evidence free from personal bias."),
    (T_CON, "Hard", "A vehicle acquired under a finance lease is shown as an asset in the lessee's balance sheet although legal title remains with the lessor. This applies",
     "the historical cost concept", "the going concern concept", "substance over form", "the realisation concept",
     "C", "Substance over form reports the economic reality (the lessee enjoys the risks and rewards of ownership) rather than the legal form."),
    (T_CON, "Medium", "A note to the accounts describing a pending court case against the company is required by the convention of",
     "consistency", "full disclosure", "materiality", "objectivity",
     "B", "Full disclosure requires all information that could influence users' decisions to be reported, including contingencies."),
    (T_CON, "Medium", "Valuing closing stock at the lower of cost and net realisable value is an application of",
     "prudence", "duality", "consistency", "periodicity",
     "A", "Prudence ensures that anticipated losses on stock are recognised at once while unrealised gains are ignored."),
    (T_CON, "Hard", "Zeta Ltd recorded a ₦20 million sale in December 2025 although the goods were delivered to the customer in February 2026. The concept breached is",
     "realisation", "materiality", "entity", "money measurement",
     "A", "Revenue should be recognised when it is earned (goods delivered, ownership passed), so the sale belongs to the 2026 period."),
    (T_CON, "Medium", "The assumption that the purchasing power of the naira remains stable over time underlies the",
     "money measurement concept", "going concern concept", "consistency concept", "entity concept",
     "A", "Money measurement records transactions in monetary units and assumes the unit is a stable measure, ignoring inflation."),
    (T_CON, "Medium", "Charging depreciation over the useful life of an asset rather than writing off the whole cost when bought applies the",
     "entity concept", "matching concept", "prudence concept", "objectivity concept",
     "B", "Matching spreads the cost of the asset over the periods that benefit from its use so that expenses are matched with the revenue they help earn."),
    (T_CON, "Easy", "Accounting conventions are best described as",
     "laws passed by the National Assembly", "customs and practices generally accepted by accountants", "rules issued by commercial banks", "instructions from the owner of a business",
     "B", "Conventions such as consistency, materiality and prudence are generally accepted practices that guide the application of concepts."),
    (T_CON, "Hard", "A sole trader used ₦300,000 of business cash to buy a private car and debited motor vehicles account. The concept violated is",
     "money measurement", "business entity", "going concern", "periodicity",
     "B", "The car is for private use, so the payment is drawings; treating it as a business asset mixes the owner's affairs with the entity's."),
    # ---------------- Source documents and books of original entry ----------------
    (T_SRC, "Easy", "The document sent by a seller to a buyer showing the goods supplied, their quantities and prices is",
     "an invoice", "a credit note", "a receipt", "a pay-in slip",
     "A", "The invoice is the source document for credit sales (to the seller) and credit purchases (to the buyer)."),
    (T_SRC, "Easy", "A seller issues a credit note to a customer when",
     "the customer pays the amount due before the agreed date", "goods are returned by the customer or the customer was overcharged", "the customer's cheque is returned unpaid by the bank", "goods ordered by the customer are delivered to his premises",
     "B", "A credit note reduces the amount owed by the customer, for example for returns or an overcharge on the invoice."),
    (T_SRC, "Medium", "A seller who discovers that a customer was undercharged on an invoice corrects the error by sending a",
     "receipt", "credit note", "debit note", "statement of account",
     "C", "A debit note increases the amount the customer owes; a credit note would reduce it."),
    (T_SRC, "Easy", "Goods bought on credit for resale are first recorded in the",
     "purchases day book", "general journal", "cash book", "returns inwards book",
     "A", "The purchases day book (purchases journal) lists credit purchases of goods from copies of suppliers' invoices."),
    (T_SRC, "Medium", "The purchase of a delivery van on credit from Toyota Nigeria is recorded in the",
     "purchases day book", "sales day book", "cash book", "general journal",
     "D", "Credit purchases of fixed assets are not goods for resale, so they go through the journal proper (general journal)."),
    (T_SRC, "Medium", "The returns outwards book is written up from",
     "credit notes received from suppliers", "invoices sent to customers", "receipts issued to customers", "pay-in slips from the bank",
     "A", "When goods are returned to a supplier, the supplier sends a credit note; copies are the source for the returns outwards journal."),
    (T_SRC, "Easy", "The sales day book is written up from",
     "copies of invoices sent to customers", "cheques received from customers", "credit notes received from suppliers", "petty cash vouchers",
     "A", "Each credit sale is evidenced by the invoice sent to the customer; the sales journal lists these invoices."),
    (T_SRC, "Medium", "A trader bought goods with a list price of ₦80,000 subject to a trade discount of 10%. The amount entered in the purchases day book is",
     "₦80,000", "₦72,000", "₦88,000", "₦8,000",
     "B", "Trade discount is deducted on the invoice; the net amount 80,000 − 8,000 = ₦72,000 is recorded. Trade discount never appears in the ledger.", "80000*0.9"),
    (T_SRC, "Easy", "Trade discount is",
     "recorded in the discount column of the cash book", "credited to the discount received account", "not recorded in the ledger accounts at all", "debited to the discount allowed account",
     "C", "Trade discount is simply deducted on the invoice to arrive at the price; only cash discounts are entered in the books."),
    (T_SRC, "Medium", "Which of the following is both a book of original entry and a ledger account?",
     "sales day book", "general journal", "cash book", "purchases day book",
     "C", "The cash book records cash and bank transactions as they occur (prime entry) and also serves as the cash and bank accounts."),
    (T_SRC, "Easy", "Opening entries, the correction of errors and the writing off of bad debts are recorded in the",
     "sales journal", "general journal", "returns inwards journal", "petty cash book",
     "B", "The general journal (journal proper) records transactions that do not fit into any of the special journals, with a narration."),
    (T_SRC, "Easy", "A receipt is a document that",
     "orders a bank to pay money", "acknowledges money received", "requests payment from a debtor", "lists goods delivered",
     "B", "A receipt is issued by the person receiving cash or cheque as evidence of payment."),
    (T_SRC, "Easy", "The document completed when cash and cheques are paid into a bank account is the",
     "cheque counterfoil", "bank statement", "pay-in slip", "debit note",
     "C", "The pay-in slip (teller) lists the cash and cheques lodged and is the source document for bank deposits."),
    (T_SRC, "Medium", "A petty cash voucher is used to",
     "record the reimbursement of the imprest", "support each payment made from petty cash", "list the analysis columns of the petty cash book", "record purchases of goods on credit",
     "B", "Every petty cash payment should be supported by a voucher signed by the person receiving the money and authorised by an officer."),
    (T_SRC, "Easy", "The person who writes and signs a cheque is called the",
     "payee", "drawee", "drawer", "endorser",
     "C", "The drawer signs the cheque, the drawee is the bank instructed to pay and the payee is the person to be paid."),
    (T_SRC, "Medium", "The total of the sales day book at the end of the month is posted to the",
     "debit of each customer's account", "credit of the sales account", "debit of the sales account", "credit of the debtors control account",
     "B", "Individual invoices are debited to the customers; the periodic total is credited to sales account in the general ledger."),
    (T_SRC, "Medium", "Each entry in the purchases day book is posted to the",
     "credit of the individual supplier's account", "debit of the individual supplier's account", "credit of the purchases account", "debit of the cash book",
     "A", "Each credit purchase increases what is owed to the supplier (credit the personal account); the total is debited to purchases account."),
    (T_SRC, "Medium", "A statement of account received monthly from a supplier is used by the buyer to",
     "record the month's purchases in the purchases day book", "check the balance owed against the supplier's account in the purchases ledger", "calculate the trade discount allowed on each invoice", "replace the individual invoices received during the month",
     "B", "The statement summarises invoices, credit notes and payments; the buyer agrees it with the supplier's ledger account before paying."),
    (T_SRC, "Easy", "Goods returned by a customer are recorded in the",
     "returns outwards journal", "sales journal", "returns inwards journal", "purchases journal",
     "C", "Sales returns (returns inwards) are listed in the returns inwards journal from copies of credit notes issued."),
    # ---------------- Accounting equation and ledger ----------------
    (T_EQN, "Easy", "A business has assets of ₦950,000 and liabilities of ₦320,000. Its capital is",
     "₦1,270,000", "₦630,000", "₦320,000", "₦950,000",
     "B", "Capital = assets − liabilities = 950,000 − 320,000 = ₦630,000.", "950000-320000"),
    (T_EQN, "Easy", "If capital is ₦400,000 and liabilities are ₦150,000, total assets amount to",
     "₦250,000", "₦400,000", "₦550,000", "₦150,000",
     "C", "Assets = capital + liabilities = 400,000 + 150,000 = ₦550,000.", "400000+150000"),
    (T_EQN, "Medium", "Which transaction increases both total assets and total liabilities?",
     "paying a creditor by cheque", "buying goods on credit", "receiving cash from a debtor", "owner withdrawing cash",
     "B", "Goods bought on credit increase stock (an asset) and creditors (a liability) by the same amount."),
    (T_EQN, "Medium", "Which transaction leaves the total assets of a business unchanged?",
     "collecting ₦40,000 cash from a debtor", "paying ₦40,000 to a creditor", "buying goods on credit for ₦40,000", "the owner introducing ₦40,000 cash",
     "A", "Cash goes up and debtors go down by the same amount: one asset replaces another and the total is unchanged."),
    (T_EQN, "Easy", "When the owner takes goods from the business for personal use, the effect on the accounting equation is that",
     "assets decrease and capital decreases", "assets increase and liabilities increase", "liabilities decrease and capital increases", "assets decrease and liabilities decrease",
     "A", "Drawings of stock reduce the asset (stock) and reduce the owner's capital."),
    (T_EQN, "Easy", "Paying a creditor ₦50,000 by cheque",
     "increases assets and increases liabilities", "decreases assets and decreases liabilities", "decreases assets and increases capital", "increases liabilities and decreases capital",
     "B", "Bank (asset) falls by 50,000 and creditors (liability) fall by 50,000."),
    (T_EQN, "Easy", "The accounts of individual debtors and creditors are classified as",
     "real accounts", "nominal accounts", "personal accounts", "suspense accounts",
     "C", "Personal accounts are those of persons and organisations; real accounts are for assets and nominal accounts for expenses, losses, incomes and gains."),
    (T_EQN, "Easy", "Rent account and wages account are examples of",
     "nominal accounts", "real accounts", "personal accounts", "capital accounts",
     "A", "Expenses and incomes are recorded in nominal (impersonal) accounts which are closed to the profit and loss account."),
    (T_EQN, "Easy", "Motor vehicles account is classified as a",
     "personal account", "nominal account", "real account", "memorandum account",
     "C", "Real accounts record tangible property such as buildings, machinery and vehicles."),
    (T_EQN, "Medium", "The rule 'debit the receiver, credit the giver' applies to",
     "nominal accounts", "personal accounts", "real accounts", "control accounts",
     "B", "For personal accounts, the person who receives value is debited and the person who gives value is credited."),
    (T_EQN, "Easy", "The double entry for cash sales of ₦25,000 is",
     "debit sales, credit cash", "debit cash, credit sales", "debit debtors, credit sales", "debit cash, credit debtors",
     "B", "Cash comes in (debit cash account) and sales revenue is earned (credit sales account)."),
    (T_EQN, "Medium", "Goods previously bought on credit from Musa are returned to him. The entry is",
     "debit returns outwards, credit Musa", "debit Musa, credit purchases", "debit Musa, credit returns outwards", "debit returns inwards, credit Musa",
     "C", "The return reduces what is owed to Musa (debit his account) and is recorded in returns outwards account (credit)."),
    (T_EQN, "Easy", "A debit balance on a customer's account in the sales ledger means that",
     "the customer owes the business", "the business owes the customer", "the customer has overpaid", "the account has been closed",
     "A", "Debtors' accounts normally have debit balances representing amounts due from customers."),
    (T_EQN, "Medium", "The credit balance on the capital account of a sole trader represents",
     "cash available in the business", "the amount the business owes its owner", "the value of fixed assets", "profit for the year",
     "B", "Under the entity concept the owner is treated as a creditor of the business for the capital invested plus accumulated profits."),
    (T_EQN, "Medium", "Which of the following accounts normally has a credit balance?",
     "carriage inwards", "drawings", "discount received", "returns inwards",
     "C", "Discount received is an income and, like sales and capital, has a credit balance; the others are debit balances."),
    (T_EQN, "Easy", "The purchase of office furniture by cheque is recorded by",
     "debit furniture, credit bank", "debit purchases, credit bank", "debit bank, credit furniture", "debit furniture, credit cash",
     "A", "A fixed asset account is debited and the bank account credited; it is not a purchase of goods for resale."),
    (T_EQN, "Easy", "When the owner introduces additional capital of ₦200,000 in cash, the entry is",
     "debit capital, credit cash", "debit cash, credit drawings", "debit cash, credit capital", "debit capital, credit drawings",
     "C", "Cash (asset) increases so cash is debited; the owner's claim increases so capital is credited."),
    (T_EQN, "Medium", "In a business that keeps a sales ledger, a purchases ledger and a general ledger, the discount allowed account is found in the",
     "sales ledger", "purchases ledger", "general ledger", "cash book",
     "C", "Nominal accounts such as discount allowed are kept in the general (nominal) ledger; personal accounts go in the sales and purchases ledgers."),
    (T_EQN, "Hard", "A trader has stock ₦60,000, debtors ₦40,000, cash ₦25,000 and a van ₦300,000. He owes creditors ₦45,000 and has a bank overdraft of ₦20,000. His capital is",
     "₦425,000", "₦360,000", "₦380,000", "₦490,000",
     "B", "Assets 60,000 + 40,000 + 25,000 + 300,000 = 425,000; liabilities 45,000 + 20,000 = 65,000; capital = ₦360,000.", "425000-65000"),
    # ---------------- Trial balance ----------------
    (T_TB, "Easy", "The main purpose of extracting a trial balance is to",
     "calculate the profit for the year", "test the arithmetical accuracy of the ledger", "list the assets and liabilities of the business", "detect all errors in the books",
     "B", "A trial balance checks that total debits equal total credits; it does not reveal every kind of error."),
    (T_TB, "Easy", "Which of the following appears on the credit side of a trial balance?",
     "carriage inwards", "drawings", "returns outwards", "opening stock",
     "C", "Returns outwards reduce purchases and have a credit balance; the other three are debit balances."),
    (T_TB, "Easy", "Which of the following appears on the debit side of a trial balance?",
     "sales", "capital", "creditors", "carriage inwards",
     "D", "Carriage inwards is an expense (debit balance); sales, capital and creditors are credit balances."),
    (T_TB, "Medium", "Closing stock does not normally appear in the trial balance because",
     "it is not regarded as an asset of the business at the year end", "it is valued by physical count after the ledger balances have been extracted", "it is always equal to the opening stock of the following year", "it belongs to the customers who have already paid for it",
     "B", "The stock figure at the year end comes from a stocktaking, so it is brought into the books only when the final accounts are prepared."),
    (T_TB, "Medium", "The totals of a trial balance agree. Which of the following errors may still exist in the books?",
     "an error of principle", "posting only the debit entry of a transaction", "adding up the sales day book wrongly", "entering ₦4,500 as ₦5,400 in one account only",
     "A", "Errors of principle, omission, commission, original entry, compensating errors and complete reversal do not disturb the agreement of the trial balance."),
    (T_TB, "Medium", "The debit total of a trial balance is ₦1,254,000 and the credit total is ₦1,238,000. Pending discovery of the errors, the difference is",
     "credited to a suspense account, ₦16,000", "debited to a suspense account, ₦16,000", "credited to capital account, ₦16,000", "written off to profit and loss, ₦16,000",
     "A", "Debits exceed credits by 16,000, so a credit of ₦16,000 is entered in a suspense account to make the trial balance agree temporarily.", "1254000-1238000"),
    (T_TB, "Easy", "In a trial balance, the provision for doubtful debts appears as a",
     "debit balance", "credit balance", "note below the totals", "current asset",
     "B", "A provision is a credit balance set against the debtors, which are a debit balance."),
    (T_TB, "Easy", "Which of these balances would appear on the same side of the trial balance as purchases?",
     "sales", "drawings", "discount received", "bank loan",
     "B", "Purchases and drawings are both debit balances; the others are credit balances."),
    (T_TB, "Easy", "A trial balance is usually extracted",
     "before any transaction of the period is posted to the ledger", "at the end of an accounting period before the final accounts are prepared", "only when the business is about to be sold to a new owner", "after the balance sheet of the period has been drawn up",
     "B", "Balancing the ledger and listing the balances is the step between posting and preparing the final accounts."),
    (T_TB, "Easy", "Capital, sales, creditors and a loan from the bank are all",
     "debit balances", "credit balances", "real accounts", "current assets",
     "B", "Sources of funds (capital and liabilities) and incomes have credit balances."),
    (T_TB, "Hard", "Discount allowed of ₦4,000 was listed on the credit side of the trial balance instead of the debit side. The difference between the two totals is",
     "₦4,000", "₦2,000", "₦8,000", "nil",
     "C", "The debit side is short by 4,000 and the credit side is overstated by 4,000, giving a difference of ₦8,000.", "4000*2"),
    (T_TB, "Easy", "Rent received of ₦30,000 appears in the trial balance of a trader as a",
     "credit balance", "debit balance", "current liability", "fixed asset",
     "A", "Rent received is an income and therefore has a credit balance."),
    (T_TB, "Easy", "A bank overdraft is shown in the trial balance on the",
     "debit side as an asset", "credit side as a liability", "debit side as an expense", "credit side as an income",
     "B", "An overdraft is money owed to the bank; the bank column of the cash book has a credit balance."),
    (T_TB, "Medium", "The provision for depreciation on machinery appears in the trial balance as a",
     "debit balance representing an expense", "credit balance representing accumulated depreciation", "debit balance representing the asset", "credit balance representing income",
     "B", "The provision (accumulated depreciation) account collects the depreciation charged to date and is a credit balance deducted from the asset's cost."),
    # ---------------- Correction of errors and suspense ----------------
    (T_ERR, "Easy", "A credit sale of ₦45,000 to Bola was not recorded anywhere in the books. This is an error of",
     "commission", "omission", "principle", "original entry",
     "B", "An error of omission occurs when a transaction is completely left out of the books; the trial balance still agrees."),
    (T_ERR, "Easy", "Cash paid to Chidi was correctly credited to cash but debited to the account of Chike, another supplier. This is an error of",
     "commission", "principle", "omission", "compensation",
     "A", "An error of commission posts the correct amount to the wrong account of the same class (a personal account for another personal account)."),
    (T_ERR, "Easy", "The purchase of a computer for office use was debited to the purchases account. This is an error of",
     "original entry", "commission", "principle", "omission",
     "C", "An error of principle records a transaction in the wrong class of account, here capital expenditure treated as revenue expenditure."),
    (T_ERR, "Medium", "A sales invoice for ₦72,000 was entered in the sales day book as ₦27,000 and posted with that figure to both accounts. This is an error of",
     "original entry", "complete reversal", "commission", "principle",
     "A", "When the wrong amount is entered in the book of original entry and carried through the double entry, it is an error of original entry."),
    (T_ERR, "Medium", "The sales day book was overcast by ₦10,000. The correcting entry is",
     "debit suspense, credit sales ₦10,000", "debit sales, credit suspense ₦10,000", "debit debtors, credit sales ₦10,000", "debit sales, credit debtors ₦10,000",
     "B", "Sales account was over-credited by 10,000 while the individual debtors were correct, so sales is debited and suspense credited."),
    (T_ERR, "Easy", "Cash received from a debtor was debited to the debtor's account and credited to cash account. This is an error of",
     "omission", "principle", "complete reversal of entries", "compensation",
     "C", "Both entries were made with the correct amount but on the wrong sides; the trial balance still agrees."),
    (T_ERR, "Easy", "Purchases were undercast by ₦5,000 and, quite separately, sales were undercast by ₦5,000. These are",
     "errors of principle", "compensating errors", "errors of omission", "errors of commission",
     "B", "Two independent errors of equal amount on opposite sides cancel each other out so the trial balance still agrees."),
    (T_ERR, "Medium", "Which of the following errors would cause the trial balance to disagree?",
     "recording a sale to Ade in the account of Ada", "posting only the debit side of a transaction", "treating repairs as an addition to machinery", "omitting a purchase invoice entirely",
     "B", "A one-sided (single) entry means debits no longer equal credits; the other three errors keep the totals equal."),
    (T_ERR, "Hard", "Discount allowed of ₦3,000 was credited to discount received account. The entry to correct the error is",
     "debit discount allowed ₦3,000, credit discount received ₦3,000", "debit discount allowed ₦3,000, debit discount received ₦3,000, credit suspense ₦6,000", "debit suspense ₦6,000, credit discount allowed ₦6,000", "debit discount received ₦3,000, credit suspense ₦3,000",
     "B", "Discount allowed should have been debited 3,000; instead discount received was credited 3,000. Both must be corrected, and the 6,000 goes to suspense."),
    (T_ERR, "Hard", "Returns outwards of ₦8,000 were correctly entered in the returns outwards account but not posted to the supplier's account. Before correction the suspense account would show",
     "a debit balance of ₦8,000", "a credit balance of ₦8,000", "a debit balance of ₦16,000", "no balance at all",
     "A", "The credit to returns outwards was made but the debit to the supplier was missing, so debits are short by 8,000 and suspense carries a debit of ₦8,000."),
    (T_ERR, "Medium", "Wages of ₦25,000 paid to workers who installed a new machine were debited to wages account. As a result the net profit is",
     "overstated by ₦25,000", "understated by ₦25,000", "overstated by ₦50,000", "not affected",
     "B", "Installation wages are part of the cost of the machine (capital expenditure); charging them as an expense reduces profit wrongly by ₦25,000."),
    (T_ERR, "Medium", "A suspense account was opened with a debit of ₦5,000. It was later found that the purchases account had been undercast by ₦5,000. The correcting entry is",
     "debit suspense, credit purchases ₦5,000", "debit purchases, credit suspense ₦5,000", "debit purchases, credit creditors ₦5,000", "debit creditors, credit suspense ₦5,000",
     "B", "Purchases needs an extra debit of 5,000; the credit goes to suspense, which clears the balance."),
    (T_ERR, "Easy", "Which of the following errors does not require the use of a suspense account for its correction?",
     "a one-sided entry", "an error of principle", "an addition error in a ledger account", "a balance omitted from the trial balance",
     "B", "Errors of principle do not affect the agreement of the trial balance, so they are corrected by journal entries between the accounts concerned."),
    (T_ERR, "Medium", "After errors are corrected, the net profit previously reported must be adjusted when the error involved",
     "two personal accounts only", "an expense or income account", "two asset accounts only", "the cash and bank columns only",
     "B", "Only errors touching nominal accounts (revenues and expenses) change the profit; errors between assets and liabilities affect the balance sheet only."),
    (T_ERR, "Hard", "Goods worth ₦15,000 returned by a customer were recorded in the returns outwards book and posted accordingly. The correcting entry is",
     "debit returns inwards ₦15,000, credit returns outwards ₦15,000", "debit returns inwards ₦15,000, debit returns outwards ₦15,000, credit the customer ₦30,000", "debit the customer ₦30,000, credit returns inwards ₦30,000", "debit returns outwards ₦15,000, credit the customer ₦15,000",
     "B", "The wrong entry debited the customer 15,000 and credited returns outwards; the correct entry needed a debit to returns inwards and a credit to the customer. Reversing and correcting gives a 30,000 credit to the customer."),
    (T_ERR, "Medium", "Motor expenses of ₦12,000 were debited to motor vehicles account. The effect of the error is that",
     "profit is understated and assets are understated", "profit is overstated and assets are overstated", "profit is overstated and liabilities are understated", "there is no effect on profit or assets",
     "B", "An expense was treated as an asset, so expenses are too low (profit too high) and fixed assets too high, each by ₦12,000."),
    (T_ERR, "Hard", "A trader's draft net profit was ₦480,000. It was then found that closing stock had been understated by ₦30,000 and that rent paid of ₦20,000 had been omitted. The corrected net profit is",
     "₦490,000", "₦530,000", "₦430,000", "₦470,000",
     "A", "Higher closing stock raises profit by 30,000; the omitted rent reduces it by 20,000: 480,000 + 30,000 − 20,000 = ₦490,000.", "480000+30000-20000"),
    (T_ERR, "Hard", "Cash of ₦18,000 received from Femi, a debtor, was debited to Femi's account and credited to cash. The correcting entry is",
     "debit cash ₦18,000, credit Femi ₦18,000", "debit Femi ₦36,000, credit cash ₦36,000", "debit cash ₦36,000, credit Femi ₦36,000", "debit suspense ₦18,000, credit Femi ₦18,000",
     "C", "To cancel the reversed entry and record the correct one, twice the amount is needed: debit cash 36,000 and credit Femi 36,000."),
]

Q += [
    # ---------------- Ethics and regulatory bodies ----------------
    (T_ETH, "Easy", "An accountant who refuses to inflate the profit figure despite pressure from the managing director is displaying",
     "integrity", "confidentiality", "competence", "courtesy",
     "A", "Integrity means being straightforward and honest in all professional and business relationships, even under pressure."),
    (T_ETH, "Easy", "An accountant who discusses a client's tax affairs with friends at a party breaches the ethical principle of",
     "objectivity", "confidentiality", "professional competence", "independence",
     "B", "Confidentiality forbids disclosing information acquired in the course of professional work without proper authority."),
    (T_ETH, "Medium", "An auditor who owns a large number of shares in the company he audits lacks",
     "competence", "due care", "independence", "diligence",
     "C", "A financial interest in the client threatens the auditor's objectivity and independence, so it is prohibited."),
    (T_ETH, "Easy", "The professional body whose members use the designation ACA and which was established in Nigeria in 1965 is the",
     "Association of National Accountants of Nigeria", "Institute of Chartered Accountants of Nigeria", "Chartered Institute of Bankers of Nigeria", "Chartered Institute of Taxation of Nigeria",
     "B", "ICAN was established by Act of Parliament No. 15 of 1965 and confers the ACA and FCA designations."),
    (T_ETH, "Easy", "The body responsible for the registration and regulation of companies in Nigeria is the",
     "Central Bank of Nigeria", "Federal Inland Revenue Service", "Corporate Affairs Commission", "Nigerian Stock Exchange",
     "C", "The CAC, set up under the Companies and Allied Matters Act, registers companies and business names and keeps their statutory filings."),
    (T_ETH, "Medium", "The Nigerian body that issues and enforces financial reporting standards for companies is the",
     "Financial Reporting Council of Nigeria", "Securities and Exchange Commission", "National Insurance Commission", "Institute of Chartered Accountants of Nigeria",
     "A", "The FRCN (formerly the Nigerian Accounting Standards Board) sets and monitors compliance with accounting and auditing standards in Nigeria."),
    (T_ETH, "Easy", "International Financial Reporting Standards (IFRS) are issued by the",
     "International Monetary Fund", "International Accounting Standards Board", "World Bank", "United Nations",
     "B", "The IASB, based in London, develops and publishes IFRS, which Nigeria adopted for listed companies from 2012."),
    (T_ETH, "Medium", "The other recognised accountancy professional body in Nigeria whose members bear the designation CNA is the",
     "Chartered Institute of Stockbrokers", "Association of National Accountants of Nigeria", "Nigerian Institute of Management", "Chartered Institute of Personnel Management",
     "B", "ANAN, established by Decree 76 of 1993, awards the Certified National Accountant (CNA) designation."),
    (T_ETH, "Medium", "An accountant who accepts an engagement to prepare accounts under IFRS although he has never studied the standards breaches the principle of",
     "confidentiality of client information", "integrity in professional dealings", "professional competence and due care", "objectivity and independence",
     "C", "Professional competence requires an accountant to take on only work he has the knowledge and skill to perform properly."),
    (T_ETH, "Easy", "Which quality is most essential to an accountant entrusted with public funds?",
     "eloquence", "accountability", "popularity", "creativity",
     "B", "Accountability means being answerable for the resources placed in one's care and being ready to give a true account of them."),
    (T_ETH, "Medium", "The body that regulates the capital market and protects investors in Nigeria is the",
     "Central Bank of Nigeria", "Nigeria Deposit Insurance Corporation", "Securities and Exchange Commission", "Bureau of Public Enterprises",
     "C", "The SEC is the apex regulator of the Nigerian capital market and oversees public offers, stockbrokers and listed companies' disclosures."),
    (T_ETH, "Easy", "The federal agency responsible for assessing and collecting companies income tax in Nigeria is the",
     "Federal Inland Revenue Service", "Corporate Affairs Commission", "Nigerian Customs Service", "Budget Office of the Federation",
     "A", "The FIRS administers companies income tax, petroleum profits tax and value added tax at the federal level."),
    (T_ETH, "Medium", "Transparency in accounting means that",
     "profit figures are kept secret from competitors and from the tax authorities", "financial information is presented openly so that users can see how figures were arrived at", "the accountant works in an open office where every visitor can watch him", "all the figures in the accounts are rounded to the nearest million naira",
     "B", "Transparent reporting discloses methods, assumptions and results clearly rather than hiding them."),
    (T_ETH, "Hard", "A cashier who records fictitious payments and pockets the money is committing",
     "an error of principle", "a compensating error", "fraud", "an error of original entry",
     "C", "Fraud is a deliberate act to obtain an unjust advantage; errors are unintentional mistakes."),
    (T_ETH, "Medium", "The main purpose of adopting IFRS in Nigeria was to",
     "increase the salaries and status of accountants working in Nigeria", "make Nigerian financial statements comparable with those of other countries", "reduce the number of companies registered by the Corporate Affairs Commission", "abolish the payment of companies income tax by listed companies",
     "B", "A single set of global standards allows investors and lenders to compare companies across borders and improves confidence in Nigerian reports."),
    # ---------------- Cash book and discounts ----------------
    (T_CB, "Easy", "A three-column cash book has columns for",
     "cash, bank and discount", "cash, cheque and credit", "debit, credit and balance", "sales, purchases and cash",
     "A", "The three columns on each side are discount, cash and bank; the discount columns are memorandum columns only."),
    (T_CB, "Easy", "The discount columns of a three-column cash book are",
     "balanced off at the month end exactly like the cash columns", "totalled and posted to the discount accounts in the general ledger", "ignored at the end of the month because they are memoranda", "transferred directly to the balance sheet as current assets",
     "B", "The discount columns are memoranda: the debit-side total goes to discount allowed account and the credit-side total to discount received account."),
    (T_CB, "Medium", "A customer who owes ₦60,000 settles his account within the discount period and is allowed 5% cash discount. The bank column and discount column entries on the debit side are",
     "₦57,000 and ₦3,000", "₦60,000 and ₦3,000", "₦63,000 and ₦3,000", "₦57,000 and ₦5,000",
     "A", "Discount allowed = 5% of 60,000 = 3,000; the cheque received is 57,000, entered in the bank column, and the 3,000 in the discount allowed column."),
    (T_CB, "Easy", "Cash discount is given to a customer to",
     "encourage bulk purchases", "encourage prompt payment", "compensate for damaged goods", "reduce the list price",
     "B", "Cash (settlement) discount is an allowance for paying within a stated period; trade discount is for bulk or trade buyers."),
    (T_CB, "Easy", "Discount allowed is shown in the final accounts as",
     "an expense in the profit and loss account", "a deduction from sales in the trading account", "an income in the profit and loss account", "a current liability",
     "A", "Discount allowed to customers is a cost of collecting debts and is debited to the profit and loss account."),
    (T_CB, "Medium", "The entry 'cash ₦50,000 paid into bank' is recorded in the cash book by",
     "debit bank column, credit cash column", "debit cash column, credit bank column", "debit bank column only", "credit cash column only",
     "A", "This is a contra entry: bank receives (debit) and cash gives (credit), marked with the letter C in the folio column."),
    (T_CB, "Easy", "The letter 'C' written in the folio column of a cash book indicates",
     "a cheque payment", "a contra entry", "a credit sale", "a cash discount",
     "B", "Contra entries are transfers between the cash and bank columns; both halves are within the cash book so no ledger posting is needed."),
    (T_CB, "Medium", "The bank column of a cash book shows a credit balance. This means the business has",
     "money in the bank", "an overdraft at the bank", "uncredited lodgements", "unpresented cheques",
     "B", "A credit (excess of payments over receipts) in the bank column indicates that the business owes the bank, that is an overdraft."),
    (T_CB, "Easy", "The cash column of a cash book can never have a credit balance because",
     "cash payments are recorded on the debit side", "a business cannot pay out more cash than it has", "cash is always banked immediately", "cash receipts are recorded in the sales day book",
     "B", "Physical cash paid cannot exceed cash held, so the cash column always has a debit balance or nil."),
    (T_CB, "Medium", "A trader bought goods listed at ₦100,000 less 20% trade discount and paid within a week to obtain 2½% cash discount. The amount paid was",
     "₦77,500", "₦78,000", "₦80,000", "₦97,500",
     "B", "Invoice price = 100,000 − 20% = 80,000; cash discount 2½% of 80,000 = 2,000; amount paid ₦78,000.", "80000*0.975"),
    (T_CB, "Medium", "Discount received appears in the final accounts as",
     "a deduction from purchases in the trading account", "an expense in the profit and loss account", "an income in the profit and loss account", "an addition to creditors in the balance sheet",
     "C", "Discount received from suppliers for prompt payment is a gain, credited to the profit and loss account."),
    (T_CB, "Hard", "A business received a cheque for ₦38,000 from Ola in full settlement of a debt of ₦40,000. Two days later the cheque was dishonoured. On dishonour the correct entries are",
     "debit Ola ₦38,000, credit bank ₦38,000, with no entry for the discount", "debit Ola ₦40,000, credit bank ₦38,000, credit discount allowed ₦2,000", "debit bank ₦38,000, credit Ola ₦38,000, credit discount allowed ₦2,000", "debit bad debts ₦40,000, credit Ola ₦38,000, credit discount allowed ₦2,000",
     "B", "When the cheque bounces the full debt is reinstated: the discount previously allowed is cancelled and the bank entry reversed."),
    (T_CB, "Easy", "In a two-column cash book, the two money columns on each side are for",
     "cash and discount", "cash and bank", "bank and discount", "sales and purchases",
     "B", "A two-column cash book combines the cash account and the bank account; the discount columns make it a three-column cash book."),
    (T_CB, "Medium", "Cash withdrawn from the bank for office use is entered in the cash book as",
     "debit cash column, credit bank column", "debit bank column, credit cash column", "debit drawings, credit bank", "debit cash column only",
     "A", "Cash increases (debit cash column) and the bank balance falls (credit bank column); it is a contra entry."),
    (T_CB, "Medium", "The total of the discount allowed column of the cash book for a month is posted to the",
     "credit of discount allowed account", "debit of discount allowed account", "credit of each customer's account only", "debit of discount received account",
     "B", "The individual discounts are credited to the customers' accounts; the total is debited to discount allowed account to complete the double entry."),
    (T_CB, "Hard", "A cash book (bank column) shows receipts ₦620,000 and payments ₦655,000 for the month with an opening debit balance of ₦20,000. The closing balance is",
     "an overdraft of ₦15,000", "a bank balance of ₦15,000", "an overdraft of ₦35,000", "a bank balance of ₦55,000",
     "A", "20,000 + 620,000 − 655,000 = −15,000, that is a credit balance (overdraft) of ₦15,000."),
    # ---------------- Petty cash ----------------
    (T_PC, "Easy", "Under the imprest system, the petty cashier begins each period with",
     "a fixed sum of money", "whatever cash is left in the main cash book", "a bank overdraft", "the total of last month's expenses",
     "A", "A fixed float (imprest) is set; at the end of the period the cashier is reimbursed exactly what has been spent."),
    (T_PC, "Easy", "The main advantage of the petty cash book is that it",
     "records all cash sales of the business", "relieves the main cash book of many small payments", "replaces the bank statement", "eliminates the need for vouchers",
     "B", "Numerous small payments (postage, cleaning, transport) are kept out of the main cash book and summarised through analysis columns."),
    (T_PC, "Medium", "A petty cashier with an imprest of ₦20,000 spent ₦13,650 during the month and received ₦13,650 from the chief cashier. The amount in hand after reimbursement is",
     "₦13,650", "₦6,350", "₦20,000", "₦33,650",
     "C", "Reimbursement restores the float to the fixed imprest amount of ₦20,000.", "20000"),
    (T_PC, "Easy", "The analysis columns of a petty cash book are used to",
     "classify petty expenses under headings for posting to the ledger", "record all the cash receipts of the business for the month", "calculate the discount allowed to customers who pay promptly", "list the debtors of the business and the amounts they owe",
     "A", "Each payment is entered in the total column and again in an analysis column (e.g. postage, travelling); column totals are posted to the expense accounts."),
    (T_PC, "Medium", "A payment of ₦3,000 from petty cash to a supplier, Ade, for goods bought earlier on credit is entered in the",
     "postage column", "ledger accounts column", "travelling column", "stationery column",
     "B", "Payments to personal accounts do not fit any expense column and are analysed in the 'ledger' column for individual posting."),
    (T_PC, "Easy", "The petty cashier is normally reimbursed by",
     "the external auditor at the end of the audit", "the chief cashier from the main cash book", "customers who pay their accounts in cash", "the bank manager on receipt of a cheque",
     "B", "The chief cashier pays the petty cashier the amount spent, recorded as a credit in the main cash book and a debit in the petty cash book."),
    (T_PC, "Medium", "A petty cash float of ₦15,000 is found to contain vouchers totalling ₦11,200 and cash of ₦3,500. The shortage is",
     "₦300", "₦3,800", "₦11,200", "₦500",
     "A", "Vouchers plus cash should equal the imprest: 15,000 − (11,200 + 3,500) = ₦300 short.", "15000-11200-3500"),
    (T_PC, "Easy", "In the petty cash book, the reimbursement received from the chief cashier is entered",
     "on the receipts (debit) side", "in the total payments column", "in the postage analysis column", "on the credit side of the main cash book only",
     "A", "Money received by the petty cashier is debited in the petty cash book; the same amount is credited in the main cash book."),
    (T_PC, "Medium", "The person who signs a petty cash voucher as the recipient of money is called the",
     "chief cashier", "payee", "auditor", "drawer",
     "B", "The payee receives the money and signs the voucher; an authorising officer approves it."),
    (T_PC, "Hard", "A firm's imprest is ₦40,000. In June the petty cashier spent ₦28,400 and, in addition, received ₦2,000 from a staff member repaying a personal loan. The reimbursement required at the end of June is",
     "₦28,400", "₦26,400", "₦30,400", "₦40,000",
     "B", "Cash in hand = 40,000 − 28,400 + 2,000 = 13,600; to restore the imprest the cashier needs 40,000 − 13,600 = ₦26,400.", "40000-(40000-28400+2000)"),
    # ---------------- Bank reconciliation ----------------
    (T_BRS, "Easy", "A bank reconciliation statement is prepared to",
     "find the profit of the business for the month under review", "explain the difference between the cash book balance and the bank statement balance", "record the cash sales made during the month in the cash book", "correct the errors discovered in the sales ledger and purchases ledger",
     "B", "Timing differences and unrecorded items make the two balances differ; the statement reconciles one to the other."),
    (T_BRS, "Easy", "A cheque issued by a business that has not yet been paid by the bank is called",
     "an uncredited lodgement", "a dishonoured cheque", "an unpresented cheque", "a stale cheque",
     "C", "Unpresented (outstanding) cheques are recorded in the cash book but not yet on the bank statement."),
    (T_BRS, "Easy", "Which of the following appears in the bank statement before it is recorded in the cash book?",
     "an unpresented cheque", "an uncredited lodgement", "bank charges", "a cheque received from a customer today",
     "C", "Bank charges are deducted by the bank and are known to the business only when the statement arrives."),
    (T_BRS, "Medium", "Starting from a debit balance in the cash book of ₦120,000, unpresented cheques of ₦35,000 and uncredited lodgements of ₦20,000, the balance on the bank statement is",
     "₦135,000", "₦105,000", "₦175,000", "₦65,000",
     "A", "Bank statement balance = 120,000 + 35,000 (bank has not yet paid them) − 20,000 (bank has not yet credited them) = ₦135,000.", "120000+35000-20000"),
    (T_BRS, "Medium", "A standing order is",
     "an instruction to the bank to make regular fixed payments", "a cheque that has expired", "a request by a creditor to collect varying amounts", "a deposit made by a customer",
     "A", "A standing order is the customer's instruction to the bank to pay a fixed amount at regular intervals, e.g. rent or insurance."),
    (T_BRS, "Medium", "A direct debit differs from a standing order in that a direct debit",
     "is initiated by the bank without the customer's knowledge or consent", "allows the payee to collect varying amounts on the account holder's authority", "can only be used for the payment of salaries and wages to staff", "is a special form of cheque that cannot be crossed or endorsed",
     "B", "With a direct debit the account holder authorises the payee to collect amounts which may vary, e.g. utility bills."),
    (T_BRS, "Easy", "Which item is added to the cash book balance when updating it before reconciliation?",
     "bank charges", "a dishonoured cheque", "a standing order payment", "interest credited by the bank",
     "D", "Interest or dividends received directly by the bank increase the balance and must be debited in the cash book."),
    (T_BRS, "Medium", "A cheque received from a customer and recorded in the cash book was later returned unpaid by the bank. In the updated cash book this is",
     "debited to the bank column", "credited to the bank column", "ignored until the customer pays again", "entered in the discount column",
     "B", "The original debit for the receipt is cancelled by crediting the bank column and debiting the customer's account again."),
    (T_BRS, "Hard", "The bank statement of a business shows an overdraft of ₦42,000. There are unpresented cheques of ₦18,000 and uncredited lodgements of ₦30,000. The cash book balance is",
     "an overdraft of ₦30,000", "an overdraft of ₦54,000", "a debit balance of ₦6,000", "an overdraft of ₦6,000",
     "A", "From the bank overdraft (−42,000): deduct unpresented cheques (−18,000 → −60,000) and add uncredited lodgements (+30,000) = overdraft of ₦30,000."),
    (T_BRS, "Easy", "A cheque that is presented more than six months after its date and is refused by the bank is described as",
     "post-dated", "stale", "crossed", "open",
     "B", "Banks refuse to pay stale cheques, usually those older than six months."),
    (T_BRS, "Easy", "A cheque dated 30 November 2026 issued on 19 September 2026 is",
     "a stale cheque", "a crossed cheque", "a post-dated cheque", "a dishonoured cheque",
     "C", "A post-dated cheque bears a future date and cannot be paid by the bank before that date."),
    (T_BRS, "Medium", "Two parallel lines drawn across the face of a cheque mean that the cheque",
     "can be cashed over the counter by anyone", "must be paid into a bank account", "has been cancelled", "cannot be endorsed",
     "B", "A crossed cheque can only be paid through a bank account, which reduces the risk of loss or theft."),
    (T_BRS, "Medium", "Which of the following bank reconciliation items is an error rather than a timing difference?",
     "a cheque issued last week not yet presented", "a lodgement made this morning not yet on the statement", "a cheque for ₦14,500 entered in the cash book as ₦15,400", "a standing order paid by the bank",
     "C", "Transposition of figures is an error in the cash book; the other items arise only because of the timing of recording."),
    (T_BRS, "Easy", "The document sent by the bank to a customer showing all transactions on the account for a period is the",
     "pay-in slip", "bank statement", "cheque book", "bank draft",
     "B", "The bank statement is the bank's record of the customer's account and is compared with the cash book."),
    (T_BRS, "Medium", "In the bank's own books, a customer's current account balance of ₦80,000 is shown as a",
     "debit balance because the customer is a debtor of the bank", "credit balance because the bank owes the customer", "credit balance because it is an income of the bank", "debit balance because cash is an asset",
     "B", "Money deposited is owed by the bank to the customer, so the bank credits the customer's account; a bank overdraft is therefore a debit in the bank's books."),
    (T_BRS, "Hard", "A trader's cash book showed a bank balance of ₦64,000. The bank statement showed ₦71,300. The only differences were bank charges of ₦1,200, unpresented cheques of ₦12,000 and a lodgement not yet credited. The uncredited lodgement was",
     "₦3,500", "₦5,900", "₦4,700", "₦6,100",
     "A", "Adjusted cash book = 64,000 − 1,200 = 62,800. Statement 71,300 − unpresented 12,000 + lodgement = 62,800, so the lodgement = 62,800 − 59,300 = ₦3,500.", "62800-(71300-12000)"),
    (T_BRS, "Medium", "Automated transfers such as salaries paid directly into employees' accounts are examples of",
     "e-banking transactions", "petty cash payments", "trade discounts", "contra entries",
     "A", "Electronic banking allows credit transfers, interbank transfers and direct debits without cheques or cash."),
    (T_BRS, "Easy", "Which of the following is an instrument of bank transactions?",
     "a debit card", "a credit note", "a petty cash voucher", "a goods received note",
     "A", "Cheques, pay-in slips, debit and credit cards and internet transfers are instruments used to move money through a bank account."),
    # ---------------- Final accounts of a sole trader ----------------
    (T_FIN, "Easy", "The trading account is prepared to ascertain the",
     "net profit", "gross profit", "working capital", "cash balance",
     "B", "Gross profit = net sales − cost of goods sold; it is the result of the trading account."),
    (T_FIN, "Easy", "Carriage inwards is debited to the trading account because it",
     "is a selling and distribution expense", "forms part of the cost of purchases", "reduces the sales figure of the year", "is treated as a fixed asset of the business",
     "B", "The cost of bringing goods into the business is added to purchases; carriage outwards is a distribution expense in the profit and loss account."),
    (T_FIN, "Easy", "Which of the following is charged in the profit and loss account and not in the trading account?",
     "purchases", "returns inwards", "carriage outwards", "opening stock",
     "C", "Carriage outwards is a selling and distribution expense; the others are trading account items."),
    (T_FIN, "Medium", "Sales ₦900,000; opening stock ₦70,000; purchases ₦560,000; closing stock ₦90,000. The gross profit is",
     "₦340,000", "₦360,000", "₦380,000", "₦270,000",
     "B", "Cost of goods sold = 70,000 + 560,000 − 90,000 = 540,000; gross profit = 900,000 − 540,000 = ₦360,000.", "900000-(70000+560000-90000)"),
    (T_FIN, "Medium", "A trader's gross profit was ₦250,000. Expenses were rent ₦40,000, salaries ₦80,000 and depreciation ₦15,000; he also received commission of ₦10,000. His net profit was",
     "₦115,000", "₦105,000", "₦125,000", "₦135,000",
     "C", "Net profit = 250,000 + 10,000 − (40,000 + 80,000 + 15,000) = ₦125,000.", "250000+10000-135000"),
    (T_FIN, "Easy", "The goods a trader takes for his own use are",
     "debited to purchases and credited to drawings", "debited to drawings and credited to purchases", "debited to sales and credited to drawings", "ignored in the accounts",
     "B", "Goods withdrawn reduce purchases (credit) at cost and are charged to the owner as drawings (debit)."),
    (T_FIN, "Medium", "Which of the following is a current asset?",
     "a motor van", "goodwill", "stock of goods", "premises",
     "C", "Current assets are cash or items expected to turn into cash within a year: stock, debtors, prepayments, bank and cash."),
    (T_FIN, "Easy", "Working capital is calculated as",
     "fixed assets minus current liabilities", "current assets minus current liabilities", "total assets minus fixed assets", "capital minus drawings",
     "B", "Working capital (net current assets) measures the funds available for day-to-day operations."),
    (T_FIN, "Medium", "Debtors ₦80,000, stock ₦120,000, bank ₦30,000, creditors ₦90,000, bank loan repayable in 5 years ₦200,000. The working capital is",
     "₦140,000", "₦230,000", "₦40,000", "−₦60,000",
     "A", "Current assets 230,000 − current liabilities 90,000 = ₦140,000. The long-term loan is not a current liability.", "230000-90000"),
    (T_FIN, "Easy", "The balance sheet of a sole trader shows",
     "the profit earned during the year", "the assets, liabilities and capital at a particular date", "the cash receipts and payments for the year", "the purchases and sales of the year",
     "B", "A balance sheet is a statement of financial position at a point in time, not a record of flows during a period."),
    (T_FIN, "Medium", "Opening capital ₦600,000; net profit ₦180,000; drawings ₦70,000; additional capital introduced ₦50,000. The closing capital is",
     "₦760,000", "₦710,000", "₦660,000", "₦900,000",
     "A", "Closing capital = 600,000 + 180,000 + 50,000 − 70,000 = ₦760,000.", "600000+180000+50000-70000"),
    (T_FIN, "Medium", "Which of the following is a long-term liability?",
     "bank overdraft", "trade creditors", "a 10-year mortgage loan", "accrued wages",
     "C", "Long-term liabilities fall due after more than one year; the others are current liabilities."),
    (T_FIN, "Easy", "Returns inwards are deducted from",
     "purchases", "sales", "closing stock", "capital",
     "B", "Goods returned by customers reduce the sales figure, giving net sales (turnover)."),
    (T_FIN, "Medium", "Net sales ₦1,200,000 and gross profit ₦300,000. The gross profit percentage on sales (margin) is",
     "20%", "25%", "33⅓%", "30%",
     "B", "Margin = 300,000 ÷ 1,200,000 × 100 = 25%. Mark-up would be 300,000 ÷ 900,000 = 33⅓% on cost.", "300000/1200000*100"),
    (T_FIN, "Hard", "A trader marks up goods by 25% on cost. If his sales for the year were ₦750,000, the cost of goods sold was",
     "₦562,500", "₦600,000", "₦625,000", "₦500,000",
     "B", "Cost × 1.25 = 750,000, so cost = 750,000 ÷ 1.25 = ₦600,000; gross profit 150,000 = 20% margin.", "750000/1.25"),
    (T_FIN, "Medium", "Capital expenditure differs from revenue expenditure in that capital expenditure",
     "is charged in full to the profit and loss account of the year", "brings benefits over more than one accounting period", "is always paid in cash", "relates only to goods for resale",
     "B", "Capital expenditure acquires or improves fixed assets whose benefits last several years; revenue expenditure benefits the current period only."),
    (T_FIN, "Easy", "Which of the following is capital expenditure?",
     "repainting the shop front", "payment of wages", "legal fees on the purchase of land", "purchase of stationery",
     "C", "Costs incurred in acquiring a fixed asset, including legal fees, are added to the cost of the asset."),
    (T_FIN, "Medium", "Which of the following is revenue expenditure?",
     "installation cost of a new machine", "extension of a factory building", "annual servicing of a delivery van", "purchase of a second-hand lorry",
     "C", "Servicing maintains the asset in working order without increasing its capacity or life, so it is a revenue expense."),
    (T_FIN, "Medium", "Which of the following is a capital receipt for a sole trader?",
     "cash sales of goods made during the year", "commission received from a manufacturer", "proceeds from the sale of an old delivery van", "rent received from a tenant of the business",
     "C", "Money from disposing of a fixed asset is a capital receipt; income from normal operations is a revenue receipt."),
    (T_FIN, "Easy", "In the balance sheet of a sole trader, drawings are",
     "added to capital", "deducted from capital", "shown as a current liability", "shown as a fixed asset",
     "B", "Drawings reduce the owner's investment: closing capital = opening capital + profit − drawings."),
    (T_FIN, "Hard", "Cost of goods sold ₦480,000; opening stock ₦50,000; closing stock ₦70,000. The rate of stock turnover is",
     "8 times", "6.9 times", "9.6 times", "4 times",
     "A", "Average stock = (50,000 + 70,000) ÷ 2 = 60,000; turnover = 480,000 ÷ 60,000 = 8 times a year.", "480000/60000"),
    (T_FIN, "Medium", "Which of the following is an intangible asset?",
     "goodwill", "delivery van", "stock", "furniture",
     "A", "Goodwill, patents and trademarks have no physical form but have value to the business."),
    (T_FIN, "Medium", "Marshalling assets in the balance sheet in the order of permanence means",
     "listing cash first and land last", "listing land and buildings first and cash last", "listing assets alphabetically", "listing only fixed assets",
     "B", "In order of permanence the least liquid assets (land, buildings) come first; in order of liquidity cash comes first."),
    (T_FIN, "Hard", "Net profit ₦180,000; capital at the start of the year ₦900,000. The return on capital employed (opening capital) is",
     "18%", "20%", "25%", "16⅔%",
     "B", "180,000 ÷ 900,000 × 100 = 20%.", "180000/900000*100"),
    # ---------------- Adjustments ----------------
    (T_ADJ, "Easy", "Rent of ₦120,000 per year is payable quarterly in advance. By the year end only ₦90,000 had been paid. The amount charged to the profit and loss account is",
     "₦90,000", "₦120,000", "₦30,000", "₦150,000",
     "B", "The full year's rent of ₦120,000 is the expense for the period; the unpaid ₦30,000 is an accrual shown as a current liability.", "120000"),
    (T_ADJ, "Easy", "An accrued expense at the year end is shown in the balance sheet as a",
     "current asset", "current liability", "fixed asset", "deduction from capital",
     "B", "Expenses incurred but unpaid are owed by the business at the balance sheet date."),
    (T_ADJ, "Medium", "Insurance of ₦48,000 was paid on 1 October 2025 for the year to 30 September 2026. In the accounts to 31 December 2025 the prepaid insurance is",
     "₦12,000", "₦36,000", "₦48,000", "₦24,000",
     "B", "Only 3 months (Oct–Dec) belong to 2025: 48,000 × 3/12 = 12,000 expense; the remaining 9 months, ₦36,000, is a prepayment (current asset).", "48000*9/12"),
    (T_ADJ, "Easy", "A prepaid expense is treated in the balance sheet as a",
     "current liability", "long-term liability", "current asset", "fixed asset",
     "C", "A prepayment is a benefit already paid for but not yet received, so it is an asset."),
    (T_ADJ, "Medium", "Rent receivable for the year is ₦200,000; only ₦170,000 was received. In the balance sheet the ₦30,000 outstanding is",
     "an accrued income shown as a current asset", "an accrued expense shown as a current liability", "income received in advance", "deducted from capital",
     "A", "Income earned but not yet received is a debtor of the business (accrued income)."),
    (T_ADJ, "Medium", "A tenant paid ₦60,000 rent in December 2025 for January 2026. In the landlord's accounts for 2025 this amount is",
     "credited to the profit and loss account as rent income", "shown as income received in advance, a current liability", "treated as a prepaid expense", "added to capital",
     "B", "The landlord has received money for a service not yet provided; it is a liability until the period it relates to."),
    (T_ADJ, "Easy", "A debt that is definitely irrecoverable because the customer has died without assets is",
     "written off as a bad debt", "kept in debtors until further notice", "provided for as a doubtful debt", "transferred to creditors",
     "A", "Bad debts written off are debited to bad debts account and credited to the debtor's personal account."),
    (T_ADJ, "Medium", "Debtors at the year end were ₦400,000 and a provision for doubtful debts of 5% is to be maintained. The existing provision was ₦15,000. The charge to the profit and loss account is",
     "₦20,000", "₦5,000", "₦15,000", "₦35,000",
     "B", "Required provision = 5% of 400,000 = 20,000; only the increase of 20,000 − 15,000 = ₦5,000 is charged this year.", "400000*0.05-15000"),
    (T_ADJ, "Hard", "Debtors ₦250,000 after writing off bad debts of ₦10,000. The provision for doubtful debts is to be reduced from ₦18,000 to 4% of debtors. The effect on the profit and loss account is",
     "a debit of ₦8,000", "a credit of ₦8,000", "a credit of ₦10,000", "a debit of ₦2,000",
     "B", "New provision = 4% of 250,000 = 10,000; decrease of 18,000 − 10,000 = 8,000 is credited to profit and loss as a gain.", "18000-250000*0.04"),
    (T_ADJ, "Easy", "A provision for doubtful debts is shown in the balance sheet as",
     "a current liability", "a deduction from debtors", "an addition to debtors", "a fixed asset",
     "B", "Debtors are shown at cost less the provision, giving the amount expected to be collected."),
    (T_ADJ, "Medium", "A debt of ₦9,000 written off last year was recovered this year. The entry on recovery is",
     "debit bank, credit bad debts recovered", "debit bad debts, credit bank", "debit bank, credit debtors", "debit bad debts recovered, credit bank",
     "A", "The recovery is a gain credited to bad debts recovered account (or to bad debts account) and closed to profit and loss."),
    (T_ADJ, "Medium", "Wages for the last week of December 2025, ₦35,000, were paid on 3 January 2026. In preparing the accounts to 31 December 2025 the ₦35,000 is",
     "ignored because it was paid in 2026", "added to wages for 2025 and shown as an accrual", "deducted from wages for 2025", "shown as a prepayment",
     "B", "Under the accrual concept the cost belongs to 2025 when the work was done."),
    (T_ADJ, "Hard", "Electricity paid during 2025 was ₦95,000. There was an accrual of ₦8,000 at the start of the year and ₦11,000 at the end. The electricity expense for 2025 is",
     "₦98,000", "₦92,000", "₦114,000", "₦76,000",
     "A", "Expense = cash paid 95,000 − opening accrual 8,000 + closing accrual 11,000 = ₦98,000.", "95000-8000+11000"),
    (T_ADJ, "Hard", "Rates paid in 2025 totalled ₦60,000. Rates prepaid at 1 January 2025 were ₦5,000 and at 31 December 2025 ₦9,000. The rates charged to the 2025 profit and loss account is",
     "₦64,000", "₦56,000", "₦74,000", "₦46,000",
     "B", "Expense = paid 60,000 + opening prepayment 5,000 − closing prepayment 9,000 = ₦56,000.", "60000+5000-9000"),
    (T_ADJ, "Easy", "The purpose of making adjustments for accruals and prepayments at the year end is to",
     "increase the cash balance of the business", "match expenses with the period to which they relate", "reduce the amount of tax payable on the profit", "make the two sides of the trial balance agree",
     "B", "Adjustments apply the accrual (matching) concept so that profit reflects the period's true expenses and incomes."),
    (T_ADJ, "Medium", "A provision differs from a reserve in that a provision is",
     "an appropriation of profit made after the net profit has been found", "a charge against profit for a known liability or loss of uncertain amount", "always shown as a fixed asset in the balance sheet of the business", "created only by limited companies and never by sole traders",
     "B", "Provisions (for depreciation, doubtful debts) are charges in arriving at profit; reserves are set aside out of profit already earned."),
    (T_ADJ, "Medium", "Commission received in advance at the year end is shown in the balance sheet as",
     "a current asset", "a current liability", "part of capital", "a fixed asset",
     "B", "Income received before it is earned is owed back (in service) to the payer and is a liability at the balance sheet date."),
    (T_ADJ, "Hard", "Stock at the year end cost ₦85,000 but part of it, costing ₦15,000, is damaged and can be sold for only ₦9,000 after repairs costing ₦1,000. The closing stock value is",
     "₦85,000", "₦78,000", "₦79,000", "₦70,000",
     "B", "Damaged goods are valued at net realisable value 9,000 − 1,000 = 8,000 instead of cost 15,000; total = 70,000 + 8,000 = ₦78,000.", "70000+8000"),
    # ---------------- Depreciation and disposal ----------------
    (T_DEP, "Easy", "Depreciation is best described as the",
     "cash set aside each year in a special fund to replace a fixed asset", "fall in the market price of an asset between two balance sheet dates", "systematic allocation of the cost of a fixed asset over its useful life", "loss made when a fixed asset is sold for less than its original cost",
     "C", "Depreciation spreads the cost of a fixed asset over the periods that benefit from it, in line with the matching concept."),
    (T_DEP, "Easy", "Which of the following is not a cause of depreciation?",
     "wear and tear through use", "obsolescence through invention", "the passage of time", "a rise in market price",
     "D", "Depreciation arises from use, time, obsolescence and depletion; a rise in market value is the opposite of depreciation."),
    (T_DEP, "Medium", "A machine cost ₦800,000 with an estimated scrap value of ₦80,000 and a useful life of 8 years. The annual straight-line depreciation is",
     "₦100,000", "₦90,000", "₦110,000", "₦80,000",
     "B", "(800,000 − 80,000) ÷ 8 = ₦90,000 per year.", "(800000-80000)/8"),
    (T_DEP, "Medium", "A van costing ₦1,500,000 is depreciated at 20% per annum by the reducing-balance method. The depreciation for the second year is",
     "₦300,000", "₦240,000", "₦192,000", "₦270,000",
     "B", "Year 1: 20% of 1,500,000 = 300,000, leaving 1,200,000; year 2: 20% of 1,200,000 = ₦240,000.", "1500000*0.8*0.2"),
    (T_DEP, "Easy", "Under the reducing-balance method the depreciation charge",
     "is the same every year", "decreases every year", "increases every year", "is charged only in the year of purchase",
     "B", "A fixed percentage is applied to a falling net book value, so the annual charge falls year by year."),
    (T_DEP, "Medium", "The method of depreciation most suitable for a quarry or an oil well is the",
     "straight-line method", "reducing-balance method", "depletion unit method", "revaluation method",
     "C", "Wasting assets are depreciated according to the quantity extracted in each period."),
    (T_DEP, "Easy", "Net book value of a fixed asset is",
     "cost plus accumulated depreciation", "cost less accumulated depreciation", "market value less cost", "scrap value plus depreciation",
     "B", "Net book value (written-down value) is the amount at which an asset is carried in the balance sheet."),
    (T_DEP, "Medium", "An asset bought for ₦640,000 is depreciated at 25% per annum on the reducing balance. Its net book value after two years is",
     "₦320,000", "₦360,000", "₦480,000", "₦400,000",
     "B", "640,000 × 0.75 × 0.75 = ₦360,000.", "640000*0.75*0.75"),
    (T_DEP, "Easy", "The double entry for the annual depreciation charge is",
     "debit provision for depreciation, credit profit and loss", "debit profit and loss (depreciation expense), credit provision for depreciation", "debit fixed asset, credit provision for depreciation", "debit bank, credit fixed asset",
     "B", "The expense is charged to profit and loss and accumulated in the provision (accumulated depreciation) account, leaving the asset at cost."),
    (T_DEP, "Medium", "Loose tools are usually depreciated by the",
     "straight-line method", "sum-of-the-years'-digits method", "revaluation method", "annuity method",
     "C", "Small tools are revalued at the year end; the fall in value (plus purchases, less opening value) is the depreciation."),
    (T_DEP, "Hard", "A machine costing ₦900,000 has a life of 4 years and no scrap value. Using the sum-of-the-years'-digits method, the depreciation for the first year is",
     "₦225,000", "₦360,000", "₦270,000", "₦90,000",
     "B", "Sum of digits = 4 + 3 + 2 + 1 = 10; year 1 charge = 4/10 × 900,000 = ₦360,000.", "900000*4/10"),
    (T_DEP, "Medium", "An asset with a net book value of ₦150,000 is sold for ₦180,000. The disposal results in",
     "a loss of ₦30,000", "a profit of ₦30,000", "a profit of ₦180,000", "neither profit nor loss",
     "B", "Proceeds exceed the net book value by 180,000 − 150,000 = ₦30,000, credited to profit and loss as a profit on disposal."),
    (T_DEP, "Medium", "When a fixed asset is sold, the accumulated depreciation on it is transferred to the",
     "credit of the disposal account", "debit of the disposal account", "credit of the profit and loss account", "debit of the bank account",
     "A", "The disposal account is debited with cost and credited with accumulated depreciation and sale proceeds; the balance is the profit or loss."),
    (T_DEP, "Easy", "Land is not normally depreciated because it",
     "is too expensive", "has an unlimited useful life", "is a current asset", "cannot be sold",
     "B", "Land does not wear out or become obsolete, so its cost is not allocated over time (buildings on it are depreciated)."),
    (T_DEP, "Hard", "A machine bought on 1 July 2024 for ₦1,200,000 is depreciated at 10% per annum on cost, time-apportioned. The financial year ends on 31 December. The accumulated depreciation at 31 December 2025 is",
     "₦120,000", "₦240,000", "₦180,000", "₦60,000",
     "C", "2024: 6 months = 60,000; 2025: full year = 120,000; total ₦180,000.", "60000+120000"),
    (T_DEP, "Medium", "A provision for depreciation account is",
     "a real account with a debit balance", "a nominal account closed to trading account", "a credit balance representing depreciation charged to date", "a current liability",
     "C", "It accumulates the depreciation charged since purchase and is deducted from the asset's cost in the balance sheet."),
    (T_DEP, "Easy", "Which method charges more depreciation in the early years of an asset's life?",
     "straight-line", "reducing-balance", "revaluation", "depletion",
     "B", "Reducing balance front-loads the charge, which is appropriate when repairs rise as the asset ages, keeping total annual cost fairly even."),
    (T_DEP, "Hard", "A trader sold a van for ₦350,000. It had cost ₦1,000,000 and accumulated depreciation to the date of sale was ₦600,000. The profit or loss on disposal was",
     "profit of ₦50,000", "loss of ₦50,000", "loss of ₦250,000", "profit of ₦350,000",
     "B", "Net book value 1,000,000 − 600,000 = 400,000; proceeds 350,000; loss = ₦50,000."),
    (T_DEP, "Medium", "The cost of a fixed asset for depreciation purposes includes",
     "annual insurance of the asset", "the cost of installing the asset", "repairs during the first year", "fuel used by the asset",
     "B", "All costs of bringing the asset to working condition (carriage, installation, legal fees) are capitalised; running costs are expenses."),
    (T_DEP, "Medium", "Which of the following is depreciated by the depletion method?",
     "office furniture", "a timber concession", "computer software", "a delivery motorcycle",
     "B", "Natural resources such as timber, mines and quarries are written off according to the quantity extracted."),
]


def build():
    build_batch(
        S, "batch_035_accounting_round1a.json", "batch_035_accounting_round1a",
        "Principles of Accounts round 1 (part A): nature of accounting, concepts and conventions, source documents and books of original entry, accounting equation and ledger, trial balance, correction of errors and suspense account, ethics and regulatory bodies, cash book and discounts, petty cash, bank reconciliation, final accounts of a sole trader, year-end adjustments, depreciation and disposal - with a trial-balance extract, a bank reconciliation case, a petty cash table, an accounting-equation case and a machine-disposal case as data passages.",
        PASSAGES, PQ, Q,
    )


if __name__ == "__main__":
    build()
