"""Batch 049 - WAEC/NECO Economics, Paper 1 round 1.

WASSCE Economics Paper 1 is a 50-item objective paper (60 minutes).  This batch
covers the SSCE syllabus: basic concepts, economic systems, tools of analysis,
demand and supply, elasticity, consumer behaviour, production, business
organisations, market structures, distributive trade, population and labour,
money and inflation, financial institutions, public finance, international trade
and development planning - with Nigerian applications throughout.  Numeric
items (elasticity, means, opportunity cost, taxes, per-capita income) carry
independent `verify` computations.

    python3 scripts/build_content_batch49.py -> content/batch_049_waec_economics.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Economics"

T_BASIC = "Basic Economic Concepts"
T_SYS = "Economic Systems"
T_TOOLS = "Tools of Economic Analysis"
T_DEM = "Demand and Supply"
T_ELAS = "Elasticity"
T_CONS = "Theory of Consumer Behaviour"
T_PROD = "Theory of Production"
T_BUS = "Business Organisations"
T_MKT = "Market Structures"
T_DIST = "Distributive Trade"
T_POP = "Population and Labour"
T_MONEY = "Money and Inflation"
T_FIN = "Financial Institutions"
T_PUB = "Public Finance"
T_INT = "International Trade"
T_DEV = "Economic Development and Planning"

PASSAGES = []
PQ = []

Q = [
    # ------------------------------------------------------------ basic concepts
    (T_BASIC, "Easy", "Economics is described as a social science because it studies",
     "human behaviour in relation to scarce resources", "only the buying and selling of goods", "only government accounts", "plants and animals", "A",
     "It examines how people and societies choose among scarce alternatives.", None),
    (T_BASIC, "Easy", "Scarcity in economics means that resources are",
     "limited in supply relative to wants", "completely used up", "not available anywhere at all", "not wanted by any consumer", "A",
     "Human wants are unlimited while resources to satisfy them are limited.", None),
    (T_BASIC, "Medium", "A scale of preference is a list of a consumer's wants arranged in order of",
     "importance", "cost", "date of purchase", "availability", "A",
     "The most pressing want comes first, guiding rational choice.", None),
    (T_BASIC, "Medium", "A farmer gives up planting maize to plant rice on his land. The opportunity cost of the rice is the",
     "maize harvest forgone", "money spent on rice seed", "rent of the land", "price of rice in the market", "A",
     "Opportunity cost is the next best alternative sacrificed.", None),
    (T_BASIC, "Easy", "Choice arises in economics because resources are",
     "scarce while human wants are unlimited", "abundant in every country", "free to everyone that needs them", "equally distributed among people", "A",
     "Scarcity forces individuals and governments to choose.", None),
    (T_BASIC, "Hard", "A production possibility curve shows the",
     "combinations of goods its resources can produce", "the distribution of income among citizens", "the prices charged by sellers over time", "the population growth of the country", "A",
     "Points on the curve are efficient; inside it, resources are wasted.", None),
    (T_BASIC, "Hard", "A point inside the production possibility curve indicates that the economy is",
     "under-utilising its resources", "operating at full efficiency", "growing rapidly", "exporting more goods", "A",
     "Idle or misused resources leave output below the attainable maximum.", None),
    (T_BASIC, "Easy", "The basic economic problems of every society include what to produce, how to produce and",
     "for whom to produce", "when to sleep", "who to vote for", "where to relax", "A",
     "Every economy, rich or poor, faces these three fundamental questions.", None),
    (T_BASIC, "Medium", "Labour as a factor of production refers to",
     "human physical and mental effort in production", "the machines installed in a factory", "the money deposited in a bank account", "the raw materials kept in the store", "A",
     "Labour covers both manual and intellectual human contributions.", None),
    (T_BASIC, "Medium", "Which factor of production is rewarded with interest?",
     "Capital", "Labour", "Land", "Entrepreneurship", "A",
     "Land earns rent, labour earns wages, capital earns interest, enterprise earns profit.", None),
    (T_BASIC, "Easy", "The reward for entrepreneurship as a factor of production is",
     "profit", "rent", "wages", "interest", "A",
     "The entrepreneur bears risk and is rewarded with whatever profit remains.", None),
    (T_BASIC, "Medium", "The naira notes and coins used in Nigeria are examples of money functioning as",
     "a medium of exchange", "a store of value only", "a commodity", "a factor of production", "A",
     "Notes and coins are generally accepted in payment for goods and services.", None),

    # --------------------------------------------------------- economic systems
    (T_SYS, "Medium", "In a capitalist economy, the means of production are owned and controlled largely by",
     "private individuals and firms", "the government", "traditional rulers", "foreign donors", "A",
     "Private ownership and the profit motive drive resource allocation in capitalism.", None),
    (T_SYS, "Medium", "In a socialist economy, major decisions on what to produce are taken by the",
     "central government or planning authority", "market forces of demand and supply", "private investors", "religious bodies", "A",
     "The state directs production towards planned social objectives.", None),
    (T_SYS, "Easy", "Nigeria's present economy, where both government and private individuals operate businesses, is best described as",
     "a mixed economy", "a pure capitalist economy", "a socialist economy", "a subsistence economy", "A",
     "Public corporations co-exist with private enterprise in a mixed system.", None),
    (T_SYS, "Medium", "A subsistence economy is one in which production is mainly for",
     "the family's own consumption", "export markets", "government use only", "large factories", "A",
     "Output is produced to meet the producer's immediate needs, not for sale.", None),
    (T_SYS, "Hard", "A major disadvantage of a purely capitalist system is that it can lead to",
     "great inequality in the distribution of income", "shortage of consumer goods always", "excessive government control", "abolition of private property", "A",
     "Unrestricted markets concentrate wealth, which is why most nations mix systems.", None),
    (T_SYS, "Hard", "Economic questions in a traditional economy are settled mainly by",
     "customs and traditions of the people", "elected parliamentarians", "computer models", "the price mechanism alone", "A",
     "Ancestral practice governs what, how and for whom to produce.", None),

    # --------------------------------------------------------------------- tools
    (T_TOOLS, "Easy", "The mean of the incomes ₦20,000, ₦30,000, ₦40,000, ₦50,000 and ₦60,000 is",
     "₦40,000", "₦30,000", "₦45,000", "₦35,000", "A",
     "Total income ₦200,000 divided by five values gives ₦40,000.", "(20000+30000+40000+50000+60000)/5"),
    (T_TOOLS, "Medium", "The median of the numbers 3, 9, 4, 11, 7, 2 and 6 is",
     "6", "7", "5", "4", "A",
     "Arranged in order (2, 3, 4, 6, 7, 9, 11) the middle value is 6.", "sorted([3,9,4,11,7,2,6])[3]"),
    (T_TOOLS, "Medium", "In a distribution, the value that occurs most frequently is the",
     "mode", "mean", "median", "range", "A",
     "The mode is simply the most common observation.", None),
    (T_TOOLS, "Easy", "A graph showing the relationship between two economic variables over time is best drawn using a",
     "line graph", "pie chart", "pictogram", "population pyramid", "A",
     "Line graphs display trends and relationships between variables clearly.", None),
    (T_TOOLS, "Medium", "A pie chart is most suitable for showing",
     "the proportion of a total contributed by parts", "a time trend", "the correlation of two variables", "a frequency distribution", "A",
     "Each sector's angle is proportional to the share of that component.", None),
    (T_TOOLS, "Hard", "The range of the values 15, 22, 8, 31 and 19 is",
     "23", "8", "31", "15", "A",
     "Range is the difference between the largest and smallest: 31 − 8 = 23.", "max([15,22,8,31,19])-min([15,22,8,31,19])"),
    (T_TOOLS, "Medium", "A histogram is used to display the distribution of data that is",
     "grouped into class intervals", "in percentages only", "of a single value", "qualitative only", "A",
     "Adjacent bars touch because the classes are continuous.", None),

    # ------------------------------------------------------------ demand/supply
    (T_DEM, "Easy", "The law of demand states that, other things being equal, the higher the price of a commodity, the",
     "lower the quantity demanded", "higher the quantity demanded", "lower the demand curve shifts", "greater the supply", "A",
     "Price and quantity demanded move in opposite directions along the curve.", None),
    (T_DEM, "Easy", "The law of supply states that the higher the price of a commodity, the",
     "greater the quantity supplied", "smaller the quantity supplied", "less the producer earns", "lower the demand", "A",
     "Higher prices make production more profitable, encouraging more output.", None),
    (T_DEM, "Medium", "If the price of a commodity falls and nothing else changes, there will be",
     "an extension of demand along the curve", "an outward shift of the demand curve", "a contraction of demand", "no change at all", "A",
     "Movement along the curve is caused only by the good's own price.", None),
    (T_DEM, "Medium", "A rise in consumers' incomes, holding prices constant, will cause the demand curve for a normal good to",
     "shift to the right", "shift to the left", "remain stationary", "become vertical", "A",
     "Better incomes raise purchases at every price, shifting the whole curve.", None),
    (T_DEM, "Medium", "If the price of tea rises sharply, the demand for coffee, a substitute, will",
     "increase", "decrease", "remain constant", "fall to zero", "A",
     "Consumers switch from the dearer tea to the relatively cheaper coffee.", None),
    (T_DEM, "Hard", "Two goods are complements if a fall in the price of one leads to",
     "an increase in the demand for the other", "a decrease in the demand for the other", "no change in the other", "an increase in the supply of the other", "A",
     "Complements like cars and petrol are consumed together.", None),
    (T_DEM, "Medium", "The market equilibrium price is the price at which",
     "quantity demanded equals quantity supplied", "demand greatly exceeds supply", "supply greatly exceeds demand", "government fixes all the prices", "A",
     "At equilibrium the market clears with neither shortage nor surplus.", None),
    (T_DEM, "Hard", "If the market price is fixed below the equilibrium price, the immediate result is a",
     "shortage of the commodity", "surplus of the commodity", "perfect market clearing", "fall in demand", "A",
     "Quantity demanded exceeds quantity supplied, creating queues and black markets.", None),
    (T_DEM, "Hard", "If the market price is fixed above the equilibrium price, the result is a",
     "surplus of the commodity", "shortage of the commodity", "zero supply", "higher demand", "A",
     "Producers offer more than buyers wish to purchase at that price.", None),
    (T_DEM, "Medium", "A decrease in the cost of producing garri, other things equal, will",
     "shift the supply curve of garri to the right", "shift the supply curve to the left", "shift the demand curve right", "raise the equilibrium price", "A",
     "Cheaper production makes more output profitable at every price.", None),
    (T_DEM, "Easy", "The demand curve normally slopes downward from left to right because of",
     "diminishing marginal utility", "increasing returns", "constant costs", "government policy", "A",
     "Extra units give less satisfaction, so buyers only purchase more at lower prices.", None),
    (T_DEM, "Hard", "Effective demand refers to desire for a commodity backed by the",
     "ability and willingness to pay", "permission of the seller", "availability of credit always", "advertisements seen", "A",
     "Mere want without purchasing power is not demand in economics.", None),

    # ----------------------------------------------------------------- elasticity
    (T_ELAS, "Easy", "The price elasticity of demand measures the responsiveness of quantity demanded to changes in",
     "price", "income", "taste", "population", "A",
     "It is the percentage change in quantity demanded divided by the percentage change in price.", None),
    (T_ELAS, "Medium", "When the percentage change in quantity demanded is 10% following a 5% change in price, the price elasticity of demand is",
     "2", "0.5", "15", "5", "A",
     "Dividing the percentage change in demand by the percentage change in price gives 10 ÷ 5 = 2.", "10/5"),
    (T_ELAS, "Medium", "When demand is price inelastic, the elasticity coefficient is",
     "less than 1", "greater than 1", "equal to 1", "equal to infinity", "A",
     "Quantity responds less than proportionately to the price change.", None),
    (T_ELAS, "Easy", "Demand for table salt is generally price inelastic because salt is",
     "a necessity with very few substitutes", "a luxury good for rich families", "a very expensive table item", "a commodity rarely consumed", "A",
     "Households buy roughly the same amount whatever the price does.", None),
    (T_ELAS, "Hard", "The price of a commodity rises from ₦10 to ₦12 and its quantity demanded falls from 40 units to 30 units. The price elasticity of demand is",
     "1.25", "0.8", "2", "0.4", "A",
     "%ΔQ = 25%, %ΔP = 20%, so elasticity = 25 ÷ 20 = 1.25.", "(10/40)/((12-10)/10)"),
    (T_ELAS, "Hard", "If a 20% rise in income increases the quantity demanded of a good by 10%, the income elasticity of demand is",
     "0.5", "2", "0.2", "1", "A",
     "Elasticity = percentage change in demand ÷ percentage change in income = 10 ÷ 20 = 0.5.", "10/20"),
    (T_ELAS, "Hard", "For an inferior good, the income elasticity of demand is",
     "negative", "positive", "zero", "infinite", "A",
     "Rising incomes reduce demand for inferior goods like low-grade garri.", None),
    (T_ELAS, "Medium", "Demand is said to be perfectly inelastic when the demand curve is",
     "vertical", "horizontal", "downward sloping", "upward sloping", "A",
     "Quantity demanded is fixed whatever the price, so elasticity is zero.", None),
    (T_ELAS, "Medium", "If demand is elastic, a small rise in price will cause total revenue to",
     "fall", "rise", "stay constant", "double", "A",
     "The percentage drop in quantity outweighs the percentage rise in price.", None),
    (T_ELAS, "Hard", "Cross elasticity of demand between two goods is positive when the goods are",
     "substitutes", "complements", "unrelated", "inferior", "A",
     "A price rise for one substitute pushes demand towards the other.", None),

    # ------------------------------------------------------- consumer behaviour
    (T_CONS, "Easy", "Utility in economics means the",
     "satisfaction derived from consuming a good", "the price charged for the good", "the cost of producing the good", "the usefulness of money holdings", "A",
     "Utility is the satisfaction, whether or not the good is objectively useful.", None),
    (T_CONS, "Medium", "The law of diminishing marginal utility states that as more units of a commodity are consumed, the extra satisfaction from each additional unit",
     "falls", "rises", "stays constant", "becomes negative immediately", "A",
     "The first plate of food delights; the fifth may add little.", None),
    (T_CONS, "Medium", "Total utility is at a maximum when marginal utility is",
     "zero", "at its maximum", "negative", "rising", "A",
     "Once an extra unit adds nothing, total satisfaction cannot rise further.", None),
    (T_CONS, "Hard", "A rational consumer maximises satisfaction by equating the",
     "marginal utility per naira spent on all goods", "the total utilities of the goods", "the market prices of all the goods", "his total income with his savings", "A",
     "Shifting spending until each naira buys equal extra satisfaction removes any incentive to swap.", None),
    (T_CONS, "Easy", "A consumer's demand curve can be derived from the",
     "marginal utility curve", "supply curve", "cost curve of the firm", "production function", "A",
     "Consumption stops where marginal utility equals price, tracing the demand curve.", None),
    (T_CONS, "Hard", "Consumer surplus is the difference between what a consumer is",
     "willing to pay and what he actually pays", "charged and what he earns", "owes and what he saves", "demands and what is supplied", "A",
     "Buying below the maximum acceptable price leaves the buyer better off.", None),

    # ---------------------------------------------------------------- production
    (T_PROD, "Easy", "Production in economics is complete when goods and services reach the",
     "final consumer", "warehouse", "factory", "wholesaler", "A",
     "Production includes distribution, right up to final satisfaction of wants.", None),
    (T_PROD, "Medium", "The law of diminishing returns states that as more units of a variable factor are combined with fixed factors, the marginal product eventually",
     "falls", "rises continuously", "stays constant", "becomes infinite", "A",
     "Successive workers add less and less output in a fixed space.", None),
    (T_PROD, "Medium", "Which of these is a fixed factor of production on a farm?",
     "The size of the land", "Fertiliser applied", "Day labourers hired", "Seeds planted", "A",
     "Land cannot be varied in the short run, unlike labour and materials.", None),
    (T_PROD, "Hard", "Average product is calculated as total product divided by the",
     "quantity of the variable input", "price of output", "number of consumers", "fixed costs", "A",
     "It shows output per unit of the variable factor employed.", None),
    (T_PROD, "Medium", "Economies of scale are the cost advantages a firm enjoys as its",
     "scale of output expands", "workforce ages", "prices fall", "taxes rise", "A",
     "Bulk buying, specialist machines and spreading overheads cut unit costs.", None),
    (T_PROD, "Hard", "Diseconomies of scale set in when a firm becomes so large that",
     "unit costs begin to rise", "profits become zero", "workers are few", "machines stop", "A",
     "Management bottlenecks and coordination problems eventually raise average costs.", None),
    (T_PROD, "Easy", "The short run in economics is the period during which",
     "some factors of production are fixed", "all factors can be varied", "prices never change", "profits are highest", "A",
     "In the long run every factor, including plant size, can change.", None),
    (T_PROD, "Hard", "When total product is rising at a decreasing rate, marginal product is",
     "positive but falling", "negative", "zero", "rising", "A",
     "Output still grows with each extra worker, but by smaller steps.", None),

    # -------------------------------------------------------- business organisations
    (T_BUS, "Easy", "The owner of a sole proprietorship has",
     "unlimited liability for the business debts", "liability limited to his investment", "no liability at all", "liability shared with the state", "A",
     "Personal assets can be seized to settle business debts.", None),
    (T_BUS, "Medium", "A major advantage of the sole proprietorship is that decisions are",
     "taken quickly by one person", "taken by a large board", "always taken by government", "delayed by law", "A",
     "No partners or directors need consulting before acting.", None),
    (T_BUS, "Medium", "A partnership business in Nigeria normally has between two and",
     "twenty partners", "fifty partners", "five partners", "a hundred partners", "A",
     "Beyond twenty members the company must be incorporated under company law.", None),
    (T_BUS, "Medium", "In a public limited company, ownership is divided into",
     "shares that are sold freely to the public", "family holdings that cannot be sold", "bonds issued by the government only", "dues paid by co-operative members", "A",
     "Shares are quoted on the stock exchange and transferable to anyone.", None),
    (T_BUS, "Easy", "The document that sets out the rules governing the internal affairs of a company is the",
     "articles of association", "prospectus", "certificate of incorporation", "memorandum of association", "A",
     "The articles regulate meetings, directors' powers and shareholders' rights.", None),
    (T_BUS, "Medium", "A co-operative society is owned and controlled by its",
     "members who use its services", "paid directors", "bankers", "largest customer", "A",
     "Surpluses are shared among members in proportion to their patronage.", None),
    (T_BUS, "Hard", "Public corporations are established to provide essential services mainly because",
     "private firms find them unprofitable or too costly", "the government dislikes all businesses", "they are always very cheap to run", "they pay no wages to any worker", "A",
     "Services like water and railways need huge capital with slow returns.", None),
    (T_BUS, "Hard", "One disadvantage of public corporations is that they often",
     "suffer from bureaucratic delays in decisions", "raise their capital far too easily", "respond far too fast to consumers", "make excessive profits every year", "A",
     "Civil-service style management can blunt commercial initiative.", None),
    (T_BUS, "Easy", "Which business organisation has legal personality separate from its owners?",
     "A limited liability company", "A sole proprietorship", "An ordinary partnership", "A family trade", "A",
     "The company can sue, be sued and own property in its own name.", None),

    # ------------------------------------------------------------ market structures
    (T_MKT, "Easy", "A perfect market is one in which",
     "buyers and sellers have perfect knowledge", "only one single seller exists", "government fixes all the prices", "goods are always quite different", "A",
     "Uniform products, many traders and free entry make price uniform.", None),
    (T_MKT, "Medium", "A monopolist is a seller who",
     "controls the whole supply without close substitutes", "sells alongside very many rivals", "sells to government departments only", "cannot influence the market price", "A",
     "Entry barriers keep competitors out, giving the monopolist pricing power.", None),
    (T_MKT, "Medium", "Under perfect competition, an individual firm is a",
     "price taker", "price maker", "price fixer with government", "monopolist", "A",
     "Its output is too small a share of the market to sway price.", None),
    (T_MKT, "Hard", "Which is a feature of monopolistic competition?",
     "Many sellers of slightly differentiated products", "One seller of a single unique product", "Two giant sellers in the whole market", "No advertising by any firm at all", "A",
     "Product differentiation, e.g. brands of bread, gives each firm limited price control.", None),
    (T_MKT, "Hard", "An oligopolistic market is one with",
     "a few large firms dominating the industry", "thousands of very tiny firms", "only consumers without sellers", "no barriers to entering the market", "A",
     "Cement and telecommunications in Nigeria are classic oligopolies.", None),
    (T_MKT, "Hard", "Price discrimination is possible only when the seller can",
     "separate buyers into markets of different elasticity", "sell only one grade of the goods", "avoid every transport cost involved", "obey one uniform price law", "A",
     "Charging different prices in separable markets raises total revenue.", None),
    (T_MKT, "Medium", "A cartel formed by producers aims to",
     "fix prices and output for joint benefit", "increase competition among members", "cut all members' prices", "welcome every new producer", "A",
     "OPEC is the best-known example among oil-producing nations.", None),

    # --------------------------------------------------------------- distributive trade
    (T_DIST, "Easy", "The chain of distribution moves goods from the producer to the",
     "final consumer", "bank", "port", "factory", "A",
     "Middlemen like wholesalers and retailers complete the channel.", None),
    (T_DIST, "Medium", "A wholesaler buys goods mainly from the",
     "producer and sells in bulk to retailers", "consumer and sells to producers", "retailer and sells to banks", "government only", "A",
     "The wholesaler is the link between manufacturer and the retail trade.", None),
    (T_DIST, "Medium", "One function of a retailer is to",
     "break bulk and sell in small units to consumers", "manufacture new products in factories", "fix the exchange rates of the naira", "insure the wholesalers against loss", "A",
     "Retailers stock convenient pack sizes near the consumer.", None),
    (T_DIST, "Hard", "A producer selling directly through his own shops removes the",
     "middlemen from the chain", "consumers from the market", "need for money", "cost of transport", "A",
     "Direct selling shortens the channel and keeps the middlemen's margin.", None),
    (T_DIST, "Medium", "Which is an argument AGAINST middlemen?",
     "They raise the final price to consumers", "They store goods until needed", "They break bulk for retailers", "They inform producers about demand", "A",
     "Each layer of the chain takes a margin that the consumer finally pays.", None),

    # -------------------------------------------------------- population/labour
    (T_POP, "Easy", "A census is best described as the",
     "official count of a country's population", "election of the country's leaders", "registration of businesses and firms", "taxation of personal incomes", "A",
     "It records people, their ages, sex, occupation and residence at a set date.", None),
    (T_POP, "Medium", "The labour force of a country consists of people who are",
     "able and willing to work", "under fifteen years old", "retired from work", "in school full-time", "A",
     "It includes the employed plus the unemployed who are seeking work.", None),
    (T_POP, "Hard", "A country's unemployment rate is the number of unemployed divided by the",
     "total labour force", "total population", "number of children", "number of firms", "A",
     "Only the active labour force forms the base of the ratio.", None),
    (T_POP, "Hard", "In a labour force of 80 million people, 4 million are unemployed. The unemployment rate is",
     "5%", "0.5%", "20%", "4%", "A",
     "Rate = 4 ÷ 80 × 100 = 5%.", "4/80*100"),
    (T_POP, "Medium", "Frictional unemployment occurs when workers are",
     "between jobs while searching for new ones", "replaced by machines permanently", "too old to work", "unskilled forever", "A",
     "Even a healthy economy has people changing jobs at any moment.", None),
    (T_POP, "Hard", "Unemployment caused by a fall in total demand for goods during a recession is called",
     "cyclical unemployment", "frictional unemployment", "structural unemployment", "seasonal unemployment", "A",
     "When spending collapses economy-wide, workers are laid off across industries.", None),
    (T_POP, "Medium", "The mobility of labour refers to the ease with which workers can",
     "move between jobs and places", "join trade unions", "increase their wages", "retire early", "A",
     "Both geographical and occupational mobility matter for the labour market.", None),
    (T_POP, "Medium", "One reason trade unions bargain collectively is to",
     "improve members' wages and working conditions", "reduce the workers' productivity", "raise the firms' profits directly", "fix the exchange rates", "A",
     "One strong voice negotiates better than isolated individuals.", None),
    (T_POP, "Hard", "An increase in population that outpaces real output causes",
     "a fall in per capita income", "a rise in per capita income", "zero population growth", "automatic development", "A",
     "Income shared among more people leaves less per head.", None),

    # ------------------------------------------------------------- money/inflation
    (T_MONEY, "Easy", "Inflation is best defined as a",
     "persistent rise in the general price level", "one-off rise in a single price", "fall in total government spending", "rise in the volume of exports", "A",
     "Sustained increases across the economy erode money's purchasing power.", None),
    (T_MONEY, "Medium", "Demand-pull inflation occurs when aggregate demand",
     "exceeds the available supply of goods", "falls below the supply of goods", "exactly equals the supply", "reduced to zero completely", "A",
     "Too much money chasing too few goods pulls prices upward.", None),
    (T_MONEY, "Medium", "Cost-push inflation is caused mainly by",
     "rising costs of production", "falling wages", "cheaper fuel", "lower taxes", "A",
     "Higher input costs are passed on as higher prices.", None),
    (T_MONEY, "Easy", "Money serves as a store of value when it",
     "holds its worth for spending in future", "buys goods today and never later", "changes its colour over time", "earns no interest whatever ever", "A",
     "Because it keeps value, people can save it for later purchases.", None),
    (T_MONEY, "Medium", "A major disadvantage of inflation is that it",
     "reduces the purchasing power of savings", "raises real wages at all times", "increases exports automatically", "makes money scarce to banks", "A",
     "Fixed incomes and money savings buy progressively less.", None),
    (T_MONEY, "Medium", "Which is a measure the Central Bank uses to control inflation?",
     "Raising the bank rate", "Printing more currency notes", "Increasing government spending", "Reducing taxation", "A",
     "A higher bank rate tightens credit and cools spending in the economy.", None),
    (T_MONEY, "Hard", "Deflation, a persistent fall in the general price level, typically causes",
     "rising unemployment as firms cut output", "an immediate boom in production", "unlimited credit for all borrowers", "higher imports at all times", "A",
     "Falling prices squeeze profits, so firms lay off workers.", None),
    (T_MONEY, "Medium", "The essential quality that makes anything acceptable as money is that it must be",
     "generally acceptable in exchange", "made of gold and silver only", "issued by foreign governments", "very heavy to carry about", "A",
     "Acceptability, not the material, is the defining feature of money.", None),
    (T_MONEY, "Hard", "Hyperinflation can lead to a situation where people",
     "lose confidence in the currency and barter", "save more and more naira notes", "lend money at very low interest", "import more and more goods", "A",
     "When prices change daily, money can no longer measure value reliably.", None),

    # -------------------------------------------------------- financial institutions
    (T_FIN, "Easy", "The Central Bank of Nigeria is the",
     "apex bank that issues the national currency", "largest trading company in Lagos", "bank reserved for primary pupils", "agent of foreign firms only", "A",
     "The CBN issues notes, supervises banks and implements monetary policy.", None),
    (T_FIN, "Medium", "One function of commercial banks is to",
     "accept deposits and grant loans", "print the national currency notes", "fix the national budget", "build roads and bridges", "A",
     "Banks mobilise savings and create credit for investors.", None),
    (T_FIN, "Hard", "The lender of last resort to commercial banks in Nigeria is the",
     "Central Bank", "World Bank", "biggest savings club", "stock exchange", "A",
     "When banks are short of funds, the CBN lends to keep the system stable.", None),
    (T_FIN, "Medium", "Monetary policy is concerned with controlling the",
     "supply of money and credit in the economy", "salaries paid to civil servants", "control of the border posts", "conduct of national elections", "A",
     "The CBN uses bank rate, reserves and open-market operations.", None),
    (T_FIN, "Hard", "Treasury bills are financial instruments traded in the",
     "money market", "commodity market", "labour market", "foreign exchange black market", "A",
     "Short-term government debt changes hands in the money market.", None),
    (T_FIN, "Hard", "Long-term funds for company expansion are raised mainly in the",
     "capital market", "money market", "mortgage of houses only", "petrol station", "A",
     "Shares and long bonds trade in the capital market, e.g. the Nigerian Exchange.", None),
    (T_FIN, "Medium", "The Nigerian Security Printing and Minting Company is responsible for",
     "printing the nation's currency", "issuing driving licences", "insuring banks", "teaching economics", "A",
     "It prints notes and mints coins on behalf of the Central Bank.", None),
    (T_FIN, "Medium", "A savings account differs from a current account because the savings account",
     "earns interest but rarely uses cheques", "is opened by companies only", "is used mainly to pay taxes", "requires a very huge balance", "A",
     "Current accounts offer cheque facilities but traditionally no interest.", None),

    # ------------------------------------------------------------- public finance
    (T_PUB, "Easy", "A tax is a compulsory payment to government for which there is",
     "no direct quid pro quo", "a direct service rendered", "a share certificate issued", "an interest coupon", "A",
     "Taxes finance public services without a specific price tag per payer.", None),
    (T_PUB, "Medium", "Which of these is a direct tax?",
     "Personal income tax", "Value Added Tax", "Import duty", "Excise duty", "A",
     "Direct taxes are levied on income or wealth and cannot be shifted easily.", None),
    (T_PUB, "Medium", "Value Added Tax is classified as an indirect tax because it is",
     "levied on goods and services and shifted onward", "paid only by the limited companies", "charged directly on workers' salaries", "refunded to every one of the payers", "A",
     "VAT, at 7.5% in Nigeria, is built into prices paid by final consumers.", None),
    (T_PUB, "Medium", "A progressive tax system is one in which the tax rate rises as income",
     "increases", "decreases", "stays fixed", "disappears", "A",
     "The rich pay a larger fraction, narrowing income inequality.", None),
    (T_PUB, "Hard", "A man pays 10% tax on a taxable income of ₦200,000. His tax bill is",
     "₦20,000", "₦2,000", "₦180,000", "₦200,000", "A",
     "Tax = 10% of 200,000 = ₦20,000.", "200000*0.1"),
    (T_PUB, "Hard", "A regressive tax takes a larger fraction of income from",
     "low-income earners than high-income earners", "high-income earners than the poor", "limited companies alone", "nobody in the country at all", "A",
     "A flat levy like a poll tax bites hardest the smallest incomes.", None),
    (T_PUB, "Medium", "A budget deficit occurs when government expenditure exceeds",
     "government revenue", "last year's deficit", "the national debt", "state revenue", "A",
     "Deficits are financed by borrowing, adding to public debt.", None),
    (T_PUB, "Hard", "A balanced government budget means expenditure is",
     "equal to revenue", "above revenue", "below revenue", "spent on farms only", "A",
     "Neither surplus nor deficit appears in the accounts.", None),
    (T_PUB, "Medium", "The fiscal policy of a government concerns taxation and",
     "government expenditure", "money supply", "border control", "court judgements", "A",
     "Budgets and tax changes form the levers of fiscal policy.", None),
    (T_PUB, "Hard", "Internal debts are owed by a government to",
     "creditors within the country", "foreign governments only", "the United Nations", "tourists", "A",
     "Treasury bills held by residents and local banks are internal debt.", None),

    # -------------------------------------------------------- international trade
    (T_INT, "Easy", "International trade exists because countries differ in their",
     "resource endowments and production costs", "national flags and anthems", "languages and dialects only", "weather and climate alone", "A",
     "Nations specialise where they are comparatively cheapest and exchange.", None),
    (T_INT, "Medium", "The principle of comparative advantage advises a country to produce goods in which it has the",
     "lowest opportunity cost", "largest factories", "biggest population", "most minerals always", "A",
     "Relative efficiency, not absolute superiority, decides the pattern of trade.", None),
    (T_INT, "Medium", "The visible balance of trade records the difference between a country's exports and imports of",
     "physical goods", "services", "gifts", "loans", "A",
     "Oil sales and machinery purchases are visible trade items.", None),
    (T_INT, "Hard", "The balance of payments is a record of a country's transactions with the rest of the world in goods, services and",
     "capital flows", "school enrolments", "elections", "football matches", "A",
     "The current and capital accounts together give the overall position.", None),
    (T_INT, "Medium", "A tariff on imported goods is levied mainly to",
     "protect local industries and raise revenue", "punish the consumers of imports", "increase the inflow of imports", "empty goods from the ports", "A",
     "Making imports dearer shifts demand towards home-made substitutes.", None),
    (T_INT, "Hard", "Devaluation of a country's currency makes its exports",
     "cheaper to foreign buyers", "more expensive to foreign buyers", "illegal", "tax-free", "A",
     "A cheaper naira prices Nigerian goods lower in foreign currency terms.", None),
    (T_INT, "Medium", "An embargo on trade means a",
     "complete ban on trade in a good or country", "reduction of tariffs on imports", "form of subsidy to exporters", "type of insurance for traders", "A",
     "Embargoes cut off the trade flow entirely.", None),
    (T_INT, "Medium", "Nigeria belongs to OPEC, an organisation whose main objective is to",
     "co-ordinate petroleum policies of members", "print dollars for member countries", "run all the African airlines", "manage world fishing rights", "A",
     "OPEC stabilises the oil market through quota agreements.", None),
    (T_INT, "Hard", "The Economic Community of West African States (ECOWAS) was founded in 1975 primarily to promote",
     "economic integration in West Africa", "military rule in the sub-region", "single-party systems of government", "the return of colonialism", "A",
     "Free movement and a common market for member states are its goals.", None),
    (T_INT, "Medium", "A major problem of Nigeria's reliance on crude oil exports is that revenue fluctuates with",
     "world oil prices", "the school calendar", "national awards", "local festivals", "A",
     "When prices crash, government revenue and foreign exchange earnings fall.", None),
    (T_INT, "Hard", "Import substitution industrialisation aims to",
     "produce at home goods previously imported", "ban all home industries", "export raw materials only", "increase import duties on food", "A",
     "Nigeria followed it to save foreign exchange and create factory jobs.", None),

    # ------------------------------------------------------ development/planning
    (T_DEV, "Easy", "Economic growth is best measured by increases in a country's real",
     "gross domestic product", "population", "land area", "football trophies", "A",
     "Real GDP strips out price changes to show true output growth.", None),
    (T_DEV, "Medium", "Economic development differs from economic growth because development includes",
     "improvements in welfare and living standards", "increases in output totals only", "changes in the price level only", "growth in export volumes only", "A",
     "Health, education and income distribution matter alongside output.", None),
    (T_DEV, "Medium", "The per capita income of a country is obtained by dividing national income by the",
     "total population", "number of workers only", "number of firms", "number of states", "A",
     "It is a rough average income per head of the population.", None),
    (T_DEV, "Hard", "A country with a GDP of ₦200 billion and a population of 10 million has a per capita income of",
     "₦20,000", "₦2,000", "₦200,000", "₦2 million", "A",
     "₦200,000,000,000 ÷ 10,000,000 = ₦20,000 per head.", "200e9/10e6"),
    (T_DEV, "Medium", "One feature of an underdeveloped economy is a high dependence on",
     "primary production and agriculture", "services exports", "capital export", "high technology industries", "A",
     "Raw-material production with little processing keeps incomes low.", None),
    (T_DEV, "Hard", "Nigeria's Structural Adjustment Programme of 1986 was designed mainly to",
     "restructure the economy away from oil", "increase spending on the military", "nationalise all the banks", "double the wages of civil servants", "A",
     "SAP promoted privatisation, exchange-rate reform and non-oil exports.", None),
    (T_DEV, "Medium", "Development plans are important because they set out a country's",
     "priorities and targets for national growth", "football fixtures for the season", "rulings of the law courts", "calendar of religious events", "A",
     "Plans allocate scarce resources to chosen sectors over a period.", None),
    (T_DEV, "Hard", "A rapidly growing population can hinder development when it",
     "swallows the output gains that raise welfare", "provides a large market at all times", "reduces the supply of labour", "lowers the rate of births", "A",
     "Unless output grows faster, per capita welfare stagnates.", None),
    (T_DEV, "Medium", "Human capital formation refers to investment in",
     "education, training and health of people", "machinery, tools and equipment", "roads, bridges and flyovers", "pipelines and oil installations", "A",
     "Skilled, healthy workers raise productivity across the economy.", None),
]

if __name__ == "__main__":
    build_batch(
        S,
        "batch_049_waec_economics.json",
        "batch_049_waec_economics",
        "WAEC/NECO Economics Paper 1, round 1: full SSCE syllabus - basic concepts, "
        "economic systems, tools of analysis, demand and supply, elasticity, consumer "
        "behaviour, production, business organisations, market structures, distributive "
        "trade, population and labour, money and inflation, financial institutions, "
        "public finance, international trade and development planning, with Nigerian "
        "applications. Numeric answers (elasticity, means, tax, per capita) "
        "machine-verified.",
        PASSAGES,
        PQ,
        Q,
        exam_type="WAEC",
    )
