"""Batch 028 - Literature in English round 3, part A (unseen passages and literary devices).

Twelve new unseen passages (six poems, three prose extracts, three drama extracts) with appreciation
questions, plus stand-alone items on literary devices, figures of speech and poetic terms, each built
around a fresh example line.

    python3 scripts/build_content_batch28.py -> content/batch_028_lit_round3a.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Literature in English"
T_APP = "Literary Appreciation"
T_DEV = "Literary Devices and Figures of Speech"


def poem(*lines):
    for ln in lines:
        assert len(ln) <= 42, (len(ln), ln)
    return "\n".join(lines)


PASSAGES = [
    ("L1", T_APP, "Queue at the Borehole (unseen poem)", poem(
        "Before the cock has cleared its throat,",
        "the jerrycans are already there,",
        "yellow soldiers standing in a line",
        "no general ever ordered.",
        "The borehole coughs, spits, then sings,",
        "and twenty women lean into its song.",
        "Mama Nkechi guards her place like land;",
        "a girl of six defends a bucket",
        "taller than her patience.",
        "When the handle sighs its last, dry sigh,",
        "the queue does not disperse. It waits,",
        "the way a village waits for rain,",
        "the way the poor have always waited,",
        "with jerrycans, with jokes, with God.")),
    ("L2", T_APP, "Letter to a Brother in Toronto (unseen poem)", poem(
        "You write that the snow is kind this year,",
        "that the cold has learned your name.",
        "Here the sun still argues with the roof",
        "and NEPA keeps its old promises: none.",
        "Mama has framed your graduation photo",
        "beside the calendar of a bank that closed.",
        "She dusts you every Saturday.",
        "Send the money when you can, she says,",
        "and means: send yourself.",
        "The mango you planted fruits without you;",
        "we eat them and do not speak of it.",
        "Come back, brother, or do not come back,",
        "but write. The cold, you say, is kind.",
        "Kindness was never what we lacked.")),
    ("L3", T_APP, "Harvest of Rust (unseen poem)", poem(
        "The looms are quiet. Where thread ran",
        "like rivers through a thousand fingers,",
        "spiders spin the only cloth in town.",
        "The gate that swallowed two thousand men",
        "each dawn, and spat them out at dusk,",
        "hangs from one hinge, a broken jaw.",
        "Baba worked here. His hands still move",
        "at night, feeding looms no longer there.",
        "We harvest rust now, and a kind of rage",
        "with no factory to go to in the morning.")),
    ("L4", T_APP, "The Tree at Number Twelve (unseen poem)", poem(
        "The mango tree at Number Twelve is gone;",
        "a wall of grey blocks stands in its place.",
        "We climbed it when the school day was done",
        "and dared the branches to a higher race.",
        "Its shade held Baba Tailor's rented chair,",
        "where gossip ripened faster than fruit,",
        "and every child in Surulere knew there",
        "was one ripe mango no one would dispute.",
        "The landlord's son came back from overseas",
        "with drawings and a chainsaw's steady hum;",
        "the tree came down in pieces by degrees,",
        "and nobody had told us it would come.",
        "The wall is tidy, freshly painted, bare;",
        "no fruit, no shade; nobody gathers there.")),
    ("L5", T_APP, "Night Shift (unseen poem)", poem(
        "At 2 a.m. the ward forgets to breathe;",
        "only the drip counts seconds on its beads.",
        "Sister Ugo moves from bed to bed,",
        "a lighthouse on soft shoes.",
        "Bed Four is calling for a mother",
        "dead these thirty years. She answers.",
        "Bed Nine will not see morning; she knows,",
        "and straightens his sheet as if he might.",
        "Outside, the generator preaches",
        "its one loud sermon to the dark.",
        "At six she signs the register: no change.",
        "Everything has changed. She goes home.")),
    ("L6", T_APP, "Okada (unseen poem)", poem(
        "He wears the city on his back:",
        "a nurse, a bag of rice, a coffin once,",
        "three schoolchildren stacked like plates.",
        "Between the buses and the gutters",
        "he threads a needle nobody else can see.",
        "The policeman at the bridge knows his name",
        "and the price of forgetting it.",
        "At night he counts notes soft as leaves,",
        "sends half to a village that calls him",
        "engineer, because he once was.")),
    ("L7", T_APP, "First Day at St. Jude's (unseen prose)",
     "The gate of St. Jude's was taller than any gate I had seen, and it was painted the green of unripe "
     "pawpaw. My father carried my metal box on his head the way he carried yams from the farm, and I "
     "walked behind him with the bucket and the new mattress rolled under my arm, trying not to look like "
     "a boy who had never slept away from home. Senior students lounged on the steps of the dormitory like "
     "lizards on a warm wall. One of them, a tall boy with a torn collar, looked at my father's bare feet, "
     "then at my shoes, and smiled a smile I would learn to fear. 'JJC,' he said softly, as we passed. I did "
     "not know then what it meant. I know now that it meant everything: that I was new, that I was raw, that "
     "I would be broken and remade in this place, and that my father, who had sold two goats to bring me "
     "here, would never see any of it."),
    ("L8", T_APP, "The Road (unseen prose)",
     "The elders met under the iroko as they had always met, though the iroko was now only a stump and a "
     "memory of shade. Chief Okoro spoke first, because he always spoke first, and said the government road "
     "must pass through the eastern farms. He did not mention that the eastern farms belonged to the Nwosu "
     "family, with whom he had quarrelled for thirty years. Pa Nwosu, who knew exactly what was not being "
     "mentioned, replied that the western route was shorter, cheaper and kinder to the stream; he did not "
     "mention that the western route would pass through Chief Okoro's cashew plantation. The young surveyor "
     "from the ministry, who understood none of this, wrote 'community undecided' in his notebook and thought "
     "about his lunch. Above them, the sky, which had watched such meetings for a hundred years, prepared, "
     "without much interest, to rain."),
    ("L9", T_APP, "The Interview (unseen prose)",
     "Ngozi had ironed the blouse twice. It did not matter; by the time the bus reached Marina the blouse "
     "had forgotten the iron entirely. Seventeen of them sat in the corridor, seventeen first-class brains "
     "in second-hand shoes, each pretending not to count the others. The door opened every twenty minutes "
     "and swallowed one. Nobody came out that way. When her turn came, the man behind the desk did not look "
     "up from her file. 'Ngozi Okafor. Second class upper. Who do you know here?' She said she knew her "
     "subject. He smiled at the file, as if the file had made a joke. 'Everybody knows their subject, my "
     "dear.' Outside, afterwards, the sun was where she had left it, and she stood on the steps a long time, "
     "doing arithmetic that would not come out."),
    ("L10", T_APP, "Contract (extract from an unseen play)",
     "ALHAJI SANI: (spreading a drawing across the desk) Six classrooms, Madam. Roofing, painting, "
     "everything. Finished before the rains.\n"
     "MRS. BELLO: (not touching the drawing) The last contractor also said 'before the rains'. The rains "
     "came. The roof did not.\n"
     "ALHAJI SANI: (laughing) That one was not a professional. Me, I have done work for the Ministry "
     "itself. Ask anybody.\n"
     "MR. OKON: (aside, to the audience) I have asked. Everybody says the same thing: ask somebody else.\n"
     "MRS. BELLO: And your price?\n"
     "ALHAJI SANI: Twelve million. (pause) For the school, ten. (lower) And for Madam personally, there is "
     "always something for the goodwill.\n"
     "MRS. BELLO: (rising) Mr. Okon, please show Alhaji the gate. And measure it; we may need a new one "
     "that closes faster.\n"
     "(ALHAJI SANI gathers his drawing. At the door he turns.)\n"
     "ALHAJI SANI: Madam, in this country, the one who refuses eats last.\n"
     "MRS. BELLO: Then I will eat last, Alhaji. But I will eat with my own spoon."),
    ("L11", T_APP, "The Will (extract from an unseen play)",
     "(A sitting room. A framed photograph of an old man hangs slightly crooked. UCHE, the elder brother, "
     "in a suit, checks his watch. OBI, the younger, in slippers, is arranging kola nuts on a tray.)\n"
     "UCHE: The lawyer will be here at ten. Let us be sensible. The house in Enugu is mine; I am the first "
     "son. You take the farm.\n"
     "OBI: The farm that Papa said was 'for whoever stays'. I stayed, Uche. Eleven years. You sent money "
     "and photographs.\n"
     "UCHE: Money that built the very room you are standing in.\n"
     "OBI: (quietly) And who stood in it when he could no longer stand?\n"
     "(UCHE straightens the photograph. It tilts back.)\n"
     "UCHE: We are not going to quarrel in front of a stranger.\n"
     "OBI: No. We will quarrel in front of Papa. (He gestures at the photograph.) He is used to it.\n"
     "(The doorbell rings. Neither moves.)"),
    ("L12", T_APP, "From the Diary of a Trainee Teacher (unseen prose)",
     "Monday. Forty-seven pupils, one chalk, no duster. I used my handkerchief. The headmaster says the "
     "chalk allocation 'finished' in February. It is October.\n"
     "Tuesday. A girl named Halima solved the fraction problem before I had finished writing it. She hides "
     "her cleverness the way other children hide sweets. I must find out why.\n"
     "Wednesday. Found out why. Her mother came to withdraw her; there is a husband waiting in the next "
     "village. I said the law. The mother said the rent. We were speaking two languages.\n"
     "Thursday. The headmaster said, 'Mr Tunde, you are new. Do not carry what you cannot lift.' I said "
     "nothing. My handkerchief is white with chalk and I have started to think it is a flag.\n"
     "Friday. Halima came to school. Her mother did not. I do not know what this means. I taught fractions "
     "again, slowly, as if speed were the enemy, and she solved everything, and I did not, for once, ask why."),
]

PQ = [
    # ---- L1 Queue at the Borehole ----
    ("L1", "Easy", "In 'Queue at the Borehole', the 'yellow soldiers standing in a line' are",
     "the jerrycans placed in a queue by the women", "the children sent to fetch water at dawn",
     "the women waiting their turn at the borehole", "the soldiers posted to guard the borehole",
     "A", "The jerrycans, yellow and lined up before dawn, are pictured as soldiers on parade - a metaphor."),
    ("L1", "Easy", "'The borehole coughs, spits, then sings' is an example of",
     "personification", "hyperbole", "simile", "paradox",
     "A", "Coughing, spitting and singing are human actions given to the borehole as it starts to flow."),
    ("L1", "Medium", "The phrase 'no general ever ordered' suggests that the queue is",
     "a discipline created by need rather than by any authority", "controlled strictly by the village head every morning",
     "made up of retired soldiers and their families", "an official arrangement enforced by the water board",
     "A", "The orderly line forms on its own; scarcity, not a commander, produces the discipline."),
    ("L1", "Easy", "'Mama Nkechi guards her place like land' is a",
     "simile", "metaphor", "metonymy", "euphemism",
     "A", "The comparison is made explicitly with 'like', so the device is a simile."),
    ("L1", "Medium", "The repetition of 'the way ... waits' and 'the way ... waited' in the closing lines is an example of",
     "anaphora", "onomatopoeia", "oxymoron", "litotes",
     "A", "Successive clauses begin with the same words ('the way'), which is anaphora."),
    ("L1", "Medium", "The tone of the final line, 'with jerrycans, with jokes, with God', is best described as",
     "wry admiration for the endurance of the poor", "bitter contempt for the laziness of the villagers",
     "cold indifference to the suffering described", "open mockery of the women's religious faith",
     "A", "The poet notes humour and faith alongside the jerrycans, admiring the people's resilience with gentle irony."),
    ("L1", "Medium", "The poem is mainly concerned with",
     "the patient endurance of ordinary people in the face of scarcity", "the bravery of soldiers who protect village water supplies",
     "the beauty of the countryside at the break of day", "the conflict between Mama Nkechi and a little girl",
     "A", "The queue, the failed handle and the waiting 'the way the poor have always waited' point to endurance under hardship."),
    ("L1", "Hard", "'a bucket taller than her patience' suggests that the girl",
     "is very small and is quickly losing patience with the long wait", "has brought the biggest bucket in the whole queue",
     "is more patient than any of the women around her", "has been asked to carry water for the entire village",
     "A", "The bucket dwarfs the six-year-old, and the comparison with her patience shows that her patience is short."),

    # ---- L2 Letter to a Brother in Toronto ----
    ("L2", "Medium", "In 'Letter to a Brother in Toronto', 'the cold has learned your name' suggests that the brother",
     "has become settled and familiar in his new country", "is suffering badly from the Canadian winter",
     "has changed his name since arriving in Toronto", "is unknown and lonely in the city he lives in",
     "A", "The cold 'learning' his name is a personification implying that he now belongs there."),
    ("L2", "Easy", "'NEPA keeps its old promises: none' is an example of",
     "irony", "simile", "apostrophe", "alliteration",
     "A", "The line pretends to praise NEPA for keeping promises, then reveals that it keeps none - verbal irony."),
    ("L2", "Medium", "'She dusts you every Saturday' means that Mama",
     "cleans his framed photograph as if she were tending him", "scolds him on the telephone every weekend",
     "sweeps his old room every Saturday morning", "washes the clothes he left behind at home",
     "A", "The photograph stands for the brother; dusting 'you' shows how she keeps him present."),
    ("L2", "Medium", "'Send the money when you can, she says, and means: send yourself' reveals that Mama",
     "hides her longing for her son behind practical requests", "cares more about money than about her son",
     "wants her son to stop sending money altogether", "does not believe her son has any money to send",
     "A", "What she says (money) and what she means (his return) differ; her real wish is for him."),
    ("L2", "Medium", "'The mango you planted fruits without you' most likely symbolises",
     "life at home continuing in the brother's absence", "the wealth the brother has made abroad",
     "the family's anger at the brother's laziness", "the failure of the brother's plans in Toronto",
     "A", "What he planted bears fruit he does not share - a symbol of home moving on without him."),
    ("L2", "Medium", "The speaker's attitude to the brother is best described as",
     "loving but tinged with reproach", "hostile and openly contemptuous", "indifferent and detached", "envious and mocking",
     "A", "'Come back, brother, or do not come back, but write' mixes affection with quiet rebuke."),
    ("L2", "Hard", "The last line, 'Kindness was never what we lacked', implies that",
     "what the family lacked was opportunity, not human warmth", "the family has always been unkind to the brother",
     "the brother left home because nobody was kind to him", "Canada is a kinder country than Nigeria",
     "A", "The brother praises the kind cold; the speaker answers that kindness was plentiful at home - it was other things they lacked."),
    ("L2", "Easy", "The poem is written in the form of",
     "a verse letter in free verse", "a sonnet with a final couplet", "a ballad in four-line stanzas", "a dramatic monologue in blank verse",
     "A", "It addresses the brother directly as a letter, without regular rhyme or metre."),

    # ---- L3 Harvest of Rust ----
    ("L3", "Medium", "In 'Harvest of Rust', 'spiders spin the only cloth in town' is effective because it",
     "contrasts the factory's former weaving with the desolation of the present", "shows that the town has found a new source of income",
     "praises the skill of the spiders compared with the workers", "suggests that the factory will soon reopen",
     "A", "Where looms once wove cloth, only cobwebs are 'woven' now - an ironic image of decline."),
    ("L3", "Easy", "The gate is compared to 'a broken jaw' by means of",
     "metaphor", "simile", "onomatopoeia", "euphemism",
     "A", "The gate is directly called a broken jaw, without 'like' or 'as', so the device is metaphor."),
    ("L3", "Medium", "'The gate that swallowed two thousand men each dawn, and spat them out at dusk' presents the factory as",
     "a living creature that consumed the workers' days", "a generous provider that fed the whole town",
     "a prison from which nobody ever escaped", "a temple where the workers came to worship",
     "A", "Swallowing and spitting are actions of a living thing - personification of the factory's daily routine."),
    ("L3", "Medium", "Baba's hands moving at night 'feeding looms no longer there' suggest that he",
     "cannot let go of the work that defined his life", "has found night work at another factory",
     "is teaching his children how to weave", "still goes to the factory every evening",
     "A", "Even in sleep his hands repeat the old motions; the loss haunts him."),
    ("L3", "Medium", "The title 'Harvest of Rust' is ironic because",
     "a harvest suggests plenty while rust suggests decay", "rust cannot be harvested by farmers",
     "the poem is set in a factory rather than on a farm", "the workers were paid in crops rather than money",
     "A", "The word 'harvest' promises reward; what is reaped is rust - the irony sums up the poem."),
    ("L3", "Hard", "'a kind of rage with no factory to go to in the morning' suggests that",
     "the anger of the unemployed has no outlet or direction", "the workers are too tired to be angry any more",
     "the factory owners fear the workers' revenge", "the town has decided to build a new factory",
     "A", "Like the workers, the rage has nowhere to go; it is idle and aimless."),
    ("L3", "Easy", "The dominant mood of 'Harvest of Rust' is one of",
     "desolation and bitterness", "celebration and hope", "calm contentment", "playful humour",
     "A", "Silent looms, a broken gate, rust and rage create a bleak, bitter mood."),

    # ---- L4 The Tree at Number Twelve ----
    ("L4", "Easy", "'The Tree at Number Twelve' is, in form, a",
     "Shakespearean sonnet", "Petrarchan sonnet", "ballad", "limerick",
     "A", "Fourteen lines in three quatrains and a closing couplet, rhyming abab cdcd efef gg."),
    ("L4", "Easy", "The rhyme scheme of the first four lines of 'The Tree at Number Twelve' is",
     "abab", "aabb", "abba", "abcb",
     "A", "gone/done and place/race rhyme alternately: abab."),
    ("L4", "Medium", "'where gossip ripened faster than fruit' uses",
     "metaphor", "simile", "onomatopoeia", "apostrophe",
     "A", "Gossip is said to ripen like fruit without 'like' or 'as' - a metaphor."),
    ("L4", "Medium", "The mango tree in the poem functions mainly as a symbol of",
     "shared community life and childhood", "the wealth of the landlord's family",
     "the danger of climbing trees", "the poverty of Surulere",
     "A", "Children, the tailor and gossip all gathered under it; its loss ends that common life."),
    ("L4", "Medium", "The landlord's son 'with drawings and a chainsaw's steady hum' represents",
     "a modernising generation indifferent to what the tree meant", "a skilled craftsman restoring the compound",
     "the return of prosperity to the neighbourhood", "the children who once climbed the tree",
     "A", "He arrives from overseas with plans and destroys the tree without consulting anyone."),
    ("L4", "Medium", "The final couplet is effective because it",
     "sets the neatness of the wall against the lifelessness that replaced the tree", "explains why the landlord's son wanted the tree removed",
     "shows that the children have found a new tree to climb", "describes the fruit that the new wall now provides",
     "A", "'Tidy, freshly painted, bare' is answered by 'no fruit, no shade; nobody gathers there'."),
    ("L4", "Medium", "'and nobody had told us it would come' conveys a feeling of",
     "helpless exclusion from a decision that affected the children", "relief that the dangerous tree was finally removed",
     "gratitude to the landlord for the surprise", "excitement at the arrival of the chainsaw",
     "A", "The children were neither consulted nor warned; the line records their powerlessness."),
    ("L4", "Easy", "In the poem, 'by degrees' means",
     "gradually", "with certificates", "at an angle", "very quickly",
     "A", "The tree came down 'in pieces by degrees', that is, little by little."),

    # ---- L5 Night Shift ----
    ("L5", "Easy", "In 'Night Shift', 'the ward forgets to breathe' is an example of",
     "personification", "simile", "hyperbole", "pun",
     "A", "The ward is given the human capacity to breathe and forget."),
    ("L5", "Medium", "Sister Ugo is called 'a lighthouse on soft shoes' because she",
     "is a steady source of comfort moving quietly among the patients", "is tall and can be seen from every bed in the ward",
     "carries a torch as she walks around at night", "warns the patients loudly whenever danger comes",
     "A", "A lighthouse guides and reassures; 'soft shoes' adds her quiet, unobtrusive care."),
    ("L5", "Medium", "Sister Ugo's response to the patient calling for a mother 'dead these thirty years' shows that she is",
     "compassionate, comforting rather than correcting", "confused about who the patient is calling",
     "impatient with the confused old patient", "the patient's daughter in real life",
     "A", "'She answers' - she meets the patient's need instead of pointing out his error."),
    ("L5", "Medium", "'and straightens his sheet as if he might' reveals the nurse's",
     "tenderness in preserving the dignity of a dying man", "belief that the patient will recover by morning",
     "carelessness about the condition of the patient", "fear of being blamed for the patient's death",
     "A", "She knows Bed Nine will die, yet treats him as though he had a future - an act of gentle respect."),
    ("L5", "Medium", "Describing the generator's noise as 'its one loud sermon to the dark' suggests that the sound is",
     "monotonous and insistent", "soothing and musical", "faint and distant", "cheerful and varied",
     "A", "A single sermon repeated loudly all night conveys a droning, relentless noise."),
    ("L5", "Medium", "The contrast between 'no change' in the register and 'Everything has changed' is an example of",
     "irony", "simile", "alliteration", "onomatopoeia",
     "A", "The official record says nothing happened, while the truth is that a man died - situational irony."),
    ("L5", "Easy", "The poem's attitude towards Sister Ugo is one of",
     "quiet admiration", "harsh criticism", "amused mockery", "cold indifference",
     "A", "Her steadiness, compassion and dignity are presented with restrained respect."),

    # ---- L6 Okada ----
    ("L6", "Medium", "In 'Okada', 'He wears the city on his back' means that the rider",
     "carries all kinds of people and loads for the city", "is dressed in clothes bought in the city",
     "has a map of the city printed on his shirt", "owns a large part of the city's property",
     "A", "The following lines list his passengers and loads; the city literally rides on his back."),
    ("L6", "Easy", "'three schoolchildren stacked like plates' is an example of",
     "simile", "metaphor", "irony", "apostrophe",
     "A", "The children are compared to stacked plates using 'like' - a simile."),
    ("L6", "Medium", "'he threads a needle nobody else can see' suggests that the rider",
     "weaves skilfully through gaps in the traffic", "repairs clothes when he is not riding",
     "cannot see well and rides dangerously", "follows a route marked only on his map",
     "A", "Threading an invisible needle pictures his skill in finding narrow paths between vehicles."),
    ("L6", "Medium", "'the price of forgetting it' refers to",
     "the bribe the policeman collects to let him pass", "the fine for riding without a licence",
     "the cost of repairing the motorcycle", "the fare the rider charges his passengers",
     "A", "The policeman 'knows his name' and the price of forgetting it - money paid to be left alone."),
    ("L6", "Medium", "'engineer, because he once was' implies that the rider",
     "is a trained engineer forced by unemployment into riding okada", "repairs motorcycles for the other riders in the village",
     "lied to his village about his profession", "hopes to study engineering one day",
     "A", "The village still calls him by the profession he trained for but can no longer practise."),
    ("L6", "Easy", "The poem's attitude to the okada rider is one of",
     "sympathetic respect", "open ridicule", "angry condemnation", "amused contempt",
     "A", "His skill, burdens and sacrifice for his village are presented with sympathy."),
    ("L6", "Medium", "'notes soft as leaves' suggests that the money is",
     "worn and fragile from passing through many hands", "freshly printed and crisp",
     "made of leaves rather than paper", "green in colour like new leaves",
     "A", "Old notes become soft like fallen leaves; the simile also hints at how little they are worth."),

    # ---- L7 First Day at St. Jude's ----
    ("L7", "Easy", "In 'First Day at St. Jude's', the story is told by",
     "an adult recalling his own first day at school", "the father of the new student",
     "a senior student watching the newcomers", "an outside narrator who knows all the characters",
     "A", "'I did not know then ... I know now' shows a first-person narrator looking back on his childhood."),
    ("L7", "Easy", "'the green of unripe pawpaw' is an example of",
     "visual imagery", "onomatopoeia", "hyperbole", "paradox",
     "A", "The phrase appeals to the sense of sight by describing an exact shade of green."),
    ("L7", "Medium", "'Senior students lounged on the steps ... like lizards on a warm wall' is a simile that suggests the seniors are",
     "idle yet watchful", "friendly and welcoming", "afraid of the newcomers", "busy with their studies",
     "A", "Lizards bask lazily but watch for movement; the seniors idle while sizing up the new boy."),
    ("L7", "Medium", "The senior's smile, which the narrator 'would learn to fear', is an example of",
     "foreshadowing", "flashback", "climax", "comic relief",
     "A", "It hints at the bullying to come, which the narrator will experience later."),
    ("L7", "Medium", "The contrast between the father's bare feet and the boy's shoes suggests",
     "the father's sacrifice so that his son may have a better life", "the father's refusal to buy shoes for himself",
     "that the boy is ashamed of his father's appearance", "that the school required all visitors to be barefoot",
     "A", "The father goes without so that the boy is properly equipped; he even sold two goats for the fees."),
    ("L7", "Medium", "'that I would be broken and remade in this place' suggests that the boarding school",
     "transformed the narrator through harsh experience", "was demolished and rebuilt during his time there",
     "expelled him and later readmitted him", "taught him a trade in pottery and carpentry",
     "A", "'Broken and remade' is a metaphor for the painful reshaping of his character."),
    ("L7", "Medium", "In the passage, the word 'JJC' functions as",
     "a label that marks the narrator as a raw newcomer", "the name of the tall senior with the torn collar",
     "the motto of St. Jude's written on the gate", "a greeting that the seniors gave to all visitors",
     "A", "The narrator explains that it meant he was 'new' and 'raw' - an outsider's tag."),
    ("L7", "Hard", "The closing words 'would never see any of it' suggest that the father",
     "remained shut out of the world his sacrifice had opened for his son", "went blind soon after leaving the school",
     "refused ever to visit his son at St. Jude's", "was forbidden by the seniors to enter the school",
     "A", "Having paid so much, the father would have no share in the life the school gave the boy."),

    # ---- L8 The Road ----
    ("L8", "Easy", "In 'The Road', the narrator",
     "knows and reports the private thoughts of several characters", "is Chief Okoro speaking for himself",
     "is the young surveyor telling his own story", "reports only what could be seen and heard",
     "A", "The narrator tells us what each man 'did not mention' and what the surveyor thought - an omniscient narrator."),
    ("L8", "Medium", "'the iroko was now only a stump and a memory of shade' suggests that",
     "the traditions of the community have decayed", "the elders have planted a new iroko tree",
     "the meeting was held in the heat of the sun", "the government has built a road through the village",
     "A", "The great tree under which elders met is reduced to a stump - an image of lost authority and tradition."),
    ("L8", "Medium", "The repeated phrase 'He did not mention' is used to create",
     "irony by exposing the hidden motives behind noble-sounding arguments", "suspense about which route the road will take",
     "sympathy for the surveyor who understands nothing", "humour at the expense of the Nwosu family",
     "A", "Each man argues for the public good while the narrator reveals his private grudge."),
    ("L8", "Medium", "The surveyor who 'understood none of this' represents",
     "outside officials ignorant of local realities", "the honest youth who will end corruption",
     "the government's concern for the villagers", "the future leader of the community",
     "A", "He records 'community undecided' and thinks of lunch, missing the feud entirely."),
    ("L8", "Medium", "The sky that 'prepared, without much interest, to rain' is an example of",
     "personification conveying nature's indifference to human quarrels", "pathetic fallacy showing nature's sympathy with the elders",
     "hyperbole exaggerating the importance of the meeting", "foreshadowing of a great flood that will destroy the village",
     "A", "The sky is given feelings ('without much interest'), and its boredom belittles the century-old squabble."),
    ("L8", "Easy", "The main conflict in the passage is",
     "the long-standing rivalry between Chief Okoro and Pa Nwosu", "the surveyor's disagreement with the ministry",
     "the villagers' opposition to the government road", "the struggle between the elders and the young people",
     "A", "Each man's argument about the route is really a move in a thirty-year quarrel."),
    ("L8", "Medium", "The tone of the passage is best described as",
     "gently satirical", "bitterly angry", "solemn and tragic", "warmly sentimental",
     "A", "The narrator mocks the elders' self-interest and the surveyor's ignorance with quiet humour."),

    # ---- L9 The Interview ----
    ("L9", "Medium", "The narrative technique used in 'The Interview' is",
     "third-person narration limited to Ngozi's experience", "first-person narration by Ngozi herself",
     "omniscient narration entering every character's mind", "second-person narration addressing the reader",
     "A", "The narrator says 'she' but shows only what Ngozi sees, feels and thinks."),
    ("L9", "Easy", "'the blouse had forgotten the iron entirely' is an example of",
     "personification", "simile", "alliteration", "litotes",
     "A", "The blouse is given the human ability to forget - a humorous personification."),
    ("L9", "Medium", "'seventeen first-class brains in second-hand shoes' uses",
     "antithesis", "onomatopoeia", "apostrophe", "euphemism",
     "A", "'First-class' is set against 'second-hand' in a balanced contrast."),
    ("L9", "Medium", "'The door opened every twenty minutes and swallowed one. Nobody came out that way.' creates a sense of",
     "menace and foreboding", "excitement and celebration", "boredom and routine", "peace and reassurance",
     "A", "The door that 'swallows' candidates who never reappear makes the interview seem ominous."),
    ("L9", "Medium", "The question 'Who do you know here?' reveals that",
     "jobs are given through connections rather than merit", "the interviewer wants to know Ngozi's friends",
     "the company only employs relatives of its staff", "Ngozi has applied to the wrong office",
     "A", "The interviewer is not interested in her qualifications but in her connections."),
    ("L9", "Medium", "'He smiled at the file, as if the file had made a joke' suggests that the interviewer",
     "regards Ngozi's answer with amused contempt", "is pleased with Ngozi's excellent results",
     "has found a mistake in Ngozi's application", "is nervous about interviewing Ngozi",
     "A", "He finds her reliance on merit laughable, as his next remark confirms."),
    ("L9", "Hard", "'the sun was where she had left it' suggests that",
     "the world outside is unchanged although Ngozi's hopes have been shaken", "the interview lasted only a few seconds",
     "Ngozi had forgotten her umbrella on the steps", "the weather changed suddenly after the interview",
     "A", "Nothing outside has moved; the indifference of the world contrasts with what she has just lost."),
    ("L9", "Medium", "'doing arithmetic that would not come out' most likely means that Ngozi",
     "cannot make her future plans or finances add up", "is revising mathematics for another interview",
     "is counting the other candidates in the corridor", "is calculating the salary she will be paid",
     "A", "The 'arithmetic' is her attempt to work out how she will manage now; it has no solution."),

    # ---- L10 Contract ----
    ("L10", "Easy", "In 'Contract', Mr. Okon's remark 'I have asked. Everybody says the same thing: ask somebody else' is delivered as",
     "an aside", "a soliloquy", "a prologue", "a chorus",
     "A", "It is spoken 'to the audience' and is not heard by the other characters - an aside."),
    ("L10", "Medium", "'The rains came. The roof did not.' is effective because of its",
     "brevity and irony", "rhyme and rhythm", "hyperbole and pathos", "alliteration and assonance",
     "A", "Two short sentences set the reliable rains against the unreliable roof, exposing the contractor's failure."),
    ("L10", "Medium", "Alhaji Sani's 'something for the goodwill' is",
     "a euphemism for a bribe", "a metaphor for hard work", "a proverb about generosity", "an allusion to a religious duty",
     "A", "He softens the offer of a bribe with a polite, vague phrase."),
    ("L10", "Medium", "Mrs. Bello's instruction to 'measure the gate; we may need a new one that closes faster' is an example of",
     "sarcasm", "hyperbole", "pathos", "apostrophe",
     "A", "She pretends to give an ordinary instruction while really telling Alhaji never to return."),
    ("L10", "Medium", "The saying 'the one who refuses eats last' expresses the view that",
     "honesty is punished in a corrupt society", "patience is always rewarded in the end",
     "contractors should be paid before they start work", "a guest must not eat before the host",
     "A", "Alhaji means that those who refuse bribes lose out while others prosper."),
    ("L10", "Medium", "'But I will eat with my own spoon' means that Mrs. Bello",
     "will live on what she earns honestly", "prefers to eat alone in her office",
     "will not share her food with Alhaji", "intends to buy her own cutlery",
     "A", "She accepts eating last, provided what she eats is honestly hers."),
    ("L10", "Easy", "The main conflict in 'Contract' is between",
     "integrity and corruption", "youth and age", "tradition and modernity", "town and village",
     "A", "The principal's refusal of the bribe against the contractor's assumption that everyone takes one."),
    ("L10", "Medium", "Mr. Okon's aside contributes to the extract by",
     "adding humour while confirming that Alhaji is not to be trusted", "revealing that Mr. Okon has taken bribes himself",
     "explaining the cost of building six classrooms", "showing that the principal cannot make decisions",
     "A", "His dry comment amuses the audience and undermines Alhaji's boast, 'Ask anybody'."),

    # ---- L11 The Will ----
    ("L11", "Medium", "In 'The Will', the photograph that 'tilts back' after Uche straightens it suggests that",
     "the family's disorder cannot be put right by Uche's tidy gestures", "the nail holding the photograph is loose",
     "the father disapproved of Obi's decision to stay", "Uche intends to remove the photograph from the wall",
     "A", "Uche's attempt to set things straight fails, just as his neat division of the inheritance will."),
    ("L11", "Medium", "Obi's line 'You sent money and photographs' implies that Uche",
     "replaced his presence with material support", "was too poor to visit their father",
     "worked as a photographer in the city", "sent more money than Obi could earn",
     "A", "Obi contrasts his eleven years of staying with Uche's remote contributions."),
    ("L11", "Medium", "'And who stood in it when he could no longer stand?' is",
     "a rhetorical question with a play on the word 'stand'", "a proverb about respecting one's elders",
     "an aside addressed to the audience", "a literal request for information from Uche",
     "A", "Obi expects no answer; 'stood' and 'stand' shift from being present to being physically able to stand."),
    ("L11", "Medium", "'He is used to it', said of the father's photograph, suggests that",
     "the brothers quarrelled even while their father was alive", "the father enjoyed watching his sons argue",
     "the photograph has often been knocked off the wall", "the lawyer has visited the house many times before",
     "A", "The father grew accustomed to their quarrels in life; now his picture will witness another."),
    ("L11", "Medium", "The final stage direction, 'The doorbell rings. Neither moves', creates",
     "suspense and shows that both brothers dread the decision", "relief that the argument is finally over",
     "humour at the brothers' laziness", "confusion about who is at the door",
     "A", "The lawyer's arrival should end the dispute, yet neither brother wants to face it."),
    ("L11", "Easy", "Uche's insistence 'I am the first son' appeals to",
     "the tradition that the eldest son inherits", "the wishes their father expressed",
     "the law of the country", "the advice of the lawyer",
     "A", "He claims the house by seniority, not by the father's stated wish 'for whoever stays'."),
    ("L11", "Easy", "The crooked photograph in the opening stage direction is an example of",
     "symbolism", "hyperbole", "onomatopoeia", "simile",
     "A", "A concrete detail (the crooked picture) stands for the disorder in the family."),
    ("L11", "Medium", "The conflict in 'The Will' is chiefly between",
     "duty performed from a distance and care given in person", "the lawyer's advice and the wishes of the two brothers",
     "the customs of the city and the customs of the village", "the living father and the sons who disobeyed him",
     "A", "Uche's money against Obi's eleven years of presence."),

    # ---- L12 Diary of a Trainee Teacher ----
    ("L12", "Easy", "'From the Diary of a Trainee Teacher' is written in the form of",
     "diary entries", "a letter", "a dramatic monologue", "a newspaper report",
     "A", "Each section is headed by a day of the week and records the writer's private experiences."),
    ("L12", "Easy", "'She hides her cleverness the way other children hide sweets' is a",
     "simile", "metaphor", "paradox", "pun",
     "A", "The comparison is made with 'the way', equivalent to 'like' or 'as'."),
    ("L12", "Medium", "'I said the law. The mother said the rent.' shows that",
     "the teacher's principles and the mother's poverty belong to different worlds", "the mother is a lawyer who knows the rules better than the teacher does",
     "the teacher owes several months' rent to Halima's mother", "the law requires parents to pay rent to the schools their children attend",
     "A", "He appeals to what is right; she answers with what she can afford - neither hears the other."),
    ("L12", "Medium", "'We were speaking two languages' is a metaphor for",
     "mutual incomprehension", "the school's bilingual policy", "the mother's foreign accent", "the teacher's love of languages",
     "A", "They both spoke the same tongue but could not understand each other's concerns."),
    ("L12", "Medium", "'Do not carry what you cannot lift' is the headmaster's way of",
     "warning Tunde not to take on problems beyond his power", "asking Tunde to help move the school furniture",
     "praising Tunde for his physical strength", "telling Tunde to stop using his handkerchief",
     "A", "The proverb advises the new teacher to leave alone troubles he cannot solve."),
    ("L12", "Hard", "The handkerchief that Tunde has 'started to think ... is a flag' suggests that he",
     "feels close to surrendering", "wants to celebrate a victory", "is proud of his country", "plans to lead a protest",
     "A", "A white cloth held up is a sign of surrender; the chalk-white handkerchief hints at giving up."),
    ("L12", "Medium", "The mood of the final entry is best described as",
     "cautious hope", "utter despair", "triumphant joy", "cold anger",
     "A", "Halima returns and solves everything, but Tunde 'does not know what this means' - hope held carefully."),
    ("L12", "Medium", "The headmaster is characterised as",
     "resigned to the school's problems", "eager to fight for the pupils", "cruel to the teachers", "generous with materials",
     "A", "He explains away the missing chalk and advises Tunde not to struggle against what cannot be changed."),
]

Q = [
    # ---------------- Literary devices: fresh example lines ----------------
    (T_DEV, "Easy", "'Her laughter rang through the compound like a bell at dawn' is an example of",
     "simile", "metaphor", "personification", "hyperbole",
     "A", "The laughter is compared to a bell using 'like', which makes it a simile."),
    (T_DEV, "Easy", "'The examination hall was a furnace of nerves' is an example of",
     "metaphor", "simile", "litotes", "onomatopoeia",
     "A", "The hall is directly called a furnace; the comparison is implied, not stated with 'like'."),
    (T_DEV, "Easy", "'The old lorry groaned up the hill, complaining at every gear' illustrates",
     "personification", "alliteration", "euphemism", "paradox",
     "A", "Groaning and complaining are human actions attributed to the lorry."),
    (T_DEV, "Easy", "'The queue at the filling station stretched into the next state' is an example of",
     "hyperbole", "understatement", "metonymy", "irony",
     "A", "The length of the queue is deliberately exaggerated for effect."),
    (T_DEV, "Medium", "'The governor's four-hour speech was not exactly short' is an example of",
     "litotes", "hyperbole", "apostrophe", "oxymoron",
     "A", "A quality is affirmed by denying its opposite ('not exactly short') - understatement by negation."),
    (T_DEV, "Easy", "A company that dismisses half its staff announces that it is 'right-sizing'. The expression is",
     "a euphemism", "a paradox", "an allusion", "a simile",
     "A", "A harsh reality (mass dismissal) is disguised in a mild, agreeable term."),
    (T_DEV, "Easy", "'the bitter sweetness of leaving home' contains",
     "an oxymoron", "a simile", "an allusion", "a pun",
     "A", "'Bitter' and 'sweetness' are contradictory terms placed side by side."),
    (T_DEV, "Medium", "'The more he earned, the poorer he felt' is an example of",
     "paradox", "simile", "metonymy", "alliteration",
     "A", "The statement seems self-contradictory yet expresses a truth about greed or discontent."),
    (T_DEV, "Medium", "A traffic officer is arrested for driving without a licence. This situation illustrates",
     "irony", "hyperbole", "euphemism", "metaphor",
     "A", "The outcome is the opposite of what one would expect from an enforcer of traffic law - situational irony."),
    (T_DEV, "Medium", "In a play, the audience has watched the servant pour poison into the cup which the queen now raises to toast her 'long life'. This is",
     "dramatic irony", "verbal irony", "comic relief", "poetic justice",
     "A", "The audience knows what the character does not; her words gain a meaning she cannot see."),
    (T_DEV, "Easy", "'Lovely weather,' she said, wringing out her soaked wrapper. Her remark is an example of",
     "verbal irony", "hyperbole", "personification", "metonymy",
     "A", "She says the opposite of what she means; the rain has drenched her."),
    (T_DEV, "Easy", "'Big brown bags of beans burst on the busy bridge' illustrates",
     "alliteration", "assonance", "onomatopoeia", "paradox",
     "A", "The consonant sound /b/ is repeated at the beginning of several words."),
    (T_DEV, "Medium", "'The light of the white kite in flight' illustrates",
     "assonance", "alliteration", "personification", "euphemism",
     "A", "The vowel sound /ai/ is repeated within neighbouring words."),
    (T_DEV, "Medium", "'The black rock cracked under the truck' illustrates",
     "consonance", "apostrophe", "simile", "irony",
     "A", "The consonant sound /k/ is repeated at the end of words - consonance."),
    (T_DEV, "Easy", "'The bacon sizzled and the pan crackled' is an example of",
     "onomatopoeia", "simile", "litotes", "allusion",
     "A", "'Sizzled' and 'crackled' imitate the sounds they describe."),
    (T_DEV, "Easy", "'O Lagos, city of my sleepless nights, when will you rest?' is an example of",
     "apostrophe", "simile", "litotes", "onomatopoeia",
     "A", "The poet addresses a city as if it were a person who could answer."),
    (T_DEV, "Medium", "'The Villa has not yet responded to the Senate' uses",
     "metonymy", "simile", "hyperbole", "oxymoron",
     "A", "'The Villa' (the presidential residence) stands for the presidency associated with it."),
    (T_DEV, "Medium", "'The farmer bought fifty head of cattle' is an example of",
     "synecdoche", "metaphor", "euphemism", "paradox",
     "A", "A part (head) stands for the whole animal."),
    (T_DEV, "Medium", "'When the lights went out, the electrician was delighted' plays on the word 'delighted'. The device is",
     "pun", "simile", "apostrophe", "litotes",
     "A", "'Delighted' suggests both 'pleased' and 'de-lighted' (without light) - a play on words."),
    (T_DEV, "Medium", "'She was rich in friends and poor in money' is an example of",
     "antithesis", "simile", "onomatopoeia", "euphemism",
     "A", "Opposite ideas (rich/poor) are balanced in parallel phrases."),
    (T_DEV, "Medium", "'Tired of the noise, tired of the heat, tired of the lies, he left' illustrates",
     "anaphora", "onomatopoeia", "oxymoron", "simile",
     "A", "The phrase 'tired of' is repeated at the beginning of successive units."),
    (T_DEV, "Hard", "'They wanted bread; we gave them bread. They wanted land; we gave them land.' The repetition at the end of successive clauses is",
     "epistrophe", "anaphora", "hyperbole", "pun",
     "A", "Repetition at the end of clauses is epistrophe (the opposite of anaphora)."),
    (T_DEV, "Medium", "'He lost his job, then his house, then his family, then his mind' arranges ideas in order of increasing importance. This is",
     "climax", "anticlimax", "litotes", "metonymy",
     "A", "Each loss is graver than the last, building to the most serious."),
    (T_DEV, "Medium", "'The general vowed to defend the nation, the flag and his parking space' is an example of",
     "anticlimax", "climax", "simile", "apostrophe",
     "A", "The series drops suddenly from the serious to the trivial for comic effect (bathos)."),
    (T_DEV, "Medium", "'He carried the weight of Atlas on his shoulders' contains",
     "an allusion", "a pun", "an oxymoron", "a litotes",
     "A", "The reference to Atlas, who bore the heavens in Greek myth, is an allusion."),
    (T_DEV, "Medium", "In a novel, a caged parrot sits on the veranda of an unhappy, confined wife throughout the story. The parrot is",
     "a symbol", "a simile", "an aside", "a soliloquy",
     "A", "A concrete object stands for an abstract idea - the wife's own captivity."),
    (T_DEV, "Easy", "'The smell of roasting corn and wet dust filled the evening air' appeals mainly to the sense of",
     "smell", "sight", "hearing", "touch",
     "A", "This is olfactory imagery; the line describes smells."),
    (T_DEV, "Easy", "A line repeated at the end of every stanza of a poem is called",
     "a refrain", "a couplet", "an epigram", "a caesura",
     "A", "A refrain is a recurring line or group of lines, usually at the end of stanzas."),
    (T_DEV, "Easy", "'Who among us has never told a lie?' is",
     "a rhetorical question", "a paradox", "an aside", "a euphemism",
     "A", "The question expects no answer; it makes the point that everyone has lied."),
    (T_DEV, "Medium", "'He returned back to his home village again' is an example of",
     "tautology", "hyperbole", "metaphor", "irony",
     "A", "'Returned', 'back' and 'again' needlessly repeat the same idea."),
    (T_DEV, "Hard", "'The teacher's angry red pen tore through the essay' - the adjective 'angry' belongs properly to the teacher, not the pen. The device is",
     "transferred epithet", "onomatopoeia", "litotes", "paradox",
     "A", "An adjective is transferred from the person to an associated object."),
    (T_DEV, "Hard", "'She lost her keys and her temper on the same morning' is an example of",
     "zeugma", "simile", "alliteration", "apostrophe",
     "A", "One verb ('lost') governs two objects in different senses - zeugma."),
    (T_DEV, "Medium", "'I am not saying the treasurer is a thief, but the church roof still leaks after three collections.' This is an example of",
     "innuendo", "hyperbole", "simile", "onomatopoeia",
     "A", "An accusation is implied indirectly rather than stated openly."),
    (T_DEV, "Medium", "'It's just a scratch,' he said, looking at the wrecked car. This is an example of",
     "understatement", "hyperbole", "personification", "allusion",
     "A", "The seriousness of the damage is deliberately minimised."),
    (T_DEV, "Medium", "'Work to live; do not live to work' reverses the order of words in the second clause. The device is",
     "chiasmus", "simile", "onomatopoeia", "euphemism",
     "A", "The structure A-B / B-A (work-live / live-work) is chiasmus."),
    (T_DEV, "Easy", "'Brilliant! Another power cut,' said Ola. Ola's remark is an example of",
     "sarcasm", "hyperbole", "simile", "apostrophe",
     "A", "He says 'brilliant' to mock a situation he finds annoying."),
    (T_DEV, "Medium", "'Hunger knocked on every door in the village that year' illustrates",
     "personification", "simile", "understatement", "pun",
     "A", "Hunger is given the human action of knocking on doors."),
    (T_DEV, "Easy", "'Her handbag weighed a ton' is an example of",
     "hyperbole", "litotes", "metonymy", "paradox",
     "A", "The weight of the bag is deliberately exaggerated."),
    (T_DEV, "Easy", "'Seven sleepy students slumped silently' illustrates",
     "alliteration", "assonance", "oxymoron", "irony",
     "A", "The initial /s/ sound is repeated in successive words."),
    (T_DEV, "Medium", "'Go slow over the road, Joe' repeats the vowel sound in 'go', 'slow', 'road' and 'Joe'. The device is",
     "assonance", "consonance", "personification", "metaphor",
     "A", "Repetition of the same vowel sound within nearby words is assonance."),
    (T_DEV, "Medium", "A marriage counsellor files for divorce on the day her book on lasting marriages is launched. This is an example of",
     "situational irony", "dramatic irony", "hyperbole", "apostrophe",
     "A", "The outcome sharply contradicts what her profession and book lead one to expect."),
    (T_DEV, "Medium", "A pause within a line of poetry, often marked by punctuation, as in 'I stood; the river did not', is called",
     "a caesura", "an enjambment", "a refrain", "a stanza",
     "A", "A caesura is a break or pause in the middle of a line of verse."),
    (T_DEV, "Medium", "'I bring fresh showers for the thirsting flowers' contains",
     "internal rhyme", "eye rhyme", "half rhyme", "blank verse",
     "A", "'Showers' and 'flowers' rhyme within the same line."),
    (T_DEV, "Hard", "In a poem, the words 'love' and 'move' are placed at the ends of successive lines. Their rhyme is",
     "an eye rhyme", "a perfect rhyme", "an internal rhyme", "a feminine rhyme",
     "A", "They look alike in spelling but do not sound alike - an eye rhyme."),
    (T_DEV, "Hard", "Line endings such as 'shape' and 'keep', which share the final consonant but not the vowel, are examples of",
     "half rhyme", "full rhyme", "eye rhyme", "internal rhyme",
     "A", "Half rhyme (slant rhyme) matches consonants but not vowels."),
    (T_DEV, "Medium", "'Nothing is so exhausting as doing nothing' is an example of",
     "paradox", "simile", "metonymy", "onomatopoeia",
     "A", "It appears contradictory yet expresses a recognisable truth about idleness."),
    (T_DEV, "Medium", "Throughout a poem the nation is described as a ship: its captain, its sails, its leaking hull and its mutinous crew. This is",
     "an extended metaphor", "a simile", "a pun", "an apostrophe",
     "A", "A single metaphor (nation = ship) is developed through several related details."),
    (T_DEV, "Hard", "In a poem, the souls of two lovers are compared at length to the two legs of a drawing compass. Such an elaborate, surprising comparison is called",
     "a conceit", "a proverb", "an epigram", "a euphemism",
     "A", "A conceit is a far-fetched, extended comparison, typical of metaphysical poetry."),
    (T_DEV, "Medium", "The description of a creaking, unlit house lashed by rain at midnight creates",
     "an atmosphere of foreboding", "a tone of celebration", "comic relief", "poetic justice",
     "A", "The setting details build a mood of dread and expectancy."),
    (T_DEV, "Medium", "A play ridicules greedy senators by exaggerating their faults so that the audience laughs at them. The play is an example of",
     "satire", "elegy", "pastoral", "epic",
     "A", "Satire uses humour, exaggeration and ridicule to expose vice or folly."),
    (T_DEV, "Medium", "A poem imitates the style and tune of the national anthem in order to mock political failure. The poem is",
     "a parody", "an ode", "an elegy", "a sonnet",
     "A", "A parody imitates a known work or style for comic or critical effect."),
    (T_DEV, "Easy", "'A stitch in time saves nine' is",
     "a proverb", "a pun", "a paradox", "an aside",
     "A", "A short, traditional saying that expresses a general truth is a proverb."),
    (T_DEV, "Medium", "In 'Alexander the Great' and 'Richard the Lionheart', the descriptive title attached to the name is",
     "an epithet", "a euphemism", "a metonymy", "an oxymoron",
     "A", "An epithet is an adjective or phrase expressing a characteristic quality of a person."),
    (T_DEV, "Medium", "A character says, 'He is the very pineapple of politeness,' meaning 'pinnacle'. The comic misuse of a word is",
     "malapropism", "metaphor", "assonance", "innuendo",
     "A", "A malapropism is the mistaken use of a similar-sounding word, often with comic effect."),
    (T_DEV, "Medium", "A military spokesman describes the deaths of civilians as 'collateral damage'. The phrase is",
     "a euphemism", "a hyperbole", "a simile", "an apostrophe",
     "A", "A distressing reality is expressed in a bland, technical term."),
    (T_DEV, "Medium", "'The bench ruled against the bar' uses",
     "metonymy", "simile", "hyperbole", "onomatopoeia",
     "A", "'The bench' stands for judges and 'the bar' for lawyers - things associated with them."),
    (T_DEV, "Medium", "'The country needs more boots on the ground' is an example of",
     "synecdoche", "apostrophe", "litotes", "paradox",
     "A", "'Boots' (a part of a soldier's equipment) stands for soldiers."),
    (T_DEV, "Medium", "A white dove that appears repeatedly in a poem about war is most likely",
     "a symbol of peace", "an example of onomatopoeia", "a simile for the soldiers", "a pun on 'dove' and 'dived'",
     "A", "The dove conventionally represents peace; a recurring image with such meaning is a symbol."),
    (T_DEV, "Easy", "'The drumming shook the ground and rattled the windows' appeals mainly to the sense of",
     "hearing", "taste", "smell", "sight",
     "A", "This is auditory imagery; the line conveys sound."),
    (T_DEV, "Easy", "'The rough rope burned her palms as she pulled' appeals mainly to the sense of",
     "touch", "sight", "hearing", "smell",
     "A", "The line uses tactile imagery, conveying texture and physical sensation."),
    (T_DEV, "Easy", "'The bitter-leaf soup stung her tongue' appeals mainly to the sense of",
     "taste", "sight", "hearing", "touch",
     "A", "The image is gustatory - it conveys taste."),
    (T_DEV, "Medium", "The metrical foot in the word 'be-LOW', an unstressed syllable followed by a stressed one, is",
     "an iamb", "a trochee", "a dactyl", "a spondee",
     "A", "An iamb is an unstressed syllable followed by a stressed syllable."),
    (T_DEV, "Medium", "The metrical foot in 'GAR-den', a stressed syllable followed by an unstressed one, is",
     "a trochee", "an iamb", "an anapaest", "a spondee",
     "A", "A trochee is a stressed syllable followed by an unstressed syllable."),
    (T_DEV, "Easy", "A stanza of three lines is called",
     "a tercet", "a couplet", "a quatrain", "a sestet",
     "A", "Tercet = three lines; couplet = two; quatrain = four; sestet = six."),
    (T_DEV, "Easy", "A stanza of eight lines is called",
     "an octave", "a quatrain", "a tercet", "a couplet",
     "A", "An octave (or octet) has eight lines, as in the first part of a Petrarchan sonnet."),
    (T_DEV, "Easy", "Four lines of a poem end with the words 'day', 'night', 'play' and 'light'. The rhyme scheme is",
     "abab", "aabb", "abba", "abcd",
     "A", "day/play rhyme (a) and night/light rhyme (b), alternating: abab."),
    (T_DEV, "Medium", "The voice that speaks in a poem, which need not be the poet's own, is called the",
     "persona", "protagonist", "chorus", "antagonist",
     "A", "The persona is the assumed speaker or 'mask' through which a poet speaks."),
    (T_DEV, "Easy", "A writer's choice of words, whether formal, colloquial or technical, is known as",
     "diction", "syntax", "plot", "setting",
     "A", "Diction refers to the selection of words in a literary work."),
    (T_DEV, "Medium", "'The clash and clatter of cracked crockery' uses harsh, jarring sounds. This effect is called",
     "cacophony", "euphony", "assonance", "litotes",
     "A", "Cacophony is the deliberate use of harsh, discordant sounds."),
    (T_DEV, "Medium", "Lines in which soft, flowing sounds produce a pleasing musical effect, such as 'the murmuring of innumerable bees', illustrate",
     "euphony", "cacophony", "hyperbole", "paradox",
     "A", "Euphony is the use of pleasant, harmonious sounds."),
    (T_DEV, "Medium", "'Slowly through the village walked the old priest' reverses the normal order of words. This device is",
     "inversion", "simile", "pun", "irony",
     "A", "Inversion (anastrophe) changes the usual subject-verb-object order for emphasis or rhythm."),
    (T_DEV, "Medium", "'We had rice and beans and plantain and stew and still we were hungry' uses many conjunctions. This device is",
     "polysyndeton", "asyndeton", "oxymoron", "litotes",
     "A", "Polysyndeton is the deliberate repetition of conjunctions."),
    (T_DEV, "Medium", "'He ran, stumbled, rose, ran again' omits conjunctions between the verbs. This device is",
     "asyndeton", "polysyndeton", "apostrophe", "assonance",
     "A", "Asyndeton leaves out conjunctions to quicken the pace."),
    (T_DEV, "Medium", "'The silent snake slid softly across the stones' repeats the hissing /s/ sound. This effect is called",
     "sibilance", "assonance", "onomatopoeia", "hyperbole",
     "A", "Sibilance is the repetition of /s/ or /sh/ sounds, here imitating the snake's hiss."),
    (T_DEV, "Medium", "'Time is a thief that leaves no fingerprints' is an example of",
     "metaphor", "simile", "litotes", "onomatopoeia",
     "A", "Time is identified directly with a thief - an implied comparison."),
    (T_DEV, "Easy", "'She is as stubborn as a locked gate' is an example of",
     "simile", "metaphor", "paradox", "metonymy",
     "A", "The comparison uses 'as ... as', making it a simile."),
    (T_DEV, "Medium", "'Death, you have taken my mother; now leave my children alone' addresses death directly. The device is",
     "apostrophe", "euphemism", "irony", "pun",
     "A", "Speaking to an absent or abstract thing as if present is apostrophe (here also personification)."),
    (T_DEV, "Medium", "'Our neighbour finally answered the last call' is a gentle way of saying that he died. This is",
     "euphemism", "hyperbole", "simile", "antithesis",
     "A", "A mild expression replaces a blunt reference to death."),
    (T_DEV, "Medium", "A poet writes, 'The sun crept out, apologetic, after the storm.' The word 'apologetic' is an example of",
     "personification", "onomatopoeia", "hyperbole", "metonymy",
     "A", "The sun is given a human attitude - being apologetic."),
    (T_DEV, "Medium", "The main effect of a refrain in a poem or song is to",
     "emphasise a key idea and give the poem a musical structure", "introduce a new character in each stanza",
     "conceal the meaning of the poem from the reader", "shorten the poem so that it can be memorised",
     "A", "Repetition at regular intervals stresses the central idea and creates rhythm."),
    (T_DEV, "Medium", "In the line 'The wind wept with the widow', the wind is made to share human grief. This device is called",
     "pathetic fallacy", "hyperbole", "litotes", "synecdoche",
     "A", "Pathetic fallacy attributes human emotions to nature, usually to reflect a character's feelings."),
    (T_DEV, "Medium", "'Cruel kindness' and 'living death' are examples of",
     "oxymoron", "simile", "metonymy", "allusion",
     "A", "Each phrase joins two contradictory words."),
    (T_DEV, "Medium", "In 'Nigeria won the match', the name of the country stands for its football team. The device is",
     "metonymy", "simile", "hyperbole", "pun",
     "A", "The country is named for the team closely associated with it - metonymy."),
    (T_DEV, "Medium", "'The road ahead is dark, and the bridge is broken' said of a nation's future is an example of",
     "metaphor", "simile", "onomatopoeia", "litotes",
     "A", "The nation's future is pictured as a journey along a road, without 'like' or 'as'."),
    (T_DEV, "Medium", "The line 'Ask the traffic. Ask the tray. Ask the silence at home.' relies chiefly on",
     "repetition", "rhyme", "onomatopoeia", "euphemism",
     "A", "The repeated 'Ask the ...' gives the line its insistent force."),
    (T_DEV, "Hard", "A poet describes a corrupt official as 'this honourable thief'. The phrase is an example of",
     "oxymoron", "simile", "euphemism", "onomatopoeia",
     "A", "'Honourable' and 'thief' contradict each other and expose the man's hypocrisy."),
    (T_DEV, "Medium", "'The market was a river of heads' is an example of",
     "metaphor", "simile", "litotes", "apostrophe",
     "A", "The crowd is called a river directly; the comparison is implied."),
    (T_DEV, "Medium", "'Justice is blind, but in this town she also seems deaf' plays on the traditional image of justice. The device is chiefly",
     "irony", "onomatopoeia", "alliteration", "assonance",
     "A", "The remark mocks the failure of justice by extending a familiar image."),
    (T_DEV, "Medium", "A speaker says, 'I could sleep for a year.' This is",
     "hyperbole", "litotes", "oxymoron", "metonymy",
     "A", "The desire for sleep is exaggerated beyond possibility."),
    (T_DEV, "Medium", "The device in 'The pot called the kettle black' when used to describe a hypocrite is",
     "an idiomatic proverb", "an onomatopoeia", "a caesura", "a refrain",
     "A", "The expression is a proverbial saying whose meaning is not literal."),
    (T_DEV, "Easy", "The expression 'as brave as a lion' is a",
     "simile", "metaphor", "euphemism", "pun",
     "A", "It compares using 'as ... as'."),
    (T_DEV, "Medium", "The general term for language that appeals to the senses - sight, sound, smell, taste and touch - is",
     "imagery", "rhyme", "plot", "setting",
     "A", "Imagery is descriptive language that creates sensory impressions."),
    (T_DEV, "Medium", "A poet calls the senators 'our tireless servants, resting in Dubai'. The tone of the line is",
     "sarcastic", "admiring", "nostalgic", "sorrowful",
     "A", "The praise is mock praise; 'resting in Dubai' undercuts 'tireless servants' - the tone is sarcastic."),
    (T_DEV, "Medium", "The emotional atmosphere that a poem creates in the reader is its",
     "mood", "metre", "diction", "rhyme scheme",
     "A", "Mood is the feeling evoked in the reader, distinct from the writer's tone."),
    (T_DEV, "Medium", "'Sweet are the uses of adversity' is a memorable, compressed statement of a truth. Such a statement is",
     "an aphorism", "a caesura", "an aside", "a limerick",
     "A", "An aphorism (or maxim) is a brief, pointed statement of a general truth."),
]

FIX = {}


def build():
    build_batch(
        S, "batch_028_lit_round3a.json", "batch_028_lit_round3a",
        "Literature in English round 3 (part A): twelve new unseen passages (six poems, three prose extracts, three drama extracts) with appreciation questions, plus stand-alone items on literary devices, figures of speech and poetic terms built around fresh example lines.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
