"""Batch 021 - Economics round 3, part A (micro-economics).

Basic concepts, scarcity and choice, scale of preference, production and its factors, division of labour,
economic systems, demand, supply, price determination, elasticity, consumer behaviour, theory of the firm,
costs, revenue and profit, market structures.  Three data passages: a demand/supply schedule with a tax,
a utility schedule and a cost schedule.  Together with batch 022 this takes Economics past 500 curated items.

    python3 scripts/build_content_batch21.py -> content/batch_021_econ_round3a.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Economics"

PASSAGES = [
    ("E1", "Price Determination", "Weekly market for bottled water in a town",
     "The table shows the weekly demand and supply of 75 cl bottled water in a town. Qs1 is the quantity "
     "supplied before a tax of ₦10 per bottle was imposed on sellers and Qs2 is the quantity supplied "
     "after the tax.\n\n"
     "Price (₦)   Qd    Qs1    Qs2\n"
     "   50       400   200    100\n"
     "   55       350   250    150\n"
     "   60       300   300    200\n"
     "   65       250   350    250\n"
     "   70       200   400    300\n"
     "   75       150   450    350"),
    ("E2", "Consumer Behaviour", "Utility a student gets from meat pies",
     "The table shows the total utility (in utils) a student gets from eating meat pies at the school "
     "canteen in one day. Each meat pie costs ₦500 and the student values one util at ₦50.\n\n"
     "Meat pies       1    2    3    4    5\n"
     "Total utility  20   36   48   56   60"),
    ("E3", "Costs of Production", "Weekly costs of a small furniture workshop",
     "The table shows the total cost (TC) of a small workshop for different weekly outputs of dining "
     "tables. Each table sells for ₦60,000.\n\n"
     "Tables made     0    1    2    3    4    5\n"
     "TC (₦000)      50   80  100  130  180  250"),
]

PQ = [
    ("E1", "Easy", "From the table above, the equilibrium price before the tax was",
     "₦60", "₦55", "₦65", "₦70", "A",
     "Before the tax, quantity demanded equals quantity supplied (300 bottles) at ₦60.", "60"),
    ("E1", "Easy", "From the table above, the equilibrium quantity traded before the tax was",
     "300 bottles", "250 bottles", "350 bottles", "400 bottles", "A",
     "At the pre-tax equilibrium price of ₦60, both Qd and Qs1 are 300 bottles.", "300"),
    ("E1", "Medium", "From the table above, at a price of ₦75 before the tax the market would have",
     "a surplus of 300 bottles", "a shortage of 300 bottles", "a surplus of 150 bottles", "a shortage of 450 bottles", "A",
     "At ₦75, Qs1 (450) exceeds Qd (150) by 300 bottles, so there is excess supply.", "300"),
    ("E1", "Medium", "From the table above, the equilibrium price after the tax was imposed is",
     "₦65", "₦60", "₦70", "₦75", "A",
     "After the tax, Qd equals Qs2 (250 bottles) at ₦65.", "65"),
    ("E1", "Hard", "From the table above, the part of the ₦10 tax per bottle that is passed on to consumers is",
     "₦5", "₦10", "₦2.50", "nothing", "A",
     "The price paid by consumers rose from ₦60 to ₦65, so consumers bear ₦5 of the tax and sellers bear the other ₦5.", "5"),
    ("E1", "Medium", "From the table above, the government's weekly revenue from the tax is",
     "₦2,500", "₦3,000", "₦2,000", "₦6,500", "A",
     "After the tax 250 bottles are sold each week; 250 × ₦10 = ₦2,500.", "250*10"),
    ("E1", "Hard", "Using the table above, the price elasticity of demand when the price falls from ₦60 to ₦50 (original values) is",
     "2.0", "0.5", "1.0", "1.5", "A",
     "Quantity rises by 100 from 300 (33.3%); price falls by ₦10 from ₦60 (16.7%); 33.3 ÷ 16.7 = 2.0, so demand is elastic.", "(100/300)/(10/60)"),
    ("E1", "Medium", "From the table above, if the government had fixed a maximum price of ₦50 before the tax, the market would have had",
     "a shortage of 200 bottles", "a surplus of 200 bottles", "a shortage of 400 bottles", "no shortage or surplus", "A",
     "At ₦50, Qd is 400 but Qs1 is only 200, leaving excess demand of 200 bottles.", "200"),
    ("E1", "Medium", "Comparing Qs2 with Qs1 in the table above, the effect of the tax on the supply curve is that it",
     "shifted to the left, with less supplied at every price", "shifted to the right, with more supplied at every price", "became a vertical line at 250 bottles", "was unchanged, but demand shifted to the left", "A",
     "At every price Qs2 is 100 bottles less than Qs1: the tax raised sellers' costs and shifted supply leftwards (upwards)."),
    ("E2", "Easy", "From the table above, the marginal utility of the third meat pie is",
     "12 utils", "48 utils", "16 utils", "8 utils", "A",
     "Marginal utility = change in total utility: 48 − 36 = 12 utils.", "48-36"),
    ("E2", "Easy", "From the table above, the marginal utility of the fifth meat pie is",
     "4 utils", "60 utils", "8 utils", "12 utils", "A",
     "Marginal utility of the fifth pie = 60 − 56 = 4 utils.", "60-56"),
    ("E2", "Medium", "The pattern of marginal utility in the table above illustrates the",
     "law of diminishing marginal utility", "law of diminishing returns", "law of demand", "law of comparative advantage", "A",
     "Each extra meat pie adds less satisfaction than the one before (20, 16, 12, 8, 4 utils)."),
    ("E2", "Hard", "From the table above, the number of meat pies the student should buy to maximise satisfaction is",
     "3", "5", "4", "2", "A",
     "Buy while the money value of marginal utility (MU × ₦50) is at least the price of ₦500, i.e. MU ≥ 10 utils: pies 1, 2 and 3 (MU 20, 16, 12). The fourth pie is worth only 8 × ₦50 = ₦400.", "3"),
    ("E2", "Hard", "If the price of a meat pie in the table above fell to ₦300, the student would buy",
     "4 pies", "3 pies", "5 pies", "2 pies", "A",
     "Now buy while MU × ₦50 ≥ ₦300, i.e. MU ≥ 6 utils: the fourth pie (MU 8, worth ₦400) is bought but the fifth (MU 4, worth ₦200) is not.", "4"),
    ("E2", "Medium", "From the table above, the average utility per pie when four pies are eaten is",
     "14 utils", "56 utils", "8 utils", "16 utils", "A",
     "Average utility = total utility ÷ quantity = 56 ÷ 4 = 14 utils.", "56/4"),
    ("E2", "Medium", "From the table above, total utility keeps rising from the first to the fifth pie but at a decreasing rate because",
     "each extra pie adds less satisfaction than the one before", "the price of meat pies rises with each one bought", "the student's income falls as she buys more pies", "the canteen reduces the size of each extra pie sold", "A",
     "Marginal utility is positive but falling, so total utility rises more slowly with each additional pie."),
    ("E3", "Easy", "From the table above, the workshop's total fixed cost per week is",
     "₦50,000", "₦80,000", "₦30,000", "₦250,000", "A",
     "Fixed cost is the cost incurred when output is zero: ₦50,000.", "50000"),
    ("E3", "Medium", "From the table above, the total variable cost of making 3 tables is",
     "₦80,000", "₦130,000", "₦50,000", "₦30,000", "A",
     "TVC = TC − TFC = 130,000 − 50,000 = ₦80,000.", "130000-50000"),
    ("E3", "Medium", "From the table above, the average variable cost when 4 tables are made is",
     "₦32,500", "₦45,000", "₦12,500", "₦50,000", "A",
     "TVC at 4 tables = 180,000 − 50,000 = 130,000; 130,000 ÷ 4 = ₦32,500.", "(180000-50000)/4"),
    ("E3", "Medium", "From the table above, the marginal cost of the fifth table is",
     "₦70,000", "₦50,000", "₦250,000", "₦20,000", "A",
     "MC = change in total cost = 250,000 − 180,000 = ₦70,000.", "250000-180000"),
    ("E3", "Easy", "From the table above, the average total cost when 2 tables are made is",
     "₦50,000", "₦25,000", "₦100,000", "₦40,000", "A",
     "ATC = TC ÷ output = 100,000 ÷ 2 = ₦50,000.", "100000/2"),
    ("E3", "Medium", "From the table above, the average fixed cost when 5 tables are made is",
     "₦10,000", "₦50,000", "₦40,000", "₦12,500", "A",
     "AFC = TFC ÷ output = 50,000 ÷ 5 = ₦10,000; average fixed cost falls as output rises.", "50000/5"),
    ("E3", "Hard", "From the table above, marginal cost is lowest for the",
     "second table", "first table", "third table", "fifth table", "A",
     "Marginal costs are ₦30,000, ₦20,000, ₦30,000, ₦50,000 and ₦70,000 for the 1st to 5th tables; the second table costs least to add."),
    ("E3", "Hard", "From the table above, with tables selling at ₦60,000 each, the workshop's profit when it makes 4 tables is",
     "₦60,000", "₦50,000", "₦240,000", "₦180,000", "A",
     "TR = 4 × 60,000 = 240,000; TC = 180,000; profit = ₦60,000 (making a fifth table would add ₦70,000 to cost but only ₦60,000 to revenue).", "240000-180000"),
]

Q = [
    # ---------------- Basic Economic Concepts ----------------
    ("Basic Economic Concepts", "Easy", "Economics is regarded as a social science because it",
     "studies human choices about scarce resources in a systematic way", "uses laboratory experiments to prove every one of its theories", "deals only with the production of goods in factories and on farms", "is concerned mainly with how governments raise and spend taxes", "A",
     "Economics studies human behaviour (choice under scarcity) using systematic methods of observation and analysis."),
    ("Basic Economic Concepts", "Medium", "A minister says, \"The government SHOULD remove the fuel subsidy in order to save money.\" This statement is",
     "a normative statement", "a positive statement", "an economic law", "a scientific fact", "A",
     "It expresses an opinion about what ought to be done, which is normative; positive statements describe what is and can be tested."),
    ("Basic Economic Concepts", "Easy", "Which of the following is a topic in microeconomics?",
     "the pricing of sachet water in a local market", "the rate of inflation in Nigeria", "the level of national unemployment", "the growth of the country's total output", "A",
     "Microeconomics studies individual units such as a single market, firm or consumer; the others are economy-wide (macro) issues."),
    ("Basic Economic Concepts", "Medium", "The basic economic question \"for whom to produce\" is concerned with",
     "how output is shared among the members of society", "the choice of technique used in production", "the types of goods a country decides to produce", "the quantity of resources available to producers", "A",
     "\"For whom\" is the distribution question; \"what\" concerns the goods chosen and \"how\" concerns the method of production."),
    ("Basic Economic Concepts", "Easy", "Bread bought by a family for breakfast is a ______ while the flour bought by the bakery to make it is a ______.",
     "consumer good; producer good", "producer good; consumer good", "free good; economic good", "durable good; capital good", "A",
     "Goods used directly to satisfy wants are consumer goods; goods used to produce other goods are producer (capital) goods."),
    ("Basic Economic Concepts", "Medium", "Air in the open atmosphere is classified as a free good because it",
     "is available in abundance and commands no price", "is provided by the government at no charge", "cannot be seen or touched by the consumer", "is not needed for any productive activity", "A",
     "A free good exists in such abundance relative to wants that it has no opportunity cost and no price."),
    ("Basic Economic Concepts", "Easy", "The work done by a teacher in a classroom is classified in economics as",
     "a service", "a free good", "a capital good", "a durable good", "A",
     "Services are intangible economic goods that satisfy wants; they are consumed as they are produced."),
    ("Basic Economic Concepts", "Easy", "The fundamental economic problem facing every society is that",
     "human wants are unlimited while resources are limited", "governments never have enough money to spend", "the prices of goods rise every year", "workers are not paid enough for their labour", "A",
     "Scarcity of resources relative to unlimited wants forces every society to make choices."),
    ("Basic Economic Concepts", "Medium", "In economics, wealth refers to",
     "the stock of valuable goods owned at a point in time", "the flow of money a person earns within a year", "the total amount of cash kept in a bank account", "any item that satisfies a want without any payment", "A",
     "Wealth is a stock of economic goods (houses, land, machinery, shares) that have value and are owned; income is a flow."),
    ("Basic Economic Concepts", "Medium", "A student's monthly allowance of ₦20,000 is an example of",
     "income, which is a flow", "wealth, which is a stock", "capital, which is a stock", "savings, which is a stock", "A",
     "Income is measured per period of time (a flow); wealth and capital are measured at a point in time (stocks)."),
    ("Basic Economic Concepts", "Medium", "The statement \"a rise in the price of rice will reduce the quantity of rice demanded\" is positive because it",
     "can be tested against evidence", "expresses the opinion of consumers", "is always true in every country", "was made by a government official", "A",
     "Positive statements are about what is and can be verified or refuted by facts; they contain no value judgement."),
    ("Basic Economic Concepts", "Easy", "Macroeconomics is concerned with",
     "the economy as a whole, such as total output and the price level", "the behaviour of one consumer choosing goods in a single market", "the pricing decision of a single firm selling one product", "the wages paid to the workers in one small local industry", "A",
     "Macroeconomics studies aggregates: national income, employment, inflation and growth."),
    # ---------------- Scarcity, Choice and Opportunity Cost ----------------
    ("Scarcity, Choice and Opportunity Cost", "Medium", "A farmer's plot can produce maize worth ₦300,000, cassava worth ₦250,000 or yam worth ₦200,000 in a season. If he grows maize, his opportunity cost is",
     "₦250,000 worth of cassava", "₦200,000 worth of yam", "₦450,000 worth of cassava and yam", "₦300,000 worth of maize", "A",
     "Opportunity cost is the value of the next best alternative forgone, which is the cassava.", "250000"),
    ("Scarcity, Choice and Opportunity Cost", "Easy", "Scarcity in economics means that",
     "resources are limited relative to the wants they must satisfy", "goods are not available in the shops during a shortage", "a country is poor and most of its people are unemployed", "the government has banned the importation of some goods", "A",
     "Even rich countries face scarcity: resources are never enough to satisfy all wants."),
    ("Scarcity, Choice and Opportunity Cost", "Easy", "A state government with a limited budget builds a hospital instead of a stadium. The stadium forgone is the",
     "opportunity cost of the hospital", "money cost of the hospital", "social benefit of the hospital", "real income of the state", "A",
     "The alternative sacrificed when a choice is made is the opportunity (real) cost of that choice."),
    ("Scarcity, Choice and Opportunity Cost", "Easy", "Choice is necessary in economics because",
     "resources are scarce relative to human wants", "consumers do not know what they want", "prices are fixed by the government", "producers make too many kinds of goods", "A",
     "Since limited resources cannot satisfy every want, individuals and societies must choose which wants to satisfy."),
    ("Scarcity, Choice and Opportunity Cost", "Medium", "A country producing on its production possibility curve can increase its output of cars only by",
     "reducing its output of the other good", "employing its idle resources", "importing more raw materials", "raising the price of cars", "A",
     "On the curve all resources are fully and efficiently used, so more of one good means less of the other."),
    ("Scarcity, Choice and Opportunity Cost", "Medium", "A point inside a country's production possibility curve indicates",
     "unemployment or inefficient use of resources", "full employment of all resources", "a combination that cannot be attained", "economic growth in the economy", "A",
     "Inside the frontier the economy is producing less than it could, so some resources are idle or wasted."),
    ("Scarcity, Choice and Opportunity Cost", "Medium", "A combination of goods lying outside the production possibility curve is",
     "unattainable with present resources and technology", "attainable only if some resources are left idle", "the most efficient point for the economy", "attainable by reducing the output of one good", "A",
     "Points beyond the frontier require more resources or better technology than the economy currently has."),
    ("Scarcity, Choice and Opportunity Cost", "Medium", "Which of the following would shift a country's production possibility curve outwards?",
     "the discovery of new oil fields and improved technology", "an increase in the prices of the two goods", "a decision to produce more of one good", "a rise in the level of unemployment", "A",
     "The frontier shifts outwards when the quantity or quality of resources rises or technology improves."),
    ("Scarcity, Choice and Opportunity Cost", "Easy", "A student spends Saturday at a friend's party instead of working at a shop that would have paid her ₦3,000. The opportunity cost of attending the party is",
     "the ₦3,000 wage she gave up", "the cost of transport to the party", "the food and drinks served at the party", "nothing, because the party was free", "A",
     "Opportunity cost is the best alternative forgone, here the ₦3,000 she could have earned."),
    ("Scarcity, Choice and Opportunity Cost", "Medium", "The opportunity cost of using a resource is zero when the resource",
     "has no alternative use", "is owned by the government", "is very expensive to buy", "is used by many people at once", "A",
     "If nothing else could have been done with the resource, nothing is sacrificed by using it; free goods are an example."),
    ("Scarcity, Choice and Opportunity Cost", "Medium", "A production possibility curve that is a straight line shows that",
     "the opportunity cost of each good is constant", "the opportunity cost rises as more is produced", "resources are not fully employed", "one good cannot be produced at all", "A",
     "A constant slope means a fixed amount of one good is given up for each extra unit of the other."),
    ("Scarcity, Choice and Opportunity Cost", "Medium", "The concept of opportunity cost is useful to a government because it",
     "helps it to allocate limited revenue among competing projects", "guarantees that all projects will be completed on time", "removes the need to collect taxes from citizens", "ensures that prices of goods remain stable", "A",
     "Weighing what must be given up for each project guides the choice among competing uses of scarce public funds."),
    ("Scarcity, Choice and Opportunity Cost", "Hard", "A university degree costs ₦2 million in fees, and the student could have earned ₦1.5 million by working during the four years. The economic (opportunity) cost of the degree is",
     "₦3.5 million", "₦2 million", "₦1.5 million", "₦0.5 million", "A",
     "Economic cost includes both the money paid out and the earnings forgone: 2 + 1.5 = ₦3.5 million.", "3.5"),
    # ---------------- Scale of Preference ----------------
    ("Scale of Preference", "Easy", "Before going to the market, Bola writes down everything she needs and numbers the items from the most pressing to the least pressing. In economics her list is called",
     "a scale of preference", "a price list of goods in the market", "a budget deficit statement", "a demand schedule for the goods", "A",
     "Consumers rank their wants so that the most pressing are satisfied first with the limited means available."),
    ("Scale of Preference", "Medium", "Ada earns ₦30,000 a month and ranks her wants as: rent ₦15,000, food ₦10,000, data ₦4,000, cinema ₦3,000 and new shoes ₦5,000. Satisfying her wants in that order, the number of wants she can fully satisfy this month is",
     "3", "4", "5", "2", "A",
     "Rent + food + data = ₦29,000; the remaining ₦1,000 cannot fully pay for the cinema or the shoes.", "3"),
    ("Scale of Preference", "Easy", "The main reason a consumer draws up a scale of preference is that",
     "her income cannot satisfy all her wants at once", "the government requires every consumer to do so", "prices of goods are the same in all markets", "she has more money than she needs to spend", "A",
     "Because means are limited relative to wants, ranking wants ensures the most important ones are met first."),
    ("Scale of Preference", "Easy", "A scale of preference helps a consumer to",
     "make a rational choice among competing wants", "increase the amount of income she earns", "reduce the prices charged by sellers", "avoid paying tax on the goods she buys", "A",
     "It shows which wants to satisfy first and which to postpone, so spending is rational."),
    ("Scale of Preference", "Medium", "A business ranks its projects as: (1) buy a generator, (2) repaint the shop, (3) buy a delivery van, and has money for only one. It should undertake",
     "the generator; the repainting is its opportunity cost", "the van; the generator is its opportunity cost", "the repainting; the van is its opportunity cost", "the generator; the van is its opportunity cost", "A",
     "The top-ranked project is chosen and the next best alternative forgone (repainting) is the opportunity cost."),
    ("Scale of Preference", "Medium", "Which of the following is TRUE of a scale of preference?",
     "it differs from one person to another", "it is the same for everyone with equal income", "it lists wants in the order they are remembered", "it is prepared only by governments and firms", "A",
     "Tastes and circumstances differ, so two people with the same income may rank their wants differently."),
    ("Scale of Preference", "Medium", "When a consumer's income rises while prices stay the same, her scale of preference",
     "allows more of the listed wants to be satisfied", "must be discarded because it no longer applies", "becomes shorter because wants disappear", "is no longer needed for rational choice", "A",
     "The ranking may remain, but the higher income lets her move further down the list of wants."),
    ("Scale of Preference", "Medium", "The want placed at the top of a rational consumer's scale of preference is the one that",
     "gives the greatest satisfaction relative to the others", "has the lowest price in the market", "is advertised most on radio and television", "was bought most recently by the consumer", "A",
     "Rational consumers rank wants by the satisfaction they give, not by price or advertising alone."),
    # ---------------- Production ----------------
    ("Production", "Medium", "In economics, production is said to be complete when the good",
     "reaches the final consumer", "leaves the factory gate", "is stored in the warehouse", "is advertised on television", "A",
     "Production includes distribution: it ends only when the good or service reaches the person who uses it."),
    ("Production", "Easy", "A fisherman catching fish in the Lagos lagoon is engaged in",
     "primary production", "secondary production", "tertiary production", "indirect production", "A",
     "Primary production extracts raw materials directly from nature (fishing, farming, mining)."),
    ("Production", "Easy", "Turning cassava into garri in a processing plant is an example of",
     "secondary production", "primary production", "tertiary production", "subsistence production", "A",
     "Secondary production converts raw materials into finished or semi-finished goods."),
    ("Production", "Easy", "A bank cashier and a lorry driver are both engaged in",
     "tertiary production", "primary production", "secondary production", "direct production", "A",
     "Both provide services (commercial and transport services), which is tertiary production."),
    ("Production", "Medium", "Direct production differs from indirect production in that direct production",
     "is carried out to satisfy the producer's own wants", "always takes place in large factories", "involves the use of money as a medium of exchange", "requires a high degree of division of labour", "A",
     "In direct (subsistence) production people make what they themselves consume; indirect production is for exchange."),
    ("Production", "Easy", "The ultimate aim of production is to",
     "create utility to satisfy human wants", "provide employment for the citizens", "earn foreign exchange for the country", "increase the population of a country", "A",
     "Goods and services are produced because they have utility, that is, the ability to satisfy wants."),
    ("Production", "Medium", "A tailor who sews cloth into a dress creates",
     "form utility", "place utility", "time utility", "possession utility", "A",
     "Changing the form of a material into a more useful product creates form utility."),
    ("Production", "Medium", "A trader who buys yams cheaply in Benue and sells them in Lagos creates",
     "place utility", "form utility", "time utility", "service utility", "A",
     "Moving goods from where they are plentiful to where they are wanted creates place utility."),
    ("Production", "Medium", "Storing grains after the harvest and selling them during the dry season creates",
     "time utility", "form utility", "place utility", "marginal utility", "A",
     "Making goods available when they are wanted, rather than when produced, creates time utility."),
    ("Production", "Easy", "Which of the following is an example of tertiary production?",
     "a lawyer defending a client in court", "a miner digging tin in Jos", "a weaver making aso-oke cloth", "a farmer growing rice in Kebbi", "A",
     "Tertiary production consists of services; the others are primary (mining, farming) and secondary (weaving)."),
    ("Production", "Easy", "Which of the following is NOT a stage of production?",
     "consumption of the finished good", "extraction of raw materials", "manufacturing of goods", "distribution of goods to consumers", "A",
     "Consumption is the use of goods to satisfy wants; extraction, manufacturing and distribution are the stages of production."),
    ("Production", "Medium", "Economists regard a retailer as a producer because he",
     "adds place and possession utility to goods", "manufactures the goods that he sells", "fixes the prices of goods in the economy", "employs more workers than a farmer", "A",
     "By making goods available where and when consumers want them, the retailer adds utility, which is production."),
    ("Production", "Easy", "A farmer who grows food crops only for his own family is engaged in",
     "subsistence production", "commercial production", "tertiary production", "indirect production", "A",
     "Producing for one's own consumption rather than for sale or exchange is subsistence (direct) production."),
    # ---------------- Factors of Production ----------------
    ("Factors of Production", "Easy", "A landowner in Abuja receives ₦2 million a year from a company that uses his plot as a car park. In economics this payment is",
     "rent, the reward for land", "interest, the reward for capital", "profit, the reward for enterprise", "wages, the reward for labour", "A",
     "Payment for the use of land (a gift of nature) is rent; labour earns wages, capital interest and enterprise profit."),
    ("Factors of Production", "Medium", "Capital as a factor of production is best described as",
     "man-made goods used to produce other goods", "the money a firm keeps in its bank account", "the shares issued by a public company", "any natural resource used in production", "A",
     "Machines, tools, buildings and equipment are capital because they are produced goods used for further production."),
    ("Factors of Production", "Easy", "In economics, land includes",
     "all natural resources such as forests, rivers and minerals", "only the soil used for growing crops", "buildings and roads constructed on the soil", "the machines used to cultivate a farm", "A",
     "Land covers all gifts of nature: the soil, minerals, water, forests and climate."),
    ("Factors of Production", "Medium", "A distinguishing feature of land as a factor of production is that",
     "its total supply is fixed", "its reward is called interest", "it can be moved from place to place", "it is produced by human effort", "A",
     "The total quantity of land cannot be increased by human effort, so it is fixed in supply and geographically immobile."),
    ("Factors of Production", "Medium", "Labour differs from the other factors of production in that it",
     "cannot be separated from the person who supplies it", "is the only factor that receives a reward", "is never affected by changes in technology", "can be stored and used at a later date", "A",
     "Labour is human effort; the worker must be present to supply it, and unused labour time is lost."),
    ("Factors of Production", "Easy", "Interest is the reward for",
     "capital", "land", "labour", "entrepreneurship", "A",
     "Interest is paid for the use of capital (or the funds used to acquire it)."),
    ("Factors of Production", "Medium", "The entrepreneur differs from a salaried manager in that the entrepreneur",
     "bears the risk of the business", "supervises the daily work of employees", "receives a fixed monthly income", "cannot own shares in the business", "A",
     "The entrepreneur organises the other factors and bears the uncertainty of loss; the manager is a paid employee."),
    ("Factors of Production", "Medium", "On a cocoa farm in Ondo State, the cocoa trees planted by the farmer are ______ while the soil is ______.",
     "capital; land", "land; capital", "labour; land", "capital; labour", "A",
     "The trees were produced by human effort to yield future output (capital); the soil is a gift of nature (land)."),
    ("Factors of Production", "Easy", "The efficiency of labour can be increased by",
     "training, good health and better tools", "reducing the wages paid to workers", "increasing the number of public holidays", "employing more workers on the same job", "A",
     "Education, training, health, motivation and the quality of equipment all raise output per worker."),
    ("Factors of Production", "Medium", "Which of the following would increase the supply of labour in a country?",
     "an increase in the population of working age", "a reduction in the normal working week", "a rise in the school-leaving age", "an increase in the emigration of young people", "A",
     "More people of working age means more labour available; the other changes reduce the hours or numbers offered."),
    ("Factors of Production", "Easy", "A teacher in Kano who accepts a teaching post in Ibadan shows",
     "geographical mobility of labour", "occupational mobility of labour", "vertical mobility of labour", "industrial mobility of capital", "A",
     "Moving from one place to another in the same occupation is geographical mobility."),
    ("Factors of Production", "Easy", "A bank cashier who retrains and becomes a nurse shows",
     "occupational mobility of labour", "geographical mobility of labour", "horizontal mobility of capital", "immobility of labour", "A",
     "Changing from one occupation to another is occupational mobility."),
    ("Factors of Production", "Medium", "Wages differ between occupations mainly because of differences in",
     "the skill and training required and the demand for each type of labour", "the number of public holidays enjoyed in each occupation", "the age of the workers employed in each occupation", "the distance between the workers' homes and their offices", "A",
     "Scarce skills that take long training and are in high demand command higher wages."),
    # ---------------- Division of Labour and Specialization ----------------
    ("Division of Labour and Specialization", "Easy", "Division of labour is limited mainly by",
     "the size of the market", "the number of public holidays", "the level of taxation", "the price of raw materials", "A",
     "A producer can only split work into specialised tasks if the market is large enough to absorb the extra output."),
    ("Division of Labour and Specialization", "Easy", "An advantage of division of labour to a firm is that it",
     "increases output per worker", "makes workers independent of one another", "removes the need for machines", "reduces the size of the market", "A",
     "Practice makes workers more skilful and less time is wasted moving between tasks, so productivity rises."),
    ("Division of Labour and Specialization", "Easy", "A disadvantage of division of labour to the worker is",
     "monotony from repeating one task all day", "an increase in the time taken to learn the job", "a fall in the total output of the factory", "the need to buy his own tools and machines", "A",
     "Doing the same small task repeatedly becomes boring and can reduce job satisfaction."),
    ("Division of Labour and Specialization", "Medium", "A country that concentrates on producing cocoa and imports most other goods is practising",
     "international specialisation", "division of labour by process", "subsistence production", "import substitution", "A",
     "When countries concentrate on the goods they produce best and trade for others, they specialise internationally."),
    ("Division of Labour and Specialization", "Medium", "Division of labour makes the use of machines possible because",
     "each task is broken into simple, repetitive operations", "workers no longer need to be trained", "machines are cheaper than human labour", "the market for the product becomes smaller", "A",
     "Simple, repetitive operations can be mechanised more easily than a complex job done by one craftsman."),
    ("Division of Labour and Specialization", "Medium", "Specialisation by a country in one or two export crops is risky because",
     "a fall in the world price of the crops hurts the whole economy", "the country cannot use money as a medium of exchange", "farmers will refuse to grow any other crop", "the crops cannot be transported to other countries", "A",
     "Over-dependence on a few products exposes the economy to price and demand shocks in the world market."),
    ("Division of Labour and Specialization", "Medium", "Division of labour increases the need for",
     "a medium of exchange", "subsistence farming", "barter trading", "direct production", "A",
     "Specialised workers produce more than they need of one thing and must exchange the surplus, which money makes easy."),
    ("Division of Labour and Specialization", "Easy", "A one-man barbing salon cannot practise division of labour mainly because",
     "the scale of the business is too small", "barbing cannot be broken into separate tasks", "the barber has no training", "customers prefer to be served by one person", "A",
     "Division of labour requires enough workers and enough work to split; a one-man business has neither."),
    ("Division of Labour and Specialization", "Medium", "Adam Smith used the example of a pin factory to show that",
     "division of labour greatly increases output", "pins are the most important manufactured good", "large factories always make losses", "workers should own the factories they work in", "A",
     "Smith observed that ten specialised workers made far more pins per day than ten working separately."),
    ("Division of Labour and Specialization", "Medium", "A worker who spends years fixing only car tyres on an assembly line and can no longer build a complete car has suffered",
     "loss of craftsmanship", "occupational mobility", "structural unemployment", "diminishing returns", "A",
     "Narrow specialisation can destroy the all-round skill of the craftsman who once made the whole product."),
    ("Division of Labour and Specialization", "Medium", "Specialisation by process in a car assembly plant makes workers",
     "interdependent, so a stoppage in one section can halt production", "independent, so each can finish a car alone", "less skilled in the tasks they perform", "unwilling to use machines in their work", "A",
     "Each section depends on the output of the previous one, so a strike or breakdown in one section affects all."),
    # ---------------- Economic Systems ----------------
    ("Economic Systems", "Easy", "In a free market economy, the basic economic problems are solved through",
     "the price mechanism", "central planning", "government decrees", "custom and tradition", "A",
     "Prices set by demand and supply signal what to produce, how to produce and for whom."),
    ("Economic Systems", "Easy", "The main feature of a capitalist economy is",
     "private ownership of the means of production", "state ownership of all industries", "the absence of money and prices", "equal distribution of income", "A",
     "In capitalism individuals own resources and firms and make decisions in pursuit of profit."),
    ("Economic Systems", "Medium", "An advantage of a centrally planned economy is that",
     "resources can be directed to socially desirable goods", "consumers have the widest choice of goods", "prices respond quickly to changes in demand", "individuals are free to set up any business", "A",
     "The planning authority can ensure essential goods and services are produced even if they are not the most profitable."),
    ("Economic Systems", "Medium", "A disadvantage of the free market economy is that it",
     "may neglect the provision of public goods", "removes the profit motive from producers", "gives consumers no freedom of choice", "requires a large planning bureaucracy", "A",
     "Private firms cannot profitably supply goods like street lighting and defence, so markets under-provide them."),
    ("Economic Systems", "Medium", "Street lighting is usually provided by the government rather than by private firms because",
     "nobody can be excluded from enjoying it once it is provided", "it is more expensive than any other public service", "private firms are not allowed to own electric bulbs", "it is consumed only by the very poor in society", "A",
     "Non-excludability means private firms cannot charge users, so public goods would not be supplied by the market."),
    ("Economic Systems", "Medium", "In a mixed economy, the government intervenes in the market mainly to",
     "correct the failures of the free market", "abolish private ownership of property", "fix the prices of all goods and services", "prevent consumers from saving money", "A",
     "Mixed economies combine private enterprise with state action to provide public goods, regulate monopolies and redistribute income."),
    ("Economic Systems", "Easy", "Which of the following countries operated a centrally planned economy for most of the twentieth century?",
     "the Soviet Union", "the United States", "Japan", "Nigeria", "A",
     "The Soviet Union's economy was directed by state plans from the 1920s until its collapse in 1991."),
    ("Economic Systems", "Medium", "A characteristic of a socialist economy is that",
     "prices are fixed by the state rather than by demand and supply", "firms compete freely to maximise their profits", "the means of production belong to private individuals", "consumers decide what is produced through their spending", "A",
     "Under socialism the state owns the major means of production and sets prices and output targets."),
    ("Economic Systems", "Easy", "In a traditional (subsistence) economy, what to produce is decided mainly by",
     "custom and tradition", "the price mechanism", "a central planning board", "multinational companies", "A",
     "People produce what their ancestors produced, using traditional methods, largely for their own consumption."),
    ("Economic Systems", "Medium", "Consumer sovereignty means that",
     "consumers' spending decisions determine what is produced", "the government protects consumers from high prices", "consumers are members of the country's parliament", "producers decide what consumers should buy", "A",
     "In a market economy producers respond to the pattern of consumer demand, so consumers ultimately direct production."),
    ("Economic Systems", "Medium", "Nigeria's sale of state-owned enterprises such as NITEL and the power companies to private investors moved the economy",
     "towards greater reliance on the market", "towards a centrally planned system", "back to a subsistence economy", "away from private ownership of firms", "A",
     "Privatisation transfers production decisions from the state to private owners guided by the market."),
    ("Economic Systems", "Medium", "Adam Smith's \"invisible hand\" refers to",
     "the way self-interest in free markets promotes the good of society", "the secret control of the economy by the government", "the influence of foreign firms on a nation's economy", "the power of trade unions to fix wages", "A",
     "Smith argued that individuals pursuing their own gain are led, as if by an invisible hand, to serve society through the market."),
    # ---------------- Demand ----------------
    ("Demand", "Easy", "Effective demand refers to",
     "the desire for a good backed by the ability and willingness to pay", "the total quantity of a good produced in the economy", "the desire for a good that a consumer cannot afford", "the amount of a good that the government supplies", "A",
     "In economics, demand means desire backed by purchasing power at a given price and time."),
    ("Demand", "Easy", "A trader noticed that whenever she reduced the price of her oranges, customers bought more of them. This everyday observation illustrates the law of demand, which states that, other things being equal,",
     "the higher the price, the lower the quantity demanded", "the higher the price, the higher the quantity demanded", "quantity demanded does not change with price", "demand rises whenever supply rises", "A",
     "Price and quantity demanded are inversely related, giving a downward-sloping demand curve."),
    ("Demand", "Medium", "A movement along the demand curve for garri is caused by",
     "a change in the price of garri", "a change in consumers' incomes", "a change in the price of rice", "a change in consumers' tastes", "A",
     "Only a change in the good's own price moves along the curve; other factors shift the whole curve."),
    ("Demand", "Medium", "Which of the following will shift the demand curve for a brand of powdered milk to the right?",
     "an increase in consumers' incomes", "a fall in the price of the milk itself", "a fall in the price of a rival brand", "a health report linking the brand to illness", "A",
     "Higher income raises demand for a normal good at every price; the own-price change is a movement, the others reduce demand."),
    ("Demand", "Medium", "Petrol and cars are ______ goods, so a large rise in the price of petrol will ______ the demand for cars.",
     "complementary; reduce", "substitute; increase", "complementary; increase", "inferior; reduce", "A",
     "Goods used together are complements: dearer petrol makes running a car costlier and reduces demand for cars."),
    ("Demand", "Easy", "If the price of tea rises sharply, the demand for coffee is likely to",
     "increase, because the two are substitutes", "decrease, because the two are complements", "remain unchanged, because they are unrelated", "fall to zero, because consumers switch to tea", "A",
     "Tea and coffee satisfy the same want; when one becomes dearer, consumers switch to the other."),
    ("Demand", "Easy", "A good whose demand rises when consumers' incomes rise is",
     "a normal good", "an inferior good", "a Giffen good", "a free good", "A",
     "Normal goods have positive income elasticity of demand."),
    ("Demand", "Medium", "As workers in a town received higher salaries, their purchases of garri fell while purchases of rice rose. For these workers, garri is",
     "an inferior good", "a normal good", "a luxury good", "a complementary good", "A",
     "Demand for an inferior good falls as income rises because consumers switch to preferred alternatives."),
    ("Demand", "Medium", "A wealthy man buys a very expensive wristwatch precisely because its high price displays his status. The watch is",
     "an ostentatious (Veblen) good", "an inferior good", "a Giffen good", "a producer good", "A",
     "For goods of ostentation, a higher price increases their appeal, an exception to the law of demand."),
    ("Demand", "Easy", "The demand for bricklayers depends on the demand for new houses. The demand for bricklayers is",
     "derived demand", "joint demand", "composite demand", "competitive demand", "A",
     "Factors of production are demanded not for their own sake but for the goods they help to produce."),
    ("Demand", "Easy", "The demand for exercise books and biros together at the start of a school term is an example of",
     "joint demand", "composite demand", "derived demand", "competitive demand", "A",
     "Joint (complementary) demand arises when goods are wanted together to satisfy one want."),
    ("Demand", "Easy", "Palm oil is demanded for cooking, soap-making and margarine production. The demand for palm oil is",
     "composite demand", "joint demand", "derived demand", "competitive demand", "A",
     "Composite demand is demand for a good that has several different uses."),
    ("Demand", "Easy", "Consumers choosing between two rival brands of instant noodles illustrate",
     "competitive demand", "joint demand", "composite demand", "derived demand", "A",
     "When goods are substitutes for each other, their demands are competitive."),
    ("Demand", "Easy", "Other things being equal, a fall in the price of a good leads to",
     "an extension of demand along the same curve", "a shift of the demand curve to the right", "a contraction of demand along the same curve", "a shift of the demand curve to the left", "A",
     "A change in the good's own price causes a movement along the curve; a fall in price extends quantity demanded."),
    ("Demand", "Medium", "The market demand curve for a good is obtained by",
     "adding the quantities demanded by all consumers at each price", "multiplying the price by the number of consumers", "adding the prices paid by all the consumers", "taking the demand of the largest single buyer", "A",
     "Market demand is the horizontal summation of individual demand curves."),
    ("Demand", "Medium", "Which of the following is an exception to the law of demand?",
     "goods bought in larger quantities because their prices are expected to rise further", "goods whose demand falls when their prices rise", "goods bought in smaller quantities when income falls", "goods whose demand rises when the price of a substitute rises", "A",
     "When consumers expect further price rises, they may buy more as price rises; Giffen and ostentatious goods are other exceptions."),
    # ---------------- Supply ----------------
    ("Supply", "Easy", "The law of supply states that, other things being equal,",
     "more is supplied at higher prices than at lower prices", "less is supplied at higher prices than at lower prices", "supply is fixed regardless of price", "supply rises whenever demand falls", "A",
     "Higher prices make production more profitable, so producers offer more; the supply curve slopes upwards."),
    ("Supply", "Medium", "Which of the following will shift the supply curve of bread to the right?",
     "a fall in the price of flour", "a rise in the price of bread", "an increase in the wages of bakers", "a new tax on each loaf of bread", "A",
     "Cheaper inputs lower costs so more is supplied at every price; the own-price change is a movement along the curve."),
    ("Supply", "Medium", "On a market day, the supply of fresh tomatoes already brought to the market is",
     "fixed, whatever price buyers offer", "perfectly elastic at the ruling price", "increased easily if the price rises", "determined by the number of buyers", "A",
     "Perishable goods already on sale cannot be increased or withheld for long, so supply is fixed for that day."),
    ("Supply", "Easy", "Beef and hides are produced together from cattle. Their supply is",
     "joint supply", "competitive supply", "composite supply", "derived supply", "A",
     "Joint supply occurs when the production of one good automatically produces another."),
    ("Supply", "Easy", "A farmer can use his land either for maize or for beans. The supply of the two crops is",
     "competitive", "joint", "composite", "complementary", "A",
     "When the same resources can produce either good, more of one means less of the other: competitive supply."),
    ("Supply", "Medium", "A new tax on each bag of cement produced will",
     "shift the supply curve of cement to the left", "shift the supply curve of cement to the right", "cause a movement down the supply curve", "leave the supply curve unchanged", "A",
     "The tax raises the cost of supplying each bag, so less is offered at every price."),
    ("Supply", "Medium", "A government subsidy on fertiliser will most likely",
     "increase the supply of fertiliser and lower its price", "reduce the supply of fertiliser and raise its price", "reduce the demand for fertiliser by farmers", "leave the supply of fertiliser unchanged", "A",
     "A subsidy lowers producers' costs, shifting supply to the right and reducing the market price."),
    ("Supply", "Easy", "An improvement in technology in the poultry industry will",
     "increase the quantity of eggs supplied at every price", "reduce the quantity of eggs supplied at every price", "shift the demand curve for eggs to the left", "have no effect on the supply of eggs", "A",
     "Better technology lowers unit costs, so producers can offer more at each price."),
    ("Supply", "Easy", "A movement along the supply curve of yam is caused by a change in",
     "the price of yam", "the cost of fertiliser", "the weather", "the price of cassava", "A",
     "Only the good's own price causes a movement along its supply curve; other factors shift the curve."),
    ("Supply", "Easy", "Quantity supplied is the amount of a good that producers",
     "are willing and able to offer for sale at a given price and time", "have produced in total since the firm was established", "keep in their warehouses for future sale", "would like to sell if the price were much higher", "A",
     "Supply, like demand, is defined at a specific price over a specific period."),
    ("Supply", "Medium", "An increase in supply means that",
     "more is offered for sale at every price", "the price of the good has risen", "producers have moved up the supply curve", "the quantity demanded has increased", "A",
     "An increase in supply is a rightward shift of the whole curve, not a movement along it."),
    ("Supply", "Hard", "A backward-bending supply curve is associated with the supply of",
     "labour", "land", "manufactured goods", "agricultural produce", "A",
     "Beyond a certain wage, workers may prefer more leisure and offer fewer hours, so the labour supply curve bends backwards."),
    ("Supply", "Easy", "A fall in the price of cocoa, other things being equal, leads to",
     "a contraction in the quantity of cocoa supplied", "an extension in the quantity of cocoa supplied", "a rightward shift of the cocoa supply curve", "an increase in the supply of cocoa", "A",
     "Lower prices make production less profitable, so quantity supplied falls along the same curve."),
    ("Supply", "Medium", "Rice traders who expect the price of rice to rise sharply next month are likely to",
     "withhold some stock from the market now", "sell all their stock immediately", "reduce the price of rice now", "import less rice next month", "A",
     "Expectations of higher future prices reduce current supply as sellers hold back stock to sell later."),
    # ---------------- Price Determination ----------------
    ("Price Determination", "Easy", "The equilibrium price of a good is the price at which",
     "quantity demanded equals quantity supplied", "the government fixes the price of the good", "sellers make the largest possible profit", "buyers are willing to pay the highest price", "A",
     "At equilibrium there is neither shortage nor surplus, so the price has no tendency to change."),
    ("Price Determination", "Easy", "When the market price of a good is below its equilibrium level, there is",
     "excess demand, which pushes the price up", "excess supply, which pushes the price down", "equilibrium, so the price stays the same", "excess supply, which pushes the price up", "A",
     "At a low price buyers want more than sellers offer; competition among buyers bids the price up."),
    ("Price Determination", "Medium", "The demand and supply functions for a good are Qd = 60 − 2P and Qs = 3P − 15. The equilibrium price is",
     "₦15", "₦12", "₦20", "₦9", "A",
     "Set 60 − 2P = 3P − 15, so 5P = 75 and P = 15.", "15"),
    ("Price Determination", "Medium", "If Qd = 60 − 2P and Qs = 3P − 15, the equilibrium quantity is",
     "30 units", "45 units", "15 units", "60 units", "A",
     "At P = 15, Q = 60 − 30 = 30 (and 3 × 15 − 15 = 30).", "30"),
    ("Price Determination", "Medium", "A government fixes a minimum wage above the equilibrium wage. The likely result in the labour market is",
     "a surplus of labour (unemployment)", "a shortage of labour", "no change in employment", "a rise in the demand for labour", "A",
     "A price floor above equilibrium raises the quantity of labour supplied and reduces the quantity demanded."),
    ("Price Determination", "Medium", "A state government fixes a maximum price for cooking gas well below the market equilibrium. Apart from shortages, a likely consequence is",
     "the emergence of a black market", "a surplus of cement in the market", "a fall in the demand for cement", "an increase in the supply of cement", "A",
     "A price ceiling creates a shortage, and some buyers will pay more than the legal price illegally."),
    ("Price Determination", "Medium", "An increase in demand for a good, with supply unchanged, leads to",
     "a rise in both equilibrium price and quantity", "a fall in both equilibrium price and quantity", "a rise in price and a fall in quantity", "a fall in price and a rise in quantity", "A",
     "The demand curve shifts right along an upward-sloping supply curve, so price and quantity both rise."),
    ("Price Determination", "Medium", "An increase in supply with demand unchanged will",
     "lower the equilibrium price and raise the equilibrium quantity", "raise the equilibrium price and lower the equilibrium quantity", "raise both the equilibrium price and quantity", "lower both the equilibrium price and quantity", "A",
     "A rightward shift of supply along a downward-sloping demand curve reduces price and increases quantity."),
    ("Price Determination", "Hard", "If demand and supply of a good both increase by the same proportion, the equilibrium",
     "quantity rises while the price stays the same", "price rises while the quantity stays the same", "price and quantity both fall", "price rises and the quantity falls", "A",
     "Equal rightward shifts of both curves leave the price unchanged but raise the quantity traded."),
    ("Price Determination", "Medium", "Given Qd = 50 − P and Qs = 2P − 10, at a price of ₦25 the market has",
     "a surplus of 15 units", "a shortage of 15 units", "a surplus of 25 units", "equilibrium", "A",
     "At P = 25, Qd = 25 and Qs = 40, so 15 units are unsold.", "15"),
    ("Price Determination", "Medium", "The price system rations scarce goods by",
     "allocating them to those willing and able to pay the price", "sharing them equally among all consumers", "giving them first to those who queue longest", "allowing the government to decide who gets them", "A",
     "When a good is scarce its price rises until only those who can and will pay obtain it."),
    ("Price Determination", "Medium", "The government fixes the pump price of petrol at ₦600 per litre when the market equilibrium is ₦900. The likely effects are",
     "long queues, shortages and a black market", "a surplus of petrol at filling stations", "a fall in the demand for petrol", "an increase in the supply of petrol", "A",
     "A maximum price below equilibrium causes excess demand; rationing by queues and illegal sales above the fixed price follow."),
    ("Price Determination", "Medium", "A rise in the cost of production of a good, with demand unchanged, will lead to",
     "a higher equilibrium price and a lower equilibrium quantity", "a lower equilibrium price and a higher equilibrium quantity", "a higher equilibrium price and a higher equilibrium quantity", "no change in the equilibrium price or quantity", "A",
     "Higher costs shift supply to the left: price rises and quantity falls."),
    ("Price Determination", "Hard", "The demand and supply of a good are Qd = 100 − 5P and Qs = 5P. The total revenue of sellers at equilibrium is",
     "₦500", "₦1,000", "₦250", "₦100", "A",
     "100 − 5P = 5P gives P = 10 and Q = 50; revenue = 10 × 50 = ₦500.", "500"),
    # ---------------- Elasticity of Demand and Supply ----------------
    ("Elasticity of Demand and Supply", "Medium", "A shop raised the price of a sachet of detergent from ₦40 to ₦50 and its weekly sales fell from 200 to 170 sachets. Using original values, the price elasticity of demand is",
     "0.6", "1.5", "0.8", "1.2", "A",
     "%ΔQ = 30/200 = 15%; %ΔP = 10/40 = 25%; 15 ÷ 25 = 0.6 (inelastic).", "(30/200)/(10/40)"),
    ("Elasticity of Demand and Supply", "Medium", "The price elasticity of demand for a good is 2. If its price falls by 5%, the quantity demanded will",
     "rise by 10%", "rise by 2.5%", "fall by 10%", "rise by 5%", "A",
     "%ΔQ = elasticity × %ΔP = 2 × 5% = 10%, in the opposite direction to the price change.", "10"),
    ("Elasticity of Demand and Supply", "Medium", "A 20% rise in the price of a good leaves the seller's total revenue unchanged. The demand for the good is",
     "unitary elastic", "perfectly inelastic", "perfectly elastic", "fairly inelastic", "A",
     "When demand is unit elastic, the percentage fall in quantity equals the percentage rise in price, so revenue is constant."),
    ("Elasticity of Demand and Supply", "Easy", "A perfectly inelastic demand curve is",
     "a vertical straight line", "a horizontal straight line", "a downward-sloping curve", "an upward-sloping curve", "A",
     "Quantity demanded does not change at all when price changes, so the curve is vertical."),
    ("Elasticity of Demand and Supply", "Easy", "A perfectly elastic demand curve is",
     "a horizontal straight line", "a vertical straight line", "a curve sloping downwards", "a curve sloping upwards", "A",
     "Buyers take any quantity at one price but nothing at a higher price, so the curve is horizontal."),
    ("Elasticity of Demand and Supply", "Easy", "The demand for a good is likely to be more elastic when",
     "the good has many close substitutes", "the good is a necessity of life", "the good takes a tiny share of income", "the good is habit-forming", "A",
     "Availability of substitutes makes consumers respond strongly to a change in price."),
    ("Elasticity of Demand and Supply", "Medium", "When the price of a good rose by 10%, the quantity supplied rose by 25%. The price elasticity of supply is",
     "2.5", "0.4", "1.5", "0.25", "A",
     "Elasticity of supply = 25% ÷ 10% = 2.5, so supply is elastic.", "2.5"),
    ("Elasticity of Demand and Supply", "Medium", "Supply is usually more elastic in the long run than in the short run because",
     "producers can adjust all their factors of production", "prices always rise in the long run", "consumers have more time to change their tastes", "the government removes all taxes in the long run", "A",
     "Given time, firms can build new plants and new firms can enter, so output responds more to price."),
    ("Elasticity of Demand and Supply", "Medium", "The cross elasticity of demand between bread and butter is −0.8. The two goods are",
     "complements", "substitutes", "unrelated goods", "inferior goods", "A",
     "A negative cross elasticity means a rise in the price of one reduces the demand for the other: they are used together."),
    ("Elasticity of Demand and Supply", "Medium", "When consumers' incomes rose by 10%, the demand for garri fell by 4%. The income elasticity of demand for garri is",
     "−0.4, so garri is an inferior good", "0.4, so garri is a necessity", "−2.5, so garri is a luxury", "2.5, so garri is a normal good", "A",
     "Income elasticity = −4% ÷ 10% = −0.4; a negative value identifies an inferior good.", "-0.4"),
    ("Elasticity of Demand and Supply", "Easy", "A good whose income elasticity of demand is greater than 1 is",
     "a luxury", "a necessity", "an inferior good", "a Giffen good", "A",
     "Demand for luxuries rises more than proportionately when income rises."),
    ("Elasticity of Demand and Supply", "Medium", "After a bumper harvest, tomato farmers found their total revenue fell even though they sold more. This is because the demand for tomatoes is",
     "price inelastic", "price elastic", "unitary elastic", "perfectly elastic", "A",
     "With inelastic demand the large price fall needed to sell the extra output reduces total revenue."),
    ("Elasticity of Demand and Supply", "Medium", "A government that wants to raise the most revenue from an indirect tax should tax goods whose demand is",
     "price inelastic", "price elastic", "perfectly elastic", "highly income elastic", "A",
     "When demand is inelastic, the tax raises price without greatly reducing the quantity bought, so revenue is high."),
    ("Elasticity of Demand and Supply", "Hard", "On a straight-line downward-sloping demand curve, demand is unitary elastic",
     "at the midpoint of the curve", "at every point on the curve", "where the curve meets the price axis", "where the curve meets the quantity axis", "A",
     "Elasticity falls from infinity at the price axis to zero at the quantity axis, passing through 1 at the midpoint."),
    ("Elasticity of Demand and Supply", "Medium", "The demand for petrol is inelastic in the short run mainly because",
     "motorists cannot quickly change their vehicles or travel habits", "petrol is very cheap compared with other goods", "petrol has many close substitutes", "the government controls the number of petrol stations", "A",
     "In the short run there are few substitutes and consumers need time to adjust, so quantity demanded responds little to price."),
    ("Elasticity of Demand and Supply", "Medium", "A seller raised the price of a good from ₦100 to ₦120 and total revenue rose from ₦50,000 to ₦54,000. The demand for the good is",
     "price inelastic", "price elastic", "unitary elastic", "perfectly elastic", "A",
     "Total revenue rises when price rises only if demand is inelastic."),
    ("Elasticity of Demand and Supply", "Easy", "Which of the following goods is likely to have the LEAST elastic demand?",
     "table salt", "a particular brand of biscuit", "a holiday abroad", "a new private car", "A",
     "Salt is a cheap necessity with no close substitute, so its quantity demanded hardly responds to price; the others are luxuries or have many substitutes."),
    # ---------------- Consumer Behaviour ----------------
    ("Consumer Behaviour", "Easy", "Utility in economics means",
     "the satisfaction derived from consuming a good or service", "the usefulness of a good to the whole society", "the price a consumer pays for a good", "the profit a producer makes from a good", "A",
     "Utility is subjective satisfaction; a good has utility if it satisfies a want, whether or not it is useful."),
    ("Consumer Behaviour", "Easy", "Marginal utility is",
     "the extra satisfaction from consuming one more unit of a good", "the total satisfaction from all units consumed", "the satisfaction from the first unit consumed", "the average satisfaction per unit consumed", "A",
     "MU = change in total utility ÷ change in quantity consumed."),
    ("Consumer Behaviour", "Easy", "The law of diminishing marginal utility states that as a consumer consumes more units of a good,",
     "the additional satisfaction from each extra unit falls", "total satisfaction falls from the first unit", "the price of the good keeps falling", "the additional satisfaction from each unit rises", "A",
     "Successive units add less and less to total utility, other things being equal."),
    ("Consumer Behaviour", "Medium", "When total utility is at its maximum, marginal utility is",
     "zero", "at its maximum", "negative", "equal to total utility", "A",
     "Total utility stops rising when the extra unit adds nothing; beyond that point MU becomes negative."),
    ("Consumer Behaviour", "Hard", "A cup of rice gives a consumer 30 utils and costs ₦150; a cup of beans gives 40 utils and costs ₦250. To increase total satisfaction with the same money, the consumer should buy",
     "more rice and less beans", "more beans and less rice", "equal quantities of both", "only beans", "A",
     "MU per naira: rice 30/150 = 0.2, beans 40/250 = 0.16; shifting spending towards rice raises total utility until the ratios are equal."),
    ("Consumer Behaviour", "Medium", "Water is essential to life yet cheap, while diamonds are unnecessary yet very expensive. This paradox of value is explained by",
     "marginal utility", "total utility", "the law of supply", "the cost of production", "A",
     "Price reflects marginal, not total, utility: water is abundant so its marginal utility is low, diamonds are scarce so theirs is high."),
    ("Consumer Behaviour", "Easy", "Consumer surplus is",
     "the difference between what a consumer is willing to pay and what he actually pays", "the extra goods a consumer buys when prices fall", "the money a consumer has left after buying all his needs", "the profit a seller makes on each unit sold", "A",
     "It measures the benefit consumers gain from paying a market price lower than their maximum willingness to pay."),
    ("Consumer Behaviour", "Medium", "Ngozi was willing to pay ₦1,200 for a textbook but bought it for ₦900. Her consumer surplus is",
     "₦300", "₦900", "₦1,200", "₦2,100", "A",
     "Consumer surplus = willingness to pay − price paid = 1,200 − 900 = ₦300.", "1200-900"),
    ("Consumer Behaviour", "Medium", "An indifference curve shows",
     "combinations of two goods that give the consumer equal satisfaction", "the quantities of a good bought at different prices", "the combinations of two goods a consumer can afford", "how total utility changes as consumption rises", "A",
     "The consumer is indifferent between all the combinations on one curve."),
    ("Consumer Behaviour", "Medium", "A consumer's budget line shifts outwards, parallel to the old one, when",
     "her income rises while prices remain unchanged", "the price of one good rises", "her tastes change in favour of one good", "the prices of both goods rise proportionately", "A",
     "Higher income with constant prices lets her buy more of both goods, so the whole line moves out."),
    ("Consumer Behaviour", "Easy", "Measuring satisfaction in units called utils is the ______ approach to utility.",
     "cardinal", "ordinal", "marginal", "indifference", "A",
     "The cardinal approach assumes utility can be measured in numbers; the ordinal approach only ranks preferences."),
    ("Consumer Behaviour", "Medium", "A rational consumer buying a single good will stop buying additional units when",
     "the marginal utility of the good, in money terms, equals its price", "total utility begins to rise", "the marginal utility of the good is at its maximum", "the price of the good begins to fall", "A",
     "Buying continues while each extra unit is worth at least its price; the last unit bought is worth exactly the price."),
    ("Consumer Behaviour", "Medium", "When the price of beef falls and a consumer buys more beef in place of the relatively dearer fish, this is the",
     "substitution effect of the price change", "income effect of the price change", "law of diminishing marginal utility", "paradox of value", "A",
     "A fall in relative price leads consumers to substitute the cheaper good for the dearer one."),
    # ---------------- Theory of the Firm ----------------
    ("Theory of the Firm", "Easy", "A firm differs from an industry in that a firm is",
     "a single unit of production under one ownership or management", "a group of producers making similar products", "any market in which goods are exchanged", "the whole of the economy's manufacturing sector", "A",
     "An industry is made up of all the firms producing the same or similar products."),
    ("Theory of the Firm", "Medium", "The law of diminishing returns operates in the short run because",
     "at least one factor of production is fixed", "all factors of production can be varied", "the firm can change its scale of operation", "prices of inputs rise as output rises", "A",
     "Adding more of a variable factor to a fixed factor eventually yields smaller additions to output."),
    ("Theory of the Firm", "Medium", "Employing a fourth worker raised a workshop's output from 60 to 84 units, and a fifth raised it to 100 units. The marginal product of the fifth worker is",
     "16 units", "24 units", "20 units", "100 units", "A",
     "MP = change in total product = 100 − 84 = 16 units, less than the fourth worker's 24: diminishing returns have set in.", "100-84"),
    ("Theory of the Firm", "Easy", "Five workers in a bakery produce 100 loaves a day. The average product of labour is",
     "20 loaves", "100 loaves", "5 loaves", "500 loaves", "A",
     "Average product = total product ÷ number of workers = 100 ÷ 5 = 20 loaves.", "100/5"),
    ("Theory of the Firm", "Easy", "In the short run, a firm's fixed factor is most likely to be its",
     "factory building", "raw materials", "casual labour", "electricity consumption", "A",
     "Buildings and heavy plant cannot be changed quickly; materials, casual labour and power vary with output."),
    ("Theory of the Firm", "Easy", "The long run in the theory of production is the period in which",
     "all factors of production can be varied", "at least one factor is fixed", "no new firms can enter the industry", "prices of all inputs are constant", "A",
     "In the long run a firm can change its plant size and scale, and firms can enter or leave the industry."),
    ("Theory of the Firm", "Medium", "A large flour mill buys wheat in bulk at a discount and spreads its advertising cost over millions of bags. These are examples of",
     "internal economies of scale", "external economies of scale", "diseconomies of scale", "diminishing returns", "A",
     "Cost advantages that arise from the growth of the firm itself are internal economies of scale."),
    ("Theory of the Firm", "Medium", "A shoe firm in Aba benefits from the pool of skilled shoemakers and leather suppliers that have grown up in the town. This is an example of",
     "external economies of scale", "internal economies of scale", "diminishing marginal returns", "internal diseconomies of scale", "A",
     "Advantages that come from the growth of the whole industry in an area, not from the firm's own size, are external economies."),
    ("Theory of the Firm", "Medium", "As a company grew very large, decisions became slow, communication broke down and unit costs began to rise. The firm was experiencing",
     "diseconomies of scale", "economies of scale", "diminishing returns to labour", "external economies", "A",
     "Beyond the optimum size, management problems raise average cost; these are internal diseconomies of scale."),
    ("Theory of the Firm", "Medium", "A firm earning normal profit is one whose total revenue",
     "just covers total cost including the reward of the entrepreneur", "exceeds total cost by a very large margin", "covers variable cost but not fixed cost", "is less than the wages paid to its workers", "A",
     "Normal profit is the minimum return that keeps the entrepreneur in the industry and is counted as a cost."),
    ("Theory of the Firm", "Medium", "The optimum size of a firm is the size at which it",
     "produces at the lowest average cost", "employs the largest number of workers", "earns the highest total revenue", "has the largest share of the market", "A",
     "At the optimum, all economies of scale have been reaped and diseconomies have not yet set in."),
    ("Theory of the Firm", "Medium", "Many small firms survive alongside large ones in Nigeria mainly because",
     "they serve small local markets and offer personal services", "the law forbids firms from growing beyond a certain size", "large firms always have higher costs than small ones", "small firms pay no taxes to the government", "A",
     "Where the market is small or personal attention matters, the advantages of large scale are limited."),
    ("Theory of the Firm", "Easy", "The total product of a firm with 10 workers is 200 units. Average product per worker is",
     "20 units", "10 units", "200 units", "2,000 units", "A",
     "AP = TP ÷ L = 200 ÷ 10 = 20 units.", "200/10"),
    # ---------------- Costs of Production ----------------
    ("Costs of Production", "Easy", "Fixed costs are costs that",
     "do not vary with output in the short run", "rise as output rises", "are paid only when the firm produces", "fall when output increases", "A",
     "Rent, insurance and interest on loans must be paid even when output is zero."),
    ("Costs of Production", "Easy", "Which of the following is a variable cost for a pure-water factory?",
     "the cost of nylon sachets", "the rent of the factory premises", "the insurance premium on the building", "the salary of the general manager", "A",
     "The cost of sachets rises directly with the number of bags produced; the others are fixed in the short run."),
    ("Costs of Production", "Medium", "A firm's total fixed cost is ₦40,000 and its average variable cost is ₦50 when it produces 1,000 units. Its total cost is",
     "₦90,000", "₦50,000", "₦40,050", "₦140,000", "A",
     "TVC = 50 × 1,000 = 50,000; TC = TFC + TVC = 40,000 + 50,000 = ₦90,000.", "40000+50*1000"),
    ("Costs of Production", "Medium", "Average fixed cost falls continuously as output rises because",
     "the same fixed cost is spread over more units", "fixed cost falls as the firm grows", "variable cost falls as output rises", "the firm receives discounts on rent", "A",
     "AFC = TFC ÷ output; a constant numerator divided by a rising output gives a falling value."),
    ("Costs of Production", "Medium", "A block-moulding business found that its weekly total cost rose from ₦300,000 to ₦324,000 when it increased output from 100 to 106 blocks. The marginal cost per block is",
     "₦4,000", "₦24,000", "₦3,000", "₦3,057", "A",
     "MC = ΔTC ÷ ΔQ = 24,000 ÷ 6 = ₦4,000.", "24000/6"),
    ("Costs of Production", "Medium", "A trader uses her own shop for her business instead of renting it out for ₦200,000 a year. The ₦200,000 is",
     "an implicit cost", "an explicit cost", "a fixed cost", "a sunk cost", "A",
     "Implicit costs are the opportunity costs of using the owner's own resources; no money payment is made."),
    ("Costs of Production", "Easy", "Explicit costs are",
     "actual money payments made to outsiders for inputs", "the opportunity costs of the owner's own resources", "costs that cannot be recovered once incurred", "costs that do not change with output", "A",
     "Wages, rent and payments for materials are explicit (accounting) costs."),
    ("Costs of Production", "Medium", "Money already spent on an advertising campaign that failed cannot be recovered. It is",
     "a sunk cost", "a variable cost", "an implicit cost", "a marginal cost", "A",
     "Sunk costs have already been incurred and should not affect future decisions."),
    ("Costs of Production", "Hard", "The marginal cost curve cuts the average total cost curve at",
     "the minimum point of the average total cost curve", "the maximum point of the average total cost curve", "the point where average fixed cost is zero", "the point where total cost is lowest", "A",
     "When MC is below ATC it pulls ATC down; when above, it pushes ATC up; so they meet at ATC's minimum."),
    ("Costs of Production", "Medium", "The U-shape of the short-run average cost curve is explained by",
     "the law of diminishing returns", "economies of scale", "the law of demand", "changes in the prices of inputs", "A",
     "Average cost first falls as the fixed factor is used more fully, then rises when diminishing returns set in."),
    ("Costs of Production", "Medium", "The downward-sloping part of a firm's long-run average cost curve is due to",
     "economies of scale", "diminishing returns", "diseconomies of scale", "rising input prices", "A",
     "As the firm expands its scale, technical, managerial and financial economies lower unit cost."),
    ("Costs of Production", "Medium", "When marginal cost is below average variable cost, average variable cost is",
     "falling", "rising", "constant", "at its minimum", "A",
     "An extra unit costing less than the current average pulls the average down."),
    ("Costs of Production", "Medium", "At an output of 50 units a firm's average total cost is ₦120 and its average fixed cost is ₦40. Its total variable cost is",
     "₦4,000", "₦6,000", "₦2,000", "₦8,000", "A",
     "AVC = ATC − AFC = ₦80; TVC = 80 × 50 = ₦4,000.", "(120-40)*50"),
    ("Costs of Production", "Hard", "A firm's total revenue is ₦500,000, its explicit costs are ₦350,000 and its implicit costs are ₦100,000. Its economic profit is",
     "₦50,000", "₦150,000", "₦100,000", "₦450,000", "A",
     "Economic profit = TR − (explicit + implicit costs) = 500,000 − 450,000 = ₦50,000; accounting profit would be ₦150,000.", "500000-450000"),
    ("Costs of Production", "Medium", "A factory discharges waste into a river, killing the fish on which a nearby village depends. The loss suffered by the village is",
     "an external cost of production", "a private cost of the factory", "a fixed cost of the factory", "an implicit cost of the village", "A",
     "Costs imposed on third parties who are not part of the transaction are external (social) costs."),
    # ---------------- Revenue and Profit ----------------
    ("Revenue and Profit", "Easy", "A trader sells 200 units of a good at ₦150 each. Her total revenue is",
     "₦30,000", "₦3,000", "₦350", "₦15,000", "A",
     "Total revenue = price × quantity = 150 × 200 = ₦30,000.", "150*200"),
    ("Revenue and Profit", "Easy", "Average revenue is always equal to",
     "the price of the good", "marginal revenue", "total profit", "marginal cost", "A",
     "AR = TR ÷ Q = (P × Q) ÷ Q = P."),
    ("Revenue and Profit", "Medium", "Under monopoly, marginal revenue is less than average revenue because",
     "the firm must lower its price to sell more units", "the firm faces a horizontal demand curve", "the monopolist's costs rise with output", "the government fixes the monopolist's price", "A",
     "Selling an extra unit means cutting the price on all units, so the revenue added is less than the new price."),
    ("Revenue and Profit", "Easy", "Normal profit is",
     "the minimum return needed to keep the entrepreneur in the business", "the profit earned when total revenue equals variable cost", "any profit above the average for the industry", "the profit declared to tax authorities", "A",
     "Normal profit is treated as a cost of production because without it the entrepreneur would leave."),
    ("Revenue and Profit", "Medium", "A firm earns supernormal (abnormal) profit when",
     "total revenue exceeds total cost including normal profit", "total revenue just equals total cost", "average revenue equals average variable cost", "marginal revenue is zero", "A",
     "Supernormal profit is the excess over the normal profit already counted in costs."),
    ("Revenue and Profit", "Easy", "A firm's total revenue is ₦1,200,000 and its total cost is ₦950,000. Its profit is",
     "₦250,000", "₦2,150,000", "₦150,000", "₦350,000", "A",
     "Profit = TR − TC = 1,200,000 − 950,000 = ₦250,000.", "1200000-950000"),
    ("Revenue and Profit", "Medium", "A bakery's weekly revenue rose from ₦80,000 to ₦84,000 when its sales rose from 400 to 410 loaves. The marginal revenue per loaf is",
     "₦400", "₦4,000", "₦200", "₦205", "A",
     "MR = ΔTR ÷ ΔQ = 4,000 ÷ 10 = ₦400.", "4000/10"),
    ("Revenue and Profit", "Easy", "A firm whose total revenue is exactly equal to its total cost is",
     "breaking even", "making a loss", "making supernormal profit", "shutting down", "A",
     "At the break-even point the firm covers all its costs, including normal profit, but earns nothing extra."),
    ("Revenue and Profit", "Easy", "Profit is the reward for",
     "entrepreneurship and risk-bearing", "the use of land", "the supply of labour", "the use of borrowed capital", "A",
     "The entrepreneur who organises production and bears its risks receives profit, which may be negative."),
    ("Revenue and Profit", "Medium", "When demand is price elastic, a fall in price will",
     "raise total revenue", "reduce total revenue", "leave total revenue unchanged", "reduce the quantity sold", "A",
     "With elastic demand the percentage rise in quantity exceeds the percentage fall in price, so revenue rises."),
    ("Revenue and Profit", "Hard", "A monopolist's total revenue is at its maximum where",
     "marginal revenue is zero", "marginal revenue equals price", "average revenue is zero", "marginal cost is zero", "A",
     "Total revenue stops rising when an extra unit adds nothing to it, i.e. MR = 0 (demand is unit elastic there)."),
    ("Revenue and Profit", "Hard", "A firm has fixed costs of ₦100,000, sells each unit for ₦500 and incurs a variable cost of ₦300 per unit. Its break-even output is",
     "500 units", "200 units", "333 units", "1,000 units", "A",
     "Each unit contributes 500 − 300 = ₦200 towards fixed cost; 100,000 ÷ 200 = 500 units.", "100000/200"),
    ("Revenue and Profit", "Medium", "Which of the following would reduce a firm's profit without any change in its revenue?",
     "a rise in the price of its raw materials", "a rise in the price of its product", "an increase in the quantity it sells", "a fall in the wages it pays", "A",
     "Higher input prices raise total cost; with revenue unchanged, profit falls."),
    # ---------------- Market Structures ----------------
    ("Market Structures", "Easy", "Under perfect competition an individual firm is a price taker because it",
     "produces a negligible share of total market output", "is the only seller of the product in the whole market", "sells a product that differs from those of its rivals", "can fix any price it likes for the product it sells", "A",
     "One firm's output is too small to influence the market price, so it must accept the price set by the market."),
    ("Market Structures", "Easy", "The demand curve facing a firm in a perfectly competitive market is",
     "horizontal (perfectly elastic)", "vertical (perfectly inelastic)", "downward-sloping", "upward-sloping", "A",
     "The firm can sell any quantity at the market price but nothing above it."),
    ("Market Structures", "Medium", "In the long run, firms in perfect competition earn only normal profit because",
     "free entry of new firms competes away supernormal profit", "the government taxes all profits above normal", "consumers refuse to pay high prices", "the products of different firms are differentiated", "A",
     "Supernormal profit attracts entrants, raising supply and lowering price until only normal profit remains."),
    ("Market Structures", "Easy", "Patents, huge capital requirements and control of raw materials are",
     "barriers to entry that help to create monopoly", "features of perfect competition", "methods of price discrimination", "causes of diseconomies of scale", "A",
     "Anything that prevents new firms from entering an industry protects the market power of existing firms."),
    ("Market Structures", "Medium", "An electricity company charges industrial users a different tariff per unit from households for the same electricity. This is",
     "price discrimination", "product differentiation", "perfect competition", "a cartel arrangement", "A",
     "Charging different prices to different groups for the same product, where the groups can be separated and have different elasticities, is price discrimination."),
    ("Market Structures", "Medium", "A monopolist can fix",
     "either the price or the quantity sold, but not both", "both the price and the quantity sold", "neither the price nor the quantity sold", "the prices of substitutes as well as his own", "A",
     "The monopolist faces the market demand curve; once he sets a price, buyers decide the quantity, and vice versa."),
    ("Market Structures", "Medium", "Nigeria's mobile network operators compete mainly through bonus data, adverts and promotions rather than by cutting call prices. This behaviour is typical of",
     "non-price competition in an oligopoly", "price competition in a perfect market", "output restriction by a pure monopoly", "exploitation of sellers by a monopsony", "A",
     "Oligopolists avoid price wars, which hurt all of them, and compete through advertising and product features."),
    ("Market Structures", "Easy", "A group of producing countries that agree to restrict output in order to keep prices high is",
     "a cartel", "a monopsony", "a perfectly competitive industry", "a public corporation", "A",
     "OPEC is the best-known example of a cartel: independent producers acting together like a monopoly."),
    ("Market Structures", "Easy", "The main feature that distinguishes monopolistic competition from perfect competition is",
     "product differentiation", "a single seller", "barriers to entry", "a homogeneous product", "A",
     "Under monopolistic competition many sellers offer similar but not identical products, giving each some price control."),
    ("Market Structures", "Medium", "In the colonial era the marketing board was the only buyer of cocoa from all Nigerian farmers. The board was",
     "a monopsonist", "a monopolist", "an oligopolist", "a price taker", "A",
     "A monopsony is a market with a single buyer."),
    ("Market Structures", "Easy", "Only two firms supply cement to a region. This market structure is",
     "a duopoly", "a monopoly", "perfect competition", "monopolistic competition", "A",
     "Duopoly is the special case of oligopoly with exactly two sellers."),
    ("Market Structures", "Medium", "Piped water supply is usually provided by one firm because it is cheaper for a single supplier to serve the whole town than for several to lay competing pipelines. This is",
     "a natural monopoly", "a legal monopoly", "a cartel", "perfect competition", "A",
     "Where economies of scale are so large that one firm can serve the market at the lowest cost, a natural monopoly arises."),
    ("Market Structures", "Medium", "A feature common to perfect competition and monopolistic competition is",
     "a large number of sellers and freedom of entry", "a homogeneous product sold by all firms", "a single firm controlling the market price", "high barriers preventing new firms from entering", "A",
     "Both structures have many firms and free entry; they differ in whether the product is homogeneous or differentiated."),
    ("Market Structures", "Medium", "Governments usually control monopolies by",
     "regulating prices and encouraging competition", "granting them more patents", "banning consumers from buying their goods", "forcing them to raise their prices", "A",
     "Price regulation, anti-trust laws, removal of entry barriers and public ownership are common controls."),
    ("Market Structures", "Medium", "In equilibrium, a perfectly competitive firm produces where price equals",
     "marginal cost and marginal revenue", "average fixed cost", "total revenue", "average variable cost minus marginal cost", "A",
     "For the price taker P = AR = MR, and profit is maximised where MR = MC, so P = MC."),
]

FIX = {}


def build():
    build_batch(
        S, "batch_021_econ_round3a.json", "batch_021_econ_round3a",
        "Economics round 3 (part A): micro-economics - concepts, scarcity, scale of preference, production, factors, division of labour, economic systems, demand, supply, price determination, elasticity, consumer behaviour, theory of the firm, costs, revenue and market structures, with a taxed demand/supply schedule, a utility table and a cost table as data passages.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
