"""Builds content/batch_004_lit_crs_irs.json — Literature (unseen poems/prose with questions, devices
shown inside quoted lines), CRS and IRS (situation-based application of well-known texts).

Run:  python3 scripts/build_content_batch4.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_content_batch1 import _balance  # noqa: E402

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(BASE, "content", "batch_004_lit_crs_irs.json")

POEM1 = ("Harmattan (unseen poem)",
         "The harmattan creeps in on dusty feet,\n"
         "it wraps the town in a grey and silent shawl;\n"
         "the mango leaves hang tired in the heat,\n"
         "and cracked lips wait for rain that will not fall.\n\n"
         "Yet in the compound Grandma hums her song,\n"
         "her voice a thread that stitches dawn to dusk;\n"
         "she says the dry wind cannot stay for long,\n"
         "that every seed lies waiting in its husk.\n\n"
         "So I will keep my hope the way she keeps\n"
         "her rosary of years, bead after bead,\n"
         "until the first fat drop of April leaps\n"
         "and wakes the patient sleeper in the seed.")
POEM2 = ("Hawker (unseen poem)",
         "'Buy your groundnut! Buy your groundnut!'\n"
         "Amaka's voice climbs over the horns of Upper Iweka,\n"
         "a small bird against a storm of engines.\n"
         "Her tray is a crown she never asked to wear;\n"
         "beneath it, the school books her mother sold\n"
         "still turn their pages in her head.\n"
         "'Buy your groundnut! Buy your groundnut!'\n"
         "The sun beats its drum upon her back,\n"
         "the children of tomorrow pass her by in yellow buses,\n"
         "and nobody asks her name.\n"
         "What is the price of a childhood?\n"
         "Ask the traffic. Ask the tray. Ask the silence at home.")
PROSE = ("Unseen prose extract",
         "I did not cry when they read my father's will. I had done my crying years before, on the night he came home "
         "from the mill with his right hand wrapped in a bloody cloth and told us, quite calmly, that we would manage. "
         "We managed. My mother sold akara at the junction; I hawked her wares before school and after it, and my father, "
         "with his one good hand, taught me to read from newspapers that other people had thrown away. So when the lawyer "
         "announced that everything - the house, the small plot in the village, the savings nobody knew he had - was to go "
         "to my stepbrother Emeka, who had not visited in eleven years, I merely nodded. Emeka wept loudly. I remember "
         "thinking that he had not learnt, as I had, that some things are worth more than a house. Then I went outside and "
         "sat on the step where my father used to sit, and I waited to feel something.")

# (passage_key, difficulty, question, A, B, C, D, answer, explanation)
LIT_PASSAGE = [
    ("L1", "Easy", "The mood created in the first stanza of the poem is one of", "celebration", "weariness and gloom", "anger", "terror", "B", "Dusty, grey, silent, tired leaves and cracked lips all build a tired, gloomy atmosphere."),
    ("L1", "Easy", "'The harmattan creeps in on dusty feet' is an example of", "simile", "hyperbole", "personification", "onomatopoeia", "C", "The wind is given a human action (creeping in on feet) — personification."),
    ("L1", "Medium", "In 'her voice a thread that stitches dawn to dusk', the poet uses", "a metaphor", "a simile", "an oxymoron", "a pun", "A", "The voice is directly identified with a thread, without 'like' or 'as' — a metaphor."),
    ("L1", "Medium", "The rhyme scheme of the first stanza is", "aabb", "abab", "abba", "abcb", "B", "feet/heat rhyme (a) and shawl/fall rhyme (b), alternating: abab."),
    ("L1", "Hard", "'The patient sleeper in the seed' most likely stands for", "Grandma's tiredness after a long day's work", "the dust that the harmattan leaves behind", "new life and hope waiting for the rain", "the poet's fear that April will never come", "C", "The seed 'waiting in its husk' will be woken by the first rain; it symbolises the hope the speaker keeps alive through the dry season."),

    ("L2", "Easy", "The repeated line 'Buy your groundnut! Buy your groundnut!' is an example of", "a refrain", "an aside", "a soliloquy", "a paradox", "A", "A line repeated at intervals in a poem is a refrain; here it also imitates the hawker's cry."),
    ("L2", "Medium", "'a small bird against a storm of engines' suggests that Amaka's voice is", "loud and commanding above the traffic", "frail and easily drowned by the traffic", "musical and admired by passers-by", "angry and defiant towards the drivers", "B", "A small bird against a storm is weak and overpowered — her voice is lost in the noise of the vehicles."),
    ("L2", "Medium", "The device used in 'Her tray is a crown she never asked to wear' is", "simile", "metaphor", "alliteration", "euphemism", "B", "The tray is directly called a crown (a burden imposed like royalty's duty) — a metaphor."),
    ("L2", "Easy", "'What is the price of a childhood?' is", "a rhetorical question", "an apostrophe", "an epigram", "a litotes", "A", "The question is asked for effect; no answer is expected, and the next line replies only with more questions."),
    ("L2", "Medium", "The poet's attitude towards Amaka is one of", "mockery", "indifference", "sympathy", "envy", "C", "Every image (the sold books, the crown she never asked for, nobody asking her name) invites pity for a child denied school."),

    ("L3", "Easy", "The passage is narrated from the", "first-person point of view", "third-person omniscient point of view", "second-person point of view", "third-person limited point of view", "A", "The narrator speaks as 'I' and takes part in the events."),
    ("L3", "Medium", "The narrator's account of the night the father came home injured is an example of", "foreshadowing", "flashback", "suspense", "climax", "B", "The story moves back from the reading of the will to an earlier event — a flashback."),
    ("L3", "Medium", "The contrast between Emeka's loud weeping and the narrator's silence chiefly serves to", "show that Emeka loved his father more than the narrator did", "highlight the irony that the absent son displays the most grief", "prove that the narrator is heartless and unfeeling", "suggest that the lawyer had forged the father's will", "B", "Emeka, who stayed away for eleven years, weeps loudly while the child who suffered alongside the father stays quiet — an ironic reversal of what we expect."),
    ("L3", "Hard", "'some things are worth more than a house' refers to", "the savings that nobody knew the father had", "the small plot of land in the village", "the love, values and learning the father gave the narrator", "the akara business the mother ran at the junction", "C", "The narrator received the father's teaching and example, which he/she values above the property Emeka inherits."),
    ("L3", "Medium", "The narrator can best be described as", "bitter and vengeful", "greedy", "composed and mature", "careless", "C", "He/she 'merely nodded', reflects calmly and shows no resentment — self-controlled maturity, even while numb with grief."),
]

# (topic, difficulty, question, A, B, C, D, answer, explanation)
LIT = [
    ("Literary Devices and Figures of Speech", "Easy", "In 'The wind whispered secrets to the sleeping village', the poet uses", "personification", "simile", "hyperbole", "irony", "A", "The wind is given the human ability to whisper secrets."),
    ("Literary Devices and Figures of Speech", "Easy", "'He fought like a wounded lion' is an example of", "metaphor", "simile", "metonymy", "paradox", "B", "The comparison is made with 'like' — a simile."),
    ("Literary Devices and Figures of Speech", "Easy", "'Sadly, Sunday's sermon sent Sam to sleep' illustrates", "assonance", "onomatopoeia", "alliteration", "antithesis", "C", "The repetition of the initial 's' consonant sound is alliteration."),
    ("Literary Devices and Figures of Speech", "Easy", "'I have told you a million times to shut that door' is an example of", "litotes", "hyperbole", "euphemism", "pun", "B", "Deliberate exaggeration for effect is hyperbole."),
    ("Literary Devices and Figures of Speech", "Medium", "'The deafening silence of the empty hall' contains", "an oxymoron", "a simile", "an allusion", "a refrain", "A", "Two contradictory words placed together (deafening silence) form an oxymoron."),
    ("Literary Devices and Figures of Speech", "Medium", "In 'The crown announced new taxes', the word 'crown' is an example of", "synecdoche", "metonymy", "apostrophe", "hyperbole", "B", "Something closely associated with a thing (the crown) is used to stand for it (the monarchy/government) — metonymy."),
    ("Literary Devices and Figures of Speech", "Medium", "In 'We need more hands on the farm', 'hands' is an example of", "synecdoche", "onomatopoeia", "euphemism", "paradox", "A", "A part (hands) stands for the whole (workers) — synecdoche."),
    ("Literary Devices and Figures of Speech", "Easy", "'The bees buzzed and the kettle hissed on the fire' illustrates", "onomatopoeia", "assonance", "metaphor", "litotes", "A", "'Buzzed' and 'hissed' imitate the sounds they describe."),
    ("Literary Devices and Figures of Speech", "Medium", "A fire station burns to the ground while the firemen are attending a safety lecture. This is an example of", "dramatic irony", "verbal irony", "situational irony", "sarcasm", "C", "The outcome is the opposite of what one would expect — situational irony."),
    ("Literary Devices and Figures of Speech", "Medium", "On stage a king says, 'I trust my brother with my life', although the audience has just watched the brother plot his murder. This is", "situational irony", "dramatic irony", "verbal irony", "pathetic fallacy", "B", "The audience knows something the character does not — dramatic irony."),
    ("Literary Devices and Figures of Speech", "Easy", "'Our dear teacher has gone to rest with his ancestors' is an example of", "euphemism", "hyperbole", "paradox", "metonymy", "A", "A mild expression replaces a harsh one (he has died) — euphemism."),
    ("Literary Devices and Figures of Speech", "Medium", "'O Death, where is thy sting?' illustrates", "apostrophe", "alliteration", "epigram", "anticlimax", "A", "Addressing an absent person or an abstraction (Death) as if present is apostrophe."),
    ("Literary Devices and Figures of Speech", "Medium", "'The child is father of the man' is an example of", "antithesis", "paradox", "simile", "irony", "B", "The statement seems self-contradictory yet contains a truth (childhood shapes the adult) — a paradox."),
    ("Literary Devices and Figures of Speech", "Medium", "'Man proposes, God disposes' illustrates", "antithesis", "onomatopoeia", "euphemism", "allusion", "A", "Contrasting ideas are set against each other in a balanced structure — antithesis."),
    ("Literary Devices and Figures of Speech", "Medium", "'She is not unkind to strangers' is an example of", "hyperbole", "litotes", "oxymoron", "paradox", "B", "Understatement by denying the opposite (not unkind = kind) is litotes."),
    ("Literary Devices and Figures of Speech", "Medium", "'The champion met his Waterloo in the final match' contains", "an allusion", "a simile", "a refrain", "a pun", "A", "A reference to Napoleon's defeat at Waterloo — a historical allusion meaning a final defeat."),
    ("Literary Devices and Figures of Speech", "Hard", "'In one week he lost his wife, his fortune and his favourite pen' is an example of", "climax", "anticlimax", "antithesis", "apostrophe", "B", "The series descends suddenly from the serious to the trivial — anticlimax (bathos)."),
    ("Literary Devices and Figures of Speech", "Medium", "'The bank's employees lost interest in their jobs' relies on", "a pun", "a simile", "an apostrophe", "a paradox", "A", "'Interest' is used in two senses at once (enthusiasm; money earned on deposits) — a pun."),
    ("Literary Devices and Figures of Speech", "Medium", "'The rain in Spain stays mainly in the plain' illustrates", "assonance", "consonance", "alliteration", "onomatopoeia", "A", "The same vowel sound (/eɪ/) is repeated in rain, Spain, mainly, plain — assonance."),
    ("Genre and Forms of Literature", "Medium", "A character alone on stage speaks his private thoughts aloud so that the audience can hear them. This is", "an aside", "a soliloquy", "a prologue", "a monologue to another character", "B", "A soliloquy is a speech made by a character alone on stage revealing his thoughts."),
    ("Genre and Forms of Literature", "Medium", "During a conversation, a character turns and makes a brief remark heard by the audience but supposedly not by the other characters. This is", "an aside", "a soliloquy", "an epilogue", "a chorus", "A", "An aside is a short remark to the audience that other characters are assumed not to hear."),
    ("Genre and Forms of Literature", "Medium", "A play presents a noble hero whose downfall and death are brought about by a weakness in his own character. The play is a", "comedy", "farce", "tragedy", "melodrama", "C", "A serious play ending in the ruin of the protagonist through his tragic flaw (hamartia) is a tragedy."),
    ("Genre and Forms of Literature", "Medium", "A poem has fourteen lines, three quatrains and a final couplet, rhyming abab cdcd efef gg. It is", "a Petrarchan sonnet", "a Shakespearean sonnet", "an ode", "a ballad", "B", "Three quatrains and a closing couplet with that rhyme scheme is the English (Shakespearean) sonnet; the Petrarchan sonnet has an octave and a sestet."),
    ("Genre and Forms of Literature", "Easy", "A poem written to mourn the death of a person is", "an ode", "an elegy", "an epic", "a lyric", "B", "An elegy is a poem of mourning or lament for the dead."),
    ("Genre and Forms of Literature", "Easy", "A long narrative poem recounting the heroic deeds of a legendary figure is", "an epic", "a sonnet", "an elegy", "a limerick", "A", "Epics such as the Iliad or Sundiata are long narrative poems about heroes."),
    ("Genre and Forms of Literature", "Medium", "Lines of unrhymed iambic pentameter, such as most of Shakespeare's plays, are written in", "free verse", "blank verse", "heroic couplets", "prose", "B", "Blank verse is unrhymed iambic pentameter; free verse has no regular metre at all."),
    ("Genre and Forms of Literature", "Medium", "A novel that tells its story entirely through letters exchanged between the characters is", "a picaresque novel", "an epistolary novel", "a historical novel", "a bildungsroman", "B", "Epistolary comes from 'epistle' (letter)."),
    ("Genre and Forms of Literature", "Medium", "A novel that traces the moral and psychological growth of its main character from childhood to adulthood is called", "a satire", "a bildungsroman", "an allegory", "a fable", "B", "Bildungsroman is the novel of formation or growing up."),
    ("Genre and Forms of Literature", "Medium", "Animal Farm uses talking animals to ridicule the abuses of power after a revolution. The work is best described as", "a fable and a satire", "a historical tragedy", "an epic of the countryside", "a farce about farm life", "A", "It is a fable (animals as characters teaching a lesson) used as political satire."),
    ("Genre and Forms of Literature", "Medium", "In a tragedy, a scene of humour introduced to ease the tension is called", "comic relief", "climax", "catharsis", "denouement", "A", "Comic relief lightens the mood temporarily, e.g. the porter scene in Macbeth."),
    ("Plot, Setting and Structure", "Medium", "The point in a play or novel where the conflict reaches its highest intensity is the", "exposition", "climax", "denouement", "prologue", "B", "The climax is the turning point of greatest tension."),
    ("Plot, Setting and Structure", "Medium", "The part of the plot in which the loose ends are tied up after the climax is the", "exposition", "rising action", "denouement", "flashback", "C", "Denouement (resolution) follows the climax and settles the outcome."),
    ("Plot, Setting and Structure", "Medium", "Early in a novel, a character remarks that the old bridge 'will kill someone one day'; in the final chapter the hero drowns when it collapses. The early remark is an example of", "flashback", "foreshadowing", "anticlimax", "digression", "B", "A hint of what is to come later in the story is foreshadowing."),
    ("Plot, Setting and Structure", "Medium", "A story in which characters and events stand for abstract ideas such as greed, justice or salvation is", "an allegory", "an elegy", "a lampoon", "a parody", "A", "In allegory the surface story carries a second, symbolic meaning throughout."),
    ("Narrative Techniques and Point of View", "Medium", "A narrator who reports the thoughts and feelings of every character and comments on events is", "a first-person narrator", "an omniscient narrator", "an unreliable narrator", "a limited third-person narrator", "B", "The omniscient ('all-knowing') narrator has access to all characters' minds."),
    ("Narrative Techniques and Point of View", "Medium", "A short story is told by a ten-year-old who does not understand the adult events he describes, so the reader knows more than he does. The narrator is", "omniscient", "unreliable (naive)", "objective", "second-person", "B", "A narrator whose account cannot be fully trusted because of ignorance, youth or bias is an unreliable narrator."),
    ("Themes and Characterization", "Medium", "A character who is arrogant at the start of a novel but, after suffering, becomes humble and generous is", "a flat character", "a static character", "a dynamic (round) character", "a stock character", "C", "A character who undergoes significant change is dynamic; flat and static characters remain the same."),
    ("Themes and Characterization", "Medium", "In a play, the honest, gentle brother is placed beside the cruel, scheming one so that each shows up the other's qualities. The gentle brother is a", "foil", "protagonist", "chorus", "narrator", "A", "A foil is a character whose qualities contrast with and highlight those of another."),
    ("Themes and Characterization", "Medium", "The main character of a story who drives the action is the", "antagonist", "protagonist", "foil", "confidant", "B", "The protagonist is the central character; the antagonist opposes him or her."),
    ("Literary Appreciation", "Medium", "In a poem the lines run on into one another without punctuation at the end of each line. This technique is called", "enjambment", "caesura", "end-stopping", "refrain", "A", "Enjambment is the running-on of sense from one line to the next; a caesura is a pause within a line."),
]

CRS = [
    ("The Sovereignty of God", "Medium", "After his brothers sold him into slavery and he later became governor of Egypt, Joseph told them, 'You meant evil against me, but God meant it for good.' This statement teaches that", "evil deeds always go unpunished", "God can bring good out of human wickedness", "Joseph had forgotten what they did", "slavery is acceptable", "B", "Genesis 50:20 shows God's sovereignty and providence: He turned the brothers' evil plan into the saving of many lives."),
    ("The Covenant", "Medium", "The sign of the covenant God made with Abraham was", "the rainbow", "circumcision", "the Sabbath", "the Passover lamb", "B", "In Genesis 17 every male of Abraham's household was to be circumcised as the sign of the covenant; the rainbow was the sign given to Noah."),
    ("Leadership Qualities", "Medium", "Moses' father-in-law Jethro saw him judging the people alone from morning till evening and advised him to", "stop judging the people and leave it to the priests", "appoint able men to judge minor cases while he handled the difficult ones", "send the quarrelsome people back to Egypt", "hand over all the judging to Aaron and his sons", "B", "Exodus 18: Jethro taught delegation — choose capable, God-fearing men as rulers of thousands, hundreds, fifties and tens."),
    ("Leadership Qualities", "Medium", "A class captain who divides duties among group leaders instead of doing everything himself is applying the lesson Moses learnt from", "Aaron", "Pharaoh", "Jethro", "Joshua", "C", "Jethro's counsel to Moses (Exodus 18) is the biblical model of delegation of responsibility."),
    ("Divine Providence, Guidance and Protection", "Medium", "During the wilderness journey God guided the Israelites by day and by night with", "a pillar of cloud and a pillar of fire", "Moses' rod and Aaron's staff", "the ark and the tabernacle", "angels and prophets", "A", "Exodus 13:21 — a pillar of cloud by day and a pillar of fire by night led the way."),
    ("Parental Responsibility", "Medium", "Eli the priest was judged by God mainly because he", "offered sacrifices that were not according to the law", "failed to restrain his sons Hophni and Phinehas from their wickedness", "refused to train the boy Samuel in the service of God", "stole the offerings of the people from the sanctuary", "B", "1 Samuel 2–3: Eli honoured his sons above God by not restraining them, so judgment came on his house."),
    ("Obedience and Disobedience", "Medium", "Samuel told Saul, 'To obey is better than sacrifice', after Saul", "built an altar to the Lord without Samuel's permission", "spared King Agag and the best of the Amalekite animals contrary to God's command", "refused to lead Israel against the Philistines", "consulted the medium at Endor about the Philistines", "B", "1 Samuel 15: Saul kept the best animals 'to sacrifice' instead of destroying everything as commanded, and lost the kingdom."),
    ("A Man after God's Own Heart", "Medium", "Nathan told David a parable about a rich man who took a poor man's only ewe lamb. The purpose of the parable was to", "praise David for his generosity to the poor", "make David condemn himself for taking Uriah's wife", "ask David to provide a lamb for the sacrifice", "warn David about the rebellion of Absalom", "B", "2 Samuel 12: when David condemned the rich man, Nathan said, 'You are the man', exposing his sin with Bathsheba."),
    ("A Man after God's Own Heart", "Medium", "When Nathan confronted David over his sin with Bathsheba, David's response was to", "order that Nathan be put to death", "deny the charge and demand witnesses", "confess, saying 'I have sinned against the Lord'", "blame Bathsheba for tempting him", "C", "2 Samuel 12:13 — David's immediate confession and repentance (see also Psalm 51) is why he is called a man after God's own heart."),
    ("Decision-Making", "Medium", "Rehoboam rejected the advice of the elders and followed the advice of his young friends to increase the people's burdens. The result was that", "the people loved him more", "the kingdom was divided", "he conquered Egypt", "Solomon returned to the throne", "B", "1 Kings 12: ten tribes revolted under Jeroboam, leaving Rehoboam with Judah and Benjamin."),
    ("Decision-Making", "Medium", "When God asked Solomon at Gibeon what he wanted, Solomon asked for", "a long life on the throne of Israel", "great riches and honour", "the death of all his enemies", "an understanding mind to govern the people", "D", "1 Kings 3: Solomon asked for wisdom to discern between good and evil, and God added riches and honour."),
    ("Greed and Its Effects", "Medium", "Ahab wanted Naboth's vineyard. Jezebel arranged for Naboth to be falsely accused and stoned. The prophet who condemned Ahab for this was", "Elisha", "Elijah", "Nathan", "Micaiah", "B", "1 Kings 21: Elijah met Ahab in the vineyard and pronounced judgment on his house."),
    ("Greed and Its Effects", "Medium", "Gehazi, Elisha's servant, secretly collected gifts from Naaman after his master had refused them. His punishment was", "death by stoning", "leprosy", "banishment to Syria", "loss of his sight", "B", "2 Kings 5:27 — Naaman's leprosy clung to Gehazi and his descendants."),
    ("Greed and Its Effects", "Medium", "A cashier who quietly pockets money a customer left behind, thinking no one saw her, is repeating the sin of", "Achan", "Gehazi", "Judas", "Ananias", "B", "Like Gehazi (2 Kings 5), she takes for herself what she has no right to, believing it hidden."),
    ("The Supremacy of God", "Medium", "On Mount Carmel, Elijah proved that the Lord is God when", "rain fell after three and a half years of drought", "fire from heaven consumed his water-soaked sacrifice", "the prophets of Baal fled to the brook Kishon", "Ahab repented and destroyed the altars of Baal", "B", "1 Kings 18: the fire fell on Elijah's drenched altar and the people cried, 'The Lord, he is God.'"),
    ("Religious Reforms in Judah", "Medium", "The reforms of King Josiah began when", "he defeated the Assyrians at Megiddo", "the Book of the Law was found in the temple during repairs", "the prophet Isaiah rebuked him for idolatry", "he saw a vision of the Lord in the temple", "B", "2 Kings 22: Hilkiah found the Book of the Law; Josiah tore his clothes, renewed the covenant and destroyed idolatry."),
    ("Concern for Judah", "Medium", "Nehemiah, cup-bearer to the Persian king, wept and prayed when he heard that", "the temple had been burnt by the Babylonians", "the walls of Jerusalem were broken down and its gates burnt", "Ezra the scribe had died in Jerusalem", "the Jews in Jerusalem were worshipping Baal", "B", "Nehemiah 1: the report about Jerusalem's broken walls led him to seek permission to rebuild them."),
    ("Faith, Courage and Protection", "Medium", "Shadrach, Meshach and Abednego were thrown into the fiery furnace because they", "refused to bow down to Nebuchadnezzar's golden image", "prayed three times a day", "refused the king's food", "interpreted the king's dream wrongly", "A", "Daniel 3: they told the king that even if God did not deliver them, they would not serve his gods."),
    ("Faith, Courage and Protection", "Medium", "Daniel was thrown into the lions' den because he", "refused to eat the king's meat", "continued to pray to God despite the king's decree", "insulted King Darius", "refused to interpret the writing on the wall", "B", "Daniel 6: jealous officials tricked Darius into a decree, and Daniel kept praying openly three times a day."),
    ("God's Message to Nineveh", "Medium", "Jonah was angry after preaching in Nineveh because", "the people of Nineveh stoned him", "God spared the city when the people repented", "the king of Nineveh refused to listen to him", "the great fish swallowed him a second time", "B", "Jonah 4: he resented God's mercy on Israel's enemy; God used the plant and worm to teach him compassion."),
    ("Social Justice, True Religion and Divine Love", "Medium", "Amos condemned the people of Israel who 'sell the righteous for silver and the needy for a pair of sandals'. Amos was speaking against", "the worship of golden calves at Bethel", "social injustice and oppression of the poor", "the profaning of the Sabbath and new moon", "alliances with Assyria and Egypt", "B", "Amos 2:6 and 5:24 ('let justice roll down like waters') attack corruption and exploitation of the poor."),
    ("Social Justice, True Religion and Divine Love", "Medium", "God told Hosea to marry Gomer, an unfaithful woman, in order to", "punish Hosea for his earlier disobedience", "illustrate God's steadfast love for unfaithful Israel", "show that marriage to a foreigner is sinful", "qualify Hosea to serve as a priest", "B", "Hosea 1–3: Hosea's love for his adulterous wife pictured God's continued love for idolatrous Israel."),
    ("Holiness and Divine Call", "Medium", "In his vision in the temple, Isaiah cried 'Woe is me! For I am a man of unclean lips.' His lips were then cleansed by", "water from the laver in the temple", "a burning coal carried by a seraph", "the blood of a lamb sprinkled by a priest", "the anointing oil of the high priest", "B", "Isaiah 6: a seraph touched his mouth with a live coal and declared his guilt taken away; then he said, 'Here am I! Send me.'"),
    ("Punishment and Hope", "Medium", "Ezekiel's vision of the valley of dry bones that came to life symbolised", "the resurrection of Jesus on the third day", "the restoration of the exiled nation of Israel", "the destruction of Babylon by the Persians", "the creation of man from the dust of the ground", "B", "Ezekiel 37:11 — 'These bones are the whole house of Israel'; God would bring them back to their land."),
    ("The Baptism and Temptation of Jesus", "Medium", "In the wilderness the devil said to Jesus, 'If you are the Son of God, command these stones to become bread.' Jesus replied that", "man shall not live by bread alone", "you shall not tempt the Lord your God", "you shall worship the Lord only", "get behind me, Satan", "A", "Matthew 4:4 quotes Deuteronomy 8:3; the other replies belong to the second and third temptations."),
    ("Discipleship", "Medium", "A man told Jesus, 'I will follow you wherever you go.' Jesus answered, 'Foxes have holes and birds have nests, but the Son of Man has nowhere to lay his head.' Jesus meant that", "the man should first buy a house for them", "discipleship demands readiness to bear hardship", "he was homeless and needed the man's help", "the man should go home to his family", "B", "Luke 9:57–62 sets out the cost of discipleship: sacrifice, urgency and no looking back."),
    ("Miracles", "Medium", "Four men could not reach Jesus because of the crowd, so they lowered their paralysed friend through the roof. Jesus first said to the paralytic,", "'Rise, take up your bed'", "'Your sins are forgiven'", "'Your faith has made you well'", "'Go and sin no more'", "B", "Mark 2:5 — Jesus forgave his sins first, and healed him to prove that the Son of Man has authority to forgive sins."),
    ("Miracles", "Medium", "Jesus healed ten lepers, but only one returned to give thanks. That man was", "a Pharisee", "a Roman", "a Samaritan", "a Levite", "C", "Luke 17:16 — the grateful one was a Samaritan, a 'foreigner', which highlights ingratitude among Jesus' own people."),
    ("The Parables", "Medium", "In the parable of the Good Samaritan, the priest and the Levite passed by the wounded man. Jesus told this parable in answer to the question", "'Who is my neighbour?'", "'How many times shall I forgive?'", "'What must I do to be saved?'", "'Who is the greatest?'", "A", "Luke 10:29 — a lawyer asked, 'And who is my neighbour?'; Jesus ended, 'Go and do likewise.'"),
    ("The Parables", "Medium", "A student helps an injured stranger from a rival school get to the hospital, paying for his treatment. He is putting into practice the parable of the", "prodigal son", "good Samaritan", "talents", "rich fool", "B", "Practical mercy to someone outside one's own group is the lesson of the good Samaritan (Luke 10)."),
    ("The Parables", "Medium", "In the parable of the unforgiving servant, the servant whose debt of ten thousand talents was cancelled then", "forgave his fellow servant who owed him a hundred denarii", "seized a fellow servant who owed him a small sum and had him jailed", "paid off his fellow servant's debt to the king", "thanked the king and served him faithfully thereafter", "B", "Matthew 18:21–35 answers Peter's question about forgiving 'seventy times seven'."),
    ("The Parables", "Medium", "A rich man planned to pull down his barns and build bigger ones, saying to himself, 'Eat, drink, be merry.' God called him a fool because", "he refused to share his harvest with his labourers", "he laid up treasure for himself but was not rich towards God", "he had cheated his neighbours to acquire the land", "he did not pay tithes on the harvest to the priests", "B", "Luke 12:16–21 warns against covetousness: 'one's life does not consist in the abundance of possessions'."),
    ("The Sermon on the Mount", "Medium", "A boy is slapped by a classmate and, instead of retaliating, walks away and later helps the same boy with his homework. He is obeying Jesus' teaching to", "demand an eye for an eye and a tooth for a tooth", "turn the other cheek and love your enemies", "judge not, that you be not judged", "seek first the kingdom of God and his righteousness", "B", "Matthew 5:38–48 replaces retaliation with non-resistance and love for enemies."),
    ("The Sermon on the Mount", "Medium", "Jesus asked, 'Why do you see the speck in your brother's eye but do not notice the log in your own eye?' He was warning against", "false prophets", "hypocritical judgment of others", "anxiety about food and clothing", "swearing oaths", "B", "Matthew 7:1–5 — 'Judge not, that you be not judged.'"),
    ("The Great Confession", "Medium", "At Caesarea Philippi Jesus asked, 'Who do you say that I am?' The disciple who answered 'You are the Christ, the Son of the living God' was", "John", "Andrew", "Peter", "Thomas", "C", "Matthew 16:16 — Jesus replied that flesh and blood had not revealed this to Peter but the Father in heaven."),
    ("The Transfiguration", "Medium", "At the transfiguration the two Old Testament figures who appeared talking with Jesus were", "Abraham and Isaac", "Moses and Elijah", "David and Solomon", "Isaiah and Jeremiah", "B", "Matthew 17:3 — Moses (the Law) and Elijah (the Prophets) appeared, and Peter offered to build three booths."),
    ("The Triumphal Entry and the Cleansing of the Temple", "Medium", "When Jesus drove out the traders from the temple he said, 'My house shall be called a house of prayer, but you have made it", "a market'", "a den of robbers'", "a place of sacrifice'", "a synagogue'", "B", "Matthew 21:13 combines Isaiah 56:7 and Jeremiah 7:11."),
    ("The Last Supper", "Medium", "At the Last Supper, Jesus washed the disciples' feet in order to", "fulfil the requirements of the Passover law", "teach them humble service to one another", "prepare them for baptism with the Holy Spirit", "show the disciples that Judas was clean", "B", "John 13:14–15 — 'I have given you an example, that you also should do as I have done to you.'"),
    ("The Trials and the Death of Jesus", "Medium", "Pilate offered to release one prisoner at the feast. The crowd chose", "Barabbas", "Jesus", "Simon of Cyrene", "Joseph of Arimathea", "A", "Matthew 27:15–26 — the crowd, stirred by the chief priests, demanded Barabbas and shouted 'Crucify him' about Jesus."),
    ("Resurrection, Appearances and Ascension", "Medium", "Two disciples walking to Emmaus recognised the risen Jesus only when he", "showed them his wounds", "broke bread with them", "calmed the storm", "called Mary by name", "B", "Luke 24:30–31 — their eyes were opened at the breaking of bread."),
    ("Resurrection, Appearances and Ascension", "Medium", "Thomas said he would not believe unless he saw the nail marks. When he later saw Jesus he exclaimed,", "'It is the Lord!'", "'My Lord and my God!'", "'Rabboni!'", "'Truly this was the Son of God'", "B", "John 20:28; Jesus replied, 'Blessed are those who have not seen and yet believe.'"),
    ("Jesus' Teachings about Himself", "Medium", "Jesus said, 'I am the good shepherd. The good shepherd lays down his life for the sheep.' By this he contrasted himself with", "the Pharisees who were faithful shepherds", "the hireling who flees when the wolf comes", "Moses who led the flock", "John the Baptist", "B", "John 10:11–13 — the hired hand cares nothing for the sheep and abandons them."),
    ("Fellowship in the Early Church", "Medium", "Ananias and Sapphira died because they", "refused to sell their land for the common fund", "lied to the Holy Spirit about the price of the land they sold", "stole money from the apostles' common purse", "denied Jesus before the Sanhedrin", "B", "Acts 5:1–11 — the sin was not keeping part of the money but pretending to give all of it."),
    ("The Holy Spirit and the Mission of the Church", "Medium", "On the day of Pentecost the disciples spoke in other tongues, and the crowd from many nations", "could not understand a word they said", "each heard them speaking in his own language", "stoned them for blasphemy", "asked them for money and food", "B", "Acts 2:6–8; Peter then preached and about three thousand were baptised."),
    ("Opposition to the Gospel Message", "Medium", "When the Sanhedrin ordered Peter and John to stop preaching in the name of Jesus, they replied that", "they would obey the council", "they must obey God rather than men", "they would leave Jerusalem", "Paul would take over", "B", "Acts 4:19–20 and 5:29 — 'We cannot but speak of what we have seen and heard.'"),
    ("Opposition to the Gospel Message", "Medium", "Gamaliel advised the Sanhedrin to leave the apostles alone because", "they were Roman citizens protected by law", "a work of God cannot be overthrown by men", "Peter had healed his son of a fever", "the crowd would riot if they were harmed", "B", "Acts 5:34–39 — he cited the failed movements of Theudas and Judas the Galilean."),
    ("Mission to the Gentiles", "Medium", "Peter's vision of a sheet full of unclean animals, before he visited Cornelius, taught him that", "Jews were now free to eat pork and other unclean foods", "God shows no partiality and Gentiles may receive the gospel", "the law of Moses had been abolished completely", "Cornelius should first become a Jew by circumcision", "B", "Acts 10:28, 34 — 'God has shown me that I should not call any man common or unclean.'"),
    ("Mission to the Gentiles", "Medium", "The Council of Jerusalem decided that Gentile converts", "must be circumcised according to the custom of Moses", "need not be circumcised, but must avoid idol food, blood and immorality", "must keep the whole law of Moses to be saved", "could not be baptised until they kept the Sabbath", "B", "Acts 15:19–20 records James' judgment, sent by letter to Antioch."),
    ("Justification by Faith", "Medium", "Paul cited Abraham, who 'believed God, and it was counted to him as righteousness', to prove that a person is justified by", "works of the law", "faith", "circumcision", "sacrifice", "B", "Romans 4:1–5 and Galatians 3:6 — Abraham was counted righteous before he was circumcised or the law was given."),
    ("The Law and Grace", "Medium", "Paul called the law 'our custodian (schoolmaster) until Christ came' to show that the law", "saves all those who keep it perfectly", "was meant to lead people to Christ, who justifies by faith", "is no longer to be read in the churches", "was given only to the Gentiles, not the Jews", "B", "Galatians 3:24–25 — once faith has come, we are no longer under a custodian."),
    ("New Life in Christ", "Medium", "Paul wrote, 'If anyone is in Christ, he is a new creation; the old has passed away.' A convert who gives up cheating in examinations and lying is demonstrating", "civic responsibility", "the new life in Christ", "spiritual gifts", "impartiality", "B", "2 Corinthians 5:17 and Colossians 3:5–10 describe putting off the old nature and its practices."),
    ("Christians as Joint Heirs with Christ", "Medium", "According to Paul, believers are 'heirs of God and fellow heirs with Christ' provided that they", "pay their tithes faithfully to the church", "suffer with him so that they may be glorified with him", "are circumcised according to the law", "speak in tongues as evidence of the Spirit", "B", "Romans 8:16–17: the Spirit bears witness that we are children of God, and therefore heirs, 'provided we suffer with him'."),
    ("Humility", "Medium", "Paul urged the Philippians to have the mind of Christ, who 'though he was in the form of God ... emptied himself, taking the form of a servant'. The virtue being taught is", "courage", "humility", "generosity", "patience", "B", "Philippians 2:5–11 — Christ's self-emptying is the model of humility; therefore God highly exalted him."),
    ("Forgiveness", "Medium", "Paul wrote to Philemon asking him to receive back Onesimus, his runaway slave,", "as a runaway slave to be punished severely", "no longer as a slave but as a beloved brother", "only after Onesimus had repaid what he stole", "as Paul's replacement in the Colossian church", "B", "Philemon 15–17 — Paul offered to pay whatever Onesimus owed."),
    ("Spiritual Gifts", "Medium", "Paul compared the church to a human body with many members to teach that", "some spiritual gifts are useless to the church", "every member's gift is needed and none should despise another's", "only the apostles and prophets really matter", "the body can manage without its weaker parts", "B", "1 Corinthians 12:12–27 — 'the eye cannot say to the hand, I have no need of you'."),
    ("Christian Giving", "Medium", "Paul praised the Macedonian churches because, in deep poverty, they", "gave nothing", "gave generously, even beyond their means", "borrowed to give", "gave only to the apostles", "B", "2 Corinthians 8:1–5; and 9:7 — 'God loves a cheerful giver'."),
    ("Civic Responsibility", "Medium", "A Christian who pays his taxes honestly and obeys traffic laws, even when nobody is watching, is following Paul's teaching in Romans 13 that", "Christians are above the laws of the state", "governing authorities are instituted by God and must be obeyed", "taxes are unjust and need not be paid", "only the laws of the church are binding", "B", "Romans 13:1–7 — 'pay taxes to whom taxes are due, respect to whom respect is due'."),
    ("Dignity of Labour", "Medium", "Paul told the Thessalonians, 'If anyone will not work, let him not eat', because some members were", "too poor to find any work in the city of Thessalonica", "idle busybodies living off other members", "working on the Sabbath against the law", "refusing to pay tithes to the elders", "B", "2 Thessalonians 3:6–12 — Paul himself worked night and day so as not to burden anyone."),
    ("The Second Coming of Christ", "Medium", "Paul told the Thessalonians that the day of the Lord will come 'like a thief in the night'. He meant that Christians should", "calculate the exact date from the prophets", "stop working and wait on the mountains", "be watchful and live soberly since the time is unknown", "sell their property and give to the church", "C", "1 Thessalonians 5:1–11 — 'let us keep awake and be sober'."),
    ("Impartiality", "Medium", "James condemned church members who gave a rich man in fine clothes the best seat while telling a poor man to sit on the floor. This sin is", "greed", "partiality (favouritism)", "hypocrisy in prayer", "idolatry", "B", "James 2:1–9 — 'if you show partiality, you commit sin'."),
    ("Effective Prayer", "Medium", "James gave Elijah as an example of effective prayer because Elijah", "was an angel sent from heaven", "prayed for drought and later for rain, and both happened", "prayed in the temple three times every day", "never sinned throughout his life", "B", "James 5:16–18 — 'The prayer of a righteous man has great power'; Elijah was 'a man of like nature with ourselves'."),
    ("Corruption", "Medium", "Simon the sorcerer offered the apostles money so that he too could give the Holy Spirit by laying on hands. Peter's response teaches that", "spiritual gifts can be bought by the rich", "the gift of God cannot be obtained with money", "sorcery is acceptable", "money should be given to apostles", "B", "Acts 8:18–24 — 'Your silver perish with you'; buying church office is still called simony."),
    ("Sexual Immorality", "Medium", "Joseph refused the advances of Potiphar's wife, saying, 'How can I do this great wickedness and sin against God?' He was later", "rewarded by Potiphar", "falsely accused and imprisoned", "sent back to Canaan", "made a priest", "B", "Genesis 39 — Joseph chose purity at great cost, yet God was with him in prison."),
    ("Sexual Immorality", "Medium", "Paul told the Corinthians to 'flee from sexual immorality' because the believer's body is", "his own to use as he likes", "a temple of the Holy Spirit, bought with a price", "unimportant compared with the soul", "already condemned", "B", "1 Corinthians 6:18–20 — 'glorify God in your body'."),
    ("Love", "Medium", "According to Paul in 1 Corinthians 13, a person who speaks in tongues, has prophetic powers and gives away all he has, but has not love,", "is the greatest in the kingdom", "is nothing and gains nothing", "will still be rewarded", "should be made an elder", "B", "1 Corinthians 13:1–3; 'the greatest of these is love'."),
]

IRS = [
    ("The Qur'an", "Medium", "The first verses of the Qur'an revealed to Prophet Muhammad (SAW) in the cave of Hira began with the command", "'Iqra' (Read)", "'Qul' (Say)", "'Sabbih' (Glorify)", "'Qum' (Arise)", "A", "Surah Al-'Alaq (96:1–5) opens 'Read in the name of your Lord who created', brought by the angel Jibril."),
    ("The Qur'an", "Medium", "Surah Al-Fatihah is recited in every rak'ah of Salah. It is also known as", "Umm al-Kitab (the Mother of the Book)", "Ayat al-Kursi (the Verse of the Throne)", "Surah Al-Ikhlas (the Chapter of Sincerity)", "Khatm al-Qur'an (the Seal of the Qur'an)", "A", "Al-Fatihah is called Umm al-Kitab and As-Sab' al-Mathani (the seven oft-repeated verses)."),
    ("The Qur'an", "Medium", "The Surah that declares 'Say: He is Allah, the One; Allah the Eternal; He begets not, nor was He begotten' is", "Al-Kawthar", "Al-Ikhlas", "An-Nasr", "Al-Asr", "B", "Surah Al-Ikhlas (112) is the clearest statement of Tawhid and is said to equal a third of the Qur'an in reward."),
    ("The Qur'an", "Medium", "Surah Al-Asr teaches that all mankind is in loss except those who", "are wealthy, powerful and respected in society", "believe, do righteous deeds, and enjoin one another to truth and patience", "fast every Monday and Thursday throughout the year", "perform Hajj and Umrah every year of their lives", "B", "Surah 103 gives four conditions for salvation: faith, good deeds, mutual counsel to truth and to patience."),
    ("Hadith", "Medium", "A student fasts only so that his classmates will praise his piety. According to the Hadith 'Actions are judged by intentions', his fast", "is doubly rewarded because others were encouraged", "earns no reward with Allah because the intention was to be seen", "is fully rewarded because he abstained from food and drink", "counts as a voluntary fast of the highest grade", "B", "The first Hadith in Bukhari: 'every person will get what he intended' — worship done for show (riya') is worthless."),
    ("Hadith", "Medium", "A trader hides the fault in the goods he sells. The Prophet (SAW) said of such a person:", "'He is a wise trader'", "'Whoever cheats is not one of us'", "'Trade is half of faith'", "'He has performed jihad'", "B", "The Prophet found wet grain hidden under dry grain in the market and declared, 'Man ghashshana fa laysa minna'."),
    ("Hadith", "Medium", "The Prophet (SAW) said, 'The strong man is not the one who overcomes others in wrestling, but the one who ______.'", "has the most wealth", "controls himself when angry", "wins every argument", "prays the longest", "B", "The Hadith (Bukhari and Muslim) redefines strength as self-control."),
    ("Hadith", "Medium", "According to the Hadith, 'None of you truly believes until he", "loves for his brother what he loves for himself'", "performs Hajj to the House of Allah'", "memorises the whole of the Qur'an'", "gives away all his wealth in charity'", "A", "Reported by Bukhari and Muslim; it is the basis of Islamic brotherhood."),
    ("Tawhid and the Oneness of Allah", "Medium", "A man wears a charm because he believes it, and not Allah, protects him from harm. This belief is", "Ihsan", "Shirk", "Taqwa", "Ikhlas", "B", "Attributing power that belongs to Allah alone to anything else is shirk, the gravest sin (Qur'an 4:48)."),
    ("The Attributes of Allah", "Medium", "The Ayat al-Kursi states that 'neither slumber nor sleep overtakes Him'. This describes Allah's attribute of being", "Al-Hayy Al-Qayyum (the Ever-Living, Self-Sustaining)", "Ar-Rahman Ar-Rahim (the Most Gracious, Most Merciful)", "Al-Ghafur Ar-Rahim (the Forgiving, the Merciful)", "Al-Malik Al-Quddus (the King, the Holy)", "A", "Qur'an 2:255 begins 'Allah — there is no god but He, the Living, the Self-Subsisting'."),
    ("The Articles of Faith", "Medium", "A Muslim who loses his business in a fire says, 'This is from Allah; I accept it and will work again.' He is showing belief in", "the angels", "Qadar (divine decree)", "the revealed books", "the prophets", "B", "Acceptance of what Allah has decreed, good or bad, is belief in Qadar, the sixth article of faith."),
    ("The Articles of Faith", "Medium", "The angel responsible for bringing revelation to the prophets is", "Mika'il", "Israfil", "Jibril", "Izra'il", "C", "Jibril (Gabriel) brought the Qur'an to Prophet Muhammad; Mika'il oversees rain and provision; Israfil blows the trumpet."),
    ("Salah", "Medium", "The total number of obligatory (fard) rak'ahs a Muslim prays in the five daily prayers is", "12", "15", "17", "20", "C", "Fajr 2 + Zuhr 4 + Asr 4 + Maghrib 3 + Isha 4 = 17 rak'ahs."),
    ("Salah", "Medium", "A traveller on a journey of about 300 km shortens Zuhr from four rak'ahs to two. This concession is called", "Qada", "Qasr", "Jam'", "Tayammum", "B", "Qasr is the shortening of four-rak'ah prayers on a journey (Qur'an 4:101); Jam' is combining two prayers."),
    ("Salah", "Medium", "A Muslim in the desert finds no water for ablution before prayer. He should", "skip the prayer", "perform tayammum with clean earth", "pray without purification", "wait until he reaches a town", "B", "Qur'an 5:6 permits tayammum (dry ablution) when water is unavailable or its use is harmful."),
    ("Zakat", "Medium", "Alhaji Musa has kept ₦4,000,000 in savings, above the nisab, for a full lunar year. The Zakat due on it is", "₦40,000", "₦100,000", "₦200,000", "₦400,000", "B", "Zakat on money is 2.5%: 4,000,000 × 2.5/100 = ₦100,000."),
    ("Zakat", "Medium", "Which of the following is NOT among the eight categories entitled to receive Zakat according to Qur'an 9:60?", "the poor who have nothing", "those in debt who cannot repay", "wayfarers stranded on a journey", "the wealthy relatives of the giver", "D", "The eight recipients are the poor, the needy, Zakat collectors, those whose hearts are to be reconciled, captives, debtors, in the cause of Allah, and wayfarers."),
    ("Zakat", "Medium", "The Zakat paid by every Muslim who can afford it before the Eid-ul-Fitr prayer, on behalf of each member of the household, is", "Zakat al-Mal", "Zakat al-Fitr", "Sadaqah jariyah", "Khums", "B", "Zakat al-Fitr purifies the fasting person and feeds the poor on the day of Eid."),
    ("Sawm", "Medium", "A pregnant woman fears that fasting will harm her baby. Islamic law allows her to", "fast only at night", "break the fast and make up the missed days later", "abandon fasting permanently with no compensation", "fast every alternate day", "B", "The sick, travellers, pregnant and nursing women may postpone the fast and make it up (Qur'an 2:184–185)."),
    ("Sawm", "Medium", "A very old man is permanently unable to fast in Ramadan. He should", "make up the days after Ramadan when he feels stronger", "pay fidyah by feeding a poor person for each day missed", "perform Hajj instead of fasting that year", "pray extra rak'ahs each night in place of the fast", "B", "Qur'an 2:184 — those who cannot fast at all give fidyah (feeding a needy person per day)."),
    ("Sawm", "Medium", "While fasting, a man forgetfully eats a piece of bread. His fast", "is broken and must be repeated", "remains valid; he should continue fasting", "is broken and requires 60 days' expiation", "is converted to a voluntary fast", "B", "The Prophet said whoever eats or drinks forgetfully should complete his fast, for it was Allah who fed him."),
    ("Hajj", "Medium", "The rite of Hajj without which the pilgrimage is invalid, performed on the 9th of Dhul-Hijjah, is", "Tawaf al-Qudum", "standing at Arafah (Wuquf)", "Sa'y between Safa and Marwah", "stoning the Jamarat", "B", "The Prophet said 'Al-Hajj Arafah' — Hajj is Arafah."),
    ("Hajj", "Medium", "Hajj is obligatory on a Muslim", "every year for as long as he lives", "once in a lifetime, if physically and financially able", "only after he reaches the age of sixty", "only if he is a man and head of a family", "B", "Qur'an 3:97 — pilgrimage is a duty owed to Allah by those who can find a way to it."),
    ("Hajj", "Medium", "The walking seven times between the hills of Safa and Marwah during Hajj commemorates", "the Prophet's Hijrah from Makkah to Madinah", "Hajar's search for water for her son Isma'il", "the Muslims' march to the battle of Badr", "the digging of the trench around Madinah", "B", "Sa'y re-enacts Hajar running between the two hills before the well of Zamzam gushed forth."),
    ("Jihad and Self-Discipline", "Medium", "The Prophet (SAW) described the struggle against one's own evil desires as", "the lesser jihad (jihad al-asghar)", "the greater jihad (jihad an-nafs)", "hijrah (migration for the sake of Allah)", "shura (consultation among believers)", "B", "Self-discipline against the lower self is called the greater jihad; armed struggle in defence of the faith is the lesser."),
    ("The Life of Prophet Muhammad", "Medium", "Prophet Muhammad (SAW) was born in Makkah in the year", "the Elephant (about 570 CE)", "the Hijrah (622 CE)", "of Badr (624 CE)", "of the Trench (627 CE)", "A", "He was born in 'Am al-Fil, the year Abrahah's army with an elephant attacked the Ka'bah and was destroyed."),
    ("The Life of Prophet Muhammad", "Medium", "When the Quraysh clans quarrelled over who should replace the Black Stone during the rebuilding of the Ka'bah, Muhammad (SAW) settled it by", "choosing his own clan, Banu Hashim, to place it", "placing the stone on a cloth so that all the clan leaders lifted it together", "asking his uncle Abu Talib to decide between the clans", "leaving the stone on the ground until the quarrel ended", "B", "The incident earned him the title Al-Amin (the trustworthy) and shows his wisdom and justice even before prophethood."),
    ("The Hijrah", "Medium", "The Islamic calendar begins from the year of", "the Prophet's birth in the year of the Elephant", "the first revelation in the cave of Hira", "the Prophet's migration from Makkah to Madinah (622 CE)", "the conquest of Makkah by the Muslims", "C", "Caliph Umar fixed the Hijrah of 622 CE as year 1 AH."),
    ("The Hijrah", "Medium", "During the Hijrah, the Prophet (SAW) and Abu Bakr hid for three days in", "the cave of Hira", "the cave of Thawr", "the house of Arqam", "Masjid Quba", "B", "A spider's web and a dove's nest at the mouth of the cave of Thawr turned the pursuers away."),
    ("The Prophet Muhammad as a Leader", "Medium", "On entering Madinah, the Prophet (SAW) established a written agreement between the Muslims, the Jews and other tribes of the city, known as", "the Treaty of Hudaybiyyah", "the Constitution (Sahifah) of Madinah", "the Pledge of Aqabah", "the Farewell Sermon", "B", "The Sahifah guaranteed mutual defence and religious freedom, creating one community (ummah) under the Prophet's authority."),
    ("The Prophet Muhammad as a Model", "Medium", "On the conquest of Makkah, the Prophet (SAW) said to the Makkans who had persecuted him for years, 'Go, you are free.' This shows his quality of", "vengeance", "forgiveness and magnanimity", "weakness", "indecision", "B", "He forgave his enemies at the moment of total victory, following the example of Prophet Yusuf."),
    ("The Rightly Guided Caliphs", "Medium", "After many huffaz (memorisers of the Qur'an) died at the battle of Yamamah, the first collection of the Qur'an into a single volume was ordered by", "Ali", "Uthman", "Abu Bakr", "Mu'awiyah", "C", "Abu Bakr, on Umar's advice, appointed Zayd ibn Thabit to compile the Qur'an; Uthman later standardised copies."),
    ("The Rightly Guided Caliphs", "Medium", "The caliph who introduced the Hijrah calendar, established the Bayt al-Mal (public treasury) departments and appointed judges in the provinces was", "Abu Bakr", "Umar ibn al-Khattab", "Uthman ibn Affan", "Ali ibn Abi Talib", "B", "Umar's ten-year caliphate (634–644 CE) built the administrative institutions of the Islamic state."),
    ("The Muslim Community in Madinah", "Medium", "On arrival in Madinah, the Prophet (SAW) paired each emigrant from Makkah (Muhajir) with a resident of Madinah (Ansar) as brothers. This bond is called", "Bay'ah", "Mu'akhah (brotherhood)", "Shura", "Zakat", "B", "The Ansar shared their homes and property with the Muhajirun, uniting the community."),
    ("Marriage and Divorce", "Medium", "Which of the following makes an Islamic marriage contract (nikah) valid?", "a lavish ceremony attended by both families", "offer and acceptance, the bride's guardian (wali), two witnesses and mahr", "registration of the marriage at a court or registry", "the couple living together for at least one year", "B", "These are the essential pillars of nikah; the mahr (dower) is the wife's right, not the family's."),
    ("Marriage and Divorce", "Medium", "The waiting period (iddah) of a widow, if she is not pregnant, is", "one month", "three menstrual cycles", "four months and ten days", "one year", "C", "Qur'an 2:234; a divorced woman waits three menstrual cycles (2:228); a pregnant woman until delivery."),
    ("Rights and Duties of Parents and Children", "Medium", "The Qur'an commands: 'Say not to them (your parents) a word of contempt (uff), nor repel them, but address them in terms of honour.' A son who shouts at his aged mother is violating", "Surah Al-Isra' 17:23", "the law of inheritance", "the rules of Zakat", "the rites of Hajj", "A", "Kindness to parents (birr al-walidayn) is placed immediately after the worship of Allah in 17:23–24."),
    ("Brotherhood and Social Relations", "Medium", "A Muslim who spreads a rumour about his neighbour without verifying it violates the Qur'anic command in Surah Al-Hujurat to", "fast on Mondays and Thursdays as expiation", "verify news brought by a wrongdoer and avoid suspicion and backbiting", "give charity in secret so the left hand does not know", "lower the voice in the Prophet's presence", "B", "Qur'an 49:6 and 49:12 forbid acting on unverified reports, suspicion, spying and backbiting."),
    ("Justice and Fairness", "Medium", "The Qur'an commands believers to 'stand out firmly for justice, as witnesses to Allah, even if it be against yourselves, or your parents or kin'. A witness who tells the truth in court although it harms his own brother is obeying", "Surah An-Nisa' 4:135", "the rules of Sawm", "the rites of Umrah", "the law of Qasr", "A", "Justice in Islam is owed even against oneself and one's relatives, and also to enemies (5:8)."),
    ("Honesty and Trustworthiness", "Medium", "A shopkeeper who uses a false measure to give customers less than they pay for is condemned in the Qur'an in", "Surah Al-Mutaffifin (Those Who Deal in Fraud)", "Surah Al-Kawthar (The Abundance)", "Surah Al-Fil (The Elephant)", "Surah Quraysh (The Tribe of Quraysh)", "A", "Surah 83 opens 'Woe to those who give less in measure and weight'."),
    ("Prohibition of Corruption and Oppression", "Medium", "A contractor gives a government official money so that he will be awarded a road contract he does not merit. The Prophet (SAW) said about such a transaction:", "'It is a gift, and gifts are permitted'", "'Allah's curse is on the one who gives a bribe and the one who takes it'", "'It is permitted if it secures lawful business'", "'Only the one who takes the money is guilty'", "B", "Reported by Abu Dawud and Tirmidhi; bribery (rishwah) is forbidden for both parties."),
    ("Islamic Economic Principles", "Medium", "A bank offers a Muslim a loan of ₦1,000,000 to be repaid as ₦1,300,000 after one year. The extra ₦300,000 is", "zakat, which is obligatory", "riba (usury), which is forbidden", "mahr, which is the wife's right", "sadaqah, which is voluntary charity", "B", "Qur'an 2:275 — 'Allah has permitted trade and forbidden riba'; any fixed increase on a loan is riba."),
    ("Lawful and Unlawful Activities", "Medium", "Which of the following foods is permitted (halal) for a Muslim?", "pork", "an animal that died of itself (carrion)", "a goat slaughtered with the name of Allah pronounced over it", "an animal slaughtered in the name of an idol", "C", "Qur'an 5:3 lists carrion, blood, pork and animals dedicated to other than Allah as forbidden."),
    ("Islamic Political Administration", "Medium", "Before deciding to meet the Makkan army outside Madinah at Uhud, the Prophet (SAW) consulted his companions and followed the majority view. This illustrates the principle of", "Shura (consultation)", "Qiyas", "Ijma' of the scholars", "Taqlid", "A", "Qur'an 42:38 describes believers as those 'whose affairs are conducted by mutual consultation'."),
    ("Shura and Leadership", "Medium", "In his first speech as caliph, Abu Bakr said, 'Obey me so long as I obey Allah and His Messenger; if I disobey them, you owe me no obedience.' This shows that in Islam a leader", "is above the law once he has been chosen", "must be obeyed only within the limits of Allah's law", "cannot be criticised by ordinary believers", "rules by inheritance from the previous caliph", "B", "Leadership in Islam is a trust (amanah) and obedience is conditional on obedience to Allah."),
    ("Relations with Non-Muslims", "Medium", "The Qur'anic verse 'There is no compulsion in religion' (2:256) teaches that Muslims should", "force non-Muslims to accept Islam", "not compel anyone to accept Islam", "avoid all contact with non-Muslims", "never trade with non-Muslims", "B", "Faith must be freely accepted; the Prophet protected the religious freedom of non-Muslims under his rule."),
    ("Islamic History and Expansion", "Medium", "The first major battle between the Muslims and the Makkan Quraysh, in which about 313 Muslims defeated a much larger army in 2 AH (624 CE), was the battle of", "Uhud", "Badr", "the Trench (Khandaq)", "Hunayn", "B", "Badr was a decisive victory; Uhud (3 AH) followed, then the Trench (5 AH)."),
    ("Islamic History and Expansion", "Medium", "At the battle of the Trench (Khandaq), the Muslims defended Madinah by digging a ditch on the advice of", "Abu Bakr", "Salman al-Farisi", "Khalid ibn al-Walid", "Bilal", "B", "Salman the Persian suggested the Persian tactic of a defensive trench; the confederates' siege failed."),
    ("Islam and Contemporary Social Issues", "Medium", "A Muslim youth is offered alcohol at a party. The Qur'an (5:90) describes intoxicants, gambling and idols as", "permitted in moderation for adults", "an abomination of Satan's handiwork, to be avoided", "lawful at all times outside the month of Ramadan", "a matter of personal choice for each believer", "B", "Surah Al-Ma'idah 5:90–91 commands believers to shun them so that they may prosper."),
    ("Family Life in Islam", "Medium", "The Prophet (SAW) said, 'The best of you are those who are best to their wives.' A husband who treats his wife harshly is", "acting within his rights", "acting against the Prophet's teaching and example", "following the Sunnah", "exempt because he provides for her", "B", "Reported by Tirmidhi; the Prophet's own gentleness at home is the model (Qur'an 4:19: 'live with them in kindness')."),
    ("Worship in Islam", "Medium", "A Muslim who prays, fasts and gives charity but also cheats his business partners has neglected the part of worship called", "Ibadah (ritual worship)", "Mu'amalat (dealings with people)", "Aqidah (articles of belief)", "Tajwid (rules of recitation)", "B", "Islam covers both ibadat (rituals) and mu'amalat (transactions); the Prophet said the bankrupt is one whose prayers are cancelled by wrongs done to others."),
]


def build():
    questions = []
    passages = [{"key": "L1", "title": POEM1[0], "text": POEM1[1]}, {"key": "L2", "title": POEM2[0], "text": POEM2[1]}, {"key": "L3", "title": PROSE[0], "text": PROSE[1]}]
    for key, diff, q, a, b, c, d, ans, exp in LIT_PASSAGE:
        questions.append({"subject": "Literature in English", "topic": "Literary Appreciation", "passage": key, "difficulty": diff, "q": q, "A": a, "B": b, "C": c, "D": d, "answer": ans, "explanation": exp})
    for subject, rows in (("Literature in English", LIT), ("Christian Religious Studies", CRS), ("Islamic Religious Studies", IRS)):
        for topic, diff, q, a, b, c, d, ans, exp in rows:
            questions.append({"subject": subject, "topic": topic, "difficulty": diff, "q": q, "A": a, "B": b, "C": c, "D": d, "answer": ans, "explanation": exp})
    _balance(questions)
    texts = [x["q"] for x in questions]
    assert len(texts) == len(set(texts)), "duplicate question text"
    assert all(x["answer"] in "ABCD" and all(x[k] for k in "ABCD") for x in questions)
    batch = {
        "batch_id": "batch_004_lit_crs_irs",
        "exam_type": "JAMB",
        "note": "Literature: unseen poems/prose with appreciation questions + devices inside quoted lines; CRS and IRS: situation-based application of the set narratives.",
        "passages": passages,
        "questions": questions,
        "deactivate": [],
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(batch, fh, ensure_ascii=False, indent=1)
    from collections import Counter
    print(f"wrote {OUT}: {len(questions)} questions, {len(passages)} passages")
    print("answer letters:", dict(Counter(x['answer'] for x in questions)))
    print("per subject:", dict(Counter(x['subject'] for x in questions)))


if __name__ == "__main__":
    build()
