"""Batch 050 - WAEC/NECO Government, Paper 1 round 1.

WASSCE Government Paper 1 is a 50-item objective paper (60 minutes).  This batch
covers the SSCE syllabus: meaning and scope of government, basic political
concepts, constitutions, organs of government, political parties and pressure
groups, elections, the development of the Nigerian constitution, colonial
administration, nationalism, federalism, local government, the civil service,
public corporations, the military in politics, Nigerian foreign policy and
international organisations.  All items are stable historical and definitional
facts (dates checked against standard SSCE texts).

    python3 scripts/build_content_batch50.py -> content/batch_050_waec_government.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Government"

T_SCOPE = "Meaning and Scope of Government"
T_CONCEPT = "Basic Political Concepts"
T_CONST = "Constitutions"
T_ORGANS = "Organs of Government"
T_PARTY = "Political Parties and Party Systems"
T_PRESS = "Pressure Groups and Public Opinion"
T_ELECT = "Electoral Systems"
T_NIGCON = "Development of the Nigerian Constitution"
T_COLON = "Colonial Administration"
T_NAT = "Nationalism in Nigeria"
T_FED = "Federalism and Regionalism"
T_LOCAL = "Local Government"
T_CIVIL = "The Civil Service"
T_PUB = "Public Corporations"
T_MIL = "The Military in Nigerian Politics"
T_FOREIGN = "Nigerian Foreign Policy"
T_INT = "International Organisations"

PASSAGES = []
PQ = []

Q = [
    # ------------------------------------------------------- meaning and scope
    (T_SCOPE, "Easy", "Government is best defined as the machinery or body that",
     "administers the affairs of a state", "owns all the land in a country", "controls private businesses only", "runs schools and hospitals", "A",
     "Government is the institution through which the will of the state is formulated and executed.", None),
    (T_SCOPE, "Easy", "A state differs from a nation because a state is a political entity while a nation is",
     "a people united by common identity", "always larger than any state", "a purely legal creation only", "always a democratic country", "A",
     "Nations are bound by shared culture and feeling; states are defined by government and territory.", None),
    (T_SCOPE, "Medium", "Which of these is NOT an essential feature of a state?",
     "A written constitution", "A defined territory", "A permanent population", "A government", "A",
     "A state may exist with an unwritten constitution, as Britain does.", None),
    (T_SCOPE, "Medium", "The two broad arms of government theory are the"
     " organs that make and that administer laws. Law-making belongs to the",
     "legislature", "executive", "judiciary", "civil service", "A",
     "The legislature deliberates and passes laws for the state.", None),
    (T_SCOPE, "Easy", "Sovereignty of a state means its",
     "supreme and final legal authority", "membership of the United Nations", "the strength of its army", "the size of its population", "A",
     "A sovereign state answers to no higher earthly authority in legal terms.", None),
    (T_SCOPE, "Medium", "The study of government at the secondary school level mainly aims to produce citizens who are",
     "politically aware and active citizens", "successful traders and merchants", "civil servants and their families", "lawyers and court officials only", "A",
     "Knowledge of government equips citizens to take part in public affairs wisely.", None),
    (T_SCOPE, "Easy", "The four main functions of government include making laws, executing laws, adjudicating disputes and",
     "defending the state", "printing textbooks", "running markets", "building churches", "A",
     "Maintaining law and order and defending the territory are core duties.", None),

    # -------------------------------------------------------- basic concepts
    (T_CONCEPT, "Medium", "Power differs from authority in that authority is power that is",
     "recognised as legitimate", "always physical", "never obeyed", "held by the rich", "A",
     "Authority is legitimate power accepted by those over whom it is exercised.", None),
    (T_CONCEPT, "Easy", "Legitimacy refers to the acceptance of a government's right to rule by the",
     "people over whom it rules", "foreign investors", "courts alone", "civil servants", "A",
     "A legitimate government is obeyed willingly, not merely out of fear.", None),
    (T_CONCEPT, "Medium", "Political power that is acquired and exercised according to the law is described as",
     "constitutional power", "raw power", "military force", "economic power", "A",
     "Constitutional power flows from the provisions of the constitution.", None),
    (T_CONCEPT, "Easy", "Democracy is a system of government in which supreme power ultimately belongs to the",
     "people", "army", "judges", "wealthy class", "A",
     "Abraham Lincoln's phrase 'government of the people, by the people, for the people' captures it.", None),
    (T_CONCEPT, "Medium", "Direct democracy is practicable only in communities that are",
     "small enough for citizens to assemble", "highly industrialised and urban", "very large in size and population", "governed by military rulers", "A",
     "Every citizen cannot gather to debate in a large modern state.", None),
    (T_CONCEPT, "Medium", "In a representative democracy, citizens exercise power through",
     "elected representatives", "soldiers", "traditional rulers", "court clerks", "A",
     "Elections select the few who act for the many.", None),
    (T_CONCEPT, "Easy", "Political culture refers to the attitudes, beliefs and values people hold about",
     "politics and government", "farming methods", "religious rites", "football", "A",
     "It shapes how citizens relate to authority and participation.", None),
    (T_CONCEPT, "Hard", "The rule of law means that everybody, including rulers, is subject to the",
     "same ordinary law in ordinary courts", "wishes of the president in office", "decrees of the soldiers in power", "decisions of party chiefs alone", "A",
     "A. V. Dicey's principle places law above every person, however powerful.", None),
    (T_CONCEPT, "Medium", "Separation of powers, as propounded by Montesquieu, divides the functions of government among the legislature, executive and",
     "judiciary", "police", "civil service", "press", "A",
     "Each organ checks the others to prevent tyranny.", None),
    (T_CONCEPT, "Medium", "Checks and balances exist in a constitution to ensure that",
     "no organ of government becomes too powerful", "the police can arrest the judges", "one party rules the country forever", "elections are cancelled at will", "A",
     "Each organ can restrain the excesses of the others.", None),
    (T_CONCEPT, "Easy", "A constitution is best described as the",
     "fundamental law of a state", "budget of a country", "rule book of a football club", "register of voters", "A",
     "It defines the organs of government, their powers and the citizens' rights.", None),
    (T_CONCEPT, "Medium", "A written constitution is one that is",
     "embodied in a single formal document", "passed by word of mouth", "kept secret from citizens", "made by judges alone", "A",
     "The Nigerian constitution of 1999 is a written, codified document.", None),
    (T_CONCEPT, "Hard", "The British constitution is often described as flexible because it can be amended by the",
     "ordinary legislative process", "courts alone", "army", "queen without parliament", "A",
     "No special cumbersome procedure guards every part of it.", None),
    (T_CONCEPT, "Medium", "A rigid constitution can only be amended through a",
     "special and more difficult procedure", "simple majority vote", "presidential announcement", "referendum only", "A",
     "The United States constitution illustrates rigidity.", None),
    (T_CONCEPT, "Hard", "A unitary constitution concentrates all constitutional powers in the",
     "central government alone", "states or regions", "local councils", "courts", "A",
     "Sub-national units exist at the centre's pleasure in a unitary state.", None),

    # -------------------------------------------------------------- organs
    (T_ORGANS, "Easy", "The organ of government responsible for interpreting the law is the",
     "judiciary", "legislature", "executive", "civil service", "A",
     "Courts interpret statutes and settle disputes according to law.", None),
    (T_ORGANS, "Medium", "The main function of the executive is to",
     "implement and enforce laws", "make new laws", "interpret the constitution", "try criminal suspects", "A",
     "Ministries and agencies carry out government policies.", None),
    (T_ORGANS, "Medium", "In Nigeria's presidential system, the president belongs to the"
     " arm of government called the",
     "executive", "legislature", "judiciary", "civil service", "A",
     "The president heads the executive and executes the laws.", None),
    (T_ORGANS, "Medium", "Judicial independence is secured mainly through the"
     " tenure and remuneration protections given to judges. Which organ appoints"
     " senior judges in Nigeria on the recommendation of the National Judicial Council?",
     "The executive arm, with Senate approval", "The Nigerian Bar Association alone", "The Supreme Court by itself", "The federal civil service bodies", "A",
     "The president appoints, and the Senate confirms, on the NJC's recommendation.", None),
    (T_ORGANS, "Hard", "Judicial review is the power of the courts to",
     "declare acts of other organs unconstitutional", "appoint ministers of government", "pass the annual budget of state", "command the armed forces", "A",
     "It keeps the legislature and executive within constitutional limits.", None),
    (T_ORGANS, "Medium", "The legislature's power of oversight includes",
     "investigating the activities of ministries", "dismissing judges at their own will", "commanding the soldiers of state", "printing the money of the nation", "A",
     "Committees scrutinise executive implementation of budgets and laws.", None),
    (T_ORGANS, "Easy", "Bills passed by the legislature become law when they are",
     "signed and assented to by the president", "read out in a court of law", "announced on the radio stations", "published by the commercial banks", "A",
     "Presidential assent is the final step, though veto overrides exist.", None),
    (T_ORGANS, "Hard", "In a parliamentary system, the head of government is the",
     "prime minister", "president", "chief judge", "speaker", "A",
     "The prime minister leads the cabinet and is responsible to parliament.", None),

    # ------------------------------------------------- parties and party systems
    (T_PARTY, "Easy", "A political party is an organised group of people who seek to",
     "control government by winning elections", "make profit from trading goods", "run court cases for clients", "manage the local markets", "A",
     "Parties contest elections to capture and exercise political power.", None),
    (T_PARTY, "Medium", "One function of a political party is to",
     "educate and mobilise voters on issues", "build private houses for members", "fix the prices of fuel products", "conduct trials in the courts", "A",
     "Parties simplify issues and present manifestos to the electorate.", None),
    (T_PARTY, "Easy", "A one-party system is one in which",
     "only one political party legally exists", "two strong parties are permitted", "many parties freely compete", "no political party exists at all", "A",
     "Other parties are banned or cannot operate legally.", None),
    (T_PARTY, "Medium", "Nigeria's First Republic operated a party system that was essentially",
     "multi-party", "one-party", "two-party only", "no-party", "A",
     "The NPC, NCNC, AG and smaller parties contested the 1959 and 1964 elections.", None),
    (T_PARTY, "Medium", "The two-party system operated in Nigeria during the transition programme of General Ibrahim Babangida, when the only parties were the",
     "SDP and NRC", "NPN and UPN", "NCNC and NPC", "PDP and APC", "A",
     "The Social Democratic Party and the National Republican Convention were created by decree.", None),
    (T_PARTY, "Hard", "A major advantage of the multi-party system is that it",
     "offers voters a wide range of choices", "abolishes the opposition parties", "saves the cost of running elections", "prevents new parties from forming", "A",
     "Diverse interests find expression, though coalitions may be needed.", None),
    (T_PARTY, "Medium", "A party manifesto is the party's published statement of its",
     "policies and programmes", "accounts", "membership register", "court cases", "A",
     "Voters judge parties largely by their manifestos.", None),
    (T_PARTY, "Hard", "Party discipline requires members in the legislature to",
     "vote according to the party's position", "always oppose the government side", "resign their seats every single year", "join as many parties as they wish", "A",
     "It keeps parliamentary parties coherent and governments stable.", None),

    # ---------------------------------------------------- pressure groups/opinion
    (T_PRESS, "Easy", "A pressure group is an organised group that seeks to",
     "influence policy without seeking office", "win elections and form government", "replace the courts of the land", "run the entire civil service", "A",
     "Unlike parties, pressure groups do not contest elections to control government.", None),
    (T_PRESS, "Medium", "The Nigeria Labour Congress is an example of a",
     "trade union pressure group", "political party", "religious body", "government agency", "A",
     "The NLC protects workers' interests through negotiation and protest.", None),
    (T_PRESS, "Medium", "Which method is legitimate for a pressure group seeking to change a policy?",
     "Lobbying legislators and petitions", "Bribing the judges of the courts", "Overthrowing the whole government", "Burning down public buildings", "A",
     "Peaceful persuasion is the constitutional route to influence.", None),
    (T_PRESS, "Medium", "Pressure groups differ from political parties mainly because pressure groups",
     "do not contest elections to rule", "have no members at any time", "cannot criticise the government", "are always illegal bodies", "A",
     "Their goal is influence over policy, not capture of office.", None),
    (T_PRESS, "Hard", "Public opinion is best described as the collected attitudes of the",
     "majority of citizens on public issues", "owners of the newspaper houses", "judges of the superior courts", "senior civil servants in service", "A",
     "It sets the climate within which governments make policy.", None),
    (T_PRESS, "Medium", "A free press is important in forming public opinion because it",
     "reports and debates issues openly", "supports only the ruling party", "avoids all criticism", "publishes only adverts", "A",
     "Independent media inform citizens so opinion rests on facts.", None),

    # ------------------------------------------------------------- elections
    (T_ELECT, "Easy", "Universal adult suffrage means that all qualified adult citizens",
     "have the right to vote", "must join a party", "can become judges", "pay no taxes", "A",
     "The franchise is not tied to wealth, gender or race.", None),
    (T_ELECT, "Medium", "An election is best defined as the process by which citizens",
     "choose their representatives by voting", "buy the membership cards", "pay their taxes to the state", "attend court sessions daily", "A",
     "Regular elections convert popular will into office-holding.", None),
    (T_ELECT, "Medium", "A free and fair election requires, among other things, an",
     "independent electoral commission", "army-run polling units", "single candidate", "state-owned press only", "A",
     "Neutral administration keeps the playing field level.", None),
    (T_ELECT, "Easy", "The body responsible for conducting elections in Nigeria today is the",
     "Independent National Electoral Commission", "The National Assembly of Nigeria", "The Nigeria Police Council alone", "The Civil Service Commission", "A",
     "INEC registers parties and conducts federal and state elections.", None),
    (T_ELECT, "Medium", "Gerrymandering is the manipulation of electoral",
     "constituency boundaries for advantage", "the annual budgets of state", "cases pending before the courts", "the salaries of public officers", "A",
     "Boundaries are redrawn to pack or crack opposing voters.", None),
    (T_ELECT, "Hard", "In the first-past-the-post system, the winner of an election is the candidate with the",
     "highest number of votes cast", "absolute majority of voters", "highest campaign spending", "party's approval", "A",
     "A simple plurality is enough, even without more than half the votes.", None),
    (T_ELECT, "Medium", "One disadvantage of the first-past-the-post system is that it",
     "may waste votes for smaller parties", "always produces coalitions", "is too slow to count", "abolishes parties", "A",
     "Votes for losing candidates win no representation at all.", None),
    (T_ELECT, "Hard", "The secret ballot was introduced to protect voters from",
     "intimidation and bribery", "taxation", "military service", "attendance at rallies", "A",
     "Nobody can verify how a voter marked the paper.", None),

    # ---------------------------------------------- Nigerian constitution development
    (T_NIGCON, "Easy", "The amalgamation of the Northern and Southern protectorates of Nigeria took place in",
     "1914", "1906", "1960", "1954", "A",
     "Sir Frederick Lugard amalgamated the protectorates under one administration.", "1914"),
    (T_NIGCON, "Medium", "The Clifford Constitution of 1922 is remembered chiefly for introducing the",
     "elective principle", "federal system", "party system", "judicial review", "A",
     "Four elected seats were created, three for Lagos and one for Calabar.", None),
    (T_NIGCON, "Medium", "The Richards Constitution of 1946 is noted for introducing",
     "regionalism into Nigerian politics", "universal adult suffrage rights", "the office of the president", "an independent judiciary arm", "A",
     "It created the Northern, Western and Eastern regional assemblies.", None),
    (T_NIGCON, "Medium", "The Macpherson Constitution of 1951 was significant because it",
     "involved wide public consultation before enactment", "abolished the regions", "created the post of president", "ended colonial rule", "A",
     "Village, district and provincial discussions fed into its making.", None),
    (T_NIGCON, "Hard", "The Lyttleton Constitution of 1954 is remembered for firmly establishing",
     "federalism in Nigeria", "the elective principle", "party politics", "local government", "A",
     "Regions became autonomous units within a federation.", None),
    (T_NIGCON, "Easy", "Nigeria attained political independence on",
     "1 October 1960", "1 October 1963", "27 May 1967", "29 May 1999", "A",
     "The union jack was lowered and the green-white-green flag hoisted in 1960.", None),
    (T_NIGCON, "Medium", "Nigeria became a republic, with the president as head of state, in",
     "1963", "1960", "1966", "1979", "A",
     "The Republican Constitution of 1963 replaced the Governor-General with a president.", "1963"),
    (T_NIGCON, "Medium", "The 1979 Constitution introduced the presidential system of government modelled largely on that of the",
     "United States", "United Kingdom", "Soviet Union", "France", "A",
     "An executive president replaced the parliamentary prime minister.", None),
    (T_NIGCON, "Easy", "The constitution currently in force in Nigeria is that of",
     "1999", "1979", "1989", "1963", "A",
     "The 1999 Constitution began the Fourth Republic on 29 May 1999.", "1999"),
    (T_NIGCON, "Hard", "The 1999 Constitution of Nigeria provides that the federation shall consist of",
     "36 states and a Federal Capital Territory", "12 states and their regional councils", "4 regions under regional premiers", "21 states and a capital city", "A",
     "The states and Abuja FCT make up the federation.", "36"),
    (T_NIGCON, "Medium", "Under the 1999 Constitution, a president is elected for a term of",
     "four years and may serve two terms", "six years without any limit", "five years for a single term", "seven years for every term", "A",
     "Two terms of four years each is the constitutional maximum.", None),
    (T_NIGCON, "Hard", "The constitutional body that can declare a seat vacant after a member defects from his party is closely linked to the legislature's own rules; the final interpreter of such disputes is the",
     "court", "police", "party chairman", "electoral officer", "A",
     "Only the judiciary can authoritatively interpret the constitution.", None),
    (T_NIGCON, "Medium", "The fundamental objectives and directive principles of state policy are contained in",
     "Chapter II of the 1999 Constitution", "the Criminal Code of the federation", "the manifestos of the parties", "the military decrees of old", "A",
     "They set out the social and economic goals the state should pursue.", None),
    (T_NIGCON, "Hard", "The constitutional amendment procedure in Nigeria requires the approval of at least",
     "two-thirds of the Assembly plus states", "the president acting alone", "the Supreme Court judges", "all 36 state governors only", "A",
     "Both national and state legislatures must concur for most alterations.", None),

    # ------------------------------------------------------ colonial administration
    (T_COLON, "Easy", "Indirect rule is the system by which the British administered their colonies through",
     "existing traditional rulers", "elected parliamentarians", "foreign judges", "trade unions", "A",
     "Native authorities governed locally under British supervision.", None),
    (T_COLON, "Medium", "The main reason the British adopted indirect rule in Northern Nigeria was the",
     "existence of the well-organised emirates", "the absence of any rulers there", "the large number of lawyers there", "the pattern of rainfall there", "A",
     "The centralised emirs and Islamic administration could simply be supervised.", None),
    (T_COLON, "Hard", "Indirect rule worked less successfully in the West than in the North partly because the"
     " Yoruba obas' authority had been"
     " weakened by constitutional changes under the",
     "westernisation and warrant chiefs", "the build-up of the army", "the powers of the police", "the coming of the railways", "A",
     "The political structure was less hierarchical and more exposed to mission education.", None),
    (T_COLON, "Hard", "In the Eastern Region, indirect rule was difficult mainly because the Igbo society was largely",
     "acephalous, without centralised chiefs", "ruled by a chain of emirs", "governed by powerful obas", "under one single paramount king", "A",
     "Warrant chiefs had to be invented, and they lacked legitimacy.", None),
    (T_COLON, "Medium", "The first Governor-General of amalgamated Nigeria was",
     "Sir Frederick Lugard", "Nnamdi Azikiwe", "Herbert Macaulay", "Abubakar Tafawa Balewa", "A",
     "Lugard oversaw the amalgamation and led the new administration.", None),
    (T_COLON, "Medium", "The name 'Nigeria' is credited to",
     "Flora Shaw", "Mary Slessor", "Queen Victoria", "Harold Smith", "A",
     "The journalist Flora Shaw, later Lady Lugard, suggested the name in 1897.", None),
    (T_COLON, "Easy", "Colonial rule in Nigeria was mainly for the economic benefit of",
     "Britain, the colonial power", "the Nigerian farmers", "the traditional rulers", "Nigerian traders", "A",
     "Raw materials and markets for British industry drove colonisation.", None),
    (T_COLON, "Hard", "One consequence of British colonial economic policy in Nigeria was the"
     " concentration on export crops such as",
     "cocoa, palm produce and groundnuts", "motor cars and machines", "computers and electronics", "aircraft and spare parts", "A",
     "Cash-crop export oriented the economy towards Britain's needs.", None),

    # ------------------------------------------------------------- nationalism
    (T_NAT, "Easy", "Nationalism in Nigeria refers to the political movement that demanded",
     "self-government and independence", "the acquisition of more colonies", "the imposition of military rule", "the collection of higher taxes", "A",
     "Nationalists campaigned for an end to colonial rule.", None),
    (T_NAT, "Medium", "The first Nigerian to be called the father of Nigerian nationalism, who led the NNDP, was",
     "Herbert Macaulay", "Nnamdi Azikiwe", "Obafemi Awolowo", "Ahmadu Bello", "A",
     "Herbert Macaulay founded the Nigerian National Democratic Party in 1923.", None),
    (T_NAT, "Medium", "The newspaper founded by Nnamdi Azikiwe that spread nationalist ideas was the",
     "West African Pilot", "Daily Times", "Lagos Weekly", "Champion", "A",
     "The Pilot, founded in 1937, popularised the campaign for self-rule.", None),
    (T_NAT, "Medium", "The NCNC, formed in 1944, drew most of its early support from the",
     "Eastern Region", "Northern Region", "Lagos market women only", "civil servants only", "A",
     "It later became the dominant party of the East under Azikiwe's leadership.", None),
    (T_NAT, "Hard", "The Northern People's Congress grew out of a cultural organisation known as",
     "Jamiyyar Mutanen Arewa", "Egbe Omo Oduduwa", "Ibibio State Union", "Igbo Federal Union", "A",
     "The NPC developed from the Northern cultural congress.", None),
    (T_NAT, "Hard", "The cultural association from which the Action Group developed was the",
     "Egbe Omo Oduduwa", "Jamiyyar Mutanen Arewa", "NCNC youth wing", "NNDP", "A",
     "The Yoruba cultural union formed the base of Awolowo's Action Group.", None),
    (T_NAT, "Medium", "The 1945 and 1953 constitutional crises in Nigeria both involved demands by nationalists for greater",
     "greater Nigerian participation in rule", "increased colonial funding grants", "transfer of powers to the police", "rebates on taxes to companies", "A",
     "Crisis followed crisis as nationalists pressed for self-government.", None),
    (T_NAT, "Medium", "Which factor strengthened Nigerian nationalism after the Second World War?",
     "Returning soldiers who saw the world", "The new colonial taxes alone", "The banning of the newspapers", "The building of fewer schools", "A",
     "Ex-servicemen resented discrimination and joined the freedom movement.", None),
    (T_NAT, "Hard", "The self-government motion crisis of 1953 was triggered by Anthony Enahoro's motion that Nigeria should become independent in",
     "1956", "1960", "1970", "1953", "A",
     "The North's call for 'as soon as practicable' sparked the crisis and the London/Lagos conferences.", "1956"),

    # ----------------------------------------------------- federalism/regionalism
    (T_FED, "Easy", "A federal system of government is one in which power is shared between the",
     "central government and the units", "the army and the police force", "the courts and the lawyers", "the rulers and the ruled", "A",
     "Each tier is constitutionally guaranteed its own powers.", None),
    (T_FED, "Medium", "One main argument for the adoption of federalism in Nigeria was the country's",
     "size and diversity", "small population", "uniform language", "single religion", "A",
     "Federalism allowed diverse peoples and regions to remain under one state.", None),
    (T_FED, "Medium", "The 1954 constitution formally divided Nigeria into regions and made the country a federation, largely because of the",
     "Lyttleton Constitution", "Clifford Constitution", "Richards Constitution", "Independence Constitution", "A",
     "The Lyttleton Constitution entrenched the federal structure.", None),
    (T_FED, "Hard", "One problem of Nigerian federalism has been the struggle over the division of revenue between the centre and the states, an issue handled today by the",
     "Revenue Mobilisation and Fiscal Commission", "The Central Bank of Nigeria", "The Nigerian Stock Exchange", "The Civil Service Commission", "A",
     "The commission advises on vertical and horizontal revenue allocation.", None),
    (T_FED, "Medium", "In a federation, powers shared by both the central government and the states are found on the",
     "concurrent legislative list", "exclusive list", "residual list", "dead letter list", "A",
     "Education appears on the concurrent list in Nigeria.", None),
    (T_FED, "Hard", "Powers not listed in the constitution and exercised by the states in Nigeria fall under the",
     "residual list", "exclusive list", "concurrent list", "emergency list", "A",
     "Residual powers belong to the component states.", None),
    (T_FED, "Medium", "TheExclusive legislative list in Nigeria contains matters on which only the",
     "National Assembly can legislate", "states can legislate", "courts can legislate", "parties can legislate", "A",
     "Defence, currency and immigration are exclusive to the centre.", None),
    (T_FED, "Easy", "The federal character principle in Nigeria seeks to ensure that public offices reflect the",
     "diversity of the federation", "interest of one zone", "will of the ruling party", "power of the army", "A",
     "Appointments must represent the country's composite nature.", None),

    # ------------------------------------------------------------- local government
    (T_LOCAL, "Easy", "Local government is the tier of government closest to the",
     "grassroots", "courts", "army", "foreign embassies", "A",
     "It administers wards, villages and towns directly.", None),
    (T_LOCAL, "Medium", "One function of local government councils in Nigeria is the provision of",
     "primary education and local roads", "the printing of the currency", "the defence of the nation", "the conduct of foreign policy", "A",
     "Local services like markets, drains and primary schools belong to councils.", None),
    (T_LOCAL, "Medium", "The 1976 local government reforms, credited to the Obasanjo military administration, made local governments the",
     "third tier of government with powers", "an arm of the national police", "the property of traditional rulers", "departments of the big banks", "A",
     "Uniform single-tier councils were created across the states.", None),
    (T_LOCAL, "Hard", "A major problem of local government in Nigeria has been the excessive control of councils by the",
     "state governments", "United Nations", "traditional council of chiefs", "foreign embassies", "A",
     "Joint State-Local Government accounts and dissolution powers weaken councils.", None),
    (T_LOCAL, "Medium", "Local government elections in Nigeria are conducted by the",
     "State Independent Electoral Commissions", "INEC officials from Abuja", "officers of the police force", "the federal civil service", "A",
     "SIECs run council polls while INEC handles federal and state elections.", None),

    # ------------------------------------------------------------- civil service
    (T_CIVIL, "Easy", "The civil service consists of government employees in ministries who",
     "implement government policies", "make laws", "judge cases", "run political parties", "A",
     "Civil servants advise ministers and execute approved policies.", None),
    (T_CIVIL, "Medium", "Civil service permanence means that a civil servant",
     "continues in office despite changes", "can never be dismissed at all", "must join the ruling party", "is elected by voters yearly", "A",
     "Unlike politicians, career officials remain after elections.", None),
    (T_CIVIL, "Medium", "Civil service neutrality requires officers to be loyal to the government of the day and to serve",
     "any government without partisan bias", "only their own ethnic group", "only one political party", "the interests of foreign powers", "A",
     "Neutral service protects continuity and professionalism.", None),
    (T_CIVIL, "Medium", "The administrative head of a Nigerian ministry is the",
     "permanent secretary", "minister", "governor", "party chairman", "A",
     "The permanent secretary coordinates the ministry's civil servants.", None),
    (T_CIVIL, "Hard", "The head of the entire civil service of the federation bears the title",
     "Head of the Civil Service of the Federation", "The Chief Justice of the federation", "The President of the Senate chamber", "The Accountant-General of the state", "A",
     "The office coordinates the federal civil service.", None),
    (T_CIVIL, "Hard", "One merit of the civil service is that it provides"
     " continuity in administration. One demerit is that it is often accused of",
     "bureaucratic red tape and delays", "making the laws of the state", "commanding the armed forces", "printing the national currency", "A",
     "Rules and files can slow decisions that citizens need quickly.", None),
    (T_CIVIL, "Medium", "The commission responsible for recruiting senior federal civil servants in Nigeria is the",
     "Federal Civil Service Commission", "INEC", "Nigeria Police Council", "SIEC", "A",
     "The FCSC recruits, promotes and disciplines federal officers.", None),

    # --------------------------------------------------------- public corporations
    (T_PUB, "Easy", "A public corporation is a business organisation owned and controlled by the",
     "government", "shareholders only", "traders' union", "foreign firms", "A",
     "The state establishes it by law to render essential services.", None),
    (T_PUB, "Medium", "Public corporations are usually established to provide services that are"
     " natural monopolies or need huge capital, such as",
     "railways and water supply", "hairdressing", "bread retailing", "newspaper vending", "A",
     "Private firms shy away from such capital-heavy essential services.", None),
    (T_PUB, "Medium", "A major reason for establishing public corporations in Nigeria was to",
     "provide services and drive development", "help foreign firms to profit", "reduce employment in the country", "close down all the factories", "A",
     "They supplied infrastructure and strategic services the private sector would not.", None),
    (T_PUB, "Hard", "One common criticism of public corporations in Nigeria is that they often",
     "suffer inefficiency and interference", "make far too much profit", "refuse to employ citizens", "build far too many railways", "A",
     "Patronage appointments and weak accountability blunt performance.", None),
    (T_PUB, "Hard", "The privatisation policy later adopted for many Nigerian public corporations aimed mainly to",
     "improve efficiency and cut fiscal burden", "create many more parastatals", "ban all private businesses", "raise party campaign funds", "A",
     "Transferring firms to private managers sought better performance.", None),

    # ------------------------------------------------------- military in politics
    (T_MIL, "Easy", "The first military coup in Nigeria took place in",
     "January 1966", "July 1966", "1975", "1983", "A",
     "The January 1966 coup ended the First Republic.", None),
    (T_MIL, "Medium", "The first military Head of State of Nigeria was",
     "Major-General J.T.U. Aguiyi-Ironsi", "General Yakubu Gowon", "General Murtala Mohammed", "General Olusegun Obasanjo", "A",
     "Aguiyi-Ironsi took over after the January 1966 coup.", None),
    (T_MIL, "Medium", "The Nigerian Civil War, triggered by the Eastern Region's secession as Biafra, lasted from",
     "1967 to 1970", "1960 to 1963", "1975 to 1976", "1983 to 1985", "A",
     "The war began in May 1967 and ended in January 1970.", None),
    (T_MIL, "Hard", "General Gowon's regime created twelve states in 1967 mainly to",
     "weaken secession and bring government nearer", "increase the taxes of the regions", "end all the regions' powers for ever", "prepare the country for war with Ghana", "A",
     "Splitting the four regions frustrated the East's claim over the whole old East.", None),
    (T_MIL, "Medium", "The military handed power to the civilian government of the Second Republic in",
     "1979", "1966", "1983", "1999", "A",
     "Alhaji Shehu Shagari's government began on 1 October 1979.", "1979"),
    (T_MIL, "Medium", "The military regime of General Abdulsalami Abubakar handed over to civilians in",
     "1999", "1993", "1995", "1998", "A",
     "The Fourth Republic began on 29 May 1999 under Olusegun Obasanjo.", "1999"),
    (T_MIL, "Hard", "A common reason given by the military for intervening in Nigerian politics is the need to",
     "correct political mismanagement", "obey the constitution always", "hold general elections yearly", "reduce the size of the army", "A",
     "Coup announcements usually cite corruption and disorder.", None),
    (T_MIL, "Hard", "One achievement often credited to Nigerian military regimes is the",
     "creation of states and infrastructure", "abolition of the civil service", "the permanent ban on parties", "the end of all taxation", "A",
     "States, dams, refineries and universities date from military years.", None),
    (T_MIL, "Medium", "Decree number 34 of 1966, which made Nigeria a unitary state by decree, was issued by",
     "Aguiyi-Ironsi's regime", "Gowon's regime", "Murtala's regime", "Babangida's regime", "A",
     "The unification decree intensified the crisis of 1966.", None),

    # ----------------------------------------------------------- foreign policy
    (T_FOREIGN, "Easy", "Nigeria's foreign policy is the sum of the strategies it uses in relating with",
     "other countries of the world", "its states", "local councils", "companies", "A",
     "Foreign policy pursues the national interest abroad.", None),
    (T_FOREIGN, "Medium", "The main instrument for conducting Nigeria's foreign policy is the",
     "Ministry of Foreign Affairs and missions", "officers of the police force", "officials of the Central Bank", "the national electoral body INEC", "A",
     "Embassies and high commissions represent Nigeria abroad.", None),
    (T_FOREIGN, "Medium", "The concept that has remained the centrepiece of Nigeria's foreign policy is",
     "Africa", "Europe", "Asia", "Latin America", "A",
     "Successive governments declare Africa the centrepiece of foreign policy.", None),
    (T_FOREIGN, "Medium", "Nigeria's membership of the Non-Aligned Movement during the Cold War meant that she",
     "stayed neutral between the two blocs", "became a member of the NATO bloc", "joined the Warsaw Pact side", "closed down all her embassies", "A",
     "Non-alignment kept Nigeria out of the East-West rivalry.", None),
    (T_FOREIGN, "Hard", "Nigeria played a leading role in the liberation of Southern Africa, including massive support for the struggle against apartheid in",
     "South Africa", "Egypt", "Morocco", "Liberia", "A",
     "The frontline states and the ANC received Nigerian financial and diplomatic backing.", None),
    (T_FOREIGN, "Hard", "Nigeria's leadership in the Economic Community of West African States produced the ECOMOG intervention that helped end the civil war in",
     "Liberia", "Ghana", "Senegal", "Gambia", "A",
     "The ECOMOG force restored order in Liberia in the 1990s.", None),
    (T_FOREIGN, "Medium", "One principle guiding Nigeria's foreign policy is respect for the",
     "the sovereignty and integrity of states", "the annexation of her neighbours", "interference in other elections", "racial discrimination abroad", "A",
     "Non-interference and legal equality of states are core principles.", None),
    (T_FOREIGN, "Medium", "The African Union, which replaced the Organisation of African Unity, was established in",
     "2002", "1963", "1980", "1999", "A",
     "The AU was launched in Durban in 2002.", "2002"),

    # -------------------------------------------------- international organisations
    (T_INT, "Easy", "The headquarters of the United Nations is located in",
     "New York", "Geneva", "Paris", "Lagos", "A",
     "The UN Secretariat sits in New York City.", None),
    (T_INT, "Medium", "The main organs of the United Nations include the General Assembly, the Secretariat, the International Court of Justice and the",
     "Security Council", "African Union", "ECOWAS Court", "Central Bank", "A",
     "Six principal organs include the Security Council and ECOSOC.", None),
    (T_INT, "Medium", "The organ of the UN primarily responsible for maintaining international peace and security is the",
     "Security Council", "General Assembly", "WHO", "UNESCO", "A",
     "Its resolutions can authorise peacekeeping and sanctions.", None),
    (T_INT, "Medium", "Nigeria became a member of the United Nations in",
     "1960", "1945", "1950", "1963", "A",
     "Independence in 1960 was followed immediately by UN membership.", "1960"),
    (T_INT, "Easy", "The Commonwealth is an association of countries most of which were formerly",
     "British colonies", "French colonies", "Spanish colonies", "Russian republics", "A",
     "Nigeria is a member of this voluntary association.", None),
    (T_INT, "Medium", "The Organisation of African Unity, the predecessor of the African Union, was founded in 1963 in",
     "Addis Ababa", "Lagos", "Nairobi", "Cairo", "A",
     "Ethiopia's capital hosted the founding conference.", None),
    (T_INT, "Medium", "ECOWAS was established in 1975 by the Treaty of",
     "Lagos", "Abuja", "Accra", "Dakar", "A",
     "The treaty was signed in Lagos to integrate West African economies.", None),
    (T_INT, "Hard", "The ECOWAS Protocol on Free Movement entitles citizens of member states to",
     "enter and reside in states without visas", "vote in other countries' polls", "own other countries' central banks", "claim customs exemption everywhere", "A",
     "Community citizens travel within West Africa without a visa.", None),
    (T_INT, "Medium", "OPEC, the organisation of petroleum exporting countries, was founded in",
     "1960", "1975", "1999", "1954", "A",
     "The founding meeting was held in Baghdad in 1960.", "1960"),
    (T_INT, "Medium", "Nigeria joined OPEC, the organisation of petroleum exporting countries, in",
     "1971", "1960", "1980", "1999", "A",
     "Nigeria became a full member in 1971.", "1971"),
    (T_INT, "Hard", "The specialised UN agency responsible for health matters is the",
     "World Health Organization", "ILO", "IMF", "FAO", "A",
     "The WHO directs international public health work.", None),
    (T_INT, "Hard", "The UN agency that provides loans to stabilise the international monetary system is the",
     "International Monetary Fund", "UNESCO", "UNICEF", "WTO", "A",
     "The IMF gives balance-of-payments support and policy advice.", None),
    (T_INT, "Medium", "The flag of Nigeria, designed by Taiwo Akinkunmi, was adopted in",
     "1959", "1960", "1963", "1914", "A",
     "The green-white-green flag was chosen just before independence.", "1959"),
]

if __name__ == "__main__":
    build_batch(
        S,
        "batch_050_waec_government.json",
        "batch_050_waec_government",
        "WAEC/NECO Government Paper 1, round 1: full SSCE syllabus - scope of "
        "government, political concepts, constitutions, organs of government, parties "
        "and pressure groups, elections, Nigerian constitutional development, colonial "
        "administration, nationalism, federalism, local government, civil service, "
        "public corporations, the military in politics, foreign policy and "
        "international organisations. Stable historical facts for SSCE.",
        PASSAGES,
        PQ,
        Q,
        exam_type="WAEC",
    )
