"""Batch 015 - Physics round 3 (JAMB syllabus, applied/calculation style).

Four data passages (velocity-time table, cell terminal p.d. readings, heating curve, simple
pendulum data) and ~215 stand-alone items across all fifteen Physics topics.  Every numerical
answer carries a `verify` expression that is evaluated before the file is written.  Options
written as "3.3 × 10⁻¹⁹ J" are verified on the mantissa (the first number in the option).

    python3 scripts/build_content_batch15.py -> content/batch_015_physics_round3.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Physics"

PASSAGES = [
    ("P1", "Motion", "Velocity-time readings for a car",
     "The velocity of a car travelling along a straight road was recorded every two seconds. "
     "The readings are shown below.\n\n"
     "Time (s)         0   2   4   6   8  10  12\n"
     "Velocity (m/s)   0   6  12  12  12   6   0"),
    ("P2", "Electricity", "Terminal p.d. of a cell at different currents",
     "A cell was connected to a variable resistor, an ammeter and a voltmeter. The terminal "
     "p.d. V was read for several values of the current I.\n\n"
     "Current I (A)    0.5   1.0   1.5   2.0\n"
     "Terminal V (V)   2.7   2.4   2.1   1.8"),
    ("P3", "Heat and Thermal Physics", "Heating curve of a solid",
     "0.1 kg of a solid substance was heated in an insulated container by a 50 W heater "
     "and its temperature was recorded every two minutes.\n\n"
     "Time (min)      0   2   4   6   8  10  12\n"
     "Temp (°C)      20  40  60  60  60  80 100"),
    ("P4", "Measurement and Units", "Simple pendulum experiment",
     "A student measured the period T of a simple pendulum for several lengths l by timing "
     "20 complete oscillations with a stopwatch. The results are shown below.\n\n"
     "Length l (m)    0.25   0.49   0.81   1.00\n"
     "Period T (s)     1.0    1.4    1.8    2.0"),
]

PQ = [
    ("P1", "Medium", "From the readings above, the acceleration of the car during the first 4 seconds is",
     "1.5 m/s²", "3.0 m/s²", "6.0 m/s²", "12 m/s²", "B",
     "Acceleration = change in velocity ÷ time = (12 − 0)/4 = 3.0 m/s².", "12/4"),
    ("P1", "Medium", "From the readings above, the distance covered by the car during the first 4 seconds is",
     "12 m", "24 m", "48 m", "96 m", "B",
     "Distance = area under the velocity-time graph = ½ × 4 s × 12 m/s = 24 m.", "0.5*4*12"),
    ("P1", "Easy", "From the readings above, between the 4th and the 8th second the car was",
     "accelerating uniformly", "moving with constant velocity", "decelerating uniformly", "at rest", "B",
     "The velocity stays at 12 m/s throughout that interval, so the acceleration is zero and the car moves with constant velocity."),
    ("P1", "Hard", "From the readings above, the total distance travelled by the car in the 12 seconds is",
     "72 m", "96 m", "120 m", "144 m", "B",
     "Areas under the graph: ½ × 4 × 12 = 24 m, then 12 × 4 = 48 m, then ½ × 4 × 12 = 24 m; total 96 m.", "24+48+24"),
    ("P1", "Medium", "From the readings above, the average speed of the car for the whole journey is",
     "6 m/s", "8 m/s", "12 m/s", "16 m/s", "B",
     "Average speed = total distance ÷ total time = 96 m ÷ 12 s = 8 m/s.", "96/12"),
    ("P1", "Medium", "From the readings above, the retardation of the car during the last 4 seconds is",
     "1.5 m/s²", "3.0 m/s²", "4.0 m/s²", "6.0 m/s²", "B",
     "Velocity falls from 12 m/s to 0 in 4 s: retardation = 12/4 = 3.0 m/s².", "12/4"),
    ("P2", "Medium", "From the readings above, the e.m.f. of the cell is",
     "2.7 V", "3.0 V", "3.3 V", "2.4 V", "B",
     "V = E − Ir. Between I = 0.5 A and 1.0 A the p.d. falls 0.3 V, so r = 0.6 Ω and E = 2.7 + 0.5 × 0.6 = 3.0 V (the intercept of the V–I graph).", "3.0"),
    ("P2", "Medium", "From the readings above, the internal resistance of the cell is",
     "0.3 Ω", "0.6 Ω", "1.2 Ω", "1.8 Ω", "B",
     "Each extra 0.5 A of current lowers the terminal p.d. by 0.3 V: r = 0.3/0.5 = 0.6 Ω, the magnitude of the slope of the V–I graph.", "0.6"),
    ("P2", "Medium", "From the readings above, the resistance of the external circuit when the current was 2.0 A is",
     "0.6 Ω", "0.9 Ω", "1.5 Ω", "3.6 Ω", "B",
     "R = V/I = 1.8 V ÷ 2.0 A = 0.9 Ω.", "1.8/2"),
    ("P2", "Medium", "From the readings above, the 'lost volts' inside the cell when the current was 1.5 A is",
     "0.6 V", "0.9 V", "2.1 V", "3.0 V", "B",
     "Lost volts = E − V = 3.0 − 2.1 = 0.9 V (equal to Ir = 1.5 × 0.6).", "3.0-2.1"),
    ("P2", "Medium", "From the readings above, the power delivered to the external circuit when the current was 1.0 A is",
     "1.8 W", "2.4 W", "3.0 W", "0.6 W", "B",
     "P = VI = 2.4 V × 1.0 A = 2.4 W.", "2.4*1.0"),
    ("P2", "Easy", "In the experiment above, the terminal p.d. fell as the current increased because",
     "the voltmeter drew more current", "more of the e.m.f. was used in driving current through the cell's own resistance", "the e.m.f. of the cell decreased", "the external resistor heated up", "B",
     "The p.d. across the internal resistance, Ir, grows with current, leaving less of the e.m.f. across the terminals."),
    ("P3", "Easy", "From the readings above, the melting point of the substance is",
     "40 °C", "60 °C", "80 °C", "100 °C", "B",
     "The temperature stayed constant at 60 °C while the solid was changing into liquid.", "60"),
    ("P3", "Medium", "From the readings above, the time taken for the substance to melt completely was",
     "2 minutes", "4 minutes", "6 minutes", "8 minutes", "B",
     "The temperature remained at 60 °C from the 4th to the 8th minute, i.e. for 4 minutes.", "8-4"),
    ("P3", "Hard", "From the readings above, the specific heat capacity of the solid is",
     "1,500 J kg⁻¹ K⁻¹", "3,000 J kg⁻¹ K⁻¹", "6,000 J kg⁻¹ K⁻¹", "12,000 J kg⁻¹ K⁻¹", "B",
     "In the first 4 minutes the heater supplied 50 × 240 = 12,000 J and the temperature rose 40 K: c = 12,000/(0.1 × 40) = 3,000 J kg⁻¹ K⁻¹.", "50*240/(0.1*40)"),
    ("P3", "Hard", "From the readings above, the specific latent heat of fusion of the substance is",
     "1.2 × 10⁴ J/kg", "1.2 × 10⁵ J/kg", "2.4 × 10⁵ J/kg", "6.0 × 10⁵ J/kg", "B",
     "Melting took 4 minutes, during which 50 × 240 = 12,000 J was supplied to 0.1 kg: L = 12,000/0.1 = 1.2 × 10⁵ J/kg.", "50*240/0.1/1e5"),
    ("P3", "Medium", "In the experiment above, the temperature did not rise between the 4th and 8th minute because the heat supplied was",
     "escaping through the container walls", "being used to break the bonds holding the solid together", "increasing the kinetic energy of the molecules", "being stored as electrical energy", "B",
     "During a change of state the energy supplied increases the potential energy of the molecules (separating them) rather than their kinetic energy, so the temperature is constant."),
    ("P3", "Medium", "From the readings above, the specific heat capacity of the liquid compared with that of the solid is",
     "twice as large", "the same", "half as large", "four times as large", "B",
     "The liquid also rose 40 K (60 °C to 100 °C) in 4 minutes with the same heater, so the same energy produced the same temperature rise in the same mass."),
    ("P4", "Medium", "From the data above, a graph of T² against l would be",
     "a curve passing through the origin", "a straight line through the origin", "a straight line with a positive intercept", "a horizontal straight line", "B",
     "T = 2π√(l/g) gives T² = (4π²/g) l, so T² is directly proportional to l: the points (0.25, 1.0), (0.49, 1.96), (0.81, 3.24) and (1.00, 4.0) lie on a line through the origin."),
    ("P4", "Hard", "Using the data above for l = 1.00 m, the value of the acceleration due to gravity is approximately (π² ≈ 9.87)",
     "4.9 m/s²", "9.9 m/s²", "19.7 m/s²", "6.3 m/s²", "B",
     "g = 4π²l/T² = 4 × 9.87 × 1.00 ÷ 2.0² = 9.87 ≈ 9.9 m/s².", "4*math.pi**2*1.00/2.0**2"),
    ("P4", "Medium", "The data above show that when the length of the pendulum is made four times as great, the period",
     "is doubled", "is quadrupled", "is halved", "remains the same", "A",
     "From 0.25 m to 1.00 m the period rises from 1.0 s to 2.0 s: T is proportional to √l, so four times the length doubles the period."),
    ("P4", "Easy", "In the experiment above, the student timed 20 oscillations instead of one in order to",
     "make the pendulum swing faster", "reduce the effect of reaction-time error on the measured period", "increase the amplitude of the swing", "keep the string from stretching", "B",
     "The stopwatch error (about 0.2 s) is spread over 20 swings, so the error in one period becomes twenty times smaller."),
    ("P4", "Medium", "From the data above, the number of complete oscillations the 0.25 m pendulum makes in one minute is",
     "30", "60", "120", "240", "B",
     "Period = 1.0 s, so in 60 s it completes 60/1.0 = 60 oscillations.", "60/1.0"),
    ("P4", "Medium", "If the pendulum in the experiment above were taken to the Moon, where g is about one-sixth of its value on Earth, the period of the 1.00 m pendulum would be",
     "shorter than 2.0 s", "longer than 2.0 s", "exactly 2.0 s", "zero", "B",
     "T = 2π√(l/g): a smaller g gives a longer period (about 2.0 × √6 ≈ 4.9 s)."),
]

Q = [
    # ---------------- Measurement and Units ----------------
    ("Measurement and Units", "Medium", "The dimensions of pressure are",
     "MLT⁻²", "ML⁻¹T⁻²", "ML²T⁻²", "ML⁻²T⁻²", "B",
     "Pressure = force/area = MLT⁻² ÷ L² = ML⁻¹T⁻²."),
    ("Measurement and Units", "Medium", "A micrometer screw gauge with no zero error has a sleeve reading of 5.5 mm and the 23rd division of the thimble on the reference line. If the thimble has 50 divisions and the pitch is 0.5 mm, the reading is",
     "5.23 mm", "5.73 mm", "5.96 mm", "7.80 mm", "B",
     "Each thimble division is 0.5/50 = 0.01 mm; reading = 5.5 + 23 × 0.01 = 5.73 mm.", "5.5+0.23"),
    ("Measurement and Units", "Medium", "The main scale of a vernier caliper reads 2.3 cm and the 6th vernier division coincides with a main-scale mark. If the vernier has 10 divisions equal to 9 mm, the length measured is",
     "2.36 cm", "2.90 cm", "2.63 cm", "2.06 cm", "A",
     "The least count is 0.1 mm = 0.01 cm; length = 2.3 + 6 × 0.01 = 2.36 cm.", "2.3+0.06"),
    ("Measurement and Units", "Easy", "A student lists mass, weight, time and temperature. The quantity in the list that is NOT a fundamental quantity is",
     "mass", "weight", "time", "temperature", "B",
     "Weight is a force (mass × acceleration due to gravity) and is derived from mass, length and time."),
    ("Measurement and Units", "Medium", "A rectangular block measures 2.0 cm by 3.0 cm by 4.0 cm and has a mass of 60 g. Its density is",
     "0.4 g/cm³", "2.5 g/cm³", "5.0 g/cm³", "10 g/cm³", "B",
     "Volume = 2 × 3 × 4 = 24 cm³; density = 60/24 = 2.5 g/cm³.", "60/24"),
    ("Measurement and Units", "Easy", "The number of significant figures in the measurement 0.00450 m is",
     "2", "3", "5", "6", "B",
     "Leading zeros are not significant but the trailing zero after the 5 is: 4, 5 and 0 give three significant figures.", "3"),
    ("Measurement and Units", "Easy", "The most suitable instrument for measuring the diameter of a thin copper wire is a",
     "metre rule", "vernier caliper", "micrometer screw gauge", "tape measure", "C",
     "A micrometer screw gauge reads to 0.01 mm, the precision needed for a wire a fraction of a millimetre thick."),
    ("Measurement and Units", "Medium", "A student measuring the period of a pendulum repeats the timing five times and takes the average. This procedure reduces",
     "systematic error", "random error", "zero error", "parallax error", "B",
     "Random errors vary unpredictably from reading to reading, so averaging several readings reduces their effect; systematic errors are not removed by averaging."),
    ("Measurement and Units", "Medium", "A micrometer screw gauge has a zero error of +0.02 mm. When used to measure a ball bearing it reads 3.45 mm. The true diameter is",
     "3.47 mm", "3.43 mm", "3.45 mm", "3.25 mm", "B",
     "A positive zero error is subtracted from the observed reading: 3.45 − 0.02 = 3.43 mm.", "3.45-0.02"),
    ("Measurement and Units", "Hard", "The force on a body moving through a fluid is given by F = kv², where v is the velocity. The dimensions of the constant k are",
     "ML⁻¹", "MLT⁻¹", "ML⁻¹T⁻¹", "M", "A",
     "k = F/v² = MLT⁻² ÷ (L²T⁻²) = ML⁻¹."),
    ("Measurement and Units", "Easy", "A car travelling at 72 km/h has a speed in metres per second of",
     "12 m/s", "20 m/s", "36 m/s", "72 m/s", "B",
     "72 km/h = 72,000 m ÷ 3,600 s = 20 m/s.", "72*1000/3600"),
    ("Measurement and Units", "Medium", "Which of the following pairs of physical quantities have the same unit?",
     "work and power", "momentum and impulse", "force and pressure", "energy and force", "B",
     "Impulse (N s) equals change of momentum (kg m s⁻¹); the two units are identical."),
    ("Measurement and Units", "Medium", "A stopwatch reading is taken with the eye not directly above the pointer. The error introduced is described as",
     "a random error due to reaction time", "a parallax error", "a zero error", "an error due to expansion", "B",
     "Reading a scale from an angle displaces the apparent position of the pointer; this is parallax and is avoided by viewing at right angles to the scale."),
    ("Measurement and Units", "Medium", "The volume of a stone that is too large for a measuring cylinder is best found by",
     "measuring its length, breadth and height with a rule", "lowering it into a eureka (displacement) can full of water and measuring the water that overflows", "weighing it on a beam balance", "wrapping a tape measure round it", "B",
     "The volume of water displaced equals the volume of the irregular stone."),
    # ---------------- Scalars and Vectors ----------------
    ("Scalars and Vectors", "Easy", "A student describes a car as moving at 60 km/h due north. Because a direction is given, the quantity she has stated is the car's",
     "acceleration", "velocity", "displacement", "momentum", "B",
     "Speed together with a stated direction is velocity, a vector quantity; speed on its own is a scalar."),
    ("Scalars and Vectors", "Medium", "A force of 20 N acts at 60° to the horizontal. Its horizontal component is",
     "10 N", "17.3 N", "20 N", "40 N", "A",
     "Horizontal component = F cos θ = 20 × cos 60° = 20 × 0.5 = 10 N.", "20*math.cos(math.radians(60))"),
    ("Scalars and Vectors", "Medium", "A boat is pulled by two ropes at right angles to each other with forces of 5 N and 12 N. The magnitude of the resultant pull on the boat is",
     "7 N", "13 N", "17 N", "60 N", "B",
     "R = √(5² + 12²) = √169 = 13 N.", "math.sqrt(25+144)"),
    ("Scalars and Vectors", "Hard", "Two forces of 10 N each act at a point with an angle of 120° between them. The magnitude of their resultant is",
     "0 N", "10 N", "17.3 N", "20 N", "B",
     "R² = 10² + 10² + 2 × 10 × 10 × cos 120° = 100 + 100 − 100 = 100, so R = 10 N.", "math.sqrt(100+100+2*100*math.cos(math.radians(120)))"),
    ("Scalars and Vectors", "Medium", "A boat that can travel at 4 m/s in still water heads straight across a river flowing at 3 m/s. The resultant velocity of the boat is",
     "1 m/s", "5 m/s", "7 m/s", "12 m/s", "B",
     "The two velocities are perpendicular: resultant = √(4² + 3²) = 5 m/s.", "5"),
    ("Scalars and Vectors", "Medium", "Two forces of 7 N and 3 N act on a body. The maximum and minimum possible magnitudes of their resultant are respectively",
     "10 N and 4 N", "21 N and 4 N", "10 N and 0 N", "7 N and 3 N", "A",
     "The resultant is greatest (7 + 3 = 10 N) when the forces are in the same direction and least (7 − 3 = 4 N) when they are opposite."),
    ("Scalars and Vectors", "Medium", "A cyclist rides 12 km due west and then 5 km due south. The magnitude of her displacement from the starting point is",
     "7 km", "13 km", "17 km", "60 km", "B",
     "Displacement = √(12² + 5²) = √169 = 13 km, although the distance travelled is 17 km.", "math.sqrt(144+25)"),
    ("Scalars and Vectors", "Medium", "Two forces of 8 N and 6 N act at right angles on a body. The force that must be applied to keep the body in equilibrium is",
     "14 N along the 8 N force", "10 N opposite to the resultant of the two forces", "2 N opposite to the 6 N force", "10 N along the resultant of the two forces", "B",
     "The resultant is √(8² + 6²) = 10 N; a third force equal and opposite to it (the equilibrant) gives zero net force."),
    ("Scalars and Vectors", "Medium", "A projectile is fired at 50 m/s at an angle of 30° above the horizontal. The vertical component of its initial velocity is",
     "25 m/s", "43.3 m/s", "50 m/s", "100 m/s", "A",
     "Vertical component = u sin θ = 50 × sin 30° = 25 m/s.", "50*math.sin(math.radians(30))"),
    ("Scalars and Vectors", "Easy", "Which of the following pairs consists of scalar quantities only?",
     "work and energy", "force and displacement", "velocity and acceleration", "weight and momentum", "A",
     "Work and energy have magnitude but no direction; each of the other pairs contains vectors."),
    ("Scalars and Vectors", "Hard", "Two forces of 6 N and 8 N act at a point with an angle of 60° between them. The magnitude of their resultant is approximately",
     "10 N", "12.2 N", "14 N", "2 N", "B",
     "R² = 6² + 8² + 2 × 6 × 8 × cos 60° = 36 + 64 + 48 = 148, so R = 12.2 N.", "math.sqrt(148)"),
    ("Scalars and Vectors", "Medium", "Car A travels east at 80 km/h while car B travels west at 60 km/h on the same road. The velocity of A relative to B is",
     "20 km/h east", "140 km/h east", "20 km/h west", "140 km/h west", "B",
     "Relative velocity = v_A − v_B = 80 − (−60) = 140 km/h towards the east.", "80+60"),
    ("Scalars and Vectors", "Medium", "A car moves round a circular track at a constant speed of 20 m/s. Which statement is correct?",
     "its velocity is constant", "its velocity changes because its direction changes", "its acceleration is zero", "no force acts on it", "B",
     "Velocity is a vector; a continuous change of direction means the velocity changes, so the car accelerates (towards the centre) and a centripetal force acts on it."),
    ("Scalars and Vectors", "Medium", "A body is acted upon by a 3 N force pointing north and a 4 N force pointing east. The direction of the resultant makes an angle with the east direction of approximately",
     "37°", "53°", "45°", "90°", "A",
     "tan θ = 3/4 = 0.75, so θ = 37° north of east.", "math.degrees(math.atan(3/4))"),
    # ---------------- Motion ----------------
    ("Motion", "Medium", "A car starts from rest and accelerates uniformly at 2 m/s² for 10 s. The distance it covers is",
     "20 m", "100 m", "200 m", "400 m", "B",
     "s = ut + ½at² = 0 + ½ × 2 × 10² = 100 m.", "0.5*2*100"),
    ("Motion", "Medium", "A stone dropped into a well hits the water 2 s later. Taking g = 10 m/s², the depth of the water surface below the top of the well is",
     "10 m", "20 m", "40 m", "80 m", "B",
     "s = ½gt² = ½ × 10 × 2² = 20 m.", "0.5*10*4"),
    ("Motion", "Medium", "A ball is kicked with a velocity of 20 m/s at 30° to the horizontal. Taking g = 10 m/s², its time of flight is",
     "1 s", "2 s", "3 s", "4 s", "B",
     "T = 2u sin θ/g = 2 × 20 × 0.5/10 = 2 s.", "2*20*math.sin(math.radians(30))/10"),
    ("Motion", "Hard", "A ball is kicked with a velocity of 20 m/s at 30° to the horizontal. Taking g = 10 m/s², its horizontal range is approximately",
     "20 m", "34.6 m", "40 m", "69.3 m", "B",
     "R = u² sin 2θ/g = 400 × sin 60°/10 = 400 × 0.866/10 = 34.6 m.", "400*math.sin(math.radians(60))/10"),
    ("Motion", "Medium", "A projectile is launched at 20 m/s at 30° to the horizontal. Taking g = 10 m/s², the maximum height it reaches is",
     "2.5 m", "5 m", "10 m", "20 m", "B",
     "H = (u sin θ)²/2g = (20 × 0.5)²/20 = 100/20 = 5 m.", "(20*0.5)**2/20"),
    ("Motion", "Medium", "A stone tied to a string is whirled in a horizontal circle at 2 revolutions per second. Its angular velocity is",
     "2 rad/s", "6.28 rad/s", "12.6 rad/s", "4 rad/s", "C",
     "ω = 2πf = 2π × 2 = 12.6 rad/s.", "2*math.pi*2"),
    ("Motion", "Medium", "A 1,000 kg car goes round a bend of radius 50 m at 10 m/s. The centripetal force required is",
     "200 N", "2,000 N", "5,000 N", "20,000 N", "B",
     "F = mv²/r = 1,000 × 10²/50 = 2,000 N, supplied by friction between the tyres and the road.", "1000*100/50"),
    ("Motion", "Medium", "A simple pendulum swings between two extreme positions. Its speed is greatest",
     "at either extreme position", "at the lowest point of the swing", "midway between the lowest point and an extreme", "at the same value everywhere", "B",
     "In simple harmonic motion the speed is maximum at the equilibrium (centre) position where the displacement is zero."),
    ("Motion", "Medium", "For a body performing simple harmonic motion, the acceleration is greatest when the body is",
     "at the centre of the motion", "at the extreme positions", "moving fastest", "midway to the centre", "B",
     "Acceleration is proportional to displacement (a = −ω²x), so it is largest at maximum displacement, where the body momentarily stops."),
    ("Motion", "Easy", "The velocity-time graph of a car is a straight line sloping downwards towards the time axis. The car is",
     "at rest", "decelerating uniformly", "accelerating uniformly", "moving with constant velocity", "B",
     "The slope of a velocity-time graph is the acceleration; a constant negative slope means uniform retardation."),
    ("Motion", "Medium", "A train 100 m long passes a signal post in 5 s at constant speed. The time it takes to pass completely through a station platform 300 m long is",
     "15 s", "20 s", "25 s", "40 s", "B",
     "Speed = 100/5 = 20 m/s. To clear the platform the train must travel 100 + 300 = 400 m, taking 400/20 = 20 s.", "400/20"),
    ("Motion", "Medium", "A ball thrown vertically upwards with a speed of 30 m/s returns to the thrower's hand after (g = 10 m/s²)",
     "3 s", "6 s", "9 s", "12 s", "B",
     "Time to the top = u/g = 3 s and the same time to fall back, so 6 s in all.", "2*30/10"),
    ("Motion", "Hard", "A ball is thrown vertically upwards at 30 m/s. Taking g = 10 m/s², its speed when it is 25 m above the point of projection is",
     "10 m/s", "20 m/s", "25 m/s", "5 m/s", "B",
     "v² = u² − 2gh = 900 − 2 × 10 × 25 = 400, so v = 20 m/s.", "math.sqrt(900-500)"),
    ("Motion", "Medium", "A cyclist moving at 12 m/s applies the brakes and comes to rest in 4 s with uniform retardation. The distance travelled while braking is",
     "12 m", "24 m", "48 m", "3 m", "B",
     "Distance = average velocity × time = ½ × 12 × 4 = 24 m.", "0.5*12*4"),
    ("Motion", "Easy", "Passengers standing in a bus lurch forward when the bus stops suddenly. This is explained by",
     "Newton's third law of motion", "the inertia of the passengers", "the centripetal force on the bus", "the friction of the road", "B",
     "By Newton's first law a body keeps moving unless a force acts on it; the passengers' bodies continue forward while the bus stops."),
    ("Motion", "Medium", "A raindrop falls through the air at constant velocity. This happens because",
     "gravity stops acting on the drop", "the air resistance on the drop equals its weight", "the drop has no mass", "the upthrust of the air equals the weight", "B",
     "At terminal velocity the resistive force balances the weight, so the net force and the acceleration are zero."),
    ("Motion", "Medium", "Two identical balls are released from the same height at the same instant; one is dropped and the other is thrown horizontally. Ignoring air resistance,",
     "the dropped ball lands first", "both balls land at the same time", "the thrown ball lands first", "the thrown ball never lands", "B",
     "The vertical motion of both balls is the same free fall from rest; the horizontal velocity of the thrown ball does not affect how long it takes to fall."),
    # ---------------- Forces and Equilibrium ----------------
    ("Forces and Equilibrium", "Medium", "A uniform plank 4 m long weighing 200 N rests on a pivot 1 m from one end. The vertical force needed at that end to keep the plank horizontal is",
     "50 N", "100 N", "200 N", "400 N", "C",
     "The weight acts at the centre, 1 m beyond the pivot; taking moments: F × 1 = 200 × 1, so F = 200 N.", "200*1/1"),
    ("Forces and Equilibrium", "Medium", "A uniform metre rule is supported at its centre. A 50 g mass is hung from the 20 cm mark. To restore the balance, a 100 g mass must be hung from the",
     "35 cm mark", "65 cm mark", "80 cm mark", "95 cm mark", "B",
     "Clockwise moment = anticlockwise moment: 100 × d = 50 × 30, so d = 15 cm on the other side, i.e. the 65 cm mark.", "50+50*30/100"),
    ("Forces and Equilibrium", "Medium", "A uniform metre rule balances horizontally on a knife edge at its 30 cm mark when a 100 g mass hangs from the 5 cm mark. The mass of the rule is",
     "60 g", "125 g", "150 g", "250 g", "B",
     "The rule's weight acts at 50 cm, 20 cm from the pivot; 100 × 25 = W × 20 gives W = 125 g.", "100*25/20"),
    ("Forces and Equilibrium", "Medium", "Two equal and opposite forces of 5 N act on a steering wheel at points 0.4 m apart. The moment of the couple is",
     "1 N m", "2 N m", "4 N m", "12.5 N m", "B",
     "Moment of a couple = one force × perpendicular distance between the forces = 5 × 0.4 = 2 N m.", "5*0.4"),
    ("Forces and Equilibrium", "Easy", "A racing car is built with a low centre of gravity and a wide wheel base in order to",
     "reduce its weight", "increase its stability", "increase friction with the road", "reduce air resistance", "B",
     "A body is stable when its centre of gravity is low and its base wide, so that tilting does not move the weight's line of action outside the base."),
    ("Forces and Equilibrium", "Medium", "For a rigid body acted on by several coplanar forces to be in equilibrium,",
     "only the resultant force must be zero", "the resultant force and the resultant moment must both be zero", "only the resultant moment must be zero", "the forces must all be equal", "B",
     "Zero resultant force prevents translation and zero resultant moment about any point prevents rotation."),
    ("Forces and Equilibrium", "Easy", "A swimmer pushes the water backwards with her hands and moves forwards. This illustrates",
     "Newton's first law", "Newton's second law", "Newton's third law", "the principle of moments", "C",
     "The backward force on the water is matched by an equal and opposite forward force of the water on the swimmer."),
    ("Forces and Equilibrium", "Medium", "A 4 kg block is pulled along a horizontal floor at constant velocity by a horizontal force of 8 N. Taking g = 10 m/s², the coefficient of kinetic friction is",
     "0.1", "0.2", "0.5", "2.0", "B",
     "At constant velocity friction equals the pull: μ = F/R = 8/(4 × 10) = 0.2.", "8/40"),
    ("Forces and Equilibrium", "Medium", "A 10 kg block slides down a smooth (frictionless) plane inclined at 30° to the horizontal. Taking g = 10 m/s², its acceleration is",
     "2.5 m/s²", "5.0 m/s²", "8.7 m/s²", "10 m/s²", "B",
     "a = g sin θ = 10 × sin 30° = 5 m/s²; the mass cancels out.", "10*math.sin(math.radians(30))"),
    ("Forces and Equilibrium", "Hard", "A 2 kg mass hangs from a spring balance in a lift. Taking g = 10 m/s², the balance reads, when the lift accelerates upwards at 2 m/s²,",
     "16 N", "20 N", "24 N", "4 N", "C",
     "T − mg = ma, so T = m(g + a) = 2 × 12 = 24 N.", "2*(10+2)"),
    ("Forces and Equilibrium", "Medium", "A person standing on a weighing scale in a lift notices that the scale reads zero. The lift must be",
     "moving upwards at constant speed", "falling freely under gravity", "at rest", "accelerating upwards", "B",
     "The scale reads m(g − a); it reads zero only when the downward acceleration equals g, i.e. free fall."),
    ("Forces and Equilibrium", "Hard", "A 5 kg picture hangs from two strings, each making 60° with the vertical. Taking g = 10 m/s², the tension in each string is",
     "25 N", "50 N", "43 N", "100 N", "B",
     "The vertical components support the weight: 2T cos 60° = 50, so T = 50 N.", "50/(2*math.cos(math.radians(60)))"),
    ("Forces and Equilibrium", "Easy", "The centre of gravity of a uniform triangular lamina lies at",
     "one of its vertices", "the point where its medians meet", "the midpoint of its longest side", "the midpoint of its shortest side", "B",
     "The medians of a triangle meet at the centroid, one-third of the way along each median from the side; a uniform lamina balances at this point."),
    ("Forces and Equilibrium", "Medium", "A 1,500 kg car accelerates uniformly from rest to 20 m/s in 10 s. The resultant force acting on it is",
     "300 N", "1,500 N", "3,000 N", "30,000 N", "C",
     "a = 20/10 = 2 m/s²; F = ma = 1,500 × 2 = 3,000 N.", "1500*2"),
    ("Forces and Equilibrium", "Medium", "A ladder leaning against a smooth wall is prevented from slipping mainly by",
     "the weight of the ladder", "friction between the ladder and the ground", "the reaction of the smooth wall", "the length of the ladder", "B",
     "The smooth wall can only push horizontally on the ladder; the ground's friction supplies the horizontal force that balances it."),
    # ---------------- Work, Energy and Power ----------------
    ("Work Energy and Power", "Medium", "A boy pulls a load 10 m along a horizontal floor with a rope inclined at 60° to the floor, using a force of 100 N. The work done is",
     "250 J", "500 J", "866 J", "1,000 J", "B",
     "W = F s cos θ = 100 × 10 × cos 60° = 500 J.", "100*10*math.cos(math.radians(60))"),
    ("Work Energy and Power", "Medium", "A 0.5 kg ball is dropped from a height of 20 m. Ignoring air resistance and taking g = 10 m/s², its speed just before it hits the ground is",
     "10 m/s", "20 m/s", "40 m/s", "200 m/s", "B",
     "mgh = ½mv², so v = √(2gh) = √(2 × 10 × 20) = 20 m/s.", "math.sqrt(2*10*20)"),
    ("Work Energy and Power", "Medium", "A pendulum bob is pulled aside until it is 0.2 m above its lowest position and released. Taking g = 10 m/s², its speed as it passes through the lowest point is",
     "1 m/s", "2 m/s", "4 m/s", "0.4 m/s", "B",
     "Potential energy becomes kinetic energy: v = √(2gh) = √(2 × 10 × 0.2) = 2 m/s.", "math.sqrt(2*10*0.2)"),
    ("Work Energy and Power", "Medium", "A crane lifts a 500 kg load through a height of 20 m in 25 s. Taking g = 10 m/s², the power developed is",
     "400 W", "4,000 W", "10,000 W", "100,000 W", "B",
     "Work = mgh = 500 × 10 × 20 = 100,000 J; power = 100,000/25 = 4,000 W.", "500*10*20/25"),
    ("Work Energy and Power", "Hard", "An electric motor rated 2 kW lifts a 100 kg load through 15 m in 10 s. Taking g = 10 m/s², the efficiency of the motor is",
     "50%", "75%", "80%", "90%", "B",
     "Useful power = 100 × 10 × 15/10 = 1,500 W; efficiency = 1,500/2,000 × 100 = 75%.", "100*10*15/10/2000*100"),
    ("Work Energy and Power", "Medium", "Which of the following has the greatest kinetic energy?",
     "a 2 kg body moving at 4 m/s", "a 4 kg body moving at 2 m/s", "an 8 kg body moving at 1 m/s", "a 1 kg body moving at 5 m/s", "A",
     "KE = ½mv²: 16 J, 8 J, 4 J and 12.5 J respectively; the 2 kg body at 4 m/s has the most."),
    ("Work Energy and Power", "Medium", "A porter carries a 20 kg load up a flight of 12 steps, each 0.25 m high. Taking g = 10 m/s², the work done against gravity is",
     "60 J", "600 J", "2,400 J", "6,000 J", "B",
     "Height = 12 × 0.25 = 3 m; work = mgh = 20 × 10 × 3 = 600 J.", "20*10*3"),
    ("Work Energy and Power", "Medium", "A spring of force constant 200 N/m is stretched by 0.1 m. The elastic potential energy stored in it is",
     "0.5 J", "1 J", "2 J", "20 J", "B",
     "E = ½kx² = ½ × 200 × 0.1² = 1 J.", "0.5*200*0.1**2"),
    ("Work Energy and Power", "Medium", "If the speed of a car is doubled, the distance it needs to stop with the same braking force is",
     "halved", "doubled", "quadrupled", "unchanged", "C",
     "Work done by the brakes (F × d) equals the kinetic energy ½mv²; doubling v makes the energy, and hence the stopping distance, four times as great."),
    ("Work Energy and Power", "Medium", "A car engine develops 40 kW while the car travels at a steady 20 m/s on a level road. The total resistive force on the car is",
     "200 N", "800 N", "2,000 N", "20,000 N", "C",
     "Power = force × velocity, so F = 40,000/20 = 2,000 N; at steady speed the driving force equals the resistance.", "40000/20"),
    ("Work Energy and Power", "Easy", "In a hydroelectric power station the energy changes that take place are",
     "kinetic → potential → electrical", "potential → kinetic → electrical", "chemical → heat → electrical", "electrical → kinetic → potential", "B",
     "Water stored high in the dam has potential energy, gains kinetic energy as it falls and turns turbines that drive generators."),
    ("Work Energy and Power", "Medium", "A stone is whirled in a horizontal circle at constant speed. The work done by the centripetal force during one revolution is",
     "equal to the kinetic energy of the stone", "zero", "equal to the force multiplied by the circumference", "equal to the weight multiplied by the radius", "B",
     "The centripetal force is always perpendicular to the displacement, so it does no work and the speed stays constant."),
    ("Work Energy and Power", "Hard", "A 10 g bullet moving at 400 m/s penetrates 20 cm into a block of wood before stopping. The average resistive force of the wood is",
     "400 N", "4,000 N", "8,000 N", "40,000 N", "B",
     "KE = ½ × 0.01 × 400² = 800 J; F = KE/d = 800/0.2 = 4,000 N.", "0.5*0.01*400**2/0.2"),
    ("Work Energy and Power", "Medium", "A 3 kg body is thrown vertically upwards with 100 J of kinetic energy. Taking g = 10 m/s² and ignoring air resistance, the maximum height it reaches is",
     "3.3 m", "10 m", "30 m", "33 m", "A",
     "At the top all the kinetic energy has become potential energy: h = 100/(3 × 10) = 3.3 m.", "round(100/30,1)"),
    ("Work Energy and Power", "Easy", "Which of the following is a renewable source of energy?",
     "coal", "natural gas", "solar energy", "petroleum", "C",
     "Sunlight is continually replenished, whereas fossil fuels are used up faster than they form."),
    # ---------------- Momentum and Machines ----------------
    ("Momentum and Machines", "Easy", "A 1,500 kg car travelling at 20 m/s and a 30,000 kg lorry crawling at 1 m/s have",
     "the same kinetic energy", "the same momentum", "the same velocity", "the same acceleration", "B",
     "Momentum = mass × velocity: 1,500 × 20 = 30,000 kg m/s for the car and 30,000 × 1 = 30,000 kg m/s for the lorry; their kinetic energies (300 kJ and 15 kJ) differ."),
    ("Momentum and Machines", "Medium", "A 0.2 kg ball moving at 10 m/s is caught and brought to rest in 0.05 s. The average force exerted on the ball is",
     "4 N", "40 N", "100 N", "400 N", "B",
     "Force = change in momentum ÷ time = (0.2 × 10)/0.05 = 40 N.", "0.2*10/0.05"),
    ("Momentum and Machines", "Medium", "A 40 kg boy standing on a smooth skateboard throws a 2 kg ball horizontally at 10 m/s. The boy and skateboard move backwards at",
     "0.05 m/s", "0.5 m/s", "5 m/s", "20 m/s", "B",
     "Momentum is conserved: 40 × v = 2 × 10, so v = 0.5 m/s in the opposite direction.", "2*10/40"),
    ("Momentum and Machines", "Medium", "A 4 kg trolley moving at 6 m/s catches up with a 2 kg trolley at rest on the same track and couples to it. The speed of the coupled trolleys is",
     "2 m/s", "4 m/s", "6 m/s", "12 m/s", "B",
     "Total momentum before = 4 × 6 = 24 kg m/s = (4 + 2) × v, so v = 4 m/s.", "4*6/6"),
    ("Momentum and Machines", "Medium", "In a perfectly elastic collision between two bodies,",
     "only momentum is conserved", "both momentum and kinetic energy are conserved", "only kinetic energy is conserved", "the bodies stick together afterwards", "B",
     "Momentum is conserved in every collision; kinetic energy is conserved only in elastic collisions. Bodies that stick together undergo a perfectly inelastic collision."),
    ("Momentum and Machines", "Medium", "A fielder draws his hands backwards while catching a fast cricket ball in order to",
     "increase the momentum of the ball", "increase the time of impact and so reduce the force on his hands", "reduce the kinetic energy of the ball to zero instantly", "make the ball bounce", "B",
     "Force = change of momentum ÷ time; spreading the same momentum change over a longer time reduces the average force."),
    ("Momentum and Machines", "Easy", "A car jack raises a 4,000 N car when a force of 200 N is applied to its handle. The mechanical advantage of the jack is",
     "0.05", "20", "3,800", "800,000", "B",
     "Mechanical advantage = load ÷ effort = 4,000/200 = 20.", "4000/200"),
    ("Momentum and Machines", "Medium", "A machine has a mechanical advantage of 4 and a velocity ratio of 5. Its efficiency is",
     "20%", "80%", "125%", "45%", "B",
     "Efficiency = (MA/VR) × 100 = 4/5 × 100 = 80%.", "4/5*100"),
    ("Momentum and Machines", "Hard", "A screw jack has a pitch of 5 mm and a handle of length 20 cm. Its velocity ratio is approximately",
     "40", "126", "251", "400", "C",
     "VR = 2πR/pitch = 2π × 200 mm/5 mm ≈ 251.", "2*math.pi*200/5"),
    ("Momentum and Machines", "Medium", "A wheel and axle has a wheel of radius 30 cm and an axle of radius 5 cm. Its velocity ratio is",
     "6", "25", "35", "150", "A",
     "VR = radius of wheel ÷ radius of axle = 30/5 = 6.", "30/5"),
    ("Momentum and Machines", "Medium", "The velocity ratio of an inclined plane that makes an angle of 30° with the horizontal is",
     "0.5", "2", "1.73", "30", "B",
     "VR = length of plane ÷ height = 1/sin 30° = 2.", "1/math.sin(math.radians(30))"),
    ("Momentum and Machines", "Hard", "A pulley system with a velocity ratio of 5 is 80% efficient. The effort needed to raise a load of 400 N with it is",
     "64 N", "80 N", "100 N", "125 N", "C",
     "MA = efficiency × VR = 0.8 × 5 = 4; effort = load/MA = 400/4 = 100 N.", "400/(0.8*5)"),
    ("Momentum and Machines", "Easy", "A wheelbarrow is an example of a lever in which",
     "the fulcrum is between the load and the effort", "the load is between the fulcrum and the effort", "the effort is between the fulcrum and the load", "the load and effort act at the same point", "B",
     "In a wheelbarrow the wheel is the fulcrum, the load sits in the tray and the effort is applied at the handles: a second-class lever."),
    ("Momentum and Machines", "Easy", "The efficiency of a practical machine is always less than 100% mainly because",
     "the load is always heavier than the effort", "part of the work done is used against friction and in moving parts of the machine", "the velocity ratio is always less than 1", "energy is created inside the machine", "B",
     "Some of the work input is wasted as heat due to friction and in lifting the movable parts of the machine itself."),
    ("Momentum and Machines", "Medium", "A gear wheel with 20 teeth drives another gear wheel with 60 teeth. The velocity ratio of the arrangement is",
     "1/3", "3", "40", "80", "B",
     "VR = number of teeth on driven wheel ÷ number on driving wheel = 60/20 = 3.", "60/20"),
    # ---------------- Properties of Matter ----------------
    ("Properties of Matter", "Medium", "A spring is 20 cm long when unloaded and 24 cm long when a 2 N weight hangs from it. Within the elastic limit, its length when a 5 N weight hangs from it is",
     "26 cm", "30 cm", "34 cm", "50 cm", "B",
     "2 N gives 4 cm extension, so 5 N gives 10 cm; length = 20 + 10 = 30 cm.", "20+5*4/2"),
    ("Properties of Matter", "Hard", "A wire 2 m long with cross-sectional area 1.0 × 10⁻⁶ m² stretches by 1.0 mm under a load of 100 N. The Young's modulus of the material is",
     "5.0 × 10⁷ N/m²", "2.0 × 10¹¹ N/m²", "1.0 × 10⁸ N/m²", "2.0 × 10⁸ N/m²", "B",
     "Stress = 100/10⁻⁶ = 10⁸ N/m²; strain = 10⁻³/2 = 5 × 10⁻⁴; E = stress/strain = 2.0 × 10¹¹ N/m².", "(100/1e-6)/(1e-3/2)/1e11"),
    ("Properties of Matter", "Easy", "The wall of a dam is built much thicker at the bottom than at the top because",
     "the water is colder at the bottom", "the pressure of the water increases with depth", "the bottom carries the weight of the top", "the water flows faster at the bottom", "B",
     "Pressure in a liquid = hρg, so it is greatest at the base of the dam and the wall must be strongest there."),
    ("Properties of Matter", "Medium", "A solid of volume 200 cm³ is completely immersed in water of density 1,000 kg/m³. Taking g = 10 m/s², the upthrust on it is",
     "0.2 N", "2 N", "20 N", "200 N", "B",
     "Upthrust = weight of water displaced = 200 × 10⁻⁶ m³ × 1,000 × 10 = 2 N.", "200e-6*1000*10"),
    ("Properties of Matter", "Medium", "A block of wood of density 0.6 g/cm³ floats in water. The fraction of its volume below the water surface is",
     "0.4", "0.6", "1.0", "1.67", "B",
     "For a floating body, the fraction submerged = density of body ÷ density of liquid = 0.6/1.0 = 0.6.", "0.6"),
    ("Properties of Matter", "Medium", "A density bottle weighs 20 g empty, 70 g full of water and 60 g full of a liquid. The relative density of the liquid is",
     "0.6", "0.8", "0.86", "1.25", "B",
     "RD = mass of liquid ÷ mass of equal volume of water = (60 − 20)/(70 − 20) = 0.8.", "(60-20)/(70-20)"),
    ("Properties of Matter", "Easy", "A steel needle placed carefully on the surface of water floats although steel is denser than water. This is due to",
     "upthrust", "surface tension", "capillarity", "viscosity", "B",
     "The water surface behaves like a stretched elastic skin that supports the light needle."),
    ("Properties of Matter", "Medium", "When a narrow glass tube is dipped into water the water rises in the tube, but when it is dipped into mercury the mercury level in the tube is depressed. This is because",
     "water is less dense than mercury", "water wets glass (adhesion > cohesion) while mercury does not", "mercury is a metal", "the tube is too narrow for mercury", "B",
     "Capillary rise occurs when the liquid's adhesion to the glass exceeds its own cohesion; for mercury cohesion is stronger, giving a convex meniscus and depression."),
    ("Properties of Matter", "Medium", "A steel ball falling through glycerine soon reaches a constant (terminal) velocity. At this stage",
     "the weight of the ball is zero", "the weight equals the sum of the upthrust and the viscous drag", "the viscous drag is zero", "the upthrust equals the weight", "B",
     "The net force is zero at terminal velocity, so the downward weight is balanced by the upward upthrust plus viscous force."),
    ("Properties of Matter", "Medium", "A 50 kg girl stands on two stiletto heels each of area 1 cm². Taking g = 10 m/s², the pressure she exerts on the floor is",
     "2.5 × 10⁴ Pa", "2.5 × 10⁶ Pa", "5.0 × 10⁴ Pa", "5.0 × 10⁶ Pa", "B",
     "P = F/A = 500 N ÷ (2 × 10⁻⁴ m²) = 2.5 × 10⁶ Pa.", "500/2e-4/1e6"),
    ("Properties of Matter", "Easy", "The mercury column of a simple barometer becomes shorter when the barometer is carried up a high mountain because",
     "the temperature falls", "atmospheric pressure decreases with altitude", "mercury contracts at high altitude", "the glass tube expands", "B",
     "The height of the column is held up by atmospheric pressure, which falls as the mass of air above decreases."),
    ("Properties of Matter", "Medium", "A spring stretched beyond its elastic limit",
     "returns to its original length when the load is removed", "does not return to its original length when the load is removed", "obeys Hooke's law more closely", "becomes stiffer", "B",
     "Beyond the elastic limit the material is permanently deformed; Hooke's law applies only up to the limit of proportionality."),
    ("Properties of Matter", "Medium", "Glass softens gradually over a range of temperatures rather than melting sharply because it is",
     "a crystalline solid", "an amorphous solid", "a pure metal", "a very hard solid", "B",
     "Amorphous solids have no regular long-range structure and no fixed melting point; crystalline solids melt sharply."),
    ("Properties of Matter", "Medium", "A hydrometer floats deeper in kerosene than in water because",
     "kerosene is less dense than water", "kerosene is more viscous than water", "kerosene is warmer than water", "kerosene wets the glass", "A",
     "A floating hydrometer displaces its own weight of liquid; in a less dense liquid it must sink further to displace the same weight."),
    ("Properties of Matter", "Hard", "A body weighs 8 N in air and 6 N when completely immersed in a liquid of relative density 0.8. The volume of the body is (g = 10 m/s²)",
     "2.5 × 10⁻⁴ m³", "2.0 × 10⁻⁴ m³", "8.0 × 10⁻⁴ m³", "1.0 × 10⁻⁴ m³", "A",
     "Upthrust = 8 − 6 = 2 N = V × 800 × 10, so V = 2/8,000 = 2.5 × 10⁻⁴ m³.", "2/8000/1e-4"),
    # ---------------- Heat and Thermal Physics ----------------
    ("Heat and Thermal Physics", "Medium", "On an unmarked mercury thermometer the mercury thread is 2 cm long in melting ice and 22 cm long in steam at 100 °C. When the thread is 10 cm long the temperature is",
     "10 °C", "40 °C", "50 °C", "80 °C", "B",
     "θ = (l − l₀)/(l₁₀₀ − l₀) × 100 = (10 − 2)/(22 − 2) × 100 = 40 °C.", "(10-2)/(22-2)*100"),
    ("Heat and Thermal Physics", "Medium", "A 500 W immersion heater is used to warm 2 kg of water for 84 s. Ignoring heat losses and taking c = 4,200 J kg⁻¹ K⁻¹, the rise in temperature is",
     "2.5 °C", "5 °C", "10 °C", "20 °C", "B",
     "Energy = 500 × 84 = 42,000 J; ΔT = 42,000/(2 × 4,200) = 5 °C.", "500*84/(2*4200)"),
    ("Heat and Thermal Physics", "Medium", "The energy required to change 0.5 kg of water at 100 °C into steam at 100 °C is (specific latent heat of vaporisation = 2.26 × 10⁶ J/kg)",
     "1.13 × 10⁵ J", "1.13 × 10⁶ J", "4.52 × 10⁶ J", "2.26 × 10⁶ J", "B",
     "Q = mL = 0.5 × 2.26 × 10⁶ = 1.13 × 10⁶ J; no temperature change is involved.", "0.5*2.26e6/1e6"),
    ("Heat and Thermal Physics", "Hard", "0.1 kg of ice at 0 °C is added to 0.4 kg of water at 30 °C in an insulated cup. The final temperature of the mixture is (L_ice = 336,000 J/kg, c_water = 4,200 J kg⁻¹ K⁻¹)",
     "0 °C", "8 °C", "15 °C", "24 °C", "B",
     "Heat available cooling water to 0 °C: 0.4 × 4,200 × 30 = 50,400 J; melting the ice needs 33,600 J, leaving 16,800 J to warm 0.5 kg: ΔT = 16,800/(0.5 × 4,200) = 8 °C.", "(0.4*4200*30-0.1*336000)/(0.5*4200)"),
    ("Heat and Thermal Physics", "Medium", "200 cm³ of a gas at 27 °C and 1 atm is heated to 327 °C while its pressure is raised to 2 atm. Its new volume is",
     "100 cm³", "200 cm³", "400 cm³", "800 cm³", "B",
     "P₁V₁/T₁ = P₂V₂/T₂: V₂ = 200 × (1/2) × (600/300) = 200 cm³.", "200*(1/2)*(600/300)"),
    ("Heat and Thermal Physics", "Easy", "A glass stopper stuck in the neck of a glass bottle can be loosened by warming the neck gently because",
     "the stopper contracts", "the neck expands before the stopper does", "glass becomes soft when warm", "the air inside the bottle escapes", "B",
     "Heat reaches the outer neck first and it expands, widening the hole slightly before the stopper warms up."),
    ("Heat and Thermal Physics", "Medium", "The linear expansivity of a metal is 1.2 × 10⁻⁵ K⁻¹. Its cubic expansivity is",
     "1.2 × 10⁻⁵ K⁻¹", "2.4 × 10⁻⁵ K⁻¹", "3.6 × 10⁻⁵ K⁻¹", "4.8 × 10⁻⁵ K⁻¹", "C",
     "Cubic expansivity ≈ 3 × linear expansivity = 3 × 1.2 × 10⁻⁵ = 3.6 × 10⁻⁵ K⁻¹.", "3*1.2"),
    ("Heat and Thermal Physics", "Easy", "During the day a breeze blows from the sea towards the land because",
     "the sea is warmer than the land", "the land heats up faster, and the warm air over it rises and is replaced by cooler air from the sea", "the sea water evaporates and pushes the air", "the land is at a higher level than the sea", "B",
     "Land has a lower specific heat capacity than water, so it warms faster; the resulting convection current is the sea breeze."),
    ("Heat and Thermal Physics", "Easy", "The silvered walls and the vacuum between the walls of a vacuum flask reduce heat transfer respectively by",
     "conduction and convection", "radiation, and conduction and convection", "convection and radiation", "radiation and evaporation", "B",
     "Shiny surfaces are poor emitters and absorbers of radiation, while the vacuum contains no material to conduct or convect heat."),
    ("Heat and Thermal Physics", "Medium", "A person feels cold after coming out of a swimming pool on a windy day because",
     "the water on the skin is colder than the air", "the water evaporating from the skin takes its latent heat from the body", "the wind is always colder than still air", "water conducts heat into the body", "B",
     "Evaporation is a cooling process; the wind speeds it up, so heat is removed from the skin faster."),
    ("Heat and Thermal Physics", "Medium", "Food cooks faster in a pressure cooker because",
     "the pressure forces heat into the food", "the increased pressure raises the boiling point of the water above 100 °C", "steam is hotter than boiling water at the same pressure", "the lid prevents heat loss by radiation", "B",
     "The boiling point of a liquid rises with pressure, so the water and steam in the cooker are hotter than 100 °C."),
    ("Heat and Thermal Physics", "Medium", "Dew forms on grass on a clear night when the temperature of the air near the ground falls to the",
     "boiling point of water", "dew point", "melting point of ice", "room temperature", "B",
     "At the dew point the air becomes saturated with water vapour and the excess condenses on cool surfaces."),
    ("Heat and Thermal Physics", "Medium", "Which of the following statements explains why the temperature of the sea changes much less than that of the land between day and night?",
     "sea water has a higher specific heat capacity than land", "sea water is a better conductor of heat than land", "sea water reflects all the sunlight", "the sea is deeper than the land is high", "A",
     "A large specific heat capacity means that a given amount of heat produces only a small change in temperature."),
    ("Heat and Thermal Physics", "Easy", "The lowest temperature recorded at a weather station was −73 °C. On the kelvin scale this is",
     "73 K", "200 K", "346 K", "−346 K", "B",
     "T(K) = θ(°C) + 273 = −73 + 273 = 200 K.", "-73+273"),
    ("Heat and Thermal Physics", "Easy", "On the same morning a tiled floor feels much colder to bare feet than a rug lying next to it. This is because the tiles",
     "are at a lower temperature than the rug", "conduct heat away from the feet faster than the rug", "absorb cold from the ground beneath", "have a lower specific heat capacity than the rug", "B",
     "Both surfaces are at room temperature; the tiles are the better conductor and remove heat from the skin faster, which feels cold."),
    ("Heat and Thermal Physics", "Medium", "Fish survive in a pond whose surface has frozen because",
     "ice is a good conductor of heat", "water has its maximum density at 4 °C, so the densest water stays at the bottom and does not freeze", "fish generate their own heat", "the ice melts at the bottom", "B",
     "Because of the anomalous expansion of water, water at 4 °C sinks and the ice forms on top, insulating the water below."),
    ("Heat and Thermal Physics", "Medium", "A 2 kg copper pot is heated on a stove from 20 °C to 70 °C. Taking the specific heat capacity of copper as 400 J kg⁻¹ K⁻¹, the heat absorbed by the pot is",
     "4,000 J", "40,000 J", "56,000 J", "16,000 J", "B",
     "Q = mcΔT = 2 × 400 × 50 = 40,000 J.", "2*400*50"),
    # ---------------- Waves ----------------
    ("Waves", "Easy", "A loudspeaker emits a note of frequency 170 Hz. Taking the speed of sound in air as 340 m/s, the distance between successive compressions in the air is",
     "0.5 m", "2 m", "170 m", "57,800 m", "B",
     "Wave speed = frequency × wavelength, so λ = v/f = 340/170 = 2 m.", "340/170"),
    ("Waves", "Medium", "Sound waves are described as longitudinal because",
     "they can travel through a vacuum", "the particles of the medium vibrate parallel to the direction of travel of the wave", "they cannot be reflected", "the particles vibrate at right angles to the direction of travel", "B",
     "In a longitudinal wave the vibrations are along the direction of propagation, producing compressions and rarefactions."),
    ("Waves", "Medium", "A vibrator produces 40 complete waves in 8 s on a rope, and the distance between successive troughs is 0.15 m. The speed of the waves is",
     "0.03 m/s", "0.75 m/s", "1.2 m/s", "6 m/s", "B",
     "f = 40/8 = 5 Hz; v = fλ = 5 × 0.15 = 0.75 m/s.", "40/8*0.15"),
    ("Waves", "Medium", "Two points on a progressive wave are a quarter of a wavelength apart. The phase difference between them is",
     "45°", "90°", "180°", "360°", "B",
     "One wavelength corresponds to 360°, so λ/4 corresponds to 90° (π/2 radians).", "90"),
    ("Waves", "Medium", "In a stationary wave the distance between two successive nodes is 0.2 m. The wavelength of the wave is",
     "0.1 m", "0.2 m", "0.4 m", "0.8 m", "C",
     "Adjacent nodes are half a wavelength apart, so λ = 2 × 0.2 = 0.4 m.", "2*0.2"),
    ("Waves", "Easy", "A person standing round the corner of a building can hear people talking on the other side but cannot see them. This is because sound waves",
     "travel faster than light", "are diffracted round the corner more than light waves", "are reflected by the building", "are longitudinal", "B",
     "Sound wavelengths (about a metre) are comparable to the size of the obstacle, so sound diffracts strongly; light wavelengths are far too small."),
    ("Waves", "Medium", "When water waves pass from deep water into shallow water, their",
     "frequency decreases", "speed and wavelength decrease while the frequency stays the same", "speed increases", "wavelength increases", "B",
     "The frequency is fixed by the source; slowing down in shallow water shortens the wavelength (v = fλ), which is refraction."),
    ("Waves", "Easy", "The electromagnetic waves used in television remote controls are",
     "X-rays", "infrared waves", "ultraviolet waves", "gamma rays", "B",
     "Remote controls send coded pulses of infrared radiation to the receiver."),
    ("Waves", "Hard", "A progressive wave is represented by y = 5 sin(200πt − 0.5πx), where x and y are in metres and t in seconds. The frequency of the wave is",
     "50 Hz", "100 Hz", "200 Hz", "400 Hz", "B",
     "Comparing with y = A sin(2πft − kx): 2πf = 200π, so f = 100 Hz.", "200/2"),
    ("Waves", "Medium", "If the amplitude of a wave is doubled while its frequency stays the same, the energy it carries becomes",
     "half as much", "twice as much", "four times as much", "unchanged", "C",
     "The energy of a wave is proportional to the square of its amplitude."),
    ("Waves", "Medium", "The speed of a transverse wave on a stretched string is 20 m/s. If the tension in the string is made four times as great, the new speed is",
     "5 m/s", "40 m/s", "80 m/s", "10 m/s", "B",
     "v = √(T/μ), so quadrupling the tension doubles the speed: 40 m/s.", "20*math.sqrt(4)"),
    ("Waves", "Medium", "Plane water waves in a ripple tank pass through a narrow gap in a barrier and spread out in circular arcs. This phenomenon is",
     "refraction", "diffraction", "reflection", "polarisation", "B",
     "Spreading of waves after passing through an opening (or round an edge) is diffraction, most marked when the gap is about a wavelength wide."),
    ("Waves", "Medium", "The Moon is about 3.84 × 10⁸ m from the Earth. The time taken for a radio signal to travel from the Earth to the Moon is (c = 3 × 10⁸ m/s)",
     "0.78 s", "1.28 s", "2.56 s", "12.8 s", "B",
     "t = distance/speed = 3.84 × 10⁸/3 × 10⁸ = 1.28 s.", "3.84e8/3e8"),
    ("Waves", "Easy", "A mosquito's wings complete one beat every 0.004 s. The frequency of the whine it produces is",
     "25 Hz", "250 Hz", "400 Hz", "2,500 Hz", "B",
     "Frequency = 1/period = 1/0.004 = 250 Hz.", "1/0.004"),
    ("Waves", "Medium", "Which of the following phenomena shows that light waves are transverse?",
     "reflection", "refraction", "polarisation", "diffraction", "C",
     "Only transverse waves can be polarised; reflection, refraction and diffraction occur with longitudinal waves too."),
    # ---------------- Sound ----------------
    ("Sound", "Medium", "A flash of lightning is seen and the thunder is heard 6 s later. Taking the speed of sound as 330 m/s, the distance of the lightning is about",
     "0.55 km", "1.98 km", "3.3 km", "55 km", "B",
     "The light arrives almost instantly; distance = 330 × 6 = 1,980 m ≈ 1.98 km.", "330*6/1000"),
    ("Sound", "Medium", "A man fires a gun and hears the echo from a cliff 1.5 km away. Taking the speed of sound as 330 m/s, the echo is heard after about",
     "4.5 s", "9.1 s", "18 s", "2.3 s", "B",
     "The sound travels to the cliff and back, 3,000 m: t = 3,000/330 = 9.1 s.", "3000/330"),
    ("Sound", "Easy", "The pitch of a musical note depends on the",
     "amplitude of the vibration", "frequency of the vibration", "speed of sound in air", "distance from the source", "B",
     "Pitch rises with frequency; amplitude determines loudness and the mixture of overtones determines quality."),
    ("Sound", "Hard", "A tuning fork of frequency 425 Hz produces the first resonance of an air column closed at one end when the column is 20 cm long. Ignoring end correction, the speed of sound in air is",
     "170 m/s", "340 m/s", "680 m/s", "85 m/s", "B",
     "For the first resonance L = λ/4, so λ = 0.8 m and v = fλ = 425 × 0.8 = 340 m/s.", "4*0.2*425"),
    ("Sound", "Medium", "An air column closed at one end gives its first resonance with a tuning fork when it is 20 cm long. The next resonance with the same fork occurs when the column is",
     "30 cm long", "40 cm long", "60 cm long", "80 cm long", "C",
     "Resonance lengths of a closed pipe are λ/4, 3λ/4, 5λ/4…, so the second resonance is at 3 × 20 = 60 cm.", "3*20"),
    ("Sound", "Medium", "The fundamental frequency of an open pipe 0.5 m long is (speed of sound = 340 m/s)",
     "170 Hz", "340 Hz", "680 Hz", "85 Hz", "B",
     "For an open pipe L = λ/2, so λ = 1 m and f = v/λ = 340 Hz.", "340/(2*0.5)"),
    ("Sound", "Medium", "A sonometer wire 50 cm long vibrates at 256 Hz. Keeping the tension the same, the length that will vibrate at 512 Hz is",
     "100 cm", "25 cm", "12.5 cm", "200 cm", "B",
     "Frequency is inversely proportional to length: halving the length doubles the frequency, so 25 cm.", "50*256/512"),
    ("Sound", "Medium", "If the tension in a vibrating string is made four times as great, its fundamental frequency",
     "doubles", "quadruples", "halves", "remains the same", "A",
     "f = (1/2L)√(T/μ), so f is proportional to √T; four times the tension gives twice the frequency."),
    ("Sound", "Medium", "Two tuning forks of frequencies 256 Hz and 260 Hz are sounded together. The number of beats heard per second is",
     "2", "4", "8", "516", "B",
     "Beat frequency = difference of the two frequencies = 260 − 256 = 4 per second.", "260-256"),
    ("Sound", "Easy", "An electric bell ringing inside a bell jar becomes inaudible as the air is pumped out, although the hammer is still seen striking the gong. This shows that",
     "sound needs a material medium to travel through", "light needs a material medium to travel through", "the bell stops working in a vacuum", "sound travels faster in a vacuum", "A",
     "Sound is carried by vibrating particles; with no air in the jar there is nothing to carry it, while light still passes."),
    ("Sound", "Easy", "The range of frequencies audible to a normal human ear is approximately",
     "2 Hz to 2 kHz", "20 Hz to 20 kHz", "200 Hz to 200 kHz", "20 kHz to 200 kHz", "B",
     "Sounds below 20 Hz are infrasonic and those above 20 kHz are ultrasonic."),
    ("Sound", "Medium", "A person puts an ear to a railway line and hears an approaching train before hearing it through the air because",
     "sound travels faster in steel than in air", "the rail amplifies the sound", "air absorbs all the sound", "the train is moving towards the person", "A",
     "Sound travels about 15 times faster in steel than in air, so the vibration through the rail arrives first."),
    ("Sound", "Medium", "A stretched string has a fundamental frequency of 100 Hz. The frequency of its second overtone is",
     "150 Hz", "200 Hz", "300 Hz", "400 Hz", "C",
     "For a string the overtones are integral multiples of the fundamental; the second overtone is the third harmonic, 3 × 100 = 300 Hz.", "3*100"),
    ("Sound", "Medium", "A noise-cancelling headphone produces a sound wave that is exactly out of phase with the incoming noise. The noise is reduced because of",
     "constructive interference", "destructive interference", "resonance", "diffraction", "B",
     "When two waves of equal amplitude meet in antiphase their displacements cancel, which is destructive interference."),
    # ---------------- Light and Optics ----------------
    ("Light and Optics", "Medium", "A ray of light strikes a plane mirror making an angle of 30° with the surface of the mirror. The angle of reflection is",
     "30°", "60°", "90°", "120°", "B",
     "Angles of incidence and reflection are measured from the normal: 90° − 30° = 60°.", "90-30"),
    ("Light and Optics", "Medium", "Two plane mirrors are inclined at 60° to each other. The number of images of an object placed between them is",
     "3", "5", "6", "7", "B",
     "Number of images = 360°/θ − 1 = 360/60 − 1 = 5.", "360/60-1"),
    ("Light and Optics", "Medium", "A plane mirror is rotated through 10° while the incident ray is kept fixed. The reflected ray turns through",
     "5°", "10°", "20°", "40°", "C",
     "Rotating the mirror by θ changes the angle of incidence by θ, so the angle between the incident and reflected rays changes by 2θ = 20°.", "2*10"),
    ("Light and Optics", "Medium", "A swimming pool is 2.0 m deep but appears to be only 1.5 m deep when viewed from directly above. The refractive index of the water is",
     "0.75", "1.33", "1.5", "3.5", "B",
     "n = real depth/apparent depth = 2.0/1.5 = 1.33.", "2/1.5"),
    ("Light and Optics", "Easy", "Light is transmitted along an optical fibre without escaping through its sides because of",
     "diffraction", "total internal reflection", "dispersion", "polarisation", "B",
     "Light meeting the wall of the fibre at angles greater than the critical angle is totally reflected back into the core."),
    ("Light and Optics", "Medium", "Light travelling inside a glass block of refractive index 2.0 is totally internally reflected at the glass-air surface whenever its angle of incidence exceeds",
     "30°", "45°", "60°", "90°", "A",
     "Total internal reflection occurs beyond the critical angle C, where sin C = 1/n = 0.5, so C = 30°.", "math.degrees(math.asin(1/2))"),
    ("Light and Optics", "Hard", "A ray of light travelling in water (refractive index 4/3) meets the water-air surface at an angle of incidence of 30°. The angle of refraction in the air is approximately",
     "22°", "42°", "30°", "60°", "B",
     "n_water sin i = n_air sin r: sin r = (4/3) × 0.5 = 0.667, so r ≈ 42°.", "math.degrees(math.asin(4/3*0.5))"),
    ("Light and Optics", "Medium", "A camera with a lens of focal length 10 cm is used to photograph a flower 30 cm away. For a sharp picture the film must be",
     "15 cm behind the lens, receiving a real, diminished image", "15 cm behind the lens, receiving a virtual, magnified image", "30 cm behind the lens, receiving a real image of the same size", "7.5 cm behind the lens, receiving a virtual, diminished image", "A",
     "1/v = 1/f − 1/u = 1/10 − 1/30 = 2/30, so v = 15 cm; the image is real, inverted and half the size (m = v/u = 0.5)."),
    ("Light and Optics", "Hard", "A small lamp is placed 20 cm in front of a diverging lens of focal length 10 cm. The image of the lamp is",
     "6.7 cm from the lens, virtual and erect", "20 cm from the lens, real and inverted", "6.7 cm from the lens, real and inverted", "40 cm from the lens, virtual and magnified", "A",
     "1/v = 1/f − 1/u = −1/10 − 1/20 = −3/20, so v = −6.7 cm: a virtual, erect, diminished image on the same side as the object."),
    ("Light and Optics", "Easy", "An optician prescribes spectacles of power +4 D for a patient. The lenses are",
     "diverging, of focal length 4 cm", "converging, of focal length 25 cm", "diverging, of focal length 25 cm", "converging, of focal length 4 m", "B",
     "f = 1/P = 1/4 m = 25 cm; a positive power means a converging lens."),
    ("Light and Optics", "Medium", "A converging lens is used as a magnifying glass. To see a magnified, erect image the object must be placed",
     "beyond twice the focal length", "between the focal point and the lens", "exactly at the focal point", "at twice the focal length", "B",
     "An object inside the focal length gives a virtual, erect, magnified image on the same side as the object."),
    ("Light and Optics", "Medium", "The eye focuses on objects at different distances by",
     "moving the retina backwards and forwards", "changing the focal length of the lens through the ciliary muscles", "changing the size of the pupil", "moving the lens towards or away from the retina", "B",
     "This is accommodation; a camera, by contrast, focuses by moving its lens."),
    ("Light and Optics", "Easy", "When white light passes through a glass prism, the colour that is deviated most is",
     "red", "yellow", "green", "violet", "D",
     "Violet light has the shortest wavelength and the greatest refractive index in glass, so it is bent most."),
    ("Light and Optics", "Medium", "A red shirt is viewed in a room lit only by pure green light. The shirt appears",
     "red", "green", "black", "yellow", "C",
     "A red object reflects only red light and absorbs green; with no red light available, it reflects nothing and looks black."),
    ("Light and Optics", "Medium", "A man 2 m tall stands 10 m from a pinhole camera whose screen is 20 cm from the pinhole. The height of his image on the screen is",
     "2 cm", "4 cm", "10 cm", "40 cm", "B",
     "Magnification = image distance/object distance = 0.2/10; image height = 2 × 0.02 = 0.04 m = 4 cm.", "2*0.2/10*100"),
    ("Light and Optics", "Medium", "An object is placed 10 cm in front of a concave mirror of focal length 20 cm. The image formed is",
     "real, inverted and diminished", "virtual, erect and magnified", "real, inverted and magnified", "virtual, erect and diminished", "B",
     "An object inside the focal length of a concave mirror gives a virtual, erect, enlarged image — the principle of the shaving mirror."),
    ("Light and Optics", "Hard", "A long-sighted person can read clearly only when a book is held 100 cm away. The focal length of the spectacle lens that lets him read at 25 cm is",
     "20 cm converging", "33 cm converging", "33 cm diverging", "100 cm converging", "B",
     "The lens must form a virtual image at 100 cm of an object at 25 cm: 1/f = 1/25 − 1/100 = 3/100, so f = 33 cm (converging).", "round(100/3)"),
    # ---------------- Electricity ----------------
    ("Electricity", "Medium", "A 12 Ω and a 6 Ω resistor are connected in parallel, and the combination is joined in series with a 2 Ω resistor across an 18 V battery of negligible internal resistance. The current drawn from the battery is",
     "1 A", "3 A", "6 A", "9 A", "B",
     "Parallel pair: (12 × 6)/(12 + 6) = 4 Ω; total = 4 + 2 = 6 Ω; I = 18/6 = 3 A.", "18/(12*6/18+2)"),
    ("Electricity", "Hard", "Two resistors of 3 Ω and 6 Ω are joined in parallel and a 4 Ω resistor is placed in series with them. The arrangement is connected to a 12 V battery of negligible internal resistance. The current in the 3 Ω resistor is",
     "0.67 A", "1.33 A", "2 A", "4 A", "B",
     "Parallel pair: (3 × 6)/(3 + 6) = 2 Ω; total 6 Ω, so the battery supplies 2 A. The p.d. across the pair is 2 × 2 = 4 V and the 3 Ω resistor carries 4/3 = 1.33 A.", "4/3"),
    ("Electricity", "Medium", "A copper wire 2 m long has a cross-sectional area of 1.0 mm². Taking the resistivity of copper as 1.7 × 10⁻⁸ Ω m, its resistance is",
     "0.0085 Ω", "0.034 Ω", "0.34 Ω", "3.4 Ω", "B",
     "R = ρL/A = 1.7 × 10⁻⁸ × 2/(1.0 × 10⁻⁶) = 0.034 Ω.", "1.7e-8*2/1e-6"),
    ("Electricity", "Medium", "A current of 2 A flows through a 5 Ω resistor for 1 minute. The heat produced is",
     "10 J", "600 J", "1,200 J", "2,400 J", "C",
     "H = I²Rt = 2² × 5 × 60 = 1,200 J.", "4*5*60"),
    ("Electricity", "Easy", "A 100 W bulb left on for 10 hours consumes",
     "0.1 kWh", "1 kWh", "10 kWh", "1,000 kWh", "B",
     "Energy = power × time = 0.1 kW × 10 h = 1 kWh (one 'unit').", "100*10/1000"),
    ("Electricity", "Easy", "Currents of 3 A and 2 A flow into a junction and a single wire carries the current away. The current in that wire is",
     "1 A", "5 A", "6 A", "2.5 A", "B",
     "By Kirchhoff's first law the total current entering a junction equals the total leaving: 3 + 2 = 5 A.", "3+2"),
    ("Electricity", "Medium", "An electric kettle is rated 2 kW, 240 V. The current it draws is approximately",
     "0.12 A", "8.3 A", "12 A", "480 A", "B",
     "I = P/V = 2,000/240 = 8.3 A, so a 13 A fuse is suitable.", "2000/240"),
    ("Electricity", "Medium", "A 4 Ω resistor and an 8 Ω resistor are connected in series across a 12 V supply. The potential difference across the 8 Ω resistor is",
     "4 V", "8 V", "12 V", "6 V", "B",
     "The current is 12/12 = 1 A, so the p.d. across 8 Ω is 1 × 8 = 8 V (the resistors share the voltage in the ratio of their resistances).", "12*8/12"),
    ("Electricity", "Medium", "A torch cell of e.m.f. 2.0 V and internal resistance 1 Ω lights a bulb of resistance 3 Ω. The p.d. across the bulb is",
     "0.5 V", "1.5 V", "2.0 V", "6.0 V", "B",
     "I = E/(R + r) = 2/4 = 0.5 A; terminal p.d. = IR = 0.5 × 3 = 1.5 V.", "2/(3+1)*3"),
    ("Electricity", "Medium", "The energy stored in a 4 μF capacitor charged to 100 V is",
     "0.02 J", "0.04 J", "0.2 J", "2 J", "A",
     "E = ½CV² = ½ × 4 × 10⁻⁶ × 100² = 0.02 J.", "0.5*4e-6*100**2"),
    ("Electricity", "Medium", "Two 2 μF capacitors are connected in series. Their combined capacitance is",
     "0.5 μF", "1 μF", "2 μF", "4 μF", "B",
     "For series capacitors 1/C = 1/2 + 1/2 = 1, so C = 1 μF.", "1"),
    ("Electricity", "Medium", "A charge of 60 C passes a point in a wire in 2 minutes. The current in the wire is",
     "0.5 A", "2 A", "30 A", "120 A", "A",
     "I = Q/t = 60/120 = 0.5 A.", "60/120"),
    ("Electricity", "Medium", "The force between two point charges is F when they are 2 cm apart. When the separation is increased to 4 cm the force becomes",
     "F/2", "F/4", "2F", "4F", "B",
     "By Coulomb's law the force is inversely proportional to the square of the distance; doubling the distance divides the force by four."),
    ("Electricity", "Medium", "Two parallel metal plates 4 mm apart have a potential difference of 200 V between them. The electric field strength between the plates is",
     "5 × 10² V/m", "5 × 10⁴ V/m", "8 × 10² V/m", "8 × 10⁵ V/m", "B",
     "E = V/d = 200/(4 × 10⁻³) = 5 × 10⁴ V/m.", "200/4e-3/1e4"),
    ("Electricity", "Easy", "To convert a galvanometer into an ammeter, one connects",
     "a high resistance in series with it", "a low resistance (shunt) in parallel with it", "a high resistance in parallel with it", "a low resistance in series with it", "B",
     "The shunt carries most of the current so that only a small known fraction passes through the delicate coil."),
    ("Electricity", "Hard", "A galvanometer of resistance 50 Ω gives full-scale deflection for a current of 2 mA. The shunt needed to convert it to an ammeter reading up to 1 A is approximately",
     "0.1 Ω", "1 Ω", "10 Ω", "50 Ω", "A",
     "The shunt carries 0.998 A while 0.002 A passes through the coil: S = (0.002 × 50)/0.998 ≈ 0.1 Ω.", "0.002*50/0.998"),
    ("Electricity", "Medium", "In a metre bridge a 6 Ω resistor in the left gap balances an unknown resistor R in the right gap at the 40 cm mark from the left end. The value of R is",
     "4 Ω", "9 Ω", "15 Ω", "2.4 Ω", "B",
     "6/R = 40/60, so R = 6 × 60/40 = 9 Ω.", "6*60/40"),
    ("Electricity", "Medium", "The current-voltage graph for a filament lamp is a curve that bends towards the voltage axis because",
     "the lamp obeys Ohm's law", "the resistance of the filament increases as it gets hotter", "the filament resistance decreases with temperature", "the voltage supply is alternating", "B",
     "A tungsten filament is non-ohmic: as the current heats it, its resistance rises, so the current increases less than proportionally."),
    ("Electricity", "Easy", "The earth wire of a three-pin plug is connected to the metal casing of an appliance so that",
     "the appliance uses less electricity", "if a live wire touches the casing the current flows to earth and blows the fuse instead of passing through the user", "the appliance heats up faster", "the current returns to the power station", "B",
     "The earth wire provides a low-resistance path for fault current, protecting the user from electric shock."),
    ("Electricity", "Medium", "A bulb rated 60 W, 240 V has a working resistance of",
     "4 Ω", "240 Ω", "960 Ω", "14,400 Ω", "C",
     "P = V²/R, so R = 240²/60 = 960 Ω.", "240**2/60"),
    ("Electricity", "Medium", "A lightning conductor on a tall building has a pointed tip because",
     "charge concentrates at sharp points, allowing it to leak away and neutralise the cloud", "points attract lightning more strongly", "a point is cheaper to make than a ball", "a sharp point melts more easily", "A",
     "The high charge density at a point ionises the surrounding air, quietly discharging the building and reducing the chance of a strike (action of points)."),
    # ---------------- Magnetism and Electromagnetic Induction ----------------
    ("Magnetism and Electromagnetic Induction", "Medium", "A transformer is to step down 240 V to 12 V. If its primary coil has 1,000 turns, the number of turns on the secondary coil is",
     "20", "50", "500", "20,000", "B",
     "Ns/Np = Vs/Vp, so Ns = 1,000 × 12/240 = 50 turns.", "1000*12/240"),
    ("Magnetism and Electromagnetic Induction", "Medium", "The core of a transformer is made of thin laminated sheets rather than one solid block in order to reduce",
     "hysteresis loss", "eddy current loss", "copper loss", "flux leakage", "B",
     "Thin insulated laminations break up the paths of the circulating eddy currents that would otherwise heat the core."),
    ("Magnetism and Electromagnetic Induction", "Medium", "A straight wire 0.1 m long carrying a current of 2 A lies at right angles to a magnetic field of flux density 0.5 T. The force on the wire is",
     "0.01 N", "0.1 N", "1 N", "10 N", "B",
     "F = BIL = 0.5 × 2 × 0.1 = 0.1 N.", "0.5*2*0.1"),
    ("Magnetism and Electromagnetic Induction", "Easy", "The rule used to find the direction of the force on a current-carrying conductor in a magnetic field is",
     "Fleming's right-hand rule", "Fleming's left-hand rule", "Maxwell's corkscrew rule", "Lenz's law", "B",
     "The left-hand rule applies to the motor effect; the right-hand rule gives the direction of an induced current in a generator."),
    ("Magnetism and Electromagnetic Induction", "Medium", "A bar magnet dropped down a vertical copper tube falls much more slowly than an identical unmagnetised bar. This is because",
     "copper is magnetic and attracts the magnet", "the induced currents in the tube produce a field that opposes the motion of the magnet", "the air in the tube slows the magnet", "the magnet loses its weight in the tube", "B",
     "By Lenz's law the eddy currents induced in the tube oppose the change causing them, i.e. the fall of the magnet."),
    ("Magnetism and Electromagnetic Induction", "Medium", "The e.m.f. induced in a coil by a moving magnet can be increased by",
     "moving the magnet more slowly", "using a coil with more turns", "using a weaker magnet", "using a thicker coil wire only", "B",
     "By Faraday's law the induced e.m.f. is proportional to the number of turns and the rate of change of flux; a faster or stronger magnet also helps."),
    ("Magnetism and Electromagnetic Induction", "Easy", "The magnetic field lines around a long straight wire carrying a current are",
     "straight lines parallel to the wire", "concentric circles centred on the wire", "radial lines pointing away from the wire", "straight lines at right angles to the wire", "B",
     "The field forms closed circles round the wire, with the direction given by the right-hand grip rule."),
    ("Magnetism and Electromagnetic Induction", "Medium", "The angle between the direction of the Earth's magnetic field and the horizontal is called the",
     "angle of declination", "angle of dip (inclination)", "magnetic meridian", "angle of variation", "B",
     "A freely suspended magnetic needle dips below the horizontal by the angle of dip; declination is the angle between magnetic and geographic north."),
    ("Magnetism and Electromagnetic Induction", "Medium", "Soft iron rather than steel is used for the core of an electromagnet because soft iron",
     "retains its magnetism permanently", "is magnetised and demagnetised easily", "is a better conductor of electricity", "is heavier than steel", "B",
     "An electromagnet must switch on and off with the current; steel keeps its magnetism and is used for permanent magnets."),
    ("Magnetism and Electromagnetic Induction", "Easy", "Which of the following will NOT demagnetise a bar magnet?",
     "heating it strongly", "hammering it repeatedly", "placing it in a solenoid carrying alternating current and withdrawing it slowly", "storing it with keepers across its poles", "D",
     "Keepers preserve magnetism by completing the magnetic circuit; heat, mechanical shock and a.c. fields all disorder the magnetic domains."),
    ("Magnetism and Electromagnetic Induction", "Medium", "Two long parallel wires carry currents in the same direction. The wires",
     "attract each other", "repel each other", "experience no force", "rotate about each other", "A",
     "Each wire lies in the magnetic field of the other; for currents in the same direction the forces are attractive."),
    ("Magnetism and Electromagnetic Induction", "Medium", "A metal rod 0.5 m long moves at 4 m/s at right angles to a magnetic field of flux density 0.2 T. The e.m.f. induced across its ends is",
     "0.1 V", "0.4 V", "1.6 V", "4 V", "B",
     "E = BLv = 0.2 × 0.5 × 4 = 0.4 V.", "0.2*0.5*4"),
    ("Magnetism and Electromagnetic Induction", "Medium", "A simple a.c. generator differs from a d.c. generator in that the a.c. generator uses",
     "a split-ring commutator", "two slip rings", "a soft-iron armature", "a permanent magnet", "B",
     "Slip rings deliver the alternating output as it is; the split-ring commutator of a d.c. generator reverses the connections every half turn."),
    ("Magnetism and Electromagnetic Induction", "Medium", "A transformer takes 200 W from the mains and delivers 160 W to a load. Its efficiency is",
     "40%", "60%", "80%", "125%", "C",
     "Efficiency = output/input × 100 = 160/200 × 100 = 80%.", "160/200*100"),
    ("Magnetism and Electromagnetic Induction", "Medium", "Electrical energy is transmitted over long distances at very high voltage in order to",
     "make the current larger", "reduce the energy lost as heat in the cables", "speed up the electricity", "reduce the cost of the cables' insulation", "B",
     "For a given power, a higher voltage means a smaller current, and the I²R loss in the cables falls sharply."),
    ("Magnetism and Electromagnetic Induction", "Hard", "The magnet of a moving-coil galvanometer has curved pole pieces with a soft-iron cylinder between them in order to",
     "make the coil lighter", "produce a radial field so that the scale is linear", "increase the resistance of the coil", "prevent the coil from overheating", "B",
     "In a radial field the coil is always parallel to the field lines, so the deflecting torque is proportional to the current and the scale divisions are equal."),
    # ---------------- Atomic and Nuclear Physics ----------------
    ("Atomic and Nuclear Physics", "Medium", "The count rate of a radioactive source falls from 800 counts per minute to 100 counts per minute in 45 minutes. The half-life of the source is",
     "5 min", "15 min", "22.5 min", "45 min", "B",
     "800 → 400 → 200 → 100 is three half-lives, so one half-life = 45/3 = 15 minutes.", "45/3"),
    ("Atomic and Nuclear Physics", "Easy", "A radiation from a radioactive source is stopped by a sheet of paper. The radiation consists of",
     "alpha particles", "beta particles", "gamma rays", "X-rays", "A",
     "Alpha particles are the least penetrating; beta particles need a few millimetres of aluminium and gamma rays several centimetres of lead."),
    ("Atomic and Nuclear Physics", "Medium", "In the decay ²²⁶₈₈Ra → ²²²₈₆Rn + X, the particle X is",
     "a beta particle", "an alpha particle", "a neutron", "a gamma ray", "B",
     "The mass number falls by 4 and the atomic number by 2, the signature of an alpha particle (⁴₂He)."),
    ("Atomic and Nuclear Physics", "Medium", "When a nucleus emits a beta particle, a neutron inside the nucleus changes into",
     "a proton and an electron", "two protons", "a proton and an alpha particle", "an electron and a photon only", "A",
     "n → p + e⁻ (+ antineutrino); the electron is ejected as the beta particle and the atomic number rises by one."),
    ("Atomic and Nuclear Physics", "Medium", "The energy released in a nuclear reactor comes from the",
     "fusion of hydrogen nuclei", "fission of heavy nuclei such as uranium-235", "chemical burning of uranium", "radioactive decay of carbon-14", "B",
     "A neutron splits a U-235 nucleus into lighter fragments, releasing energy and more neutrons that sustain a chain reaction."),
    ("Atomic and Nuclear Physics", "Medium", "The energy equivalent of a mass of 1 g is (c = 3 × 10⁸ m/s)",
     "3 × 10⁵ J", "9 × 10¹³ J", "9 × 10¹⁶ J", "3 × 10¹¹ J", "B",
     "E = mc² = 10⁻³ × (3 × 10⁸)² = 9 × 10¹³ J.", "1e-3*(3e8)**2/1e13"),
    ("Atomic and Nuclear Physics", "Medium", "The mass of a helium nucleus is less than the total mass of its two protons and two neutrons. The difference is called the",
     "mass defect", "atomic mass", "binding energy", "mass number", "A",
     "The missing mass has been released as the binding energy that holds the nucleus together (E = Δmc²)."),
    ("Atomic and Nuclear Physics", "Easy", "The number of neutrons in the nucleus ²³⁵₉₂U is",
     "92", "143", "235", "327", "B",
     "Neutrons = mass number − atomic number = 235 − 92 = 143.", "235-92"),
    ("Atomic and Nuclear Physics", "Medium", "An electron in an atom falls from an energy level of −1.5 × 10⁻¹⁹ J to one of −6.45 × 10⁻¹⁹ J. Taking h = 6.6 × 10⁻³⁴ J s, the frequency of the photon emitted is",
     "7.5 × 10¹⁴ Hz", "2.3 × 10¹⁴ Hz", "9.8 × 10¹⁴ Hz", "7.5 × 10¹³ Hz", "A",
     "ΔE = 6.45 − 1.5 = 4.95 × 10⁻¹⁹ J; f = ΔE/h = 4.95 × 10⁻¹⁹/6.6 × 10⁻³⁴ = 7.5 × 10¹⁴ Hz.", "4.95e-19/6.6e-34/1e14"),
    ("Atomic and Nuclear Physics", "Easy", "The age of an ancient wooden object is estimated by measuring the activity of the isotope",
     "uranium-238", "carbon-14", "cobalt-60", "iodine-131", "B",
     "Living things take in carbon-14 while alive; after death it decays with a half-life of about 5,700 years, so the remaining fraction gives the age."),
    ("Atomic and Nuclear Physics", "Medium", "The rate of decay of a radioactive sample",
     "increases when the sample is heated", "is unaffected by temperature, pressure or chemical combination", "decreases when the sample is compressed", "depends on the chemical compound containing the nuclide", "B",
     "Radioactive decay is a spontaneous, random nuclear process that external physical or chemical conditions cannot alter."),
    ("Atomic and Nuclear Physics", "Medium", "A 16 g sample of a radioactive element is left for three half-lives. The mass of the element that remains is",
     "8 g", "4 g", "2 g", "0 g", "C",
     "16 → 8 → 4 → 2 g after three successive half-lives.", "16/8"),
    ("Atomic and Nuclear Physics", "Easy", "Which of the following detects radiation by the ionisation it produces in a gas?",
     "a thermometer", "a Geiger–Müller tube", "a photographic plate", "a barometer", "B",
     "Each ionising particle entering the tube triggers a pulse of current that is counted."),
    ("Atomic and Nuclear Physics", "Medium", "Radiation from ¹³¹I is used to treat thyroid disorders and ⁶⁰Co to treat cancers. These applications rely mainly on the radiation's ability to",
     "heat the tissue", "destroy or damage living cells", "make the tissue radioactive permanently", "reflect off bone", "B",
     "Ionising radiation kills cells; it is directed at the diseased tissue so that healthy tissue receives as little as possible."),
    ("Atomic and Nuclear Physics", "Medium", "In Rutherford's alpha-scattering experiment, the few alpha particles that were deflected through very large angles had passed",
     "through the electron cloud", "very close to the small, massive, positive nucleus", "through empty space", "along the surface of the foil", "B",
     "Only a concentrated positive charge could repel the fast, heavy alpha particles so strongly; most particles met only empty space."),
    # ---------------- Electronics and Modern Physics ----------------
    ("Electronics and Modern Physics", "Medium", "Photons of energy 5.0 eV strike a metal surface whose work function is 2.0 eV. The stopping potential needed to prevent the fastest photoelectrons from reaching the collector is",
     "2.0 V", "3.0 V", "5.0 V", "7.0 V", "B",
     "KE_max = hf − W = 5.0 − 2.0 = 3.0 eV, so a reverse p.d. of 3.0 V just stops the fastest electrons.", "5-2"),
    ("Electronics and Modern Physics", "Medium", "In the photoelectric effect, increasing the intensity of the incident light while keeping its frequency the same",
     "increases the maximum kinetic energy of the electrons", "increases the number of electrons emitted per second", "lowers the work function of the metal", "changes the threshold frequency", "B",
     "Each photon frees at most one electron; more photons per second mean more electrons, but each still receives the same energy hf."),
    ("Electronics and Modern Physics", "Medium", "The work function of a metal is 3.3 × 10⁻¹⁹ J. Taking h = 6.6 × 10⁻³⁴ J s, its threshold frequency is",
     "2 × 10¹⁴ Hz", "5 × 10¹⁴ Hz", "2 × 10¹⁵ Hz", "5 × 10¹⁵ Hz", "B",
     "f₀ = W/h = 3.3 × 10⁻¹⁹/6.6 × 10⁻³⁴ = 5 × 10¹⁴ Hz.", "3.3e-19/6.6e-34/1e14"),
    ("Electronics and Modern Physics", "Hard", "The de Broglie wavelength of an electron (mass 9.1 × 10⁻³¹ kg) moving at 1.0 × 10⁶ m/s is (h = 6.6 × 10⁻³⁴ J s)",
     "7.3 × 10⁻¹⁰ m", "7.3 × 10⁻⁷ m", "1.4 × 10⁻⁹ m", "6.0 × 10⁻²⁸ m", "A",
     "λ = h/mv = 6.6 × 10⁻³⁴/(9.1 × 10⁻³¹ × 10⁶) = 7.3 × 10⁻¹⁰ m.", "6.6e-34/(9.1e-31*1e6)/1e-10"),
    ("Electronics and Modern Physics", "Medium", "X-rays are produced in an X-ray tube when",
     "a heated filament glows", "fast-moving electrons are suddenly stopped by a metal target", "a radioactive source decays", "ultraviolet light strikes a metal", "B",
     "Electrons accelerated through a high voltage lose their kinetic energy on hitting the tungsten target and part of it is emitted as X-ray photons."),
    ("Electronics and Modern Physics", "Medium", "Pure silicon is doped with a small amount of phosphorus (a Group 5 element). The material produced is",
     "an insulator", "an n-type semiconductor", "a p-type semiconductor", "a superconductor", "B",
     "Each phosphorus atom supplies one extra electron that is free to move, so the majority carriers are negative electrons."),
    ("Electronics and Modern Physics", "Medium", "A p-n junction diode is forward biased when",
     "the p-side is connected to the positive terminal of the battery", "the n-side is connected to the positive terminal of the battery", "both sides are earthed", "no battery is connected", "A",
     "Forward bias narrows the depletion layer and lets current flow; reverse bias (p to negative) blocks it."),
    ("Electronics and Modern Physics", "Medium", "A single diode connected in series with a load across an a.c. supply produces",
     "a steady direct current", "half-wave rectified current", "full-wave rectified current", "an alternating current of doubled frequency", "B",
     "The diode conducts during one half of each cycle only; full-wave rectification needs a bridge of four diodes or two diodes with a centre-tapped transformer."),
    ("Electronics and Modern Physics", "Easy", "The three terminals of a junction transistor are the",
     "anode, cathode and grid", "emitter, base and collector", "source, gate and drain", "p-type, n-type and depletion layer", "B",
     "A small base current controls a much larger collector current, which is why the transistor can amplify."),
    ("Electronics and Modern Physics", "Medium", "Unlike a metal, the electrical conductivity of a pure semiconductor increases when it is heated because",
     "its atoms vibrate less", "more electrons gain enough energy to break free and act as charge carriers", "its resistance is unaffected by temperature", "the holes disappear", "B",
     "Thermal energy frees electron-hole pairs; in metals heating only increases lattice vibrations and hence resistance."),
    ("Electronics and Modern Physics", "Medium", "The output of a two-input AND gate is 1 only when",
     "either input is 1", "both inputs are 1", "both inputs are 0", "the inputs are different", "B",
     "The AND operation requires every input to be high; an OR gate gives 1 when either input is high."),
    ("Electronics and Modern Physics", "Medium", "A large capacitor is connected across the output of a rectifier in a d.c. power supply in order to",
     "increase the output frequency", "smooth the output by reducing the ripple", "convert d.c. back to a.c.", "step down the voltage", "B",
     "The capacitor charges at the peaks and discharges slowly between them, keeping the output voltage nearly constant."),
    ("Electronics and Modern Physics", "Easy", "The emission of electrons from a heated metal surface is called",
     "photoelectric emission", "thermionic emission", "field emission", "secondary emission", "B",
     "Heating gives the free electrons enough energy to escape; this is how the cathode of a cathode-ray tube produces its electron beam."),
    ("Electronics and Modern Physics", "Medium", "The photoelectric effect provides evidence for the",
     "wave nature of light", "particle nature of light", "wave nature of electrons", "existence of the nucleus", "B",
     "Electron emission depends on frequency, not intensity, which is explained only if light arrives in packets (photons) of energy hf."),
    ("Electronics and Modern Physics", "Medium", "The energy of a photon of light of wavelength 600 nm is (h = 6.6 × 10⁻³⁴ J s, c = 3 × 10⁸ m/s)",
     "3.3 × 10⁻¹⁹ J", "1.1 × 10⁻²⁷ J", "3.3 × 10⁻²⁸ J", "1.98 × 10⁻²⁵ J", "A",
     "E = hc/λ = 6.6 × 10⁻³⁴ × 3 × 10⁸/(600 × 10⁻⁹) = 3.3 × 10⁻¹⁹ J.", "6.6e-34*3e8/600e-9/1e-19"),
    ("Electronics and Modern Physics", "Easy", "A light-dependent resistor (LDR) is used in an automatic street-lighting circuit because its resistance",
     "increases as the light intensity increases", "decreases as the light intensity increases", "is independent of light", "becomes infinite in daylight", "B",
     "In the dark the LDR's high resistance switches the lamp on; in daylight its resistance falls and the lamp switches off."),
]

FIX = {
    "the terminal p.d. fell as the current increased because": ("the voltmeter drew a larger share of the current at higher readings", "more of the e.m.f. was dropped across the cell's own internal resistance", "the chemical e.m.f. of the cell fell steadily as the current rose", "the external resistor became hot and its resistance increased"),
    "timed 20 oscillations instead of one": ("make the pendulum swing faster and so save time in the laboratory", "reduce the effect of reaction-time error on the measured period", "increase the amplitude of the swing so that it is easier to count", "stop the string from stretching while the readings are being taken"),
    "too large for a measuring cylinder": ("measuring its length, breadth and height with a metre rule", "lowering it into a full displacement can and measuring the overflow", "weighing it on a beam balance and dividing by the density of water", "wrapping a tape measure round it and cubing the circumference"),
    "round a circular track at a constant speed": ("its velocity is constant because its speed is constant", "its velocity changes because its direction changes", "its acceleration is zero because its speed is constant", "no resultant force acts on it while it is on the track"),
    "several coplanar forces to be in equilibrium": ("only the resultant force on the body must be zero", "the resultant force and the resultant moment must both be zero", "only the resultant moment about any point must be zero", "all the forces must be equal in magnitude and parallel"),
    "efficiency of a practical machine": ("the load is always heavier than the effort applied to the machine", "some of the work input is wasted against friction and in lifting moving parts", "the velocity ratio of the machine is always less than one", "energy is destroyed inside the machine whenever it is used"),
    "mercury level in the tube is depressed": ("water is much less dense than mercury and so rises more easily", "water wets glass (adhesion > cohesion) while mercury does not", "mercury is a metal and metals are always repelled by glass", "the tube is too narrow for the heavy mercury to enter it"),
    "steel ball falling through glycerine": ("the weight of the ball has been reduced to zero by the liquid", "the weight equals the sum of the upthrust and the viscous drag", "the viscous drag on the ball has fallen to zero", "the upthrust on the ball alone balances its weight"),
    "breeze blows from the sea towards the land": ("the sea is warmer than the land during the day and heats the air", "the land warms faster, so air over it rises and cooler sea air flows in", "water evaporating from the sea expands and pushes the air inland", "the land is at a higher level than the sea, so air flows uphill"),
    "silvered walls and the vacuum": ("conduction, and convection and radiation", "radiation, and conduction and convection", "convection, and radiation and conduction", "evaporation, and radiation and conduction"),
    "coming out of a swimming pool": ("the water left on the skin is at a lower temperature than the air", "water evaporating from the skin takes its latent heat from the body", "moving air is always at a lower temperature than still air", "water on the skin conducts heat from the air into the body"),
    "Fish survive in a pond": ("ice is a good conductor of heat and keeps the water below warm", "water is densest at 4 °C, so this water sinks and only the top layer freezes", "fish generate enough heat of their own to keep the water liquid", "the ice at the surface melts from below as fast as it forms"),
    "round the corner of a building": ("travel faster than light waves through the air", "are diffracted round the corner more than light waves", "are reflected back by the walls of the building", "are longitudinal and so can pass through the bricks"),
    "from deep water into shallow water": ("frequency decreases while the speed and wavelength stay the same", "speed and wavelength decrease while the frequency stays the same", "speed increases while the wavelength and frequency decrease", "wavelength increases while the speed and frequency decrease"),
    "earth wire of a three-pin plug": ("the appliance draws less current from the mains supply", "a fault current flows safely to earth and blows the fuse instead of shocking the user", "the appliance heats up faster when it is switched on", "the current can return to the power station through the ground"),
    "lightning conductor on a tall building": ("charge concentrates at the point and leaks away, neutralising the cloud", "a sharp point attracts lightning far more strongly than a ball", "a point is much cheaper to manufacture than a metal sphere", "a sharp point melts more easily and so absorbs the strike"),
    "dropped down a vertical copper tube": ("copper is a magnetic metal and attracts the magnet as it falls", "induced currents in the tube produce a field that opposes the magnet's motion", "the air trapped in the tube slows the falling magnet down", "the magnet loses most of its weight inside the copper tube"),
    "Rutherford's alpha-scattering experiment": ("through the diffuse cloud of electrons round the atoms", "very close to the small, massive, positive nucleus", "through the empty space between the atoms of the foil", "along the surface of the foil without entering it"),
    "X-rays are produced in an X-ray tube when": ("a heated filament glows brightly inside the evacuated tube", "fast-moving electrons are suddenly stopped by a metal target", "a radioactive source inside the tube decays and emits radiation", "ultraviolet light strikes a metal plate and releases electrons"),
    "conductivity of a pure semiconductor increases": ("its atoms vibrate less and so obstruct the electrons less", "more electrons gain enough energy to break free and carry charge", "its resistance is completely unaffected by temperature", "the holes in its structure disappear when it is heated"),
}


def build():
    build_batch(
        S, "batch_015_physics_round3.json", "batch_015_physics_round3",
        "Physics round 3: four data passages (velocity-time table, cell readings, heating curve, pendulum data) and applied/calculation items across the JAMB syllabus.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
