"""Batch 046 - WAEC/NECO Biology, Paper 1 round 1.

WASSCE Biology Paper 1 is a 50-item objective paper (50 minutes).  This batch
covers the full SSCE syllabus: cell structure, cell division, nutrition,
transport, respiration, excretion, reproduction and growth, genetics, ecology,
diseases and immunity, nervous and hormonal coordination, support and movement,
and practical-style items (food tests, magnification, quadrat sampling).
Numeric answers (genetic ratios, energy transfer, sampling estimates,
magnification) carry independent `verify` computations.

    python3 scripts/build_content_batch46.py -> content/batch_046_waec_biology.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Biology"

T_CELL = "Cell Structure and Organisation"
T_CELLDIV = "Cell Division"
T_NUTR = "Nutrition in Plants and Animals"
T_TRANS = "Transport Systems"
T_RESP = "Respiration and Gaseous Exchange"
T_EXCR = "Excretion"
T_REPRO = "Reproduction and Growth"
T_GEN = "Genetics and Heredity"
T_ECO = "Ecology and Ecosystems"
T_DIS = "Diseases and Immunity"
T_NERV = "Nervous Coordination and Sense Organs"
T_HORM = "Hormones and Chemical Coordination"
T_SUP = "Support and Movement"
T_PRACT = "Biology Practical Skills"

PASSAGES = []
PQ = []

Q = [
    # ---------------------------------------------------------- cell structure
    (T_CELL, "Easy", "In which organelle does aerobic respiration mainly occur?",
     "Mitochondrion", "Ribosome", "Nucleus", "Vacuole", "A",
     "Aerobic respiration releases energy in the mitochondria, the powerhouse of the cell.", None),
    (T_CELL, "Easy", "Which organelle contains chlorophyll in a plant cell?",
     "Chloroplast", "Leucoplast", "Mitochondrion", "Lysosome", "A",
     "Chlorophyll, the green photosynthetic pigment, is found inside chloroplasts.", None),
    (T_CELL, "Easy", "The cellulose cell wall of a plant cell mainly",
     "gives the cell a definite shape", "controls what enters the cell", "stores cell sap", "makes food for the cell", "A",
     "The rigid cellulose wall provides support and a definite shape for plant cells.", None),
    (T_CELL, "Medium", "Which structure controls all the activities of a cell?",
     "Nucleus", "Cell membrane", "Cytoplasm", "Golgi body", "A",
     "The nucleus contains the genetic material and directs all cell activities.", None),
    (T_CELL, "Medium", "The cell membrane is described as selectively permeable because it",
     "allows only certain substances to pass through", "allows all substances to pass freely", "prevents all substances from entering", "is found only in plant cells", "A",
     "Selectively permeable means the membrane chooses which molecules pass through.", None),
    (T_CELL, "Medium", "Which organelle is the site of protein synthesis?",
     "Ribosome", "Chloroplast", "Vacuole", "Centrosome", "A",
     "Ribosomes assemble amino acids into proteins during translation.", None),
    (T_CELL, "Easy", "Which of these is found in a plant cell but NOT in an animal cell?",
     "Large permanent vacuole", "Nucleus", "Mitochondrion", "Cell membrane", "A",
     "Plant cells have a large permanent vacuole; animal cells have only small temporary ones.", None),
    (T_CELL, "Hard", "Lysosomes are sometimes called 'suicide bags' because they",
     "contain enzymes that digest worn-out organelles", "store food reserves for the cell", "produce energy for the cell", "trap sunlight for the cell", "A",
     "Lysosomes hold powerful digestive enzymes that can break down cell parts.", None),
    (T_CELL, "Easy", "Red blood cells lack a nucleus so that they",
     "can carry more haemoglobin", "can divide rapidly", "can move actively", "can live forever", "A",
     "Lacking a nucleus creates space for more haemoglobin to carry oxygen.", None),

    # ------------------------------------------------------------ cell division
    (T_CELLDIV, "Easy", "Mitosis produces daughter cells that are",
     "genetically identical to the parent cell", "haploid and different from the parent", "half the chromosome number", "gametes only", "A",
     "Mitosis copies the parent cell exactly, keeping the same diploid chromosome number.", None),
    (T_CELLDIV, "Easy", "Meiosis is important in sexual reproduction because it",
     "halves the chromosome number in gametes", "doubles the chromosome number", "produces identical body cells", "repairs worn-out tissues", "A",
     "Halving the chromosome number in gametes keeps the species number constant at fertilisation.", None),
    (T_CELLDIV, "Medium", "How many chromosomes are present in a normal human sperm cell?",
     "23", "46", "23 pairs", "44", "A",
     "A sperm is a gamete, so it carries half of the 46 chromosomes, which is 23.", "46//2"),
    (T_CELLDIV, "Medium", "A body cell of an organism contains 20 chromosomes. How many chromosomes will each gamete of that organism contain?",
     "10", "20", "40", "5", "A",
     "Gametes are haploid, so they carry half the body-cell number of 20, which is 10.", "20//2"),
    (T_CELLDIV, "Hard", "In a flowering plant, meiosis occurs in the",
     "anthers and ovules", "petals and sepals", "stem and roots", "fruits and seeds", "A",
     "Pollen mother cells in the anthers and ovule mother cells undergo meiosis to form gametes.", None),
    (T_CELLDIV, "Hard", "The division of the cytoplasm during cell division is called",
     "cytokinesis", "karyokinesis", "mitosis", "meiosis", "A",
     "Cytokinesis is cytoplasm division; karyokinesis is nuclear division.", None),

    # --------------------------------------------------------------- nutrition
    (T_NUTR, "Easy", "The raw materials for photosynthesis are",
     "carbon dioxide and water", "oxygen and water", "glucose and oxygen", "nitrogen and water", "A",
     "Plants use carbon dioxide and water, with light energy trapped by chlorophyll.", None),
    (T_NUTR, "Medium", "In an experiment, a destarched leaf is tested with iodine solution and turns blue-black. This shows that the leaf contains",
     "starch", "reducing sugar", "protein", "fat", "A",
     "Iodine solution turns blue-black in the presence of starch.", None),
    (T_NUTR, "Easy", "Which class of food is the body's main source of energy?",
     "Carbohydrates", "Proteins", "Vitamins", "Mineral salts", "A",
     "Carbohydrates are broken down to glucose, the chief fuel for respiration.", None),
    (T_NUTR, "Easy", "Proteins are needed in the diet mainly for",
     "growth and repair of body tissues", "instant energy release", "preventing scurvy", "carrying oxygen", "A",
     "Proteins supply amino acids for building new cells and repairing worn-out ones.", None),
    (T_NUTR, "Medium", "A child whose diet lacks vitamin D is likely to develop",
     "rickets", "scurvy", "night blindness", "beri-beri", "A",
     "Vitamin D and calcium are needed for strong bones; deficiency causes rickets.", None),
    (T_NUTR, "Medium", "Bleeding gums and poor wound healing are classic signs of a deficiency of",
     "vitamin C", "vitamin A", "iron", "calcium", "A",
     "Vitamin C deficiency weakens connective tissue, causing scurvy with bleeding gums.", None),
    (T_NUTR, "Medium", "Lack of iron in the diet can lead to",
     "anaemia", "goitre", "rickets", "kwashiorkor", "A",
     "Iron is part of haemoglobin, so a shortage reduces the oxygen-carrying capacity of blood.", None),
    (T_NUTR, "Easy", "The enzyme that digests starch in the mouth is",
     "salivary amylase", "pepsin", "lipase", "trypsin", "A",
     "Salivary amylase (ptyalin) breaks down cooked starch into maltose in the mouth.", None),
    (T_NUTR, "Medium", "Pepsin in the stomach works best in an environment that is",
     "strongly acidic", "strongly alkaline", "neutral", "slightly alkaline", "A",
     "Pepsin is a protein-digesting enzyme that works best in the stomach's acidic juice.", None),
    (T_NUTR, "Easy", "Fats are digested into",
     "fatty acids and glycerol", "glucose molecules", "amino acids", "peptones", "A",
     "Lipase breaks fats (oils) down into fatty acids and glycerol.", None),
    (T_NUTR, "Medium", "Most digested food is absorbed into the blood through the",
     "villi of the small intestine", "walls of the stomach", "large intestine", "oesophagus", "A",
     "The villi of the ileum give a huge surface area for absorption of nutrients.", None),
    (T_NUTR, "Medium", "Benedict's solution is used to test for the presence of",
     "reducing sugar", "starch", "protein", "lipids", "A",
     "On warming, Benedict's solution turns orange-red with a reducing sugar present.", None),
    (T_NUTR, "Hard", "The emulsion test for fats gives a",
     "cloudy white emulsion", "blue-black colour", "brick-red precipitate", "violet colour", "A",
     "Fat dissolved in ethanol forms a cloudy white emulsion when mixed with water.", None),
    (T_NUTR, "Medium", "The association between Rhizobium bacteria and leguminous plants is an example of",
     "mutualism", "parasitism", "commensalism", "saprophytism", "A",
     "Both partners benefit: the bacteria fix nitrogen and receive carbohydrates, which is mutualism.", None),
    (T_NUTR, "Easy", "An organism that feeds on dead and decaying matter is called a",
     "saprophyte", "parasite", "autotroph", "holozoic feeder", "A",
     "Saprophytes such as Rhizopus (bread mould) absorb nutrients from dead matter.", None),

    # ---------------------------------------------------------------- transport
    (T_TRANS, "Easy", "The xylem vessels of a plant transport",
     "water and mineral salts", "manufactured food", "sugars only", "hormones only", "A",
     "Xylem carries water and dissolved mineral salts upward from the roots.", None),
    (T_TRANS, "Easy", "Transpiration is the loss of water vapour from a plant mainly through the",
     "stomata", "lenticels", "root hairs", "xylem", "A",
     "Most water vapour escapes through the stomata of the leaves.", None),
    (T_TRANS, "Medium", "Translocation is the transport of",
     "manufactured food through the phloem", "water through the xylem", "mineral salts through the xylem", "gases through the stomata", "A",
     "Sugars made in the leaves are moved to other parts through the phloem.", None),
    (T_TRANS, "Easy", "The blood component that transports oxygen is",
     "haemoglobin in red blood cells", "plasma", "platelets", "white blood cells", "A",
     "Haemoglobin, the red pigment of red blood cells, combines reversibly with oxygen.", None),
    (T_TRANS, "Medium", "Which chamber of the human heart has the thickest muscular wall?",
     "Left ventricle", "Right ventricle", "Left atrium", "Right atrium", "A",
     "The left ventricle pumps blood around the whole body, so it needs the most muscle.", None),
    (T_TRANS, "Medium", "The pulmonary artery carries blood that is",
     "deoxygenated, from the heart to the lungs", "oxygenated, from the lungs to the heart", "oxygenated, from the heart to the body", "deoxygenated, from the body to the heart", "A",
     "It is the only artery carrying deoxygenated blood, taking it to the lungs.", None),
    (T_TRANS, "Easy", "Blood is prevented from flowing backwards in the heart by the",
     "valves", "septum", "coronary vessels", "pericardium", "A",
     "Valves like the bicuspid and tricuspid ensure one-way flow through the heart.", None),
    (T_TRANS, "Medium", "The wall of a capillary is one cell thick. This adaptation",
     "allows rapid exchange with the tissues", "prevents blood from escaping", "makes the blood flow faster", "stops platelets from clotting", "A",
     "A thin wall shortens the diffusion distance for oxygen, food and wastes.", None),
    (T_TRANS, "Medium", "A person with blood group O is called a universal donor because such blood",
     "has neither antigen A nor B on the red cells", "has both antigens A and B", "lacks antibodies in the plasma", "has no red blood cells", "A",
     "With no A or B antigens, group O red cells are not clumped by the recipient's antibodies.", None),
    (T_TRANS, "Hard", "Fibrinogen, prothrombin and platelets are all involved in",
     "blood clotting", "oxygen transport", "fighting infection", "maintaining osmotic balance", "A",
     "These factors interact in a cascade that forms a clot sealing wounds.", None),
    (T_TRANS, "Hard", "A farmer's crops wilt at midday even though the soil is moist. The most likely explanation is that",
     "transpiration exceeds water absorption", "photosynthesis has stopped", "respiration has stopped", "the root hairs are dead", "A",
     "When water loss from leaves is faster than uptake, cells lose turgor and the plant wilts.", None),
    (T_TRANS, "Easy", "In which blood vessel is blood pressure lowest?",
     "Vena cava", "Aorta", "Pulmonary artery", "Renal artery", "A",
     "Veins returning blood to the heart, like the vena cava, carry blood at the lowest pressure.", None),

    # ------------------------------------------------- respiration/gas exchange
    (T_RESP, "Easy", "The word equation for aerobic respiration is",
     "glucose + oxygen → carbon dioxide + water + energy", "glucose → lactic acid + energy", "carbon dioxide + water → glucose + oxygen", "glucose + water → starch + energy", "A",
     "Aerobic respiration uses oxygen to release energy from glucose completely.", None),
    (T_RESP, "Medium", "During vigorous exercise, human muscles may respire anaerobically, producing",
     "lactic acid", "alcohol", "carbon dioxide and water", "oxygen", "A",
     "Anaerobic respiration in muscle converts glucose to lactic acid with little energy.", None),
    (T_RESP, "Medium", "Anaerobic respiration in yeast is used in baking because it produces",
     "carbon dioxide that makes dough rise", "oxygen that makes dough rise", "lactic acid that makes dough rise", "alcohol that makes dough rise", "A",
     "Yeast fermentation releases carbon dioxide bubbles that raise the dough.", None),
    (T_RESP, "Easy", "The organ of gaseous exchange in a fish is the",
     "gill", "lung", "trachea", "skin", "A",
     "Fish take dissolved oxygen from water across their gill filaments.", None),
    (T_RESP, "Medium", "Which feature of the alveoli speeds up gaseous exchange?",
     "Thin, moist walls and a rich blood supply", "Thick, dry walls", "A small total surface area", "Cartilage rings around each alveolus", "A",
     "Thin moist walls, dense capillaries and a huge surface area all favour diffusion.", None),
    (T_RESP, "Medium", "Limewater turns milky when exhaled air is bubbled through it. This shows that exhaled air contains",
     "carbon dioxide", "oxygen", "nitrogen", "water vapour", "A",
     "Carbon dioxide reacts with limewater to form a milky precipitate of calcium carbonate.", None),
    (T_RESP, "Hard", "Insects exchange gases directly with their tissues through the",
     "tracheal system", "gills", "book lungs", "skin", "A",
     "Air reaches body tissues directly through spiracles and tracheae.", None),
    (T_RESP, "Hard", "Compared with inhaled air, exhaled air contains",
     "more carbon dioxide and less oxygen", "more oxygen and less carbon dioxide", "more nitrogen", "no water vapour", "A",
     "Respiration uses oxygen and releases carbon dioxide, so the proportions swap.", None),

    # ------------------------------------------------------------------ excretion
    (T_EXCR, "Easy", "The functional unit of the kidney is the",
     "nephron", "neuron", "alveolus", "glomerulus only", "A",
     "Each kidney contains about a million nephrons, its filtering units.", None),
    (T_EXCR, "Medium", "Ultrafiltration of blood takes place in the",
     "the glomerulus and Bowman's capsule", "the loop of Henle of the nephron", "the collecting duct system", "the renal artery", "A",
     "Blood is filtered under pressure from the glomerulus into the Bowman's capsule.", None),
    (T_EXCR, "Medium", "Selective reabsorption in the nephron returns useful substances such as",
     "glucose and some salts to the blood", "urea and salts to the blood", "glucose to the bladder", "proteins to the ureter", "A",
     "Glucose, amino acids, much salt and most water are reabsorbed into the blood.", None),
    (T_EXCR, "Easy", "Which organ converts excess amino acids into urea?",
     "Liver", "Kidney", "Pancreas", "Spleen", "A",
     "The liver deaminates excess amino acids, removing nitrogen as urea.", None),
    (T_EXCR, "Medium", "The hormone that controls the reabsorption of water in the kidney is",
     "antidiuretic hormone", "insulin", "adrenaline", "thyroxine", "A",
     "ADH from the pituitary makes the tubules reabsorb more water when the blood is concentrated.", None),
    (T_EXCR, "Medium", "A patient with kidney failure can have their blood cleaned artificially by",
     "dialysis", "transfusion", "electrontherapy", "photosynthesis", "A",
     "A dialysis machine filters waste from blood across a partially permeable membrane.", None),
    (T_EXCR, "Easy", "Which of these is NOT an excretory product in mammals?",
     "Carbon dioxide only", "Urea", "Sweat", "Faeces", "A",
     "Faeces is undigested food material, not a metabolic waste product of cells.", None),
    (T_EXCR, "Hard", "Which excretory product leaves flowering plants mainly through the stomata?",
     "Water vapour and oxygen", "Urea", "Ammonia", "Insulin", "A",
     "Plants lose water vapour (transpiration) and excess oxygen via the stomata.", None),

    # -------------------------------------------------------- reproduction/growth
    (T_REPRO, "Easy", "The male part of a flower is the",
     "stamen", "carpel", "corolla", "calyx", "A",
     "The stamen, made of anther and filament, produces pollen grains.", None),
    (T_REPRO, "Medium", "Pollination is the transfer of pollen grains from",
     "anther to stigma", "stigma to ovary", "anther to ovule", "stamen to petal", "A",
     "Pollination only delivers pollen to a stigma; fertilisation comes later.", None),
    (T_REPRO, "Medium", "Which feature is an adaptation of insect-pollinated flowers?",
     "Large brightly coloured petals and nectar", "Small dull petals with no scent", "Light, smooth pollen grains", "Feathery stigmas hanging outside the flower", "A",
     "Colour, scent and nectar attract insects; their pollen is sticky or spiky.", None),
    (T_REPRO, "Medium", "In flowering plants, fertilisation occurs when",
     "the male nucleus fuses with the egg cell in the ovule", "pollen lands on the stigma", "the pollen tube grows down the style", "the seed disperses", "A",
     "Fusion of gametes inside the ovule forms the zygote; the earlier steps only prepare it.", None),
    (T_REPRO, "Easy", "The part of the seed that develops into the shoot is the",
     "plumule", "radicle", "cotyledon", "testa", "A",
     "The plumule grows into the shoot system while the radicle forms the root.", None),
    (T_REPRO, "Medium", "In epigeal germination, as in the bean, the",
     "cotyledons are carried above the soil", "cotyledons remain below the soil", "plumule remains below the soil", "testa stays around the root", "A",
     "Epi- means above: the hypocotyl lifts the cotyledons above ground.", None),
    (T_REPRO, "Medium", "Germination of maize, where the cotyledons remain underground, is called",
     "hypogeal germination", "epigeal germination", "viviparous germination", "seed dormancy", "A",
     "Hypo- means below, so the cotyledons stay below the soil surface in maize.", None),
    (T_REPRO, "Easy", "The testes are located outside the abdominal cavity in the scrotum because",
     "sperm develop best below body temperature", "they need extra space to grow bigger", "they must stay close to the bladder", "sperm need light in order to develop", "A",
     "The slightly cooler scrotal temperature is needed for healthy sperm formation.", None),
    (T_REPRO, "Medium", "In the human female, fertilisation normally takes place in the",
     "oviduct", "uterus", "ovary", "vagina", "A",
     "Sperm meets the egg in the fallopian tube (oviduct) before the zygote travels to the uterus.", None),
    (T_REPRO, "Easy", "The placenta functions mainly to",
     "allow exchange of materials with the foetus", "protect the foetus from all diseases", "produce the eggs for the ovary", "store the baby's liquid wastes", "A",
     "The placenta is the exchange surface for nutrients, gases and wastes via the umbilical cord.", None),
    (T_REPRO, "Easy", "The amniotic fluid that surrounds a foetus mainly",
     "protects it from mechanical shock", "feeds the foetus with dissolved food", "removes urea from the foetus", "supplies oxygen to the foetal blood", "A",
     "The fluid acts as a shock absorber protecting the developing baby.", None),
    (T_REPRO, "Hard", "In a 28-day menstrual cycle, ovulation normally occurs around day",
     "14", "7", "1", "26", "A",
     "The egg is released from the ovary about midway, around day 14 of a 28-day cycle.", "28//2"),
    (T_REPRO, "Medium", "After ovulation, which hormone maintains the thickened lining of the uterus?",
     "Progesterone", "Adrenaline", "Insulin", "Oxytocin", "A",
     "Progesterone from the corpus luteum keeps the uterine lining ready for implantation.", None),
    (T_REPRO, "Hard", "A seed remains inactive even under suitable conditions until its dormancy is broken. Dormancy helps the plant by",
     "timing germination to a favourable season", "making the seed bigger than others", "doubling the food store of the seed", "preventing the pollination of flowers", "A",
     "Dormancy stops seeds from germinating when conditions for seedlings would be poor.", None),

    # ----------------------------------------------------------------- genetics
    (T_GEN, "Medium", "A tall heterozygous pea plant (Tt) is crossed with another Tt plant. What fraction of the offspring is expected to be tall?",
     "3/4", "1/4", "1/2", "All", "A",
     "The Punnett square gives TT, Tt, Tt and tt: three of four show the dominant tallness.", "3/4"),
    (T_GEN, "Medium", "When two heterozygous organisms are crossed, the expected phenotypic ratio for a single character is",
     "3 : 1", "1 : 1", "9 : 3 : 3 : 1", "1 : 2 : 1", "A",
     "Mendel's monohybrid result: three offspring show the dominant form to one recessive.", "3/1"),
    (T_GEN, "Hard", "In a dihybrid cross between two heterozygous plants (RrYy × RrYy), what fraction of the offspring shows both dominant phenotypes?",
     "9/16", "3/16", "1/16", "12/16", "A",
     "The classic dihybrid ratio is 9 : 3 : 3 : 1, so nine of sixteen show both dominants.", "9/16"),
    (T_GEN, "Easy", "The genetic make-up of an organism is its",
     "genotype", "phenotype", "allele", "gamete", "A",
     "Genotype is the allele combination; phenotype is what is seen outwardly.", None),
    (T_GEN, "Medium", "An organism with two identical alleles for a character is described as",
     "homozygous", "heterozygous", "haploid", "hybrid", "A",
     "Homo- means the same, as in TT or tt; heterozygous would be Tt.", None),
    (T_GEN, "Easy", "In humans, the sex of a child is determined by",
     "the chromosome carried by the father's sperm", "the mother's diet during pregnancy", "the chromosome in the mother's egg", "the temperature of the womb", "A",
     "The mother always gives an X; the child is XX (girl) or XY (boy) depending on the sperm.", None),
    (T_GEN, "Medium", "A couple are both carriers of sickle-cell anaemia (AS). What is the probability that a child of theirs has the disease (SS)?",
     "1/4", "1/2", "3/4", "None", "A",
     "AS × AS gives AA, AS, AS and SS: only one in four is SS.", "1/4"),
    (T_GEN, "Medium", "In a cross between a homozygous red-flowered plant (RR) and a homozygous white-flowered plant (rr), the F1 offspring will be",
     "all red and heterozygous", "all white and heterozygous", "half red, half white", "all red and homozygous", "A",
     "Every F1 plant is Rr, and R shows complete dominance over r.", None),
    (T_GEN, "Hard", "The two strands of a DNA molecule are held together by complementary base pairs in which adenine pairs with",
     "thymine", "guanine", "cytosine", "uracil", "A",
     "A pairs with T and C pairs with G in the DNA double helix.", None),
    (T_GEN, "Medium", "Which characteristic shows continuous variation in humans?",
     "Height", "Blood group", "Sex", "Sickle-cell trait", "A",
     "Height ranges smoothly between extremes, while blood group falls into distinct classes.", None),
    (T_GEN, "Hard", "A man with blood group AB marries a woman with blood group O. Which blood groups can their children have?",
     "A or B only", "AB or O", "A, B, AB or O", "O only", "A",
     "The father passes A or B and the mother passes O, so children are AO or BO only.", None),
    (T_GEN, "Hard", "Haemophilia is more common in males than females because",
     "males have only one X chromosome", "males have two Y chromosomes", "the gene is on the Y chromosome", "females cannot carry the allele", "A",
     "A single recessive allele on a male's only X chromosome shows up, with no second X to mask it.", None),
    (T_GEN, "Medium", "The observable appearance of an organism is called its",
     "phenotype", "genotype", "karyotype", "clone", "A",
     "Phenotype covers all visible traits, the result of genes plus environment.", None),

    # ------------------------------------------------------------------ ecology
    (T_ECO, "Easy", "All the organisms of different species living together and interacting in a habitat make up a",
     "community", "population", "ecosystem", "biosphere", "A",
     "A community is the collection of all populations in a habitat.", None),
    (T_ECO, "Easy", "Organisms that break down dead organic matter into simpler substances are",
     "decomposers", "producers", "primary consumers", "carnivores", "A",
     "Bacteria and fungi decompose dead matter and recycle nutrients.", None),
    (T_ECO, "Medium", "In the food chain grass → grasshopper → lizard → hawk, the grasshopper is a",
     "primary consumer", "producer", "secondary consumer", "decomposer", "A",
     "Grasshoppers eat plants, so they are primary (first-level) consumers.", None),
    (T_ECO, "Hard", "Green plants in an ecosystem trap 20,000 kJ of energy per square metre per year. About how much of this is available to the primary consumers?",
     "2,000 kJ", "10,000 kJ", "200 kJ", "20 kJ", "A",
     "Only about 10 per cent of the energy passes to each next trophic level.", "20000*0.1"),
    (T_ECO, "Medium", "The pyramid of energy is always broadest at the bottom because",
     "energy is lost at each trophic level", "producers are the largest organisms", "consumers eat little", "decomposers return energy to plants", "A",
     "Heat losses at every level mean less energy is available higher up.", None),
    (T_ECO, "Medium", "In the carbon cycle, carbon returns to the atmosphere mainly through",
     "respiration and combustion", "photosynthesis", "nitrogen fixation", "assimilation", "A",
     "Living things respire out CO2 and burning fuels releases it; photosynthesis removes it.", None),
    (T_ECO, "Hard", "Which group of bacteria converts atmospheric nitrogen into nitrates that plants can absorb?",
     "Nitrogen-fixing bacteria", "Denitrifying bacteria", "Putrefying bacteria", "Nitrifying bacteria only", "A",
     "Rhizobium and free-living fixers turn nitrogen gas into usable nitrogen compounds.", None),
    (T_ECO, "Hard", "Denitrifying bacteria in the soil",
     "change nitrates back into nitrogen gas", "change nitrogen gas into nitrates", "decompose proteins into ammonia", "absorb nitrates into roots", "A",
     "Denitrification returns nitrogen gas to the air, completing the cycle.", None),
    (T_ECO, "Medium", "A plant with thick succulent stems, spines instead of leaves and a thick waxy cuticle is best adapted to",
     "a dry desert habitat", "a freshwater pond", "a mangrove swamp", "a tropical rainforest floor", "A",
     "These are classic xerophytic features that reduce water loss.", None),
    (T_ECO, "Medium", "Mangrove trees in Nigerian coastal swamps have breathing roots (pneumatophores) that",
     "obtain oxygen from the air", "absorb salt for the plant", "store food for the plant", "anchor the tree in the mud", "A",
     "The exposed roots take in air for the submerged root system in oxygen-poor mud.", None),
    (T_ECO, "Hard", "Which relationship is illustrated by a tapeworm living in a human intestine?",
     "Parasitism", "Mutualism", "Commensalism", "Saprophytism", "A",
     "The tapeworm benefits while the host is harmed, which defines parasitism.", None),
    (T_ECO, "Medium", "The region of Nigeria with tall grasses, scattered drought-resistant trees and distinct wet and dry seasons is the",
     "savanna", "tropical rainforest", "mangrove swamp", "desert", "A",
     "The savanna belt has seasonal rainfall, grasses and scattered trees like shea and baobab.", None),
    (T_ECO, "Hard", "A student counts 250 organisms of a species in ten 1 m² quadrats thrown at random in a 1,000 m² field. The estimated total population of the species in the field is",
     "25,000", "2,500", "250,000", "1,000", "A",
     "The mean is 25 per quadrat, so 25 × 1,000 gives 25,000 organisms.", "250/10*1000"),
    (T_ECO, "Medium", "Which gas is mainly responsible for the enhanced greenhouse effect?",
     "Carbon dioxide", "Nitrogen", "Oxygen", "Argon", "A",
     "Excess carbon dioxide from burning fuels traps more heat in the atmosphere.", None),
    (T_ECO, "Hard", "Rain with a pH below about 5.6, caused mainly by sulphur dioxide pollution, is called",
     "acid rain", "greenhouse rain", "acid dew", "smog", "A",
     "Sulphur dioxide dissolves in rain to form acids; the fall in pH kills plants and fish.", None),
    (T_ECO, "Medium", "An organism's role in its community, including what it eats and where it lives, is its",
     "ecological niche", "habitat", "biome", "trophic level", "A",
     "The niche is the full way of life of the species, not just its address.", None),

    # ---------------------------------------------------------- diseases/immunity
    (T_DIS, "Easy", "The organism that causes malaria is transmitted by the bite of the",
     "female Anopheles mosquito", "male Culex mosquito", "tsetse fly", "housefly", "A",
     "The female Anopheles transmits the Plasmodium parasite.", None),
    (T_DIS, "Medium", "Cholera is spread mainly through",
     "contaminated food and water", "mosquito bites", "direct skin contact", "inhaling dust", "A",
     "The cholera bacterium spreads via faeces polluting drinking water and food.", None),
    (T_DIS, "Medium", "Immunity acquired when ready-made antibodies are injected is",
     "passive artificial immunity", "active natural immunity", "active artificial immunity", "passive natural immunity", "A",
     "The antibodies were made elsewhere and given by injection, so it is artificial and passive.", None),
    (T_DIS, "Easy", "Vaccination protects a person by stimulating the body to",
     "produce its own antibodies", "receive antibodies from another animal", "increase its red blood cells", "thicken the skin", "A",
     "A weakened pathogen triggers antibody production, giving active artificial immunity.", None),
    (T_DIS, "Hard", "The HIV virus weakens the immune system by attacking mainly the",
     "the white blood cells (helper T-cells)", "the red blood cells of the body", "the platelets in blood plasma", "the liver cells of the abdomen", "A",
     "HIV destroys helper T-cells, the coordinators of the immune response.", None),
    (T_DIS, "Medium", "Antibiotics are useful in treating",
     "bacterial infections only", "viral infections only", "all diseases", "malaria only", "A",
     "Antibiotics act on bacteria; viruses need antivirals or vaccines.", None),
    (T_DIS, "Medium", "An organism that carries and transmits a pathogen without suffering the disease is a",
     "vector", "host", "parasite", "carrier species", "A",
     "Vectors like the mosquito carry the pathogen from host to host.", None),
    (T_DIS, "Hard", "River blindness in West Africa is transmitted by the",
     "blackfly", "tsetse fly", "housefly", "sandfly", "A",
     "Simulium blackflies breeding in fast rivers transmit the worm causing river blindness.", None),

    # -------------------------------------------------- nervous coordination/senses
    (T_NERV, "Easy", "The central nervous system consists of the",
     "brain and spinal cord", "brain and nerves", "spinal cord and sense organs", "nerves and muscles", "A",
     "The CNS is made of the brain plus the spinal cord only.", None),
    (T_NERV, "Medium", "The gap across which an impulse passes from one neuron to the next is the",
     "synapse", "dendrite", "axon", "node", "A",
     "At the synapse a chemical transmitter carries the signal across the tiny gap.", None),
    (T_NERV, "Medium", "In a simple reflex arc, the correct pathway is",
     "receptor → sensory neuron → relay neuron → motor neuron → effector", "receptor → motor neuron → sensory neuron → effector", "effector → sensory neuron → relay neuron → receptor", "receptor → relay neuron → sensory neuron → effector", "A",
     "The message goes in via sensory neurons, is relayed in the spinal cord, then out via motor neurons.", None),
    (T_NERV, "Easy", "The part of the eye where light is focused to form an image is the",
     "retina", "cornea", "iris", "lens only", "A",
     "The lens focuses light onto the retina, which contains the photoreceptors.", None),
    (T_NERV, "Medium", "In bright light, the iris muscles make the pupil",
     "constrict to reduce light entering the eye", "dilate to admit even more light", "stay exactly the same size", "close up completely in protest", "A",
     "Circular muscles of the iris contract, making the pupil smaller in bright light.", None),
    (T_NERV, "Hard", "Accommodation of the eye for near objects involves the",
     "ciliary muscles contracting so the lens becomes more convex", "ciliary muscles relaxing so the lens flattens", "iris pushing the lens forward", "retina moving nearer the lens", "A",
     "For near vision the lens becomes fatter (more convex) to focus the image on the retina.", None),
    (T_NERV, "Medium", "Photoreceptors that work in dim light but do not detect colour are the",
     "rods", "cones", "fovea cells", "eyelid cells", "A",
     "Rods are sensitive in poor light; cones handle colour and detail in bright light.", None),
    (T_NERV, "Hard", "The region of the retina with no photoreceptors, where the optic nerve leaves the eye, is the",
     "blind spot", "yellow spot", "fovea", "cornea", "A",
     "No image can be detected where the optic nerve exits, hence the blind spot.", None),
    (T_NERV, "Medium", "In the mammalian ear, hearing occurs in the",
     "cochlea", "semi-circular canals", "ear ossicles", "Eustachian tube", "A",
     "The cochlea converts vibrations into nerve impulses heard by the brain.", None),
    (T_NERV, "Medium", "The semi-circular canals of the ear are concerned with",
     "body balance and posture", "hearing high-pitched sounds", "amplifying sound", "draining the ear", "A",
     "Fluid movement in these canals detects the position and motion of the head.", None),
    (T_NERV, "Hard", "The ear ossicles (hammer, anvil and stirrup) function to",
     "amplify vibrations passed to the inner ear", "equalise the air pressure in the ear", "produce the wax that traps dust", "detect the balance of the body", "A",
     "The three small bones relay and amplify vibrations from the eardrum to the oval window.", None),
    (T_NERV, "Hard", "A knee-jerk response is rapid because the pathway",
     "is completed in the spinal cord without the brain", "uses hormones carried in the blood", "passes directly through the muscles", "travels only through motor neurones", "A",
     "Reflex arcs are short spinal pathways, so the response is immediate and automatic.", None),

    # ------------------------------------------------------------------- hormones
    (T_HORM, "Easy", "Insulin lowers blood sugar level. The gland that produces it is the",
     "pancreas", "liver", "kidney", "pituitary", "A",
     "The islets of Langerhans in the pancreas secrete insulin.", None),
    (T_HORM, "Medium", "A person whose pancreas produces too little insulin is likely to suffer from",
     "diabetes mellitus", "goitre", "gigantism", "anaemia", "A",
     "Without enough insulin, glucose cannot enter cells, so blood sugar stays dangerously high.", None),
    (T_HORM, "Medium", "The hormone that prepares the body for an emergency, increasing heart rate and blood sugar, is",
     "adrenaline", "insulin", "thyroxine", "oestrogen", "A",
     "Adrenaline from the adrenal glands produces the fight-or-flight response.", None),
    (T_HORM, "Medium", "Lack of iodine in the diet causes goitre because iodine is needed to make",
     "thyroxine", "insulin", "adrenaline", "adrenaline only", "A",
     "The thyroid gland swells when it lacks the iodine needed for thyroxine production.", None),
    (T_HORM, "Easy", "The growth response of a plant shoot bending towards light is called",
     "phototropism", "geotropism", "hydrotropism", "thigmotropism", "A",
     "Photo- refers to light; shoots are positively phototropic.", None),
    (T_HORM, "Medium", "The plant hormone mainly responsible for cell elongation in shoots is",
     "auxin", "insulin", "adrenaline", "chlorophyll", "A",
     "Auxin produced at shoot tips promotes elongation of cells behind the tip.", None),
    (T_HORM, "Medium", "Roots grow downwards in response to gravity. This response is",
     "positive geotropism", "negative phototropism", "positive phototropism", "negative hydrotropism", "A",
     "Roots are positively geotropic, growing with the direction of gravity.", None),
    (T_HORM, "Hard", "Which statement correctly compares nervous and hormonal coordination?",
     "Nerve impulses are faster, hormones last longer", "Hormones act faster than nerve impulses", "Nerves affect only the glands", "Hormones travel along nerve fibres", "A",
     "Electrical nerve signals are rapid but brief; hormones are slower but give sustained effects.", None),

    # ---------------------------------------------------------- support/movement
    (T_SUP, "Easy", "The axial skeleton consists of the",
     "skull, vertebral column, ribs and sternum", "the limbs and their girdles", "the bones of the arms and the legs", "the pelvic and shoulder girdles", "A",
     "The axial skeleton forms the central axis of the body; limbs form the appendicular part.", None),
    (T_SUP, "Medium", "How many cervical vertebrae are there in the human vertebral column?",
     "7", "5", "12", "33", "A",
     "Humans have seven neck (cervical) vertebrae, twelve thoracic and five lumbar.", "7"),
    (T_SUP, "Medium", "The vertebrae to which the ribs are attached are the",
     "thoracic vertebrae", "cervical vertebrae", "lumbar vertebrae", "sacral vertebrae", "A",
     "The twelve thoracic vertebrae each carry a pair of ribs.", None),
    (T_SUP, "Easy", "The shoulder joint is an example of a",
     "ball and socket joint", "hinge joint", "pivot joint", "fixed joint", "A",
     "The rounded head of the humerus fits into the socket of the scapula.", None),
    (T_SUP, "Easy", "The elbow joint allows movement in one plane only. It is a",
     "hinge joint", "ball and socket joint", "gliding joint", "saddle joint", "A",
     "Like a door hinge, the elbow bends and straightens in one plane.", None),
    (T_SUP, "Medium", "Tough cords that connect muscles to bones are called",
     "tendons", "ligaments", "cartilage", "marrow", "A",
     "Tendons join muscle to bone; ligaments join bone to bone.", None),
    (T_SUP, "Medium", "Ligaments connect",
     "bone to bone", "muscle to bone", "bone to muscle", "nerve to muscle", "A",
     "Ligaments strap bones together at joints, keeping them stable.", None),
    (T_SUP, "Medium", "The biceps and triceps of the upper arm work as antagonistic muscles. This means that",
     "one contracts while the other relaxes to move the forearm", "both contract together to bend the arm", "both relax to bend the arm", "they work only during running", "A",
     "When the biceps bends the arm the triceps relaxes, and the reverse straightens it.", None),
    (T_SUP, "Hard", "The cartilage found at the surface of bones in a joint functions to",
     "reduce friction and absorb shock", "produce red blood cells", "store fat", "connect muscles to bones", "A",
     "Smooth cartilage lets joint surfaces glide and cushions impacts.", None),
    (T_SUP, "Hard", "Red blood cells are produced in the",
     "bone marrow", "cartilage", "liver", "spleen only", "A",
     "The marrow of long bones is the main factory for red blood cells.", None),

    # ------------------------------------------------------- practical skills
    (T_PRACT, "Medium", "A student draws a cell 40 mm long. If the cell's actual length is 0.2 mm, the magnification of the drawing is",
     "×200", "×20", "×2,000", "×40", "A",
     "Magnification = drawing size ÷ actual size = 40 ÷ 0.2 = 200.", "40/0.2"),
    (T_PRACT, "Hard", "A cell measured 0.05 mm across. Under a microscope magnification of ×400, the image the student sees will measure",
     "20 mm", "8 mm", "2 mm", "40 mm", "A",
     "Image size = magnification × actual size = 400 × 0.05 = 20 mm.", "400*0.05"),
    (T_PRACT, "Easy", "To test a leaf for starch, the leaf is first boiled in alcohol to",
     "remove the chlorophyll", "kill bacteria on the leaf", "soften the cell walls", "add iodine to the leaf", "A",
     "Decolourising in hot alcohol removes the green pigment so the iodine colour can show.", None),
    (T_PRACT, "Medium", "When testing a food sample with Benedict's solution, the mixture must be",
     "warmed in a water bath", "frozen", "dried in an oven", "shaken with acid", "A",
     "The orange-red colour of a positive result appears only on warming.", None),
    (T_PRACT, "Medium", "In a food test, a violet colour with NaOH and CuSO₄ (Biuret test) indicates the presence of",
     "protein", "reducing sugar", "starch", "fat", "A",
     "The Biuret reagent turns violet in the presence of protein.", None),
    (T_PRACT, "Hard", "A quadrat is most useful for estimating",
     "the population of a species in a habitat", "the age of a tree in the forest", "the rate of photosynthesis of leaves", "the pH of a soil sample in the lab", "A",
     "Quadrat counts, repeated randomly, give a mean used to estimate whole-area populations.", None),
    (T_PRACT, "Easy", "The instrument used to observe cells in the laboratory is the",
     "microscope", "periscope", "telescope", "barometer", "A",
     "Light microscopes magnify thin specimens like cell slides.", None),
]

if __name__ == "__main__":
    build_batch(
        S,
        "batch_046_waec_biology.json",
        "batch_046_waec_biology",
        "WAEC/NECO Biology Paper 1, round 1: full SSCE syllabus coverage - cells, "
        "nutrition, transport, respiration, excretion, reproduction, genetics, ecology, "
        "diseases, coordination, support/movement and practical skills. Numeric answers "
        "(genetic ratios, energy flow, quadrats, magnification) machine-verified.",
        PASSAGES,
        PQ,
        Q,
        exam_type="WAEC",
    )
