"""Batch 025 - Christian Religious Studies round 3, part A (Old Testament themes).

Sovereignty of God, covenant, leadership, providence, parental responsibility, obedience, David,
decision-making, greed, supremacy of God, reforms in Judah, Nehemiah, faith and courage, Jonah,
social justice (Amos, Hosea), holiness and call (Isaiah, Jeremiah, Ezekiel), punishment and hope.
Scripture-based and application (scenario) items in the JAMB style.

    python3 scripts/build_content_batch25.py -> content/batch_025_crs_round3a.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Christian Religious Studies"

T_SOV = "The Sovereignty of God"
T_COV = "The Covenant"
T_LEAD = "Leadership Qualities"
T_PROV = "Divine Providence, Guidance and Protection"
T_PAR = "Parental Responsibility"
T_OBEY = "Obedience and Disobedience"
T_DAV = "A Man after God's Own Heart"
T_DEC = "Decision-Making"
T_GREED = "Greed and Its Effects"
T_SUP = "The Supremacy of God"
T_REF = "Religious Reforms in Judah"
T_NEH = "Concern for Judah"
T_FAITH = "Faith, Courage and Protection"
T_JON = "God's Message to Nineveh"
T_JUST = "Social Justice, True Religion and Divine Love"
T_HOLY = "Holiness and Divine Call"
T_HOPE = "Punishment and Hope"

PASSAGES = []
PQ = []

Q = [
    # ---------------- The Sovereignty of God ----------------
    (T_SOV, "Medium", "Genesis 1 records that God gave man dominion over the fish, the birds and every living thing. A farmer who deliberately poisons a stream to kill all the fish for a quick harvest is",
     "abusing that dominion, forgetting that man is a steward who is answerable to the Creator",
     "exercising the dominion properly, since the fish were created for man to use as he pleases",
     "fulfilling the command to be fruitful and multiply by increasing his household's food supply",
     "acting within his rights, because dominion means unlimited control over every living creature",
     "A", "Dominion in Genesis 1:26-28 is delegated authority under God, so man must care for creation as a steward, not destroy it."),
    (T_SOV, "Medium", "In Isaiah 45, God calls Cyrus, a Persian king who did not know Him, 'my anointed' and uses him to release the exiles. This shows that",
     "God's sovereignty extends even over rulers who do not acknowledge Him",
     "Cyrus had secretly converted to the worship of the God of Israel before his conquest",
     "God works only through leaders who belong to His covenant people",
     "the Persian empire was more righteous than the kingdom of Judah had been",
     "A", "Isaiah 45:1-6 stresses that God raised up Cyrus 'though you do not know me', proving that He rules all nations and their kings."),
    (T_SOV, "Hard", "Isaiah 45:9 asks, 'Does the clay say to him who fashions it, What are you making?' A church member who insists that God must explain why her business failed before she will keep serving Him is",
     "questioning the Creator's purposes in the very way the prophet warned against",
     "showing the honest faith that Isaiah encouraged among the exiles in Babylon",
     "following the example of Cyrus, who demanded signs from God before acting",
     "acting as the potter rather than the clay, exactly as Isaiah recommended",
     "A", "The potter-and-clay image in Isaiah 45:9-12 teaches that the creature has no right to demand explanations from its Maker."),
    (T_SOV, "Medium", "Psalm 19 says the heavens declare the glory of God, yet 'there is no speech, nor are there words'. The psalmist's point is that",
     "creation bears silent but universal witness to the glory of its Creator",
     "the sun and the stars should be honoured as gods because of their splendour",
     "God can be known only by scholars who study the movements of the stars",
     "the written law is unnecessary because nature teaches everything about God",
     "A", "Psalm 19:1-4 teaches that the created order proclaims God's glory to all people everywhere without using words; verses 7-11 then praise the law."),
    (T_SOV, "Easy", "In Genesis 1 God said, 'Let there be light,' and there was light. This manner of creation shows that",
     "God's word alone has the power to bring things into existence",
     "God needed pre-existing light before He could create anything else",
     "creation was a long struggle between God and the powers of darkness",
     "light was produced by the sun and the moon on the first day",
     "A", "Creation by divine command (Genesis 1:3, 6, 9) reveals God's absolute sovereignty: He speaks and it is done, without effort or opposition."),
    (T_SOV, "Medium", "God commanded Adam not to eat of the tree of the knowledge of good and evil, 'for in the day that you eat of it you shall die'. This shows that",
     "God alone has the right to set limits for man, who is accountable to Him",
     "the fruit of the tree was poisonous and God was protecting Adam's health",
     "man was created without any freedom to choose between good and evil",
     "God did not want man to gain knowledge of any kind in the garden",
     "A", "Genesis 2:16-17 presents God as the sovereign Lord who sets the boundaries of human freedom and holds man responsible for keeping them."),
    (T_SOV, "Medium", "Genesis 2:7 says God formed man of dust from the ground and breathed into his nostrils the breath of life. This teaches that",
     "human life is a gift that depends entirely on God",
     "man is made of the same material as the animals and is no different from them",
     "the human body is evil because it was made from the dust of the ground",
     "man became a living being through his own effort and intelligence",
     "A", "Man became 'a living being' only when God breathed life into him, so life belongs to God and is held in dependence on Him."),
    (T_SOV, "Hard", "Isaiah 45:7 says, 'I form light and create darkness, I make weal and create woe; I am the LORD, who do all these things.' A student who claims that God controls only pleasant events is corrected by this verse, which shows that",
     "nothing happens outside God's control, whether prosperity or calamity",
     "God is personally responsible for the evil deeds committed by human beings",
     "there are two gods, one who sends good things and another who sends evil",
     "calamity comes only from the devil while prosperity alone comes from God",
     "A", "Isaiah 45:7 was addressed to Persians who believed in rival gods of light and darkness; the LORD alone rules over all events."),

    # ---------------- The Covenant ----------------
    (T_COV, "Medium", "God's covenant with Noah differed from the one with Abraham in that it",
     "was made with every living creature on earth and required nothing of man",
     "was sealed with the sign of circumcision on the eighth day after birth",
     "promised a land and a great nation to one particular family",
     "was conditional on the building of an altar every year at Shechem",
     "A", "Genesis 9:8-17: the Noahic covenant embraces all flesh and is an unconditional promise never again to destroy the earth by flood."),
    (T_COV, "Hard", "In Genesis 15 God passed between the pieces of the sacrificed animals as a smoking fire pot and a flaming torch while Abram slept. This signified that",
     "God alone bound Himself to fulfil the covenant promises",
     "Abram had to walk through fire before he could receive the promise",
     "the animals were unacceptable and had to be burnt up completely",
     "God rejected Abram's offering because he had fallen asleep",
     "A", "In ancient covenants both parties passed between the pieces; here only God passed, showing that the promise rested on God's faithfulness alone."),
    (T_COV, "Medium", "When God changed Abram's name to Abraham and Sarai's to Sarah in Genesis 17, the change signified",
     "a new identity tied to the promise of many nations and descendants",
     "that Abram had been adopted into the royal family of Egypt",
     "the transfer of the promise from Sarah to Hagar and Ishmael",
     "a punishment for Abram's earlier lie about Sarai in Egypt",
     "A", "Abraham means 'father of a multitude'; the new names marked the couple as bearers of God's promise of nations and kings."),
    (T_COV, "Medium", "At Sinai God said, 'If you will obey my voice and keep my covenant, you shall be my own possession among all peoples... a kingdom of priests and a holy nation.' This shows that",
     "Israel's privileged position depended on obedience to God's voice",
     "Israel was chosen because it was already holier than the other nations",
     "only the tribe of Levi was included in the covenant made at Sinai",
     "God had abandoned His earlier promises to Abraham and his descendants",
     "A", "Exodus 19:5-6 links the blessings of election to the condition 'if you will obey my voice and keep my covenant'."),
    (T_COV, "Medium", "A new church member signs a membership pledge and within weeks breaks every promise in it. His behaviour resembles that of the Israelites who",
     "promised at Sinai to obey all God's words and soon afterwards made a golden calf",
     "refused to accept the covenant until Moses had come down from the mountain",
     "asked Aaron to read the book of the covenant to them a second time",
     "kept the covenant faithfully throughout the forty years in the wilderness",
     "A", "In Exodus 24:3-8 the people said 'All that the LORD has spoken we will do'; in Exodus 32 they worshipped the golden calf."),
    (T_COV, "Medium", "A believer says she keeps God's commands not because a list hangs on the wall but because the desire to obey has been planted inside her. Her experience illustrates the covenant Jeremiah foretold, which differs from the Sinai covenant in that",
     "the law is written on the heart and every member knows the LORD personally",
     "it applies only to the priests and Levites who serve in the temple",
     "it must be renewed every seven years by a public reading of the law",
     "it replaces the commandments with the customs of the surrounding nations",
     "A", "Jeremiah 31:31-34: 'I will write it upon their hearts... they shall all know me, from the least of them to the greatest'."),
    (T_COV, "Medium", "A feature common to the covenants with Noah, Abraham and Israel at Sinai is that",
     "God took the initiative in establishing each covenant",
     "each was sealed by the sprinkling of blood on the people",
     "each was made after the people had first kept the law perfectly",
     "each had the rainbow in the clouds as its sign",
     "A", "In every case God Himself established the covenant (Genesis 9:9; 17:2; Exodus 19:3-6); the signs and terms differed."),
    (T_COV, "Medium", "In Genesis 17 an uncircumcised male was to be 'cut off from his people' because",
     "he had broken God's covenant by rejecting its sign",
     "circumcision was required for good health in the desert",
     "uncircumcised men were not allowed to fight in Abraham's army",
     "he would be unable to inherit any land in the country of Egypt",
     "A", "Genesis 17:14 states that the uncircumcised male 'has broken my covenant'; the sign was an essential mark of belonging."),
    (T_COV, "Medium", "Deuteronomy 28 sets out blessings for obedience and curses for disobedience. This shows that the covenant at Sinai",
     "made Israel's prosperity in the land dependent on faithfulness to God",
     "guaranteed Israel's prosperity no matter how the people behaved",
     "applied only to the generation that stood at the foot of the mountain",
     "was concerned with worship alone and not with everyday conduct",
     "A", "The blessings and curses of Deuteronomy 28 tie national welfare to covenant loyalty; the later exile is explained by these curses."),

    # ---------------- Leadership Qualities ----------------
    (T_LEAD, "Medium", "When Pharaoh said he had heard that Joseph could interpret dreams, Joseph replied, 'It is not in me; God will give Pharaoh a favourable answer.' This shows the leadership quality of",
     "humility that acknowledges God as the source of one's ability",
     "cleverness in avoiding blame if the interpretation should fail",
     "fear of Pharaoh, which made him deny that he had any gift",
     "pride disguised as a false show of modesty before the king",
     "A", "Genesis 41:16: Joseph pointed away from himself to God, a mark of humble leadership that later earned him Pharaoh's trust."),
    (T_LEAD, "Medium", "A school principal sets aside part of each term's fees to repair classrooms during the rainy season. She is applying the quality Joseph showed when he",
     "advised Pharaoh to store grain during the seven years of plenty",
     "refused to eat at the same table with his brothers in Egypt",
     "hid his silver cup in the sack of grain belonging to Benjamin",
     "interpreted the dreams of the butler and the baker in prison",
     "A", "Genesis 41:33-36: Joseph's foresight and planning during plenty saved Egypt and the surrounding nations during the famine."),
    (T_LEAD, "Medium", "At the burning bush Moses objected, 'Who am I that I should go to Pharaoh?' and later, 'I am slow of speech.' God's response was to",
     "promise His presence and appoint Aaron as his spokesman",
     "choose Joshua in his place because of his unbelief",
     "strike him dumb until the day he arrived in Egypt",
     "send him back to Jethro to tend the flock for another forty years",
     "A", "Exodus 3:12 ('I will be with you') and 4:14-16 (Aaron to speak for him) show God equipping a reluctant leader."),
    (T_LEAD, "Hard", "After the golden calf incident Moses prayed, 'If thou wilt forgive their sin - and if not, blot me, I pray thee, out of thy book.' This reveals",
     "selfless intercession for the people he led",
     "a desire to be released from the burden of leadership",
     "anger at God for choosing such a stubborn people",
     "fear that God would punish him for Aaron's failure",
     "A", "Exodus 32:30-32: Moses was ready to lose his own place for the people's sake, a mark of shepherd-like leadership."),
    (T_LEAD, "Medium", "Barak insisted that Deborah accompany him to battle against Sisera. Deborah agreed but told him that",
     "the honour of the victory would go to a woman",
     "God had rejected him and chosen Gideon instead",
     "the battle would be postponed until the rains ended",
     "Sisera would escape and rule Israel for forty years",
     "A", "Judges 4:8-9: because of Barak's hesitation, Sisera was killed by Jael, the wife of Heber, and the glory went to her."),
    (T_LEAD, "Medium", "God told Joshua, 'This book of the law shall not depart out of your mouth, but you shall meditate on it day and night... for then you shall make your way prosperous.' Joshua's success as a leader was therefore tied to",
     "constant meditation on and obedience to God's law",
     "the size of the army he had inherited from Moses",
     "his skill in negotiating treaties with the Canaanites",
     "the wealth the people had brought out of Egypt",
     "A", "Joshua 1:7-9 makes courage and success depend on faithfulness to the law of Moses rather than on military strength."),
    (T_LEAD, "Medium", "A head prefect refuses to cheat in examinations while urging the junior students to be honest. He is following the example of Joshua when he",
     "declared at Shechem, 'As for me and my house, we will serve the LORD'",
     "sent two spies secretly to view the land and the city of Jericho",
     "commanded the sun to stand still over Gibeon during the battle",
     "made a treaty of peace with the deceitful men of Gibeon",
     "A", "Joshua 24:15: Joshua led by personal example, committing himself and his household before asking the people to choose."),
    (T_LEAD, "Medium", "When Miriam and Aaron spoke against Moses because of his Cushite wife, and Miriam was struck with leprosy, Moses",
     "cried to the LORD to heal her",
     "demanded that she be stoned outside the camp",
     "removed Aaron from the priesthood as punishment",
     "left the camp and refused to lead the people any further",
     "A", "Numbers 12:13: 'Heal her, O God, I beseech thee.' Moses' meekness and readiness to pray for those who opposed him mark true leadership."),
    (T_LEAD, "Easy", "Which quality did Joseph display when he revealed himself to his brothers and settled them in the land of Goshen?",
     "forgiveness and generosity towards those who had wronged him",
     "cunning in luring them to Egypt so that he could enslave them",
     "favouritism toward Benjamin at the expense of the other brothers",
     "reluctance to let his father Jacob know that he was still alive",
     "A", "Genesis 45:4-15 and 47:11-12: Joseph forgave, comforted and settled his brothers in the best part of the land."),

    # ---------------- Divine Providence, Guidance and Protection ----------------
    (T_PROV, "Medium", "Abraham's servant prayed at the well that the girl who offered water to him and his camels would be the one chosen for Isaac; before he had finished praying, Rebekah came and did so. This shows that",
     "God guides those who seek His direction in specific decisions",
     "Rebekah had been told in advance what the servant would ask",
     "the servant chose Rebekah because she was the most beautiful girl",
     "Abraham had arranged the marriage with Laban many years earlier",
     "A", "Genesis 24:12-27: the servant sought God's guidance in prayer and God directed him to Rebekah; he then worshipped the LORD."),
    (T_PROV, "Easy", "Abraham named the place on Mount Moriah 'The LORD will provide' because",
     "God provided a ram caught in a thicket in place of Isaac",
     "God gave him water when he and Isaac were dying of thirst",
     "an angel brought bread and meat for the journey home",
     "God provided a wife for Isaac at that mountain",
     "A", "Genesis 22:13-14: Abraham offered the ram instead of his son and called the place Jehovah-jireh, 'the LORD will provide'."),
    (T_PROV, "Medium", "When Jacob dreamt of a ladder reaching to heaven at Bethel and heard God say, 'I am with you and will keep you wherever you go,' he was",
     "a fugitive fleeing from his brother Esau's anger",
     "returning home as a wealthy man with two wives",
     "a prisoner being taken down to Egypt by traders",
     "leading the tribes of Israel into the land of Canaan",
     "A", "Genesis 28:10-15: God's promise of protection came to Jacob when he was alone and running from Esau after deceiving Isaac."),
    (T_PROV, "Medium", "In the wilderness those who gathered much manna had nothing over and those who gathered little had no lack, but manna kept overnight bred worms. The lesson was",
     "daily dependence on God and obedience to His instructions",
     "that the strong should gather for the weak in the camp",
     "that food should be stored for the future whenever possible",
     "that manna could be eaten only by the priests and Levites",
     "A", "Exodus 16:16-20: God supplied enough for each day and tested whether the people would trust Him and keep His commands."),
    (T_PROV, "Medium", "A student who has paid this term's fees is already anxious about next year's fees. The story of the manna reminds him that",
     "God provides for each day and asks for trust rather than anxiety",
     "God provides only for those who have first saved up for themselves",
     "he should collect money from his classmates to be on the safe side",
     "God's provision for His people ended when Israel entered Canaan",
     "A", "The daily manna (Exodus 16) taught Israel to rely on God one day at a time; hoarding out of anxiety was met with rot and worms."),
    (T_PROV, "Medium", "At the Red Sea, with Pharaoh's army behind and the sea in front, Moses told the people, 'Fear not, stand firm, and see the salvation of the LORD.' This shows that",
     "God protects His people even when there is no human way of escape",
     "the people should have surrendered to Pharaoh peacefully",
     "Moses intended to fight the Egyptian army with the men of Israel",
     "God expected the Israelites to swim across the sea by night",
     "A", "Exodus 14:13-14: 'The LORD will fight for you, and you have only to be still'; the sea was divided for them to cross."),
    (T_PROV, "Hard", "Moses told Israel that God fed them with manna 'that he might make you know that man does not live by bread alone, but by every word that proceeds out of the mouth of the LORD'. The wilderness experience was meant to",
     "humble Israel and teach the people to depend on God's word",
     "punish Israel for the sin of the golden calf at Sinai",
     "prove that manna was more nourishing than ordinary bread",
     "keep the people from ever farming in the land of Canaan",
     "A", "Deuteronomy 8:2-3: God humbled Israel and tested them so that they would learn to depend on Him and His word."),
    (T_PROV, "Medium", "A woman who lost her job says, 'God allowed it, because the new job I found is far better.' Her attitude reflects Joseph's when he told his brothers,",
     "'God sent me before you to preserve life.'",
     "'You shall not see my face unless your brother is with you.'",
     "'By this you shall be tested: you shall not go from this place.'",
     "'Go up in peace to your father, and take your brother with you.'",
     "A", "Genesis 45:5-8 and 50:20: Joseph saw God's providence behind his brothers' evil act, turning it to the saving of many lives."),
    (T_PROV, "Medium", "At Rephidim the place was named Massah and Meribah because",
     "the people tested the LORD, asking whether He was among them or not",
     "the Amalekites were defeated there while Moses held up his hands",
     "Jethro visited Moses there and advised him to appoint judges",
     "the Israelites received the Ten Commandments at that spot",
     "A", "Exodus 17:7: Massah means 'testing' and Meribah 'contention'; the people quarrelled with Moses and doubted God's presence."),

    # ---------------- Parental Responsibility ----------------
    (T_PAR, "Medium", "Eli's sons took the best of the sacrificial meat by force and lay with the women who served at the tent of meeting. Eli's response was",
     "a mild verbal rebuke that he never backed with discipline",
     "to remove them immediately from the priesthood at Shiloh",
     "to hand them over to Samuel for judgment",
     "to bring them before the elders of Shiloh for stoning",
     "A", "1 Samuel 2:22-25: Eli only asked 'Why do you do such things?' and his sons ignored him; God said he honoured his sons above God."),
    (T_PAR, "Medium", "A father knows that his son steals from the neighbours but says, 'Boys will be boys,' and does nothing. He is repeating the failure of",
     "Eli, who did not restrain his sons from their evil ways",
     "Jacob, who loved Joseph more than all his other sons",
     "Abraham, who sent Ishmael away into the wilderness",
     "Jesse, who did not present David to Samuel at first",
     "A", "1 Samuel 3:13: God judged Eli's house 'because his sons were blaspheming God, and he did not restrain them'."),
    (T_PAR, "Medium", "The message given to the boy Samuel at Shiloh was that",
     "Eli's house would be punished for ever for the iniquity he knew of and did not restrain",
     "Samuel would become the first king of Israel in the place of Eli",
     "the Philistines would be defeated and never trouble Israel again",
     "Eli's sons would be forgiven if they offered a sin offering",
     "A", "1 Samuel 3:11-14: God confirmed to Samuel the judgment already announced on Eli's family."),
    (T_PAR, "Medium", "Phinehas' wife named her son Ichabod, saying, 'The glory has departed from Israel,' because",
     "the ark of God had been captured and her husband and Eli were dead",
     "Samuel had refused to succeed Eli as priest at Shiloh",
     "the temple in Jerusalem had been destroyed by the Babylonians",
     "the Philistines had carried away the tablets of the law",
     "A", "1 Samuel 4:19-22: the capture of the ark, together with the deaths of Eli and his sons, marked the departure of God's glory."),
    (T_PAR, "Medium", "After Amnon raped his half-sister Tamar, David 'was very angry' but took no action. The result was that",
     "Absalom nursed his hatred and murdered Amnon two years later",
     "Amnon repented and married Tamar according to the law",
     "Tamar was sent to live with her grandmother in Bethlehem",
     "Joab arrested Amnon and brought him before the elders",
     "A", "2 Samuel 13:21-29: David's failure to discipline Amnon allowed Absalom's revenge and set off further tragedy in the family."),
    (T_PAR, "Hard", "When David wept, 'O my son Absalom, would I had died instead of you,' Joab rebuked him because",
     "his mourning shamed the soldiers who had risked their lives for him",
     "Absalom had always been David's least favourite son",
     "David had personally ordered that Absalom be killed",
     "the law forbade a king to mourn for a rebel",
     "A", "2 Samuel 19:5-7: Joab warned that David's grief for a rebel made his loyal men feel that he loved his enemies and hated his friends."),
    (T_PAR, "Medium", "King Asa removed Maacah, his mother, from being queen mother because",
     "she had made an abominable image for Asherah",
     "she had plotted with the king of Israel against him",
     "she refused to attend the Passover in Jerusalem",
     "she had married a foreigner after his father's death",
     "A", "1 Kings 15:13: Asa cut down her image and burnt it, putting loyalty to God above family ties."),
    (T_PAR, "Medium", "When the elders asked Samuel for a king because his sons took bribes and perverted justice, God told Samuel that",
     "the people had rejected God as their king, not Samuel",
     "Samuel's sons would be punished with death for their crimes",
     "he should refuse the request and appoint Joel judge in his place",
     "a king would make Israel the most righteous nation on earth",
     "A", "1 Samuel 8:7: 'They have not rejected you, but they have rejected me from being king over them.'"),
    (T_PAR, "Medium", "The stories of Eli and Samuel together teach that",
     "even godly leaders can fail as parents by not correcting their children",
     "the children of priests are always wicked because of their upbringing",
     "sons should never be allowed to follow their fathers' profession",
     "a leader's children are not his responsibility once they are grown",
     "A", "Both Eli (1 Samuel 2-3) and Samuel (1 Samuel 8:1-5) served God faithfully yet had sons who went astray, with serious national consequences."),

    # ---------------- Obedience and Disobedience ----------------
    (T_OBEY, "Medium", "At Gilgal Saul offered the burnt offering himself because Samuel delayed and the people were scattering. Samuel's verdict was that",
     "his kingdom would not continue because he had not kept God's commandment",
     "he had acted wisely to keep the army together before the battle",
     "he should be made high priest as well as king over Israel",
     "the Philistines would now be defeated because of his sacrifice",
     "A", "1 Samuel 13:13-14: 'You have done foolishly... now your kingdom shall not continue'; God sought a man after His own heart."),
    (T_OBEY, "Medium", "Saul spared Agag and the best of the sheep and oxen, claiming that he kept them to sacrifice to the LORD. His basic fault was",
     "partial obedience, which God counts as rebellion",
     "excessive generosity towards the Amalekite prisoners",
     "cowardice in the face of the Amalekite army",
     "delay in going to war when Samuel commanded him",
     "A", "1 Samuel 15:22-23: Saul obeyed in part but disregarded the command to destroy everything; Samuel called this rebellion and stubbornness."),
    (T_OBEY, "Hard", "Samuel told Saul that 'rebellion is as the sin of divination, and stubbornness is as iniquity and idolatry' in order to show that",
     "disobedience to God is as grave as witchcraft and the worship of other gods",
     "Saul had secretly consulted a medium before the battle with Amalek",
     "the Amalekites practised divination and therefore deserved destruction",
     "Saul should offer more sacrifices to atone for his stubbornness",
     "A", "Samuel equated Saul's disobedience with practices Saul himself had banned, showing how seriously God views disobedience."),
    (T_OBEY, "Medium", "A treasurer who alters the accounts says, 'The chairman insisted, and I was afraid of losing my job.' His excuse resembles Saul's when he said,",
     "'I feared the people and obeyed their voice.'",
     "'I have performed the commandment of the LORD.'",
     "'The LORD has torn the kingdom of Israel from you.'",
     "'Honour me now before the elders of my people.'",
     "A", "1 Samuel 15:24: Saul blamed the people's pressure for his disobedience; fear of men is not accepted as an excuse before God."),
    (T_OBEY, "Medium", "After his rejection Saul begged Samuel, 'Honour me now before the elders of my people.' This shows that Saul was more concerned about",
     "his public image than about genuine repentance",
     "the welfare of the elders than about his own position",
     "restoring the Amalekite spoil to its rightful owners",
     "Samuel's safety on the journey back to Ramah",
     "A", "1 Samuel 15:30: Saul's plea was for outward honour, not for restoration with God, unlike David's later repentance."),
    (T_OBEY, "Medium", "A student asked to write a ten-page project submits five pages and says, 'These are the best pages anyway.' His attitude mirrors that of",
     "Saul, who kept the best of the sheep and oxen against God's command",
     "Achan, who hid the devoted things under the floor of his tent",
     "Jonah, who fled to Tarshish instead of going to Nineveh",
     "Lot's wife, who looked back at the city of Sodom",
     "A", "Like Saul in 1 Samuel 15, the student substitutes his own judgment of what is 'best' for full obedience to the instruction given."),
    (T_OBEY, "Medium", "After pronouncing God's rejection of Saul, Samuel",
     "grieved over Saul and did not see him again until the day of his death",
     "anointed Jonathan as king in his father's place",
     "joined Saul in the sacrifice and blessed his reign",
     "fled to the Philistines for fear of Saul's anger",
     "A", "1 Samuel 15:35: Samuel did not see Saul again until his death but mourned for him; the LORD then sent him to anoint David."),
    (T_OBEY, "Easy", "Lot's wife looked back at Sodom and became a pillar of salt, and Achan hid the devoted things and was stoned. Together these episodes teach that",
     "disobedience to a clear command of God brings certain judgment",
     "God punishes only those who lead others into sin",
     "women and men are judged by different standards",
     "God's commands may be ignored if no one is harmed",
     "A", "Genesis 19:26 and Joshua 7 both show that a direct command of God cannot be disregarded without consequence."),

    # ---------------- A Man after God's Own Heart ----------------
    (T_DAV, "Medium", "When Samuel saw Eliab he thought, 'Surely the LORD's anointed is before him,' but God said, 'Man looks on the outward appearance, but the LORD looks on the heart.' This teaches that",
     "God chooses leaders by their character rather than their appearance",
     "the eldest son should always be preferred for leadership",
     "Samuel had lost the ability to hear God's voice in his old age",
     "physical strength is the most important quality in a king",
     "A", "1 Samuel 16:6-7: David, the youngest and a shepherd, was chosen over his impressive brothers because of his heart."),
    (T_DAV, "Medium", "David told Goliath, 'You come to me with a sword and a spear, but I come to you in the name of the LORD of hosts.' This shows that David",
     "placed his confidence in God rather than in weapons",
     "had no weapon at all and expected to die in the valley",
     "relied on the training he had received in Saul's army",
     "wanted to impress Saul's daughter with his bravery",
     "A", "1 Samuel 17:45-47: David's trust was in the LORD, who 'saves not with sword and spear'."),
    (T_DAV, "Medium", "A student prefers her own well-practised study method to an unfamiliar one that a friend insists on. Her choice is like David's when he",
     "refused Saul's armour because he had not tested it",
     "took Saul's spear and water jar while he slept",
     "danced before the ark with all his might",
     "refused to drink the water from the well of Bethlehem",
     "A", "1 Samuel 17:38-40: David put off Saul's armour, saying 'I am not used to them', and went with his sling and five stones."),
    (T_DAV, "Medium", "When Michal despised David for dancing before the ark, David replied that he would make himself even more contemptible for the LORD's sake. This shows",
     "wholehearted devotion to God regardless of human opinion",
     "disrespect for his wife and for the dignity of a king",
     "that David had drunk too much wine during the procession",
     "that David wanted to shame the house of Saul publicly",
     "A", "2 Samuel 6:20-22: David's joy before the LORD mattered more to him than his image before people."),
    (T_DAV, "Medium", "God's promise through Nathan that David's house and throne would be established for ever is known as",
     "the Davidic covenant, fulfilled in Christ, the Son of David",
     "the Sinai covenant, given through Moses to Israel",
     "the covenant of circumcision made with Abraham",
     "the new covenant written on the heart of every believer",
     "A", "2 Samuel 7:12-16: God promised David an everlasting dynasty; the New Testament sees this fulfilled in Jesus (Luke 1:32-33)."),
    (T_DAV, "Medium", "A governor pays the school fees of the children of a late friend who once helped him. He is imitating David's treatment of",
     "Mephibosheth, Jonathan's lame son, who ate at the king's table",
     "Uriah the Hittite, whom he placed in the front line of battle",
     "Shimei, who cursed him as he fled from Absalom",
     "Nabal, who refused to give food to his men in the wilderness",
     "A", "2 Samuel 9: David showed kindness to Mephibosheth 'for Jonathan's sake', restoring Saul's land to him and giving him a place at table."),
    (T_DAV, "Medium", "David refused to accept Araunah's threshing floor and oxen as a gift, saying, 'I will not offer burnt offerings to the LORD my God which cost me nothing.' This teaches that",
     "true sacrifice to God must cost the giver something",
     "a king must never accept gifts from foreigners",
     "offerings may be made only on land bought from Jebusites",
     "God rejects any offering made on a threshing floor",
     "A", "2 Samuel 24:24: David paid fifty shekels of silver; genuine worship involves real personal cost."),
    (T_DAV, "Medium", "In the wilderness of Ziph David proved to Saul that he had spared his life by showing",
     "Saul's spear and the jar of water taken from beside his head",
     "the piece of Saul's robe he had cut off in the cave",
     "the armour Saul had lent him for the fight with Goliath",
     "the letter Jonathan had written to warn him of danger",
     "A", "1 Samuel 26:11-16: David took the spear and water jar but would not lift his hand against the LORD's anointed."),
    (T_DAV, "Hard", "In his prayer of repentance David said, 'Against thee, thee only, have I sinned.' This shows that he",
     "recognised that every sin is ultimately an offence against God",
     "believed that Bathsheba and Uriah had not really been wronged",
     "thought his sin was too small for anyone else to notice",
     "wanted to keep the whole matter secret from Nathan",
     "A", "Psalm 51:4: David saw his adultery and murder chiefly as sin against God, whose law he had despised (2 Samuel 12:9)."),

    # ---------------- Decision-Making ----------------
    (T_DEC, "Medium", "Solomon's decision to marry many foreign women led, in his old age, to",
     "his heart being turned after other gods and the kingdom being divided",
     "peace with all his neighbours and a long, prosperous reign for his son",
     "the building of a second temple for the worship of the LORD",
     "the conversion of the surrounding nations to the God of Israel",
     "A", "1 Kings 11:1-13: Solomon's wives turned his heart to other gods, and God tore the kingdom from his son, leaving one tribe."),
    (T_DEC, "Medium", "God gave Solomon riches and honour in addition to wisdom because",
     "he had not asked for long life, riches or the death of his enemies",
     "he had offered a thousand burnt offerings at Gibeon",
     "he was the son of David and the grandson of Jesse",
     "he promised to build the temple within seven years",
     "A", "1 Kings 3:11-13: God commended Solomon's unselfish request and added what he had not asked for."),
    (T_DEC, "Medium", "A newly elected class captain listens to the older students and eases some petty rules, and the class co-operates with him. He is following the advice that",
     "the elders gave Rehoboam at Shechem",
     "the young men gave Rehoboam at Shechem",
     "Jeroboam gave the ten tribes at Shechem",
     "Ahijah the prophet gave Solomon at Shiloh",
     "A", "1 Kings 12:7: the elders told Rehoboam that if he served the people and spoke good words to them they would be his servants for ever."),
    (T_DEC, "Medium", "The immediate consequence of Rehoboam's harsh answer at Shechem was that",
     "ten tribes rejected the house of David and made Jeroboam king",
     "the people of Judah stoned him and chose a new king",
     "Egypt invaded Jerusalem and carried away the temple treasures",
     "the elders resigned and left him without any advisers",
     "A", "1 Kings 12:16-20: 'What portion have we in David?'; Israel went to their tents and made Jeroboam king over the ten tribes."),
    (T_DEC, "Medium", "God did not tear the kingdom from Solomon in his own lifetime because",
     "of His promise to David, Solomon's father",
     "Solomon repented and destroyed the high places",
     "the people of Israel prayed for their king",
     "Solomon's wisdom outweighed his idolatry",
     "A", "1 Kings 11:12: 'For the sake of David your father I will not do it in your days, but I will tear it out of the hand of your son.'"),
    (T_DEC, "Medium", "A new manager ignores the experienced staff and follows the advice of his university friends, who tell him to tighten every rule. He is repeating the error of",
     "Rehoboam, who forsook the counsel of the elders",
     "Solomon, who asked God for wisdom at Gibeon",
     "Jeroboam, who set up golden calves at Bethel and Dan",
     "David, who numbered the people against Joab's advice",
     "A", "1 Kings 12:8: Rehoboam 'forsook the counsel which the old men gave him' and took the counsel of the young men, losing ten tribes."),
    (T_DEC, "Medium", "For a student choosing a career, the lesson of Solomon's request at Gibeon is that",
     "an understanding heart for serving others matters more than wealth or fame",
     "one should ask God for riches first and for wisdom afterwards",
     "career choices should be left entirely to one's parents",
     "the most profitable profession is always the will of God",
     "A", "1 Kings 3:9: Solomon asked for 'an understanding mind to govern thy people', and God was pleased with this priority."),
    (T_DEC, "Medium", "Solomon's judgment between the two women who each claimed the living child was remarkable because",
     "there were no witnesses and the claims could not be checked in any ordinary way",
     "both women confessed the truth as soon as they saw the king",
     "the king had known both women before they came to court",
     "the child was old enough to identify his own mother",
     "A", "1 Kings 3:16-28: with no evidence, Solomon's order to divide the child exposed the true mother through her compassion."),
    (T_DEC, "Medium", "Jeroboam decided to set up golden calves at Bethel and Dan so that",
     "the people would not go to Jerusalem to worship and return to Rehoboam",
     "the Egyptians would recognise him as a lawful king",
     "the Levites would have more places at which to serve",
     "the ark of the covenant could be moved to the north",
     "A", "1 Kings 12:26-30: Jeroboam feared that pilgrimages to Jerusalem would win the people back; his decision became 'a sin' for Israel."),

    # ---------------- Greed and Its Effects ----------------
    (T_GREED, "Medium", "Naboth refused to sell his vineyard to King Ahab because",
     "the LORD forbade him to give away the inheritance of his fathers",
     "the king offered a price far below its market value",
     "he wanted to sell it to Jezebel's relatives instead",
     "the vineyard belonged to the priests of Jezreel",
     "A", "1 Kings 21:3: 'The LORD forbid that I should give you the inheritance of my fathers'; the law protected family land."),
    (T_GREED, "Medium", "When Naboth refused, Ahab went home vexed and sullen, lay on his bed, turned away his face and would eat no food. This shows that greed",
     "produces discontent even in a man who owns a kingdom",
     "is easily overcome by fasting and rest",
     "affected Ahab less than it affected Jezebel",
     "is found only among the poor who lack necessities",
     "A", "1 Kings 21:4: Ahab, who had everything, was miserable over one man's vineyard, showing the restless nature of covetousness."),
    (T_GREED, "Medium", "An official forges signatures and hires false witnesses in order to seize a widow's land. His methods resemble those of",
     "Jezebel in obtaining Naboth's vineyard for Ahab",
     "Gehazi in collecting gifts from Naaman the Syrian",
     "Achan in taking the devoted things from Jericho",
     "Ahab in pleading with Naboth to sell the vineyard",
     "A", "1 Kings 21:8-14: Jezebel wrote letters in Ahab's name and set two worthless men to accuse Naboth falsely so that he was stoned."),
    (T_GREED, "Hard", "When Ahab tore his clothes, put on sackcloth and fasted after Elijah pronounced judgment on him, God",
     "postponed the disaster on his house to the days of his son",
     "cancelled the judgment and restored the vineyard to Naboth's sons",
     "struck Jezebel with leprosy for the rest of her life",
     "sent Elijah to anoint Ahab a second time as king",
     "A", "1 Kings 21:27-29: because Ahab humbled himself, God delayed the evil on his house until his son's days."),
    (T_GREED, "Medium", "Gehazi's greed was made worse by the fact that he",
     "lied both to Naaman and to Elisha in order to cover it up",
     "shared the gifts with the sons of the prophets",
     "returned the gifts to Naaman when he was confronted",
     "confessed to Elisha before he was found out",
     "A", "2 Kings 5:22-25: Gehazi invented a story about two visiting prophets and then told Elisha 'Your servant went nowhere'."),
    (T_GREED, "Medium", "Elisha refused Naaman's gift because he wanted Naaman to understand that",
     "the healing was a free gift of God, not a service bought with money",
     "prophets in Israel were paid only by the king",
     "Syrian silver was unclean and could not be used in Israel",
     "Naaman should give the money to the poor of Damascus instead",
     "A", "2 Kings 5:15-16: 'As the LORD lives, whom I serve, I will receive none'; God's grace cannot be purchased."),
    (T_GREED, "Medium", "Because Achan secretly took a mantle, silver and gold from Jericho,",
     "Israel was defeated at Ai and about thirty-six men died",
     "the walls of Jericho were rebuilt by the Canaanites",
     "Joshua was removed as leader and replaced by Caleb",
     "the ark of the covenant was captured by the Philistines",
     "A", "Joshua 7:1-5: Achan's hidden greed brought defeat and death on the whole nation before he was exposed and punished."),
    (T_GREED, "Medium", "The punishment of Gehazi with Naaman's leprosy, which would cling to his descendants, teaches that",
     "dishonest gain can bring lasting harm to the greedy person and his family",
     "leprosy was the normal punishment for any lie told in Israel",
     "prophets had power to curse anyone who displeased them",
     "servants should never handle money on behalf of their masters",
     "A", "2 Kings 5:27: the silver Gehazi gained cost him his health, his position and his family's future."),
    (T_GREED, "Easy", "Which of the following best describes what Ahab, Gehazi and Achan had in common?",
     "Each desired what was not his and brought judgment on himself",
     "Each was a priest who misused the offerings of the people",
     "Each repented immediately and was fully restored",
     "Each was a foreigner who did not know the law of God",
     "A", "Ahab (1 Kings 21), Gehazi (2 Kings 5) and Achan (Joshua 7) all coveted what God had not given them and suffered for it."),

    # ---------------- The Supremacy of God ----------------
    (T_SUP, "Medium", "Elijah told Ahab, 'There shall be neither dew nor rain these years, except by my word.' The drought was intended to show that",
     "the LORD, not Baal the supposed god of rain, controlled the weather",
     "Elijah was more powerful than any prophet before him",
     "the northern kingdom deserved to be destroyed by famine",
     "Ahab should build irrigation canals for the farmers",
     "A", "1 Kings 17:1: Baal was worshipped as the god of rain and fertility; the drought exposed his powerlessness and the LORD's supremacy."),
    (T_SUP, "Medium", "On Mount Carmel Elijah mocked the prophets of Baal: 'Cry aloud, for he is a god; either he is musing, or he has gone aside, or he is on a journey, or perhaps he is asleep.' He was",
     "exposing the helplessness of an idol that could not hear or answer",
     "encouraging the prophets to pray with greater sincerity",
     "suggesting that Baal would answer later in the day",
     "admitting that the LORD was also slow to respond",
     "A", "1 Kings 18:27: Elijah's sarcasm highlighted that Baal was no god at all, in contrast to the LORD who answered by fire."),
    (T_SUP, "Medium", "Elijah had twelve jars of water poured over the sacrifice and the wood before he prayed, so that",
     "no one could claim that the fire was a trick or an accident",
     "the wood would burn more slowly and be seen by all",
     "the people would have water to drink after the drought",
     "the prophets of Baal could not steal his sacrifice",
     "A", "1 Kings 18:33-35: the drenched altar made the fire that fell an unmistakable act of God."),
    (T_SUP, "Easy", "When the fire of the LORD fell and consumed the sacrifice, the wood, the stones, the dust and the water, the people",
     "fell on their faces and said, 'The LORD, he is God'",
     "ran away in fear to the brook Kishon",
     "demanded that Ahab kill Elijah at once",
     "asked the prophets of Baal to try again",
     "A", "1 Kings 18:38-40: the people confessed the LORD as God and, at Elijah's command, seized the prophets of Baal."),
    (T_SUP, "Medium", "The widow of Zarephath said to Elijah, 'Now I know that you are a man of God, and that the word of the LORD in your mouth is truth,' after",
     "Elijah raised her son from the dead",
     "her jar of meal and cruse of oil first failed to run out",
     "rain finally fell on the land after three years",
     "Elijah killed the prophets of Baal on Mount Carmel",
     "A", "1 Kings 17:17-24: the raising of her son convinced the Gentile widow of the LORD's power and Elijah's authority."),
    (T_SUP, "Medium", "A trader who consults a herbalist for charms 'just in case' while also attending church is doing what Elijah condemned when he asked,",
     "'How long will you go limping between two opinions?'",
     "'Is it because there is no God in Israel that you go to inquire of Baal-zebub?'",
     "'Have you found me, O my enemy?'",
     "'Why have you troubled Israel with your father's sins?'",
     "A", "1 Kings 18:21: Elijah demanded that the people stop wavering between the LORD and Baal and choose one."),
    (T_SUP, "Medium", "Elijah's prayer on Carmel asked that the people would know 'that thou, O LORD, art God, and that thou hast turned their hearts back'. The main purpose of the contest was to",
     "bring the people back to the worship of the true God",
     "prove that Elijah was greater than Moses",
     "punish Ahab for the murder of Naboth",
     "end the drought so that trade could resume",
     "A", "1 Kings 18:36-37: the miracle was meant to turn Israel's heart back to the LORD, not to display Elijah's power."),
    (T_SUP, "Medium", "Ahab 'did more to provoke the LORD to anger than all the kings of Israel who were before him' because he",
     "married Jezebel and built a temple and altar for Baal in Samaria",
     "refused to pay tribute to the king of Assyria",
     "moved the capital of Israel from Tirzah to Samaria",
     "made peace with Jehoshaphat, the king of Judah",
     "A", "1 Kings 16:31-33: Ahab married Jezebel of Sidon, served Baal, built him a house in Samaria and made an Asherah."),
    (T_SUP, "Medium", "Nebuchadnezzar said, 'Blessed be the God of Shadrach, Meshach and Abednego... there is no other god who is able to deliver in this way.' This shows that",
     "even a pagan king was forced to acknowledge the supremacy of God",
     "Nebuchadnezzar became a Jew and abolished idol worship in Babylon",
     "the Babylonian gods were regarded as equal to the God of Israel",
     "the fiery furnace was a test the king had planned with Daniel",
     "A", "Daniel 3:28-29: the deliverance from the furnace made the most powerful king of the age confess the supremacy of the God of Israel."),

    # ---------------- Religious Reforms in Judah ----------------
    (T_REF, "Medium", "Hezekiah broke in pieces the bronze serpent that Moses had made because",
     "the people had been burning incense to it, turning a symbol into an idol",
     "the serpent had been made by the Canaanites and not by Moses",
     "the Assyrians demanded all bronze objects as tribute",
     "it had rusted and could no longer be used for healing",
     "A", "2 Kings 18:4: the people called it Nehushtan and worshipped it; Hezekiah destroyed even a sacred relic that had become an idol."),
    (T_REF, "Medium", "Church members treat their late founder's chair as sacred and pray before it. They are repeating the error Hezekiah corrected when he",
     "broke the bronze serpent to which the people burned incense",
     "opened the doors of the temple that his father had shut",
     "stopped paying tribute to the king of Assyria",
     "built the tunnel that brought water into Jerusalem",
     "A", "2 Kings 18:4: an object connected with a past act of God had become an object of worship, which is idolatry."),
    (T_REF, "Medium", "When the book of the law found in the temple was read to Josiah, he tore his clothes because",
     "he realised how far the nation had departed from the law and feared its curses",
     "the book showed that he was not the rightful king of Judah",
     "Hilkiah the priest had hidden the book from him for many years",
     "the book commanded him to pull down the temple",
     "A", "2 Kings 22:11-13: 'great is the wrath of the LORD that is kindled against us, because our fathers have not obeyed the words of this book'."),
    (T_REF, "Medium", "Huldah the prophetess told Josiah's messengers that",
     "judgment would fall on Judah, but not in Josiah's days, because he had humbled himself",
     "the book of the law was a forgery written by the priests and should be burned at once",
     "Josiah would reign for forty more years in peace if he rebuilt the altar at Bethel",
     "the Assyrians would capture Jerusalem within one year unless the king paid tribute",
     "A", "2 Kings 22:15-20: judgment on Judah was certain, but Josiah would be gathered to his grave in peace because his heart was penitent."),
    (T_REF, "Medium", "Josiah defiled Topheth in the valley of the son of Hinnom so that",
     "no one might burn his son or daughter as an offering to Molech",
     "the Levites would have a place to bury the dead",
     "the water supply of Jerusalem would be protected",
     "the Passover lambs could be slaughtered there",
     "A", "2 Kings 23:10: Josiah ended the practice of child sacrifice to Molech as part of his purge of idolatry."),
    (T_REF, "Medium", "Josiah kept a Passover 'such as had not been kept since the days of the judges'. This shows that true religious reform involves",
     "restoring proper worship as well as removing what is evil",
     "abolishing all festivals inherited from earlier generations",
     "changing the place of worship from Jerusalem to Bethel",
     "replacing the priests with the king's own officials",
     "A", "2 Kings 23:21-23: after purging idolatry, Josiah renewed covenant worship according to the book of the covenant."),
    (T_REF, "Hard", "Hezekiah's reforms were remarkable because his father Ahaz had",
     "shut the doors of the temple and sacrificed to the gods of Damascus",
     "already removed all the high places in Judah",
     "been a faithful king who kept the Passover every year",
     "destroyed the altar of Baal on Mount Carmel",
     "A", "2 Chronicles 28:22-25 and 29:3: Ahaz closed the temple and set up altars everywhere; Hezekiah reopened and cleansed it in his first month."),
    (T_REF, "Hard", "At Bethel Josiah broke down the altar that Jeroboam had built and burnt bones on it, thereby fulfilling",
     "the prophecy of the man of God from Judah in Jeroboam's time",
     "the promise God made to Solomon at Gibeon",
     "the curse Joshua pronounced on whoever rebuilt Jericho",
     "the words of Isaiah to Hezekiah about the Babylonians",
     "A", "2 Kings 23:15-18 and 1 Kings 13:1-3: the man of God had foretold that a son of David named Josiah would defile that altar."),
    (T_REF, "Medium", "A school rediscovers its forgotten rule book and publicly recommits every student to it. This resembles",
     "Josiah's covenant renewal after the book of the law was found",
     "Hezekiah's destruction of the bronze serpent",
     "Rehoboam's consultation with the young men at Shechem",
     "Solomon's dedication of the temple in Jerusalem",
     "A", "2 Kings 23:1-3: Josiah read the book to all the people and led them in a public renewal of the covenant."),

    # ---------------- Concern for Judah ----------------
    (T_NEH, "Medium", "When King Artaxerxes asked Nehemiah, 'For what do you make request?' Nehemiah first",
     "prayed to the God of heaven before answering the king",
     "asked the queen to plead his case before the king",
     "denied that anything at all was troubling him",
     "asked to be released from the king's service for ever",
     "A", "Nehemiah 2:4: a quick, silent prayer in a critical moment shows Nehemiah's habit of depending on God."),
    (T_NEH, "Medium", "Nehemiah inspected the broken walls of Jerusalem by night with a few men and told no one what God had put in his heart, because he wanted to",
     "assess the task fully before announcing his plan and alerting opponents",
     "avoid paying the toll charged for entering the city by day",
     "take building materials from the houses of the nobles",
     "keep the wall unrepaired so that the king would recall him",
     "A", "Nehemiah 2:11-16: careful planning and discretion preceded his public appeal, 'Come, let us build the wall of Jerusalem'."),
    (T_NEH, "Medium", "When Sanballat and Tobiah plotted to attack the builders, Nehemiah said, 'We prayed to our God and set a guard as a protection against them day and night.' This teaches that",
     "prayer and practical vigilance go together",
     "prayer makes any human precaution unnecessary",
     "guards are more reliable than prayer in a crisis",
     "believers should abandon their work when threatened",
     "A", "Nehemiah 4:9 and 4:17: the people prayed and also built with a weapon in one hand, combining faith with action."),
    (T_NEH, "Medium", "A co-operative leader stops wealthy members from charging crippling interest to poorer members in a time of hardship. He is acting as Nehemiah did when he",
     "confronted the nobles who were exacting interest and taking children as slaves",
     "shut the gates of Jerusalem before the Sabbath began",
     "threw Tobiah's furniture out of the temple chamber",
     "refused Sanballat's invitation to meet in the plain of Ono",
     "A", "Nehemiah 5:1-13: Nehemiah rebuked the nobles and made them restore fields, houses and interest to their brothers."),
    (T_NEH, "Medium", "Nehemiah did not take the food allowance due to him as governor for twelve years because",
     "the burden on the people was already heavy and he feared God",
     "the king of Persia had forbidden governors to receive allowances",
     "he was wealthy enough to build a palace from his own funds",
     "he wanted the people to pay him a larger sum after the wall was built",
     "A", "Nehemiah 5:14-18: 'because of the fear of God' he did not lord it over the people as former governors had done."),
    (T_NEH, "Medium", "Nehemiah ordered the gates of Jerusalem to be shut before the Sabbath and set his servants over them in order to",
     "stop traders from selling goods in the city on the Sabbath",
     "prevent the Samaritans from worshipping in the temple",
     "protect the city from an attack by the Ammonites",
     "collect a tax from every merchant who entered the city",
     "A", "Nehemiah 13:15-22: he warned the merchants who camped outside that he would lay hands on them if they came again."),
    (T_NEH, "Medium", "Sanballat mocked, 'If a fox goes up on it he will break down their stone wall!' Yet the wall soon reached half its height because",
     "the people had a mind to work",
     "the king of Persia sent soldiers to build it",
     "Sanballat later changed his mind and helped",
     "Nehemiah hired builders from Egypt",
     "A", "Nehemiah 4:6: 'So we built the wall... for the people had a mind to work'; unity and commitment overcame ridicule."),
    (T_NEH, "Medium", "When the wall was finished in fifty-two days, the surrounding nations were afraid because",
     "they perceived that the work had been accomplished with the help of God",
     "the Persian army had arrived to garrison Jerusalem",
     "Nehemiah threatened to invade Samaria next",
     "the Jews had recovered the ark of the covenant",
     "A", "Nehemiah 6:15-16: the enemies 'fell greatly in their own esteem; for they perceived that this work had been accomplished with the help of our God'."),
    (T_NEH, "Medium", "Nehemiah's decision to leave his comfortable post as cup-bearer in Susa to rebuild Jerusalem shows",
     "patriotic concern for God's people that put their welfare above personal comfort",
     "ambition to become king of Judah in place of the Persian governors",
     "fear that Artaxerxes was about to dismiss him from the palace",
     "a desire to escape a famine that had struck the land of Persia",
     "A", "Nehemiah 1-2: his weeping, fasting and request to go show a selfless concern for the 'great trouble and shame' of his people."),

    # ---------------- Faith, Courage and Protection ----------------
    (T_FAITH, "Medium", "Shadrach, Meshach and Abednego told the king, 'Our God whom we serve is able to deliver us... But if not, be it known to you, O king, that we will not serve your gods.' The words 'but if not' show that",
     "their obedience did not depend on being rescued",
     "they doubted that God had the power to save them",
     "they expected the king to change his mind at the last moment",
     "they were prepared to bow if the fire proved too hot",
     "A", "Daniel 3:17-18: their faith was in God Himself, not in a guaranteed outcome; they would obey whether delivered or not."),
    (T_FAITH, "Medium", "After the three Hebrews came out of the furnace unharmed, Nebuchadnezzar",
     "decreed that no people should speak against their God and promoted them",
     "threw Daniel into the furnace in their place",
     "ordered that the golden image be made even larger",
     "sent them back to Jerusalem with the temple vessels",
     "A", "Daniel 3:28-30: the king blessed their God, made a decree protecting their faith and promoted them in Babylon."),
    (T_FAITH, "Medium", "Daniel's enemies said, 'We shall not find any ground for complaint against this Daniel unless we find it in connection with the law of his God.' This shows that",
     "his conduct was so blameless that only his faith could be used against him",
     "Daniel had broken several Persian laws in secret",
     "the law of God permitted Daniel to disobey the king",
     "Darius had already decided to remove Daniel from office",
     "A", "Daniel 6:4-5: Daniel was faithful and without error, so his rivals attacked the one thing he would never compromise."),
    (T_FAITH, "Medium", "A Christian student keeps praying openly in the hostel despite a ban on religious activities, just as Daniel prayed with his windows open after the decree was signed. The student is showing",
     "Daniel's courage in maintaining his devotion to God under threat",
     "Esther's silence about her nationality in the palace of Susa",
     "the three Hebrews' refusal to eat the food from the king's table",
     "Nehemiah's caution in inspecting the walls of Jerusalem by night",
     "A", "Daniel 6:10: Daniel neither hid nor changed his practice of prayer when it became dangerous."),
    (T_FAITH, "Medium", "King Darius was greatly distressed and laboured till sundown to rescue Daniel but could not, because",
     "a law of the Medes and Persians once signed could not be changed",
     "the lions had already been released into the city",
     "Daniel refused to accept a pardon from a pagan king",
     "the satraps had locked the king in his own palace",
     "A", "Daniel 6:14-15: the king's rash decree trapped him; only God could deliver Daniel, and He shut the lions' mouths."),
    (T_FAITH, "Medium", "Before going to the king uninvited, Esther asked Mordecai to gather all the Jews in Susa to fast for three days, saying, 'If I perish, I perish.' This shows",
     "courage combined with dependence on God through fasting",
     "reckless disregard for the law of the Persian court",
     "confidence that the king could never refuse her anything",
     "a plan to escape from Susa if the king was angry",
     "A", "Esther 4:15-16: Esther prepared for a life-risking act by seeking God's help together with her people."),
    (T_FAITH, "Medium", "Mordecai told Esther, 'Who knows whether you have not come to the kingdom for such a time as this?' He meant that",
     "God may have placed her in the palace so that she could save her people",
     "the king would soon divorce her as he had divorced Vashti",
     "she should flee the palace before Haman's decree took effect",
     "her position as queen was purely a matter of good luck",
     "A", "Esther 4:14: Mordecai saw God's providence in Esther's position and called her to use it courageously."),
    (T_FAITH, "Medium", "A nurse refuses to falsify a report even after being threatened with dismissal, saying, 'God can protect me, but even if He does not, I will not lie.' Her attitude echoes that of",
     "the three Hebrews before Nebuchadnezzar",
     "Jonah before the sailors in the storm",
     "Gehazi before Naaman the Syrian",
     "Saul before Samuel at Gilgal",
     "A", "Daniel 3:17-18: like Shadrach, Meshach and Abednego, she obeys God regardless of whether deliverance follows."),
    (T_FAITH, "Easy", "The lesson common to Daniel in the lions' den and the three Hebrews in the furnace is that",
     "God protects those who remain faithful to Him under persecution",
     "believers should avoid serving in pagan governments",
     "God always removes His people from danger before it comes",
     "kings have no authority at all over the people of God",
     "A", "Daniel 3 and 6: faithfulness under threat was met by divine protection, and God was glorified before pagan kings."),

    # ---------------- God's Message to Nineveh ----------------
    (T_JON, "Easy", "Jonah went down to Joppa and boarded a ship for Tarshish in order to",
     "flee from the presence of the LORD and avoid preaching to Nineveh",
     "reach Nineveh more quickly by travelling over the sea",
     "trade with the Phoenicians before starting his mission",
     "escape a famine that had struck the land of Israel",
     "A", "Jonah 1:3: Tarshish lay in the opposite direction from Nineveh; Jonah was running from his commission."),
    (T_JON, "Medium", "During the storm the sailors rowed hard to bring the ship to land, prayed to the LORD not to hold them guilty, and only then threw Jonah into the sea. Their behaviour shows that",
     "the pagan sailors showed more reverence and compassion than the runaway prophet",
     "sailors in those days were secretly worshippers of the God of Israel",
     "Jonah had persuaded them to become Jews during the voyage",
     "they had intended to kill Jonah from the moment he boarded",
     "A", "Jonah 1:13-16: the sailors' reluctance and their fear of the LORD contrast with Jonah's disobedience and indifference."),
    (T_JON, "Medium", "When Jonah preached, 'Yet forty days, and Nineveh shall be overthrown!' the king of Nineveh",
     "rose from his throne, put on sackcloth, sat in ashes and decreed a fast for man and beast",
     "had Jonah arrested as a foreign spy and thrown into prison until the forty days had passed",
     "sent his army to attack the land of Israel in revenge for the insult to his great city",
     "ignored the message completely and held a feast on the fortieth day to mock the prophet",
     "A", "Jonah 3:6-9: the king humbled himself and commanded everyone to turn from evil and violence, hoping God would relent."),
    (T_JON, "Medium", "The king of Nineveh commanded, 'Let every one turn from his evil way and from the violence which is in his hands.' This shows that genuine repentance involves",
     "a concrete change of conduct and not merely outward signs of sorrow",
     "fasting and sackcloth only, without any change of behaviour",
     "offering sacrifices in the temple at Jerusalem",
     "paying compensation to the prophet who brought the message",
     "A", "Jonah 3:8-10: God saw 'how they turned from their evil way' and repented of the evil He had said He would do."),
    (T_JON, "Medium", "God used the plant that sheltered Jonah and then withered to teach him that",
     "God's compassion for Nineveh's people was far greater than Jonah's concern for a plant",
     "prophets should never rest in the shade while waiting for judgment to fall",
     "the east wind was a sign of the coming destruction of Nineveh",
     "Jonah should have planted a tree instead of building a booth",
     "A", "Jonah 4:10-11: 'You pity the plant... and should not I pity Nineveh, that great city, in which there are more than 120,000 persons?'"),
    (T_JON, "Medium", "A church youth refuses to join an outreach to a neighbourhood notorious for crime, saying, 'They deserve whatever comes to them.' His attitude resembles",
     "Jonah's attitude towards the people of Nineveh",
     "the sailors' attitude towards Jonah in the storm",
     "the king of Nineveh's attitude towards God's warning",
     "Nehemiah's attitude towards the nobles of Judah",
     "A", "Jonah 4:1-2: Jonah was angry that God spared Nineveh; he wanted judgment on Israel's enemies rather than their salvation."),
    (T_JON, "Medium", "God's decision to spare Nineveh after Jonah had announced its destruction shows that",
     "God's threats of judgment are conditional on the response of the people",
     "Jonah's prophecy was false and he was not a true prophet",
     "God changes His mind without any reason at all",
     "Nineveh was never really in danger of destruction",
     "A", "Jonah 3:10 (compare Jeremiah 18:7-8): when a nation turns from evil, God relents of the disaster He announced."),
    (T_JON, "Hard", "In his anger Jonah said, 'I knew that thou art a gracious God and merciful, slow to anger, and abounding in steadfast love.' This reveals that Jonah",
     "fled because he did not want God's mercy extended to Israel's enemies",
     "did not believe that God was merciful before the events at Nineveh",
     "had never heard of God's character until the plant withered",
     "expected God to destroy Israel instead of Nineveh",
     "A", "Jonah 4:2: Jonah's complaint shows he had fled precisely because he expected God to forgive the repentant Ninevites."),
    (T_JON, "Easy", "The book of Jonah teaches Israel that",
     "God's love and salvation extend to all nations, not to Israel alone",
     "prophets may refuse missions they consider too dangerous",
     "God never sends His messengers to Gentile cities",
     "only the people of Israel are able to repent",
     "A", "Jonah 4:11: the book ends with God's compassion for a Gentile city, correcting a narrow view of God's love."),

    # ---------------- Social Justice, True Religion and Divine Love ----------------
    (T_JUST, "Medium", "Amos declared in God's name, 'I hate, I despise your feasts... But let justice roll down like waters, and righteousness like an ever-flowing stream.' This teaches that",
     "worship is unacceptable to God when it is not accompanied by justice",
     "God abolished all feasts and sacrifices in the time of Amos",
     "justice is a substitute for worship, so that worship is unnecessary",
     "feasts should be held near rivers and flowing streams",
     "A", "Amos 5:21-24: elaborate worship cannot cover up the oppression of the poor; God requires justice first."),
    (T_JUST, "Medium", "A trader uses a measuring cup with a false bottom so that customers receive less than they pay for. Amos condemned this practice when he spoke against those who",
     "make the ephah small and the shekel great and deal deceitfully with false balances",
     "lie upon beds of ivory and sing idle songs to the sound of the harp",
     "trample the head of the poor into the dust of the earth",
     "go to Bethel and transgress, and to Gilgal and multiply transgression",
     "A", "Amos 8:4-6: dishonest weights and measures that cheat the needy are singled out as sins God will never forget."),
    (T_JUST, "Hard", "When Amaziah, priest of Bethel, told Amos to go and prophesy in Judah, Amos replied that he was no prophet nor a prophet's son but a herdsman whom the LORD had taken from following the flock. His reply showed that",
     "his authority came from God's direct call and not from a professional prophetic guild",
     "he was too poor to travel back to Judah as Amaziah had demanded",
     "he had agreed to stop prophesying in the king's sanctuary",
     "he intended to become a priest at Bethel himself",
     "A", "Amos 7:14-15: Amos rejected the suggestion that he prophesied for a living; he spoke because the LORD had sent him."),
    (T_JUST, "Medium", "Hosea said in God's name, 'I desire steadfast love and not sacrifice, the knowledge of God rather than burnt offerings.' A church that raises huge offerings while its members cheat and hate one another is failing in what Hosea called",
     "steadfast love and the knowledge of God",
     "burnt offerings and sacrifice",
     "the payment of tithes and first fruits",
     "the observance of new moons and Sabbaths",
     "A", "Hosea 6:6: God values covenant love and true knowledge of Him above ritual; Jesus quoted this verse twice."),
    (T_JUST, "Medium", "Hosea blamed the priests for the moral decay of Israel because they",
     "had rejected the knowledge of God and fed on the sins of the people",
     "had moved the sanctuary from Bethel to Jerusalem",
     "refused to accept sacrifices from the poor",
     "had joined Amos in condemning the king",
     "A", "Hosea 4:6-8: 'because you have rejected knowledge, I reject you from being a priest to me... they feed on the sin of my people'."),
    (T_JUST, "Medium", "God told Hosea to buy back his unfaithful wife for fifteen shekels of silver and a measure of barley. This act symbolised",
     "God's redeeming love for unfaithful Israel",
     "the price of a slave in the markets of Samaria",
     "Hosea's poverty as a prophet without support",
     "the payment Israel owed to Assyria as tribute",
     "A", "Hosea 3:1-3: 'Go again, love a woman who is beloved of a paramour... even as the LORD loves the people of Israel'."),
    (T_JUST, "Medium", "The name Lo-ammi given to Hosea's third child meant",
     "'not my people', signifying God's rejection of unfaithful Israel",
     "'God sows', signifying a coming harvest of blessing",
     "'not pitied', signifying that God would no longer have mercy",
     "'God saves', signifying the coming deliverance from Assyria",
     "A", "Hosea 1:9: 'Call his name Not my people, for you are not my people and I am not your God'; Lo-ruhamah meant 'not pitied'."),
    (T_JUST, "Medium", "A landlord evicts a widow in the rainy season over a small debt and then goes to lead worship on Sunday. This illustrates what Amos condemned:",
     "oppression of the poor combined with outward religious observance",
     "the failure to pay tithes on income earned from property",
     "the worship of Baal alongside the LORD at Bethel",
     "the refusal to attend the appointed feasts in Jerusalem",
     "A", "Amos 2:6-8: those who trampled the poor also lay down beside every altar on garments taken in pledge."),
    (T_JUST, "Medium", "Hosea's final message, 'Return, O Israel, to the LORD your God... I will heal their faithlessness; I will love them freely,' shows that",
     "God's love offers restoration to those who repent even after serious unfaithfulness",
     "Israel had never really been unfaithful to God in the first place",
     "God's love is given only to those who have kept the covenant perfectly",
     "the northern kingdom would not be punished at all",
     "A", "Hosea 14:1-4: the book that exposes Israel's adultery ends with an invitation to return and a promise of free, healing love."),

    # ---------------- Holiness and Divine Call ----------------
    (T_HOLY, "Medium", "In the temple vision Isaiah cried, 'Woe is me! For I am lost,' because",
     "the vision of God's holiness made him conscious of his own sinfulness and his people's",
     "the seraphim had threatened to burn him with the live coal",
     "King Uzziah had just died and he feared for the nation",
     "he had entered the Holy of Holies without permission",
     "A", "Isaiah 6:1-5: seeing the thrice-holy LORD, Isaiah confessed that he was a man of unclean lips among a people of unclean lips."),
    (T_HOLY, "Medium", "After his lips were cleansed, Isaiah heard, 'Whom shall I send, and who will go for us?' and answered, 'Here am I! Send me.' This teaches that",
     "cleansing from sin leads to willing service for God",
     "God sends only those who volunteer before being cleansed",
     "prophets were chosen by casting lots in the temple",
     "Isaiah was appointed high priest in place of Uzziah",
     "A", "Isaiah 6:6-8: forgiveness came first, then the readiness to be sent; call follows cleansing."),
    (T_HOLY, "Hard", "Isaiah's commission included the warning that",
     "the people would hear but not understand, and judgment would leave only a stump",
     "the Assyrians would be converted by his preaching within a year",
     "he would be stoned by the people of Jerusalem",
     "no king of Judah would ever listen to him",
     "A", "Isaiah 6:9-13: the message would harden hearts until the land lay desolate, yet 'the holy seed is its stump' promised a remnant."),
    (T_HOLY, "Medium", "When Jeremiah objected, 'I do not know how to speak, for I am only a youth,' God",
     "touched his mouth, put His words in it and promised to deliver him",
     "chose Baruch the scribe to prophesy instead of him",
     "gave him seven years to train under the priests at Anathoth",
     "struck him dumb until he agreed to go",
     "A", "Jeremiah 1:6-9: 'Do not say, I am only a youth... Be not afraid of them, for I am with you to deliver you'."),
    (T_HOLY, "Medium", "Ezekiel was told to eat the scroll written with words of lamentation, mourning and woe before speaking to Israel, in order to",
     "take God's message fully into himself before delivering it",
     "prove that he could survive without ordinary food",
     "destroy the evidence of God's judgment on the people",
     "show the exiles that the scroll tasted sweet",
     "A", "Ezekiel 2:8-3:3: the prophet must first absorb the word of God; it tasted as sweet as honey though its content was judgment."),
    (T_HOLY, "Medium", "A pastor never preaches against the corruption of his wealthy members for fear of losing them. He is failing in the duty God gave Ezekiel when He appointed him",
     "a watchman who must warn the wicked or answer for their blood",
     "a priest who must offer sacrifices for the sins of the people",
     "a king who must judge between the rich and the poor",
     "a scribe who must record the history of the exile",
     "A", "Ezekiel 3:17-19: if the watchman does not warn the wicked, 'his blood I will require at your hand'."),
    (T_HOLY, "Medium", "A feature common to the calls of Isaiah, Jeremiah and Ezekiel is that",
     "God took the initiative and equipped the prophet for a difficult task",
     "each prophet volunteered at a festival in the temple",
     "each was called while serving as a priest in Babylon",
     "each was promised that the people would gladly accept his message",
     "A", "Isaiah 6, Jeremiah 1 and Ezekiel 2-3: in every case God called, cleansed or strengthened the prophet and warned of resistance."),
    (T_HOLY, "Easy", "The seraphim covered their faces and their feet in the presence of the LORD. This shows",
     "reverence before God's overwhelming holiness",
     "that the seraphim were ashamed of their appearance",
     "that the temple was too bright for them to see",
     "that they were about to fly away from the throne",
     "A", "Isaiah 6:2: even sinless heavenly beings veil themselves before the thrice-holy God."),
    (T_HOLY, "Medium", "God told Ezekiel, 'I have made your face hard against their faces, and your forehead hard against their foreheads,' because",
     "the house of Israel was rebellious, impudent and stubborn",
     "Ezekiel was a timid man who feared the exiles",
     "the Babylonians would try to torture him",
     "the prophet had asked God for physical strength",
     "A", "Ezekiel 2:3-7 and 3:8-9: God equipped Ezekiel with resolve equal to the stubbornness of the people he was sent to."),

    # ---------------- Punishment and Hope ----------------
    (T_HOPE, "Medium", "Ezekiel rejected the proverb 'The fathers have eaten sour grapes, and the children's teeth are set on edge' in order to teach that",
     "each person is responsible for his own sin and will be judged individually",
     "children must bear the punishment for the sins of their parents",
     "sour grapes were forbidden food for the exiles in Babylon",
     "the exile was entirely the fault of the previous generation",
     "A", "Ezekiel 18:2-4: 'The soul that sins shall die'; the son shall not suffer for the iniquity of the father."),
    (T_HOPE, "Medium", "A boy says, 'I keep failing because my grandfather was cursed.' Ezekiel's teaching contradicts him by insisting that",
     "a person is judged for his own conduct, not for his ancestors' sins",
     "curses pass from generation to generation without any limit",
     "only a priest can remove a curse from a family",
     "failure in examinations is always a sign of divine punishment",
     "A", "Ezekiel 18:20: 'The righteousness of the righteous shall be upon himself, and the wickedness of the wicked shall be upon himself.'"),
    (T_HOPE, "Medium", "God said through Ezekiel, 'Have I any pleasure in the death of the wicked... and not rather that he should turn from his way and live?' This shows that",
     "God desires the repentance of sinners rather than their punishment",
     "God takes no notice of the sins of the wicked",
     "the wicked can never escape the death they deserve",
     "repentance is possible only for the righteous",
     "A", "Ezekiel 18:21-23: the wicked man who turns from his sins 'shall surely live; he shall not die'."),
    (T_HOPE, "Medium", "A deacon says, 'I have served this church for thirty years, so my present fraud does not matter.' Ezekiel would reply that",
     "the righteous deeds of a man who turns to sin will not be remembered",
     "long service cancels out any later wrongdoing",
     "fraud is a minor sin compared with idolatry",
     "God judges only the first half of a person's life",
     "A", "Ezekiel 18:24: when a righteous man turns away and does wrong, 'none of the righteous deeds which he has done shall be remembered'."),
    (T_HOPE, "Medium", "In Ezekiel's vision of the valley of dry bones, God said, 'These bones are the whole house of Israel. Behold, they say, Our bones are dried up, and our hope is lost.' The vision was therefore a message of",
     "hope that God would restore the nation the exiles thought was dead",
     "judgment on the exiles for failing to bury their dead",
     "warning that the exile would last another seventy years",
     "instruction on how the exiles should honour their ancestors",
     "A", "Ezekiel 37:11-14: God promised to open their graves, put His Spirit in them and bring them back to their own land."),
    (T_HOPE, "Medium", "Ezekiel joined two sticks into one, marked 'Judah' and 'Joseph', to symbolise",
     "the reunion of Israel and Judah under one king",
     "the alliance between Judah and Egypt against Babylon",
     "the two tablets of the law kept in the ark",
     "the union of priests and prophets in the temple",
     "A", "Ezekiel 37:15-22: 'I will make them one nation in the land... and one king shall be king over them all'."),
    (T_HOPE, "Medium", "Jeremiah bought a field at Anathoth from his cousin Hanamel while Jerusalem was under siege by the Babylonians. This purchase was a sign that",
     "God would restore His people to the land after the exile",
     "Jeremiah intended to flee to Anathoth before the city fell",
     "land prices had collapsed and the prophet was making a profit",
     "the Babylonians would never capture the city",
     "A", "Jeremiah 32:15: 'Houses and fields and vineyards shall again be bought in this land'; judgment would be followed by restoration."),
    (T_HOPE, "Medium", "God said through Jeremiah, 'Return, faithless Israel... I will not look on you in anger, for I am merciful... Only acknowledge your guilt.' The condition for restoration was",
     "honest acknowledgement of sin and a return to God",
     "payment of double tribute to the king of Babylon",
     "the rebuilding of the high places destroyed by Josiah",
     "the return of the ark from the land of the Philistines",
     "A", "Jeremiah 3:12-13: mercy was offered freely, but it required repentance and confession of guilt."),
    (T_HOPE, "Medium", "A prisoner is told, 'God does not hold your past against you if you turn to Him now.' This counsel reflects the teaching of",
     "Ezekiel 18, that the wicked who turn from their sins shall live",
     "Amos 5, that God despises the feasts of Israel",
     "Jonah 1, that no one can flee from the presence of God",
     "1 Samuel 15, that rebellion is as the sin of divination",
     "A", "Ezekiel 18:21-22: 'None of the transgressions which he has committed shall be remembered against him'."),
]

FIX = {}


def build():
    build_batch(
        S, "batch_025_crs_round3a.json", "batch_025_crs_round3a",
        "Christian Religious Studies round 3 (part A): Old Testament themes - sovereignty of God, covenant, leadership, providence, parental responsibility, obedience, David, decision-making, greed, supremacy of God, reforms in Judah, Nehemiah, faith and courage, Jonah, social justice, holiness and call, punishment and hope - scripture-based and application items.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
