"""Batch 036 - Principles of Accounts (Accounting) round 1, part B.

Second half of the JAMB Principles of Accounts syllabus: stock valuation, control accounts, incomplete
records and single entry, manufacturing accounts, accounts of not-for-profit organisations, departmental
accounts, branch accounts, partnership accounts, company accounts, public sector accounting, information
technology in accounting and interpretation of accounts (ratios).  Scenario, computation and data-table
items in the style of the UTME paper.

    python3 scripts/build_content_batch36.py -> content/batch_036_accounting_round1b.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Accounting"

T_STK = "Stock Valuation"
T_CTL = "Control Accounts"
T_INC = "Incomplete Records and Single Entry"
T_MFG = "Manufacturing Accounts"
T_NFP = "Accounts of Not-for-Profit Organisations"
T_DPT = "Departmental Accounts"
T_BRN = "Branch Accounts"
T_PTN = "Partnership Accounts"
T_CO = "Company Accounts"
T_PUB = "Public Sector Accounting"
T_IT = "Information Technology in Accounting"
T_RAT = "Interpretation of Accounts and Ratios"

PASSAGES = [
    ("B1", T_STK, "Stock movements of Product X",
     "The receipts and issues of Product X for January 2026 were as follows:\n\n"
     "Date    Transaction       Units  ₦/unit\n"
     "Jan 1   Opening stock       100     50\n"
     "Jan 8   Purchases           200     60\n"
     "Jan 15  Issued (sold)       150      -\n"
     "Jan 22  Purchases           100     70\n"
     "Jan 28  Issued (sold)       150      -\n\n"
     "All units issued were sold at ₦100 each."),
    ("B2", T_CTL, "Debtors of Ola Ventures",
     "The following information relates to the debtors of Ola Ventures for June 2026:\n\n"
     "Item                              ₦\n"
     "Debtors at 1 June            210,000\n"
     "Credit sales                 640,000\n"
     "Cash received from debtors   520,000\n"
     "Discount allowed              14,000\n"
     "Returns inwards               26,000\n"
     "Bad debts written off          9,000\n"
     "Customer's cheque dishonoured 12,000\n"
     "Set-off against purchases\n"
     "  ledger                       8,000"),
    ("B3", T_INC, "Tunde's position at the start and end of 2025",
     "Tunde, a trader, does not keep proper books of account. His assets and liabilities were:\n\n"
     "Item              1 Jan 2025   31 Dec 2025\n"
     "Stock                 80,000        95,000\n"
     "Debtors               45,000        60,000\n"
     "Cash at bank          25,000        15,000\n"
     "Furniture (cost)     100,000       100,000\n"
     "Creditors             30,000        40,000\n\n"
     "Furniture is to be depreciated by 10% for 2025. During the year Tunde withdrew ₦120,000 for private use and paid ₦50,000 of his own money into the business as additional capital."),
    ("B4", T_MFG, "Costs of Bright Soap Factory",
     "The following figures were extracted from the books of Bright Soap Factory for the year ended 31 December 2025:\n\n"
     "Item                            ₦\n"
     "Raw materials: 1 Jan        40,000\n"
     "Raw materials: 31 Dec       50,000\n"
     "Purchases of raw materials 300,000\n"
     "Carriage on raw materials   10,000\n"
     "Direct wages               180,000\n"
     "Direct expenses             20,000\n"
     "Indirect factory wages      60,000\n"
     "Factory rent                45,000\n"
     "Depreciation of plant       25,000\n"
     "Work in progress: 1 Jan     30,000\n"
     "Work in progress: 31 Dec    20,000\n"
     "Office salaries             70,000"),
    ("B5", T_NFP, "Unity Social Club, year ended 31 December 2025",
     "The treasurer of Unity Social Club provided the following information for 2025. Cash in hand on 1 January was ₦70,000.\n\n"
     "Receipts                        ₦\n"
     "Subscriptions               480,000\n"
     "Bar takings                 350,000\n\n"
     "Payments                        ₦\n"
     "Bar purchases               220,000\n"
     "Barman's wages               60,000\n"
     "Rent of clubhouse           100,000\n"
     "Secretary's honorarium       40,000\n"
     "Purchase of chairs          150,000\n\n"
     "The subscriptions received include ₦30,000 paid in advance for 2026 and ₦20,000 of arrears for 2024. Subscriptions of ₦25,000 for 2025 were still unpaid at the year end. Bar stock was ₦30,000 on 1 January and ₦40,000 on 31 December."),
    ("B6", T_PTN, "Ade and Bisi in partnership",
     "Ade and Bisi are in partnership sharing profits and losses in the ratio 3:2. Their partnership agreement provides for interest on capital at 5% per annum, a salary of ₦120,000 per annum for Bisi, and interest on drawings. For the year ended 31 December 2025:\n\n"
     "Item                    Ade        Bisi\n"
     "Capital account     600,000     400,000\n"
     "Interest on drawings 10,000       6,000\n\n"
     "The net profit for the year before any appropriation was ₦500,000."),
    ("B7", T_CO, "Share issue by Zenith Foods Plc",
     "Zenith Foods Plc has an authorised share capital of 10,000,000 ordinary shares of ₦1 each. In 2025 the company offered 6,000,000 of the shares to the public at ₦1.50 per share, payable in full on application. Applications were received for 7,500,000 shares. The directors allotted 6,000,000 shares and refunded the money on the excess applications. The company also issued ₦2,000,000 of 10% debentures at par."),
    ("B8", T_PUB, "Budget of Alimosho Local Government",
     "The following is an extract from the approved 2025 budget of a local government (figures in ₦ million):\n\n"
     "Item                              ₦m\n"
     "Statutory allocation             900\n"
     "Internally generated revenue     250\n"
     "Share of value added tax         150\n"
     "Personnel costs                  500\n"
     "Overhead costs                   300\n"
     "Capital projects                 450"),
    ("B9", T_DPT, "Two departments of Crown Stores",
     "Crown Stores has two departments, A and B. Rent is apportioned on floor area in the ratio A:B = 3:2 and salaries in proportion to sales. Figures for the year ended 31 December 2025:\n\n"
     "Item              Dept A     Dept B\n"
     "Sales            600,000    400,000\n"
     "Opening stock     50,000     30,000\n"
     "Purchases        380,000    250,000\n"
     "Closing stock     70,000     40,000\n\n"
     "Rent for the year was ₦100,000 and salaries ₦90,000."),
]

PQ = [
    # ---------------- B1 stock ----------------
    ("B1", "Easy", "The number of units of Product X in stock on 31 January 2026 was",
     "150", "100", "200", "50",
     "B", "100 + 200 − 150 + 100 − 150 = 100 units remained at the end of the month.", "100+200-150+100-150"),
    ("B1", "Medium", "Using the FIFO method, the value of the closing stock of Product X was",
     "₦5,000", "₦6,000", "₦7,000", "₦6,200",
     "C", "Under FIFO the earliest units are issued first, so the 100 units left are the latest purchase at ₦70 each = ₦7,000.", "100*70"),
    ("B1", "Medium", "Using the LIFO method (perpetual), the value of the closing stock of Product X was",
     "₦7,000", "₦5,000", "₦6,000", "₦6,200",
     "B", "Jan 15 issue takes 150 units at ₦60; Jan 28 issue takes 100 at ₦70 and 50 at ₦60. The 100 units left are the opening stock at ₦50 = ₦5,000.", "100*50"),
    ("B1", "Hard", "Using the simple weighted average of all units received in the month, the value of the closing stock of Product X was",
     "₦6,000", "₦6,200", "₦5,000", "₦7,000",
     "A", "Total cost = 100×50 + 200×60 + 100×70 = 24,000 for 400 units, an average of ₦60 per unit; 100 units × ₦60 = ₦6,000.", "24000/400*100"),
    ("B1", "Hard", "The gross profit on Product X for January 2026 under the FIFO method was",
     "₦11,000", "₦13,000", "₦12,000", "₦6,000",
     "B", "Sales 300 units × ₦100 = 30,000; cost of goods sold = total cost 24,000 − closing stock 7,000 = 17,000; gross profit = ₦13,000.", "30000-(24000-7000)"),
    ("B1", "Medium", "In a period of rising prices such as January 2026, the method that gives Product X the lowest closing stock value and the lowest gross profit is",
     "FIFO", "simple average", "LIFO", "weighted average",
     "C", "LIFO charges the latest, dearest units against sales, leaving the oldest, cheapest units in stock; profit and stock are therefore lowest."),
    # ---------------- B2 control ----------------
    ("B2", "Medium", "The balance of the sales ledger control account of Ola Ventures on 30 June 2026 was",
     "₦285,000", "₦301,000", "₦269,000", "₦293,000",
     "A", "Debits: 210,000 + 640,000 + 12,000 = 862,000. Credits: 520,000 + 14,000 + 26,000 + 9,000 + 8,000 = 577,000. Balance = ₦285,000.", "862000-577000"),
    ("B2", "Easy", "In the sales ledger control account of Ola Ventures, the dishonoured cheque of ₦12,000 is",
     "credited because the customer has paid", "debited because the customer's debt is restored", "ignored because it concerns the bank only", "credited as a bad debt",
     "B", "A bounced cheque cancels the earlier receipt; the customer owes the money again, so the control account is debited."),
    ("B2", "Easy", "The total of the debit side of the sales ledger control account of Ola Ventures for June 2026 was",
     "₦850,000", "₦862,000", "₦874,000", "₦640,000",
     "B", "Opening balance 210,000 + credit sales 640,000 + dishonoured cheque 12,000 = ₦862,000.", "210000+640000+12000"),
    ("B2", "Medium", "The set-off of ₦8,000 in the Ola Ventures records arose because",
     "a customer returned goods that had been invoiced to him in error", "a customer is also a supplier and the amounts owed were netted", "the bank charged commission on cheques lodged during the month", "a debt owed by a customer who had died was written off",
     "B", "A contra (set-off) transfers the balance owed by a person who is both a debtor and a creditor from one ledger to the other; it is credited in the sales ledger control account."),
    ("B2", "Medium", "Which item from the Ola Ventures data would NOT be entered in the sales ledger control account?",
     "returns inwards", "discount allowed", "cash purchases", "bad debts written off",
     "C", "Cash purchases involve neither debtors nor creditors; every other item changes what customers owe."),
    # ---------------- B3 incomplete records ----------------
    ("B3", "Medium", "Tunde's capital on 1 January 2025 was",
     "₦250,000", "₦220,000", "₦190,000", "₦280,000",
     "B", "Opening capital = assets 80,000 + 45,000 + 25,000 + 100,000 − creditors 30,000 = ₦220,000.", "80000+45000+25000+100000-30000"),
    ("B3", "Medium", "Tunde's capital on 31 December 2025, after depreciating the furniture, was",
     "₦230,000", "₦210,000", "₦220,000", "₦270,000",
     "C", "Closing capital = 95,000 + 60,000 + 15,000 + 90,000 (furniture less 10%) − 40,000 = ₦220,000.", "95000+60000+15000+90000-40000"),
    ("B3", "Hard", "Tunde's net profit for 2025 was",
     "₦70,000", "₦170,000", "₦nil", "₦120,000",
     "A", "Profit = closing capital 220,000 − opening capital 220,000 + drawings 120,000 − capital introduced 50,000 = ₦70,000.", "220000-220000+120000-50000"),
    ("B3", "Easy", "The method used to find Tunde's profit from his opening and closing positions is called the",
     "conversion method", "net worth (statement of affairs) method", "gross profit percentage method", "control account method",
     "B", "Where no records of transactions exist, profit is deduced from the increase in net worth adjusted for drawings and capital introduced."),
    ("B3", "Medium", "If Tunde had withdrawn nothing during 2025 and introduced no capital, his closing capital would have been",
     "₦290,000", "₦150,000", "₦220,000", "₦240,000",
     "A", "Closing capital would be opening capital 220,000 + profit 70,000 = ₦290,000.", "220000+70000"),
    # ---------------- B4 manufacturing ----------------
    ("B4", "Easy", "The cost of raw materials consumed by Bright Soap Factory in 2025 was",
     "₦290,000", "₦300,000", "₦310,000", "₦350,000",
     "B", "Opening 40,000 + purchases 300,000 + carriage 10,000 − closing 50,000 = ₦300,000.", "40000+300000+10000-50000"),
    ("B4", "Medium", "The prime cost of Bright Soap Factory for 2025 was",
     "₦480,000", "₦500,000", "₦630,000", "₦520,000",
     "B", "Prime cost = raw materials consumed 300,000 + direct wages 180,000 + direct expenses 20,000 = ₦500,000.", "300000+180000+20000"),
    ("B4", "Easy", "The total factory overheads of Bright Soap Factory for 2025 amounted to",
     "₦200,000", "₦105,000", "₦130,000", "₦155,000",
     "C", "Indirect wages 60,000 + factory rent 45,000 + depreciation of plant 25,000 = ₦130,000. Office salaries are an administrative expense.", "60000+45000+25000"),
    ("B4", "Hard", "The cost of goods manufactured (production cost of finished goods) by Bright Soap Factory in 2025 was",
     "₦620,000", "₦640,000", "₦630,000", "₦710,000",
     "B", "Prime cost 500,000 + factory overheads 130,000 + opening WIP 30,000 − closing WIP 20,000 = ₦640,000.", "500000+130000+30000-20000"),
    ("B4", "Medium", "In the accounts of Bright Soap Factory the office salaries of ₦70,000 are charged to the",
     "manufacturing account as a factory overhead", "trading account as part of cost of sales", "profit and loss account as an administrative expense", "balance sheet as a current liability",
     "C", "Only factory costs go into the manufacturing account; office and selling costs belong in the profit and loss account."),
    # ---------------- B5 club ----------------
    ("B5", "Medium", "The subscription income of Unity Social Club to be credited to the income and expenditure account for 2025 is",
     "₦480,000", "₦455,000", "₦505,000", "₦435,000",
     "B", "480,000 − 30,000 (2026 in advance) − 20,000 (2024 arrears) + 25,000 (2025 still owing) = ₦455,000.", "480000-30000-20000+25000"),
    ("B5", "Medium", "The profit on the bar of Unity Social Club for 2025 was",
     "₦130,000", "₦70,000", "₦80,000", "₦90,000",
     "C", "Bar cost of sales = 30,000 + 220,000 − 40,000 = 210,000; bar profit = 350,000 − 210,000 − barman's wages 60,000 = ₦80,000.", "350000-210000-60000"),
    ("B5", "Easy", "The cash balance of Unity Social Club on 31 December 2025 was",
     "₦330,000", "₦260,000", "₦400,000", "₦480,000",
     "A", "70,000 + 480,000 + 350,000 − (220,000 + 60,000 + 100,000 + 40,000 + 150,000) = ₦330,000.", "70000+480000+350000-570000"),
    ("B5", "Hard", "Ignoring depreciation, the surplus of income over expenditure of Unity Social Club for 2025 was",
     "₦245,000", "₦395,000", "₦260,000", "₦545,000",
     "B", "Income: subscriptions 455,000 + bar profit 80,000 = 535,000. Expenditure: rent 100,000 + honorarium 40,000 = 140,000. Surplus = ₦395,000. The chairs are capital expenditure.", "455000+80000-100000-40000"),
    ("B5", "Easy", "In the balance sheet of Unity Social Club at 31 December 2025, the ₦30,000 subscriptions received for 2026 are shown as",
     "a current asset", "a current liability", "part of the accumulated fund", "income for 2025",
     "B", "Subscriptions received in advance are owed (in membership benefits) to the members and are a liability at the year end."),
    # ---------------- B6 partnership ----------------
    ("B6", "Easy", "The total interest on capital credited to Ade and Bisi for 2025 was",
     "₦40,000", "₦50,000", "₦30,000", "₦60,000",
     "B", "5% of 600,000 = 30,000 for Ade and 5% of 400,000 = 20,000 for Bisi; total ₦50,000.", "0.05*1000000"),
    ("B6", "Medium", "The profit of Ade and Bisi available for sharing in the profit-sharing ratio for 2025 was",
     "₦330,000", "₦346,000", "₦360,000", "₦314,000",
     "B", "500,000 + interest on drawings 16,000 − interest on capital 50,000 − Bisi's salary 120,000 = ₦346,000.", "500000+16000-50000-120000"),
    ("B6", "Medium", "Ade's share of the residual profit for 2025 was",
     "₦207,600", "₦138,400", "₦300,000", "₦173,000",
     "A", "Ade takes 3/5 of 346,000 = ₦207,600.", "346000*3/5"),
    ("B6", "Hard", "Bisi's total earnings from the partnership for 2025, net of interest on drawings, were",
     "₦278,400", "₦258,400", "₦272,400", "₦138,400",
     "C", "Interest on capital 20,000 + salary 120,000 + share of profit 2/5 × 346,000 = 138,400, less interest on drawings 6,000 = ₦272,400.", "20000+120000+138400-6000"),
    ("B6", "Easy", "In the partnership of Ade and Bisi, interest on drawings is",
     "debited to the appropriation account", "credited to the appropriation account", "debited to the profit and loss account as an expense", "credited to the bank account",
     "B", "Interest charged on partners' drawings is income of the firm: it is credited to the appropriation account and debited to the partners' current accounts."),
    # ---------------- B7 company ----------------
    ("B7", "Easy", "After the 2025 issue, the issued share capital of Zenith Foods Plc was",
     "₦6,000,000", "₦9,000,000", "₦10,000,000", "₦7,500,000",
     "A", "Issued capital is recorded at nominal value: 6,000,000 shares × ₦1 = ₦6,000,000. The extra 50 kobo per share is share premium.", "6000000"),
    ("B7", "Medium", "The share premium account of Zenith Foods Plc arising from the issue was",
     "₦3,750,000", "₦9,000,000", "₦3,000,000", "₦1,500,000",
     "C", "Premium = (1.50 − 1.00) × 6,000,000 shares allotted = ₦3,000,000.", "0.5*6000000"),
    ("B7", "Medium", "The amount refunded by Zenith Foods Plc to unsuccessful applicants was",
     "₦1,500,000", "₦2,250,000", "₦750,000", "₦3,000,000",
     "B", "Excess applications = 7,500,000 − 6,000,000 = 1,500,000 shares × ₦1.50 = ₦2,250,000.", "1500000*1.5"),
    ("B7", "Easy", "The annual interest payable by Zenith Foods Plc on its debentures is",
     "₦100,000", "₦200,000", "₦600,000", "₦20,000",
     "B", "10% of ₦2,000,000 = ₦200,000, charged in the profit and loss account whether or not a profit is made.", "0.1*2000000"),
    ("B7", "Medium", "The unissued share capital of Zenith Foods Plc after the issue was",
     "₦4,000,000", "₦2,500,000", "₦3,000,000", "₦6,000,000",
     "A", "Authorised 10,000,000 shares − issued 6,000,000 shares = 4,000,000 shares of ₦1 = ₦4,000,000.", "10000000-6000000"),
    ("B7", "Hard", "The debenture holders of Zenith Foods Plc differ from its ordinary shareholders in that debenture holders",
     "receive dividends only when profits are made", "are creditors of the company entitled to fixed interest", "have voting rights at the annual general meeting", "are the last to be paid if the company is wound up",
     "B", "Debentures are loans: holders are creditors who receive fixed interest and rank before shareholders on winding up; they do not vote."),
    # ---------------- B8 local government ----------------
    ("B8", "Easy", "The total budgeted revenue of the local government for 2025 was",
     "₦1,150 million", "₦1,300 million", "₦1,050 million", "₦1,250 million",
     "B", "900 + 250 + 150 = ₦1,300 million.", "900+250+150"),
    ("B8", "Easy", "The budgeted recurrent expenditure of the local government for 2025 was",
     "₦800 million", "₦1,250 million", "₦450 million", "₦750 million",
     "A", "Recurrent expenditure = personnel costs 500 + overhead costs 300 = ₦800 million; capital projects are capital expenditure.", "500+300"),
    ("B8", "Medium", "The budgeted overall surplus of the local government for 2025 was",
     "₦500 million", "₦50 million", "₦100 million", "₦450 million",
     "B", "Total revenue 1,300 − total expenditure (800 + 450 = 1,250) = ₦50 million.", "1300-1250"),
    ("B8", "Medium", "In the local government budget, the statutory allocation represents",
     "money borrowed from commercial banks", "the local government's share of the Federation Account", "fees collected from market traders", "grants from foreign donors",
     "B", "Statutory allocations are the constitutionally fixed shares of federally collected revenue distributed to the three tiers of government."),
    ("B8", "Easy", "Which item in the local government budget is classified as capital expenditure?",
     "personnel costs", "overhead costs", "capital projects", "share of value added tax",
     "C", "Spending on roads, buildings and other long-lived assets is capital expenditure; salaries and overheads are recurrent."),
    # ---------------- B9 departmental ----------------
    ("B9", "Easy", "The gross profit of Department A of Crown Stores for 2025 was",
     "₦220,000", "₦240,000", "₦170,000", "₦260,000",
     "B", "Cost of sales A = 50,000 + 380,000 − 70,000 = 360,000; gross profit = 600,000 − 360,000 = ₦240,000.", "600000-360000"),
    ("B9", "Easy", "The gross profit of Department B of Crown Stores for 2025 was",
     "₦160,000", "₦150,000", "₦180,000", "₦120,000",
     "A", "Cost of sales B = 30,000 + 250,000 − 40,000 = 240,000; gross profit = 400,000 − 240,000 = ₦160,000.", "400000-240000"),
    ("B9", "Medium", "The rent charged to Department B of Crown Stores was",
     "₦60,000", "₦50,000", "₦40,000", "₦36,000",
     "C", "Rent is shared 3:2 on floor area, so Department B bears 2/5 × 100,000 = ₦40,000.", "100000*2/5"),
    ("B9", "Medium", "The salaries charged to Department A of Crown Stores were",
     "₦45,000", "₦54,000", "₦36,000", "₦60,000",
     "B", "Salaries are apportioned on sales 600:400 = 3:2, so Department A bears 3/5 × 90,000 = ₦54,000.", "90000*3/5"),
    ("B9", "Hard", "The net profit of Department A of Crown Stores for 2025 was",
     "₦126,000", "₦84,000", "₦140,000", "₦150,000",
     "A", "Gross profit 240,000 − rent 60,000 − salaries 54,000 = ₦126,000.", "240000-60000-54000"),
]

Q = [
    # ---------------- Stock valuation ----------------
    (T_STK, "Easy", "Under the FIFO method of stock valuation, closing stock is made up of the",
     "earliest purchases", "most recent purchases", "cheapest purchases", "average of all purchases",
     "B", "First in, first out assumes the oldest units are sold first, so what remains is the latest bought."),
    (T_STK, "Easy", "Closing stock is valued at the lower of cost and net realisable value in obedience to the",
     "consistency concept", "prudence concept", "going concern concept", "entity concept",
     "B", "Prudence requires that stock is not carried above the amount it is expected to realise."),
    (T_STK, "Medium", "Net realisable value of stock is",
     "the original purchase price plus carriage", "the expected selling price less costs still to be incurred to sell it", "the replacement cost on the balance sheet date", "the insured value of the goods",
     "B", "NRV = estimated selling price − further costs of completion and selling."),
    (T_STK, "Medium", "An overstatement of closing stock in 2025 will",
     "understate the profit of 2025 and overstate the profit of 2026", "overstate the profit of 2025 and understate the profit of 2026", "overstate the profits of both 2025 and 2026", "have no effect on the profit of either year",
     "B", "Closing stock reduces cost of sales in 2025 (profit up) and becomes the opening stock of 2026 (profit down); the error cancels over two years."),
    (T_STK, "Medium", "A trader bought 500 units at ₦40 and later 300 units at ₦50. He sold 600 units. Under FIFO the cost of goods sold was",
     "₦25,000", "₦26,000", "₦27,000", "₦30,000",
     "A", "FIFO: 500 × 40 = 20,000 plus 100 × 50 = 5,000; total ₦25,000.", "500*40+100*50"),
    (T_STK, "Medium", "A trader bought 500 units at ₦40 and later 300 units at ₦50 and sold 600 units. Under LIFO the closing stock was",
     "₦10,000", "₦8,000", "₦9,000", "₦15,000",
     "B", "LIFO issues the 300 dearer units first, then 300 of the ₦40 units, leaving 200 × ₦40 = ₦8,000.", "200*40"),
    (T_STK, "Hard", "Opening stock 200 units at ₦30; purchases 400 units at ₦36 and 400 units at ₦45; 700 units were sold. Using the weighted average cost of all units, closing stock is valued at",
     "₦11,520", "₦13,500", "₦9,000", "₦10,800",
     "A", "Total cost = 6,000 + 14,400 + 18,000 = 38,400 for 1,000 units, an average of ₦38.40 per unit; the 300 units left are valued at 300 × 38.40 = ₦11,520.", "300*38.4"),
    (T_STK, "Easy", "The method of stock valuation that is not permitted under International Financial Reporting Standards is",
     "FIFO", "weighted average", "LIFO", "specific identification",
     "C", "IAS 2 prohibits LIFO because it can carry stock at outdated costs; FIFO, weighted average and specific identification are allowed."),
    (T_STK, "Medium", "Which method of stock valuation is most suitable for a car dealer who can trace the cost of each vehicle?",
     "specific identification", "FIFO", "LIFO", "simple average",
     "A", "When individual items are large, distinct and traceable, each is valued at its own actual cost."),
    (T_STK, "Easy", "Stock-taking is the",
     "physical counting and listing of goods on hand at a date", "sale of slow-moving goods at a discount", "recording of purchases in the day book", "transfer of goods between branches",
     "A", "A physical count at the year end establishes the quantities to be valued as closing stock."),
    (T_STK, "Medium", "Goods costing ₦20,000 were sent to a customer on sale or return and had not been accepted by the year end. At the year end these goods should be",
     "excluded from stock and treated as a sale", "included in the seller's closing stock at cost", "included in stock at selling price", "written off as a bad debt",
     "B", "Until the customer accepts them the goods still belong to the seller and remain part of his stock at cost."),
    (T_STK, "Hard", "A trader's closing stock at cost was ₦300,000, but an item costing ₦40,000 could only be sold for ₦28,000. Stock should be valued at",
     "₦300,000", "₦288,000", "₦272,000", "₦260,000",
     "B", "The damaged item is reduced from 40,000 to its NRV of 28,000, a fall of 12,000; stock = 300,000 − 12,000 = ₦288,000.", "300000-12000"),
    (T_STK, "Medium", "During a period of rising prices, the method that reports the highest closing stock value is",
     "LIFO", "FIFO", "weighted average", "simple average",
     "B", "FIFO leaves the most recently bought, dearest units in stock."),
    (T_STK, "Easy", "The cost of stock includes",
     "the purchase price and costs of bringing it to its present location", "the selling and distribution costs expected when it is sold", "the profit margin the business expects to earn on its sale", "the cost of abnormal wastage and idle time in the factory",
     "A", "Cost comprises purchase price, import duties, carriage inwards and conversion costs; selling costs are excluded."),
    (T_STK, "Medium", "The cost of stock destroyed by fire in a warehouse is",
     "included in closing stock at its full cost", "charged as a loss in the profit and loss account", "added to the purchases figure for the year", "deducted from the sales figure for the year",
     "B", "Destroyed goods no longer exist at the year end; their cost (less any insurance recovery) is written off as a loss."),
    # ---------------- Control accounts ----------------
    (T_CTL, "Easy", "A sales ledger control account is also called a",
     "purchases ledger control account", "total debtors account", "total creditors account", "suspense account",
     "B", "It summarises all the personal accounts of debtors in the sales ledger."),
    (T_CTL, "Easy", "The main purpose of control accounts is to",
     "replace the sales and purchases ledgers so that personal accounts are no longer needed", "check the arithmetical accuracy of the sales and purchases ledgers and locate errors quickly", "calculate the gross profit of the business without preparing a trading account", "record the cash and bank transactions of the business in summary form",
     "B", "The control account balance should equal the total of the individual ledger balances; any difference signals an error in that ledger."),
    (T_CTL, "Medium", "Which of the following is entered on the credit side of the purchases ledger control account?",
     "returns outwards", "discount received", "credit purchases", "cash paid to suppliers",
     "C", "Credit purchases increase the amount owed to suppliers, so they are credited; the other three reduce the liability and are debited."),
    (T_CTL, "Medium", "Which of the following appears on the debit side of the sales ledger control account?",
     "discount allowed", "returns inwards", "cash received from customers", "credit sales",
     "D", "Credit sales increase debtors and are debited; receipts, discounts and returns reduce debtors and are credited."),
    (T_CTL, "Medium", "The source of the credit sales figure in the sales ledger control account is the",
     "total of the sales day book", "cash book", "purchases day book", "individual customers' accounts",
     "A", "Control accounts are built from the totals of the books of original entry, not from the personal accounts."),
    (T_CTL, "Hard", "Opening creditors ₦150,000; credit purchases ₦720,000; payments to suppliers ₦650,000; discount received ₦18,000; returns outwards ₦22,000. The closing creditors balance is",
     "₦180,000", "₦220,000", "₦160,000", "₦200,000",
     "A", "150,000 + 720,000 − 650,000 − 18,000 − 22,000 = ₦180,000.", "150000+720000-650000-18000-22000"),
    (T_CTL, "Medium", "A credit balance on a sales ledger control account may arise when",
     "a customer has overpaid or paid for goods later returned", "a supplier has been paid in advance for goods not yet delivered", "goods are sold for cash to a customer who also buys on credit", "bad debts are written off against the provision for doubtful debts",
     "A", "Overpayments and credit notes issued after payment leave the customer as a creditor of the business."),
    (T_CTL, "Medium", "The total of the sales ledger balances exceeds the balance on the sales ledger control account. Which error could explain the difference?",
     "an invoice omitted from the sales day book but posted to the customer's account", "the sales day book overcast", "cash received from a debtor not recorded anywhere", "a credit sale omitted from both the day book and the ledger",
     "A", "An invoice posted to the personal account but missing from the day book total makes the ledger total larger than the control account."),
    (T_CTL, "Easy", "Bad debts written off are recorded in the sales ledger control account on the",
     "debit side", "credit side", "both sides", "neither side",
     "B", "Writing off a debt reduces total debtors, so the control account is credited."),
    (T_CTL, "Medium", "Interest charged to a customer on an overdue account is",
     "credited to the sales ledger control account", "debited to the sales ledger control account", "debited to the purchases ledger control account", "ignored in the control accounts",
     "B", "Interest increases what the customer owes, so debtors (and the control account) are debited."),
    (T_CTL, "Easy", "Discount received from suppliers is recorded in the purchases ledger control account on the",
     "credit side", "debit side", "balance line", "memorandum column",
     "B", "Discount received reduces the amount owed to suppliers and is debited in the total creditors account."),
    (T_CTL, "Hard", "The sales ledger control account shows a balance of ₦520,000 but the list of debtors totals ₦512,000. It is then found that the sales day book was overcast by ₦8,000. After correction the",
     "control account balance falls to ₦512,000 and agrees with the list", "list of debtors rises to ₦520,000 and agrees with the control account", "difference between the two figures becomes ₦16,000", "control account balance rises to ₦528,000 and the difference doubles",
     "A", "An overcast day book inflates the control account only; correcting it reduces the control balance by 8,000 to ₦512,000."),
    (T_CTL, "Easy", "A provision for doubtful debts is",
     "entered in the sales ledger control account", "not entered in the sales ledger control account", "entered in the purchases ledger control account", "entered in the cash book",
     "B", "The provision is a general estimate kept in a separate account; it does not alter any individual debtor's balance or the control account."),
    (T_CTL, "Medium", "The person who keeps the sales ledger should not also keep the sales ledger control account because",
     "it would be too much work for one clerk to handle in a single day", "the control account is a check on the ledger and independence detects fraud and error", "the control account must by law be kept by the bank on behalf of the business", "the auditor is required to keep the control account personally",
     "B", "Separating the duties makes it harder to conceal errors or misappropriation in the debtors' ledger."),
    (T_CTL, "Medium", "Cash sales are",
     "debited to the sales ledger control account", "credited to the sales ledger control account", "not entered in the sales ledger control account", "credited to the purchases ledger control account",
     "C", "Only credit transactions with customers pass through the debtors' control account; cash sales create no debtor."),
    # ---------------- Incomplete records ----------------
    (T_INC, "Easy", "Single entry is a system in which",
     "every transaction is recorded twice, once on each side of the ledger", "only some aspects of transactions, usually cash and personal accounts, are recorded", "only the fixed assets of the business are recorded in a register", "records are kept only by limited companies and never by sole traders",
     "B", "Small traders often keep a cash book and records of debtors and creditors without a complete double entry system."),
    (T_INC, "Medium", "A trader's capital increased from ₦400,000 to ₦520,000 during a year in which he withdrew ₦90,000 and introduced no new capital. His profit for the year was",
     "₦120,000", "₦210,000", "₦30,000", "₦610,000",
     "B", "Profit = increase in capital 120,000 + drawings 90,000 = ₦210,000.", "120000+90000"),
    (T_INC, "Medium", "A trader's net assets fell from ₦300,000 to ₦280,000 during a year in which his drawings were ₦60,000 and he introduced ₦10,000 capital. His result for the year was a",
     "profit of ₦30,000", "loss of ₦30,000", "profit of ₦70,000", "loss of ₦70,000",
     "A", "Profit = −20,000 + 60,000 − 10,000 = ₦30,000.", "-20000+60000-10000"),
    (T_INC, "Easy", "A statement of affairs is prepared under incomplete records in order to find the",
     "credit sales for the year", "capital at a given date", "gross profit for the year", "bank balance",
     "B", "Listing assets and liabilities at a date gives the capital (net worth) at that date."),
    (T_INC, "Medium", "Opening debtors ₦50,000; cash received from debtors ₦610,000; closing debtors ₦70,000; discount allowed ₦5,000. Credit sales for the year were",
     "₦635,000", "₦595,000", "₦630,000", "₦585,000",
     "A", "Credit sales = receipts 610,000 + discount 5,000 + closing debtors 70,000 − opening debtors 50,000 = ₦635,000.", "610000+5000+70000-50000"),
    (T_INC, "Medium", "Opening creditors ₦40,000; payments to suppliers ₦380,000; closing creditors ₦55,000. Credit purchases for the year were",
     "₦365,000", "₦395,000", "₦420,000", "₦325,000",
     "B", "Purchases = payments 380,000 + closing creditors 55,000 − opening creditors 40,000 = ₦395,000.", "380000+55000-40000"),
    (T_INC, "Hard", "A trader's sales were ₦840,000 at a uniform mark-up of 40% on cost. Opening stock was ₦60,000 and purchases ₦620,000. Closing stock was",
     "₦80,000", "₦176,000", "₦92,000", "₦104,000",
     "A", "Cost of sales = 840,000 ÷ 1.4 = 600,000; closing stock = 60,000 + 620,000 − 600,000 = ₦80,000.", "60000+620000-840000/1.4"),
    (T_INC, "Hard", "A trader's stock was destroyed by fire. Sales up to the fire were ₦450,000 at a gross margin of 20% on sales; opening stock ₦70,000; purchases ₦360,000. The cost of stock destroyed was",
     "₦70,000", "₦90,000", "₦40,000", "₦110,000",
     "A", "Cost of sales = 80% of 450,000 = 360,000; stock at the date of fire = 70,000 + 360,000 − 360,000 = ₦70,000.", "70000+360000-450000*0.8"),
    (T_INC, "Easy", "The conversion of single entry to double entry involves",
     "preparing control accounts for debtors and creditors to find credit sales and purchases", "closing down the business and selling all its assets to start afresh", "writing off all the debtors of the business as bad debts", "ignoring all the cash transactions of the business for the period",
     "A", "Total debtors and total creditors accounts, together with the cash summary, reconstruct the missing figures."),
    (T_INC, "Medium", "A trader banked all takings after paying wages of ₦120,000 and drawings of ₦80,000 in cash. Bankings were ₦900,000. His total cash sales were",
     "₦1,100,000", "₦900,000", "₦1,020,000", "₦700,000",
     "A", "Cash sales = amount banked 900,000 + cash used before banking (120,000 + 80,000) = ₦1,100,000.", "900000+120000+80000"),
    (T_INC, "Medium", "Which of the following is a disadvantage of the single entry system?",
     "it is cheap to operate and needs few books", "a trial balance cannot be extracted so errors are hard to detect", "it records every transaction twice and wastes time", "it needs a qualified accountant to operate it every day",
     "B", "Without complete double entry there is no arithmetical check, and profit can only be estimated."),
    (T_INC, "Hard", "A trader had opening capital ₦250,000 and closing capital ₦310,000. During the year he took goods costing ₦15,000 for his family and cash of ₦45,000, and he won ₦100,000 in a lottery which he paid into the business. His profit was",
     "₦20,000", "₦120,000", "₦220,000", "₦160,000",
     "A", "Profit = 60,000 increase + drawings 60,000 − capital introduced 100,000 = ₦20,000.", "60000+60000-100000"),
    # ---------------- Manufacturing accounts ----------------
    (T_MFG, "Easy", "Prime cost consists of",
     "direct materials, direct labour and direct expenses", "factory overheads and office expenses", "raw materials and factory rent", "direct wages and depreciation of office furniture",
     "A", "Prime cost is the total of all direct costs of production."),
    (T_MFG, "Easy", "Which of the following is a factory overhead?",
     "salary of the factory supervisor", "raw materials used", "wages of machine operators", "advertising of finished goods",
     "A", "Supervisors' salaries are indirect labour, part of factory overheads; materials and operators' wages are direct costs."),
    (T_MFG, "Medium", "Work in progress at the end of the year is",
     "deducted in the manufacturing account", "added in the manufacturing account", "shown in the trading account", "ignored until the goods are finished",
     "A", "Closing work in progress represents cost not yet turned into finished goods, so it is deducted (and opening WIP added) to arrive at the cost of goods completed."),
    (T_MFG, "Medium", "The cost of production of finished goods is transferred from the manufacturing account to the",
     "profit and loss account", "trading account", "balance sheet", "capital account",
     "B", "The trading account uses the cost of goods manufactured in place of purchases."),
    (T_MFG, "Medium", "Raw materials consumed = ₦400,000; direct wages ₦250,000; royalties per unit produced ₦30,000; factory power ₦45,000. Prime cost was",
     "₦680,000", "₦650,000", "₦725,000", "₦695,000",
     "A", "Royalties based on output are a direct expense: 400,000 + 250,000 + 30,000 = ₦680,000. Factory power is an overhead.", "400000+250000+30000"),
    (T_MFG, "Hard", "A factory transfers goods to the warehouse at cost plus 20%. Cost of production was ₦900,000. The manufacturing profit and the transfer price are",
     "₦180,000 and ₦1,080,000", "₦150,000 and ₦1,050,000", "₦180,000 and ₦900,000", "₦200,000 and ₦1,100,000",
     "A", "20% of 900,000 = 180,000 manufacturing profit; transfer price = ₦1,080,000."),
    (T_MFG, "Easy", "In a manufacturing business, the three classes of stock are",
     "raw materials, work in progress and finished goods", "opening, closing and average stock", "cash, debtors and creditors", "direct, indirect and overhead stock",
     "A", "Each class is valued separately at the year end and shown under current assets."),
    (T_MFG, "Medium", "Which of the following is a direct expense of production?",
     "hire of a special machine for a particular job", "factory rent", "depreciation of factory building", "salary of the works manager",
     "A", "Costs traceable to a specific product or job are direct; rent, depreciation and management salaries are indirect."),
    (T_MFG, "Medium", "Carriage inwards on raw materials is",
     "added to the cost of raw materials consumed", "treated as a factory overhead", "charged to the profit and loss account", "deducted from purchases",
     "A", "Delivery costs of materials are part of the cost of getting them to the factory, so they increase the direct materials cost."),
    (T_MFG, "Hard", "Purchases of raw materials ₦500,000; returns outwards ₦20,000; opening raw materials ₦60,000; closing raw materials ₦80,000; direct wages ₦300,000; factory overheads ₦150,000; opening WIP ₦40,000; closing WIP ₦70,000. Cost of goods manufactured was",
     "₦880,000", "₦940,000", "₦910,000", "₦850,000",
     "A", "Materials 60,000 + 480,000 − 80,000 = 460,000; prime cost 760,000; + overheads 150,000 = 910,000; + WIP 40,000 − 70,000 = ₦880,000.", "460000+300000+150000+40000-70000"),
    (T_MFG, "Easy", "A manufacturing account is prepared to ascertain the",
     "cost of goods produced", "gross profit on sales", "net profit of the firm", "capital of the owner",
     "A", "It collects the factory costs of the period to arrive at the cost of finished goods produced."),
    (T_MFG, "Medium", "Which item appears in the profit and loss account and not in the manufacturing account of a factory?",
     "factory insurance", "salesmen's commission", "lubricants for machines", "factory lighting",
     "B", "Selling costs such as commission are not costs of manufacturing; they are charged against gross profit."),
    (T_MFG, "Medium", "The reason a manufacturer may add a profit loading when transferring goods to the trading account is to",
     "increase the total profit of the business for the year", "show whether it is cheaper to make the goods or to buy them from outside", "reduce the amount of tax payable on the profit of the year", "value the closing stock of finished goods at selling price",
     "B", "Transferring at market value reveals a separate manufacturing profit and lets management compare making with buying."),
    (T_MFG, "Hard", "Finished goods are transferred at cost plus 25%. Closing stock of finished goods at transfer price is ₦250,000. The provision for unrealised profit on the closing stock is",
     "₦62,500", "₦50,000", "₦40,000", "₦31,250",
     "B", "Unrealised profit = 250,000 × 25/125 = ₦50,000, which must be removed so that stock is shown at cost.", "250000*25/125"),
    # ---------------- Not-for-profit ----------------
    (T_NFP, "Easy", "The receipts and payments account of a club is equivalent to a trader's",
     "trading account", "cash book summary", "profit and loss account", "balance sheet",
     "B", "It is a summary of the cash and bank transactions of the period, including capital items."),
    (T_NFP, "Easy", "The income and expenditure account of a club corresponds to a trader's",
     "profit and loss account", "cash book", "balance sheet", "trial balance",
     "A", "It matches the period's revenue income against revenue expenditure on the accrual basis to find the surplus or deficit."),
    (T_NFP, "Easy", "The excess of income over expenditure of a club is called",
     "net profit", "surplus", "gross profit", "capital",
     "B", "Non-trading organisations speak of a surplus (or deficit), not profit or loss."),
    (T_NFP, "Easy", "The capital of a club or society is usually called the",
     "share capital", "accumulated fund", "working capital", "reserve fund",
     "B", "The accumulated fund is the excess of assets over liabilities, built up from surpluses over the years."),
    (T_NFP, "Medium", "Subscriptions in arrears at the year end are shown in the balance sheet of a club as",
     "a current liability", "a current asset", "part of the accumulated fund", "a deduction from subscriptions income",
     "B", "Amounts owed by members are receivable by the club, hence a current asset (subject to prudence)."),
    (T_NFP, "Medium", "A one-off large donation received by a club for the building of a new hall should be",
     "credited to income and expenditure account", "capitalised and shown as a special fund on the balance sheet", "treated as subscription income", "used to pay the secretary's honorarium",
     "B", "Donations for a specific capital purpose are not income of the year; they are credited to a building fund."),
    (T_NFP, "Medium", "Entrance fees of new members are usually treated as",
     "revenue income of the year, unless the club decides to capitalise them", "a loan to the club repayable when the member leaves", "an expense of the club charged to income and expenditure", "a deduction from the accumulated fund at the year end",
     "A", "Small recurring entrance fees are treated as income; where they are large and non-recurring they may be capitalised."),
    (T_NFP, "Hard", "Subscriptions received in 2025 were ₦600,000. Arrears at the start of 2025 were ₦40,000 and at the end ₦55,000; advances at the start were ₦20,000 and at the end ₦35,000. Subscription income for 2025 was",
     "₦600,000", "₦615,000", "₦585,000", "₦630,000",
     "A", "600,000 − 40,000 + 55,000 + 20,000 − 35,000 = ₦600,000.", "600000-40000+55000+20000-35000"),
    (T_NFP, "Medium", "Life membership fees received by a club are best treated as",
     "income of the year in which they are received", "a liability to be released to income over the expected membership period", "a fixed asset of the club shown in the balance sheet", "a deduction from the expenditure of the year of receipt",
     "B", "The member has paid in advance for many years' benefits, so the fee is spread over the estimated period."),
    (T_NFP, "Medium", "A club's bar or canteen trading result is calculated in a",
     "receipts and payments account together with the other cash items", "separate bar trading account whose profit is transferred to income and expenditure", "statement of affairs prepared at the beginning of the year", "subscription account along with the members' subscriptions",
     "B", "Trading activities are accounted for separately; only the bar profit (or loss) enters the income and expenditure account."),
    (T_NFP, "Easy", "The honorarium paid to a club secretary is",
     "capital expenditure added to the fixed assets", "revenue expenditure charged to the income and expenditure account", "a distribution of the surplus to one of the members", "a deduction from the subscriptions received in the year",
     "B", "An honorarium is a payment for services to the club and is an expense of the year."),
    (T_NFP, "Hard", "A club had an accumulated fund of ₦850,000 at the start of the year. It made a deficit of ₦60,000 and received a legacy of ₦200,000 which it capitalised. Its accumulated fund at the year end was",
     "₦990,000", "₦1,110,000", "₦790,000", "₦1,050,000",
     "A", "850,000 − 60,000 + 200,000 = ₦990,000.", "850000-60000+200000"),
    (T_NFP, "Easy", "Which of the following is a not-for-profit organisation?",
     "a partnership of lawyers", "a public limited company", "an old students' association", "a sole trader",
     "C", "Clubs, societies, associations and charities exist to serve their members or the public, not to earn profit for owners."),
    (T_NFP, "Medium", "The purchase of a lawn mower by a sports club is recorded in the",
     "receipts and payments account and the balance sheet", "income and expenditure account only", "subscription account", "bar trading account",
     "A", "As a cash payment it appears in the receipts and payments account; as capital expenditure it becomes a fixed asset, with only depreciation charged to income and expenditure."),
]

Q += [
    # ---------------- Departmental accounts ----------------
    (T_DPT, "Easy", "Departmental accounts are prepared mainly to",
     "show the profit or loss made by each department separately", "reduce the total expenses of the business", "calculate the salary of the general manager", "value the closing stock of the whole business",
     "A", "Separate results show which departments are profitable and help management decide on expansion or closure."),
    (T_DPT, "Medium", "The most suitable basis for apportioning rent between departments is",
     "sales of each department", "floor area occupied by each department", "number of employees in each department", "purchases of each department",
     "B", "Rent is a cost of space, so floor area is the fairest basis."),
    (T_DPT, "Medium", "The most suitable basis for apportioning advertising expenses between departments is",
     "floor area", "number of light bulbs", "sales of each department", "value of fixed assets",
     "C", "Advertising promotes sales, so the benefit is assumed to follow sales value."),
    (T_DPT, "Medium", "Depreciation of departmental equipment is best apportioned on the basis of",
     "the value of the equipment in each department", "the sales made by each department", "the number of staff in each department", "the floor area occupied by each department",
     "A", "The charge follows the asset that causes it."),
    (T_DPT, "Hard", "Electricity of ₦120,000 is to be shared among departments X, Y and Z in the ratio of floor area 5:3:2. Department Y's share is",
     "₦60,000", "₦24,000", "₦36,000", "₦40,000",
     "C", "Y's share = 3/10 × 120,000 = ₦36,000.", "120000*3/10"),
    (T_DPT, "Easy", "Expenses that cannot reasonably be apportioned among departments should be",
     "ignored when preparing the accounts", "charged against the combined profit of all departments", "charged to the department with the largest sales", "capitalised and shown as an asset",
     "B", "Unallocable items such as the general manager's salary are deducted in the general profit and loss account."),
    (T_DPT, "Medium", "Goods transferred from Department P to Department Q at cost are recorded by",
     "debit Department Q purchases, credit Department P purchases (or sales)", "debit Department P, credit cash", "debit sales, credit Department Q", "no entry, since the goods remain in the business",
     "A", "Inter-departmental transfers must be recorded so that each department's cost of sales and gross profit are correct."),
    (T_DPT, "Medium", "The advantage of departmental accounts to management is that they",
     "eliminate the need for a balance sheet at the end of the year", "reveal loss-making departments so that corrective action can be taken", "reduce the amount of tax payable by the business as a whole", "remove the need for stock-taking in each of the departments",
     "B", "Comparing departmental gross profit ratios highlights weak departments and helps in planning."),
    # ---------------- Branch accounts ----------------
    (T_BRN, "Easy", "When the head office keeps all the accounting records of a branch, the branch stock is usually invoiced at",
     "cost or selling price, as decided by head office", "the branch manager's estimate", "the market value at the year end", "the historical cost of head office premises",
     "A", "Goods may be sent at cost, at cost plus a fixed percentage, or at selling price to control the branch."),
    (T_BRN, "Medium", "Goods are sent to a branch at cost plus 25%. Goods invoiced to the branch amounted to ₦500,000. The cost of these goods was",
     "₦375,000", "₦400,000", "₦425,000", "₦450,000",
     "B", "500,000 × 100/125 = ₦400,000.", "500000*100/125"),
    (T_BRN, "Medium", "The main purpose of invoicing goods to a branch at selling price is to",
     "increase the profit reported by the branch", "enable head office to check the branch stock and detect losses", "reduce the price paid by customers of the branch", "avoid paying tax on the sales made by the branch",
     "B", "Since all sales should be at the invoice price, any difference between expected and actual stock reveals shortages or pilferage."),
    (T_BRN, "Hard", "A branch receives goods invoiced at selling price. Opening stock ₦60,000, goods received ₦540,000, sales ₦520,000, closing stock ₦70,000 (all at selling price). The stock shortage was",
     "₦10,000", "₦20,000", "₦30,000", "nil",
     "A", "Expected closing stock = 60,000 + 540,000 − 520,000 = 80,000; actual 70,000; shortage ₦10,000.", "60000+540000-520000-70000"),
    (T_BRN, "Medium", "In the head office books, the branch stock account is",
     "a real account showing stock held at the branch", "a personal account of the branch manager", "a nominal account for branch expenses", "part of the cash book",
     "A", "Branch stock account records the goods held at the branch (at cost or invoice price)."),
    (T_BRN, "Medium", "Where goods are sent to a branch at cost plus a mark-up, the unrealised profit in closing branch stock is",
     "credited to the branch adjustment account and carried forward", "treated as part of the branch profit for the year", "added to the sales figure of the head office", "written off as a bad debt in the head office books",
     "A", "The loading on unsold stock has not been realised, so it is kept back in the branch adjustment (mark-up) account."),
    (T_BRN, "Easy", "Cash remitted by a branch to head office is recorded in the head office books by",
     "debit bank, credit branch account", "debit branch account, credit bank", "debit branch expenses, credit bank", "debit bank, credit sales",
     "A", "Head office receives cash (debit bank) and the branch's indebtedness falls (credit branch account)."),
    (T_BRN, "Medium", "A branch that keeps its own complete set of books records goods received from head office by",
     "debit goods from head office (purchases), credit head office current account", "debit head office current account, credit branch sales account", "debit cash account, credit goods from head office (purchases)", "debit head office current account, credit bank account",
     "A", "The head office current account in the branch books shows what the branch owes head office."),
    (T_BRN, "Hard", "At the year end the head office current account in the branch books shows ₦900,000 while the branch current account in the head office books shows ₦950,000. The difference is most likely due to",
     "cash or goods in transit between the two", "an error in the branch stock count", "the branch making a loss", "unrealised profit on closing stock",
     "A", "Items sent by one party but not yet received and recorded by the other create temporary differences that must be reconciled."),
    (T_BRN, "Easy", "Branch accounts differ from departmental accounts in that a branch",
     "is located away from the head office", "sells only to the head office", "has no stock of its own", "prepares no records at all",
     "A", "Departments operate under one roof; branches are geographically separate outlets or units of the same business."),
    # ---------------- Partnership ----------------
    (T_PTN, "Easy", "In the absence of a partnership agreement, profits and losses are shared",
     "in proportion to capital contributed", "equally", "in proportion to time spent in the business", "as the senior partner decides",
     "B", "The Partnership Act provides for equal sharing where the partners have not agreed otherwise."),
    (T_PTN, "Easy", "In the absence of a partnership agreement, a loan by a partner to the firm attracts interest at",
     "10% per annum", "5% per annum", "no interest", "the bank rate",
     "B", "Under the Partnership Act a partner is entitled to 5% per annum on advances beyond his agreed capital, but no interest on capital and no salary."),
    (T_PTN, "Medium", "Interest on partners' capital is provided in order to",
     "reward the partners for the work they do in the firm", "compensate partners fairly when capital contributions differ", "increase the total profit of the firm for the year", "reduce the tax payable by the partners on their shares",
     "B", "Without it, a partner who contributes more capital would be disadvantaged if profits were shared in some other ratio."),
    (T_PTN, "Medium", "A partner's salary is",
     "an expense charged in the profit and loss account", "an appropriation of profit debited in the appropriation account", "a drawing debited to the capital account", "a loan repayment",
     "B", "Salaries to partners are a way of dividing profit, not a cost of earning it."),
    (T_PTN, "Easy", "Where fixed capital accounts are kept, a partner's share of profit, salary and interest are credited to his",
     "capital account", "current account", "drawings account", "loan account",
     "B", "Fixed capital accounts change only when capital is introduced or withdrawn; all other entries go through current accounts."),
    (T_PTN, "Medium", "A debit balance on a partner's current account means that the partner",
     "has drawn more than his total entitlement", "has undrawn profits in the firm", "owns more capital than the others", "has lent money to the firm",
     "A", "The partner has overdrawn his share of profits, salary and interest and effectively owes the firm."),
    (T_PTN, "Hard", "X and Y share profits 2:1. Net profit was ₦360,000 after charging interest of ₦20,000 on a loan from X. Interest on capital was ₦30,000 for X and ₦15,000 for Y. X's total income from the firm for the year was",
     "₦260,000", "₦240,000", "₦210,000", "₦230,000",
     "A", "Residual = 360,000 − 45,000 = 315,000; X's share 2/3 = 210,000; plus interest on capital 30,000 and loan interest 20,000 = ₦260,000.", "210000+30000+20000"),
    (T_PTN, "Medium", "Goodwill is created in the books when a new partner is admitted in order to",
     "give the new partner a share of the profits earned before he joined", "compensate the old partners for the share of the firm's reputation the new partner will enjoy", "increase the cash resources of the firm at the date of admission", "reduce the capital accounts of the old partners to the level of the new one",
     "B", "Goodwill built up by the old partners is credited to them in the old ratio before the new partner shares in future profits."),
    (T_PTN, "Hard", "A and B share profits 3:2. They admit C who takes a one-fifth share. Goodwill is valued at ₦200,000 and is not to remain in the books. The net effect on A's capital account is",
     "a credit of ₦120,000 and a debit of ₦96,000", "a credit of ₦120,000 only", "a debit of ₦40,000 only", "a credit of ₦96,000 and a debit of ₦120,000",
     "A", "Goodwill raised is credited in the old ratio (A 3/5 × 200,000 = 120,000); written off in the new ratio A:B:C = 12:8:5, A bears 12/25 × 200,000 = 96,000."),
    (T_PTN, "Medium", "On admission of a new partner, the revaluation of assets is carried out so that",
     "the new partner can buy his share of the assets at a cheaper price", "profits or losses on assets up to the date of admission accrue only to the old partners", "the firm can pay less tax on the profit of the year of admission", "the bank can grant a loan on the security of the revalued assets",
     "B", "Increases or decreases in asset values before admission belong to the old partners in the old ratio."),
    (T_PTN, "Easy", "The document that sets out the rights and duties of partners is the",
     "memorandum of association", "partnership deed", "prospectus", "certificate of incorporation",
     "B", "The partnership deed (agreement) covers capital, profit sharing, salaries, interest and admission or retirement of partners."),
    (T_PTN, "Medium", "On the dissolution of a partnership, the account opened to record the sale of assets and settlement of liabilities is the",
     "revaluation account", "realisation account", "appropriation account", "suspense account",
     "B", "Assets are transferred to the realisation account at book value; proceeds and expenses are recorded there and the balance is the profit or loss on realisation."),
    (T_PTN, "Hard", "On dissolution, after all assets are realised and creditors paid, a partner's capital account shows a debit balance of ₦50,000 and he is insolvent. Under the rule in Garner v Murray the deficiency is borne by the solvent partners",
     "in their profit-sharing ratio", "in the ratio of their last agreed capitals", "equally", "by the partner with the largest drawings",
     "B", "Garner v Murray requires solvent partners to bear an insolvent partner's deficiency in the ratio of their capitals before dissolution."),
    (T_PTN, "Medium", "Which of the following is NOT usually found in a partnership appropriation account?",
     "interest on capital", "partners' salaries", "interest on partners' loans", "share of residual profit",
     "C", "Interest on a partner's loan is a charge against profit in the profit and loss account, not an appropriation."),
    (T_PTN, "Easy", "The maximum number of partners in an ordinary trading partnership in Nigeria is",
     "2", "7", "20", "50",
     "C", "Ordinary partnerships are limited to 20 members; beyond that a company must be formed (professional firms are exempt)."),
    (T_PTN, "Medium", "A partner who contributes capital and shares profit but takes no part in management is a",
     "general partner", "sleeping (dormant) partner", "nominal partner", "minor partner",
     "B", "A sleeping partner invests but does not manage; a nominal partner lends only his name."),
    (T_PTN, "Hard", "Partners P and Q share profits 3:1. Q is guaranteed a minimum of ₦150,000 per year. Profit for the year was ₦480,000. P's share after honouring the guarantee was",
     "₦360,000", "₦330,000", "₦345,000", "₦300,000",
     "B", "Normal shares: P 360,000, Q 120,000. Q's shortfall of 30,000 is made up by P, leaving P with ₦330,000.", "360000-30000"),
    # ---------------- Company accounts ----------------
    (T_CO, "Easy", "The document that states the objects of a company and its authorised share capital is the",
     "articles of association", "memorandum of association", "prospectus", "certificate of incorporation",
     "B", "The memorandum defines the company's name, objects and capital; the articles regulate its internal management."),
    (T_CO, "Easy", "The maximum amount of share capital a company is allowed to issue is its",
     "issued capital", "called-up capital", "authorised capital", "paid-up capital",
     "C", "Authorised (registered or nominal) capital is the ceiling stated in the memorandum."),
    (T_CO, "Medium", "The part of the called-up capital that shareholders have actually paid is the",
     "paid-up capital", "uncalled capital", "reserve capital", "authorised capital",
     "A", "Paid-up capital = called-up capital − calls in arrears."),
    (T_CO, "Medium", "When shares are issued at a price above their nominal value, the excess is credited to",
     "the profit and loss account", "share premium account", "general reserve", "ordinary share capital account",
     "B", "Share premium is a capital reserve that cannot be distributed as dividend."),
    (T_CO, "Easy", "Shareholders who receive a fixed rate of dividend before ordinary shareholders hold",
     "debentures", "preference shares", "deferred shares", "bonus shares",
     "B", "Preference shares carry a fixed dividend and rank before ordinary shares for dividend and usually for repayment of capital."),
    (T_CO, "Medium", "Cumulative preference shares differ from non-cumulative preference shares in that",
     "unpaid dividends are carried forward and must be paid before ordinary dividends", "they carry voting rights at every general meeting of the company", "they are always redeemable at the option of the company", "their dividend varies with the profits earned each year",
     "A", "Arrears of cumulative preference dividend accumulate until paid."),
    (T_CO, "Medium", "Debenture interest is",
     "an appropriation of profit decided by the shareholders", "a charge against profit payable whether or not profits are made", "paid only when the directors recommend it at the year end", "the same as a dividend on ordinary shares",
     "B", "Debentures are loans; their interest is an expense in the profit and loss account."),
    (T_CO, "Easy", "Bonus shares are issued",
     "for cash at a premium to the public", "free to existing shareholders out of reserves", "to debenture holders in place of interest", "to employees only as part of their pay",
     "B", "A bonus (capitalisation) issue converts reserves into share capital without bringing in cash."),
    (T_CO, "Medium", "A rights issue is an offer of new shares",
     "to the general public at a premium through a prospectus issued by the directors", "to existing shareholders in proportion to their holdings, usually at a favourable price", "to the directors only as a reward for their services", "to the government in exchange for a licence to operate",
     "B", "Rights issues raise cash from existing shareholders and preserve their proportionate ownership."),
    (T_CO, "Hard", "A company has 5,000,000 ordinary shares of 50k each and 1,000,000 8% preference shares of ₦1 each. Profit available for distribution is ₦900,000. If the directors pay the preference dividend and an ordinary dividend of 10k per share, the retained profit is",
     "₦320,000", "₦400,000", "₦820,000", "₦420,000",
     "A", "Preference dividend 8% × 1,000,000 = 80,000; ordinary dividend 5,000,000 × 0.10 = 500,000; retained = 900,000 − 580,000 = ₦320,000.", "900000-80000-500000"),
    (T_CO, "Easy", "A company's retained earnings appear in the balance sheet as part of",
     "current liabilities", "shareholders' funds (equity)", "fixed assets", "long-term loans",
     "B", "Retained profits belong to the shareholders and are shown with share capital and reserves."),
    (T_CO, "Medium", "The dividend proposed by directors but not yet approved by shareholders at the year end is",
     "shown as a current liability in the balance sheet", "disclosed in a note and not recognised as a liability", "deducted from the share capital of the company", "credited to the share premium account",
     "B", "Under IFRS a proposed dividend becomes a liability only when declared (approved), so at the year end it is disclosed but not accrued."),
    (T_CO, "Medium", "Calls in arrears are",
     "deducted from called-up capital to give paid-up capital", "added to the share premium account of the company", "shown as a current liability in the balance sheet", "written off to the profit and loss account of the year",
     "A", "Amounts called but not yet paid by shareholders reduce the paid-up capital figure."),
    (T_CO, "Hard", "A company issued 2,000,000 ordinary shares of ₦1 at ₦1.20, payable ₦0.50 on application (including the premium), ₦0.40 on allotment and ₦0.30 on first and final call. The amount credited to share premium account was",
     "₦400,000", "₦1,000,000", "₦240,000", "₦600,000",
     "A", "Premium = (1.20 − 1.00) × 2,000,000 = ₦400,000, received with the application money.", "0.2*2000000"),
    (T_CO, "Medium", "Which of the following is a capital reserve?",
     "general reserve", "retained profit", "share premium", "dividend equalisation reserve",
     "C", "Capital reserves (share premium, capital redemption reserve, revaluation reserve) are not available for cash dividends; the others are revenue reserves."),
    (T_CO, "Medium", "The main advantage of a limited liability company over a partnership is that",
     "it pays no tax on the profits it earns", "shareholders' liability is limited to the amount unpaid on their shares", "it needs no audit of its annual accounts", "profits are shared equally among all the shareholders",
     "B", "Members of a limited company cannot be called upon to pay the company's debts beyond their shareholding."),
    (T_CO, "Easy", "The statement that must be prepared by a company showing its assets, liabilities and equity at the year end is the",
     "statement of financial position", "statement of cash flows", "directors' report", "auditor's report",
     "A", "The statement of financial position is the IFRS name for the balance sheet."),
    (T_CO, "Hard", "A company redeemed ₦1,000,000 of preference shares out of profits. To protect creditors, an amount equal to the nominal value redeemed must be transferred to",
     "share premium account", "capital redemption reserve", "general reserve", "debenture redemption fund",
     "B", "The capital redemption reserve keeps the company's permanent capital intact when shares are redeemed out of distributable profits."),
    (T_CO, "Medium", "Preliminary (formation) expenses of a company are normally",
     "capitalised as a fixed asset and depreciated", "written off against share premium or profit in the first year", "added to the share capital of the company", "treated as a current asset for as long as the company exists",
     "B", "Formation costs have no lasting value and are written off, share premium being one permitted source."),
    (T_CO, "Easy", "Persons who manage the affairs of a company on behalf of the shareholders are the",
     "auditors", "directors", "debenture holders", "liquidators",
     "B", "Directors are elected by shareholders to run the company and are accountable to them."),
    # ---------------- Public sector ----------------
    (T_PUB, "Easy", "Government accounting in Nigeria is mainly based on the",
     "accrual basis", "cash basis", "matching concept", "going concern concept",
     "B", "Public sector accounts have traditionally recorded revenue when received and expenditure when paid, though IPSAS accrual accounting is being adopted."),
    (T_PUB, "Easy", "The account into which all revenues of the Federal Government are paid, as required by the Constitution, is the",
     "Development Fund", "Consolidated Revenue Fund", "Contingencies Fund", "Treasury Single Account",
     "B", "Section 80 of the 1999 Constitution establishes the Consolidated Revenue Fund of the Federation."),
    (T_PUB, "Medium", "The account from which federally collected revenue is shared among the federal, state and local governments is the",
     "Consolidated Revenue Fund", "Federation Account", "Capital Development Fund", "Excess Crude Account",
     "B", "Revenue such as oil receipts, companies income tax and customs duties is paid into the Federation Account for distribution by the approved formula."),
    (T_PUB, "Medium", "The officer of the Federal Government who audits and reports on the public accounts to the National Assembly is the",
     "Accountant-General of the Federation", "Auditor-General for the Federation", "Minister of Finance", "Governor of the Central Bank",
     "B", "The Auditor-General is independent of the executive and reports to the legislature."),
    (T_PUB, "Medium", "The officer responsible for keeping the accounts of the Federal Government and preparing the annual financial statements is the",
     "Auditor-General for the Federation", "Accountant-General of the Federation", "Clerk of the National Assembly", "Chairman of the Revenue Mobilisation Commission",
     "B", "The Accountant-General heads the Treasury and is the chief accounting officer of receipts and payments."),
    (T_PUB, "Easy", "The document that authorises government expenditure for a year is the",
     "audit report", "Appropriation Act", "warrant of arrest", "treasury circular",
     "B", "The budget becomes law as the Appropriation Act once passed by the legislature and assented to."),
    (T_PUB, "Medium", "Personnel costs, overheads and debt servicing are examples of government",
     "capital expenditure", "recurrent expenditure", "revenue receipts", "internally generated revenue",
     "B", "Recurrent expenditure is spent on running the government year after year; capital expenditure creates lasting assets."),
    (T_PUB, "Medium", "A vote in government accounting is",
     "an election held among civil servants to choose a treasurer", "an amount approved by the legislature for a specific purpose", "a warrant signed by the Auditor-General for the Federation", "the balance standing in the Federation Account at the year end",
     "B", "Money can only be spent under the head and sub-head (vote) for which it was appropriated."),
    (T_PUB, "Hard", "A ministry spent money on a project not provided for in the Appropriation Act. This is known as",
     "virement", "extra-budgetary expenditure", "a supplementary estimate", "a revenue shortfall",
     "B", "Spending outside the approved budget is unauthorised (extra-budgetary); a supplementary appropriation is the lawful route."),
    (T_PUB, "Medium", "Virement in public sector accounting means",
     "the transfer of savings from one sub-head to another within the same head with approval", "the audit of government accounts by the Auditor-General at the end of the year", "the sharing of the Federation Account among the three tiers of government", "the collection of taxes by agents appointed by the revenue authorities",
     "A", "Virement allows limited re-allocation of funds without a new Appropriation Act."),
    (T_PUB, "Easy", "The authority issued by the Minister of Finance to the Accountant-General permitting the release of funds is a",
     "warrant", "vote book", "treasury receipt", "payment voucher",
     "A", "Warrants (e.g. the Annual General Warrant) authorise expenditure from the Consolidated Revenue Fund."),
    (T_PUB, "Medium", "The book kept by a ministry to record its expenditure against the amounts allocated in the budget is the",
     "the treasury cash book", "the departmental vote book", "the register of fixed assets", "the imprest (petty cash) book",
     "B", "The vote book shows the balance remaining on each vote so that expenditure is not exceeded."),
    (T_PUB, "Medium", "The Treasury Single Account (TSA) introduced in Nigeria requires that",
     "all government revenues are paid into a unified account at the Central Bank", "every ministry keeps its own commercial bank accounts", "local governments pay revenue to state governments", "taxes are paid only in cash",
     "A", "TSA consolidates government cash balances in one account at the CBN to improve control and transparency."),
    (T_PUB, "Hard", "The international standards on which Nigeria's public sector accounting reforms are based are the",
     "International Financial Reporting Standards", "International Public Sector Accounting Standards", "Generally Accepted Auditing Standards", "Basel Accords",
     "B", "IPSAS, issued by the IPSAS Board, guide accrual-based financial reporting by governments."),
    (T_PUB, "Easy", "Personal income tax paid by workers in a state is collected by the",
     "Federal Inland Revenue Service", "State Internal Revenue Service", "Nigerian Customs Service", "Central Bank of Nigeria",
     "B", "PAYE of residents is a state revenue collected by the State Board of Internal Revenue."),
    (T_PUB, "Medium", "The main source of revenue for most Nigerian local governments is",
     "internally generated revenue from markets", "statutory allocation from the Federation Account", "grants from foreign donors", "bank loans",
     "B", "Most local governments depend heavily on their monthly statutory allocations."),
    (T_PUB, "Medium", "The fund from which unforeseen and urgent expenditure may be met pending approval by the legislature is the",
     "Consolidated Revenue Fund", "Contingencies Fund", "Development Fund", "Sinking Fund",
     "B", "Advances from the Contingencies Fund are later replaced by a supplementary appropriation."),
    (T_PUB, "Easy", "In the public sector, the accounting officer of a ministry, answerable for its funds, is usually the",
     "Minister", "Permanent Secretary", "Auditor-General", "Chief Justice",
     "B", "The Permanent Secretary is the accounting officer and can be summoned by the Public Accounts Committee."),
    (T_PUB, "Medium", "The main purpose of public sector accounting is to",
     "maximise the profit earned by the government each year", "demonstrate stewardship and accountability for public funds", "reduce the salaries and allowances of civil servants", "increase the amount the nation can borrow abroad",
     "B", "Governments account to the legislature and the public for how money voted was spent."),
    (T_PUB, "Medium", "A payment voucher in government accounting must be supported by",
     "the personal opinion of the cashier that the payment is genuine", "documents such as invoices, receipts and evidence of approval", "a newspaper advertisement announcing the payment", "a bank statement of the payee for the previous six months",
     "B", "Every payment must be properly authorised and supported before the Treasury will pass it."),
]

Q += [
    # ---------------- Information technology in accounting ----------------
    (T_IT, "Easy", "A computerised accounting system differs from a manual one mainly in that it",
     "does not use the double entry principle at all", "processes and posts transactions automatically once entered", "requires no source documents to support entries", "cannot produce a trial balance at the end of a period",
     "B", "Once a transaction is captured, the software posts to the ledger, updates balances and produces reports instantly; double entry still underlies it."),
    (T_IT, "Easy", "A program in which figures are arranged in rows and columns and formulae recalculate totals automatically is a",
     "word processor", "spreadsheet", "database", "web browser",
     "B", "Spreadsheets such as Microsoft Excel are widely used for budgets, schedules and financial analysis."),
    (T_IT, "Medium", "Which of the following is an advantage of computerised accounting?",
     "it eliminates the need for internal control", "speed and accuracy in processing large volumes of transactions", "it never breaks down", "it costs nothing to install",
     "B", "Computers process data quickly and consistently, but controls, backups and training are still needed."),
    (T_IT, "Medium", "Which of the following is a disadvantage of computerised accounting?",
     "reports are produced quickly at the end of the period", "risk of data loss through virus attack or system failure", "arithmetical errors in posting and balancing are reduced", "records take much less storage space than paper ledgers",
     "B", "Dependence on hardware and software exposes the records to viruses, power failure and hacking, hence the need for backups."),
    (T_IT, "Easy", "The physical components of a computer such as the keyboard, monitor and processor are called",
     "software", "hardware", "data", "programs",
     "B", "Hardware is the tangible equipment; software is the set of programs that run on it."),
    (T_IT, "Easy", "Which of the following is accounting software?",
     "Sage", "Adobe Photoshop", "Google Chrome", "AutoCAD",
     "A", "Sage, QuickBooks, Peachtree and Tally are widely used accounting packages."),
    (T_IT, "Medium", "The sequence of processing in a computerised accounting system is",
     "output → processing → input", "input → processing → output", "processing → input → storage", "storage → output → input",
     "B", "Data is entered (input), processed by the program, stored, and reports are produced (output)."),
    (T_IT, "Medium", "Making a copy of accounting data on a separate device or in the cloud so that it can be restored after a failure is called",
     "encryption", "backup", "formatting", "debugging",
     "B", "Regular backups protect against loss of records through hardware failure, theft or virus attack."),
    (T_IT, "Medium", "A password in an accounting package is used to",
     "speed up the processing of data", "restrict access to authorised users", "correct errors made in posting", "calculate depreciation on assets",
     "B", "Access controls are an internal control that prevents unauthorised entry or alteration of records."),
    (T_IT, "Easy", "Garbage in, garbage out (GIGO) means that",
     "computers produce wrong output if the input data is wrong", "computers must be cleaned regularly to avoid breakdown", "old computers should be discarded and replaced with new ones", "printers waste paper when reports are printed too often",
     "A", "The computer cannot correct inaccurate or incomplete data entered by users."),
    (T_IT, "Medium", "An audit trail in a computerised system is",
     "the auditor's travelling expenses when visiting the branches of a client", "a record that allows a transaction to be traced from source document to final report", "a list of the auditor's staff and the work assigned to each of them", "the fee charged by the auditor for examining the computerised records",
     "B", "An audit trail shows who entered what and when, so that figures in the accounts can be verified back to their origin."),
    (T_IT, "Medium", "Electronic banking allows a business to",
     "avoid keeping a cash book because the bank keeps all the records", "transfer funds, pay suppliers and check balances online without visiting the bank", "stop reconciling its bank account because the statement is always correct", "borrow money from the bank without paying any interest on the loan",
     "B", "Internet and mobile banking speed up payments and collections; records and reconciliations remain necessary."),
    (T_IT, "Hard", "A company keeps its accounting records on servers it accesses over the internet rather than on its own computers. This arrangement is called",
     "batch processing", "cloud computing", "offline storage", "manual accounting",
     "B", "Cloud-based accounting packages store data remotely and allow access from any location."),
    (T_IT, "Easy", "The device used to produce a printed copy of a financial statement is the",
     "scanner", "printer", "modem", "mouse",
     "B", "A printer produces hard copy output; a scanner captures images as input."),
    (T_IT, "Medium", "In a spreadsheet, the formula =SUM(B2:B10) will",
     "multiply the values in B2 and B10", "add all the values from cell B2 to cell B10", "find the average of B2 to B10", "count the empty cells in column B",
     "B", "SUM adds the values in the specified range of cells."),
    (T_IT, "Medium", "An Automated Teller Machine (ATM) card used to pay for goods directly from the buyer's bank balance is a",
     "credit card", "debit card", "store card", "loyalty card",
     "B", "A debit card draws immediately on funds in the customer's account; a credit card draws on a line of credit."),
    (T_IT, "Hard", "A firm records sales during the day and posts them all to the ledger at night in one run. This method of processing is called",
     "real-time processing", "batch processing", "online processing", "distributed processing",
     "B", "Batch processing accumulates transactions and processes them together at intervals; real-time systems update records immediately."),
    (T_IT, "Medium", "Which of the following is an internal control in a computerised accounting system?",
     "allowing all staff to use one password", "separating the duties of data entry and authorisation", "disabling the audit trail to save space", "never updating the software",
     "B", "Segregation of duties, access levels and audit trails reduce the risk of fraud and error."),
    # ---------------- Ratios ----------------
    (T_RAT, "Easy", "The current ratio is calculated as",
     "current assets ÷ current liabilities", "current liabilities ÷ current assets", "fixed assets ÷ current assets", "sales ÷ current assets",
     "A", "It measures the ability of a business to meet its short-term obligations."),
    (T_RAT, "Medium", "Current assets ₦450,000 (including stock ₦150,000); current liabilities ₦200,000. The acid-test (quick) ratio is",
     "2.25 : 1", "1.5 : 1", "0.75 : 1", "3 : 1",
     "B", "Quick ratio = (450,000 − 150,000) ÷ 200,000 = 1.5 : 1.", "(450000-150000)/200000"),
    (T_RAT, "Medium", "Sales ₦2,000,000; gross profit ₦500,000; net profit ₦200,000. The net profit percentage is",
     "25%", "10%", "40%", "20%",
     "B", "Net profit margin = 200,000 ÷ 2,000,000 × 100 = 10%.", "200000/2000000*100"),
    (T_RAT, "Medium", "Gross profit ₦360,000 on cost of goods sold ₦900,000. The mark-up is",
     "28.6%", "40%", "25%", "36%",
     "B", "Mark-up = gross profit ÷ cost × 100 = 360,000 ÷ 900,000 × 100 = 40%.", "360000/900000*100"),
    (T_RAT, "Hard", "Credit sales ₦1,460,000; average debtors ₦120,000. The average collection period (365-day year) is",
     "30 days", "24 days", "36 days", "12 days",
     "A", "120,000 ÷ 1,460,000 × 365 = 30 days.", "120000/1460000*365"),
    (T_RAT, "Easy", "A current ratio of 0.8 : 1 indicates that the business",
     "has more current assets than current liabilities", "may have difficulty paying its short-term debts", "is highly profitable", "has no stock",
     "B", "Current liabilities exceed current assets, a sign of possible liquidity problems."),
    (T_RAT, "Medium", "Net profit ₦300,000; capital employed ₦1,500,000. Return on capital employed is",
     "20%", "5%", "25%", "15%",
     "A", "300,000 ÷ 1,500,000 × 100 = 20%.", "300000/1500000*100"),
    (T_RAT, "Medium", "The rate of stock turnover measures",
     "how many times average stock is sold and replaced in a period", "the gross profit earned on each unit of stock sold in the period", "the number of days that credit customers take to pay their accounts", "the ratio of the fixed assets of the business to its sales",
     "A", "Stock turnover = cost of goods sold ÷ average stock; a higher figure usually means faster-moving stock."),
    (T_RAT, "Hard", "Average stock ₦80,000; stock turnover 6 times; gross margin 25% on sales. Sales for the year were",
     "₦480,000", "₦640,000", "₦600,000", "₦360,000",
     "B", "Cost of sales = 6 × 80,000 = 480,000 = 75% of sales; sales = 480,000 ÷ 0.75 = ₦640,000.", "480000/0.75"),
    (T_RAT, "Medium", "A fall in the gross profit percentage from one year to the next may be caused by",
     "an increase in the rent paid for the shop", "selling goods at lower prices without a fall in cost", "an increase in the salaries paid to the sales staff", "higher advertising costs in the second year",
     "B", "Gross profit percentage is affected only by trading account items such as selling prices, purchase costs and stock losses."),
    (T_RAT, "Hard", "A business has fixed assets ₦800,000, current assets ₦300,000, current liabilities ₦150,000 and a long-term loan of ₦250,000. Its capital employed (owner's equity) is",
     "₦950,000", "₦700,000", "₦1,100,000", "₦850,000",
     "B", "Equity = 800,000 + 300,000 − 150,000 − 250,000 = ₦700,000.", "800000+300000-150000-250000"),
    (T_RAT, "Medium", "The ratio that measures how much of a company's long-term finance is provided by borrowing rather than by shareholders is the",
     "current ratio", "gearing ratio", "acid-test ratio", "debtors' ratio",
     "B", "Gearing (leverage) compares fixed-interest capital with equity; high gearing means greater risk to ordinary shareholders."),
    (T_RAT, "Easy", "Which of the following users would be most interested in the liquidity ratios of a business?",
     "a trade creditor deciding whether to supply goods on credit", "a customer buying one item for cash", "the government's population census office", "a rival firm's advertising agency",
     "A", "Suppliers want assurance that the business can pay its short-term debts as they fall due."),
    (T_RAT, "Medium", "Purchases on credit ₦730,000; average creditors ₦60,000. The average payment period (365 days) is",
     "30 days", "12 days", "45 days", "36 days",
     "A", "60,000 ÷ 730,000 × 365 = 30 days.", "60000/730000*365"),
    (T_RAT, "Hard", "A business has a current ratio of 2 : 1 and current liabilities of ₦300,000. It then pays a creditor ₦100,000 by cheque. The new current ratio is",
     "2.5 : 1", "2 : 1", "1.5 : 1", "3 : 1",
     "A", "Current assets were 600,000. After payment: 500,000 ÷ 200,000 = 2.5 : 1.", "500000/200000"),
    (T_RAT, "Medium", "Earnings per share is calculated as",
     "profit after tax and preference dividend ÷ number of ordinary shares", "total dividend paid in the year ÷ number of shareholders on the register", "sales for the year ÷ number of ordinary shares in issue", "market price of the share ÷ dividend per share for the year",
     "A", "EPS shows the profit earned for each ordinary share and is a key measure for investors."),
]


def build():
    build_batch(
        S, "batch_036_accounting_round1b.json", "batch_036_accounting_round1b",
        "Principles of Accounts round 1 (part B): stock valuation (FIFO/LIFO/average), control accounts, incomplete records, manufacturing accounts, not-for-profit organisations, departmental and branch accounts, partnership accounts (appropriation, goodwill, admission, dissolution), company accounts (share issues, debentures, reserves), public sector accounting, IT in accounting and ratio analysis - with a stock-movement table, a debtors' control case, a statement-of-affairs case, a manufacturing cost table, a club's receipts and payments, a partnership appropriation, a share issue, a local government budget and a two-department table as data passages.",
        PASSAGES, PQ, Q,
    )


if __name__ == "__main__":
    build()
