"""Batch 014 - Chemistry round 3 (JAMB syllabus, applied/calculation style).

Four data passages (titration readings, rate-of-reaction data, standard electrode potentials,
solubility data) and ~210 stand-alone items across all fifteen Chemistry topics.  Every numerical
answer carries a `verify` expression that is evaluated before the file is written.

    python3 scripts/build_content_batch14.py -> content/batch_014_chemistry_round3.json
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from batch_common import build_batch  # noqa: E402

S = "Chemistry"

# (key, topic, title, text) - table rows use runs of >= 3 spaces and fit a 42-character line.
PASSAGES = [
    ("C1", "Acids Bases and Salts", "Titration of sodium trioxocarbonate(IV) with hydrochloric acid",
     "25.0 cm³ portions of a solution of sodium trioxocarbonate(IV), Na₂CO₃, were titrated with "
     "0.10 mol/dm³ hydrochloric acid using methyl orange as indicator. The burette readings are "
     "shown below. (Na = 23, C = 12, O = 16)\n\n"
     "Titration          1      2      3\n"
     "Final (cm³)     25.60  49.90  25.10\n"
     "Initial (cm³)    0.00  25.00   0.00\n"
     "Titre (cm³)     25.60  24.90  25.10"),
    ("C2", "Energy and Rates of Reaction", "Rate of reaction of magnesium with dilute acid",
     "A piece of magnesium ribbon was dropped into excess dilute hydrochloric acid at 25 °C and the "
     "volume of hydrogen collected was recorded every 20 seconds.\n\n"
     "Time (s)        0   20   40   60   80  100\n"
     "Volume (cm³)    0   30   50   62   68   68"),
    ("C3", "Electrochemistry", "Standard electrode potentials of some metals",
     "The standard electrode potentials of some metals are given below.\n\n"
     "Electrode         E°/V\n"
     "Mg²⁺/Mg          -2.37\n"
     "Zn²⁺/Zn          -0.76\n"
     "Fe²⁺/Fe          -0.44\n"
     "Cu²⁺/Cu          +0.34\n"
     "Ag⁺/Ag           +0.80"),
    ("C4", "Acids Bases and Salts", "Solubility of potassium trioxonitrate(V) at different temperatures",
     "The solubility of potassium trioxonitrate(V), KNO₃, in water at different temperatures is "
     "shown below. (KNO₃ = 101)\n\n"
     "Temp (°C)              20   40   60   80\n"
     "Solubility             32   64  110  169\n"
     "(g per 100 g water)"),
]

# (passage, difficulty, q, A, B, C, D, answer, explanation[, verify])
PQ = [
    ("C1", "Easy", "In the titration above, the average titre that should be used in the calculation is",
     "25.20 cm³", "25.00 cm³", "24.90 cm³", "25.60 cm³", "B",
     "Only the concordant titres (24.90 and 25.10 cm³, within 0.2 cm³ of each other) are averaged: (24.90 + 25.10)/2 = 25.00 cm³.", "25"),
    ("C1", "Medium", "From the titration above, the number of moles of hydrochloric acid in the average titre is",
     "0.0025 mol", "0.0050 mol", "0.00125 mol", "0.025 mol", "A",
     "Moles = concentration × volume in dm³ = 0.10 × 25.00/1000 = 0.0025 mol.", "0.10*25/1000"),
    ("C1", "Medium", "From the titration above, the concentration of the sodium trioxocarbonate(IV) solution in mol/dm³ is",
     "0.025", "0.050", "0.100", "0.200", "B",
     "Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂, so moles Na₂CO₃ = 0.0025/2 = 0.00125 in 25.0 cm³; concentration = 0.00125/0.025 = 0.050 mol/dm³.", "0.00125/0.025"),
    ("C1", "Medium", "From the titration above, the concentration of the sodium trioxocarbonate(IV) solution in g/dm³ is",
     "2.65", "5.30", "10.6", "21.2", "B",
     "Molar mass of Na₂CO₃ = 2(23) + 12 + 3(16) = 106; 0.050 mol/dm³ × 106 g/mol = 5.30 g/dm³.", "0.05*106"),
    ("C1", "Easy", "In the titration above, the colour change observed at the end point is from",
     "colourless to pink", "pink to colourless", "yellow to orange", "red to yellow", "C",
     "Methyl orange is yellow in the alkaline carbonate solution in the flask and turns orange (then red) as the acid from the burette reaches the end point."),
    ("C1", "Medium", "In the titration above, the result of titration 1 was left out when finding the average because",
     "the burette was wrongly read from the top of the meniscus", "it was only a rough trial and differs from the others by over 0.2 cm³",
     "too much indicator was added to the first conical flask", "the first portion of the solution was not exactly 25.0 cm³", "B",
     "The first titration is a rough run to locate the end point; only titres that agree closely (concordant) are used in the calculation."),
    ("C2", "Medium", "From the data above, the average rate of reaction during the first 20 seconds is",
     "0.67 cm³/s", "1.5 cm³/s", "2.5 cm³/s", "30 cm³/s", "B",
     "Rate = volume of gas ÷ time = 30 cm³ ÷ 20 s = 1.5 cm³/s.", "30/20"),
    ("C2", "Medium", "From the data above, the average rate of reaction between 40 s and 60 s is",
     "0.3 cm³/s", "0.6 cm³/s", "1.2 cm³/s", "3.1 cm³/s", "B",
     "Volume produced between 40 s and 60 s = 62 − 50 = 12 cm³; 12/20 = 0.6 cm³/s, slower than at the start.", "12/20"),
    ("C2", "Easy", "From the data above, the reaction was complete after about",
     "40 s", "60 s", "80 s", "100 s", "C",
     "No more hydrogen was collected after 80 s (the volume stayed at 68 cm³), so the magnesium had all reacted by then.", "80"),
    ("C2", "Medium", "In the experiment above, the rate of reaction decreased with time because",
     "the temperature of the acid kept rising", "the magnesium was gradually used up", "hydrogen gas dissolved in the acid", "the acid became more concentrated", "B",
     "The acid was in excess, so it was the magnesium (the limiting reactant) whose amount and surface fell as the reaction proceeded, giving fewer collisions per second."),
    ("C2", "Medium", "If the experiment above were repeated with the same mass of magnesium powder instead of ribbon, the final volume of hydrogen would be",
     "68 cm³, collected in a shorter time", "68 cm³, collected in a longer time", "more than 68 cm³, collected faster", "less than 68 cm³, collected more slowly", "A",
     "The same amount of magnesium gives the same amount of hydrogen; the larger surface area of the powder only makes the reaction faster."),
    ("C2", "Hard", "From the final volume of hydrogen in the data above, the mass of magnesium used was about (Mg = 24, molar volume at room temperature = 24,000 cm³)",
     "0.034 g", "0.068 g", "0.136 g", "0.68 g", "B",
     "Mg + 2HCl → MgCl₂ + H₂: 68/24,000 = 0.00283 mol of H₂ came from 0.00283 mol of Mg = 0.00283 × 24 = 0.068 g.", "68/24000*24"),
    ("C3", "Easy", "From the table above, the strongest reducing agent is",
     "magnesium", "zinc", "copper", "silver", "A",
     "The most negative electrode potential belongs to the metal that loses electrons most readily; magnesium (−2.37 V) is the strongest reducing agent."),
    ("C3", "Medium", "From the table above, the e.m.f. of the cell Zn(s)|Zn²⁺(aq)||Ag⁺(aq)|Ag(s) under standard conditions is",
     "0.04 V", "1.56 V", "0.46 V", "1.10 V", "B",
     "E°cell = E°(cathode) − E°(anode) = (+0.80) − (−0.76) = 1.56 V.", "0.80+0.76"),
    ("C3", "Medium", "From the table above, which of the following reactions will take place spontaneously?",
     "Cu + 2Ag⁺ → Cu²⁺ + 2Ag", "Cu + Zn²⁺ → Cu²⁺ + Zn", "2Ag + Fe²⁺ → 2Ag⁺ + Fe", "Fe + Mg²⁺ → Fe²⁺ + Mg", "A",
     "A metal displaces the ions of any metal with a more positive E°. Copper (+0.34 V) can reduce Ag⁺ (+0.80 V): E°cell = +0.46 V. The other three have negative e.m.f.s."),
    ("C3", "Medium", "From the table above, the metal that would protect an iron pipe best when attached to it as a sacrificial anode is",
     "magnesium", "iron", "copper", "silver", "A",
     "A sacrificial anode must be more easily oxidised (more negative E°) than iron; magnesium at −2.37 V corrodes in place of the iron. Copper and silver would make the iron corrode faster."),
    ("C3", "Medium", "From the table above, the e.m.f. of a cell made from the Fe²⁺/Fe and Cu²⁺/Cu half-cells is",
     "0.10 V", "0.78 V", "1.10 V", "0.22 V", "B",
     "Copper is the cathode: E°cell = 0.34 − (−0.44) = 0.78 V.", "0.34+0.44"),
    ("C3", "Medium", "In a cell Mg(s)|Mg²⁺(aq)||Cu²⁺(aq)|Cu(s) built from the table above, reduction takes place at",
     "the magnesium electrode", "the copper electrode", "both electrodes equally", "the salt bridge", "B",
     "Cu²⁺ ions gain electrons (Cu²⁺ + 2e⁻ → Cu) at the copper electrode, the cathode; magnesium is oxidised at the anode."),
    ("C4", "Medium", "From the data above, the mass of KNO₃ that crystallises out when a saturated solution containing 100 g of water is cooled from 60 °C to 20 °C is",
     "32 g", "78 g", "110 g", "142 g", "B",
     "At 60 °C the solution holds 110 g per 100 g of water; at 20 °C only 32 g can stay dissolved, so 110 − 32 = 78 g crystallises.", "110-32"),
    ("C4", "Easy", "From the data above, the maximum mass of KNO₃ that will dissolve in 50 g of water at 80 °C is",
     "42.25 g", "84.5 g", "169 g", "338 g", "B",
     "Solubility at 80 °C is 169 g per 100 g of water, so 50 g of water dissolves 169/2 = 84.5 g.", "169/2"),
    ("C4", "Hard", "From the data above, the solubility of KNO₃ at 20 °C in mol/dm³ is approximately (take 100 g of water as 100 cm³)",
     "0.32", "3.17", "1.58", "31.7", "B",
     "32 g per 100 cm³ = 320 g/dm³; 320 ÷ 101 = 3.17 mol/dm³.", "320/101"),
    ("C4", "Medium", "From the data above, when 80 g of KNO₃ is stirred with 100 g of water at 40 °C, the mass of solid that remains undissolved is",
     "0 g", "16 g", "46 g", "64 g", "B",
     "Only 64 g can dissolve in 100 g of water at 40 °C, so 80 − 64 = 16 g stays as solid and the solution is saturated.", "80-64"),
    ("C4", "Medium", "The data above show that the dissolution of KNO₃ in water is",
     "exothermic, since solubility rises with temperature", "endothermic, since solubility rises with temperature",
     "exothermic, since solubility falls with temperature", "neither, since solubility does not change with temperature", "B",
     "By Le Chatelier's principle, heating favours the endothermic direction; since more salt dissolves as the temperature rises, dissolving absorbs heat."),
]

# (topic, difficulty, q, A, B, C, D, answer, explanation[, verify])
Q = [
    # ---------------- States of Matter (separation, kinetic theory, gas laws) ----------------
    ("States of Matter", "Medium", "A mixture contains iodine crystals, sand and sodium chloride. The correct order of processes for separating the three components is",
     "sublimation, then dissolving in water, filtration and evaporation", "filtration, then sublimation, dissolving and evaporation",
     "evaporation, then filtration, sublimation and dissolving", "dissolving in water, then evaporation, filtration and sublimation", "A",
     "Gentle heating sublimes the iodine first; water then dissolves the salt, filtration removes the sand and evaporation recovers the salt from the filtrate."),
    ("States of Matter", "Easy", "A mixture of ethanol (boiling point 78 °C) and water (boiling point 100 °C) is best separated by",
     "filtration", "fractional distillation", "decantation", "sublimation", "B",
     "Two miscible liquids with different boiling points are separated by fractional distillation; the more volatile ethanol distils over first."),
    ("States of Matter", "Easy", "The coloured dyes in a sample of black ink are best separated by",
     "chromatography", "crystallisation", "simple distillation", "magnetic separation", "A",
     "Paper chromatography separates the dyes because they travel at different rates up the paper with the solvent."),
    ("States of Matter", "Medium", "A solid melted over the range 108–115 °C instead of sharply at 118 °C, the value given in data tables. The most reasonable conclusion is that the solid",
     "is a pure element", "contains impurities", "is a pure compound", "has decomposed completely", "B",
     "Impurities lower the melting point and make a solid melt over a range of temperatures; a pure substance melts sharply at a fixed temperature."),
    ("States of Matter", "Medium", "A gas occupies 250 cm³ at 27 °C and 750 mmHg. Its volume at 127 °C and 1000 mmHg is",
     "125 cm³", "250 cm³", "375 cm³", "500 cm³", "B",
     "P₁V₁/T₁ = P₂V₂/T₂: V₂ = 250 × (750/1000) × (400/300) = 250 cm³; the effects of the pressure and temperature changes cancel.", "250*(750/1000)*(400/300)"),
    ("States of Matter", "Medium", "Under the same conditions, 50 cm³ of hydrogen diffuses through a porous plug in 20 s. The time taken for 50 cm³ of oxygen to diffuse through the same plug is (H = 1, O = 16)",
     "5 s", "40 s", "80 s", "320 s", "C",
     "Graham's law: rate ∝ 1/√M, so hydrogen diffuses √(32/2) = 4 times as fast as oxygen; oxygen therefore takes 4 × 20 = 80 s.", "20*math.sqrt(32/2)"),
    ("States of Matter", "Hard", "Gas X diffuses 1.5 times as fast as gas Y under the same conditions. If the relative molecular mass of X is 16, that of Y is",
     "24", "36", "10.7", "64", "B",
     "(rate of X ÷ rate of Y)² = M_Y ÷ M_X, so M_Y = 16 × 1.5² = 36.", "16*1.5**2"),
    ("States of Matter", "Medium", "When a sealed metal can containing air is heated, the pressure inside rises because the air molecules",
     "become larger and fill more space", "move faster and strike the walls more often and harder", "increase in number as the air expands", "stick together to form heavier particles", "B",
     "Heating raises the average kinetic energy of the molecules; faster molecules collide with the walls more frequently and with greater force, so the pressure rises."),
    ("States of Matter", "Easy", "Under a microscope, pollen grains suspended in water are seen to move in a zig-zag manner. This observation supports the idea that",
     "pollen grains are alive and swim", "water molecules are in constant random motion", "water expands when heated", "pollen grains dissolve slowly in water", "B",
     "Brownian motion of the grains is caused by unequal bombardment by fast-moving water molecules, evidence for the kinetic theory."),
    ("States of Matter", "Medium", "The volume occupied by 0.25 mol of an ideal gas at 27 °C and 1 atm is (R = 0.082 atm dm³ K⁻¹ mol⁻¹)",
     "0.55 dm³", "6.15 dm³", "24.6 dm³", "2.05 dm³", "B",
     "PV = nRT: V = 0.25 × 0.082 × 300 ÷ 1 = 6.15 dm³.", "0.25*0.082*300"),
    ("States of Matter", "Medium", "A cylinder holds 0.1 mol of nitrogen mixed with 0.3 mol of oxygen at a total pressure of 800 mmHg. The partial pressure of the oxygen is",
     "200 mmHg", "400 mmHg", "600 mmHg", "800 mmHg", "C",
     "Partial pressure = mole fraction × total pressure = (0.3/0.4) × 800 = 600 mmHg.", "0.3/0.4*800"),
    ("States of Matter", "Medium", "Which of the following gases is expected to deviate most from ideal behaviour?",
     "helium", "hydrogen", "nitrogen", "ammonia", "D",
     "Ammonia molecules are polar and hydrogen-bonded, so the intermolecular forces that the kinetic theory ignores are strongest in ammonia."),
    ("States of Matter", "Medium", "Which statement correctly distinguishes evaporation from boiling?",
     "evaporation occurs throughout the liquid; boiling only at the surface", "evaporation occurs at any temperature; boiling at one fixed temperature",
     "evaporation needs heat; boiling does not", "evaporation occurs only in closed vessels; boiling in open ones", "B",
     "Evaporation is a surface process that happens at all temperatures, whereas boiling occurs throughout the liquid at the boiling point, when the vapour pressure equals the external pressure."),
    ("States of Matter", "Medium", "A fixed mass of gas occupies 600 cm³ at 27 °C. At constant pressure its volume becomes 800 cm³ at",
     "36 °C", "127 °C", "400 °C", "227 °C", "B",
     "Charles' law: T₂ = 300 K × 800/600 = 400 K = 127 °C.", "300*800/600-273"),
    ("States of Matter", "Easy", "The pressure on a fixed mass of gas at constant temperature is increased from 1 atm to 3 atm. Its volume",
     "increases three times", "decreases to one-third", "remains the same", "decreases to one-ninth", "B",
     "Boyle's law: PV is constant, so tripling the pressure reduces the volume to a third."),
    ("States of Matter", "Easy", "The components of crude oil can be separated by fractional distillation because they have different",
     "colours", "densities", "boiling points", "solubilities in water", "C",
     "Fractional distillation separates liquids by their boiling points; the fractions condense at different heights in the column."),
    # ---------------- Atomic Structure (incl. radioactivity) ----------------
    ("Atomic Structure", "Medium", "An atom has mass number 40 and 21 neutrons. The number of electrons in its outermost shell is",
     "1", "2", "8", "19", "A",
     "Protons = 40 − 21 = 19 (potassium), configuration 2, 8, 8, 1; there is one electron in the outer shell.", "1"),
    ("Atomic Structure", "Medium", "The ion X³⁺ has 10 electrons and 14 neutrons. The mass number of X is",
     "24", "27", "13", "23", "B",
     "X³⁺ has lost 3 electrons, so the atom has 13 electrons and 13 protons; mass number = 13 + 14 = 27 (aluminium).", "27"),
    ("Atomic Structure", "Hard", "Which of the following sets of quantum numbers is NOT possible for an electron?",
     "n = 1, l = 0, m = 0", "n = 2, l = 1, m = −1", "n = 3, l = 3, m = 0", "n = 4, l = 2, m = 2", "C",
     "The value of l can only run from 0 to n − 1, so for n = 3 the largest possible l is 2."),
    ("Atomic Structure", "Medium", "The number of unpaired electrons in an atom of nitrogen (atomic number 7) is",
     "1", "2", "3", "5", "C",
     "Nitrogen is 1s² 2s² 2p³; by Hund's rule the three 2p electrons occupy separate orbitals and are all unpaired.", "3"),
    ("Atomic Structure", "Medium", "Isotopes of the same element show identical chemical properties because they have the same",
     "mass number", "number of neutrons", "electronic configuration", "density", "C",
     "Chemical behaviour depends on the electrons; isotopes differ only in neutron number and hence in mass."),
    ("Atomic Structure", "Medium", "Neon consists of 90.0% ²⁰Ne, 0.3% ²¹Ne and 9.7% ²²Ne. Its relative atomic mass is approximately",
     "20.0", "20.2", "21.0", "21.5", "B",
     "(90 × 20 + 0.3 × 21 + 9.7 × 22) ÷ 100 = 20.2.", "(90*20+0.3*21+9.7*22)/100"),
    ("Atomic Structure", "Hard", "Boron has a relative atomic mass of 10.8 and consists of the isotopes ¹⁰B and ¹¹B only. The percentage abundance of ¹¹B is",
     "20%", "50%", "80%", "90%", "C",
     "Let x be the fraction of ¹¹B: 10(1 − x) + 11x = 10.8, so x = 0.8, i.e. 80%.", "80"),
    ("Atomic Structure", "Medium", "A radioactive isotope has a half-life of 8 days. The fraction of a sample remaining after 32 days is",
     "1/4", "1/8", "1/16", "1/32", "C",
     "32 days is four half-lives: 1 → 1/2 → 1/4 → 1/8 → 1/16 of the original amount.", "1/16"),
    ("Atomic Structure", "Medium", "When an atom of ²³⁸₉₂U emits an alpha particle, the daughter nucleus has",
     "atomic number 90 and mass number 234", "atomic number 93 and mass number 238", "atomic number 92 and mass number 236", "atomic number 88 and mass number 230", "A",
     "An alpha particle is a helium nucleus (2 protons, 2 neutrons): the atomic number falls by 2 and the mass number by 4."),
    ("Atomic Structure", "Medium", "When ¹⁴₆C decays by emitting a beta particle, the product is",
     "¹⁴₇N", "¹²₆C", "¹⁴₅B", "¹⁰₄Be", "A",
     "In beta decay a neutron becomes a proton and an electron; the atomic number rises by 1 while the mass number is unchanged."),
    ("Atomic Structure", "Medium", "When the radiations from a radioactive source pass between charged plates, the radiation deflected towards the positive plate is",
     "alpha particles", "beta particles", "gamma rays", "neutrons", "B",
     "Beta particles are electrons and carry a negative charge, so they are attracted to the positive plate; alpha particles go the other way and gamma rays are undeflected."),
    ("Atomic Structure", "Medium", "A radioactive sample decays from 80 g to 5 g in 60 minutes. Its half-life is",
     "10 min", "12 min", "15 min", "20 min", "C",
     "80 → 40 → 20 → 10 → 5 is four half-lives, so one half-life = 60 ÷ 4 = 15 minutes.", "15"),
    ("Atomic Structure", "Medium", "In Rutherford's experiment most alpha particles passed straight through gold foil but a few bounced back. This showed that",
     "electrons are heavier than alpha particles", "the atom has a tiny, dense, positively charged nucleus", "gold atoms are mostly solid matter", "alpha particles carry no charge", "B",
     "The rare large deflections could only be caused by a very small, massive, positively charged centre, while most of the atom is empty space."),
    ("Atomic Structure", "Hard", "The electronic configuration of the Fe²⁺ ion (Fe, atomic number 26) is",
     "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁴ 4s²", "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁶", "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁵ 4s¹", "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁶ 4s²", "B",
     "Iron is [Ar] 3d⁶ 4s²; the two 4s electrons are lost first, leaving 3d⁶ for Fe²⁺."),
    ("Atomic Structure", "Easy", "Which of the following species has the same number of electrons as a neon atom (atomic number 10)?",
     "Na (atomic number 11)", "Mg²⁺ (atomic number 12)", "Cl⁻ (atomic number 17)", "F (atomic number 9)", "B",
     "Mg²⁺ has 12 − 2 = 10 electrons, the same as neon; Cl⁻ has 18, Na has 11 and F has 9."),
    # ---------------- Periodic Table ----------------
    ("Periodic Table", "Medium", "Elements P, Q, R and S have atomic numbers 3, 9, 12 and 17 respectively. The pair with similar chemical properties is",
     "P and Q", "Q and S", "P and R", "R and S", "B",
     "Q (2,7) and S (2,8,7) both have seven outer electrons and are halogens in Group 7; P is a Group 1 metal and R a Group 2 metal."),
    ("Periodic Table", "Medium", "Across period 3 from sodium to chlorine the atomic radius decreases because",
     "the number of shells increases", "the nuclear charge increases while electrons enter the same shell", "electrons are removed from the atoms", "the atoms lose their outer shells", "B",
     "Each successive element has one more proton pulling on electrons in the same shell, so the shell is drawn closer to the nucleus."),
    ("Periodic Table", "Medium", "Which of the following period 3 elements has the highest first ionisation energy?",
     "sodium", "magnesium", "aluminium", "chlorine", "D",
     "Ionisation energy generally rises across a period as nuclear charge increases and the atomic radius shrinks; chlorine is furthest right of the four."),
    ("Periodic Table", "Medium", "An element X forms an oxide X₂O₃ which reacts with both acids and alkalis. X is most likely",
     "sodium", "aluminium", "sulphur", "chlorine", "B",
     "Aluminium oxide, Al₂O₃, is amphoteric and aluminium forms X³⁺ ions, giving the formula X₂O₃."),
    ("Periodic Table", "Medium", "The oxide of an element dissolves in water to give a solution of pH 2. The element is most likely",
     "sodium", "magnesium", "sulphur", "calcium", "C",
     "Non-metal oxides such as sulphur(IV) oxide are acidic; metal oxides give neutral or alkaline solutions."),
    ("Periodic Table", "Medium", "Element Y has the electronic configuration 2, 8, 6. Which statement about Y is correct?",
     "It is in Group 2 of the periodic table", "It forms a Y²⁺ ion readily", "It is a non-metal in period 3", "Its oxide is strongly basic", "C",
     "Three shells place Y in period 3 and six outer electrons in Group 6 (sulphur); it is a non-metal that gains two electrons to form Y²⁻."),
    ("Periodic Table", "Medium", "Going down Group 1 from lithium to caesium, the reactivity of the metals with water increases because",
     "the atoms become smaller", "the outer electron is further from the nucleus and more easily lost", "the metals become harder", "the number of outer electrons increases", "B",
     "Extra inner shells shield the single outer electron from the nucleus, so less energy is needed to remove it."),
    ("Periodic Table", "Easy", "Which pair of elements would combine most readily to form an ionic compound?",
     "carbon and oxygen", "nitrogen and hydrogen", "potassium and fluorine", "sulphur and chlorine", "C",
     "A very reactive metal (Group 1) and a very reactive non-metal (Group 7) transfer electrons readily to form an ionic compound."),
    ("Periodic Table", "Easy", "The element with atomic number 20 is found in",
     "Group 2, period 4", "Group 4, period 2", "Group 2, period 3", "Group 8, period 4", "A",
     "Configuration 2, 8, 8, 2: four shells give period 4 and two outer electrons give Group 2 (calcium)."),
    ("Periodic Table", "Medium", "Chlorine displaces bromine from potassium bromide solution, but iodine does not. This shows that the oxidising power of the halogens",
     "increases down the group", "decreases down the group", "is the same for all halogens", "depends only on concentration", "B",
     "A halogen oxidises the ions of those below it in the group; chlorine (above bromine) can, iodine (below bromine) cannot."),
    ("Periodic Table", "Easy", "Which of the following elements is a transition metal?",
     "potassium", "calcium", "copper", "gallium", "C",
     "Copper forms an ion with a partly filled d-subshell (Cu²⁺ is 3d⁹), the defining feature of a transition metal."),
    ("Periodic Table", "Medium", "Iron and copper differ from sodium in that they",
     "form coloured ions and show variable oxidation states", "react violently with cold water", "form only one type of ion", "have low melting points and densities", "A",
     "Transition metals typically form coloured compounds (Fe²⁺ green, Cu²⁺ blue) and exist in more than one oxidation state (Fe²⁺/Fe³⁺, Cu⁺/Cu²⁺)."),
    # ---------------- Chemical Bonding ----------------
    ("Chemical Bonding", "Medium", "Element X has the electronic configuration 2, 8, 2 and element Y has 2, 7. The compound they form has the formula and bond type",
     "XY, covalent", "XY₂, ionic", "X₂Y, ionic", "XY₂, covalent", "B",
     "X loses two electrons to form X²⁺ and each Y gains one to form Y⁻; two Y⁻ ions balance one X²⁺, giving the ionic compound XY₂."),
    ("Chemical Bonding", "Medium", "When hydrogen chloride dissolves in water, H₃O⁺ ions form. The bond between the water molecule and the added proton is",
     "an ionic bond", "a dative (coordinate) covalent bond", "a hydrogen bond", "a metallic bond", "B",
     "Oxygen donates both electrons of one of its lone pairs to the proton, which has none; a bond in which one atom supplies both electrons is dative covalent."),
    ("Chemical Bonding", "Medium", "Ice floats on water because",
     "ice contains trapped air bubbles", "hydrogen bonds hold water molecules in an open structure of lower density", "the covalent bonds in ice are longer", "ice molecules are lighter than water molecules", "B",
     "In ice each molecule is hydrogen-bonded to four others in an open lattice, so ice is less dense than liquid water."),
    ("Chemical Bonding", "Medium", "Graphite conducts electricity but diamond does not because in graphite",
     "the carbon atoms are ionised", "each carbon atom bonds to three others, leaving one delocalised electron", "the atoms are packed more closely together", "there are no covalent bonds", "B",
     "Each carbon in graphite uses three electrons for bonds within a layer; the fourth is delocalised over the layer and carries current."),
    ("Chemical Bonding", "Easy", "A crystal of sodium chloride does not conduct electricity, yet the molten salt conducts well. This is because in the solid",
     "there are no ions until the salt melts", "the ions are held in fixed positions in the lattice", "all the electrons are shared between the atoms in pairs", "the sodium and chlorine atoms are covalently bonded", "B",
     "The ions are present but cannot move in the rigid lattice; once molten or dissolved they are free to move and conduct."),
    ("Chemical Bonding", "Medium", "The shape of the ammonia molecule, NH₃, is",
     "linear", "trigonal planar", "trigonal pyramidal", "tetrahedral", "C",
     "Nitrogen has three bond pairs and one lone pair; the lone pair pushes the three N–H bonds into a pyramid with a bond angle of about 107°."),
    ("Chemical Bonding", "Medium", "Hydrogen fluoride boils at 20 °C while hydrogen chloride boils at −85 °C. The main reason is that",
     "HF has a higher relative molecular mass", "HF molecules are held together by hydrogen bonds", "HCl is ionic while HF is covalent", "HF molecules are larger", "B",
     "Fluorine is small and very electronegative, so strong hydrogen bonds form between HF molecules and more energy is needed to separate them."),
    ("Chemical Bonding", "Medium", "Metals can be hammered into sheets and drawn into wires because",
     "the layers of positive ions slide over one another within the sea of electrons", "their atoms are held together by weak van der Waals forces",
     "they contain free-moving negative ions", "their bonds break easily and re-form as new compounds", "A",
     "In metallic bonding the delocalised electrons keep bonding the ions whatever their positions, so layers can slip without the metal shattering."),
    ("Chemical Bonding", "Easy", "Which of the following substances has a giant covalent structure?",
     "carbon(IV) oxide", "silicon(IV) oxide", "sodium chloride", "iodine", "B",
     "In SiO₂ every silicon atom is covalently bonded to four oxygens in a continuous network, which is why sand has a very high melting point."),
    ("Chemical Bonding", "Medium", "Which of the following bonds is the most polar?",
     "H–H", "H–C", "H–N", "H–F", "D",
     "Polarity increases with the electronegativity difference between the bonded atoms; fluorine is the most electronegative element."),
    ("Chemical Bonding", "Medium", "Iodine crystals have a low melting point and sublime easily because",
     "the I–I covalent bond is very weak", "only weak van der Waals forces act between the I₂ molecules", "iodine is a metal", "iodine molecules are ionic", "B",
     "The covalent bond within each I₂ molecule is strong, but the molecules are held to each other by weak intermolecular forces that little heat can overcome."),
    ("Chemical Bonding", "Medium", "Which of the following compounds contains both ionic and covalent bonds?",
     "sodium chloride", "ammonium chloride", "tetrachloromethane", "hydrogen chloride", "B",
     "NH₄Cl consists of NH₄⁺ and Cl⁻ ions (ionic), while the N–H bonds inside the ammonium ion are covalent."),
    ("Chemical Bonding", "Easy", "The water molecule is V-shaped (bent) rather than linear because the oxygen atom",
     "has two lone pairs of electrons", "forms a double bond with each hydrogen", "is larger than hydrogen", "has no lone pairs", "A",
     "The two lone pairs on oxygen repel the two bond pairs, bending the molecule to an angle of about 104.5°."),
    # ---------------- Mole Concept and Stoichiometry ----------------
    ("Mole Concept and Stoichiometry", "Medium", "The mass of 3.01 × 10²³ molecules of water is (H = 1, O = 16, Avogadro's number = 6.02 × 10²³)",
     "4.5 g", "9.0 g", "18 g", "36 g", "B",
     "3.01 × 10²³ molecules is 0.5 mol; 0.5 × 18 = 9.0 g.", "0.5*18"),
    ("Mole Concept and Stoichiometry", "Medium", "The total number of atoms in 0.2 mol of ammonia, NH₃, is (Avogadro's number = 6.02 × 10²³)",
     "1.2 × 10²³", "2.4 × 10²³", "4.8 × 10²³", "6.0 × 10²³", "C",
     "Each NH₃ molecule has 4 atoms: 0.2 × 4 × 6.02 × 10²³ = 4.8 × 10²³ atoms."),
    ("Mole Concept and Stoichiometry", "Medium", "The volume of carbon(IV) oxide at s.t.p. produced when 10 g of calcium trioxocarbonate(IV) is heated strongly is (CaCO₃ = 100, molar volume = 22.4 dm³)",
     "1.12 dm³", "2.24 dm³", "4.48 dm³", "22.4 dm³", "B",
     "CaCO₃ → CaO + CO₂; 10 g is 0.1 mol, giving 0.1 mol of CO₂ = 0.1 × 22.4 = 2.24 dm³.", "0.1*22.4"),
    ("Mole Concept and Stoichiometry", "Medium", "The percentage by mass of water of crystallisation in CuSO₄·5H₂O is (Cu = 64, S = 32, O = 16, H = 1)",
     "18%", "36%", "40%", "64%", "B",
     "Molar mass = 160 + 90 = 250; water = 90/250 × 100 = 36%.", "90/250*100"),
    ("Mole Concept and Stoichiometry", "Medium", "A compound has the empirical formula CH₂O and a relative molecular mass of 180. Its molecular formula is (C = 12, H = 1, O = 16)",
     "C₂H₄O₂", "C₃H₆O₃", "C₆H₁₂O₆", "C₁₂H₂₂O₁₁", "C",
     "Empirical formula mass = 30; 180/30 = 6, so the molecular formula is (CH₂O)₆ = C₆H₁₂O₆."),
    ("Mole Concept and Stoichiometry", "Medium", "0.24 g of magnesium reacts completely with excess dilute hydrochloric acid. The volume of hydrogen produced at s.t.p. is (Mg = 24, molar volume = 22.4 dm³)",
     "112 cm³", "224 cm³", "448 cm³", "2,240 cm³", "B",
     "Mg + 2HCl → MgCl₂ + H₂; 0.24 g = 0.01 mol Mg gives 0.01 mol H₂ = 0.01 × 22,400 = 224 cm³.", "0.01*22400"),
    ("Mole Concept and Stoichiometry", "Hard", "2.4 g of magnesium is burnt in 1.6 g of oxygen. The mass of magnesium oxide formed is (Mg = 24, O = 16)",
     "1.6 g", "2.4 g", "4.0 g", "8.0 g", "C",
     "2Mg + O₂ → 2MgO: 0.1 mol Mg needs 0.05 mol O₂, which is exactly the 1.6 g present, so 0.1 mol MgO = 4.0 g forms.", "0.1*40"),
    ("Mole Concept and Stoichiometry", "Hard", "20 cm³ of methane is exploded with 60 cm³ of oxygen. After cooling to room temperature the volume of the gaseous mixture is",
     "20 cm³", "40 cm³", "60 cm³", "80 cm³", "B",
     "CH₄ + 2O₂ → CO₂ + 2H₂O(l): 20 cm³ CH₄ uses 40 cm³ O₂ and forms 20 cm³ CO₂; the water condenses, leaving 20 cm³ CO₂ + 20 cm³ unused O₂ = 40 cm³.", "40"),
    ("Mole Concept and Stoichiometry", "Medium", "The concentration of a solution containing 5.3 g of sodium trioxocarbonate(IV) in 250 cm³ is (Na₂CO₃ = 106)",
     "0.05 mol/dm³", "0.10 mol/dm³", "0.20 mol/dm³", "0.50 mol/dm³", "C",
     "5.3/106 = 0.05 mol in 0.25 dm³ gives 0.05/0.25 = 0.20 mol/dm³.", "5.3/106/0.25"),
    ("Mole Concept and Stoichiometry", "Medium", "The volume of water that must be added to 100 cm³ of 0.5 mol/dm³ hydrochloric acid to reduce its concentration to 0.2 mol/dm³ is",
     "100 cm³", "150 cm³", "250 cm³", "400 cm³", "B",
     "C₁V₁ = C₂V₂: 0.5 × 100 = 0.2 × V₂, so V₂ = 250 cm³ and 250 − 100 = 150 cm³ of water must be added.", "250-100"),
    ("Mole Concept and Stoichiometry", "Hard", "8.0 g of copper(II) oxide was reduced by hydrogen and 5.6 g of copper was obtained. The percentage yield of copper is (Cu = 64, O = 16)",
     "70.0%", "80.0%", "87.5%", "93.3%", "C",
     "8.0 g CuO = 0.1 mol, so the theoretical yield is 0.1 × 64 = 6.4 g; 5.6/6.4 × 100 = 87.5%.", "5.6/6.4*100"),
    ("Mole Concept and Stoichiometry", "Medium", "The number of moles of ions present when 0.2 mol of calcium trioxonitrate(V), Ca(NO₃)₂, dissolves completely in water is",
     "0.2", "0.4", "0.6", "1.0", "C",
     "Each formula unit gives one Ca²⁺ and two NO₃⁻ ions (three ions): 0.2 × 3 = 0.6 mol.", "0.6"),
    ("Mole Concept and Stoichiometry", "Medium", "In the balanced equation aC₃H₈ + bO₂ → cCO₂ + dH₂O, the values of a, b, c and d are respectively",
     "1, 3, 3, 4", "1, 5, 3, 4", "2, 7, 6, 8", "1, 4, 3, 8", "B",
     "Propane has 3 C and 8 H, giving 3CO₂ and 4H₂O; the oxygen needed is (6 + 4)/2 = 5 O₂."),
    ("Mole Concept and Stoichiometry", "Easy", "The mass of sodium hydroxide required to prepare 250 cm³ of a 0.1 mol/dm³ solution is (NaOH = 40)",
     "0.5 g", "1.0 g", "2.5 g", "4.0 g", "B",
     "Moles = 0.1 × 0.25 = 0.025; mass = 0.025 × 40 = 1.0 g.", "0.1*0.25*40"),
    ("Mole Concept and Stoichiometry", "Medium", "The density of a gas at s.t.p. is 1.25 g/dm³. Its relative molecular mass is (molar volume = 22.4 dm³)",
     "14", "28", "44", "56", "B",
     "One mole occupies 22.4 dm³ at s.t.p.: 1.25 × 22.4 = 28 (nitrogen or carbon(II) oxide).", "1.25*22.4"),
    ("Mole Concept and Stoichiometry", "Medium", "A gas has a vapour density of 22. The volume occupied by 4.4 g of the gas at s.t.p. is (molar volume = 22.4 dm³)",
     "1.12 dm³", "2.24 dm³", "4.48 dm³", "11.2 dm³", "B",
     "Relative molecular mass = 2 × vapour density = 44; 4.4 g is 0.1 mol, which occupies 2.24 dm³.", "4.4/44*22.4"),
    ("Mole Concept and Stoichiometry", "Hard", "5.0 g of an impure sample of calcium trioxocarbonate(IV) reacted with excess acid to give 896 cm³ of carbon(IV) oxide at s.t.p. The percentage purity of the sample is (CaCO₃ = 100, molar volume = 22.4 dm³)",
     "40%", "60%", "80%", "90%", "C",
     "896 cm³ = 0.04 mol CO₂, which comes from 0.04 mol = 4.0 g of CaCO₃; 4.0/5.0 × 100 = 80%.", "0.896/22.4*100/5*100"),
    # ---------------- Acids, Bases and Salts ----------------
    ("Acids Bases and Salts", "Medium", "In the reaction NH₃ + H₂O ⇌ NH₄⁺ + OH⁻, the conjugate acid of ammonia is",
     "H₂O", "OH⁻", "NH₄⁺", "H₃O⁺", "C",
     "A conjugate acid is the base plus one proton; NH₃ gains H⁺ to become NH₄⁺, while water acts as the acid and OH⁻ is its conjugate base."),
    ("Acids Bases and Salts", "Medium", "When the pH of a solution changes from 3 to 5, the hydrogen ion concentration",
     "doubles", "increases 100 times", "decreases 100 times", "decreases 2 times", "C",
     "pH is −log[H⁺]; each unit is a tenfold change, so two units means [H⁺] falls from 10⁻³ to 10⁻⁵ mol/dm³, i.e. 100 times."),
    ("Acids Bases and Salts", "Easy", "Which of the following is an acid salt?",
     "NaCl", "Na₂SO₄", "NaHSO₄", "Na₂CO₃", "C",
     "NaHSO₄ still contains a replaceable hydrogen from the parent acid H₂SO₄; it can react with more base to form the normal salt Na₂SO₄."),
    ("Acids Bases and Salts", "Medium", "A solution of ammonium chloride turns blue litmus red because",
     "the salt contains free hydrochloric acid", "the ammonium ion reacts with water to release hydrogen ions", "chloride ions are acidic", "ammonia gas escapes from the solution", "B",
     "NH₄Cl is the salt of a strong acid and a weak base; NH₄⁺ hydrolyses (NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺), making the solution acidic."),
    ("Acids Bases and Salts", "Medium", "0.1 mol/dm³ solutions of hydrochloric acid and ethanoic acid were tested with a pH meter. The hydrochloric acid gave the lower pH because it",
     "is more concentrated", "is completely ionised in water while ethanoic acid is only partly ionised", "contains chlorine, which is very reactive", "has a higher relative molecular mass", "B",
     "At equal concentration the strong acid releases far more H⁺ ions; ethanoic acid exists mainly as un-ionised molecules."),
    ("Acids Bases and Salts", "Medium", "Which of the following procedures is most suitable for preparing pure crystals of zinc chloride?",
     "mixing zinc with concentrated acid and filtering off the zinc at once", "adding excess zinc to dilute HCl, filtering, then evaporating the filtrate to crystallise",
     "adding zinc to sodium chloride solution and evaporating to dryness", "burning zinc in chlorine, dissolving the product in water and filtering", "B",
     "Excess metal ensures all the acid is used; the unreacted zinc is filtered off and the salt crystallises from the filtrate on cooling."),
    ("Acids Bases and Salts", "Medium", "Sodium chloride is best prepared in the laboratory by",
     "adding sodium metal to dilute hydrochloric acid", "titrating sodium hydroxide with hydrochloric acid and evaporating the neutral solution",
     "adding excess sodium trioxocarbonate(IV) to acid and filtering", "mixing sodium sulphate and calcium chloride solutions and filtering", "B",
     "Both reactants and product are soluble, so titration (with an indicator) gives the exact neutral mixture; the salt is then recovered by evaporation."),
    ("Acids Bases and Salts", "Easy", "Crystals of Na₂CO₃·10H₂O left in an open dish turn to a white powder after a few days. This process is called",
     "deliquescence", "efflorescence", "hygroscopy", "sublimation", "B",
     "Efflorescent crystals lose their water of crystallisation to the air and crumble to a powder."),
    ("Acids Bases and Salts", "Easy", "Concentrated tetraoxosulphate(VI) acid is used to dry chlorine gas because the acid is",
     "a strong oxidising agent", "hygroscopic", "volatile", "a reducing agent", "B",
     "Hygroscopic substances absorb water vapour, so the acid removes moisture from the gas passed through it without reacting with chlorine."),
    ("Acids Bases and Salts", "Medium", "Which of the following oxides reacts with both dilute hydrochloric acid and sodium hydroxide solution?",
     "calcium oxide", "zinc oxide", "sulphur(IV) oxide", "carbon(II) oxide", "B",
     "Zinc oxide is amphoteric: it forms ZnCl₂ with the acid and sodium zincate, Na₂ZnO₂, with the alkali."),
    ("Acids Bases and Salts", "Medium", "20 cm³ of 0.25 mol/dm³ tetraoxosulphate(VI) acid exactly neutralised 40 cm³ of potassium hydroxide solution. The concentration of the alkali is",
     "0.125 mol/dm³", "0.25 mol/dm³", "0.50 mol/dm³", "1.00 mol/dm³", "B",
     "H₂SO₄ + 2KOH → K₂SO₄ + 2H₂O: moles of acid = 0.25 × 0.02 = 0.005, so moles KOH = 0.010 in 0.04 dm³ = 0.25 mol/dm³.", "0.25*0.02*2/0.04"),
    ("Acids Bases and Salts", "Medium", "Assuming complete ionisation, the pH of a 0.05 mol/dm³ solution of tetraoxosulphate(VI) acid is",
     "0.5", "1", "1.3", "2", "B",
     "Each H₂SO₄ gives two H⁺: [H⁺] = 0.1 mol/dm³ and pH = −log 0.1 = 1.", "1"),
    ("Acids Bases and Salts", "Medium", "The most suitable indicator for the titration of ethanoic acid (a weak acid) with sodium hydroxide is",
     "methyl orange", "phenolphthalein", "litmus", "universal indicator", "B",
     "The salt formed (sodium ethanoate) is alkaline, so the end point lies above pH 7, in the range where phenolphthalein changes colour."),
    ("Acids Bases and Salts", "Medium", "The number of moles of sodium hydroxide needed to neutralise 1 mol of tetraoxophosphate(V) acid, H₃PO₄, completely is",
     "1", "2", "3", "4", "C",
     "H₃PO₄ is tribasic, with three replaceable hydrogens: H₃PO₄ + 3NaOH → Na₃PO₄ + 3H₂O.", "3"),
    ("Acids Bases and Salts", "Medium", "A few drops of silver trioxonitrate(V) solution added to a salt solution gave a white precipitate that is insoluble in dilute trioxonitrate(V) acid but dissolves in aqueous ammonia. The salt contains",
     "chloride ions", "sulphate ions", "carbonate ions", "nitrate ions", "A",
     "Silver chloride is a white precipitate that stays in dilute nitric acid but dissolves in ammonia to form a soluble complex ion."),
    ("Acids Bases and Salts", "Easy", "A salt effervesces with dilute hydrochloric acid, giving a colourless gas that turns lime water milky. The anion present is",
     "sulphate", "trioxocarbonate(IV)", "chloride", "trioxonitrate(V)", "B",
     "Carbonates (and hydrogencarbonates) release carbon(IV) oxide with dilute acids; the gas forms a white precipitate of CaCO₃ in lime water."),
    ("Acids Bases and Salts", "Hard", "A salt solution gives a white precipitate with sodium hydroxide that dissolves in excess sodium hydroxide, and also a white precipitate with aqueous ammonia that dissolves in excess ammonia. The cation is",
     "Al³⁺", "Ca²⁺", "Zn²⁺", "Pb²⁺", "C",
     "Zn(OH)₂ is amphoteric (dissolves in excess NaOH) and also forms a soluble ammine complex in excess ammonia; Al³⁺ and Pb²⁺ do not dissolve in excess ammonia."),
    # ---------------- Chemical Reactions (redox, reaction types) ----------------
    ("Chemical Reactions", "Medium", "The oxidation number of sulphur in sodium thiosulphate, Na₂S₂O₃, is",
     "0", "+2", "+4", "+6", "B",
     "2(+1) + 2x + 3(−2) = 0 gives x = +2 (the average oxidation number of the two sulphur atoms)."),
    ("Chemical Reactions", "Medium", "In the reaction MnO₂ + 4HCl → MnCl₂ + Cl₂ + 2H₂O, the oxidising agent is",
     "MnO₂", "HCl", "MnCl₂", "Cl₂", "A",
     "Manganese falls from +4 to +2 (it is reduced) while chloride rises from −1 to 0; the substance that is itself reduced is the oxidising agent."),
    ("Chemical Reactions", "Easy", "Which of the following changes is an oxidation?",
     "Cl₂ → 2Cl⁻", "Cu²⁺ → Cu", "Fe²⁺ → Fe³⁺", "MnO₄⁻ → Mn²⁺", "C",
     "Oxidation is loss of electrons or an increase in oxidation number; Fe²⁺ loses an electron to become Fe³⁺."),
    ("Chemical Reactions", "Medium", "When Cr₂O₇²⁻ is converted to Cr³⁺, the oxidation number of chromium changes from",
     "+6 to +3", "+7 to +3", "+6 to +2", "+3 to +6", "A",
     "In Cr₂O₇²⁻: 2x + 7(−2) = −2, so x = +6; the fall to +3 means chromium is reduced."),
    ("Chemical Reactions", "Medium", "When chlorine is bubbled through potassium iodide solution, the solution turns brown because",
     "chlorine dissolves to give a brown solution", "chlorine oxidises iodide ions to iodine", "potassium is displaced as a brown metal", "chlorine reduces iodide ions to iodine", "B",
     "Cl₂ + 2I⁻ → 2Cl⁻ + I₂; the iodide ions lose electrons (are oxidised) and the iodine formed colours the solution brown."),
    ("Chemical Reactions", "Medium", "In the reaction 2H₂S + SO₂ → 3S + 2H₂O, sulphur(IV) oxide acts as",
     "a reducing agent", "an oxidising agent", "a catalyst", "a dehydrating agent", "B",
     "Sulphur in SO₂ falls from +4 to 0 (reduced) while sulphur in H₂S rises from −2 to 0; SO₂ therefore oxidises H₂S."),
    ("Chemical Reactions", "Hard", "Which of the following is a disproportionation reaction?",
     "Zn + CuSO₄ → ZnSO₄ + Cu", "Cl₂ + 2NaOH → NaCl + NaOCl + H₂O", "2Mg + O₂ → 2MgO", "CaCO₃ → CaO + CO₂", "B",
     "In disproportionation the same element is both oxidised and reduced: chlorine goes from 0 to −1 (in NaCl) and to +1 (in NaOCl)."),
    ("Chemical Reactions", "Easy", "Which of the following is a double decomposition reaction?",
     "AgNO₃(aq) + NaCl(aq) → AgCl(s) + NaNO₃(aq)", "2H₂O₂ → 2H₂O + O₂", "Fe + S → FeS", "Zn + 2HCl → ZnCl₂ + H₂", "A",
     "Two compounds exchange partners to form two new compounds, one of them a precipitate."),
    ("Chemical Reactions", "Medium", "Zinc reacts with copper(II) tetraoxosulphate(VI) solution but copper does not react with zinc tetraoxosulphate(VI) solution. This is because zinc",
     "is a stronger reducing agent than copper", "is a weaker reducing agent than copper", "is less reactive than copper", "has a smaller atomic mass than copper", "A",
     "Zinc is above copper in the activity series, so it loses electrons more readily and can displace copper ions from solution, but not the reverse."),
    ("Chemical Reactions", "Easy", "In the reaction CuO + H₂ → Cu + H₂O, the reducing agent is",
     "CuO", "H₂", "Cu", "H₂O", "B",
     "Hydrogen removes oxygen from copper(II) oxide and is itself oxidised to water; the substance oxidised is the reducing agent."),
    ("Chemical Reactions", "Hard", "In acid solution, the number of moles of Fe²⁺ ions oxidised by 1 mol of MnO₄⁻ ions is",
     "1", "2", "3", "5", "D",
     "MnO₄⁻ + 8H⁺ + 5Fe²⁺ → Mn²⁺ + 5Fe³⁺ + 4H₂O; manganese gains five electrons, one from each of five Fe²⁺ ions.", "5"),
    ("Chemical Reactions", "Medium", "Which of the following reactions involves oxidation and reduction?",
     "NaOH + HCl → NaCl + H₂O", "AgNO₃ + NaCl → AgCl + NaNO₃", "2Mg + O₂ → 2MgO", "CaCO₃ → CaO + CO₂", "C",
     "Only in the burning of magnesium do oxidation numbers change: Mg goes from 0 to +2 and O from 0 to −2."),
    ("Chemical Reactions", "Medium", "The oxidation number of nitrogen in the trioxonitrate(V) ion, NO₃⁻, is",
     "+3", "+4", "+5", "−3", "C",
     "x + 3(−2) = −1 gives x = +5, which is why the ion is named trioxonitrate(V)."),
    ("Chemical Reactions", "Medium", "When sulphur(IV) oxide is bubbled into acidified potassium tetraoxomanganate(VII) solution, the purple colour disappears because SO₂",
     "is a bleaching agent for all dyes", "reduces MnO₄⁻ ions to almost colourless Mn²⁺ ions", "oxidises the manganese to a colourless compound", "dissolves the permanganate crystals", "B",
     "SO₂ is a reducing agent; it is oxidised to sulphate while purple MnO₄⁻ (manganese +7) is reduced to Mn²⁺ (+2)."),
    # ---------------- Electrochemistry ----------------
    ("Electrochemistry", "Medium", "The mass of copper deposited at the cathode when 0.2 faraday of electricity is passed through copper(II) tetraoxosulphate(VI) solution is (Cu = 64)",
     "3.2 g", "6.4 g", "12.8 g", "25.6 g", "B",
     "Cu²⁺ + 2e⁻ → Cu: 0.2 F deposits 0.2/2 = 0.1 mol = 6.4 g of copper.", "0.2/2*64"),
    ("Electrochemistry", "Hard", "A current of 3 A passed for 30 minutes through a solution of a divalent metal ion deposited 1.8 g of the metal. The relative atomic mass of the metal is approximately (1 F = 96,500 C)",
     "27", "56", "64", "108", "C",
     "Q = 3 × 1800 = 5,400 C = 0.056 mol of electrons; a divalent ion needs 2 mol of electrons per mole, so 0.028 mol of metal weighs 1.8 g, giving M ≈ 64 (copper).", "1.8/(3*1800/96500/2)"),
    ("Electrochemistry", "Medium", "The volume of hydrogen at s.t.p. liberated at the cathode when 0.5 faraday is passed through dilute tetraoxosulphate(VI) acid is (molar volume = 22.4 dm³)",
     "2.8 dm³", "5.6 dm³", "11.2 dm³", "22.4 dm³", "B",
     "2H⁺ + 2e⁻ → H₂: 0.5 F gives 0.25 mol of H₂ = 0.25 × 22.4 = 5.6 dm³.", "0.5/2*22.4"),
    ("Electrochemistry", "Medium", "During the electrolysis of copper(II) tetraoxosulphate(VI) solution with copper electrodes, the blue colour of the solution",
     "fades gradually", "becomes deeper", "remains unchanged", "turns green", "C",
     "Copper dissolves from the anode as fast as it is deposited on the cathode, so the Cu²⁺ concentration, and hence the colour, stays constant."),
    ("Electrochemistry", "Medium", "When very dilute sodium chloride solution is electrolysed with platinum electrodes, the products at the cathode and anode respectively are",
     "sodium and chlorine", "hydrogen and chlorine", "hydrogen and oxygen", "sodium and oxygen", "C",
     "At low chloride concentration OH⁻ is discharged in preference to Cl⁻, giving oxygen at the anode; H⁺ is always discharged rather than Na⁺."),
    ("Electrochemistry", "Easy", "To electroplate an iron spoon with silver, the spoon should be made the",
     "cathode, in a solution containing silver ions", "anode, in a solution containing silver ions", "cathode, in a solution containing iron ions", "anode, in dilute tetraoxosulphate(VI) acid", "A",
     "Metal is deposited at the cathode (Ag⁺ + e⁻ → Ag); a silver anode dissolves to keep the Ag⁺ concentration steady."),
    ("Electrochemistry", "Medium", "In the electrolysis of concentrated sodium chloride solution, chloride ions are discharged at the anode in preference to hydroxide ions mainly because of",
     "the position of chlorine in the electrochemical series", "the much higher concentration of chloride ions", "the nature of the platinum electrodes", "the low temperature of the solution", "B",
     "Hydroxide ions are normally discharged more easily, but a very high concentration of chloride ions reverses the preference."),
    ("Electrochemistry", "Easy", "In the Daniell cell Zn(s)|Zn²⁺(aq)||Cu²⁺(aq)|Cu(s), electrons flow through the external wire",
     "from zinc to copper", "from copper to zinc", "through the salt bridge only", "in both directions alternately", "A",
     "Zinc is oxidised (Zn → Zn²⁺ + 2e⁻) and releases electrons, which travel through the wire to the copper electrode where Cu²⁺ ions are reduced."),
    ("Electrochemistry", "Medium", "The salt bridge in an electrochemical cell",
     "supplies electrons to the cathode", "allows ions to move between the half-cells and keeps them electrically neutral", "prevents any ions from moving between the solutions", "acts as the negative electrode", "B",
     "Without the salt bridge charge would build up in each half-cell and the current would stop almost immediately."),
    ("Electrochemistry", "Medium", "An iron nail kept in boiled water under a layer of oil did not rust, while a similar nail in tap water open to the air rusted. This shows that rusting requires",
     "water only", "oxygen (air) as well as water", "oil-free water", "high temperature", "B",
     "Boiling removes dissolved oxygen and the oil keeps air out; the nail with water but no oxygen did not rust."),
    ("Electrochemistry", "Medium", "A scratched galvanised (zinc-coated) bucket does not rust because zinc",
     "forms a waterproof paint over the scratch", "is more readily oxidised than iron and corrodes in its place", "is less reactive than iron", "reacts with the rust to remove it", "B",
     "Zinc is above iron in the activity series; it becomes the anode and is sacrificed while iron remains protected even where exposed."),
    ("Electrochemistry", "Hard", "Given E°(Fe³⁺/Fe²⁺) = +0.77 V and E°(I₂/I⁻) = +0.54 V, when iron(III) chloride solution is added to potassium iodide solution",
     "no reaction occurs", "iodide ions are oxidised to iodine", "iron(III) ions are oxidised", "iodine is reduced to iodide", "B",
     "E°cell = 0.77 − 0.54 = +0.23 V, so Fe³⁺ oxidises I⁻ to I₂ (the solution turns brown) and is itself reduced to Fe²⁺."),
    ("Electrochemistry", "Medium", "The time needed for a current of 1 A to deposit 0.5 mol of silver from silver trioxonitrate(V) solution is (1 F = 96,500 C)",
     "24,125 s", "48,250 s", "96,500 s", "193,000 s", "B",
     "Ag⁺ + e⁻ → Ag: 0.5 mol needs 0.5 F = 48,250 C; t = Q/I = 48,250 s.", "0.5*96500"),
    ("Electrochemistry", "Easy", "Which of the following liquids will NOT conduct an electric current?",
     "molten sodium chloride", "copper(II) tetraoxosulphate(VI) solution", "sugar solution", "dilute tetraoxosulphate(VI) acid", "C",
     "Sugar dissolves as neutral molecules and gives no ions, so its solution is a non-electrolyte."),
    # ---------------- Energy and Rates of Reaction ----------------
    ("Energy and Rates of Reaction", "Easy", "When ammonium chloride dissolves in water, the beaker feels cold. This shows that the dissolution is",
     "exothermic with a negative ΔH", "endothermic with a positive ΔH", "exothermic with a positive ΔH", "endothermic with a negative ΔH", "B",
     "Heat is absorbed from the surroundings (the beaker cools), so the enthalpy change is positive."),
    ("Energy and Rates of Reaction", "Hard", "Given C(s) + O₂(g) → CO₂(g), ΔH = −394 kJ and CO(g) + ½O₂(g) → CO₂(g), ΔH = −283 kJ, the enthalpy change for C(s) + ½O₂(g) → CO(g) is",
     "−677 kJ", "−111 kJ", "+111 kJ", "+677 kJ", "B",
     "By Hess's law: ΔH = −394 − (−283) = −111 kJ.", "-394+283"),
    ("Energy and Rates of Reaction", "Hard", "Bond energies: H–H 436, Cl–Cl 242 and H–Cl 431 kJ/mol. The enthalpy change for H₂(g) + Cl₂(g) → 2HCl(g) is",
     "−184 kJ", "+184 kJ", "−247 kJ", "+247 kJ", "A",
     "ΔH = bonds broken − bonds formed = (436 + 242) − 2(431) = −184 kJ.", "(436+242)-2*431"),
    ("Energy and Rates of Reaction", "Hard", "50 cm³ of 1.0 mol/dm³ HCl was mixed with 50 cm³ of 1.0 mol/dm³ NaOH and the temperature rose by 6.8 °C. The enthalpy of neutralisation is (density = 1 g/cm³, c = 4.2 J g⁻¹ K⁻¹)",
     "−28.6 kJ/mol", "−57.1 kJ/mol", "−114 kJ/mol", "−2.86 kJ/mol", "B",
     "Heat = 100 × 4.2 × 6.8 = 2,856 J for 0.05 mol of water formed; 2,856/0.05 = 57,120 J/mol ≈ −57.1 kJ/mol.", "-100*4.2*6.8/0.05/1000"),
    ("Energy and Rates of Reaction", "Medium", "A catalyst added to a reaction does NOT change the",
     "rate of the forward reaction", "activation energy", "enthalpy change of the reaction", "time taken to reach equilibrium", "C",
     "A catalyst provides a lower-energy pathway and speeds up both directions, but the energy difference between reactants and products is unchanged."),
    ("Energy and Rates of Reaction", "Medium", "Raising the temperature increases the rate of a reaction mainly because",
     "the activation energy is lowered", "a larger fraction of the molecules have energy equal to or greater than the activation energy", "the molecules become larger and collide more", "the reaction becomes more exothermic", "B",
     "Higher temperature increases the number of molecules with sufficient energy and the collision frequency, so many more collisions are successful."),
    ("Energy and Rates of Reaction", "Easy", "Food keeps longer in a refrigerator because the low temperature",
     "kills all the bacteria in the food", "slows down the chemical reactions that cause decay", "removes water from the food", "stops oxygen from reaching the food", "B",
     "Rates of reaction, including those catalysed by microbial enzymes, fall sharply as the temperature is lowered."),
    ("Energy and Rates of Reaction", "Medium", "Which of the following processes is accompanied by an increase in entropy?",
     "freezing of water", "condensation of steam", "sublimation of iodine", "crystallisation of salt from solution", "C",
     "Entropy (disorder) rises when a solid becomes a gas, whose particles move randomly and occupy far more space."),
    ("Energy and Rates of Reaction", "Hard", "A reaction is spontaneous at all temperatures when",
     "ΔH is positive and ΔS is negative", "ΔH is negative and ΔS is positive", "ΔH and ΔS are both positive", "ΔH and ΔS are both negative", "B",
     "ΔG = ΔH − TΔS is negative at every temperature only when ΔH is negative and ΔS is positive."),
    ("Energy and Rates of Reaction", "Medium", "In an exothermic reaction, the activation energy of the forward reaction is",
     "greater than that of the reverse reaction", "less than that of the reverse reaction", "equal to that of the reverse reaction", "equal to the enthalpy change", "B",
     "The products lie below the reactants, so the reverse reaction must climb from a lower level to the same peak, needing more energy."),
    ("Energy and Rates of Reaction", "Medium", "The concentration of a reactant fell from 0.8 mol/dm³ to 0.2 mol/dm³ in 3 minutes. The average rate of reaction is",
     "0.1 mol dm⁻³ min⁻¹", "0.2 mol dm⁻³ min⁻¹", "0.3 mol dm⁻³ min⁻¹", "0.6 mol dm⁻³ min⁻¹", "B",
     "Rate = change in concentration ÷ time = (0.8 − 0.2)/3 = 0.2 mol dm⁻³ min⁻¹.", "(0.8-0.2)/3"),
    ("Energy and Rates of Reaction", "Hard", "Burning 0.5 g of ethanol raised the temperature of 200 g of water by 15 °C. The enthalpy of combustion of ethanol is approximately (C₂H₅OH = 46, c = 4.2 J g⁻¹ K⁻¹)",
     "−12.6 kJ/mol", "−580 kJ/mol", "−1,159 kJ/mol", "−2,318 kJ/mol", "C",
     "Heat = 200 × 4.2 × 15 = 12,600 J from 0.5/46 = 0.0109 mol; 12,600/0.0109 ≈ 1,159,000 J/mol, i.e. −1,159 kJ/mol.", "-200*4.2*15/(0.5/46)/1000"),
    ("Energy and Rates of Reaction", "Medium", "A lump of coal burns slowly in air, but coal dust suspended in air can explode. The difference is due to",
     "the higher purity of coal dust", "the much larger surface area of the dust", "a lower activation energy for coal dust", "the higher temperature of the dust", "B",
     "Finely divided solids expose a far greater surface to oxygen, so collisions occur much more often and the reaction is very fast."),
    # ---------------- Chemical Equilibrium ----------------
    ("Chemical Equilibrium", "Medium", "For the reaction 2SO₂(g) + O₂(g) ⇌ 2SO₃(g), the equilibrium constant Kc is",
     "[SO₃]² / ([SO₂]²[O₂])", "[SO₂]²[O₂] / [SO₃]²", "[SO₃] / ([SO₂][O₂])", "2[SO₃] / (2[SO₂] + [O₂])", "A",
     "Kc = products over reactants, each concentration raised to the power of its coefficient in the balanced equation."),
    ("Chemical Equilibrium", "Hard", "Kc for H₂(g) + I₂(g) ⇌ 2HI(g) is 50 at a certain temperature. If [H₂] = [I₂] = 0.10 mol/dm³ at equilibrium, the concentration of HI is",
     "0.50 mol/dm³", "0.71 mol/dm³", "5.0 mol/dm³", "0.25 mol/dm³", "B",
     "[HI]² = Kc × [H₂][I₂] = 50 × 0.01 = 0.50, so [HI] = √0.50 = 0.71 mol/dm³.", "math.sqrt(50*0.1*0.1)"),
    ("Chemical Equilibrium", "Medium", "Which change will shift the equilibrium PCl₅(g) ⇌ PCl₃(g) + Cl₂(g), ΔH = +ve, to the right?",
     "increasing the pressure", "adding more chlorine", "raising the temperature", "adding a catalyst", "C",
     "The forward reaction is endothermic, so heat favours it; higher pressure and added Cl₂ push the equilibrium left and a catalyst has no effect on the position."),
    ("Chemical Equilibrium", "Easy", "Which statement is true of a chemical system at dynamic equilibrium?",
     "the forward and reverse reactions have stopped", "the rates of the forward and reverse reactions are equal", "the concentrations of reactants and products are equal", "only the forward reaction continues", "B",
     "Both reactions continue at the same rate, so the concentrations stay constant although they need not be equal to each other."),
    ("Chemical Equilibrium", "Medium", "For the equilibrium N₂O₄(g) ⇌ 2NO₂(g), a decrease in pressure will",
     "favour the formation of NO₂", "favour the formation of N₂O₄", "have no effect on the equilibrium", "stop the reaction completely", "A",
     "Lower pressure favours the side with more moles of gas; two moles of NO₂ form from one of N₂O₄."),
    ("Chemical Equilibrium", "Medium", "Changing the pressure has no effect on the position of the equilibrium CO(g) + H₂O(g) ⇌ CO₂(g) + H₂(g) because",
     "the reaction is exothermic", "there are equal numbers of moles of gas on both sides", "water vapour is not a gas", "carbon(II) oxide is insoluble", "B",
     "Two moles of gas become two moles of gas, so a pressure change cannot favour either direction."),
    ("Chemical Equilibrium", "Easy", "The equilibrium constant of a reaction is 1 × 10¹⁰. This means that at equilibrium",
     "reactants greatly predominate over products", "products greatly predominate over reactants", "reactants and products are present in equal amounts", "the reaction is very slow", "B",
     "A very large K means the numerator (products) is enormous compared with the denominator (reactants); the equilibrium lies far to the right."),
    ("Chemical Equilibrium", "Medium", "In the Haber process a temperature of about 450 °C is used, although a lower temperature would give more ammonia, because",
     "the iron catalyst only works above 450 °C", "at lower temperatures the rate is too slow to be economical", "ammonia decomposes below 450 °C", "nitrogen is a liquid below 450 °C", "B",
     "The forward reaction is exothermic, so low temperature favours the yield, but the compromise temperature gives an acceptable yield quickly enough."),
    ("Chemical Equilibrium", "Hard", "The unit of Kc for the equilibrium 2SO₂(g) + O₂(g) ⇌ 2SO₃(g) is",
     "mol dm⁻³", "dm³ mol⁻¹", "mol² dm⁻⁶", "no unit", "B",
     "Kc = (mol dm⁻³)² ÷ [(mol dm⁻³)² × (mol dm⁻³)] = 1/(mol dm⁻³) = dm³ mol⁻¹."),
    ("Chemical Equilibrium", "Medium", "In the equilibrium Fe³⁺(aq) + SCN⁻(aq) ⇌ FeSCN²⁺(aq) (deep red), adding a reagent that removes Fe³⁺ ions makes the red colour fade because",
     "the equilibrium shifts to the right", "the equilibrium shifts to the left to replace the Fe³⁺", "the FeSCN²⁺ ion is oxidised", "SCN⁻ ions are precipitated", "B",
     "By Le Chatelier's principle the system opposes the loss of Fe³⁺ by decomposing some FeSCN²⁺, so less of the red complex remains."),
    ("Chemical Equilibrium", "Hard", "1 mol of ethanoic acid and 1 mol of ethanol were mixed in a 1 dm³ vessel. At equilibrium 2/3 mol of ethyl ethanoate had formed. The equilibrium constant Kc is",
     "0.25", "2", "4", "9", "C",
     "At equilibrium ester = water = 2/3 mol and acid = alcohol = 1/3 mol: Kc = (2/3 × 2/3)/(1/3 × 1/3) = 4.", "4"),
    # ---------------- Metals and Non-Metals ----------------
    ("Metals and Non-Metals", "Medium", "When copper turnings are warmed with concentrated tetraoxosulphate(VI) acid, a colourless gas is evolved that decolourises acidified potassium tetraoxomanganate(VII). The gas is",
     "hydrogen", "sulphur(IV) oxide", "oxygen", "hydrogen sulphide", "B",
     "Hot concentrated H₂SO₄ oxidises copper and is itself reduced to SO₂, a reducing gas that decolourises acidified KMnO₄."),
    ("Metals and Non-Metals", "Easy", "A colourless gas collected over water burns with a 'pop' sound when a lighted splint is brought near it. The gas is",
     "oxygen", "hydrogen", "carbon(IV) oxide", "chlorine", "B",
     "The pop is the small explosion of hydrogen combining with oxygen in the air to form water."),
    ("Metals and Non-Metals", "Medium", "Moist blue litmus paper held in chlorine gas first turns red and is then bleached. The bleaching is caused by",
     "chlorine gas dissolving the dye", "oxochlorate(I) acid, HOCl, formed with water, which oxidises the dye", "hydrogen chloride reducing the dye", "the heat of the reaction", "B",
     "Cl₂ + H₂O ⇌ HCl + HOCl; the acids turn litmus red and HOCl, an oxidising agent, destroys the colour. Dry chlorine does not bleach."),
    ("Metals and Non-Metals", "Medium", "Freshly prepared iron(II) tetraoxosulphate(VI) solution was added to a salt solution and concentrated tetraoxosulphate(VI) acid was poured carefully down the side of the tube. A brown ring formed. The salt contains",
     "chloride ions", "trioxonitrate(V) ions", "trioxocarbonate(IV) ions", "sulphite ions", "B",
     "The brown ring test is the confirmatory test for nitrates; the ring is a complex of iron(II) with nitrogen(II) oxide."),
    ("Metals and Non-Metals", "Medium", "Concentrated tetraoxosulphate(VI) acid cannot be used to dry ammonia gas because",
     "ammonia is insoluble in the acid", "the acid reacts with ammonia to form ammonium tetraoxosulphate(VI)", "the acid is too dilute", "ammonia is lighter than the acid", "B",
     "Ammonia is a base; the drying agent must be non-reactive, so quicklime (CaO) is used instead."),
    ("Metals and Non-Metals", "Easy", "Brown fumes are produced when concentrated trioxonitrate(V) acid is added to copper. The brown gas is",
     "nitrogen(II) oxide", "nitrogen(IV) oxide", "nitrogen", "dinitrogen oxide", "B",
     "Cu + 4HNO₃ → Cu(NO₃)₂ + 2NO₂ + 2H₂O; nitrogen(IV) oxide is the reddish-brown, acidic gas."),
    ("Metals and Non-Metals", "Easy", "Graphite is used as a lubricant because",
     "it is a very hard substance", "its layers slide easily over one another", "it melts at a low temperature", "it dissolves in oil", "B",
     "The weak forces between the flat layers of carbon atoms let the layers slip, so graphite feels slippery."),
    ("Metals and Non-Metals", "Medium", "In the extraction of aluminium, purified bauxite (Al₂O₃) is dissolved in molten cryolite. The cryolite is used to",
     "act as the reducing agent", "lower the melting point of the aluminium oxide", "remove iron impurities", "supply extra aluminium ions", "B",
     "Alumina melts above 2000 °C; dissolving it in cryolite allows electrolysis at about 950 °C, saving energy."),
    ("Metals and Non-Metals", "Medium", "Tin is extracted from its ore, cassiterite (SnO₂), by",
     "electrolysis of the molten ore", "heating the ore with carbon (coke)", "heating the ore in air", "dissolving the ore in acid and evaporating", "B",
     "Tin is low enough in the activity series for carbon to reduce its oxide: SnO₂ + 2C → Sn + 2CO."),
    ("Metals and Non-Metals", "Medium", "In the electrolytic refining of copper, the impure copper is made the",
     "anode", "cathode", "electrolyte", "salt bridge", "A",
     "Copper dissolves from the impure anode as Cu²⁺ and is deposited as pure copper on the cathode; impurities fall as anode sludge."),
    ("Metals and Non-Metals", "Hard", "A scratched tin-plated iron can rusts faster than a scratched galvanised iron sheet because",
     "tin is more reactive than iron and dissolves", "tin is less reactive than iron, so iron corrodes preferentially at the scratch", "zinc prevents water from reaching the scratch", "tin reacts with air to form an acid", "B",
     "Once the tin coating is broken, iron (the more reactive metal) becomes the anode and corrodes; zinc, being more reactive than iron, corrodes instead of the iron."),
    ("Metals and Non-Metals", "Easy", "Sodium metal is stored under paraffin oil because it",
     "reacts readily with oxygen and moisture in the air", "melts at room temperature", "is a liquid that evaporates", "dissolves in water to give an acid", "A",
     "Sodium tarnishes rapidly in air and reacts violently with water; the oil keeps both away."),
    ("Metals and Non-Metals", "Easy", "A farmer adds quicklime (calcium oxide) to his field in order to",
     "neutralise acidity in the soil", "supply nitrogen to the crops", "kill earthworms", "make the soil more acidic", "A",
     "Calcium oxide is a basic oxide that reacts with acids in the soil, raising the pH."),
    ("Metals and Non-Metals", "Medium", "Oxygen (O₂) and ozone (O₃) are described as allotropes because they are",
     "isotopes of the same element", "different physical forms of the same element in the same state", "compounds of oxygen with different formulae", "different states of the same substance", "B",
     "Allotropes are different structural forms of one element, like diamond and graphite for carbon."),
    ("Metals and Non-Metals", "Medium", "Nitrogen gas is very unreactive at room temperature because",
     "it is a noble gas", "the triple bond between its atoms is very strong", "its molecules are very large", "it is less dense than air", "B",
     "Breaking the N≡N bond needs about 945 kJ/mol, so most reactions of nitrogen need high temperature, pressure or a catalyst."),
    ("Metals and Non-Metals", "Medium", "Sulphur burns in air with a blue flame to give a gas that turns acidified potassium heptaoxodichromate(VI) paper from orange to green. The gas is",
     "sulphur(IV) oxide", "hydrogen sulphide", "carbon(IV) oxide", "sulphur(VI) oxide", "A",
     "SO₂ is a reducing agent; it reduces orange dichromate(VI) to green chromium(III)."),
    # ---------------- Organic Chemistry ----------------
    ("Organic Chemistry", "Easy", "Which of the following hydrocarbons belongs to the alkene series?",
     "C₄H₁₀", "C₄H₈", "C₄H₆", "C₆H₆", "B",
     "Alkenes have the general formula CₙH₂ₙ; C₄H₈ (butene) fits, C₄H₁₀ is an alkane, C₄H₆ an alkyne and C₆H₆ is benzene."),
    ("Organic Chemistry", "Hard", "A gaseous hydrocarbon decolourises bromine water and gives a white precipitate with ammoniacal silver trioxonitrate(V). It is",
     "ethane", "ethene", "ethyne", "methane", "C",
     "Only a terminal alkyne such as ethyne has an acidic hydrogen that forms the silver salt; ethene decolourises bromine but gives no precipitate."),
    ("Organic Chemistry", "Medium", "An organic compound effervesces with sodium hydrogentrioxocarbonate(IV) solution. Its functional group is",
     "hydroxyl, –OH", "carboxyl, –COOH", "aldehyde, –CHO", "amino, –NH₂", "B",
     "Carboxylic acids are acidic enough to liberate carbon(IV) oxide from hydrogencarbonates; alcohols and aldehydes are not."),
    ("Organic Chemistry", "Medium", "The IUPAC name of CH₃CH=CHCH₃ is",
     "but-1-ene", "but-2-ene", "butane", "2-methylpropene", "B",
     "The chain has four carbons and the double bond starts at the second carbon."),
    ("Organic Chemistry", "Medium", "The number of structural isomers of C₅H₁₂ is",
     "2", "3", "4", "5", "B",
     "Pentane, 2-methylbutane and 2,2-dimethylpropane are the three isomers.", "3"),
    ("Organic Chemistry", "Medium", "When ethanol is warmed with acidified potassium heptaoxodichromate(VI), the solution turns from orange to green because",
     "ethanol is reduced to ethane", "ethanol is oxidised while dichromate(VI) is reduced to chromium(III)", "the dichromate dissolves in ethanol", "ethanol is dehydrated to ethene", "B",
     "Ethanol is oxidised (via ethanal) to ethanoic acid; the oxidising agent Cr₂O₇²⁻ (orange) is reduced to green Cr³⁺."),
    ("Organic Chemistry", "Medium", "Which reagent distinguishes ethanol from ethanoic acid?",
     "bromine water", "sodium trioxocarbonate(IV) solution", "ammoniacal silver trioxonitrate(V)", "distilled water", "B",
     "Ethanoic acid effervesces with the carbonate, releasing CO₂; ethanol gives no reaction."),
    ("Organic Chemistry", "Medium", "When an ester is boiled with sodium hydroxide solution, the products are an alcohol and the sodium salt of the acid. This reaction is called",
     "esterification", "saponification (alkaline hydrolysis)", "polymerisation", "dehydration", "B",
     "Saponification is the alkaline hydrolysis of esters; with fats and oils it produces soap."),
    ("Organic Chemistry", "Medium", "Nylon is formed from its monomers by condensation polymerisation. This means that",
     "the monomers simply add together with no other product", "a small molecule such as water is eliminated as each monomer joins", "the polymer forms only in the presence of light", "the monomers must contain a double bond", "B",
     "In condensation polymerisation each new link releases a small molecule; addition polymers such as polythene form with no by-product."),
    ("Organic Chemistry", "Medium", "Methane reacts with chlorine in the presence of sunlight to form chloromethane and hydrogen chloride. The reaction is",
     "an addition reaction", "a substitution reaction", "a polymerisation", "a hydrolysis", "B",
     "A hydrogen atom of the saturated alkane is replaced by chlorine; alkanes cannot undergo addition."),
    ("Organic Chemistry", "Medium", "The volume of oxygen required for the complete combustion of 10 cm³ of propane, C₃H₈, is",
     "30 cm³", "40 cm³", "50 cm³", "100 cm³", "C",
     "C₃H₈ + 5O₂ → 3CO₂ + 4H₂O; volumes of gases are in the same ratio as moles, so 10 × 5 = 50 cm³.", "10*5"),
    ("Organic Chemistry", "Hard", "The mass of ethanol obtained by the complete fermentation of 18 g of glucose is (C₆H₁₂O₆ = 180, C₂H₅OH = 46)",
     "4.6 g", "9.2 g", "18 g", "23 g", "B",
     "C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂; 0.1 mol of glucose gives 0.2 mol of ethanol = 0.2 × 46 = 9.2 g.", "18/180*2*46"),
    ("Organic Chemistry", "Easy", "Which of the following compounds will decolourise bromine water in the dark?",
     "propane", "propene", "benzene", "ethanol", "B",
     "Only the unsaturated alkene adds bromine across its double bond without light; propane needs light for substitution and benzene resists addition."),
    ("Organic Chemistry", "Medium", "Which of the following alcohols is oxidised to a ketone?",
     "methanol", "ethanol", "propan-1-ol", "propan-2-ol", "D",
     "Secondary alcohols, in which the –OH carbon carries two alkyl groups, are oxidised to ketones (propanone); primary alcohols give aldehydes and acids."),
    ("Organic Chemistry", "Medium", "A compound with the molecular formula C₃H₆O₂ could be",
     "propanal", "propanoic acid", "propan-1-ol", "propanone", "B",
     "Propanoic acid, CH₃CH₂COOH, has three carbons, six hydrogens and two oxygens; the others contain only one oxygen or more hydrogens."),
    ("Organic Chemistry", "Hard", "Benzene undergoes substitution rather than addition reactions because",
     "it has no hydrogen atoms", "its delocalised electrons give the ring extra stability that addition would destroy", "it is a saturated hydrocarbon", "its carbon atoms are joined by single bonds only", "B",
     "The six π electrons are spread over the whole ring; substitution keeps this stable system while addition would break it."),
    ("Organic Chemistry", "Medium", "Ethene is converted to ethanol industrially by",
     "fermentation with yeast", "reaction with steam over a phosphoric acid catalyst", "heating with concentrated sulphuric acid alone", "oxidation with acidified dichromate", "B",
     "Direct hydration: C₂H₄ + H₂O → C₂H₅OH at about 300 °C and 60 atm over phosphoric acid on silica."),
    # ---------------- Water, Air and Environmental Chemistry ----------------
    ("Water Air and Environmental Chemistry", "Medium", "Permanent hardness in water can be removed by",
     "boiling the water", "adding washing soda, Na₂CO₃", "filtering the water", "adding calcium tetraoxosulphate(VI)", "B",
     "Carbonate ions precipitate the Ca²⁺ and Mg²⁺ ions as insoluble carbonates; boiling only removes temporary hardness."),
    ("Water Air and Environmental Chemistry", "Medium", "Which of the following is an advantage of hard water?",
     "it lathers easily with soap", "it does not fur kettles and boilers", "it supplies calcium for strong bones and teeth", "it wastes less soap", "C",
     "The dissolved calcium salts are nutritionally useful and give the water a pleasant taste; the other options are disadvantages or false."),
    ("Water Air and Environmental Chemistry", "Medium", "In the treatment of water for a town, alum [Al₂(SO₄)₃] is added in order to",
     "kill bacteria", "coagulate suspended particles so that they settle", "remove the hardness", "add fluoride to the water", "B",
     "Alum forms a gelatinous aluminium hydroxide precipitate that traps fine suspended matter; chlorine is added later to kill germs."),
    ("Water Air and Environmental Chemistry", "Medium", "100 cm³ of air was passed repeatedly over heated copper until no further change occurred. The volume of gas remaining was about",
     "21 cm³", "50 cm³", "79 cm³", "100 cm³", "C",
     "Copper removes the oxygen (about 21% of air) as copper(II) oxide, leaving mainly nitrogen, about 79 cm³.", "79"),
    ("Water Air and Environmental Chemistry", "Medium", "Rain water collected near an industrial area had a pH of 4.2. This is mainly due to dissolved",
     "carbon(IV) oxide only", "sulphur(IV) oxide and oxides of nitrogen", "oxygen and nitrogen", "ozone from the upper atmosphere", "B",
     "Sulphur and nitrogen oxides from burning fuels dissolve to form sulphurous, sulphuric and nitric acids, making rain far more acidic than the pH 5.6 caused by CO₂ alone."),
    ("Water Air and Environmental Chemistry", "Easy", "A petrol generator running in a closed room can kill the occupants because it releases",
     "carbon(IV) oxide, which is heavier than air", "carbon(II) oxide, which binds to haemoglobin and stops oxygen transport", "nitrogen, which dilutes the oxygen", "water vapour, which causes suffocation", "B",
     "Incomplete combustion produces odourless carbon(II) oxide, which combines with haemoglobin about 200 times more strongly than oxygen does."),
    ("Water Air and Environmental Chemistry", "Easy", "Which of the following wastes is biodegradable?",
     "polythene bags", "glass bottles", "vegetable peelings", "aluminium cans", "C",
     "Plant material is broken down by bacteria and fungi; plastics, glass and metals persist in the environment."),
    ("Water Air and Environmental Chemistry", "Medium", "A river water sample has a high biochemical oxygen demand (BOD). This indicates that the water",
     "is very pure", "contains a large amount of organic waste", "has a high concentration of dissolved oxygen", "is too cold for fish", "B",
     "Bacteria decomposing organic pollution consume dissolved oxygen; the more waste, the more oxygen is demanded."),
    ("Water Air and Environmental Chemistry", "Medium", "Which of the following observations shows that water is a compound and not a mixture?",
     "it boils at 100 °C", "electrolysis gives hydrogen and oxygen in a fixed ratio of 2 : 1 by volume", "it dissolves many substances", "it can exist as ice, water and steam", "B",
     "A compound has a fixed composition and can be split into its elements only by chemical means such as electrolysis."),
    ("Water Air and Environmental Chemistry", "Easy", "A liquid turns white anhydrous copper(II) tetraoxosulphate(VI) blue. This shows that the liquid",
     "is pure water", "contains water", "is an acid", "is hard water", "B",
     "The test detects the presence of water (forming blue CuSO₄·5H₂O) but says nothing about purity; purity is checked by boiling point."),
    ("Water Air and Environmental Chemistry", "Easy", "Which of the following is NOT a normal component of clean, dry air?",
     "argon", "carbon(IV) oxide", "nitrogen", "sulphur(IV) oxide", "D",
     "Sulphur(IV) oxide is a pollutant from burning sulphur-containing fuels; argon (0.9%), CO₂ (0.04%) and nitrogen (78%) are natural constituents."),
    ("Water Air and Environmental Chemistry", "Easy", "Argon is used to fill electric light bulbs because it",
     "glows brightly when heated", "is inert and does not react with the hot filament", "conducts electricity well", "is the cheapest gas available", "B",
     "In air the tungsten filament would oxidise and burn out; the unreactive argon protects it."),
    ("Water Air and Environmental Chemistry", "Medium", "Soap forms a scum with hard water because the calcium and magnesium ions",
     "react with soap to form insoluble salts", "make the soap dissolve too quickly", "neutralise the alkali in the soap", "increase the surface tension of the water", "A",
     "Calcium and magnesium stearates are insoluble; soap is wasted as scum until all these ions are removed."),
    # ---------------- Industrial Chemistry ----------------
    ("Industrial Chemistry", "Medium", "In the Contact process, sulphur(VI) oxide is absorbed in concentrated tetraoxosulphate(VI) acid rather than in water because",
     "sulphur(VI) oxide is insoluble in water", "the reaction with water is too violent and produces a mist of acid droplets", "water decomposes sulphur(VI) oxide", "concentrated acid is cheaper than water", "B",
     "SO₃ dissolved in 98% H₂SO₄ gives oleum, which is then carefully diluted; direct reaction with water releases too much heat."),
    ("Industrial Chemistry", "Easy", "The main raw materials for the manufacture of cement are",
     "sand and sodium trioxocarbonate(IV)", "limestone and clay", "bauxite and cryolite", "gypsum and sand", "B",
     "Limestone (CaCO₃) and clay (aluminosilicates) are heated in a rotary kiln to form clinker, to which a little gypsum is added."),
    ("Industrial Chemistry", "Easy", "In the fractional distillation of petroleum, the fraction collected at the top of the column is",
     "bitumen", "kerosene", "lubricating oil", "refinery gas", "D",
     "The lowest-boiling fraction (methane to butane) rises to the coolest part at the top; bitumen remains at the bottom."),
    ("Industrial Chemistry", "Medium", "Long-chain hydrocarbon fractions from crude oil are cracked mainly because",
     "they are too impure to burn", "the demand for petrol and short-chain alkenes exceeds their yield from distillation", "long chains cannot be stored safely", "cracking removes sulphur from them", "B",
     "Cracking breaks large, less useful molecules into smaller alkanes (petrol) and alkenes (raw materials for plastics)."),
    ("Industrial Chemistry", "Medium", "A petrol that causes little knocking in an engine has a",
     "low octane number", "high octane number", "high boiling point", "high sulphur content", "B",
     "The octane number measures resistance to knocking; branched-chain alkanes such as 2,2,4-trimethylpentane (octane number 100) burn smoothly."),
    ("Industrial Chemistry", "Easy", "Most of the ammonia produced by the Haber process is used to make",
     "fertilisers", "plastics", "soap", "glass", "A",
     "Ammonia is converted to ammonium salts and urea, the main nitrogen fertilisers."),
    ("Industrial Chemistry", "Medium", "Ordinary glass is made by heating sand (silicon(IV) oxide) with",
     "sodium trioxocarbonate(IV) and limestone", "clay and gypsum", "sodium chloride and coke", "bauxite and cryolite", "A",
     "Na₂CO₃ and CaCO₃ react with SiO₂ to form a mixture of sodium and calcium silicates, which cools to soda-lime glass."),
    ("Industrial Chemistry", "Medium", "An advantage of soapless detergents over soap is that they",
     "are made from animal fats", "lather well even in hard water", "are completely biodegradable", "do not dissolve in water", "B",
     "The calcium and magnesium salts of detergents are soluble, so no scum forms in hard water."),
    ("Industrial Chemistry", "Easy", "A farmer wants to add nitrogen to his soil. Which of the following fertilisers should he use?",
     "calcium trioxocarbonate(IV)", "calcium tetraoxosulphate(VI)", "ammonium tetraoxosulphate(VI)", "potassium chloride", "C",
     "(NH₄)₂SO₄ supplies nitrogen as ammonium ions; the others provide calcium or potassium."),
    ("Industrial Chemistry", "Medium", "Which of the following is a thermosetting plastic?",
     "polythene", "polyvinyl chloride (PVC)", "Bakelite", "polystyrene", "C",
     "Bakelite has cross-linked chains and cannot be softened again by heating; the others are thermoplastics that soften on heating."),
    ("Industrial Chemistry", "Medium", "Ethene, the starting material for polythene and many other petrochemicals, is obtained industrially mainly by",
     "fermentation of sugar", "cracking of petroleum fractions", "fractional distillation of air", "electrolysis of brine", "B",
     "Cracking naphtha or ethane at high temperature breaks the chains and produces ethene and other alkenes."),
    ("Industrial Chemistry", "Medium", "In the Solvay process for making sodium trioxocarbonate(IV), the ammonia used is",
     "lost as a waste gas", "recovered by heating ammonium chloride with calcium hydroxide and re-used", "converted to fertiliser", "burnt to provide heat for the process", "B",
     "Ca(OH)₂ + 2NH₄Cl → CaCl₂ + 2NH₃ + 2H₂O; recycling the ammonia keeps the process economical."),
    # ---------------- Chemistry of Biomolecules ----------------
    ("Chemistry of Biomolecules", "Easy", "When starch is boiled with dilute hydrochloric acid for some time, the final product is",
     "sucrose", "glucose", "ethanol", "maltose only", "B",
     "Acid hydrolysis breaks starch through dextrins and maltose down to its monomer, glucose."),
    ("Chemistry of Biomolecules", "Medium", "Sucrose gives no precipitate with Benedict's solution, but after it is boiled with dilute acid a brick-red precipitate forms. This is because",
     "the acid is a reducing agent", "hydrolysis produces glucose and fructose, which are reducing sugars", "sucrose is oxidised by the acid", "the heat alone reduces Benedict's solution", "B",
     "Sucrose is a non-reducing disaccharide; acid splits it into two reducing monosaccharides."),
    ("Chemistry of Biomolecules", "Medium", "When a protein is boiled with dilute hydrochloric acid for several hours, it breaks down into",
     "fatty acids and glycerol", "amino acids", "glucose units", "nucleotides", "B",
     "Proteins are condensation polymers of amino acids joined by peptide bonds, which acid hydrolysis breaks."),
    ("Chemistry of Biomolecules", "Easy", "Fats and oils are esters formed from fatty acids and",
     "ethanol", "propane-1,2,3-triol (glycerol)", "methanol", "glucose", "B",
     "Each glycerol molecule has three –OH groups that combine with three fatty acid molecules to form a triglyceride."),
    ("Chemistry of Biomolecules", "Medium", "A vegetable oil decolourises bromine water but palm kernel fat does not. This shows that the vegetable oil",
     "contains more unsaturated fatty acid chains", "is a saturated fat", "contains glycerol", "has a higher melting point", "A",
     "C=C double bonds in the unsaturated chains add bromine; saturated fats have no double bonds."),
    ("Chemistry of Biomolecules", "Easy", "The white of an egg becomes solid and opaque when boiled because the heat",
     "hydrolyses the protein to amino acids", "denatures and coagulates the protein", "converts the protein to fat", "removes all the water from it", "B",
     "Heat destroys the folded structure of albumin so the chains tangle and precipitate; the process is irreversible."),
    ("Chemistry of Biomolecules", "Medium", "During fermentation with yeast, raising the temperature to 70 °C stops the production of ethanol because",
     "the sugar evaporates", "the enzymes in the yeast are denatured", "ethanol reacts with the yeast", "carbon(IV) oxide is no longer soluble", "B",
     "Zymase and other enzymes are proteins; above about 60 °C they lose their shape and stop working."),
    ("Chemistry of Biomolecules", "Easy", "Glucose and fructose both have the molecular formula C₆H₁₂O₆ but different structures. They are described as",
     "isotopes", "isomers", "allotropes", "polymers", "B",
     "Compounds with the same molecular formula but different structural arrangement are isomers."),
    ("Chemistry of Biomolecules", "Medium", "Humans cannot digest cellulose although it is made of glucose units, because they",
     "lack the enzyme that hydrolyses its β-linkages", "have no acid in the stomach", "cannot absorb glucose", "have too much amylase", "A",
     "Amylase breaks the α-links of starch but not the β-links of cellulose; ruminants rely on bacteria that produce cellulase."),
    ("Chemistry of Biomolecules", "Medium", "Liquid vegetable oils are converted into solid margarine by",
     "hydrolysis with sodium hydroxide", "hydrogenation using a nickel catalyst", "oxidation in air", "esterification with glycerol", "B",
     "Adding hydrogen across the C=C bonds saturates the chains and raises the melting point."),
    ("Chemistry of Biomolecules", "Easy", "Which of the following is a disaccharide?",
     "glucose", "fructose", "maltose", "starch", "C",
     "Maltose consists of two glucose units joined together; glucose and fructose are monosaccharides and starch a polysaccharide."),
    ("Chemistry of Biomolecules", "Medium", "Amino acids are amphoteric because each molecule contains",
     "two acidic groups", "both a basic –NH₂ group and an acidic –COOH group", "a hydroxyl group only", "a benzene ring", "B",
     "The amino group accepts protons and the carboxyl group donates them, so amino acids react with both acids and bases."),
]

# Option sets rewritten where the correct option was conspicuously longer than the distractors
# (same letter positions as in the rows above). Key = unique fragment of the stem.
FIX = {
    "Across period 3 from sodium to chlorine": ("the number of electron shells increases from left to right", "the nuclear charge increases while electrons enter the same shell", "electrons are progressively removed from the outer shell", "the atoms lose their outer shells as they become non-metals"),
    "Going down Group 1 from lithium to caesium": ("the atoms become smaller and hold water molecules more tightly", "the outer electron is further from the nucleus and more easily lost", "the metals become harder and denser down the group", "the number of electrons in the outer shell increases down the group"),
    "The bond between the water molecule and the added proton": ("an ionic bond", "a dative covalent bond", "a hydrogen bond", "a metallic bond"),
    "Ice floats on water because": ("air bubbles trapped during freezing make the ice lighter than water", "hydrogen bonds hold the molecules in an open lattice of lower density", "the covalent O–H bonds become longer and weaker when water freezes", "the molecules in ice are lighter than the molecules in liquid water"),
    "Graphite conducts electricity but diamond does not": ("the carbon atoms are ionised and the ions carry the current", "each carbon atom bonds to three others, leaving one delocalised electron", "the carbon atoms are packed more closely together than in diamond", "the carbon atoms are held together by metallic bonds instead of covalent bonds"),
    "Iodine crystals have a low melting point": ("the covalent bond between the two iodine atoms is very weak", "only weak van der Waals forces act between the I₂ molecules", "iodine is a metal with a weak metallic bond", "iodine molecules are ionic and the ions separate on heating"),
    "The hydrochloric acid gave the lower pH because it": ("is more concentrated than the ethanoic acid solution", "is completely ionised in water while ethanoic acid is only partly ionised", "contains chlorine, a very reactive element, while ethanoic acid does not", "has a higher relative molecular mass than ethanoic acid"),
    "Which of the following is a double decomposition reaction?": ("AgNO₃(aq) + NaCl(aq) → AgCl(s) + NaNO₃(aq)", "2H₂O₂(aq) → 2H₂O(l) + O₂(g)", "Fe(s) + S(s) → FeS(s)", "Zn(s) + 2HCl(aq) → ZnCl₂(aq) + H₂(g)"),
    "The salt bridge in an electrochemical cell": ("supplies electrons to the cathode when the cell is working", "allows ions to move between the half-cells and keeps them electrically neutral", "prevents any ions from moving between the two solutions", "acts as the negative electrode at which oxidation takes place"),
    "Raising the temperature increases the rate of a reaction mainly because": ("the activation energy of the reaction is lowered by the heat", "more of the molecules have energy equal to or greater than the activation energy", "the molecules become larger and so collide with one another more often", "the reaction becomes more exothermic and releases heat faster"),
    "Changing the pressure has no effect on the position of the equilibrium": ("the reaction is exothermic in the forward direction", "there are equal numbers of moles of gas on both sides", "water vapour does not behave as a gas at equilibrium", "carbon(II) oxide is insoluble in water"),
    "adding a reagent that removes Fe³⁺ ions makes the red colour fade": ("the equilibrium shifts to the right to form more FeSCN²⁺", "the equilibrium shifts to the left to replace the Fe³⁺", "the FeSCN²⁺ ion is oxidised by the added reagent", "the SCN⁻ ions are precipitated by the added reagent"),
    "The bleaching is caused by": ("chlorine gas dissolving the dye out of the paper", "oxochlorate(I) acid, formed with the water, which oxidises the dye", "hydrogen chloride, formed with the water, which reduces the dye", "the heat released when chlorine reacts with the water"),
    "cannot be used to dry ammonia gas because": ("ammonia is insoluble in the concentrated acid", "the acid reacts with ammonia to form ammonium tetraoxosulphate(VI)", "the acid is too dilute to absorb the water vapour in the gas", "ammonia is much lighter than the acid and floats above it"),
    "The cryolite is used to": ("act as the reducing agent for the aluminium oxide", "lower the melting point of the aluminium oxide", "remove the iron impurities from the aluminium oxide", "supply extra aluminium ions to the electrolyte"),
    "A scratched tin-plated iron can rusts faster": ("tin is more reactive than iron and dissolves away from the scratch", "tin is less reactive than iron, so the iron corrodes at the scratch", "zinc forms a barrier that prevents water from reaching the scratch", "tin reacts with the air to form an acid that attacks the iron"),
    "Nitrogen gas is very unreactive at room temperature": ("it is a noble gas with a full outer shell of electrons", "the triple bond between its atoms is very strong", "its molecules are very large and move very slowly", "it is less dense than air and escapes before reacting"),
    "the solution turns from orange to green because": ("ethanol is reduced to ethane while the dichromate(VI) is oxidised", "ethanol is oxidised while dichromate(VI) is reduced to chromium(III)", "the orange dichromate(VI) dissolves in the ethanol to give a green solution", "ethanol is dehydrated to ethene, which reacts with the dichromate(VI)"),
    "the products are an alcohol and the sodium salt of the acid": ("esterification", "saponification", "polymerisation", "dehydration"),
    "Benzene undergoes substitution rather than addition": ("it has no hydrogen atoms that can be added to or replaced", "its delocalised electrons give the ring a stability that addition would destroy", "it is a saturated hydrocarbon with no double bonds at all", "its carbon atoms are joined by alternating double and single bonds that never move"),
    "alum [Al₂(SO₄)₃] is added in order to": ("kill the bacteria and other germs in the water", "coagulate suspended particles so that they settle", "remove the hardness caused by dissolved calcium salts", "add fluoride to the water to protect the teeth"),
    "A petrol generator running in a closed room": ("carbon(IV) oxide, which is heavier than air and collects near the floor", "carbon(II) oxide, which binds to haemoglobin and stops oxygen transport", "nitrogen, which dilutes the oxygen in the room until it cannot be breathed", "water vapour, which saturates the air and causes suffocation"),
    "shows that water is a compound and not a mixture": ("it boils at 100 °C and freezes at 0 °C at atmospheric pressure", "electrolysis gives hydrogen and oxygen in a fixed ratio of 2 : 1 by volume", "it dissolves many substances and is called the universal solvent", "it can exist as ice, liquid water and steam at different temperatures"),
    "Argon is used to fill electric light bulbs": ("glows brightly when the filament heats it", "is inert and does not react with the hot filament", "conducts electricity well between the terminals", "is the cheapest gas available in large quantities"),
    "sulphur(VI) oxide is absorbed in concentrated tetraoxosulphate(VI) acid rather than in water": ("sulphur(VI) oxide is insoluble in water but dissolves in the acid", "the reaction with water is so violent that it produces a mist of acid droplets", "water decomposes sulphur(VI) oxide back to sulphur(IV) oxide and oxygen", "concentrated acid is cheaper and more readily available than pure water"),
    "Long-chain hydrocarbon fractions from crude oil are cracked": ("they are too impure to burn cleanly in modern engines", "the demand for petrol and short-chain alkenes exceeds the yield from distillation", "long-chain molecules cannot be stored safely in tanks for long periods", "cracking removes the sulphur compounds that cause acid rain"),
    "Ordinary glass is made by heating sand": ("sodium trioxocarbonate(IV) and limestone", "clay and calcium tetraoxosulphate(VI)", "sodium chloride and powdered coke", "bauxite and molten cryolite"),
    "In the Solvay process for making sodium trioxocarbonate(IV), the ammonia used is": ("lost as a waste gas through the top of the tower", "recovered by heating ammonium chloride with calcium hydroxide and re-used", "converted to ammonium tetraoxosulphate(VI) fertiliser and sold", "burnt in air to provide the heat needed for the process"),
    "Sucrose gives no precipitate with Benedict's solution": ("the acid itself is a reducing agent that reacts with the copper(II) ions", "hydrolysis produces glucose and fructose, which are reducing sugars", "sucrose is oxidised by the acid to a sugar that reduces copper(II)", "the heat alone reduces the copper(II) ions in Benedict's solution"),
    "A vegetable oil decolourises bromine water but palm kernel fat does not": ("contains more unsaturated fatty acid chains", "is a saturated fat with no double bonds", "contains glycerol as well as fatty acids", "has a higher melting point than the palm kernel fat"),
    "Humans cannot digest cellulose": ("lack the enzyme that hydrolyses its β-linkages", "have no acid in the stomach to break it down", "cannot absorb the glucose it would produce", "have too much amylase in their saliva"),
    "Amino acids are amphoteric because each molecule contains": ("two acidic carboxyl groups on the same carbon", "both a basic –NH₂ group and an acidic –COOH group", "a hydroxyl group attached to a benzene ring", "a benzene ring with a methyl side chain"),
}


def build():
    build_batch(
        S, "batch_014_chemistry_round3.json", "batch_014_chemistry_round3",
        "Chemistry round 3: four data passages (titration, rate data, electrode potentials, solubility) and applied/calculation items across the JAMB syllabus.",
        PASSAGES, PQ, Q, FIX,
    )


if __name__ == "__main__":
    build()
